<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="urn:schemas-iswift:struct-dir" xmlns="urn:schemas-iswift:struct-dir" xmlns:a="urn:schemas-iswift:struct-dir" xmlns:mstns="urn:schemas-iswift:struct-dir" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="dir" type="dirType">
  </xs:element>

  <xs:complexType name="dirType">
    <xs:sequence>
      <xs:element name="title" type="textType" minOccurs="0">
      </xs:element>
      <xs:element name="subtitle" type="textType" minOccurs="0">
      </xs:element>
      <xs:element name="title0" type="textType" minOccurs="0">
      </xs:element>
      <xs:element name="title1" type="textType" minOccurs="0">
      </xs:element>
      <xs:element name="forms" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element maxOccurs="unbounded" name="form">
              <xs:complexType>
                <xs:sequence>
                  <xs:element minOccurs="0" name="text" type="textType" >
                  </xs:element>
                  <xs:element name="fields">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element maxOccurs="unbounded" name="field">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="text">
                                <xs:complexType>
                                  <xs:simpleContent>
                                    <xs:extension base="xs:string">
                                      <xs:attribute name="v" type="xs:string" use="required" />
                                      <xs:attribute name="e" type="xs:string" use="required" />
                                    </xs:extension>
                                  </xs:simpleContent>
                                </xs:complexType>
                              </xs:element>
                              <xs:element minOccurs="0" name="viewInfo" type="viewInfoType">
                              </xs:element>
                              <xs:element name="jsScript" minOccurs="0">
                                <xs:complexType>
                                  <xs:sequence>
                                    <xs:element name="text" type="xs:string" />
                                  </xs:sequence>
                                </xs:complexType>
                              </xs:element>
                              <xs:element name="appScript" minOccurs="0">
                                <xs:complexType>
                                  <xs:sequence>
                                    <xs:element name="text" type="xs:string" />
                                  </xs:sequence>
                                </xs:complexType>
                              </xs:element>
                            </xs:sequence>
                            <xs:attribute name="name" type="xs:string" use="required" />
                            <xs:attribute name="fieldType" type="fieldType" use="optional" />
                            <xs:attribute name="dataType" type="dataType" use="optional" />
                            <xs:attribute name="viewType" type="formViewType" use="optional" />
                            <xs:attribute name="format" type="formatType" use="optional" />
                            <xs:attribute name="blank" type="xs:string" use="optional" />
                            <xs:attribute name="label" type="xs:string" use="optional" />
                            <xs:attribute name="field" type="xs:string" use="optional" />
                            <xs:attribute name="rows" type="xs:unsignedByte" use="optional" />
                            <xs:attribute name="rowHeight" type="xs:unsignedByte" use="optional" />
                            <xs:attribute name="maxLength" type="xs:string" use="optional" />
                            <xs:attribute name="cellCss" type="xs:string" use="optional" />
                            <xs:attribute name="clientDefault" type="xs:boolean" use="optional" />
                            <xs:attribute name="valueDefault" type="xs:string" use="optional" />
                            <xs:attribute name="nextRow" type="xs:boolean" use="optional" />
                            <xs:attribute name="readOnly" type="xs:boolean" use="optional" />
                            <xs:attribute name="disabled" type="xs:boolean" use="optional" />
                            <xs:attribute name="hidden" type="xs:boolean" use="optional" />
                            <xs:attribute name="inactivate" type="xs:boolean" use="optional" />
                            <xs:attribute name="invisible" type="xs:boolean" use="optional" />
                            <xs:attribute name="allowBlank" type="xs:boolean" use="optional" />
                            <xs:attribute name="notAuth" type="xs:boolean" use="optional" />
                            <xs:attribute name="copy" type="xs:boolean" use="optional" />
                            <xs:attribute name="lookupRef" type="xs:boolean" use="optional" />
                            <xs:attribute name="aliasName" type="xs:string" use="optional" />
                            <xs:attribute name="align" type="alignType" use="optional" />
                            <xs:attribute name="importable" type="xs:int" use="optional" />
                            <xs:attribute name="importWidth" type="xs:unsignedShort" use="optional" />
                            <xs:attribute name="checkCode" type="xs:string" use="optional" />
                            <xs:attribute name="operation" type="xs:string" use="optional" />
                            <xs:attribute name="join" type="xs:string" use="optional" />
                            <xs:attribute name="readOnlyCondition" type="xs:string" use="optional" />
                            <xs:attribute name="allowBlankCondition" type="xs:string" use="optional" />
                            <xs:attribute name="setype" type="xs:string" use="optional" />
                            <xs:attribute name="note" type="xs:string" use="optional" />
                            <xs:attribute name="note2" type="xs:string" use="optional" />
                            <xs:attribute name="note3" type="xs:string" use="optional" />
                          </xs:complexType>
                        </xs:element>
                      </xs:sequence>
                    </xs:complexType>
                  </xs:element>
                </xs:sequence>
                <xs:attribute name="tabPageIndex" type="xs:string" use="optional" />
                <xs:attribute name="gravity" type="gravityType" use="optional" />
                <xs:attribute name="columns" type="xs:string" use="optional" />
                <xs:attribute name="height" type="xs:unsignedShort" use="optional" />
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="grids" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element maxOccurs="unbounded" name="grid">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="fields">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element maxOccurs="unbounded" name="field">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="text" type="textType">
                              </xs:element>
                              <xs:element name="text2" type="textType" minOccurs="0">
                              </xs:element>
                              <xs:element name="text3" type="textType" minOccurs="0">
                              </xs:element>
                              <xs:element minOccurs="0" name="viewInfo" type="viewInfoType">
                              </xs:element>
                              <xs:element name="jsScript" minOccurs="0">
                                <xs:complexType>
                                  <xs:sequence>
                                    <xs:element name="text" type="xs:string" />
                                  </xs:sequence>
                                </xs:complexType>
                              </xs:element>
                              <xs:element name="appScript" minOccurs="0">
                                <xs:complexType>
                                  <xs:sequence>
                                    <xs:element name="text" type="xs:string" />
                                  </xs:sequence>
                                </xs:complexType>
                              </xs:element>
                            </xs:sequence>
                            <xs:attribute name="name" type="xs:string" use="optional" />
                            <xs:attribute name="foreignKey" type="xs:string" use="optional" />
                            <xs:attribute name="fieldType" type="fieldType" use="optional" />
                            <xs:attribute name="dataType" type="dataType" use="optional" />
                            <xs:attribute name="viewType" type="gridViewType" use="optional" />
                            <xs:attribute name="format" type="formatType" use="optional" />
                            <xs:attribute name="width" type="xs:unsignedShort" use="optional" />
                            <xs:attribute name="allowFilter" type="xs:boolean" use="optional" />
                            <xs:attribute name="allowOrder" type="xs:boolean" use="optional" />
                            <xs:attribute name="readOnly" type="xs:boolean" use="optional" />
                            <xs:attribute name="disabled" type="xs:boolean" use="optional" />
                            <xs:attribute name="hidden" type="xs:boolean" use="optional" />
                            <xs:attribute name="allowBlank" type="xs:boolean" use="optional" />
                            <xs:attribute name="notAuth" type="xs:boolean" use="optional" />
                            <xs:attribute name="inactivate" type="xs:boolean" use="optional" />
                            <xs:attribute name="copy" type="xs:boolean" use="optional" />
                            <xs:attribute name="filterType" type="xs:string" use="optional" />
                            <xs:attribute name="maxLength" type="xs:string" use="optional" />
                            <xs:attribute name="cellCss" type="xs:string" use="optional" />
                            <xs:attribute name="clientDefault" type="xs:boolean" use="optional" />
                            <xs:attribute name="valueDefault" type="xs:string" use="optional" />
                            <xs:attribute name="aliasName" type="xs:string" use="optional" />
                            <xs:attribute name="align" type="alignType" use="optional" />
                            <xs:attribute name="importable" type="xs:int" use="optional" />
                            <xs:attribute name="importWidth" type="xs:unsignedShort" use="optional" />
                            <xs:attribute name="foreignField" type="xs:string" use="optional" />
                            <xs:attribute name="link" type="xs:string" use="optional" />
                            <xs:attribute name="operation" type="xs:string" use="optional" />
                            <xs:attribute name="join" type="xs:string" use="optional" />
                            <xs:attribute name="readOnlyCondition" type="xs:string" use="optional" />
                            <xs:attribute name="allowBlankCondition" type="xs:string" use="optional" />
                            <xs:attribute name="lastSymbol" type="xs:string" use="optional" />
                            <xs:attribute name="firstSymbol" type="xs:string" use="optional" />
                            <xs:attribute name="note" type="xs:string" use="optional" />
                            <xs:attribute name="note2" type="xs:string" use="optional" />
                            <xs:attribute name="note3" type="xs:string" use="optional" />
                            <xs:attribute name="rowspan" type="xs:unsignedByte" use="optional" />
                            <xs:attribute name="rowspan2" type="xs:unsignedByte" use="optional" />
                            <xs:attribute name="rowspan3" type="xs:unsignedByte" use="optional" />
                            <xs:attribute name="columnspan" type="xs:unsignedByte" use="optional" />
                            <xs:attribute name="columnspan2" type="xs:unsignedByte" use="optional" />
                            <xs:attribute name="columnspan3" type="xs:unsignedByte" use="optional" />
                          </xs:complexType>
                        </xs:element>
                      </xs:sequence>
                    </xs:complexType>
                  </xs:element>
                  <xs:element name="buttons" minOccurs="0" type="a:buttonType">
                  </xs:element>
                  <xs:element name="mobileView" minOccurs="0">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="text" type="xs:string" />
                      </xs:sequence>
                    </xs:complexType>
                  </xs:element>
                  <xs:element name="script" minOccurs="0">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="query" minOccurs="0">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="text" type="xs:string" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>

                        <xs:element name="finding" minOccurs="0">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="text" type="xs:string" />
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                      </xs:sequence>
                    </xs:complexType>
                  </xs:element>
                </xs:sequence>
                <xs:attribute name="id" type="xs:string" use="optional" />
                <xs:attribute name="table" type="xs:string" use="optional" />
                <xs:attribute name="order" type="xs:string" use="optional" />
                <xs:attribute name="fieldKey" type="xs:string" use="optional" />
                <xs:attribute name="fieldName" type="xs:string" use="optional" />
                <xs:attribute name="key" type="xs:string" use="optional" />
                <xs:attribute name="allowFilter" type="xs:boolean" use="optional" />
                <xs:attribute name="allowOrder" type="xs:boolean" use="optional" />
                <xs:attribute name="readOnly" type="xs:boolean" use="optional" />
                <xs:attribute name="headerRowCount" type="xs:unsignedByte" use="optional" />
                <xs:attribute name="boldCondition" type="xs:string" use="optional" />
                <xs:attribute name="boldConditionExcel" type="xs:string" use="optional" />
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="buttons" minOccurs="0" type="a:buttonType">
      </xs:element>

      <xs:element name="js" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="text" type="xs:string" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="css" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="text" type="xs:string" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="script" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="request" minOccurs="0" maxOccurs="unbounded">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="text" type="xs:string" />
                </xs:sequence>
                <xs:attribute name="code" type="xs:string" use="optional" />
                <xs:attribute name="transaction" type="xs:boolean" use="optional" />
              </xs:complexType>
            </xs:element>
            <xs:element name="query" minOccurs="0">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="text" type="xs:string" />
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            <xs:element name="processing" minOccurs="0">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="text" type="xs:string" />
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            <xs:element name="declare" minOccurs="0">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="text" type="xs:string" />
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            <xs:element name="loading" minOccurs="0">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="text" type="xs:string" />
                </xs:sequence>
                <xs:attribute name="code" type="xs:string" use="optional" />
              </xs:complexType>
            </xs:element>
            <xs:element name="beforesave" minOccurs="0">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="text" type="xs:string" />
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            <xs:element name="deleting" minOccurs="0">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="text" type="xs:string" />
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            <xs:element name="deleted" minOccurs="0">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="text" type="xs:string" />
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            <xs:element name="updating" minOccurs="0">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="text" type="xs:string" />
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            <xs:element name="updated" minOccurs="0">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="text" type="xs:string" />
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            <xs:element name="inserting" minOccurs="0">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="text" type="xs:string" />
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            <xs:element name="inserted" minOccurs="0">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="text" type="xs:string" />
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            <xs:element name="aftersave" minOccurs="0">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="text" type="xs:string" />
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            <xs:element name="uploaded" minOccurs="0">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="text" type="xs:string" />
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            <xs:element name="importing" minOccurs="0">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="text" type="xs:string" />
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            <xs:element name="imported" minOccurs="0">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="text" type="xs:string" />
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            <xs:element name="error" minOccurs="0">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="text" type="xs:string" />
                </xs:sequence>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>

      <xs:element name="messages" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="message">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="text" type="textType">
                  </xs:element>
                </xs:sequence>
                <xs:attribute name="val" type="xs:string" use="optional" />
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" use="required" />
    <xs:attribute name="table" type="xs:string" use="optional" />
    <xs:attribute name="fieldKey" type="xs:string" use="optional" />
    <xs:attribute name="dirViewType" type="dirViewType" />
    <xs:attribute name="dirObjectType" type="dirObjectType" />
    <xs:attribute name="voucherCode" type="xs:string" use="optional" />
    <xs:attribute name="baseCurrency" type="xs:string" use="optional" />
    <xs:attribute name="selectMultiple" type="selectMultipleType" use="optional" />
    <xs:attribute name="width" type="dirFormWidth" />
    <xs:attribute name="height" type="xs:string" use="optional" />
    <xs:attribute name="transaction" type="xs:boolean" use="optional" />
    <xs:attribute name="tryCatch" type="xs:boolean" use="optional" />
    
  </xs:complexType>

  <xs:complexType name="textType">
    <xs:attribute name="v" type="xs:string" use="required"/>
    <xs:attribute name="e" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="buttonType">
    <xs:sequence>
      <xs:element maxOccurs="unbounded" name="button">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="text" type="textType">
            </xs:element>
            <xs:element minOccurs="0" type="buttonType" name="items">
            </xs:element>
          </xs:sequence>
          <xs:attribute name="id" type="xs:string" use="required" />
          <xs:attribute name="default" type="xs:boolean" use="optional" />
          <xs:attribute name="image" type="xs:string" use="optional" />
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="viewInfoType">
    <xs:sequence minOccurs="0">
      <xs:element name="options">
        <xs:complexType>
          <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="option">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="text" type="textType">
                  </xs:element>
                </xs:sequence>
                <xs:attribute name="val" type="xs:string" use="optional" />
              </xs:complexType>
            </xs:element>
          </xs:sequence>
          <xs:attribute name="query" type="xs:string" use="optional" />
          <xs:attribute name="cache" type="xs:boolean" use="optional" />
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="lookupType" type="lookupType" use="optional" />
    <xs:attribute name="lookupId" type="xs:string" use="optional" />
    <xs:attribute name="lookupRef" type="xs:string" use="optional" />
    <xs:attribute name="lookupKey" type="xs:string" use="optional" />
    <xs:attribute name="lookupCheck" type="xs:string" use="optional" />
    <xs:attribute name="lookupInfo" type="xs:string" use="optional" />
    <xs:attribute name="lookupExactValue" type="xs:string" use="optional" />
    
    <xs:attribute name="importCheck" type="xs:string" use="optional" />
    
    <xs:attribute name="fileGroup" type="xs:string" use="optional" />
    <xs:attribute name="fileFieldId0" type="xs:string" use="optional" />
    <xs:attribute name="maxFileSize" type="xs:string" use="optional" />
    <xs:attribute name="maxFileCount" type="xs:unsignedByte" use="optional" />
    <xs:attribute name="fileExtension" type="xs:string" use="optional" />
    <xs:attribute name="fileParamFields" type="xs:string" use="optional" />
    <xs:attribute name="fileStrJson" type="xs:string" use="optional" />

    <xs:attribute name="checkHours" type="xs:boolean" use="optional" />

    <xs:attribute name="listType" type="lookupType" use="optional" />

    <xs:attribute name="commandJSFunction" type="xs:string" use="optional" />
  </xs:complexType>

  <xs:simpleType name="gravityType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="TopLeft"/>
      <xs:enumeration value="TopRight"/>
      <xs:enumeration value="MiddleLeft"/>
      <xs:enumeration value="MiddleRight"/>
      <xs:enumeration value="BottomLeft"/>
      <xs:enumeration value="BottomRight"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="alignType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Left"/>
      <xs:enumeration value="Right"/>
      <xs:enumeration value="Center"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="dataType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="C"/>
      <xs:enumeration value="N"/>
      <xs:enumeration value="D"/>
      <xs:enumeration value="DT"/>
      <xs:enumeration value="B"/>
      <xs:enumeration value="I"/>
      <xs:enumeration value="E"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="formViewType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Combobox"/>
      <xs:enumeration value="List"/>
      <xs:enumeration value="Lookup"/>
      <xs:enumeration value="Time"/>
      <xs:enumeration value="LongTime"/>
      <xs:enumeration value="Grid"/>
      <xs:enumeration value="File"/>
      <xs:enumeration value="Image"/>
      <xs:enumeration value="Command"/>
      <xs:enumeration value="AutoIncrease"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="gridViewType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Combobox"/>
      <xs:enumeration value="Lookup"/>
      <xs:enumeration value="File"/>
      <xs:enumeration value="Image"/>
      <xs:enumeration value="Time"/>
      <xs:enumeration value="LongTime"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="dirViewType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Grid"/>
      <xs:enumeration value="Dialog"/>
      <xs:enumeration value="Popup"/>
      <xs:enumeration value="Lookup"/>
      <xs:enumeration value=""/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="dirObjectType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="List"/>
      <xs:enumeration value="Report"/>
      <xs:enumeration value="Voucher"/>
      <xs:enumeration value=""/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="dirFormWidth">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Large"/>
      <xs:enumeration value="Medium"/>
      <xs:enumeration value="Small"/>
      <xs:enumeration value=""/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="lookupType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="One"/>
      <xs:enumeration value="Multi"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="selectMultipleType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="List"/>
      <xs:enumeration value="Table"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="fieldType">
    <xs:restriction base="xs:string">
      <xs:enumeration value=""/>
      <xs:enumeration value="PK"/>
      <xs:enumeration value="EX"/>
      <xs:enumeration value="RF"/>
      <xs:enumeration value="Temp"/>
      <xs:enumeration value="EXParam"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="formatType">
    <xs:restriction base="xs:string">
      <xs:enumeration value=""/>
      <xs:enumeration value="U"/>
      <xs:enumeration value="L"/>
      <xs:enumeration value="C"/>
      <xs:enumeration value="Amount"/>
      <xs:enumeration value="FCAmount"/>
      <xs:enumeration value="Rate"/>
      <xs:enumeration value="ExRate"/>
      <xs:enumeration value="Price"/>
      <xs:enumeration value="FCPrice"/>
      <xs:enumeration value="Qty"/>
      <xs:enumeration value="-1"/>
      <xs:enumeration value="0"/>
      <xs:enumeration value="1"/>
      <xs:enumeration value="2"/>
      <xs:enumeration value="3"/>
      <xs:enumeration value="4"/>
      <xs:enumeration value="5"/>
      <xs:enumeration value="6"/>
      <xs:enumeration value="7"/>
      <xs:enumeration value="8"/>
      <xs:enumeration value="9"/>
      <xs:enumeration value="12"/>
      <xs:enumeration value="dd/MM/yyyy"/>
      <xs:enumeration value="mm:ss"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>