<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>

<dir id="dmloainh" table="dmloainh" fieldKey="ma_loai_nh" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục loại nhóm" e="List of customer"></title>
  <title0 v="Thêm mới loại nhóm" e="New customer"></title0>
  <title1 v="Sửa loại nhóm" e="Edit customer"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,240,120"  >
      <fields>
        <field name="ma_loai_nh" disabled="true" format="U" label="1" field="1" allowBlank="false" fieldType="PK" >
          <text v="Mã loại nhóm" e="Code"></text>
        </field>
        <field name="ten_loai_nh" allowBlank="false" label="1" field="-">
          <text v="Tên loại nhóm" e="Name"></text>
        </field>
        <field name="ten_loai_nh2" label="1" field="-">
          <text v="Tên 2" e="Name 2"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>LSMLCdsYVdf+eJUGrS5xj9Rpy0plKSIyJYAq+Y84Nsvl2fzbIUUfyrSQ1e1UDpRCl59x4w+P1/TMjucsu0EEcw9OuqySi+VBLc7AAKcWLnvnayDC0qg5pPcFmxBnbmAZvjvmBgIkz7WR2b7TXFQp916No67sBSR3Kvd/bag+D0wqh/n2vN6QMTsLDUNZpJBqNmeWNhX59s9CqqIeOWI4bXOjO4FdWZ2jnmTIgol7Ja8=</enc>]]>
    </text>
  </js>

  <script>
    <declare>
      <text>
        <![CDATA[<enc>hxQPm/hYhpvPifcenBxj7nfT+X4T8oXvYmZx4Kpwn3fRRVZY+foYIow2vt1OHdzq0lG6PkDpvnlKR1ei3AR28UkawCxswedTww8YMZ/ax/1/BVJZ6K0wvLOosliedaWZAZZQJt+bLBksKe9RWXks/lVXLtqbuORfhQZiuDXNB6z94aRlNTFboEpidGu2ooVP98Jbu7382x2jt4lWFaH5dH+r/Vobfups1xFRCfsxb/RbQMU99D0pRR+tf31RerGe</enc>]]>
      </text>
    </declare>
  </script>

</dir>