<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>

<dir id="options" table="options" fieldKey="name" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Khai báo các tham số tùy chọn" e="Optional Parameters"></title>
  <title0 v="Thêm mới tham số tùy chọn" e="New Parameters"></title0>
  <title1 v="Sửa tham số tùy chọn" e="Edit Parameters"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120,120"  >
      <fields>
        <field name="name" hidden="true" fieldType="PK" label="1" field="1" checkCode="0">
          <text v="" e=""></text>
        </field>
        <field name="inputmask" hidden="true">
          <text v="" e=""></text>
        </field>
        <field name="type"  hidden="true">
          <text v="" e=""></text>
        </field>
        <field name="val" hidden="true">
          <text v="" e=""></text>
        </field>
        <field name="val_mask" fieldType="EX" checkCode="0" hidden="true">
          <text v="" e=""></text>
        </field>
        
        <field name="descript" label="1" field="-" allowBlank="false" disabled="true" >
          <text v="Tên tham số" e="Parameters Name"></text>
        </field>
        
        <field name="val_num" format="2" dataType="N" fieldType="EX" label="1" field="1">
          <text v="Giá trị" e="Value"></text>
        </field>
        <field name="val_cbo" viewType="Combobox" fieldType="EX" label="1" field="2">
          <text v="Giá trị" e="Value"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
        <field name="val_date" fieldType="EX" dataType="D" label="1" field="1" >
          <text v="Giá trị" e="Value"></text>
        </field>
        <field name="val_text" fieldType="EX" label="1" field="-" >
          <text v="Giá trị" e="Value"></text>
        </field>
      </fields>
    </form>
  </forms>

&DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>H36qL08+hSig4YMBeLPlhCTl9KHKE1/IAxFwCz+lk0+GSCoUfT93qsX4UeItw/G01hZ/pKBxwpiV3dZ+4qVueFD+YpzwL1SbUr51ymN7WfMr375hOcXsp3jzA/15HDQBxuw/a9/07eOOyccNNE9aMOEDRgqOYZYdPEisKNCRSsWkiu2G7MFH7T4zoMVuY5QDJgYpwZ3vWu+YwLxTAOiKafb2OMRfZJzR283yu1qjRH9BAMWdprtVJnV6wHLjw2kIvbGJP11fIZ/2TNarMPNbrqqhq25KRbMYFWPvM9uFtgznuGO3ACMWiVwv9J+yYQ46t8Ej2xaSrWlsrYiQNG2FNjnEk6oS/52y0BdWIxO56rrpkdTCxmZpacvmZxE0j1v2SiE23UW4vICsfLEOi8Zw8yciS8lo9LEhuglRmESUakO6h2y3NcTr3cFN4vXCrDPSPoSoDRNmOvm1Ofa6BXzeNSuv2m13hUET+rGw2h3O4I9zsw3a4BomDlY0S0V7SLEv1NFu3xJjok+h7+x5VbPvAipv/TQ3dKDqA3SCW5515lsr4i1u0GrXzhjNv3EQW/ajWxOxHBR+NnfrD6gQsEA8kJJuRvIejBa5Q9kdCH3/zgkXLLUvQYYCvCeqR9okEGheL47bKpfzDCHshSNufjiboEKpJn6FGU894kl0uVeZkkgscvivcechmVm9KWUw/GOLEYV9WPaad+kLQ91nTEdVOGT9gnUGukRDDHjaj7lcDZZ+1BSL/Dj0jGjAmMH94RO+Y8ctw98uLX2nO2bj87Jby42/Ws5JNJ3xwVfxxMczOsODWarLKJza0FSwMvtOFRBng82rty4GH/821KFtd7DdPDjf1kvqKThveFAH2uzWwXMLaaqqpOr6JXTlo+pc7S0o</enc>]]>
    </text>
  </js>

  <script>
    <declare>
      <text>
        <![CDATA[<enc>hxQPm/hYhpvPifcenBxj7nfT+X4T8oXvYmZx4Kpwn3fRRVZY+foYIow2vt1OHdzq0lG6PkDpvnlKR1ei3AR28SzjESCDA2EtG2sfHnni81uOonMnF15VB/l/c/bVAZ/m</enc>]]>
      </text>
    </declare>
  </script>
</dir>