<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>

<dir id="sysgroupinfo" table="sysgroupinfo" fieldKey="group_id" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Khai báo nhóm người sử dụng" e="Group Maintenance"></title>
  <title0 v="Thêm thông tin nhóm người sử dụng" e="New Group's Information"></title0>
  <title1 v="Sửa thông tin nhóm người sử dụng" e="Edit Group's Information"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120,240"  >
      <fields>
        <field name="group_id" label="" field="1" dataType="I" hidden="true" fieldType="PK">
          <text v="" e=""></text>
        </field>
        <field name="groupname" format="U" allowBlank="false" label="1" field="1">
          <text v="Nhóm" e="Group"></text>
        </field>
        <field name="dien_giai" allowBlank="false" label="1" field="2">
          <text v="Tên nhóm" e="Description"></text>
        </field>
        <field name="ds_username" allowBlank="false" viewType="Lookup" label="1" field="-">
          <text v="Ds người sử dụng" e="User List"></text>
          <viewInfo lookupType="Multi" lookupId="sysuserinfo" lookupKey="admin = 0 and status=1" lookupCheck="admin = 0 and status=1" lookupRef="" lookupInfo="sysuserinfo|username|nickname" />
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>pLIXfQfuQux/cD98WEIJX3rntWNC5+xE257rOIqAIZyqdiIIKFersVCx7DmYxYgYIi+h7iccoix6uOGjF3sOst0T66vc7U0CUCcHvvBEC6/g0bGewfxslYAf9isv50xnDHaCee2i3Nj8Z7huAurOiygbxCvfIhEjNycWFYjteLNquiiXTMFAx1WnmpAIo6592HDjfu4mVmtD90NGmN9110GyITkTRiZaw2RSf/vVbVqkqcvx1u9tX12OCNxcgNL0</enc>]]>
    </text>
  </js>

  <script>
    <query>
      <text>
        <![CDATA[<enc>faqOvccPg7wjaceLXx4X1Bb4W9SCSQnefnbx7Wm3WkgOGEi49sW4vFCPo6HXVEH1EXK05Nq615d6xmIsfHqvE6bUWvMTpZ1uMj+ztx90GKzOuP0s+1BMu/JhcttmzbXztFSKWV0qjcrlsFei/nDIvueDIN/GKneoh2DlrwLiSfjvFmsqBF3kJ6KBgFtuNb6EThFVvs6rMMy2IS+J9owemORHLJJuMRQGHq7m19kRyGaniR9l8+JCTl//xBG6d2zh</enc>]]>
      </text>
    </query>

    <loading>
      <text>
        <![CDATA[<enc>GJgBVkOd9xy3In+SUACpODN4Or9eMMtOfNcUkLIneO0KIV8QBGJRqOZG8ql7nLdDPgwHPKuFdomYJnMP1eq7AMeNAwCO66tObP1c04xWbuRQ99c9ApGeD4h2gvDCsH75gzazWsjtREBc8Q8Km3YCLERgPKdkVWAKSwTgqfsoCPc=</enc>]]>
      </text>
    </loading>

    <updating>
      <text>
        <![CDATA[<enc>oCm5/mq6MD/wspS+Wte7oTrTzaugsenX3WWyXgeFab4jYauI7sT0g4Vdn73E6IvPd6Qa8qpQL/nnNkEBXrOpENgPr0HwSM4U56tCeKYN8qEj9GlKom8yEVcpaMtVviuOtUuF2kdOGf8FunuYeNeSMD3AJICgB6m4w5MVcaPQPXjCobP080QzKdKjhh/GUqiLq2YbJq8lRChrxvjV+PfAyN9rNXQpHdHkeASJoV6EGD6Sj3LjUyiPbuq156aMq3npMPjNugKjtleR/Bl5evX9dw==</enc>]]>
      </text>
    </updating>

    <inserting>
      <text>
        <![CDATA[<enc>R/BVmEqV2LkaSBzJb32hKuzAjHIWsP+KJEXaXOBUB+xZHgAA8cCIE9/wktHldoCj9y7pA/WjIcDd0vh2zSWekE1yoB9671reoSWY+bEmS1+c4lQHFiPueIal6poxSvsgQNbVOuxjoZqWl65sEX9jv9riKDTq9K461TbPGGEI3+sZHXz8aXuoYId4l8pbk84KQMy7rHy+xvSQSzVNARWP6GtIPx1n9sTgfecthxBi3+LaOc/XqIp3if06wS5jdT4JxwWUDCNxALccAzkQBNqqFdr3Ueywn+P5Y3UiRrcoteudb6OzFmjc5wq6vlQ2eb7nnbkAlBWf7+C+EDrfhDfpLffGDRmd1uhbAUd7v/ipE8A=</enc>]]>
      </text>
    </inserting>

    <inserted>
      <text>
        <![CDATA[<enc>GJgBVkOd9xy3In+SUACpOOhZZSA3lGzDhwhJgBPbaLxqai0aWLtb6airTZHQjzhKhYWXpz675ihX4ZCVHuruiA==</enc>]]>
      </text>
    </inserted>

  </script>
  
  <messages>
    <message val="codeExistsNewMsg">
      <text v="Nhóm đã tồn tại trong danh mục nhóm hoặc người sử dụng." e="Group is exists" />
    </message>
    <message val="codeExistsEditMsg">
      <text v="Nhóm đã tồn tại trong danh mục nhóm hoặc người sử dụng." e="Group is exists" />
    </message>
  </messages>

</dir>