<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>

<dir id="sysunit" table="sysunit" fieldKey="unit_id" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir" width="Large">
  <title v="Danh mục đơn vị cơ sở" e="List of unit"></title>
  <title0 v="Mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>
  
  <forms>
    <form gravity="TopLeft" columns="160,120,180,300">
      <fields>
        <field name="unit_id" hidden="true" fieldType="PK" label="1" field="1">
          <text v="" e=""></text>
        </field>
        <field name="ma_unit" fieldType="PK" format="U" label="1" field="1" allowBlank="false" disabled="true">
          <text v="Mã đơn vị" e="Unit Code"></text>
        </field>
        <field name="ten_unit" allowBlank="false" label="1" field="3">
          <text v="Tên đơn vị" e="Unit Name"></text>
        </field>
        <field name="ten_unit2" label="1" field="3">
          <text v="Tên khác" e="Tên khác"></text>
        </field>
        <field name="ma_so_thue" label="1" field="1">
          <text v="Mã số thuế" e="Mã số thuế"></text>
        </field>
        <field name="ngay_ks" dataType="D" label="1" field="1">
          <text v="Ngày khóa sổ" e="Lock Date"></text>
        </field>
        <field name="entity_line11" label="1" field="2">
          <text v="Cấp tên/tên khác dòng 1" e="Cấp tên/tên khác dòng 1"></text>
        </field>
        <field name="entity_line12" label="0" field="1" nextRow="false">
          <text v="" e=""></text>
        </field>
        <field name="entity_line21" label="1" field="2">
          <text v="Cấp tên/tên khác dòng 2" e="Cấp tên/tên khác dòng 2"></text>
        </field>
        <field name="entity_line22" label="0" field="1" nextRow="false">
          <text v="" e=""></text>
        </field>
        <field name="entity_line31" label="1" field="2">
          <text v="Cấp tên/tên khác dòng 3" e="Cấp tên/tên khác dòng 3"></text>
        </field>
        <field name="entity_line32" label="0" field="1" nextRow="false">
          <text v="" e=""></text>
        </field>
        <field name="entity_line41" label="1" field="2">
          <text v="Cấp tên/tên khác dòng 4" e="Cấp tên/tên khác dòng 4"></text>
        </field>
        <field name="entity_line42" label="0" field="1" nextRow="false">
          <text v="" e=""></text>
        </field>
        <field name="entity_line51" label="1" field="2">
          <text v="Cấp tên/tên khác dòng 5" e="Cấp tên/tên khác dòng 5"></text>
        </field>
        <field name="entity_line52" label="0" field="1" nextRow="false">
          <text v="" e=""></text>
        </field>
        
        <field name="status" viewType="Combobox" hidden="true" inactivate="true" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

&DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>++hMXVcxRkZ9iRZMzG7zsC1ws+Q7g7U0SkmNqZLWhP3fjnz/YHFKpjz4MkVu6l+elLO4m4uuEjg5HQhj91Cozg6LXVdGPmelU32VIkrUtjeIvUuhn8uYNlx2g2cD47Z/5lT6IBSZl2P0FQHw5/YvbwK790WlyzqaaA415PKojWIHaX9mSBz/njiRCn624VCy8bBhg01Z52aCWBBMamT/gg==</enc>]]>
    </text>
  </js>

  <script>
    <declare>
      <text>
        <![CDATA[<enc>hxQPm/hYhpvPifcenBxj7nfT+X4T8oXvYmZx4Kpwn3fRRVZY+foYIow2vt1OHdzqoOzuM/IRGwBzFOXcMEXimaTE5pGG9NJdD2fVmhwFRss=</enc>]]>
      </text>
    </declare>
  </script>
</dir>