<?xml version="1.0" encoding="utf-8"?>

<dir id="dmbaohanh" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục bảo hành" e="Warranty of List"></title>
  <grids>
    <grid table="dmbaohanh" fieldKey="ma_baohanh" fieldName="ten_baohanh" order="ma_baohanh" allowFilter="true" allowOrder="true" key="" >
      <fields join="">
        <field name="ma_baohanh" fieldType="PK" width="100" filterType="Code" >
          <text v="Mã bảo hành" e="Warranty code"></text>
        </field>
        <field name="ten_baohanh" width="250">
          <text v="Tên bảo hành" e="Warranty name"></text>
        </field>
		<field name="unit_id" hidden="true" dataType="I" width="120" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="100" fieldType="EX" >
          <text v="Đơn vị" e="Unit"></text>
        </field>
      </fields>
	  <script>
        <query>
          <text> 	
            <![CDATA[<enc>wIIlH9AXqu3T8miUUdN3WpPJ1sF9McKDc4iqTJnw3hq51McneREdN6j8Yr6XtSDIdF/9yM0bWlM3UKZfP70LenfbRP31pW82g0JVaXTkJTYjU/PQHUs7u/utwPXwQrtJWgb/NPTDPcXSWeok/3v31Y3KynFFeQvM+NjUlETLvNEll3GBgzQxCIEjr+ziILpi+57pPANdVJqauar3x0SWQsFzGl/rrkaZ2pt2OWBm25aeVzbWTt/PW1dRyxhhBPPH6pZ6E0Xkbrkp3V1HZSkFdak6/pOKsXZiVRaBYJOf2J29v4QV0sXCbBX8GC/e300FOLMeNn6atFM3ux10mgWXc2l0vtTAoCbxIniUvY26ZbjHTfOWkepBc3SGLuKqpoeYJoL4OeiW/obxK07yN0fh7Q==</enc>]]>
          </text>
        </query>
      </script>
    </grid>
  </grids>
</dir>