<?xml version="1.0" encoding="utf-8"?>

<dir id="dmbp" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục bộ phận" e="Department List"></title>
  <grids>
    <grid table="dmbp" fieldKey="ma_bp" fieldName="ten_bp" order="ma_bp" allowFilter="true" allowOrder="true" key="" >
      <fields join="">
        <field name="ma_bp" fieldType="PK" width="100" filterType="Code" >
          <text v="Mã bộ phận" e="Department code"></text>
        </field>
        <field name="ten_bp" width="250">
          <text v="Tên bộ phận" e="Department name"></text>
        </field>
      </fields>
    </grid>
  </grids>
</dir>