<?xml version="1.0" encoding="utf-8"?>
<dir id="dmbp" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục bộ phận" e="List of Subunit"></title>
  <grids>
    <grid table="dmbp" fieldKey="ma_bp" fieldName="ten_bp" order="ma_bp" allowFilter="true" allowOrder="true" key="" >
      <fields join="">
        <field name="ma_bp" fieldType="PK" width="100" filterType="Code" >
          <text v="Mã bộ phận" e="Subunit Code"></text>
        </field>
        <field name="ten_bp" width="250">
          <text v="Tên bộ phận" e="Subunit Name"></text>
        </field>       
		<field name="ten_bp2" width="250">
          <text v="Tên khác" e="Other Name"></text>
        </field>
      </fields>
	  <script>
		<query>
		  <text>
			<![CDATA[<enc>O0tPJ/zrBYwyy3CWQlA1WMYrCw6m0TiGVJvnTFjyYnXKpOXMeTqse3SR7HRougWfnJe2hu8vRDrNjKpRTED/zkwyS0jaiaJ6yeE3E8NYRbQBA1czIKCGE6T+QY2KyHUQO2rFg7QzAfDUqX8ZGneLqpv0X00KR+L7e6gD9ZCpATDLYbwVmWHl/TPbLNsI1nZ6pE8wNPueeEa5QYN7Tvr14Z7NVIB/HM2EFZe5MRHvv2LIE9dEsBwy2bj4N1YYZaEgsm7Dl8y8ODjOhvSZvloL5lWWbCUuWVvk9EN+arSYaFv497p2EMWgSsEtVYGnq/3SA/e1j+q6jMaBMDQO3/WEb7/el/eRCqFodfvE6Sf3cVo=</enc>]]>
		  </text>
		</query>
	  </script>
    </grid>
  </grids>
</dir>