<?xml version="1.0" encoding="utf-8"?>

<dir id="dmcang" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục cảng" e="Port List"></title>
  <grids>
    <grid table="dmcang" fieldKey="ma_cang" fieldName="ten_cang" order="ma_cang" allowFilter="true" allowOrder="true" key="" >
      <fields join="">
        <field name="ma_cang" fieldType="PK" width="120" filterType="Code" >
          <text v="Mã cảng" e="Port code"></text>
        </field>
        <field name="ten_cang" width="250">
          <text v="Tên cảng" e="Port name"></text>
        </field>
      </fields>
    </grid>
  </grids>
</dir>