<?xml version="1.0" encoding="utf-8"?>

<dir id="dmccnn" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục chứng chỉ" e="List of certificate foreign language"></title>
  <grids>
    <grid table="dmccnn" fieldKey="ma_cc" fieldName="ten_cc" order="ma_cc" allowFilter="true" allowOrder="true" key="" >
      <fields join="">
        <field name="ma_cc" fieldType="PK" width="120" filterType="Code" >
          <text v="Mã chứng chỉ" e="Certificate code"></text>
        </field>
        <field name="ten_cc" width="250">
          <text v="Tên chứng chỉ" e="Certificate name"></text>
        </field>
      </fields>
    </grid>
  </grids>
</dir>