<?xml version="1.0" encoding="utf-8"?>

<dir id="dmchibo" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh sách chi bộ" e="Household List"></title>
  <grids>
    <grid table="dmchibo" fieldKey="ma_chibo" fieldName="ten_chibo" order="ma_chibo" allowFilter="true" allowOrder="true">
      <fields>
		<field name="ma_chibo" width="120" fieldType="PK" filterType="Code">
		  <text v="Mã chi bộ" e="Party Cell Code"></text>
		</field>
		<field name="ten_chibo" width="120">
		  <text v="Tên chi bộ" e="Party Cell Name"></text>
		</field>
		<field name="ma_ttp" width="120">
		  <text v="Mã tỉnh thành" e="Province/City Code"></text>
		</field>
		<field name="ten_ttp" width="200" fieldType="EX">
		  <text v="Tên tỉnh thành" e="Province/City Code"></text>
		</field>
		<field name="ma_phuongxa" width="120">
			<text v="Mã phường/xã" e="Ward/Commune Code"></text>
		</field>
		<field name="ten_phuongxa" width="200" fieldType="EX">
			<text v="Tên phường/xã" e="Ward/Commune Name"></text>
		</field>
		<field name="ma_khupho" width="120">
		  <text v="Mã khu phố" e="Neighborhood Code"></text>
		</field>
		<field name="ten_khupho" width="200" fieldType="EX">
		  <text v="Tên khu phố" e="Neighborhood Name"></text>
		</field>
      </fields>
	<script>
	<query>
	  <text>
		<![CDATA[<enc>oyXuZN6wlYqMCg8x0zL5fH4FqbEduUB2VNbEdCL7E7fooVo5BKxcAT9UU083mbXIZOnrVMCuoQqEodvb8Sy6qILvqL58QNFS4NdcM06Lk3il8ZjTztQA8EuRoP0sy+v3OD+AXtXiqMyrSL2eNWGFgqNheK+VT1Q+ceXZ9YvVGvK5iNr30pvgGx466IMeZzGiS0uuf7dnkScRUVSkM0Oo+k0zMcNrZIUcJgWjU9KSlflhuklE25ThLILOAX3ZIzSqCcLroQ8deGj7MMa1bOeBNLJNQyh7j79x7YN4/BG5MwRljSxWA7T5iVMjqQpDu5ExCg/shy6kFs+rf+zjIv1STQHtZ5i50ITCFcQoRgnHcVs/NRLe7f6UVocJ2HnUi8LjgNEyBqz2fs7iMao0dRXA+otTfbPs89h2VPcdejMbf7bLsvpVg9+rT6fW+ezhThQnhA3/+NUSOZsqS7uFoEtGsOrVklcc/9BfCNRliUtvdAc=</enc>]]>
	  </text>
	</query>
	</script>
    </grid>
  </grids>
</dir>