<?xml version="1.0" encoding="utf-8"?>

<dir id="dmclvt" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Loại sản phẩm" e="Category List"></title>
  <grids>
    <grid table="dmclvt" fieldKey="ma_clvt" fieldName="Title" order="ma_clvt" allowFilter="true" allowOrder="true" key="" >
      <fields>
        <field name="ma_clvt" fieldType="PK" width="100" filterType="Code" >
          <text v="Mã loại sản phẩm" e="Product category code"></text>
        </field>
        <field name="ten_clvt" width="250">
          <text v="Tên loại sản phẩm" e="Product category name"></text>
        </field>
		<field name="status" width="250">
          <text v="Trangj thái" e="Active"></text>
        </field>
      </fields>
    </grid>
  </grids>
</dir>