<?xml version="1.0" encoding="utf-8"?>

<dir id="dmdkgh" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục điều kiện giao hàng" e="Department List"></title>
  <grids>
    <grid table="dmdkgh" fieldKey="ma_dkgh" fieldName="ten_dkgh" order="ma_dkgh" allowFilter="true" allowOrder="true" key="" >
      <fields>
        <field name="ma_dkgh" fieldType="PK" width="100" filterType="Code" >
          <text v="Mã điều kiện" e="Department Code"></text>
        </field>
        <field name="ten_dkgh" width="250">
          <text v="Tên điều kiện" e="Department Name"></text>
        </field>
      </fields>
    </grid>
  </grids>
</dir>