<?xml version="1.0" encoding="utf-8"?>

<dir id="dmdkngay" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục ngày trong tuần" e="Days of the Week List"></title>
  <grids>
    <grid table="dmdkngay" fieldKey="ma_dkngay" fieldName="ten_dkngay" order="ma_dkngay" allowFilter="true" allowOrder="true">
      <fields>
		<field name="ma_dkngay" fieldType="PK" width="120" filterType="Code">
          <text v="Mã thứ" e="Weekday Code"></text>
        </field>
        <field name="ten_dkngay" width="300">
		  <text v="Tên thứ" e="Weekday Name"></text>
        </field>
      </fields>
	<script>
	<query>
	  <text>
		<![CDATA[<enc>VGq7kagZf8on7/jemugEgGktg8roSNOYZQXBVk1kkidNlIpRSkUC+f968GkBqOMAOTHHyRD0r8qnFr8kPWNWA5XZpg1kQ93k9Fm2SHox5rGRHR/fhleQ+kyZ1eKYcoDkfCn0eA3tSyNMuWafDxRkChDB4v51pFCvt4DeeNz/7IkLptU8M89bLuC0+zBfiv3SoAcaFU+YXH+BL/topSQqYurzjNEuBXnAPgVMYbihIWT+zwngCtLDMvyIOHFg/cMukVyLT7w1zxDtdVOSCcUfLkhOU/Upkl0oLeHCpfaaZpA5d7ogMunrizMOeIS12I+oVRB9ZLX0dTKJBpYAOK8Ygv6XsPdP6R9gP3sPQcl4zW1pJa+Bk3+IDnJ8ALjnSF9T</enc>]]>
	  </text>
	</query>
	</script>
    </grid>
  </grids>
</dir>