<?xml version="1.0" encoding="utf-8"?>

<dir id="dmahngtau" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục hãng tàu" e="List of carriers"></title>
  <grids>
    <grid table="dmhangtau" fieldKey="ma_hang" fieldName="ten_hang" order="ma_hang" allowFilter="true" allowOrder="true" key="" >
      <fields join="">
        <field name="ma_hang" fieldType="PK" width="120" filterType="Code" >
          <text v="Mã hãng tàu" e="Carriers code"></text>
        </field>
        <field name="ten_hang" width="250">
          <text v="Tên hãng tàu" e="Carriers name"></text>
        </field>
      </fields>
    </grid>
  </grids>
</dir>