<?xml version="1.0" encoding="utf-8"?>

<dir id="dmhccong" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục hành chính công" e="Public Administration Catalog"></title>
  <grids>
    <grid table="dmhccong" fieldKey="ma_hccong" fieldName="ten_hccong" order="ma_hccong" allowFilter="true" allowOrder="true" key="" >
      <fields join="">
        <field name="ma_hccong" fieldType="PK" width="120" filterType="Code" >
          <text v="Mã hành chính công" e="Public Administration Code"></text>
        </field>
        <field name="ten_hccong" width="250">
          <text v="Tên hành chính công" e="Public Administration Name"></text>
        </field>
		<field name="ten_hccong2" width="250">
          <text v="Tên tiếng anh" e="English name"></text>
        </field>
      </fields>
	  <script>
        <query>
          <text>
            <![CDATA[<enc>YrwPlWRGirODFAJFLt/u1lz93TfeHg3TQE0vuxwDJDMf5dLSOtk+l1tPmc5rynVNtxxLoZSB4hAl+hAZLaQPSj6wjdiaoYatU9S3dTw3OZFO6waPYLx0TmA07e0xotkoX6HkxO6+A8xPebWjw6gKtPZRNplPLP3Hw8ihCkDuXw4hVi224fG+4q1lYLvogLCpuveo47KoAu234t8clRWn8arpJUrmPXORcbXMzGpZ+5p4GOMLNQHjs/RLdc8VwiTcVrZpiV8/hOFzrSGo/BLEOQIawrte8ipZqtThdq7KcDITPkSJkFGhy7KPwdpNQCS/abg4CLeV9i3ep4iQZwXHE3QrYGYYp1GBFqNGYVz2+Qk=</enc>]]>
          </text>
        </query>
      </script>
    </grid>
  </grids>
</dir>