<?xml version="1.0" encoding="utf-8"?>

<dir id="dmhmdx" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục hạng mục đề xuất" e="List of Target type"></title>
  <grids>
    <grid table="dmhmdx" fieldKey="ma_hmdx" fieldName="ten_hmdx" order="ma_hmdx" allowFilter="true" allowOrder="true" key="" >
      <fields join="">
        <field name="ma_hmdx" fieldType="PK" width="120" filterType="Code" >
          <text v="Mã hạng mục " e="Type code"></text>
        </field>
        <field name="ten_hmdx" width="200">
          <text v="Tên hạng mục" e="Type name"></text>
        </field>
		 <field name="ten_hmdx2" width="200">
          <text v="Tên khác" e="Type name"></text>
        </field>
		<field name="nguoi_check" width="250">
          <text v="Người check" e="Type name"></text>
        </field>
		<field name="nguoi_duyet" width="250">
          <text v="Người duyệt" e="Type name"></text>
        </field>	
		<field name="nguoi_thuchien" width="250">
          <text v="Người thực hiện" e="Type name"></text>
        </field>
      </fields>
	  <script>
        <query>
          <text>
            <![CDATA[<enc>YrwPlWRGirODFAJFLt/u1lz93TfeHg3TQE0vuxwDJDMf5dLSOtk+l1tPmc5rynVNtxxLoZSB4hAl+hAZLaQPSj6wjdiaoYatU9S3dTw3OZFO6waPYLx0TmA07e0xotkoX6HkxO6+A8xPebWjw6gKtPZRNplPLP3Hw8ihCkDuXw4hVi224fG+4q1lYLvogLCpuveo47KoAu234t8clRWn8arpJUrmPXORcbXMzGpZ+5p4GOMLNQHjs/RLdc8VwiTcVrZpiV8/hOFzrSGo/BLEOQIawrte8ipZqtThdq7KcDITPkSJkFGhy7KPwdpNQCS/abg4CLeV9i3ep4iQZwXHE3QrYGYYp1GBFqNGYVz2+Qk=</enc>]]>
          </text>
        </query>
      </script>
    </grid>
  </grids>
</dir>