<?xml version="1.0" encoding="utf-8"?>

<dir id="dmhopdong" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục hợp đồng" e="List of contract"></title>
  <grids>
    <grid table="dmhopdong" fieldKey="ma_hd" fieldName="ten_hd" order="ma_hd" allowFilter="true" allowOrder="true" key="" >
      <fields join="">
        <field name="ma_hd" fieldType="PK" width="120" filterType="Code" >
          <text v="Mã hợp đồng" e="Contract code"></text>
        </field>
        <field name="ten_hd" width="250">
          <text v="Tên hợp đồng" e="Contract name"></text>
        </field>
      </fields>
    </grid>
  </grids>
</dir>