<?xml version="1.0" encoding="utf-8"?>

<dir id="dmhogiadinh" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh sách hộ gia đình" e="Household List"></title>
  <grids>
    <grid table="dmhogiadinh" fieldKey="ma_hogiadinh" fieldName="ten_hogiadinh" order="ma_hogiadinh" allowFilter="true" allowOrder="true">
      <fields>
		<field name="ma_hogiadinh" width="120" fieldType="PK" format="U" filterType="Code">
          <text v="Mã hộ gia đình" e="Household Code"></text>
        </field>
		<field name="ma_chuho" width="120">
		  <text v="Mã chủ hộ" e="Household Lead Code"></text>
		</field>
		<field name="ten_chuho" width="200" fieldType="EX">
		  <text v="Tên chủ hộ" e="Household Lead Name"></text>
		</field>
		<field name="dia_chi" width="200">
		  <text v="Địa chỉ" e="Address"></text>
		</field>
		<field name="ma_khupho" width="120">
		  <text v="Mã khu phố" e="Neighborhood Code"></text>
		</field>
		<field name="ten_khupho" width="200" fieldType="EX">
		  <text v="Tên khu phố" e="Neighborhood Name"></text>
		</field>
		<field name="ma_phuongxa" width="120">
			<text v="Mã phường/xã" e="Ward/Commune Code"></text>
		</field>
		<field name="ten_phuongxa" width="200" fieldType="EX">
			<text v="Tên phường/xã" e="Ward/Commune Name"></text>
		</field>
		<field name="ma_ttp" width="120">
		  <text v="Mã tỉnh thành" e="Province/City Code"></text>
		</field>
		<field name="ten_ttp" width="200" fieldType="EX">
		  <text v="Tên tỉnh thành" e="Province/City Code"></text>
		</field>
      </fields>
	<script>
	<query>
	  <text>
		<![CDATA[<enc>7XhUf9ToOwvd6VBoO9fVfNif28IO0XTDX7IxMrFkBTK8xgbjy1f3e0JfoKJiZ8azD+WRBznC8Gwx4GemJWqilIUIU8mhiStC9p8iImvAZ351nXoski3BZ28Cy5I9+uCZu+xxUjZzt/IpLL0Kn93m9KJphfDi5M0fjgo6qoZCjmJrKE3spimWqIUSBjSUZvI6wBsaJlAVikw0OGsL9iYWogPAXO1iaS6W/A7pnccQTdw9AJwVP5UTWLLxGgTSNQZAbptwUdHgmkHdVKfMF43jLZr0cX9NO4X+s/q3uvFGQkq6uo49/o9XPmrQ/CWD0rQ7HBTHK+LG585OhzOtMqScWTaMCgu60hgsI8S73VhJMHfKdEkJTieicRpT4GTpbzpLrGumpddCdxsIxZ7RgJiCg1zzB95EQMtc/0nvtwDUcuO5j3n2tFoGXhY4+f0IhXwzYFR1MAzmFff6IkTLUJYd9b1W3CbAgKFmPb/sVxadzj4vFm6VTLD4wez1Wwhf1Z4SgQirSDRIdX0rQTUzOufHkw==</enc>]]>
	  </text>
	</query>
	</script>
    </grid>
  </grids>
</dir>