<?xml version="1.0" encoding="utf-8"?>

<dir id="dmhttt" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục hình thức thanh toán" e="List of payment methods"></title>
  <grids>
    <grid table="dmhttt" fieldKey="httt" fieldName="ma_httt" order="ma_httt" allowFilter="true" allowOrder="true" >
      <fields>
        <field name="ma_httt" fieldType="PK" width="100" filterType="Code" >
          <text v="Mã hình thức thanh toán" e="Payment code"></text>
        </field>
        <field name="ten_httt" width="250">
          <text v="Tên hình thức thanh toán" e="Payment name"></text>
        </field>
      </fields>
    </grid>
  </grids>
</dir>