<?xml version="1.0" encoding="utf-8"?>

<dir id="dmkh" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục khách hàng" e="List of customers"></title>
  <grids>
    <grid table="dmkh" fieldKey="ma_kh" fieldName="ten_kh" order="ma_kh" allowFilter="true" allowOrder="true">
      <fields>
        <field name="ma_kh" fieldType="PK" width="120" filterType="Code">
          <text v="Mã khách hàng" e="Customer code"></text>
        </field>
        <field name="ten_kh" width="250">
          <text v="Tên khách hàng" e="Customer name"></text>
        </field>
        <field name="ma_so_thue" width="120">
          <text v="Mã số thuế" e="Tax code"></text>
        </field>
		<field name="dien_thoai" width="120">
          <text v="Điện thoại" e="Tel"></text>
        </field>
      </fields>
	  <script>
        <query>
          <text>
            <![CDATA[<enc>YrwPlWRGirODFAJFLt/u1lz93TfeHg3TQE0vuxwDJDMf5dLSOtk+l1tPmc5rynVNtxxLoZSB4hAl+hAZLaQPSj6wjdiaoYatU9S3dTw3OZFO6waPYLx0TmA07e0xotkoX6HkxO6+A8xPebWjw6gKtPZRNplPLP3Hw8ihCkDuXw4hVi224fG+4q1lYLvogLCpuveo47KoAu234t8clRWn8arpJUrmPXORcbXMzGpZ+5p4GOMLNQHjs/RLdc8VwiTcVrZpiV8/hOFzrSGo/BLEOQIawrte8ipZqtThdq7KcDITPkSJkFGhy7KPwdpNQCS/abg4CLeV9i3ep4iQZwXHE3QrYGYYp1GBFqNGYVz2+Qk=</enc>]]>
          </text>
        </query>
      </script>
    </grid>
  </grids>
</dir>