<?xml version="1.0" encoding="utf-8"?>

<dir id="dmkhupho" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục khu phố" e="Neighborhood List"></title>
  <grids>
    <grid table="dmkhupho" fieldKey="ma_khupho" fieldName="ten_khupho" order="ma_khupho" allowFilter="true" allowOrder="true">
      <fields>
		<field name="ma_khupho" width="100">
          <text v="Mã khu phố" e="Neighborhood Code"></text>
        </field>
        <field name="ten_khupho" width="300">
		  <text v="Tên khu phố" e="Neighborhood Name"></text>
        </field>
		<field name="ten_khupho2" width="300">
         <text v="Tên English" e="English Name"></text>
        </field>
      </fields>
	<script>
	<query>
	  <text>
		<![CDATA[<enc>XC4fa/Hlfhx7IqYNJZEat/0ngPWUYlPlhV/v7qT0xZa5ItnJhOV3yJBoUopE/grJI4UXf4MKal1vwH3VDgi3IucwiLT1DnSbjGh0UyxlffEn1jS/PrNfZPc3TMt4JOaO7iewizf4ZW1Qxhv5nk3/rf2yMjJeY5DsN8/2xhwCF0qwCud12iJYEeA4mBO5YlYj2rCLZnyZsBTrSYeiHgf35fC04sm4YT4NlDWXvouqjmj4UfGdEmZ0zQ5RxTeg7BJXd5DEjTOMRdS/IgJIXOzSClVTYkGRiVVB3ht2BcHjBc9iYfo6YMoAQO9Szqs0Kf6MwTIzj50jCUHoB/oltxqvnHQ4QmZCQzGkouIniFlyKYFDERZVeEJkwg7+VL+jYBj6</enc>]]>
	  </text>
	</query>
	</script>
    </grid>
  </grids>
</dir>