<?xml version="1.0" encoding="utf-8"?>

<dir id="dmkien" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục kiện" e="List of Packages"></title>
  <grids>
    <grid table="dmkien" fieldKey="ma_kien" fieldName="ten_kien" order="ma_kien" allowFilter="true" allowOrder="true" key="" >
      <fields>
        <field name="ma_kien" fieldType="PK" width="120" filterType="Code" >
          <text v="Mã kiện" e="Package Code"></text>
        </field>
        <field name="ten_kien" width="250">
          <text v="Tên kiện" e="Package Name"></text>
        </field>        
		<field name="ten_kien2" width="250">
          <text v="Tên khác" e="Other Name"></text>
        </field>
		<field name="ma_kien3" width="120">
          <text v="Mã cũ" e="Old Case Code"></text>
        </field>
		 <field name="ten_kien3" width="250">
          <text v="Tên cũ" e="Old Case Name"></text>
        </field>
      </fields>
	  <script>
		<query>
		  <text>
			<![CDATA[<enc>YELDnlGRl+lrBwkVEdpsZUqWHYQ+50SVg9p4HJBF0BePvMLgcU2XDjUwXc/OObs5PQftB153i6Y5Ln3Qp1Y/e8PuYSdZFXeqjfrciH0nuV3jgGRRJs4+fuQVTNf35CQ7cdQVtxd649dLPL8LuPflMTFeZAKPVOCZ5LIM3c1t8dCOIAM6kuo6syWKnDr600gPFyJWSX1MjO6oR6XgWN3hkqz9dFhcwTcfatZYhQjlc7W2U2z02Qy9hcGBaRx49YA9PDRUhJA5AUHOqufKX2OOIaF7Ma+nWgAHmkgk6nckoJ2Qp+1Q/BhrCWUF159IYpMpc8i7zozkf7beJ5o42CWUEtuhRs1hTQEgJ14Q/FFTWJo=</enc>]]>
		  </text>
		</query>
	  </script>
    </grid>
  </grids>
</dir>