<?xml version="1.0" encoding="utf-8"?>

<dir id="dmlgt" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục loại giấy tờ" e="List of Document Types"></title>
  <grids>
    <grid table="dmlgt" fieldKey="ma_lgt" fieldName="ten_lgt" order="ma_lgt" allowFilter="true" allowOrder="true" key="" >
      <fields join="">
        <field name="ma_lgt" fieldType="PK" width="100" filterType="Code" >
          <text v="Mã loại" e="Type Code"></text>
        </field>
        <field name="ten_lgt" width="250">
          <text v="Tên loại" e="Type Name"></text>
        </field>
		<field name="ten_lgt2" width="250">
          <text v="Tên khác" e="Other Name"></text>
        </field>
      </fields>
	  <script>
        <query>
          <text>
            <![CDATA[<enc>YrwPlWRGirODFAJFLt/u1lz93TfeHg3TQE0vuxwDJDMf5dLSOtk+l1tPmc5rynVNtxxLoZSB4hAl+hAZLaQPSj6wjdiaoYatU9S3dTw3OZFO6waPYLx0TmA07e0xotkoX6HkxO6+A8xPebWjw6gKtPZRNplPLP3Hw8ihCkDuXw4hVi224fG+4q1lYLvogLCpuveo47KoAu234t8clRWn8arpJUrmPXORcbXMzGpZ+5p4GOMLNQHjs/RLdc8VwiTcVrZpiV8/hOFzrSGo/BLEOQIawrte8ipZqtThdq7KcDITPkSJkFGhy7KPwdpNQCS/abg4CLeV9i3ep4iQZwXHE3QrYGYYp1GBFqNGYVz2+Qk=</enc>]]>
          </text>
        </query>
      </script>
    </grid>
  </grids>
</dir>