<?xml version="1.0" encoding="utf-8"?>

<dir id="dmlinegoi" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục line gọi" e="List of contract types"></title>
  <grids>
    <grid table="dmlinegoi" fieldKey="ma_line" fieldName="ten_line" order="ma_line" allowFilter="true" allowOrder="true" key="" >
      <fields join="">
        <field name="ma_line" fieldType="PK" width="100" filterType="Code" >
          <text v="Mã line" e="Type code"></text>
        </field>
        <field name="ten_line" width="250">
          <text v="Tên line" e="Type name"></text>
        </field>
      </fields>
    </grid>
  </grids>
</dir>