<?xml version="1.0" encoding="utf-8"?>

<dir id="dmloaidvt" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục loại đơn vị tính" e="List of Unit type "></title>
  <grids>
    <grid table="dmloaidvt" fieldKey="loaidvt" fieldName="ma_loai" order="ma_loai" allowFilter="true" allowOrder="true" >
      <fields>
        <field name="ma_loai" fieldType="PK" width="100" filterType="Code" >
          <text v="Mã loại ĐVT" e="Unit type code"></text>
        </field>
        <field name="ten_loai" width="250">
          <text v="Tên loại ĐVT" e="Unit type name"></text>
        </field>
      </fields>
    </grid>
  </grids>
</dir>