<?xml version="1.0" encoding="utf-8"?>

<dir id="dmloaikm" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Loại Khuyến Mãi" e="Category Product List"></title>
  <grids>
    <grid table="dmloaikm" fieldKey="ma_loaikm" fieldName="ten_loaikm" order="ma_loaikm" allowFilter="true" allowOrder="true" key="" >
      <fields>
		<field name="ma_loaikm" fieldType="PK" width="150" filterType="Code">
          <text v="Mã Loại Khuyến Mãi" e="Product category code"></text>
        </field>
        <field name="ten_loaikm" width="250">
          <text v="Tên Loại Khuyến Mãi" e="Product category name"></text>
        </field>
		<field name="status" width="150">
          <text v="Status" e="Status"></text>
        </field>
      </fields>
	 <script>
	  <query>
	  <text>
		<![CDATA[<enc>O0tPJ/zrBYwyy3CWQlA1WJz0CSgKkL07jwgDhPeMuJWa/5QsZVYlrPB8Lq4Ob8gHK8EsyoweFM5IURbRkTHMI1RQvVSGS7E4mHSa3BkVnD88aORM2lnCLCk/SHGtjYu+q5oiGqtAz8QhVEPMvpJcM3OLqivvXmYgf4V1p3z7bJUZ4iNgFZmyR1y239XWzR0cCDp4b9+OADnM/Fyy9sky7dS85zwZNiotL/ZgerQUpz5odcwVyXuseXoxpIOUeWFSJYNiXegqZmOg4ksRfA5ZsQD5y7ySvBuEOj0WndTgBo9QFVH6vlN7RzLdE+9MZ/tpiIT/xatkd7+Q2T+YuvtwOZIy3CU2BxvAim9T8zWZfjI=</enc>]]>
	  </text>
	  </query>
	</script>
    </grid>
  </grids>
</dir>