<?xml version="1.0" encoding="utf-8"?>

<dir id="dmmodelvt" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Quản lý sản phẩm theo S/N" e="Department List"></title>
  <grids>
    <grid table="dmmodelvt" fieldKey="ma_model" fieldName="ma_vt" order="ma_model" allowFilter="true" allowOrder="true" key="" >
      <fields join="">
		<field name="ma_model" fieldType="PK" width="250" filterType="Code" >
          <text v="Mã model" e="Model Code"></text>
        </field>
        <field name="ma_vt" fieldType="PK" width="100" filterType="Code" >
          <text v="Mã sản phẩm" e="Product Code"></text>
        </field>
        <field name="ten_vt" width="300" fieldType="EX">
          <text v="Tên sản phẩm" e="Product Name"></text>
        </field>
      </fields>
	  <script>
        <query>
          <text>
            <![CDATA[<enc>o98Q/ebLZEAf52fn7MObKvpT2fQIz0/ED2OX8g3lK9zlW60jgk6P+QwMWsRw45K7xSUkDzXyl0E/xt/nBKEilm2bcju5CehGgofQgEEbEKCn7Icyy3EGFIa6lYL7WLDZ2jmZUHREajY5qiyZGw9CLn8IplwZr8+NwFN78o5s6OBSuvqjLaMtf/4AiH87qyLDS/OcQ2388s7Xsjd1hPRBg82yzkAJJW+RQdu4Rnfa4MVupllbuF7fsplbgVkfOCHGGvA1jiJJHWR9TIo7bwcDLrdfoDFZLVxui0SFxKAFw5QS4xKiY9z7+cYbDPGbuZ3qP/tgtr/LpkC4wn4s9P5wUQKBC1TUm4lyIhG+9Nko07Yw2dEhY/RGHS/0XTx6bJ+YjMaLGIAdX6pDDkAAo1/b8A==</enc>]]>
          </text>
        </query>
      </script>
    </grid>
  </grids>
</dir>