<?xml version="1.0" encoding="utf-8"?>

<dir id="dmnganhang" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục ngân hàng" e="List Bank "></title>
  <grids>
    <grid table="dmnganhang" fieldKey="ma_nh" fieldName="ma_nh" order="ma_nh" allowFilter="true" allowOrder="true" >
      <fields>
        <field name="ma_nh" fieldType="PK" width="100" filterType="Code" >
          <text v="Mã ngân hàng" e="Bank code"></text>
        </field>
        <field name="ten_nh" width="250">
          <text v="Tên ngân hàng" e="Bank name"></text>
        </field>
      </fields>
    </grid>
  </grids>
</dir>