<?xml version="1.0" encoding="utf-8"?>

<dir id="dmnganhcn" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục Ngành công nghiệp" e="Industry Directory"></title>
  <grids>
    <grid table="dmnganhcn" fieldKey="ma_ncn" fieldName="ten_ncn" order="ma_ncn" allowFilter="true" allowOrder="true">
      <fields>
        <field name="ma_ncn" fieldType="PK" width="100" filterType="Code">
          <text v="Mã ngành CN" e="Industry code"></text>
        </field>
        <field name="ten_ncn" width="250">
          <text v="Tên ngành CN" e="Industry name"></text>
        </field>
      </fields>
    </grid>
  </grids>
</dir>