<?xml version="1.0" encoding="utf-8"?>

<dir id="dmnhomkh" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục nhóm khách hàng" e="List of customer groups"></title>
  <grids>
    <grid table="dmnhomkh" fieldKey="ma_nhom" fieldName="ten_nhom" order="ma_nhom" allowFilter="true" allowOrder="true" key="" >
      <fields join="">
        <field name="ma_nhom" fieldType="PK" width="100" filterType="Code" >
          <text v="Mã nhóm khách hàng" e="Customer group code"></text>
        </field>
        <field name="ten_nhom" width="250">
          <text v="Tên nhóm khách hàng" e="Customer group name"></text>
        </field>
      </fields>
    </grid>
  </grids>
</dir>