<?xml version="1.0" encoding="utf-8"?>

<dir id="dmnhomvb" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục nhóm văn bản" e="List of group document"></title>
  <grids>
    <grid table="dmnhomvb" fieldKey="ma_nvb" fieldName="ten_nvb" order="ten_nvb" allowFilter="true" allowOrder="true">
      <fields>
		<field name="ma_nvb" width="80">
          <text v="Mã nhóm văn bản" e="Document Group Code"></text>
        </field>
        <field name="ten_nvb" width="300">
          <text v="Tên nhóm văn bản" e="Document Group Name"></text>
        </field>
		<field name="ten_nvb2" width="300">
         <text v="Tên tiếng anh" e="English Name"></text>
        </field>
      </fields>
	  <script>
		<query>
		  <text>
			<![CDATA[<enc>YELDnlGRl+lrBwkVEdpsZUqWHYQ+50SVg9p4HJBF0BePvMLgcU2XDjUwXc/OObs5PQftB153i6Y5Ln3Qp1Y/e8PuYSdZFXeqjfrciH0nuV3jgGRRJs4+fuQVTNf35CQ7cdQVtxd649dLPL8LuPflMTFeZAKPVOCZ5LIM3c1t8dCOIAM6kuo6syWKnDr600gPFyJWSX1MjO6oR6XgWN3hkqz9dFhcwTcfatZYhQjlc7W2U2z02Qy9hcGBaRx49YA9PDRUhJA5AUHOqufKX2OOIaF7Ma+nWgAHmkgk6nckoJ2Qp+1Q/BhrCWUF159IYpMpc8i7zozkf7beJ5o42CWUEtuhRs1hTQEgJ14Q/FFTWJo=</enc>]]>
		  </text>
		</query>
	  </script>
    </grid>
  </grids>
</dir>