<?xml version="1.0" encoding="utf-8"?>

<dir id="dmnv" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục nhân sự" e="List of Employee"></title>
  <grids>
    <grid table="dmnv" fieldKey="ma_nv" fieldName="ten_nv" order="ma_nv" allowFilter="true" allowOrder="true" >
      <fields>
        <field name="ma_nv" fieldType="PK" width="120" filterType="Code" >
          <text v="Mã nhân viên" e="Employee Code"></text>
        </field>
        <field name="ten_nv" width="250">
          <text v="Tên nhân viên" e="Employee Name"></text>
        </field>
		<field name="ma_pb" width="120">
          <text v="Mã phòng ban" e="Department Code"></text>
        </field>
		<field name="ten_pb" width="120" fieldType="EX">
          <text v="Phòng ban" e="Department"></text>
        </field>
		<field name="ma_bp" width="120">
          <text v="Bộ phận" e="Division Code"></text>
        </field>
		<field name="ten_bp" width="120" fieldType="EX">
          <text v="Bộ phận" e="Division"></text>
        </field>
      </fields>
	  <script>
        <query>
          <text> 	
            <![CDATA[<enc>3aRdIfPf8WcMI8XRJj9ncrTeodrrh6MxGoH0egFADGZij20faR+LSy1Ny3u8IrIaoh0DxGkPTIXSV3KjiJXfR+v1JL/UNfCopaz72ISrWvmJP6UYCdX8vvSHoDEjRY5Xy8FBAVygs8sAMMwzdPpYPn7na4NF4huaDLfwIHvrqzyH/HPDQW2SLN4jHoIzIsTRbRT3E36wkD3sATMraDtOBdGZ8c7Vhtra7IcRoUR+SIf68Jw8peC/G8m75VU07U1lmKIS1iyR8W7WZVbL2Jd4uyho6oRm/28PPqqbfRQnr9qIxHi1xMvKGEAQpr0xkOaQXOKvSPt0vUQkBjP59oR9VI35vF/kx8xip8vnJ3JbbKIg3xHYkjK4OGpVYUhf6rsHQEynQpPlkdmJcdY/gJk/tjLo+2qGeLkI/u/ZcvEFmMM=</enc>]]>
          </text>
        </query>
      </script>
    </grid>
  </grids>
</dir>