<?xml version="1.0" encoding="utf-8"?>
<dir id="dmnv" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục Nhân viên" e="Directory staff"></title>
  <grids>
    <grid table="dmnv" fieldKey="ma_nv" fieldName="ma_nv" order="ma_nv" allowFilter="true" allowOrder="true" >
      <fields>
        <field name="ma_nv" fieldType="PK" width="100" filterType="Code" >
          <text v="Mã Nhân viên" e="Staff code"></text>
        </field>
        <field name="ten_nv2" width="250">
          <text v="Tên Nhân viên" e="Staff name"></text>
        </field>
      </fields>
    </grid>
  </grids>
</dir>