<?xml version="1.0" encoding="utf-8"?>

<dir id="dmphuongxa" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục Phường/Xã" e="Ward/Commune List"></title>
  <grids>
    <grid table="dmphuongxa" fieldKey="ma_phuongxa" fieldName="ten_phuongxa" order="ma_phuongxa" allowFilter="true" allowOrder="true">
      <fields>
        <field name="ma_phuongxa" fieldType="PK" width="100" filterType="Code">
          <text v="Mã phường/xã" e="Ward/Commune Code"></text>
        </field>
        <field name="ten_phuongxa" width="250">
          <text v="Tên phường/xã" e="Ward/Commune Name"></text>
        </field>
      </fields>
	  <script>
        <query>
          <text> 	
            <![CDATA[<enc>QEWTid9R9PkCtRbb7pbwHjPJpwzo8rHi/t4v2XSyOStpte2sfbGcMxjiHLniQ9albFmFzwph+xiDT7bW2iWXWfSUGdGgAnJGNTprcjxftKr/LpnfUQXcBz82VCWJrqpby0mvMLJem2XHnz8rClqQF6pyOoUd8UOPte5iYihGD/Q6U+JBrFLsnho4Pm8k+HAHEAeLaGnakHJgtYRA2yhgHogvX38BJ1QcnrqC1HibEgbaKcYFol+rg9SBtl2nFnajDYnDHZ7fxb5MhzG5TenqGxksR0dAZKSuC9PPW4X7nmMEHmFNsVanyAYjhDRA9h+GYEwnr+pIdQBnd0s1GnHAS0ujukEO5nemQJ5ROiQ5ILDROGrhdQ/y728dN3QJ1nDw</enc>]]>
          </text>
        </query>
      </script>
    </grid>
  </grids>
</dir>