<?xml version="1.0" encoding="utf-8"?>

<dir id="dmplvb" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <text v="Văn bản lưu hành" e="Personal information: "></text>
  <grids>
    <grid table="dmplvb" fieldKey="ma_pl" fieldName="ten_pl" order="ma_pl" allowFilter="true" allowOrder="true">
      <fields>
		<field name="ma_pl" width="80">
          <text v="Mã văn bản lưu hành" e="Circulation Document Code"></text>
        </field>
        <field name="ten_pl" width="300">
		  <text v="Tên văn bản lưu hành" e="Circulation Document Name"></text>
        </field>
		<field name="ten_pl2" width="300">
         <text v="Tên English" e="English Name"></text>
        </field>
		<field name="tu_so" dataType="N" width="100">
		  <text v="Ký hiệu từ" e="Word symbol"></text>
		</field>
		<field name="den_so" dataType="N" width="100">
		  <text v="Ký hiệu đến" e="Incoming symbol"></text>
		</field>
		<field name="loai_ut" viewType="Combobox" width="100">
		  <text v="Ưu tiên" e="Priority"></text>
          <viewInfo>
            <options>
				<option val="0">
					<text v="0 - Không ưu tiên" e="0 - Không ưu tiên"></text>
				</option>
				<option val="1">
					<text v="1 - Ưu tiên" e="1 - Ưu tiên"></text>
				</option>
            </options>
          </viewInfo>
        </field>
      </fields>
	<script>
	<query>
	  <text>
		<![CDATA[<enc>54dI72bce9XoSKU6XExLwiV6ZsNJa4XN4qod4VoESBhiOh+lMtp4QpwNhd97GAzqtoolUpDW9OGLoK56fzvKJrcmCUQFsPsQmfQFnuUzl9c6Ql0ErTi2Hoto9zGx32RpF7qS7SfKTQg0OS80+3dM3nN0Y2dtRvRzGBs9+giclRIuia/0MkwW87UL7eTuF4rWbaJaXif9+PhitPQQVRWM8ycwuiJhimWZmw2lhDMNYBi5w1FtLJ0pDCXd1g05wwvQDDi2JjOjYBHjHsfdQ2Qax7rvBjnfJruIG7s/ie9p4xNDxZPosA/l75hb+iSSxgk/XWSkyv5mQVF6dey06qCfpTyYFsRYFGvN1+6xwM9mVos=</enc>]]>
	  </text>
	</query>
	</script>
    </grid>
  </grids>
</dir>