<?xml version="1.0" encoding="utf-8"?>

<dir id="dmplnhvtc2" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục nhóm phân loại vật tư 2" e="Material Group Level 2"></title>
  <grids>
    <grid table="dmplnhvtc2" fieldKey="ma_nh" fieldName="ten_nh" order="ma_nh" allowFilter="true" allowOrder="true" key="unit_id in (select unit_id from dbo.ISWIFTFunctionGetUnitIDRight(@@userId, @@admin, ''''))" >
      <fields>
        <field name="ma_nh" fieldType="PK" width="120" filterType="Code" >
          <text v="Mã nhóm plvt 2" e="MGroup Code 2"></text>
        </field>
        <field name="ten_nh" width="250">
          <text v="Tên nhóm plvt 2" e="MGroup Name 2"></text>
        </field>
      </fields>
	  <script>
        <query>
          <text>
            <![CDATA[<enc>YrwPlWRGirODFAJFLt/u1lz93TfeHg3TQE0vuxwDJDMf5dLSOtk+l1tPmc5rynVNtxxLoZSB4hAl+hAZLaQPSj6wjdiaoYatU9S3dTw3OZFO6waPYLx0TmA07e0xotkoX6HkxO6+A8xPebWjw6gKtPZRNplPLP3Hw8ihCkDuXw4hVi224fG+4q1lYLvogLCpuveo47KoAu234t8clRWn8arpJUrmPXORcbXMzGpZ+5p4GOMLNQHjs/RLdc8VwiTcVrZpiV8/hOFzrSGo/BLEOQIawrte8ipZqtThdq7KcDITPkSJkFGhy7KPwdpNQCS/abg4CLeV9i3ep4iQZwXHE3QrYGYYp1GBFqNGYVz2+Qk=</enc>]]>
          </text>
        </query>
      </script>
    </grid>
  </grids>
</dir>