<?xml version="1.0" encoding="utf-8"?>

<dir id="dmptvc" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục phương tiện vận chuyển" e="Department List"></title>
  <grids>
    <grid table="dmptvc" fieldKey="ma_ptvc" fieldName="ten_ptvc" order="ma_ptvc" allowFilter="true" allowOrder="true" key="" >
      <fields>
        <field name="ma_ptvc" fieldType="PK" width="100" filterType="Code" >
          <text v="Mã phương tiện" e="Department Code"></text>
        </field>
        <field name="ten_ptvc" width="250">
          <text v="Tên phương tiện" e="Department Name"></text>
        </field>
      </fields>
    </grid>
  </grids>
</dir>