<?xml version="1.0" encoding="utf-8"?>

<dir id="dmqhgd" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục quan hệ gia đình" e="List of position"></title>
  <grids>
    <grid table="dmqhgd" fieldKey="ma_qh" fieldName="ten_qh" order="ma_qh" allowFilter="true" allowOrder="true" key="" >
      <fields join="">
        <field name="ma_qh" fieldType="PK" width="120" filterType="Code" >
          <text v="Mã quan hệ" e="Relationship code"></text>
        </field>
        <field name="ten_qh" width="250">
          <text v="Tên quan hệ" e="Relationship name"></text>
        </field>
      </fields>
		<script>
        <query>
          <text>
            <![CDATA[<enc>YrwPlWRGirODFAJFLt/u1lz93TfeHg3TQE0vuxwDJDMf5dLSOtk+l1tPmc5rynVNtxxLoZSB4hAl+hAZLaQPSj6wjdiaoYatU9S3dTw3OZFO6waPYLx0TmA07e0xotkoX6HkxO6+A8xPebWjw6gKtPZRNplPLP3Hw8ihCkDuXw4hVi224fG+4q1lYLvogLCpuveo47KoAu234t8clRWn8arpJUrmPXORcbXMzGpZ+5p4GOMLNQHjs/RLdc8VwiTcVrZpiV8/hOFzrSGo/BLEOQIawrte8ipZqtThdq7KcDITPkSJkFGhy7KPwdpNQCS/abg4CLeV9i3ep4iQZwXHE3QrYGYYp1GBFqNGYVz2+Qk=</enc>]]>
          </text>
        </query>
      </script>
    </grid>
  </grids>
</dir>