<?xml version="1.0" encoding="utf-8"?>

<dir id="dmrmail" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục mail" e="List of mail"></title>
  <grids>
    <grid table="dmrmail" fieldKey="r_mail" fieldName="ten_mail" order="r_mail" allowFilter="true" allowOrder="true" key="" >
      <fields>
        <field name="r_mail" fieldType="PK" width="120" filterType="Code" >
          <text v="Mã mail" e="mail Code"></text>
        </field>
        <field name="ten_mail" width="250">
          <text v="Tên mail" e="mail Name"></text>
        </field>     
		<field name="ten_mail2" width="250">
          <text v="Tên khác" e="Other Name"></text>
        </field>
      </fields>
	  <script>
        <query>
          <text>
            <![CDATA[<enc>YrwPlWRGirODFAJFLt/u1lz93TfeHg3TQE0vuxwDJDMf5dLSOtk+l1tPmc5rynVNtxxLoZSB4hAl+hAZLaQPSj6wjdiaoYatU9S3dTw3OZFO6waPYLx0TmA07e0xotkoX6HkxO6+A8xPebWjw6gKtPZRNplPLP3Hw8ihCkDuXw4hVi224fG+4q1lYLvogLCpuveo47KoAu234t8clRWn8arpJUrmPXORcbXMzGpZ+5p4GOMLNQHjs/RLdc8VwiTcVrZpiV8/hOFzrSGo/BLEOQIawrte8ipZqtThdq7KcDITPkSJkFGhy7KPwdpNQCS/abg4CLeV9i3ep4iQZwXHE3QrYGYYp1GBFqNGYVz2+Qk=</enc>]]>
          </text>
        </query>
      </script>
    </grid>
  </grids>
</dir>