<?xml version="1.0" encoding="utf-8"?>

<dir id="dmtdhv" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục học vấn" e="List of education"></title>
  <grids>
    <grid table="dmtdhv" fieldKey="ma_hv" fieldName="ten_hv" order="ma_hv" allowFilter="true" allowOrder="true" key="" >
      <fields join="">
        <field name="ma_hv" fieldType="PK" width="120" filterType="Code" >
          <text v="Mã học vấn" e="Education code"></text>
        </field>
        <field name="ten_hv" width="250">
          <text v="Tên học vấn" e="Education name"></text>
        </field>
      </fields>
    </grid>
  </grids>
</dir>