<?xml version="1.0" encoding="utf-8"?>

<dir id="dmtgluuvb" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh sách thời hạn lưu trữ" e="List of Retention Periods"></title>
  <grids>
    <grid table="dmtgluuvb" fieldKey="ma_tg" fieldName="ten_tg" order="ma_tg" allowFilter="true" allowOrder="true">
      <fields>
		<field name="ma_tg" width="120" fieldType="PK" format="U" filterType="Code">
			<text v="Mã thời hạn lưu trữ" e="Retention period code"></text>
		</field>
		<field name="ten_tg" width="250">
		  <text v="Tên thời hạn lưu trữ" e="Retention period Name"></text>
		</field>
		<field name="ten_tg2" width="200">
		  <text v="Tên English" e="Name English"></text>
		</field>
		<field name="he_so" dataType="N" format = "Amount" width="100">
			<text v="Hệ số" e="Coefficient"></text>
		</field>
      </fields>
	<script>
	<query>
	  <text>
		<![CDATA[<enc>VGq7kagZf8on7/jemugEgGktg8roSNOYZQXBVk1kkidNlIpRSkUC+f968GkBqOMAOTHHyRD0r8qnFr8kPWNWA5XZpg1kQ93k9Fm2SHox5rGRHR/fhleQ+kyZ1eKYcoDkfCn0eA3tSyNMuWafDxRkChDB4v51pFCvt4DeeNz/7IkLptU8M89bLuC0+zBfiv3SoAcaFU+YXH+BL/topSQqYurzjNEuBXnAPgVMYbihIWT+zwngCtLDMvyIOHFg/cMukVyLT7w1zxDtdVOSCcUfLkhOU/Upkl0oLeHCpfaaZpA5d7ogMunrizMOeIS12I+oVRB9ZLX0dTKJBpYAOK8Ygv6XsPdP6R9gP3sPQcl4zW1pJa+Bk3+IDnJ8ALjnSF9T</enc>]]>
	  </text>
	</query>
	</script>
    </grid>
  </grids>
</dir>