<?xml version="1.0" encoding="utf-8"?>

<dir id="dmtongiao" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục tôn giáo" e="List of Religions"></title>
  <grids>
    <grid table="dmtongiao" fieldKey="ma_tg" fieldName="ten_tg" order="ma_tg" allowFilter="true" allowOrder="true" key="" >
      <fields join="">
        <field name="ma_tg" fieldType="PK" width="120" filterType="Code" >
          <text v="Mã tôn giáo" e="Religion Code"></text>
        </field>
        <field name="ten_tg" width="250">
          <text v="Tên tôn giáo" e="Religion Name"></text>
        </field>
		<field name="ten_tg2" width="250">
          <text v="Tên khác" e="Other Name"></text>
        </field>
      </fields>
	  <script>
        <query>
          <text>
            <![CDATA[<enc>YrwPlWRGirODFAJFLt/u1lz93TfeHg3TQE0vuxwDJDMf5dLSOtk+l1tPmc5rynVNtxxLoZSB4hAl+hAZLaQPSj6wjdiaoYatU9S3dTw3OZFO6waPYLx0TmA07e0xotkoX6HkxO6+A8xPebWjw6gKtPZRNplPLP3Hw8ihCkDuXw4hVi224fG+4q1lYLvogLCpuveo47KoAu234t8clRWn8arpJUrmPXORcbXMzGpZ+5p4GOMLNQHjs/RLdc8VwiTcVrZpiV8/hOFzrSGo/BLEOQIawrte8ipZqtThdq7KcDITPkSJkFGhy7KPwdpNQCS/abg4CLeV9i3ep4iQZwXHE3QrYGYYp1GBFqNGYVz2+Qk=</enc>]]>
          </text>
        </query>
      </script>
    </grid>
  </grids>
</dir>