<?xml version="1.0" encoding="utf-8"?>

<dir id="dmttp" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục tỉnh thành phố" e="List of provinces/cities"></title>
  <grids>
    <grid table="dmttp" fieldKey="ma_ttp" fieldName="ten_ttp" order="ma_ttp" allowFilter="true" allowOrder="true">
      <fields>
        <field name="ma_ttp" fieldType="PK" width="120" filterType="Code">
          <text v="Mã thành phố" e="City Code"></text>
        </field>
        <field name="ten_ttp" width="250">
          <text v="Tên thành phố" e="City Name"></text>
        </field>
      </fields>
	  <script>
        <query>
          <text> 	
            <![CDATA[<enc>x2e/Imt1kOGMV57jmrRXTZ1ZXjj1XnFX20e62e4TuiG7k+POvZTuO6BFxYqO53CoBqLvHvTAsctQ2ge70qZJ8gawLIHx5c26uKcMXMHnOoRTnM8BB6qM6kICH9OnhPm2XQs4vpViZSzLHL+V15+gk6hELorMs0YvyvjP7sBdwtgZ/z3VgtvTjSJeGC+9s0fGVTHbiQ1m/ANFH9j9iBEVRZMV4wTXsYebfObHOzPAi+Jxae3nREoiyqKyL0HNsDc5azJ6wT8f1mY8ULohMBt8hjdtwcCzKSouuqNK8FYvgmyTUZEgTfHF8Cw6kZIZfhJFRghK55E13prSvwG5wwO6Nlh65n3qU4JuuRRnX909zYhdoMhm5/TcNzdjblo0g34k</enc>]]>
          </text>
        </query>
      </script>
    </grid>
  </grids>
</dir>