<?xml version="1.0" encoding="utf-8"?>

<dir id="qldctcccd" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
   <title v="Quản lý dân cư theo căn cước công dân" e="Population Management by Citizen ID"></title>
  <grids>
    <grid table="qldctcccd" fieldKey="ma_dancu" fieldName="ten_dancu" order="ma_dancu" allowFilter="true" allowOrder="true">
      <fields>
		<field name="ma_dancu" width="80" fieldType="PK" format="U" filterType="Code">
          <text v="Mã cư dân" e="Resident Code"></text>
        </field>
        <field name="ten_dancu" width="300">
		  <text v="Tên cư dân" e="Resident Name"></text>
        </field>
		<field name="ten_dancu2" width="300">
         <text v="Tên khác" e="Other name"></text>
        </field>
		<field name="dien_thoai" width="80">
		  <text v="Điện thoại" e="Phone"></text>
		</field>
		<field name="so_cccd" width="120">
		  <text v="Số CCCD/Mã định danh" e="ID Number"></text>
		</field>
		<field name="ngay_sinh" datatype="D" width="80">
		  <text v="Ngày sinh" e="Birthday"></text>
		</field>
		<field name="gioi_tinh" width="80">
		  <text v="Giới tính" e="ID Number"></text>
		</field>
		<field name="dan_toc" width="80">
		  <text v="Dân tộc" e="Ethnicity"></text>
		</field>
      </fields>
	<script>
	<query>
	  <text>
		<![CDATA[<enc>VGq7kagZf8on7/jemugEgGktg8roSNOYZQXBVk1kkidNlIpRSkUC+f968GkBqOMAOTHHyRD0r8qnFr8kPWNWA5XZpg1kQ93k9Fm2SHox5rGRHR/fhleQ+kyZ1eKYcoDkfCn0eA3tSyNMuWafDxRkChDB4v51pFCvt4DeeNz/7IkLptU8M89bLuC0+zBfiv3SoAcaFU+YXH+BL/topSQqYurzjNEuBXnAPgVMYbihIWT+zwngCtLDMvyIOHFg/cMukVyLT7w1zxDtdVOSCcUfLkhOU/Upkl0oLeHCpfaaZpA5d7ogMunrizMOeIS12I+oVRB9ZLX0dTKJBpYAOK8Ygv6XsPdP6R9gP3sPQcl4zW1pJa+Bk3+IDnJ8ALjnSF9T</enc>]]>
	  </text>
	</query>
	</script>
    </grid>
  </grids>
</dir>