<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
]>

<dir id="s13" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Yêu cầu báo giá dịch vụ" e="Request a quote services"></title>

  <grids>
    <grid table="s13" fieldKey="id" fieldName="so_ct" order="id" allowFilter="true" allowOrder="true">
      <fields>
        <field name="id" dataType="N" fieldType="PK" width="50" format="0" filterType="Code">
          <text v="ID" e="ID"></text>
        </field>
        <field name="so_ct" width="80" fieldType="RF" >
          <text v="Số c/từ" e="Voucher number"></text>
        </field>
        <field name="ngay_ct" width="120" dataType="D">
          <text v="Ngày c/từ" e="Voucher date"></text>
        </field>
        <field name="ma_kh" width="120" >
          <text v="Mã khách hàng" e="Customer Code"></text>
        </field>
        <field name="ten_kh" width="250" >
          <text v="Tên khách hàng" e="Customer Name"></text>
        </field>
		<field name="ma_noi_di" width="120" hidden="false">
          <text v="Mã nơi đi" e="Origin Code"></text>
        </field>
        <field name="ten_noi_di" width="250" fieldType="EX">
		  <text v="Nơi đi " e="Origin"></text>
		</field>	
		<field name="ma_noi_den" width="120" hidden="false">
          <text v="Mã nơi đến" e="Destination Code"></text>
        </field>
		<field name="ten_noi_den" width="250" fieldType="EX">
		  <text v="Nơi đến" e="Destination"></text>
		</field>	
		<field name="ngay_hl" width="120" dataType="D" >
			<text v="Ngày hiệu lực" e="Effective date"></text>
		</field>		
		<field name="ngay_hld" width="120" dataType="D">
			<text v="Hiệu lực đến" e="Expiry date"></text>
		</field>
		<field name="t_so_luong" dataType="N" format="FCAmount" width="80">
          <text v="Tổng kiện" e="Total Container"></text>
        </field>
        <field name="t_tong_trong" dataType="N" format="FCAmount" width="120">
          <text v="Tổng trọng lượng" e="Total amount"></text>
        </field>
		<field name="t_tong_khoi" dataType="N" format="FCAmount" width="120">
          <text v="Tổng Volume" e="Total Volume"></text>
        </field>
      </fields>
      <script>
        <query>
          <text>
            <![CDATA[<enc>xapjpy0GrkPSI8mE/fqgYfObDY5rbalJGU6r28gmhcW9PJVB+xWsMiF5JkbT+5PAacTuPdkRoFOhU/eWcSfUzmNF5+ciJjMXhZLBdrwzl6emswktCKXG+hFmrUAtZpSozofYhNFRH6ANa9BucmonGhz28pvF8F9tYYe+6L2qnobVngrc98LHrCsY+JhJE7gToSfRYkQYRgJ5u5g148aV62uUDpl3bVK4lGfvLOsX93CZDIEdDS5tcpZQeSqAIa/C3dbG0ncM5d8KCnxTV92P1uQf0YzytGO8uRk5RHIMjHqNCwQnr+XOEvQqWPK2PMiRhzgvDTzEyC81jlGK1dLc3lD+m38aPziigXVVmMBatQC6z+EpJrp922ZH01J6ATEdcjhYeJboRCezEISu8j2bSwd6mhoNQH7amTSxQjmYUrI=</enc>]]>
          </text>
        </query>
      </script>
    </grid>
  </grids>
</dir>