<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
]>

<dir id="s41" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Báo giá dịch vụ" e="Quotation services"></title>

  <grids>
    <grid table="s41" fieldKey="id" fieldName="ma_kh" order="ngay_ct" allowFilter="true" allowOrder="true">
      <fields>
        <field name="id" dataType="N" fieldType="PK" width="50" format="0" filterType="Code">
          <text v="ID" e="ID"></text>
        </field>
        <field name="so_ct" width="120" fieldType="RF" hidden="true" >
          <text v="Số c/từ" e="Voucher number"></text>
        </field>
        <field name="ngay_ct" width="120" dataType="D">
          <text v="Ngày c/từ" e="Voucher date"></text>
        </field>
		<field name="ma_job" width="100" hidden="false" >
          <text v="Mã job" e="Job Code"></text>
        </field>
		<field name="so_job" width="100" >
          <text v="Số job" e="Job Number"></text>
        </field>
        <field name="ma_kh" width="120" >
          <text v="Mã khách hàng" e="Customer Code"></text>
        </field>
        <field name="ten_kh" width="250" fieldType="EX" >
          <text v="Tên khách hàng" e="Customer name"></text>
        </field>
		<field name="ma_noi_di" width="100" hidden="false">
          <text v="Mã nơi đi" e="Origin"></text>
        </field>
        <field name="ten_noi_di" width="250" fieldType="EX">
		  <text v="Nơi đi " e="Origin name"></text>
		</field>
		<field name="ma_noi_den" width="100" hidden="false">
          <text v="Nơi đến" e="Destination"></text>
        </field>
		<field name="ten_noi_den" width="250" fieldType="EX">
		  <text v="Nơi đến" e="Destination"></text>
		</field>
		<field name="ma_hang" width="150" >
          <text v="Mã Hãng tàu/Đại lý" e=" Carrier/Agent Code"></text>
        </field>
		<field name="ten_hang" width="250" fieldType="EX" >
          <text v="Tên Hãng tàu/Đại lý" e="Carrier/Agent Name"></text>
        </field>		
		<field name="ngay_hl" width="120" dataType="D" >
			<text v="Ngày hiệu lực" e="Effective date"></text>
		</field>	
		<field name="ngay_hld" width="120" dataType="D">
			<text v="Hiệu lực đến" e="Expiry date"></text>
		</field>
      </fields>
      <script>
        <query>
          <text>
            <![CDATA[<enc>atkdHtxEbWTTvY30Jpcrj/2yszgEbeii+EysJml0OFJZKQHvBepw0XJpeBdTdW0ie9Ri00evg3v7NSFnl+q6dpODIm8iBcGN71LL2Rxf+L5hZF1l/1qRT/AVUaS75oyZBdHBfTXkW9hwUrBaSHpL/HqBJRMkHRl3CKqL3YG8GGLwBbIoI5oGKlBqu2jwb/FR1FPmqRfbPywkiUZz6twSBKE+RJAcC1iM0WxkpZaxubJaNDIlgjjt9AZDvUhq8KWQpU4iG+nCbcnXLIhUAf7ULrkG2bG09x4MiAuAJEOry8PNJYAsnwu+c/n09o5SsnXPTQMmUF9lr1CBILV2/yqYotHDbyxnZNgDcoIBU26ZQtSOR158DREE+G0WDot5Bm5IYybAMK5nGcTEwWMcX5knkv2hWlm5xRZQZ/ZlgiijfxHM1zWEnVmYpnNy9LkiVspSDOp/209Y29qqpNyDF+vz83kp7cIj8SzyhFtYJtPIT+8=</enc>]]>
          </text>
        </query>
      </script>

    </grid>
  </grids>
</dir>