<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
]>

<dir id="s61" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh sách tổng hợp đơn hàng" e="Order summary list"></title>

  <grids>
    <grid table="s61" fieldKey="id" fieldName="(ma_job+so_job) so_ct_dh" order="id" allowFilter="true" allowOrder="true">
      <fields>
		<field name="id" dataType="N" fieldType="PK" width="50" format="0" filterType="Code">
          <text v="ID" e="ID"></text>
        </field>
		<field name="so_ct_dh" width="100" aliasName=" so_ct as " >
          <text v="Số c/từ" e="Voucher number"></text>
        </field>
		<field name="ma_ct" width="100" >
          <text v="Mã c/từ" e="Voucher Code"></text>
        </field>
        <field name="ngay_ct" width="100" dataType="D">
          <text v="Ngày c/từ" e="Voucher date"></text>
        </field>
        <field name="so_ct" width="0" fieldType="RF" >
          <text v="Số c/từ" e="Voucher number"></text>
        </field>
		<!-- <field name="ma_log" width="100"> -->
          <!-- <text v="Mã log" e="Voucher number"></text> -->
        <!-- </field> -->
		<field name="ma_job" width="0" hidden = "false">
          <text v="Mã job" e="Job Code"></text>
        </field>
		<field name="so_job" width="0" >
          <text v="Số job" e="Job Number"></text>
        </field>
		<field name="ma_gd" width="0" >
          <text v="Giao dịch" e="Voucher number"></text>
        </field>
		<field name="ma_ngv" width="0" >
          <text v="Loại hóa đơn" e="Voucher number"></text>
        </field>

        <field name="ma_kh" width="120" >
          <text v="Mã khách hàng" e="Customer Code"></text>
        </field>
        <field name="ten_kh" width="250" fieldType="EX" >
          <text v="Tên khách hàng" e="Customer name"></text>
        </field>
		<field name="ma_hang" width="120" >
          <text v="Mã hãng tàu" e="Carrier Code"></text>
        </field>
        <field name="ten_hang" width="250" fieldType="EX" >
          <text v="Tên khách hàng" e="Carrier name"></text>
        </field>
        <field name="ten_noi_di" width="250" fieldType="EX">
		  <text v="Nơi đi " e="Origin "></text>
		</field>
		<field name="ten_noi_den" width="250" fieldType="EX">
		  <text v="Nơi đến " e="Destination"></text>
		</field>		
		<field name="ma_noi_di" width="100" hidden="false">
          <text v="Nơi đi" e="Origin"></text>
        </field>
		<field name="ma_noi_den" width="100" hidden="false">
          <text v="Nơi đến" e="Destination"></text>
        </field>
		<field name="ngay_hl" width="120" dataType="D" >
			<text v="Ngày hiệu lực" e="Effective date"></text>
		</field>	
		<field name="ngay_hld" width="120" dataType="D">
			<text v="Hiệu lực đến" e="Expiry date"></text>
		</field>
      </fields>
      <script>
        <query>
          <text>
            <![CDATA[<enc>9fX3tuAp6g418eFn420s5Z85qEmSB8sTA7htufpTvP/GTsPJ0o1gOzRQMHPvSvQ0DUEFabCnJalrr5iVB3Fk1bRciCNp0wJqOWwkB1GXP1xC6ldn0DF/Zmbh3sTQVtSFtYvRpU98WmNAv8M/B19SoTdTDPC0vjhmBDfBq+IbvC8DfrpY5mR+mWtxg/c4q0w1LOlY5xtq/Kye6Wt5UYFsSAtehJ9sHmfJ6ISfAsUOQFDVKufFg+QlSGq/MwBf+ts+9rXUiFQ8dOFYILTnFH8J16cL3fW3uT6+sX3RmqJ10u189VNXy5qNdjF1oTT+g9F5F1QBP9mcX9Zk0a+1Xiz7c0CRGN9imo5VfkZe5no3Ymd+stUGVTAtuyn6uQ5E7lA3g0s5Kvh0lD0Grw0ChvPT7fOJJQp8PRcHyEum/La47+r8zatIZ51oYmLLYwt0LnTuEt2FM+/2+nwQjdksgCku8QuM3+EjU3PqSNiXrcQRivE=</enc>]]>
          </text>
        </query>
      </script>

    </grid>
  </grids>
</dir>