<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
]>

<dir id="s61" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Báo giá dịch vụ" e="Quotation services"></title>

  <grids>
    <grid table="s61" fieldKey="id" fieldName="so_ct" order="id" allowFilter="true" allowOrder="true">
      <fields>
		<field name="id" dataType="N" fieldType="PK" width="50" format="0" filterType="Code">
          <text v="ID" e="ID"></text>
        </field>
        <field name="so_ct" width="120" fieldType="RF" >
          <text v="Số c/từ" e="Voucher number"></text>
        </field>
        <field name="ngay_ct" width="120" dataType="D">
          <text v="Ngày c/từ" e="Voucher date"></text>
        </field>
		<field name="ma_gd" width="0" >
          <text v="Giao dịch" e="Voucher number"></text>
        </field>
		<field name="ma_ngv" width="0" >
          <text v="Loại hóa đơn" e="Voucher number"></text>
        </field>
        <field name="ma_kh" width="120" >
          <text v="Mã khách hàng" e="Customer Code"></text>
        </field>
        <field name="ten_kh" width="250" fieldType="EX" >
          <text v="Tên khách hàng" e="Customer name"></text>
        </field>
		<field name="ma_hang" width="120" >
          <text v="Mã khách hàng" e="Customer Code"></text>
        </field>
        <field name="ten_hang" width="250" fieldType="EX" >
          <text v="Tên khách hàng" e="Customer name"></text>
        </field>
        <field name="ten_noi_di" width="250" fieldType="EX">
		  <text v="Nơi đi " e="Origin name"></text>
		</field>
		<field name="ten_noi_den" width="250" fieldType="EX">
		  <text v="Nơi đến " e="Destination name"></text>
		</field>		
		<field name="ma_noi_di" width="100" hidden="false">
          <text v="Nơi đi" e="Origin"></text>
        </field>
		<field name="ma_noi_den" width="100" hidden="false">
          <text v="Nơi đến" e="Destination"></text>
        </field>
		<field name="ngay_hl" width="120" dataType="D" >
			<text v="Ngày hiệu lực" e="Effective date"></text>
		</field>	
		<field name="ngay_hld" width="120" dataType="D">
			<text v="Hiệu lực đến" e="Expiry date"></text>
		</field>
      </fields>
      <script>
        <query>
          <text>
            <![CDATA[<enc>PLVYb/VtGXQVwFBCk+BpVGEwP9u4nyEADeBPlF9H5Aa3rx5fe6RnTIp08oL+4Z4/K4vUmy1MkfED8m1i/pjlXk5e2TSRKCcWJQo7h8eeCsVG8V6Y2rPXuPq/5KLBEPQc4ib+vIYJz2hXNH6UajjXGgqG2RrpRMduIbIvODezOPBGyo0DWrHPhXul+lr8Z6y2zhxR2g0Ca6Cqaui+rrydZ7Hbbabr+7Fwc0lrayAU4iyDtWy3eCzElKV5cMTW4ASJwXXM2GqkCsSuvIsMaqGldiQgMIg3YUqJf2HVsssVl4O5yt5JzsKNye9UUk42s4/QtDu66cE1+B5ajOLn2hCpHaV8BHTkXeyUNLxyyfo/JR0yoAn6y+5M/qbi48VV7JEFpT3dmzy1Bnvu49IdcgMmSVhPR4HqoVqZtL+hHvZKvoE=</enc>]]>
          </text>
        </query>
      </script>

    </grid>
  </grids>
</dir>