<?xml version="1.0" encoding="utf-8"?>

<dir id="tb_ProductCategory" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Loại sản phẩm" e="Category List"></title>
  <grids>
    <grid table="tb_ProductCategory" fieldKey="Id" fieldName="Title" order="Id" allowFilter="true" allowOrder="true" key="" >
      <fields>
        <field name="Id" fieldType="PK" width="100" filterType="Code" >
          <text v="Mã loại sản phẩm" e="Product category code"></text>
        </field>
        <field name="Title" width="250">
          <text v="Tên loại sản phẩm" e="Product category name"></text>
        </field>
		<field name="IsActive" width="250">
          <text v="Kích hoạt" e="Active"></text>
        </field>
      </fields>
    </grid>
  </grids>
</dir>