<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
]>

<dir id="v311" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Chi phí cho vận chuyển" e="Shipping costs"></title>

  <grids>
    <grid table="v311" fieldKey="id" fieldName="so_ct" order="id" allowFilter="true" allowOrder="true">
      <fields>
        <field name="id" dataType="N" fieldType="PK" width="120" format="0" hidden="true">
          <text v="ID" e="ID"></text>
        </field>
		<field name="line" width="0" fieldType="RF" >
          <text v="Line" e="Line"></text>
        </field>
        <field name="so_ct" width="120" fieldType="RF" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="120" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
		<field name="ma_phi" width="120" hidden="false">
          <text v="Mã phí" e="Fee code"></text>
        </field>
		<field name="ten_phi" width="250" fieldType="EX">
		  <text v="Tên phí " e="Frr Name"></text>
		</field>
		
		<field name="ma_kh" width="0"  >
          <text v="Hãng tàu/ Đại lý" e="Carrier/ Agent Code"></text>
        </field>
		<field name="ten_kh" width="120" fieldType="EX" >
          <text v="Hãng tàu/ Đại lý" e="Carrier/ Agent Code"></text>
        </field>
		
     
		<field name="ten_noi_di" width="250" fieldType="EX">
		  <text v="Nơi đi " e="Origin Name"></text>
		</field>
		
		<field name="ten_noi_den" width="250" fieldType="EX">
		  <text v="Nơi đến " e="Destination Name"></text>
		</field>		
		<field name="ma_noi_di" width="0" hidden="false">
          <text v="Nơi đi" e="Origin"></text>
        </field>
		<field name="ma_noi_den" width="0" hidden="false">
          <text v="Nơi đến" e="Destination"></text>
        </field>
		
		 <field name="ds_ngay" width="120">
          <text v="Lịch vận chuyển" e="Schedule Days"></text>
         </field>
		<field name="so_ngay_vc" dataType="N" width="120" >
          <text v="Số ngày vc" e="Transit time"></text>
        </field>			
				
		<field name="ma_dk_vc" width="120" >
			<text v="Đi thẳng/Chuyển tải" e="Direct / Transit"></text>
		</field>			
		<field name="tl_ban" dataType="N" width="120" >
          <text v="Lợi nhuận (%)" e="%s Profit "></text>
        </field>		
		<field name="gia_20GP" dataType="N" width="120" >
          <text v="20'GP VND" e="VND Freight"></text>
        </field>	
		<field name="gia_40GP" dataType="N" width="120" >
          <text v="40'GP VND" e="VND Freight"></text>
        </field>
		 <field name="gia_40HQ" dataType="N" width="120" >
          <text v="40'HQ VND" e="VND Freight"></text>
        </field>		
		<field name="gia_45HQ" dataType="N" width="120" >
          <text v="45'HQ VND" e="VND Freight"></text>
        </field>		
		<field name="gia_20RF" dataType="N" width="120" >
          <text v="20'RF VND" e="VND Freight"></text>
        </field>	
		<field name="gia_40RF" dataType="N" width="120" >
          <text v="40'RF VND" e="VND Freight"></text>
        </field>
		<field name="gia_40RQ" dataType="N" width="120" >
          <text v="40'RQ VND" e="VND Freight"></text>
        </field>	
		<field name="gia_45RQ" dataType="N" width="120" >
          <text v="45'RQ VND" e="VND Freight"></text>
        </field>	
		
		<field name="gia_20OT" dataType="N" width="120" >
          <text v="20'OT VND" e="VND Freight"></text>
        </field>		
		<field name="gia_40OT" dataType="N" width="120" >
          <text v="40'OT VND" e="VND Freight"></text>
        </field>
	
		<field name="gia_40HOT" dataType="N" width="120" >
          <text v="40'OT HQ VND" e="VND Freight"></text>
        </field>
		
		<field name="gia_20FL" dataType="N" width="120" >
          <text v="20'FL VND" e="VND Freight"></text>
        </field>
		
		<field name="gia_40FL" dataType="N" width="120" >
          <text v="40'FL VND" e="VND Freight"></text>
        </field>
		
		 <field name="gia_40HFL" dataType="N" width="120" >
          <text v="40'FL HQ VND" e="VND Freight"></text>
        </field>
		
		<field name="gia_20TK" dataType="N" width="120" >
          <text v="20'TK VND" e="VND Freight"></text>
        </field>
		<field name="gia_40TK" dataType="N" width="120" >
          <text v="40'TK VND" e="%s Freight"></text>
        </field>
        <field name="ngay_hl" width="120" >
			<text v="Ngày hiệu lực " e="Effective date"></text>
		</field>
				
		<field name="ngay_hld" width="120" >
			<text v="Hiệu lực đến" e="Expiry date"></text>
		</field>
      </fields>
      <script>
        <query>
          <text>
            <![CDATA[<enc>jlbpi6MyRbJkafr8z+nPQ8jP6JgqwivOc3C0LEk7JnZ4kIus2jVZy1r1GAMaUb9MVijJ4zjRv3kS4P0PMFFloFZsp8Q0gjoes9bsUg/arbtjs9InpWxrew6UiQvxtKSPlIB+w+mEDASXJATwlu5szEhqoWQerzJCCQ/K2/KLufnenBE7lY3oZ9x+D8QwD+TYg7ZCEb0C34EhMuEiUylBoRaJmaGEKsxNAbiRcaTABZpL6/tfMCrKtsiyZv3R+AUT8UcCr1Xg73CeKMuxd3B/+YchpReNI/5GeBL/q/tlv7H15dESx1j09Pt7LdBGik2CdAMq9hDnH76Cr9lVHb5uEgrNDPnkBuVuHvJsVKxNAlJW/+BxIp3hvVFOlu1+Y+NrBvkvR0d5LafQ2gypaaIpi5C8Sb8OgDt3lsS48ofuei9W7awkGby8fZqxHDYgMQj9PYJc3G/ZfM9DrsZ5lofUOtfZCwzp+lYCd2JRrP5rzuMoJGsKnLFzEgviutdNDLCw</enc>]]>
          </text>
        </query>
      </script>

    </grid>
  </grids>
</dir>