<?xml version="1.0" encoding="utf-8"?>

<dir id="vdmnv" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục nhân viên" e="Employee Directory"></title>
  <grids>
    <grid table="vdmnv" fieldKey="username" fieldName="nickname" order="username" allowFilter="true" allowOrder="true" >
      <fields>
        <field name="username" fieldType="PK" width="120" filterType="Code" >
          <text v="Mã nhân viên" e="Employee code"></text>
        </field>
        <field name="nickname" width="250">
          <text v="Tên nhân viên" e="Employee name"></text>
        </field>
		<field name="dien_thoai" width="250">
          <text v="Điện thoại" e="Telephone"></text>
        </field>
      </fields>
	  <script>
        <query>
          <text>
            <![CDATA[<enc>YrwPlWRGirODFAJFLt/u1lz93TfeHg3TQE0vuxwDJDMf5dLSOtk+l1tPmc5rynVNtxxLoZSB4hAl+hAZLaQPSj6wjdiaoYatU9S3dTw3OZFO6waPYLx0TmA07e0xotkoX6HkxO6+A8xPebWjw6gKtPZRNplPLP3Hw8ihCkDuXw4hVi224fG+4q1lYLvogLCpuveo47KoAu234t8clRWn8arpJUrmPXORcbXMzGpZ+5p4GOMLNQHjs/RLdc8VwiTcVrZpiV8/hOFzrSGo/BLEOQIawrte8ipZqtThdq7KcDITPkSJkFGhy7KPwdpNQCS/abg4CLeV9i3ep4iQZwXHE3QrYGYYp1GBFqNGYVz2+Qk=</enc>]]>
          </text>
        </query>
      </script>
    </grid>
  </grids>
</dir>