<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
]>

<dir id="wfdmkh" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh sách cấu hình workflow" e="Workflow Configuration List"></title>

  <grids>
    <grid table="wfdmkh" fieldKey="id" fieldName="ma_wf" order="ngay_ct" allowFilter="true" allowOrder="true">
      <fields>
        <field name="id" dataType="N" fieldType="PK" width="80" format="0" filterType="Code">
          <text v="ID" e="ID"></text>
        </field>
		<field name="ma_wf" width="100" hidden="false" >
          <text v="Mã worfkflow" e="Worfkflow Code"></text>
        </field>
		<field name="ds_ntask" width="250" fieldType="EX">
          <text v="D/s nhóm công việc" e="Explain"></text>
        </field>
        <field name="ngay_ct" width="80" dataType="D">
          <text v="Ngày c/từ" e="Voucher date"></text>
        </field>
        <field name="dien_giai" width="250" >
          <text v="Diễn giải" e="Explain"></text>
        </field>
      </fields>
      <script>
        <query>
          <text>
            <![CDATA[<enc>gP/MVAWmtMV+8cGKxaI6S29ZhIZRkShXS+DdwS1HnlpyDAz1S24G/qStWeQAHRo5Y8kCFtQVl73OPVDzysjl8/06f17hpTYXnsCo3rb2zkDm65qEYMEnfHT620VmGCQaKK+IKiRJApU/7wV9QE28YTZjqnqK+ul8yZ9IoZRdYzTo+XHM6WE6IG/3cBoQHiIzvYzx2P5KVvad6ypnCg61dYRg4idFiI4AkWTp07knghSB9Y9PWBzojqLijjx/Q2JVJ/4AjjNggcLhgy/+8rsDKO1t9yq7yIX6btbrpoOUEm7VekIYJlMWbAcwsQ+Epb3aVVyqNamWG1rfygKqmGOKoGlBakXC++t8c5o+TzyXMVQDsi5JBG6WlBVTRVkCkZ3bKoqc0Fo6ULZwzEQmwnlseQCu9bGH8GDr4ZxmIQylrIrhk4ynr3fCxt4FJ4uAIhjMiiw3Yj8rIlF3as26ik+6R8UAPwTrlEfq85MjqRgwarsvQ0zMdb1gEx3jecHkV3u4</enc>]]>
          </text>
        </query>
      </script>

    </grid>
  </grids>
</dir>