<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="confirmpassword" table="" fieldKey="" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Xác nhận mật khẩu để tiếp tục phiên làm việc (Tên đang nhập: %s)" e="Confirm password (Username: %s)"></title>
  <title0 v="" e=""></title0>
  <title1 v="" e=""></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="old_pass" label="1" field="1" allowBlank="false" >
          <text v="Mật khẩu" e="Password"></text>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>0TpZS6agAs1CCQRkvKa040ibM79oWnPWFeSMTQm2z1JSgy8eyJi4NnVBUJw7JpqOR4kxsRlCspjAZlQFxqwA/ySxegosDoU2Qw670sT47zpwbixaC45U2MvgUfO0pTLSstKE23YGaz6f7M34JXH2FKMuOksSGgjeqwhNmSZNlittcM2G5fVHn33hzQ0R/o21Um7ANbvN3N9Ss3pahGpgZ78/tjMjg+023nh6MwhmrdijM4UnZ4CK4l2SYqp7b+SeNScPzMGcVCAK/7elsJB0eH08zj/pCbfseEFBxxsPQrBhEgIlHG9yO7sS/TT+HnnTwe2BOJ2c6NG8ZKq7dneRpltRv0c+D11vLegicyKUBkvo82q2/R8BRBL+CO605Fq4KXOpCz8vcd5NP1meA9OBN1qmQIYtsGSkK3TJx39RyEhx9M4K6g3F53xnI0nvLNj8PAKe+rLswjv+oU4sxhjbpBMpDto2B02fOrpsTc4Rfs7yCnLt/P8lECA0viiipu27oK/mWhlmnh9NWhrsjMg9ImVB0NABAUnJ0sftBynPJzlR0BSVim3VzsZloPXp2sdR</enc>]]>
    </text>
  </js>
</dir>