<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="dmnh" table="" height="" fieldKey="ma_nh" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục phân nhóm (Lọc)" e="List of customer"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,240,120"  >
      <fields>
        <field name="ma_loai_nh" allowBlank="false" viewType="Lookup" label="1" field="1">
          <text v="Loại nhóm" e=""></text>
          <viewInfo lookupType="One" lookupId="dmloainh" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_loai_nh" lookupExactValue="1"/>
        </field>
        <field name="ten_loai_nh" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>B2lSMSRWTWRugBZLb37auOwiWSE+myiKxqHY/DhH424KmaId3Fk2o6Sf8gIev2vLqOyHWLkD6529TajyPC658zEq4tTYic6YG+avfaA3P7NyjtkcT2VzVhEXvVY11glT7LN9UyfYK46mA5/48ot6Vubq0XnS6tEodEn5fBmTL+DxX0LmRJkSGTpcCiamwpubiE1pDmLlTWThJiJLGoPAqzed9h6I2epwpWjLXpvsS+qSss5sOK9Wqry1jIpBPsN/qGnpSUfMNvGAgGaJ+X/AQYSYfVmr5OA4SrBJQJK/BsYSJ1c6pO0oh2SpiGoamMGC</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>