<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="dmnk" table="" height="" fieldKey="ma_nh" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục quyển chứng từ (Lọc)" e="List of voucher book (Filter)"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,240,120"  >
      <fields>
        <field name="ma_ct" viewType="Lookup" label="1" field="2">
          <text v="Chứng từ" e=""></text>
          <viewInfo lookupType="Multi" lookupId="dmct" lookupKey="status = 1" lookupCheck="1 = 1" />
        </field>
        <field name="username" viewType="Lookup" label="1" field="2">
          <text v="Người sử dụng" e="User"></text>
          <viewInfo lookupType="Multi" lookupId="vsysuserinfo" lookupKey="is_user = 1 and status = 1 and admin = 0" lookupCheck="1=1" lookupInfo="vsysuserinfo|username|nickname" />
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>991dreUclXKCZhE5yCus3X/kA21akm4qmDhYVZ7xQCmq4Y6gk/JEOnHlTSi2MvSRQ2UJLaW1/WX/rD69IxsL+8zPNbmo3DOhGYNwQVowdPuKDgVn29DDPQYJqg3PhrX9Y0NoK78gEfZD0MpRak84ocLq578NVf7nmEDW0uQOGyQfnSkso8B9mYnjmsf/TF0z</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>