<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="messageInput" table="" height="" fieldKey="id" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="" e=""></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="data" label="1" allowBlank="false" rows="1" field="-">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>XP60ZARwmBfV+urg7CpXRy6Rv2Bt9zyeEZrVNOCr113F3QR57RwaxFBj2B4mZgWEjQYDPrHRgOC3CkBiELGJ/TxmwfMny+znFqh7m4qL6LYnUKJrG0yVMsX6GS0Kk0aGim2cuT63eZ/Q6q8gWt7u70KxUBB/lFYFbpXmzSP8FWqYBWr/SVzvOT+SOQsuJcZUFtd8uIakN/EJDSvJXv0vC7i1dEZINQUi9wMSXcb6xHP8LpqwEzlIKICF3YUUr/hlK/5iq4TOdjGZX6twv1iIjHFCYsKx1Lx7u7gUXgBpglaC9pWarbRmPJxrQnKinEvw2sQZIskOWfbX6Oi0b6/Mww6a6pM3bMXqOY4WA9zOqcDREvDXk/0KSi6KIo4+U2bD</enc>]]>
    </text>
  </js>
</dir>