<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="sysunit" table="" fieldKey="name" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Chọn đơn vị cơ sở làm việc" e="Select Current Unit"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,240,120"  >
      <fields>
        <field name="unit_id" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Chọn đơn vị" e="Unit"></text>
          <viewInfo>
            <options cache="false" query="select unit_id, ma_unit + ' - ' + ten_unit from sysunit where unit_id in (select unit_id from dbo.ISWIFTFunctionGetUnitIDRight(@@userId, @@admin, ''))">
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>2sG6gR23p4hSWY2AGe8E4uRLqcfow9sHXBEIaGvxqGjJXGRh1skOKPAOjSkRSbUasusudHE37AqU3ctO4JC1eyz8nksgHqFWPRSsuFAFhscT7TJ8s+gZF4JYf824ua40wuCqCCYb8boE/iermBUq0HQQasLw14GrXevCxqWUqcmODiyQBmI9P+EN923UWhn/C2eehp5cp9b2exBHSnVuS6mdE0WuIMvwpRTmbZwyqw4dA7EP7riek0nnKjy5ZKnWvRgb12cbtyPKrLbUrcTwIDEdx2clM/d1wHzRlVjAcU50hnvbm7CYozQofrjNFIDuALVF1djupSr1lcRIOyI4xuR8biJ/fENGDGE4OziNciLtB/eOGBsboKUODYgPAI3o+SZuXIXP6QfW5R11Zazb0FIyxeK6zhRcO4jOCq5EmjHrJISGEuukuDRzTeGhsrCRAlF5wu2fBVbHkoyqbo8t6SofhBMT4CfTestTlvwSEAjuTrm2Xag+kdSkROE6mluMoYEUqJVF7VrHTfpzZVHyVcWHoWbngnTnF9Ov0CLKT8ecrK2hOuva+go1k6wlmB5R</enc>]]>
    </text>
  </js>

  <script>
    <loading code="1">
      <text>
        <![CDATA[<enc>B6uGb+1ViCnJmhgbJCyuT74UxwvzWxLsDkOqoDVUB+ryXHElVbglF9hF2KwCEeOrPA2q/VZtmRydYFZJV+0rOyrpjvBdk05q+OvcyazpjpCekOVuuAGm4vSbhzJ2UR7CuHIozIR7S7S36HhmhhFY+XtGREsO8CEoPz8WZmb8IiQvh52x8oxFoBGgjkuuyzE0jb/yt9kTZyXgpIfcrn2u7i9FU5XzdysodV/siWaEZvgB+uJuPMt5AsmGQaZRGlzWs4sIwX32Tm3Q8LQ14KK8cg==</enc>]]>
      </text>
    </loading>
  </script>

  <messages>
    <message val="errorSelectUnit">
      <text v="Có lỗi trong quá trình chọn đơn vị, phân quyền có thể đã bị thay đổi hãy trở lại màn hình đăng nhập và đăng nhập lại hệ thống" e=""/>
    </message>
  </messages>
</dir>