<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridReport.xml">
]>

<dir id="bctkttuoi" dirViewType="Grid" dirObjectType="Report" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Báo cáo tồn kho theo tuổi" e="Stock Coverage Report" />
  <subtitle v="Ngày: {ngay_ct1}" e="Date: {ngay_ct1}"></subtitle>
  <grids>
    <grid>
      <fields>
        <field name="ma_vt" width="100">
          <text v="Mã vật tư" e="Item Code"></text>
        </field>
        <field name="ten_vt" width="350">
          <text v="Tên vật tư" e="Item Name"></text>
        </field>
        <field name="dvt" width="80">
          <text v="Đvt" e="UOM"></text>
        </field>
        <field name="so_luong" dataType="N" format="Qty" width="120">
          <text v="Số lượng tồn" e="Closing Q'ty"></text>
        </field>
        <field name="tien_nt" dataType="N" format="Amount" width="120">
          <text v="Giá trị tồn nt" e="FC Closing Amt."></text>
        </field>
        <field name="tien" dataType="N" format="FCAmount" width="120">
          <text v="Giá trị tồn" e="Closing Amt."></text>
        </field>
      </fields>

      &DefaultButton;
    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>Tyue8/hNf0BcXlHHhagXZCnfEE1bYSSXXa9fU8BVk3soO7dbRGPm4a0+aKGVJYW6WqRd+BCmz9Z0Qg9rAJEbpN/fre04AXUZ4mK+VV+TM+v9Ta6npwMDqNTmDqTr3h118Is8Rj+5MuPK/Ku1HhDJG6xcPB4uF7fLPwjgpbYecA6zeW9SIekYrZoJHNnlcrEV4gPUvMawDOwC3NzvJZnouzpIkRHXGhZ10VMy7J5sazVRTgJ3t5v17kfofOaXAkjOHYrbOr3BHQzmV72nb3vPXpIHP7TpP4411c2sbqMoLE5NZmSwhGEaQXWNrLAcIMSyCogfTmbG4m717v1fOaU/XtRGVZDtI6lCma3WPBEOHuM=</enc>]]>
    </text>
  </js>

</dir>