<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridReport.xml">
]>

<dir id="" dirViewType="Grid" dirObjectType="Report" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Báo cáo tồn vật tư" e="Stock" />
  <subtitle v="Đến ngày {ngay_ct1}..." e="Date To {ngay_ct1}..."></subtitle>
  <grids>
    <grid>
      <fields>
	  
        <field name="ma_vt" width="150">
          <text v="Mã vật tư" e="Item Code"></text>
        </field>
        <field name="ten_vt" width="300">
          <text v="Tên vật tư" e="Item Name"></text>
        </field>

        <field name="ton_cuoi" dataType="N" format="Qty" width="100">
          <text v="Tồn cuối" e="Closing Q'ty"></text>
        </field>
        
      </fields>

      &DefaultButton;
    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>P946D2YSQzFiXi7+STAl5CHJZrxPcs565GRcQC9pZ0s83fi9PU/NgjcM0raJN28RhUNXVMcum+u6YY8/Hatee5CK6NxB2wjpt7+2evCR0ntBPa+VVtppOhTctgKAjs2xTHyFQKWu4TjUH2cuC0AyfUhA+vCgd5SuVM6+daJzbfOYUlSLm9m6JOGXeyLAdVlxxsCxVpjuNsAvzHtbe/OvV53nnemsVwcpdtyg9VM5/WPcRDDhqJHa5KrXeXC/jQTOfVTfMDtffIMt7wYYuMjlx0l9Xss9sf8e0hH6H4xa9Uq5GlVngRg0u0lbeQp3qN7CAj/d+X7L4fWNGbwJP9capE1+T4WRMzu63fKU7LagBPc=</enc>]]>
    </text>
  </js>

</dir>