<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridReport.xml">
]>

<dir id="bkctbh" dirViewType="Grid" dirObjectType="Report" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Bảng kê chi tiết hóa đơn bán hàng" e="Detailed list of sales invoices"></title>
  <subtitle v="Từ ngày {ngay_ct1} đến ngày {ngay_ct2}..." e="From {ngay_ct1} To {ngay_ct2}..."></subtitle>
  <grids>
    <grid>
      <fields>
        <field name="ma_unit" width="80" aliasName="d" join="left join sysunit d on a.unit_id = d.unit_id" >
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="ngay_ct" width="100" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
        <field name="so_ct" width="100" link="V" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ma_kh" width="100">
          <text v="Mã khách hàng" e="Customer Code"></text>
        </field>
        <field name="ten_kh" width="250" aliasName="b" join="left join dmkh b on a.ma_kh = b.ma_kh">
          <text v="Tên khách hàng" e="Customer Name"></text>
        </field>
        <field name="dien_giai" width="250">
          <text v="Diễn giải" e="Description"></text>
        </field>
        <field name="ma_vt" width="100">
          <text v="Mã vật tư" e="Item Code"></text>
        </field>
        <field name="ten_vt" width="250" aliasName="c" join="left join dmvt c on a.ma_vt = c.ma_vt">
          <text v="Tên vật tư" e="Item Name"></text>
        </field>
        <field name="dvt" width="50">
          <text v="Đvt" e="UOM"></text>
        </field>
       
		
		 <field name="so_luong_vc" dataType="N" format="Qty" width="100" aliasName="f" join="left join d54 f on a.id = f.id and a.line = f.line">
           <text v="Số lượng vận chuyển" e="Trans Quantity"></text>
        </field>
		
		 <field name="so_luong_hh" dataType="N" format="Qty" width="100" aliasName="f"  >
           <text v="Số lượng hao hụt" e="Quantity of loss"></text>
        </field>
		 <field name="sl_xuat" dataType="N" format="Qty" width="100">
          <text v="Số lượng thực tế" e="Quantity"></text>
        </field>
		
        <field name="gia_nt2" dataType="N" format="FCPrice" width="100">
          <text v="Giá bán nt" e="FC Price"></text>
        </field>
        <field name="tien_nt2" dataType="N" format="FCAmount" width="100">
          <text v="Doanh thu nt" e="FC Turnover"></text>
        </field>
        <field name="thue_nt" dataType="N" format="FCAmount" width="100">
          <text v="Thuế nt" e="FC Tax Amt."></text>
        </field>
        <field name="ck_nt" dataType="N" format="FCAmount" width="100">
          <text v="Chiết khấu nt" e="FC Discount Amt."></text>
        </field>
        <field name="pt_nt" dataType="N" format="FCAmount" width="100">
          <text v="Phải thu nt" e="FC Receivable Amt."></text>
        </field>
        <field name="gia_nt" dataType="N" format="FCPrice" width="100">
          <text v="Giá vốn nt" e="FC Cogs"></text>
        </field>
        <field name="tien_nt_xuat" dataType="N" format="FCAmount" width="100">
          <text v="Tiền vốn nt" e="FC Cogs Amt."></text>
        </field>
        <field name="ma_nt" width="60">
          <text v="Mã nt" e="FC Code"></text>
        </field>
        <field name="ty_gia" dataType="N" format="ExRate" width="100">
          <text v="Tỷ giá" e="Exchange Rate"></text>
        </field>
        <field name="gia2" dataType="N" format="Price" width="100">
          <text v="Giá bán" e="Price"></text>
        </field>
        <field name="tien2" dataType="N" format="Amount" width="100">
          <text v="Doanh thu" e="Turnover"></text>
        </field>
        <field name="thue" dataType="N" format="Amount" width="100">
          <text v="Thuế" e="Tax Amt."></text>
        </field>
        <field name="ck" dataType="N" format="Amount" width="100">
          <text v="Chiết khấu" e="Discount Amt."></text>
        </field>
        <field name="pt" dataType="N" format="Amount" width="100">
          <text v="Phải thu" e="Receivable Amt."></text>
        </field>
        <field name="gia" dataType="N" format="Price" width="0">
          <text v="Giá vốn" e="Cogs"></text>
        </field>
        <field name="tien_xuat" dataType="N" format="Amount" width="0">
          <text v="Tiền vốn" e="Cogs Amt."></text>
        </field>
        <field name="ma_kho" width="0" >
          <text v="Mã kho" e="Site"></text>
        </field>
        <field name="ma_bp" width="0" >
          <text v="Mã bộ phận" e="Department"></text>
        </field>
        <field name="ma_vv" width="0" >
          <text v="Mã vụ việc" e="Job"></text>
        </field>

        <field name="unit_id" dataType="I" hidden="true" width="100" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="id" dataType="I" hidden="true" width="100" >
          <text v="ID" e="ID"></text>
        </field>
		<field name="line" dataType="I" hidden="true" width="100" >
          <text v="Line" e="Line"></text>
        </field>
        <field name="ma_ct" width="100" hidden="true">
          <text v="Mã chứng từ" e="VC Code"></text>
        </field>
      </fields>

      &DefaultButton;
    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>HdmDGG94HYBhyGjL/tgXc9wYLjGZhMis6Z+4UauU5w0H8j2B0fXGkjRjxHOhOYUnDuSWsPKrFdOE2roVBMijXSlavjztC1Vers2WaHcDR5SQs8s8vLXAOuOM/fWTR/Nv0ZQEligzYwQitneMKNtddke5k82Twx4TV/X2fFPXEzUw2FVVzw78XHzOsAHgprzCXFgqaIER/pVGRC2+hsJpU1iimNM/EnZJQJyv40B+tCNQOzHAiz33mbSup7J3rEvTB+ZSUscKsV+o5FrR6IqR2GknjE1j2vFCU4ltetBPpa59cWuH8U9pUihh/hxPwFINQorz+2KT/qVQYwCJsHshYgvacnzmq019B10dtu5x4KvbwZ4OOe9JcaSfPOYWQtNs3saLkuqFEfnk95ekUyULGw==</enc>]]>
    </text>
  </js>
  <script>
    <processing>
      <text>
        <![CDATA[<enc>QHmXXqmGz0knX3SA1x63zK5dSohybJ2JIk46psBsvh2cZUeh1WlKGHMGpf7ZO1dGBf3qw1tIPPOE10kw+gGwmvc0gGkVarUOnY4+Vy00ewN6jMyzNCfdfejinGOBPrSN8Csde/Z/W+HcQo0/td2hd0ZbiBU2ikLe3jkXiNcl1JYgOl144/igmJazB9f0w3y3</enc>]]>
      </text>
    </processing>
  </script>
</dir>