<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridReport.xml">
]>

<dir id="bkhdtl" dirViewType="Grid" dirObjectType="Report" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Bảng kê hàng bán bị trả lại" e="Sales Return Listing"></title>
  <subtitle v="Từ ngày {ngay_ct1} đến ngày {ngay_ct2}..." e="From {ngay_ct1} To {ngay_ct2}..."></subtitle>
  <grids>
    <grid>
      <fields>
        <field name="ma_unit" width="80" aliasName="d" join="left join sysunit d on a.unit_id = d.unit_id" >
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="ngay_ct" width="100" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
        <field name="so_ct" width="100" link="V" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ma_kh" width="100">
          <text v="Mã khách hàng" e="Customer Code"></text>
        </field>
        <field name="ten_kh" width="250" aliasName="b" join="left join dmkh b on a.ma_kh = b.ma_kh">
          <text v="Tên khách hàng" e="Customer Name"></text>
        </field>
        <field name="dien_giai" width="250">
          <text v="Diễn giải" e="Description"></text>
        </field>
        <field name="ma_vt" width="100">
          <text v="Mã vật tư" e="Item Code"></text>
        </field>
        <field name="ten_vt" width="250" aliasName="c" join="left join dmvt c on a.ma_vt = c.ma_vt">
          <text v="Tên vật tư" e="Item Name"></text>
        </field>
        <field name="dvt" width="50">
          <text v="Đvt" e="UOM"></text>
        </field>
        <field name="sl_nhap" dataType="N" format="Qty" width="100">
          <text v="Số lượng" e="Quantity"></text>
        </field>
        <field name="gia_nt2" dataType="N" format="FCPrice" width="100">
          <text v="Giá bán nt" e="FC Price"></text>
        </field>
        <field name="tien_nt2" dataType="N" format="FCAmount" width="100">
          <text v="Trả lại nt" e="FC Return"></text>
        </field>
        <field name="thue_nt" dataType="N" format="FCAmount" width="100">
          <text v="Thuế nt" e="FC Tax Amt."></text>
        </field>
        <field name="pt_nt" dataType="N" format="FCAmount" width="100">
          <text v="Tổng trả lại nt" e=""></text>
        </field>
        <field name="gia_nt" dataType="N" format="FCPrice" width="100">
          <text v="Giá vốn nt" e="FC Cogs"></text>
        </field>
        <field name="tien_nt_nhap" dataType="N" format="FCAmount" width="100">
          <text v="Tiền vốn nt" e="FC Cogs Amt."></text>
        </field>
        <field name="ma_nt" width="60">
          <text v="Mã nt" e="FC Code"></text>
        </field>
        <field name="ty_gia" dataType="N" format="ExRate" width="100">
          <text v="Tỷ giá" e="Exchange Rate"></text>
        </field>
        <field name="gia2" dataType="N" format="Price" width="100">
          <text v="Giá bán" e="Price"></text>
        </field>
        <field name="tien2" dataType="N" format="Amount" width="100">
          <text v="Trả lại" e="Return"></text>
        </field>
        <field name="thue" dataType="N" format="Amount" width="100">
          <text v="Thuế" e="Tax Amt."></text>
        </field>
        <field name="pt" dataType="N" format="Amount" width="100">
          <text v="Tổng trả lại" e=""></text>
        </field>
        <field name="gia" dataType="N" format="Price" width="100">
          <text v="Giá vốn" e="Cogs"></text>
        </field>
        <field name="tien_nhap" dataType="N" format="Amount" width="100">
          <text v="Tiền vốn" e="Cogs Amt."></text>
        </field>
        <field name="ma_kho" width="100" >
          <text v="Mã kho" e="Site"></text>
        </field>
        <field name="ma_bp" width="100" >
          <text v="Mã bộ phận" e="Department"></text>
        </field>
        <field name="ma_vv" width="100" >
          <text v="Mã vụ việc" e="Job"></text>
        </field>

        <field name="unit_id" dataType="I" hidden="true" width="100" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="id" dataType="I" hidden="true" width="100" >
          <text v="ID" e="ID"></text>
        </field>
        <field name="ma_ct" width="100" hidden="true">
          <text v="Mã chứng từ" e="VC Code"></text>
        </field>
      </fields>

      &DefaultButton;
    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>bZe3bI060DUyC3f0wwMmcZsr940+dW+TB4Tbd3mvdBnlpjzOX3JqmvJdIB2inzIOokH5+T79Zk9DYdmsqQbrKRQS94hpXgqWfqYe5aDUIPv3HkO0pHGeDBCwn3KTW3l/6hG+zFqWAG5D//L2gIGiN6BYz0IMxm9YpiqS6j1E1KrNlxTrS/aWLgnDMedDxFGTq3uDETrwpKF3bny8LRZ51bOhYhG1jjZRktUKXouOJKGwus2bX/cpkSKyloK0nUVRnSXvtTjhpYa1CyNalaDcwb+yq3dD5btw3pTEPuIfOBb98SFPzua5vrY10gSYqMBGVurAFgLsjLTUxNkpbQ6TuegZ88/PQ8rq7kMqRID+NHo0jpfZ/y13ls3BvxMF7fXO</enc>]]>
    </text>
  </js>
  <script>
    <processing>
      <text>
        <![CDATA[<enc>QHmXXqmGz0knX3SA1x63zK5dSohybJ2JIk46psBsvh3BArVFSKajD6AlMz7jGSzlxMbjwxY4wC7KYEawiGprpEi+wGC08EOvSMxQghELHjL73nSqs5eGRwzhjH0LTKQhdZOcPxEjrr35ym6BZuMUQwAnEDTn7rvvHwV7bOxUpp3BpggfeeuFLHfmB1V24v0R</enc>]]>
      </text>
    </processing>
  </script>
</dir>