<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridFinding.xml">
]>

<dir id="cngb" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Cập nhật giá bán" e="Sales Price List"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="cngb" fieldKey="ma_vt, ma_nt, dvt, ngay_hl, ma_kh, nh_kh1, nh_kh2, nh_kh3" order="ma_vt, ngay_hl desc, ma_nt" allowFilter="true" allowOrder="true" key="" >
      <fields>
        <field name="ma_vt" fieldType="PK" width="80">
          <text v="Mã vật tư" e="Item Code"></text>
        </field>
        <field name="ten_vt" fieldType="EX" width="250" aliasName="b">
          <text v="Tên vật tư" e="Item Name"></text>
        </field>
        <field name="dvt" fieldType="PK" width="120">
          <text v="Đơn vị tính" e="UOM"></text>
        </field>
        <field name="ngay_hl" fieldType="PK" width="100" dataType="D">
          <text v="Ngày hiệu lực" e="Effective Date"></text>
        </field>
        <field name="ma_kh" width="100" fieldType="PK">
          <text v="Mã khách hàng" e="Customer Code"></text>
        </field>
        <field name="ten_kh" width="250" fieldType="EX" aliasName="c">
          <text v="Tên khách hàng" e="Customer Name"></text>
        </field>

        <field name="gia_nt2" width="120" dataType="N" format="Price">
          <text v="Giá bán" e="Sales Price"></text>
        </field>
        <field name="ma_nt" fieldType="PK" width="100">
          <text v="Ngoại tệ" e="Customer Code"></text>
        </field>
        <field name="nh_kh1" width="100" fieldType="PK">
          <text v="Nhóm khách hàng 1" e="Customer Group 1"></text>
        </field>
        <field name="nh_kh2" width="100" fieldType="PK">
          <text v="Nhóm khách hàng 2" e="Customer Group 2"></text>
        </field>
        <field name="nh_kh3" width="100" fieldType="PK">
          <text v="Nhóm khách hàng 3" e="Customer Group 3"></text>
        </field>
      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>1pYA30de34aQ63VH1qr3ETybpZlzxP70qerwlHXH18Sj+21YVTy3HdKnEpJqvSMQoA0+FuKYkaSGVB/p5tKKUjfNQ8dJaHqn5mnlKXYeigZsBt+dhS/Lcv3inFPi4yJv1R7iybdSPAfN5ALnK45LV+gxqEPc1NIsFjdOac3iO7Fhq8wRsqeQIV+1kOmxCwPXJNx431KN2oNARShf99cYdIoz9aOTNCiXWY+LByBkqTGTPR7Js5Ac8RzOIeJnUeLe</enc>]]>
          </text>
        </query>
      </script>
    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>T5Nuk0XwnW0VlRYHOIM5VXhKO7/eOS+JOgvPzcIet9bgpY9/Z3MMbVYOE+e7KGJFK61ggMSnPLUzk2MC1fWhI9AaGvm/ENI7E/cBiKkWiDZWZRTdAYPFDnye7HgQtxiNWZWs+tKts1Kz6UNwryb5YbmrsrXxj1xRFijhYcfgnJ4szuDL4JXK9ZHamfGjySgQ</enc>]]>
    </text>
  </js>
</dir>