<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridFinding.xml">
]>

<dir id="cnhmnkh" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Cập nhật hạn mức nợ khách hàng" e="Cập nhật hạn mức nợ khách hàng"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit..."></subtitle>
  <grids>
    <grid table="cnhmnkh" fieldKey="ma_kh, ngay_hl" order="ma_kh, ngay_hl" allowFilter="true" allowOrder="true" >
      <fields>
        <field name="ma_kh" width="120" fieldType="PK" >
          <text v="Mã khách hàng" e="Customer Code"></text>
        </field>
        <field name="ten_kh" width="350" fieldType="EX" >
          <text v="Tên khách hàng" e="Customer Name"></text>
        </field>
        <field name="ngay_hl" width="100" dataType="D" fieldType="PK">
          <text v="Từ ngày" e="Từ ngày"></text>
        </field>
        <field name="han_muc_no" dataType="N" format="Amount" width="120">
          <text v="Hạn mức nợ" e="Hạn mức nợ"></text>
        </field>
      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>M38DzFGcb9HJxdKgJBtZ/q5EBQPIiE+2cgNyIMMS4G8zgPwBhlfrmYAyr/i5OAjZl/ELLkG3pFIvAT/1c7N6PIQyfipt4/lsROsh4fZPmD+Us2sHwbEObJp+FXrNaKKz3d7N6EfVLoaT641rojreShjvYYDh4dsO5Q51Lgit6iIvkvLzgA99n0QSoIuxdO1hpW+gT7NyFPkLikYhuq5XMH3E+efzlyaiZEt4qvONmSI=</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>aAwMU71+19kvh8z3NJ7ku39zRXi4uoJx+2ybVU8bBLx/t7KAnnLdlIvSzKAVG4ByIBqTXr5RGuSHktOVZhbdqbANbdfI/XCWA0M6b3WuklKSruVH4XsXl0DnAVSUe8jPLAxH1Y3uV9tGIoGNymNHkXVY/Ka6Z0K/Xy16Wu7i+/dEEa6r+vKQh4OP1U9jiR97t8ahnJvUx0aSNbG9IfZMZCIJjPRTbyCQWhUmri4+5o0=</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>uw3iZoR/y/5o6FF1x5y/2WFA/TQ5b5eUiczZXcfGjRI/BePGRv1cgbwlRt//WplZhubDkJRoqxoZLmzzRfIe3Btf7+m6im40QHrNN67JZpSm8W0pTVmtWZnkZXD7m4ya9ekLDzub7Cf89o4xLbJ5uNDcNgaNlwXkgvV9wOMF7uTY9j3O8VlQthLzvcHFyLh0</enc>]]>
    </text>
  </js>
</dir>