<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmbbct" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục biên bản chứng từ" e="Minutes List"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid id="0" table="dmbbct" fieldKey="ma_bbct" order="ma_bbct" allowFilter="true" allowOrder="true" >
      <fields>
        <field name="ma_bbct" fieldType="PK" width="150">
          <text v="Mã biên bản chứng từ" e="Minutes code"></text>
        </field>
		 <field name="ten_bbct" fieldType="PK" width="250">
          <text v="Tên biên bản chứng từ" e="Minutes name"></text>
        </field>
        <field name="status" width="150">
          <text v="Trạng thái" e="Status"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>gbveqZ921+F0tM5Cn1/sdH/qPjV+tq6XUIE6sG7TV59wPGZy0gDMl/WFN0dlkZVn3xa9puXgvhMdOoX5mQW5QujTfZIgCCrWisB4Vda+N2/6RcEATWclFAzM1XyiFdPQwAMw024Tut77E9JlkjaNv4bEBmJPIcnYFHDS6GjQTAvZlKY0dYy2ywR1OHmvJhZC</enc>]]>
    </text>
  </js>
</dir>