<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmbp" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục bộ phận" e="Department List"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmbp" fieldKey="ma_bp" order="ma_bp" allowFilter="true" allowOrder="true">
      <fields >
        <field name="ma_bp" fieldType="PK" width="120">
          <text v="Mã bộ phận" e="Department Code"></text>
        </field>
        <field name="ten_bp" width="250">
          <text v="Tên bộ phận" e="Description"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>gbveqZ921+F0tM5Cn1/sdPgCLj40uyC5LdytxqF5OvWQ2zbXz9oXaV4K4tkHYo1Nsghorz4J5DqbLth9eCq7Yn0LLU2rBNoXcvMFh8S1H3b37eqUpYK8d0JUHWcDeeGcx2WH119w4YzmvPDZFPBASyuyjKUXP4o0Kiz0anaTQL42Wg9R6UMaPTgrMjY8jaRi</enc>]]>
    </text>
  </js>
</dir>