<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmcang" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục cảng" e="Port List"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmcang" fieldKey="ma_cang" order="ma_cang" allowFilter="true" allowOrder="true">
      <fields >
        <field name="ma_cang" fieldType="PK" width="120">
          <text v="Mã cảng" e="Port Code"></text>
        </field>
        <field name="ten_cang" width="200">
          <text v="Tên cảng" e="Port Name"></text>
        </field>
		<field name="dia_chi" fieldType="PK" width="300" link="1">
          <text v="Địa chỉ" e="Address"></text>
        </field>
        <field name="dien_thoai" width="120">
          <text v="Điện thoại" e="Phone"></text>
        </field>
        <field name="ma_qg" width="120">
          <text v="Mã quốc gia" e="Country code"></text>
        </field>
		<field name="ma_kv" width="120">
          <text v="Mã khu vực" e="Area code"></text>
        </field>
		<field name="tdx" width="120">
          <text v="Kinh độ" e="Longitude"></text>
        </field>
		<field name="tdy" width="120">
          <text v="Vĩ độ" e="Latitude"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>K8JPsPQtkuBwkJkHk8HQW7iy1GGQAzVxXzHmdZuE7BQ8gEjeFcyCbccPW7m6Hj5UPQbzcWCMNZNmWly/g4MbNizLMzl4O+2koeNTiTv99BYRIMlLbgLHzN29MrNWMqFnB0gZKr27I4jXcjiCnnNyXIObXkxIjfIAro/992DfLd8UPIjaofgs0Y6vT1wtlzPC</enc>]]>
    </text>
  </js>
</dir>