<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmchungtu" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục chứng từ" e="Vocher list"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmchungtu" fieldKey="ma_ct" order="ma_ct" allowFilter="true" allowOrder="true">
      <fields >
        <field name="ma_ct" fieldType="PK" width="150">
          <text v="Mã chứng từ" e="Vocher code"></text>
        </field>
        <field name="ten_ct" width="250">
          <text v="Tên chứng từ" e="Vocher name"></text>
        </field>
		<field name="status" width="150">
          <text v="Trạng thái" e="Status"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>Xm0SQO244yhm4oovG3IvuGWZVkwdldFFDmpUmMtuEWJn10W8OJ7XmeZkKpQiBENXLC8AJWl4vSidJB1NbeONv/Uz4SHyTv3HonMY23j6kDX6Ze6mW99F4pcJWaAHuJKqgCnJ3lQQqbxUWi2uNHaeqRdh8q95iqfNi5piRqJrd4c7g9J2XJKz6niWWKkH3kDJ</enc>]]>
    </text>
  </js>
</dir>