<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmcong" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục công/thùng hàng" e="Container List"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmcong" fieldKey="ma_cong" order="ma_cong" allowFilter="true" allowOrder="true">
      <fields >
        <field name="ma_cong" fieldType="PK" width="150">
          <text v="Mã container" e="Container Code"></text>
        </field>
        <field name="ten_cong" width="250">
          <text v="Tên container" e="Container Name"></text>
        </field>
        <field name="ma_loai" width="250">
          <text v="Mã loại" e="Type Code"></text>
        </field>
		<field name="status" width="150">
          <text v="Trạng thái" e="Status"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>/P9Shux7F0Mmh7E260+hpeIndoKqOKjCh8sJF0PvOM7qInDmHNkB1fKOQ7v2FUd/qefLLTpBuUPv1JVvYmFYh+HQXDirXQ7H/2GbND3+NMxn2SoGjox7gryGDVy+WJYCJuzqGK9rUApNfnWhlBdp3PKs9E/jZFfsp+JUuBh3wib2hQniund/1NWsWATB9CBJ</enc>]]>
    </text>
  </js>
</dir>