<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="vdmdvvt" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục đơn vị hàng" e="Trans/Site List"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, edit, delete..."></subtitle>
  <grids>
    <grid table="vdmdvvt" fieldKey="ma_dvvt" order="ma_dvvt" allowFilter="true" allowOrder="true">
      <fields >
        <field name="ma_unit" width="120">
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="ma_dvvt" fieldType="PK" width="120">
          <text v="Mã đơn vị" e="Code"></text>
        </field>
        <field name="ten_dvvt" width="250">
          <text v="Tên đơn vị" e="Description"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>dWARx5oyNggjYSWXeJWjdsIlMKAFYcvEfOd1/bvapZNszbQ79nRkGq8oUl0livgDeyyj8JlDSQkX/KujiMmQC6JRVo2iI8P/2B514mc1imqR0yM8vTLgXVv9Gffaab9A+vq2dDw8TpFaLRVNLRnXdSPzy0y3WkirZIdTscx1HYoXBOJOa5UUicKmtvEEvmX6</enc>]]>
    </text>
  </js>
</dir>