<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmdvt" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục đơn vị tính" e="UOM"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmdvt" fieldKey="dvt" order="dvt" allowFilter="true" allowOrder="true" >
      <fields >
        <field name="dvt" fieldType="PK" width="120">
          <text v="Đơn vị tính" e="UOM"></text>
        </field>
        <field name="ten_dvt" width="250">
          <text v="Diễn giải" e="Description"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>gbveqZ921+F0tM5Cn1/sdH/qPjV+tq6XUIE6sG7TV5+veW1fZmr2crX8P7xVQeH2113nKH2HKka4wUluhtcf7kzinGo/nbq+uOwc963poxUXYvGow1GJwJTWNXVtKWXc+4sAaeEJQ+WIZawSLuJqWxzzPHsfpmHS7SG1tNO4JK+i4S8/LAHo8NmsIKF/pYlS</enc>]]>
    </text>
  </js>
</dir>