<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmkhuvuc" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục khu vực" e="Area Directory"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmkhuvuc" fieldKey="ma_kv" order="ma_kv" allowFilter="true" allowOrder="true">
      <fields >
        <field name="ma_kv" fieldType="PK" width="120">
          <text v="Mã khu vực" e="Area code"></text>
        </field>
        <field name="ten_kv" width="250">
          <text v="Tên khu vực" e="Area name"></text>
        </field>
		 <field name="status" width="150">
          <text v="Trạng thái" e="Status"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>Xm0SQO244yhm4oovG3IvuLeLIyJNX4Y9n7qfFwoZpqyMIngva0lpOEjJsvVzu/J+kuBUnccGI1khu9dqIuAoLLknn8fZcDR/intBR8Vyi8nc3IrfNKXXyGmQBpZNY+gQbvdjFQebmY8QgeY87fx0RaLt6syN520Ph+VkpY9P94D6jk/3JXNtkSgW3I7QWBOH</enc>]]>
    </text>
  </js>
</dir>