<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmkien" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục Kiện" e="List of packages"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid id="0" table="dmkien" fieldKey="ma_kien" order="ma_kien" allowFilter="true" allowOrder="true" >
      <fields>
        <field name="ma_kien" fieldType="PK" width="150">
          <text v="Mã Kiện" e="Package Code"></text>
        </field>
		 <field name="ten_kien" fieldType="PK" width="250">
          <text v="Tên Kiện" e="Package name"></text>
        </field>
        <field name="status" width="150">
          <text v="Trạng thái" e="Status"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>8wsLme4If9rNawhEvon3/dzPlZUCxUOfYR4D+nDUyIntWWjAguor0lVSH/0/+eOtlG+xvK18EYezXgLUYGdK9qwqRRDvOdOZXgDwQou0gBvlbz7CIzUtn8dkKA+5Jjeh9d9R+x4YxoEYs1JzT8H8qQCXbO1qHp1E8PMOdlKRLY64kJaYsChQr9tygR2kvmUa</enc>]]>
    </text>
  </js>
</dir>