<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="vdmlo" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục lô" e="Lot Maintenance"></title>
  <subtitle v="Cập nhật lô: thêm, sửa, xóa..." e="Add, Edit, Delete Lot..."></subtitle>
  <grids>
    <grid table="vdmlo" fieldKey="ma_vt, ma_lo" order="ma_vt, ma_lo" allowFilter="true" allowOrder="true">
      <fields>
        <field name="ma_vt" fieldType="PK" width="100">
          <text v="Mã vật tư" e="Item"></text>
        </field>
        <field name="ten_vt" width="300">
          <text v="Tên vật tư" e="Item Name"></text>
        </field>
        <field name="ma_lo" fieldType="PK" width="100">
          <text v="Mã lô" e="Lot"></text>
        </field>
        <field name="ten_lo" width="300">
          <text v="Tên lô" e="Description"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>uw3iZoR/y/5o6FF1x5y/2R+LYPQPUfZfUjuTB2vd6jq4HLf0X4Zl2SpWy76mC8rM2LiBvjKyfftgGPv2I3ubAuggeCUNXNS2/yqC4ccX/WlRH1wkoyy4VRZ/MFfpoQoPO/2kBs5ydF5ubAcXKjZB9qc0KfIQmAQSrGRPAoSQOC57ty2wfFqAnI3EEqfG+5MA</enc>]]>
    </text>
  </js>
</dir>