<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmloaicong" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục loại container" e="Container Type List"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmloaicong" fieldKey="ma_loai" order="ma_loai" allowFilter="true" allowOrder="true">
      <fields >
        <field name="ma_loai" fieldType="PK" width="150">
          <text v="Mã loại container" e="Container Type Code"></text>
        </field>
        <field name="ten_loai" width="250">
          <text v="Tên loại container" e="Container Type Name"></text>
        </field>
		<field name="status" width="150">
          <text v="Trạng thái" e="Status"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>He0/7dHkFsicFOIBGo9frM1EjsE4VueihqPyqnyHA+lMV9YjzIzM73dhK/Ss1l0BOxfKKF1TzyaJ32R52tg8nmBPQ+2Xb58sZVtEjbfujDwT3VWmXgmyjf14Zgrj8svcGA3X+o5w8ufpKY7Pu8q3s4EmiPHUcoOpLNKsSjDbOjMDdZJuWvPY1mWhetpyrZx6</enc>]]>
    </text>
  </js>
</dir>