<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmphi" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục phí" e="Fee List"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid id="0" table="dmphi" fieldKey="ma_phi" order="ma_phi" allowFilter="true" allowOrder="true" >
      <fields>
        <field name="ma_phi" fieldType="PK" width="120">
          <text v="Mã phí" e="Fee code"></text>
        </field>
        <field name="ten_phi" width="250">
          <text v="Tên phí" e="Fee name"></text>
        </field>
		<field name="ten_phi2" width="250">
          <text v="Tên tiếng Anh" e="English name"></text>
        </field>	
		<field name="ma_dvt" width="150">
          <text v="Đơn vị tính" e="Unit"></text>
        </field>
		<field name="nhom_bg1" width="80">
          <text v="Nhóm 1" e="Group 1"></text>
        </field>
		<field name="nhom_bg2" width="80">
          <text v="Nhóm 2" e="Group 2"></text>
        </field>
		<field name="nhom_bg3" width="80">
          <text v="Nhóm 3" e="Group 3"></text>
        </field>
		
      </fields>

      &DefaultButton;
	   <script>
        <query>
          <text>
          <![CDATA[<enc>g+KZ+QKBlC+LdD0jHhpbmYRKK+4Gijkh7WSpwhJe5w68bfA8v5nE+mNwoDST4awPHaF0j7jIOEJEQaA3z3pN1XiBxNRIC98oql6MEWKdj+r5OJPZr+UeE4BK02dzqkqZbsUNj6akiHJjEp2ZN2G8kC0Pr/rkf6m8ivalEBBKpNGqppv9BAzFtDfFy44RQEyq</enc>]]>
          </text>
        </query>
      </script>
    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>PoZY7gtiqLjMyWhzpqyQdvSGdh5tAfOCM9/yuCKZRUELJBScDb32ONKU1Un/uF9Kf6/p2Mx31lWpJDC6UFlax/yThMLqCMM6j7RGun0j3leR6v/9SSQjVEIOcw6cGBwpVP3GzfibfKdN1TVa22ttMAwgNpkG0LDpBcx/S6WWytStWERoaUOfxJ3DWTTUujk0</enc>]]>
    </text>
  </js>
</dir>