<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmtg" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Tỷ giá quy đổi ngoại tệ" e="Exchange Rate List"></title>
  <subtitle v="Cập nhật tỷ giá..." e="Add, Edit, Delete Exchange Rate..."></subtitle>
  <grids>
    <grid table="dmtg" fieldKey="ma_nt,ngay_hl" order="ma_nt" allowFilter="true" allowOrder="true" >
      <fields >
        <field name="ma_nt" fieldType="PK" width="120" >
          <text v="Mã ngoại tệ" e="Currency Code"></text>
        </field>
        <field name="ten_nt" width="250" fieldType="EX"  aliasName="b">
          <text v="Tên ngoại tệ" e="Currency Name"></text>
        </field>
        <field name="ngay_hl" fieldType="PK" width="100" dataType="D">
          <text v="Ngày" e="Date"></text>
        </field>
        <field name="ty_gia" dataType="N" format="ExRate" width="100">
          <text v="Tỷ giá" e="Exchange Rate"></text>
        </field>
      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>jfWY55PlsFb3adF5OHRtDJ/5QTFeH65q9OWJgo5J4yoCwuKIbTGUoCdaEDEHcL+9qwR1TsOs72ipbz9CBSi3XZih1atza1irv4Ait0Qeaz8EHaDTH6pjE4tBUYvkB9BJjrP+59P/YxukOTo/o1qI2pn/n1L/Kc2fs4cxLywd4aSl1hxqpbz/n1SA9rgf7+UnwqXCvo32bH2+09DLTHPLi8xH9uTKk9EL31Lby7hwsPF/v2iWBGz8TTVMbTsfWwl+</enc>]]>
          </text>
        </query>
      </script>
    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>gbveqZ921+F0tM5Cn1/sdIIjvYrrrcr5tN3rExNVy2OQwPSWaD5Ok0OM7CzXHW9nGupUFwmrgvyQOjhYac9B4dna99KUSZSfnxf2sNn0WNjessDeljnwc2r7teQR3Os0+gM78h1Sg+nNaRF7bYvCYg2aaDLQARpwGewF1shNoBRIiw1zvL3Kn6/JCXuFctxL</enc>]]>
    </text>
  </js>
</dir>