<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="m48" dirViewType="Grid" dirObjectType="Voucher" voucherCode="CT0" xmlns="urn:schemas-iswift:struct-dir">
  <title v="phiếu chi tiền" e="Cash Receipt"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>

  <grids>
    <grid table="m48" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true" key = " ma_ngv =1">
      <fields>
        <field name="so_ct" width="100" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="100" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
        <field name="ma_ngv" viewType="Combobox" valueDefault="" width="140" >
          <text v="Loại phiếu chi" e="Voucher Type"></text>
          <viewInfo>
            <options query="select ma_ngv, ten_ngv%l from dmngv where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="ma_nt" width="100" >
          <text v="Mã ngoại tệ" e="Currency Code"></text>
        </field>
        <field name="dien_giai" width="250">
          <text v="Diễn giải" e="Pay for"></text>
        </field>
        <field name="t_tien_nt" dataType="N" format="FCAmount" width="100">
          <text v="Tổng tiền" e="Total Amount"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="80" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="80" fieldType="EX" >
          <text v="Đơn vị" e="Customer Name"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>vGhhx6UX2ukHmYI+roecmvkpcTu8WyDAXe6ey467lIg6chdIUIOsI8/uFwdjW6lEYL4Nl0UHv9BLLoa3uyQ7iAglYvuUBWGVpB0GkfINeBKe5cGRPG2U/hTi3/ta81n+XS2Yr9q1aGSBLkpmxmTA51q+tCju9izTlNFf+xz51oP7FCdpyJ82OyVtECyZEEKnKeVnqWcR1BYMOgNHD6ZwQCC/ODm8eGG9Scx1xmsGp1s=</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>Xi9ks7k/W+jttFV06t2QjAwa0kVt7mF97MX3V9RCZOlUNr/y9C5e9rdzNrajkdpx/JMJm7fQQVvy53G9LiXaO8oqrV1E4FJwgRSMRo/KzXdGqzC98HJFZIyjtky6hJR43lRiv/9N8074M3gwJikt1/ZBUhCss9OX8BHD09PhmfexILUObLW4OEYW3zn5r4g/i2JOC8SO2blFFoJx3FYBcPN1N7kFRn//LoYewhClmIfXT3Dptu1ZTlxxzYsMPDoxbtLXiVqChab0orR0XgPzMiVpBV4MINlJTYVu/Y6kPL5nlZ3bU2L6jUoMkirOKsf//YRpjYTRjJBlsgW/BnL0ZyHnGtVsfeZzhIP3Gh5Ixk6hCKBlZ9PQjcmeNsvsOVpIVUj0EgfC+snGQW858unuq6wxvJ3poou11b3kr7dfEEBGxKhb/Jnphp2GIrg78iywRGmPi2WK9CqF0Pbt53fGbGK6IgOVxS2deCQnI7/+tUG+cWMKRELbAdqzqiX9JHPg6VKV5kZpHA4BKooVyYsI6YVu+FJBIo8ggzG3y5AAXiKn655QgKFGW4G4yclpF4OV</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>XymOY7dD2w2+zQLbB/WOXG1d5GPL5AAFi2GKmZZrxlK1UV20S6f0Zk+MSm/mKpSaQVElNOzzSqzuX4GCKEE81kI8mUW0WHM+cKXoVqs7XTNbayDmAGDhz1PGSvEo943L8E6OZur0GGBZ5q3+6v13l3TZKhISgi4DICfx1wWfeyriHajaVQs7X0/3SNcXNC+c</enc>]]>
    </text>
  </js>

  <script>
    &VoucherJSLoading;
  </script>

  <messages>
    <message val="DaPhanBo">
      <text v="Đã phân bổ phiếu chi này, không được sửa/xóa" e=""/>
    </message>
  </messages>
</dir>