<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="m49" dirViewType="Grid" dirObjectType="Voucher" voucherCode="CN0" xmlns="urn:schemas-iswift:struct-dir">
  <title v="phiếu chi tiền" e="Cash Receipt"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>

  <grids>
    <grid table="m49" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true" key = " ma_ngv =2">
      <fields>
        <field name="so_ct" width="100" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="100" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
        <field name="ma_ngv" viewType="Combobox" valueDefault="" width="140" >
          <text v="Loại phiếu chi" e="Voucher Type"></text>
          <viewInfo>
            <options query="select ma_ngv, ten_ngv%l from dmngv where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="ma_nt" width="100" >
          <text v="Mã ngoại tệ" e="Currency Code"></text>
        </field>
        <field name="dien_giai" width="250">
          <text v="Diễn giải" e="Pay for"></text>
        </field>
        <field name="t_tien_nt" dataType="N" format="FCAmount" width="100">
          <text v="Tổng tiền" e="Total Amount"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="80" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="80" fieldType="EX" >
          <text v="Đơn vị" e="Customer Name"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>vGhhx6UX2ukHmYI+roecmvkpcTu8WyDAXe6ey467lIg6chdIUIOsI8/uFwdjW6lE0GV9flyJ8moi7Vn0Aec33wVjkXJ1M5gm9Xo4tvXMHT01ZBVBvdwnCk6xGtJvaqYILCfqEKh819ZkSc2FZwY3Pmdn1Ev1vhXQjxYlkhDcFHeF5ddUGhSkZL/VlpYc/zSeENGIigmZZV7/iZGlamDD7AVjMr/rBO8k8jEpMwl5uqY=</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>Xi9ks7k/W+jttFV06t2QjLreJvl1khJO+AVtgbxErc/qURmI2lWjEJdHv2RGNLRHtGzTKBk1LdEZC133gA/vwOwjQW4BVcWyFsDcW9VEdRG1NYTuMaEjQg1M7J/LiDhTKE1RqMmpQVknxsbDpgtIuOP23+Bd14ljRTf7+1QYoJ5U5kTgXbnucBpQ2JBJnEZMKgH9r8M+Snd5JalGxvJgRoW8N5+WxuZUUjVTS2gkG2NLI8DGBdFrWcmtGuWxJ4pMBkZ79shQ2H3K4+WOmExrXGk7M8dKjlblHt+qNnFdG+/shpQLbMiRiwNBVl0/GY6lgR284kqhedoDXqV2V/vd6kRaHnaqTXFQqebV8X3irvfvG3xlCJuDNqPwEqwQRzbX56q638qul/kV8MoPJKWCCIGymsxs7fiXPOs3T+OmMufEQvLoXC8MfMDYY03SEAO72hHcESisGIVelwZPrMm9Yp8f6ZhFziLJlfOG/Q9DAy5zYpLg4Syxqf2A4vG9z3W9kmki9qxXdIeT/0UBXEbrbRnM4DOSGXzEfrss93nwV269CyZsJ2ikF2czZ6ixdF2C</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>hLiBLm3iF/aJj7eF2MoRKrJnsX0IcP5ZDiQEBFUDAJY/h+55TkmURHUlUNmMzBio+wbXGFUQ0CSEXJwkxuz/rpktbaeQtpBDN1QATftdECBwxSD7S8x3Y87gGsaCrulPu1s3LJz19kjNrlr8356Lc3UQtnTYio1CTo8Qf6Etpqi9kB4fBwiXBbG0oqqHxNoC</enc>]]>
    </text>
  </js>

  <script>
    &VoucherJSLoading;
  </script>

  <messages>
    <message val="DaPhanBo">
      <text v="Đã phân bổ phiếu chi này, không được sửa/xóa" e=""/>
    </message>
  </messages>
</dir>