<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="m51" dirViewType="Grid" dirObjectType="Voucher" voucherCode="BG1" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Báo giá" e="Quotation Entry"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>

  <grids>
    <grid table="m51" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true">
      <fields>
        <field name="so_ct" width="100" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="100" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
        <field name="ma_kh" width="120" >
          <text v="Mã khách hàng" e="Customer Code"></text>
        </field>
        <field name="ten_kh" width="250" fieldType="EX" >
          <text v="Tên khách hàng" e="Customer Name"></text>
        </field>
        <field name="ma_nt" width="80" >
          <text v="Ngoại tệ" e="FC"></text>
        </field>
        <field name="t_tt_nt" dataType="N" format="FCAmount" width="100">
          <text v="Tổng tiền" e="Pcs UOM"></text>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="80" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="80" fieldType="EX" >
          <text v="Đơn vị" e="Customer Name"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>ut7bmtX51o7ohlkZy11sVIaZnUwHEM+ebZUTVuvKujT003xHFhXk+bfhdo+bOLeOc6q63u3F2aexGLbLnl1qTTXhLrNlXeSxVkMrIqXqOIV0K//tFN5voZDEwxmggErUPzh+qFPUrUMIk3h+Ki6PotHKs2S1UZVa98zmFp4o9+J+uINWCG/0sLwuHcsDKIU19OP6Sc81dVTM/vl6dUUBlcpGftcyDenTxwFE2b469gB46nBpzJU1ETEPwEwoY+NGyJC2fwU1SXrO9LnA5xSiMg==</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>fLvsT8g+OP5RgvwdX+lih0FXcPJk9/hrbKBNuhxvJ+NNj2oFswGDO0zUpDdUskx6CFCvTcoo47NpTnuVappMlzLNSS+G5CjqKwzo9u3zqesauPDa0gWHUf2JQk7uLrfTgB1NzRq7N91TfgSaVof7X2WVlllyFF7iI27/v2JxcBgCp3ama+5Fh9+/Be1iFMvoZhseJn+sGSK3qiulnCQOU3QyXciDxk3yqHJvGWDXR4HfZhFp/tb/NTgeH608VyMF07tSTOopgYbCnKR8gFDdBatgRm+TGaExp7R0zhVwWsSe3CAPnnvuCgljmJu1pmBeKaccYdtbU14dwOswL+2KLqvA2c4NY3At69b4jkZgT0KnfCqmd4o+qj3lwJLoje78Np1hIBrBUfMuqBVcsYT/s0yUjoj/LNbarhInkUoIE+7Vd4Je9661rltTBIctxENuciDv5NqXGY83nO4JB0ViCEnh7ysXLbMaqqzsPDCl4uZITNZZD3o5LdUgKvyHTz/tDznzIbwlQH/jzIt4neAewXuonZNfETg/jIYX3Vr08EhbE1+KyXhEarWkiSPpvMolIyutI8GMidc03s1pi4MRdThpAPM1vymRjAG4jmUHKbMenM+elGP1g1/D9WGBaQbp</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>XymOY7dD2w2+zQLbB/WOXIs0x0vAWTZgKQme4ELWLX988ok5qBKEkspwwMIIgygSXrPPcjefqBL63M63AIBmbJWEvDR6Asy2eAzvRaaab3Jj2+8AZLNg+b9afyAJlgIPSKWE/15Rv8I6vVwZbqB1sZYxXUiPiVNcWdmRHsvwhaQDpg3uVAFOokMh5NrMjqyF</enc>]]>
    </text>
  </js>

  <script>
    &VoucherJSLoading;
  </script>
</dir>