<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="m54" dirViewType="Grid" dirObjectType="Voucher" voucherCode="PX3" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Hóa đơn bán hàng" e="Sales Invoice"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>

  <grids>
    <grid table="m54" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true">
      <fields>
        <field name="so_ct" width="100" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="100" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
        <field name="ma_ngv" viewType="Combobox" width="100" >
          <text v="Loại hóa đơn" e="Inv. Type"></text>
          <viewInfo>
            <options query="select ma_ngv, ten_ngv%l from dmngv where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="ma_kh" width="120" >
          <text v="Mã khách hàng" e="Customer Code"></text>
        </field>
        <field name="ten_kh" width="250" fieldType="EX" >
          <text v="Tên khách hàng" e="Customer Name"></text>
        </field>
		<field name="dien_thoai" width="120" fieldType="EX" >
          <text v="Điện thoại" e="Tel"></text>
        </field>
        <field name="ma_nt" width="80" >
          <text v="Ngoại tệ" e="FC"></text>
        </field>
		<field name="t_so_luong" dataType="N" format="Qty" width="100">
          <text v="Tổng số lượng" e="Total Quanlity"></text>
        </field>
        <field name="t_tt_nt" dataType="N" format="FCAmount" width="100">
          <text v="Tổng tiền" e="Pcs UOM"></text>
        </field>
		 <field name="t_phi" dataType="N" format="CostAmount" width="100">
          <text v="Tổng phí" e="Pcs UOM"></text>
        </field>
		<field name="t_tt" dataType="N" format="CostAmount" width="100">
          <text v="Tổng cộng" e="Total"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="80" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="80" fieldType="EX" >
          <text v="Đơn vị" e="Customer Name"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>ut7bmtX51o7ohlkZy11sVOLa5Jhz2RDkKOEXar2fa7ZrRChgEQ8Al6jIu/IL/Y78hfUAw8KYrELQpHuehIbDA+e8AEOwIHjLApb2mvWnC0RgfiYW6SHiDNnphlX8rgqx81ffrhqgz8ZfW17EUUhto6Nu0grK+7s+eWQy1QX9pSOlQzvNbyPVNa4WouQZ1SH9fhgyt3SDiLHUsNLApDR9mb8YiIDVJt4G8PmZZ23HEvwqHf9GkyulpMsbTmG89NJejR1N83Smi8tHVSx8mu6xtg==</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>fLvsT8g+OP5RgvwdX+lih4oE1J1Frc1sQXXEkZ4RU0MQHk+V3SG1aoThjHjwL2aMGmaBSpvOOnbrDflY3PcgOjeCAbZa5GxThw9mbI9at2OzKiEJR3Vi5pHhqWtsVT902vyXElJM+hkAVFliQ6erBSwd4StLfz+nqbxCArD7Uokw9zFhJZgVGJ8HtQJkXbPtgAnKrqsWNjOKWkpgO3Os79xZHo/agcTM0FPyfn+J6gB38Xh+cxuw2F/nBTS7enjacn/2ZypXswAtygxVrKKmmDDI7ti+BxKHgQVaBMB6mH9VZCRadWrhu4rh+767IMIxLfLYidyoLy5A0nddUkNjDRA45umJ+EUymOXTsxxLdEpx63Od9BQ+W5KNGNNE/uKKhZLV2+Dts8/CuW13f6bVEZPkw1iFHGxlmTO0at6EpBL5TEiLfwuinhmuY2NWQUhl1dxCYQJEybsSCUecLPGd61Wp1uvMev9lOschJ+hvKveD/Ih13tDgRJQkF02cy/IivGsLrP6fhiezgpVkMpp8+rWluSiZtSPgm3pcrn8LUhlgkESqc8256b3Zaj32CzETjkbV4ZeXaGTlawo7aT3AniDI2RFMA+0Ny+sOnjEysO/pUdv4D3phET4wwBNKbNBPdmlN5I6ef4gUjUGYN7nBAQ==</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>hLiBLm3iF/aJj7eF2MoRKkVrUDZares+TCtMAvrDcy+DR6gzQww2/A93NXL1SDstz8B956IkQjCFpww+gt+mquRiZflgRnpYt+pKTQJv+3BTOnRC7vZn53yAMkUIDVFZus75Q11IqLMSyrl8vr/bSqcFAzoOf5ui/U+R17zDXv1wlnrf0/LnLhxWzDerKIIX</enc>]]>
    </text>
  </js>

  <script>
    &VoucherJSLoading;
  </script>

  <messages>
    <message val="DaThanhToan">
      <text v="Đã có chứng từ thanh toán cho hóa đơn này, không được sửa/xóa." e=""/>
    </message>
    <message val="DaTraLai">
      <text v="Đã có chứng từ trả lại cho hóa đơn này, không được sửa/xóa." e=""/>
    </message>
  </messages>
</dir>