<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="m57" dirViewType="Grid" dirObjectType="Voucher" voucherCode="GH1" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Phiếu giao hàng" e="Delivery Note"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>

  <grids>
    <grid table="m57" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true">
      <fields>
        <field name="so_ct" width="100" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="100" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>

        <field name="ma_kh" width="120" >
          <text v="Mã khách hàng" e="Customer Code"></text>
        </field>
        <field name="ten_kh" width="250" fieldType="EX" >
          <text v="Tên khách hàng" e="Customer Name"></text>
        </field>
        <field name="dien_giai" width="350">
          <text v="Diễn giải" e="Descriptions"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="80" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="80" fieldType="EX" >
          <text v="Đơn vị" e="Customer Name"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>ut7bmtX51o7ohlkZy11sVIaZnUwHEM+ebZUTVuvKujT003xHFhXk+bfhdo+bOLeOc6q63u3F2aexGLbLnl1qTTXhLrNlXeSxVkMrIqXqOIV0K//tFN5voZDEwxmggErUPzh+qFPUrUMIk3h+Ki6PotHKs2S1UZVa98zmFp4o9+J+uINWCG/0sLwuHcsDKIU19OP6Sc81dVTM/vl6dUUBlcpGftcyDenTxwFE2b469gB46nBpzJU1ETEPwEwoY+NGyJC2fwU1SXrO9LnA5xSiMg==</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>fLvsT8g+OP5RgvwdX+lih9Kb9AciKyAnxxO1UtaWHpOO4pPksduPOxHlh64dj5cd4Mh3/vNLShO3wd9aOTM5BgzblSVlG9Kbr+DcKU83OOCAxG4rq7BtIv0skU1UbzzZdag3wn/NL0HMhrDUljpG/mi3FIXz14WXam/hxM+G4vQ7BCsOXJD/ediMSK2TNBPI/tivLcHDXGLhyICXDcto+Nt3+JwMH3ttXi3x1EFM5HV7WjDCstJOa68opZ71Kup4WB9hi4i6nWPzchnsMFKa4K6rEaIeauTzRqs1j4Yb9+XCXLWsPHVlSqbAVNkMXpCcBA3/ys5jmtyQsIXlYljMP3SGqqg7NWkzBSmgGrp/GmaRoTE+mK1B13gq0MdPIb4qB4QJRTChcEQrymZQoEDlAF/AcRLaVTOzGdgysogUk7nEGs0vdd9N0o/b9Fqb8dO4EItIAP0whO5yhr6VV1WPoMmWXSY9okWTYe8SJNXMTEtE6tCjjifiqFifSzHxyILPiBtfRjmfNvqvzGfJBLF7rSftCqb3i70vk7bEMYVtb4glqbJXclKBk2MaB7qTCQI8wNo7i1rv4b5r4kc8fbgQS6pukWKVG9N2iQb9jr3XPjFI53GJxY+ZXibdFiMw92VkT+Gcm5QQu68vFEFXyRMcQw==</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>hLiBLm3iF/aJj7eF2MoRKvHqPUsAXb8t+ZMVc5QCTJ0F7sInbLTRshNVSolBJqhcuhr/MpxSBkN7nbsKmE7o1uEB/lKBif/V0UH/rf8ViSiaUyOHv/IF3svT6kqzLDbMWGJu2cQwyk8S1jktufffm3n52tLBddXWef3palDCNZfotgKKjMY8pMHFa87tyzk6</enc>]]>
    </text>
  </js>

  <script>
    &VoucherJSLoading;
  </script>
</dir>