<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="m58" dirViewType="Grid" dirObjectType="Voucher" voucherCode="TT0" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Phiếu thu tiền" e="Cash Receipt"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>

  <grids>
    <grid table="m58" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true" key = " ma_ngv =2">
      <fields>
        <field name="so_ct" width="100" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="100" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
        <field name="ma_ngv" viewType="Combobox" valueDefault="" width="140" >
          <text v="Loại phiếu thu" e="Voucher Type"></text>
          <viewInfo>
            <options query="select ma_ngv, ten_ngv%l from dmngv where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="ma_nt" width="100" >
          <text v="Mã ngoại tệ" e="Currency Code"></text>
        </field>
        <field name="dien_giai" width="250">
          <text v="Diễn giải" e="Pay for"></text>
        </field>
        <field name="t_tien_nt" dataType="N" format="FCAmount" width="100">
          <text v="Tổng tiền" e="Total Amount"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="80" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="80" fieldType="EX" >
          <text v="Đơn vị" e="Customer Name"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>vGhhx6UX2ukHmYI+roecmvkpcTu8WyDAXe6ey467lIg6chdIUIOsI8/uFwdjW6lE0GV9flyJ8moi7Vn0Aec33wVjkXJ1M5gm9Xo4tvXMHT01ZBVBvdwnCk6xGtJvaqYILCfqEKh819ZkSc2FZwY3Pmdn1Ev1vhXQjxYlkhDcFHeF5ddUGhSkZL/VlpYc/zSeENGIigmZZV7/iZGlamDD7AVjMr/rBO8k8jEpMwl5uqY=</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>Xi9ks7k/W+jttFV06t2QjNlGCFTpGV9akGIOTvNNdxw257Bi8w37ToT+hdpVIDmbHxI8cTA39PM2E5vuQiCR7ehpmhEj+TwUkwSNfP/RugmOmlgHLav7j5hZgsy4TnIc98RVyBiHSChyK6F90ze3+P3tHi2e47j8YUm87qLC/SwUwkO2XvF/LxhGavNYTO2y/GJYsOXRJDp4EJJ7a5vC+f/joM0VQkiRKmShMCZ13eMIAN1yuxxhTzXs9huUSjSIm5e6PleSHGjW0XYteX6twJuFLB+5HEJorUb2+P0PE1L2FVkfWZ0+vXib65i4XUFtk39gTpcD/eO27ut1Cmrx6ZCU3IKkOOPEr+JDvDiDrAVDZrj8REr8hCnby1acSUTA3zxo5jmP56m8Lxfa4OD0MWZwzU9WQIva3ZnsWNmz9pM3MQafWu7tpcSMgnFGhiitXr5MStgM+a7dk94W1O62QooyvqaNNkNPO702UQ5WfTSdpnGJA+9XEN2wG+N+iOtFsRT2wG6zynJoWJ+J1XuZY8uEVeRUtNX4KT5NJUy81/lzo0RSgsfosVcDHX4oijaM</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>XymOY7dD2w2+zQLbB/WOXHgjackvy2lYc8CexoyVliOcHgmh9siDTEyvta52L0SFwF6qLvxIRgF5TidZ8J0lTZJiKocmLnN4E8YL4kU123urAxwl9jPCVHPGZ2nq43dSRdkOXDfhrrw5aanaYb4NIh6nG3p5CTqS6rhxeqWrkm6Nt0VU67/JOusEA+RtIKlC</enc>]]>
    </text>
  </js>

  <script>
    &VoucherJSLoading;
  </script>

  <messages>
    <message val="DaPhanBo">
      <text v="Đã phân bổ phiếu thu này, không được sửa/xóa" e=""/>
    </message>
  </messages>
</dir>