<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="m73" dirViewType="Grid" dirObjectType="Voucher" voucherCode="PX1" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Phiếu xuất kho" e="Issue"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>

  <grids>
    <grid table="m73" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true">
      <fields>
        <field name="so_ct" width="100" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="100" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
        <field name="ma_ngv" viewType="Combobox" width="100" >
          <text v="Loại xuất" e="Issue Type"></text>
          <viewInfo>
            <options query="select ma_ngv, ten_ngv%l from dmngv where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="ma_kh" width="120" >
          <text v="Mã đối tượng" e="Customer Code"></text>
        </field>
        <field name="ten_kh" width="250" fieldType="EX" >
          <text v="Tên đối tượng" e="Customer Name"></text>
        </field>
        <field name="ma_nt" width="80" >
          <text v="Ngoại tệ" e="FC"></text>
        </field>
      
        <field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="80" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="80" fieldType="EX" >
          <text v="Đơn vị" e="Customer Name"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>ut7bmtX51o7ohlkZy11sVIaZnUwHEM+ebZUTVuvKujT003xHFhXk+bfhdo+bOLeOc6q63u3F2aexGLbLnl1qTTXhLrNlXeSxVkMrIqXqOIV0K//tFN5voZDEwxmggErUPzh+qFPUrUMIk3h+Ki6PotHKs2S1UZVa98zmFp4o9+J+uINWCG/0sLwuHcsDKIU19OP6Sc81dVTM/vl6dUUBlcpGftcyDenTxwFE2b469gB46nBpzJU1ETEPwEwoY+NGyJC2fwU1SXrO9LnA5xSiMg==</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>fLvsT8g+OP5RgvwdX+lih8k6eeNaNo8AXyVdO8mhrd2COA93Z3OINqkA+E6rBhN91QXlHqr/jLIL1wq+ArLDh2e0AE/cjRoyy61KQgZORxDSyGTYicmvUC5Bo0iIh3qkHpoLwbqYiNWmo0LlSWVNnTUwa9gIFdPuCw+J5J4zYrAF2EZpKbAwEXn2spW5EycLpHxbHRRIU9hwQcYS5m9Om4x6cE1jbrh7XKDlic4xAesKc6H4vwMLA5sdbQKFnnPFUuQcW912pslBHE4yWIwaiJ77uS0kvRTGdh2MyAKYCWG97odcvT6OpZmcvbeRyn6Ohry8T+yT9KX5I0efsoqvLEBmKFZQrNH1FShF46sKvbHfl466UXB7Cg3NPNLLIypLaBRrV2JImX8YCaLvSD5UOTr2hxoOZjsvAXKwMLOC9WynrdO+GHHKrbhlum9Ddgz7+tEpV2wxasZqDgMc2zCFGOdMdI94GUdqZyYmvFIoScmJLwc1COgTOhF2Q2bsiYiRpbt81B5G/OZXDlJhoAe9QR8PWfFvhZWBfWCQlv5ich6tDQ4MTQqHTeLjSSgX78+V7+BZEP+4RZuoFMQiifcxwQZ4c//wHygYtDycW1x+9D8dkD77xeDyiFWfRBhojUSEWN2uojBkf7lTV7duZXPVFw==</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>hLiBLm3iF/aJj7eF2MoRKq+ezhnfR9ttQKO1/+2z8zguwputqdZoZGLnXSoETak0E5LifIhhJEAXS/Lx170ku+mAmNMlnmw+2rJ40joSMOzq/S0bUwtad+izTZUOXvqlJpjbFtdSU1ZzGxZc25o0X3Eqhv4Z34THSCsY9XvUwzCCf7AfRxIDwS+dowP6fFPy</enc>]]>
    </text>
  </js>

  <script>
    &VoucherJSLoading;
  </script>
</dir>