<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="s22" dirViewType="Grid" dirObjectType="Voucher" voucherCode="YG2" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Yêu cầu báo giá(Hàng Lẻ)" e="Quotations LCL"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>

  <grids>
    <grid table="s22" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true">
      <fields>
        <field name="so_ct" width="100" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="100" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
		
		<field name="ma_noi_di" width="100" hidden="true">
          <text v="Nơi đi" e="Origin"></text>
        </field>
		<field name="ten_noi_di" width="150" fieldType="EX">
		  <text v="Nơi đi " e="Origin Name"></text>
		</field>
	
		<field name="ma_dk_gh" width="0" hidden="true">
          <text v="ĐK giao hàng" e="Traffic term"></text>
        </field>
		<field name="ten_dk" width="100" fieldType="EX" >
          <text v="ĐK giao hàng" e="Traffic term"></text>
        </field>	
		
		<field name="ma_noi_den" width="100" hidden="true" >
          <text v="Nơi đến" e="Destination"></text>
        </field>	
		<field name="ten_noi_den" width="150" fieldType="EX" >
		  <text v="Nơi đến " e="Destination Name"></text>
		</field>	
		
		<field name="ma_dk_nh" width="0" hidden="true">
          <text v="ĐK nhận hàng" e="Traffic term"></text>
        </field>
		<field name="ten_gn" width="100" fieldType="EX" >
          <text v="ĐK nhận hàng" e="Traffic term"></text>
        </field>

		<field name="trong_luong" width="150">
		  <text v="Trọng lượng(KG) " e="Gross Weight (KG) "></text>
		</field>
		<field name="khoi_luong" width="150">
		  <text v="Khối lượng(CBM) " e="Volume (CBM)"></text>
		</field>
		
		<field name="ma_dh" width="0" hidden="true">
          <text v="Đóng hàng" e="Package type"></text>
        </field>
		<field name="ten_dh" width="100" fieldType="EX" >
          <text v="Đóng hàng" e="Package type"></text>
        </field>		
		
        <field name="unit_id" hidden="true" dataType="I" width="80" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="80" fieldType="EX" >
          <text v="Đơn vị" e="Customer Name"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
    </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>tofzbM/SPrThRE9DnYpt7uQOFLDHjV51z8tpAHseESVPXzPVD5l7/vkAk1Gow+divXvJW8ISvIeVFV5JoBqtk/zJYu90RPmu5D/FjNe1mH7YjsnLTT4e+C2V51yUP2AtcHnb+4jfI8HNXvGcLglhzwvU7akuFbokPHgGArKuiF4eq2Wc/TNnGXLjkMRaTx4ICfJaKkg0Jywbf3/kPRkB1zQHpVrW83cjUvkVjGgJMAuWZdUhwByaT70fkTJlZgi691xJFQHCgMe/3zI8rcPHC/PXAkbxzaBorDEow4VqerSIQMfyc5hRqxz9Lag1UEZYuA3tOPgkfhXroaJJZh6fREJ8ZwAapvzbFk+FHkiqB1sHqKV+rkPwHdqF/aE5OtSGFs8ZDHZNM2FMeRoNtj33uw==</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>CSCja0fFnuk18yAKx2L1XvGat3n/J5CyHlbkBKuMtw50ztt5Gm4lUk97IXpPcOqnJtDzVdv1O3OWfkXjfL3v142aFrHcncKHIaqUnZ/ryTBtYH8XeAHyYDzp+DXDykoXgexCz+xCgpRwHKV8gEQf5ozgBxwuEuDAH3zeg8uEvdQDNFgXTbROk6DfqjEdmocxAE7HLMTqM/zRp9UGVu4qGbFteHzVFycD6fhb+7leGVVFvYmCdeZJyoN6SPZzMOf5SwT0gw90jyVA2sLTx/9rHS8zVFgSmpookqNZUmBbAsFTfefPJKg/V4boJGupV2WSwnSKdFOWvofzgPn2I3SOYnWURZGqBH5IYsqmZJXBFiONzNcSShwYdT1KGgCQWPNBz/kt9YY5K5+cSYgeC8Alijp9Ss8E4jIcfKAgUv63AGA2V5VkXaCo89m58ndO0lsSfp/JreE4JVNxoI9ibrg9dkxF492hh4MDBBEcGQfzpKIY6nr0WshhemGSuu7VQBTCYiEuKuTwljWbxWJgxFdVkhvOSnwZxgLLmVSUcrD76VgeTXgKN5VSZJdCmqbI3unGTxgPoRoFInAwVp7E8+IHfYiRxzZnLc6EAtPyPP9OFLPVfHKqaAMW9SihP9nazMvk</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>KbLEjVRm53aLNLsq9ZJcPkZReU9U9vCZ1XdBi/1lrqwo8RuzmijDA1OgFLH2IXT4e9Kp/V4sCXVWvRwMMMgcnzNnrRB6hz1/AhYS6P4HJjgI74XpeDh2O7B2eLH+/qtDKIl/+uLiORlDAyvGempJuS8vrvG3nvmnJwlnczkLdpk53nnuzJCW01L2qUCslISl</enc>]]>
    </text>
  </js>

  <script>
    &VoucherJSLoading;
  </script>
</dir>