<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="s32" dirViewType="Grid" dirObjectType="Voucher" voucherCode="YG2" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Yêu cầu báo giá dịch vụ" e="Quotation Services"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>

  <grids>
    <grid table="s32" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true">
      <fields>
        <field name="so_ct" width="80" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="80" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
        <field name="ma_kh" width="0" >
          <text v="Mã khách hàng" e="Customer Code"></text>
        </field>
        <field name="ten_kh" width="0" fieldType="EX" >
          <text v="Tên khách hàng" e="Customer Name"></text>
        </field>     
		<field name="ma_noi_di" width="100" hidden="true">
          <text v="Nơi đi" e="Origin"></text>
        </field>
		<field name="ten_noi_di" width="150" fieldType="EX">
		  <text v="Nơi đi " e="Origin Name"></text>
		</field>
		<field name="ma_dk_gh" width="0" hidden="true">
          <text v="ĐK giao hàng" e="Traffic term"></text>
        </field>
		<field name="ten_dk_gh" width="80" fieldType="EX" >
          <text v="ĐK giao hàng" e="Traffic term"></text>
        </field>
		
		<field name="ma_noi_den" width="100" hidden="true" >
          <text v="Nơi đến" e="Destination"></text>
        </field>	
		<field name="ten_noi_den" width="150" fieldType="EX" >
		  <text v="Nơi đến " e="Destination Name"></text>
		</field>		
			
		<field name="ma_dk_nh" width="0" hidden="true">
          <text v="ĐK nhận hàng" e="Traffic term"></text>
        </field>	
		<field name="ten_dk_nh" width="80" fieldType="EX" >
          <text v="ĐK nhận hàng" e="Traffic term"></text>
        </field>	
		
		<field name="ngay_hl" width="100" dataType="D">
          <text v="Ngày dự đi" e="Effective  date"></text>
        </field>
		<field name="ngay_hld" width="100" dataType="D">
          <text v="Ngày dự đến" e="Expiry  date"></text>
        </field>
		<field name="ma_nt" width="0" >
          <text v="Ngoại tệ" e="Currency"></text>
        </field>
		
		 <field name="t_so_luong" dataType="N" format="FCAmount" width="100">
          <text v="Tổng số cont." e="Total Container"></text>
        </field>
        <field name="t_tong_trong" dataType="N" format="FCAmount" width="100">
          <text v="Tổng trọng lượng" e="Total amount"></text>
        </field>
		<field name="dien_giai" width="200">
          <text v="Ghi chú" e="Note"></text>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="80" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="80" fieldType="EX" >
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>BrK8X4c+VGYMVRV7YqyxmooMHBLIUuEf/yoxv22aVVCQjfjJW6P5TXoJa3Di0E1AxYIzE3LqnDhV3FApeirW4GWJHCBxzaGshhQPCsvGkPxv16PViB8xykAnR4PKMa6GB7P4bPa8fmgcz0MwJt/6mpdkQITVu3T3/M8S8seSGtx6a1PSZ1jlYw0JeZ/D9mtrMyECmCW5cCrAlY1C6wPEVnqo5H56kWoe6OysERrskw245d62t7VY5ttqQTI7U3B0L+2UlemanuU4Leo+fLxxUhUbjPGmhPZdmwYKLKJGgi9t3c9asNIZIc7g5xf1fqbuvvat521AM5+gvW8jx8IM3zNiLoX69k+TXSWUNWxgH+Yw16h2Ax/lzFs6oasc2CsCSPAqKL5Klg9RU1SwbMS4+A==</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>jsqiuBskM2gW12j+aeHw8o2uChpJOumynzbD7HbrJ8DLzDoK9nhuq3XHhDoq2hx3SakR1KyxIEnfXYZsCKCnTL97BHUgix8US0v6zhi/SBDuBjeKMLIYmpVDHKpxaRP5NVTvwIdLpMJPH81xONZ2NIhw4nDQA4bE90IpMp89EEDRVxHxAnljbfDFqItwtTI+xFMr4wQy79y8+We0/vyI62naj3T8Yp0udTFh7N7gOwS31R9jEg1IG+muh5rlkzC8iiwTV7uSW4RYQVb5bsjJlM4BzdQ8JdX6WcdJrWYD4EB4XULSux9y71I9YfdxQ4/0s0VkTkaL/OQaXxqdnZdXI1RgNyQ+/DD0LRPcNW7Bfj8sYX7BuXv3gpOpJAcqHdr2WTP92Hk9Bobn2Z4RcLPh1h1ZlH7/BHIZb1hJA9e8VoyxHBcOQz86Yi+OW9uxkYnrXW4nAsNONvm4+NMQv5SU31zySqHIwYVCh5F4qIx97e68dfyeA9QztGcv3Y9VLhgTiWyYltxbO98oP+v3VRDqKg0Xm/hjPdDaP49vsXKh1zycGxAgqa1JpVer2PB7DrzLKEQiIIopOEMbzN8ZX4YZI5u2U7hHHV5l4vrt6GuNH8BALjRw3w/CZqYCrDqaXHSPm84KT75jNvX2mluCSUy66Bi7XijSWwRi4oUEFLAhPL8PRXSxszsmizPLYcmwtABJNR0ch9uaXs5aaHwm+fwYCwl4GsXKd5tp7iQnS+QzLdYx/o93G+vETRFpiLDyOy6W</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>5wErx4q93yz4A4Cu1Ug/I/caseYeLZIKOnaLAWXu1Z1bcfHCG2dHtqFihLmTJQa3YPSIURNkgiHuFUanlKE8O6SGTHCU9gYQ/Mwq6+SvriD44nhAldp0fStcozpB1aruXVASy3Gelsv3fqNdrzDRSPwcftHaP9KxEWNbLrb/ksw+s/RlndYRfvZ2dl0m6EFxA30VnF3RHfZcG8N4Z+iGEw==</enc>]]>
    </text>
  </js>

  <script>
    &VoucherJSLoading;
  </script>
</dir>