<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="s43" dirViewType="Grid" dirObjectType="Voucher" voucherCode="BQ3" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Báo giá dịch vụ" e="Quotation Services"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>

  <grids>
    <grid table="s43" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true">
      <fields>
        <field name="so_ct" width="80" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="80" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
        <field name="ma_kh" width="0" >
          <text v="Mã khách hàng" e="Customer Code"></text>
        </field>
        <field name="ten_kh" width="0" fieldType="EX" >
          <text v="Tên khách hàng" e="Customer Name"></text>
        </field>     
		<field name="ma_noi_di" width="100" hidden="true">
          <text v="Nơi đi" e="Origin"></text>
        </field>
		<field name="ten_noi_di" width="150" fieldType="EX">
		  <text v="Nơi đi " e="Origin Name"></text>
		</field>
		<field name="ma_dk_gh" width="0" hidden="true">
          <text v="ĐK giao hàng" e="Traffic term"></text>
        </field>
		<field name="ten_dk_gh" width="80" fieldType="EX" >
          <text v="ĐK giao hàng" e="Traffic term"></text>
        </field>
		
		<field name="ma_noi_den" width="100" hidden="true" >
          <text v="Nơi đến" e="Destination"></text>
        </field>	
		<field name="ten_noi_den" width="150" fieldType="EX" >
		  <text v="Nơi đến " e="Destination Name"></text>
		</field>		
			
		<field name="ma_dk_nh" width="0" hidden="true">
          <text v="ĐK nhận hàng" e="Traffic term"></text>
        </field>	
		<field name="ten_dk_nh" width="80" fieldType="EX" >
          <text v="ĐK nhận hàng" e="Traffic term"></text>
        </field>	
		
		<field name="ma_hang" width="0" >
          <text v="Hãng tàu" e="Carrier"></text>
        </field>
		<field name="ten_hang" width="140" fieldType="EX" >
          <text v="Hãng tàu" e="Carrier"></text>
        </field>
		<field name="ngay_hl" width="100" dataType="D">
          <text v="Ngày hiệu lực" e="Effective  date"></text>
        </field>
		<field name="ngay_hld" width="100" dataType="D">
          <text v="Ngày hiệu lực đến" e="Expiry  date"></text>
        </field>
		<field name="ma_nt" width="0" >
          <text v="Ngoại tệ" e="Currency"></text>
        </field>
		<field name="dien_giai" width="200">
          <text v="Ghi chú" e="Note"></text>
        </field>
        <field name="t_tt_nt" dataType="N" format="FCAmount" width="100">
          <text v="Tổng tiền" e="Total amount"></text>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="80" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="80" fieldType="EX" >
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>W1zQzIwMTOGyELfrjvz9Yp6QH8CgTlJeO4cDgYJu/xyHoL08AUVteH9G+NQ+scSV+w4F+vmNNpgXKt+9pUt5zE8T0Ti7Tmu7wJDoZfKzJs41VTdx3OTxKSoHJ/xZCnAviTljX4putEE+5FVwL3iIq4CpSDizPwNflesuTBReIqZOQnufEHwpshwoUasbfSXDWaZaIbbKeQW8WGx1FjaCR61dB7nTuXNtR0pPpa/9dUUiLk18v6K5J+E/nf/6aXCG2pDYYAKusYyY+UUxZCtV4u4JQczMQt9y3cFCAKnA+mF1c/SnF+Vzp4V/plcyY8C93RjXG4/w1BpS12Aa/xUvxsvEROqIIn2colq122jrAGVFD4YYwr90P3tK36TeFRhypsrttRtyp7APNH+loUMzb8L0Xivh0buApXQPktqlA4k=</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>IcDgiKELlvOD4RgR97QXJXxvxOUwpL7GNRYAnKTLV3yvEPwj67c6j/8ypN/5889SXPPfMra0Z9T1GU/RxtsPGy556+tilzBurxhHrN2fSJlphJjuA9He2RF5uiK+DCKcwvsfHUHZ7HQ+SbVy1JmEMIkqhafUTYzHIlCREDIlGGjrc4/48remNPYWo+UvRdvMRzcOZtpx238AMZd2iOu6FZwtlNiA4hM2+QR9WCapFd43Y42lk2X7uo64n4P/xepP7cgdk7v3htX6v1sZzhwM1fbCYaWSREreLEKV1B5YCsB1LfrS/QNx9QODlSvx2mnqsGpxKBYl/l/qE3NK07TCfrFAn8nO3keaq7QFylJ9tmNwZi9KqZnnP8XN9o1oW5vIed1IluiERFr3HvNc49WVrE9YjJy/w/H+TGBBHBOANF3oqzcd7vmvveBcdsiP5zjXNL1Sed6ZHJAorbuiCRRlsO3qX1u+ZtutvEOXWdus4J38qo6RQgAum31HLyGzKc2UgcislqYdGp7c0OpqD7RrA+0QGVGaYhNuAEBD4/BjzDfubhZ2x+vQIUzg+H5HTlh1dmJw2idLTQzrjws/0FvMBo0rgGk/yaqepeEzIm4FlAAgHCWryBAL2zwTP5jwCZ6l/KpEhWdH4DbY2tKPp0a1+JK8JJ4tPlvYU3aRxPpbu1fLbysp4MuprK6LpcRx5vWgCNHUGyMRSqPQ5IV5GRn1jA5dUg/jDptuXATnii9rQF9xsjRH+SAxwXtuzkAs/wGHQXAa+7LbsWpx2kLWMeiL4A==</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>5wErx4q93yz4A4Cu1Ug/I+aQ9Q5HONRREHvKMtyc12U2vvhEGWd6xFE8pPtLpNTuqRMr8JNn6VxMF6mq9HcvO9zS/F0YN7AvGEXDyCFahAeyiPWPaGIOzjthpoZOso9gikVDL9zTYTfOGEdIyF9N68OZoLklul44ZkSijYmKkNZCesNPc7Xr+Sg+BaObLZeOnyPyIIbxv7AWpNWTzu8d9Q==</enc>]]>
    </text>
  </js>

  <script>
    &VoucherJSLoading;
  </script>
</dir>