<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="sysrighthrempinfo" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Phân quyền truy vấn thông tin nhân viên" e=""></title>
  <subtitle v="Phân quyền" e="Permission"></subtitle>
  <grids>
    <grid table="vsysuserinfo" fieldKey="user_id" order="user_id" allowFilter="true" allowOrder="true" key="(@@admin = 1 or user_id = @@userId)" >
      <fields>
        <field name="user_id" fieldType="PK" dataType="N" align="Right" width="40" filterType="Code" aliasName="a">
          <text v="ID" e="ID"></text>
        </field>
        <field name="username" width="120" filterType="Code" aliasName="a">
          <text v="Tên" e="Name"></text>
        </field>
        <field name="nickname" width="300" aliasName="a">
          <text v="Tên đầy đủ" e="Fullname"></text>
        </field>
      </fields>

      <buttons>
        <button id="permission">
          <text v="Phân quyền (Ctrl + E, Alt + E)" e="Permission (Ctrl + E, Alt + E)"></text>
        </button>
        <button id="view">
          <text v="$ViewToolbar" e="$ViewToolbar"></text>
        </button>
        <button id="find">
          <text v="$FindToolbar" e="$FindToolbar"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="refresh">
          <text v="$RefreshToolbar" e="$RefreshToolbar"></text>
        </button>
        <button id="freeze">
          <text v="$FreezeToolbar" e="$FreezeToolbar"></text>
        </button>
      </buttons>

      <script>
        <query>
          <text>
            <![CDATA[<enc>2K/BUz0bP0yVuot8KY4CgophycZ0ycwuhBXYZtk/cTvJZiP5CG9i9Q6P5rEFXU0AKL50FHRFl/Dig+pYOdjfsoFOVO5YSmBHTDLcVYZqoGGiaghkg9TO1YrZ1MZnuWuhx3Zxuxl+KAZr7/N+fWvGZVnphbFlr9f2ZXFkuGc+nI8nCTzvE3LkDYdE6lMpKaucc8vOboi2tkTj44iw//mYB/XwUt/23QC2t1le16HTKBXZvIxwFM5VpKo02ELiZEgHVwaZz1VNs37GbSmY/9TUR/MhW7YaIvUP9ijapNZk3sMaesQqolOlv+yfdAOPyfVv</enc>]]>
          </text>
        </query>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>6oIPVN14IlXeW3znUfdnRgHViw4tBtD/xhfKIInPV0aQ6aALm7CAN1bVe7+IGfJmjN4kufF9ehTsQwQAAGCb8ztVnry4rhBQnh9Zllo44fVCJIA1OQCiGMhoftWhPRyCybrvW+HggThNWiLXCx4XSNO50jh9T4HtmXuyiyUPo33nyvuWCOCTzaCwRrg8WXWy5q6rz37Q3AOABJJLwPgSO0kePuzSiS0DFLGvJiuN4mTUp7fQzjBQpTjtm5vvQ/i4bwBmlndLxceY4vCM1uGIFlOEjhMhUNcfuDDiOGgaidVrsuLfI9Ru/qqWusMIIfhbMlQWC/vbp5zKx1GpkQY6UnZhb7FTpYrMKDNs9XwmUy2s2HGu73vQGOiKf2gPu8UCHzzz4S8J/b7jgtVvpP5Oi4uEqUq/lmhBecIvN19q3VZlz5530PxTUyIe+ynkYqh/mjN+bcFdMy/Sj9i2t9YdtT8RFiGosaXZD1Puy88C0FW58c8fxHJgRsBzSbeehkNz0cEUJbrrecXquP/QmjcTUwhBV3gKaFBtBg3pQn304GEuuos4QEDl58c0uYQ+vaiVp2IvN6OpOok+1TYYoK90bTAx5lrRd6L6mF2bEgd/FsTdh/JROKTCghov7OF3jguNVPsBrJP6qLUUvh8OQ0RlUw8qVqL4UDJSBm9LfWsj9lQ=</enc>]]>
    </text>
  </js>

  <script>
    <request code="CheckRight">
      <text>
        <![CDATA[<enc>r07gHy2a1YsWBN5sJQoNxb4xjNEuroiUKExJ8zUOMf1/3HeoNjMl0dyQw42aagBzvzLxRwI58/bs6KnGaOZsn61LJk243kVa1wYRuYLxclNbo+COgDbx/TdAcLYYm4Ao/Wwgk1UB0YrGbenJx0UdV1ht9eh/LBR9mk9K1UMTGjI=</enc>]]>
      </text>
    </request>
  </script>
</dir>