<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="t51" dirViewType="Grid" dirObjectType="Voucher" voucherCode="VD1" xmlns="urn:schemas-iswift:struct-dir">
  <title v="VẬN ĐƠN VẬN CHUYỂN" e="Sales Invoice"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>

  <grids>
    <grid table="t51" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true">
      <fields>
        <field name="so_ct" width="100" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="100" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
        <field name="ma_ngv" viewType="Combobox" width="100" >
          <text v="Loại hóa đơn" e="Inv. Type"></text>
          <viewInfo>
            <options query="select ma_ngv, ten_ngv%l from dmngv where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="ma_kh" width="120" >
          <text v="Mã khách hàng" e="Customer Code"></text>
        </field>
        <field name="ten_kh" width="250" fieldType="EX" >
          <text v="Tên khách hàng" e="Customer Name"></text>
        </field>
		<field name="dien_thoai" width="120" fieldType="EX" >
          <text v="Điện thoại" e="Tel"></text>
        </field>
        <field name="ma_nt" width="80" >
          <text v="Ngoại tệ" e="FC"></text>
        </field>
		<field name="t_so_luong" dataType="N" format="Qty" width="100">
          <text v="Tổng số lượng" e="Total Quanlity"></text>
        </field>
        <field name="t_tt_nt" dataType="N" format="FCAmount" width="100">
          <text v="Tổng tiền" e="Pcs UOM"></text>
        </field>
		 <field name="t_phi" dataType="N" format="CostAmount" width="100">
          <text v="Tổng phí" e="Pcs UOM"></text>
        </field>
		<field name="t_tt" dataType="N" format="CostAmount" width="100">
          <text v="Tổng cộng" e="Total"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="80" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="80" fieldType="EX" >
          <text v="Đơn vị" e="Customer Name"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>ut7bmtX51o7ohlkZy11sVOLa5Jhz2RDkKOEXar2fa7ZrRChgEQ8Al6jIu/IL/Y78hfUAw8KYrELQpHuehIbDA+e8AEOwIHjLApb2mvWnC0RgfiYW6SHiDNnphlX8rgqx81ffrhqgz8ZfW17EUUhto6Nu0grK+7s+eWQy1QX9pSOlQzvNbyPVNa4WouQZ1SH9fhgyt3SDiLHUsNLApDR9mb8YiIDVJt4G8PmZZ23HEvwqHf9GkyulpMsbTmG89NJejR1N83Smi8tHVSx8mu6xtg==</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>8F3dGYAfTmkBA085VB5fh1e+e2m/cBoQWpuZ23+l156sKYMvhclzfmHL+zVOblME0h5cuhvxVOxJclNDx8abBb/UNgWXqRq4kpDSeP7kGr9EReHgNKz1P2x4SReP+X0IXg/z60juCT5/5jppjztoGefzOfNMl5wsq2/rvScGF9IgY75u410+YX4tYTgj5YgHqumCVo2dcAovSeasPQCuRU4x3Slu1/3wCFbzHeAcjKej5SEGwFN3MyVfgLr1obZeJXxEkg1QLPw88IwaabFDgXIkYLTipqCka02qNYAHusD6Mv3D3lmj9VR4hT1y0b3ITOq/QCEkQXAypBNzW8sWcs4ult3v1AB4E11qzI505IKBf2K4DWG48vk27RGxQkl3Nk0EK6qGVIIe2V9x9YqZTKBQjsI6RAkUCkDLqkXg0z7GA9DvhxsGCtwOMIFDJNS3ck81G5wgvtMzXpZvw/QjO4czWjoJlpYAii44TzRIq2oFDPghSFuyqFWNYlD1DmZb1nCXIDSUNJSiDO0lLwac6jmQnbOt2lm7f6mEkzp7B3XaPESaf4QNUfINhhfqwOKNJLnedaQJ+mj65yOnZvATDJZn6rsM2YBWcFz6A0UmpAwKG2rHl6lnWNjrp/iR+qwFGAeUoadjHonOe7MRQFAtZQ==</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>XymOY7dD2w2+zQLbB/WOXIs0x0vAWTZgKQme4ELWLX+nnQqffFtCBTU4CuIMR0cvmzJgSCjA5LhM4H8HJKMJdBJH5u96GPgNTsTigTCLfVr6so52ntl1CY6FbRObtR/WNk4lJ73xe+MW8SKC3XePWLZnFcg5y24x6OgaUh4bzb9/EFrLgbmkAnHNMuW2d+zc</enc>]]>
    </text>
  </js>

  <script>
    &VoucherJSLoading;
  </script>

  <messages>
    <message val="DaThanhToan">
      <text v="Đã có chứng từ thanh toán cho hóa đơn này, không được sửa/xóa." e=""/>
    </message>
    <message val="DaTraLai">
      <text v="Đã có chứng từ trả lại cho hóa đơn này, không được sửa/xóa." e=""/>
    </message>
  </messages>
</dir>