<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridReport.xml">
]>

<dir id="bctkttgian" dirViewType="Grid" dirObjectType="Report" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Báo cáo tồn kho theo thời gian" e="Aging Stock by Time" />
  <subtitle v="Ngày: {ngay_ct1}" e="Date: {ngay_ct1}"></subtitle>
  <grids>
    <grid>
      <fields>
        <field name="ma_vt" width="100">
          <text v="Mã vật tư" e="Item Code"></text>
        </field>
        <field name="ten_vt" width="350">
          <text v="Tên vật tư" e="Item Name"></text>
        </field>
        <field name="dvt" width="80">
          <text v="Đvt" e="UOM"></text>
        </field>
        <field name="so_luong" dataType="N" format="Qty" width="120">
          <text v="Số lượng" e="Q'ty"></text>
        </field>
        <field name="ky" width="100">
          <text v="Kỳ" e="Month"></text>
        </field>
        <field name="ten_ky" width="100">
          <text v="Tên kỳ" e="Month Name"></text>
        </field>
      </fields>

      &DefaultButton;
    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>08dcf0Sha8fCaXp3CCCcAYZX6tXEH2J2o2YqDrGZo57FgJFdyFrXQPq4zuKqZDws5VysCmCpljaGD881vQ9YoUf4Mu53P+pyxQFjpRmuqCZzkPE8+oKPAaLho1lAt8QfN2ePIKCCTGbq7mhpCSVYTkqPN9ow7qbkntRJVwaKPDbBsSv4mhbCQTUH7CO/vUWK2t5dZ5f6FmIn7ke5o+W1Vx9TOieL4CeaVk/8sF8QCX4u1v9sQbZ4Zu09XH0cOkuV</enc>]]>
    </text>
  </js>

</dir>