<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridReport.xml">
]>

<dir id="bctk" dirViewType="Grid" dirObjectType="Report" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Báo cáo tồn kho" e="Stock" />
  <subtitle v="Đến ngày {ngay_ct1}..." e="Date To {ngay_ct1}..."></subtitle>
  <grids>
    <grid>
      <fields>
        <field name="ma_kho" width="100">
          <text v="Mã kho" e="Site"></text>
        </field>
        <field name="ma_vt" width="100">
          <text v="Mã vật tư" e="Item Code"></text>
        </field>
        <field name="ten_vt" width="250">
          <text v="Tên vật tư" e="Item Name"></text>
        </field>

        <field name="ton_cuoi" dataType="N" format="Qty" width="100">
          <text v="Tồn cuối" e="Closing Q'ty"></text>
        </field>
        <field name="du_cuoi_nt" dataType="N" format="FCAmount" width="100">
          <text v="Dư cuối nt" e="FC Closing Amt."></text>
        </field>
        <field name="du_cuoi" dataType="N" format="Amount" width="100">
          <text v="Dư cuối" e="Closing Amt."></text>
        </field>
      </fields>

      &DefaultButton;
    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>pYwA8X42IeIiB9QO4FsgUJl92gojriqrz8Rg6PIOhepYpRjkUlXFWVp5OVjRi7dpdxKq3wo6m2ne7iL3RKE+fqrjRg/4gDFR5q1mbj6qHg63qT3v6JRl0nUAnEUVUYy1iekEmWwpYbe/6UmFG+0TKnkdsqupy4WdjWRSz8G3mOvyg9+f1dQZyeHXpmXvODWEy/fWDSdNKFnYpaA9nzZQcIRQR6d9/wzTn7aBWhMgVUrT4/b3/ZwyqVdSOFGpNC/udRt1z4/imb6c4wxWH0tWubEDrZMp3cgmPss+lfM25FDg6knFZR+qBdfmGaUsaieBoqjGwQVf/c59QySiul3tSHqaRMDIpfjzsIMqe3Jfhts=</enc>]]>
    </text>
  </js>

</dir>