<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridReport.xml">
]>

<dir id="" dirViewType="Grid" dirObjectType="Report" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Báo cáo tồn vật tư thực tế" e="Stock" />
  <subtitle v="Đến ngày {ngay_ct1}..." e="Date To {ngay_ct1}..."></subtitle>
  <grids>
    <grid>
      <fields>
	  
        <field name="ma_vt" width="150">
          <text v="Mã vật tư" e="Item Code"></text>
        </field>
        <field name="ten_vt" width="300">
          <text v="Tên vật tư" e="Item Name"></text>
        </field>

        <field name="ton_cuoi" dataType="N" format="Qty" width="100">
          <text v="Tồn cuối" e="Closing Q'ty"></text>
        </field>
        
      </fields>

      &DefaultButton;
    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>P946D2YSQzFiXi7+STAl5C20KtUEQmLfgQZwKzTVJ1ppIpxlebiMefUzG2Yrpy1HRD6Ue/Nx41I/6STXbayOOo5LNHVdKx8KKZFFX1SqacJNJ9UZM1pTqLQCW2TAWVaI1naERM4aJyXGqbR2AO0Kl+kr2a7I4zEBOTk1rjI+iw8Om7wTAtVoVn2P2QTTi+VZONRDlcmh4gtEgPAary51uZNHpv5DniG+XSn/CVYI6CJ7ukprOit+U++YC0FoZG4TWxEXgUP06TCck+pUlFxVx5b3pqIcDYLYI0VzTcuGNt3xWAHIVPW7ZEIrSMrtqT0yIN5X41LrM9YdPvi6/xJf44TFYSCcX3VbdPeSU4QDWjA=</enc>]]>
    </text>
  </js>

</dir>