<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridReport.xml">
]>

<dir id="bdtkvt" dirViewType="Grid" dirObjectType="Report" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Báo động tồn kho vật tư" e="Stock" />
  <subtitle v="Đến ngày {ngay_ct1}..." e="Date To {ngay_ct1}..."></subtitle>
  <grids>
    <grid>
      <fields>
        <field name="ma_kho" width="100">
          <text v="Mã kho" e="Site"></text>
        </field>
        <field name="ma_vt" width="100">
          <text v="Mã vật tư" e="Item Code"></text>
        </field>
        <field name="ten_vt" width="250">
          <text v="Tên vật tư" e="Item Name"></text>
        </field>

        <field name="ton_cuoi" dataType="N" format="Qty" width="100">
          <text v="Tồn cuối" e="Closing Q'ty"></text>
        </field>
        <field name="du_cuoi_nt" dataType="N" format="FCAmount" width="100">
          <text v="Dư cuối nt" e="FC Closing Amt."></text>
        </field>
        <field name="du_cuoi" dataType="N" format="Amount" width="100">
          <text v="Dư cuối" e="Closing Amt."></text>
        </field>
      </fields>

      &DefaultButton;
    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>STDef7tf8r/IAvwOvkTSLjSX65zrchx0RNyOGJvgXCiGjJHjoncVN4BC33G1STb1860JaQL1x/XJQdwr0YdJeYoBVxheYvXKyMctPLQkgWOx79dClj+MdGuahrPW2V7r0k6Lt3kOG0jpNu6Hlnb5KVlql/hsaYU1Uy6lHvSxm3YiSs/9uw5kJIK5efKaaiFKbhuqEOpFO0MBhv6wOw5PzZKL601VlMfnM+7xcgyliH6/Bi1Nsy7DnvuVQxTgkVe6Vt0VcjDnWJ91mS05i53uZzYp4wvttvxElZ4CSji4iGrckNZwgwbD+0thCehiPl+NqYRnoboTX21t9RGYHW4rwKWpVhiAipYsJe15t1CZiEE=</enc>]]>
    </text>
  </js>

</dir>