<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="cdct20" dirViewType="Grid" voucherCode="C20" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Vào đầu kỳ công nợ hóa đơn" e="Invoice Opening Balance"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>

  <grids>
    <grid table="ctct20" fieldKey="id" order="id desc" key="ma_ct = ''@@voucherCode''" allowFilter="true" allowOrder="true">
      <fields>
        <field name="so_ct" width="100" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="100" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
        <field name="ma_kh" width="120" >
          <text v="Mã nhà cung cấp" e="Customer Code"></text>
        </field>
        <field name="ten_kh" width="250" fieldType="EX" >
          <text v="Tên nhà cung cấp" e="Customer Name"></text>
        </field>
        <field name="ma_nt" width="80" >
          <text v="Ngoại tệ" e="FC"></text>
        </field>
        <field name="t_tt_nt" dataType="N" format="FCAmount" width="100">
          <text v="Tổng tiền" e="Pcs UOM"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="80" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="80" fieldType="EX" >
          <text v="Đơn vị" e="Customer Name"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>ut7bmtX51o7ohlkZy11sVIaZnUwHEM+ebZUTVuvKujT003xHFhXk+bfhdo+bOLeOc6q63u3F2aexGLbLnl1qTTXhLrNlXeSxVkMrIqXqOIV0K//tFN5voZDEwxmggErUPzh+qFPUrUMIk3h+Ki6PotHKs2S1UZVa98zmFp4o9+J+uINWCG/0sLwuHcsDKIU19OP6Sc81dVTM/vl6dUUBlcpGftcyDenTxwFE2b469gB46nBpzJU1ETEPwEwoY+NGyJC2fwU1SXrO9LnA5xSiMg==</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>EOdhX9kTM3avR87/GEZMK41K2FRHxQMlqVORofJLkAfPBfcDwoyRZ3QMsxI/pjHND6dChnKhd2KGrYivB5LB2xhG4qs+gWrGoRLoy7cwtYfBO2/A9UlS5UCmIIYntOjLZoRF0x5GVppX6V7IKluhpP//Mhq0xbM7VdDKqCuRCotpOcwW2ubImp5NFmX1UAREAX0LoUBhh03y2qiDTkkZVwU4zhKIW2UWWsPQ/7KsaR/OghFNvQrMU0MxfFXvUyVNJdY04wKaLUwQe0EhdVqApC5aK4tYjk1zJ3goFn7Z3p8HxCqunuLaT/0DlPshciAOxlntDwOIlHzhNxD34+jR0a9idBKEUEHSs5KT3+f6DFROPdNwUf4VAaefkTy3QvTEVjftHO6X+n1esweKQpOufcf0l/Km9ZMEKEoredyEY8fHXaeCUbBR9STgvt38MKAV</enc>]]>
          </text>
        </finding>
      </script>

    </grid>

  </grids>

  <js>
    <text>
      <![CDATA[<enc>VVX+SUWCsf268+Fj3cBzY8BXf+PrFLh0rH2aqIF/OMBQqg2p0es3Po2EoeZ+fX4vM9/fyJ1S9hHkP5Ho+3j9kNLr2EyTh9pRa2+M0ny+9/Wo3jE/PlprLG5N2dn5J9zuXd6InvY3JnIlVXgaZCC/b87ZYWYaZkjRx8YAnYBPHWwasQSvMjwp4I76UcSsm9sKYcIF9CbDlvYbQnJjSJbFPg==</enc>]]>
    </text>
  </js>
  
  <script>
    &VoucherJSLoading;
  </script>
  
</dir>