<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmdv" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục dịch vụ" e="Service List"></title>
  <subtitle v="Cập nhật dịch vụ: thêm, sửa, xóa..." e="Add, Edit, Delete Service..."></subtitle>
  <grids>
    <grid table="dmdv" fieldKey="ma_dv" order="ma_dv" allowFilter="true" allowOrder="true">
      <fields >
        <field name="ma_dv" fieldType="PK" width="120">
          <text v="Mã dịch vụ" e="Service"></text>
        </field>
        <field name="ten_dv" width="250">
          <text v="Tên dịch vụ" e="Description"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>gbveqZ921+F0tM5Cn1/sdDZ3cUcoUI1YCqu2PjebA2XZS085whUjfAirvdUP2OeaqgV6//UVWAYpuGeJmAh9plXWKcwM8uWGHdz14uspZiPZZBegNQtsHbwm398QOurYKx9l9oR+2f5f/QNmc2UPmq8qeQq+18h4jmY+dwkH13lrGtizav008JrlLnfSkoRQ</enc>]]>
    </text>
  </js>
</dir>