<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="vdmkho" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục kho hàng" e="Warehouse/Site List"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, edit, delete..."></subtitle>
  <grids>
    <grid table="vdmkho" fieldKey="ma_kho" order="ma_kho" allowFilter="true" allowOrder="true">
      <fields >
        <field name="ma_unit" width="120">
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="ma_kho" fieldType="PK" width="120">
          <text v="Mã kho" e="Code"></text>
        </field>
        <field name="ten_kho" width="250">
          <text v="Tên kho" e="Description"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>uw3iZoR/y/5o6FF1x5y/2be5dSiphKQhyj+elG5GRJmWgYO9sOBws38C5vjkCo3sL968jjQKsS6chXIrc+7lhO159+WwR3cnNfeNP+uwwscEvLLPZBtdSpzUAwVXZtfQXFXHIujSenJOoZJ0a5tznOG7roFchzElts+FDpzBHcRUFGPsavE1DmYeLFkrQ1xw</enc>]]>
    </text>
  </js>
</dir>