<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmphi" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục phí" e="Free List"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid id="0" table="dmphi" fieldKey="ma_phi" order="ma_phi" allowFilter="true" allowOrder="true" >
      <fields>
        <field name="ma_phi" fieldType="PK" width="120">
          <text v="Mã phí" e="Code"></text>
        </field>
        <field name="ten_phi" width="250">
          <text v="Diễn giải" e="Description"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>PoZY7gtiqLjMyWhzpqyQdvSGdh5tAfOCM9/yuCKZRUELJBScDb32ONKU1Un/uF9Kf6/p2Mx31lWpJDC6UFlax/yThMLqCMM6j7RGun0j3leR6v/9SSQjVEIOcw6cGBwpVP3GzfibfKdN1TVa22ttMAwgNpkG0LDpBcx/S6WWytStWERoaUOfxJ3DWTTUujk0</enc>]]>
    </text>
  </js>
</dir>