<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmvv" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục vụ việc" e="Job List"></title>
  <subtitle v="Cập nhật vụ việc: thêm, sửa, xóa..." e="Add, Edit, Delete Job..."></subtitle>
  <grids>
    <grid table="dmvv" fieldKey="ma_vv" order="ma_vv" allowFilter="true" allowOrder="true">
      <fields >
        <field name="ma_vv" fieldType="PK" width="120">
          <text v="Mã vụ việc" e="Job"></text>
        </field>
        <field name="ten_vv" width="250">
          <text v="Tên vụ việc" e="Description"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>gbveqZ921+F0tM5Cn1/sdDZ3cUcoUI1YCqu2PjebA2XZS085whUjfAirvdUP2OeaPuxxYK2bCVmHHApsSzie7j+C2MpIJ7HUcXQgRmzcf/2g7ErjFLXxvou521amKL+5EP8xVbwk/rUUvvHCfr4yNp8hsxmgRlxo9dy9OxeCfkj+YnchRfwppL4tN64znoVh</enc>]]>
    </text>
  </js>
</dir>