<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
]>

<dir id="m52Close" dirViewType="Grid" selectMultiple="Table" voucherCode="" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Đóng đơn hàng" e="Đóng đơn hàng"></title>
  <subtitle v="Xử lý &lt;b&gt;%s&lt;/b&gt; đơn hàng" e="&lt;b&gt;%s&lt;/b&gt; Sales Order"></subtitle>

  <grids>
    <grid table="m52" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true">
      <fields>
        <field name="so_ct" width="100" link="V" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="100" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
        <field name="ma_gd" width="80" >
          <text v="Giao dịch" e="Transaction Code"></text>
        </field>
        <field name="ma_kh" width="120" >
          <text v="Mã khách hàng" e="Customer Code"></text>
        </field>
        <field name="ten_kh" width="250" fieldType="EX" >
          <text v="Tên khách hàng" e="Customer Name"></text>
        </field>
        <field name="ma_nvbh" width="100">
          <text v="Mã nhân viên" e="Sale"></text>
        </field>
        <field name="ma_nt" width="80" >
          <text v="Ngoại tệ" e="FC"></text>
        </field>
        <field name="t_tt_nt" dataType="N" format="Amount" width="100" >
          <text v="Tổng tiền" e="Pcs UOM"></text>
        </field>
        <field name="status" fieldType="PK" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = 'DH1' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="ma_ct" hidden="true">
          <text v="" e=""></text>
        </field>
        <field name="id" dataType="I" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      <buttons>
        <button id="close">
          <text v="Đóng/Bỏ đóng" e="Close/Cancel Close"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="find">
          <text v="$FindToolbar" e="$FindToolbar"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="refresh">
          <text v="$RefreshToolbar" e="$RefreshToolbar"></text>
        </button>
        <button id="freeze">
          <text v="$FreezeToolbar" e="$FreezeToolbar"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
      </buttons>

      <script>
        <finding>
          <text>
            <![CDATA[<enc>p1Yr/Sc3YaCjYw6eFdziokIJGwF/equNvDF1pGPdI7eYh+QncYt0LJ+aYktOWnVifzbFWdw8c410SGbHhi3Sl3QGnkTGr+Rv8klPVhx8Q9tqmcQ8LLvFEK4keB9wc03a9UyXupsskkygik4Q/NQ3NWL9+bqI6cVV0i8VEvQT3kY3BOIYfkYzOtbJLv8mzY7Ql2/z6ZCAc7IuPOPNGePn2otSt7JK5WxxKE0BrNbSFKDjYoKLd9n+GMaZj/HPENbEDkQrVsL7rz9c6YpRl5EQecbsoSV+a6A4Nx9h5itu6O1WW3P/RiqSw7H+wWqR1wYnpkAHz6nbwvJMJ8KEkUarWrjalNW+ewMivd3tsI3eb8BfPbvtdzVd4mmMzBDCrn3HbvJCWz79bmJgOOj+rtS8zA==</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>RHvQFF3mi+iQ+U21Y8fNc0kiZ+y9qSHCL6Vq4TzYvgJhd+lfKet/8UvY/AxX3hAdb6L10gDGkDxfDtX2f100Ud0KUZ60Qb8CkpYRyKxCnZWrrZhXEdoDDuI3SgE43/ZDzKuOEWEuqLfkRWaxhNV5mwKUwbM08XRghavoYS7sbn4hSIBns02gE4EaL8h2t2KT72lSrR60FfuGWSBV8nMvDaz6tlBhyehzrsL0iFMemlH9Rfa1QaS3yzgOI9a2P7bHK2kxHdke1o118xmoh+ZFY+ewcGT8VhAldT+WE2PxVzKHDBfq9iOAzDOHjz+f+g+M+r6KEXUaFsOgoz1A+TH7eQTIvTBt3NRQ79BA6xKZp+KhWsUh8HDsNIS8zIhQXPeo1KmCjK9E9hXrwzSCDQWEXkJLDAK/PBqGRyKxfEB7AyRmVMVu6ilkh7A1csX3ci+Rhyn/WKdoBs60jYq62zr0Zl8gntqIBcuAa835YzcxfkrHrtfduZzGabr5/vW2LD3aXTFS96uCvEXfAU5AjmjG7iuSCiLA9Nlll9WZTetSl0ZzAwUl+T+3cGBFtSV11swc6VYv8/hFMLTGnziLiOvLl5QdlIIefaexqdZ20800yPzHzEeSbtqjR4sbgriwCqWOYeBPEV/YhhmRfumDwsV7KzLOlGoaocfh2Sgwxraa/VNciECI38/ljQ9WJ1WBuMjGuDVuhgbV7TYSD4goqDAg1Q==</enc>]]>
    </text>
  </js>

  <css>
    <text>
      <![CDATA[<enc>KC1cKJv5fV3yTGRKpOAWLOrvz21BaEnqgu3aGnAY8RBVenDkJZKQFYghY4E1scCovM9zIzWSUYvwGt8aqZFF4XWjnod/Lq5lWN8PMIdfH6y7DYVxXCmlOajLypQf35Dv01RPyr6Je23sNK01q9ZwHA==</enc>]]>
    </text>
  </css>
  
  <script>
    <request code="CloseDH">
      <text>
        <![CDATA[<enc>Vjq6sH6Nr8LKdE00/3x6y6iP8boNdFhgz39Q9O4gYzwKdcNoj/oWY9nXn7dPUGaHyPZsdU6y4oVrbor5HzGv4URAkYtbcrECuINbR8z5ZdSq1vI0WjqzXfaJc9dXDwj+pPBXowjz8b/Brp8deFKQaQz6GUJOnUrFxBFeTduNx/GwJHHYnSjV4sbZK+ZQxvUxZNl7Q2mKfW4zIDcqcOH0OSLNN3VUkMAI9Cd7zkVkACkIdlq2VptBYhCufjO/0tZsmJJU4cZOPkIscBRlejtGt1g6o9FBAXzWJijrlBQ+UVql6Q2pLAF1yZdidq1j+T6A6AILHCDsnfpUXYcTjogc7bOl5fBkeXg3UEhDNdPYgro=</enc>]]>
      </text>
    </request>
  </script>

  <messages>
    <message val="msg1">
      <text v="Bạn có chắc chắn sẽ &lt;b&gt;đóng&lt;/b&gt; các đơn hàng được chọn không?" e="Bạn có chắc chắn sẽ &lt;b&gt;đóng&lt;/b&gt; các đơn hàng được chọn không?"/>
    </message>
    <message val="msg2">
      <text v="Bạn có chắc chắn sẽ &lt;b&gt;bỏ đóng&lt;/b&gt; các đơn hàng được chọn không?" e="Bạn có chắc chắn sẽ &lt;b&gt;bỏ đóng&lt;/b&gt; các đơn hàng được chọn không?"/>
    </message>
    <message val="close">
      <text v="Đóng đơn hàng" e="Đóng đơn hàng"/>
    </message>
    <message val="unclose">
      <text v="Bỏ đóng đơn hàng" e="Bỏ đóng đơn hàng"/>
    </message>
  </messages>
</dir>