<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="m54" dirViewType="Grid" dirObjectType="Voucher" voucherCode="PX3" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Phiếu xuất bán hàng" e="Pick List"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>

  <grids>
    <grid table="m54" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true">
      <fields>
        <field name="so_ct" width="100" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="100" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
        <field name="ma_kh" width="120" >
          <text v="Mã khách hàng" e="Customer Code"></text>
        </field>
        <field name="ten_kh" width="250" fieldType="EX" >
          <text v="Tên khách hàng" e="Customer Name"></text>
        </field>
        <field name="ma_nt" hidden="true" width="80" >
          <text v="Ngoại tệ" e="FC"></text>
        </field>
        <field name="t_so_luong" dataType="N" format="Qty" width="100">
          <text v="Tổng số lượng" e="Total Quanlity"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="80" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="80" fieldType="EX" >
          <text v="Đơn vị" e="Customer Name"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      <buttons>

  <button id="view">
    <text v="$ViewToolbar" e="$ViewToolbar"></text>
  </button>
  <button id="split">
    <text v="-" e="-"></text>
  </button>
  <button id="refresh">
    <text v="$RefreshToolbar" e="$RefreshToolbar"></text>
  </button>
  <button id="freeze">
    <text v="$FreezeToolbar" e="$FreezeToolbar"></text>
  </button>
  <button id="split">
    <text v="-" e="-"></text>
  </button>
   <button id="print">
    <text v="$PrintToolbar" e="$PrintToolbar"></text>
  </button>
  <button id="export">
    <text v="$ExportToolbar" e="$ExportToolbar"></text>
  </button>
</buttons>

      <script>
        <query>
          <text>
            <![CDATA[<enc>ut7bmtX51o7ohlkZy11sVIaZnUwHEM+ebZUTVuvKujT003xHFhXk+bfhdo+bOLeOc6q63u3F2aexGLbLnl1qTTXhLrNlXeSxVkMrIqXqOIV0K//tFN5voZDEwxmggErUPzh+qFPUrUMIk3h+Ki6PotHKs2S1UZVa98zmFp4o9+J+uINWCG/0sLwuHcsDKIU19OP6Sc81dVTM/vl6dUUBlcpGftcyDenTxwFE2b469gB46nBpzJU1ETEPwEwoY+NGyJC2fwU1SXrO9LnA5xSiMg==</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>fLvsT8g+OP5RgvwdX+lih441Psarz98c46Eour9Nzzvgsv7OvhXFilT8MV5uhqmWtV4FDxKTXGMAIbdbz0rDT3qPZnjwjVm8Xy65hd//LvDeqJ8iSN+2GnpaeR9lOn/lFntJjFXeNSDZZFphgjh0NP4h6E85nqyPgm5qLhsQnQiHcrlS69a0iQL24VtQ79ceEdaS2cGhb5XiVvjx4oBWMh2ggBRNu1IllQomBuXPbWwLOGPkI0ztqRIR8Jp0Y5ajw9IDVun1FspHbOatMWcGbcTlLQyCyYRt4brl0SC8TtZ+/EiulH1pvPpRgFx+nrs9eU2NJ3Al5/yqeh/JN6LVjo6QEjOm0yYXSpBk98HP/tJ6x1FYoJ1+mE1tppfiMSoCmVVaaTPAwmqsN4+wm4/36jdn93Jts8AmAwLurVx3opONJjEJ5RgE9atkk7q7uMOaSBwMZHAVzJW8I0UbJGwiIvTCO2TryPVCNvzS8wsK+xtAmsVq0vvyQnOtyMXVXkTNoc3L9aEopEpEnHaBx7JfSOzz2iFztq1XlnwJlFlOMWoROFP/4eB0naEuolAr9/moacfsRPmQVebYCOu8Q99saHvokef/rXqOUYwDYSX9unRfopU6IMztBTeY7TbElBou</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>hLiBLm3iF/aJj7eF2MoRKkVrUDZares+TCtMAvrDcy+DR6gzQww2/A93NXL1SDstz8B956IkQjCFpww+gt+mquRiZflgRnpYt+pKTQJv+3BTOnRC7vZn53yAMkUIDVFZus75Q11IqLMSyrl8vr/bSqcFAzoOf5ui/U+R17zDXv1wlnrf0/LnLhxWzDerKIIX</enc>]]>
    </text>
  </js>

  <script>
    &VoucherJSLoading;
  </script>

  <messages>
    <message val="DaTraLai">
      <text v="Đã có chứng từ trả lại cho phiếu xuất này, không được sửa/xóa." e=""/>
    </message>
  </messages>
</dir>