<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="m65" dirViewType="Grid" dirObjectType="Voucher" voucherCode="MH1" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Hóa đơn mua hàng" e="Purchase Invoice"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>

  <grids>
    <grid table="m65" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true">
      <fields>
        <field name="so_ct" width="100" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="100" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
        <field name="ma_ngv" viewType="Combobox" width="100" >
          <text v="Loại hóa đơn" e="Inv. Type"></text>
          <viewInfo>
            <options query="select ma_ngv, ten_ngv%l from dmngv where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="ma_kh" width="120" >
          <text v="Mã nhà cung cấp" e="Customer Code"></text>
        </field>
        <field name="ten_kh" width="250" fieldType="EX" >
          <text v="Tên nhà cung cấp" e="Customer Name"></text>
        </field>
		<field name="dien_thoai" width="120" fieldType="EX" >
          <text v="Điện thoại" e="Tel"></text>
        </field>
        <field name="ma_nt" width="80" >
          <text v="Ngoại tệ" e="FC"></text>
        </field>
        <field name="t_tt_nt" dataType="N" format="FCAmount" width="100">
          <text v="Tổng tiền" e="Pcs UOM"></text>
        </field>
		 <field name="t_phi" dataType="N" format="CostAmount" width="100">
          <text v="Tổng phí" e="Pcs UOM"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="80" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="80" fieldType="EX" >
          <text v="Đơn vị" e="Customer Name"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>ut7bmtX51o7ohlkZy11sVOLa5Jhz2RDkKOEXar2fa7ZrRChgEQ8Al6jIu/IL/Y78hfUAw8KYrELQpHuehIbDA+e8AEOwIHjLApb2mvWnC0RgfiYW6SHiDNnphlX8rgqx81ffrhqgz8ZfW17EUUhto6Nu0grK+7s+eWQy1QX9pSOlQzvNbyPVNa4WouQZ1SH9fhgyt3SDiLHUsNLApDR9mb8YiIDVJt4G8PmZZ23HEvwqHf9GkyulpMsbTmG89NJejR1N83Smi8tHVSx8mu6xtg==</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>fLvsT8g+OP5RgvwdX+lih3LQS5nGgC2FIu/oxTRu1b0551ajy+qJTkBC6u7rtwTubR3JyYXvIIYYNizKTHBLOT5EGEffZGHkmUruYadoKlwwnaRd95vAkVBo7XPE8TZUEqY4/ZoOPMUN/QIT+eTiSoobO5INiJsz/fMEF06ktOHSEe7wKpba/4LNoyZnwZXlt5bHhqJf4lvinaqJxNu0b1qNh4CED4nOoUZD7KGTBSfuhROT9gpsObylHs9dtPBzFJh/1jAaHH7pCaMngaX/4V+x1Ov71nsJqODnn+Xq4xbCqfyFN8v9JPr03UTsnD/hbXl8b0e+styw1Eg9WDUIlKErvxIYjR954QupUkKsKl6UHJ4Bye91TzVnHI55EpghgtlxTIQlnyNadsK2Gpupl/2TNdW57USW0vOnDcNAv1kJFzsE4lKg3OPfPJ2kh5ipeJpZQVgr9jiDsZl6wmtWePlzCkzKp5F0ma/v9gwbUALgXE/LcIjRPbmw/RzG3FZTXlxTgLVQ4k3N2SvPtrwl+pyTJ/Kb/dLG7Z+P8EKuMcw/vQHE3ob7jUgzKL00UtQaM+quaHHG+tRr/HJIXgWO1PxFNJSEmJJvh1LnR4pt8IGHT+khU7VgmankVUHKOrIp/s1Wc45l0Nuqq7iey7j+PQ==</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>hLiBLm3iF/aJj7eF2MoRKt7e2Ivbp/v92T0VlYD/XjM9VzMmoBIP2CpnD8/FVjIkgDdUxun7pIwpH/8hNF/F2tXe3U2f8XiDNVXFPVEaKNel6u66pCfouG8YgXj6UjADHwhK8M6t0lJCXTZGfk1K60S65MUr2L7cOlB3s9L98+u4IHj56xk2BgF+YNUI9w7i</enc>]]>
    </text>
  </js>

  <script>
    &VoucherJSLoading;
  </script>

  <messages>
    <message val="DaThanhToan">
      <text v="Đã có chứng từ thanh toán cho hóa đơn này, không được sửa/xóa." e=""/>
    </message>
    <message val="DaTraLai">
      <text v="Đã có chứng từ trả lại cho hóa đơn này, không được sửa/xóa." e=""/>
    </message>
  </messages>
</dir>