<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="m72" dirViewType="Grid" dirObjectType="Voucher" voucherCode="MH1" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Hóa đơn mua hàng" e="Purchase Invoice"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>

  <grids>
    <grid table="m72" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true">
      <fields>
	   <field name="id" width="100" >
          <text v="Số id" e="Voucher Number"></text>
        </field>
        <field name="so_ct" width="100" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
		
        <field name="ngay_ct" width="100" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
        <field name="ma_ngv" viewType="Combobox" width="100" >
          <text v="Loại hóa đơn" e="Inv. Type"></text>
          <viewInfo>
            <options query="select ma_ngv, ten_ngv%l from dmngv where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="ma_kh" width="120" >
          <text v="Mã nhà cung cấp" e="Customer Code"></text>
        </field>
        <field name="ten_kh" width="250" fieldType="EX" >
          <text v="Tên nhà cung cấp" e="Customer Name"></text>
        </field>
		<field name="dien_thoai" width="120" fieldType="EX" >
          <text v="Điện thoại" e="Tel"></text>
        </field>
        <field name="ma_nt" width="80" >
          <text v="Ngoại tệ" e="FC"></text>
        </field>
        <field name="t_so_luong" dataType="N" format="FCAmount" width="100">
          <text v="Tổng số lượng" e="Quantity Total"></text>
        </field>
		
        <field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="80" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="80" fieldType="EX" >
          <text v="Đơn vị" e="Customer Name"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" >
          <text v="ID" e="ID"></text>
        </field>
      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>ut7bmtX51o7ohlkZy11sVOLa5Jhz2RDkKOEXar2fa7ZrRChgEQ8Al6jIu/IL/Y78hfUAw8KYrELQpHuehIbDA+e8AEOwIHjLApb2mvWnC0RgfiYW6SHiDNnphlX8rgqx81ffrhqgz8ZfW17EUUhto6Nu0grK+7s+eWQy1QX9pSOlQzvNbyPVNa4WouQZ1SH9fhgyt3SDiLHUsNLApDR9mb8YiIDVJt4G8PmZZ23HEvwqHf9GkyulpMsbTmG89NJejR1N83Smi8tHVSx8mu6xtg==</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>8F3dGYAfTmkBA085VB5fh6frb65V/PlZscByQJG2jwm2MDjeqZhVMosfDyL+vzSlY1msGuYYMIA+JHeBeLpMip2fQfyc6Ubo9IddDmBfLXy9gZbm7UsFjPOQCCPQ0qWtbpERC2z/EoTmfCsfymGe2grm1nYG47SFwmakiC4iD+NW6XB2GDgZVM6QhFiQOYpfVSraRThi+hIYU62T++eCStTVNr9mDBZ5az5Ld5QLffq7rh4omsRR52K+2+DgWiuQCswfZ0BY6Zl9/O8IlVy5JQhq/Q+8Xeq9UMQk5rscAQyakgGi9A/A1YNE/WLL4KuiBgV504WhYJZyrloNbCyp43MZ/VLZ9wYkerCcJ73Ud07YdufN+dpYux+xmuEJru3kuOF1sBXlRWM7Vpag7MG1yHCZ/hqAhQ0OV7M+MGaqzabmyp7WCNugiEpOz0SvWvUGBGrHUNOnZwAFcwleCY1/zsV/lh+PWln/JIEBrdolY0ofbTANoy87/RuwWm1jHf7ZG1PHzo1u8OzL9dr+n1Nmbg8ukQnJBG/V+Apj/HK8XbEmnNb4PSwa99OqqjYWb+WadMHrh4n+gOa07oFaCML3ePcXn8z4lwWn+a7EvGpJy8Pq05iIqYIhsJk1w9arwgog9pRFV2X5RTaCg+ExvAAGLw==</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>hLiBLm3iF/aJj7eF2MoRKrZt4ZJUaq/Ii4BmwCb0UgSMxLEtzjmpongigOh7U+/zlio7bw9nsHw7VUThlAeGDDhuotN9NiLMRelvezHa6NZNz72mmu6rb1q78e0auccWScneJ66lmzeWMb1l5B/5Ea0kogbyk1V5Or5CJmKXzU1deUuBxB9cwqxQulc2NLPD</enc>]]>
    </text>
  </js>

  <script>
    &VoucherJSLoading;
  </script>

  <messages>
    <message val="DaThanhToan">
      <text v="Đã có chứng từ thanh toán cho hóa đơn này, không được sửa/xóa." e=""/>
    </message>
    <message val="DaTraLai">
      <text v="Đã có chứng từ trả lại cho hóa đơn này, không được sửa/xóa." e=""/>
    </message>
  </messages>
</dir>