<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="m75" dirViewType="Grid" dirObjectType="Voucher" voucherCode="PN2" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Phiếu nhập điều chuyển" e="Stock Transfer In"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>

  <grids>
    <grid table="m75" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true">
      <fields>
        <field name="so_ct" width="100" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="100" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
        <field name="ma_ngv" viewType="Combobox" width="100" >
          <text v="Loại xuất" e="Issue Type"></text>
          <viewInfo>
            <options query="select ma_ngv, ten_ngv%l from dmngv where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="ma_kho" width="120" >
          <text v="Mã kho xuất" e="Site Issue"></text>
        </field>
        <field name="ten_kho" width="250" fieldType="EX" >
          <text v="Tên kho" e="Site Name"></text>
        </field>
        <field name="ma_nt" width="80" >
          <text v="Ngoại tệ" e="FC"></text>
        </field>
        <field name="t_tien_nt" dataType="N" format="FCAmount" width="100">
          <text v="Tổng tiền" e="Pcs UOM"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="80" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="80" fieldType="EX" >
          <text v="Đơn vị" e="Customer Name"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      <buttons>
        <button id="edit">
          <text v="$EditToolbar" e="$EditToolbar"></text>
        </button>
        <button id="view">
          <text v="$ViewToolbar" e="$ViewToolbar"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="find">
          <text v="$FindToolbar" e="$FindToolbar"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="refresh">
          <text v="$RefreshToolbar" e="$RefreshToolbar"></text>
        </button>
        <button id="freeze">
          <text v="$FreezeToolbar" e="$FreezeToolbar"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="print">
          <text v="$PrintToolbar" e="$PrintToolbar"></text>
        </button>
        <button id="export">
          <text v="$ExportToolbar" e="$ExportToolbar"></text>
        </button>
      </buttons>

      <script>
        <query>
          <text>
            <![CDATA[<enc>LYD75dCdQMdHYwRxBZzawHOULk2y5P1xbU8kULH9V8QrRchuPfMhyD0aL4RHBvecKL7g7blJmpqaGWJaB1DqTbgqd9UuoCTi4O1HE/bxF6GrIWlUzDtEBcy7LDdqCHMvHAXoiW4R6bshNyaEzmiy00OMa5i4TR900U97VzCCgS43QBS9WdtgckS1OaJXvZrlWMs/h6RqllFB9GCVyhR66PDPGAoJ4qFWTPmQUzkCO3FSWLp8B0b9Y5GKcEOVFHYkn0YKplSZkM5Rxp3NvFrDng==</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>2hR5tyAPOVwxAt29Jaw5pba80cQIG9Pm2KcvOt2QoNP+jkeW+IAxcHwvJS/XJVtUjOLNZemE0j24pyPQad0TAjEWmEt77QF8y5u0hfAP0SueuthbHo0IKQZKo6T/KLr2Uk31oU7t2kC4kC8aoIN0lmxsteTXrfCDjxHtXnlwuj7lw+dwhSUcjKYvtHeuf8XWyFWuzJDlfJI8XNFLZDMl2b4YesBcPdha4aKL1whm5V02HXLyVlNHqZrqCxn2I0an88/GS4qseev2TDF7kvYQm8raf8FtusLX3CsrZtjeqSSUJ6MoC5HKRx+pnFDDn01vf/x+2jAdD8sYTOXEewSOT4P6XaRjeWdQJFurlEJyrmplqNubebp5FBAGpWJjC5mk1GSQg/Nf4fthBfEXm5mg3MS5VITVtj/m+mjMY1NMEXGXnvEh/YSiIJAVmZ6rAi0S16mwZqyj19Dgcjhnpj7TADBtdFb9DmHKQtQ3m6WcaCNnhrwyRaoEDmhbBm1dCODhlQKSYUq6DfHdNCVVYICJtX96YP+bMuMSeOoGDkfaB2t2DpN7eH4PtRrRY/phPICN89YkX/9yuf7is3OAc9DPNTWHoNGjdpGUflAEEgVsCr39MOsURuisTiF9oZnFtPxWsVBmY5M0JmDjktEZmOxOBg==</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>hLiBLm3iF/aJj7eF2MoRKvHqPUsAXb8t+ZMVc5QCTJ0F7sInbLTRshNVSolBJqhcYLiqM7dZv9gVStAu01y9UsvqsvxsnCA2I2Hny5avR+YpjEoIcL2LxDMW6jkFlTwET37g8hq4txD/0o4twGDZcJ/82PvoUBY2KnP4g+SbeiwJVqRoAFz22iADxdQPn0SK</enc>]]>
    </text>
  </js>

  <script>
    &VoucherJSLoading;
  </script>
</dir>