<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="m85" dirViewType="Grid" dirObjectType="Voucher" voucherCode="GH1" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Phiếu vận chuyển" e="Shipping Voucher"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>

  <grids>
    <grid table="m85" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true">
      <fields>
        <field name="so_ct" width="100" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="100" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>

        <field name="ma_kh" width="120" >
          <text v="Mã khách hàng" e="Customer Code"></text>
        </field>
        <field name="ten_kh" width="250" fieldType="EX" >
          <text v="Tên khách hàng" e="Customer Name"></text>
        </field>
		 <field name="ma_dvvt" width="120" >
		  <text v="Mã đơn vị vận tải" e="Service"></text>
        </field>
        <field name="ten_dvvt" width="250" fieldType="EX" >
          <text v="Tên đơn vị vận tải" e="Service Name"></text>
        </field>
        <field name="dien_giai" width="350">
          <text v="Diễn giải" e="Descriptions"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="80" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="80" fieldType="EX" >
          <text v="Đơn vị" e="Customer Name"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>lOG+lsrIzErDXFDwmdtoxBkBk6QKrRfezpkBRQw5UoT43wP7Vx0CN/97y6INxusenLgkagZaFbBJ/lyG+gfqu0wsdIkLN02RcvAh03IkVWHG/ChDrIyYJzRu0P2cKajgnQwZ5PsCoVh19BesNtTzaC/kbEFdjcNn4PQRy2p6a1e5W48Ty50k704OsUb/Ul/0sKdNUWsEmOFWm1L7Wc9uzkXqnazdAhUo8kHhVBK0mOm0GkCOiVcObH8EtanRx75tb5CKho7NdnN6ffv1gWH1PgoKPaMe7w2ol3v0SxwDhho=</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>4iWQaOijw6/OOxcQswFfJEeEFQxu3COtS4ZHrYffXJIEckfy7Bgxk9hhQrW8TWBQ4WU1xb9p9FFAJ1sWozgXtxpkE/0AH1+JVSNIt6syBRRiMXsrHOCyrohdmMHjc+IRODxO06xwWiy7vSgb95HGe7535O8W4T9DGtDCy9IBkBXLybRaFNjc9fDLsPrc3N2gp+1OY0+jaCBJ4/8t+D8E4KwDDPjXM3KX4qE8M8XwflWkf3EIZ7i9TVK6+KDHHCmPXhXYBVxXuMlTF8tmt8y95FDqiIlkFq+7VfoI2C+KP6RZH5qB/JcOlOZn2K19It7mnSMrC0+yw1x5iua1OPU9RA8RHfx1QuSLk8+9jYLnC7V3mQGdfsikwcNRcIT/hgDrj13AEem7Sh8wvhiAzfeMY6VkAUEMApaAOfkK6TRv93y+bACIy3hbGZoL9P9fRHiBC+TQDnV41lhALExWPHLcA2efwHRKfp32WhSloKK04MSPjdkXwCeRz0SjusZp+Nx/VTSvd+NhrOPeJExwCN6ecdsZgG00i91u8BXzRx/PHEPM9A0ttMI6K+UuDrP4ifUxQokKN8yJyygo7hvl+Cfjb1RTR01wJhVyeuHKUgIJHwY/cbuZ5y/L8993ct1MXSjEhSUp4SiUWig4uVuW04D+Gj3dQzrdk8i1lyNFjxaqYYM=</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>XymOY7dD2w2+zQLbB/WOXHgjackvy2lYc8CexoyVliOcHgmh9siDTEyvta52L0SFD/QAuh8YHK6CemO7rfxqbT0F1/ECxFzNfceHSNI6Pjt3RZ2u+amzyhouTjSFYP7VmoVA4OIFs4wQ7K9VuUNbBg3RMVTGa40jJn8+r/1yWF1wQqFM8SYwqDhknY0XaTMh</enc>]]>
    </text>
  </js>

  <script>
    &VoucherJSLoading;
  </script>
</dir>