<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="sysrighthr" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Phân quyền bộ phận và chức năng cho thông tin nhân viên" e="Departments And Menu Access Right Maintenace"></title>
  <subtitle v="Phân quyền" e="Permission"></subtitle>
  <grids>
    <grid table="vsysuserinfo" fieldKey="user_id" order="user_id" allowFilter="true" allowOrder="true" key="(@@admin = 1 or user_id = @@userId)" >
      <fields>
        <field name="user_id" fieldType="PK" dataType="N" align="Right" width="40" filterType="Code" aliasName="a">
          <text v="ID" e="ID"></text>
        </field>
        <field name="username" width="120" filterType="Code" aliasName="a">
          <text v="Tên" e="Name"></text>
        </field>
        <field name="nickname" width="300" aliasName="a">
          <text v="Tên đầy đủ" e="Fullname"></text>
        </field>
      </fields>

      <buttons>
        <button id="permission">
          <text v="Phân quyền (Ctrl + E, Alt + E)" e="Permission (Ctrl + E, Alt + E)"></text>
        </button>
        <button id="view">
          <text v="$ViewToolbar" e="$ViewToolbar"></text>
        </button>
        <button id="find">
          <text v="$FindToolbar" e="$FindToolbar"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="refresh">
          <text v="$RefreshToolbar" e="$RefreshToolbar"></text>
        </button>
        <button id="freeze">
          <text v="$FreezeToolbar" e="$FreezeToolbar"></text>
        </button>
      </buttons>

      <script>
        <query>
          <text>
            <![CDATA[<enc>+4t+JKiO4MbUO2oMoDBPPZaF/OnDRUh5it0NS1xbTZyKSgkmBNlYzZaOdr7vWZrX41T6BPY/B2wwAXCwGgymOeU0HAU8qviIdUEeHdIQbbxwDfDHOqoKjZYwuQW6dv0TtQQNFhCHuR9v5iNsLvE8LLFpD8DFWqH2fPHgFrQRfgxOpsNOuVe179aODl9mgikm6d6OhoGuqHg/O5i9vzugb/QwcnsLCZjldsdaWYn+wLhLkbC5WvzH7/SNmr+6+d8Etuoh0XUcEEYNVbesKUm4jcUfHWtZDs0hKz/42C0wHcAi7maAfS7Rgnh2JB8lOUbu</enc>]]>
          </text>
        </query>
      </script>

    </grid>
  </grids>
  
  <js>
    <text>
      <![CDATA[<enc>Trkb2bekX4tiEuol68lz9jKfUs87jjiGEeSe/WIe4IVMajsVb1noXchVrE1EvTkzrHEDAxieF/oYSpy+lsi6H/HJGmr473cbkEJ2cdlQ0pQLVhiK80uZkLc7MQpY3okOsDUGDM2FN7U2g0zChjb89aS0acyUFboQkSzpSVvDKOU+9wCNhLfpwtyO76JksaRgziS0sNr0KPi6okSj4PDkth6z0V+uVWhteifqYpeV2T6Q3FXxEANtTpfqcnxoprwasL3DuLr0rGTG3qHWTuec1tRbRlLlt8fWPHUfsFoZIhcNivjP+X4I10+GeIjF1g8pW1IHHxOGwZwDMPyBMii1LU85ciarGHmvuZ+RU1xUr6euDcS+9MFlAc9gjIt/icVaN2kzwLh/Z1aN7Z/52TOwMUqMAPndgEgiy+VamnhI+G/zYXFSqR9ccLA5ehQCX+ESqKPRrD3yd81BFCW+ONT/qOaHZ0wbgfDjaUce+wc/drdrse0uNAJtAu3ru+d8heYUlGZZ8XvW/DXDYoXJvYmmhHGXe9LVJcoEWP3hoUZNU+ahVIMhCEBjk1Gv2+C6M2iUqxMLEwapxf1ahKhm9EaM2RPiLu2jbieGQ3R8LuZN7PUK0PVlCPp30mCRIktyeNJoJ3IO0zkz0FMyd56CRNlD7rEqiKO5c/BM1IBCoY5Zc6k=</enc>]]>
    </text>
  </js>

  <script>
    <request code="CheckRight">
      <text>
        <![CDATA[<enc>r07gHy2a1YsWBN5sJQoNxb4xjNEuroiUKExJ8zUOMf1/3HeoNjMl0dyQw42aagBzvzLxRwI58/bs6KnGaOZsn61LJk243kVa1wYRuYLxclNbo+COgDbx/TdAcLYYm4Ao/Wwgk1UB0YrGbenJx0UdV1ht9eh/LBR9mk9K1UMTGjI=</enc>]]>
      </text>
    </request>
  </script>
</dir>