<?xml version="1.0" encoding="utf-8"?>

<dir id="dmct" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục chứng từ" e="List of voucher"></title>
  <grids>
    <grid table="dmct" fieldKey="ma_ct" fieldName="ten_ct" order="ma_ct" allowFilter="true" allowOrder="true" key="" >
      <fields>
        <field name="ma_ct" fieldType="PK" width="100" filterType="Code" >
          <text v="Mã chứng từ" e="Code"></text>
        </field>
        <field name="ten_ct" width="250">
          <text v="Tên chứng từ" e="Name"></text>
        </field>
      </fields>
    </grid>
  </grids>
</dir>