<?xml version="1.0" encoding="utf-8"?>

<dir id="dmloainh" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục khu vực" e="List of dmloainh"></title>
  <grids>
    <grid table="dmloainh" fieldKey="ma_loai_nh" fieldName="ten_loai_nh" order="ma_loai_nh" allowFilter="true" allowOrder="true" key="" >
      <fields>
        <field name="ma_loai_nh" fieldType="PK" width="100" filterType="Code" >
          <text v="Mã khu vực" e="Code"></text>
        </field>
        <field name="ten_loai_nh" width="250">
          <text v="Tên khu vực" e="Name"></text>
        </field>
      </fields>
    </grid>
  </grids>
</dir>