<?xml version="1.0" encoding="utf-8"?>

<dir id="sysregioninfo" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục khu vực" e="List of sysregioninfo"></title>
  <grids>
    <grid table="sysregioninfo" fieldKey="rg_code" fieldName="rgname" order="stt_ref" allowFilter="true" allowOrder="true" key="" >
      <fields>
        <field name="rg_code" fieldType="PK" width="100" filterType="Code" >
          <text v="Mã khu vực" e="Code"></text>
        </field>
        <field name="rgname" hidden="true" width="250">
          <text v="Tên khu vực" e="Name"></text>
        </field>
        <field name="rgnamex" width="250" aliasName="a.rgname as ">
          <text v="Tên khu vực" e="Name"></text>
        </field>
        <field name="rg_ref" width="0" hidden="true">
          <text v="" e=""></text>
        </field>
        <field name="stt_ref" width="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      <script>
        <query>
          <text>
            <![CDATA[<enc>NFi+yJPRo24hcZx/EjN8uk2scmsJjJWH5jvTHM+YM5s4DQnXF9HtStiGjROWtQyJkjlxAPaAPaFPnWaOJ0ohlZdR8kROti8gRHDotBGIrzq0d0PtzNg5lnd9CNS3XVr/uOkqRcYBhcnHiqZ1AwZuEqJIYXgIXII2gWJekG9q3GE/69D1prxF0xP0s/PRPb22naIoSgm8zaFRamNcM4c2nUHvuQ5PfNG53rnaAnBvhkq2lVyj0SiAFKlh/8zLZQMfHqhzUHx3YQcc2ebcE51JkLoTNwEYa8YHcVBYkZdOb/zpesbmOSXC4atTd2ZaHhHTEhu/gQHhaxPxRpQxmG9iNp4j2E5Yc/wASh6ovJy+qtphV9Au1i+zImxuZeHRWSmGOJhZpp1FAh16UzKsRFIHKNcoHzMq8sg2mAr1VRmLcnk=</enc>]]>
          </text>
        </query>

      </script>
    </grid>
  </grids>
</dir>