<?xml version="1.0" encoding="utf-8"?>

<dir id="vdmgd" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục giao dịch" e="Department List"></title>
  <grids>
    <grid table="vdmgd" fieldKey="code" fieldName="name" order="code" allowFilter="true" allowOrder="true" key="" >
      <fields>
        <field name="code" fieldType="PK" width="100" >
          <text v="Mã giao dịch" e="Code"></text>
        </field>
        <field name="name" width="250">
          <text v="Tên giao dịch" e="Name"></text>
        </field>
        <field name="ma_ct" width="100" >
          <text v="Mã chứng từ" e="Voucher Code"></text>
        </field>
      </fields>
    </grid>
  </grids>
</dir>