<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>

<dir id="cdncc" table="cdncc" fieldKey="nam,unit_id,ma_kh" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Vào đầu kỳ công nợ nhà cung cấp" e="Customer Opening Balance"></title>
  <title0 v="Cập nhật công nợ" e="New Customer Opening Balance"></title0>
  <title1 v="Sửa công nợ" e="Edit Customer Opening Balance"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
        <field name="nam" label="" field="1" format="-1" maxLength="4" hidden="true" fieldType="PK" dataType="I">
          <text v="" e=""></text>
        </field>
        <field name="unit_id" label="" field="1" format="-1" hidden="true" fieldType="PK" dataType="I">
          <text v="" e=""></text>
        </field>
        <field name="ma_kh" format="U" label="1" field="1" viewType="Lookup" allowBlank="false" fieldType="PK" >
          <text v="Mã nhà cung cấp" e="Customer Code"></text>
          <viewInfo lookupType="One" lookupId="dmkh" lookupKey="1=1" lookupCheck="1=1" lookupRef="ten_kh" lookupInfo="dmkh|ma_kh|ten_kh" />
        </field>
        <field name="ten_kh" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
        <field name="du_no0" label="1" field="1" allowBlank="true" format="Amount" dataType="N">
          <text v="Dư nợ" e="Debit Balance"></text>
        </field>
        <field name="du_co0" label="1" field="1" allowBlank="true" format="Amount" dataType="N">
          <text v="Dư có" e="Credit Balance"></text>
        </field>
        <field name="du_no_nt0" label="1" field="1" allowBlank="true" format="FCAmount" dataType="N">
          <text v="Dư nợ nt" e="FC Dr. Balance"></text>
        </field>
        <field name="du_co_nt0" label="1" field="1" allowBlank="true" format="FCAmount" dataType="N">
          <text v="Dư có nt" e="FC Cr. Balance"></text>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>4VmXWJkQrn1vXazsgkD0mB8vRobGBNLZMTsesPGgOVd96lTS9DsW62m/rIOlUQO4sKARWDOeFdhU+dJ3QVSlGmlFkTLbb3UITpyqQtlex9OBuYrZa4k48yQfRXB7jRysUpDvZIMSfgDwIqPaWaoWSO6+JsPPHSzMwCJHWgM2eMu0gf86a026YqPV1YEdjCQFY1Lc31m2JvZiuvHpRtaJ9zJccWuT9MvatvG7kAKqzHo7zCetU+fcmNxAWYRd3s4s</enc>]]>
    </text>
  </js>

  <script>
    <query>
      <text>
        <![CDATA[<enc>GJgBVkOd9xy3In+SUACpOOdXdTQbLjDNG098RVYG+mqJrACGNi8MwNsRrtmQkuMIYyR65+M+8FdE2nQkBtdUjjGtkBSGsDqbRbA3vrYN89ZzUnQVJ+W1/9AMkiZ8xTjP+2RTNpSxyNoYjrbfEIJzqQ==</enc>]]>
      </text>
    </query>

    <beforesave>
      <text>
      <![CDATA[<enc>r07gHy2a1YsWBN5sJQoNxXUjOzccVwVnzbiWkdSER3GSrxRUQ70+cXCQE/TPBWYKNuStEIcY3vWd3u3W90dDbQ==</enc>]]>
      </text>
    </beforesave>

    <deleted>
      <text>
        <![CDATA[<enc>l2RBYdHOlenDqXbxvQR0AvPWHV6retlFzrC99cM625AQrZohyMufX60ptNwkJShW/IGRNS8xlRy1McWoVIDeMjYyOqJfYSvLr1sBsWD3Gbo=</enc>]]>
      </text>
    </deleted>

    <aftersave>
      <text>
        <![CDATA[<enc>31JOOL/XQPnVGk3KYY2yH7ThtzI6wPg0h2WnJ9JRM+YvDnqm+ewYYhjBn+QITT3sdUtAdNHP2A8yU8TCZTt3/XBwcYIQMGNPpmWiX/EF5UsfF94VnHlB152naI/wPaAbxq8RNqOx1GZzqrMwlXUy2AvPGbbNVbtNuImCBvWwkGQVcPg63QKkMB/pEPEIBt3qGutTmvRCVCHkFqr5NqSe9oNB4Ms4pYZaPzbgbs+yv4OU7ZRsl/Z/tKwK3Ux5RoodDXootB1MJUdVb+IPcfUTWg==</enc>]]>
      </text>
    </aftersave>

  </script>

  <messages>
    <message val="codeExistsNewMsg">
      <text v="Công nợ nhà cung cấp tồn tại." e="Customer Opening Balance is exists." />
    </message>
    <message val="codeExistsEditMsg">
      <text v="Công nợ nhà cung cấp tồn tại." e="Customer Opening Balance is exists." />
    </message>
  </messages>

</dir>