<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="cnhmnkh" table="cnhmnkh" fieldKey="ma_kh, ngay_hl" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Cập nhật hạn mức nợ khách hàng" e="Cập nhật hạn mức nợ khách hàng"></title>
  <title0 v="Mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
        <field name="ma_kh" allowBlank="false" viewType="Lookup" label="1" field="1" fieldType="PK">
          <text v="Mã khách hàng" e="Item Code"></text>
          <viewInfo lookupType="One" lookupId="dmkhkt" lookupKey="status=1 and ma_kh_kt &lt;&gt; ''" lookupCheck="1=1" lookupRef="ten_kh" lookupInfo="dmkh|ma_kh_kt|ten_kh" />
        </field>
        <field name="ten_kh" clientDefault="true" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
        <field name="ngay_hl" label="1" field="1" allowBlank="false" dataType="D" fieldType="PK">
          <text v="Từ ngày" e="Từ ngày"></text>
        </field>
        <field name="han_muc_no" label="1" field="1" dataType="N" format="Amount">
          <text v="Hạn mức nợ" e="Hạn mức nợ"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" label="1" field="2" valueDefault="1">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>8wsLme4If9rNawhEvon3/QVwfjdEwm+/bFrzUcaSHdtIl+JoO+pb3UQG5jBjuv/1QCLxt6Z3EpjFlgedWvCDrSqZ1ajbb/3BS8P/i5eWrbiN2HeYRsU0aRd/4hAoql8eK9qcWgmLa1uLebAmA/4R432bcY7ZQVrDbJU4T95DwqvFwhk2Jb7VnpJcZ9Tqdxy9</enc>]]>
    </text>
  </js>

  <script>
    <declare>
      <text>
        <![CDATA[<enc>msQndfXVe4yzbX61lyYjl1nvBdAf7+K7U0/oTbBRpkEAlgdDs13VYcC6Kpo+NJ03+I2KdpzjGkpM/hVMUFcPkwbXvJa2cEnPJd0TuEAtR62Yw5UcpznrDx7YY5nY0L+sJKKuO2wBhwVwryCVC6/beE5pHL0FqqoB+38daMLOCEcPYYbsDZEnwTnc8AAJBOQH4u20dllPYRY+KU8l4QaE/jRPaN7nyRfiRxleuTxsE1vUEiw/mjp26+cEtwPQObdcqg7PvfeF+Z6LfgdJgHWGTtE/W7MREGtS3f5F0/ZXahM=</enc>]]>
      </text>
    </declare>
  </script>
</dir>