<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmbencang" table="dmbencang" fieldKey="ma_ben" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục bến cảng" e="Port Directory"></title>
  <title0 v="Thêm mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
        <field name="ma_ben" format="U" label="1" field="1" allowBlank="false" fieldType="PK" >
          <text v="Mã bến cảng" e="Harbor Code"></text>
        </field>
        <field name="ten_ben" label="1" field="2" allowBlank="false" fieldType="PK" >
          <text v="Tên bến cảng" e="Harbor name"></text>
        </field>
        <field name="ten_ben2" label="1" field="2">
          <text v="Tên khác" e="Other name"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>1PFOGp66gVgaSTPirrPUVQbMSKkhmnTmRHH3u+H6D2zM8z3Qwt/ZFDnp1dW7nqktJ7jFzoeKjFoTwOCExszb2S/0Pf8fvxx7pZHiNx2qUZoQeiRDT9Z3bqnn1fXbtvHv2uC0PeSL1EhWXh58H9kYZM4he7FOAXwmLto0Eis3KUlzJaEk0rDd0BXOz8Hj8cx70lu1qMM61klESDg3wIjx+y9BRX7QAjieI/CN/zLIilH4SY0rJWb/SQWF57ZZlZ/O4eVbj4SsS2P+tkLw1MOmaXXBLXQPIW0fIZINhspJEtBEqCi73HjDoZBPICAyySkvx8HgsjcC5c0NLFkxxBA+8WyiNvZTqM9L/RBAFdsSDs0=</enc>]]>
    </text>
  </js>

  <script>
    <declare>
      <text>
        <![CDATA[<enc>hxQPm/hYhpvPifcenBxj7nfT+X4T8oXvYmZx4Kpwn3fRRVZY+foYIow2vt1OHdzq0lG6PkDpvnlKR1ei3AR28UkawCxswedTww8YMZ/ax/1/BVJZ6K0wvLOosliedaWZN/O/aWda8yI4bNk0lG9MtLdWhBTIGdwzQ9qPgw1Uqkn1OtRP1Vn5AbmlQRaQ6x02/Fqh/06aWhZs1d3L2oNvocnYnLH8USVBzSlPC2XKjcRVPh+chwpAEE/y4465aYhu</enc>]]>
      </text>
    </declare>
  </script>

</dir>