<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>

<dir id="dmcnct" table="dmcnct" fieldKey="ma_cnct" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục Chức năng chứng từ" e="List of voucher functions"></title>
  <title0 v="Mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
        <field name="ma_cnct" format="U" label="1" field="1" allowBlank="false" fieldType="PK" >
          <text v="Mã chứng từ " e="Voucher code"></text>
        </field>
        <field name="ten_cnct" label="1" field="2" allowBlank="false">
          <text v="Tên chứng từ" e="Voucher name"></text>
        </field>
        <field name="ten_cnct2" label="1" field="2" allowBlank="true">
          <text v="Tên khác" e="Other name"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>1PFOGp66gVgaSTPirrPUVUgXFguRdD4kd6Aw/AylcI85VhQTdfoBoPJsej69r4xhFn1lTx5dH1CAq9XwEcgjFxUp5bgPNUoyrYMl4vaAa6mUTLFZ6Zow3jjwQYKxaK4i3thIjcHSYwB2TWXRkyYXUwa7JNFOsYEnK7HFBLVWaY55i6fvzjMP9Egs6JTHejyMNpWhhCDGNDEz7uhZW5lK/sRsFkA9pLw7RAjzR367raRj3lpidbtwQ9POx5johTdH9aY0pTXQaGHBaB811Co7hsCbiF9iom8YudvzCHR7bv0FzFDB7W/YwmeBbCmp8J09R53f5TOhOsjgHPV5zkGvWg==</enc>]]>
    </text>
  </js>

  <script>
    <declare>
      <text>
        <![CDATA[<enc>jlawCjXJ1tF+DiIdlzbAVflMvuW8mhpDW7lvuJsKpEnUy5MMv5sI+mjhbv+YYLtnqKXTaYU0+DQDhw4o0M6c4OFmppaKhTSoqhtngj+F65bMmtq4egYbX7wL2FPFe2FTE8/wiTQvvHI5flE4UTcH0yenIUbwziMBZTB72DheafvsSmzW31Erf2cdPXDo4UlBTCJfw4T9n5GDztOsnBdhqq4D3c5UjMnIHSECACoWz8tqtjT8xBpsEWLaRDwksptTwdvl/3YzHiOsqp2vX/CwUA==</enc>]]>
      </text>
    </declare>
  </script>

</dir>