<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmhangtau" table="dmhangtau" fieldKey="ma_hang" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục hãng tàu" e="List Of Shipping Lines"></title>
  <title0 v="Thêm mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
        <field name="ma_hang" format="U" label="1" field="1" allowBlank="false" fieldType="PK" >
          <text v="Mã hãng" e="Brand Code"></text>
        </field>
        <field name="ten_hang" format="U" label="1" field="[200]" viewType="AutoIncrease" allowBlank="false" fieldType="PK" importable="5">
          <text v="Tên hãng" e="Brand Name"></text>
        </field>
		<field name="ten_hang2" format="U" label="1" field="[200]" viewType="AutoIncrease" allowBlank="false" fieldType="PK" importable="5">
          <text v="Tên khác" e="Another Name"></text>
        </field>
		<field name="ma_thue" format="U" label="1" field="1" viewType="AutoIncrease" allowBlank="false" fieldType="PK" importable="5">
          <text v="Mã thuế" e="Tax Code"></text>
        </field>
		<field name="dien_thoai" label="1" field="1" importable="80">
          <text v="Điện thoại" e="Phone"></text>
        </field>
		<field name="fax" label="1" field="1"  importable="85">
          <text v="Fax" e="Fax"></text>
        </field>
		<field name="ma_qg" viewType="Lookup" label="1" field="[120]"  >
           <text v="Mã quốc gia" e="Country code"></text>
           <viewInfo lookupType="One" lookupId="dmquocgia" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_qg" lookupInfo="dmquocgia|ma_qg|ten_qg" importCheck="@@DF and z.status=1"/>
        </field>
        <field name="ten_qg" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
           <text v="" e=""></text>
        </field>
        <field name="email" label="1" field="2" importable="90">
          <text v="Email" e="Email"></text>
        </field>
		<field name="web" label="1" field="2" importable="80">
          <text v="Website" e="Website"></text>
        </field>		
		<field name="dia_chi" label="1" field="-" importWidth="250" importable="30">
          <text v="Địa chỉ" e="Address"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>1PFOGp66gVgaSTPirrPUVUgXFguRdD4kd6Aw/AylcI/GkrNvvUzimpcazEL6YCXoUd4JCrc5/8fkOGZqNPiYmAssD3YUU5/+T2dL6+GQ/ZS5cqtYrywG30DEkhLzHtNF9nmO4UhJYS1L4+kyv3+OXMd4Rgfr38Umbyv/HCFgMl79w1/4nkRE63UFzYZ1mxpDy5E0VLhvGApoPTdKwJkmiB1qTWNuM5LHmN8Oe3YJ6tntHXLBEnpZ+GHcEdnGAeGBMNYYv8ZFchtJKo3oKgSjgNIXv84iIWQ5nfL2XVcNhqcs8l51H25rDcjIB/388Lf4gOHB9+KUTg5g9t2TLW5cGEe2Xri0a3lJzJj8gDNQSXs=</enc>]]>
    </text>
  </js>

  <script>
    <declare>
      <text>
        <![CDATA[<enc>hxQPm/hYhpvPifcenBxj7nfT+X4T8oXvYmZx4Kpwn3fRRVZY+foYIow2vt1OHdzq0lG6PkDpvnlKR1ei3AR28UkawCxswedTww8YMZ/ax/1/BVJZ6K0wvLOosliedaWZ4wJbBQNpEYeEGvsFyxSRDboPE3NesEzJ3iH+4/4DgeseagZw+WUCIh9B21nVHB9ODPP9tXOpxXhskIupsqFM94tRNijPgqMarW2ni5XnaUmR/8P20fIXmassdggNCdfa</enc>]]>
      </text>
    </declare>
  </script>

</dir>