<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmkhuvuc" table="dmkhuvuc" fieldKey="ma_kv" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục khu vực" e="Area Directory"></title>
  <title0 v="Thêm mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
        <field name="ma_kv" format="U" label="1" field="1" allowBlank="false" fieldType="PK" >
          <text v="Mã khu vực" e="Area code"></text>
        </field>
        <field name="ten_kv" label="1" field="2" allowBlank="false" fieldType="PK" >
          <text v="Tên khu vực" e="Area name"></text>
        </field>
        <field name="ten_kv2" label="1" field="2">
          <text v="Tên khác" e="Other name"></text>
        </field> 
        <field name="status" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>dtYy4kD7R/zFbl3e6NPEDhISVU+DqLhdi+NLfHNxtptCHsi0gnaRumoB8Mtk5JnTxoCsuv7ioKEpq0LcWF8IpNr4TZ0H3sc9yIFQVOLdL2Xij4DiQ9ZRtu8Yh7oNk1aIKkvQssbonAICBN3wruHmHLUi74EvgpyT7B9s3XGE+kjp2z89jSzdYkH22jQm95zSf0zK2wWSYpFbS/LBQVHFJT3JTc2Rsbf0tfcRNNPRS0bDj/qpsYGaERZ0C6lHF9TTy1+mTUvdcHxysMoRegU+9rcOrTxrYRT2WEtm76wjjxcahU0S1FCbBBNxLdZYslk5loWeHwXprybuODbJZL6ae6ysnvuCDaeVYsbvYPqYUTA=</enc>]]>
    </text>
  </js>

  <script>
    <declare>
      <text>
        <![CDATA[<enc>hxQPm/hYhpvPifcenBxj7nfT+X4T8oXvYmZx4Kpwn3fRRVZY+foYIow2vt1OHdzq0lG6PkDpvnlKR1ei3AR28UkawCxswedTww8YMZ/ax/1/BVJZ6K0wvLOosliedaWZUz/Y2dgSnmIfKOQ3W6jSn/p3/e/71ybUN1IdvW/+DloHNs6v6VYw7Isc9fsJh78P60fVSrGlROpRgi4iXE0EPkOiExL4F35F5/zuRX5hwPE=</enc>]]>
      </text>
    </declare>
  </script>

</dir>