<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>

<dir id="dmkien" table="dmkien" fieldKey="ma_kien" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục Kiện" e="List of packages"></title>
  <title0 v="Mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
        <field name="ma_kien" format="U" label="1" field="1" allowBlank="false" fieldType="PK" >
          <text v="Mã Kiện" e="Package code"></text>
        </field>
        <field name="ten_kien" label="1" field="2" allowBlank="false">
          <text v="Tên Kiện" e="Package Name"></text>
        </field>
        <field name="ten_kien2" label="1" field="2" allowBlank="true">
          <text v="Tên khác" e="Other name"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>1PFOGp66gVgaSTPirrPUVVXHCZhYQQOqRHPLw9CqJ8mtPa/9x0hqnqLV1cVRJtK78H3pGcxWVvdyB6rHYzMmB5nQx66oAaTQb7RWYTPWRTuf4mGRokPabaDG31UO/reMncN0LuBzsa1Ft7v8jCq2+/icH9KXqF5MdmxQsv0tc1/d1FZsM28chArTXFeXPdr6qgRH3j6vIH9/NylAvD4kBo+wotbL2UyvdkWWVhPqe08llYPWvZwVf+tyOwssu9yqIyMN2jcSn+Y7ArskQr0Kjt9L7cmh5LsF4PD28z1fyKUMqW0vve5F3lSABvtnCTgCnw5q0WeIsTi6UmK62ViVzE7lQa8NOYk6uMFhcS/6s30=</enc>]]>
    </text>
  </js>

  <script>
    <declare>
      <text>
        <![CDATA[<enc>hxQPm/hYhpvPifcenBxj7nfT+X4T8oXvYmZx4Kpwn3fRRVZY+foYIow2vt1OHdzq0lG6PkDpvnlKR1ei3AR28UkawCxswedTww8YMZ/ax/1/BVJZ6K0wvLOosliedaWZK7hrtb/qYmpqsSh8aqTYuCduV6KqBPjmiSe8Fg2fuQcSYNfZJwZI6wfTA2apN+cQurWaAbzXHnNt6mzlkX7dAt4ybqofsBKP52UzJVMK9a7TXZiVW3H3aAy9nBlmYqev</enc>]]>
      </text>
    </declare>
  </script>

</dir>