<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmloaitau" table="dmloaitau" fieldKey="ma_loai" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục loại tàu" e="Port Type"></title>
  <title0 v="Thêm mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
        <field name="ma_loai" format="U" label="1" field="1" allowBlank="false" fieldType="PK" >
          <text v="Mã loại" e="Type Code"></text>
        </field>
        <field name="ten_loai" label="1" field="2" allowBlank="false">
          <text v="Tên loại" e="Type Name"></text>
        </field>
		<field name="ten_loai2" label="1" field="2" >
          <text v="Tên khác" e="Aother Name"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>1PFOGp66gVgaSTPirrPUVVXHCZhYQQOqRHPLw9CqJ8kd4cEIlVT+op9oQ6sFLqxIGebRkT4FH1iueuOjshn0ZJbXUp+K3km7IBPx51IcqcXp83kOSAewph2cn32qkJG/pd3S3iCiVDDXwrPOQh8VJbb7mplY9pgmD6TrYer+2wiOPpSTwTHp5Kx5+2vXLomj9Gk98Y/DTKfYEau54WmfRDgVQuG00ygSEesKmdHC95l/M1Ic0hawrQ/DDRr3RbUL++c3KmsvrdMfe/5bgZ/XWzk2N4a8d6uFozl3mnXxAdev1g7E6ICQjEH64s4vYEsDuq8xRmBogwoPNMHV3O+qGCsmbef5rbUA8aSwXq4nHVE=</enc>]]>
    </text>
  </js>

  <script>
    <declare>
      <text>
        <![CDATA[<enc>hxQPm/hYhpvPifcenBxj7nfT+X4T8oXvYmZx4Kpwn3fRRVZY+foYIow2vt1OHdzq0lG6PkDpvnlKR1ei3AR28UkawCxswedTww8YMZ/ax/1/BVJZ6K0wvLOosliedaWZAZZQJt+bLBksKe9RWXks/levCfPgDA86GJAVt2lHZYTcgIhY9jVRaI5pSmJAyOu2jSc5Z6mBpyhMk/TwjCo6tUN9f7RVc6s1HR9Hemu+zOoRMach5LBw3iNXy88uuuZ0</enc>]]>
      </text>
    </declare>
  </script>

</dir>