<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmloaicong" table="dmloaicong" fieldKey="ma_loai" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục loại container" e="Container Type List"></title>
  <title0 v="Thêm mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
        <field name="ma_loai" format="U" label="1" field="1" allowBlank="false" fieldType="PK" >
          <text v="Mã loại container" e="Container Type Code"></text>
        </field>
        <field name="ten_loai" label="1" field="2" allowBlank="false" fieldType="PK" >
          <text v="Tên loại container" e="Container Type Name"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>1PFOGp66gVgaSTPirrPUVeYzrXstur9UVisKTJQ3FkPgbqXeLmfGlYSdMUyTPsqUcpawCs9DBrLSeFJBPRxClHsrjjPNeGxjSL5GR3qFkHh5l9bSqi6YXWh2s+lmgj/ZJW6k+ImZw+3xK0h6CnzbSF7CNmjKxcenyB8xd7vVMUF+nBCAaG2eR0MyZjYhMtfVI51mFX3E0P1hocx+OLMBekAB7QtJ7tyEhFMjQI6WXYUOj+id7CpTBAOmYP8A76q2dcl6hgpOyTK9AIRoAvdO9OZeOnS3hXrw5Qif8q1JCWO8uI6BmP+XOjiesRE+WL5ITJbiOeFVbWn3hyHgVsZp3MKKLXSnZaVxwiFoyyIt71A=</enc>]]>
    </text>
  </js>

  <script>
    <declare>
      <text>
        <![CDATA[<enc>hxQPm/hYhpvPifcenBxj7nfT+X4T8oXvYmZx4Kpwn3fRRVZY+foYIow2vt1OHdzq0lG6PkDpvnlKR1ei3AR28UkawCxswedTww8YMZ/ax/1/BVJZ6K0wvLOosliedaWZAZZQJt+bLBksKe9RWXks/rTWIAErPXWKXW4zgGZ2NkefXgTDcQoGZ5h17ryQ99db2XEKLsk6b/7j1cjNK6/Rm+UMsDdu2iAwnKWvUmJ4qLcFCqIHSp2OwQs8xav/YZjl</enc>]]>
      </text>
    </declare>
  </script>

</dir>