<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmloaikh" table="dmloaikh" fieldKey="ma_loai" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục loại khách hàng" e="List of customer types"></title>
  <title0 v="Thêm mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
        <field name="ma_loai" format="U" label="1" field="1" allowBlank="false" fieldType="PK" >
          <text v="Mã loại khách hàng" e="Customer type code"></text>
        </field>
        <field name="ten_loai" label="1" field="2" allowBlank="false" fieldType="PK" >
          <text v="Tên loại khách hàng" e="Customer type name"></text>
        </field>
        <field name="ten_loai2" label="1" field="2">
          <text v="Tên khác" e="Other name"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>pX79fY+BQf9bV+YuDv83hJMo/wxnw3GwASqN3hT2Q83XvOvCQYPH4WAtYyOlPU7WtvVT7UzrKawZf+j9RVPYISI21DzDdZCwRXX+4pI5ZJCwpYAZx/w2BfQti0J7k7T+cKZoJcIC99zkEVdeDFZusAAFAK9Uexk/t0b4ROr0I3d3gZZt/vspq9EOTK7qxenkUHr4EgacIIxvczMV5SD4JOXKZLFN/q7+YB4JylCPN+/zxFMxT/JTeaaWrZhofakR9VsHhApD8UeLOCX/iwGgIVA/ilufsL+/a7xJmkMsF5wALSzWmMI3xTltuPW6K1uimzav8o/OC1n1OWVz9JoE83OlJJGODjubeMD0yKDXgeM=</enc>]]>
    </text>
  </js>

  <script>
    <declare>
      <text>
        <![CDATA[<enc>SL4IDJ241nDuu7oAbMYOlok0cYvrADysYzSGusQGF2UWtxqz/ESWYL737v0Csv840/+XVX7UOc2BS2QG9VzM1fTF8qK9/iw59M2ZTuhapKV6uDUwZ+XFxOTVLvjsc5LEr7/NGMZgz9q96ebgJnzpOhtEJsanPrJ/WslsdHTDqUN5FLkzZSzh3FmYCWrzAXo1XcXIgrApMc5LCu2lHlJmekNaMlCup7rV5VPY211CSQ6P9rsbXdwMm+4MYQlcWBI2gRxaCE+9jNw/goIKO27FoQ==</enc>]]>
      </text>
    </declare>
  </script>

</dir>