<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmlvt" table="dmlvt" fieldKey="ma_lvt" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục loại vật tư" e="Payment Methods List"></title>
  <title0 v="Mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
        <field name="ma_lvt" format="U" label="1" field="1" allowBlank="false" fieldType="PK" >
          <text v="Mã loại vật tư" e="Payment Methods Code"></text>
        </field>
         <field name="ten_lvt" label="1" field="-" allowBlank="false">
          <text v="Tên loại vật tư" e="Description"></text>
        </field>
        <field name="ten_lvt2" label="1" field="-" allowBlank="true">
          <text v="Tên khác" e="Other name"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>8wsLme4If9rNawhEvon3/QVwfjdEwm+/bFrzUcaSHduK+sAQWcKArI58vRdUwP1+IsXbUjSiItEst+oslRtxYbH/AeUSpLLLURoKHhXBRJieDpfqR3K8xGeepce32zcqI0JLUsb8hRpYlZ1py810LfM2bhDB0zGqvCgdjlSg/eK5TLz1IGqUUyQIAzRJ+P4P</enc>]]>
    </text>
  </js>

  <script>
    <declare>
      <text>
        <![CDATA[<enc>D8ieS6Kn3Xfstmj4kvf1je+3YqdKst2EPpaQlDEEDY5A6czA+IXCPe1qKQvh5zir8ZG3alprxb8eX3CMD53Ju2w6phAMhTfPIa2ISWeuqQ2BnT/Ux8CuklBSqF71zLVpZSGbWrVT1XFxM5oEC3ZSVi8Mhpf2VQISwr8sujlm+octZUqUUgqEh9Wj1JKx/yvqjKa7dV26iQyD6t1TGmnzugfy1vY7NN43scVAWbcoA2vifJTFtqD8TyN0vgSJF5Za</enc>]]>
      </text>
    </declare>
  </script>
  
</dir>