<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmnvbh" table="dmnvbh" fieldKey="ma_nvbh" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục nhân viên bán hàng" e="Saleman List"></title>
  <title0 v="Mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
        <field name="ma_nvbh" format="U" label="1" field="1" allowBlank="false" fieldType="PK" >
          <text v="Mã nhân viên" e="Saleman Code"></text>
        </field>
        <field name="ten_nvbh" label="1" field="-" allowBlank="false" >
          <text v="Tên nhân viên" e="Description"></text>
        </field>
        <field name="ten_nvbh2" label="1" field="-" allowBlank="true">
          <text v="Tên khác" e="Other name"></text>
        </field>
        <field name="nh_nv1" label="1" field="1" viewType="Lookup" clientDefault="true" allowBlank="true">
          <text v="Nhóm nhân viên 1" e="Saleman Group 1"></text>
          <viewInfo lookupType="One" lookupId="dmnh" lookupKey="ma_loai_nh = 'NV1' and status=1" lookupCheck="ma_loai_nh = 'NV1'" lookupRef="ten_nh_nv1" lookupInfo="dmnh|ma_nh|ten_nh" />
        </field>
        <field name="ten_nh_nv1" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
        <field name="nh_nv2" label="1" field="1" viewType="Lookup" clientDefault="true" allowBlank="true">
          <text v="Nhóm nhân viên 2" e="Saleman Group 2"></text>
          <viewInfo lookupType="One" lookupId="dmnh" lookupKey="ma_loai_nh = 'NV2' and status=1" lookupCheck="ma_loai_nh = 'NV2'" lookupRef="ten_nh_nv2" lookupInfo="dmnh|ma_nh|ten_nh" />
        </field>
        <field name="ten_nh_nv2" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
        <field name="nh_nv3" label="1" field="1" viewType="Lookup" clientDefault="true" allowBlank="true">
          <text v="Nhóm nhân viên 3" e="Saleman Group 3"></text>
          <viewInfo lookupType="One" lookupId="dmnh" lookupKey="ma_loai_nh = 'NV3' and status=1" lookupCheck="ma_loai_nh = 'NV3'" lookupRef="ten_nh_nv3" lookupInfo="dmnh|ma_nh|ten_nh" />
        </field>
        <field name="ten_nh_nv3" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
        <field name="ma_bp" format="U" label="1" field="1" viewType="Lookup" clientDefault="true" allowBlank="false" >
          <text v="Bộ phận" e="Department"></text>
          <viewInfo lookupType="One" lookupId="dmbp" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_bp" lookupInfo="dmbp|ma_bp|ten_bp" />
        </field>
        <field name="ten_bp" nextRow="false" fieldType="EX" readOnly="true" clientDefault="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
        <field name="user_id" dataType="I" hidden="true" readOnly="true" inactivate="true" label="1" field="1">
          <text v="User ID" e="User ID"></text>
        </field>
        <field name="username" fieldType="EXParam" viewType="Lookup" label="1" field="1">
          <text v="Tên đăng nhập" e="Username"></text>
          <viewInfo lookupType="One" lookupId="sysuserinfo" lookupKey="1=1" lookupCheck="1=1" lookupRef="nickname" lookupInfo="sysuserinfo|username|nickname" />
        </field>
        <field name="nickname" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>T5Nuk0XwnW0VlRYHOIM5VXhKO7/eOS+JOgvPzcIet9agoUDVC1alvxportOK0U1nNvpD6F/FcPTD8N9DkBEqmKYxJ9p4SErsSr1WJWx2BmwYx5LbU4B5BHzvmTlJqfWKNvXeYOk78JmeIgiu2fEHbuHwwLHri0J+6gEvwiANxAs2kRoM42ftWui1BMCuCjMr</enc>]]>
    </text>
  </js>

  <script>

    <query>
      <text>
        <![CDATA[<enc>Am611OXKgRIXY8qq+rH0XkpsOrmoeuFFIcK7708nwjAzMkGxBVNUnMUul/6owdIKzOszbQBDDvVuAyoRU0OdtPCy4akLOg9+7zQ1SARkEji48JHrKXuIdZJMaJA6LhRthlpFrCLfClou0/kEpmDAsDhwgnNWv5b7zUiUWl0ZQ1gP8Zyfw1rRApgia66cwE7mdNkNG7sybQWzI+lc1gIRmjYDdB9FCCGQ8LYCyHWIOiGEDB10A+1TyiDejXeRdoUp</enc>]]>
      </text>
    </query>
    
    <declare>
      <text>
        <![CDATA[<enc>hxQPm/hYhpvPifcenBxj7nfT+X4T8oXvYmZx4Kpwn3fRRVZY+foYIow2vt1OHdzq0lG6PkDpvnlKR1ei3AR28UkawCxswedTww8YMZ/ax/1/BVJZ6K0wvLOosliedaWZ/7pGMY7ZR7oT4bGVGiysGeFyKnyvmYcOO7B3Iswn1XDjzzQ16LqTgqvwwQhfRikVqLo7M/usPBGLryFIL4mvILdmXCE8Ze1nD1MxZZ8EkWv2LR2U0bXT0Ue8aUsALlWq</enc>]]>
      </text>
    </declare>

    <beforesave>
      <text>
        <![CDATA[<enc>t0ZGGiBEED6F1l6Y3sZcUwdlFNrunb5qvduUNSyNJm4DwhhRWTC59MCtYEAYDZTXz7ZhivoY4aZ9MtL6SfSdL0ifNCNZoYM48X5bi5nOvyB5D/iGk0E//zkppYR/mDLzuAVA0y7iBHxwQvj0N0nNrCaDp5JXYfErkBefYsXUP6HtHf0HTHhA2AYOXJiuj3CQGB1uWKfHshtjZrOIklPQMkTHHqIAnFpdweD+p34RpYGutmI1bA654A12j50mK7JK9Aye3JOR9teuoqAsdaT69Q==</enc>]]>
      </text>
    </beforesave>

    <updated>
      <text>
        <![CDATA[<enc>sxD5Swu0R4mcxEHdwcy2ynVkJ6IiRfsuHiDzDrC78ELIJg2k4xX5PxEITwgSuDtWSiTOU3sqnIo/Bv0T8e877gfuWsJ9mdOcaRiXyvCNT1dX5Mlqk5u4+w9hMhZcJlJkvLo92qpUZ/lmiToJRRFQOw==</enc>]]>
      </text>
    </updated>
  
  </script>

</dir>