<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>

<dir id="dmsvc" table="dmsvc" fieldKey="ma_svc" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục svc" e="SVC List"></title>
  <title0 v="Mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
        <field name="ma_svc" format="U" label="1" field="1" allowBlank="false" fieldType="PK" >
          <text v="Mã svc" e="svc code"></text>
        </field>
        <field name="ten_svc" label="1" field="2" allowBlank="false">
          <text v="Tên svc" e="svc name"></text>
        </field>
        <field name="ten_svc2" label="1" field="2" allowBlank="true">
          <text v="Tên khác" e="Other name"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>1PFOGp66gVgaSTPirrPUVVXHCZhYQQOqRHPLw9CqJ8kSjWjuDE6K6scEY1EFCyjLMfTFO6xsnlk+Sn0eKU+N+8PR5xnx1b3fNApe9V9yjImwrmeMjymVM7Xh2ZBD/mlhy4TfPWD3+VwaIvS7WFlD5t5y1cYbbWb3HbBw5kd9ZL/+jiixco2tjsjDFHW8GzYX0/flU4G47W/Wu9fN3byc7wzvjkXJcHliOXJmUdhbWXo12Bhw9Q/D51dqFdHYkNCKzDBOS6Ye/79sfU+q7PkU7bLkZJtxm4zNUKl4SETaxgXjYbpTbfRq0eYfIDpOwMuJOZeoRnGI58f/zZBahDj5Pw==</enc>]]>
    </text>
  </js>

  <script>
    <declare>
      <text>
        <![CDATA[<enc>hxQPm/hYhpvPifcenBxj7nfT+X4T8oXvYmZx4Kpwn3fRRVZY+foYIow2vt1OHdzq0lG6PkDpvnlKR1ei3AR28UkawCxswedTww8YMZ/ax/1/BVJZ6K0wvLOosliedaWZAZ0+m44mH1XC9z0Xct3FqXYwCF5xUw3Zhs7vAZwnzkMK69Cl5pklEiMPzi3UK22RWOa+Y4WimDEUKXZeIShpBMiWLXsHIF7sj/cy03X640w=</enc>]]>
      </text>
    </declare>
  </script>

</dir>