<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
  <!ENTITY ReportFilterItemGroup SYSTEM "..\Include\XML\ReportFilterItemGroup.xml">
  <!ENTITY ReportFilterStockType SYSTEM "..\Include\XML\ReportFilterStockType.xml">
  <!ENTITY ReportJSLoading SYSTEM "..\Include\XML\ReportJSLoading.xml">
  <!ENTITY ReportFilterUnit SYSTEM "..\Include\XML\ReportFilterUnit.xml">
  <!ENTITY ReportFiltering SYSTEM "..\Include\XML\ReportFiltering.xml">
  <!ENTITY ReportDataAnalysisStruct SYSTEM "..\Include\XML\ReportDataAnalysisStruct.xml">
]>

<dir id="bctkttgian" table="" height="" fieldKey="id" dirViewType="Dialog" dirObjectType="Report" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Báo cáo tồn kho theo thời gian" e="Aging Stock by Time" />

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDTo" clientDefault="true" allowBlank="false" dataType="D">
          <text v="Đến ngày" e="Date From/To"></text>
        </field>
        <field name="loai_ky" dataType="I" viewType="Combobox" valueDefault="2" label="1" field="1" >
          <text v="Kỳ tính tuổi" e="Analysis Period"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="Theo ngày" e="By Day"></text>
              </option>
              <option val="2">
                <text v="Theo tháng" e="By Month"/>
              </option>
            </options>
          </viewInfo>
        </field>
        <field name="chu_Ky" label="1" field="1" dataType="N" format="0" valueDefault="1">
          <text v="Chu kỳ tính tuổi" e="Analysis Time"></text>
        </field>
        <field name="so_ky" label="1" field="1" dataType="N" format="0" valueDefault="3">
          <text v="Số kỳ" e="Number of Period"></text>
        </field>
      </fields>
    </form>

    <form tabPageIndex="1" gravity="MiddleLeft" height="0" columns="120,120,120,120,120"  >
      <text v="Thông tin chung" e="General"></text>
      <fields>
        <field name="ma_kho" viewType="Lookup" label="1" field="1" operation="like">
          <text v="Mã kho" e="Site"></text>
          <viewInfo lookupType="One" lookupId="dmkho" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_kho" />
        </field>
        <field name="ten_kho" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
        <field name="ma_vt" viewType="Lookup" operation="like" label="1" field="1">
          <text v="Mã vật tư" e="Item"></text>
          <viewInfo lookupType="One" lookupId="dmvt" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_vt" />
        </field>
        <field name="ten_vt" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
        &ReportFilterItemGroup;
        &ReportFilterUnit;
        &ReportFilterStockType;
        &ReportFiltering;
        &ReportDataAnalysisStruct;
      </fields>
    </form>    
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>QE7uhHnLA6YrfHikU3ChHUDggfR/T61/5L9HJvJoDb2zFZRGRuivMc81KPMldwva0dMgBpc0J822y4HgBRPf3fM1zpg4iw7OEn53dT7CoJMzb0FYtxd4YQMkpYnkoVa7POruMuLKfozMOC3auB0uX7xusuz0rT7USfgEMhvLZifkQ0PybEjxEndJ3DGaga1Dbw4a+ijqDHVLjmrfkqR6sGNbLtatxpAhsU+QEOumLV4/1nLr/JJqIU6dRqUAv5uCqUM9i5rF5ms8qqN4aG8UXQ==</enc>]]>
    </text>
  </js>

  <script>
    <processing>
      <text>
        <![CDATA[<enc>AYIgDTpbYzicCrZfToT/PRnH1xbW/vCMe85IsuzYoGJTwbyiJ8xJ5d6d8cH/pemHUlkGIZC8JgHLupCEEWreT46byA1oEHkp9lQfihqfLIHMW2lOq1s/8ygobUVO1CxYUbhW9sBw3AUSw5EMo02ifDKzaMUTfxjOpKV+yfDONks=</enc>]]>
      </text>
    </processing>
    &ReportJSLoading;
  </script>
</dir>