<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">

]>

<dir id="dmbbct" table="" height="" fieldKey="ma_bbct" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Điều kiện lọc" e="Filter"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,240,120"  >
      <fields>
		<field name="ma_bbct" viewType="Lookup" label="1" field="[150]" operation="like">
			<text v="Mã biên bản" e="Report Code"></text>
			<viewInfo lookupType="One" lookupId="dmbbct" lookupKey="status = 1" lookupCheck="1=1" lookupRef="ten_bbct" lookupInfo="dmbbct|ma_bbct|ten_bbct"/>
        </field>
        <field name="ten_bbct" nextRow="false" readOnly="true" inactivate="true" label="" field="[150]" >
           <text v="" e=""></text>
        </field>
		<field name="status" viewType="Combobox" inactivate="true" label="1" field="[150]" operation="=" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
			  <option val="">
                <text v="Tất cả" e="All"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>GYD0OC5JhpEhu2renQHOp0G45y+Ym1vNMLhSnecDl27mD2BHzRANrgvtc3vljzuBpdwPL8AhFYb8Z1JukgFc/gKx+zdPmZ9xenVHd5N/cxfTvsoHThPCo/zpA9SmcapTk551W1hoKyD+OG1h5YVXwMzoZ1kEaOWRYaqqJhobHsm+L+JrGDyKSA/DV4jC5tIc</enc>]]>
    </text>
  </js>
  <script>

  </script>
</dir>