<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">

]>

<dir id="dmbencang" table="" height="" fieldKey="ma_ben" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Điều kiện lọc" e="Filter"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,240,120">
      <fields>
		<field name="ma_ben" viewType="Lookup" label="1" field="[150]" operation="like">
			<text v="Mã bến cảng" e="Port Code"></text>
			<viewInfo lookupType="One" lookupId="dmbencang" lookupKey="status = 1" lookupCheck="1=1" lookupRef="ten_ben" lookupInfo="dmbencang|ma_ben|ten_ben"/>
        </field>
        <field name="ten_ben" nextRow="false" readOnly="true" inactivate="true" label="" field="[150]" aliasName=" cast( '' as nvarchar(200)) as " >
           <text v="" e=""></text>
        </field>
		<field name="status" viewType="Combobox" inactivate="true" label="1" field="[150]" operation="=" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
			  <option val="">
                <text v="Tất cả" e="All"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>gjV3rCI/bNUFTHYsROWUJ1N6hz+C62kcZmQZHbv8ZG2oW0j9kcQGgxrNHKAh7fi36xpuEDCRQxQkfY+m2jNugNsTuDC/K3R8NnoaABRQtWgfwdI8mHQW24BHdXfvCixk96XtTie3weS6nG/Eu0OCMshvwQNRfduIZoBMitEt3x4AE56xnOa+OuqcZxWr7pXKQRHvxMfq3xC/vN/w//nH0g==</enc>]]>
    </text>
  </js>
  <script>

  </script>
</dir>