<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">

]>

<dir id="dmbp" table="" height="" fieldKey="ma_bp" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Điều kiện lọc" e="Filter"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,240,120"  >
      <fields>
		<field name="ma_bp" viewType="Lookup" label="1" field="[150]" operation="like">
			<text v="Mã bộ phận" e="Department code"></text>
			<viewInfo lookupType="One" lookupId="dmbp" lookupKey="status = 1" lookupCheck="1=1" lookupRef="ten_bp" lookupInfo="dmbp|ma_bp|ten_bp"/>
        </field>
        <field name="ten_bp" nextRow="false" readOnly="true" inactivate="true" label="" field="[150]" >
           <text v="" e=""></text>
        </field>
		<field name="status" viewType="Combobox" inactivate="true" label="1" field="[150]" operation="=" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
			  <option val="">
                <text v="Tất cả" e="All"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>Knm6eCC/JR/e71MIbEUVyQkHeja5hlrQi8seOgIg4B1CbB3I3Rj10499yUEAtg4oRj1rn2150Hp+akSK7qXoBYvgjzNlQQ64kGVi3qwDGTlCHWxW2SSpdEQ9w71FYenlQfYSEamuTpqUsInnHJh4NjZcPnqAgKDu7aYUw67s5vi0ioF9l49l53f9dIUH9/j0</enc>]]>
    </text>
  </js>
  <script>

  </script>
</dir>