<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">

]>

<dir id="dmchungtu" table="" height="" fieldKey="ma_ct" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Điều kiện lọc" e="Filter"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,240,120">
      <fields>
		<field name="ma_ct" viewType="Lookup" label="1" field="[150]" operation="like">
			<text v="Mã chứng từ" e="Voucher Code"></text>
			<viewInfo lookupType="One" lookupId="dmchungtu" lookupKey="status = 1" lookupCheck="1=1" lookupRef="ten_ct" lookupInfo="dmchungtu|ma_ct|ten_ct"/>
        </field>
        <field name="ten_ct" nextRow="false" readOnly="true" inactivate="true" label="" field="[150]" >
           <text v="" e=""></text>
        </field>
		<field name="status" viewType="Combobox" inactivate="true" label="1" field="[150]" operation="=" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
			  <option val="">
                <text v="Tất cả" e="All"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>GYD0OC5JhpEhu2renQHOp+wcdzj99072o/OC3Hj+M5230BT7wWo6GJkKELoahXNdN9Jtq1kk/wyn1kNFrUbm9Au3KFpsfE0WPzcpFYa1aZGknGWLE8ZcUsBLbzYIJrFZj6kz+T/9kXgWKi9nDsKjfWewpzeDPTrJ5R1nq/oT+xCUWUh/QtiquSDgxsoq9dKPK8PglItFkpYNPkgMab6mNg==</enc>]]>
    </text>
  </js>
  <script>

  </script>
</dir>