<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">

]>

<dir id="dmdonvi" table="" height="" fieldKey="ma_dv" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Điều kiện lọc" e="Filter"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,240,120"  >
      <fields>
		<field name="ma_dv" viewType="Lookup" label="1" field="[150]" operation="like">
			<text v="Mã đơn vị" e="Unit code"></text>
			<viewInfo lookupType="One" lookupId="dmdonvi" lookupKey="status = 1" lookupCheck="1=1" lookupRef="ten_dv" lookupInfo="dmdonvi|ma_dv|ten_dv"/>
        </field>
        <field name="ten_dv" nextRow="false" readOnly="true" inactivate="true" label="" field="[150]" >
           <text v="" e=""></text>
        </field>
		<field name="status" viewType="Combobox" inactivate="true" label="1" field="[150]" operation="=" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
			  <option val="">
                <text v="Tất cả" e="All"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>Yz0ptC4JBRSKhIpTcycdh+62DaCgwpe8Ay2o9IQfPbUGb3bY0tnzLRD7TvEZ+kslQy9mA3sLhQ/0Qg8+GxxNUPNCb/8H2YEDCzqoHy/EA1HoEE9MbQR1aBVeII8ZgyNjWzhYkRIXWS74qT/8Nq9q5T5F2b7VfmfgXTyqftglTcV1lGRzbpSpgzls3/TL3iZl</enc>]]>
    </text>
  </js>
  <script>

  </script>
</dir>