<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="dmdtcn" table="" height="" fieldKey="dien_thoai" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc thông tin điện thoại cá nhân" e="Filter personal information"></title>
  <title v="Danh mục điện thoại cá nhân" e="List of personal phone"></title>
  <forms>
    <form gravity="TopLeft" columns="120,120,120,120,120,120"  >
      <fields>
		<!-- <field name="datetime0" label="1" field="1" clientDefault="true" allowBlank="true" dataType="D"> -->
          <!-- <text v="Từ ngày" e="Date From"></text> -->
        <!-- </field> -->
        <!-- <field name="datetime2" label="" field="1" clientDefault="true" allowBlank="true" dataType="D" nextRow="false"> -->
          <!-- <text v="Đến ngày" e="Date To"></text> -->
        <!-- </field> -->
		<field name="ma_so_thue" label="1" field="[150]" operation="ma_so_thue like N'%%s%'">
          <text v="Mã số thuế" e="Tax Code"></text>
		</field>
		<field name="dien_thoai" label="1" field="[150]" dataType="N" importable="55" disabled="false" align="left" operation="dien_thoai like N'%%s%'" fieldType="PK">
			<text v="Điện thoại" e="Phone Number"></text>
		</field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>WlBokkiI0ufyqq2kyjTH64tp/9rL7aze+44qxEG0Oq/88E8//IQnfYyPIqWBZxiXn5+KgQKHGZQmZ7wt+IdGUYsvOuz5EOcnOKeVWbWUCP+bnrWpZueC9uiXuMqDoPpxd4B70bMaEvAOLvYDmpfOPFNjBanbV6AadjuP69FJ1dBCMzrZMZYtLaXZU4k83Hdd</enc>]]>
    </text>
  </js>
 
</dir>