<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">

]>

<dir id="dmdvt" table="" height="" fieldKey="dvt" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Điều kiện lọc" e="Filter"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,240,120">
      <fields>
		<field name="dvt" viewType="Lookup" label="1" field="[150]" fieldType="PK" operation="like" >
			<text v="Mã đơn vị tính" e="Units Code"></text>
			<viewInfo lookupType="One" lookupId="dmdvt" lookupKey="status = 1" lookupCheck="1=1" lookupRef="ten_dvt" lookupInfo="dmdvt|dvt|ten_dvt"/>
        </field>
        <field name="ten_dvt" nextRow="false" readOnly="true" inactivate="true" label="" field="[150]" operation="ten_dvt like N'%%s%'">
           <text v="" e=""></text>
        </field>
		<field name="status" viewType="Combobox" inactivate="true" label="1" field="[150]" operation="=" >
		  <text v="Trạng thái" e="Status"></text>
		  <viewInfo>
			<options>
			  <option val="1">
				<text v="1 - Còn sử dụng" e="1 - Use"></text>
			  </option>
			  <option val="0">
				<text v="0 - Không sử dụng" e="0 - Not use"></text>
			  </option>
			  <option val="">
				<text v="Tất cả" e="All"></text>
			  </option>
			</options>
		  </viewInfo>
		</field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>QilkekTP7q3HJ2zAnQ9TmRdNB3npgDIEAfMq0IKSTPT0uXvQQuQJ0ScSRQ8La+rqfm/nIFQ8PZd7iVyhlNNwtSPiYXtFjKA5I4R/bHjc3yy6FRzJpYaOAcgCWONHJ6mvdoaA9Lc/ZRToWjMWe5DrGsFzsBaWKKTIUqJFn3vnkbQE85B2ftWYjOPe0GIt4a+b</enc>]]>
    </text>
  </js>
  <script>

  </script>
</dir>