<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">

]>

<dir id="dmhaiquan" table="" height="" fieldKey="ma_hq" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Điều kiện lọc" e="Filter"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,240,120">
      <fields>
		<field name="ma_hq" viewType="Lookup" label="1" field="[150]" operation="like">
			<text v="Mã hải quan" e="Customs Code"></text>
			<viewInfo lookupType="One" lookupId="dmhaiquan" lookupKey="status = 1" lookupCheck="1=1" lookupRef="ten_hq" lookupInfo="dmhaiquan|ma_hq|ten_hq"/>
        </field>
        <field name="ten_hq" nextRow="false" readOnly="true" inactivate="true" label="" field="[150]" aliasName=" cast( '' as nvarchar(200)) as " >
           <text v="" e=""></text>
        </field>
		<field name="status" viewType="Combobox" inactivate="true" label="1" field="[150]" operation="=" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
			  <option val="">
                <text v="Tất cả" e="All"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>FX6/CwAQ8MlKX3V0i7zucqZlDM1ECYalh67Q7uryD2kDjLB7sE9Dk2P0nrK1iITmS8HCV/vZ2G97DFIVirlqHNLi8T0UIqrMhDwWVLCpDnLyAW222srCbEurGEThpZEx0tHqi9BClZedx3rKYn5qPaV/ukY2nF9RGwdgyLtz2/0mmSyN/8g+zSvIhDJrFSleuYiT9sGxP8ecWWgGURoELg==</enc>]]>
    </text>
  </js>
  <script>

  </script>
</dir>