<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">

]>

<dir id="dmhccong" table="" height="" fieldKey="ma_bp" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Điều kiện lọc" e="Filter"></title>
  <forms>
    <form gravity="TopLeft" columns="120,120,240,120"  >
      <fields>
	  	<field name="ma_hccong" label="1" field="2" operation="like">
			<text v="Mã hành chính công" e="Public Administration Code"></text>
        </field>
	  	<field name="ten_hccong" label="1" field="2" operation="like">
			<text v="Tên hành chính công" e="Public Administration Name"></text>
        </field>
		<field name="status" viewType="Combobox" label="1" field="1" operation="like" >
          <text v="Trạng thái" e="Status"></text>
		  <viewInfo>
			<options query="select ma_tt, ten_tt%l from dmttsd where status = 1 ">
				<option val="">
                <text v="Tất cả" e="All"></text>
              </option>
			</options>
		  </viewInfo>
		</field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>uw3iZoR/y/5o6FF1x5y/2ftOFjRRVUdz0db9XsETGXW2csJ+55RApbYqhNNPcOasgxC/+62TAV62YzUA319ozFrsdiQVES72sXneHr4mA1JV5AoWLax21/kgJnEZoDZcZN3sdRqh0OUP0MOPic2Ad8A5jFtotliBB0Zrt8apGpBDRJThBJ79dzHLXN4ikrgV</enc>]]>
    </text>
  </js>
  <script>

  </script>
</dir>