<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">

]>

<dir id="dmlhhd" table="" height="" fieldKey="ma_bp" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Điều kiện lọc" e="Filter"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,240,120"  >
      <fields>
	  	<field name="ma_lhhd" label="1" field="2" operation="like">
			<text v="Mã loại địa điểm" e="Location Type Code"></text>
        </field>
	  	<field name="ten_lhhd" label="1" field="2" operation="like">
			<text v="Tên loại địa điểm" e="Location Type Name"></text>
        </field>
		<field name="status" viewType="Combobox" label="1" field="1" operation="like" >
          <text v="Trạng thái" e="Status"></text>
		  <viewInfo>
			<options query="select ma_tt, ten_tt%l from dmttsd where status = 1 ">
				<option val="">
                <text v="Tất cả" e="All"></text>
              </option>
			</options>
		  </viewInfo>
		</field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>lEVRYe7GzDZqWzWfpmfh9fjFAzhYe+OaAHRhSKu3uTXBCiV/QfTwkMaL/28uScNB25pm350raQLPC3lPU8jD26YiAl47uJzpdnU6GTmrVi9bh6mFF/DX2GeEL9r+kBbTV47O4kfsYqZSQkOneNn6tk+xE7bxU3CMRE5RpwOh/xy3+RydE8i3jSeU99oeLVkO</enc>]]>
    </text>
  </js>
  <script>

  </script>
</dir>