<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">

]>

<dir id="dmllocation" table="" height="" fieldKey="ma_bp" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Điều kiện lọc" e="Filter"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,240,120"  >
      <fields>
	  	<field name="ma_llocation" label="1" field="2" operation="like">
			<text v="Mã loại địa điểm" e="Location Type Code"></text>
        </field>
	  	<field name="ten_llocation" label="1" field="2" operation="like">
			<text v="Tên loại địa điểm" e="Location Type Name"></text>
        </field>
		<field name="status" viewType="Combobox" label="1" field="1" operation="like" >
          <text v="Trạng thái" e="Status"></text>
		  <viewInfo>
			<options query="select ma_tt, ten_tt%l from dmttsd where status = 1 ">
				<option val="">
                <text v="Tất cả" e="All"></text>
              </option>
			</options>
		  </viewInfo>
		</field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>q7+KGkfD8dtajlmczdPHco7rWQ2FEklEgdR3vb6ZpUFvA1DuFcUo6TjIhDylyM1pNOEVZHBI7gkQvhX9qYqhKBVK/miDgiLPNL7hdL6O64oWvRGwxqCF6E4nqzhkoSfJQUKgxSYFFe61cjdxwmjI+aUTJAgtoNnOEt8RqHRrL0JVWbqEpGdlupPgIFA3XM3g</enc>]]>
    </text>
  </js>
  <script>

  </script>
</dir>