<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">

]>

<dir id="dmloaingaycong" table="" height="" fieldKey="ma_loaingaycong" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Điều kiện lọc" e="Filter Condition"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,240,120"  >
      <fields>
		<field name="ma_loaingaycong" viewType="Lookup" label="1" field="1" operation="like">
			<text v="Mã loại" e="Type code"></text>
			<viewInfo lookupType="One" lookupId="dmloaingaycong" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_loaingaycong" lookupInfo="dmloaingaycong|ma_loaingaycong|ten_loaingaycong"/>
        </field>
        <field name="ten_loaingaycong" nextRow="false" readOnly="true" inactivate="true" label="" field="-" >
           <text v="" e=""></text>
        </field>
		<field name="status" viewType="Combobox" inactivate="true" label="1" field="[150]" operation="=" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
			  <option val="">
                <text v="Tất cả" e="All"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>C4p2jMw8Vy17Izk5sH9be2dCOFbL/uPpGkPzWGsrg9lc4Bjcj1z5YX7hR4bzNdtFEI0bJZHYVeYiD8HMA5V2snRKej6zklrqudw520dlh/7AEAGxyK1Fj6zqXHY1X0cbJ5xT+fa/HCi5SOVtVnwRufL9GZ3iPcKxdOAUEpnl4KwarpPhfi6KtleerKB132L+A7AprjKixqc3ydW87aVyDA==</enc>]]>
    </text>
  </js>
  <script>

  </script>
</dir>