<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">

]>

<dir id="dmloaikh" table="" height="" fieldKey="ma_loai" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Điều kiện lọc" e="Filter"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,240,120"  >
      <fields>
		<field name="ma_loai" viewType="Lookup" label="1" field="[150]" operation="like">
			<text v="Mã loại" e="Type Code"></text>
			<viewInfo lookupType="One" lookupId="dmloaikh" lookupKey="status = 1" lookupCheck="1=1" lookupRef="ten_loai" lookupInfo="dmloaikh|ma_loai|ten_loai"/>
        </field>
        <field name="ten_loai" nextRow="false" readOnly="true" inactivate="true" label="" field="[150]" >
           <text v="" e=""></text>
        </field>
		<field name="status" viewType="Combobox" inactivate="true" label="1" field="[150]" operation="like" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>uw3iZoR/y/5o6FF1x5y/2Rn3k63sCG7H5nNR5cJXgIcY9XhiKhsIa7ZcJ86SIqoZwGvTsXLPPb+wpbMVt0YoPzzOtu2g7+r7E/xpOs5E3TAXVzXT6jwwlN3KB9Zvs1HdXYi5QP7d0yfadGqqnwYDCGhiJtOiwTe78Wb9sNhbTrmi5FkW7VbRo5R8QqbgeujHie6Qjtn2tUDNZZv9cb/AxA==</enc>]]>
    </text>
  </js>
  <script>

  </script>
</dir>