<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">

]>

<dir id="dmnganhnghe" table="" height="" fieldKey="ma_nganhnghe" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Điều kiện lọc" e="Filter Condition"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,240,120"  >
      <fields>
	  	<field name="ma_nganhnghe" label="1" field="2" operation="like">
			<text v="Mã ngành nghề" e="Occupation Code"></text>
        </field>
	  	<field name="ten_nganhnghe" label="1" field="2" operation="like">
			<text v="Tên ngành nghề" e="Occupation Name"></text>
        </field>
		<field name="status" viewType="Combobox" label="1" field="1" operation="like" >
          <text v="Trạng thái" e="Status"></text>
		  <viewInfo>
			<options query="select ma_tt, ten_tt%l from dmttsd where status = 1 ">
				<option val="">
                <text v="Tất cả" e="All"></text>
              </option>
			</options>
		  </viewInfo>
		</field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>res7o41ZyxV7ie5eKEA1Ff8dJ8MdoegOAJ8/k9kn+1yjIo0xhukGIuO2bf1PjvTei+TPburAot0gtdooA1KwCwqpczVR2yuCzve0Ka+WLiGh9/CejNUI7TNp6dfOz2cR5WDngtw6JdiYSz8Pd4lcivDHoEqG1XQ5yXw2FbFSEJD49PBr5PegJrl1X8/eO6UiAJ8Iq3ofPBUFLB91KSiApg==</enc>]]>
    </text>
  </js>
  <script>

  </script>
</dir>