<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="dmnhomvb" table="" height="" fieldKey="ma_nvb" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Điều kiện lọc" e="Filter Condition"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120,120" >
      <fields>
		<field name="ma_nvb" inactivate="false" label="1" field="-" operation="like" >
			<text v="Mã nhóm văn bản" e="Document Group Code"></text>
		</field>
		<field name="ten_nvb" inactivate="false" label="1" field="-" operation="ten_nvb like N'%%s%'">
			<text v="Tên nhóm văn bản" e="Document Group Name"></text>
		</field>
		<field name="ten_nvb2"  inactivate="false" label="1" field="-" operation="ten_nvb2 like N'%%s%'">
          <text v="Tên tiếng anh" e="English Name"></text>
		</field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>uw3iZoR/y/5o6FF1x5y/2Wzf7tsKdb3VvfjGafCdeuuI1cqvp9jkG4ff8esbjl5rnQCssHzb3JqASLx53fCwMDTpR1Vx3HRXLIcC4ylXBo3fSnWbXn+avnYPi+9hw49c+iPeSha1VdPkI999XLMbBpMRSVvPRba9k37TLCqCq1zaZozjAVk95QUfKJo0L+4FsqW5816kscKBghnQQVtUWg==</enc>]]>
    </text>
  </js>
 
</dir>