<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="dmnv" table="" height="" fieldKey="ma_nv" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Điều kiện lọc" e="Filter"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,240,120"  >
      <fields>

		<field name="ma_ttp" viewType="Lookup" label="1" field="1" operation="like">
			<text v="Quê quán" e="Position"></text>
			<viewInfo lookupType="One" lookupId="dmttp" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_bp" lookupInfo="dmttp|ma_ttp|ten_ttp"/>
        </field>
        <field name="ten_ttp" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
           <text v="" e=""></text>
        </field>
		

      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>991dreUclXKCZhE5yCus3X/kA21akm4qmDhYVZ7xQCmJvB5rKirUnUl3lWRieScWr4OM1O9ysptc8Dwb6rSHy5+o280kjtO2yI4bEoPoctjfqFyOJL4iRvlktzeqD/NfHPhfczTAJrJIzG7aNq7V4Soi4qVtfQ52L0x3dyBv7DAQSwCm0Z/ej8i5ex5Cq6fw</enc>]]>
    </text>
  </js>

  <script>
    &VoucherJSLoading;
  </script>
</dir>