<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">

]>

<dir id="dmphuongxa" table="" height="" fieldKey="ma_phuongxa" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Điều kiện lọc" e="Filter Condition"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,240,120"  >
      <fields>
	  	<field name="ma_phuongxa" label="1" field="2" operation="like">
			<text v="Mã phường/xã" e="Ward/Commune Code"></text>
        </field>
	  	<field name="ten_phuongxa" label="1" field="2" operation="like">
			<text v="Tên phường/xã" e="Ward/Commune Name"></text>
        </field>
		<field name="status" viewType="Combobox" label="1" field="1" operation="like" >
          <text v="Trạng thái" e="Status"></text>
		  <viewInfo>
			<options query="select ma_tt, ten_tt%l from dmttsd where status = 1 ">
				<option val="">
                <text v="Tất cả" e="All"></text>
              </option>
			</options>
		  </viewInfo>
		</field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>IaQNzlrpr3uhtbTfLXTJBQRFIOknmpPdqVGGMd9Y09c6ZXVfhsXV7qUhEnWQETH+hArYNtFKCSZh7iPRqef+QS7YeFdnYJM239K2BnWdF9v9fhiF3Voa4uIL5Us+dO1nbeAShm62wFrPrZjExCa8dDTevcwpKIB5JReM9w6SW9UacbMOyOSBQffsHSLjMSJFYmfilmNHYChb2TeNWSwl8g==</enc>]]>
    </text>
  </js>
  <script>

  </script>
</dir>