<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">

]>

<dir id="dmphi" table="" height="" fieldKey="ma_phi" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Điều kiện lọc" e="Filter"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,240,120"  >
      <fields>
		<field name="ma_phi" viewType="Lookup" label="1" field="[150]" operation="like">
			<text v="Mã phí" e="Fee Code"></text>
			<viewInfo lookupType="One" lookupId="dmphi" lookupKey="status = 1" lookupCheck="1=1" lookupRef="ten_phi" lookupInfo="dmphi|ma_phi|ten_phi"/>
        </field>
        <field name="ten_phi" nextRow="false" readOnly="true" inactivate="true" label="" field="[150]" >
           <text v="" e=""></text>
        </field>
		
		<field name="ma_dvt" viewType="Lookup" label="1" field="[150]" operation="like">
			<text v="Mã đơn vị tính" e="Unit Code"></text>
			<viewInfo lookupType="One" lookupId="dmdvt" lookupKey="status = 1" lookupCheck="1=1" lookupRef="ten_dvt" lookupInfo="dmdvt|dvt|ten_dvt"/>
        </field>
        <field name="ten_dvt" nextRow="false" readOnly="true" inactivate="true" label="" field="[150]" >
           <text v="" e=""></text>
        </field>
		<field name="status" viewType="Combobox" inactivate="true" label="1" field="[150]" operation="=" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
			  <option val="">
                <text v="Tất cả" e="All"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>0MRgY+MgdWwcIeuPCwL/s6YB7+LEJ5DeBrxPjbgt85Qfuj8vpHFRO0vzjXxw7rEhWP939q+B2yq9TTTqs+a/mk8GxjjvEx4FJz1eFcb/yNZ+D2De6XlERocWWf5JIYwcgFOpTruUWNa9oA8QdeEY+peCTQkHXHSfp2cIl4rJWMzCxFSRc89obnZv20O+2YZe</enc>]]>
    </text>
  </js>
  <script>

  </script>
</dir>