<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">

]>

<dir id="dmttxe" table="" height="" fieldKey="ma_xe" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Điều kiện lọc" e="Filter"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,240,120">
      <fields>
	  
		<field name="ma_xe" viewType="Lookup" label="1" field="[150]" operation="like">
			<text v="Mã xe" e="Vehicle Code"></text>
			<viewInfo lookupType="One" lookupId="dmttxe" lookupKey="status = 1" lookupCheck="1=1" lookupRef="ten_xe" lookupInfo="dmttxe|ma_xe|ten_xe"/>
        </field>
        <field name="ten_xe" nextRow="false" readOnly="true" inactivate="true" label="" field="[150]" >
           <text v="" e=""></text>
        </field>
		
		<field name="tt_xe" viewType="Lookup" label="1" field="[150]" operation="like">
			<text v="Mã xe" e="Vehicle Code"></text>
			<viewInfo lookupType="One" lookupId="dmbgn" lookupKey="status = 1 and ma_ct ='TXE' " lookupCheck="1=1" lookupRef="ten_bgn" lookupInfo="dmbgn|ten_ma|ten_bgn"/>
        </field>
        <field name="tt_xe" nextRow="false" readOnly="true" inactivate="true" label="" field="[150]" >
           <text v="" e=""></text>
        </field>
		
		<field name="status" viewType="Combobox" inactivate="true" label="1" field="[150]" operation="=" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
			  <option val="">
                <text v="Tất cả" e="All"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>GYD0OC5JhpEhu2renQHOp0G45y+Ym1vNMLhSnecDl26lOXotAbnmcjKe9tTyfRtcdcO6wWPNSO9a530i8I7fv6mdlYMrDnKJciJoQoskwj0aJzutGzLjYwvMrexj3gugUXeXH1OSj82nRBm1YI5H+k9AKTSrzDVBF/IXaHXzOtz6/DOq4hdHHczEAV4aI7zJ</enc>]]>
    </text>
  </js>
  <script>

  </script>
</dir>