<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">

]>

<dir id="dmxe" table="" height="" fieldKey="ma_xe" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Điều kiện lọc" e="Filter"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,240,120">
      <fields>
		<field name="ma_xe" viewType="Lookup" label="1" field="[150]" operation="like">
			<text v="Mã xe" e="Vehicle Code"></text>
			<viewInfo lookupType="One" lookupId="dmxe" lookupKey="status = 1" lookupCheck="1=1" lookupRef="ten_xe" lookupInfo="dmxe|ma_xe|ten_xe"/>
        </field>
        <field name="ten_xe" nextRow="false" readOnly="true" inactivate="true" label="" field="[150]" aliasName=" cast( '' as nvarchar(200)) as " >
           <text v="" e=""></text>
        </field>
		<field name="status" viewType="Combobox" inactivate="true" label="1" field="[150]" operation="=" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
			  <option val="">
                <text v="Tất cả" e="All"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>Knm6eCC/JR/e71MIbEUVySchOt4bbYuOqrFfIuWM2GS6tz9/sajFGQn9JVa+LMbrLGgh7bm9aDVBcwEACkTPpS1zclJuv6/bzWm1zGgotCDPRyExG5r8Lmm3hf4PhB4NfBUUQkAARM3db+keLxNyopIphQVSufBZCip1JLUP1TZ6srMXZyI+WIjRpKNL63Zk</enc>]]>
    </text>
  </js>
  <script>

  </script>
</dir>