<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="hrpermission" table="" fieldKey="user_id" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Phân quyền" e="Permission"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120">
      <fields>
        <field name="user_id" allowBlank="false" dataType="I" hidden="true" label="" field="1">
          <text v="" e=""></text>
        </field>
        <field name="username" disabled="true" >
          <text v="Tên" e="Name"></text>
          <viewInfo lookupType="One" lookupId="dmkho" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_kho" />
        </field>
        <field name="nickname" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
    <form tabPageIndex="1" gravity="MiddleLeft" height="400" columns="120,120,120" >
      <text v="Quyền bộ phận" e=""></text>
      <fields>
        <field name="dept_permission" fieldType="EX" hidden="true" label="1" field="1">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
    <form tabPageIndex="2" gravity="MiddleLeft" height="0" columns="120,120,120" >
      <text v="Quyền chức năng" e=""></text>
      <fields>
        <field name="menu_permission" fieldType="EX" hidden="true" label="1" field="1">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>MILY0XNyIswqHJfzeBNtXQkbnDc6miontiov/IjLGA6MYpaMn66Rs/otO6HSKgcLo7ZSpBp0zdcJ0qxBVEvIUyxAF5K0S8Xl5lxX0GgXMARZijU4+JbJ+oS8Lu2B15wQ7Egchd2AADaJpuJC/AQRPLtdzX4Ol10TY4byve4+QTZoxhpsNKbtECiuPAkmdbcFcKd89xyO0Tcd8inw59pVg9HNB8fDmhNqDh1e0ZcbzAiVqyUBi4MZRgyAP4p/neMJZGJJ18V1aHLLy/s65oZQRr0aHQ+ZjgNV0KiQOxRXjX5K8YabROegX4vewHUdfN4Nb6Og+8WDlJb2yHHfxarsuWnmM/dMPvY3LYssZQdF9CTuXBkOP4r9AM0rCp55ZErQzkYuwp5ODoqEmFnfsPdf93gelHW8saQ5q53bsTXeJF0U2ZJE0qit0+3tAKA+NZZsq2TZ/Dwqwbn9xt6i4MJ1tJi/1Anmi2JNBBcXoNxE8l5szYgJNmVTrZfINPRAXsJoP9GsDPhhYzVzMasoQyFyKdg82cDyHigQYi1pvCd5tn5aZVqn8x96hKsjEWfRyJFLcRmRa13WnItBCkYpagjBtsGh7+Xafijxbj0KGjNqTm/1C0qOFjeRHIqzYgoznIrq//s9L8Osx8yaZcWKmvHfz+yg67nMINep2vGOcbBBD1fGSdU69HpguK/4qaVVzi3n+T48UFPTCZnm0HR4NXfnqIR7QerdsA0z7NUvslm6gCY=</enc>]]>
    </text>
  </js>
  <css>
    <text>
      <![CDATA[<enc>d1GMZDcnarTxjQCuNVQuEALaQnS1NznPTNgawNkuxzFBYpUflhZCdG8YYGsUAvTkJabPKuxSyGeg8+ODFiBTWVGBVdtZ2u3R9XqoB9CBxPCZfl6FLRpR+gwgF6Y08790gjnJvU3Ef6KKd8UkV6YS969ESe5inB401Romk7Q9Xzc39gDnH3iBaam7n6WBv0z9</enc>]]>
    </text>
  </css>
  <script>
    <request code="getHRPermission">
      <text>
        <![CDATA[<enc>g+KZ+QKBlC+LdD0jHhpbmTbVfyMbiF0tkgA5TiyHiz3hjm0QFGwX2pWQ7wlTzSXFins5CPQaS09gKInyLkEGU6mzPXD0fHgGMVsoNva4K3Qun/2fWVx3Gb71Qa5SHG/XIWhAoHy46R7wjV9flgh6fw==</enc>]]>
      </text>
    </request>

    <request code="updateRight" transaction="true">
      <text>
        <![CDATA[<enc>Q7KyCVeUURfiYcrOqW+Smy66gM1iB11kQnC4bsG9ZmzU+SKPbuY0TlsHCc8gsmMBV5LlqwPrkw0csnpPPZxV+9MY7XDkLox7BOjF6xjwV5eKffth/zuVKIaV5J9v4VvqECpuzVywE5QVU0oqdOjBSiAdaWW3f2/kSq6BQF3Mfpz3TEw6ZI/WW1+o7thwsWiuQZM+Bv3rE5wjG3uYZL1SlJe5V725qhMbJD9BLzI/mRZFsUFNbwiBtP3VW6N96KOLjeQGXqodMx4CQhqJ5x9ibriZWTkulSIfN9eTMG+iNj1/ypI76RnwEy6IwC6bro7HEfcbMYjWsBevEDaNaiFiS2mNBiKGkuyIVji//BWLCNhpEWeMmZc3ZiP3unRRZ6ch2k1LpQSQ+Rq4mwJYf8r4iQ==</enc>]]>
      </text>
    </request>

  </script>

</dir>