<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
  <!ENTITY ReportFilterItemGroup SYSTEM "..\Include\XML\ReportFilterItemGroup.xml">
  <!ENTITY ReportFilterCustomerGroup SYSTEM "..\Include\XML\ReportFilterCustomerGroup.xml">
  <!ENTITY ReportFilterStockType SYSTEM "..\Include\XML\ReportFilterStockType.xml">
  <!ENTITY ReportJSLoading SYSTEM "..\Include\XML\ReportJSLoading.xml">
  <!ENTITY ReportFilterUnit SYSTEM "..\Include\XML\ReportFilterUnitHidden.xml">
  <!ENTITY ReportFiltering SYSTEM "..\Include\XML\ReportFiltering.xml">
  <!ENTITY ReportDataAnalysisStruct SYSTEM "..\Include\XML\ReportDataAnalysisStruct.xml">
]>

<dir id="khhdvhq" table="" height="" fieldKey="id" dirViewType="Dialog" dirObjectType="Report" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Kế hoạch hàng: Dịch vụ hải quan" e="Row Plan: Customs Service"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" clientDefault="true" allowBlank="false" dataType="D">
          <text v="Ngày từ/đến" e="Date From/To"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" aliasName="@DFDTo" clientDefault="true" allowBlank="false" dataType="D" nextRow="false">
          <text v="" e=""></text>
        </field>
		
		<field name="ma_gd" viewType="Lookup" label="1" field="1" operation="like">
          <text v="Type Log" e="Type Log"></text>
          <viewInfo lookupType="One" lookupId="dmloailog" lookupKey="status = 1" lookupCheck="1=1" lookupRef="ten_loai" />
        </field>
        <field name="ten_loai" nextRow="false" fieldType="EX" readOnly="true" disabled="true" label="" field="1">
          <text v="" e=""></text>
        </field>
		
		<field name="ma_job" viewType="Lookup" label="1" field="1" operation="like">
          <text v="Mã Job" e="Job Code"></text>
          <viewInfo lookupType="One" lookupId="vdmjob" lookupKey="status = 1" lookupCheck="1=1" lookupRef="ten_job" />
        </field>
        <field name="ten_job" nextRow="false" fieldType="EX" readOnly="true" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
		
	    <field name="ma_kh" viewType="Lookup" label="1" field="1" operation="like">
          <text v="Mã khách hàng" e="Customer"></text>
          <viewInfo lookupType="One" lookupId="dmkh" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_kh" />
        </field>
        <field name="ten_kh" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
		
        <field name="ma_kh_g" viewType="Lookup" label="1" field="1" operation="like">
          <text v="Người nhận" e="Consignee"></text>
          <viewInfo lookupType="One" lookupId="dmkh" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_kh_g" />
        </field>
        <field name="ten_kh_g" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
		
		 <field name="ma_nv" viewType="Lookup" label="1" field="1" operation="like">
          <text v="Mã nhân viên" e="Employee Code"></text>
          <viewInfo lookupType="One" lookupId="vdmnvbh" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_nv" />
        </field>
        <field name="ten_nv" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
		&ReportFilterUnit;
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>GYD0OC5JhpEhu2renQHOp/Q0K6oePH/TJN4iqm/LT9rY0dm04X1ljy/f9aDn6CEZ1en6ADJzzEs6vc46ivrYYO/Oky4SNOTr0b9WcR1wGxSVcp2a0H7ud15XWGi52nwKPBqQKRZ2ORjYUHSWYSiqbmXmC0XNq6yoWpoa6UX/s/UPYMHwD9Np9QxqQ/fyIT/JKnmQr6+So5Yz9oNhvfOHQg==</enc>]]>
    </text>
  </js>

  <script>
    <processing>
      <text>
        <![CDATA[<enc>TN45BLVvlQZWD1bhImJFui3B6za/B5OT7CPnricv7F9VxXndoQI7mrkZhe35dbbb</enc>]]>
      </text>
    </processing>
    &ReportJSLoading;
  </script>
</dir>