<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="l11BQ1" fieldKey="id" voucherCode="CR1" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc báo giá nhanh" e="Quick Quote Filtering"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D">
          <text v="Ngày từ/đến" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" aliasName="@DFDTo" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D" nextRow="false">
          <text v="" e=""></text>
        </field>
		<field name="ma_noi_di" viewType="Lookup" disabled="false" label="1" field="1" operation="like">
			<text v="Nơi đi" e="Origin "></text>
			<viewInfo lookupType="One" lookupId="vdmcangdi" lookupKey="(kkh_yn = 1 or hc_yn = 1) and status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_di" />
		</field>
		<field name="ten_noi_di" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="ma_noi_den" viewType="Lookup" disabled="false" label="1" field="1" operation="like">
			<text v="Nơi đến" e="Destination"></text>
			<viewInfo lookupType="One" lookupId="vdmcangden" lookupKey="(kkh_yn = 1 or hc_yn = 1) and status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_den"  />
		</field>
		<field name="ten_noi_den" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>  
		 <field name="so_ct" label="1" field="1" allowBlank="false" viewType="Lookup">
          <text v="Lấy số báo giá" e="Get a quote number"></text>
          <viewInfo lookupType="one" lookupId="s41" lookupRef="ds_so_bg" lookupKey="ngay_ct between ![ngay_ct1]! and ![ngay_ct2]! and ma_noi_di like ![ma_noi_di]! +'%' and ma_noi_den like ![ma_noi_den]! +'%'  and status in (5,6)" lookupCheck="ma_kh = ![ma_kh]! and status in (5,6) and ma_nt = ![ma_nt]!" />
        </field>
        <field name="ds_so_bg" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
	
	
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>H6lgBu6hcsf2ESwZXzTk9Hr8p35+q0smxe9akdKYFushMBCTHeGdMlz9Kng6QnKA1HkYcD+zZgx0++k8Je9IcDZNbUa5orLcI++F9Qk1UI/nf3vz70J/2voZ2KS28fHOgJHK7Y3HHnU1KhyG0FELDPvCxWYDV/jiBDB3RGvqvTtXmUhf3fyjp9a/hG5R/32XHgMKmNCm6AdmehqAMDZgPljuZ9yfLmJ902tqrfhupZa4hA1OONqPOqgiWD2Bgtu1LdooKedRF2sBb3uvU1/gz+NrzfvnK/SaJl4Rpz9P93mSE3r7VUGDxDu9heXOU8mFDafKPUpLA94/b5rqjGm950sMKQvK6NbkKwDUJyh82stE6FbXDvrNG3r5YYNttYkMnE+KyqQkjacqxuECc9LbHWADgi1UCnj54Acj8spnZLQunBydqrbOt7tAgiSBHDu81CycVAdY5XaVahlbiboVz1m8G+edmivpYIWfoBsWjrtVHjUaS1nIW6WQ3rcT9jdIvFJGw3T16NK2JzxKiOKN4C5er3CFD0Cpv6XJZXEE5VxRrDp+FSdk0rJiMsTcTVgFrgP8mCWl8ssyrTw25BluQQ==</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>