<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="m45BQ1" fieldKey="id" voucherCode="BQ1" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc số báo giá FCL" e="Filter FCL Quotes Numbers"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" allowBlank="false" dataType="D">
          <text v="Ngày c/từ từ/đến" e="From Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" allowBlank="false" inactivate="true" dataType="D" nextRow="false">
          <text v="Ngày đến" e="To Date"></text>
        </field>
       
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>
		
        <field name="ma_noi_di" viewType="Lookup" disabled="false" label="1" field="1" operation="like">
			<text v="Nơi đi" e="Origin "></text>
			<viewInfo lookupType="One" lookupId="vdmcangdi" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_di" />
		</field>
		<field name="ten_noi_di" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="ma_noi_den" viewType="Lookup" label="1" field="1" operation="like">
			<text v="Nơi đến" e="Destination"></text>
			<viewInfo lookupType="One" lookupId="vdmcangden" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_den"  />
		</field>
		<field name="ten_noi_den" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>  
			
		 <field name="id_bg" label="1" field="1" allowBlank="false">
          <text v="Số báo giá" e="Get the order number"></text>
        </field>
      </fields>
    </form>
	
	
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>6zqcKTM+BlB9FgSJhQ+uJgPQQfhyxsrbNXf29rMnSnGf+BTgzgCi7bRmbRWp9TAtRagwxChbnpQfdqEhaFD0yqnfp2CCCv7ucvm6/qXcMhISYtQYVZNULKudlF1gkCesr8QsuFf+5/9WPJDXOKLzqoDyxeDuTHBypGqB5fq6LqcJYHPKRy+uVhQyX/MFcm0zGeBolFK27LJA1BODqV8v5qF7/Vv6qCk1KsIRsJybfq4o4iKiR/lB35fQIaONFEuOiMZ/1srX0Pc2oMWBZ5bfXH0ZDk+gY/dvXmdlFFuXJo2iwu4UMJ9h9tArg9ZKjz006dS4dytgI///2vaBBpZgSNg4gEiF2+1a/TXZmPkwQBGRbK6IvJcgWKUi1o6d9faqlRZtBkUCDxLy2zc0xpNPg6ftEnRG354LI4kIOpZ/BmZ9hF8H5oZHGPozl1y+33peRqmdSgCYsTpCCUN6rid2Nm79+g9efkziXpQ8ESWrsGmQYG9ZjOucqbywTX693H53xmpZQdfzPeSIWLs85A2+COC+jZTKHjRuZxiZXFHtr2thfhpUu4AzinMBvQmhNYhppkXnAVgRk8tIZ9nc8AHT4JQdibPWYlNJb5kGKmegk03fn14H0I9djV0blNDJQ9VU</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>