<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="m45CR1" fieldKey="id" voucherCode="CR1" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc số đơn hàng FCL" e="Filter FCL Order Numbers"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D">
          <text v="Ngày từ/đến" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" aliasName="@DFDTo" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D" nextRow="false">
          <text v="" e=""></text>
        </field>
       
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>	
        <field name="ma_noi_di" viewType="Lookup" disabled="false" label="1" field="1" operation="like">
			<text v="Nơi đi" e="Origin "></text>
			<viewInfo lookupType="One" lookupId="vdmcangdi" lookupKey="(kkh_yn = 1 or hc_yn = 1) and status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_di" />
		</field>
		<field name="ten_noi_di" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="ma_noi_den" viewType="Lookup" label="1" field="1" operation="like">
			<text v="Nơi đến" e="Destination"></text>
			<viewInfo lookupType="One" lookupId="vdmcangden" lookupKey="(kkh_yn = 1 or hc_yn = 1) and status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_den"  />
		</field>
		<field name="ten_noi_den" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>	
		 <field name="so_ct" label="1" field="1" allowBlank="false" viewType="Lookup" operation="like">
          <text v="Lấy số đơn hàng" e="Get the order number"></text>
          <viewInfo lookupType="one" lookupId="s611" lookupRef="ds_so_dh" lookupKey="ngay_ct between ![ngay_ct1]! and ![ngay_ct2]! and ma_noi_di like ![ma_noi_di]! +'%' and ma_noi_den like ![ma_noi_den]! +'%'" lookupCheck="ma_noi_di like ![ma_noi_di]! and ma_noi_den like ![ma_noi_den]!  and status in (5,6)" />
        </field>
        <field name="ds_so_dh" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>	
      </fields>
    </form>
	
	
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>H6lgBu6hcsf2ESwZXzTk9OiH5DFHt28M9l/fcQmr2tcllrLRgaFGFZ+u1Inu8Pf4xvELXiDQG8b2hVI8d4jA/v8pIaJQeIZhJHHLKTTQJyIZnH5zRiTeE5zmYW/w038T4bfuBzeLm7BsB3TZQ1uA5iGOacBcmdQYpNpcvYWqHUm55+kUwT+b3DerODIP/8AAo4uG7es0hHyoRTUmqXEWFOcVW+uiEdZrgQCJkR3bf7X1vgS2sMaGsNpfwjf7Odz0022RhgIIE18gW3f8n0D8mHXPn7s6RsdeTovGRVe0vxrkHr28f5oHEGNHpEiN6JJOt20vxcn2SB+QvDMz+VzXivJySblu3iuUHED4usBOSjlHbCZy1g4FIEuFPd5nJkWymE+6V8+3r6/O98e/uYx/N1mJt8Bc8i60JKvwXdCJaldFAva/Qd+uEjLN7SZrB/U68a38O1ubq+3MJ0HrVCrM+XbQaKKd8B6rffR2H9s317Q+CH3dXv4k76ldbwUIVdK+qHlDUiwrM4H9KRcNLQ+ylh0SByMHc4XxVyTriCqCGWWJobtfifa8SJ5ujW1Mlk3L</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>