<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
  <!ENTITY VoucherExtendFields SYSTEM "..\Include\XML\VoucherExtendFields.xml">
]>

<dir id="m48_1Select" table="" height="" fieldKey="id" voucherCode="BQ1" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Chi tiết phiếu được chọn" e="Quotation Entry Detail"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
		<field name="ngay_ct1" label="1" field="1" readOnly="true" aliasName="@DFDFrom" disabled="true" allowBlank="false" dataType="D">
          <text v="Ngày c/từ từ/đến" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" allowBlank="false" disabled="true" inactivate="true" dataType="D" nextRow="false">
          <text v="Ngày đến" e="Voucher Date"></text>
        </field>
        <field name="ma_nt" hidden="true" label="1" field="1">
          <text v="Mã ngoại tệ" e="Ex Code"></text>
        </field>
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>

		<field name="ma_kh" label="1" disabled="true"  field="1" >
          <text v="Mã người thanh toán" e="Payer Code"></text>
        </field>
		<field name="ten_kh" allowBlank="true" label="1" disabled="true"  field="-" importWidth="250" importable="10">
          <text v="Tên người thanh toán" e="Payer Name"></text>
        </field>
		
        <field name="xprocess" label="1" field="2" valueDefault="2" viewType="Combobox">
          <text v="Xử lý" e="Process"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="Thêm vào chi tiết" e="Append To Detail"></text>
              </option>
              <option val="2">
                <text v="Xóa hết chi tiết và thêm mới" e="Delete All Detail And Append New"></text>
              </option>
            </options>
          </viewInfo>
        </field>
		<field name="id" dataType="N" hidden="true" fieldType="PK" label="1" field="1"  >
			<text v="ID" e="Code"></text>
		</field>
      </fields>
    </form>
	
    <form tabPageIndex="1" gravity="MiddleLeft" height="350" columns="120,120,240" >
      <text v="Chi tiết" e="Detail"></text>
      <fields>
        <field name="ctct20" label="" field="-" viewType="Grid">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
  </forms>

 <grids>
    <grid id="ctct20" table="ctct20" fieldKey="id, line" order="id, line" allowFilter="true" readOnly="false" allowOrder="true">
      <fields>
		<field name="chon_yn" dataType="B" width="80" valueDefault="1" readOnly="false" >
          <text v="Chọn" e="Check"></text>
        </field>
        <field name="id" dataType="N" width="50" format="0" >
          <text v="ID" e="ID"></text>
        </field>
        <field name="line" foreignField="@@ROW" dataType="I" fieldType="PK" hidden="true">
          <text v="Dòng" e="Line"></text>
        </field>
		<field name="ma_job_dh" width="100" fieldType="EX"  inactivate="true">
          <text v="Mã DH" e="Order Code"></text>
        </field>
        <field name="so_job_dh" width="100" fieldType="EX"  inactivate="true">
          <text v="Số DH" e="Order Number"></text>
        </field>
        <field name="id_hd" width="80" allowBlank="true" readOnly="false">
          <text v="ID phiếu" e="Voucher ID"></text>
        </field>
        <field name="so_ct_hd" width="100" fieldType="EX" inactivate="true" >
          <text v="Số phiếu" e="Voucher No"></text>
        </field>
		<field name="ma_ct_hd" width="100" fieldType="EX"  inactivate="true">
          <text v="Mã phiếu" e="Voucher Code"></text>
        </field>
        <field name="ngay_ct_hd" width="100" dataType="D"  inactivate="true" fieldType="EX">
          <text v="Ngày phiếu" e="Voucher Date"></text>
        </field>
        <field name="ma_nt_hd" width="100" fieldType="EX"  inactivate="true">
          <text v="Ngoại tệ" e="Currency"></text>
        </field>
        <field name="ty_gia_hd" dataType="N" format="FCAmount" width="120" inactivate="true" fieldType="EX">
          <text v="Tỷ giá hđ" e="EX Inv"></text>
        </field>
        <field name="tien_hd_nt" dataType="N" format="FCAmount" width="120" fieldType="EX">
          <text v="Tiền trên hóa đơn" e="Invoice Amount"></text>
        </field>
        <field name="da_pb_nt" dataType="N" format="FCAmount" width="120" fieldType="EX" >
          <text v="Đã phân bổ" e="Pcs UOM"></text>
        </field>
        <field name="cl_nt" dataType="N" format="FCAmount" width="100" fieldType="EX">
          <text v="Còn lại" e=""></text>
        </field>
        <field name="tien_nt" dataType="N" allowBlank="true" format="FCAmount" width="120" readOnly="false">
          <text v="Tiền phải thanh toán" e="Money payable"></text>
        </field>
		<field name="ma_ct_dh" width="100" fieldType="EX"  inactivate="true">
          <text v="Mã c/từ đh" e="Voucher Code"></text>
        </field>
		<field name="so_ct_dh" width="100" fieldType="EX"  inactivate="true">
          <text v="Số c/từ đh" e="Voucher Code"></text>
        </field>
        <field name="ngay_ct_dh" width="100" dataType="D" inactivate="true" fieldType="EX">
          <text v="Ngày c/từ đh" e="Voucher Date"></text>
        </field>
      </fields>

      <buttons>
        <button id="freeze">
          <text v="$FreezeToolbar" e="$FreezeToolbar"></text>
        </button>
      </buttons>

      <script>
        <query>
          <text>
            <![CDATA[<enc>Rx1SpSTJCSGk2YsaXOQqjgpif+NA4eszEqOpMAeyOjyWvOAgrJqd7xU4S0XklccbtRDKPiYMp/8nzZnWL1QXurTQABpSN8p+Q4yP14iTGsUCBstUaKLmkaROQK1yKBOBGTzBxjmQR3FdxmExKfU25SsSe7Ft2GFPnWv3wA3k4yR/m3IhUds9eE11DhAR1u9kGSpc3fdKTHDYTuQhGvYUiJoExXkmhO4W1k0RuVJPmDqgBiJhI2PNb5oZ2/S+XQANpzVxhb2Isz2vuKtcQcJKYkKDmCrPPG4iB3jlAQB+0veKJQuBQ+ML1U6RhoEk9fpSNrHKNYBclyQO32WoA6UAg5S49EL30r5U0/KQufP3vTCHyN9kur5upiQiXz5TV0SmWp+d8YuOiqEeqV8Y+HiMh4mmKnNVLxHV34MUvqp/G/9HdVK3BrlvcGqnrlbcZlBavFPC0FnLY4Zodmij6jYr77vec2QQPd8IjGHpSFuYTTHuLf4uTpSkU7uRrvsrzsOOFvTWlOAGcFOP/h2gRlA0+mpMHPp/0eeueSTRHQKXJ7SrBJ6bjZZBwufdjUr4u3hmj416vBLBo6NHS3siKLIwGv2VDNbsqxuBpVuEa9aMIAl0h0iyVzIT0IuKYwHDHn9hrfcwppa1j/d77Ic2k8V92htT/DPCqyDbe+2bXRhzm+OJa4napQHmKWVF/52DaLqQlrLApMaFI86pgehzZ4TbFeX62Jqrc0hpnwKy2df++gYBjfLDrulcLxFS9izV7/Th+2k7VZFFLcPtwWsKhbXvkw==</enc>]]>
          </text>
        </query>
      </script>

    </grid>
   
  </grids>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>vP0KViDupDhbY2LGomsOBTqc0qdLgYLhVpoiz6rDNT5a2plQ60VEY478/Tv7Jmf6ccO3O+OYtkS8kBH/jojelGVbJj0cO/Sayz6rFJLMts15EjpOt0rTIYUIJ27zFG25LCS5sovcHoU6Sl+WU+AZXe8tCNMurnm7QBXwYtr1mMHm33s6NsqQJNFmrXblEKOyTA64lSnjF43/kDM8XR3/UFytXVKnw1gR9dgXfwnP4uExgUcWRSYclmIp8VSg++2ixRlQcivv5ZG7wxlvN6ab2oldDvYYHeijOLXz1r2E3zacOs6GFnjuBamckO4LClkEB+/wJhtF5EgZxClYAf6tFGIIuN+2V0Hvep+5LzeDpJElRlgWaUVb3th7MrGw3VUURdyQk4gVas6HWtwtBvctz++qnA15C7jVlA9yjWLswLzay2Y4OHnBjYTKqo7kv+MNV5wKNJ+HxwN+OxoiuVhWiHketA/e9PGs3Z1JZTv1NRQSpe9NOIOxAYBHBySsUaGQCjpMmXUkjU+JpK9tZ49yRjg0a8CZxFZpDmQNKJ3Y4WLYA8eSNeGDiBcwX4fYnTK2JasQUxXo6nN3g9yFSdchyfbE0c7623hyr5wir750EyGRJyBFDGgDPiI5HdpYyqa0egffK3NeDWo0cbr2alf3o2kVVSogMlabLqSpBydY43mmqXkUgjweQRXWyJEJah1xaeIHbiJTtUFQOjGsHnaStzPuUkmUJ+egtIOfsJX3tg/i6KgAvJjFC2YRAZOs2Z2daTG3GdDVyQBoff9vEOpbQxs8OvKu27F/6QAr2v2SAhoXREHFcq9rCXABq/ozMNtEIqYpMxGG2yxTuFjaiA4aes89tEWk5cOyxZOrAsnnhXk=</enc>]]>
    </text>
  </js>
  
  <script>
		<request code="ma_kh_request">
			<text>
			  <![CDATA[<enc>FTkFm4igxdrH0JOWCSE3pGHYC1WBe4eYZxuXqK1sQME=</enc>]]>
			</text>
		</request>
  </script>
</dir>