<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="m53HD1" fieldKey="id" voucherCode="LX1" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc hóa đơn" e="Sales Invoice Filter"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" allowBlank="false" dataType="D">
          <text v="Ngày c/từ từ/đến" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" allowBlank="false" inactivate="true" dataType="D" nextRow="false">
          <text v="Ngày đến" e="Voucher Date"></text>
        </field>
          <field name="ma_nt" hidden="true" label="1" field="1">
          <text v="Mã ngoại tệ" e="Ex Code"></text>
        </field>
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="ma_kh" viewType="Lookup" disabled="true" inactivate="true" label="1" field="1">
          <text v="Mã khách hàng" e=""></text>
          <viewInfo lookupType="One" lookupId="dmkh" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_kh" />
        </field>
        <field name="ten_kh" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
        <field name="so_ct" label="1" field="1" allowBlank="false" viewType="Lookup">
          <text v="Số hóa đơn" e="Inv. No"></text>
          <viewInfo lookupType="Multi" lookupId="m55" lookupRef="ds_so_ct" lookupKey="ngay_ct between ![ngay_ct1]! and ![ngay_ct2]! and ma_ngv = 1 and ma_kh = ![ma_kh]! and unit_id = ![unit_id]! and status in (5,6)" />
        </field>
        <field name="ds_so_ct" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>4rbgQPq2PC/Jy8+m3mXt/3tl/VzEAMFLpBKHRnTbRteaNRL4VpURwzbp10vsj85PPhayzm5JDq/E/9fXgaxqkVEKRQELj8Bln84xYPO4uNy+R5rSjqrF9KE5AD36fyI0qngWNH8srXvPmZVyV5XmRaauS4OjkDI6sSk4+XfWSY1bmlOlf0QY2UQPtDSM0w2Gv5aEbzraZH0D8RJvPA4b2ayF21PY27eZArbRMpwIRVR3z4w6fiL1/FPXp+3Ki6Uh9rj/sEbQXKuYe6ADINsNqooh6QxvN10GImU7qRbbSuH1heWbKPLv8Rc2ZIN5YaCtsVx7snePedY15yCKqT1+zL2X3X96u0dx+yBpLOeEpr0YuLHJNSjfTElAyDClbHYSWlWaFD9mAlbhptDMkIaNVesa0/TqnAc6LVEPVDhhbISfLpuL82DVJoBl34uYs37r6jVE3RpYa7k2YEC5rXABrnHUop21i46ArT/KGcgbQGwxo22hDFNCO8qM9ZU6eEK0fbtKHQiAYps49IuW5uZMjA==</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>