<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="m54CR1" fieldKey="id" voucherCode="CR1" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc danh sách đơn hàng" e="Filter FCL Order Numbers"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D">
          <text v="Ngày từ/đến" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" aliasName="@DFDTo" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D" nextRow="false">
          <text v="" e=""></text>
        </field>
		<field name="ma_job" allowBlank="true" viewType="Lookup" label="1" field="1"  hidden="false" tabIndex="1">
          <text v="Mã/Số" e="Code/No"></text>
          <viewInfo lookupType="One" lookupId="vdmjob" lookupKey="status = 1" lookupCheck="1=1" lookupRef="ten_job" lookupInfo="vdmjob|ma_job|ten_job" />
        </field>
        <field name="ten_job" nextRow="false" fieldType="EX" readOnly="true" inactivate="true"  hidden="false" label="" field="" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
		<field name="so_job"  label="" field="1" nextRow="false" >
          <text v="Số" e="Voucher Number"></text>
        </field>
		<field name="ma_ct" viewType="Combobox" inactivate="true" label="1" field="1">
          <text v="Loại đơn hàng" e="Type Order"></text>
          <viewInfo>
            <options>
              <option val="">
                <text v="Tất cả" e="All"></text>
              </option>
              <option val="FCL">
                <text v="Hàng FCL" e="FCL Marine"></text>
              </option>
			  <option val="LCL">
                <text v="Hàng LCL" e="LCL Marine"></text>
              </option>
				<option val="AIR">
                <text v="Hàng AIR" e="AIR Marine"></text>
              </option>
			  <option val="OTH">
                <text v="Hàng Khác" e="OTHER Marine"></text>
              </option>
			  <option val="CTS">
                <text v="Dịch vụ hải quan" e="Customs Service"></text>
              </option>
            </options>
          </viewInfo>
        </field>
		<!-- <field name="ma_log" allowBlank="true" viewType="Lookup" label="1" field="1"  hidden="false" tabIndex="1"> -->
          <!-- <text v="Mã Log" e="Log Code"></text> -->
          <!-- <viewInfo lookupType="One" lookupId="dmlog" lookupKey="status = 1" lookupCheck="1=1" lookupRef="ten_log" lookupInfo="dmlog|ma_log|ten_log" /> -->
        <!-- </field> -->
        <!-- <field name="ten_log" nextRow="false" fieldType="EX" readOnly="true" inactivate="true"  hidden="false" label="" field="-" aliasName="cast('' as nvarchar(4000)) as "> -->
          <!-- <text v="" e=""></text> -->
        <!-- </field> -->
		<field name="ma_kh" allowBlank="true" viewType="Lookup" label="1" field="1"  hidden="false" nextRow="true">
          <text v="Khách hàng" e="Customer"></text>
          <viewInfo lookupType="One" lookupId="dmkh" lookupKey="status = 1 and kh_yn = 1" lookupCheck="kh_yn = 1" lookupRef="ten_kh" lookupInfo="dmkh|ma_kh|ten_kh" />
        </field>
        <field name="ten_kh" nextRow="false" fieldType="EX" readOnly="true" inactivate="true"  hidden="false" label="" field="1" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
		<field name="ma_kh_g" allowBlank="true" viewType="Lookup" label="1" field="1"  hidden="false">
          <text v="Người nhận" e="Consignee"></text>
          <viewInfo lookupType="One" lookupId="dmkh" lookupKey="status = 1 and other_yn = 1" lookupCheck="other_yn = 1" lookupRef="ten_kh_g" lookupInfo="dmkh|ma_kh|ten_kh" />
        </field>
        <field name="ten_kh_g" nextRow="false" fieldType="EX" readOnly="true" inactivate="true"  hidden="false" label="" field="1" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
		<field name="ma_kh_s" allowBlank="true" viewType="Lookup" label="1" field="1"  hidden="false">
          <text v="Người gửi" e="Shipper"></text>
          <viewInfo lookupType="One" lookupId="dmkh" lookupKey="status = 1 and other_yn = 1" lookupCheck="other_yn = 1" lookupRef="ten_kh_s" lookupInfo="dmkh|ma_kh|ten_kh" />
        </field>
		<field name="ten_kh_s" nextRow="false" fieldType="EX" readOnly="true" inactivate="true"  hidden="false" label="" field="1" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
		<field name="ma_dl" allowBlank="true" viewType="Lookup" label="1" field="1"  hidden="false" tabIndex="2" nextRow="true">
		  <text v="Đại lý" e="Agent"></text>
		  <viewInfo lookupType="One" lookupId="vdmdaily" lookupKey="status = 1 and dl_yn =1" lookupCheck="1=1" lookupRef="ten_dl" lookupInfo="vdmdaily|ma_dl|ten_dl" />
		</field>
		<field name="ten_dl" nextRow="false" fieldType="EX" readOnly="true" inactivate="true"  hidden="true" label="" field="1" aliasName="cast('' as nvarchar(200)) as ">
		  <text v="" e=""></text>
		</field>
        <field name="ma_noi_di" viewType="Lookup" disabled="false" label="1" field="1" operation="like">
			<text v="Nơi đi" e="Origin "></text>
			<viewInfo lookupType="One" lookupId="vdmcangdi" lookupKey="(kkh_yn = 1 or hc_yn = 1) and status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_di" />
		</field>
		<field name="ten_noi_di" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="ma_noi_den" viewType="Lookup" label="1" field="1" operation="like">
			<text v="Nơi đến" e="Destination"></text>
			<viewInfo lookupType="One" lookupId="vdmcangden" lookupKey="(kkh_yn = 1 or hc_yn = 1) and status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_den"  />
		</field>
		<field name="ten_noi_den" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>	
		 <field name="so_ct" label="1" field="1" allowBlank="false" viewType="Lookup" operation="like">
          <text v="Lấy số đơn hàng" e="Get the order number"></text>
          <viewInfo lookupType="one" lookupId="s61" lookupRef="ds_so_dh" lookupKey="ngay_ct between ![ngay_ct1]! and ![ngay_ct2]! and ma_job like ![ma_job]! + '%' and so_job like ![so_job]! + '%' and ma_noi_di like ![ma_noi_di]! +'%' and ma_noi_den like ![ma_noi_den]! +'%' and ma_ct like ![ma_ct]! +'%' and ma_kh like ![ma_kh]! +'%' and ma_kh_g like ![ma_kh_g]! +'%' and ma_kh_s like ![ma_kh_s]! +'%' and ma_dl like ![ma_dl]! +'%' and status in (1)" lookupCheck="ma_job like ![ma_job]! + '%' and so_job like ![so_job]! + '%' and status in (1)" />
        </field>
        <field name="ds_so_dh" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>	
      </fields>
    </form>
	
	
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>IOtmQw+hlbKKUjwffg5sQzGkZ7AlLE2APJ+SkjpEJ8FpZe8Pl383Bd9fqj0qqsnfTsPQ1xdahsBE3yY8otOnweJ2rQB/TnmNI9BsyY2N6GkjCl60jjYd/Tj5Wyjc7wYdZyAgMcfbwRgKNZFv2H6J4nt9ucBUanKHlhZ3BEuvR6+RpeNMm6xhqGLCls+PiH6hwM2DMobgzm5DVsCjOjngl34WwLw8HSlcw3pV5l3US2oeoWDWwRBgnFlKzGZxd1ckyhFgKI20lEsvKgOTXE+Jd8SjopHSXFM0tic+dFevq8pFwx3sMMvW7i7Z0lJCJOv8DX3fGrEnyeB+KplPUineRW3B3YFG6tQompFjttXikEZ/AMpNORlLRVEecHtwQINXkRkdkqVj3t1G3gilE5mA8qWIZHEI9vU5QTJPaqiDFO6A7IfJH7wW4rGyhN4ZPs3lq64Rgf+qcadz9U+8l3fA4bay0HplY/39NlP+ht/10aLQQcfIFV8CBTT+Az9aBwxmwLPc75x7P1unjLBbBwFk/0T4oL1f3CGXJRJA2ltlCMs=</enc>]]>
    </text>
  </js>
<css>
    <text>
      <![CDATA[<enc>/T0x+X5J8VnLtXSs8xERBy5XsIhTcMK77n2BsK4suh7al6IPHe8OdNVaharGtBWoIj54XqGtRPyUlbB6zG6gOVTWDaEMF4Lb+C9dT+n+d8E=</enc>]]>
    </text>
  </css>
  <script>

  </script>
</dir>