<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="m55PX3" fieldKey="id" voucherCode="HD1" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc phiếu xuất" e="Pick List Filter"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" allowBlank="false" dataType="D">
          <text v="Ngày c/từ từ/đến" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" allowBlank="false" inactivate="true" dataType="D" nextRow="false">
          <text v="Ngày đến" e="Voucher Date"></text>
        </field>
          <field name="ma_nt" hidden="true" label="1" field="1">
          <text v="Mã ngoại tệ" e="Ex Code"></text>
        </field>
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="ma_kh" viewType="Lookup" disabled="true" inactivate="true" label="1" field="1">
          <text v="Mã khách hàng" e=""></text>
          <viewInfo lookupType="One" lookupId="dmkh" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_kh" />
        </field>
        <field name="ten_kh" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
        <field name="so_ct" label="1" field="1" allowBlank="false" viewType="Lookup">
          <text v="Số phiếu xuất" e="PL No"></text>
          <viewInfo lookupType="Multi" lookupId="m54" lookupRef="ds_so_ct" lookupKey="ngay_ct between ![ngay_ct1]! and ![ngay_ct2]! and ma_kh = ![ma_kh]! and unit_id = ![unit_id]! and status in (5,6) and ma_nt = ![ma_nt]!" />
        </field>
        <field name="ds_so_ct" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>KnJ66uF0s8Sz+E1B2mMw0pAmYVC9lCePD2zzo2fOL0UBdFZ/aCSKXA6BJme9zAhHh/hAMCogknKqMMMxEh+zimvh9JxPhojkKDv7CZPelwpCkRkmY+sO/S136KqiMnvlxA5kz2cp33ooKvhfNdmUKR9CgcNvDIDu8hGOqgFvmN7BloeKN6rjlA0p3RFQjq8jVktB4iL0rtXMcOZRaKzaoMGqH+auwv0y80ezji5fkk9Oyg0qYu1JY7cqhzZt3pxF1y3XGrdK8YMy++DyQOxrDSkc1e+eblwPboT7DBTGxBYuwM4f7ufi3HiOxGZPLsw7/iyGAK6Z0lGHiMvj7UG+eNwwcrjP7EK/Bbbe678iWZbnsAF4KR/+0o01nPqG/+jgKFojg9DG2UpVuD12f3MK40A2Q9Dg94c21B/pYVUuKkKiQ7wUtMWe/qT/PnrYGH1vlYt+rCLGobYhtqxjcyDrZkp6BavV1jjBv1dUp3BoakWpX1TXGqBzbMncEmiR+qROtlDUoi6IWTe1hbYBXeLQkg==</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>