<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="m58_1Filter" fieldKey="id" voucherCode="BQ1" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc chi tiền theo phiếu" e="Quick Quote Filtering"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D">
          <text v="Ngày từ/đến" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" aliasName="@DFDTo" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D" nextRow="false">
          <text v="" e=""></text>
        </field>
		<field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="ma_kh" allowBlank="true" viewType="Lookup" label="1" field="1" importable="5">
          <text v="Mã khách hàng" e="Customer Code"></text>
          <viewInfo lookupType="One" lookupId="dmkh" lookupKey="status = 1 and kh_yn = 1" lookupCheck="1=1" lookupRef="ten_kh" lookupInfo="dmkh|ma_kh|ten_kh" />
        </field>
        <field name="ten_kh" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
	
	
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>VgosVqkajzgPv0sFzv3Bejws1lLbLEpuR+fjEDnnOZO+5fdiX2L7B/HW4Ma5cADVsIsluxex6wsqKndPY/GMAWVUN8a40yKcKnwhegFkE9q4u2w6YzMVY+xePOOVPBDZooTjxbuHVv9mvWcq1YZe7Tda6tHdO7yFj+AQy0LlurkTfBNGBYjOLgE1scRHsKPYYHzG4Z9dzNtok9m4j/UGY3POEY5ynyLcqh4Tr6oykzuVb1NY3JgMjf0Yv/4s47mwuyZkqhTBaz+LnoDe2bRqqQYwGmn10WmJx0lQ9l0SUMrhoGpi/2dJdXuWfWvvuNWeRgmoNZjZ9+XOjnpfThfnWP8yUOeqiGUGHsjhD+s7MOaa70tPsFf+R9NogxA1y+Yle1pt4fKzsa0PiDe+pOmN38cmd/yS9AB5efSRq1Jtl0of5zUQ+f50AYtvVtn27uB8tfkEDUGTQoMi0eWJ16P3oIYC2AIscOBSTNV/jIEpUKyAVSXGNm4y8Zb52yxswO0r</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>