<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="d58" table="" height="" fieldKey="id" voucherCode="TT0" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc phiếu thu tiền" e="Cash Receipt"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D">
          <text v="Ngày c/từ (từ/đến)" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" aliasName="@DFDTo" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D" nextRow="false">
          <text v="" e=""></text>
        </field>
		<field name="ma_job" clientDefault="true" viewType="Lookup" label="1" field="1" allowBlank="true"  setype="1" operation="like">
          <text v="Mã" e="Code"></text>
          <viewInfo lookupType="One" lookupId="vdmjob" lookupKey="status = 1" lookupCheck="1=1" lookupRef="ten_job" lookupInfo="vdmjob|ma_job|ten_job" />
        </field>
        <field name="ten_job" clientDefault="true" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
        <field name="so_job"  label="1" field="1" operation="a.so_job &gt;= N'%s'" nextRow="true">
          <text v="Số" e="Number"></text>
        </field>
		<field name="ma_kh" viewType="Lookup" label="1" field="1" operation="like">
          <text v="Khách hàng" e="Customer Code"></text>
          <viewInfo lookupType="One" lookupId="dmkh" lookupKey="status = 1 and kh_yn = 1" lookupCheck="1=1" lookupRef="ten_kh" lookupInfo="dmkh|ma_kh|ten_kh" />
        </field>
        <field name="ten_kh" nextRow="false" fieldType="EX" readOnly="true" inactivate="true"  hidden="false" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
        <field name="ma_ngv" viewType="Combobox" label="1" field="2" operation="=" >
          <text v="Loại xuất" e="Issue Type"></text>
          <viewInfo>
            <options query="select ma_ngv, ten_ngv%l from dmngv where ma_ct = '@@voucherCode' and status = 1 and ma_ngv=1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="dien_giai" label="1" field="-" operation="a.dien_giai like N'%%s%'">
          <text v="Diễn giải" e="Voucher Number"></text>
        </field>
      </fields>
    </form>
    
    <form gravity="BottomLeft" columns="120,120,120"  >
      <fields>
        <field name="ma_unit" viewType="Lookup" inactivate="true" label="1" field="2" >
          <text v="Đơn vị" e="Unit"></text>
          <viewInfo lookupType="Multi" lookupId="sysunit" lookupKey="status = 1 and unit_id in (select unit_id from dbo.ISWIFTFunctionGetUnitIDRight(@@userId, @@admin, ''))" lookupCheck="1 = 1" lookupRef="ten_unit" />
        </field>
        <field name="ten_unit" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" label="1" field="2" operation="=" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
              <option val="">
                <text v="Tất cả" e="All"></text>
              </option>
            </options>
          </viewInfo>
        </field>
        <field name="user_id0" viewType="Combobox" inactivate="true" label="1" field="2" operation="a.user_id0 in (select user_id from sysuserinfo where user_ref like '@@userRef%')" >
          <text v="Lọc theo người sd" e="Filter By User"></text>
          <viewInfo>
            <options>
              <option val="">
                <text v="Tất cả" e="All"></text>
              </option>
              <option val="1">
                <text v="Lọc theo người tạo" e="Filter By Create User"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>uw3iZoR/y/5o6FF1x5y/2d25edYK6HKYD6+GbidnZp6MNKDvDhQESiqBESkiwhcL6i12Ak74RPpM0Rixao3Z5In5x7j57wFBNAxbPIBbe7eSCQmMcyMKKED5sh/r6yrRvU1ArJ/kLlAKDi1yCF6nVRSaXgBlzhqW8vFb/QiBjZnJd53wGmBiiq0D+Fxg71Oq</enc>]]>
    </text>
  </js>

  <script>
    &VoucherJSLoading;
  </script>
</dir>