<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="d72" table="" height="" fieldKey="id" voucherCode="CH0" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc phiếu chi hộ" e="Purchase Invoice Filter"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D">
          <text v="Ngày c/từ (từ/đến)" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" aliasName="@DFDTo" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D" nextRow="false">
          <text v="" e=""></text>
        </field>
        <field name="so_ct1"  label="1" field="1" operation="a.so_ct &gt;= N'%s'">
          <text v="Số c/từ (từ/đến)" e="Voucher Number"></text>
        </field>
        <field name="so_ct2"  label="" nextRow="false" field="1" operation="a.so_ct &lt;= N'%s'">
          <text v="" e=""></text>
        </field>
        <field name="ma_ngv" viewType="Combobox" label="1" field="2" operation="=" hidden="true" >
          <text v="Loại xuất" e="Issue Type"></text>
          <viewInfo>
            <options query="select ma_ngv, ten_ngv%l from dmngv where ma_ct = '@@voucherCode' and status = 1 order by stt">
              <option val="">
                <text v="Tất cả" e="All"></text>
              </option>
            </options>
          </viewInfo>
        </field>
        <field name="ma_gd" viewType="Combobox" label="1" field="2" operation="=" hidden="true"  >
          <text v="Giao dịch" e="Transaction"></text>
          <viewInfo>
            <options query="select ma_gd, ten_gd%l from dmgd where ma_ct = '@@voucherCode' and status = 1 order by stt">
              <option val="">
                <text v="Tất cả" e="All"></text>
              </option>
            </options>
          </viewInfo>
        </field>
        <field name="ma_kh" viewType="Lookup" label="1" field="1" operation="like">
          <text v="Đối tượng TT" e="Payer Code"></text>
          <viewInfo lookupType="One" lookupId="dmkh" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_kh" />
        </field>
        <field name="ten_kh" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
		<field name="ma_kh_tt" viewType="Lookup" label="1" field="1" operation="like">
          <text v="Khách hàng" e="Customer Code"></text>
          <viewInfo lookupType="One" lookupId="dmkh" lookupKey="status = 1 and ma_kh not in (select ma_kh from dmkh where nv_yn = 1)" lookupCheck="ma_kh not in (select ma_kh from dmkh where nv_yn = 1)" lookupRef="ten_kh_tt" />
        </field>
        <field name="ten_kh_tt" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
        <field name="ma_bp" viewType="Lookup" label="1" field="1" operation="like">
          <text v="Mã bộ phận" e="Purchaseman"></text>
          <viewInfo lookupType="One" lookupId="dmbophan" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_bp" />
        </field>
        <field name="ten_bp" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
        <field name="dien_giai" label="1" field="-" operation="a.dien_giai like N'%%s%'">
          <text v="Diễn giải" e="Voucher Number"></text>
        </field>
      </fields>
    </form>
    
    <form gravity="MiddleLeft" tabPageIndex="1" columns="120,120,120"  >
      <text v="Chi tiết" e="Detail"/>
      <fields>
        <field name="ma_vt" viewType="Lookup" label="1" field="1">
          <text v="Mã phí" e="Fee Code"></text>
          <viewInfo lookupType="One" lookupId="dmvt" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_vt" />
        </field>
        <field name="ten_vt" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
    
	
    <form gravity="BottomLeft" columns="120,120,120"  >
      <fields>
        <field name="ma_unit" viewType="Lookup" inactivate="true" label="1" field="2" >
          <text v="Đơn vị" e="Unit"></text>
          <viewInfo lookupType="Multi" lookupId="sysunit" lookupKey="status = 1 and unit_id in (select unit_id from dbo.ISWIFTFunctionGetUnitIDRight(@@userId, @@admin, ''))" lookupCheck="1 = 1" lookupRef="ten_unit" />
        </field>
        <field name="ten_unit" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" label="1" field="2" operation="=" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
              <option val="">
                <text v="Tất cả" e="All"></text>
              </option>
            </options>
          </viewInfo>
        </field>
        <field name="user_id0" viewType="Combobox" inactivate="true" label="1" field="2" operation="a.user_id0 = @@userId" >
          <text v="Lọc theo người sd" e="Filter By User"></text>
          <viewInfo>
            <options>
              <option val="">
                <text v="Tất cả" e="All"></text>
              </option>
              <option val="1">
                <text v="Lọc theo người tạo" e="Filter By Create User"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>uw3iZoR/y/5o6FF1x5y/2Sz1qZ1gTfLy7dPX/UBEpuSEXg3kdoQW5ZV1B2YtFv3GktQs3HGWZLQPzxviSG/OJMPio64xyCNNg14XdhP/S3bCSVemnjO8b4NSaqxV3eaQJLsLiU6oFOxWhUoflL/dQtf5K3Nz+m3d4SpjAr/yaSjCh4V7JPpPcnGprBzfcnmk</enc>]]>
    </text>
  </js>

  <script>
    &VoucherJSLoading;
  </script>
</dir>