<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
  <!ENTITY VoucherExtendFields SYSTEM "..\Include\XML\VoucherExtendFields.xml">
]>

<dir id="m63CR1Select" table="" height="" fieldKey="id" voucherCode="CR1" dirViewType="Dialog" readOnly="true" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Chi tiết đơn hàng được chọn" e="Quotation Entry Detail"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" readOnly="true" aliasName="@DFDFrom" disabled="true" allowBlank="false" dataType="D">
          <text v="Ngày c/từ từ/đến" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" allowBlank="false" disabled="true" inactivate="true" dataType="D" nextRow="false">
          <text v="Ngày đến" e="Voucher Date"></text>
        </field>
        <field name="ma_nt" hidden="true" label="1" field="1">
          <text v="Mã ngoại tệ" e="Ex Code"></text>
        </field>
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>	
		<field name="ma_kh" format="U" label="1" disabled="true"  field="1" operation="like" >
          <text v="Mã khách hàng" e="Code"></text>
        </field>
		<field name="ten_kh" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		 <field name="ma_hang" viewType="Lookup" label="1" disabled="true" field="1" operation="like">
			<text v="Hãng tàu/ Đại lý" e="Carrier/ Agent Code"></text>
		</field>
		<field name="ten_hang" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="ds_cong" allowBlank="true" viewType="Lookup" label="1" field="-"  hidden="false" disabled="true">
			<text v="Container" e="Container List"></text>
			<viewInfo lookupType="Multi" lookupId="dmcong2" lookupKey="status=1" lookupCheck="status=1" lookupRef="" lookupInfo="dmcong|ma_cong|ten_cong" />
		</field>
        <field name="ma_noi_di" viewType="Lookup" label="1" disabled="true" field="1" operation="like">
			<text v="Nơi đi" e="Origin "></text>
			<viewInfo lookupType="One" lookupId="vdmcangdi" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_di" />
		</field>
		<field name="ten_noi_di" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="ma_noi_den" viewType="Lookup" disabled="true" label="1" field="1" operation="like">
			<text v="Nơi đến" e="Destination"></text>
			<viewInfo lookupType="One" lookupId="vdmcangden" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_den"  />
		</field>
		<field name="ten_noi_den" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>  
		<field name="so_ct" label="1" field="1" disabled="true" hidden="true">
          <text v="Số báo giá" e="Quot. Number"></text>
        </field>
		<field name="dien_giai" label="1" rows="1" field="-" disabled="true">
		  <text v="Diễn giải" e="Explain"></text>
		</field>
		<field name="id" dataType="N" hidden="true" fieldType="PK" label="1" field="1"  >
			 <text v="ID" e="Code"></text>
		</field>
		
      </fields>
    </form>
    <form tabPageIndex="1" gravity="MiddleLeft" height="0" columns="120,120,240" >
      <text v="" e=""></text>
      <fields>
        <field name="v61" label="" field="-" viewType="Grid">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
  </forms>

 <grids>
    <grid id="v61" table="v61" fieldKey="id, line" order="id, line" allowFilter="true" readOnly="true" allowOrder="true">
      <fields>
        <field name="id" foreignField="id" dataType="N" fieldType="PK" format="0" copy="false" hidden="true">
          <text v="" e=""></text>
        </field>
        <field name="line" foreignField="@@ROW" dataType="I" fieldType="PK" hidden="true">
          <text v="Dòng" e="Line"></text>
        </field>
		
      </fields>

      <buttons>
        <button id="freeze">
          <text v="$FreezeToolbar" e="$FreezeToolbar"></text>
        </button>
      </buttons>

      <script>
        <query>
          <text>
            <![CDATA[<enc>vKBlGj1Ruumhje83o77vBRiR/1Om54N2TUW5LKPUeH13AO8EFlt6ecTxhChPl93hIE12jz0T9aizKM1t6xGfgH6voF1vzcPaaiVmbJxEI5Q57exzMAKT5jXZKVwvsh5aHeDY0EKNLuiDoeP7KDSxYoHIGifz3GlvlgiF4eyWWgoxnVoEchFNqm1kkIwiYuXb8ZeN7M3txJXDxD1WNjCz9+FcfHGt7NgmIOkMbjCgGwckmoFby6IhWzf5p+stlh2SkzB4steZE+G5u9IaMFJWmoyMIR9tsmJhP+74b1G22Hd/0bBDfNyqdd3EKh4Fc/MvC6KiNg0C3w47A/AC6msmk8vTKGzn5oJ4S8h2q6lg4eQm8r9tQNJfXWG1zT9M1TtuBKNHm1t5MEiACIfT5mTy6El2oo7I2O0iutawBmlOmTlTMTQrrrqixNTDf1DVz4ff</enc>]]>
          </text>
        </query>
      </script>

    </grid>
   
  </grids>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>l6YXouPCl+9YFRqCaCLgmITWZXn137teRVMK9PeI4vSIOUK251VUwH36zXZUODL+RT0B02MY+OoW5Zev9SDVbyfIs6Mhu4XWhRSIGihvfAWn5LJidM4kIoBBS/CRFHVl+lZmz5sD7sz0zNIt8OQ/2S+yrwbRCXpuqqd25/taw/1DBIKJpszAKCiIbkfxqEG4HuZQLBMGWNaJ2wGuWbTfiQ7MIYmFf+WfXWgUYUtIJL9H5ffV75bEbrc/ZxjRGKwvlqYMY5BzOrcFY3K8X1xan0U1CVV3rYbbfeOs69z6V30DCCbby1xGqeaXfXOC+GVap9sNsFzg3rbKEhLh2I4m5W5xXMmmmoziOFHmx6aQzAEAmfSG9b6DDS2CSFdDVWtWGLUCxWgi8taaiTPTstbt6yRrl7jnF3bu8rX6fAwkojcxJ28rngpI6ADEO+6oE0Vi9ev4euZBGja7/YhjLDuC7GZxA56Ezc+yX6N2QUeUgmc571oi2HP5HfqFFpA7t78vZawnmfhzO9kq4hCrzwjCarqqfmYltapcPLcX4iLofVSEy/zStWAZShwFdt54CzMO55EHrwwvCk85X9Uj1FaJCIXl4ll93OhWlZPuYpPKbmoJFugqejkp1bMXg2bdegucECs0s0xH8chF4OQXjmKF79PyetvbxuXKjY8XHBtYgNC2QxoG+bJLBaPEwlSaimQ6b89F6/3w3KT/F/cOT1ONN96ev5oMb5RjbKOaVe35SbMtR+ayexEpS3td6oZWlYFXVnsrDiy/7Wt2lf2KU2MHPcnJEl+ShKXeIMfMywkuC1k=</enc>]]>
    </text>
  </js>
  
  <script>
		<request code="ma_kh_request">
			<text>
			  <![CDATA[<enc>Hm+zoi9l+L0DTPvuGzsimcaf3DOWd7UVoXenHuA2shxE5pXrRa5GAEs6hIF+bG7TfAAN4uzgHOBbpjuxUBthxjXH3TENMJsIDn41XYj7P3u2EvqhSORaaKwRKffi6zjnjxLD2ABxZwVuUq3Ljq21i/WAqghWfZSvPFxtHLzXtMt944QZJBSvJgaXZeMFJ/TJnwBXnctoc+xo8N0/aT75ddVbUV0rQo63JQRTYv9R77tPL6CK0OtMuHQaxIZy2Igdvg8QHvIGR0IQrJP7mEfaBphq2v+bETb3UPbTUjtGqPtQjnDEsZbaiIgWsPdatqN2fKVBFcspM2zFblRpw6tASYSVrQzOkoxDnSGhyE0piyPedmW896rCCOPb7uWGlafCQLWd0XrTtwyDRnj7q2Cxee3T0WoZbjrNZMjQgizFNuGHbjPU6CEKUbbgXTCUnmk0+uoEDjmoTb6KZUn12zk9rALzyNZ0ZTJ5yuHfjrbVLEE=</enc>]]>
			</text>
		  </request>
    
  </script>
  
</dir>