<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
  <!ENTITY VoucherExtendFields SYSTEM "..\Include\XML\VoucherExtendFields.xml">
]>

<dir id="m64_1Select" table="" height="" fieldKey="id" voucherCode="BQ1" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Chi tiết phiếu được chọn" e="Quotation Entry Detail"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
		<field name="ngay_ct1" label="1" field="1" readOnly="true" aliasName="@DFDFrom" disabled="true" allowBlank="false" dataType="D">
          <text v="Ngày c/từ từ/đến" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" allowBlank="false" disabled="true" inactivate="true" dataType="D" nextRow="false">
          <text v="Ngày đến" e="Voucher Date"></text>
        </field>
        <field name="ma_nt" hidden="true" label="1" field="1">
          <text v="Mã ngoại tệ" e="Ex Code"></text>
        </field>
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>

		<field name="ma_kh" label="1" disabled="true"  field="1" >
          <text v="Mã nhân viên" e="Employee Code"></text>
        </field>
		<field name="ten_kh" allowBlank="true" label="1" disabled="true"  field="-" importWidth="250" importable="10">
          <text v="Tên nhân viên" e="Employee Name"></text>
        </field>
		
        <field name="xprocess" label="1" field="2" valueDefault="2" viewType="Combobox">
          <text v="Xử lý" e="Process"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="Thêm vào chi tiết" e="Append To Detail"></text>
              </option>
              <option val="2">
                <text v="Xóa hết chi tiết và thêm mới" e="Delete All Detail And Append New"></text>
              </option>
            </options>
          </viewInfo>
        </field>
		<field name="id" dataType="N" hidden="true" fieldType="PK" label="1" field="1"  >
			<text v="ID" e="Code"></text>
		</field>
      </fields>
    </form>
	
    <form tabPageIndex="1" gravity="MiddleLeft" height="350" columns="120,120,240" >
      <text v="Chi tiết" e="Detail"></text>
      <fields>
        <field name="cthu20" label="" field="-" viewType="Grid">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
  </forms>

 <grids>
    <grid id="cthu20" table="cthu20" fieldKey="id, line" order="id, line" allowFilter="true" readOnly="false" allowOrder="true">
      <fields>
		<field name="chon_yn" dataType="B" width="80" valueDefault="1" readOnly="false" >
          <text v="Chọn" e="Check"></text>
        </field>
        <field name="id" dataType="N" width="50" format="0" >
          <text v="ID" e="ID"></text>
        </field>
		<field name="so_ct" width="80" fieldType="RF" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
		<field name="ma_ct" width="80" >
          <text v="Mã c/từ" e="Voucher Code"></text>
        </field>
        <field name="ngay_ct" width="100" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
		<field name="ma_kh" width="100" >
          <text v="Mã nhân viên" e="Employee Code"></text>
        </field>
        <field name="ten_kh" width="200" fieldType="EX" >
          <text v="Tên nhân viên" e="Employee name"></text>
        </field>
        <field name="t_tt" dataType="N" format="FCAmount" width="120">
          <text v="Tiền trên hóa đơn" e="Invoice amount"></text>
        </field>
        <field name="da_tt_nt" dataType="N" format="FCAmount" width="120" aliasName="t_tt*0 as ">
          <text v="Đã thanh toán" e="Received"></text>
        </field>
        <field name="cl_nt" dataType="N" format="FCAmount" width="120" aliasName="t_tt*0 as ">
          <text v="Còn phải thanh toán" e="Receivable"></text>
        </field>
		<field name="ma_ct_dh" width="100" inactivate="true" hidden="true"  >
          <text v="Mã c/từ đh" e="Voucher Code"></text>
        </field>
		<field name="so_ct_dh" width="100" inactivate="true" hidden="true" >
          <text v="Số c/từ đh" e="Voucher Code"></text>
        </field>
        <field name="ngay_ct_dh" width="100" dataType="D"  inactivate="true" hidden="true" >
          <text v="Ngày c/từ đh" e="Voucher Date"></text>
        </field>
		<field name="ma_job_dh" width="100" inactivate="true" hidden="true" >
          <text v="Mã job đh" e="Voucher Code"></text>
        </field>
        <field name="so_job_dh" width="100" inactivate="true" hidden="true" >
          <text v="Số job đh" e="Currency"></text>
        </field>
      </fields>

      <buttons>
        <button id="freeze">
          <text v="$FreezeToolbar" e="$FreezeToolbar"></text>
        </button>
      </buttons>

      <script>
        <query>
          <text>
            <![CDATA[<enc>7dkt8IUJdf+fggEJrmwgn+o9jcOjtGKwkSZiBWy4Sjbz4iTRJyRAk42mkWgL4W+muZUhi+N83woN/0ew7BogZ2zcwRQVulA67HJXXBTPBFT/rge2rXnkCE0UPugLuisw99AKigrTn+kPioA7mno1sr/5nmNizf4U4VCeRcaAHrv0ux5P1M0P9Bkp124TuUIV4RAAdtDnwubJIZ4CinZqljY21fGnuy9QFMtFbL4Z3Oh9/D5NHARfxp68nCbyWoQfWBMXW9FrP4/NVWt6rECs/IxyBJjvXZNqXmMde4kSAhh2RW19k63KuI5jJgopo0JWXUyU20gWTbjtB5CUk2RMi/bIF1hDWvb4zKEppcYaPSb8zFr/GNrg5HH0wLHaStR01z83WImX3Ug3EfKqueXPZ16Ax4T9hcswYWwAcRV9TJvrzNMzKfq1Icnw4/I2BW3P0w/vUshjTuEc/l565JclcStsmmD1vAC5SByD5PW3MkyDhPC4v8xlf76WmVSwooE1yER574TKHTEOuZF+Ej0ENR1Fa3NYui0q4EE9Lzb6zrfG89k8ZH7FnAs6K69tdkfWHAm9nFs17cIPXTM8JJVmnABjwhSHjZatTO1ik99fOYK5Eg+Jw2owUEPuqbr3U0CyyL7khMH29N6Pms/1GYTdriYheufYWvngQhycYkFRPAUADVV3Mkz+2cAOPsh2m9molcApDzw/3sCkqV4HTz40Q3TdTuFe5JRyGWaxGfyOqzk=</enc>]]>
          </text>
        </query>
      </script>

    </grid>
   
  </grids>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>l6YXouPCl+9YFRqCaCLgmDcQWIQ4AWfFpPbAvSEdvn0ThH2pThB3VNPVvxVATM4429VoevdxF7S0suRY2+KxZ/HazAW6GCsJzw/77ulGvmj3nKTmM6qBB0RrHmvJYr8BRwVgcg3lPAmIcQIiSuq9Kn9eKbNpxOtVGfNVeugMoqv77MnOeehUlPH4WYJC6aBPC7FW8FTh1Fljz0yLiZMNl/BMPiAs5eTp59N8R4m+i39giwsB7fvdWLdQJhVPiXlATeeT72dribN2Bdc0o4+Hb4GAmEATYGnJAAL+/Zh6XU2Tmn3RlnQnov+8j4xA0U9yhFpT2KaH9VOweh9BnySU+m6BoBA7nKvczdMcdpQko6TsU5lT5MjHDosDvDVFLEzb0wGhHLWYwp7GdXfrK+IwKNXS3WQBgR6qdeU5dtGOygxmDgg68un+MCpcqCJ1lDhL55GTG4urivglFhCzdcWWF4PucwhvjhVDsA4egnmdbdN5oWEoaZeRuPvxcgXCffXU51WPxfnM+dVgCqbzyDSvWCCIwOK8DoXcNk569OzUcIjotAqY8FWFlWudMjuU/KlIiAuQZhZAav7WqmsvF1ToQg7dF+/43CVIsC1PCJVSn6p6sIX4EK4aF3zZ5ij3IcWZp3AFBQTUpjJlKNfYcr3ZR7N+1G/D7akmBHwO8OKKct3GNU17aC6PtuyzLk/iKW/lvvNLCf2WLkKDOC+qBPe3qd/tSlcJ7LLwtkjxBUlmC2gqMa9cjBG1fL52OQhpYm5grqIo0KOnsTtCdkhcaxdbqoaQPvBVVPDwhbEEEGr1JOg/PTiiqFt0DNKHWom21N7Bgrp8lHtdRUgaxm1Smho+6QqwB5joTZGaoxXEa9G+qVc=</enc>]]>
    </text>
  </js>
  
  <script>
		<request code="ma_kh_request">
			<text>
			  <![CDATA[<enc>FTkFm4igxdrH0JOWCSE3pGHYC1WBe4eYZxuXqK1sQME=</enc>]]>
			</text>
		</request>
  </script>
</dir>