<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="d72" table="" height="" fieldKey="id" voucherCode="PN1" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc phiếu tạm ứng" e="Purchase Invoice Filter"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D">
          <text v="Ngày c/từ (từ/đến)" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" aliasName="@DFDTo" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D" nextRow="false">
          <text v="" e=""></text>
        </field>
		<field name="ma_job" clientDefault="true" viewType="Lookup" label="1" field="1" allowBlank="true"  setype="1" operation="like">
          <text v="Mã/Số Hoàn ứng" e="Employee Code"></text>
          <viewInfo lookupType="One" lookupId="vdmjob" lookupKey="status = 1" lookupCheck="1=1" lookupRef="ten_job" lookupInfo="vdmjob|ma_job|ten_job" />
        </field>
        <field name="ten_job" clientDefault="true" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
        <field name="so_ct1"  label="" field="1" operation="a.so_job like N'%%s%'" nextRow="false">
          <text v="Số" e="Voucher Number"></text>
        </field>
		<field name="ma_job1" clientDefault="true" viewType="Lookup" label="1" field="1" allowBlank="true"  setype="1">
          <text v="Mã/Số Phiếu chi" e="Employee Code"></text>
          <viewInfo lookupType="One" lookupId="vdmjob" lookupKey="status = 1" lookupCheck="1=1" lookupRef="ten_job1" lookupInfo="vdmjob|ma_job1|ten_job1" />
        </field>
        <field name="ten_job1" clientDefault="true" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
        <field name="so_ct2"  label="" nextRow="false" field="1" >
          <text v="" e=""></text>
        </field>

        <field name="ma_kh" viewType="Lookup" label="1" field="1" operation="like">
          <text v="Mã người ứng" e="Employee Code"></text>
          <viewInfo lookupType="One" lookupId="dmkh" lookupKey="status = 1 and nv_yn = 1" lookupCheck="1 = 1" lookupRef="ten_kh" />
        </field>
        <field name="ten_kh" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
        <field name="dien_giai" label="1" field="-" operation="a.dien_giai like N'%%s%'">
          <text v="Diễn giải" e="Explain"></text>
        </field>
      </fields>
    </form>
	
    <form gravity="BottomLeft" columns="120,120,120"  >
      <fields>
        <field name="ma_unit" viewType="Lookup" inactivate="true" label="1" field="2" >
          <text v="Đơn vị" e="Unit"></text>
          <viewInfo lookupType="Multi" lookupId="sysunit" lookupKey="status = 1 and unit_id in (select unit_id from dbo.ISWIFTFunctionGetUnitIDRight(@@userId, @@admin, ''))" lookupCheck="1 = 1" lookupRef="ten_unit" />
        </field>
        <field name="ten_unit" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" label="1" field="2" operation="=" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
              <option val="">
                <text v="Tất cả" e="All"></text>
              </option>
            </options>
          </viewInfo>
        </field>
        <field name="user_id0" viewType="Combobox" inactivate="true" label="1" field="2" operation="a.user_id0 = @@userId" >
          <text v="Lọc theo người sd" e="Filter By User"></text>
          <viewInfo>
            <options>
              <option val="">
                <text v="Tất cả" e="All"></text>
              </option>
              <option val="1">
                <text v="Lọc theo người tạo" e="Filter By Create User"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>uw3iZoR/y/5o6FF1x5y/2Sz1qZ1gTfLy7dPX/UBEpuSEXg3kdoQW5ZV1B2YtFv3GktQs3HGWZLQPzxviSG/OJMPio64xyCNNg14XdhP/S3bCSVemnjO8b4NSaqxV3eaQJLsLiU6oFOxWhUoflL/dQtf5K3Nz+m3d4SpjAr/yaSjCh4V7JPpPcnGprBzfcnmk</enc>]]>
    </text>
  </js>

  <script>
    &VoucherJSLoading;
  </script>
</dir>