<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="m65ctchi20" fieldKey="id" voucherCode="CR1" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc danh sách phiếu chi" e="Filter FCL Order Numbers"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D">
          <text v="Ngày từ/đến" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" aliasName="@DFDTo" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D" nextRow="false">
          <text v="" e=""></text>
        </field>
		<field name="ma_kh" allowBlank="true" viewType="Lookup" label="1" field="1"  hidden="false" nextRow="true">
          <text v="Người ứng" e="Customer"></text>
          <viewInfo lookupType="One" lookupId="dmkh" lookupKey="status = 1 and nv_yn = 1" lookupCheck="status = 1 and nv_yn = 1" lookupRef="ten_kh" lookupInfo="dmkh|ma_kh|ten_kh" />
        </field>
        <field name="ten_kh" nextRow="false" fieldType="EX" readOnly="true" inactivate="true"  hidden="false" label="" field="1" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>

		 <field name="so_ct" label="1" field="1" allowBlank="false" viewType="Lookup" operation="like">
          <text v="Lấy số phiếu chi" e="Get the order number"></text>
          <viewInfo lookupType="one" lookupId="ctchi20" lookupRef="ds_so_dh" lookupKey="ngay_ct between ![ngay_ct1]! and ![ngay_ct2]! and ma_kh like ![ma_kh]! +'%' and status in (5)" lookupCheck="ma_kh like ![ma_kh]!" />
        </field>
        <field name="ds_so_dh" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
	
	
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>yjg08rIL27s3kh7i3AMU9Lx11ZNI9Ff7qDe1Flw7TQFQwWWrfy/ctfVeWNJFyWTCyybHOmhAID5Yf0+I32ttBGCIJXdkvACEsIlsZyduP9z2kyRRmDMQONxULOitn+4cIqzenrFeCskRGxrdRUTsiT3w1k4ZnRMu+BLyL0zMAuaE+z6NL9ETDjb6Iu3LL/ieLnZenLog+oYsI2U/CltnBVHpG60nw3Y5mQ0IpNlKrq++RshQdgu5wPR+VpSpD1AHqeOIFgMtW13rFVtHyx1x7QorJDsfeJ5NFmv5m2gMORuaJPiWg7cxnLJEGOS3ZM8e8nTDVBwe7Sx0jScFgQ7C5bI2Wx5iIznvhWQ2kbZOaTKNu6j6xC5VCm7z/JzXTIQhYzqNE6jIZAjR1KV9pN4RHnqZuihbTXRXEuoFFCWkJoSO+kT07z6TI8uoVD+0itGl9sus9MJPbsxY9jea+b+D3VuPlr6Wa1QDRts2qCZ2QeGc5N1k3wn75WHKF0KYHxOBktDP4JIEmW2cqVHGttDE4fPkz0XyvWhfymplDH4n2qs=</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>