<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="m72BN1" fieldKey="id" voucherCode="TG1" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc báo giá" e="Quotation Entry Filter"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" allowBlank="false" dataType="D">
          <text v="Ngày c/từ từ/đến" e="Date From"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" allowBlank="false" inactivate="true" dataType="D" nextRow="false">
          <text v="Ngày đến" e="Date To"></text>
        </field>
		<field name="ngay_ct" label="" field="1" allowBlank="false" inactivate="true"  hidden="true" dataType="D" nextRow="true">
          <text v="Ngày chứng từ" e="Voucher Date"></text>
        </field>
        <field name="ma_nt" hidden="true" label="1" field="1">
          <text v="Mã ngoại tệ" e="Ex Code"></text>
        </field>
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="ma_noi_di" viewType="Lookup" disabled="true" inactivate="true" label="1" field="1">
			<text v="Nơi đi" e="Origin "></text>
			<viewInfo lookupType="One" lookupId="vdmcangdi" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_di" />
		</field>
		<field name="ten_noi_di" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="ma_noi_den" viewType="Lookup" disabled="true" label="1" field="1" operation="like">
			<text v="Nơi đến" e="Destination"></text>
			<viewInfo lookupType="One" lookupId="vdmcangden" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_den"  />
		</field>
		<field name="ten_noi_den" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>  
		
		<field name="ma_hang" viewType="Lookup" disabled="true" inactivate="true" label="1" field="1" hidden="true">
          <text v="Mã hãng tàu" e=" Carriers"></text>
          <viewInfo lookupType="One" lookupId="dmhangtau" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_hang" />
        </field>
        <field name="ten_hang" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
		
		 <field name="ds_cong" allowBlank="true" viewType="Lookup" label="1" field="2"  hidden="">
			  <text v="Container" e="Container List"></text>
			  <viewInfo lookupType="Multi" lookupId="dmcong2" lookupKey="status=1" lookupCheck="status=1" lookupRef="" lookupInfo="dmcong|ma_cong|ten_cong" />
		</field>
		<field name="t_tong_trong" dataType="N" label="1" field="[120]" format="FCAmount" hidden="false" disabled="true" nextRow="true">
			<text v="G.W Volume" e="Gross Weight(KGS)"></text>
		</field>
		
		<field name="t_tong_khoi" dataType="N" label="0" field="[120]" format="FCAmount" nextRow="false"  hidden="false" disabled="true">
		  <text v="" e=""></text>
		</field>	

        <!-- <field name="so_ct" label="1" field="1" allowBlank="true" hidden="true" viewType="Lookup"> -->
          <!-- <text v="Số báo giá" e="Quot. Number"></text> -->
          <!-- <viewInfo lookupType="One" lookupId="v311" lookupRef="ds_so_ct" lookupKey=" ![ngay_ct2]! >= ngay_hl  and  ngay_hld >= ![ngay_ct1]! and ma_noi_di = ![ma_noi_di]! and ma_noi_den = ![ma_noi_den]! and ma_kh like ![ma_hang]! +'%' and unit_id = ![unit_id]!" /> -->
        <!-- </field> -->
		<field name="ma_ct_dh" label="1" field="1" allowBlank="true" hidden="false" disabled="true">
          <text v="Mã chứng từ" e="Quot. Number"></text>
        </field>
			
        <field name="so_ct" label="1" field="1" allowBlank="true" hidden="true" >
          <text v="Số báo giá" e="Quot. Number"></text>
        </field>
		
        <field name="ds_so_ct" nextRow="false" fieldType="EX" readOnly="true"   hidden="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
	
	
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>6zqcKTM+BlB9FgSJhQ+uJmd3vjgRLZI3HnuLFiC9LznB+S+RVaYnWGAAzJndoEcaUVox/rV9k7lUKhOO4BRDGJ4WsGyvLWzPwBJUPOTF/W33Cd9wOnd1k2ewT8FbabaapnOTL7Ing6ypWx7ypLH93PpADiPJ+88PnBBhPlshEaDTmpIB9Ilm16jZ+dlWfUmxAsoMKLQ28RgrUky6pOVQfh8np+tfQwjiRfDd7tI1FP56lS07DoMo5GKwkD84xZDefjHER4iM5Z5yFV0kOCBckz3KAgFbUzSVV+UoV13O1FZQdZOVqab8I/HZSWeV/1Sj40wPCtg1qfuy0KSKZ1tAmz2gX+lPqOpoDqfQrEAzVAciMsIjnGtdEKyF/LFP7BkVOzawL+/QhHlvetJFD2b4wQMKHtT3cB+DadoeyiUQsJQ0XXln49qVahTFQQzTRVFMnnR+1K25anoZ+z43omsPOsGrVx4MV6Qq/vRqhrFxBlx3ycM9syQh/HVpMfoH66Q9mRTnckbm9CbaC0dMsu1+zOiNxIaHbn1NH7dr2gOMzrCCrw8TNV6b/5LIESoHifqjqsJaXuGFqhSmEk068JlOq9Lof+0ucMjxN9wTkcfmsIxG02J0Fs+ywoT+GkHVKRi3fALawJdzsXYO7YU1b65+DQ==</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>