<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="m72PX3" fieldKey="id" voucherCode="CR1" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc danh sách phiếu bán" e="Filter FCL Order Numbers"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D">
          <text v="Ngày từ/đến" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" aliasName="@DFDTo" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D" nextRow="false">
          <text v="" e=""></text>
        </field>
		<field name="id_dh"  label="1" field="1" nextRow="true" hidden="true">
          <text v="ID DH" e="Voucher Number"></text>
        </field>
		
		<field name="ma_job" label="1" field="1" disabled="true">
          <text v="Mã đơn hàng" e="Order Code"></text>
        </field>
		<field name="so_job_dh" label="0" field="1" nextRow="false" disabled="true">
          <text v="Số đơn hàng" e="Order Number"></text>
        </field>
		<field name="id_m54" label="1" field="1" allowBlank="false" viewType="Lookup" operation="like">
          <text v="Lấy số phiếu bán" e="Get the order number"></text>
          <viewInfo lookupType="one" lookupId="m54" lookupRef="ds_id_m54" lookupKey="ngay_ct between ![ngay_ct1]! and ![ngay_ct2]! and id_dh_nb like ![id_dh]! + '%' and xstatus = 5" lookupCheck="id_nb like ![id_dh]! + '%' and xstatus = 5" />
        </field>
        <field name="ds_id_m54" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>	
      </fields>
    </form>
	
	
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>d3reR4MpBKvFMFpkk39mW9FLK4VLF54JVPF1vioLSVBc47gUIGpRy7o/hRnhwx1oe/ISorIyTWDqYJAaEAR674YanJzCZuliBzREs1OFeF6pQBlTjufYcRYUJvABkQaltkcxIYZ5Ur6QMLxQNziRVGqKDLZKZF1nKbkj2F5rXe1Sv2otZXbdbmoCi5F1R6TyvaC1xtEsh8S//Fa6LrUgIs0GJ40htAE2YGxX1QV5ZhHBXbe/lL3Rdgu+qMMKxppMfeLyxjSjk3fBHbog6Cr76/N/I4InhIaKLLNz5W0RVSN1pcvAg1IQArjYOkUCPTvJmPtO+EvUdXEUhmJcLF7OWg6paPrin76jo3xbLkuvjDaTB4Jv9SKyHHc7atVwaRWpzFY8EZnqtKhkJ0JGfQVlL08MTZzy8hijX6Jexbm7V64aVrNE/Y5HFhRYYvS1GapZkrCly0jzYBHnT4B2cP9xm77eddUTvgCtBlaWl6nBz6U3dMUYpk7dS9rCkFImRZA7</enc>]]>
    </text>
  </js>
<css>
    <text>
      <![CDATA[<enc>/T0x+X5J8VnLtXSs8xERBy5XsIhTcMK77n2BsK4suh7al6IPHe8OdNVaharGtBWo9R48jT6gp9H8MYSEzVBuOMpIATmaM+12t0R46YQ1t/YGPOSdwPbvJjdowWS38VFKPlctvuRgUZT93pNFe3ghhiNQWCkIY4rjTrY7HTHOg2k=</enc>]]>
    </text>
  </css>
  <script>

  </script>
</dir>