<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="m82CR1" fieldKey="id" voucherCode="CR1" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc danh sách đơn hàng" e="Filter FCL Order Numbers"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D">
          <text v="Ngày từ/đến" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" aliasName="@DFDTo" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D" nextRow="false">
          <text v="" e=""></text>
        </field>
       
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>	
        <field name="ma_noi_di" viewType="Lookup" disabled="false" label="1" field="1" operation="like">
			<text v="Nơi đi" e="Origin "></text>
			<viewInfo lookupType="One" lookupId="vdmcangdi" lookupKey="(kkh_yn = 1 or hc_yn = 1) and status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_di" />
		</field>
		<field name="ten_noi_di" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="ma_noi_den" viewType="Lookup" label="1" field="1" operation="like">
			<text v="Nơi đến" e="Destination"></text>
			<viewInfo lookupType="One" lookupId="vdmcangden" lookupKey="(kkh_yn = 1 or hc_yn = 1) and status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_den"  />
		</field>
		<field name="ten_noi_den" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>	
		 <field name="so_ct" label="1" field="1" allowBlank="false" viewType="Lookup" operation="like">
          <text v="Lấy số đơn hàng" e="Get the order number"></text>
          <viewInfo lookupType="one" lookupId="s61" lookupRef="ds_so_dh" lookupKey="ngay_ct between ![ngay_ct1]! and ![ngay_ct2]! and ma_noi_di like ![ma_noi_di]! +'%' and ma_noi_den like ![ma_noi_den]! +'%'" lookupCheck="ma_noi_di like ![ma_noi_di]! and ma_noi_den like ![ma_noi_den]!  and status in (5,6)" />
        </field>
        <field name="ds_so_dh" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>	
      </fields>
    </form>
	
	
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>IOtmQw+hlbKKUjwffg5sQ7yvZFkbY57oi95S6iCNXEDp/ioyu1giXuXMO84MVG1qsD8AUTUWm4acp/rSVi5SfgvY51r73HohQ1QFZkKoeWMxqAaaRpeFVN4N1GShdglHFyqv5koNidrcY7W8RlS8CN+XDQvJ1kNaHbGHoEmttsfAOhWYJcWUc9vNvFIn9k9d/7Yj0BGUwzxa8Ig5ezbA/c0lsy6qHpCOMTqMjWmXhh3gh6AFHNE7/DK8pByBQX8rXi3/+ahWtW6CDZUtQDQw3movNKFMMQOImGcswjVCQ5af2MFORY6wa4L+UNfehEbCoVp9fSLG7JByYa6g8I+rrjEOVugIUP0akFlSuR4RRWnXEF48ahyNGUOMsJQbXbthztyv3lcKItXQ7FvBOTjxzbh0PaLragZu8EqxzmCv/6AoLXLGLQ8CE4oS2WhoW+aqKZBDraDpsgz23qKQzVxRFdpLUJkg5KD0XmEe7YB7+G48tqQbKODrdi3bvC07Z3o/jdujyFi2JW6hqNxdifRAMYviySwc8JgrY2hkhfi8tFM=</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>