<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="m85PX1" table="" height="" fieldKey="id" voucherCode="PX1" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc phiếu xuất" e="Issue Filter"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" allowBlank="false" dataType="D">
          <text v="Ngày c/từ từ/đến" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" allowBlank="false" inactivate="true" dataType="D" nextRow="false">
          <text v="Ngày đến" e="Voucher Date"></text>
        </field>
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="ma_kh" viewType="Lookup" disabled="true" inactivate="true" label="1" field="1">
          <text v="Mã khách hàng" e="Customer"></text>
          <viewInfo lookupType="One" lookupId="dmkh" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_kh" />
        </field>
        <field name="ten_kh" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
        <field name="so_ct" label="1" field="1" allowBlank="false" viewType="Lookup">
          <text v="Số phiếu xuất" e="Voucher Number"></text>
          <viewInfo lookupType="Multi" lookupId="m73" lookupRef="ds_so_ct" lookupKey="ngay_ct between ![ngay_ct1]! and ![ngay_ct2]! and ma_kh = ![ma_kh]! and unit_id = ![unit_id]! and status in (5,6)" />
        </field>
        <field name="ds_so_ct" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>37YA8pIV31z1GB2JMvgyiFBezU/onTjOTXtYEJnK/JYTX8ED+1sO7uo+6KJQlty+9+n8wJ2ygYGcKFm1rzZO47+l5a+WYEdVb8YjV6ykJSY0RoWMg5fs2EkB7roVVLsd3fpqDz9TjpnO5DvZeIl7JcZwj4PKIcPLJrSd7BjkSWcnGUWZAAPpWYlsgVgdLKCPJg9GgYi3pxWuoGs0VfXc8QLk36x6cwj0/+v5IqHBpGUY28DocOSjt9HiiYaSbESyXp3xRsvkm3nWMx0kQErWxCYwLpKe+hqCNCR3CwK6BblRNd9bJtYlEKVJ6wpkd8TxiTRnMI4jkHFSxRiSPHGln4Am/Iafr1Q9pUSJ3XQ2VmpC5qxHp7J1gzY2X7+w2jkpZul7Vd7RERIFcWcsc0M3wCzYgBYjnO2DyNGbf68BprG2G4vlcLSa+IT7ajSIkBB3kE89mAED8aQdRsf/F7QwnrYYXTzYD9hEzLv4C0UVMwNCUOBoDqSgfJpUKJeCRRA4</enc>]]>
    </text>
  </js>
</dir>