<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="n14Approve" table="" height="" fieldKey="id" voucherCode="CL0" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc chấm công(Duyệt)" e="Filter training form (Approve)"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D">
          <text v="Ngày c/từ (từ/đến)" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" aliasName="@DFDTo" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D" nextRow="false">
          <text v="" e=""></text>
        </field>
        <field name="so_ct1"  label="1" field="1" operation="a.so_ct &gt;= N'%s'">
          <text v="Số c/từ (từ/đến)" e="Voucher Number"></text>
        </field>
        <field name="so_ct2"  label="" nextRow="false" field="1" operation="a.so_ct &lt;= N'%s'">
          <text v="" e=""></text>
        </field>


		<field name="ma_bp" viewType="Lookup" label="1" field="1" operation="like" allowBlank="true">
           <text v="Nhóm" e="Team"></text>
           <viewInfo lookupType="One" lookupId="dmbp" lookupKey="status = 1 and unit_id = @@unit" lookupCheck="1=1" lookupRef="ten_bp" lookupInfo="dmbp|ma_bp|ten_bp"/>
        </field>
        <field name="ten_bp" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
           <text v="" e=""></text>
        </field>	
		
        <field name="dien_giai" label="1" field="-" operation="a.dien_giai like N'%%s%'">
          <text v="Diễn giải" e="Explain"></text>
        </field>
      </fields>
    </form>

    <form gravity="BottomLeft" columns="120,120,120,120"  >
      <fields>
        <field name="ma_unit" viewType="Lookup" inactivate="true" label="1" field="3" >
          <text v="Đơn vị" e="Unit"></text>
          <viewInfo lookupType="Multi" lookupId="sysunit" lookupKey="status = 1 and unit_id in (select unit_id from dbo.ISWIFTFunctionGetUnitIDRight(@@userId, @@admin, ''))" lookupCheck="1 = 1" lookupRef="ten_unit" />
        </field>
        <field name="ten_unit" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" label="1" field="3" valueDefault="1" operation="=" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="Chờ duyệt (Xử lý Duyệt/Hủy yêu cầu)" e="Open (Approve)"/>
              </option>
              <option val="5">
                <text v="Đã duyệt (Xử lý bỏ duyệt)" e="Approved (Undo)"/>
              </option>
            </options>
          </viewInfo>
        </field>
        <field name="user_id0" viewType="Combobox" inactivate="true" label="1" field="3" operation="a.user_id0 in (select user_id from sysuserinfo where user_ref like '@@userRef%')" >
          <text v="Lọc theo người sd" e="Filter By User"></text>
          <viewInfo>
            <options>
              <option val="">
                <text v="Tất cả" e="All"></text>
              </option>
              <option val="1">
                <text v="Lọc theo nhân viên đang quản lý" e=""></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>8Y+cBM1q/katAB8dXforbiYK9ps5KMQ6mGYpLN+sBeyAu/W/7p8EXLhXy1lvxCqX1ENfar+yE8pUdu5slQ1G9CeTJRZnNdK77UAoyYCsBSkbCSFWgDUUXuarS6jFw6YfWq3FR2YTbsNSDbuoDrBkZhyu82amsfCyuZ2y1CCR5dJXK1I+wGjASlw83zV1M5qw3CUe7gpqrynhA6T48nZ7PQHR8vZ/lF5UHN8HbAKkQXjjeyNePqQHfo394a/jHsb8DKenVq4qK/XlpXtAXbUKknAF1utwQbD+IjpdYam/F1FVKz5VijaUMuOEZGSLynMhCglSwccYcnhIlhDQnqRFaA==</enc>]]>
    </text>
  </js>

  <script>
    &VoucherJSLoading;
  </script>

  <messages>
    <message val="approve">
      <text v="duyệt/hủy" e="Approve/Close"/>
    </message>
    <message val="undo">
      <text v="bỏ duyệt" e="Open "/>
    </message>
    <message val="open">
      <text v="bỏ đóng" e="Open"/>
    </message>
  </messages>
</dir>