<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
  <!ENTITY VoucherExtendFields SYSTEM "..\Include\XML\VoucherExtendFields.xml">
]>

<dir id="q64_1Select" table="" height="" fieldKey="id" voucherCode="BQ1" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Chi tiết phiếu được chọn" e="Quotation Entry Detail"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
		<field name="ngay_ct1" label="1" field="1" readOnly="true" aliasName="@DFDFrom" disabled="true" allowBlank="false" dataType="D">
          <text v="Ngày c/từ từ/đến" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" allowBlank="false" disabled="true" inactivate="true" dataType="D" nextRow="false">
          <text v="Ngày đến" e="Voucher Date"></text>
        </field>
        <field name="ma_nt" hidden="true" label="1" field="1">
          <text v="Mã ngoại tệ" e="Ex Code"></text>
        </field>
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>

		<field name="ma_kh" label="1" disabled="true"  field="1" >
          <text v="Mã nhân viên" e="Employee Code"></text>
        </field>
		<field name="ten_kh" allowBlank="true" label="1" disabled="true"  field="-" importWidth="250" importable="10">
          <text v="Tên nhân viên" e="Employee Name"></text>
        </field>
		
        <field name="xprocess" label="1" field="2" valueDefault="2" viewType="Combobox">
          <text v="Xử lý" e="Process"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="Thêm vào chi tiết" e="Append To Detail"></text>
              </option>
              <option val="2">
                <text v="Xóa hết chi tiết và thêm mới" e="Delete All Detail And Append New"></text>
              </option>
            </options>
          </viewInfo>
        </field>
		<field name="id" dataType="N" hidden="true" fieldType="PK" label="1" field="1"  >
			<text v="ID" e="Code"></text>
		</field>
      </fields>
    </form>
	
    <form tabPageIndex="1" gravity="MiddleLeft" height="350" columns="120,120,240" >
      <text v="Chi tiết" e="Detail"></text>
      <fields>
        <field name="ctqlq20" label="" field="-" viewType="Grid">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
  </forms>

 <grids>
    <grid id="ctqlq20" table="ctqlq20" fieldKey="id, line" order="id, line" allowFilter="true" readOnly="false" allowOrder="true">
      <fields>
		<field name="chon_yn" dataType="B" width="80" valueDefault="1" readOnly="false" >
          <text v="Chọn" e="Check"></text>
        </field>
        <field name="id" dataType="N" width="50" format="0" >
          <text v="ID" e="ID"></text>
        </field>
		<field name="so_ct" width="80" fieldType="RF" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
		<field name="ma_ct" width="80" >
          <text v="Mã c/từ" e="Voucher Code"></text>
        </field>
        <field name="ngay_ct" width="100" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
		<field name="ma_kh" width="100" >
          <text v="Mã nhân viên" e="Employee Code"></text>
        </field>
        <field name="ten_kh" width="200" fieldType="EX" >
          <text v="Tên nhân viên" e="Employee name"></text>
        </field>
        <field name="t_tt" dataType="N" format="FCAmount" width="120">
          <text v="Tiền trên hóa đơn" e="Invoice amount"></text>
        </field>
        <field name="da_tt_nt" dataType="N" format="FCAmount" width="120" aliasName="t_tt*0 as ">
          <text v="Đã thanh toán" e="Received"></text>
        </field>
        <field name="cl_nt" dataType="N" format="FCAmount" width="120" aliasName="t_tt*0 as ">
          <text v="Còn phải thanh toán" e="Receivable"></text>
        </field>
		<field name="ma_ct_dh" width="100" inactivate="true" hidden="true"  >
          <text v="Mã c/từ đh" e="Voucher Code"></text>
        </field>
		<field name="so_ct_dh" width="100" inactivate="true" hidden="true" >
          <text v="Số c/từ đh" e="Voucher Code"></text>
        </field>
        <field name="ngay_ct_dh" width="100" dataType="D"  inactivate="true" hidden="true" >
          <text v="Ngày c/từ đh" e="Voucher Date"></text>
        </field>
		<field name="ma_job_dh" width="100" inactivate="true" hidden="true" >
          <text v="Mã job đh" e="Voucher Code"></text>
        </field>
        <field name="so_job_dh" width="100" inactivate="true" hidden="true" >
          <text v="Số job đh" e="Currency"></text>
        </field>
      </fields>

      <buttons>
        <button id="freeze">
          <text v="$FreezeToolbar" e="$FreezeToolbar"></text>
        </button>
      </buttons>

      <script>
        <query>
          <text>
            <![CDATA[<enc>7dkt8IUJdf+fggEJrmwgn7/c+uJJmELzLlN069g/edbkt29iUTEyErSDqKHASeWD/Vkyr9LJ8ga5nbxwvF2ipKUPJ81fJxjlxSaQ132XWk6cUAsWr4MFNFB4R1NHehFFV57VqnioV4tC69SbhtPrubH+1jsnlCEOHaGuaSO7I73YgYZ/ANBC3QTkhsqs93hPEbgGcRlFWvfedLuwgzBAyBwvGYYf+idfqkWP8BuNoCtVn0CnYRZT+2CvAfOslvyMsQwjupJrpUanCOAf8OhK/wMTJNX8m5IoNqUbv04XEXwlRi/auHDl3fjJKtpjUz+dV+L1JOxIxuZd057FkQvaiHmdOZXFAO0phXgOaUut+sqNec0CTnVdK8nABoMmhcr36NkEIkBWyxKl5F5DxyEN/vmNFPiZS+H6mbMvKCdZGfburHZH6/zimBkbF9AUcZuKEFA4ZFVi8hLLuqVIrFgvMt1utKhAePDQu0q4zSAr1TpIlg7aPFTz2weWUuMHOURg1yOANg0E45KmIGTu6CPPocGeeseoAAUNv75VsXS/Go4JNPibiN7kkpoxk8W61dgg/PCLKe8BwOf14xh9TVS7sBhJp0iERPhiYphtg3io8NZpaWUPCrPx1BTkYhq6tEQYf/TxSYPbR06ijIcCLIBu7ZdlhAUuUviYEmnQ+Fq3fluLWvUKNzoGmBjVkhJFZl+idEHzAopqbyNAdvsbQ99h5rE5P366hVgAi9XNkLx/fyI=</enc>]]>
          </text>
        </query>
      </script>

    </grid>
   
  </grids>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>l6YXouPCl+9YFRqCaCLgmDcQWIQ4AWfFpPbAvSEdvn1em4W9GQA0bZUVSTqCq+o9dQ4fIo20Y4GNdB9Hm1OdWSIeezhS0MIyTV+FPGtFFZIUvl2pigP9WG+SbG5LsgiSMyJCGSIGXqxeV6CvTpwdgF3sjsugXBqbwaynCNnmvikV6T5tAeQFBaWluRpIFAWXClVA7fQBRzPJiFjvM1zS8sZyrzcx3bSM+tTA5hALTh5h/6UYfvtg/3Ixn6HN/yGChqugGK/ReUk9p6Oe2tOHrPRGbXZa5AltwBGXSfCESKLeHwInhoKYizGzRmF8mEQ9zNoQfbJNRELw2Wn8RNjxnkVu3G/l+ysVxIuh7NtCaVV0bDcyfc7NCSsgZQxZdxXiW0zPVtLKUf01T6Et1i7CQf2d4SvnfYzBL0KLQwWccVmq+9lWRyXRo2jNhvkRar89SUli+o/qdaqCDpPkBiyKqHkb6kCiHw8pQHVO2zYoEo3/z+XXvM+F4b4TKNmG1/zy4tRICslqxzu15afqRM5KJxFkkHn8R4fLMJcGvF4lVjAoxzF6FjLkuGUm8cseJ3MX4EcLvhe4vJwLAoYpCwucHeSbvVxleSfBB1NBEgJm7dsIbEt88Pu1MbXRhbRrsp24EF/GMdQPNn62VRolkx17iscxrxvqhY3zQYtOCATSzhk6qjPfr1Oa0mZVqQBz8EHa/+8nWK0JFhf9tvXqkn9RFiDIWfJ/Sana21NkI7P3hCEemKU7SQMZnayHgP6XMM8QanwIftbjyiijSCNRxzBM/WYXY7w4boAXvpdM567aa5YFqs1nceJytWGraLNq+Qt7iN4s4OZzh+xPPG7f6tzo/yb6HT7EHY5dn5k9rTxgm6Q=</enc>]]>
    </text>
  </js>
  
  <script>
		<request code="ma_kh_request">
			<text>
			  <![CDATA[<enc>FTkFm4igxdrH0JOWCSE3pGHYC1WBe4eYZxuXqK1sQME=</enc>]]>
			</text>
		</request>
  </script>
</dir>