<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="qldctcccd_1" table="" height="" fieldKey="ma_pl" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Điều kiện lọc" e="Filter Condition"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120,120,120,120"  >
      <fields>
		<field name="ma_dancu" inactivate="false" label="1" field="-" operation="ma_dancu like N'%%s%'" >
			<text v="Mã dân cư" e="Resident Code"></text>
		</field>
		<field name="ten_dancu" inactivate="false" label="1" field="-" operation="ten_dancu like N'%%s%'">
			<text v="Tên dân cư" e="Resident Name"></text>
		</field>
		<field name="ma_hogiadinh" label="1" field="1" allowBlank="true" nextRow="true" hidden="true">
			<text v="Mã hộ" e="B/L No"></text>
		</field>
		<field name="status" viewType="Combobox" label="1" field="1" operation="=" >
          <text v="Trạng thái" e="Status"></text>
		  <viewInfo>
			<options query="select ma_tt, ten_tt%l from dmttsd where status = 1 ">
				<option val="">
                <text v="Tất cả" e="All"></text>
              </option>
			</options>
		  </viewInfo>
		</field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>g37U4Fsz+eokjPk3TwfHlAOFBNDV/ZqaVQ+fI0eNz4KpSO68P04n4BSKo0RXlcFARZlykllEgx85gH1BRNr4OIywUq31aWFRIdBHiQ99cS6cDh385zN5m4hdHiXG4gcBrypq5ypdByAga9e5IcPaZTmRZTMkzlFrRnEMsP9FO+vT/cfJKb9eCE9rXJM4YGDJRRy/LBYsxeJ8tbdVOl7K0Q==</enc>]]>
    </text>
  </js>
</dir>