<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="qlhccong" table="" height="" fieldKey="ma_pl" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Điều kiện lọc" e="Filter Condition"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120,120,120,120"  >
      <fields>
		<field name="ma_pl" inactivate="false" label="1" field="-" operation="like" >
			<text v="Mã văn bản" e="Document Code"></text>
		</field>
		<field name="ten_pl" inactivate="false" label="1" field="-" operation="ten_pl like N'%%s%'">
			<text v="Tên văn bản" e="Document Name"></text>
		</field>
		<field name="ten_pl2"  inactivate="false" label="1" field="-" operation="ten_pl2 like N'%%s%'">
          <text v="Tên English" e="Name English"></text>
		</field>
		<field name="tu_so" dataType="N" label="1" field="1" operation="tu_so &gt;= N'%s'">
		  <text v="Ký hiệu từ" e="Word symbol"></text>
		</field>
		<field name="khoang_cach" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" hidden="true" label="[0]" field="[60]">
			<text v="" e=""></text>
		</field>
		<field name="den_so" nextRow="false" label="1" field="1" operation="den_so &lt;= N'%s'">
		  <text v="Ký hiệu đến" e="Incoming symbol"></text>
		</field>
		<field name="status" viewType="Combobox" label="1" field="1" operation="=" >
          <text v="Trạng thái" e="Status"></text>
		  <viewInfo>
			<options query="select ma_tt, ten_tt%l from dmttsd where status = 1 ">
				<option val="">
                <text v="Tất cả" e="All"></text>
              </option>
			</options>
		  </viewInfo>
		</field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>uw3iZoR/y/5o6FF1x5y/2Zqh+REHQGEc5dVjCNewjyn0za2I9EgvKD5QGgK4aBC3NWFbbID/B4WVOwE0eg7wOR8qjEBq/VbR8czY0o4A8Vp5LvLT5V1tJVjz9pR16uyqZfBlrtw+NIaqf9nFlVqXgY/dbwlDJoCNZQfl6wgK4fUnq2WM/gcKwid+kdIGldsJ</enc>]]>
    </text>
  </js>
</dir>