<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="s331C1" fieldKey="id" voucherCode="" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc danh sách cảng" e="Filter The Port List"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
       
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>
		
        <field name="ma_ttp" viewType="Lookup" disabled="false" label="1" field="1">
			<text v="Khu vực" e="Area "></text>
			<viewInfo lookupType="One" lookupId="dmttp" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_ttp" />
		</field>
		<field name="ten_ttp" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="ma_qg" viewType="Lookup" label="1" field="1" operation="like">
			<text v="Quốc gia" e="Country"></text>
			<viewInfo lookupType="One" lookupId="dmquocgia" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_qg"  />
		</field>
		<field name="ten_qg" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>  
      </fields>
    </form>
	
	
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>CYr/JYVxoIGpzpArwj4J0bcOomK9Tl74xLy6miRL6R3EIIUXZTcGtEqrh7pjCtxYPpMyc9VvssUXPVn+ddG5YGgcmtdDkhdnoewoRpHWNNmCkFsw71hbY1DFD4s7mJo4Go4WUZZZagluEsA1NGO+my6Aqfitc5Ny+FcewzPV27J4AOlQqyOWRxuXDhXsCSWsDdy7kNHelCNaiyOtBQn6LWC8a4O59w+GM1rvrjBj2A9wteBS89u2QYUQ8acstV4kolT/xUZCMRWYrAo5kzdNd/Yq8aALzpmAaHyA3abgcrU+GE8UCqF8W1/cMsV/6hLAEEik7CBGVctk8TLAgZ0Pj+aiB1/zZQ6Pi+NrfLpeX65hh2a6Xg5PnUoU3f0f2aHaTqBSln4kVavEQLSYm23D0+xJCTuxd+fzj0jNwXHOAGJEzobBhMGL3fAEgJwojR2d2yXEYp8stM2lrHujzvUBpn6NK2ArMM7skQdV4gi4CKQt6JcLNmSXvyhkDaeKlIAAn+QRatj/LdtNoeSEcU+z5Vk1qsNbJXZ2Hs8UmvNTbETQzFZ+VmN8zHcxmLyFD+LJ</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>