<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="s322C1" fieldKey="id" voucherCode="" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc danh sách cảng" e="Filter The Port List"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
       
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>
		
        <field name="ma_ttp" viewType="Lookup" disabled="false" label="1" field="1">
			<text v="Khu vực" e="Area "></text>
			<viewInfo lookupType="One" lookupId="dmttp" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_ttp" />
		</field>
		<field name="ten_ttp" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="ma_qg" viewType="Lookup" label="1" field="1" operation="like">
			<text v="Quốc gia" e="Country"></text>
			<viewInfo lookupType="One" lookupId="dmquocgia" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_qg"  />
		</field>
		<field name="ten_qg" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>  
      </fields>
    </form>
	
	
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>hzH3MjYwFwEwj3RvVlJhhdXHU8Mu8MiAZVLZ6mUzBrAh6i3jqA/XXSHlq4iWo0VWT0fYLgPSv1wMaFCoU2FpSI02nSb+HJUKEJbxBQK8Rtho0Jvg1D1+9iBAW+2W9us/RKubktZ4ZhHPg4d7DSDu3bVb9+04JMKIt7No8p06ufmoEOzSI2+a+qaAp63keheneZGn6Io9Hs3lok7OriX/qx5aTATNXBQ3ZmiE+IswTA6zJZNRDi+KU68n8efyqKu7mW7DdJdZ7v+XhFDZMt6e1SC/HlrM+qhBfliYRkzQHdEhS9V0C3QE3NJBhgHtdiNaLNfmZ67WEakgv0wqR767FnTMCmzPd+Wo6ySnYpq/WHVxnlTwHDmoQn+pRtahyYyq/tsWMD2jQR3dlXWk371nmORYT1cI7V6OM+5urVX3M7HjQj75CMU5bUkGWiXX47H6uxoPKlMz6mpHVrxFLuuF6txS5ppW/W/aDRkU+wP5BUY3QEJUiY5fXKdiu92aetxYxZXb8aRa30K69QutTmtR7BpVStIJKUfHNg7u1MbhHUs=</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>