<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="s333C1" fieldKey="id" voucherCode="" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc danh sách cảng" e="Filter The Port List"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
       
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>
		
        <field name="ma_ttp" viewType="Lookup" disabled="false" label="1" field="1">
			<text v="Khu vực" e="Area "></text>
			<viewInfo lookupType="One" lookupId="dmttp" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_ttp" />
		</field>
		<field name="ten_ttp" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="ma_qg" viewType="Lookup" label="1" field="1" operation="like">
			<text v="Quốc gia" e="Country"></text>
			<viewInfo lookupType="One" lookupId="dmquocgia" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_qg"  />
		</field>
		<field name="ten_qg" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>  
      </fields>
    </form>
	
	
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>hzH3MjYwFwEwj3RvVlJhhVpvx1QM7TLWQtTOpXUdm2yNmr+Zf/19RxkdKQ1470415Vb+tnE7J+zinqf2FNi2v2B6MyiABQzvfXs7JacMi+znQyxGNd173R/fkP7Ov3pd6rmW07NtNONpns/OLniQX6buGi7W3PtORqZKxmPRPUQc7X7zT3rfK0MTwtqqLFh4Od87uQMMBo/hESPfamA75Tn5CkgzLM8MtbB+sfZIfOViWU6SBIt3YtHLnMGzMjbDg3Ys1sV5dkgFH48y4R/QQEpA7kbP+qk9qDYS76bfXJ3K/zJoFv54PGLsyj8O6L5iYdZzs9+fIYpQQFAZ45i87EsEVGBZR4RKPuTNkxwizGpDPaRxBZ44IjkCzuKYUTEqd6ya/OGm0gsiK1RigmyQ0qVtbveOixO9XFZtmf5C7fsrH8fAjkavnrj8WT7/B6yKM5k4NwcPXnVAgN+o279yCgchAxMCaXLT1sGuVjYtB183r+BCnpQg3eN7wPBiqULH6ejtn9OHh0WvWPSiMhmAKYqEdgLA8PVcfvzUmSp3F7g=</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>