<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="s41YG1" fieldKey="id" voucherCode="YG1" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc yêu cầu báo giá" e="Filter quote requests"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" allowBlank="false" dataType="D">
          <text v="Ngày c/từ từ/đến" e="From Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" allowBlank="false" inactivate="true" dataType="D" nextRow="false">
          <text v="Ngày đến" e="To Date"></text>
        </field>
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="ma_noi_di" viewType="Lookup" disabled="false" label="1" field="1" operation="like">
			<text v="Nơi đi" e="Origin "></text>
			<viewInfo lookupType="One" lookupId="vdmcangdi" lookupKey="(kkh_yn = 1 or hc_yn = 1) and status = 1 " lookupCheck="1=1" lookupRef="ten_noi_di" />
		</field>
		<field name="ten_noi_di" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="ma_noi_den" viewType="Lookup" label="1" field="1" operation="like">
			<text v="Nơi đến" e="Destination"></text>
			<viewInfo lookupType="One" lookupId="vdmcangden" lookupKey="(kkh_yn = 1 or hc_yn = 1) and status = 1" lookupCheck="1=1" lookupRef="ten_noi_den"  />
		</field>
		<field name="ten_noi_den" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>  
		 <field name="so_ct" label="1" field="1" allowBlank="false" viewType="Lookup">
          <text v="Lấy số yêu cầu báo giá" e="Get a quote request number"></text>
          <viewInfo lookupType="one" lookupId="s11" lookupRef="ds_so_ct" lookupKey="ngay_ct between ![ngay_ct1]! and ![ngay_ct2]! and ma_noi_di like ![ma_noi_di]! +'%' and ma_noi_den like ![ma_noi_den]! +'%' and status = 1" lookupCheck="ma_kh = ![ma_kh]! and status in (5) and ma_ngv = 4 and ma_nt = ![ma_nt]!" />
        </field>
        <field name="ds_so_ct" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>O2D0IjtuowH6eeIQD28ZbNzdVsp+Rlx2Z/2jorXhbCWu3+kvq54QfEFnClhIjfa1D+LNVwAKInltdpmlGw7c0nLrcmoZ0Hr/asWycW7kb0fb2KVkooTIUll6QE61u0LdRZ6/sZQk9PRi+OzcQAX4ZBz7vyMQsNBU6Y1vxfYKWSvsEQBEMFC6AjAM6eTTteohZdQLrGDCoto8i6WSvmesVllmzvQHniUgxEdRR3IoDlfhR2fV+q6K2hCmxrn9nhEkFcWsFY80Lc/yPZdpeZthjCTJMlq/mcJ/wJfgAo+7GRmCFYzuEeu0xo7ABEQUfKZllPzc7JbqVf8+8+xM23xJpzIOosst65bqq/KhXgqJz8ZDPExyCts+eyrOLT5CURZ6HhOOuiwXjfQzKmxpHdMvswITHd7eJvfMrxC6vzTB+WekvmndOT+nhrLE2NlfKpDn1Zkh81zz6x3qmEAY2NS2DuloKZ4Tan77APButN8MQMziZnemOduJzMTo03iXnrEikMmm8h0pbgjpU9Z3xMqV67jdktG/jYIZNNoWZgQfIeKAdKlly7m1M3pZ1bl26V4/bP3ug+l8g8+5HHuk14EolJtB1kuAwpZ740w8HLiXoYIlHg2HCi4OJp/m97Vd7jB2</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>