<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="s42BN2" fieldKey="id" voucherCode="BQ2" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc giá cước" e="Rate Filter"></title>
  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
       <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" clientDefault="true" allowBlank="false" dataType="D">
          <text v="Ngày từ/đến" e="Date From/To"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" aliasName="@DFDTo" clientDefault="true" allowBlank="false" dataType="D" nextRow="false">
          <text v="" e=""></text>
        </field>
		<field name="ngay_ct" label="" field="1" allowBlank="false" inactivate="true"  hidden="true" dataType="D" nextRow="true">
          <text v="Ngày chứng từ" e="Voucher Date"></text>
        </field>
        <field name="ma_nt" hidden="true" label="1" field="1">
          <text v="Mã ngoại tệ" e="Ex Code"></text>
        </field>
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="ma_noi_di" viewType="Lookup" disabled="true" inactivate="true" label="1" field="1">
			<text v="Nơi đi" e="Origin "></text>
			<viewInfo lookupType="One" lookupId="vdmcangdi" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_di" />
		</field>
		<field name="ten_noi_di" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="ma_noi_den" viewType="Lookup" disabled="true" label="1" field="1" operation="like">
			<text v="Nơi đến" e="Destination"></text>
			<viewInfo lookupType="One" lookupId="vdmcangden" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_den"  />
		</field>
		<field name="ten_noi_den" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>  
		<field name="ma_hang" viewType="Lookup" disabled="true" inactivate="true" label="1" field="1" hidden="true">
          <text v="Mã hãng tàu" e=" Carriers"></text>
          <viewInfo lookupType="One" lookupId="dmhangtau" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_hang" />
        </field>
        <field name="ten_hang" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
		 <field name="t_tong_trong" label="1" field="1" dataType="N" disabled="true" readOnly="false" nextRow="true" format="FCAmount" >
          <text v="Tổng trọng lượng" e="Total Weight"></text>
        </field>
		<field name="t_tong_khoi" label="1" field="1" dataType="N" disabled="true" readOnly="false" nextRow="true" format="FCAmount" >
          <text v="Tổng Volume" e="Total Volume"></text>
        </field>
		<field name="cvc_yn" dataType="B" clientDefault="true" label="[60]" field="[40]" nextRow="true" hidden="true" inactivate="true">
          <text v="Cước v/c" e="Freight"></text>
        </field>
		<field name="xk_yn" dataType="B" clientDefault="true" label="[60]" field="[40]" nextRow="false"  hidden="true"  inactivate="true">
          <text v="Xuất khẩu" e="Export"></text>
        </field>
		<field name="nk_yn" dataType="B" clientDefault="true" label="[60]" field="[40]" nextRow="false"  hidden="true"  inactivate="true">
          <text v="Nhập khẩu" e="Import"></text>
        </field>
		<field name="pp_yn" dataType="B" clientDefault="true" label="[60]" field="[40]" nextRow="false"  hidden="true"  inactivate="true">
          <text v="Phụ phí" e="Surcharge"></text>
        </field>
        <field name="so_ct" label="1" field="1" allowBlank="true" hidden="true" >
          <text v="Số báo giá" e="Quot. Number"></text>
        </field>
		
        <field name="ds_so_ct" nextRow="false" fieldType="EX" readOnly="true"   hidden="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
		<field name="id_yc" dataType="I"  readOnly="true" fieldType="PK" hidden="true" >
          <text v="Id yc" e="Request. Id"></text>
        </field>
      </fields>
    </form>
	
	
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>HQXkUK2rqOFEm6pTGyYXcCpdSpl7wd68VFJfJ1v4JvsqcPdt6234IQXSD4tlVs+x2s4/UBQ0P0hK4/Vqo0WUVlkVrVogsA/0RH5JYYkuUlE0D7ApWUdZicJFnxsPyOyF7lY7KEmx2JJyzo4ZDIGPnImkI1VK4L8z6KO0jwwAz8MREOAMxTAeT5zhsDiJazOP7Fn9VtZTA4RhYm12SX3xgeyYY8unhgU0B+mX0qvdXmA2E+S7m0ADQObM8KHmCFvB0oqypEOwm+NxMPEWumhR/4BhOgequQ5GLsWxaUFcwK76e5gnKAruNvl1scj3MfnbYs7ZHE+p5flHy7Nmx7YXcGYOIKR019K8kU12myeAWkZzD4pgfZFax5KU5E3bx3kPdNsbM2ZUA9/NzrqJiH7SnQJskIFLxRWYqnMcjpnD27cnPDLa7z568V5zJ26sNG7WUJ/uscDAd52zxKrZwnxq3WUd/qpI+Cu92Sul+d24rB9ouyCTFeB2XxoSXK263ImF8/OYpMiPqNbbesdmEgEqair6jwtyZuaS9vF++HlV7giK0g2jbKtxCGbe/0ib/qWFtdrOYht2n1OC7Z9RHUcKH73EdcKuOlsyzuF3KVKP7NYlr+riDU69PbMDcfGf1v9KIFvJX2SrdHxacieLeDigIfm61PHAUV+H/Kp/PmNakLqpvyjsb0teu3Pq1symGUFsjPn7uNHCddUf4O5PI3ZewezgjWi30x1EVPcm6cdBg99ZcBBpb3fy3e2o3V4qNet1rWEJKEVkdpljbQ7q+KtKfe6koqv3bXVCzTt9uMiHV9uc9H7f/dxI+RQsHG7/T/mc+kC2Qw+5pcnKH62MpM2WcQ==</enc>]]>
    </text>
  </js>

  <script>

  </script>
  
  <messages> 
	 <message val="noEmpty">
      <text v="Vui lòng nhập trọng lượng hoặc tỷ khối" e="Please enter weight."/>
    </message>
  </messages>
  
</dir>