<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="s42TG2" fieldKey="id" voucherCode="TG2" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc báo giá đề nghị" e="Quick Price Search Filtering"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D">
          <text v="Ngày từ/đến" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" aliasName="@DFDTo" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D" nextRow="false">
          <text v="" e=""></text>
        </field>
		<field name="ma_noi_di" viewType="Lookup" disabled="false" label="1" field="1" operation="like">
			<text v="Nơi đi" e="Origin "></text>
			<viewInfo lookupType="One" lookupId="vdmcangdi" lookupKey="(kkh_yn = 1 or hc_yn = 1) and status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_di" />
		</field>
		<field name="ten_noi_di" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="ma_noi_den" viewType="Lookup"  disabled="false" label="1" field="1" operation="like">
			<text v="Nơi đến" e="Destination"></text>
			<viewInfo lookupType="One" lookupId="vdmcangden" lookupKey="(kkh_yn = 1 or hc_yn = 1) and status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_den"  />
		</field>
		<field name="ten_noi_den" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>  
		 <field name="so_ct" label="1" field="1" allowBlank="false" viewType="Lookup">
          <text v="Lấy số báo giá" e="Get a quote number"></text>
          <viewInfo lookupType="one" lookupId="s52" lookupRef="ds_so_bg" lookupKey="ngay_ct between ![ngay_ct1]! and ![ngay_ct2]! and ma_noi_di like ![ma_noi_di]! +'%' and ma_noi_den like ![ma_noi_den]! +'%'  and status in (1,2)" lookupCheck="ma_kh = ![ma_kh]! and status in (1,2) and ma_nt = ![ma_nt]!" />
        </field>
        <field name="ds_so_bg" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
	
	
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>H6lgBu6hcsf2ESwZXzTk9B4ZJjXJ8P/xk+4QBuRVNyFhaAyJXSkrvNKLMoBC63YY+uQW9qmQNSKoa2R+DA4tTfqjb1y+jPtQjnlBSSJw0mDlyx7R3jyuhCl0vl7w/kN8PNPhPs4fcjMZfhuEJ9BNW6RGUJnBB/gJv9QMbeam4Y+4v/CXRFxmLAxSYRSHSHDd1X2mLTJ4LyU4UVffdNHhudmyufy/yKURDARrek7W3XtlTGh4+J8DHOt7PGKeVGx2emcygESVaK+xI6Afipb2aOr3OKPSM8Q1ZKSPURF1Nb5H1lU7WoraYJx4IQJ/JDFUIwq7MMfKroUnWvMAgb5BpVzrzpf7WFw7vrKBeYHlZlJi9xAazK6DHzeSiA9gJpOirWCaSSAVO9MPr6BxHPoCo/TeN2yLeqOTTf5OI8lDlQ/QpQJPv4VVDRaN8IrcsOvu4QogyF73PIMn2giTpzBLeGLaWDNq3DEx++GLR/Yu/2IUS7jkkSFmmKpBkX84sp7iYCaiMlpYepCFDfpQuCDuw03l3KQmrKU5wKoQDFy7B8tGuflM5UCOSsMRrjWRpWKIbJC3SN0FYbIZTqZaXg8Evw==</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>