<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="s43Approve" table="" height="" fieldKey="id" voucherCode="BQ3" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc báo giá (Duyệt)" e="Quote Orders Filter (Approve)"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D">
          <text v="Ngày c/từ (từ/đến)" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" aliasName="@DFDTo" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D" nextRow="false">
          <text v="" e=""></text>
        </field>
		<field name="ma_job" clientDefault="true" viewType="Lookup" label="1" field="1" allowBlank="true"  setype="1" operation="like">
          <text v="Mã job" e="Job Code"></text>
          <viewInfo lookupType="One" lookupId="vdmjob" lookupKey="status = 1" lookupCheck="1=1" lookupRef="ten_job" lookupInfo="vdmjob|ma_job|ten_job" />
        </field>
        <field name="ten_job" clientDefault="true" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
        <field name="so_job"  label="1" field="1" operation="a.so_job &gt;= N'%s'" nextRow="true">
          <text v="Số job" e="Job Number"></text>
        </field>

		
        <field name="ma_kh" viewType="Lookup" label="1" field="1" operation="like">
          <text v="Mã khách hàng" e="Customer Code"></text>
          <viewInfo lookupType="One" lookupId="dmkh" lookupKey="kh_yn = 1 and status = 1" lookupCheck="1 = 1" lookupRef="ten_kh" />
        </field>
        <field name="ten_kh" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
		<field name="ma_hang" allowBlank="true" viewType="Lookup" label="1" field="1"  hidden="false" operation="like">
		  <text v="Hãng tàu/ Đại lý" e="Carrier/ Agent Code"></text>
		  <viewInfo lookupType="One" lookupId="dmkh" lookupKey="hk_yn = 1 and status =1" lookupCheck="1=1" lookupRef="ten_hang" lookupInfo="dmkh|ma_kh|ten_kh" />
		</field>
		<field name="ten_hang" nextRow="false" fieldType="EX" readOnly="true" inactivate="true"  hidden="true" label="" field="-" aliasName="cast('' as nvarchar(200)) as ">
		  <text v="" e=""></text>
		</field>		
        <field name="dien_giai" label="1" field="-" operation="a.dien_giai like N'%%s%'">
          <text v="Diễn giải" e="Voucher Number"></text>
        </field>
      </fields>
    </form>
    
    <form gravity="MiddleLeft" tabPageIndex="1" columns="120,120,120"  >
      <text v="Chi tiết" e="Detail"/>
      <fields>
        <field name="ma_phi" viewType="Lookup" label="1" field="1">
          <text v="Mã chi phí" e="Fee Code"></text>
          <viewInfo lookupType="One" lookupId="dmphi" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_phi" />
        </field>
        <field name="ten_phi" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
    
    <form gravity="BottomLeft" columns="120,120,120,120"  >
      <fields>
        <field name="ma_unit" viewType="Lookup" inactivate="true" label="1" field="3" >
          <text v="Đơn vị" e="Unit"></text>
          <viewInfo lookupType="Multi" lookupId="sysunit" lookupKey="status = 1 and unit_id in (select unit_id from dbo.ISWIFTFunctionGetUnitIDRight(@@userId, @@admin, ''))" lookupCheck="1 = 1" lookupRef="ten_unit" />
        </field>
        <field name="ten_unit" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" label="1" field="3" valueDefault="1" operation="=" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="Chờ duyệt (Xử lý Duyệt/Hủy đơn hàng)" e="Open (Approve)"/>
              </option>
              <option val="5">
                <text v="Đã duyệt (Xử lý bỏ duyệt)" e="Approved (Undo)"/>
              </option>
              <option val="9">
                <text v="Đóng (Xử lý bỏ đóng, duyệt đơn hàng)" e="Close (Open &amp; Approve)"/>
              </option>
            </options>
          </viewInfo>
        </field>
        <field name="user_id0" viewType="Combobox" inactivate="true" label="1" field="3" operation="a.user_id0 in (select user_id from sysuserinfo where user_ref like '@@userRef%')" >
          <text v="Lọc theo người sd" e="Filter By User"></text>
          <viewInfo>
            <options>
              <option val="">
                <text v="Tất cả" e="All"></text>
              </option>
              <option val="1">
                <text v="Lọc theo nhân viên đang quản lý" e=""></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>vw61CfkUMjBsEk48pnhRWbIEZ8VzACU3eF404jqEqr0CsaMeRbxfoVF5TnKavEH+rFiq5tQsK5eLYF4r5NHYeq1NLRAq8k/88noEURtAsGiwu4PQyZFbFlfHOhKY3XF+2b4ZKrgWQ76dvSiVdmjR9dLY7PReyGFPabka+Y9KwR1+uhjcBdsyM12yZbXJBJbiR0294GJwLDkDr/inPUJL4WNPoRmWforERPy/D+HT3U9AbQx2ENSMLluz1GiEiw+GQIefbMGnlAuRCMII+scASqc/ZGo0rRFtJLzpF0GrqdAhr7XOkFLuPR0H5TTzICz5SqyJFB0QD+WtF2GZvGPq0Q==</enc>]]>
    </text>
  </js>

  <script>
    &VoucherJSLoading;
  </script>

  <messages>
    <message val="approve">
      <text v="duyệt/hủy" e="Approve/Close"/>
    </message>
    <message val="undo">
      <text v="bỏ duyệt" e="Open "/>
    </message>
    <message val="open">
      <text v="bỏ đóng" e="Open"/>
    </message>
  </messages>
</dir>