<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="s43BQ3" fieldKey="id" voucherCode="BQ3" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc báo giá" e="Rate Filter"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
       <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" clientDefault="true" allowBlank="false" dataType="D">
          <text v="Ngày từ/đến" e="Date From/To"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" aliasName="@DFDTo" clientDefault="true" allowBlank="false" dataType="D" nextRow="false">
          <text v="" e=""></text>
        </field>
		<field name="ngay_ct" label="" field="1" allowBlank="false" inactivate="true"  hidden="true" dataType="D" nextRow="true">
          <text v="Ngày chứng từ" e="Voucher Date"></text>
        </field>
        <field name="ma_nt" hidden="true" label="1" field="1">
          <text v="Mã ngoại tệ" e="Ex Code"></text>
        </field>
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>

        <field name="ma_noi_di" viewType="Lookup" disabled="true" inactivate="true" label="1" field="1">
			<text v="Nơi đi" e="Origin "></text>
			<viewInfo lookupType="One" lookupId="vdmcangdi" lookupKey="status = 1 and hk_yn = 1" lookupCheck="1 = 1" lookupRef="ten_noi_di" />
		</field>
		<field name="ten_noi_di" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="ma_noi_den" viewType="Lookup" disabled="true" label="1" field="1" operation="like">
			<text v="Nơi đến" e="Destination"></text>
			<viewInfo lookupType="One" lookupId="vdmcangden" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_den"  />
		</field>
		<field name="ten_noi_den" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>  
		
		<field name="ma_hang" viewType="Lookup" disabled="true" inactivate="true" label="1" field="1" hidden="true">
          <text v="Mã hãng tàu" e=" Carriers"></text>
          <viewInfo lookupType="One" lookupId="dmhangtau" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_hang" />
        </field>
        <field name="ten_hang" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
		 <field name="t_tong_trong" label="1" field="1" dataType="N" disabled="true" nextRow="true" format="FCAmount" >
          <text v="Tổng trọng lượng" e="Total Weight"></text>
        </field>
		<field name="t_tong_khoi" label="1" field="1" dataType="N" disabled="true" hidden="true" nextRow="true" format="FCAmount" >
          <text v="Tổng Volume" e="Total Volume"></text>
        </field>
		<field name="cvc_yn" dataType="B" clientDefault="true" label="[60]" field="[40]" nextRow="true" hidden="true" inactivate="true">
          <text v="Cước v/c" e="Freight"></text>
        </field>
		<field name="xk_yn" dataType="B" clientDefault="true" label="[60]" field="[40]" nextRow="false"  hidden="true"  inactivate="true">
          <text v="Xuất khẩu" e="Export"></text>
        </field>
		<field name="nk_yn" dataType="B" clientDefault="true" label="[60]" field="[40]" nextRow="false"  hidden="true"  inactivate="true">
          <text v="Nhập khẩu" e="Import"></text>
        </field>
		<field name="pp_yn" dataType="B" clientDefault="true" label="[60]" field="[40]" nextRow="false"  hidden="true"  inactivate="true">
          <text v="Phụ phí" e="Surcharge"></text>
        </field>	
        <field name="so_ct" label="1" field="1" allowBlank="true" hidden="true" >
          <text v="Số báo giá" e="Quot. Number"></text>
        </field>
		
        <field name="ds_so_ct" nextRow="false" fieldType="EX" readOnly="true"   hidden="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
		<field name="id_yc" dataType="I"  readOnly="true" fieldType="PK" hidden="true" >
          <text v="Id yc" e="Request. Id"></text>
        </field>
      </fields>	    
	</form>
		
</forms>

 


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>RdZYscXGBrwdrkGziOPdq2lA5bEDb/zkr3F390zHG1UKNm/I9Qvbjz8BqeW4bA1XoMS5HhYocrLgne7KQ6IpVr627Mj5agH+KX2vUL5mAAwI/oTW0mG/JRYX6I1fyj3t/y9Zu+PO7ih2XA9K2R2qry5axow2/ZOE0KnZAmpu44j6PFv1E9sxsnTiXkBX+hJ39MAxUZ2CtBU78HJSHYNoHu7aAl5bXeAs4wa179BC5AjWH47YM21JIL8f8Iw6HyBe4afDcB1wrkWK2tRBrc2LHRxjp76KYP0O7jzwldvMcFJCt6Cmiy7GcCIPl3S3IS9huvPGObz2kQYFb1RSNLfWtnNFnTnV9FRn42cy+ZULm1/vpu15pcdhatxSRb9ns6FkvlH2cpCCej3n9Kgt4bHuYiVgKq/+PawT598SjNF4vzUcz6Zx619n5htqXnmctSXE23BtKpleKNEJ7yM6YqpUmpfvRJhNDCVy6Om2af3DKRJNU/GXUmerdc5OGnI4Dha3AM8jVt6JlaBdgujMs7NmWzAi+U9WuJ2SAK/7NRcGMoQa1qS1Aczo+09VEGWnl7ioGsmHqI7Rf7mcRKj33tSRoaceeVqUl8GaTsoNHVmtkgISIUsNk2onfNNcKLnLsRwQIcyfaPbHWMJVkRzSUMdzlVqbj55x8vc0icP5/6tDM9Lkhh82h7jFh1mYLHRr92n6jplyNqM8NKLLce3DfBpqgA2PxvK5MU/wyMEC2ApXmxypfILiRnlz+TiX5SaiOcrVl57Jjo7MEcFmBI/9SDtDCVFfdfWg8+EygVdy3uXbHSAEoqVp9MaPznCSGiisWO56JrBPwpNN705FHnpOlPunvQ==</enc>]]>
    </text>
  </js>

 <script>
		
    
  </script>
  <messages> 
	 <message val="noEmpty">
      <text v="Vui lòng nhập trọng lượng." e="Please enter weight."/>
    </message>
  </messages>
</dir>