<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="s43Close" table="" height="" fieldKey="id" voucherCode="BQ3" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc báo giá (Đóng báo giá)" e="Filter Order (Close)"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D">
          <text v="Ngày c/từ (từ/đến)" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" aliasName="@DFDTo" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D" nextRow="false">
          <text v="" e=""></text>
        </field>
        <field name="so_ct1"  label="1" field="1" operation="a.so_ct &gt;= N'%s'">
          <text v="Số c/từ (từ/đến)" e="Voucher Number"></text>
        </field>
        <field name="so_ct2"  label="" nextRow="false" field="1" operation="a.so_ct &lt;= N'%s'">
          <text v="" e=""></text>
        </field>

        <field name="ma_kh" viewType="Lookup" label="1" field="1" operation="like">
          <text v="Mã khách hàng" e="Customer"></text>
          <viewInfo lookupType="One" lookupId="dmkh" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_kh" />
        </field>
        <field name="ten_kh" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
		<field name="ma_hang" allowBlank="true" viewType="Lookup" label="1" field="1"  hidden="false" operation="like">
		  <text v="Hãng tàu/ Đại lý" e="Carrier/ Agent Code"></text>
		  <viewInfo lookupType="One" lookupId="dmkh" lookupKey="ncc_yn = 1 or dl_yn = 1 and status =1" lookupCheck="1=1" lookupRef="ten_hang" lookupInfo="dmkh|ma_kh|ten_kh" />
		</field>
		<field name="ten_hang" nextRow="false" fieldType="EX" readOnly="true" inactivate="true"  hidden="true" label="" field="-" aliasName="cast('' as nvarchar(200)) as ">
		  <text v="" e=""></text>
		</field>
        <field name="dien_giai" label="1" field="-" operation="a.dien_giai like N'%%s%'">
          <text v="Diễn giải" e="Voucher Number"></text>
        </field>
      </fields>
    </form>

    <form gravity="MiddleLeft" tabPageIndex="1" columns="120,120,120"  >
      <text v="Chi tiết" e="Detail"/>
      <fields>
        <field name="ma_phi" viewType="Lookup" label="1" field="1">
          <text v="Mã chi phí" e="Fee"></text>
          <viewInfo lookupType="One" lookupId="dmphi" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_phi" />
        </field>
        <field name="ten_phi" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
        <field name="ma_kho" viewType="Lookup" label="1" field="1">
          <text v="Mã kho" e="Site"></text>
          <viewInfo lookupType="One" lookupId="dmkho" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_kho" />
        </field>
        <field name="ten_kho" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
        <field name="ma_lo" viewType="Lookup" hidden="true" label="1" field="1">
          <text v="Mã lô" e="Lot"></text>
          <viewInfo lookupType="One" lookupId="dmlo2" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_lo" />
        </field>
        <field name="ten_lo" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
        <field name="ma_vi_tri" viewType="Lookup" hidden="true" label="1" field="1">
          <text v="Mã vị trí" e="Position"></text>
          <viewInfo lookupType="One" lookupId="dmvitri" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_vi_tri" />
        </field>
        <field name="ten_vi_tri" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>

    <form gravity="BottomLeft" columns="120,120,120,120"  >
      <fields>
        <field name="ma_unit" viewType="Lookup" inactivate="true" label="1" field="3" >
          <text v="Đơn vị" e="Unit"></text>
          <viewInfo lookupType="Multi" lookupId="sysunit" lookupKey="status = 1 and unit_id in (select unit_id from dbo.ISWIFTFunctionGetUnitIDRight(@@userId, @@admin, ''))" lookupCheck="1 = 1" lookupRef="ten_unit" />
        </field>
        <field name="ten_unit" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" label="1" field="3" valueDefault="-1">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="-1">
                <text v="Chưa đóng" e="Chưa đóng"/>
              </option>
              <option val="9">
                <text v="Đã đóng" e="Đã đóng"/>
              </option>
            </options>
          </viewInfo>
        </field>
        <field name="user_id0" viewType="Combobox" inactivate="true" label="1" field="3" operation="a.user_id0 in (select user_id from sysuserinfo where user_ref like '@@userRef%')" >
          <text v="Lọc theo người sd" e="Filter By User"></text>
          <viewInfo>
            <options>
              <option val="">
                <text v="Tất cả" e="All"></text>
              </option>
              <option val="1">
                <text v="Lọc theo nhân viên đang quản lý" e=""></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>3ibmR959SqcTRrzGPiRvgFTHuiI/06ri3I/pQnbqtc/SCzeZEpnmMOx9kbZPqO+ln8TffwreDSiA5BmZETBAIZyv1w7lxwKrEYU+JHharTf1BzwiZxLK6ccEDIcO/5ne8I8XwKFOEvJEOnUL3DP2c6MMQDUOYn9sQ+Lb6cHMZxmwoZn4oUaHug/zahQc9uWubCPVIJp+8dlOWTDxLDAauzldaCDu/11AFSOgo6eD/OcePNduWjIHRGjUWjOkO9wWCW6Y3QNi8GO1Ci/b5GLOIkIABevLghTNZVY8KZSVKpcA5kxl8ydOIfUw+y+pyrvO</enc>]]>
    </text>
  </js>

  <script>

  </script>
  
  <messages>
    <message val="close">
      <text v="đóng" e="đóng"/>
    </message>
    <message val="unclose">
      <text v="bỏ đóng" e="Cancel Close"/>
    </message>
  </messages>
</dir>