<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
  <!ENTITY VoucherExtendFields SYSTEM "..\Include\XML\VoucherExtendFields.xml">
]>

<dir id="s43TG3Select" table="" height="" fieldKey="id" voucherCode="TG3" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Chi tiết báo giá được chọn" e="Quotation Entry Detail"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" readOnly="true" aliasName="@DFDFrom" disabled="true" allowBlank="false" dataType="D">
          <text v="Ngày c/từ từ/đến" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" allowBlank="false" disabled="true" inactivate="true" dataType="D" nextRow="false">
          <text v="Ngày đến" e="Voucher Date"></text>
        </field>
        <field name="ma_nt" hidden="true" label="1" field="1">
          <text v="Mã ngoại tệ" e="Ex Code"></text>
        </field>
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>
		<field name="ma_kh" format="U" label="1" disabled="true"  field="1"  >
          <text v="Mã khách hàng" e="Code"></text>
        </field>
		<field name="ma_so_thue" label="1" field="-" disabled="true"  importable="35" nextRow="false" allowBlank="true">
          <text v="Mã số thuế " e="Tax Code"></text>
        </field>
		<field name="ten_kh" allowBlank="true" label="1" disabled="true"  field="-" importWidth="250" importable="10">
          <text v="Tên khách hàng" e="Name"></text>
        </field>
        <field name="ma_noi_di" viewType="Lookup" label="1" disabled="true" field="1" operation="like">
			<text v="Nơi đi" e="Origin "></text>
			<viewInfo lookupType="One" lookupId="vdmcangdi" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_di" />
		</field>
		<field name="ten_noi_di" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>
		
		<field name="ma_noi_den" viewType="Lookup" disabled="true" label="1" field="1" operation="like">
			<text v="Nơi đến" e="Destination"></text>
			<viewInfo lookupType="One" lookupId="vdmcangden" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_den"  />
		</field>
		<field name="ten_noi_den" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>  
		<field name="so_ct" label="1" field="2" disabled="true">
          <text v="Số báo giá" e="Quot. Number"></text>
        </field>

        <field name="xprocess" label="1" field="2" valueDefault="2" viewType="Combobox">
          <text v="Xử lý" e="Process"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="Thêm vào chi tiết" e="Append To Detail"></text>
              </option>
              <option val="2">
                <text v="Xóa hết chi tiết và thêm mới" e="Delete All Detail And Append New"></text>
              </option>
            </options>
          </viewInfo>
        </field>
		<field name="id" dataType="N" hidden="true" fieldType="PK" label="1" field="1"  >
			<text v="ID" e="Code"></text>
		</field>
        
      </fields>
    </form>
    <form tabPageIndex="1" gravity="MiddleLeft" height="350" columns="120,120,240" >
      <text v="Chi tiết" e="Detail"></text>
      <fields>
        <field name="v53" label="" field="-" viewType="Grid">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
  </forms>

 <grids>
    <grid id="v53" table="v53" fieldKey="id, line" order="id, line" allowFilter="true" readOnly="false" allowOrder="true">
      <fields>
        <field name="id" foreignField="id" dataType="N" fieldType="PK" format="0" copy="false" hidden="true">
          <text v="" e=""></text>
        </field>
        <field name="line" foreignField="@@ROW" dataType="I" fieldType="PK" hidden="true">
          <text v="Dòng" e="Line"></text>
        </field>
        <field name="ma_phi" width="100" allowBlank="false" viewType="Lookup" readOnly="false" >
          <text v="Mã phí" e="Fee"></text>
          <viewInfo lookupType="One" lookupId="dmphi" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_phi" lookupInfo="dmphi|ma_phi|ten_phi" />
        </field>
        <field name="ten_phi" width="250" fieldType="EX" inactivate="true" readOnly="true" aliasName="b" join=" left join dmphi b on a.ma_phi = b.ma_phi ">
          <text v="Tên phí" e="Fee Name"></text>
        </field>
		<field name="ma_cong" width="100" allowBlank="false" viewType="Lookup" readOnly="false" hidden="true" >
          <text v="Container" e="Container"></text>
          <viewInfo lookupType="One" lookupId="dmcong" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_cong" lookupInfo="dmcong|ma_cong|ten_cong" />
        </field>
        <field name="ten_cong" width="0" fieldType="EX" inactivate="true" readOnly="true" hidden="true" aliasName="c" join=" left join dmcong c on a.ma_cong = c.ma_cong ">
          <text v="Container" e="Container Name"></text>
        </field>
         <field name="ma_dk_phi" viewType="Combobox" width="120" readOnly="false">
			<text v="Loại phí" e="Fee type"></text>
			<viewInfo>
				<options query="select ma_bgn, ten_bgn%l from dmbgn where ma_ct = 'LPH' and status = 1 order by stt">
				</options>
			</viewInfo>
		</field>
		<field name="ma_dvt" width="80" allowBlank="false" viewType="Lookup" readOnly="false" >
          <text v="Đơn vị" e="Fee"></text>
          <viewInfo lookupType="One" lookupId="dmdvt" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_dvt" lookupInfo="dmdvt|dvt|ten_dvt" />
        </field>
        <field name="ten_dvt" width="0" fieldType="EX" inactivate="true" readOnly="true" aliasName="x" join=" left join dmdvt x on a.ma_dvt = x.dvt ">
          <text v="Tên đơn vị" e="Fee Name"></text>
        </field>
        <field name="so_luong" dataType="N" format="Qty" allowBlank="false" valueDefault="1" width="80" readOnly="false" >
          <text v="Số lượng" e="Quantity"></text>
        </field>

       <field name="gia_nt1" dataType="N" inactivate="true" hidden="false" format="FCPrice" width="100" readOnly="true" >
          <text v="Giá mua " e=" Cost Price"></text>
        </field>
        <field name="gia_nt2" dataType="N" format="FCPrice" width="100" readOnly="false" >
          <text v="Giá bán" e="Bill Price"></text>
        </field>
		 <field name="tien_nt1" dataType="N" format="FCAmount" width="100" readOnly="false" >
          <text v="Tiền mua" e="Cost Amount"></text>
        </field>
        <field name="tien_nt2" dataType="N" format="FCAmount" width="100" readOnly="false" >
          <text v="Tiền bán" e="Bill Amount"></text>
        </field>
        <field name="tl_ck" dataType="N" format="Rate" width="100" hidden="true" readOnly="false" >
          <text v="Tl ck(%)" e="Dis.Rate"></text>
        </field>
        <field name="ck_nt" dataType="N" format="FCAmount" width="100" hidden="true" readOnly="false" clientDefault="true" >
          <text v="Ch.khấu " e=" Discount"></text>
        </field>
		 <field name="ma_nt" width="60" allowBlank="true" viewType="Lookup" readOnly="false" >
          <text v="Mã ngoại tệ" e="Currency"></text>
          <viewInfo lookupType="One" lookupId="dmnt" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_nt" lookupInfo="dmnt|ma_nt|ten_nt" />
        </field>
		 <field name="ten_nt" width="0" fieldType="EX" inactivate="true" readOnly="true" aliasName="d" join=" left join dmnt d on a.ma_nt = d.ma_nt ">
          <text v="Tên phí" e="Fee Name"></text>
        </field>
		 <field name="ty_gia" dataType="N" format="Price" width="100" hidden="false" readOnly="false" >
          <text v="Tỷ giá" e="Curr.Rate"></text>
        </field>
        <field name="thue_suat" dataType="N" format="0" width="60" readOnly="false" hidden="false" clientDefault="true" >
          <text v="VAT(%)" e="Tax"></text>
        </field>
        <field name="thue_nt" dataType="N" format="FCAmount" width="100" hidden="true" readOnly="false">
          <text v="Thuế %s" e="%s Tax"></text>
        </field>
        <field name="gia1" dataType="N" format="Price" width="100" hidden="true" inactivate="true" readOnly="true" >
          <text v="Giá chuẩn" e="Std.Price"></text>
        </field>
        <field name="gia2" dataType="N" format="Price" width="0" inactivate="true" readOnly="false" >
          <text v="Giá bán" e="Price"></text>
        </field>
		 <field name="tien1" dataType="N" format="Amount" width="100" inactivate="false" readOnly="false" >
          <text v="Chi phí" e="Total Cost"></text>
        </field>
        <field name="tien2" dataType="N" format="Amount" width="100" inactivate="false" readOnly="false" >
          <text v="Doanh thu" e="Total Bill"></text>
        </field>
		<field name="tt" dataType="N" format="Amount" width="100" hidden="false" valueDefault="0" inactivate="false" readOnly="true" >
          <text v="Tổng cộng" e="Total"></text>
        </field>
		<field name="tien_ln" dataType="N" format="Amount" width="100" inactivate="false" readOnly="false" >
          <text v="Lợi nhuận" e="Profit"></text>
        </field>
        <field name="ck" dataType="N" format="Amount" width="100" inactivate="true" hidden="true" readOnly="false">
          <text v="Chiết khấu" e="Discount"></text>
        </field>
        <field name="thue" dataType="N" format="Amount" width="100" inactivate="true" hidden="true" readOnly="false">
          <text v="Thuế" e="Tax"></text>
        </field>
		<field name="dien_giai" width="200" inactivate="true" readOnly="false">
          <text v="Diễn giải" e="Explain"></text>
        </field>
        <field name="id_tg" dataType="N" fieldType="PK" format="0" hidden="true" aliasName="a.id as ">
          <text v="ID BG" e="ID BG"></text>
        </field>
        <field name="so_tg" dataType="N" fieldType="PK" format="0" hidden="true" aliasName="a.so_ct as ">
          <text v="Số báo giá" e="Quot. .No"></text>
        </field>
        <field name="line_tg" dataType="I" fieldType="PK" hidden="true" aliasName="a.line as ">
          <text v="Dòng BG" e="Quot. Line"></text>
        </field>
      </fields>

      <buttons>
        <button id="freeze">
          <text v="$FreezeToolbar" e="$FreezeToolbar"></text>
        </button>
      </buttons>

      <script>
        <query>
          <text>
            <![CDATA[<enc>TofPCwT6Jn8ioFhQSvOlOCU64JWwzngd51FQEgX4tvM9U78+AalBmHXEyxqpz2JHjCNQwLEqUOXaly66CYbb+nLzHxTBSlFTBQ3FEOX8v7+01Ed9WJpqiAW90IbrqPerYqE/hF8fFapytusfVXn+roo6xHHHZScZrYMo+8NFtPOflV+CuvcjnOdTGcEewjy+fPmy9n8VulU2TIpRn89NaZ5h7oRPCXVKGOvSgRrxaLoyk1hxK+TKNr4rZ0mKXKN9mr2F87qgkMwyl5vVfei6n2sMAcEBYKyv4x4h9SR7tW9vkI9wxmN9IbQil/DUbzXzelUScjPkuQvfhs+HsuuPwfiB8v8jaZNAup/qvGjOVvT0DIzLqTbj5+ZZA6QdPIT5RB695uY8o/RljQRPBFsL52Z+Lp/iRy1tFQtvj2DA39WroWV+REQxLYDukkBRtUFFA55vfgu3SZ7RkGxMjkLPLxtyZrGPeVFPI/7ZF5VafYURdD0EP8FWDtqu2WbeKTpGfmTNkRB5yUK+VUZmrKZGYE8cH8qbV3ym4c3EMJP6l8MDQTHYyNfLYwbV6JcM6Ur4TmxXLwAFJ7VjYkl46EHco75zKIomaLoXYugkxlKMf8Zk40c6wzNJ8r2C2C5bCTIeQqcT3YJxWAp6voSD3WMduYSNV1bsX/6VEa/0gelO4YNxbJy6+K4tZwFwIMKM5fX6</enc>]]>
          </text>
        </query>
      </script>

    </grid>
   
  </grids>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>RHvQFF3mi+iQ+U21Y8fNc+SETxaC7ksvmyCY2DxOoR4WZ7RyFTOLU4LC/DDd+L+KJUdTp0FgSpKfT7cVOkfDcBtuKpgrATH7TDkLN7f60dideDLeh/NC48gErz1XRPuq25BJ/fwfP9OsZBbQrFdhQCZEawlNG0JqdjtRoKOC+mmYdymqSJaRtryvwYlh3aP6sksT3X8ksftA+7oTNQ/luSXxeeuY7ouvL5Vv1NydocWyJ03wt1L/Za9OzO5LlxmqQTX9n81+jjGDchNgKwLMoqCx83zF1GnsppypEBhzHgigXqDWVz+nzZoxMtTsVUKPSqjePwRN6cd8eWY5by87rJhpam6RzkebvvAdzdSkPbmUf8aUItVD/37BzfMaOct7w0FZxh6HDwhVjbNdk2VdqBmFb/GmJ8gnaWkbpxo5zfwYFH7WkVD9CfKxT/qcmi6DZQvCllMyYlyWJjWypYAxQyJViYu/kI6r7P67KWoz3Zz30VghRVhHEVytmMK/E8QMyFunfoa2FuInC1w5/GrGhq1cXXF2EIYxbbKc6XjSNph5yLJGUOrxZOXsZStpDwireuBFoJd3b2uU2GDGoHg7hw1ZovJjXH6VCsZMnQDRvWaBLHz+v9Z7me44CBFxZMpNdRaCCD66h8ElVRHmsR/XAGacBQpFor+kanUN2kmj85+j8QM/6ArZERfI7sNtmJDDxzfh6r99icM9OgvC7OhfyqtiNsj8RFG+A2UKv9s49pO7PqNJo+0d+us2Gf6PDyHeCuMPzwW7ouJb+gF/zXOK/g==</enc>]]>
    </text>
  </js>
  
  <script>
		<request code="ma_kh_request">
			<text>
			  <![CDATA[<enc>X7TZHohr7BAxO28qzYStcP805HGnbKOeAH0BvJeB85J/h7c5Mwh6vZ7Jwnbhr8VmSu6m8mW+SuxjFDkayl8Krg+Lrvzrc4IbJc65fIhvByrLcuEfX4txzd0ZCOmXv3IxvPS6LUJ+z3LITb8vgYQ6X0K3zXOr9xFPaLeyStnGnXShqCE5t93oiy5sNKVtfjgS/UEEBrhF31A+MDw6U7z5gbwacjo07gz383KmjdKJJD3+9XLrL8nj/7nHwpINGzwf8ucqH1gCW89DANUJ330rKwGm4htQGh7e4oL0+EMVYX7TJC5+HVLp0jb+XOOAHiMizHYaVu0po3tpx2YWck4SOfJ2mSekvOGuP//EZhdI5Ac=</enc>]]>
			</text>
		</request>
  </script>
</dir>