<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="s43YG3" fieldKey="id" voucherCode="YG3" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc báo giá" e="Quotation Entry Filter"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" allowBlank="false" dataType="D">
          <text v="Ngày c/từ từ/đến" e="From Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" allowBlank="false" inactivate="true" dataType="D" nextRow="false">
          <text v="Ngày đến" e="To Date"></text>
        </field>
       
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>
		
        <field name="ma_noi_di" viewType="Lookup" disabled="false" label="1" field="1">
			<text v="Nơi đi" e="Origin "></text>
			<viewInfo lookupType="One" lookupId="vdmcangdi" lookupKey="status = 1 and hk_yn = 1" lookupCheck="1 = 1" lookupRef="ten_noi_di" />
		</field>
		<field name="ten_noi_di" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="ma_noi_den" viewType="Lookup" label="1" field="1" operation="like">
			<text v="Nơi đến" e="Destination"></text>
			<viewInfo lookupType="One" lookupId="vdmcangden" lookupKey="status = 1 and hk_yn = 1" lookupCheck="1 = 1" lookupRef="ten_noi_den"  />
		</field>
		<field name="ten_noi_den" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>  
			
		 <field name="so_ct" label="1" field="1" allowBlank="false" viewType="Lookup">
          <text v="Lấy yêu cầu báo giá" e="Get a quote request number"></text>
          <viewInfo lookupType="one" lookupId="s13" lookupRef="ds_so_ct" lookupKey="ngay_ct between ![ngay_ct1]! and ![ngay_ct2]! and ma_noi_di like ![ma_noi_di]! +'%' and ma_noi_den like ![ma_noi_den]! +'%' and status = 1" lookupCheck="ma_kh = ![ma_kh]! and status in (1) and ma_ngv = 4 and ma_nt = ![ma_nt]!" />
        </field>
        <field name="ds_so_ct" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
	
	
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>xDqHA65tWdmKzA7Vta3yK5yJOtieQy/3BpasfpAU3Q786ABhluRO77ud/+u9AWJSkozkvCF25dm/0Usz/TsX9W3do+tkr+bmC5PrPnQ/Yoea2MjB8O9tAIGa3qmLoS2eKTcEQ9EpW3Uf97gLUjV50SD081We8MKm3j3bsGr19WV4gEjjRrfDR/r5yecACfFj5dNhuxBWtL3Qn8gaB8MOIBsAC02xiii6jtY4ZtA1VIKkK+cHVFlcjHDCNTudB5cewbKHrQcjk5vF0N+C3zoj5uiHE4lNaSxKZGYvNGNN9jPnrtyzaEzuyXn5YXSVmNA+iR8sWl1lw33zbH1J1HqlJI1dmDHa6shOqg+74f59znD7/hbFdaDIVv8riiKtU/RUV19Z8UlplzVIDt489i1tczrFZxrQuU8lJalO17Ahq5dHyACQVtGGCrJj2ej1B8v7iZpeMfKW7yROGAv/J7TVKa4u/tL2iLTIY7BqBF/SvH0RnNu66PvGlKFwqKtKTWRkVgVqaluHORfpBaniJ0oYZ4ZMOz1H4ZTc4ekcBcB+lUN5j8OvsrNInKOs6TZtZarvSY5u/FibmQUm9t9fvCENu6hdosKpsV55/CrTjcXA3mfq8dSxf6ovrRTGBTyRLCi6</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>