<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="s52BN2" fieldKey="id" voucherCode="TG2" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc phiếu giá cost" e="Filter Cost Voucher"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" allowBlank="false" dataType="D">
          <text v="Ngày c/từ từ/đến" e="Date From"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" allowBlank="false" inactivate="true" dataType="D" nextRow="false">
          <text v="Ngày đến" e="Date To"></text>
        </field>
		<field name="ngay_ct" label="" field="1" allowBlank="false" inactivate="true"  hidden="true" dataType="D" nextRow="true">
          <text v="Ngày chứng từ" e="Voucher Date"></text>
        </field>
        <field name="ma_nt" hidden="true" label="1" field="1">
          <text v="Mã ngoại tệ" e="Ex Code"></text>
        </field>
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="ma_noi_di" viewType="Lookup" disabled="true" inactivate="true" label="1" field="1">
			<text v="Nơi đi" e="Origin "></text>
			<viewInfo lookupType="One" lookupId="vdmcangdi" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_di" />
		</field>
		<field name="ten_noi_di" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="ma_noi_den" viewType="Lookup" disabled="true" label="1" field="1" operation="like">
			<text v="Nơi đến" e="Destination"></text>
			<viewInfo lookupType="One" lookupId="vdmcangden" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_den"  />
		</field>
		<field name="ten_noi_den" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>  
		<field name="ma_hang" viewType="Lookup" disabled="true" inactivate="true" label="1" field="1" hidden="true">
          <text v="Mã hãng tàu" e=" Carriers"></text>
          <viewInfo lookupType="One" lookupId="dmhangtau" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_hang" />
        </field>
        <field name="ten_hang" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
		 <field name="t_tong_trong" label="1" field="1" dataType="N" disabled="true" nextRow="true" format="FCAmount" >
          <text v="Tổng trọng lượng" e="Total Weight"></text>
        </field>
		<field name="t_tong_khoi" label="1" field="1" dataType="N" disabled="true" nextRow="true" format="FCAmount" >
          <text v="Tổng Volume" e="Total Volume"></text>
        </field>
		<field name="cvc_yn" dataType="B" clientDefault="true" label="[60]" field="[40]" nextRow="true" hidden="true" inactivate="true">
          <text v="Cước v/c" e="Freight"></text>
        </field>
		<field name="xk_yn" dataType="B" clientDefault="true" label="[60]" field="[40]" nextRow="false"  hidden="true"  inactivate="true">
          <text v="Xuất khẩu" e="Export"></text>
        </field>
		<field name="nk_yn" dataType="B" clientDefault="true" label="[60]" field="[40]" nextRow="false"  hidden="true"  inactivate="true">
          <text v="Nhập khẩu" e="Import"></text>
        </field>
		<field name="pp_yn" dataType="B" clientDefault="true" label="[60]" field="[40]" nextRow="false"  hidden="true"  inactivate="true">
          <text v="Phụ phí" e="Surcharge"></text>
        </field>
			
        <field name="so_ct" label="1" field="1" allowBlank="true" hidden="true" >
          <text v="Số báo giá" e="Quot. Number"></text>
        </field>
		
        <field name="ds_so_ct" nextRow="false" fieldType="EX" readOnly="true"   hidden="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
	
	
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>+PcfrYPqvL69bPSKXvGkLf7nLFGC7kgCun5BsI//YalbqTnxDUBvDxqhkCW3njcNpvF1XowvrA1X2evDxY2Kcqmo3zv9gWX4zPBed5yPbl5svt0b2RVg/NDtoBdgiT44q2tuoJem+mOwsHEGxe4QNdeUUbw6yg7g/mwgRAIwZx2b1hY4eEDRf7/LtjqH66CH/qzDG6Qb7Uaz7QFp51mQSYSDrhMcsChuwVj3kcr0VBmMOw3qrwi1PgjdsObG4PPm9oLhzdgZA2e4ulxrlHQlCyEP1E8SZ1LbcIlyZCZbyo6/KZ6xtahjrkfO7jer27AxbPQ+jUxpYS8IcJmoofez6EPrXYNoXVUCfBwFo6rSurIyVyBXo4MnNqz2cQ1hmVfBUy3kr6IA4m7+awScTg2uTplb6cHfxwGJLH+Adk/jSUFyZel3wcfVtrBFzXDFh/fNZ1zvf32LrD4ZDsenl22yB9Tf/Xj5avZorzpcc16kCrqEx1Ez6mF2azx2gJLU88l2y1q8TfRWz+V6Nf507v+QcTsjdW7xoHmXf9NLhD++qwzXpXtq7bmVeUhfWuqTRHxTZc8m6ndQnXx4x0amtCLgpo63xKQ8/Ejg7mn4fBiSAAwaM4XtdTrMHfzl6o4Bz2g8zK5IeIzTAoHKwX2lkvERkU/bEt0E7Ulf6+Y+yq6Kn/5FChTomLDuIkMFbG2YSjZKpJ+rUrs+SXxC9Jbloi99/kHIPEpAme57QEvrrrIv005orJYZkbJvTokG3nJVJV8P</enc>]]>
    </text>
  </js>

  <script>
  </script>
  <messages> 
	 <message val="noEmpty">
	  <text v="Vui lòng nhập trọng lượng hoặc tỷ khối" e="Please enter weight."/>
	</message>
  </messages>
</dir>