<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="s53BN3" fieldKey="id" voucherCode="TG3" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc phiếu giá cost" e="Filter Cost Voucher"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" allowBlank="false" dataType="D">
          <text v="Ngày c/từ từ/đến" e="Date From"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" allowBlank="false" inactivate="true" dataType="D" nextRow="false">
          <text v="Ngày đến" e="Date To"></text>
        </field>
		<field name="ngay_ct" label="" field="1" allowBlank="false" inactivate="true"  hidden="true" dataType="D" nextRow="true">
          <text v="Ngày chứng từ" e="Voucher Date"></text>
        </field>
        <field name="ma_nt" hidden="true" label="1" field="1">
          <text v="Mã ngoại tệ" e="Ex Code"></text>
        </field>
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="ma_noi_di" viewType="Lookup" disabled="true" inactivate="true" label="1" field="1">
			<text v="Nơi đi" e="Origin "></text>
			<viewInfo lookupType="One" lookupId="vdmcangdi" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_di" />
		</field>
		<field name="ten_noi_di" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="ma_noi_den" viewType="Lookup" disabled="true" label="1" field="1" operation="like">
			<text v="Nơi đến" e="Destination"></text>
			<viewInfo lookupType="One" lookupId="vdmcangden" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_den"  />
		</field>
		<field name="ten_noi_den" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>  
		
		<field name="ma_hang" viewType="Lookup" disabled="true" inactivate="true" label="1" field="1" hidden="true">
          <text v="Mã hãng tàu" e=" Carriers"></text>
          <viewInfo lookupType="One" lookupId="dmhangtau" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_hang" />
        </field>
        <field name="ten_hang" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
		 <field name="t_tong_trong" label="1" field="1" dataType="N" disabled="false" nextRow="true" format="FCAmount" >
          <text v="Tổng trọng lượng" e="Total Weight"></text>
        </field>
		<field name="t_tong_khoi" label="1" field="1" dataType="N" disabled="true" hidden="true" nextRow="true" format="FCAmount" >
          <text v="Tổng Volume" e="Total Volume"></text>
        </field>
		<field name="cvc_yn" dataType="B" clientDefault="true" label="[60]" field="[40]" nextRow="true" hidden="true" inactivate="true">
          <text v="Cước v/c" e="Freight"></text>
        </field>
		<field name="xk_yn" dataType="B" clientDefault="true" label="[60]" field="[40]" nextRow="false"  hidden="true"  inactivate="true">
          <text v="Xuất khẩu" e="Export"></text>
        </field>
		<field name="nk_yn" dataType="B" clientDefault="true" label="[60]" field="[40]" nextRow="false"  hidden="true"  inactivate="true">
          <text v="Nhập khẩu" e="Import"></text>
        </field>
		<field name="pp_yn" dataType="B" clientDefault="true" label="[60]" field="[40]" nextRow="false"  hidden="true"  inactivate="true">
          <text v="Phụ phí" e="Surcharge"></text>
        </field>
        <field name="so_ct" label="1" field="1" allowBlank="true" hidden="false" >
          <text v="Số báo giá" e="Quot. Number"></text>
        </field>
		
        <field name="ds_so_ct" nextRow="false" fieldType="EX" readOnly="true"   hidden="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
		<field name="id_yc" dataType="I"  readOnly="true" fieldType="PK" hidden="true" >
          <text v="Id yc" e="Request. Id"></text>
        </field>
      </fields>	    
	</form>
		
</forms>

 


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>dWHD70USeRK8AVdG494z0eqkial+8NRWSnnf26//T2egu2QVpsLAmjwXbVXjRWKKmW0uFq6e2sIOXgnknkXN+6yp/7YfoGtcX5QCzQDznZ8lPBaU4O85W5luIuTSKykWF2KnxZWy7clbxkn8TZZJU9Hei1ETXS3fAfmR0Xm5O5zP7oV3uKmlmjUJy1AchAwh7Y3Mm8/DffnGqN3n+kQ7O3UTRttkMUbyNJ86revziUHTEkicWzA688vgIFD0oFuD8oX6yZUBzIxaEC30QDBFe02ptbvxdyrDojIwM0yBjcF3dtGHzwgqv+8udHKu7kLVkB2v+UM/T20TnZg/MYLZ9Yu7mDRlztAfCj6hHhItY/PPqex/+Y3q4q7ByUZLllx47QyCP6pz6kfNZvMGyuAs0xlqCnBSBYtN472MDXMIViezwGLV9Ujlh08w91V2YJcyaTd9Yx7mb6tI5Ie0jJRAYM4bTBR00KxPqpVR43nFG3UfLzommtm+jd9jOg/UKrToCoNHwSjoK8Ew1cMT4bMMrvP6j5NoRtQXrXDD1IN87AcVIubaVEwuJYC+ugHMjakKJozY5MksROCV7r/NyJ4JbV+8JG6TOYSm/+MM3yIxTLHngCC+lFfQNlCaV6jAry4kr1ib727zsh3GjV3+dkaENJUDjoq9aHRf8Zn/R18aCrDnTqBqSxKktGWmMD2LpjM05Si7S8Nwp6GV8k63fGlAE0tczhUYDE1YibQpt7GvqPO8bs9KKIYzxORGHNXrFn+PcxzFKEoRGeYsShmoCuRRBcpAsiVP4ni4zHG8ZVMzFXE=</enc>]]>
    </text>
  </js>

 <script>
		
    
  </script>
  <messages> 
	 <message val="noEmpty">
      <text v="Vui lòng nhập trọng lượng." e="Please enter weight."/>
    </message>
  </messages>
</dir>