<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="s611BQ1" fieldKey="id" voucherCode="BQ1" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc báo giá vận chuyển FCL" e="Filter shipping quotes FCL"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D">
          <text v="Ngày từ/đến" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" aliasName="@DFDTo" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D" nextRow="false">
          <text v="" e=""></text>
        </field>
		<field name="ma_noi_di" viewType="Lookup" disabled="false" label="1" field="1" operation="like">
			<text v="Nơi đi" e="Origin "></text>
			<viewInfo lookupType="One" lookupId="vdmcangdi" lookupKey="(kkh_yn = 1 or hc_yn = 1) and status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_di" />
		</field>
		<field name="ten_noi_di" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="ma_noi_den" viewType="Lookup" disabled="false" label="1" field="1" operation="like">
			<text v="Nơi đến" e="Destination"></text>
			<viewInfo lookupType="One" lookupId="vdmcangden" lookupKey="(kkh_yn = 1 or hc_yn = 1) and status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_den"  />
		</field>
		<field name="ten_noi_den" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>  
		 <field name="so_ct" label="1" field="1" allowBlank="false" viewType="Lookup">
          <text v="Lấy số báo giá" e="Get a quote number"></text>
          <viewInfo lookupType="one" lookupId="s41" lookupRef="ds_so_bg" lookupKey="ngay_ct between ![ngay_ct1]! and ![ngay_ct2]! and ma_noi_di like ![ma_noi_di]! +'%' and ma_noi_den like ![ma_noi_den]! +'%'  and status in (5,6)" lookupCheck="ma_kh = ![ma_kh]! and status in (5,6) and ma_nt = ![ma_nt]!" />
        </field>
        <field name="ds_so_bg" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
	
	
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>7dnUqIuxukLuRCTGhnr/WcmCCvSyIHedtlixH5QWfQHAcRtqgLm/69mTL7vI0nr+p0HGPFQzJd3JCpLQnkdRmpR8+BRxzy4fGFxsMdFodNW+bZ1110P3agvY1extzhjwmbRpEzhubFnYRJjbwwz8EF7hd7TYX81KpWX9q7NexeCSOTnxp4zRA3m0eOYOa0J67VzavwWgCQ82ticzFtiKX4roJAQJYdl9UW+l2DtJbQffmIEgB+YDheSgPn7L9BQAUA0N1SyrEoG6MC3bxv6zHvpiBA9z7vi6XapqWw/y88D++Z8ieBOOWiKbsFnNeozzX7KdVQIQ7PecQUHgizgl++nCGT+irHPTZCGZ86UnwEwtpTJpytzT+jAfehWfDbSrq78iAJzjWn8Y4emQXb0dKZy7AZymCJo8VGbGHHpmu9Gb8TBwv8VzYGGm4HA4V2Sgl9hl+/TtG3fdL7HGPgexkrbaaPOAHnBCUFoUbLzb99s4lwHLIBuK/D5EfscjNSMp0o2DPp4kXWudtT8pUemAdarF+mSDOb5YuPi/CaYaFS6K6Ky9amcAZp+xMi5GT/62c4LnWPp5qpd70HfP+L4w6Q==</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>