<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="s611TG1" fieldKey="id" voucherCode="CR1" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc tìm báo giá nhanh" e="Quick Price Search Filtering"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D">
          <text v="Ngày từ/đến" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" aliasName="@DFDTo" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D" nextRow="false">
          <text v="" e=""></text>
        </field>
	    <field name="ma_gd" viewType="Combobox" valueDefault=""  hidden="false" label="1" field="1" disabled="false" >
          <text v="Giao dịch" e="Transaction Code"></text>
          <viewInfo>
            <options query="select ma_gd, ten_gd%l from dmgd where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
		<field name="ma_noi_di" viewType="Lookup" disabled="false" label="1" field="1" operation="like">
			<text v="Nơi đi" e="Origin "></text>
			<viewInfo lookupType="One" lookupId="vdmcangdi" lookupKey="(kkh_yn = 1 or hc_yn = 1) and status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_di" />
		</field>
		<field name="ten_noi_di" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="ma_noi_den" viewType="Lookup" label="1" field="1" operation="like">
			<text v="Nơi đến" e="Destination"></text>
			<viewInfo lookupType="One" lookupId="vdmcangden" lookupKey="(kkh_yn = 1 or hc_yn = 1) and status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_den"  />
		</field>
		<field name="ten_noi_den" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>  
		 <field name="so_ct" label="1" field="1" allowBlank="false" viewType="Lookup">
          <text v="Lấy số báo giá" e="Get a quote number"></text>
          <viewInfo lookupType="one" lookupId="s51" lookupRef="ds_so_bg" lookupKey="ngay_ct between ![ngay_ct1]! and ![ngay_ct2]! and ma_noi_di like ![ma_noi_di]! +'%' and ma_noi_den like ![ma_noi_den]! +'%'  and status in (5,6)" lookupCheck="ma_kh = ![ma_kh]! and status in (5,6) and ma_nt = ![ma_nt]!" />
        </field>
        <field name="ds_so_bg" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
	
	
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>XAcO56GMRKstGNVQXIu2BKkoGtKaF/7EUzDJUsbF/n8V56a+wZ1pHDapVdNHmirY8AAvkfa7+WBtdGwICAraEZhQE7vyN2s4nKz/qaePgsehZSn6fftEtYLfyZ9PjMtFBpqApJ3nH5AqYujUyJBt0iekKSygqoNYdGMeRhlf7MWglceW2xiRAyRKYSV5i30C2Fa+kcTixRJeYovPk1XXLlU1J1/zBCvbGC5vZoVqUD2cwuhadLNaNCDfJrSlxYqMjx0ofhOQsqNo1o06DJ3bOXloTgnfWQKJXb7lDN062ucMdgIS/YOKAvsXukTTM5bYVgVzqLm9OpiSD7Xk7FEICUqYxdUV91Ym/4OnEzFANDHci/vi7FqAGiYrVTeOaLxBzHsx4eEE2QLOXtC4xk2Zkf6hkHQN4jIkRidL5a3kJXYhFd9niQo/0bMzQjdqFXB1GCn+sfURWEm44vGCCl7p12GZGjTWvcuz8lTmMlTy6/u//e1VYWsvPcAFuh+zAp8xl3NsTTClE9+xZbA3NmWke1Tud5B2vkdZ1OADudgz1Ofbvs0P71BwMXKSCNfHKJ2Dy9WzGiBAAD0E0oVcIfJSjoGEACRdDQIuwXtdrGERgZ0=</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>