<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
  <!ENTITY VoucherExtendFields SYSTEM "..\Include\XML\VoucherExtendFields.xml">
]>

<dir id="s612TG2Select" table="" height="" fieldKey="id" voucherCode="TG2" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Chi tiết báo giá được chọn" e="Quotation Entry Detail"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" readOnly="true" aliasName="@DFDFrom" disabled="true" allowBlank="false" dataType="D">
          <text v="Ngày c/từ từ/đến" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" allowBlank="false" disabled="true" inactivate="true" dataType="D" nextRow="false">
          <text v="Ngày đến" e="Voucher Date"></text>
        </field>
        <field name="ma_nt" hidden="true" label="1" field="1">
          <text v="Mã ngoại tệ" e="Ex Code"></text>
        </field>
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>
		<field name="ma_gd" viewType="Combobox" valueDefault=""  hidden="false" label="1" field="1" disabled="true" >
          <text v="Giao dịch" e="Transaction Code"></text>
          <viewInfo>
            <options query="select ma_gd, ten_gd%l from dmgd where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
		<field name="ma_kh" format="U" label="1" disabled="true"  field="1"  >
          <text v="Mã khách hàng" e="Code"></text>
        </field>
		<field name="ma_so_thue" label="1" field="-" disabled="true"  importable="35" nextRow="false" allowBlank="true">
          <text v="Mã số thuế " e="Tax Code"></text>
        </field>
		<field name="ten_kh" allowBlank="true" label="1" disabled="true"  field="-" importWidth="250" importable="10">
          <text v="Tên khách hàng" e="Name"></text>
        </field>
        <field name="ma_noi_di" viewType="Lookup" label="1" disabled="true" field="1" operation="like">
			<text v="Nơi đi" e="Origin "></text>
			<viewInfo lookupType="One" lookupId="vdmcangdi" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_di" />
		</field>
		<field name="ten_noi_di" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="ma_noi_den" viewType="Lookup" disabled="true" label="1" field="1" operation="like">
			<text v="Nơi đến" e="Destination"></text>
			<viewInfo lookupType="One" lookupId="vdmcangden" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_den"  />
		</field>
		<field name="ten_noi_den" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="so_ct" label="1" field="2" disabled="true">
          <text v="Số báo giá" e="Quot. Number"></text>
        </field>
        <field name="xprocess" label="1" field="2" valueDefault="2" viewType="Combobox">
          <text v="Xử lý" e="Process"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="Thêm vào chi tiết" e="Append To Detail"></text>
              </option>
              <option val="2">
                <text v="Xóa hết chi tiết và thêm mới" e="Delete All Detail And Append New"></text>
              </option>
            </options>
          </viewInfo>
        </field>
		<field name="id" dataType="N" hidden="true" fieldType="PK" label="1" field="1"  >
			<text v="ID" e="Code"></text>
		</field>
        
      </fields>
    </form>
    <form tabPageIndex="1" gravity="MiddleLeft" height="350" columns="120,120,240" >
      <text v="Chi tiết" e="Detail"></text>
      <fields>
        <field name="v52" label="" field="-" viewType="Grid">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
  </forms>

 <grids>
    <grid id="v52" table="v52" fieldKey="id, line" order="id, line" allowFilter="true" readOnly="false" allowOrder="true">
      <fields>
        <field name="id" foreignField="id" dataType="N" fieldType="PK" format="0" copy="false" hidden="true">
          <text v="" e=""></text>
        </field>
        <field name="line" foreignField="@@ROW" dataType="I" fieldType="PK" hidden="true">
          <text v="Dòng" e="Line"></text>
        </field>
		<field name="ma_kien" width="100" allowBlank="false" viewType="Lookup" readOnly="false" hidden="false"  >
          <text v="Mã kiện" e="Package Code"></text>
          <viewInfo lookupType="One" lookupId="dmkien" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_kien" lookupInfo="dmkien|ma_kien|ten_kien" />
        </field>
        <field name="ten_kien" width="120" fieldType="EX" inactivate="true" readOnly="true" aliasName="k" join="left join dmkien k on a.ma_kien = k.ma_kien" hidden="false" >
          <text v="Tên kiện" e="Package Name"></text>
        </field>
		
        <field name="so_luong" dataType="N" format="Amount" allowBlank="false" valueDefault="1" width="100" readOnly="false" >
          <text v="Số lượng" e="Quantity"></text>
        </field>
		<field name="ty_trong" dataType="N" format="FCPrice" width="120" readOnly="false" >
          <text v="Trọng lượng(KGS)" e="Gross Weight(KGS)"></text>
        </field>
		 <field name="tong_trong" dataType="N" inactivate="true" format="FCPrice" readOnly="false" disabled="true" width="120">
          <text v="Tổng trọng lượng (KGS)" e="Total Gross Weight(KGS)"></text>
        </field>
		<field name="ty_khoi" dataType="N" format="FCPrice" width="120" readOnly="false" >
          <text v="Volume(CBM)" e="Volume(CBM)"></text>
        </field>
		<field name="tong_khoi" dataType="N" inactivate="true" format="FCPrice"   readOnly="false" disabled="true" width="120">
          <text v="Tổng Volume" e="Total Volume"></text>
        </field>
        <field name="id_bg" dataType="N" fieldType="PK" format="0" hidden="true" aliasName="a.id as ">
          <text v="ID BG" e="ID BG"></text>
        </field>
        <field name="so_ct_bg" dataType="N" fieldType="PK" format="0" hidden="true" aliasName="a.so_ct as ">
          <text v="Số báo giá" e="Quot. .No"></text>
        </field>
        <field name="line_bg" dataType="I" fieldType="PK" hidden="true" aliasName="a.line as ">
          <text v="Dòng BG" e="Quot. Line"></text>
        </field>
      </fields>

      <buttons>
        <button id="freeze">
          <text v="$FreezeToolbar" e="$FreezeToolbar"></text>
        </button>
      </buttons>

      <script>
        <query>
          <text>
            <![CDATA[<enc>V7c+2t0Eir1eEUoY5j2zWJUJSVDCFu3hnkvCGA25Ti1TmvoWVN8/S1LTGdgl+BX/mu+D0zo5jHVAlrvbiwBGqH0ZNHsLCPz5cZ+UHhbNtFSpw6yAgPjYuDUzMCjfk9fyBxswT3TpfUIyelrQB/KVvS5z8BcJIxYM7dDuj4cU2EDGHMMsUEMYt7BiCToblB45kVUEqGLe05gDYN/hXaG21VQKXcNFdQ5P3KXbs+42goKiwAkCWgiy8iq2k+WpG60lhFSHEP3CaMMID1qDlNqGUrxbjuqfJM7dBB9lZmUDi7BNiYS8SozOGTpaPVnfwU64hpUPRtPhRz5DFsIO//gsoQ3JhNk6jYNLmD5tgFQJfppVd5uoFcnFpCN7NJ8u9Yyf2sWWxOasUoFfHpgLHXEK1JOlXie4jarFKjAhS17vy1dhfEN14gRC7wl80Rv4GSRQQXxJZpY5QztGTObn5IS3H8+GFsNBYXpimrnbXZsB1Voxnp60KGsPPoKy3xyTzhBlFoX4+ki7RO/7ep8wNl2oQIxeJVOqhbIjyT24hhcSMNdFb2CLZ14JGmS5p+KDQB5INoD3zX2B+aXEChS11JH54NN9mrxN9qPSKmynsrCvZsJNitui3+xzcOQZ3OM24nAq2j79K8+bpcogiQaS0K3QYtlMBpA709sNooZR9LJrPaa58uSkMxNCv0+9pLh2lS/VINkid+qjCoCYRXrCDNdN8tCInRE7rn+WXZN2XHL1t30=</enc>]]>
          </text>
        </query>
      </script>

    </grid>
   
  </grids>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>7f9uLLR/l5LzljgWQjHpy7RhidsXcQF4kEnOy/tMdxUybN0qolBrULnyO7go2K8IfTXuRQUTG5lq3Zddt7pkZzNlyXW4qWtWlY5x7VvRiAsFM4QMsbGg/lvv3Ktsw7g4ZW03GWIrHM64dxwX4m6dsH+Hn0zMmuWoC43t3Bfi+v9XryzMiOJHwIA/GSxST2Xv7u5BCBWu4vuazj1R0HGH/wsq8HUHMUYq2w+gAtAjKuwbvWsQLl2jcvtRYeFcdBh+qifNxhRcefbvRW7oUG5JzX/CeGaLx/4IyhmBe8S678sjB1pNnU/NeQFgQpQiG6OrQednzqZyPVSrUDSkm/wKugWlh/jcbbu5REfGud2Pmk06Pgw7OR0VgCnrvLQSxqkSl/jObLWLXeywNcZtKDLokjB60BjJ9kQQN/HJ1eLJVtUpM1wtKetw4bb8M3ySBba/+1BZpM5UuSAXJPG2+THsOu1KopXj0v+5/5rPh/zzIkzz5kVn2QT0zejOdlkXAqYcJyQ20fBMwMI84K/B+jHd5voFgkBc0awuniuSndVEvIkjXrsspSJJDfZiQo/c7wm+5dGm6E2RH1N2eqaZFNsWL2v+dtIKMUxLZ5ii32+r1uNarS3uiD0FASIDC1cBeEqJrTJDlecmL7BzTD9S5qszuEIcewxKQQ2ZH9kJSIf5lQCMgIqf/vNjswb00Cn1OEsPiCyU6ibn9a3qjt1QG/SeFT2gQElhARR3ThL5Nijk8h0PGFGwyicGzG8k7wqgBjztW96hkqzCf833TX238CinMw==</enc>]]>
    </text>
  </js>
  
  <script>
		<request code="ma_kh_request">
			<text>
			  <![CDATA[<enc>QR9NMhL8v8qeUwdztaTfNjE/3nuPjO5LyDSL52NLXtcRZ83J4HVSiPXhCPUNVQxyF+nWf0kfRRdeo6Xa6wiuy/Fg6nDByJ5Q+OBPygN5KN6OQ+aylCW3zdW1ZI4XRyxInN4LEbgCR5NCFvHyl6sE9iNGjd//zLCyFqiIcUwFWLAGT1Kk5znKMeXV7KR/JcB6tw5d+s+mENE3BQgcXNonQFY/7poIGXfxzQqALbrMTvz3XXs4MUUZU3B6LUap4gLd9DWpqshCJm4lpz7ItWLhtcUaXkznSgrSolXcGnyH4yw=</enc>]]>
			</text>
		</request>
  </script>
</dir>