<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="s612BQ2" fieldKey="id" voucherCode="BQ2" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc báo giá nhanh" e="Quick Quote Filtering"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D">
          <text v="Ngày từ/đến" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" aliasName="@DFDTo" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D" nextRow="false">
          <text v="" e=""></text>
        </field>
		<field name="ma_noi_di" viewType="Lookup" disabled="false" label="1" field="1" operation="like">
			<text v="Nơi đi" e="Origin "></text>
			<viewInfo lookupType="One" lookupId="vdmcangdi" lookupKey="(kkh_yn = 1 or hc_yn = 1) and status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_di" />
		</field>
		<field name="ten_noi_di" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="ma_noi_den" viewType="Lookup" disabled="false" label="1" field="1" operation="like">
			<text v="Nơi đến" e="Destination"></text>
			<viewInfo lookupType="One" lookupId="vdmcangden" lookupKey="(kkh_yn = 1 or hc_yn = 1) and status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_den"  />
		</field>
		<field name="ten_noi_den" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>  
		 <field name="so_ct" label="1" field="1" allowBlank="false" viewType="Lookup">
          <text v="Lấy số báo giá" e="Get a quote number"></text>
          <viewInfo lookupType="one" lookupId="s42" lookupRef="ds_so_bg" lookupKey="ngay_ct between ![ngay_ct1]! and ![ngay_ct2]! and ma_noi_di like ![ma_noi_di]! +'%' and ma_noi_den like ![ma_noi_den]! +'%'  and status in (5,6)" lookupCheck="ma_kh = ![ma_kh]! and status in (5,6) and ma_nt = ![ma_nt]!" />
        </field>
        <field name="ds_so_bg" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
	
	
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>1V6giqiwpQAhfyIP2xcEHFSyeaEi6qBdvyXkqnE8ag4irYB6lDlRIye8UROdboxukX4+FOT6nvAiSnPDFixWhxAwGgTJGWkvxp3o5aZwMOjB+IGbTieJL9M/w+SLaY7tfd77RYR8OndLbVLUiWodkzZq57NZfTAKhGdX7BMMbRUU9xd+G4DZ//3SCIwR8NyNEgRmsjcZGNF19eBMU1W3fIXOgfUS15/x8K/ZbYMNwW28At4IbRlYoKXUFmh0JSMSoHZozZeFDh2zP0MEpmNsb2e1GijIz+CrU8mAOju4/D3wsX6z0oomi20xf7qNPw/1oycWD4tKpCUfKW0inSw3+YmWuGH2+C8XTJb5vtRYG48rK3y+ygf/3dA230t0uywYD9aXn3+JZDLMbZ0E4OeNGAw5EGmg0T4pMRFkf86iJ4dVaIjbWnskzDWR6J2lhqY9XhH7vggPYWD624Miw0iawrfiW3pDcs04J8Y4W4H6szIM97K1cdrga45orb/w+bmZn5YMiPRoMQGicdIy70HcFuJlLX3S8ijjnifNhZvHCmqwIz6ZoYvzUyR78AdCXTsUFJ7njibFhYOTsmuxZn22FQ==</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>