<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="s613BQ3" fieldKey="id" voucherCode="AIR" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc báo giá nhanh" e="Quick Quote Filtering"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D">
          <text v="Ngày từ/đến" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" aliasName="@DFDTo" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D" nextRow="false">
          <text v="" e=""></text>
        </field>
		<field name="ma_noi_di" viewType="Lookup" disabled="false" label="1" field="1" operation="like">
			<text v="Nơi đi" e="Origin "></text>
			<viewInfo lookupType="One" lookupId="vdmcangdi" lookupKey="(kkh_yn = 1 or hc_yn = 1) and status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_di" />
		</field>
		<field name="ten_noi_di" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="ma_noi_den" viewType="Lookup" disabled="false" label="1" field="1" operation="like">
			<text v="Nơi đến" e="Destination"></text>
			<viewInfo lookupType="One" lookupId="vdmcangden" lookupKey="(kkh_yn = 1 or hc_yn = 1) and status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_den"  />
		</field>
		<field name="ten_noi_den" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>  
		 <field name="so_ct" label="1" field="1" allowBlank="false" viewType="Lookup">
          <text v="Lấy số báo giá" e="Get a quote number"></text>
          <viewInfo lookupType="one" lookupId="s43" lookupRef="ds_so_bg" lookupKey="ngay_ct between ![ngay_ct1]! and ![ngay_ct2]! and ma_noi_di like ![ma_noi_di]! +'%' and ma_noi_den like ![ma_noi_den]! +'%'  and status in (5,6)" lookupCheck="ma_kh = ![ma_kh]! and status in (5,6) and ma_nt = ![ma_nt]!" />
        </field>
        <field name="ds_so_bg" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
	
	
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>1V6giqiwpQAhfyIP2xcEHKdCb1bYdYG+e/q5qibyBM0z3q3LYonVB6LFbVL7OaxqoeS86G1xsFw3zYaPCKvKBDBTlIZbO3RENv6nkh8EvY325hghMP7vUQEtNLAH2ElIslIDreZuaEUqdxvMmEAXFuMJevBi5h9yb/wvAX07kUTtSmxha9GEyV+6cTGcelAGBVN2HuOpWmgbgaLAxu0QtB8XVPHCD6/kvD6w2N8PGc+THZHFRF5TpuurnzKzX/MSE+Iw0fHqjg6PS2gRqbmaxjIbJN126yt+ayjjvh4DBnJRvo+a8UmDnK6ylCQJXR9gh2I1uqzQrzeoi/UsFyVvaMdM3HgzWkhiJ1UigNhn7R+3/htjBhokLilWOCI8Mx0p5zOWbRF+Q8yyVG/hitKKpYMA0XkNZWlFUYbItXPbenusbN3+0SUHQjtGWz0jq1YrbL3caKXNYY69mLwEfbQlvxDnNCgvaQU7woPwpFmJ7O5PqrIp0IM0idm4jt+SvxLvykB49JH00CuvsEHtYg/jkGOHVa/ouqVB6yahI6MyBa7yerBlQPaas0endB8b5oMlT8rAy54biHxOZlD7TTG51Q==</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>