<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="s613TG3" fieldKey="id" voucherCode="TG3" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc tìm báo giá nhanh" e="Quick Price Search Filtering"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D">
          <text v="Ngày từ/đến" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" aliasName="@DFDTo" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D" nextRow="false">
          <text v="" e=""></text>
        </field>
		<field name="ma_noi_di" viewType="Lookup" disabled="true" label="1" field="1" operation="like">
			<text v="Nơi đi" e="Origin "></text>
			<viewInfo lookupType="One" lookupId="vdmcangdi" lookupKey="(kkh_yn = 1 or hc_yn = 1) and status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_di" />
		</field>
		<field name="ten_noi_di" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="ma_noi_den" viewType="Lookup" disabled="true" label="1" field="1" operation="like">
			<text v="Nơi đến" e="Destination"></text>
			<viewInfo lookupType="One" lookupId="vdmcangden" lookupKey="(kkh_yn = 1 or hc_yn = 1) and status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_den"  />
		</field>
		<field name="ten_noi_den" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>  
		 <field name="so_ct" label="1" field="1" allowBlank="false" viewType="Lookup">
          <text v="Lấy số báo giá" e="Get a quote number"></text>
          <viewInfo lookupType="one" lookupId="s53" lookupRef="ds_so_bg" lookupKey="ngay_ct between ![ngay_ct1]! and ![ngay_ct2]! and ma_noi_di like ![ma_noi_di]! +'%' and ma_noi_den like ![ma_noi_den]! +'%'  and status in (5,6)" lookupCheck="ma_kh = ![ma_kh]! and status in (5,6) and ma_nt = ![ma_nt]!" />
        </field>
        <field name="ds_so_bg" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
	
	
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>Am4HwVWZUdjyweGs7WCxsYMMM54qvCK7lufQ1ex7eQGVTugaKxqKvGGNT+qvGHYnJomXnzn0VFvwPQZXnQJk4i3wCpKC0xbG0EeAuEWXzF1p/5mjM1KE8dm9Z2XH+UZt5Johbz6+LNVpNX6mr328Elk4c9JLWqI4la+2x5XnWGAVypgfU8YEB3FYgpVpH1NPqyi8eHu0ogOkJTBVfbvO0vbk1Bz7E6NUScU/EEXaEdjsjGZq0TQre4AKsbDHuSr0FX6zODxwJh8c3NVkYPmhudtMIPSfYGpoYVIp5xZMQ9eTVOBki/QC/oKP/Yw/LeGBNErdE1mZea9TT5GBdeo4lIfhQq3H0nbNO/G2zJkm7VWlGJyl0qMcQivow21avs/VGYeRGx1DBfeOWqGmJc+ICQBReMKANJTLpqtuMF5kEx9bwcxQrJOdu5sL8pmyUQ6L5Iu4CNFysLfiPC8G9bq49fQALafyWDNQLwzg81jXcEuC7TTi4I7vb4OsFXUcQGQeviDf4Ev/s2gl+gs0KwKST55QiMCe5+X/fLun5Gp31YcoDLNNnqWA+Z4S5U/Q/lN8MHf6MsX89tbtzWrDkqOBMg==</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>