<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="s614CR" fieldKey="id" voucherCode="BQ2" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc đơn hàng cước quốc tế" e="Filtering International Freight Orders"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D">
          <text v="Ngày từ/đến" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" aliasName="@DFDTo" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D" nextRow="false">
          <text v="" e=""></text>
        </field>
		<field name="ma_job" allowBlank="true" viewType="Lookup" label="1" field="1"  hidden="false" tabIndex="1">
          <text v="Mã/Số" e="Code/No"></text>
          <viewInfo lookupType="One" lookupId="vdmjob" lookupKey="status = 1" lookupCheck="1=1" lookupRef="ten_job" lookupInfo="vdmjob|ma_job|ten_job" />
        </field>
        <field name="ten_job" nextRow="false" fieldType="EX" readOnly="true" inactivate="true"  hidden="false" label="" field="" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
		<field name="so_job" label="" field="1" nextRow="false" >
          <text v="Số" e="Voucher Number"></text>
        </field>
		<field name="ma_ct" viewType="Combobox" inactivate="true" label="1" field="1">
          <text v="Loại đơn hàng" e="Type Order"></text>
          <viewInfo>
            <options>
              <option val="">
                <text v="Tất cả" e="All"></text>
              </option>
              <option val="FCL">
                <text v="Hàng FCL" e="FCL Marine"></text>
              </option>
			  <option val="LCL">
                <text v="Hàng LCL" e="LCL Marine"></text>
              </option>
				<option val="AIR">
                <text v="Hàng AIR" e="AIR Marine"></text>
              </option>
            </options>
          </viewInfo>
        </field>
		<!-- <field name="ma_log" allowBlank="true" viewType="Lookup" label="1" field="1"  hidden="false" tabIndex="1"> -->
          <!-- <text v="Mã Log" e="Log Code"></text> -->
          <!-- <viewInfo lookupType="One" lookupId="dmlog" lookupKey="status = 1" lookupCheck="1=1" lookupRef="ten_log" lookupInfo="dmlog|ma_log|ten_log" /> -->
        <!-- </field> -->
        <!-- <field name="ten_log" nextRow="false" fieldType="EX" readOnly="true" inactivate="true"  hidden="false" label="" field="-" aliasName="cast('' as nvarchar(4000)) as "> -->
          <!-- <text v="" e=""></text> -->
        <!-- </field> -->
		<field name="ma_kh" allowBlank="true" viewType="Lookup" label="1" field="1"  hidden="false" nextRow="true">
          <text v="Khách hàng" e="Customer"></text>
          <viewInfo lookupType="One" lookupId="dmkh" lookupKey="status = 1 and kh_yn = 1" lookupCheck="kh_yn = 1" lookupRef="ten_kh" lookupInfo="dmkh|ma_kh|ten_kh" />
        </field>
        <field name="ten_kh" nextRow="false" fieldType="EX" readOnly="true" inactivate="true"  hidden="false" label="" field="1" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
		<field name="ma_kh_g" allowBlank="true" viewType="Lookup" label="1" field="1"  hidden="false">
          <text v="Người nhận" e="Consignee"></text>
          <viewInfo lookupType="One" lookupId="dmkh" lookupKey="status = 1 and other_yn = 1" lookupCheck="other_yn = 1" lookupRef="ten_kh_g" lookupInfo="dmkh|ma_kh|ten_kh" />
        </field>
        <field name="ten_kh_g" nextRow="false" fieldType="EX" readOnly="true" inactivate="true"  hidden="false" label="" field="1" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
		<field name="ma_kh_s" allowBlank="true" viewType="Lookup" label="1" field="1"  hidden="false">
          <text v="Người gửi" e="Shipper"></text>
          <viewInfo lookupType="One" lookupId="dmkh" lookupKey="status = 1 and other_yn = 1" lookupCheck="other_yn = 1" lookupRef="ten_kh_s" lookupInfo="dmkh|ma_kh|ten_kh" />
        </field>
		<field name="ten_kh_s" nextRow="false" fieldType="EX" readOnly="true" inactivate="true"  hidden="false" label="" field="1" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
		<field name="ma_dl" allowBlank="true" viewType="Lookup" label="1" field="1"  hidden="false" tabIndex="2" nextRow="true">
		  <text v="Đại lý" e="Agent"></text>
		  <viewInfo lookupType="One" lookupId="vdmdaily" lookupKey="status = 1 and dl_yn =1" lookupCheck="1=1" lookupRef="ten_dl" lookupInfo="vdmdaily|ma_dl|ten_dl" />
		</field>
		<field name="ten_dl" nextRow="false" fieldType="EX" readOnly="true" inactivate="true"  hidden="true" label="" field="1" aliasName="cast('' as nvarchar(200)) as ">
		  <text v="" e=""></text>
		</field>
        <field name="ma_noi_di" viewType="Lookup" disabled="false" label="1" field="1" operation="like">
			<text v="Nơi đi" e="Origin "></text>
			<viewInfo lookupType="One" lookupId="vdmcangdi" lookupKey="(kkh_yn = 1 or hc_yn = 1) and status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_di" />
		</field>
		<field name="ten_noi_di" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="ma_noi_den" viewType="Lookup" label="1" field="1" operation="like">
			<text v="Nơi đến" e="Destination"></text>
			<viewInfo lookupType="One" lookupId="vdmcangden" lookupKey="(kkh_yn = 1 or hc_yn = 1) and status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_den"  />
		</field>
		<field name="ten_noi_den" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>	
		 <field name="so_ct" label="1" field="1" allowBlank="false" viewType="Lookup" operation="like">
          <text v="Lấy số đơn hàng" e="Get the order number"></text>
          <viewInfo lookupType="one" lookupId="s61" lookupRef="ds_so_dh" lookupKey="ngay_ct between ![ngay_ct1]! and ![ngay_ct2]! and ma_job like ![ma_job]! + '%' and so_job like ![so_job]! + '%' and ma_noi_di like ![ma_noi_di]! +'%' and ma_noi_den like ![ma_noi_den]! +'%' and ma_ct like ![ma_ct]! +'%' and ma_kh like ![ma_kh]! +'%' and ma_kh_g like ![ma_kh_g]! +'%' and ma_kh_s like ![ma_kh_s]! +'%' and ma_dl like ![ma_dl]! +'%' and status in (1) " lookupCheck="ma_job like ![ma_job]! + '%' and so_job like ![so_job]! + '%' and status in (1)" />
        </field>
        <field name="ds_so_dh" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
	
	
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>LyWv3ltyii9A1XZTGL+IZ11KEVTVsquib2m3zV8GdLf8/ktBbfRCXzYRnUOFDa7UtgceiJA9dfWgGOE4gqPS7mFBPvnYgK/Q78ZVBJQe8idA0UENVQkQiu0JnyXG65Lgz1u/IjHIEF9m6F2eDOaf+Q5mln2Oz9Z/4195eoqunx0m68+eddVkT6Wd1s6a5/L4fZt/up530RJ2rdzQfxik9zvILFPJokt0WsLjUCMW8dbA+7mVWLAhnafN11s1dBiumIo70SwAd8lPfVGtre1/5yuu5qsjZzdj8ncimXkTIdcVgT3FufMHcVRDUvfIVMQwvmAPxGHSLpyvLFKXA4dgXPYj+ChW1G4Ma0jwLTd83bQZph5TpiFD3W97swfGX3oiSx0bKdU1CWU5PR6V2clFvDoYHzH8wYk4RKDAVlaJf7eYa+6sc3QlRAeDF3olvcSwlz7wXtZ8qMCGEZZTXaI7PrmgCdIO5NZr34qkLitteIuS0gRZpoo/bbTyfhq4dm7WEc5vUm0MLV12Qm8SojhkcoY0IAjv76vfD/eNPDRR6XzTL2yCj1kEFsRwHfmqB1NIgbpQLpCt4QvmJRsY87e57Q==</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>