<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="s614BQ2" fieldKey="id" voucherCode="BQ2" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc báo giá nhanh" e="Quick Quote Filtering"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D">
          <text v="Ngày từ/đến" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" aliasName="@DFDTo" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D" nextRow="false">
          <text v="" e=""></text>
        </field>
		<field name="ma_noi_di" viewType="Lookup" disabled="false" label="1" field="1" operation="like">
			<text v="Nơi đi" e="Origin "></text>
			<viewInfo lookupType="One" lookupId="vdmcangdi" lookupKey="(kkh_yn = 1 or hc_yn = 1) and status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_di" />
		</field>
		<field name="ten_noi_di" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="ma_noi_den" viewType="Lookup" disabled="false" label="1" field="1" operation="like">
			<text v="Nơi đến" e="Destination"></text>
			<viewInfo lookupType="One" lookupId="vdmcangden" lookupKey="(kkh_yn = 1 or hc_yn = 1) and status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_den"  />
		</field>
		<field name="ten_noi_den" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>  
		 <field name="so_ct" label="1" field="1" allowBlank="false" viewType="Lookup">
          <text v="Lấy số báo giá" e="Get a quote number"></text>
          <viewInfo lookupType="one" lookupId="s42" lookupRef="ds_so_bg" lookupKey="ngay_ct between ![ngay_ct1]! and ![ngay_ct2]! and ma_noi_di like ![ma_noi_di]! +'%' and ma_noi_den like ![ma_noi_den]! +'%'  and status in (5,6)" lookupCheck="ma_kh = ![ma_kh]! and status in (5,6) and ma_nt = ![ma_nt]!" />
        </field>
        <field name="ds_so_bg" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
	
	
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>1V6giqiwpQAhfyIP2xcEHLdJxQK+z7iFk4enSqz7CSxANzkNbS7V9/i0zP/kC+53yNFz7SthDcrmHpsRUwlZbPxuZUsYdVzTrR0rJqhT4XRqvZ0OUa6+V9uJxPjQ4q9M5uYeVx+iieE3kuQDBKGWFrNdUo4bm6iPckfQUyX8m3DOepcpwCOGFfBlg1j6GyeBA/XwQQtJ5n0p5tYjSj79OROIAksJASXcJ1YBqk3E44e4UV8XuMgEKJGbZi8O01gXc4+lGBFBBon0K6uQpxv7Qz3fUCU0aXuY1KeEj4vnYclRBchC1zaC7mCxL78gowgeQ64KvgrUU6/MgYt2MS2zF8PvlS2d6ZAnyehcj1cyorQ38aMC8qtAXn0XgNX7pjI2vWfhHAmqnF/iGowjC9VFfQ2xUtENoD4hYqR6Zs6NwdQRfc5sJZVU6SSzIobJHFlFpU6hJo+k+vcQqLCRawz+bcbvaVCwfaL5bKW++Cdg/Te3HKNQW1zODzgv5S9NF5NLu0YFGlD//lSFdVg3X4uRRb9jzcffzo4ZE+njgEzextnrs+QENhMzFHtXhAvhPaJB45Ab7/AsKSsVxOPNq5UHwQ==</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>