<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="s631BN1" fieldKey="id" voucherCode="PM1" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc giá cước" e="Rate Filtering"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" allowBlank="false" dataType="D">
          <text v="Ngày c/từ từ/đến" e="Date From"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" allowBlank="false" inactivate="true" dataType="D" nextRow="false">
          <text v="Ngày đến" e="Date To"></text>
        </field>
		<field name="ngay_ct" label="" field="1" allowBlank="false" inactivate="true"  hidden="true" dataType="D" nextRow="true">
          <text v="Ngày chứng từ" e="Voucher Date"></text>
        </field>
        <field name="ma_nt" hidden="true" label="1" field="1">
          <text v="Mã ngoại tệ" e="Ex Code"></text>
        </field>
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="ma_noi_di" viewType="Lookup" disabled="true" inactivate="true" label="1" field="1">
			<text v="Nơi đi" e="Origin "></text>
			<viewInfo lookupType="One" lookupId="vdmcangdi" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_di" />
		</field>
		<field name="ten_noi_di" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="ma_noi_den" viewType="Lookup" disabled="true" label="1" field="1" operation="like">
			<text v="Nơi đến" e="Destination"></text>
			<viewInfo lookupType="One" lookupId="vdmcangden" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_den"  />
		</field>
		<field name="ten_noi_den" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>  
		
		<field name="ma_hang" viewType="Lookup" disabled="true" inactivate="true" label="1" field="1">
          <text v="Mã hãng tàu" e=" Carriers"></text>
          <viewInfo lookupType="One" lookupId="dmhangtau" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_hang" />
        </field>
        <field name="ten_hang" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
		
		<!-- <field name="ma_cong" viewType="Lookup" disabled="false" inactivate="true" label="1" field="1"> -->
			  <!-- <text v="Loại Container" e="Container"></text> -->
			  <!-- <viewInfo lookupType="One" lookupId="dmcong" lookupKey="status = 1 " lookupCheck="1=1" lookupRef="ten_cong" /> -->
			<!-- </field> -->
			<!-- <field name="ten_cong"  nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-"> -->
			  <!-- <text v="" e=""></text> -->
		<!-- </field> -->
		
		 <field name="ds_cong" allowBlank="false" viewType="Lookup" label="1" field="-"  hidden="false">
			  <text v="Container" e="Container List"></text>
			  <viewInfo lookupType="Multi" lookupId="dmcong2" lookupKey="status=1" lookupCheck="status=1" lookupRef="" lookupInfo="dmcong|ma_cong|ten_cong" />
		</field>
			
        <!-- <field name="so_ct" label="1" field="1" allowBlank="true" hidden="true" viewType="Lookup"> -->
          <!-- <text v="Số báo giá" e="Quot. Number"></text> -->
          <!-- <viewInfo lookupType="One" lookupId="v311" lookupRef="ds_so_ct" lookupKey=" ![ngay_ct2]! >= ngay_hl  and  ngay_hld >= ![ngay_ct1]! and ma_noi_di = ![ma_noi_di]! and ma_noi_den = ![ma_noi_den]! and ma_kh like ![ma_hang]! +'%' and unit_id = ![unit_id]!" /> -->
        <!-- </field> -->
		
		<field name="trong_luong" label="1" field="1" dataType="N" disabled="true" nextRow="true" format="Amount" hidden="true" >
          <text v="Tổng trọng lượng" e="Total Weight"></text>
        </field>	
        <field name="so_ct" label="1" field="1" allowBlank="true" hidden="false" >
          <text v="Số báo giá" e="Quot. Number"></text>
        </field>
		
        <field name="ds_so_ct" nextRow="false" fieldType="EX" readOnly="true"   hidden="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
		<field name="id_dh" dataType="I"  readOnly="true" fieldType="PK" hidden="true" >
          <text v="Id dh" e="Request. Id"></text>
        </field>
      </fields>
    </form>
	
	
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>OnRRm1WO6QuegIrFr3ybyFTMF5zVsM2vdIeoe6AIRGk0L5lLRJGqRRnAGvCUk5PEnKPyKwyL3qhC6OoYY+6wYbuNCx2DOJhodTNGn7hDc8OiV3dtfTW8nA8A6Cb68P8l151V+fm5GcgxtOExQHmpN1WurnEFcSXEYJX2UOpdmZWTmkCq4byoVOysPcNA9mKcAXTptbnbreddr2L1681Vk8qLKP5IBm9Rr/gECJP0j8PS0B21GoTvz24gQzxffiKOruCxoyOe7PR157LRW3ki3McSJPrH1H/gl8lDBuvjZnigcaqPQSje42vWCkE44GRnQ+HBTAY9d8jTD0DCk9b+zczSMF9FJ+x1KujezUVgEqIrnSBzIhP74CEix3+JSRyXDtTbqnj75mYBK9SLuf34tCZnGsoZU3Afvw5KmDVK7xAZI+MkyqjWFJBpIr22NGxjgrs9JT0TUM4byehbZqlrwGd4HaD78ILESap8g4n7pFNxnbY7pTQRcvhepGxp5QO98gaU8iXr6NysQ7FzfHR+Z/iJOL9sSwwRR+YEnQcBBIjgtlWPE9E16rym9C/J0KSnizilzEIP0L1JUn/5h/G1qFSOPUv+Yg33GKSWUAROdDVm8TBrodog4w7judNL2gg6xD9LNcUrMMehDMPp1VBQJg==</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>