<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="s621BQ1" fieldKey="id" voucherCode="BQ1" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc số báo giá FCL" e="Filter FCL Quotes Numbers"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" allowBlank="false" dataType="D">
          <text v="Ngày c/từ từ/đến" e="From Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" allowBlank="false" inactivate="true" dataType="D" nextRow="false">
          <text v="Ngày đến" e="To Date"></text>
        </field>
       
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>
		
        <field name="ma_noi_di" viewType="Lookup" disabled="false" label="1" field="1" operation="like">
			<text v="Nơi đi" e="Origin "></text>
			<viewInfo lookupType="One" lookupId="vdmcangdi" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_di" />
		</field>
		<field name="ten_noi_di" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="ma_noi_den" viewType="Lookup" label="1" field="1" operation="like">
			<text v="Nơi đến" e="Destination"></text>
			<viewInfo lookupType="One" lookupId="vdmcangden" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_den"  />
		</field>
		<field name="ten_noi_den" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>  
			
		 <field name="id_bg" label="1" field="1" allowBlank="false">
          <text v="Số báo giá" e="Get the order number"></text>
        </field>
      </fields>
    </form>
	
	
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>w6H/9c5cxGbCk2oeo1B3ui++p4cm5yMcsYn1baULcwPQGu+9eB1yQuBmJAENhCWWKF6G2fd3JVaMKhX0imDbDW3U1Z68w9RDa8q5GYH/O/pelKtI60Vm+K85SDAEj/UZ8VjksV6BgkGpY35jm46O+KvfewLtyeSNG/4IqFMpHGhK/wcDNd/T/fN1q168+4dKK0Kdyqu47SxRb/OA+COjh8MHm2cQVStDAiJYyPfwk92vXLoiyzcJdnUbz2iK/Px2qVvI9p0+0mRar5m7GB2wbMzsTeDo72sISSfO+nrgRnfp6uenWM2a6nKsGgBHAgEcExpT7Z+KW5MvwZJnEW7JF/SB5y501T6DPAQyFaElukYywyG+IrkJUd3rJ3df0KZxXcZlIF5LJDGvPeK/vu6CbkmEwRvHPovO302z/FRen4qWjIy2LQrr7y95I8JXi7ciBFAncfgxcidX1oCwAcl7OX0AzpUbKtRB5ofR8gAAoewrTnkwQnS11fX7856JKg8NX2uvSkcSPfYjgcz8Aq6jKZ6Uwg/F4I0kPqBIgKBnxB3g4HFa7gXyh2FNzGM4PZgYGab13j29FUZp7FNZ9udHqjDZZWzVIsH7oJCzneXktZbNh+7QHpHYjanVUwb6yZgw</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>