<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="s622CR2" fieldKey="id" voucherCode="CR2" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc báo giá" e="Quotation Entry Filter"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D">
          <text v="Ngày từ/đến" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" aliasName="@DFDTo" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D" nextRow="false">
          <text v="" e=""></text>
        </field>
       
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="ma_noi_di" viewType="Lookup" disabled="false" label="1" field="1" operation="like">
			<text v="Nơi đi" e="Origin "></text>
			<viewInfo lookupType="One" lookupId="vdmcangdi" lookupKey="(kkh_yn = 1 or hc_yn = 1) and status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_di" />
		</field>
		<field name="ten_noi_di" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="ma_noi_den" viewType="Lookup" label="1" field="1" operation="like">
			<text v="Nơi đến" e="Destination"></text>
			<viewInfo lookupType="One" lookupId="vdmcangden" lookupKey="(kkh_yn = 1 or hc_yn = 1) and status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_den"  />
		</field>
		<field name="ten_noi_den" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>	
		 <field name="so_ct" label="1" field="1" allowBlank="false" viewType="Lookup" operation="like">
          <text v="Lấy số đơn hàng" e="Get the order number"></text>
          <viewInfo lookupType="one" lookupId="s612" lookupRef="ds_so_dh" lookupKey="ngay_ct between ![ngay_ct1]! and ![ngay_ct2]! and ma_noi_di like ![ma_noi_di]! +'%' and ma_noi_den like ![ma_noi_den]! +'%'" lookupCheck="ma_noi_di like ![ma_noi_di]! and ma_noi_den like ![ma_noi_den]!  and status in (5,6)" />
        </field>
        <field name="ds_so_dh" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>	
      </fields>
    </form>
	
	
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>7dnUqIuxukLuRCTGhnr/WUH7IwtIpaazqmZuyyRLeAdJAahqb7/HnMr1d2J88rfKb6ydzOa1hw4DYBfpWG3vJoTujRD/RgHmX3wHSkUUiVyyNZQVxZXYj7i8yNFSd8B5YEd46/MHWyTldXaTfYaapMoWRmpmt4/Et8paX0VbFm8S9Whf4hNJ40ZoNuMvrvsRr6HHDssHlI58TAuqYqVfVryyt9Xp5/FJ6elIXYl3UeSyrFyJE5+I3AmJ9YfLqAIab5FwCeSWBQGc46bQQMR0uvLMDaV7xqRQAR/r4oJtOMuM+W63BBXkRrBT0nce4HxBLTTABYNbsZQQKs8UBCiUuEhRSF2Y1G/50U4XA2z8XuD60SXdUaM20luYMGa8Cx7k18fmEjxLyjoSPrSfkYxRFjqPXzx2Ttw+qI1NmPhWkKAwAGPrKDvR9xxjaJd7/CBivwXRzJ02fEbwayzLclJqMc2uFBmE0EnU+cpxzBPSYCn1+2CBTP23BWKdxXpxG2pe5QTG9S8ZIaf6eup/4Qt1/ucN+zoikeQZXYrHNo39H7nfgZFVt3gxPwc/UGIP8Xk+</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>