<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="s622BN2" fieldKey="id" voucherCode="PM2" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc báo giá" e="Quotation Entry Filter"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" allowBlank="false" dataType="D">
          <text v="Ngày c/từ từ/đến" e="Date From"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" allowBlank="false" inactivate="true" dataType="D" nextRow="false">
          <text v="Ngày đến" e="Date To"></text>
        </field>
		<field name="ngay_ct" label="" field="1" allowBlank="false" inactivate="true"  hidden="true" dataType="D" nextRow="true">
          <text v="Ngày chứng từ" e="Voucher Date"></text>
        </field>
        <field name="ma_nt" hidden="true" label="1" field="1">
          <text v="Mã ngoại tệ" e="Ex Code"></text>
        </field>
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="ma_noi_di" viewType="Lookup" disabled="true" inactivate="true" label="1" field="1">
			<text v="Nơi đi" e="Origin "></text>
			<viewInfo lookupType="One" lookupId="vdmcangdi" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_di" />
		</field>
		<field name="ten_noi_di" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="ma_noi_den" viewType="Lookup" disabled="true" label="1" field="1" operation="like">
			<text v="Nơi đến" e="Destination"></text>
			<viewInfo lookupType="One" lookupId="vdmcangden" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_den"  />
		</field>
		<field name="ten_noi_den" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>  
		
		<field name="ma_hang" viewType="Lookup" disabled="true" inactivate="true" label="1" field="1">
          <text v="Mã hãng tàu" e=" Carriers"></text>
          <viewInfo lookupType="One" lookupId="dmhangtau" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_hang" />
        </field>
        <field name="ten_hang" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
		
		 <field name="t_tong_trong" label="1" field="1" dataType="N" disabled="false" readOnly="false" nextRow="true" format="FCAmount" >
          <text v="Tổng trọng lượng" e="Total Weight"></text>
        </field>
		<field name="t_tong_khoi" label="1" field="1" dataType="N" disabled="false" readOnly="false" nextRow="true" format="FCAmount" >
          <text v="Tổng Volume" e="Total Volume"></text>
        </field>
				
        <field name="so_ct" label="1" field="1" allowBlank="true" hidden="false" >
          <text v="Số báo giá" e="Quot. Number"></text>
        </field>
		
        <field name="ds_so_ct" nextRow="false" fieldType="EX" readOnly="true"   hidden="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
		<field name="id_dh" dataType="I"  readOnly="true" fieldType="PK" hidden="true" >
          <text v="Id dh" e="Request. Id"></text>
        </field>
      </fields>
    </form>
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>yQ0Ka/K3BdMZDifnE7DmrIXJzwkBiw2VHYHfNmUqDdrEkQvCrW4dtOPyH2W6IKfaCno2wza2VwtloXoTzfNS8BZxzPuilMZbqWqJrREc2h9gIiobB/e84JCIdl0nh86umoPtDt9YcyJVg7YQ8lAIFHYQqGMEDexZwDtZWZikeLfMx9awkdJn8dKsdQkbLcOf7m4ImEPmlhD8b8VMsLEs3ij1HJqmV5bQeC3XbxtfPMYEP4UdAjevChVUifdp6jlSKyKjSdCot+TkQQ3SPmMPuva2AIW6DIY926ZwqSCHFUYnN1R6QGeSBfaxTwn+f6J2EsP/JFHpYZ5MIi7mCoDcj43uSxDowfU1rY7N9bvu2VmPQFTUKL+NE+i99XWpEbJGyv/niZ5dIQ5JnWZLLJjI6MzcVeHSjkAyUD1VFqaRWkzm1uFZCD6Zo/p5FE3F4/AXw5D60NZWpn+JtznOXFAsBMqFMjyH2bO07/1h3OstNj3/L8E2wl5PESIZKY03ZRyYvWDApNeDpjCYF6X0KX3/BPJFWjhpJsfF0h2ZO+trJ2I2M0dZY3ImYqmgfy/rWLGCneJ4graOY9JKrmbFXuOMqt5TyKFfXa4EfGhJfhv6aP3KUJzj4miVLSWRO5HRyHAD</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>