<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="s622BQ2" fieldKey="id" voucherCode="BQ2" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc báo giá" e="Quotation Entry Filter"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" allowBlank="false" dataType="D">
          <text v="Ngày c/từ từ/đến" e="From Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" allowBlank="false" inactivate="true" dataType="D" nextRow="false">
          <text v="Ngày đến" e="To Date"></text>
        </field>
       
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>
		
        <field name="ma_noi_di" viewType="Lookup" disabled="true" label="1" field="1" operation="like">
			<text v="Nơi đi" e="Origin "></text>
			<viewInfo lookupType="One" lookupId="vdmcangdi" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_di" />
		</field>
		<field name="ten_noi_di" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="ma_noi_den" viewType="Lookup" label="1"  disabled="true"  field="1" operation="like">
			<text v="Nơi đến" e="Destination"></text>
			<viewInfo lookupType="One" lookupId="vdmcangden" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_den"  />
		</field>
		<field name="ten_noi_den" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>  
			
		 <field name="id_bg" label="1" field="1"   disabled="true" allowBlank="false">
          <text v="Số báo giá" e="Get the order number"></text>
        </field>
      </fields>
    </form>
	
	
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>6zqcKTM+BlB9FgSJhQ+uJlOaaY//n5klOf8g0f5coRrSCXh/l9mmGf/jv3TJQr+oLcECUbuiyNIQB5gyLUbjmmuhkVc+fZHzOLfiMervllmy4FUcND3K8Mm+piBr8ElumbO3az8xzOyiBywxtYod0Lqqdx6ODWeft7+avINPzD3ewgSkc2UsrB3dqvUr7K25zIAR79Bm4yj7ygUYtyBxaEEv0eFE7acQDPIn8AOIuvz4xhvUrMgVwS7ZuXTfb1lDxStMO+A2FwtwLWQxql6zd5TO9peiZ/EN/OHZLQg+GZYLLP4b59bnn/rctmGDvGBLV6Oopls9uQXpFvU58vyKjZd5dLQg+HDlMtVA7uTlAQNhy8p5DXUj8Afqa1cW88wHwCA0Gb6SFAPQ5TbXZopgyyhZiX+35aidqJX9tHiwGhIsF5qEg2kCdGVOLHza4NV6ewCBqtTLHEhHnX5U6Nu9FrTDjWyykjjO78gs6hBd2GGxILGZT9T/cfXrTqa46UOeVixXbq4AeWNyDaKyg8/jduxOz09ud9qwmTOggNNB8W09UKU8Zt0W+MX12OF/oHdlPTLKyvHKb9AylPNl6RZ28k6Qn5qjLC0LxtxkQyr8T+gQ6zGZTkw9gSKUrbYGlGyO</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>