<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
  <!ENTITY VoucherExtendFields SYSTEM "..\Include\XML\VoucherExtendFields.xml">
]>

<dir id="s623BQ3Select" table="" height="" fieldKey="id" voucherCode="BQ3" dirViewType="Dialog" readOnly="true" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Chi tiết báo giá được chọn" e="Quotation Entry Detail"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" readOnly="true" aliasName="@DFDFrom" disabled="true" allowBlank="false" dataType="D">
          <text v="Ngày c/từ từ/đến" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" allowBlank="false" disabled="true" inactivate="true" dataType="D" nextRow="false">
          <text v="Ngày đến" e="Voucher Date"></text>
        </field>
        <field name="ma_nt" hidden="true" label="1" field="1">
          <text v="Mã ngoại tệ" e="Ex Code"></text>
        </field>
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>
		<field name="ma_kh" format="U" label="1" disabled="true"  field="1" operation="like" >
          <text v="Mã khách hàng" e="Code"></text>
        </field>
		<field name="ten_kh" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		
		 <field name="ma_hang" viewType="Lookup" label="1" disabled="true" field="1" operation="like">
			<text v="Hãng tàu/ Đại lý" e="Carrier/ Agent Code"></text>
		</field>
		<field name="ten_hang" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		
        <field name="ma_noi_di" viewType="Lookup" label="1" disabled="true" field="1" operation="like">
			<text v="Nơi đi" e="Origin "></text>
			<viewInfo lookupType="One" lookupId="vdmcangdi" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_di" />
		</field>
		<field name="ten_noi_di" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="ma_noi_den" viewType="Lookup" disabled="true" label="1" field="1" operation="like">
			<text v="Nơi đến" e="Destination"></text>
			<viewInfo lookupType="One" lookupId="vdmcangden" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_den"  />
		</field>
		<field name="ten_noi_den" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>  
		
		 <field name="xprocess" label="1" field="2" valueDefault="2" viewType="Combobox">
          <text v="Xử lý" e="Process"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="Thêm vào chi tiết" e="Append To Detail"></text>
              </option>
              <option val="2">
                <text v="Xóa hết chi tiết và thêm mới" e="Delete All Detail And Append New"></text>
              </option>
            </options>
          </viewInfo>
        </field>
		<field name="id" dataType="N" hidden="true" fieldType="PK" label="1" field="1"  >
			  <text v="ID" e="Code"></text>
		</field>
      </fields>
    </form>
    <form tabPageIndex="1" gravity="MiddleLeft" height="350" columns="120,120,240" >
      <text v="Chi tiết" e="Detail"></text>
      <fields>
        <field name="v43" label="" field="-" viewType="Grid">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
  </forms>

 <grids>
    <grid id="v43" table="v43" fieldKey="id, line" order="id, line" allowFilter="true" readOnly="true" allowOrder="true">
      <fields>
        <field name="id" foreignField="id" dataType="N" fieldType="PK" format="0" copy="false" hidden="true">
          <text v="" e=""></text>
        </field>
        <field name="line" foreignField="@@ROW" dataType="I" fieldType="PK" hidden="true">
          <text v="Dòng" e="Line"></text>
        </field>
        <field name="ma_phi" width="80" allowBlank="false" viewType="Lookup" readOnly="false" >
          <text v="Mã phí" e="Fee"></text>
          <viewInfo lookupType="One" lookupId="dmphi" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_phi" lookupInfo="dmphi|ma_phi|ten_phi" />
        </field>
        <field name="ten_phi" width="200" fieldType="EX" inactivate="true" readOnly="true" aliasName="b" join=" left join dmphi b on a.ma_phi = b.ma_phi ">
          <text v="Tên phí" e="Fee Name"></text>
        </field>
		
         <field name="ma_dk_phi" viewType="Combobox" width="130" readOnly="false">
			<text v="Loại phí" e="Fee type"></text>
			<viewInfo>
				<options query="select ma_bgn, ten_bgn%l from dmbgn where ma_ct = 'LPH' and status = 1 order by stt">
				</options>
			</viewInfo>
		</field>	
		<field name="ma_dvt" width="80" allowBlank="true" viewType="Lookup" readOnly="false" >
          <text v="Đơn vị" e="Fee"></text>
          <viewInfo lookupType="One" lookupId="dmdvt" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_dvt" lookupInfo="dmdvt|dvt|ten_dvt" />
        </field>
        <field name="ten_dvt" width="0" fieldType="EX" inactivate="true" readOnly="true" aliasName="x" join=" left join dmdvt x on a.ma_dvt = x.dvt ">
          <text v="Tên đơn vị" e="Fee Name"></text>
        </field>	
        <field name="so_luong" dataType="N" format="Amount" width="100" readOnly="false" >
          <text v="Số lượng" e="Quantity"></text>
        </field>
        <field name="gia_nt1" dataType="N" hidden="false" format="FCPrice" width="100" readOnly="false"  >
          <text v="Giá mua " e=" Cost Price"></text>
        </field>
		 <field name="tien_nt1" dataType="N" hidden="false" format="FCAmount" width="100" valueDefault="0" readOnly="false" disabled="true" >
          <text v="Tiền mua" e="Cost Amount"></text>
        </field>
		 <field name="ma_nt" width="70" allowBlank="false" viewType="Lookup" readOnly="false" >
          <text v="Mã NT" e="Currency"></text>
          <viewInfo lookupType="One" lookupId="dmnt" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_nt" lookupInfo="dmnt|ma_nt|ten_nt" />
        </field>
		 <field name="ten_nt" width="0" fieldType="EX" inactivate="true" readOnly="true" aliasName="d" join=" left join dmnt d on a.ma_nt = d.ma_nt ">
          <text v="Tên phí" e="Fee Name"></text>
        </field>
		 <field name="ty_gia" dataType="N" format="Price" width="100" valueDefault="1" hidden="false" readOnly="false" >
          <text v="Tỷ giá" e="Curr.Rate"></text>
        </field>
		<field name="gia1" dataType="N" format="Price" width="100" hidden="true"  valueDefault="0" inactivate="true" readOnly="true" >
          <text v="Giá chuẩn" e="Std.Price"></text>
        </field>
		<field name="tien1" dataType="N" format="Amount" width="100" readOnly="false" >
          <text v="Chi phí" e="Total Cost"></text>
        </field>
		<field name="dien_giai" width="200" inactivate="true" readOnly="false">
          <text v="Diễn giải" e="Explain"></text>
        </field>
        <field name="line_bg" dataType="I" fieldType="PK" hidden="false" aliasName="a.line as ">
          <text v="Dòng BG" e="Quot. Line"></text>
        </field>
		<field name="id_bg" dataType="I" fieldType="PK" hidden="false" aliasName="a.id as ">
          <text v="Id BG" e="Quot. Id"></text>
        </field>
      </fields>

      <buttons>
        <button id="freeze">
          <text v="$FreezeToolbar" e="$FreezeToolbar"></text>
        </button>
      </buttons>

      <script>
        <query>
          <text>
            <![CDATA[<enc>n2ohD4FgLfMTK2Il3d/EqanApsIlOqo/TRhI8ZXirAMI/G/4ysyG+SVu80LjFL1h307l4ms2v2sGj3uITACQKYokgAOqahwpcwQ5mvQp2rr+u1OJPo4TKmVfC8AtqTAGDcbPcW9Kg+7Rmqw9xdS/rbtU67LKXkrCW4GOASDgy5RZFf9vDsmf//b6vWhp3DWPgwS+cCle8SUJmStX/vbG0rvFXzYWnK9ura+pTg89LQz3rfS1YpsOFSpHV50McRm7EuNopuTRYCR32UNWTs41YwuM0zszJNJNRkjUogzyxxrN8XNrEA2V8R9ROlKPReEMXFw+lKWxHsFMhaRukgdHLxqdMl6T3Rtf2WkMrHS0sfmUezFVbcRjFDS9hkPaYWFS</enc>]]>
          </text>
        </query>
      </script>

    </grid>
   
  </grids>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>l6YXouPCl+9YFRqCaCLgmJIvt6Dkr0edrNb/QHHig3kyQPSz6zHT6vGPwJTvV8ohRD7mybFU2CfmeIPWH0qJza1p45MjquYzvJ6EK8E0cy5IBxLtMRawOLzSY890dmhCdmYzTFI3V1MfEqu2U07hzRfr1EgJnseWEXzqXAfLIqBi4I+Q+sbCXuFXaGeGczCUvz6gNzZ3kvDytq00T9RHi73zKC7Ls+xg5cStUdONXLbfLr/dRGIKGz4FplbK5ooue4iyFpHACroK2wEhmsU18KIfs20VjCiUEYzualSBrh+brHptiJ2EAXgsHuIICEHXQ9oqRwsNK52AaJcATQBKLLfI0HHTPYvExeFTYe0Ez4DiZRNJllcHlG0w3U6BJB2EwkEGUh9q+Hz4KSrrjiQXn8R6fh/tbM9uDl2u1vpMJvQzEWOtkmhXjBF/3SJAn0amG5jQTzFNHIAhf/OKLy5d5E6WhYU2k1pKWnbUWjvGaQ+NHRHLQFoucOclPQ6qs1wqRSBszZfGCn7kqxrcO2o0wr62pkuluoR3/RqsYj/64M4KK0etbuEptTBSU14enmWORRmV4/IOuNrlM5dGKdHTxOYAxC0cxCCm3415Ih7SFmB1v+MrFO5zNic+pXoNJfc+1Ehii66TD6vzCObNO8sIpZWkkzcOSsp6/TazvXnHL9G9tOXml1jTQsJ9fuXhVS8Qtg0jupnGJdc/AQ67akmFBC3QgPqhjTPeTGNBpv0ZHr+9GAagMWRjwZvG7lBkLdnzugNFkHEDk9M5puSnZnevJA4dxC1PbQwYSh7pAKCzWEI=</enc>]]>
    </text>
  </js>
  
  <script>
		<request code="ma_kh_request">
			<text>
			  <![CDATA[<enc>n8gvfJy7FD5ZaP4aSpKsTDCbEaT9DZs7lnYhtVN27+lPRrdTXGVJnhSoGD92AjM9g/62JRgbC5YxfOoDb0CAjPnMelCSUPuIAz1aMGrjpcfSF1CXsyGaMl6QPLzBvnxgREr/Yf2/gNWFC4PE8obsPyRzj89NLuvaab22S0AnXIXNaJukhFPv2GswUxwzA3Hu/MdzP/p9s68iS0H34QgnTRzWEsA6E/zOdyGTtrjiaDlWRlkBBCQHjovxD/CmXQL6OFr6ENciYkV2lMWffZRX8Y8yQs6Nyp+ckKqV3K8LKLUwcnB4V2BfM3NcdkLw9J9X</enc>]]>
			</text>
		  </request>
    
  </script>
  
</dir>