<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="s623BQ3" fieldKey="id" voucherCode="BQ3" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc báo giá" e="Quotation Entry Filter"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" allowBlank="false" dataType="D">
          <text v="Ngày c/từ từ/đến" e="From Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" allowBlank="false" inactivate="true" dataType="D" nextRow="false">
          <text v="Ngày đến" e="To Date"></text>
        </field>
       
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>
		
        <field name="ma_noi_di" viewType="Lookup" disabled="false" label="1" field="1" operation="like">
			<text v="Nơi đi" e="Origin "></text>
			<viewInfo lookupType="One" lookupId="vdmcangdi" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_di" />
		</field>
		<field name="ten_noi_di" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="ma_noi_den" viewType="Lookup" label="1" field="1" operation="like">
			<text v="Nơi đến" e="Destination"></text>
			<viewInfo lookupType="One" lookupId="vdmcangden" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_den"  />
		</field>
		<field name="ten_noi_den" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>  
			
		 <field name="id_bg" label="1" field="1" allowBlank="false">
          <text v="Số báo giá" e="Get the order number"></text>
        </field>
      </fields>
    </form>
	
	
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>6zqcKTM+BlB9FgSJhQ+uJpAZBXvRSuWtg2eJqpbgW55UDLP5+yKbDJJJHtrkaEsXwA3R23Dw171p9JvYGPt6txDKjhRlNxxpyiREn1epjCL2WrnUJ4R+HU7r3zcGYzfKBpQKEVEIIFeTwCvr0swzfMl/CjN/wf6uUDRlb30yn6Sou2yXvEaSS29pvKviWJwMQUsBIq6NNq3nht4ZvRARM5IfUhFxjFBMTIh8RkXezUveGXKzM99AVtz3YBjhGHzGrsO+HT0p/48n+PRPG0U+zKdLlzC9vk+YA7i2H4f/ofhXuQZ6L9FvZwLF0tWMJreANrWp2NEq3cJuKUn1BCbyhlf5cjjH1KWrDmQbVLWdDboRu+MmOGkCYli5tyD2W/+kELfaXF7lxlNdoYLKpYJhnNKnqmiPAYI9cMsNmlLZGuKlqrE8fXY2ZkCtgkyg8W6OIcVLH2b+kQTXy85B9JkUjlTmmYeMllY1at2ScNOlbaTTCTPgdxoje4PZCbjvpcMDivha7gS1nKc5Ms9fqjezf9YSeLnXPRqKa+0qiIec3ZbCQZyye4ZufdiQcaOX+h1f71jt+u2JFCraEXdglaIrksebBiDnljdm6LSSSfH6aatlT7Mk0TyIY4+KHxP0+L/D</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>