<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="s623BN3" fieldKey="id" voucherCode="PM3" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc báo giá" e="Quotation Entry Filter"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" allowBlank="false" dataType="D">
          <text v="Ngày c/từ từ/đến" e="Date From"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" allowBlank="false" inactivate="true" dataType="D" nextRow="false">
          <text v="Ngày đến" e="Date To"></text>
        </field>
		<field name="ngay_ct" label="" field="1" allowBlank="false" inactivate="true"  hidden="true" dataType="D" nextRow="true">
          <text v="Ngày chứng từ" e="Voucher Date"></text>
        </field>
        <field name="ma_nt" hidden="true" label="1" field="1">
          <text v="Mã ngoại tệ" e="Ex Code"></text>
        </field>
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="ma_noi_di" viewType="Lookup" disabled="true" inactivate="true" label="1" field="1">
			<text v="Nơi đi" e="Origin "></text>
			<viewInfo lookupType="One" lookupId="vdmcangdi" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_di" />
		</field>
		<field name="ten_noi_di" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="ma_noi_den" viewType="Lookup" disabled="true" label="1" field="1" operation="like">
			<text v="Nơi đến" e="Destination"></text>
			<viewInfo lookupType="One" lookupId="vdmcangden" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_den"  />
		</field>
		<field name="ten_noi_den" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>  
		
		<field name="ma_hang" viewType="Lookup" disabled="true" inactivate="true" label="1" field="1">
          <text v="Mã hãng tàu" e=" Carriers"></text>
          <viewInfo lookupType="One" lookupId="dmhangtau" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_hang" />
        </field>
        <field name="ten_hang" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
		
		 <field name="t_tong_trong" label="1" field="1" dataType="N" disabled="false" readOnly="false" nextRow="true" format="FCAmount" >
          <text v="Tổng trọng lượng" e="Total Weight"></text>
        </field>
				
        <field name="so_ct" label="1" field="1" allowBlank="true" hidden="false" >
          <text v="Số báo giá" e="Quot. Number"></text>
        </field>
		
        <field name="ds_so_ct" nextRow="false" fieldType="EX" readOnly="true"   hidden="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
		<field name="id_dh" dataType="I"  readOnly="true" fieldType="PK" hidden="true" >
          <text v="Id dh" e="Request. Id"></text>
        </field>
      </fields>
    </form>
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>yyGU8eyCTKYVol5Tj3TX0ud3w9X1HnB81BkfDx7aqa1gc8ONgAVw0VRBA82nPXK4Xz2S8VlLOarPurH0frGLdYhG1wSVaMDCB6noMhjjrs6bOj7O5gMbNIdGl3HHHnFtRQFJRHJ5L3EX4NCBp872aSGVzGC9ubQu72DDemVkr5OKKBIWV104njacbgj68r/m7pVbq/5JWf6eEATX1Aw5t5JBAfiZ8JoRkWDgPYXLe1D9J4+A25QhaO7TZKOhV3yV6eafl8+YA1GESjpgwaaSXfB58S7ZtK6265rq9M32jWtbEazpQoHXqDbh828tD6vBi3Ulvj2X/TNKuqAJxeGZg0v1NAaP24OhHyx5hSCgfsbj70BZE9sgdiJyj+5Pi4jAKbS8kGYSHSSWTnGV3kR11gHCXkc46s1CvjgBPq9SGAJxtY6V6fQ66TCbGw9VaKcAUDspmcSsfaiZiWOU3zy1wHhPJAJK//0jVPhmQgjTN4Gq7BdhKxXF/Ol9b7jl+CsHqzvkOE+P+Ehju3/5XQWL+nZm/T1phrANfxwQhelsjfa1Yq5SZ2poc+ndFFSCbxge5O2EXle8jcgWSy8cmS8SIXaPdixw22W2oBv4ZwMkCo0=</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>