<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="s631BQ1" fieldKey="id" voucherCode="BQ1" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc báo giá" e="Quotation Entry Filter"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" allowBlank="false" dataType="D">
          <text v="Ngày c/từ từ/đến" e="From Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" allowBlank="false" inactivate="true" dataType="D" nextRow="false">
          <text v="Ngày đến" e="To Date"></text>
        </field>
       
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>
		
        <field name="ma_noi_di" viewType="Lookup" disabled="true" label="1" field="1" operation="like">
			<text v="Nơi đi" e="Origin "></text>
			<viewInfo lookupType="One" lookupId="vdmcangdi" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_di" />
		</field>
		<field name="ten_noi_di" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="ma_noi_den" viewType="Lookup" label="1" field="1" operation="like" disabled="true" >
			<text v="Nơi đến" e="Destination"></text>
			<viewInfo lookupType="One" lookupId="vdmcangden" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_den"  />
		</field>
		<field name="ten_noi_den" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>  
			
		 <field name="id_bg" label="1" field="1" allowBlank="false" disabled="true">
          <text v="Số báo giá" e="Get the order number"></text>
        </field>
      </fields>
    </form>
	
	
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>6zqcKTM+BlB9FgSJhQ+uJnJZ28hirv7XkMSb+3512cyorpiJK/gvBrdr34APBqK5GYBdSzlNCfCATVFpqhrvyYDlYi5/gP8vVm0ez6qbIXqSLQJvxzM5GxI/NzNmfeJRlNMFDCq4MJSErx25LuavPJ8YdO/rCaWgjsVDHXBBeVPk48TZG7ptR7FQn1QIVO3gLnrFH9hDlWoNrtELEBFOmjDqMLgV3MGLwaIpv/IbPs3BCvDhDdpVcRgaOt2Toz4fAZ8/QHBzExgME1K3WrEf5cn6UhxNBRjF8hXLQ2De0dxjUEsMDPkb7j7925sm/6+E9FPVLpWl08WKV5s4ne2yN6SOwiWyvn3xOy7lQG5ayiTwUSP6DUGVVwP1pXOgbl3toQb9tU1CcV1zhrk4DqrBe5SWbnNNCZZd9a1CAF4CvRVcqoH9Xwm+vsXKt2/kOA4g8QS8ixtZSbHGl2pTKtaSSzxVUuBHq0rhX0F82Qklqr0Rh6aPmPVbG9jB5Po55E8lIAOQYWrh4EoqW03UMlLjLC5UN3WwqxqiaAEQqWi9ZUYtGb7Vx6mrVyhjnTAARmo8kbp4c9UK4AiTfRuJhsUsbEIL4m3H+fKuLjJO1HYNmZ1hBA7GhomTJqZNvnJWAyKp</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>