<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
  <!ENTITY VoucherExtendFields SYSTEM "..\Include\XML\VoucherExtendFields.xml">
]>

<dir id="s631BN1Select" table="" height="" fieldKey="id" voucherCode="PB1" dirViewType="Dialog" readOnly="true" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Chi tiết báo giá được chọn" e="Quotation Entry Detail"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
	<field name="ngay_ct1" label="1" field="1" readOnly="true" aliasName="@DFDFrom" disabled="true" allowBlank="false" dataType="D">
          <text v="Ngày c/từ từ/đến" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" allowBlank="false" disabled="true" inactivate="true" dataType="D" nextRow="false">
          <text v="Ngày đến" e="Voucher Date"></text>
        </field>
		<field name="ngay_ct" label="" field="1" allowBlank="false" inactivate="true"  hidden="true" dataType="D" nextRow="true">
          <text v="Ngày chứng từ" e="Voucher Date"></text>
        </field>
        <field name="ma_nt" hidden="true" label="1" field="1">
          <text v="Mã ngoại tệ" e="Ex Code"></text>
        </field>
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>
		 <field name="ma_hang" viewType="Lookup" label="1" disabled="true" field="1" operation="like">
			<text v="Hãng tàu/ Đại lý" e="Carrier/ Agent Code"></text>
		</field>
		<field name="ten_hang" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		
        <field name="ma_noi_di" viewType="Lookup" label="1" disabled="true" field="1" operation="like">
			<text v="Nơi đi" e="Origin "></text>
			<viewInfo lookupType="One" lookupId="vdmcangdi" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_di" />
		</field>
		<field name="ten_noi_di" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="ma_noi_den" viewType="Lookup" disabled="true" label="1" field="1" operation="like">
			<text v="Nơi đến" e="Destination"></text>
			<viewInfo lookupType="One" lookupId="vdmcangden" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_den"  />
		</field>
		<field name="ten_noi_den" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>  
		
		<field name="ds_cong" allowBlank="false" disabled="true" label="1" field="-" hidden="false">
			  <text v="Container" e="Container List"></text>
		</field>
		 <field name="xprocess" label="1" field="2" valueDefault="2" viewType="Combobox">
          <text v="Xử lý" e="Process"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="Thêm vào chi tiết" e="Append To Detail"></text>
              </option>
              <option val="2">
                <text v="Xóa hết chi tiết và thêm mới" e="Delete All Detail And Append New"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      <field name="id" dataType="N" hidden="true" fieldType="PK" label="1" field="1"  >
          <text v="ID" e="Code"></text>
        </field>
      </fields>
    </form>
    <form tabPageIndex="1" gravity="MiddleLeft" height="350" columns="120,120,240" >
      <text v="Chi tiết" e="Detail"></text>
      <fields>
        <field name="v311" label="" field="-" viewType="Grid">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
  </forms>

 <grids>
    <grid id="v311" table="v311" fieldKey="id, line" order="id, line" allowFilter="true" readOnly="true" allowOrder="true">
      <fields>
        <field name="id" foreignField="id" dataType="N" fieldType="PK" format="0" copy="false" hidden="true">
          <text v="" e=""></text>
        </field>
        <field name="line" foreignField="@@ROW" dataType="I" fieldType="PK" hidden="true">
          <text v="Dòng" e="Line"></text>
        </field>
        <field name="ma_phi" width="80" allowBlank="false" viewType="Lookup" readOnly="false" >
          <text v="Mã phí" e="Fee"></text>
          <viewInfo lookupType="One" lookupId="dmphi" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_phi" lookupInfo="dmphi|ma_phi|ten_phi" />
        </field>
        <field name="ten_phi" width="200" fieldType="EX" inactivate="true" readOnly="true" aliasName="b" join=" left join dmphi b on a.ma_phi = b.ma_phi ">
          <text v="Tên phí" e="Fee Name"></text>
        </field>
		 <field name="ma_cong" width="100" allowBlank="false" viewType="Lookup" readOnly="false" >
          <text v="Container" e="Container"></text>
          <viewInfo lookupType="One" lookupId="dmcong" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_cong" lookupInfo="dmcong|ma_cong|ten_cong" />
        </field>
        <field name="ten_cong" width="0" fieldType="EX" inactivate="true" readOnly="true" aliasName="c" join=" left join dmcong c on a.ma_cong = c.ma_cong ">
          <text v="Container" e="Container Name"></text>
        </field>
         <field name="ma_dk_phi" viewType="Combobox" width="130" readOnly="false">
			<text v="Loại phí" e="Fee type"></text>
			<viewInfo>
				<options query="select ma_bgn, ten_bgn%l from dmbgn where ma_ct = 'LPH' and status = 1 order by stt">
				</options>
			</viewInfo>
		</field>
		<field name="ma_dvt" width="80" allowBlank="true" viewType="Lookup" readOnly="false" >
          <text v="Đơn vị" e="Fee"></text>
          <viewInfo lookupType="One" lookupId="dmdvt" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_dvt" lookupInfo="dmdvt|dvt|ten_dvt" />
        </field>		
        <field name="so_luong" dataType="N" format="Amount" width="100" readOnly="false" >
          <text v="Số lượng" e="Quantity"></text>
        </field>
		<field name="gia_nt2" dataType="N" format="FCPrice" width="100" readOnly="false" hidden="false" >
          <text v="Giá bán" e="Bill Price"></text>
        </field>
        <field name="tien_nt2" dataType="N" hidden="false" format="FCAmount" width="100" valueDefault="0" readOnly="false" disabled="true">
          <text v="Tiền bán" e="Bill Amount"></text>
        </field>
		 <field name="ma_nt" width="70" allowBlank="false" viewType="Lookup" readOnly="false" >
          <text v="Mã NT" e="Currency"></text>
          <viewInfo lookupType="One" lookupId="dmnt" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_nt" lookupInfo="dmnt|ma_nt|ten_nt" />
        </field>
		 <field name="ten_nt" width="0" fieldType="EX" inactivate="true" readOnly="true" aliasName="d" join=" left join dmnt d on a.ma_nt = d.ma_nt ">
          <text v="Tên phí" e="Fee Name"></text>
        </field>
		 <field name="ty_gia" dataType="N" format="Price" width="100" valueDefault="1" hidden="false" readOnly="false" >
          <text v="Tỷ giá" e="Curr.Rate"></text>
        </field>
		<field name="gia2" dataType="N" format="Price" width="100" hidden="true"  valueDefault="0" inactivate="true" readOnly="true" >
          <text v="Giá chuẩn" e="Std.Price"></text>
        </field>
		<field name="tien2" dataType="N" format="Amount" width="100" readOnly="false" >
          <text v="Chi phí" e="Total Cost"></text>
        </field>
		<field name="dien_giai" width="200" inactivate="true" readOnly="false">
          <text v="Diễn giải" e="Explain"></text>
        </field>
      </fields>

      <buttons>
        <button id="freeze">
          <text v="$FreezeToolbar" e="$FreezeToolbar"></text>
        </button>
      </buttons>

      <script>
        <query>
          <text>
            <![CDATA[<enc>3aOwJYOgvWxsrXNbyuQv3DDIbg4R9stWzWFHscuAhCUP/MmvMG05TOYJwRqnmn4wLYnrOsN0aP/RK4S3WgLKWER+zUb7z3tc9wXOKffCgDyv0kOhNGOrGT2K45vA/NAOqBuA12i5CsaD5rcLVOWRAzolkoYI4giivVk7vTZEvneEqfSx4wIYXFafyw6Wdfq1IuyOmPLFL9JQfsBsg2Lrd1+c3q/kZgxLFXRSWl5y6bi886dvxQaLA6pZOTONSkcfbPw+wBH6bCWLWkCwjQ5bYg==</enc>]]>
          </text>
        </query>
      </script>

    </grid>
   
  </grids>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>+/mjqyKhGDW0BWe8Jhza6gUL+p7ITGHtgoxCN6TbmzFRt9JLsDpfA8wwcwW4TEHWusWp1Y0GGw6N5tJ+20XUYvRahZDHyVbpdyG8y2Mty6KVKMecwmsVxR6rhj4KEgrTNvi5auuiFbM1KrsNtyeUC6l8MzFIBfT2/3sOgjqSpJjLH8h86uWsF99OAS7N8PCHpCeCxYTQ/e22StpuNerKOPx6cY399CIuaqq1jKzs7l+c9mjrFCfXkkKajvVuQ+ioODZbJKMQ7cQzuQHayb0yGLp9VKGKsj/wFvzfzW9DMo7D9tD0a2Gg25p9awsXnrVkb2QldTJpydtQ9DdvZ/IOMnTxVACuVn4OFIeLUgGWmHTljDlHhIjZy5DS9kXhRGAAiuUugwfvm5HbAvyD6RvIYESJeHf/9jrkaNE5aIXkE+Fe4qePQx6m+ufjRxQkL5u+S/9dg8keWZ2AUGT+1KEG0YwYkR8l99Jf+vODR6IEtvNA0bf+BzxxMAHg1Hxwe3A8VmJXBPK3cNwYC99+kCCxXuxMefF+q24cSy7C2ja3bo1op7m1gCgRvF7l4lrJibE9LmY3Yd2gRi5gSgKDKvU3cFfNTIJZmlqkaNdsqXZNpuql13/moOKhlfRkKvrWBwZzGlY0ZB/KdJn5yXYI0y015aLqiVJgefOHV4qqqgfxovIfJR3WJiy5nJ6j0Eq+7715oFOTd/b4SzIiFlAgsFopBwZY7ZBk1CiU6Rw/S6idnhXwDjAqE6njMWCrSgLH1GJ9z5qzjVU4qmfDd5ZjF0bvd5qeu1w+PYCA1+pTPt0LVyi0m4gAVjIb81sjNcfgqSFPo2lViK3bL4NQLCcSD9i6GBLmdgbpyF5qMOAn03rDdt1Q0Sj+f/zEKVJt/dCOhqU2R2zFxOZr+6gP0CnaqGVX5Q==</enc>]]>
    </text>
  </js>
  
  <script>
		<request code="ma_kh_request">
			<text>
			  <![CDATA[<enc>p8Jv6giswZ7gKMwflAwRnNif0NFIzu3ucm4CBKpYIP0=</enc>]]>
			</text>
		  </request>
    
  </script>
  
</dir>