<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="s631BQ1" fieldKey="id" voucherCode="PB1" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc đơn hàng FCL" e="Quotation Entry Filter"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D">
          <text v="Ngày từ/đến" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" aliasName="@DFDTo" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D" nextRow="false">
          <text v="" e=""></text>
        </field>
       
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="ma_noi_di" viewType="Lookup" disabled="false" label="1" field="1" operation="like">
			<text v="Nơi đi" e="Origin "></text>
			<viewInfo lookupType="One" lookupId="vdmcangdi" lookupKey="(kkh_yn = 1 or hc_yn = 1) and status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_di" />
		</field>
		<field name="ten_noi_di" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="ma_noi_den" viewType="Lookup" label="1" field="1" operation="like">
			<text v="Nơi đến" e="Destination"></text>
			<viewInfo lookupType="One" lookupId="vdmcangden" lookupKey="(kkh_yn = 1 or hc_yn = 1) and status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_den"  />
		</field>
		<field name="ten_noi_den" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>	
		 <field name="so_ct" label="1" field="1" allowBlank="false" viewType="Lookup" operation="like">
          <text v="Lấy số đơn hàng" e="Get the order number"></text>
          <viewInfo lookupType="one" lookupId="s611" lookupRef="ds_so_dh" lookupKey="ngay_ct between ![ngay_ct1]! and ![ngay_ct2]! and ma_noi_di like ![ma_noi_di]! +'%' and ma_noi_den like ![ma_noi_den]! +'%'" lookupCheck="ma_noi_di like ![ma_noi_di]! and ma_noi_den like ![ma_noi_den]!  and status in (5,6)" />
        </field>
        <field name="ds_so_dh" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>	
      </fields>
    </form>
	
	
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>vH0l48A3Ncctxxn5OOGN+lSis0hlXyPT/kI3dVfpoTe44TZpb/bI5aVoVhQghSkrAcH3048Ah9XyFPBO2L9erhbMfPEBR522a7zTYeef0T66rXWUygds9HzI7rJf0I3Y+7jh2zNGdUr4ej3YouN1vDPYu96YPKKNd5cR+JCSSKyvYQZlzJprA5mID4yY2Xxp1Bz+RQzDoYHEwE83AtXjEKzxynSzgNMEEvAkIEXfmnMRSfBHguHlBuSC5us8YzwtjuKxZyRO1bRQ/9yKzOvUcgI5edk9XeEPComT3Nl+FMo8Fb75/HPO+XFcvGrktNLjIzVxX8TVWAoIOA508XkyD45yTAox5cWBx1XPfMytx3DOEgvg1lmVwU/OnjOoK2oow7Z5m9jf/doEtopFzjaT/9rMg9BD7Kby9uRXxMxZGngWvIsNocaQ9lZXk+z07BUQa7MofJz0WsbYtd9FmTbinO9R1bu6/K2p1oHCZ2kD6gN4mwIcJAmLeQF3NbZJuNWQIdFp0bW3olHkUKvgWcVGBwmnA4pYzLl3yKc9tPAcOOhW388aOI8N8gdyiZn1q87d</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>