<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="s632BQ2" fieldKey="id" voucherCode="BQ2" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc báo giá" e="Quotation Entry Filter"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" allowBlank="false" dataType="D">
          <text v="Ngày c/từ từ/đến" e="From Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" allowBlank="false" inactivate="true" dataType="D" nextRow="false">
          <text v="Ngày đến" e="To Date"></text>
        </field>
       
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>
		
        <field name="ma_noi_di" viewType="Lookup" disabled="true" label="1" field="1" operation="like">
			<text v="Nơi đi" e="Origin "></text>
			<viewInfo lookupType="One" lookupId="vdmcangdi" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_di" />
		</field>
		<field name="ten_noi_di" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="ma_noi_den" viewType="Lookup" disabled="true" label="1" field="1" operation="like">
			<text v="Nơi đến" e="Destination"></text>
			<viewInfo lookupType="One" lookupId="vdmcangden" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_den"  />
		</field>
		<field name="ten_noi_den" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>  
			
		 <field name="id_bg" label="1" field="1" disabled="true" allowBlank="false">
          <text v="Số báo giá" e="Get the order number"></text>
        </field>
      </fields>
    </form>
	
	
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>6zqcKTM+BlB9FgSJhQ+uJsb2DL/IU7v5Fmom3MVUARM1ZtTxTFcrGxMO4NJhiTJkyMtE5OWWzS8Gqic/4JRfiLkdusgkRqyYIL9SO/NU2/gE4fJtCHYuS3nAfesIQplOyZM6EGh+QdE7Qx5CADpZmdamSCu6ZuueXaDTqvtma2gSEFE6b0eII7If3lXjhnZJLZYo/vzTvhLvSRBYy8urHJOGCo1o7wEx5CQrAEmJsD68bm0L94JwTzWqtlLJlzDGtMQ2sUEJ98JgqIAsdDtnOKb8q+d9CIqm4OgKWRihfl/K/sZOzUmRIwt9QuIg5L9vQeIv9tqc3E/AWAT9iteInZsVc3yUNPlK0cELjlZC3uVpe6qofL8+arTtlBphLsbQnBCmHhg9WPx3beyMwwH0rSNxD2xz1WDWwpMLUAsHygcXIIyaXt3rh0MQJVmQzXPaTz+N0Fy4PxEspXvWJiCg6iJxdArG8fZ0Jcsd3k/9W4yyWg8d7Y468rjgvRtDAClsUo2R7ZpvI38pt3vGzdXJ4bG2YLlDbcpB/tv9XOTRvXnnNlJJHk13q6wKTxcAUTTagYIYybUAT0da5P0t6AatfX8ZFlfJ6S9Nvsaax8ta8bZMIupylF5NAiGgYElgoo49</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>