<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="s632BN2" fieldKey="id" voucherCode="PB2" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc báo giá" e="Quotation Entry Filter"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" allowBlank="false" dataType="D">
          <text v="Ngày c/từ từ/đến" e="Date From"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" allowBlank="false" inactivate="true" dataType="D" nextRow="false">
          <text v="Ngày đến" e="Date To"></text>
        </field>
		<field name="ngay_ct" label="" field="1" allowBlank="false" inactivate="true"  hidden="true" dataType="D" nextRow="true">
          <text v="Ngày chứng từ" e="Voucher Date"></text>
        </field>
        <field name="ma_nt" hidden="true" label="1" field="1">
          <text v="Mã ngoại tệ" e="Ex Code"></text>
        </field>
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="ma_noi_di" viewType="Lookup" disabled="true" inactivate="true" label="1" field="1">
			<text v="Nơi đi" e="Origin "></text>
			<viewInfo lookupType="One" lookupId="vdmcangdi" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_di" />
		</field>
		<field name="ten_noi_di" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="ma_noi_den" viewType="Lookup" disabled="true" label="1" field="1" operation="like">
			<text v="Nơi đến" e="Destination"></text>
			<viewInfo lookupType="One" lookupId="vdmcangden" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_den"  />
		</field>
		<field name="ten_noi_den" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>  
		
		<field name="ma_hang" viewType="Lookup" disabled="true" inactivate="true" label="1" field="1">
          <text v="Mã hãng tàu" e=" Carriers"></text>
          <viewInfo lookupType="One" lookupId="dmhangtau" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_hang" />
        </field>
        <field name="ten_hang" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
		
		 <field name="t_tong_trong" label="1" field="1" dataType="N" disabled="false" readOnly="false" nextRow="true" format="FCAmount" >
          <text v="Tổng trọng lượng" e="Total Weight"></text>
        </field>
		<field name="t_tong_khoi" label="1" field="1" dataType="N" disabled="false" readOnly="false" nextRow="true" format="FCAmount" >
          <text v="Tổng Volume" e="Total Volume"></text>
        </field>
				
        <field name="so_ct" label="1" field="1" allowBlank="true" hidden="false" >
          <text v="Số báo giá" e="Quot. Number"></text>
        </field>
		
        <field name="ds_so_ct" nextRow="false" fieldType="EX" readOnly="true"   hidden="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
		<field name="id_dh" dataType="I"  readOnly="true" fieldType="PK" hidden="true" >
          <text v="Id dh" e="Request. Id"></text>
        </field>
      </fields>
    </form>
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>WXgbm8uhT1/7/YUh0Gp8UyQ++E2v1TZhxvegDaQEnzxkFkyXZvD2RwPFsfmzv1/OV5JDWBgeFPi5UJfvnmUMxqS8cncI7T3A+yE1R/gfSv3RDnLNzY/mIWr+VM+vo62IYPytifrRT5AHXGywmHN4RRPLC6N3uqCSYmtK6aHW9zSkRcoSrGfXUaNqQM2OdLUvJ3mqXvgy00TqAjy2eBKG789F7FG3AqhD5RhOCSDcGvEyr0GgRWa8hBSqcMJiE/W6Xnp2PWKvKwMBa2YyD/etx389m83YK01blxTKb6vu9po5t+dgNPMdlfEPslAUTec+so8QP3lk/GvPXQKVzcs9rjMld813Fcgw9gBY18GBEc3Acd0whlQk43b+9+6mt9WHXj5lRSau9IKckfSIoIGpZHNqToCAxhk1w6MgRSUpTme6mxvVJx4sqnAYYv5aP+c6L5kgjEFmvZFu4rxKYvZIwaCXHkcnyrkBJ41ClTEc1QbrpIP+xkaI8Xr3cMVikK7GSRSFxraZSaZllX0RkejzUihGjEPZgvlYL28xPnYc0v9u8WaPnnSEsmhnTj9rK+oyAPtWcn5w/To0Tt2q1RRwHsuFNes9xcbRYSVcaxSzGaHPOeuJS0c/SjQ78XOJdtFp</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>