<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="s633CR3" fieldKey="id" voucherCode="CR3" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc báo giá" e="Quotation Entry Filter"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D">
          <text v="Ngày từ/đến" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" aliasName="@DFDTo" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D" nextRow="false">
          <text v="" e=""></text>
        </field>
       
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="ma_noi_di" viewType="Lookup" disabled="false" label="1" field="1" operation="like">
			<text v="Nơi đi" e="Origin "></text>
			<viewInfo lookupType="One" lookupId="vdmcangdi" lookupKey="(kkh_yn = 1 or hc_yn = 1) and status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_di" />
		</field>
		<field name="ten_noi_di" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="ma_noi_den" viewType="Lookup" label="1" field="1" operation="like">
			<text v="Nơi đến" e="Destination"></text>
			<viewInfo lookupType="One" lookupId="vdmcangden" lookupKey="(kkh_yn = 1 or hc_yn = 1) and status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_den"  />
		</field>
		<field name="ten_noi_den" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>	
		 <field name="so_ct" label="1" field="1" allowBlank="false" viewType="Lookup" operation="like">
          <text v="Lấy số đơn hàng" e="Get the order number"></text>
          <viewInfo lookupType="one" lookupId="s613" lookupRef="ds_so_dh" lookupKey="ngay_ct between ![ngay_ct1]! and ![ngay_ct2]! and ma_noi_di like ![ma_noi_di]! +'%' and ma_noi_den like ![ma_noi_den]! +'%'" lookupCheck="ma_noi_di like ![ma_noi_di]! and ma_noi_den like ![ma_noi_den]!  and status in (5,6)" />
        </field>
        <field name="ds_so_dh" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>	
      </fields>
    </form>
	
	
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>7dnUqIuxukLuRCTGhnr/Wek3t6wnvfsoDVWIMYfdWZlpzveod3PcNdjp07Dnekb3Q2hz30fhQPz1WkPT6Bmn2UvYqhiYQo+knTDdMDJ0lSMdBDRJaUxb1tjQfpIn7FTXjbX8NcaHqX26fNCioLmxC355yVmn4HgvKKxd7WL//3HX3WUXpd7gA1wy8NaOJI86CFwT/UG2vqvpuKV9nDvHBb2HWfxHXgeB++/vihxBRNd58+brjlsEk3Xz8pOKhQQjqNYVanimd7DD6n+grI/2lJxLIouEM0HF7LtiaEkic8HfatDohwpQoceS6P3L9i6Y4qAIva97iiMZbSju1aD4ik03AIPg8KYR1L5essjHnKcaDWEIgPgp43VADX8mKX3XSSFlNbpb3b8+UJXm3D8iQO8eCJBovpm6sq1ujWhO/JVSnBQIikIC9qvDYmTKWNF6KXu9C21rH4a163f0ZT5MDYnznqCwG0GkWMxFo05F+K64Iv1HNMDJJDBE8rlSh+0xvrWn81rpH+ijnpkFe2kbvv0nCvEbFYa2QRrmdKbHiU0ouV2B/sX4qxZ1dQKyR5E2</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>