<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="s633BQ3" fieldKey="id" voucherCode="BQ3" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc báo giá" e="Quotation Entry Filter"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" allowBlank="false" dataType="D">
          <text v="Ngày c/từ từ/đến" e="From Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" allowBlank="false" inactivate="true" dataType="D" nextRow="false">
          <text v="Ngày đến" e="To Date"></text>
        </field>
       
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>
		
        <field name="ma_noi_di" viewType="Lookup" disabled="true" label="1" field="1" operation="like">
			<text v="Nơi đi" e="Origin "></text>
			<viewInfo lookupType="One" lookupId="vdmcangdi" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_di" />
		</field>
		<field name="ten_noi_di" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="ma_noi_den" viewType="Lookup" label="1" disabled="true"  field="1" operation="like">
			<text v="Nơi đến" e="Destination"></text>
			<viewInfo lookupType="One" lookupId="vdmcangden" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_den"  />
		</field>
		<field name="ten_noi_den" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>  
			
		 <field name="id_bg" label="1" field="1" disabled="true"  allowBlank="false">
          <text v="Số báo giá" e="Get the order number"></text>
        </field>
      </fields>
    </form>
	
	
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>w6H/9c5cxGbCk2oeo1B3urAZXvydUPcgjyEOGKCXIXc2R218Al/bBZaIcHnZH7uDRtLMGO+8IvKux3dLUUltSdLJ/BV6bwIozmUxkfnMYrim3hDVJ9VyKiUFQH5ojqpkZhSc+0nFA3uAS5TDq+0Qp8Hz0YZJ/dWNTy6Gg98UTNBjTt/2/zSSdGOX29weq/etxeFCgAmNi7hvm5WKDotWk/OkdSGhh4yJI/JUy9MpMavPsTjdWAwoWyCVbbgqLVuVyWmdJ/zhTT6XRALbbEJR+qAoiwFLhE/SB+kR/D+EVAckueeqs1hxQUqxHS0IuSqdAUrdUSMjBJ66lyTy9m2wOA8x/fJb4QD6e3PF1BZokd662qg/zu4tn4cRnuAbtg+Ux4XCJUXwZLGjcBGc2n5MisLF/9H0Wy8p5CC66VVJCMDn7OA0OpMbNCU9PtYFlW3EeAj+uJBUDSG8O2KURnhOdS/gY+wUJhApheFhIRdQXxR+krV+T9dP7usWBghKJteafaQKreHQN4DAOwPa10UFh8/IDb0WCv+pjcZDVJrfqU3jwr2Ilwr0iEHtQUzztMqDiVru4ni3cKeKjvaksgCTaKBiFEqqxb3rreqwxRqf+LXNf3b+V66MEWgi5Q6uq5Au</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>