<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
  <!ENTITY VoucherExtendFields SYSTEM "..\Include\XML\VoucherExtendFields.xml">
]>

<dir id="s642CR2Select" table="" height="" fieldKey="id" voucherCode="CR2" dirViewType="Dialog" readOnly="true" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Chi tiết báo giá được chọn" e="Quotation Entry Detail"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" readOnly="true" aliasName="@DFDFrom" disabled="true" allowBlank="false" dataType="D">
          <text v="Ngày c/từ từ/đến" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" allowBlank="false" disabled="true" inactivate="true" dataType="D" nextRow="false">
          <text v="Ngày đến" e="Voucher Date"></text>
        </field>
        <field name="ma_nt" hidden="true" label="1" field="1">
          <text v="Mã ngoại tệ" e="Ex Code"></text>
        </field>
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>	
		<field name="ma_nv" format="U" label="1" disabled="true"  field="1" operation="like" >
          <text v="Mã nhân viên" e="Code Employee"></text>
        </field>
		<field name="ten_nv" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="ma_kh" format="U" label="1" disabled="true"  field="1" operation="like" >
          <text v="Mã khách hàng" e="Code"></text>
        </field>
		<field name="ten_kh" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		 <field name="ma_hang" viewType="Lookup" label="1" disabled="true" field="1" operation="like">
			<text v="Hãng tàu/ Đại lý" e="Carrier/ Agent Code"></text>
		</field>
		<field name="ten_hang" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="t_tong_trong" label="1" field="1" dataType="N" disabled="true" nextRow="true" format="FCAmount" >
          <text v="Tổng trọng lượng" e="Total Weight"></text>
        </field>
		
		<field name="t_tong_khoi" label="1" field="1" dataType="N" disabled="true" nextRow="true" format="FCAmount" >
          <text v="Tổng Volume" e="Total Volume"></text>
        </field>
        <field name="ma_noi_di" viewType="Lookup" label="1" disabled="true" field="1" operation="like">
			<text v="Nơi đi" e="Origin "></text>
			<viewInfo lookupType="One" lookupId="vdmcangdi" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_di" />
		</field>
		<field name="ten_noi_di" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="ma_noi_den" viewType="Lookup" disabled="true" label="1" field="1" operation="like">
			<text v="Nơi đến" e="Destination"></text>
			<viewInfo lookupType="One" lookupId="vdmcangden" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_den"  />
		</field>
		<field name="ten_noi_den" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>  
		<field name="so_ct" label="1" field="1" disabled="true" hidden="true">
          <text v="Số báo giá" e="Quot. Number"></text>
        </field>
		<field name="dien_giai" label="1" rows="1" field="-" disabled="true">
		  <text v="Diễn giải" e="Explain"></text>
		</field>
		<field name="id" dataType="N" hidden="true" fieldType="PK" label="1" field="1"  >
			  <text v="ID" e="Code"></text>
		</field>
      </fields>
    </form>
    <form tabPageIndex="1" gravity="MiddleLeft" height="350" columns="120,120,240" >
      <text v="Chi tiết" e="Detail"></text>
      <fields>
        <field name="v612" label="" field="-" viewType="Grid">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
  </forms>

 <grids>
    <grid id="v612" table="v612" fieldKey="id, line" order="id, line" allowFilter="true" readOnly="true" allowOrder="true">
      <fields>
        <field name="id" foreignField="id" dataType="N" fieldType="PK" format="0" copy="false" hidden="true">
          <text v="" e=""></text>
        </field>
        <field name="line" foreignField="@@ROW" dataType="I" fieldType="PK" hidden="true">
          <text v="Dòng" e="Line"></text>
        </field>

        <field name="ma_phi" width="80" allowBlank="false" viewType="Lookup" readOnly="false" hidden="true" >
          <text v="Mã phí" e="Fee"></text>
          <viewInfo lookupType="One" lookupId="dmphi" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_phi" lookupInfo="dmphi|ma_phi|ten_phi" />
        </field>
        <field name="ten_phi" width="200" fieldType="EX" inactivate="true" readOnly="true" hidden="true" aliasName="b" join=" left join dmphi b on a.ma_phi = b.ma_phi ">
          <text v="Tên phí" e="Fee Name"></text>
        </field>
		<field name="ma_kien" width="100" allowBlank="false" viewType="Lookup" readOnly="false" hidden="false"  >
          <text v="Mã kiện" e="Package Code"></text>
          <viewInfo lookupType="One" lookupId="dmkien" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_kien" lookupInfo="dmkien|ma_kien|ten_kien" />
        </field>
        <field name="ten_kien" width="120" fieldType="EX" inactivate="true" readOnly="true" aliasName="k" join=" left join dmkien k on a.ma_kien = k.ma_kien " hidden="false" >
          <text v="Tên kiện" e="Package Name"></text>
        </field>
         <field name="ma_dk_phi" viewType="Combobox" width="130" readOnly="false" hidden="true">
			<text v="Loại phí" e="Fee type"></text>
			<viewInfo>
				<options query="select ma_bgn, ten_bgn%l from dmbgn where ma_ct = 'LPH' and status = 1 order by stt">
				</options>
			</viewInfo>
		</field>	
		
        <field name="so_luong" dataType="N" format="Amount" allowBlank="false" valueDefault="1" width="100" readOnly="false" >
          <text v="Số lượng" e="Quantity"></text>
        </field>
		<field name="ty_trong" dataType="N" format="FCPrice" width="120" readOnly="false" >
          <text v="Trọng lượng(KGS)" e="Gross Weight(KGS)"></text>
        </field>
		 <field name="tong_trong" dataType="N" inactivate="true" format="FCPrice" readOnly="false" disabled="true" width="120">
          <text v="Tổng trọng lượng (KGS)" e="Total Gross Weight(KGS)"></text>
        </field>
		<field name="ty_khoi" dataType="N" format="FCPrice" width="120" readOnly="false" >
          <text v="Volume(CBM)" e="Volume(CBM)"></text>
        </field>
		<field name="tong_khoi" dataType="N" inactivate="true" format="FCPrice"   readOnly="false" disabled="true" width="120">
          <text v="Tổng Volume" e="Total Volume"></text>
        </field>
		<field name="hs_code" width="150" valueDefault="0" readOnly="false" >
          <text v="HS Code" e="Quantity"></text>
        </field>	
        <field name="ct_km" width="100" valueDefault="0" viewType="Combobox" inactivate="true" hidden="true" readOnly="false" >
          <text v="Loại hàng" e="Fee Type"></text>
          <viewInfo>
            <options>
              <option val="0">
                <text v="Hàng bán" e="Sale"/>
              </option>
              <option val="1">
                <text v="Hàng KM" e="Promotion"/>
              </option>
            </options>
          </viewInfo>
        </field>
        <field name="gia_nt1" dataType="N" hidden="true" format="FCPrice" width="100" readOnly="false"  >
          <text v="Giá mua " e=" Cost Price"></text>
        </field>
        
		 <field name="tien_nt1" dataType="N" hidden="true" format="FCAmount" width="100" valueDefault="0" readOnly="false" disabled="true" >
          <text v="Tiền mua" e="Cost Amount"></text>
        </field>
		
		<field name="gia_nt2" dataType="N" format="FCPrice" width="100" readOnly="false" hidden="true" >
          <text v="Giá bán" e="Bill Price"></text>
        </field>
        <field name="tien_nt2" dataType="N" format="FCAmount" valueDefault="0" width="100" readOnly="true" hidden="true"  >
          <text v="Tiền bán" e="Bill Amount"></text>
        </field>
        <field name="tl_ck" dataType="N" format="Rate" width="100" hidden="true" readOnly="false" >
          <text v="Tl ck(%)" e="Dis.Rate"></text>
        </field>
        <field name="ck_nt" dataType="N" format="FCAmount" width="100" hidden="true" readOnly="false" clientDefault="true" >
          <text v="Ch.khấu " e=" Discount"></text>
        </field>
		 <field name="ma_nt" width="70" allowBlank="true" viewType="Lookup" readOnly="false" hidden="true" >
          <text v="Mã NT" e="Currency"></text>
          <viewInfo lookupType="One" lookupId="dmnt" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_nt" lookupInfo="dmnt|ma_nt|ten_nt" />
        </field>
		 <field name="ten_nt" width="0" fieldType="EX" inactivate="true" readOnly="true" aliasName="d" join=" left join dmnt d on a.ma_nt = d.ma_nt ">
          <text v="Tên phí" e="Fee Name"></text>
        </field>
		 <field name="ty_gia" dataType="N" format="Price" width="100" valueDefault="1" hidden="true" readOnly="false" >
          <text v="Tỷ giá" e="Curr.Rate"></text>
        </field>
        
        <field name="gia1" dataType="N" format="Price" width="100" hidden="true"  valueDefault="0" inactivate="true" readOnly="true" >
          <text v="Giá chuẩn" e="Std.Price"></text>
        </field>
        <field name="gia2" dataType="N" format="Price" width="0" inactivate="true" valueDefault="0" readOnly="true" >
          <text v="Giá bán" e="Price"></text>
        </field>
		 <field name="tien1" dataType="N" format="Amount" width="100" hidden="true" inactivate="true"  valueDefault="0" readOnly="false" disabled="true" >
          <text v="Chi phí" e="Total Cost"></text>
        </field>
        <field name="tien2" dataType="N" format="Amount" width="100" hidden="true" inactivate="true" valueDefault="0" readOnly="true" >
          <text v="Doanh thu" e="Total Bill"></text>
        </field>
		
        <field name="ck" dataType="N" format="Amount" width="100" inactivate="true" hidden="true" readOnly="false">
          <text v="Chiết khấu" e="Discount"></text>
        </field>
		<field name="thue_suat" dataType="N" format="0" width="60" readOnly="false"  valueDefault="0" hidden="true" clientDefault="true" >
          <text v="VAT(%)" e="Tax"></text>
        </field>
        <field name="thue_nt" dataType="N" format="FCAmount" width="100" hidden="true" readOnly="true">
          <text v="Thuế %s" e="%s Tax"></text>
        </field>
        <field name="thue" dataType="N" format="Amount" width="100" inactivate="true" hidden="true" readOnly="true">
          <text v="Thuế" e="Tax"></text>
        </field>
		<field name="tc_tien2" dataType="N" format="Amount" width="100" hidden="true" valueDefault="0" inactivate="false" readOnly="true" >
          <text v="" e="Total"></text>
        </field>
		<field name="tc_tien_nt2" dataType="N" format="Amount" width="100" hidden="true" valueDefault="0" inactivate="false" readOnly="true" >
          <text v="" e="Total "></text>
        </field>
		
		<field name="tt" dataType="N" format="Amount" width="100" hidden="true" valueDefault="0" inactivate="false" readOnly="true" >
          <text v="Tổng cộng" e="Total"></text>
        </field>
		<field name="tt_nt" dataType="N" format="Amount" width="100" hidden="true" inactivate="false" readOnly="true" >
          <text v="" e="Total "></text>
        </field>
		<field name="tien_ln" dataType="N" format="Amount" width="100" inactivate="false" hidden="true" valueDefault="0" readOnly="false" disabled="true" >
          <text v="Lợi nhuận" e="Profit"></text>
        </field>
		<field name="dien_giai" width="200" inactivate="false" readOnly="false">
          <text v="Diễn giải" e="Explain"></text>
        </field>
		<field name="id_bg" dataType="N" inactivate="true" hidden="true" format="0" width="80" copy="false">
          <text v="ID BG" e="ID BG"></text>
        </field>
        <field name="so_ct_bg" width="100" fieldType="EX" copy="false" readOnly="true" hidden="true" inactivate="true" link="v41|id_bg as id" aliasName="cast('' as nvarchar(3000)) as ">
          <text v="Số báo giá" e="Quot. No."></text>
        </field>
        <field name="line_bg" dataType="I" width="70" copy="false" hidden="true" inactivate="true">
          <text v="Dòng BG" e="Quot. Line"></text>
        </field>
		<field name="id_tg" dataType="N" inactivate="true" hidden="true" format="0" width="80" copy="false">
          <text v="ID TG" e="ID BG"></text>
        </field>
        <field name="so_ct_tg" width="100" fieldType="EX" copy="false" readOnly="true" hidden="true" inactivate="true" link="v51|id_tg as id" aliasName="cast('' as nvarchar(3000)) as ">
          <text v="Số báo giá" e="Quot. No."></text>
        </field>
        <field name="line_tg" dataType="I" width="70" copy="false" hidden="true" inactivate="true">
          <text v="Dòng TG" e="Quot. Line"></text>
        </field>
      </fields>

      <buttons>
        <button id="freeze">
          <text v="$FreezeToolbar" e="$FreezeToolbar"></text>
        </button>
      </buttons>

      <script>
        <query>
          <text>
            <![CDATA[<enc>V8jL8O6o25SZvpyQeujkrTWcy22a909/guwAwMTDv5vZurSoprfFXcuaGmL3AUsa5b3pd3z+Bjv3h7gEBfG8CTI+5gwED5TyYnjK80GjkhniEDKY6Eyg02W8HpoEpJyiEOx6GNeBZoCJaYcfMic7PmE5eJ0YzG2Dg8c6KfudxIuoo7R2RPt1T0EVE4YV70D4ObpWlDpOfcvQFrGUROAfto1U7PDCEdNi/4rDxdChQKHO7y/Uut4OFj7KjfLcaFmLYLqNr+/iCw4TORKbUskh+ue5MjJfDrU6yQ+JkFrkMxhcClyvbu7S66uLCeG+xtqGTigAuPWx2BMzmxmRpXKLCQYsU8iyCqGO/7GV0AhL/GPFKgguUvxaeQiwdpwprmIELa9cNJrRAO6mIUbF9ta+i2SFY1cTG+PpXBo8HS6i8q0G7zvGeOPBZHwW8czyxjht</enc>]]>
          </text>
        </query>
      </script>

    </grid>
   
  </grids>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>l6YXouPCl+9YFRqCaCLgmBUIRvx5uARRiTQ8iGbkWiZiVmE3iCWXRUMTZUFvk2Ef5Zz1QoZdwezO1GABU/ccmpBWCaPvBB77AGN/uBn8GqnLCvmUCWZCjQtk3//wcFeUV0pW5jTS24m73zWRmZhwmh56hl9QR/6hXT8WLw4Pf5fEX8IqVm/9f2hhK4fl5fElLcZeGT0S+6okt/40O8tVE018s1LPoHrPq921LPIOL0mRZyTtL3XyZBNZKBug6doyL5VzM1zOwruudTMcVF/w5BKVGACcqEgqg+4g0lRQWqEtJtjMhbkLPUVIVHDUxIOSl0Kn+mimS063zgDezS6UGOF8nSnJ9astJ5pVoVd1kX46Ky6om1yjKLJeQhIFVdJ6r1NJp2rHl61q8R7/Q3BrlFCfb0o5DYVawdCFytKk7FKhJ6qI6v01bOrrr2Vza5XkMspEt5fYepFCN7wL7CarBPvrx1YCJAoa2yI+SMdn+dI3zE33qpa+YZi7NhthAWVWSPJnIYIbZ3QyUAv+a0zqa6+/wmlKIVBFM7GXuZqk/XJZR4OC2M31Ej5Wtyp1uUh89/5dAumzypE134lBbI02bIrn+OFMR1OBWL+/0+okxdZpCN7m7Fwcc/1G3XyPCZ1yZ2DRMwootm8Qkm24KmJvC7G66A/dxyZIBTQa7dahJ3ceCmEXzA9jCPm6XGAXE9fC4GQCMBdTEowvjDnySi5UviYYLCkv2vwkvc934I3C6kT/Lk6sBujRe9UMFc2rqKWvPhIVhr1ToF8A4LUrcrVYfMTabRkbd9TEeDyZcCGwETo=</enc>]]>
    </text>
  </js>
  
  <script>
		<request code="ma_kh_request">
			<text>
			  <![CDATA[<enc>DoWx4mziIONS2eheLqzTujulo8+YOmduGtn08YPkUTYP/jKd1FVG44QhVRmkEHpbEdB1hobcyMPT+Putie16cdU2rS9Vn9Oqoy9huQZ2tGBwwmrK2FhJqfz2PKkv/oWf9uj/6iho5xnFs+CMlJKIamPycZO+MlOSuowFusS9D8+p6wrewh0LFKVzOETUByUknfEc5jpkQUkAGp/mRnz9GoHNvuFV/eMKVcQsx4+zFxcADrCaJd3UDsWMmUQZTMZOhSxfkFX246cNNs2zm7C3xY47TGPkqGrEHwjChbnRuSE1pW3TIKW+XNXENyc6Hv17I0xBmvjlwQA331i87VXXWqwXjJfmBrTlheioziTggGHuLXP2QhH6AabPHeynHGpVxX2Z2jUiIGMOeEiOvrrbOffAcLtHoAjr+N8tVKJ7Yz/w98QifXBkHTuv7NSd2F7H</enc>]]>
			</text>
		  </request>
    
  </script>
  
</dir>