<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
  <!ENTITY VoucherExtendFields SYSTEM "..\Include\XML\VoucherExtendFields.xml">
]>

<dir id="s643CR3Select" table="" height="" fieldKey="id" voucherCode="CR3" dirViewType="Dialog" readOnly="true" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Chi tiết báo giá được chọn" e="Quotation Entry Detail"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" readOnly="true" aliasName="@DFDFrom" disabled="true" allowBlank="false" dataType="D">
          <text v="Ngày c/từ từ/đến" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" allowBlank="false" disabled="true" inactivate="true" dataType="D" nextRow="false">
          <text v="Ngày đến" e="Voucher Date"></text>
        </field>
        <field name="ma_nt" hidden="true" label="1" field="1">
          <text v="Mã ngoại tệ" e="Ex Code"></text>
        </field>
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>
	
		<field name="ma_nv" format="U" label="1" disabled="true"  field="1" operation="like" >
          <text v="Mã nhân viên" e="Code Employee"></text>
        </field>
		<field name="ten_nv" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="ma_kh" format="U" label="1" disabled="true"  field="1" operation="like" >
          <text v="Mã khách hàng" e="Code"></text>
        </field>
		<field name="ten_kh" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		 <field name="ma_hang" viewType="Lookup" label="1" disabled="true" field="1" operation="like">
			<text v="Hãng tàu/ Đại lý" e="Carrier/ Agent Code"></text>
		</field>
		<field name="ten_hang" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="t_tong_trong" label="1" field="1" dataType="N" disabled="true" nextRow="true" format="FCAmount" >
          <text v="Tổng trọng lượng" e="Total Weight"></text>
        </field>
		
		<field name="t_tong_khoi" label="1" field="1" dataType="N" disabled="true" nextRow="true" format="FCAmount" >
          <text v="Tổng Volume" e="Total Volume"></text>
        </field>
        <field name="ma_noi_di" viewType="Lookup" label="1" disabled="true" field="1" operation="like">
			<text v="Nơi đi" e="Origin "></text>
			<viewInfo lookupType="One" lookupId="vdmcangdi" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_di" />
		</field>
		<field name="ten_noi_di" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="ma_noi_den" viewType="Lookup" disabled="true" label="1" field="1" operation="like">
			<text v="Nơi đến" e="Destination"></text>
			<viewInfo lookupType="One" lookupId="vdmcangden" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_den"  />
		</field>
		<field name="ten_noi_den" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>  
		<field name="so_ct" label="1" field="1" disabled="true" hidden="true">
          <text v="Số báo giá" e="Quot. Number"></text>
        </field>
		<field name="dien_giai" label="1" rows="1" field="-" disabled="true">
		  <text v="Diễn giải" e="Explain"></text>
		</field>
		<field name="id" dataType="N" hidden="true" fieldType="PK" label="1" field="1"  >
			  <text v="ID" e="Code"></text>
		</field>
      </fields>
    </form>
    <form tabPageIndex="1" gravity="MiddleLeft" height="350" columns="120,120,240" >
      <text v="Chi tiết" e="Detail"></text>
      <fields>
        <field name="v613" label="" field="-" viewType="Grid">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
  </forms>

 <grids>
    <grid id="v613" table="v613" fieldKey="id, line" order="id, line" allowFilter="true" readOnly="true" allowOrder="true">
      <fields>
        <field name="id" foreignField="id" dataType="N" fieldType="PK" format="0" copy="false" hidden="true">
          <text v="" e=""></text>
        </field>
        <field name="line" foreignField="@@ROW" dataType="I" fieldType="PK" hidden="true">
          <text v="Dòng" e="Line"></text>
        </field>

        <field name="ma_phi" width="80" allowBlank="false" viewType="Lookup" readOnly="false" hidden="true" >
          <text v="Mã phí" e="Fee"></text>
          <viewInfo lookupType="One" lookupId="dmphi" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_phi" lookupInfo="dmphi|ma_phi|ten_phi" />
        </field>
        <field name="ten_phi" width="200" fieldType="EX" inactivate="true" readOnly="true" hidden="true" aliasName="b" join=" left join dmphi b on a.ma_phi = b.ma_phi ">
          <text v="Tên phí" e="Fee Name"></text>
        </field>
		<field name="ma_kien" width="100" allowBlank="false" viewType="Lookup" readOnly="false" hidden="false"  >
          <text v="Mã kiện" e="Package Code"></text>
          <viewInfo lookupType="One" lookupId="dmkien" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_kien" lookupInfo="dmkien|ma_kien|ten_kien" />
        </field>
        <field name="ten_kien" width="120" fieldType="EX" inactivate="true" readOnly="true" aliasName="k" join=" left join dmkien k on a.ma_kien = k.ma_kien " hidden="false" >
          <text v="Tên kiện" e="Package Name"></text>
        </field>
         <field name="ma_dk_phi" viewType="Combobox" width="130" readOnly="false" hidden="true">
			<text v="Loại phí" e="Fee type"></text>
			<viewInfo>
				<options query="select ma_bgn, ten_bgn%l from dmbgn where ma_ct = 'LPH' and status = 1 order by stt">
				</options>
			</viewInfo>
		</field>	
		
        <field name="so_luong" dataType="N" format="Amount" allowBlank="false" valueDefault="1" width="100" readOnly="false" >
          <text v="Số lượng" e="Quantity"></text>
        </field>
		<field name="ty_trong" dataType="N" format="FCPrice" width="120" readOnly="false" >
          <text v="Trọng lượng(KGS)" e="Gross Weight(KGS)"></text>
        </field>
		 <field name="tong_trong" dataType="N" inactivate="true" format="FCPrice" readOnly="false" disabled="true" width="120">
          <text v="Tổng trọng lượng (KGS)" e="Total Gross Weight(KGS)"></text>
        </field>
		<field name="ty_khoi" dataType="N" format="FCPrice" width="120" readOnly="false" >
          <text v="Volume(CBM)" e="Volume(CBM)"></text>
        </field>
		<field name="tong_khoi" dataType="N" inactivate="true" format="FCPrice"   readOnly="false" disabled="true" width="120">
          <text v="Tổng Volume" e="Total Volume"></text>
        </field>
		<field name="hs_code" width="150" valueDefault="0" readOnly="false" >
          <text v="HS Code" e="Quantity"></text>
        </field>	
        <field name="ct_km" width="100" valueDefault="0" viewType="Combobox" inactivate="true" hidden="true" readOnly="false" >
          <text v="Loại hàng" e="Fee Type"></text>
          <viewInfo>
            <options>
              <option val="0">
                <text v="Hàng bán" e="Sale"/>
              </option>
              <option val="1">
                <text v="Hàng KM" e="Promotion"/>
              </option>
            </options>
          </viewInfo>
        </field>
        <field name="gia_nt1" dataType="N" hidden="true" format="FCPrice" width="100" readOnly="false"  >
          <text v="Giá mua " e=" Cost Price"></text>
        </field>
        
		 <field name="tien_nt1" dataType="N" hidden="true" format="FCAmount" width="100" valueDefault="0" readOnly="false" disabled="true" >
          <text v="Tiền mua" e="Cost Amount"></text>
        </field>
		
		<field name="gia_nt2" dataType="N" format="FCPrice" width="100" readOnly="false" hidden="true" >
          <text v="Giá bán" e="Bill Price"></text>
        </field>
        <field name="tien_nt2" dataType="N" format="FCAmount" valueDefault="0" width="100" readOnly="true" hidden="true"  >
          <text v="Tiền bán" e="Bill Amount"></text>
        </field>
        <field name="tl_ck" dataType="N" format="Rate" width="100" hidden="true" readOnly="false" >
          <text v="Tl ck(%)" e="Dis.Rate"></text>
        </field>
        <field name="ck_nt" dataType="N" format="FCAmount" width="100" hidden="true" readOnly="false" clientDefault="true" >
          <text v="Ch.khấu " e=" Discount"></text>
        </field>
		 <field name="ma_nt" width="70" allowBlank="true" viewType="Lookup" readOnly="false" hidden="true" >
          <text v="Mã NT" e="Currency"></text>
          <viewInfo lookupType="One" lookupId="dmnt" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_nt" lookupInfo="dmnt|ma_nt|ten_nt" />
        </field>
		 <field name="ten_nt" width="0" fieldType="EX" inactivate="true" readOnly="true" aliasName="d" join=" left join dmnt d on a.ma_nt = d.ma_nt ">
          <text v="Tên phí" e="Fee Name"></text>
        </field>
		 <field name="ty_gia" dataType="N" format="Price" width="100" valueDefault="1" hidden="true" readOnly="false" >
          <text v="Tỷ giá" e="Curr.Rate"></text>
        </field>
        
        <field name="gia1" dataType="N" format="Price" width="100" hidden="true"  valueDefault="0" inactivate="true" readOnly="true" >
          <text v="Giá chuẩn" e="Std.Price"></text>
        </field>
        <field name="gia2" dataType="N" format="Price" width="0" inactivate="true" valueDefault="0" readOnly="true" >
          <text v="Giá bán" e="Price"></text>
        </field>
		 <field name="tien1" dataType="N" format="Amount" width="100" hidden="true" inactivate="true"  valueDefault="0" readOnly="false" disabled="true" >
          <text v="Chi phí" e="Total Cost"></text>
        </field>
        <field name="tien2" dataType="N" format="Amount" width="100" hidden="true" inactivate="true" valueDefault="0" readOnly="true" >
          <text v="Doanh thu" e="Total Bill"></text>
        </field>
		
        <field name="ck" dataType="N" format="Amount" width="100" inactivate="true" hidden="true" readOnly="false">
          <text v="Chiết khấu" e="Discount"></text>
        </field>
		<field name="thue_suat" dataType="N" format="0" width="60" readOnly="false"  valueDefault="0" hidden="true" clientDefault="true" >
          <text v="VAT(%)" e="Tax"></text>
        </field>
        <field name="thue_nt" dataType="N" format="FCAmount" width="100" hidden="true" readOnly="true">
          <text v="Thuế %s" e="%s Tax"></text>
        </field>
        <field name="thue" dataType="N" format="Amount" width="100" inactivate="true" hidden="true" readOnly="true">
          <text v="Thuế" e="Tax"></text>
        </field>
		<field name="tc_tien2" dataType="N" format="Amount" width="100" hidden="true" valueDefault="0" inactivate="false" readOnly="true" >
          <text v="" e="Total"></text>
        </field>
		<field name="tc_tien_nt2" dataType="N" format="Amount" width="100" hidden="true" valueDefault="0" inactivate="false" readOnly="true" >
          <text v="" e="Total "></text>
        </field>
		
		<field name="tt" dataType="N" format="Amount" width="100" hidden="true" valueDefault="0" inactivate="false" readOnly="true" >
          <text v="Tổng cộng" e="Total"></text>
        </field>
		<field name="tt_nt" dataType="N" format="Amount" width="100" hidden="true" inactivate="false" readOnly="true" >
          <text v="" e="Total "></text>
        </field>
		<field name="tien_ln" dataType="N" format="Amount" width="100" inactivate="false" hidden="true" valueDefault="0" readOnly="false" disabled="true" >
          <text v="Lợi nhuận" e="Profit"></text>
        </field>
		<field name="dien_giai" width="200" inactivate="false" readOnly="false">
          <text v="Diễn giải" e="Explain"></text>
        </field>
		<field name="id_bg" dataType="N" inactivate="true" hidden="true" format="0" width="80" copy="false">
          <text v="ID BG" e="ID BG"></text>
        </field>
        <field name="so_ct_bg" width="100" fieldType="EX" copy="false" readOnly="true" hidden="true" inactivate="true" link="v41|id_bg as id" aliasName="cast('' as nvarchar(3000)) as ">
          <text v="Số báo giá" e="Quot. No."></text>
        </field>
        <field name="line_bg" dataType="I" width="70" copy="false" hidden="true" inactivate="true">
          <text v="Dòng BG" e="Quot. Line"></text>
        </field>
		<field name="id_tg" dataType="N" inactivate="true" hidden="true" format="0" width="80" copy="false">
          <text v="ID TG" e="ID BG"></text>
        </field>
        <field name="so_ct_tg" width="100" fieldType="EX" copy="false" readOnly="true" hidden="true" inactivate="true" link="v51|id_tg as id" aliasName="cast('' as nvarchar(3000)) as ">
          <text v="Số báo giá" e="Quot. No."></text>
        </field>
        <field name="line_tg" dataType="I" width="70" copy="false" hidden="true" inactivate="true">
          <text v="Dòng TG" e="Quot. Line"></text>
        </field>
      </fields>

      <buttons>
        <button id="freeze">
          <text v="$FreezeToolbar" e="$FreezeToolbar"></text>
        </button>
      </buttons>

      <script>
        <query>
          <text>
            <![CDATA[<enc>V8jL8O6o25SZvpyQeujkrfJn09GsHQ1QXu3ZE2GizVOv5MaVm68Wmo9+IBkSfJZae64x7JTuMbMnrKSS8MzK2XAku3yI46+PO1n21vZ7fzo74TRxBniAe2+ip+uMlF0pIWBScsmZIHBugXMBHnCrQjYHTkusgNV+4rN8g4PjMwG8vEUM18g7AO9Z7iAEswsbVwjQEZHb4w0df5134iYOGJQKhYgfJqzLO+I9A5enYRVrbDQECEQ2YOE0V6jGREvYtObEGwKyGYFiKAaWG/QbRlA882dgECNfS1FDvMzgSu1FkxltFVSLXoHMA7OYgxiG9YN2lxToH5Amge3oIdNyNfp5YEzeZxYiJ5B003gXYMlPVIdc5trZFuYdNnc2PGIf/ydxeAT8YIbPXLTbcRnLG0V5TXhHllBQbJUMVZ8fiF4vry0wIgV7tRlFptz6fdaX</enc>]]>
          </text>
        </query>
      </script>

    </grid>
   
  </grids>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>l6YXouPCl+9YFRqCaCLgmJc7Spc7cujgBOqa+4OdBPdJuiUMxv0yKjzA0wncQGm9NYbn4AwYlxYav/bP1jFEgoXb0//AilzZ8dxArdF+5b6U0Cuzg8zDqC0xxkPvDnJ3z8dieWP8t4uouRZ+1CbyHT64X7RhyDhUIk0lyptbRfwwpjtLXdP0Cf/kHGQHueNdu3zfGCFqEcUeDKzeh5+rUwrnPYGvDfT/XgSHFBE9IZI/qG3Kjql2Y1zfUV1nsccD5B224pS/4TSv3sjIKSAsexnpY5BhtSzgkXLPTrnjWIzxh7qW5JZJWNta13JRNl6onbjuk9l3NV5fArAE1RAM0h9bbC0D2YyZCIHHqynw8rnoIeEiGOCrghwrXg+TzLxMGT7BMXTYsulMldjGXn+iYalkhJkAGgNe7xm0UfBR5MIezkWWT3Gav/biT7E6TNQ1aKxcgNF+rF1CRcwJ3XFLjsr0ZPwQBPV1E+qNlSYXrUScR+A62oyT2bAf/fmWZ14ePnSWOTi8P+OqgO5w4Pll/6bJOkNatXioc9vNY+MbJoO/4pN4xjaCMehHwr1kSvnbezYqrrYGeShrWGU1jBi/gth8gv0WuDmBtnD8uarmbGBvNrE1et11q+iGKLTJ/MEVTMbZUGNyZ4mN/UXCiHGW/CBaUeoFW9Dto+bVZhWrnd4HX9GW+noy9vDfiCZBpihVmG3FKE+kNqdIyuQhpr0jy6tgWc/hyHrNnvQX3AVUrCbx3Myd16zNYy6Cn3fq7PV4hideecFnnd8ptsNmtwupiqysCBYxEroPHlWDh9pKs/s=</enc>]]>
    </text>
  </js>
  
  <script>
		<request code="ma_kh_request">
			<text>
			  <![CDATA[<enc>zaFLgazYjhu2y6XMtazMt0E7K/+fMDNf6+wrxrdYqHy5cFdOSJlnDyrc8tMxif/JyUJ4Vst/ivfCi09aruWFfPM5kIlkodQ6/CC8wwwbboUjFfL74PIFX4udW7sRfrJQZSK5kcsHC20lWvIzJ46yUH37NSLdpRBAaMT/tHVxePITDnf7k1GYj/I6EgCriFzK0CtVe0Nql+T1Ocq1DqdSBTumEWEGKnlFHdxjfFeMolvl7eTX8h/HAPzlFBr41TEWws9MPscXJqKmYdyC5b58EiPJi77WEpOZaevu3GmAH8a7KFmH8NL8cTXq69m34PHGR5fl9g4UrFd2r0WoPan1nBp1b9t5geV9fvqieQ0hmRgowm7O1M0j2rzUptXNYGA/h+2UWsL2qcjQw1AyOSgFSkzFyHPEtYxTax+SBuLrgAAvUxikAsRjJ8gfkOHTt+pv</enc>]]>
			</text>
		  </request>
    
  </script>
  
</dir>