<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="s661CR1" fieldKey="id" voucherCode="CR1" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc số đơn hàng FCL" e="Filter FCL Order Numbers"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D">
          <text v="Ngày từ/đến" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" aliasName="@DFDTo" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D" nextRow="false">
          <text v="" e=""></text>
        </field>
       
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>	
        <field name="ma_noi_di" viewType="Lookup" disabled="false" label="1" field="1" operation="like">
			<text v="Nơi đi" e="Origin "></text>
			<viewInfo lookupType="One" lookupId="vdmcangdi" lookupKey="(kkh_yn = 1 or hc_yn = 1) and status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_di" />
		</field>
		<field name="ten_noi_di" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="ma_noi_den" viewType="Lookup" label="1" field="1" operation="like">
			<text v="Nơi đến" e="Destination"></text>
			<viewInfo lookupType="One" lookupId="vdmcangden" lookupKey="(kkh_yn = 1 or hc_yn = 1) and status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_den"  />
		</field>
		<field name="ten_noi_den" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>	
		 <field name="so_ct" label="1" field="1" allowBlank="false" viewType="Lookup" operation="like">
          <text v="Lấy số đơn hàng" e="Get the order number"></text>
          <viewInfo lookupType="one" lookupId="s611" lookupRef="ds_so_dh" lookupKey="ngay_ct between ![ngay_ct1]! and ![ngay_ct2]! and ma_noi_di like ![ma_noi_di]! +'%' and ma_noi_den like ![ma_noi_den]! +'%'" lookupCheck="ma_noi_di like ![ma_noi_di]! and ma_noi_den like ![ma_noi_den]!  and status in (5,6)" />
        </field>
        <field name="ds_so_dh" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>	
      </fields>
    </form>
	
	
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>7dnUqIuxukLuRCTGhnr/WXoft4J5RcFNHQ1wOqxxHStar0wB8r1o8uKNppyTPLM+GH4Ui6UMcpNxxkLaUxPPeuXsgV3ttOdesPSE7tdjMkcIdw3YdzE7pKI8P63xIXC50bK9vUwh1w6EzpMUuShiZOw7islP/WHpcFmYYbvn+Zyeta8wlReSsnS1G/I8ftKi2II3SWOn7HbXLMN+lbtTxwpdYI0DNqc0xlxWVIE46HXT2+7MKPXDNhPJOqgFdWb1llI83BQYTiKRrwmdNASJzRMb5b1FZNV1oWsL8hhUcJDIoEOiKYmC8tBPYK/kDrc4O9VFUIpJbI/0NAIrx4Cx7IBNJnieBWc/eq3xjM5Rzr0Crwm17IYbU/PS11hxr7Zvb+xYPURnG1N43zSlL3P+bG+RefH6QDwNtrtAhY1PyQBwXeOk76u1edID8RLwV4k99qi5Sc3DZZ4zh8ceTpvutUZIu+9alamjCbUcAM0ln6Lg2fDVOaQAkRnAhC1t6+HHlvLs5k0Z0OYMsHTLlmKLaiP5XH4sBUA52JGY5GNvq97V8iQr8Z1PR85EpOr0yDBS</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>