<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
  <!ENTITY ReportFilterItemGroup SYSTEM "..\Include\XML\ReportFilterItemGroup.xml">
  <!ENTITY ReportFilterCustomerGroup SYSTEM "..\Include\XML\ReportFilterCustomerGroup.xml">
  <!ENTITY ReportFilterStockType SYSTEM "..\Include\XML\ReportFilterStockType.xml">
  <!ENTITY ReportJSLoading SYSTEM "..\Include\XML\ReportJSLoading.xml">
  <!ENTITY ReportFilterUnit SYSTEM "..\Include\XML\ReportFilterUnitHidden.xml">
  <!ENTITY ReportFiltering SYSTEM "..\Include\XML\ReportFiltering.xml">
  <!ENTITY ReportDataAnalysisStruct SYSTEM "..\Include\XML\ReportDataAnalysisStruct.xml">
]>

<dir id="ss_bctkrp" table="" height="" fieldKey="id" dirViewType="Dialog" dirObjectType="Report" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Filter Agent Sumary" e="Filter Agent Sumary"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
       <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" clientDefault="true" allowBlank="false" dataType="D">
          <text v="Ngày từ/đến" e="Date From/To"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" aliasName="@DFDTo" clientDefault="true" allowBlank="false" dataType="D" nextRow="false">
          <text v="" e=""></text>
        </field>
		<field name="ma_donvi" viewType="Lookup" label="1" field="1" operation="like">
			<text v="Đơn vị" e="Origin"></text>
			<viewInfo lookupType="One" lookupId="dmdonvi" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_donvi"  />
		</field>
		<field name="ten_donvi" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 	
		
		<field name="ma_pb" viewType="Lookup" label="1" field="1" operation="like">
			<text v="Phòng ban" e="Origin"></text>
			<viewInfo lookupType="One" lookupId="dmpb" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_pb"  />
		</field>
		<field name="ten_pb" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 	
		
		<field name="ma_bp" viewType="Lookup" label="1" field="1" operation="like">
			<text v="Bộ phận" e="Origin"></text>
			<viewInfo lookupType="One" lookupId="dmbp" lookupKey="status = 1 and ma_pb = ![ma_pb]!" lookupCheck="1 = 1" lookupRef="ten_bp"  />
		</field>
		<field name="ten_bp" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>
		
		<field name="admin1" label="1" field="1" hidden="true">
		   <text v="admin" e="Voucher Number"></text>
		   </field>
		&ReportFilterUnit;
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>qrqJjfTg/LgpBo4fmaoTmt7fhuBH905Sn994nfMEXjSMsfEEH7Qhm+2bWLeBD1ABm82BIKh9rkbx9G1U6efh9pj7gUHHK5bWLH+c7eZRideIR3VoLklcctSPimyaFVgZmSzu7WPvZCj5y/+FFMaETwHuq0x1oXPK6XAmIlNFTQNvrnYEHT2AsUZ21/cHOGQRVTuvhv8/6hYtd6ZtvQrj5zL5LGksp5Di2YDSVtPElM7aSJVuROPHFcRV63XenTo1XhrNgD0SCwm3+S0AJKh1Ef9C7Xhu+u0agl320ezUNhxSxTF4CW1CkMZiRGIVPNcDLA9c2mbrJtpfmSyNN0L1Vg==</enc>]]>
    </text>
  </js>

<script>
	<request code="loadadmin">
		<text>
		  <![CDATA[<enc>nxRArfWfc4wG1um8t40QZwmNF02kNqDZyHwYyCfwJGO1FNFR2iu+cCEkGmGdXg3Vwn6KLf6g+fmf4pSRTE1Baw==</enc>]]>
		</text>
	  </request>
    <processing>
      <text>
        <![CDATA[<enc>TN45BLVvlQZWD1bhImJFui3B6za/B5OT7CPnricv7F9VxXndoQI7mrkZhe35dbbb</enc>]]>
      </text>
    </processing>
    &ReportJSLoading;
  </script>
</dir>