<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
  <!ENTITY ReportFilterItemGroup SYSTEM "..\Include\XML\ReportFilterItemGroup.xml">
  <!ENTITY ReportFilterCustomerGroup SYSTEM "..\Include\XML\ReportFilterCustomerGroup.xml">
  <!ENTITY ReportFilterStockType SYSTEM "..\Include\XML\ReportFilterStockType.xml">
  <!ENTITY ReportJSLoading SYSTEM "..\Include\XML\ReportJSLoading.xml">
  <!ENTITY ReportFilterUnit SYSTEM "..\Include\XML\ReportFilterUnitHidden.xml">
  <!ENTITY ReportFiltering SYSTEM "..\Include\XML\ReportFiltering.xml">
  <!ENTITY ReportDataAnalysisStruct SYSTEM "..\Include\XML\ReportDataAnalysisStruct.xml">
]>

<dir id="ss_bcqtvh" table="" height="" fieldKey="id" dirViewType="Dialog" dirObjectType="Report" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc báo cáo chi tiết nhật ký" e="Filter detailed log reports"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
       <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" clientDefault="true" allowBlank="false" dataType="D">
          <text v="Ngày từ/đến" e="Date From/To"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" aliasName="@DFDTo" clientDefault="true" allowBlank="false" dataType="D" nextRow="false">
          <text v="" e=""></text>
        </field>
		
		<field name="ma_donvi" viewType="Lookup" label="1" field="1" operation="like">
			<text v="Đơn vị" e="Origin"></text>
			<viewInfo lookupType="One" lookupId="dmdonvi" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_donvi"  />
		</field>
		<field name="ten_donvi" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 	
		
		<field name="ma_pb" viewType="Lookup" label="1" field="1" operation="like">
			<text v="Phòng ban" e="Origin"></text>
			<viewInfo lookupType="One" lookupId="dmpb" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_pb"  />
		</field>
		<field name="ten_pb" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 	
		<field name="ma_bp" viewType="Lookup" label="1" field="1" operation="like">
			<text v="Bộ phận" e="Origin"></text>
			<viewInfo lookupType="One" lookupId="dmbp" lookupKey="status = 1 and ma_pb = ![ma_pb]!" lookupCheck="1 = 1" lookupRef="ten_bp"  />
		</field>
		<field name="ten_bp" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>

		
		<field name="admin1" label="1" field="1" hidden="true">
		   <text v="admin" e="Voucher Number"></text>
		 </field>
		
		&ReportFilterUnit;
      </fields>
    </form>
	<form gravity="MiddleLeft" columns="120,120,120"  >
      <fields>
		<field name="ma_td" viewType="Lookup" label="1" field="1" operation="like">
			<text v="Mã tác động" e="Origin"></text>
			<viewInfo lookupType="One" lookupId="vdmtd" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_td"  />
		</field>
		<field name="ten_td" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>
		<field name="ma_plkh" viewType="Lookup" label="1" field="1" operation="like">
			<text v="P/loại khách hàng" e="Customer Classification"></text>
			<viewInfo lookupType="One" lookupId="dmploaikh" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_plkh"  />
		</field>
		<field name="ten_plkh" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>
		<!-- <field name="ma_remode" viewType="Lookup" label="1" field="1" operation="like"> -->
			<!-- <text v="Nơi liên lạc" e="Origin"></text> -->
			<!-- <viewInfo lookupType="One" lookupId="vdmremode" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_remode"  /> -->
		<!-- </field> -->
		<!-- <field name="ten_remode" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-"> -->
			<!-- <text v="" e=""></text> -->
		<!-- </field> -->
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>XzWu+M0L/hcWbkbhnNbj39V5sCIQPnM/T4+YC7xmEfa7dzEoQjd43+ONx+o2wGn9fxEussn4UDJLNhwTKpRmGBeiWd+InP3QJfmUTAlw1Fz3xgEfRUTxy8bQnALij0YACSWVOk4q7cgLjN9lkO3R/IbYSwOwV+tk/iwfUJAHaN2mJfSs8+g+LAx2HRCOv+GXffWqfFeIlZv6PX3oMaeDuh9nKgj1G/t4x9zLRiN/CFgeaWdLzHQcEeZM7frLfoyNPofI6rceZNsR+oUL+sI/6NXuC8f7ed+rCu850mjDVeWtGJgyyycWWlZ0pFN4kHbXEj7wJXOSI7NLwRvOIVI2e7FWT7J5GPlGFDUPhSv+Os0=</enc>]]>
    </text>
  </js>
<css>
    <text>
      <![CDATA[<enc>yy9zWSQQM5h40cdPRANtpBtFUaX6z8cRbH0DOZr9KI7QmzbfKhaMUx8DNcql+JYcbn0uUhZhxCjHzFEQCMa4hicKSiqTr/YWjgpvMxr9KsjRcGKkUcVZFHTeoO8OYha6</enc>]]>
    </text>
  </css>
<script>
	<request code="loadadmin">
		<text>
		  <![CDATA[<enc>nxRArfWfc4wG1um8t40QZwmNF02kNqDZyHwYyCfwJGO1FNFR2iu+cCEkGmGdXg3Vwn6KLf6g+fmf4pSRTE1Baw==</enc>]]>
		</text>
	  </request>
    <processing>
      <text>
        <![CDATA[<enc>TN45BLVvlQZWD1bhImJFui3B6za/B5OT7CPnricv7F9VxXndoQI7mrkZhe35dbbb</enc>]]>
      </text>
    </processing>
    &ReportJSLoading;
  </script>
  
</dir>