<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
  <!ENTITY ReportFilterItemGroup SYSTEM "..\Include\XML\ReportFilterItemGroup.xml">
  <!ENTITY ReportFilterCustomerGroup SYSTEM "..\Include\XML\ReportFilterCustomerGroup.xml">
  <!ENTITY ReportFilterStockType SYSTEM "..\Include\XML\ReportFilterStockType.xml">
  <!ENTITY ReportJSLoading SYSTEM "..\Include\XML\ReportJSLoading.xml">
  <!ENTITY ReportFilterUnit SYSTEM "..\Include\XML\ReportFilterUnitHidden.xml">
  <!ENTITY ReportFiltering SYSTEM "..\Include\XML\ReportFiltering.xml">
  <!ENTITY ReportDataAnalysisStruct SYSTEM "..\Include\XML\ReportDataAnalysisStruct.xml">
]>

<dir id="ss_bcbdnv" table="" height="" fieldKey="id" dirViewType="Dialog" dirObjectType="Report" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Báo cáo biến động nhân viên" e="Employee Turnover Report"></title>
  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
		<field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" clientDefault="true" allowBlank="false" dataType="D">
          <text v="Ngày từ/đến" e="Date From/To"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" aliasName="@DFDTo" clientDefault="true" allowBlank="false" dataType="D" nextRow="false">
          <text v="" e=""></text>
        </field>
		<field name="loai" dataType="I" viewType="Combobox" valueDefault="2" label="1" field="2" >
          <text v="Loại hình" e=""></text>
          <viewInfo>
            <options>
              <option val="2">
                <text v="Ngày kết thúc làm việc" e=" "/>
              </option>
            </options>
          </viewInfo>
        </field>
		<field name="ma_dv" viewType="Lookup" label="1" field="1" operation="like">
          <text v="Đơn vị" e=" "></text>
          <viewInfo lookupType="One" lookupId="dmdonvi" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_dv" />
        </field>
        <field name="ten_dv" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
		<field name="ma_pb" viewType="Lookup" label="1" field="1" operation="like">
          <text v="Phòng ban" e=""></text>
          <viewInfo lookupType="One" lookupId="dmpb" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_pb" />
        </field>
        <field name="ten_pb" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
		<field name="ma_bp" viewType="Lookup" label="1" field="1" operation="like">
          <text v="Bộ phận" e=""></text>
          <viewInfo lookupType="One" lookupId="dmbp" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_bp" />
        </field>
        <field name="ten_bp" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
		<field name="ma_cv" viewType="Lookup" label="1" field="1" operation="like">
          <text v="Chức vụ" e=""></text>
          <viewInfo lookupType="One" lookupId="dmchucvu" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_cv" />
        </field>
        <field name="ten_cv" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
		<field name="ma_vtcv" viewType="Lookup" label="1" field="1" operation="like">
          <text v="Vị trí công việc" e=""></text>
          <viewInfo lookupType="One" lookupId="dmvtcv" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_vtcv" />
        </field>
        <field name="ten_vtcv" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
		
		
		<!-- <field name="ma_nv" viewType="Combobox" valueDefault="" label="1" field="2" nextRow="true" operation="="  > -->
			<!-- <text v="Nhân viên" e="Employee"></text> -->
			<!-- <viewInfo> -->
				<!-- <options query=" -->
						<!-- select a.username, a.nickname%l from vdmnv a left join sysuserinfo b on a.username = b.username where b.user_id = @@userId order by nickname"> -->
				<!-- </options> -->
			<!-- </viewInfo> -->
		<!-- </field> -->
		
		<!-- <field name="admin1" label="1" field="1" hidden="true"> -->
	         <!-- <text v="admin" e="Voucher Number"></text> -->
	    <!-- </field> -->
		&ReportFilterUnit;
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>U2/fmJF3qMzpXtgX5wtlXflKYHVGu04ngxt6wrDokgozIUgzha4ZHHAqLPcE3+d/F/VU26YOjrhgbECUKKPSvMZeODUFEIBO6IX3im8g4VslRO5NknWiOBFgtuQqHoRiiC6j/gP08lonBZ9EMzpHzWYMSEbLhK0k188//JxIL4cScPdWvaFb7PKxqh0H+Qck60zIaa/RMB17gYOe1qDxdQ==</enc>]]>
    </text>
  </js>

<script>
    <processing>
      <text>
        <![CDATA[<enc>TN45BLVvlQZWD1bhImJFui3B6za/B5OT7CPnricv7F9VxXndoQI7mrkZhe35dbbb</enc>]]>
      </text>
    </processing>
    &ReportJSLoading;
  </script>
</dir>