<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
  <!ENTITY ReportFilterItemGroup SYSTEM "..\Include\XML\ReportFilterItemGroup.xml">
  <!ENTITY ReportFilterCustomerGroup SYSTEM "..\Include\XML\ReportFilterCustomerGroup.xml">
  <!ENTITY ReportFilterStockType SYSTEM "..\Include\XML\ReportFilterStockType.xml">
  <!ENTITY ReportJSLoading SYSTEM "..\Include\XML\ReportJSLoading.xml">
  <!ENTITY ReportFilterUnit SYSTEM "..\Include\XML\ReportFilterUnitHidden.xml">
  <!ENTITY ReportFiltering SYSTEM "..\Include\XML\ReportFiltering.xml">
  <!ENTITY ReportDataAnalysisStruct SYSTEM "..\Include\XML\ReportDataAnalysisStruct.xml">
]>

<dir id="ss_lslncuocgoi" table="" height="" fieldKey="id" dirViewType="Dialog" dirObjectType="Report" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Filter Call Detail" e="Filter Call Detail"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
       <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" clientDefault="true" allowBlank="false" dataType="D">
          <text v="Ngày từ/đến" e="Date From/To"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" aliasName="@DFDTo" clientDefault="true" allowBlank="false" dataType="D" nextRow="false">
          <text v="" e=""></text>
        </field>
		<field name="ma_so_thue" label="1" field="2">
          <text v="Mã số thuế" e="Tax Code"></text>
		</field>
		<field name="ma_donvi" viewType="Lookup" label="1" field="1" operation="like">
			<text v="Đơn vị" e="Unit"></text>
			<viewInfo lookupType="One" lookupId="dmdonvi" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_donvi"  />
		</field>
		<field name="ten_donvi" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 	
		
		<field name="ma_pb" viewType="Lookup" label="1" field="1" operation="like">
			<text v="Phòng ban" e="Department"></text>
			<viewInfo lookupType="One" lookupId="dmpb" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_pb"  />
		</field>
		<field name="ten_pb" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 	
		<field name="ma_bp" viewType="Lookup" label="1" field="1" operation="like">
			<text v="Bộ phận" e="Division"></text>
			<viewInfo lookupType="One" lookupId="dmbp" lookupKey="status = 1 and ma_pb = ![ma_pb]!" lookupCheck="1 = 1" lookupRef="ten_bp"  />
		</field>
		<field name="ten_bp" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>
		
		
		<!-- <field name="ma_nv" viewType="Combobox" valueDefault="" label="1" field="2" nextRow="true" operation="="  > -->
			<!-- <text v="Nhân viên" e="Employee"></text> -->
			<!-- <viewInfo> -->
				<!-- <options query=" -->
						<!-- select a.username, a.nickname%l from vdmnv a left join sysuserinfo b on a.username = b.username where b.user_id = @@userId order by nickname"> -->
				<!-- </options> -->
			<!-- </viewInfo> -->
		<!-- </field> -->
		
		<field name="admin1" label="1" field="1" hidden="true">
		   <text v="admin" e="Voucher Number"></text>
		   </field>
		&ReportFilterUnit;
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>ApSJP4bXdtSEo4VorXfglQzyKpqSx8gFS48Ckv/vDZYUSbOfoEkDzRUmEjU4NdYjTC3ee0JsRyXevMhkTPjZPCsZxG3ceSrDQuzacw65SYRNtgWoLdrPrRCLXsdtzOYn/lbRxxTUq/5+qMT2EQgmrCW+K8tv4Kv4kqP7Mf74rAFvO/oje3BRRsWBSatHd5CS/DiPxb3/c8eY/hUGjDCIRLH+eHPYIHQMyYLbaQ78GXB0h34ZqARo7nsBzQktsAlWdAJ+gOo2rUzqN0d+ExHYCEIr8L5V9zfR8ZOo8LFVse4INAbGPpsY2Jd/gtfmSgx1B9MEAtN7FF+zHjYp/goB7xQthIouZXg6hAQbvAN7970=</enc>]]>
    </text>
  </js>

<script>
	<request code="loadadmin">
		<text>
		  <![CDATA[<enc>nxRArfWfc4wG1um8t40QZwmNF02kNqDZyHwYyCfwJGO1FNFR2iu+cCEkGmGdXg3Vwn6KLf6g+fmf4pSRTE1Baw==</enc>]]>
		</text>
	  </request>
    <processing>
      <text>
        <![CDATA[<enc>TN45BLVvlQZWD1bhImJFui3B6za/B5OT7CPnricv7F9VxXndoQI7mrkZhe35dbbb</enc>]]>
      </text>
    </processing>
    &ReportJSLoading;
  </script>
</dir>