<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="sysrighthr" table="" fieldKey="name" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Phân quyền bộ phận và chức năng cho thông tin nhân viên" e="Departments And Menu Access Right Maintenace"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,240,120"  >
      <fields>
        <field name="xtype" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Loại" e="Type"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="Người sử dụng" e="User"></text>
              </option>
              <option val="0">
                <text v="Nhóm người sử dụng" e="Group"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>U9dMRoskrT9HDY0GbuwbY0xnBBoahsdSPK2WXNP5jiEmS4Aih6BobU3ATPU0V/im0XinZfqQNBP1mVsCvzgN0PiR9iSwnRe6kAzlXoGZ1LIEc2NfyvyRgTf/m54Arv/9AZK3gFiI5dkMTkbT/iVXQCX7xwvAKEIgtYT6w2puwwuUa01adrR8UeC1fdCj+EIr</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>