<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="sysrighthrempinfo" table="" fieldKey="name" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Phân quyền truy vấn thông tin nhân viên" e=""></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,240,120"  >
      <fields>
        <field name="xtype" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Loại" e="Type"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="Người sử dụng" e="User"></text>
              </option>
              <option val="0">
                <text v="Nhóm người sử dụng" e="Group"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>X6QBwtxe6vPwvDADx1+/ZP+6serRhok0um7iOpN9lxFIph5dazEAbuEpm+kD0/4dXVn0oXA5oNoA/erbCCpTnFwzPSueXBBXki7QCZq3UhZ1y2kvrGlkFn3TIWY/dRbj31bQ8yJPHjveTGszncxR4HB/+v0vE50N9watqrxhjNAbh5gOYOQrAjDrtc8kMY4zw4Nm1SDqSWNsjq4I5Y0eJw==</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>