<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="t11BQ1" fieldKey="id" voucherCode="BQ1" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc báo giá" e="Quotation Entry Filter"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D">
          <text v="Ngày từ/đến" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" aliasName="@DFDTo" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D" nextRow="false">
          <text v="" e=""></text>
        </field>
		<field name="ma_noi_di" viewType="Lookup" disabled="false" label="1" field="1" operation="like">
			<text v="Nơi đi" e="Origin "></text>
			<viewInfo lookupType="One" lookupId="vdmcangdi" lookupKey="(kkh_yn = 1 or hc_yn = 1) and status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_di" />
		</field>
		<field name="ten_noi_di" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="ma_noi_den" viewType="Lookup" label="1" field="1" operation="like">
			<text v="Nơi đến" e="Destination"></text>
			<viewInfo lookupType="One" lookupId="vdmcangden" lookupKey="(kkh_yn = 1 or hc_yn = 1) and status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_den"  />
		</field>
		<field name="ten_noi_den" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>  
		 <field name="id_bg" label="1" field="1" allowBlank="false" viewType="Lookup">
          <text v="Lấy số báo giá" e="Get a quote number"></text>
          <viewInfo lookupType="one" lookupId="s41" lookupRef="ds_so_bg" lookupKey="status = 7 and ![ngay_ct2]! >= ngay_hl  and  ngay_hld >= ![ngay_ct1]! and ma_noi_di like ![ma_noi_di]! +'%' and ma_noi_den like ![ma_noi_den]! +'%'" lookupCheck="ma_kh = ![ma_kh]! and status in (7) and ma_nt = ![ma_nt]!" />
        </field>
        <field name="ds_so_bg" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
	
	
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>xDqHA65tWdmKzA7Vta3yKwK2YEx0f6WVy3S85CvPGdzWnQhUkXIAl8r5Gal3M/ltwi327SPpS39YfN6u2/hJzW8n/ZBbt8kKTc92IaQvil2Eetr++cLW4OZtZ1LiQwKar3hoNoK3A6X7rXJ7hAwqyosIRON315TSZTcY77YVf/nFQ1nHHekLy2TrasKIVcbMNyuXYbbvpHzkSQcX2QHw3KB12mImVk9CWubG2OLCbCgBQO9GPuQnqXMKiwAcKDUT6xBbCxTNGzNkeajxe2xealCAF2Jj+aUabGOFYa/hH1AIrzgs/pAG1FH+d45e4IBjiP3djcEpjBTW8HQsPC8DC9NN/Q6fDGlWUgD9WRScgKYiVCR9du97y0eh26tjsCjsJyPEBlePy5r0pJvz+XXdl+VAsrz42VC55V2yrilAOZg0azeh8ORvnnXYZrh1yYs1JSWahZL53t4i7HBFSYwlTKxDu2PLk5ctl5tygmNmRZeaOvjCcWXTqfjeECwn3/LZzoqq+/ncv1cx0YcDICciqL0rOM3vDoG8Edt1kGjO3IPUtQ18oDszBBKHZ07GJxUN89ppw1Xdnlxu5N7EtVuBCOtyNje59bpoF4sYu3IL8EGrOMSWdrVuQnv7Ju/8+vhy</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>