<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="t21DC1" fieldKey="id" voucherCode="TC0" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc đơn hàng" e="Quick Quote Filtering"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D">
          <text v="Ngày từ/đến" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" aliasName="@DFDTo" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D" nextRow="false">
          <text v="" e=""></text>
        </field>
	    <field name="ma_gd" viewType="Combobox" valueDefault=""  hidden="false" label="1" field="1" disabled="false" >
          <text v="Giao dịch" e="Transaction Code"></text>
          <viewInfo>
            <options query="select ma_gd, ten_gd%l from dmgd where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
		<field name="ma_noi_di" viewType="Lookup" disabled="true" label="1" field="1" operation="like">
			<text v="Nơi đi" e="Origin "></text>
			<viewInfo lookupType="One" lookupId="vdmcangdi" lookupKey="(kkh_yn = 1 or hc_yn = 1) and status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_di" />
		</field>
		<field name="ten_noi_di" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field> 
		<field name="ma_noi_den" viewType="Lookup" disabled="true" label="1" field="1" operation="like">
			<text v="Nơi đến" e="Destination"></text>
			<viewInfo lookupType="One" lookupId="vdmcangden" lookupKey="(kkh_yn = 1 or hc_yn = 1) and status = 1" lookupCheck="1 = 1" lookupRef="ten_noi_den"  />
		</field>
		<field name="ten_noi_den" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
			<text v="" e=""></text>
		</field>  
		 <field name="so_ct" label="1" field="1" allowBlank="false" viewType="Lookup">
          <text v="Lấy số đơn hàng" e="Get a order number"></text>
          <viewInfo lookupType="one" lookupId="t11" lookupRef="ds_so_bg" lookupKey="ngay_ct between ![ngay_ct1]! and ![ngay_ct2]! and ma_noi_di like ![ma_noi_di]! +'%' and ma_noi_den like ![ma_noi_den]! +'%'  and status in (5,6) and ma_gd = ![ma_gd]!" lookupCheck="ma_kh = ![ma_kh]! and status in (1,6) and ma_nt = ![ma_nt]!" />
        </field>
        <field name="ds_so_bg" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
	
	
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>H6lgBu6hcsf2ESwZXzTk9HksYJCqfX+Gm5gPwiiEARbJ9L5Qn/Ea9rjLXbP22r81gGVynoE3ZJlzYD5wHn1VBJKU/MOPueXkeVfa+TlHf8vZ/RabkuC3Eh3D3s9a7APXaPWIPgwnd99RQfzOlpFS+igdzNoxtQyUhmpEQtZLQHNGwcKIpQ910iRKhre0u5VNJtstolfIjyNJnlSPriq9uQMXfhK9R8M12n1rr0aQIaeSmBPnlzb1BLcSpE1ZHTqMk6jBostXUl4vzNeQrFpqmjxdhpdlskhpna+pdDzbelCjCnX6iOYlpctlv7NYN+gHUEz0SxbrKQqnFR0w7QU+slnpYqVP6lvWZF1rc2/Zgbai8x/cwLIEGMSZAiNd44CA7Ere2jdhO0VL0xsk8/bOyalV0bv/7b1aHzyDbhcfFKIURoRBGfB+kdKZW90XwInli4D8TrBo1fIoYsPbg1adIdGVt35c+kkOanShfH6OHEVCmGteysjhnWwmVNkAKLcwM8Nq9X6yQV5C0152YF9rYfPDVqo+uKvugTL7tnrZ51WIY2XGMHWcdjNcoiEfpM3k0+rLzT6nU23fcEVLks8jjV4K/24CuBJ2aXHg050q/wk=</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>