<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="t311TC0" fieldKey="id" voucherCode="TT1" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc đơn hàng" e="Quick Quote Filtering"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D">
          <text v="Ngày từ/đến" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" aliasName="@DFDTo" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D" nextRow="false">
          <text v="" e=""></text>
        </field>
		<field name="ma_chungtu"  viewType="Lookup" label="1" field="1"  hidden="false" operation="like">
          <text v="Mã chuyến" e="Shipment Code"></text>
          <viewInfo lookupType="One" lookupId="dmchungtu" lookupKey="status = 1" lookupCheck="1=1" lookupRef="ten_ct" lookupInfo="dmchungtu|ma_chungtu|ten_ct" />
        </field>
        <field name="ten_ct" nextRow="false" fieldType="EX" readOnly="true" inactivate="true"  hidden="false" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
		<field name="ma_nv" clientDefault="true" viewType="Lookup" label="1" field="1"  setype="1" operation="like">
          <text v="Mã nhân viên" e="Employee Code"></text>
          <viewInfo lookupType="One" lookupId="dmnv" lookupKey="status in (5,7,9)" lookupCheck="1=1" lookupRef="ten_nv" lookupInfo="dmnv|ma_nv|ten_nv" />
        </field>
        <field name="ten_nv" clientDefault="true" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field> 
		 <field name="so_ct" label="1" field="1" allowBlank="false" viewType="Lookup">
          <text v="Lấy số chuyến hàng" e="Get a order number"></text>
          <viewInfo lookupType="one" lookupId="t21" lookupRef="ds_so_bg" lookupKey="ngay_ct between ![ngay_ct1]! and ![ngay_ct2]! and ma_chungtu like ![ma_chungtu]! +'%' and ma_nv like ![ma_nv]! +'%'" lookupCheck="1=1" />
        </field>
        <field name="ds_so_bg" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
	
	
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>o8nLBITyad0tXjgbxHxIQWLGgQI9OX4pcfAHcMzfO2QKpeV29ptB4yONvT6k6Y0hj0hkN5bnNJU/kVa0WzRso6m8KvxkT+BrOiv14tbzsLsXrmq4UemdfLE5Oha+X2yFos0fCr7YyScVBszUCtCpVKC+YptMjVyawBWDw7OKc9fcjfl2MCQQ/JXg1fEKd2RtW5BnMc3TN8wHmPJBPIETR2Gbs6HQ8szQl30fzcCAWRETC5BPwnFzjO/q8jRUaB4DqDsnTDUskL/ZFE5h2ynRgkyzfDkvMKTSunqJAsRpXA5TVZk6CC/LKulJSUjD2lP+ZC7BOspbHxLBUpdvB/L0Xz/SAOlDqdLusDAfMLHa7jWRkEGKyzM7UzVAO3AE+gscxCWtVMaPE0UM/b9+zSKROCnrtjOE7TvYiZnUl9zZyWi0nDIHOteAeiB3IqCAoETCYd5Fvlw+RfwfgdcMmyQgS3E/VcML5N6aFoG2AljIvwBFPJBSCsWarzDa40x2c4jjJqrZoT7qhrnINHeeBsrjzg==</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>