<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="thpkhTC1" fieldKey="id" voucherCode="AS1" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Điều kiện lọc" e="Filter conditions"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_thuchien1" label="1" field="1" aliasName="@DFDFrom" allowBlank="false" dataType="D">
          <text v="Ngày thực hiện từ/đến" e="Voucher Date"></text>
        </field>
        <field name="ngay_thuchien2" label="" field="1" allowBlank="false" inactivate="true" dataType="D" nextRow="false">
          <text v="Ngày đến" e="Voucher Date"></text>
        </field>
        <field name="unit_id" dataType="I" hidden="false" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>
		<field name="sl_phan" valueDefault="1000" label="1" dataType="I" field="[150]">
          <text v="SL đăng ký" e="Virtual account number"></text>
		</field>
      </fields>
    </form>

	
	
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>yXEG9niSTMY50sgZulKP+cYTgySO+0Br7VuXmNplCIpH4wq3NKZSTviyEOleiUfukXUVN3R5DcCeeBEwWY4vUinv+I+W7qz5zBEc9ofpa5cwIXFPaaQdvpJEl7v/UuyZgI8GVqAYt64Gd3UQ2HhyiDutachGOqvZFB0oqmmwjEN/cZlpgr9PdWz016UI2jdXz7PrSbAf95H8V+D7kFMwXeWUo/dzL7GLL4e0ISas5bdo3E+3UTR+nT62a1e0ceMdSkyKGivJo8Bb/3+3A6VI5L6YGwge3VR35MR1dWD1Es6KSqtQNpCf2hgmdorjaWvtst3IrYGIaMQh5yVbcyPQct+tAYhOJEqiV8FFcLsYkAyuEgjAuQgb4xA9hePlVKq3wPnHj6Zoau+R+M10skigcaemR6UEGsPXaYDoplL+d96WaURuIlImOZAOJ8vZ91OuRPCtQsU4NpwM/J45BDf6bopjyR0WVHqEVve3p0xxQSuRr2Ck9tRDnnL1Vqxhcsdm</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>