<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmkh" table="dmkh" fieldKey="ma_kh" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục khách hàng" e="List of customer"></title>
  <title0 v="Thêm" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120,120" >
      <fields>
        <field name="unit_id" dataType="I" hidden="true" readOnly="true" inactivate="true" label="1" field="1" importable="-1">
          <text v="" e=""></text>
        </field>
        <field name="ma_kh" format="U" label="1" field="1" viewType="AutoIncrease" allowBlank="false" fieldType="PK" importable="5">
          <text v="Mã khách hàng" e="Code"></text>
        </field>
        <field name="kh_yn" dataType="B" blank="1" clientDefault="true" label="1" field="[60]" nextRow="false" inactivate="true" importable="20">
          <text v="Khách hàng" e="Customer"></text>
        </field>
        <field name="ncc_yn" dataType="B" clientDefault="true" label="[100]" field="[60]" nextRow="false" inactivate="true" importable="25">
          <text v="Nhà cung cấp" e="Supplier"></text>
        </field>
        <field name="ten_kh" allowBlank="false" label="1" field="-" importWidth="250" importable="10">
          <text v="Tên khách hàng" e="Name"></text>
        </field>
        <field name="ten_kh2" label="1" field="-" importWidth="250" importable="15">
          <text v="Tên khác" e="Name 2"></text>
        </field>
        <field name="dia_chi" label="1" field="-" importWidth="250" importable="30">
          <text v="Địa chỉ" e="Address"></text>
        </field>
        <field name="ma_so_thue" label="1" field="2" importable="35">
          <text v="Mã số thuế" e="Tax Code"></text>
        </field>
        <field name="nguoi_lh" label="1" field="-" nextRow="false" importable="40">
          <text v="Người liên hệ" e="Contact"></text>
        </field>
        <field name="ma_nvbh" viewType="Lookup" label="1" field="1" clientDefault="true" importable="45">
          <text v="Nhân viên bán hàng" e="Employee"></text>
          <viewInfo lookupType="One" lookupId="dmnvbh" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_nvbh" lookupInfo="dmnvbh|ma_nvbh|ten_nvbh" importCheck="@@DF and z.status=1" />
        </field>
        <field name="ten_nvbh" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as " clientDefault="true">
          <text v="" e=""></text>
        </field>
        <field name="ma_tt" viewType="Lookup" label="1" field="1" importable="50">
          <text v="Mã thanh toán" e="Sale"></text>
          <viewInfo lookupType="One" lookupId="dmtt" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_tt" lookupInfo="dmtt|ma_tt|ten_tt" importCheck="@@DF and z.status=1"/>
        </field>
        <field name="ten_tt" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
        <field name="gioi_han_no" label="1" field="1" dataType="N" format="" importable="55">
          <text v="Giới hạn tiền nợ" e="Giới hạn tiền nợ"></text>
        </field>
        <field name="nh_kh1" viewType="Lookup" label="1" field="1" importable="60">
          <text v="Nhóm 1" e="Group 1"></text>
          <viewInfo lookupType="One" lookupId="dmnh" lookupKey="ma_loai_nh = 'KH1' and status=1" lookupCheck="ma_loai_nh = 'KH1'" lookupRef="ten_nh_kh1" lookupInfo="dmnh|ma_nh|ten_nh" importCheck="@@DF and z.ma_loai_nh = 'KH1' and z.status=1"/>
        </field>
        <field name="ten_nh_kh1" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
        <field name="nh_kh2" viewType="Lookup" label="1" field="1" importable="65">
          <text v="Nhóm 2" e="Group 2"></text>
          <viewInfo lookupType="One" lookupId="dmnh" lookupKey="ma_loai_nh = 'KH2' and status=1" lookupCheck="ma_loai_nh = 'KH2'" lookupRef="ten_nh_kh2" lookupInfo="dmnh|ma_nh|ten_nh" importCheck="@@DF and z.ma_loai_nh = 'KH2' and z.status=1"/>
        </field>
        <field name="ten_nh_kh2" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
        <field name="nh_kh3" viewType="Lookup" label="1" field="1" importable="70">
          <text v="Nhóm 3" e="Group 3"></text>
          <viewInfo lookupType="One" lookupId="dmnh" lookupKey="ma_loai_nh = 'KH3' and status=1" lookupCheck="ma_loai_nh = 'KH3'" lookupRef="ten_nh_kh3" lookupInfo="dmnh|ma_nh|ten_nh" importCheck="@@DF and z.ma_loai_nh = 'KH3' and z.status=1"/>
        </field>
        <field name="ten_nh_kh3" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
        <field name="rg_code" format="U" viewType="Lookup" label="1" field="1" clientDefault="true" importable="75">
          <text v="Khu vực" e="Region Code"></text>
          <viewInfo lookupType="One" lookupId="sysregioninfo" lookupKey="status=1" lookupCheck="1=1" lookupRef="rgname" lookupInfo="sysregioninfo|rg_code|rgname" importCheck="@@DF and z.status=1"/>
        </field>
        <field name="rgname" nextRow="false" fieldType="EX" readOnly="true" clientDefault="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
        <field name="dien_thoai" label="1" field="2" importable="80">
          <text v="Điện thoại" e="Phone"></text>
        </field>
        <field name="fax" label="1" field="-" nextRow="false" importable="85">
          <text v="Fax" e="Fax"></text>
        </field>
        <field name="e_mail" label="1" field="2" importable="90">
          <text v="Thư" e="Email"></text>
        </field>
        <field name="home_page" label="1" field="-" nextRow="false" importWidth="150" importable="95">
          <text v="Trang chủ" e="Home Page"></text>
        </field>
        <field name="ghi_chu" label="1" field="-" rows="2" inactivate="true" importWidth="250" importable="100">
          <text v="Ghi chú" e="Notes"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" label="1" field="2" valueDefault="1" importable="-1">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>jetQ/1mS9SgCdjoGT1R/Y9DkZfQXXshxv3cCf9DH8ADwOo5YhoodvGss4zAUZJSMZazHFI3KSZPBTWnBK2X6+HpyueZ0aZdK4WPoUDOuiGRx32y+rwzg3Z5uMvbDuUa4QQvTru/PwA4LZ3MaRRNavv+KNgq7e4+Mz0IG6+nKTSPj1mvf/M8fFVLKPW0Foiktmrz8YeQCRIGdrLluDlsyuauELHBlbCk/wb+9OFksUKJ4mBNZ0Wv4PCSKQGynHX2gE7h5TufKu2BZ9YuqMC7lfw==</enc>]]>
    </text>
  </js>

  <script>
    
    <query>
      <text>
        <![CDATA[<enc>iW+MwpbVYdGJDu1NI8DWbeeHIkMGYcUEJiMsNAg6qiO8/uGj5nuIH+ENTFDPmIGSc2NQPC8t0lTS64GaglPN/hbPcnxGdYWBgNY1AgYeRSLeXJgMviCgrw3m4URq0ypavYD2junWPDFlnFWIox8YXIwUS7pPA4moPHiIOiC+AuHCSPmr4tDguV9BTZdWMJCKsSDjSloQ6hvp78o9ryGapRCUMeBm1avY1U5RUwXw5/BFNYpwhtveV0JMVazTuywzSnI9seF1lLyEdd8O44FAiYVYEWb3yqBFF4kcu0Ey1zs93hHrUpuNg3vJw3zpM/wSBuDnJ8n20oxEf60vDglFAQ86U6RRKSPEDx4zFmbTosUKUCcE9uRs3Spgc9NSNAX3</enc>]]>
      </text>
    </query>
    <inserting>
      <text>
        <![CDATA[<enc>/T/6v4fr7JtuEWROY5bEopFO1HCnIjtZjFzzDG3F9/vEkIfRrRIYFlNT+1c2A+G4DGK3P1V1ru+z1kGXJXjR1VzP1TAM3KziUQ39S5UPAFO5TtFkd+A7rjU9Cj84+ron+NnAUl09CZS+jY4xst+ifUx/y0L2N86LSRXXWB0b2jLk9z1JyBTjpFwFo33O8/V92Jll9ZnIKloIczVnEYCl2/5Q4n5X9mE3/5atjZjvFut8hbyHb/wqOO6O7YgIZzpT</enc>]]>
      </text>
    </inserting>
    <aftersave>
      <text>
        <![CDATA[<enc>++V3V+E3NWH5wDFlTZgrSGbjNHJkVDS0vmsm1GR080eRHXmaYAHQCJloa1DZ2hAHX7Ul/SMrxMMA01pu0hKJuqh9ZZF8e5TF2ZR2GgJ/z+ukFomP5R6dNCYdzgWq8JWXAPilrl4x6jMYnwD1yXajgb4uRJRW3SuHjGaXxQm8QWEQV5UJ7DiV8FJhOPdV9FLF</enc>]]>
      </text>
    </aftersave>


    <importing>
      <text>
        <![CDATA[<enc>sxD5Swu0R4mcxEHdwcy2yi46ZbQRyi0uEDh1tGVfNVOBZJeZZHskWnswm55XGvVMtI3kJxA271ZmaBNQ7vOM1svvmG7tRC9SwsrihBxLjQw=</enc>]]>
      </text>

    </importing>
  </script>

  <messages>
    <message val="codeExistsNewMsg">
      <text v="Mã khách hàng đã tồn tại trong danh mục khách hàng." e="The record already exists."/>
    </message>
    <message val="codeExistsEditMsg">
      <text v="Mã khách hàng đã tồn tại trong danh mục khách hàng." e="The record already exists."/>
    </message>
    <message val="taxtCodeExists">
      <text v="Mã số thuế đã tồn tại trong danh mục, &lt;span class='Highlight'&gt;Lưu ý:&lt;/span&gt; hệ thống vẫn lưu dữ liệu vừa cập nhật." e="The tax code is already exists, &lt;span class='Highlight'&gt;Warning:&lt;/span&gt; Updated data has been saved."/>
    </message>
  </messages>
</dir>