<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmkho" table="dmkho" fieldKey="ma_kho" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục bộ phận" e="Department List"></title>
  <title0 v="Thêm mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
        <field name="unit_id" dataType="I" hidden="true" readOnly="true" inactivate="true" label="1" field="1">
          <text v="" e=""></text>
        </field>
        <field name="ma_unit" viewType="Lookup" fieldType="EXParam" readOnly="false" label="1" field="1" allowBlank="false">
          <text v="Đơn vị" e="Unit"></text>
          <viewInfo lookupType="One" lookupId="sysunit" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_unit" lookupInfo="sysunit|ma_unit|ten_unit" />
        </field>
        <field name="ten_unit" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
        <field name="ma_kho" format="U" label="1" field="1" allowBlank="false" fieldType="PK" >
          <text v="Mã kho" e="Site Code"></text>
        </field>
        <field name="ten_kho" label="1" field="-" allowBlank="false" fieldType="PK" >
          <text v="Tên kho" e="Description"></text>
        </field>
        <field name="ten_kho2" label="1" field="-">
          <text v="Tên khác" e="Other name"></text>
        </field>

        <field name="vi_tri_yn" dataType="B" clientDefault="true" valueDefault="0" label="1" field="[60]">
          <text v="Vị trí" e="Location"></text>
        </field>
        <field name="dai_ly_yn" dataType="B" clientDefault="true" valueDefault="0" label="1" field="[60]">
          <text v="Đại lý" e="Agent"></text>
        </field>
        <field name="ma_nh" viewType="Lookup" label="1" field="1">
          <text v="Nhóm kho" e="Site Group"></text>
          <viewInfo lookupType="One" lookupId="dmnh" lookupKey="ma_loai_nh = 'NKH' and status=1" lookupCheck="ma_loai_nh = 'NKH'" lookupRef="ten_nh" lookupInfo="dmnh|ma_nh|ten_nh" />
        </field>
        <field name="ten_nh" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>

        <field name="ghi_chu" rows="3" label="1" field="-" >
          <text v="Ghi chú" e="Notes"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>Knm6eCC/JR/e71MIbEUVyRwDGWt1e7Fg8ClLxEirrRNfZ7MwifI+DWVTfKX9fTTjzwv7zj4ITsY/0taLEF340X8iyaEGxPXisxlQaIhDupjlWUx7jjTLynN+nhyAJYzhkXDT9FxCTlf9pO/AEVLu6uVsgyxAkpIhngfhxsgRwt0w3HTXwWkn9TzrNjDtNoQv</enc>]]>
    </text>
  </js>
  
  <script>

    <query>
      <text>
        <![CDATA[<enc>9f1U6YGooAD/ahbpLaNsSHyE0S/SratPtk8AShhJK9pekWEt+swZdJ4S2uuv/TawWzZKvNZMYyQK6Ha9bb6amWRENM405VBZzBkYjI6+pXWvbHDyivoUN8QVetaADhpXX3UmgFsg2NJXJ1/YYVPHEVqlKUNeH+322jNJuEnzZHULbNWIC50gM4lbXlMfb3eCSzg/WlhdZZ4SNguHLj8FKpjUP/ntoByx6DaYAFklAm4pSdybV1jHC3wgFi6lKMGOkXW9BbiwxndZR1YOhh9Lqg==</enc>]]>
      </text>
    </query>
    
    <beforesave>
      <text>
        <![CDATA[<enc>GJgBVkOd9xy3In+SUACpOAX36I7LHdlCWd3wW+ezqekhnpBfBkJ3Cq8KmwzZKe7/AYwf3KxQjjmepz89VAdWL7UYyPJysyqX07UV50z8n9w=</enc>]]>
      </text>
    </beforesave>
    
  </script>

  <messages>
    <message val="codeExistsNewMsg">
      <text v="Mã kho hàng đã có trong danh mục kho hàng." e="The site is already exists."/>
    </message>
    <message val="codeExistsEditMsg">
      <text v="Mã kho hàng đã có trong danh mục kho hàng." e="The site is already exists."/>
    </message>
  </messages>

</dir>