<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="allallsmailApprove" dirViewType="Grid" selectMultiple="Table" voucherCode="HU0" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Duyệt kế hoạch gửi mail" e="Approve Plan Send Mail"></title>
  <subtitle v="Xử lý &lt;b&gt;%s&lt;/b&gt; hoàn ứng" e="Process &lt;b&gt;%s&lt;/b&gt; Reimbursement"></subtitle>

  <grids>
    <grid table="allsmail" fieldKey="id" order="ngay_ct desc" key="xstatus = 0" allowFilter="true" allowOrder="true">
      <fields>
	    <field name="unit_id" hidden="true" dataType="I" width="120" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
	   <field name="ma_unit" width="120" fieldType="EX" >
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="ten_unit" width="200" fieldType="EX" hidden="true">
          <text v="Tên đơn vị" e="Unit Name"></text>
        </field>
        <field name="so_ct" width="100" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="120" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
		<field name="s_mail" width="400" >
          <text v="Mail gửi" e="Mail Sent"></text>
        </field>
        <field name="title" width="400" >
          <text v="Tiêu đề" e="Subject"></text>
        </field>
		<field name="ds_mail" width="400" >
          <text v="D/s mail" e="Mail Sent"></text>
        </field>
        <field name="email_body" width="500" >
          <text v="Nội dung" e="Body"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
		<field name="imageisf" width="100" fieldType="EX" hidden="true">
          <text v="Hình ảnh" e="Image"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      <buttons>
        <button id="approve">
          <text v="Duyệt" e="Approve"></text>
        </button>
        <button id="cancel">
          <text v="Hủy" e="Close"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="find">
          <text v="$FindToolbar" e="$FindToolbar"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="refresh">
          <text v="$RefreshToolbar" e="$RefreshToolbar"></text>
        </button>
        <button id="freeze">
          <text v="$FreezeToolbar" e="$FreezeToolbar"></text>
        </button>
      </buttons>

      <script>
        <query>
          <text>
            <![CDATA[<enc>KB8xqdyii61Ha3yaQfUGVW9aXW+cG5N/lZsgL0IvoZ9YzkyLseC64y1KW7OCNXhnurkRk8w2Ka8Y0qySBHhCkFdte29bzWPUlW4ha8ed+rDBpYEgKACTTLR7srOKd2YmPX1lbXpt/UksKJmUiuZW3zbM1K4MT5wB98482PoAASO8cwt9hlblQeL/PY2pDOxE48eqVDiJm20GViX+OcQiFqUgFK8k2e1DWnqiv35uZkE2wqhuA1r3ynsSiJXs5TvihplK7UITkoCgxLRtrVaoTpcOX0TxQbgQB+1kd2cfBMc=</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>qaqhMclEi1tYl22H/QLox6hiKDqwUkNyAPaKDvoRJerNeaFFF6de/igEDjJwi0uPmQF0FlYJszk0CTwF594gTzkVNgjkW2gnPPGHm+Y7W8DQzLG92GCQ/Ar4d9wI9v1kSgR6a6sljRoDSsZpFjRmhqWvsDntzi5LO0EoA1GIoSD5vJ+vWt3JgA6Ho22I9WCOeJ0wc0ELxH++uI9RTO7aQMk2R2vqdMprIkgfQgefl/K7UoR6Ft9EjJIbR/p4h+/rMOpMo7JRoQwruAz0sGe81kh3HxKTT/y7HqqH3JKyU+5dTY7EGLlKuysWSnYvmLLv6RaDJRrPmEEFODXm17WNqNdkEe7caaoMQQB9UTwi0CrxuiDfr9Bm0hWRLPTUZ5J9vv+uW1v0YOC1CWlZtpH0b2HU1yOHzVjgDkifpG8sO7Sx/YvOBfZlPoW5Tix2ME/uDp4lDoKE4wUwuWSs7EfMtw==</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>6CMkmSRkyZV4MrafDhzUmZQx7JpRkw4n3PJFbGJ9IuxMv4/l8FsSP1N4BrYHMUf9dVLyouVjaS1ehUMhJ7JVs2/9byeKqxRnVY9YPh9Gcp710lu4CjM3K4hM6mnyi3dTM50eQwo+ZpaXuCb81HWCcS7IZm6IC2N0WZQ0V0Ieb2s6UYX7mIMj2hWNdFSNxPHxKNY1hbxEDZNvDTGStWU6SiOL2yiIDNhzW/+B4kbtC8gwXbFyeRf3vYTQArEltfjBdZyP9clBLDAH7m6Fdey3S4dQfDnvwHJ1W/h/MUtauPXN2YMRGlfr1MgxSarVmMtsVohkMGmCkv1SaNAG1akirHMRGsYW51J3NKdRbB8HFLTW3x3N8tP3+v+f7a6LgPvLzM8VoEiogQ0XtnwowhB9pe1WpchAY28QvUp4cpkatQxtMdA3rqxFlw+0yoB69+8oxqAOm2KzJ4W9GF2vz68k/iJsz/YUStu7nk+vBVprhkFm2qMOWY8VGguT1PzhIqDWSy6xxVuCryGIpbo5xV4kZvhNmvIkcODF0+cTl6kcV1/q46QLl9UJopYXoUAIXm81g6ykaL+2wL+AmlBL2Jz/DiOUGT8ytXXwWuWm+TaWiQ/WmNud5wEsG7V3Hw5X7HCLuvQrf6DoywQ+X/TV1fwcaASlPQ2a+KTEd2ma64OfxA4Xpg7HFiCCMppSobtQ8MkqSHYK4FLovAC8IactgZkx/vf9RsIlkTEarqsAFEXn8voRsCo6rVBy/XvAGHuO08xhZmTZ0vKP1yLbWyGK+YkHsogzrm7HcpZXg0lCNYHODkyar/oN1J4fT1oMgy6B+IwZERnypVsKppYFpn7zZe4C9Y7WYyOGy1Gyf8i4dhF3S01U1j3f9EtZ77zoE0qPdlbJl5xvtrX5kTlRf6YOujiOMxKGit/y3M6ltsTzChvy7ZYNqocv/80geRlHbgdQEFU7</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
  <script>
    <request code="Approve" transaction="true">
      <text>
        <![CDATA[<enc>7pqWwM9j1eqUH7ew99HhBvT1JMfZ13a8zO8sryytRTS9oeiyWdzO6yuvQ7Q9CpFg3bc5Y5PPhVsf0mnq1rwrtMMbLAAbHLPttPu6ZQLiRHvrlV6ceSj9D1BWHvzXJIJaNXipJvSUR3mzTHf8lCIgxAZtzZkcQgfz5LLBlXR+jiPXwqEt6VwIXnjaeyiNdADGqUeWkZm5CEWyRfyQLNg8u7lIMKmohksi5nK5qp9k2rsufsXSDMhrPoJMQkafLfzzwNsAWT0UzVn4J+i932lTOTd5ZRVXAygSbu2BAhFMXBQpoTQ5oCyEVqxicMPAKVKMRlx7xljBaSHfosR3VZOCLJhjBHOjuXmiWeUprP/Kb6OQI73YsViJMAYPWwDSyYULptVlhAkeHbS1kL9OgubtPZEjkGwXsyB2/U8SELiJiYAt7LWhKpraCjn6TG1qgjRR</enc>]]>
      </text>
    </request>
    <request code="Close" transaction="true">
      <text>
        <![CDATA[<enc>ioe1NL6g7xhbKcfdIzKlL+kbFMbAcsrw9ASbuzNuDV8j5S55nkat9YbiDh5klGbks0keUQnm9r0eix73Yale5kinuY4RAlwj7ZGH6WjgV4CyHI5ZvMsMPckX9EKnTyd1EOYw1HALhm7OzaXkN0VqliaRQvTKStWfTckM8+T9d4p+tIblSU9CQ6qqFL9PbHpMw6aV3o3Fu7HViXs2X/7f7hr3B7N0JXItO0nN2mVEq9VsVUYDzL6YWoN9zgIAYkYY</enc>]]>
      </text>
    </request>

    &VoucherJSLoading;
  </script>

  <messages>
    <message val="msg1">
      <text v="Bạn có chắc chắn sẽ &lt;b&gt;duyệt&lt;/b&gt; các phiếu được chọn không?" e=""/>
    </message>
    <message val="msg2">
      <text v="Bạn có chắc chắn sẽ &lt;b&gt;bỏ duyệt&lt;/b&gt; các phiếu được chọn trở về trạng thái [Chờ duyệt] không?" e=""/>
    </message>
    <message val="msg3">
      <text v="Bạn có chắc chắn sẽ &lt;b&gt;bỏ đóng&lt;/b&gt; các phiếu được chọn trở về trạng thái [Đã duyệt] không?" e=""/>
    </message>
    <message val="close">
      <text v="Hủy/đóng" e="Close"/>
    </message>
    <message val="approve">
      <text v="Duyệt" e="Approve"/>
    </message>
    <message val="undo">
      <text v="Bỏ duyệt" e="Undo"/>
    </message>
    <message val="open">
      <text v="Bỏ đóng" e="Open &amp; Approve"/>
    </message>
      <message val="inputTitle">
      <text v="Nhập lý do hủy hoàn ứng " e=""/>
    </message>
    <message val="reason">
      <text v="Lý do" e="Reason"/>
    </message>
  </messages>
</dir>