<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridReport.xml">
]>

<dir id="bctk" dirViewType="Grid" dirObjectType="Report" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Báo cáo tồn kho" e="Stock" />
  <subtitle v="Đến ngày {ngay_ct1}..." e="Date To {ngay_ct1}..."></subtitle>
  <grids>
    <grid>
      <fields>
        <field name="ma_kho" width="100">
          <text v="Mã kho" e="Site"></text>
        </field>
		<field name="ten_kho" width="250">
          <text v="Tên kho" e="Warehouse"></text>
        </field>
        <field name="ma_vt" width="100">
          <text v="Mã hàng hóa" e="Goods Code"></text>
        </field>
        <field name="ten_vt" width="250">
          <text v="Tên hàng hóa" e="Goods Name"></text>
        </field>

        <field name="ton_cuoi" dataType="N" format="Qty" width="100">
          <text v="Tồn cuối" e="Closing Q'ty"></text>
        </field>
        <field name="du_cuoi_nt" dataType="N" format="FCAmount" width="100">
          <text v="Dư cuối nt" e="FC Closing Amt."></text>
        </field>
        <field name="du_cuoi" dataType="N" format="Amount" width="100">
          <text v="Dư cuối" e="Closing Amt."></text>
        </field>
      </fields>

      &DefaultButton;
    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>pYwA8X42IeIiB9QO4FsgUJl92gojriqrz8Rg6PIOhepYpRjkUlXFWVp5OVjRi7dpdxKq3wo6m2ne7iL3RKE+fqrjRg/4gDFR5q1mbj6qHg63qT3v6JRl0nUAnEUVUYy1iekEmWwpYbe/6UmFG+0TKnkdsqupy4WdjWRSz8G3mOvyg9+f1dQZyeHXpmXvODWEy/fWDSdNKFnYpaA9nzZQcIRQR6d9/wzTn7aBWhMgVUrT4/b3/ZwyqVdSOFGpNC/udRt1z4/imb6c4wxWH0tWubEDrZMp3cgmPss+lfM25FDg6knFZR+qBdfmGaUsaieBoqjGwQVf/c59QySiul3tSHqaRMDIpfjzsIMqe3Jfhts=</enc>]]>
    </text>
  </js>
<css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
</dir>