<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridReport.xml">
]>

<dir id="bkcthd" dirViewType="Grid" dirObjectType="Report" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Bảng kê chi tiết hóa đơn bán hàng" e="Detailed list of sales invoices"></title>
  <subtitle v="Từ ngày {ngay_ct1} đến ngày {ngay_ct2}..." e="From {ngay_ct1} To {ngay_ct2}..."></subtitle>
  <grids>
    <grid>
      <fields>
        <field name="ma_unit" width="80" aliasName="d" join="left join sysunit d on a.unit_id = d.unit_id" >
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="ngay_ct" width="100" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
        <field name="so_ct" width="100" link="V" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ma_kh" width="100">
          <text v="Mã khách hàng" e="Customer Code"></text>
        </field>
        <field name="ten_kh" width="250" aliasName="b" join="left join dmkh b on a.ma_kh = b.ma_kh">
          <text v="Tên khách hàng" e="Customer Name"></text>
        </field>
        <field name="dien_giai" width="250">
          <text v="Diễn giải" e="Description"></text>
        </field>
        <field name="ma_vt" width="100">
          <text v="Mã hàng hóa" e="Goods Code"></text>
        </field>
        <field name="ten_vt" width="250" aliasName="c" join="left join dmvt c on a.ma_vt = c.ma_vt">
          <text v="Tên hàng hóa" e="Goods Name"></text>
        </field>
        <field name="dvt" width="50">
          <text v="Đvt" e="UOM"></text>
        </field>
        <field name="so_luong_vc" dataType="N" format="Qty" width="100" aliasName="f" join="left join d55 f on a.id = f.id and a.line = f.line">
           <text v="Số lượng vận chuyển" e="Trans Quantity"></text>
        </field>
		
		 <field name="so_luong_hh" dataType="N" format="Qty" width="100" aliasName="f"  >
           <text v="Số lượng hao hụt" e="Quantity of loss"></text>
        </field>
		 <field name="sl_xuat" dataType="N" format="Qty" width="100">
          <text v="Số lượng thực tế" e="Quantity"></text>
        </field>
        <field name="gia_nt2" dataType="N" format="FCPrice" width="100">
          <text v="Giá bán nt" e="FC Price"></text>
        </field>
        <field name="tien_nt2" dataType="N" format="FCAmount" width="100">
          <text v="Doanh thu nt" e="FC Turnover"></text>
        </field>
        <field name="thue_nt" dataType="N" format="FCAmount" width="100">
          <text v="Thuế nt" e="FC Tax Amt."></text>
        </field>
        <field name="ck_nt" dataType="N" format="FCAmount" width="100">
          <text v="Chiết khấu nt" e="FC Discount Amt."></text>
        </field>
        <field name="pt_nt" dataType="N" format="FCAmount" width="100">
          <text v="Phải thu nt" e="FC Receivable Amt."></text>
        </field>
        <field name="gia_nt" dataType="N" format="FCPrice" width="100">
          <text v="Giá vốn nt" e="FC Cogs"></text>
        </field>
        <field name="tien_nt_xuat" dataType="N" format="FCAmount" width="100">
          <text v="Tiền vốn nt" e="FC Cogs Amt."></text>
        </field>
        <field name="ma_nt" width="60">
          <text v="Mã nt" e="FC Code"></text>
        </field>
        <field name="ty_gia" dataType="N" format="ExRate" width="100">
          <text v="Tỷ giá" e="Exchange Rate"></text>
        </field>
        <field name="gia2" dataType="N" format="Price" width="100">
          <text v="Giá bán" e="Price"></text>
        </field>
        <field name="tien2" dataType="N" format="Amount" width="100">
          <text v="Doanh thu" e="Turnover"></text>
        </field>
        <field name="thue" dataType="N" format="Amount" width="100">
          <text v="Thuế" e="Tax Amt."></text>
        </field>
        <field name="ck" dataType="N" format="Amount" width="100">
          <text v="Chiết khấu" e="Discount Amt."></text>
        </field>
        <field name="pt" dataType="N" format="Amount" width="100">
          <text v="Phải thu" e="Receivable Amt."></text>
        </field>
        <field name="gia" dataType="N" format="Price" width="0">
          <text v="Giá vốn" e="Cogs"></text>
        </field>
        <field name="tien_xuat" dataType="N" format="Amount" width="0">
          <text v="Tiền vốn" e="Cogs Amt."></text>
        </field>
        <field name="ma_kho" width="0" >
          <text v="Mã kho" e="Site"></text>
        </field>
        <field name="ma_bp" width="0" >
          <text v="Mã bộ phận" e="Department"></text>
        </field>
        <field name="ma_vv" width="0" >
          <text v="Mã vụ việc" e="Job"></text>
        </field>

        <field name="unit_id" dataType="I" hidden="true" width="100" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="id" dataType="I" hidden="true" width="100" >
          <text v="ID" e="ID"></text>
        </field>
		<field name="line" dataType="I" hidden="true" width="100" >
          <text v="Line" e="Line"></text>
        </field>
        <field name="ma_ct" width="100" hidden="true">
          <text v="Mã chứng từ" e="VC Code"></text>
        </field>
      </fields>

      &DefaultButton;
    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>HdmDGG94HYBhyGjL/tgXc9wYLjGZhMis6Z+4UauU5w0H8j2B0fXGkjRjxHOhOYUnDuSWsPKrFdOE2roVBMijXZl0DHeX9xHip/zpS74L4dTrv69GkkqyJyyw4mUWsJ3uqBQN1oLXHBYhLO1mpxmlak+zhX9OlWGBBfZOmWge8O+WCTWst+SDmE/asPc8x37lI59iI7WSeCHAbVYFQ2fuUazBLkRsnLHFpVk4suo1j1RfKC8QZ/kRCHjp95Is32Qt3pQBnqiBRpxV11TzZ8/u+6z6DfIH1SRUSt6nsDPytCm0ss3KX6+EB56OcmT4zcnZ5E+VQykxE25Dj3tRT/0njLDvvSfKb5BVEEMuFG3PAr+o16kYYIwq7y7jzJ8Auqbjj0B/MZn8wnKDoMiRviyTog==</enc>]]>
    </text>
  </js>
   <css>
    <text>
		<![CDATA[<enc>nRVQr8m62Vh+aFddZ4BstdkubgX5HMu2EJ1AdJiqIaGFiQym1g9S6q4+lwVIkHq2gGpWCxsZbipT3tMtrvFmp/e81RKmYn8CNYWFccGgs38/sc90DztIKHAlv2JblpKO36oBFbr/zKFKKpibg75FbPBCCv/sc9utXRvi4f/PUOy6uSdeaOhdV4fR3z+lEXfXefEEPhDMgMrTITxaId74x8b9TRcmlfLiQ9T9Zy0EpJIrIP0N7YlWjevD7S1VGVRa2xNCAgpp+uHyOpA/RKce/drgyg0TG/6t6GOXJWLcFupFRGMFgMKi0GfX5R6X+a05L0t3G9LOcsKhy0/qvIIWZvvZgEO1QWPw59p9pS08PduOOCjuYo3duZ99XewfBjJp</enc>]]>
    </text>
  </css>
  <script>
    <processing>
      <text>
        <![CDATA[<enc>QHmXXqmGz0knX3SA1x63zK5dSohybJ2JIk46psBsvh3e8ug8B4S6eKjLn7U7T4KDDlWJm8PWH5BJNSDoQF+amVw2x/MXL6MXs93Xzl0flxWApJyjYTcX1BpGhf+bgSUL1nB0Hvz4QoVnPt5Pxh8rDdSoJu1QQBGh5rDJH5LvmN/fVblFM4a/vNP/z9ofHtkt</enc>]]>
      </text>
    </processing>
  </script>
</dir>