<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridReport.xml">
]>

<dir id="bkdvvt" dirViewType="Grid" dirObjectType="Report" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Bảng kê vận tải hàng hóa" e="Cargo transport list"></title>
  <subtitle v="Từ ngày {ngay_ct1} đến ngày {ngay_ct2}..." e="From {ngay_ct1} To {ngay_ct2}..."></subtitle>
  <grids>
    <grid>
      <fields>
        <field name="ma_unit" width="80" aliasName="d" join="left join sysunit d on a.unit_id = d.unit_id" >
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="ngay_ct" width="100" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
        <field name="so_ct" width="100" link="V" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ma_kh" width="100">
          <text v="Mã khách hàng" e="Customer Code"></text>
        </field>
        <field name="ten_kh" width="250" aliasName="b" join="left join dmkh b on a.ma_kh = b.ma_kh">
          <text v="Tên khách hàng" e="Customer Name"></text>
        </field>
		 <field name="ma_dvvt" width="100">
          <text v="Mã đơn vị vận tải" e="Trans Code"></text>
        </field>
        <field name="ten_dvvt" width="250" aliasName="C" join="left join dmdvvt C on a.ma_dvvt = C.ma_dvvt">
          <text v="Tên đơn vị vận tải" e="Trans Name"></text>
        </field>
        <field name="dien_giai" width="250">
          <text v="Diễn giải" e="Description"></text>
        </field>
       
        <field name="t_so_luong" dataType="N" format="Qty" width="100">
          <text v="Số lượng" e="Quantity"></text>
        </field>
        <field name="t_tt" dataType="N" format="FCPrice" width="100">
          <text v="Tiền vận chuyển" e="FC Price"></text>
        </field>
              

        <field name="unit_id" dataType="I" hidden="true" width="100" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="id" dataType="I" hidden="true" width="100" >
          <text v="ID" e="ID"></text>
        </field>
        <field name="ma_ct" width="100" hidden="true">
          <text v="Mã chứng từ" e="VC Code"></text>
        </field>
      </fields>

      &DefaultButton;
    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>HdmDGG94HYBhyGjL/tgXczJ7jASyyvGnj0xyvg4txu4tmxE5gLzJO70dKl3JcqwWn2L6DFbq2WAwDYvH0gQycSctUfOKZm7mcl/kU3ihORe6ZeH3D5P92OQwyLxzdnwzMI8w9QO/T+SDrJ0yXngQGXxDmMWZfBwwUAIvrH75GTERd1k/3HizQDmMC+fPBFvjCk1HZ+OuR03gDSfwK3SOZb3NDxOXC/4vUSpm7bUVjw7Q8y0C8lpY/BApzntRAfO33GUDjopRcPSosBIMKx2e0tre8HnHelIeWc74i/G8SosVItOmEHvDSpz2enoWkGHTb8t5qEak7zUzLjb/0HwE6PByl4gQ4+qGI38XturI/j8p0shlDWbmeYQhjLbF1Y3ZzvRTUVZ2W1OLf0teCU+ToQ==</enc>]]>
    </text>
  </js>
   <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
  <script>
    <processing>
      <text>
        <![CDATA[<enc>912QYdhqFaoxmTwymwtxUjKz0WYVgmA6IgZGVOtqQ3PlUgUngYO9XHd2SrevJnWOyI/0mCi85jiXYBiKZAxCPzuSM/DElPP5Ht7z3pVpQhJmmFdjVfN8Wf9PuyzJ+k3Dlq+V+7oTOMmxJ79h8TsIVHpQjy9J2ZmWWNTXVNKRJwE=</enc>]]>
      </text>
    </processing>
  </script>
</dir>