<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridFinding.xml">
]>

<dir id="cdkh" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Vào đầu kỳ công nợ khách hàng" e="Customer Opening Balance"></title>
  <subtitle v="Năm {nam}..." e="Year {nam}..."></subtitle>
  <grids>
    <grid table="cdkh" fieldKey="nam,unit_id,ma_kh" order="ma_kh" allowFilter="true" allowOrder="true" key="unit_id = @@unit" >
      <fields>
        <field name="nam" width="100" fieldType="PK" hidden="true" format="-1" dataType="I">
          <text v="" e=""></text>
        </field>
        <field name="unit_id" width="100" fieldType="PK" hidden="true" format="-1" dataType="I">
          <text v="" e=""></text>
        </field>
        <field name="ma_kh" fieldType="PK" width="100">
          <text v="Mã kh/ncc" e="Code"></text>
        </field>
        <field name="ten_kh" width="250" fieldType="EX" aliasName="b">
          <text v="Tên kh/ncc" e="Description"></text>
        </field>

        <field name="du_no0" width="120" dataType="N" format="0">
          <text v="Dư nợ" e="Debit Balance"></text>
        </field>
        <field name="du_co0" width="120" dataType="N" format="0">
          <text v="Dư có" e="Credit Balance"></text>
        </field>
        <field name="du_no_nt0" width="120" dataType="N" format="0">
          <text v="Dư nợ nt" e="FC Dr. Balance"></text>
        </field>
        <field name="du_co_nt0"  width="120" dataType="N" format="0">
          <text v="Dư có nt" e="FC Cr. Balance"></text>
        </field>
      </fields>

      &DefaultButton;
      <script>
        <query>
          <text>
            <![CDATA[<enc>Yls3K44UFNxlo+SbFjnvdxCuiSyNQs9+NaWN7soYzQfGAZ/gkEaHQ4di5YcM2M5yTAwKAL2NFXEnC6GXGwf6yOsMuYK6YPTxRg9/MPgirtFHzU1St/uZgfbTpRr4XQG1GVSzwdeni1y211LoFwUhT4IgJvldD7j+ZmtkHr8EsgSagrCk+/oTq2zzyJiA3c3qnbQ3ioDXwT4TnPIealnDTXb7TdFknXlB1wi9eWapoQbN3JSeGNDU0Tqrgdky6sQwcIIhyo52QSifMA5TbW/0/A==</enc>]]>
          </text>
        </query>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>/P9Shux7F0Mmh7E260+hpQI/ojPgqqtk0ke3z3Or5q3GY/4VOXqvQh8za56YEfgSB6FK/0Plgu2RvhpGYeHItQ5M8aoAYSsl58D2w/aySXOtTa3SUm8KQHgJm/qaHxqyHofHiWi/Qp0EBH8XcporYWNbWSHiYnsqbWMracr3ppElwuk/hqb3Jexi/8CF8Jl4</enc>]]>
    </text>
  </js>
   <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
</dir>