<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridFinding.xml">
]>

<dir id="cdncc" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Vào đầu kỳ công nợ nhà cung cấp" e="Customer Opening Balance"></title>
  <subtitle v="Năm {nam}..." e="Year {nam}..."></subtitle>
  <grids>
    <grid table="cdncc" fieldKey="nam,unit_id,ma_kh" order="ma_kh" allowFilter="true" allowOrder="true" key="unit_id = @@unit" >
      <fields>
        <field name="nam" width="100" fieldType="PK" hidden="true" format="-1" dataType="I">
          <text v="" e=""></text>
        </field>
        <field name="unit_id" width="100" fieldType="PK" hidden="true" format="-1" dataType="I">
          <text v="" e=""></text>
        </field>
        <field name="ma_kh" fieldType="PK" width="100">
          <text v="Mã kh/ncc" e="Code"></text>
        </field>
        <field name="ten_kh" width="250" fieldType="EX" aliasName="b">
          <text v="Tên kh/ncc" e="Description"></text>
        </field>

        <field name="du_no0" width="120" dataType="N" format="0">
          <text v="Dư nợ" e="Debit Balance"></text>
        </field>
        <field name="du_co0" width="120" dataType="N" format="0">
          <text v="Dư có" e="Credit Balance"></text>
        </field>
        <field name="du_no_nt0" width="120" dataType="N" format="0">
          <text v="Dư nợ nt" e="FC Dr. Balance"></text>
        </field>
        <field name="du_co_nt0"  width="120" dataType="N" format="0">
          <text v="Dư có nt" e="FC Cr. Balance"></text>
        </field>
      </fields>

      &DefaultButton;
      <script>
        <query>
          <text>
            <![CDATA[<enc>Yls3K44UFNxlo+SbFjnvdxCuiSyNQs9+NaWN7soYzQfGAZ/gkEaHQ4di5YcM2M5yTAwKAL2NFXEnC6GXGwf6yOsMuYK6YPTxRg9/MPgirtFHzU1St/uZgfbTpRr4XQG1GVSzwdeni1y211LoFwUhT4IgJvldD7j+ZmtkHr8EsgSagrCk+/oTq2zzyJiA3c3qnbQ3ioDXwT4TnPIealnDTXb7TdFknXlB1wi9eWapoQbN3JSeGNDU0Tqrgdky6sQwcIIhyo52QSifMA5TbW/0/A==</enc>]]>
          </text>
        </query>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>T5Nuk0XwnW0VlRYHOIM5VTINazeAgc/ssc2rnOgrKmViFFSKVjLX9C9GJrHWe75pRKtzimS3AHON2UpHVgmp3aUn4HARV7cVeHVorqkTIasSrwnF5lJPIuDMDXzLZ26+vW7xYvurAO/N9MAg9H9SZ7MLZtqGXIvb1VbBPJv2vBVlxZ4y+fxP1bUYbyjCh+Dw</enc>]]>
    </text>
  </js>
   <css>
    <text>
		<![CDATA[<enc>nRVQr8m62Vh+aFddZ4BstdkubgX5HMu2EJ1AdJiqIaGFiQym1g9S6q4+lwVIkHq2gGpWCxsZbipT3tMtrvFmp/e81RKmYn8CNYWFccGgs38/sc90DztIKHAlv2JblpKO36oBFbr/zKFKKpibg75FbPBCCv/sc9utXRvi4f/PUOy6uSdeaOhdV4fR3z+lEXfXefEEPhDMgMrTITxaId74x8b9TRcmlfLiQ9T9Zy0EpJIrIP0N7YlWjevD7S1VGVRa2xNCAgpp+uHyOpA/RKce/drgyg0TG/6t6GOXJWLcFupFRGMFgMKi0GfX5R6X+a05L0t3G9LOcsKhy0/qvIIWZvvZgEO1QWPw59p9pS08PduOOCjuYo3duZ99XewfBjJp</enc>]]>
    </text>
  </css>
</dir>