<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmbanggia" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Báo giá Bảng giá" e="Vehicle List"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmbanggia" fieldKey="ma_bg" order="ma_bg" allowFilter="true" allowOrder="true" >
      <fields>
        <field name="ma_bg" fieldType="PK" width="100">
          <text v="Mã Bảng giá" e="Product type code"></text>
        </field>
		<field name="ten_bg" width="220">
          <text v="Tên Bảng giá" e="Product type name"></text>
        </field>
	
		<field name="ma_loai" width="100">
          <text v="Mã Loại" e="Product type code"></text>
        </field>
		<field name="ten_loai" width="220">
          <text v="Tên Loại" e="Product type name"></text>
        </field>
	 
	
	 
		<field name="status" width="120">
          <text v="Trạng thái" e="Status"></text>
        </field>
		<field name="thu_tu" width="120">
          <text v="Thứ tự" e="Position"></text>
        </field>
		<field name="thu_tu2" width="120">
          <text v="Thứ tự 2" e="Position"></text>
        </field>
		  <field name="pack1" dataType="B" align="Center" width="100" allowOrder="false">
          <text v="Standard" e="Customer"></text>
        </field>
        <field name="pack2" dataType="B" align="Center" width="100" allowOrder="false">
          <text v="Professional" e="Supplier"></text>
        </field>
		<field name="pack3" dataType="B" align="Center" width="100" allowOrder="false">
          <text v="Premium" e="Supplier"></text>
        </field>
		<field name="pack4" dataType="B" align="Center" width="100" allowOrder="false">
          <text v="Customer" e="Supplier"></text>
        </field>
		 
		 
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <!-- <![CDATA[<enc>7wxngLoTAt8sLr75YmYfPxefLyxPyIf8bm7aIaKQh6A5oRZV+SMALy7roFZAKRQZG43uj6Tv5mDs9ZEYFRIeuC9ZCsIm9V9/q2eNPi0WzBF/30yg7HBMw6hYRtwsWhw0T6DjWCK3t45T8bs0ia429uDYQbnZ11scpgpskCdrepaM8VjwLwJA0V52C+YnT/n/FNDTEB0rl/qatXfpBRlQIw==</enc>]]> -->
		 
    </text>
	<text>
      <![CDATA[<enc>CyMbKK/FGo4nORVjcrUYAV5CA65f3XK3ORk5ECHzG5qL147ShG3cx7VNRJPHE8lRMh5A+eJejFcwmJWiQIPEVvKAzOOv9+xm4ieMWeEdZ1iei+f9qsqcRZFDMdn0E4XchITcvRApd9LRtFtjSDfO01a1UHEJmycA0lFnOqKyB71iQud8YkYMP5YOgNgETW1c4PrwzdklU+zLswmuOmM0zw==</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>cTMcaemK/mtRjps8m/sJOVirlLEJ+6JxiLPeJpYli4TAugeI+9xS9CIT96sX4XiNHefVQOt7fompL31ydAZJ3zbOdWMd5eIffmA/BGo5olHD9HllibL9oaJ+q8SIGGIxctuUbBiK/AoBCVom/JB6t7K63gLTkI+n1+rKmi9w1o3agX3Q3T7VA7fpVMPNyATDKCMwOuHkuP8gVjUw+qEn8lDMfSVRMnD0/FysmWigoBh/gLFLiJHLlzQDzpc5t/w9ovG2+hZPKJkxSGbquy14Z/Moy+LeKNtoKkGhDFJLvHX1Z9I5Pqnoi64lNbwHXFIxbOALp0KsYLr56b26De9xBtmOeTdLi0YparLh4bTcD2fca+XxZyDGiDNFsNbEQ0ln</enc>]]>
    </text>
  </css>
</dir>