<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmbanner" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục banner" e="Banner List"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmbanner" fieldKey="ma_banner" order="ma_banner" allowFilter="true" allowOrder="true" >
      <fields>
        <field name="ma_banner" fieldType="PK" width="120">
          <text v="Mã banner" e="Banner code"></text>
        </field>
		<field name="ten_banner" width="120">
          <text v="Tên banner" e="Banner name"></text>
        </field>
		<field name="ten_banner2"  width="120">
          <text v="Tên khác" e="Other"></text>
        </field>
		<field name="status" width="120">
          <text v="Trạng thái" e="Status"></text>
        </field>
		<field name="thu_tu" width="250">
          <text v="Thứ tự" e="Position"></text>
        </field>
		<field name="phan_loai" width="250">
          <text v="Phân loại" e="Type"></text>
        </field>
		 
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <!-- <![CDATA[<enc>Ccvx56Nydky3Uh55/RW4nfJzX0/RIED68cDgG8uloLdRqH7F5hOGJkGFi+X8zpX947HbOYW/4rYOzGwt+Luttcl3HBMm2wAwNNMOvKkNYQ6Prc0x7VLJkxJII3c+5kNqYCdnSkZg5LVCm8iTOlznpGgTA5W9rlFCxKTRHikQxlvBZ3XNYQhGKGD55cXGF06AxO4bdsI6YzAOfpsvEkTWvw==</enc>]]> -->
		 
    </text>
	<text>
      <![CDATA[<enc>GYD0OC5JhpEhu2renQHOp61fLzKLNeF7zpcqOnSWAp4hmPYcYTjgp9TnyowAKXeCT9flbC75QV+XU6+6dTFKRePA51sQ0P7J9xntcE9kxqnkluT36NKatVs1ndPJ4HNO2fRjoBJ77k0qbiyS6sfhoyVvqERtPQ+FKSmWyH2EtkCcbKT78xtDRMfCW0Gq6k1A</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>cTMcaemK/mtRjps8m/sJOVirlLEJ+6JxiLPeJpYli4TAugeI+9xS9CIT96sX4XiNHefVQOt7fompL31ydAZJ3zbOdWMd5eIffmA/BGo5olHD9HllibL9oaJ+q8SIGGIxctuUbBiK/AoBCVom/JB6t7K63gLTkI+n1+rKmi9w1o3agX3Q3T7VA7fpVMPNyATDKCMwOuHkuP8gVjUw+qEn8lDMfSVRMnD0/FysmWigoBh/gLFLiJHLlzQDzpc5t/w9ovG2+hZPKJkxSGbquy14Z/Moy+LeKNtoKkGhDFJLvHX1Z9I5Pqnoi64lNbwHXFIxbOALp0KsYLr56b26De9xBtmOeTdLi0YparLh4bTcD2fca+XxZyDGiDNFsNbEQ0ln</enc>]]>
    </text>
  </css>
</dir>