<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmbcc" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục bảng chấm công" e="List of timesheets"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmbcc" fieldKey="id" order="id" allowFilter="true" allowOrder="true">
      <fields >
        <field name="unit_id" hidden="true" dataType="I" width="80" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
		
        <field name="ma_nv" fieldType="PK" width="120">
          <text v="Mã nhân viên" e="Staff code"></text>
        </field>

      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>T5Nuk0XwnW0VlRYHOIM5VYnHDnH7tu2xtEYSmkPfNZAyO3cKYARmxDn0XUQuVORC4sfmr2EZB+5tS52+XeOOBuDWQpEmEJ39PXaHpI8OANR2mYm1fm3SYjPdnbpiD48IP5vQABJOiPQxz8hHRgYGpzPH6+7kItdSgPhVngQ+5xPiVyf2nlTpftqMxMJpGU74</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
</dir>