<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmbp" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục bộ phận" e="List of Subunit"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmbp" fieldKey="ma_bp,ma_pb" order="ma_bp" allowFilter="true" allowOrder="true">
      <fields >
	  	<field name="ma_pb" width="0" fieldType="PK">
          <text v="Phòng" e="Department Code"></text>
        </field>
        <field name="ten_pb" width="250" fieldType="EX">
          <text v="Phòng ban" e="Department"></text>
        </field>
        <field name="ma_bp" width="120" fieldType="PK" >
          <text v="Mã bộ phận" e="Subunit Code"></text>
        </field>
        <field name="ten_bp" width="250">
          <text v="Tên bộ phận" e="Subunit Name"></text>
        </field>
		<field name="ten_bp2" width="250">
          <text v="Tên khác" e="Other Name"></text>
        </field>
		<field name="status" width="120" align="center">
          <text v="Trạng thái" e="Status"></text>
        </field>
      </fields>

      &DefaultButton;
	  <script>
		<query>
			<text>
				<![CDATA[<enc>jmM3mdbacJpAMQkZWs/QBqk/7KCL9tGJZhHCxQApqtc7v2pYBjpj+HNeEQ4TxC2cr6/Sv1mG6+SZtr4eJk9Q9fhrz5XYXdsaBPqXxGbxTSq7XQFP61jkgwhYqrOy8vyDhSkDFHugjVc3/SCNatjrm90oqnxz7jF9HH3Q1YpobIxMQFW5/QGAOEtcOAqtOjiAVevqcNOnRyillZtFSTeG1ALQGTnqEfhOt4y/gtCg00L9eF+BfmdWwaw6MBmjFMj4Kua1cCWTqvLKiARMsfI81Q==</enc>]]>
			</text>
		</query>

		<finding>
			<text>
			<![CDATA[<enc>uwLLfiyZdhk8ism3FPbAU6BUTsKchOY+C4TgrqEHyi1Ltlwf81UZA5s9JvL+G+cAnl1VspG3Ady44I0LqqjdbA4MCLIkmaNog6w3OmRwN5EWraTjIvAewaqojhR0CGcsjrY3CUCuviTl09Sw8iaV2/K1EHzI45wlko+Xt1DHVATxgos078jcOCMatJhqF5j8A/ZZZKs33YCiCCs5QBxV2/wt+lKKUDmTACNlU1F1c8mfGm53+iP47TdnaS6f3kANdgt2Spo98S/W8rdwJ8qk0Q==</enc>]]>	
			</text>
		</finding>
	   </script>
    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>gbveqZ921+F0tM5Cn1/sdPgCLj40uyC5LdytxqF5OvWQ2zbXz9oXaV4K4tkHYo1Nsghorz4J5DqbLth9eCq7Yn0LLU2rBNoXcvMFh8S1H3b37eqUpYK8d0JUHWcDeeGcx2WH119w4YzmvPDZFPBASyuyjKUXP4o0Kiz0anaTQL42Wg9R6UMaPTgrMjY8jaRi</enc>]]>
    </text>
  </js>
  
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
</dir>