<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmcang" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục cảng" e="Port List"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmcang" fieldKey="ma_cang" order="ma_cang" allowFilter="true" allowOrder="true">
      <fields >
        <field name="ma_cang" fieldType="PK" width="120">
          <text v="Mã cảng" e="Port Code"></text>
        </field>
        <field name="ten_cang" width="250">
          <text v="Tên cảng" e="Port Name"></text>
        </field>
		<field name="dia_chi" width="250" link="1">
          <text v="Địa chỉ" e="Address"></text>
        </field>
        <field name="dien_thoai" width="120">
          <text v="Điện thoại" e="Phone"></text>
        </field>
        <field name="ma_qg" width="120">
          <text v="Mã quốc gia" e="Country code"></text>
        </field>
		<field name="ma_ttp" width="120">
          <text v="Khu vực" e="Area code"></text>
        </field>
		<field name="tdx" width="120">
          <text v="Kinh độ" e="Longitude"></text>
        </field>
		<field name="tdy" width="120">
          <text v="Vĩ độ" e="Latitude"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>K8JPsPQtkuBwkJkHk8HQW7iy1GGQAzVxXzHmdZuE7BQ8gEjeFcyCbccPW7m6Hj5UPQbzcWCMNZNmWly/g4MbNizLMzl4O+2koeNTiTv99BYRIMlLbgLHzN29MrNWMqFnB0gZKr27I4jXcjiCnnNyXIObXkxIjfIAro/992DfLd8UPIjaofgs0Y6vT1wtlzPC</enc>]]>
    </text>
  </js>
  <css>
    <text>
      <![CDATA[<enc>2FI/rX3TUEulxi9LoMIkcrNxfLRl3EeU+vXNpxQMgjAUY+e+fGyRzUkW+9nk3DQhRGDcCci+9yN9eNtbKmU791f+T6ieUFfgOjsuRVms+RLXNXkR+TQtRCS4FV0pRfP1fcwNG+tYLjCPjgr/WKew/MUhXhi4bKC7rHkp5oZhUfiM7jrj07++4J47zqqm135YfI/4/B4osMfc4JwZvc4UdOOdVeGAUSTZf5EB2pZOESRmXLeEFulW+eR/+o1UWB+1/UKKBLZIthNkBHUSRWibuDm3AC2cEyXPFjWJchNUAhngrHccQ3Oat8UBetW1Q1NE</enc>]]>
    </text>
</css>
</dir>