<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmch" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục cửa hàng" e="Store List"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmch" fieldKey="ma_ch, ma_dc" order="ma_ch" allowFilter="true" allowOrder="true" >
      <fields>
        <field name="ma_ch" fieldType="PK" width="120">
          <text v="Mã của hàng" e="Store code"></text>
        </field>
		<field name="ma_dc" fieldType="PK" width="120">
          <text v="Mã địa chỉ" e="Store address"></text>
        </field>
		<field name="ten_ch" width="120">
          <text v="Tên của hàng" e="Store name"></text>
        </field>
		<field name="ten_ch2"  width="120">
          <text v="Tên khác" e="Alias"></text>
        </field>
		<field name="noi_dung" width="240">
          <text v="Nội dung" e="Content"></text>
        </field>
		<field name="dia_chi" width="240">
          <text v="Địa chỉ" e="Address"></text>
        </field>
		<field name="dien_thoai" width="240">
          <text v="Điện thoại" e="Phone"></text>
        </field>
		<field name="hotline" width="240">
          <text v="Hotline" e="Hotline"></text>
        </field>
		<field name="email" width="240">
          <text v="Email" e="Email"></text>
        </field>
		<field name="gio_mo_cua" width="240">
          <text v="Giờ mở cửa" e="Time open"></text>
        </field>
		<field name="gio_dong_cua" width="240">
          <text v="Giờ đóng cửa" e="Time close"></text>
        </field>
		<field name="ngay_mo_cua" width="240">
          <text v="Ngày mở cửa" e="Day open"></text>
        </field>
		<field name="ngay_dong_cua" width="240">
          <text v="Ngày đóng cửa" e="Day close"></text>
        </field>
		<field name="thu_tu" width="120">
          <text v="Thứ tự" e="Position"></text>
        </field>
		<field name="status" width="120">
          <text v="Trạng thái" e="Status"></text>
        </field>		
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <!-- <![CDATA[<enc>Qkc+X0DtlkHbxfS94VCEuUtbbUgh6TTZchbvRd3jTA70O/7bFfROw79pfWCDs3oNloF7hojnqZQSIqY630zlVXOA1APv+x/eFN+jIC7uHqr/02gXQy8Bb0mTkBZJclopK4lfbzlKS9IVy2N4DA9tw8YnLG+QOUHTLFBhcxsoclNzT7du6e4yiEi5weIYHzHGbmYIHx0MBH72A+SQXittMg==</enc>]]> -->
		 
    </text>
	<text>
      <![CDATA[<enc>wpR3ICmqndSY1Y0uQqHX9PBhyQVVsoXnY4f/YhiFT+i9jPO1V6VVbQIfk9e3UkXHzbPRwQkHKUMm6m+kb52IQgHvrnCgi2BxMU8MOpIGwzusCWv9h12UA0QOM8eB746l0xzbGid5aTjIhyg82QPYuLHAuDbf94vMgqS/Owd5918For//dbysT70rpvO6y4Ag</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>cTMcaemK/mtRjps8m/sJOVirlLEJ+6JxiLPeJpYli4TAugeI+9xS9CIT96sX4XiNHefVQOt7fompL31ydAZJ3zbOdWMd5eIffmA/BGo5olHD9HllibL9oaJ+q8SIGGIxctuUbBiK/AoBCVom/JB6t7K63gLTkI+n1+rKmi9w1o3agX3Q3T7VA7fpVMPNyATDKCMwOuHkuP8gVjUw+qEn8lDMfSVRMnD0/FysmWigoBh/gLFLiJHLlzQDzpc5t/w9ovG2+hZPKJkxSGbquy14Z/Moy+LeKNtoKkGhDFJLvHX1Z9I5Pqnoi64lNbwHXFIxbOALp0KsYLr56b26De9xBtmOeTdLi0YparLh4bTcD2fca+XxZyDGiDNFsNbEQ0ln</enc>]]>
    </text>
  </css>
</dir>