<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
   <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridNotPrint.xml">
]>

<dir id="dmchungtu" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục chứng từ" e="List of Voucher"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmchungtu" fieldKey="ma_ct" order="ma_ct" allowFilter="true" allowOrder="true">
      <fields >
        <field name="ma_ct" fieldType="PK" width="120">
          <text v="Mã chứng từ" e="Voucher Code"></text>
        </field>
        <field name="ten_ct" width="250">
          <text v="Tên chứng từ" e="Voucher Name"></text>
        </field>
		<field name="ten_ct2" width="250">
          <text v="Tên khác" e="Other Name"></text>
        </field>
		<field name="status" width="120" align="center">
          <text v="Trạng thái" e="Status"></text>
        </field>
      </fields>
	  &DefaultButton;
	  <script>
		<query>
			<text>
				<![CDATA[<enc>cxblwlTjuf0RelEES+YgsZ31Dd1HelEUEdWl19BiKE0g8odsPtP2TqIBmDaT++NPKQ8aViJFi/5XhaU0OQ6A9xGOXC7pOJxOVJqtxNLJlZbVDumLHAHoNXG1DUGnpNWraE0Pd94leACG/DY8jPkmWr7wXP2hgBmBxnsqV+puSIewV/Pem69tfKwAPPCrbVMc/gjM0O7wQPHxNkm/6jqoDGssblvFO0HVOzln8drEZ/Y=</enc>]]>
			</text>
		</query>

		<finding>
			<text>
			<![CDATA[<enc>cxblwlTjuf0RelEES+YgsZsN721hLwjL3o8GIY4rMLmKLg602GmAllF988UH5sD8ZBq8nW5oaRzxVqXFeQujT3t8ntuLn+EEgxou/XEFyP4UlSVyHKWlPowBWCEegs2a3g8N1bp5FGuRw5ryBBInSyBZPEufRUeXZZhtNNe6roAR+rWx+xMKvWbMCinttBL9VmDbNgvIjDQVPBaIKALRZtG/FQUng3oxkszZkcoH4ek=</enc>]]>	
			</text>
		</finding>
	   </script>
    </grid>
  </grids>
  

  <js>
    <text>
      <![CDATA[<enc>Xm0SQO244yhm4oovG3IvuGWZVkwdldFFDmpUmMtuEWJn10W8OJ7XmeZkKpQiBENXLC8AJWl4vSidJB1NbeONv/Uz4SHyTv3HonMY23j6kDX6Ze6mW99F4pcJWaAHuJKqgCnJ3lQQqbxUWi2uNHaeqRdh8q95iqfNi5piRqJrd4c7g9J2XJKz6niWWKkH3kDJ</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
</dir>