<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridNotPrint.xml">
]>

<dir id="dmcong" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục công/thùng hàng" e="List of Container/Cargo"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmcong" fieldKey="ma_cong" order="ma_cong" allowFilter="true" allowOrder="true">
      <fields >
        <field name="ma_cong" fieldType="PK" width="120">
          <text v="Mã container" e="Container Code"></text>
        </field>
        <field name="ten_cong" width="250">
          <text v="Tên container" e="Container Name"></text>
        </field>
		<field name="ten_cong2" width="250">
          <text v="Tên khác" e="Other Name"></text>
        </field>
        <field name="ma_loai" width="120">
          <text v="Mã loại" e="Type Code"></text>
        </field>
		 <field name="ten_loai" width="220" fieldType="EX">
          <text v="Tên loại" e="Type Name"></text>
        </field>
		<field name="status" width="120" align="center">
          <text v="Trạng thái" e="Status"></text>
        </field>
      </fields>
	  
	  &DefaultButton;
	  <script>
        <query>
          <text>
            <![CDATA[<enc>lvS8xa1cQeSiGKpUDsZN7+Tbkm2J8mRhWbmeMph5rA5xilOP8ijl0fAkFmuuyiWUnWoFZQn3LK4TUJtB30QokM8rmbpgf84u6cMoczMdvEmfKcSwRzRGHD/B/xjLdoVB3JN8MsUxOs1FtDHCNT8isEfQIJtSo7OzibMHqIP1ssf7fSiV5DJDsHxbC7M+oUQdzOm5Cvbmwc+2xSzCwcYVh/nkjGBWg12N1mFy9sV7N6jc3XX0OR1CsB3uoi0U/0vn+nt8+GNhrmR9gMvUcKlwaw==</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>jmM3mdbacJpAMQkZWs/QBueWwABZvuboKhdzQWCWonXWXSG06x1o9wOLgHEu1r6EwUfhkAy3BrVOUNoO4ZdeCJ+MaHOFpKgsWwF5OUBycmku8ND9R8A9s7lkwZO5EE4WBlDasOSnBzPgyrrYtKw5J4omTpVxIqribzUM1U5ddjXbmpOHTRjW4D4c3/2TdGsLhFa+Z3JP4jIahtIzkvmIgYZokxgQ6KNTwqij8TZWqRDIGud2HESdHml70ZyvUBBMJ7Gu52iFDluIApu6KaaZZquddTjv7OpIGroU6l+w7WE=</enc>]]>
          </text>
        </finding>
      </script>
   
    </grid>
  </grids>
  

  <js>
    <text>
      <![CDATA[<enc>/P9Shux7F0Mmh7E260+hpeIndoKqOKjCh8sJF0PvOM7qInDmHNkB1fKOQ7v2FUd/qefLLTpBuUPv1JVvYmFYh+HQXDirXQ7H/2GbND3+NMxn2SoGjox7gryGDVy+WJYCJuzqGK9rUApNfnWhlBdp3PKs9E/jZFfsp+JUuBh3wib2hQniund/1NWsWATB9CBJ</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
</dir>