<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmdkxe" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Khai báo đăng kiểm" e="Registration declaration"></title>
  <subtitle v="Cập nhật tỷ giá..." e="Add, Edit, Delete Exchange Rate..."></subtitle>
  <grids>
    <grid table="dmdkxe" fieldKey="ma_xe,ngay_dk" order="ma_xe" allowFilter="true" allowOrder="true" >
      <fields >
        <field name="ma_xe" fieldType="PK" width="120" >
          <text v="Xe đăng kiểm" e="Currency Code"></text>
        </field>
        <field name="ten_xe" width="250" fieldType="EX"  aliasName="b">
          <text v="Tên xe" e="Currency Name"></text>
        </field>
        <field name="ngay_dk" fieldType="PK" width="120" dataType="D">
          <text v="Ngày đăng kiểm" e="Date"></text>
        </field>
		 <field name="ngay_hh" fieldType="PK" width="120" dataType="D">
          <text v="Ngày hết hạn" e="Date"></text>
        </field>
        
      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>jfWY55PlsFb3adF5OHRtDJ/5QTFeH65q9OWJgo5J4yoCwuKIbTGUoCdaEDEHcL+9qwR1TsOs72ipbz9CBSi3XZih1atza1irv4Ait0Qeaz8EHaDTH6pjE4tBUYvkB9BJJIoCWcrGcO3FN8an+2c+yviF1Vu7kwAewIeosBAuyQYES1Hzl68hEsnP62QjdrK/dS6reisiU3ihhU4874TiViRiWOChjgkSRUuFMUeIb6H0a+jhvKJpqNKxvqj1nfOu</enc>]]>
          </text>
        </query>
      </script>
    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>T5Nuk0XwnW0VlRYHOIM5VYa+cR6EMIk17pdf3cAyKBc0I0JuQmu2QejLdfLFBa2Ux5hMGx7k0SuWsJsHdAFaQNbzw5YBuP5yyRq8HACFJpHRBZHEw/cvtHL2Y9ojPrxUAwWKjyQUiFoPG5QG4QLwvsE113wpBVDjmpDuR4Aj7I1MvOmgOrwNUG8jyURJhhM5</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
</dir>