<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridFinding.xml">
]>

<dir id="dmdtcn" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục điện thoại cá nhân" e="List of personal phone"></title>
  <subtitle v="Xem, sửa dữ liệu..." e="View, update data..."></subtitle>
  <grids>
    <grid table="dmdtcn" fieldKey="ma_so_thue, dien_thoai" order="ma_so_thue, dien_thoai" allowFilter="true" allowOrder="true" >
      <fields>	
		<field name="ma_so_thue" width="150" fieldType="PK">
          <text v="Mã số thuế" e="Tax Code"></text>
        </field>
		<field name="dien_thoai" width="150" align="right" fieldType="PK">
          <text v="Điện thoại" e="Phone"></text>
        </field>
		<field name="ghi_chu" width="150" align="right">
          <text v="Ghi chú 1" e="Note 1 "></text>
        </field>
		<field name="ghi_chu2" width="150" align="right">
          <text v="Ghi chú 2" e="Note 2"></text>
        </field>
		<field name="status" viewType="Combobox" width ="150" valueDefault="1">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_tt, ten_tt%l from dmttsd where status = 1 order by ma_tt">
            </options>
          </viewInfo>
        </field>
		<field name="xstatus" viewType="Combobox" inactivate="true" label="1" field="[150]" nextRow="false" valueDefault ="5" >
          <text v="Trạng thái" e="Status"></text>
		  <viewInfo>
			<options query="select ma_tt, ten_tt%l from dmtrangthai where status = 1">
			</options>
		  </viewInfo>
        </field>

		<field name="user_id2" viewType="Combobox" width = "150">
          <text v="Người tác động" e="Date updated"></text>
          <viewInfo>
            <options query="select user_id, username%l from sysuserinfo where status = 1 order by user_id">
              <option val="">
                <text v="" e=""></text>
              </option>
            </options>
          </viewInfo>
        </field>
	   <field name="datetime2" hidden="false" dataType="D" width="150" align="center">
          <text v="Ngày tác động" e="Date updated"></text>
        </field>
      </fields>
	  
	  <buttons>
	   <button id="edit">
		<text v="$EditToolbar" e="$EditToolbar"></text>
	  </button>
	  <button id="view">
		<text v="$ViewToolbar" e="$ViewToolbar"></text>
	  </button>
	  <button id="split">
		<text v="-" e="-"></text>
	  </button>
	   <button id="find">
		<text v="$FindToolbar" e="$FindToolbar"></text>
	   </button>
	  <button id="split">
		<text v="-" e="-"></text>
	  </button>
	  <button id="refresh">
		<text v="$RefreshToolbar" e="$RefreshToolbar"></text>
	  </button>
	  <button id="freeze">
		<text v="$FreezeToolbar" e="$FreezeToolbar"></text>
	  </button>
	  <button id="split">
		<text v="-" e="-"></text>
	  </button>
	   <button id="print">
		<text v="$PrintToolbar" e="$PrintToolbar"></text>
	  </button>
	  <button id="export">
		<text v="$ExportToolbar" e="$ExportToolbar"></text>
	  </button>
	  <button id="downtemplate">
		<text v="Tải mẫu Excel" e="Down import template"></text>
		</button>
		<button id="import">
		<text v="Lấy dữ liệu từ tập tin" e="Import data"></text>
		</button>
	</buttons>
	<script>
        <query>
          <text>
            <![CDATA[<enc>g+KZ+QKBlC+LdD0jHhpbmX0VaU2WJtbStCT2OcRdLkOPLT3x7dBdsP9pvdc3vC0SWt2T1mt7qDKvZ8QiJgoUi99pN5vE98Nkv6WwbpN4i701qX3IKYoP6MuOVO+GdJmPxJYUoewfznFi/PjMyo+T9imGvX8IUqxBvxdQdrBViWaFbQ931ngy4bVQyASp1P6N</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>T1P00otPKsUcyvVCfWChNgPh3AGae8CoXbq3CvQcUY1uU5E4QFK6qFuJ3O0PK18aohlCWm7uVaJ38A4Ki7Y0fZ8jRzb96x9P14ee5hrQwSEpOrzM/uaIn/RWzo90qwrQbc4I4m1lMGpbyZA0A3Myes/wlzjidw6dVXFde5I0Y2NODqMFKQjtuU+NeS94nzNYhvIZxuodwg58Wu42cm83ngKRfRplpCRBBuEyGCWOdHE=</enc>]]>
          </text>
        </finding>
      </script>
    </grid>
  </grids>

  <js>
    <text>
	<![CDATA[<enc>nlFUN8/lrXj5/CIcUgVtWDcmsa3LJCJ2I4Lw8Ea74qd4bzpMfciRZw02ERUzfG4r7sp6A4YxDjfmC1+JkfSo0t7eataQOA22KWFroel64LkjWufqPLnFckgYy7a7/pr6OGCZO0yF/mrRwT5QiIacQu/zjFQNGOi6+05yDyMe8BI=</enc>]]>
    </text>
  </js>

<css>
    <text>
      <![CDATA[<enc>Kd79JRAL5i+eNv6sltH3ZNWzz6heuxLZ7kHiQ9xC4Huwf7nX7pqY0jZUe0DPj7YGp5s/dIgLtpp2PdiUXFC9kU4BAJ2ff1/1OXbJQeJ6up+n9FQSxvO0KbjEqfKXvPtB1A8UKErh6jgYUeka1gq99FGuM9cwC3v/ncZ4yGN7rfQTmeV5tpe+xx5DUvecYauHV+Q/iSKhlFsMRIuMMzXydakjpYtT3/6dph3sszgfJWeKTqB0ofuurtlJ6rJkTbltnOURX5Ki7PxTUI22Gl0+vaFAKH+s2VY/GistBknTH4Mh6aUHjVGcpnVX4clspkBRRc6um2FuXg6I0p37bMnmfwA62fIzWYaZRMwQxZ2ZxRwe7tWcBIqg5avWFi/KKP82</enc>]]>
    </text>
  </css>
  <script>

  </script>

</dir>