<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmdv" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục dịch vụ" e="Service List"></title>
  <subtitle v="Cập nhật dịch vụ: thêm, sửa, xóa..." e="Add, Edit, Delete Service..."></subtitle>
  <grids>
    <grid table="dmdv" fieldKey="ma_dv" order="ma_dv" allowFilter="true" allowOrder="true">
      <fields >
        <field name="ma_dv" fieldType="PK" width="120">
          <text v="Mã dịch vụ" e="Service"></text>
        </field>
        <field name="ten_dv" width="250">
          <text v="Tên dịch vụ" e="Description"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>gbveqZ921+F0tM5Cn1/sdDZ3cUcoUI1YCqu2PjebA2XZS085whUjfAirvdUP2OeaqgV6//UVWAYpuGeJmAh9plXWKcwM8uWGHdz14uspZiPZZBegNQtsHbwm398QOurYKx9l9oR+2f5f/QNmc2UPmq8qeQq+18h4jmY+dwkH13lrGtizav008JrlLnfSkoRQ</enc>]]>
    </text>
  </js>
   <css>
    <text>
		<![CDATA[<enc>nRVQr8m62Vh+aFddZ4BstdkubgX5HMu2EJ1AdJiqIaGFiQym1g9S6q4+lwVIkHq2gGpWCxsZbipT3tMtrvFmp/e81RKmYn8CNYWFccGgs38/sc90DztIKHAlv2JblpKO36oBFbr/zKFKKpibg75FbPBCCv/sc9utXRvi4f/PUOy6uSdeaOhdV4fR3z+lEXfXefEEPhDMgMrTITxaId74x8b9TRcmlfLiQ9T9Zy0EpJIrIP0N7YlWjevD7S1VGVRa2xNCAgpp+uHyOpA/RKce/drgyg0TG/6t6GOXJWLcFupFRGMFgMKi0GfX5R6X+a05L0t3G9LOcsKhy0/qvIIWZvvZgEO1QWPw59p9pS08PduOOCjuYo3duZ99XewfBjJp</enc>]]>
    </text>
  </css>
</dir>