<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="vdmdvvt" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục đơn vị hàng" e="Trans/Site List"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, edit, delete..."></subtitle>
  <grids>
    <grid table="vdmdvvt" fieldKey="ma_dvvt" order="ma_dvvt" allowFilter="true" allowOrder="true">
      <fields >
        <field name="ma_unit" width="120">
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="ma_dvvt" fieldType="PK" width="120">
          <text v="Mã đơn vị" e="Code"></text>
        </field>
        <field name="ten_dvvt" width="250">
          <text v="Tên đơn vị" e="Description"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>dWARx5oyNggjYSWXeJWjdsIlMKAFYcvEfOd1/bvapZNszbQ79nRkGq8oUl0livgDeyyj8JlDSQkX/KujiMmQC6JRVo2iI8P/2B514mc1imqR0yM8vTLgXVv9Gffaab9A+vq2dDw8TpFaLRVNLRnXdSPzy0y3WkirZIdTscx1HYoXBOJOa5UUicKmtvEEvmX6</enc>]]>
    </text>
  </js>
   <css>
    <text>
		<![CDATA[<enc>nRVQr8m62Vh+aFddZ4BstdkubgX5HMu2EJ1AdJiqIaGFiQym1g9S6q4+lwVIkHq2gGpWCxsZbipT3tMtrvFmp/e81RKmYn8CNYWFccGgs38/sc90DztIKHAlv2JblpKO36oBFbr/zKFKKpibg75FbPBCCv/sc9utXRvi4f/PUOy6uSdeaOhdV4fR3z+lEXfXefEEPhDMgMrTITxaId74x8b9TRcmlfLiQ9T9Zy0EpJIrIP0N7YlWjevD7S1VGVRa2xNCAgpp+uHyOpA/RKce/drgyg0TG/6t6GOXJWLcFupFRGMFgMKi0GfX5R6X+a05L0t3G9LOcsKhy0/qvIIWZvvZgEO1QWPw59p9pS08PduOOCjuYo3duZ99XewfBjJp</enc>]]>
    </text>
  </css>
</dir>