<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmhangtau" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục hãng tàu" e="List Of Shipping Lines"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmhangtau" fieldKey="ma_hang" order="ma_hang" allowFilter="true" allowOrder="true">
      <fields >
        <field name="ma_hang" fieldType="PK" width="120">
          <text v="Mã hãng" e="Brand Code"></text>
        </field>
        <field name="ten_hang" width="250">
          <text v="Tên hãng" e="Brand Name"></text>
        </field>
        <field name="ten_hang2" width="250">
          <text v="Tên khác" e="Another Name"></text>
        </field>
		<field name="ma_loai" width="120">
          <text v="Mã loại" e="Country code"></text>
        </field>
		<field name="ma_nhom" width="120">
          <text v="Mã nhóm" e="Group Code"></text>
        </field>
		<field name="ma_qg" width="120">
          <text v="Mã quốc gia" e="Country code"></text>
        </field>
		<field name="dia_chi" fieldType="PK" width="250" link="1">
          <text v="Địa chỉ" e="Address"></text>
        </field>
		<field name="ma_thue" width="120">
          <text v="Mã thuế" e="Tax code"></text>
        </field>
        <field name="dien_thoai" width="120">
          <text v="Điện thoại" e="Phone"></text>
        </field>
        <field name="email" width="120">
          <text v="Email" e="Email"></text>
        </field>
		<field name="fax" width="120">
          <text v="FAX" e="Fax"></text>
        </field>
		<field name="status" width="120">
          <text v="Trạng thái" e="Status"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>Xm0SQO244yhm4oovG3IvuLeLIyJNX4Y9n7qfFwoZpqzJlPknmCoOa44I58BfcyxfFM5nPgnpUhrQj3C5O00mTdrg1p8Rb18PHzTUmv6QW+gtwFswP1LVh+kzsSwwX8Ae392LxqiNQPzxB8gXS1pkTHHF+vi33UKw+RmFRFITE6mXBtIF74OLNyn9VtpS9K1E</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
</dir>