<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmhh" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục hàng hóa" e="Commodity Menu"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmhh" fieldKey="ma_vt" order="ma_vt" allowFilter="true" allowOrder="true">
      <fields >
        <field name="ma_vt" fieldType="PK" width="120">
          <text v="Mã vật tư" e="Agent Code"></text>
        </field>
        <field name="ten_vt" width="200">
          <text v="Tên vật tư" e="Agent Name"></text>
        </field>
		<field name="ten_vt2" width="200">
          <text v="Tên khác" e="Another Name"></text>
        </field>
		<field name="ma_dvt" fieldType="PK" width="120">
          <text v="Mã đơn vị tính" e="Unit Code"></text>
        </field>
		<field name="dg_ban" width="120">
          <text v="Đang bán" e="On Sale"></text>
        </field>
		<field name="ma_nhom" width="120">
          <text v="Mã Nhóm" e="Group Code"></text>
        </field>
		<field name="status" width="250">
          <text v="Trạng thái" e="Status"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>gbveqZ921+F0tM5Cn1/sdLGEXYzcQ9tQjcOWaiXbQOLfJAP5X5k6whazAQr1bIqiXqk3tEP110OicuOepWwbJRgJ6eoRi1MAfSxb2hmW4hPJy/nxp/9/0wrQo38+LHDIpI8HoQZ7PJOMagBmWUq6xu70pYNbDMtPYcUnR9nBs4hmUoFPqhCxNHPiWBcjp2Xi</enc>]]>
    </text>
  </js>
</dir>