<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmhmdx" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục hạng mục đề xuất" e="List of proposed types"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmhmdx" fieldKey="ma_hmdx" order="ma_hmdx" allowFilter="true" allowOrder="true">
      <fields >
        <field name="ma_hmdx" fieldType="PK" width="120">
          <text v="Mã hạng mục" e="Type code"></text>
        </field>
        <field name="ten_hmdx" width="200">
          <text v="Tên hạng mục" e="Type name"></text>
        </field>
	    <field name="ten_hmdx2" width="200">
          <text v="Tên khác" e="Type name"></text>
        </field>	
		<field name="nguoi_check" width="250">
          <text v="Người check" e="Type name"></text>
        </field>
		<field name="nguoi_duyet" width="250">
          <text v="Người duyệt" e="Type name"></text>
        </field>	
		<field name="nguoi_thuchien" width="250">
          <text v="Người thực hiện" e="Type name"></text>
        </field>	
		<field name="status" width="80" align="center">
          <text v="Trạng thái" e="Status"></text>
        </field>
      </fields>

      &DefaultButton;
      <script>	
        <query>	
          <text>	
            <![CDATA[<enc>T1P00otPKsUcyvVCfWChNlS/XqaaLY0p7W4eQGVZ8kBBLX68NqPin8k777zNwg2qtVtS0nVW4AnKG3oDRI9K4hZlxuN+hQfgTni36b7EiUptSu9MSNXkvK8gzTWb73ikhB9f/yhcNztIuezw4cGmAJHH4xohSkhhYtHjbblANL8cAQnWYupIKUxPupJxM/XWlF+OVegepRQjlFKg+jfYLVz4XkNeyciN1sZVz/jbK8s=</enc>]]>	
          </text>	
        </query>	
        <finding>	
          <text>	
            <![CDATA[<enc>A3W54x6lMMuVeGXkdNhwYCc+tUc+OtMe7ISMXab1TXyFw7N10C86MZsSz9uDOKVr3J1aW7nLQEf8GPaWueVF4Ap0hGuZyfxc518NPPaktjsG0FQwa/HwCPJOca/floxmcTlyqD7cXlISluWrAn0O1ETz58jBw0eBPM+PalINqEfwkqKG8MTVsvxyRO86v45IS86skz52Wi6NNwdW5xwdFWA9Y3GCT80tfDF4DEKwUHsa+8tsZLoj4YMSIjlHhgU7llnJI9OT1vmIrzFMrjjr5eHHsyn8qRs/M0Re64FkRfH5yrRwWFz1vpZo9vnZcyH9iTOXMeGuV7n4n3POxyBLr++jqonqsifn6MPw7aep5KA=</enc>]]>	
          </text>	
        </finding>	
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>gbveqZ921+F0tM5Cn1/sdIIjvYrrrcr5tN3rExNVy2Pl0BZYx6HOFP0TEOHbO3zK6O1xadgUqz+E8AVIgOxUTNFCvatReF8oG4LkAdpl09B4tsmR0uxhl8nmIW6Fmdrvbfp7ZPifdLdXkdHzAvNlXn30voOXhlHnQi0SwtlHaNzgjEw2kkuvVMNlkbMVzGDK</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
</dir>