<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmhoahong" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục hoa hồng" e="List of commission"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmhoahong" fieldKey="ma_hoahong" order="ma_hoahong" allowFilter="true" allowOrder="true" >
      <fields >
        <field name="ma_hoahong" fieldType="PK" width="170">
          <text v="Mã hoa hồng" e="Commission code"></text>
        </field>
        <field name="ten_hoahong" width="250">
          <text v="Tên hoa hồng" e="Commission name "></text>
        </field>
		<field name="ten_hoahong2" width="250">
          <text v="Tên khác" e="Other name"></text>
        </field>
		<field name="tyle_hh" width="250" dataType="N">
          <text v="Tỷ lệ" e="Ratio "></text>
        </field>
		 <field name="status" width="250">
          <text v="Trạng thái" e="Status"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>Xm0SQO244yhm4oovG3IvuLeLIyJNX4Y9n7qfFwoZpqx3sg0U5lG0dkND1Zj6G6wdLH4hSL7lLoXr16Y0DMvOqFA1mKnxEml8czPQadPAiEia4G5CWk2UvvBOmYocQKF8+jtOnVVmgDcrBrEMKHrANWvQdt03yvaCtI7goRfKd9GqTEiXIdqMEFZCVWYunTcz</enc>]]>
    </text>
  </js>
</dir>