<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridFinding.xml">
]>

<dir id="dmhotline_td" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh sách số điện thoại tiếp nhận tố cáo" e="List of Complaint Hotlines"></title>
  <subtitle v="Xem, sửa dữ liệu..." e="View, update data..."></subtitle>
  <grids>
    <grid table="dmhotline" fieldKey="ma_hl" order="ma_hl" allowFilter="true" allowOrder="true" key="ma_loai = ''TOCAO''">
      <fields>
	    <field name="unit_id" hidden="true" dataType="I" width="120" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="100" fieldType="EX" >
          <text v="Đơn vị" e="Unit"></text>
        </field>
		<field name="ma_hl" width="120" fieldType="PK">
          <text v="Mã hotline" e="Hotline Code"></text>
        </field>
		<field name="hl_name" width="200">
          <text v="Tên hiển thị" e="Employee Code"></text>
        </field>
		<field name="hl_lienhe" width="120">
          <text v="Người liên hệ" e="Department Code"></text>
        </field>
		<field name="dien_thoai" width="150" align="right" fieldType="PK">
          <text v="Điện thoại" e="Phone"></text>
        </field>
		<field name="ma_loai" viewType="Combobox" width ="150">
          <text v="Mã loại" e="Type Code"></text>
          <viewInfo>
			<options query="select ma_loai, ten_loai%l from dmloaiphone where status = 1 and ma_loai = 'TOCAO' order by ma_loai">
            </options>
          </viewInfo>
        </field>
		<field name="ma_ttp" width="120">
          <text v="Mã tỉnh thành" e="Province/City Code"></text>
        </field>
		<field name="ten_ttp" width="200" fieldType="EX">
          <text v="Tỉnh thành" e="Province/City"></text>
        </field>
		<field name="ma_phuongxa" width="120">
          <text v="Mã phường xã" e="Ward/Commune Code"></text>
        </field>
		<field name="ten_phuongxa" width="200" fieldType="EX">
          <text v="Tỉnh thành" e="Province/City"></text>
        </field>
		<field name="ghi_chu" width="150" align="right">
          <text v="Ghi chú" e="Note"></text>
        </field>
		<field name="status" viewType="Combobox" width ="150" valueDefault="1">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_tt, ten_tt%l from dmttsd where status = 1 order by ma_tt">
            </options>
          </viewInfo>
        </field>
      </fields>
	  
&DefaultButton;
	<script>
        <query>
          <text>
            <![CDATA[<enc>roJE7XXa5Gu+upPrtoyy5g9+RJRP4AbptihuD47RSxSABSXvL6nkHHZl7ZMpxYdASMOvvNjajgPyZ6KX6qAYPwOOO5LyDGjfsgyzCK+6Diy9i5uKQBqshgX6IlSxtThi2/IXk0uCiD1KnZNxLcBdkWPnREpJK+KCxNgP6OpC3XdEegOQhJCJ419JPc7P+J6StXIRJoSTDZVwiYKcGU4Jd05m2VBg+px7J54BUQ9424mXXPH6o5jujxYe8TOEpggdGgCiZdYmR+xoP+9HYo7Oe18QG9u7V2V14RH9nzsvDLQ=</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>TKq3I2t2bksYrz6P3CEm1xdA2mogXGaZR99Vws1X8fOmmeqEnbKyovBc/Jjcbnm98Y/Pg9gexcEYs49nrQb376TO9LaDT0GWxjG0ko84yRqUoQiGqFYdLK6Rh4B6+XCeZ1T+30li1xpORGwJAMbEHc0iYCoYXbni0C+up0zIhF3TcgLRvSsuh5V1Hf5wkva+ntOSw4d/YRAK1h1Kts75NFj3wGuI9Ksu3cyTwqozLppvB8lff1jNzhhx8wR3vorStxMlqrSdEqv6ix7bRyf3kXVMtPs4jVOg8Ltur4HoFTfa12x0DCAheTSAdkD5I1FgMrWwCUpaObWXpShbW9zm9A==</enc>]]>
          </text>
        </finding>
      </script>
    </grid>
  </grids>

  <js>
    <text>
	<![CDATA[<enc>uw3iZoR/y/5o6FF1x5y/2UOiuYHtHcg48hQ+ShHJaa60wyDUv5gGBsu144DZVzKNx8siFTL2EQsjBI749DA83sq/gfatmKY0KF3fOBfGa6j3Q63t3Kt4z9gmacoIh+ATnxHNfJpQpyYs3mVF66ke90ARfPOnS0cmYmuj2sX8CMVEbO2RT5POy1C/+tZX+sz8</enc>]]>
    </text>
  </js>

<css>
    <text>
      <![CDATA[<enc>J6OIfIkrZcbFFbjviVuzNmComv78Na7lJWHZAZvtJ32C5rRh7mAR3/WnWETJrJJ0Z6ChBESIyvw4Rs3HIxlDgZzdZvv/mMMYdfL5QVgv0234EmbPablq1lUS+DYxCMSHIgA6R2LF9jlcMZ7XM6eshBINDjoFqGtOTODYJjZHcbnKbiS5Vy+ISsEkkSHRyYyyR0hovEatw9SImh3ZfbthadLlX1fUMJt2EssemdULIzp4BaG1YYcfFElDb2I9/oziAyu/Wjr23j5AdqnbqG4VDVJI2Kwk6tKSh5kQdeQo2FX2En4WgIO4Io4MB6JJErUi</enc>]]>
    </text>
  </css>
  <script>

  </script>

</dir>