<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmhtsc" dirViewType="Grid" dirObjectType="Voucher" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục hình thức sửa chữa" e="List of repair forms"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmhtsc" fieldKey="ma_htsc" order="ma_htsc" allowFilter="true" allowOrder="true" >
      <fields >
        <field name="ma_htsc" width="170" fieldType="PK">
          <text v="Mã hình thức sửa chữa" e="Repair form code"></text>
        </field>
        <field name="ten_htsc" width="250">
          <text v="Tên hình thức sửa chữa" e="Repair form name"></text>
        </field>
		 <field name="status" width="150">
          <text v="Trạng thái" e="Status"></text>
        </field>
      </fields>
		
      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>gbveqZ921+F0tM5Cn1/sdIIjvYrrrcr5tN3rExNVy2PHE7//UBuZoaKDxRDX7R68kykbW7uDfX1av8bP9ijcTk9XFBrOLd6iBLOMzyG+FkjulQ96TvgO/VR8v2bUAJDfOj87r5n+rnZeJ2yAjGvK0yauvCIyIdep/Y7+LPXCo5q7ZWQwFiPlFnVhsHI70cyV</enc>]]>
    </text>
  </js>
</dir>