<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmhttt" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục Hình thức thanh toán" e="List Payment"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmhttt" fieldKey="ma_httt" order="ma_httt" allowFilter="true" allowOrder="true" >
      <fields >
        <field name="ma_httt" fieldType="PK" width="170">
          <text v="Mã hình thức thanh toán" e="Payment code"></text>
        </field>
        <field name="ten_httt" width="250">
          <text v="Tên hình thức thanh toán" e="Payment name "></text>
        </field>
		 <field name="status" width="250">
          <text v="Trạng thái" e="Status"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>gbveqZ921+F0tM5Cn1/sdIIjvYrrrcr5tN3rExNVy2Px6OeLd8A2wW7/F9djpbpq8fqLX2Wm0kB0Mo+2hyShtipSP66Viv+pUKkZq8I/yRaRlY0RiNQu5n6/KtvZCAQqwWwS0JX3pRaQTfjzfR8Ybwn2vhpizxw3CZXIP2+NvZvLoEJaJMpJe1tw4JnQAGIp</enc>]]>
    </text>
  </js>
</dir>