<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmkc" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục khoảng cách" e="Distance catalog"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmkc" fieldKey="ma_kc" order="ma_kc" allowFilter="true" allowOrder="true" >
      <fields>
        <field name="ma_kc" fieldType="PK" width="120" >
          <text v="Mã khoảng cách" e="Distance code"></text>
        </field>
		 <field name="ten_kc" width="250">
          <text v="Tên khoảng cách" e="Distance name"></text>
        </field>
		<field name="noi_di" width="250">
          <text v="Nơi đi" e="Distance name"></text>
        </field>
		<field name="noi_den" width="250">
          <text v="Nơi đến" e="Distance name"></text>
        </field>
		<field name="chieu_dai" width="120">
          <text v="Chiều dài" e="Distance name"></text>
        </field>
        <field name="status" width="120">
          <text v="Trạng thái" e="Status"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>wpR3ICmqndSY1Y0uQqHX9Na7q9RXcSvZvh2KS1Pkf3uFwSNlBd4EukAD/uxMXFEN2Gxc9jYE16uPbtbXuoYJaevkN0G6lc2OG+4YoOQA1VkBN1doa/ct/3KBNK9z7Mx+lX4SzwqRiE6+ov1l4dkxzZ40p0DE/+gtiB8GaV+LGAw8PwUuJo7nrjHYggs9wM8R</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
</dir>