<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="vdmlo" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục lô" e="Lot Maintenance"></title>
  <subtitle v="Cập nhật lô: thêm, sửa, xóa..." e="Add, Edit, Delete Lot..."></subtitle>
  <grids>
    <grid table="vdmlo" fieldKey="ma_vt, ma_lo" order="ma_vt, ma_lo" allowFilter="true" allowOrder="true">
      <fields>
        <field name="ma_vt" fieldType="PK" width="100">
          <text v="Mã hàng hóa" e="Goods"></text>
        </field>
        <field name="ten_vt" width="300">
          <text v="Tên hàng hóa" e="Goods Name"></text>
        </field>
        <field name="ma_lo" fieldType="PK" width="100">
          <text v="Mã lô" e="Lot"></text>
        </field>
        <field name="ten_lo" width="300">
          <text v="Tên lô" e="Description"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>uw3iZoR/y/5o6FF1x5y/2R+LYPQPUfZfUjuTB2vd6jq4HLf0X4Zl2SpWy76mC8rM2LiBvjKyfftgGPv2I3ubAuggeCUNXNS2/yqC4ccX/WlRH1wkoyy4VRZ/MFfpoQoPO/2kBs5ydF5ubAcXKjZB9qc0KfIQmAQSrGRPAoSQOC57ty2wfFqAnI3EEqfG+5MA</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>cTMcaemK/mtRjps8m/sJOVirlLEJ+6JxiLPeJpYli4TAugeI+9xS9CIT96sX4XiNHefVQOt7fompL31ydAZJ3zbOdWMd5eIffmA/BGo5olHD9HllibL9oaJ+q8SIGGIxctuUbBiK/AoBCVom/JB6t7K63gLTkI+n1+rKmi9w1o3agX3Q3T7VA7fpVMPNyATDKCMwOuHkuP8gVjUw+qEn8lDMfSVRMnD0/FysmWigoBh/gLFLiJHLlzQDzpc5t/w9ovG2+hZPKJkxSGbquy14Z/Moy+LeKNtoKkGhDFJLvHX1Z9I5Pqnoi64lNbwHXFIxbOALp0KsYLr56b26De9xBtmOeTdLi0YparLh4bTcD2fca+XxZyDGiDNFsNbEQ0ln</enc>]]>
    </text>
  </css>
</dir>