<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmloaingaycong" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục loại ngày công" e="Workday Type Category"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmloaingaycong" fieldKey="ma_loaingaycong" order="ma_loaingaycong" allowFilter="true" allowOrder="true">
      <fields >
        <field name="ma_loaingaycong" fieldType="PK" width="120">
          <text v="Mã loại" e="Type code"></text>
        </field>
        <field name="ten_loaingaycong" width="250">
          <text v="Tên loại" e="Type name"></text>
        </field>
		<field name="ten_loaingaycong2" width="250">
          <text v="Tên tiếng anh" e="English name"></text>
        </field>
		<field name="status" width="80" align="center">
          <text v="Trạng thái" e="Status"></text>
        </field>
      </fields>

      &DefaultButton;
      <script>	
        <query>	
          <text>	
            <![CDATA[<enc>hVvngwxUvvF9cm0YNi9XupBqKcOiV4lsrYUoIhvNS7X5DakbdN6BwSFfiTf2oPg/qLsvMNNHeXGJ4mIiyax7XAWTnbBK5Q6VtJa5+pf6M2KvjjSHHSsb2o8GXeSLWbOaYpRswKufUCVRtm1ng1//0fwxWjG8keCKjPmQW0+J1eqJ2X2K2Rk6rWsW2XwPOWOKbH2j6yuA7eZ7lTBIPKjfcYELZwozOdr9x+cr35Eimnw=</enc>]]>	
          </text>	
        </query>	
        <finding>	
          <text>	
            <![CDATA[<enc>ZNLZLqQuoJfX2pACKzbgQVTUUvHprRxoBQCv6hM/aDqbRm5DAp9ZgNLLWQOwtKWskZ0W03gBhqTB1OIbHQn6CqmKP3TkmJ4yxRutAdgNNTKhnTWn8Tbs5VSvZIiq5vhr07fZGn3ZXBXL7bcR/mBY8Yg152nbm/mXQHHGJNB6wfDTJdhGx1Pm+GxGhq7QHwSHntI1h3+B1Kdb3kQmY6zX1m3+22hg1zsENkGccJQOwOvblppSZtRPsXbkZs5Soe33</enc>]]>	
          </text>	
        </finding>	
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>Ur8s8ENK+kEovRhMMJmoZpesvkD8no0C4diFDctweiVLu3Dfl1SATR/TAdua8YMmLius+Dvb42NnOCWZDPcyrMfn4PAkAK6YUoZguAcR2UlolmeN4zw6LcBBbe2a6mc/CymguKqmlxBYNr1zTdgi8nMaIyGNAFtXzF4XuXAU9kNITw+F4Pcpw7al/0AauDCD</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
</dir>