<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmloaixe" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục loại xe" e="Vehicle Type List"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid id="0" table="dmloaixe" fieldKey="ma_loai" order="ma_loai" allowFilter="true" allowOrder="true" >
      <fields>
        <field name="ma_loai" fieldType="PK" width="120">
          <text v="Mã loại xe" e="Vehicle type code"></text>
        </field>
		 <field name="ten_loai" fieldType="PK" width="120">
          <text v="Tên loại xe" e="Vehicle type name"></text>
        </field>
        <field name="status" width="250">
          <text v="Trạng thái" e="Status"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>maUmHEvKnvPHe3V8WfMU+Ul6O3vM/hKqsgcjdodr87QJ8dXxOAe1FfV4VHzTsq1mJueOxtjn2OYUhxVz7j17UbgMQMyPWamQKI3v2yvBEswFd7ALSibl1BN0lNpXSMoIKQi9W9s44ZLQMxFKhnbiEVJD8s+622VS/Gtq83HKpPB4xcOeig2veY+TqxYBe20k</enc>]]>
    </text>
  </js>
</dir>