<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmloaithue" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục loại thuế" e="Tax Type List"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmloaithue" fieldKey="ma_loai" order="ma_loai" alowFilter="true" allowOrder="true">
      <fields >
        <field name="ma_loai" fieldType="PK" width="120">
          <text v="Mã loại thuế" e="Tax type code"></text>
        </field>
        <field name="ten_loai" width="250">
          <text v="Tên loại thuế" e="Tax type name"></text>
        </field>
		<field name="status" width="100">
          <text v="Trạng thái" e="Status"></text>
        </field>
		 <field name="ten_loai2" width="300">
          <text v="Tên khác" e="Other Name"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>CyMbKK/FGo4nORVjcrUYAUNbcmfvvv2ChJyXwHiqbNCJXK13ktUgUtmY3IzhZUSVbEa+fTrts+xJPQm6FojZZALmuvJwLnE3KzAWgvsmrLZ1HIJKYLcdKBx9MgvkFaXtf41iiZ9Ftdege75yWtEb8hpJJRzxd7lv4cE+2L4btIhwcWKUABObOS/bgVODLkNt</enc>]]>
    </text>
  </js>
</dir>