<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmloaibh" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục loại bảo hành" e="Warranty type of List"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmloaibh" fieldKey="ma_loaibh" order="ma_loaibh" allowFilter="true" allowOrder="true">
      <fields >
        <field name="ma_loaibh" fieldType="PK" width="120">
          <text v="Mã loại bảo hành" e="Warranty type code"></text>
        </field>
        <field name="ten_loaibh" width="250">
          <text v="Tên loại bảo hành" e="Warranty type name"></text>
        </field>
		 <field name="status" width="120">
          <text v="Trạng thái" e="Status"></text>
        </field>
		<field name="unit_id" hidden="true" dataType="I" width="120" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="100" fieldType="EX" >
          <text v="Đơn vị" e="Unit"></text>
        </field>
      </fields>

      &DefaultButton;
	  <script>	
        <query>	
          <text>	
            <![CDATA[<enc>n6SsM4/jSBKuL3BfLolp3Bs2/YOLI/FvlP7XpPWcraL0WHco89iLqaubg0HfGPyIwLXFjIQEBX0GoAdnyUfSYShu2JI9xr8Jee02GC2GnzcMDeCyFzZXnUkc4NpWqFVTCpMH69g9Swb4uQqQqqnP4nRlET/wakzzt/ds5MAbDHz7PN0ooGDnYVeGpHtznK8nab7X44xE69owqE64MeGfYjtozqE3rZi38HO4x44PGN8QemSAOl9squ2vlc3hz6jzLGYriQ8J6qw3DicZXv8kdw==</enc>]]>	
          </text>	
        </query>	
        <finding>	
          <text>	
            <![CDATA[<enc>g88cANqAF+DMlcrfKZ8g3yPZXbLMmOhPD8syHg/tGdx/3C9QOyGxA2Vq2oeUAT533i8YNK2XNAtiNqz/5/2CjyxiZMr0xqoImCr0khSzquBMWzAtQEX7Ic1QQcqViq+w/3mqVchds9m4aW+qdY1DBFuz4RM2SvQtXXJgDl5VjeV/yYpCVKC8gMm2W2i8ZZyELr+JEC8xaoeWLAoYLUHhR3LPRAZBOt+i9un7+Apyf6IrXcThLSmwIwIMBzNr7m36PdRevRuoS2uy1PTzIykxcQ==</enc>]]>	
          </text>	
        </finding>	
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>Xm0SQO244yhm4oovG3IvuLeLIyJNX4Y9n7qfFwoZpqw3h+01ykkASs+1Ih5sbRz6X0pAeXbtmE7QEiI1IRU4eT/QMPPU8+Y6WqXHowwKACxt1MPiaG1mgpmhWHHeasu1dE+n73XOXfrPWPuf1UwzR2jqXNHpscvb1NDawY64gzpZJh4B0btFUIZdsWG9hykI</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
</dir>