<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmloailuong" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục loại lương" e="List of Salary types"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmloailuong" fieldKey="ma_luong" order="ma_luong" allowFilter="true" allowOrder="true">
      <fields >
        <field name="ma_luong" fieldType="PK" width="120">
          <text v="Mã lương" e="Salary code"></text>
        </field>
        <field name="ten_luong" width="250">
          <text v="Loại lương" e="Salary type "></text>
        </field>
		 <field name="status" width="250">
          <text v="Trạng thái" e="Status"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>CyMbKK/FGo4nORVjcrUYAUWEq3EsDvVCpWlydKi7Bx9ZBIJyn4zDiZHO0nuWPKaIRupDejishgaubFAw0HxEufPR4LIRttQAKV9ntkbrKYUU7594PvtMF2RfdkDUetiz5TUYU5Igum9vHv8H2gRi/Gfk8iE8t560qSqswJiZ1kgNqoRDRyM1gC26ejVQEV+GXvAqwSKRc7w//XtzXEzoig==</enc>]]>
    </text>
  </js>
</dir>