<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmloailtx" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục loại kho và cảng" e="List of types warehouses and ports"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmloailtx" fieldKey="ma_loai" order="ma_loai" allowFilter="true" allowOrder="true">
      <fields >
        <field name="ma_loai" fieldType="PK" width="120">
          <text v="Mã loại" e="Type code"></text>
        </field>
        <field name="ten_loai" width="250">
          <text v="Tên loại" e="Type name"></text>
        </field>
		<field name="status" width="120">
          <text v="Trạng thái" e="Status"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>Xm0SQO244yhm4oovG3IvuM1BdQXNb4XcYXoumIJVYJMNRw4hMWORVVSnaSlE3pe4MPhVPGNxEutnCs8WLm8dYiPZ7WTK6j2+JIpX22sy2nik8ro/iV6Ton7m7Qyklz7l5UUNQ09DsbFGpSPyDxFBLThZeJrhhstnc3Dm+5EkzwCbTzjxz9R7BsN2POslM24B</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
</dir>