<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmloaichiphi" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục loại chi phí" e="List of expense type"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmloaichiphi" fieldKey="ma_loai" order="ma_loai" allowFilter="true" allowOrder="true">
      <fields >
        <field name="ma_loai" fieldType="PK" width="120">
          <text v="Mã loại" e="Type code"></text>
        </field>
        <field name="ten_loai" width="250">
          <text v="Tên loại" e="Type name"></text>
        </field>
		<field name="status" width="120">
          <text v="Trạng thái" e="Status"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>mMhxnlN0bwLPSrNy3eywdKefD07gNJgZiH/5LbZDbu/BLhKwfJdPbmxu6F6qQElFXCs+u+UqUbkK4yZo6E4IxK/vlPcNiX3bUG9hpiDvYUp0Svj7UBoZF4VLRbAdN7seG8atdTwuSy4FqwEKImtuW0vFi2xiOtwuUxtuXNDcJU7kPzbgfMsM5IiYY+yz2YrEzViJSdgk1poNOZj4Yi3Hqg==</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
</dir>