<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmloaidvt" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục loại đơn vị tính" e="unit Type "></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmloaidvt" fieldKey="ma_loai" order="ma_loai" allowFilter="true" allowOrder="true" >
      <fields >
        <field name="ma_loai" fieldType="PK" width="120">
          <text v="Mã loại ĐVT" e="Unit type code"></text>
        </field>
        <field name="ten_loai" width="250">
          <text v="Tên loại ĐVT" e="Unit type name "></text>
        </field>
		 <field name="status" width="250">
          <text v="Trạng thái" e="Status"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>Xm0SQO244yhm4oovG3IvuGWZVkwdldFFDmpUmMtuEWIyo46FocX69p7tvqIcH2eRugLLpd9wBKuXEJd9Wbr8RfQWY6H5kJ3cVYW3mTRIqBR87U+oO85kO8l2pyb7YGS9PTtILhQyTZsElKurT7qLovoAO5FKwr3Hd29S55D5L8fg+0dtsRi0rob8GQzhftTS</enc>]]>
    </text>
  </js>
</dir>