<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmloainghi" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục loại nghỉ, vắng mặt" e="List of vacation types"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmloainghi" fieldKey="ma_loainghi" order="ma_loainghi" allowFilter="true" allowOrder="true">
      <fields >
        <field name="ma_loainghi" fieldType="PK" width="120">
          <text v="Mã loại" e="Type code"></text>
        </field>
        <field name="ten_loainghi" width="250">
          <text v="Tên loại" e="Type name"></text>
        </field>
		<field name="status" width="80" align="center">
          <text v="Trạng thái" e="Status"></text>
        </field>
      </fields>

      &DefaultButton;
      <script>	
        <query>	
          <text>	
            <![CDATA[<enc>T1P00otPKsUcyvVCfWChNlS/XqaaLY0p7W4eQGVZ8kBBLX68NqPin8k777zNwg2qtVtS0nVW4AnKG3oDRI9K4hZlxuN+hQfgTni36b7EiUptSu9MSNXkvK8gzTWb73ikhB9f/yhcNztIuezw4cGmAJHH4xohSkhhYtHjbblANL8cAQnWYupIKUxPupJxM/XWlF+OVegepRQjlFKg+jfYLVz4XkNeyciN1sZVz/jbK8s=</enc>]]>	
          </text>	
        </query>	
        <finding>	
          <text>	
            <![CDATA[<enc>jEns0ggfKx6N1E62DxJK4m5d6OgOyki9aYM8Lu7Zn8z0sQrkTBfbow7GNxFE6/1E1a4ctbb4bivCyUaOECvGq8bZ1x9JvshGgnRcbGy/9bniIBob/rpN5DBS0TwIRYonBW7VHtjnKyFkiVuOYLXsfEXtYvHo3wCJ6SrGpnVp4u/cyGBq/Sxz+t6rQHh83oTIPBUXL9H+bbUuE71XxfvYTWpi0Iqq2N+Q4l9/YVYDq9fIYAT07Xm5zMxEA2iKiQHjzXCHGVfuxllyVy1vcH4Oz4H9gtKZxg/q8+3P+zeMrpGcoraoBkDbHpHna7z6DFHhrRaIFgpm0KHhR0EoYLrFZLcQCi3md2JL2c/qEczWjz0=</enc>]]>	
          </text>	
        </finding>	
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>He0/7dHkFsicFOIBGo9frErdL1oNbJ6nj6iZtdq6yyAl7PhcCZMOVO7gdFRL+ItFlextFt08Zx2rG0+wQVs2Fag/l+b4qo3SHNVMjhl18c4rAXrxYf6nBh641L0OS3FC5+/3/WVGFi33utvyzF3X0P7Yiu7GFcAkf8XNrUN0vbiInu7dznYMZrXZRQHNA2vL</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
</dir>