<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmloaidx" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục loại đề xuất" e="List of proposed types"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmloaidx" fieldKey="ma_loaidx" order="ma_loaidx" allowFilter="true" allowOrder="true">
      <fields >
        <field name="ma_loaidx" fieldType="PK" width="120">
          <text v="Mã loại" e="Type code"></text>
        </field>
        <field name="ten_loaidx" width="250">
          <text v="Tên loại" e="Type name"></text>
        </field>
	    <field name="ten_loaidx2" width="250">
          <text v="Tên loại2" e="Type name"></text>
        </field>	
		<field name="status" width="80" align="center">
          <text v="Trạng thái" e="Status"></text>
        </field>
      </fields>

      &DefaultButton;
      <script>	
        <query>	
          <text>	
            <![CDATA[<enc>T1P00otPKsUcyvVCfWChNlS/XqaaLY0p7W4eQGVZ8kBBLX68NqPin8k777zNwg2qtVtS0nVW4AnKG3oDRI9K4hZlxuN+hQfgTni36b7EiUptSu9MSNXkvK8gzTWb73ikhB9f/yhcNztIuezw4cGmAJHH4xohSkhhYtHjbblANL8cAQnWYupIKUxPupJxM/XWlF+OVegepRQjlFKg+jfYLVz4XkNeyciN1sZVz/jbK8s=</enc>]]>	
          </text>	
        </query>	
        <finding>	
          <text>	
            <![CDATA[<enc>A3W54x6lMMuVeGXkdNhwYLdHi+YlGcaeOHn7U2rz2j+gmZUQJevapjEZ0XvHQbgLXktIy4alZCVwKvxS1es0BgogRY9LjOBZNsB06ZDiQStv6Bn+JX9Q/ZAOQ/fI4bqtU4NyvFWhufIxbPrR6yb7XqoztpV4ebhYpwQ/8JMuoMFQhHsAtjZjCoYu07y5pdqKSxf1qlvpxhShg1YQu+YX9hVkHn6a46EQzD/nji+nz5pi431yVGV9p0MEKdJqWgHCyHfFygYY4NpNnwqbzx33mYD39y+mt5j22AyCPoaWMJtukD/q2ekYasymEr6NG0hmJERjIVnUKBfT8mMQbZUIEVAJCzzxQBdVuM6hG2bJ5Oo=</enc>]]>	
          </text>	
        </finding>	
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>Xm0SQO244yhm4oovG3IvuNUsEb5kJzBmz1z9UP0LlZO4PIPeMLgqNBU9YQq/Lg7zMb6pn2L2XP7jWiBqfPj01AePUqlnHhiQh99KqUHw7NcDD0WqgY6Clm+n1yaeRL/+pUHKTgyIk5XBWzPPVjoxl7bbcMu306we0RLcHkBely7PFYrrAENItHcm5SwhNg1P</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
</dir>