<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
	<!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmlvtc3" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
	<title v="Danh mục nghành hàng cấp 3" e="Level 3 product catalog"></title>
	<subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
	<grids>
		<grid table="dmlvtc3" fieldKey="ma_lvtc3" order="ma_lvtc3" allowFilter="true" allowOrder="true" >
			<fields>
				<field name="ma_lvtc3" link="1" width="150" fieldType="PK">
					<text v="Mã nghành hàng" e="Industry code"></text>
				</field>
				<field name="ten_lvtc3" width="250">
					<text v="Tên nghành hàng" e="Industry name"></text>
				</field>
				<field name="ten_khac" width="250">
					<text v="Tên khác" e="Other name"></text>
				</field>
				<field name="unit_id" width="120">
					<text v="Đơn vị" e="Unit"></text>
				</field>
				<field name="thu_tu" width="100">
					<text v="Thứ tự" e="Position"></text>
				</field>	
				<field name="status" width="120">
					<text v="Trạng thái" e="Status"></text>
				</field>
			</fields>

			&DefaultButton;

		</grid>
	</grids>

	<js>
		<text>
			<![CDATA[<enc>XTdhtH8UH+fi8dcVtUBb3R5yjdr3wZ22mGrckNFibBEjdhU5+lLGUN82EUbHeEJiI0sFdHYTM3Dpptge1oUNR/vz5x1uuUxXLMKkUGpvaEim77v9O7V/7hnauRvyl8Y/O2N8e+EJJfCq6Zzh+KGs82Li7Cz0SQcTfCCxq0nLVgMCsrICwHy7eAarAvGx7SQG</enc>]]>
		</text>
	</js>
	<css>
		<text>
			<![CDATA[<enc>e3k+XdGnbvZ0MKakN2CIp1L1V69Wn8hCjHPRJGLSVteZXTNCLSJS7Q/H0FV2ZXR75RjiO4uNxFPT1ALdiZVijJPsHsnnY0zjZdvzUmXCtILYmqIhY84/PfVBvwzKOd1txkpqeXDCYVkt/m3w7Au8+M1ctmL8B/XlgqFf/GGvJKi+8ilmLlDj0H1RAKXg0zC22Xe2HDqhMJuFbo+t6lxMH5t1jADBPescgO71e52oH/oHSZ8LJPBcwNuD5jx/7T4+fs+lIl6UiiSYkhLqyXq1oaU16ahznNAwyT8ypt2EIEC8/sqTMFxw55d/iI6i3DNsWEK9F1XGrg2OduKEKfVzTZiIYViuOT+xd8ohQdorjmfdFFh82n6oXdEY4u9LTb1a</enc>]]>
		</text>
	</css>
</dir>