<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmnganhcn" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục ngành CN" e="Commodity Menu"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmnganhcn" fieldKey="ma_ncn" order="ma_ncn" allowFilter="true" allowOrder="true">
      <fields >
        <field name="ma_ncn" fieldType="PK" width="120">
          <text v="Mã ngành CN" e="Agent Code"></text>
        </field>
        <field name="ten_ncn" width="200">
          <text v="Tên ngành CN" e="Agent Name"></text>
        </field>
		<field name="ten_ncn2" width="200">
          <text v="Tên khác" e="Another Name"></text>
        </field>
		
		<field name="status" width="250">
          <text v="Trạng thái" e="Status"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>Xm0SQO244yhm4oovG3IvuMRseCJ48xowyDRocP0Vb86JYT9KSRWBLSIHbalFuKHHeuBVbENdqQmPeCZBmyQ0VX6d+5QGOmMeg4lnWKw/z+YDXRwlcqimyxzSHHfpU0nU5lFURXry9H5vG5jAbdukWpT1vhPRXHFmIifsSYtxw+isv8FyO2bj5ID06W+vmkRW</enc>]]>
    </text>
  </js>
</dir>