<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmnganhnghe" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục ngành nghề" e="Occupation List"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmnganhnghe" fieldKey="ma_nganhnghe" order="ma_nganhnghe desc" allowFilter="true" allowOrder="true">
      <fields >
        <field name="ma_nganhnghe" fieldType="PK" width="120">
          <text v="Mã ngành nghề" e="Occupation Code"></text>
        </field>
        <field name="ten_nganhnghe" width="250">
          <text v="Tên ngành nghề" e="Occupation Name "></text>
        </field>
		<field name="ten_nganhnghe2" width="250">
          <text v="Tên tiếng anh" e="English name "></text>
        </field>
		<field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_tt, ten_tt%l from dmttsd where status = 1">
            </options>
          </viewInfo>
        </field>
      </fields>

      &DefaultButton;
	<script>
		<query>
		  <text>
		  <![CDATA[<enc>zxaPxfZ833ybSjd9yofPtkOpVrG9rEKLy6IXsg5rXHuqw+fybtvc0QArH48gpt0iGJhmRnp+7GPkg48lfXAfafikj26tioNOnZ6lFs85jPEnTBJ4lvqExTpfzn0gDvn/4TDWWgz14rPmxxfg9xKjb0cU4US+ihhn04St/JGxt36CM7HPxlDpVrZ+jIgx/39F</enc>]]>
		  </text>
		</query>
		<finding>	
			  <text>	
				<![CDATA[<enc>cxblwlTjuf0RelEES+YgsZATGUjj1wo1Zl1QZne9Nk4lytgooe+O79mt79AJT/x2s6hgTJDyvyiR9LYEKOz0RK5VhKahrAv1KXg64NbvLZMa78nmG7+qIl3MWgUzhdMrs0Y/LJwHc3BC3v9/NEpQh8MhURMNg3957EPh4AEHJE3ulbdXPZvizraCRHcGfubuH4focLEsk+GG7ai9F5rvx1jUqa3Wnu6aFYo5Z414ZOZ8cAGGUm7VRGddjMKwAbUr</enc>]]>	
			  </text>	
			</finding>	
	  </script>
    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>Yz0ptC4JBRSKhIpTcycdh6CNozYPve5Ch0qM8TqLMl0xAnvTvE44v/dxnfnSXwOnFEwLIhbeAFJXKxAWVL995Qoa23Liln14RsIyL/E90UQr6ryWm5aWrgmtJOo7YNofQA4dT/aprBAp2AT/hmxBudkA/LChH6UyGtoiq3o1y/vOKWaDNxPKX//DA/ytH/FLHQO+YeUcJzxIh+17EM9q0g==</enc>]]>
    </text>
  </js>
<css>
    <text>
      <![CDATA[<enc>2FI/rX3TUEulxi9LoMIkcrNxfLRl3EeU+vXNpxQMgjAUY+e+fGyRzUkW+9nk3DQhRGDcCci+9yN9eNtbKmU791f+T6ieUFfgOjsuRVms+RLXNXkR+TQtRCS4FV0pRfP1fcwNG+tYLjCPjgr/WKew/MUhXhi4bKC7rHkp5oZhUfiM7jrj07++4J47zqqm135YfI/4/B4osMfc4JwZvc4UdOOdVeGAUSTZf5EB2pZOESRmXLeEFulW+eR/+o1UWB+1/UKKBLZIthNkBHUSRWibuDm3AC2cEyXPFjWJchNUAhngrHccQ3Oat8UBetW1Q1NE</enc>]]>
    </text>
</css>
</dir>