<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmnhomkh" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục nhóm khách hàng" e="List of customer groups"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmnhomkh" fieldKey="ma_nhom" order="ma_nhom" allowFilter="true" allowOrder="true">
      <fields >
        <field name="ma_nhom" fieldType="PK" width="120">
          <text v="Mã nhóm khách hàng" e="Customer group code"></text>
        </field>
        <field name="ten_nhom" width="250">
          <text v="Tên nhóm khách hàng" e="Customer group name"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>Xm0SQO244yhm4oovG3IvuGWZVkwdldFFDmpUmMtuEWKq2uVQcgUGFIzDkAYrELEMMTI3Cd4mqdnxS4jpwbNdpg39wmI1vLllzQFkvrthbvfRzeZVIm+pqtST1PFzcnoVNEWCReuZVqQrnshf7mqEV2taDkaoqgpwkFtN7MLkmG5sPAHmFEiEgFk1nFHHE9/a</enc>]]>
    </text>
  </js>
</dir>