<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmnhomxe" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục nhóm xe" e="Vehicle group list"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmnhomxe" fieldKey="ma_nhom" order="ma_nhom" allowFilter="true" allowOrder="true">
      <fields >
        <field name="ma_nhom" fieldType="PK" width="160">
          <text v="Mã nhóm xe" e="Vehicle group code"></text>
        </field>
        <field name="ten_nhom" width="250">
          <text v="Tên nhóm xe" e="Vehicle group name"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>GYD0OC5JhpEhu2renQHOp0G45y+Ym1vNMLhSnecDl25PThlQrHg/LJ0ryX67OKc1VdvR1MQgtA+MJkWrAIOWzgTFFvnI6CeTqsdGw4HLI/xi2L17iXkqIs0LnnWCRSn5cP42tf0JggBamYow6pKTmhYmBn7fYMm15hllMbnlY1t5SD+fWgnLMPWgsGtWLBLX</enc>]]>
    </text>
  </js>
</dir>