<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmnt" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục ngoại tệ" e="Currency List"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmnt" fieldKey="ma_nt" order="ma_nt" allowFilter="true" allowOrder="true" >
      <fields>
        <field name="ma_nt" fieldType="PK" width="120">
          <text v="Mã ngoại tệ" e="Currency Code"></text>
        </field>
        <field name="ten_nt" width="300">
          <text v="Tên ngoại tệ" e="Currency Name"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>gbveqZ921+F0tM5Cn1/sdBb0fc8c5wcpa5hXjqsKkK1MU0e9D2YSqm4oA5YfguydmSRC2PPigmxX02S8gI5ts1KZpKTkgzEqH5PdS4NSHT2msTvc5iTUfX/xVcFHA3qNBCukKLYNdULo/yO/oFYdAZOTaMFU+EvZUDmzLHX9h2FdxDoALhr8dWefBx/3Xann</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>cTMcaemK/mtRjps8m/sJOVirlLEJ+6JxiLPeJpYli4TAugeI+9xS9CIT96sX4XiNHefVQOt7fompL31ydAZJ3zbOdWMd5eIffmA/BGo5olHD9HllibL9oaJ+q8SIGGIxctuUbBiK/AoBCVom/JB6t7K63gLTkI+n1+rKmi9w1o3agX3Q3T7VA7fpVMPNyATDKCMwOuHkuP8gVjUw+qEn8lDMfSVRMnD0/FysmWigoBh/gLFLiJHLlzQDzpc5t/w9ovG2+hZPKJkxSGbquy14Z/Moy+LeKNtoKkGhDFJLvHX1Z9I5Pqnoi64lNbwHXFIxbOALp0KsYLr56b26De9xBtmOeTdLi0YparLh4bTcD2fca+XxZyDGiDNFsNbEQ0ln</enc>]]>
    </text>
  </css>
</dir>