<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridFinding.xml">
]>

<dir id="dmnv" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục nhân viên" e="List of employee"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmnv" fieldKey="ma_nv" order="ma_nv" allowFilter="true" allowOrder="true" >
      <fields >
        <field name="ma_nv" fieldType="PK" width="120" hidden="false">
          <text v="Mã nhân viên" e="Employee code"></text>
        </field>
        <field name="ten_nv" width="250">
          <text v="Tên nhân viên" e="Employee name"></text>
        </field>
		<field name="ngay_sinh" width="120" dataType="D">
          <text v="Ngày sinh" e="Brithday"></text>
        </field>
		<field name="ma_bp" width="120" hidden="true">
          <text v="Bộ phận" e="Position"></text>
        </field>
		<field name="ten_bp" width="150" fieldType="EX" >
          <text v="Bộ phận" e="Department name"></text>
        </field>  
		<field name="ma_cv" width="150" hidden="true">
          <text v="Chức vụ" e="Position"></text>
        </field>
		<field name="ten_cv" width="150" fieldType="EX" >
          <text v="Chức vụ" e="Position name"></text>
        </field>  
		<field name="dt_mobil" width="120">
          <text v="Điện thoại" e="Phone"></text>
        </field>
		<field name="email" width="120">
          <text v="Email" e="Email"></text>
        </field>
		<field name="dia_chi" width="250">
          <text v="Địa chỉ" e="Address"></text>
        </field>
		<field name="status" viewType="Combobox" inactivate="true" width="120">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="5">
                <text v="Đang làm việc" e="1 - Use"></text>
              </option>
              <option val="7">
                <text v="Nghỉ thai sản" e="0 - Not use"></text>
              </option>
			  <option val="9">
                <text v="Nghỉ làm" e="1 - Use"></text>
              </option>
            </options>
          </viewInfo>
        </field>

      </fields>

      &DefaultButton;
   <script>
        <query>
          <text>
            <![CDATA[<enc>KB8xqdyii61Ha3yaQfUGVWJJi0XGB5rYOgFuu0IuNtCcfzcDuy7YU/NUwPWflIinw2+TGWqxmGc8CzIndVR1zofL9xLuDTwMnayAiMwXU7od4NC4Gj0Kaqay+zpqh1Q4fiqvMFwr83Oobtw/8t2SYF8eTi9B4dhQWWSBXwbxBlOyzJfctgbZCzHki+nh2afgHxQy4MzWgJzsm61t7MqUhaKS4ZHkRcjkNRR4gv3yZwovVtc5MFnZLnkA5Yfk3EhT4OM3q7O/BOCvTiqxWZg/bsREpvijEHacq4+Hv3FjmnIeHI5vlqZsJ/hQ+AZobQpc</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>Eax40H31vvCK8D4iqRmSQ3z7AvnwR53MUT9JWUwhWaYrJq9qDieUYHvhC4ZyIv9H1lM2MUG00yqVYl0Hzn0l+BHuGdkDd0Sqp39Ubm88a2G+rSvC3Dm2NTIDviyX/9ksByw12h1klCTXh2+lT+TTRM7bzO8jgFLYu7x/8tNMKE+I1oktZNB9uqpNXIYMNZUirvfdXkhL3i0b9nO1zDHqAs3el90Mc6smmGSuERRzqteEvsFqBj0PIkORsEFw6JafCGGpIdIBhxS2lI5s+PggSrWtVUGHOH6YCqHC81ZIn5fAhln78m+d1owJvXREp0wW0hO9+9JH9QHKR0KeY9pmqg==</enc>]]>
          </text>
        </finding>
      </script>
    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>gbveqZ921+F0tM5Cn1/sdDZ3cUcoUI1YCqu2PjebA2XZS085whUjfAirvdUP2OeaFmJZr65CB+a0jtVED4Mz7k9kqG7S81ztQW0bKSi4fqMwBNQDzXieHTme/rOh02zrBHrLqae/mVBAdpX2F8KkOJGbWAibU1ddAntuhzYl4B9pIImQZbawyHZD3AIBDYLO</enc>]]>
    </text>
  </js>
</dir>