<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmnv" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh sách nhân sự" e="Staff List"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmnv" fieldKey="ma_nv" order="xstatus" allowFilter="true" allowOrder="true" key="xstatus = 5">
      <fields >
		<field name="unit_id" hidden="true" dataType="I" width="120" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
		<field name="ma_unit" width="120" fieldType="EX" align="center" >
          <text v="Đơn vị" e="Unit"></text>
        </field>
		<field name="ma_pb" width="80" hidden="true">
          <text v="Phòng ban" e="Department"></text>
        </field>
		<field name="ten_pb" width="200" fieldType="EX" >
          <text v="Phòng ban" e="Department"></text>
        </field>  
		<field name="ma_bp" width="80" hidden="true" align="Center">
          <text v="Tổ/Nhóm" e="Section"></text>
        </field>
		<field name="ten_bp" width="200" fieldType="EX" >
          <text v="Tổ/Nhóm" e="Section"></text>
        </field>  
        <field name="ma_nv" fieldType="PK" width="100" hidden="false">
          <text v="Mã nhân sự" e="Staff Code"></text>
        </field>
		<field name="ten_nv" width="200">
          <text v="Tên nhân sự" e="Staff Name"></text>
        </field>

		<field name="ma_gt" viewType="Combobox" inactivate="true" width="100" >
		  <text v="Giới tính" e="Gender"></text>
		  <viewInfo>
			<options query="select ma_gt, ten_gt%l from dmgioitinh where status = 1">
			</options>
		  </viewInfo>
		</field>
		<field name="ngay_sinh" width="120" dataType="D" align="Center">
          <text v="Ngày sinh" e="Brithday"></text>
        </field>
        <field name="ten_gt" width="120" fieldType="EX" align="center" hidden="true" >
          <text v="Giới tính" e="Gender"></text>
        </field>
		<field name="ngay_bd_lv" width="0" dataType="D" align="Center">
          <text v="Ngày bắt đầu làm việc" e="Joining Date"></text>
        </field>
		<field name="cmnd_so" width="0" align="right">
          <text v="Số CCCD" e="Citizen Identification Card"></text>
        </field>
		<field name="ma_cv" width="120" hidden="true">
          <text v="Chức vụ" e="Duty Code"></text>
        </field>
		<field name="ten_cv" width="200" fieldType="EX" >
          <text v="Chức vụ" e="Position"></text>
        </field>  
		<field name="ma_vtcv" width="120" hidden="true">
          <text v="Vị trí công việc" e="Job Position Code"></text>
        </field>
		<field name="ten_vtcv" width="200" fieldType="EX" >
          <text v="Vị trí công việc" e="Job Position Name"></text>
        </field> 
		<field name="parent_nv" width="120">
          <text v="Mã cấp trên" e="Manager Code"></text>
        </field>
		<field name="parent_ten_nv" fieldType="EX" width="200">
          <text v="Cấp trên" e="Manager"></text>
        </field>
		<field name="dien_thoai" width="120">
          <text v="Điện thoại" e="Phone"></text>
        </field>
		<field name="email" width="120">
          <text v="Email" e="Email"></text>
        </field>
		<field name="dia_chi" width="250">
          <text v="Địa chỉ" e="Address"></text>
        </field>
		<field name="xstatus" viewType="Combobox" inactivate="true" width="100">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="5">
                <text v="Đang làm việc" e="Working"></text>
              </option>
              <option val="9">
                <text v="Nghỉ việc" e="Quitting your job"></text>
              </option>
			  <option val="7">
                <text v="Nghỉ chế độ" e="Vacation mode"></text>
              </option>
            </options>
          </viewInfo>
        </field>		
	  </fields>
&DefaultButton;
    <script>
        <query>
          <text>
            <![CDATA[<enc>V8jL8O6o25SZvpyQeujkrRRdyqJ7jGfi/XeGVRWgU7Ha8K+snRMiWE2o/FUO4qKEyLnYm7RdVYhbLJBu9FgYc8+oU9txLzNZgCF+p/zOCGTy1g9zgDRBa3XKVEcBIyKQ5ibdIqHufZoaCkTKGkF1dpYFGhmVPGoc/RO7XCuPOkezxSveLSLZoC/6bC/bZ16pF9hv4XVKD7SUPwMs7o7OPWnxQnPU/hFOQZSWtTfz+T/oKEd9NkiTFKYlEfkAOSgC+lpM/cB4OXno7BDmnrhlhv3TGX0LEzdVyt9svggjlFYxLEsPFru5rk1LrD3T3VFJwYuBt0Z1cq+9MoRSOFf9e4SanNvMmxzD+7cJmqWbrWX/UVb8sRG9u/gBOrphafQfcLWydMA6nEfYoyo1hlNHnw==</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>LUA8bVLhZcCFX3DOxD8RcMnwF5+ADhLtA0UWhtkxOVJpfkaXw5DmBB6iXYAE7ArcbYsujA+iJaIzb+E7uNkavXCCncz4K5vBf/PwVeybbevMtk2coLEWbjKgjX96dBY2ogW1zHonqL8pqq5kWAoiXXIU0JeptWs4aEVdBfL6r08uD372mFiSJgxwM13GejfXEwoIdc3SSLkICy2Tmy9hdekt3lJwBp6OfjkWvG6gqtr7Qbw6yvy8saEfHanOJdx2ibeGK566pL6Z3qjrYyvl7dhTqqblQwbgao3/YB+ITfIsfv1+6gJm7EZpsClWajsSIL5BfrdbdF91otQySi5inRTNaDEmrQIfDDHz+fvRlArFm6DArMb5oD9jnhKK0GY27rq1XgGNRlcW7QlQVsdncXHkSzHIwnld5v8m820XXSkL4cSnj1TCuKn0HoeL7Wbi+O9wL7+uVYYXpHD8f4x4rg==</enc>]]>
          </text>
        </finding>
      </script>
    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>gbveqZ921+F0tM5Cn1/sdDZ3cUcoUI1YCqu2PjebA2XZS085whUjfAirvdUP2OeaFmJZr65CB+a0jtVED4Mz7k9kqG7S81ztQW0bKSi4fqMwBNQDzXieHTme/rOh02zrBHrLqae/mVBAdpX2F8KkOJGbWAibU1ddAntuhzYl4B9pIImQZbawyHZD3AIBDYLO</enc>]]>
    </text>
  </js>
   <css>
    <text>
		<![CDATA[<enc>J6OIfIkrZcbFFbjviVuzNmComv78Na7lJWHZAZvtJ32C5rRh7mAR3/WnWETJrJJ0Z6ChBESIyvw4Rs3HIxlDgZzdZvv/mMMYdfL5QVgv0234EmbPablq1lUS+DYxCMSHIgA6R2LF9jlcMZ7XM6eshBINDjoFqGtOTODYJjZHcbnKbiS5Vy+ISsEkkSHRyYyyR0hovEatw9SImh3ZfbthadLlX1fUMJt2EssemdULIzp4BaG1YYcfFElDb2I9/oziAyu/Wjr23j5AdqnbqG4VDVJI2Kwk6tKSh5kQdeQo2FX2En4WgIO4Io4MB6JJErUi</enc>]]>
    </text>
  </css>
</dir>