<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridFinding.xml">
]>

<dir id="dmnv" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục nhân viên" e="List of employee"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmnv" fieldKey="ma_nv" order="xstatus" allowFilter="true" allowOrder="true" >
      <fields >
		<field name="unit_id" hidden="true" dataType="I" width="120" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
		<field name="ma_dv" width="120" hidden="true">
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="ten_dv" width="120" fieldType="EX" align="Center" >
          <text v="Đơn vị" e="Unit"></text>
        </field>
		<field name="ma_pb" width="120" hidden="true">
          <text v="phòng ban" e="Position"></text>
        </field>
		<field name="ten_pb" width="120" fieldType="EX" align="left">
          <text v="Phòng ban" e="Department name"></text>
        </field>  
		<field name="ma_bp" width="80" hidden="true" align="Center">
          <text v="Nhóm" e="Team"></text>
        </field>
		<field name="ten_bp" width="80" fieldType="EX" align="center" >
          <text v="Bộ phận" e="Department"></text>
        </field>  
        <field name="ma_nv" fieldType="PK" width="100" hidden="false">
          <text v="Mã nhân viên" e="Employee code"></text>
        </field>
		<field name="xstatus" viewType="Combobox" inactivate="true" width="100">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="5">
                <text v="Đang làm việc" e="Working"></text>
              </option>
              <option val="9">
                <text v="Nghỉ việc" e="Quitting your job"></text>
              </option>
			  <option val="7">
                <text v="Nghỉ chế độ" e="Vacation mode"></text>
              </option>
            </options>
          </viewInfo>
        </field>
        <field name="ten_nv" width="200">
          <text v="Tên nhân viên" e="Employee name"></text>
        </field>
		<field name="ngay_sinh" width="120" dataType="D" align="Center">
          <text v="Ngày sinh" e="Brithday"></text>
        </field>
		<field name="ngay_bd_lv" width="120" dataType="D" align="Center">
          <text v="Ngày vào cty" e="Date joining company"></text>
        </field>
		<field name="cmnd_so" width="100" align="right">
          <text v="CMND/CCCD" e="Date joining company"></text>
        </field>
		<field name="ma_cv" width="120" hidden="true">
          <text v="Chức vụ" e="Position"></text>
        </field>
		<field name="ten_cv" width="150" fieldType="EX" >
          <text v="Chức vụ" e="Position name"></text>
        </field>  
		<field name="ma_vtcv" width="120" hidden="true">
          <text v="Vị trí công việc" e="Job position"></text>
        </field>
		<field name="ten_vtcv" width="150" fieldType="EX" >
          <text v="Vị trí công việc" e="Job position"></text>
        </field> 
		<field name="parent_nv" width="120">
          <text v="NV quản lý" e="Managerial staff"></text>
        </field>
		<field name="parent_ten_nv" fieldType="EX" width="180">
          <text v="NV quản lý" e="Managerial staff"></text>
        </field>
		<field name="dien_thoai" width="120">
          <text v="Điện thoại" e="Phone"></text>
        </field>
		<field name="email" width="120">
          <text v="Email" e="Email"></text>
        </field>
		<field name="dia_chi" width="200">
          <text v="Địa chỉ" e="Address"></text>
        </field>
	  </fields>
    <buttons>
	   <button id="add">
		 <text v="$AddToolbar" e="$AddToobar"></text>
	   </button>
	   <button id="edit">
		<text v="$EditToolbar" e="$EditToolbar"></text>
	  </button>
	  <button id="delete">
		<text v="$DeleteToolbar" e="$DeleteToolbar"></text>
	  </button>
	  <button id="copy">
		<text v="$CopyToolbar" e="$CopyToolbar"></text>
	  </button>
	  <button id="view">
		<text v="$ViewToolbar" e="$ViewToolbar"></text>
	  </button>
	  <button id="split">
		<text v="-" e="-"></text>
	  </button>
	   <button id="find">
			<text v="$FindToolbar" e="$FindToolbar"></text>
	   </button>
	  <button id="refresh">
		<text v="$RefreshToolbar" e="$RefreshToolbar"></text>
	  </button>
	  <button id="freeze">
		<text v="$FreezeToolbar" e="$FreezeToolbar"></text>
	  </button>
	  <button id="split">
		<text v="-" e="-"></text>
	  </button>
	   <button id="print">
		<text v="$PrintToolbar" e="$PrintToolbar"></text>
	  </button>
	  <button id="export">
		<text v="$ExportToolbar" e="$ExportToolbar"></text>
	  </button>
	   <button id="downtemplate">
			<text v="Tải mẫu Excel" e="Down import template"></text>
		</button>
		<button id="import">
			<text v="Lấy dữ liệu từ tập tin" e="Import data"></text>
		</button>
	</buttons>
   <script>
        <query>
          <text>
            <![CDATA[<enc>40X158CCpxU7hW80mktITK0Xvy3ANG/czoavHkCtG1ERQCumuhpU8O+OStd7H7H7hQmoPvjq4S6uCXuV8bLg7/CpXNrx+AC0A61vh9F2QcWNX4nCb5Nys/ovLywLRM3pK6TIwCpVR58hYD5fwMr/Ve9evZc1f+q8T0L+avalUBSaeXqp5/toS1URfugAwzVuBW9akxgG51hAJY0UlKaomkje9Zgexqd0QDPvFe0DLGhM/Bs/UlB9visWCFS9h1qHkc3iZUynOfLdmVLdvYYp9Wl8bjGhT0Ww7+WNWZUXvDJecPVRhQMcaDK4VTzO9obpLThZgLD9zxJ2//Dxau2FoU2qXqpAa0EIa3uxoZcoi/kvpRhXG0tZCoEz8x7w2UzmXTLckWdNEdb8Iv3HqPfj6Z5GdIH8CpJX8Js7N3Mc2tYhFCWKA5O3mfD9x1L3avEs5U1BhsG8F9ZhlGTws7/z7rwhCgTCONsll4AfduxCXo6F2QyR1NF4fMpRLIuWDHw0xg6/MLggZRcHR9avokDvZbmVrCg081C23sRtGA6uZDSbpJ8b1rj5O97yLy+KHWhL+Hjpj/r2WHHhUMRhWm5QPu7tbYZK6TIdYbkZkqRLqLl3bf3+/PspVmCs16+my1j5DvccJ3oRKgPa6rPVPUjb2w==</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>Ay20WE2qnSEVxpRKNOfemLoH3Z98OfWMwKoeuUvuWdrYNBREeOQQuBD6XXLjKSH+NxD22OsRGkbicplJ01pQn5FyRqQY5GOyj9SWOx0yT7CNugC1jxDDpqT99Celgphngr6Qyi6V1zOwbSMxFTnBddpLFOxOSN7ai4L4JlkT/nBpPi7T5Wnpz+TG6DAfgVYFChNThD0H8k1o+qfRDdz7NoIJPqjfZhcX7vXorqpsQZLqjiboTd83TaZcrrgZxRywffzexYCNQBO3MrJBRVxP4kymHSRnE56/WyUmoXLA/K9dmEvI1RfmvIBVAnBZm/U2Z1o5tyKjUB9jSVXLWtPXZN2yTNXk9d+8+YLY7u8wAM0qKyCYWGdaf+oxWkaU0i83byFyRWsLRSJ/LUlozbQQJetOj79x+YFXA3UkmkBtCxE=</enc>]]>
          </text>
        </finding>
      </script>
    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>gbveqZ921+F0tM5Cn1/sdDZ3cUcoUI1YCqu2PjebA2XZS085whUjfAirvdUP2OeaFmJZr65CB+a0jtVED4Mz7k9kqG7S81ztQW0bKSi4fqMwBNQDzXieHTme/rOh02zrBHrLqae/mVBAdpX2F8KkOJGbWAibU1ddAntuhzYl4B9pIImQZbawyHZD3AIBDYLO</enc>]]>
    </text>
  </js>
   <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
</dir>