<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmnvbh" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục nhân viên bán hàng" e="Saleman List"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmnvbh" fieldKey="ma_nvbh" order="ma_nvbh" allowFilter="true" allowOrder="true">
      <fields>
        <field name="ma_nvbh" fieldType="PK" width="120" >
          <text v="Mã nhân viên" e="Saleman Code"></text>
        </field>
        <field name="ten_nvbh" width="250">
          <text v="Tên nhân viên" e="Description"></text>
        </field>
        <field name="user_id" hidden="true" width="120" >
          <text v="ID" e="ID"></text>
        </field>
        <field name="username" width="120" fieldType="EX" aliasName="b">
          <text v="Tên đăng nhập" e="Username"></text>
        </field>
        <field name="ma_bp" width="120" >
          <text v="Mã bộ phận" e="Department Code"></text>
        </field>
      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>6H00ABiTnY7XOH9NhBcpNSL0SeT245lx7NMHsurFcY5bSKWZUSKNHtByvk13M5mHqbVKcJEhzblJc4kt/m31lvwZGA0/1QxbY8PfOYvhXPb/wKkbpa5LWr5ryBKVuu5v1M5WeykcQoWxHwvBFjsSGc4dKnQow0aaxW2fz39/fSDbQN1VeMJ8tYcPqTKjRGQyya79ptGFUhnQ4+asrem4CTEAoicSrMLQonTrQLlHUV6y3XeGa4U6XbJAifqEILOE</enc>]]>
          </text>
        </query>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>gbveqZ921+F0tM5Cn1/sdK7Cu4AmAR/X+dGpQmbU4TaeC6I7X56kmSDjSdTc/QRDWWx6gM9mtdXj9uKm5fdqTWb9TIgAImRtePLHwaQ5aOnzyXljIiVeYtw4IvHyXLAPtNCt7Uf+NkMcnOFKZ5rAuc5xMrduHNrwBhDzS9qb2cSzBeqvLbSxQE8SQlO7Vn5d</enc>]]>
    </text>
  </js>
   <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>

</dir>