<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmplnhvtc2" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục nhóm phân loại vật tư 2" e="Material Group Level 2"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, edit, delete..."></subtitle>
  <grids>
    <grid table="dmplnhvtc2" fieldKey="ma_nh" order="ma_nh" allowFilter="true" allowOrder="true">
      <fields >
        <field name="unit_id" hidden="true" dataType="I" width="120" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="100" fieldType="EX" >
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="ma_nh" fieldType="PK" width="120">
          <text v="Mã nhóm plvt 2" e="MGroup Code 2"></text>
        </field>
        <field name="ten_nh" width="250">
          <text v="Tên nhóm plvt 2" e="MGroup Name 2"></text>
        </field>
      </fields>

      &DefaultButton;
      <script>
        <query>
          <text>
            <![CDATA[<enc>vGhhx6UX2ukHmYI+roecmhEQJpdz1Z5W42nlTst5AkyTjiHteHRCO0E4z5WV/4VQALBhWy/yZea77n3zURqVTT1y+VINifDLDZzjvb1+0jNYrBfv1ExMDq/rAXppXm2KGxW8K4fu8YfN0kxOww0YQVxEWIuzLZXPCLDI53/JZ/HJfZLCctQ7y8W7xMr3XejhXoVGLBDb0yZOkVegtMhST6qrA4okOpxyEAgOugWT4Fg=</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>GWtRagW07ESuMHLqkFd2MzBBZhCd6K+R2qbamzt6fEVAGy/WwkwCL51cuse7gAop+AnA3qCFK9t3aMHVX70LwpGjIK3F/FjdbJlgXTEIHVYRQJaiYK4Br6VZuhgBPPiJpsJA8W4YfgnR5s5LB3JF8hJ6ixrotWONEdSQA4a43VllF6ubSVzrLrW6eKpr6YcVNIgUJdvbjzR/oElUj7Y/ve+5qnShGqvFXK1eDJxh9eM1cpyeZ+8WTXcXGeUaKzkWtRakCnXV1NKPyExhEKbo9Q==</enc>]]>
          </text>
        </finding>
      </script>
    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>SBuKA/KnkfL905iabmkqcNIiL5ZKqCY0EicWVsp4utvGgbQ1HehmAjhapcP1JKq8dODZa+TnnNmjCx6e03aVukGIYytpQ6UyZSFysX7qGfJPz48rTvp6CnD5Cg1zhzID4cD+05W/QfEmytTV6wyakMEjw3DqkSr/raz+lnELpDhZN6wclT8l6srWkStZ7egB</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
</dir>