<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmplvtc2" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục phân loại vật tư 2" e="Material Classification List 2"></title>
  <subtitle v="Thêm, sửa, xóa..." e="Add, Edit, Delete..."></subtitle>
  <grids>
    <grid table="dmplvtc2" fieldKey="ma_lo" order="ma_lo" allowFilter="true" allowOrder="true">
      <fields>
        <field name="unit_id" hidden="true" dataType="I" width="120" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="100" fieldType="EX" >
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="ma_lo" fieldType="PK" width="150">
          <text v="Mã phân loại vật tư 2" e="MClassification 2 Code"></text>
        </field>
        <field name="ten_lo" width="250">
          <text v="Tên phân loại vật tư 2" e="MClassification 2 Name"></text>
        </field>
		 <field name="ma_nh" width="0">
          <text v="Mã nhóm ploại vật tư 1" e="Material Group Code 1"></text>
        </field>
		<field name="ten_nh" width="250" fieldType="EX">
          <text v="Nhóm ploại vật tư 1" e="Material Group 1"></text>
        </field>
      </fields>

      &DefaultButton;
      <script>
        <query>
          <text>
            <![CDATA[<enc>BhXC+WeHNiX35dTJ/P/TkDSMsGXNLwaUaIaqR5eMdR2KXv4kqaypS36HZYAQT/h1k29ufvm+pcFZlDcxgosEQnMXoOkhzKw4ZC9Wt+7CG+kQTl5IwgUXG08qD+fTGa/Msj71PYxz861obKn3RbchUNiOdzj1HgEKUqzkESiUXWiwXDn9hc4Am+lh+wdiCTiwi5AkbzF3ADsZlvqQmsbXw/WlSOQr5gP1eXXAG3bWPDfGQaWcbnx2ufOgXiGgLINasyTOTq4WrktWy7nT3zc2bg==</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>KB8xqdyii61Ha3yaQfUGVT5QSf5DGG91Sbv/oY71+4fO7ukX5acU/i2ktxTVe72kPPeAMgdWD/KvkL335OJqAhZghyg3uMWkMSMra1VAT3S9lUCqv2lTzQNO/q5U2HRlkNA85ZX7u6DCupQcPvbPLJM2CwDJIQkNrrZz8lY2ydOSo1u2XS/cw0q5xJtq5gma3vSKpNagfv9e4V/vNZKZX12MhaW5Ub1yUtz9aMOeYbjUgIdSPgGLDeupKCWDq9A0W9Ow7FBQhFnGw4SUbNE3xCnJL/gv17RpKzWTRviSGyZU0sSweb2QV88zXQpHWpSI</enc>]]>
          </text>
        </finding>
      </script>
    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>SBuKA/KnkfL905iabmkqcNIiL5ZKqCY0EicWVsp4utsXyeS5FQz+ATioWKApplBaOg7cMP2yKCzTsfVEiDcEVgDIcUOqYAClr2ptdzJpTF1U8HmOBShDKyXiHfFEA6vsaTH34tNzCj9EnPnSQvHO7w1qGgM6wByoBtucPtehAFbxsH26U9FpCAc128OILfQz</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>cTMcaemK/mtRjps8m/sJOVirlLEJ+6JxiLPeJpYli4TAugeI+9xS9CIT96sX4XiNHefVQOt7fompL31ydAZJ3zbOdWMd5eIffmA/BGo5olHD9HllibL9oaJ+q8SIGGIxctuUbBiK/AoBCVom/JB6t7K63gLTkI+n1+rKmi9w1o3agX3Q3T7VA7fpVMPNyATDKCMwOuHkuP8gVjUw+qEn8lDMfSVRMnD0/FysmWigoBh/gLFLiJHLlzQDzpc5t/w9ovG2+hZPKJkxSGbquy14Z/Moy+LeKNtoKkGhDFJLvHX1Z9I5Pqnoi64lNbwHXFIxbOALp0KsYLr56b26De9xBtmOeTdLi0YparLh4bTcD2fca+XxZyDGiDNFsNbEQ0ln</enc>]]>
    </text>
  </css>
</dir>