<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmplvtc1" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục phân loại vật tư 1" e="Material Classification List 1"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, edit, delete..."></subtitle>
  <grids>
    <grid table="dmplvtc1" fieldKey="ma_kho" order="ma_kho" allowFilter="true" allowOrder="true">
      <fields >
        <field name="unit_id" hidden="true" dataType="I" width="120" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="100" fieldType="EX" >
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="ma_kho" fieldType="PK" width="120">
          <text v="Mã p/l vật tư 1" e="MClassification 1 Code"></text>
        </field>
        <field name="ten_kho" width="250">
          <text v="Tên p/l vật tư 1" e="MClassification 1 Name"></text>
        </field>
      </fields>

      &DefaultButton;
      <script>
        <query>
          <text>
            <![CDATA[<enc>vGhhx6UX2ukHmYI+roecmhEQJpdz1Z5W42nlTst5AkyTjiHteHRCO0E4z5WV/4VQALBhWy/yZea77n3zURqVTT1y+VINifDLDZzjvb1+0jNYrBfv1ExMDq/rAXppXm2KGxW8K4fu8YfN0kxOww0YQVxEWIuzLZXPCLDI53/JZ/HJfZLCctQ7y8W7xMr3XejhXoVGLBDb0yZOkVegtMhST6qrA4okOpxyEAgOugWT4Fg=</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>GWtRagW07ESuMHLqkFd2MzBBZhCd6K+R2qbamzt6fEVAGy/WwkwCL51cuse7gAop+AnA3qCFK9t3aMHVX70LwpGjIK3F/FjdbJlgXTEIHVYRQJaiYK4Br6VZuhgBPPiJpsJA8W4YfgnR5s5LB3JF8hJ6ixrotWONEdSQA4a43VllF6ubSVzrLrW6eKpr6YcVNIgUJdvbjzR/oElUj7Y/ve+5qnShGqvFXK1eDJxh9eM1cpyeZ+8WTXcXGeUaKzkWtRakCnXV1NKPyExhEKbo9Q==</enc>]]>
          </text>
        </finding>
      </script>
    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>SBuKA/KnkfL905iabmkqcGjHlZ8Q69Lj9xALoWsXAJWm+BzVUT4+NK7GSV+O4T55nxlCZBS7OdWoS4zJl2V9rK7kSkzXtXV2kydMEBZO+oRt84IlxWzBZnsv8R58U8+TM37uS2SlKyxDh2J7x/BvwaD1i5MXRVqtj/BQXlZLZMxV28rVozf6g1fRbMA2rbag</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>cTMcaemK/mtRjps8m/sJOVirlLEJ+6JxiLPeJpYli4TAugeI+9xS9CIT96sX4XiNHefVQOt7fompL31ydAZJ3zbOdWMd5eIffmA/BGo5olHD9HllibL9oaJ+q8SIGGIxctuUbBiK/AoBCVom/JB6t7K63gLTkI+n1+rKmi9w1o3agX3Q3T7VA7fpVMPNyATDKCMwOuHkuP8gVjUw+qEn8lDMfSVRMnD0/FysmWigoBh/gLFLiJHLlzQDzpc5t/w9ovG2+hZPKJkxSGbquy14Z/Moy+LeKNtoKkGhDFJLvHX1Z9I5Pqnoi64lNbwHXFIxbOALp0KsYLr56b26De9xBtmOeTdLi0YparLh4bTcD2fca+XxZyDGiDNFsNbEQ0ln</enc>]]>
    </text>
  </css>
</dir>