<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmploaikh" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục phân loại khách hàng" e="List of Customer Types"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmploaikh" fieldKey="ma_plkh" order="ma_plkh" allowFilter="true" allowOrder="true">
      <fields >
        <field name="ma_plkh" fieldType="PK" width="120">
          <text v="Mã phân loại" e="Type Code"></text>
        </field>
        <field name="ten_plkh" width="250">
          <text v="Tên phân loại" e="Type Name"></text>
        </field>        
		<field name="ten_plkh2" width="250">
          <text v="Tên khác" e="Other Name"></text>
        </field>
	    <field name="status" width="120" align="center">
          <text v="Trạng thái" e="Status"></text>
        </field>
      </fields>

      &DefaultButton;
	  <script>
        <query>
          <text>
            <![CDATA[<enc>IOf6W0OG0hmrKrA1Kd5fWZf9NN5ahTXa9vBbpRYCZVaKIks/FBC2hg7GQT3iYdqoIB+nDl4xFtUVUAatbE2fWEGwxZMmZNfT9aX8EGb8shqgLWNfjRgPJmWY63OylJQ80a6ktmt1CfKhIhLdxiEdNLYxTCNuqt9bN+9QRtUYuakqEgB36bayeH6u4FiApvRHhzU8q7fG8nt6iHVTACk5D3fdJXmWveXJFA+ydmkOxUI=</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>c/dVjmW26UUhp2rOzcxEdQaQXFyD1xuEl2qwxi1T+iEvfj/9/30Mjj9F9wrcY98SMVkNOfqjZx4LXN+rXoyPCGjWq0mvPdO1f/9uvP4V4VaTjZ7TBgmn6qNrzYxPOTwt06FaubXId0H2pHgJvCx5nFtiepkzQ3pRFT5+k3c8HoPuv1PkLYDAFZeX+5p+c7HVK1sxN6NpV5YAILPtUzCWj/8qK6qn/5E8G17UNk5MjAo=</enc>]]>
          </text>
        </finding>
      </script>
    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>Xm0SQO244yhm4oovG3IvuLeLIyJNX4Y9n7qfFwoZpqyb+kgo9IETkFkCgD9DIdqqpYlNhQLZdkz+d6aSX4RDnAHmpC1Y5d6TOP3XWrZBuRK8ka63L3wzI1ZEd2DUJW1YsVHjKaW10eEJEBCz53AVBhvw1PnhJFnsXhDCk1GEfEk5Ogh3lWiedWs+3ZImAHX9</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
</dir>