<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmpostvt" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Quản lý sản phẩm" e="Product Manager"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmpostvt" fieldKey="ma_vt" order="ma_vt" allowFilter="true" allowOrder="true" >
      <fields>
        <field name="ma_vt" fieldType="PK" width="120" link="1">
          <text v="Mã hàng hóa" e="Product Code"></text>
        </field>
        <field name="ten_vt" width="300">
          <text v="Tên hàng hóa" e="Description"></text>
        </field>
        <field name="dvt" width="80">
          <text v="Đvt" e="UOM"></text>
        </field>
        <field name="ma_lvt" width="80" >
          <text v="Loại hàng hóa" e="Goods Type"></text>
        </field>
		<field name="ten_lvt" width="200" fieldType="EX" >
          <text v="Tên loại hàng hóa" e="Goods Type"></text>
        </field>
		   <field name="ximage1" width="80" hidden="true">
          <text v="Ảnh" e="Goods Type"></text>
        </field>
        <field name="nh_vt1"  width="80" hidden="true">
          <text v="Nhóm 1" e="Group 1"></text>
        </field>
        <field name="nh_vt2"  width="150" hidden="true">
          <text v="Nhóm 2" e="Group 2"></text>
        </field>
		<field name="nh_vt3"  width="150" hidden="true">
          <text v="Nhóm 3" e="Group 3"></text>
        </field>
		<field name="thu_tu" width="250">
          <text v="Thứ tự" e="Position"></text>
        </field>
      </fields>

      <buttons>
        <button id="add">
          <text v="$AddToolbar" e="$AddToobar"></text>
        </button>
        <button id="edit">
          <text v="$EditToolbar" e="$EditToolbar"></text>
        </button>
        <button id="delete">
          <text v="$DeleteToolbar" e="$DeleteToolbar"></text>
        </button>
        <button id="copy">
          <text v="$CopyToolbar" e="$CopyToolbar"></text>
        </button>
        <button id="view">
          <text v="$ViewToolbar" e="$ViewToolbar"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
       
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="refresh">
          <text v="$RefreshToolbar" e="$RefreshToolbar"></text>
        </button>
        <button id="freeze">
          <text v="$FreezeToolbar" e="$FreezeToolbar"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="export">
          <text v="$ExportToolbar" e="$ExportToolbar"></text>
        </button>
        <button id="downtemplate">
          <text v="Tải mẫu Excel" e="Down import template"></text>
        </button>
        <button id="import">
          <text v="Lấy dữ liệu từ tập tin" e="Import data"></text>
        </button>
      </buttons>
      <script>
        <query>
          <text>
            <![CDATA[<enc>M38DzFGcb9HJxdKgJBtZ/shc7DeGiV9WI5JYWoCXMDTcROwkTpSA0MsE9nxkaSZsR4PyvRoOrOxZtGeLQIrQDrvrs496big4ABxhN1PH1KmljsUv9I2sTvCzYw96lZc4RQ8anKn0bj1W98l70tGtUX9w/W1ze7i/TumQnXY0fgiWjMsJZbJSi08fJ5i9AXsxhCBsSQkwmzi8kzUVRwl/WIulzuDFbrQQwx9rUo5clE0=</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>WLCl3Fa4L+k8TTPU46BJ3fFoUgg5NxBi4AB+xY2wyFDy4peQk355l70Aoa5OnfPVAxwBEY+4vQsTwNdYpzLaLLROGGqNhpXiJ+++iOjgUBH2VV610glVlyuxzBPcvayn7bn5fc9DBfyiFx4cUnyePsECkNEf5EloRa5TIOlxvVGJhZaOJ8oNIuKsVcR8b4IDZ0c+KOvC2SE1YiXTZN1ZdcWWOznrW1Xsyd4G3tjyYdrq3WJzp6VBFskGVkaXZQyvMi097kg191t+H1Ox3x8W+Q==</enc>]]>
          </text>
        </finding>
      </script>
    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>gcLH81yZz1iu0ZB/Vcs6WNxK0cg1CpnbgT2t8gfVp2/u+Kgr5cLsGqRTSYX7nlfdmI6mYVgcwIQG9kCBnl12fTfkIPKFT0My8b5/2MmS2fdKlwoaty6zxjPvYf9lObNxfvey/zmvA2X/E1Rho4sUqnBb8f/5IJOj5gjHsXn5p4yB95MUgR4KNyZ6PHRGyHyG</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
</dir>