<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmpttt" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục phương thức thanh toán" e="Payment Methods List"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid id="0" table="dmpttt" fieldKey="ma_pttt" order="ma_pttt" allowFilter="true" allowOrder="true" >
      <fields>
        <field name="ma_pttt" fieldType="PK" width="120">
          <text v="Phương thức" e="Payment Methods Code"></text>
        </field>
        <field name="ten_pttt" width="250">
          <text v="Diễn giải" e="Description"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>Sr5eFaoKvc2Oa84teY6A6GOFPZEkAvOH5s0/Pvn6JeibMiZTAZ/J8dyeqIdUVfWFcBJERP+VTCcR1zhPBlIbIfN6YBSUllfqUcKEHuiriiSk3hnDERbOfEcnHsyLZNJ7bX1yuq0orYAtds8YRK0SN8ZrW4+JGvDfxw0t9PpWfv9Bjz4uUjlAvRNffwOc4CIk</enc>]]>
    </text>
  </js>
   <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
</dir>