<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmptvc" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục phương thức vận chuyển" e="Tranpost List"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmptvc" fieldKey="ma_ptvc" order="ma_ptvc" allowFilter="true" allowOrder="true" key="" >
      <fields>
        <field name="ma_ptvc" fieldType="PK" width="120">
          <text v="Phương thức" e="Tranpost Code"></text>
        </field>
        <field name="ten_ptvc" width="250">
          <text v="Diễn giải" e="Description"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>gbveqZ921+F0tM5Cn1/sdH/qPjV+tq6XUIE6sG7TV5/JfzTq9lChAJSaFC3se5EDFbLlfoAB3+fE3hHIVTkUKcj3EDxdSwpHJ3lJ/Zovy6WVvCJ4HfeHs4akAcYIoQw8HzBn9vytorulmfkBLN12MX6q3MlszLeU6VeM1uYP+qZmCX7zOnAVgK8NmhHY148V</enc>]]>
    </text>
  </js>
   <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
</dir>