<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmqddvt" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục quy đổi đơn vị tính" e="Unit Conversion"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmqddvt" fieldKey="ma_vt" order="ma_vt" allowFilter="true" allowOrder="true">
      <fields>
        <field name="ma_vt" fieldType="PK" width="120">
          <text v="Mã hàng hóa" e="Goods Code"></text>
        </field>
        <field name="ten_vt" width="250" fieldType="EX" aliasName="b">
          <text v="Tên hàng hóa" e="Goods Name"></text>
        </field>
        <field name="dvt" fieldType="PK" width="80">
          <text v="Đvt" e="UOM"></text>
        </field>
        <field name="he_so" width="80" dataType="N">
          <text v="Hệ số" e="Coefficient"></text>
        </field>
      </fields>


      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>1pYA30de34aQ63VH1qr3EUjYzt8PbugxOoGqgaN1TzIgHzQsadE8Ul4n96nuTajJ8vlLsXJTtFaPVt+DNuw7uy7lv81h/GbaLii4sPx1YN8PW9wd0D17h5STLGpDXfCUOgXnjMGNo6ZMBavA7wF8BN978zeGM+1bxSHyfalI9YF9djgrJ+rUk1avCQI7jGVKNkir1a+ykGtuJa0cGyGx6DxHqOEuRDV9q9HKnambDmEWhqE8atS6V7fitb8lKzN1</enc>]]>
          </text>
        </query>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>cUngm+7djzHSR+Bpe5bUQ5h4hWFM7mxIGROeV2c01OugeTuL/HxWX8tFr8fLe4rifsXZiaR133nPIp562GoBTslQVwkfuKLtzHIxqMiruXPJLKtAZDdxyT880+4caMXehfye9CT4ueF9v/n2NQAn3lKR7Q5NB7QveaomyCZlnHKKg8bYg9sLr+EJ7i0b7WCM</enc>]]>
    </text>
  </js>
    <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
</dir>