<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmqhgd" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục quan hệ gia đình" e="List of Family Relationships"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmqhgd" fieldKey="ma_qh" order="ma_qh" allowFilter="true" allowOrder="true">
      <fields >
        <field name="ma_qh" fieldType="PK" width="120">
          <text v="Mã quan hệ" e="Relationship Code"></text>
        </field>
        <field name="ten_qh" width="250">
          <text v="Tên quan hệ" e="Relationship Name"></text>
        </field>
		<field name="ten_qh2" width="250">
          <text v="Tên khác" e="Other Name"></text>
        </field>
		<field name="status" width="120" align="center">
          <text v="Trạng thái" e="Status"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>gbveqZ921+F0tM5Cn1/sdK7Cu4AmAR/X+dGpQmbU4Ta9HvYelEd/tEZUgs62rBWXdDtg9qXzXswtbxstj4nvhdSwmp0gYG9XJbfPhy07XKL+Bm7jkfxnw6FHrSISFErw+QMJHtalHDT8uBsttkYdGGHd84Pfh7jXSsVjW0ZEoRQZO3zdaxb3ZvK/lV18e+ch</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
</dir>