<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmsp" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục sản phẩm" e="Product List"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmsp" fieldKey="ma_sp" order="ma_sp" allowFilter="true" allowOrder="true" >
      <fields>
        <field name="ma_sp" fieldType="PK" width="120" link="1">
          <text v="Mã sản phẩm" e="Product Code"></text>
        </field>
        <field name="ten_sp" width="300">
          <text v="Tên sản phẩm" e="Description"></text>
        </field>
        <field name="dvt" width="80">
          <text v="Đvt" e="UOM"></text>
        </field>
        <field name="ma_lvt" width="80" >
          <text v="Loại sản phẩm" e="Item Type"></text>
        </field>
        <field name="nh_vt1"  width="80">
          <text v="Nhóm 1" e="Group 1"></text>
        </field>
        <field name="nh_vt2"  width="150">
          <text v="Nhóm 2" e="Group 2"></text>
        </field>
      </fields>

      <buttons>
        <button id="add">
          <text v="$AddToolbar" e="$AddToobar"></text>
        </button>
        <button id="edit">
          <text v="$EditToolbar" e="$EditToolbar"></text>
        </button>
        <button id="delete">
          <text v="$DeleteToolbar" e="$DeleteToolbar"></text>
        </button>
        <button id="copy">
          <text v="$CopyToolbar" e="$CopyToolbar"></text>
        </button>
        <button id="view">
          <text v="$ViewToolbar" e="$ViewToolbar"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
       
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="refresh">
          <text v="$RefreshToolbar" e="$RefreshToolbar"></text>
        </button>
        <button id="freeze">
          <text v="$FreezeToolbar" e="$FreezeToolbar"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="export">
          <text v="$ExportToolbar" e="$ExportToolbar"></text>
        </button>
        <button id="downtemplate">
          <text v="Tải mẫu Excel" e="Down import template"></text>
        </button>
        <button id="import">
          <text v="Lấy dữ liệu từ tập tin" e="Import data"></text>
        </button>
      </buttons>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>gbveqZ921+F0tM5Cn1/sdH/qPjV+tq6XUIE6sG7TV5+5m35O0IDaxkRn/WUQJ47gwuMbZtNoxyqqK5JC2hhW8SSECS5IKTJ1exr8AQ/S9WToP8p5WxcnFy9WG7qLGqERgX2lWK0fNy7D7OC3cxRE2qM45PdWL4LfsnNtXsnpeRYWOCI2uAUgCn4DRLUKejzG</enc>]]>
    </text>
  </js>
</dir>