<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmth" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Thương hiệu/ Nhãn hàng" e="Vehicle List"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmth" fieldKey="ma_th" order="ma_th" allowFilter="true" allowOrder="true" >
      <fields>
        <field name="ma_th" fieldType="PK" width="240">
          <text v="Mã Thương hiệu/ Nhãn hàng" e="Product type code"></text>
        </field>
		<field name="ten_th" width="220">
          <text v="Tên Thương hiệu/ Nhãn hàng" e="Product type name"></text>
        </field>
		<field name="ten_th2"  width="120">
          <text v="Tên khác" e="Alias"></text>
        </field>
		<field name="mo_ta" width="120">
          <text v="Mô tả" e="Description"></text>
        </field>
		<field name="status" width="120">
          <text v="Trạng thái" e="Status"></text>
        </field>
		<field name="thu_tu" width="120">
          <text v="Thứ tự" e="Position"></text>
        </field>
		 
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <!-- <![CDATA[<enc>Ccvx56Nydky3Uh55/RW4nfJzX0/RIED68cDgG8uloLeV3z92U8ULypc598rn/aaFEBT2oXNbQBrZs5DMw5Ay4sqIuy3halU2e7yINNrCOsOqP3wvxZZL1e6YcS1bKBIgvyot8ifqcUd752UsTfm1fAjTqZoYq/Z+z8EZNEBWU9xlwkuLDraNLGHWa38cPYRn3fIbj6eCTfSXn77n8xkKVQ==</enc>]]> -->
		 
    </text>
	<text>
      <![CDATA[<enc>dWARx5oyNggjYSWXeJWjdkhbeL9JIs2Wy85/hMIvFC1jw2Sh9hUyDoX4nVzjaVDEYCUL91lMN1ji07GdWPxkeNRKnkbcvUtnuQbdYeJrXcmJ8shR8u1wfxYYQ3Wt2TS1SrjF+TC7fyEXkuXbZwYUjLTBBXpv0s0EXZsK4HvNBqXY/ltR9c2d2M4ZAEgIPvxU3I6kF6Iwkx6ULYu7sy4bsg==</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>cTMcaemK/mtRjps8m/sJOVirlLEJ+6JxiLPeJpYli4TAugeI+9xS9CIT96sX4XiNHefVQOt7fompL31ydAZJ3zbOdWMd5eIffmA/BGo5olHD9HllibL9oaJ+q8SIGGIxctuUbBiK/AoBCVom/JB6t7K63gLTkI+n1+rKmi9w1o3agX3Q3T7VA7fpVMPNyATDKCMwOuHkuP8gVjUw+qEn8lDMfSVRMnD0/FysmWigoBh/gLFLiJHLlzQDzpc5t/w9ovG2+hZPKJkxSGbquy14Z/Moy+LeKNtoKkGhDFJLvHX1Z9I5Pqnoi64lNbwHXFIxbOALp0KsYLr56b26De9xBtmOeTdLi0YparLh4bTcD2fca+XxZyDGiDNFsNbEQ0ln</enc>]]>
    </text>
  </css>
</dir>