<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmttbm" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục trạng thái nhấc máy" e="Pick-up state List"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmttbm" fieldKey="ma_ttbm" order="ma_ttbm" allowFilter="true" allowOrder="true">
      <fields >
        <field name="ma_ttbm" fieldType="PK" width="120">
          <text v="Mã trạng thái nhấc máy" e="Pick-up state code"></text>
        </field>
        <field name="ten_ttbm" width="250">
          <text v="Tên trạng thái nhấc máy" e="Pick-up state name"></text>
        </field>
		<field name="status" width="120">
          <text v="Trạng thái" e="Status"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>gbveqZ921+F0tM5Cn1/sdH/qPjV+tq6XUIE6sG7TV59x1hQ7zhhCMZj9jocAASLjXDm7mF/5eVK7Hjk4aMvCDxrUypKFa+P/Vd/WMTQl7kApEG+ageipEzXJnF0pCMfLo2Lxb6cD+t/+zSq7rd/XP0JSngU7FIaZWUf+gC2d2BITkigQ9v6mFA6+fyBsT9Xl</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
</dir>