<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridNotPrint.xml">
]>

<dir id="dmttxe" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục trạng thái xe" e="List of Vehicle Status"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmttxe" fieldKey="ma_xe" order="ma_xe" allowFilter="true" allowOrder="true">
      <fields >
        <field name="ma_xe" fieldType="PK" width="120">
          <text v="Mã xe" e="Vehicle Code"></text>
        </field>
        <field name="tt_xe" width="120" fieldType="EX" aliasName="b" align="center">
          <text v="Trạng thái xe" e="Vehicle Status"></text>
        </field>
		<field name="ten_bgn" width="120" fieldType="EX" aliasName="c">
          <text v="Trạng thái xe" e="Vehicle Status"></text>
        </field>
		<field name="status" width="120" align="center">
          <text v="Trạng thái" e="Status"></text>
        </field>
      </fields>

      &DefaultButton;
	  <script>
		<query>
			<text>
				<![CDATA[<enc>jmM3mdbacJpAMQkZWs/QBk0T5TKXI8G9pJx6/g1luuyHvUyuWY803fZiBb4qZ4E37pGH1k0iMrpa3kMnzUnVPtzYF5HhcMqZcX+6087MxjnFk65jmjT15rQce1NRTbQ86UenP4tr8HxSmFr3H+4TliWZlfi86wJlgqfSYXNS8bcArPuSzlJjz88vwKCkRgwMYMUB5OagntOD4apt1cIjN4T++dEz2la7Sm+w21g8IcRszEZu5ViNlaFOjrNTO7HJiPztbZIs0gHg1RmEOKfM6A==</enc>]]>
			</text>
		</query>

		<finding>
			<text>
			<![CDATA[<enc>bs7GFtYpf7EzeOAnbMWsPk6tZVJ6NnCVUbOE5FjonMD6M0O+I47ud4DqRm1LvC06YQrs8lS78tMKyXMdwXaGwK93RNHFFZ+X6AHehFgQUOzdsoAJZka5k2ld/MYuDXe+eRmPF7y+nFkCZsJrmuv39QBR9QAWc2fN1GYsoF0DAIdEGhk8LZdX4T7/aBhKbLDQwphZcvsGuvRjP0eKDzPcLGjMv9OV+F+buDOr2pKPo6x/7hYtcVqT5g90CSkd59bzY3Fdpn5RLAz8HvmQ4OwK1w==</enc>]]>	
			</text>
		</finding>
	   </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>gbveqZ921+F0tM5Cn1/sdMZj4VANOEudqg6VsHk5bGAnuQeAkk0sBni0qsxMZDU+UKsevzf5QJiklQ0dV4oEWgMzU0sHTB9RMcfl6qo9hGJmnhYh55N2u3HC4SRuUfg4jsClKNIBqJwVRk05/Ao1pwK1aiyIzbqvP3B6PNzVA0WT9kl0NjVjBw57cQlL6013</enc>]]>
    </text>
  </js>
  
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
  
</dir>