<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmttp" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục quê quán" e="List of Hometown"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmttp" fieldKey="ma_ttp" order="ma_ttp" allowFilter="true" allowOrder="true">
      <fields >
        <field name="ma_ttp" fieldType="PK" width="120">
          <text v="Mã Quê quán" e="Hometown Code"></text>
        </field>
        <field name="ten_ttp" width="250">
          <text v="Tên Quê quán" e="Hometown name "></text>
        </field>
		<field name="ten_ttp2" width="250">
          <text v="Tên Quê quán (en)" e="Hometown name "></text>
        </field>
		<field name="full_name" width="250">
          <text v="Tên đẩy đủ" e="Full name "></text>
        </field>
		<field name="ma_qg" width="120" >
          <text v="Quốc gia" e="Full name "></text>
        </field>
		<field name="ten_qg" width="250"  hidden="true" fieldType="EX" >
          <text v="Quốc gia" e="Full name "></text>
        </field>
      </fields>

      &DefaultButton;
	<script>
		<query>
		  <text>
		  <![CDATA[<enc>FE0VhL2cVDLn7WbhQBHWIWrt905BwDZTTwkcB9k3TgJZNSx/tcMKhLbW2+0gZgQxK9tPTsY4jY4ROnb7sT1aebMhwTO4YYFGZjFFLuK4RlWonkSRGT1RCY01UKSO25X++aGhniPCSsYLUcXNtcX/o7pzmYwKDV7rxyVdHZnB6keggVg9B2bfxgw6IRaG78qwsCJknQTQeysxyi9GAh2InO/OoGKXyMcdy/0EANqngjs=</enc>]]>
		  </text>
		</query>
		<finding>	
			  <text>	
				<![CDATA[<enc>RwhWe0B3M4HKZOg1HAE431HDfY7b80MvoLXGoNnOYvet7yjnT9tL2In6vQcxaHnJVdZo6IpJ9iVOG+ovzX8Bp1AHrK2Onkn2HBlTH9jXAnX7DheqKRBWjXyGakhb4vOuqJCAqezoYP2JpY1x/GQGbc2+zqIIFbcdiLQzMmWHU8hFrgzlP6GAjL0fXvi4kUATX8/V3eggYlUZPJTShxOWSh/VB4b/6ov2NMDBGy4jY0CXXlSRUP2XFbLJmzcsRkhEMslYh0sRHeLJDJLuQwePoXWx7jmqdHISKkKW39rKtoelahC+O5ZUgPA5u8XBDAWx8BSkHdHgsSRCSokW+tjegIx/w6zY1StJy0u/nJM7JZQ=</enc>]]>	
			  </text>	
			</finding>	
	  </script>
    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>gbveqZ921+F0tM5Cn1/sdPg7Kd+fdJt8bs2077Li/6QGvk2ubvHyazakQjIZizDWbO9mr/8RhgW3dNzHgBDq58BVjfp/uIW6BScsQFxrUegbTTTlsc6ywXUCLVi7uq9xJxeqnyg+3pVqpwLqehM/ToSi+N5FQwwbVEu8gBBgrdGds9CTulgqmY0vJmVefqZ4</enc>]]>
    </text>
  </js>
<css>
    <text>
      <![CDATA[<enc>2FI/rX3TUEulxi9LoMIkcrNxfLRl3EeU+vXNpxQMgjAUY+e+fGyRzUkW+9nk3DQhRGDcCci+9yN9eNtbKmU791f+T6ieUFfgOjsuRVms+RLXNXkR+TQtRCS4FV0pRfP1fcwNG+tYLjCPjgr/WKew/MUhXhi4bKC7rHkp5oZhUfiM7jrj07++4J47zqqm135YfI/4/B4osMfc4JwZvc4UdOOdVeGAUSTZf5EB2pZOESRmXLeEFulW+eR/+o1UWB+1/UKKBLZIthNkBHUSRWibuDm3AC2cEyXPFjWJchNUAhngrHccQ3Oat8UBetW1Q1NE</enc>]]>
    </text>
</css>
</dir>