<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmttcall" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục trạng thái cuộc gọi" e="Call Status List"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmttcall" fieldKey="ma_ttcall" order="ma_ttcall" allowFilter="true" allowOrder="true">
      <fields >
        <field name="ma_ttcall" fieldType="PK" width="120">
          <text v="Mã trạng thái cuộc gọi" e="Call Status code"></text>
        </field>
        <field name="ten_ttcall" width="250">
          <text v="Tên trạng thái cuộc gọi" e="Call Status name"></text>
        </field>
		<field name="ma_td" width="120">
			<text v="Mã tác động" e="Impact code"></text>
        </field>
		<field name="ma_qh" width="120">
         	<text v="Quan hệ gia đình" e="Family relationship"></text>
        </field>
		<field name="is_close" width="120">
         	<text v="Is close" e="Is close"></text>
        </field>
		<field name="status" width="120">
          <text v="Trạng thái" e="Status"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>t5ThNOWSpgjuBz9ULt8tJcVY6rmjsvFUPjLMiKvDEWm4ophn83rS8M6rAt5uyC1V7Hi10SPUrnjjxG2NVy+wkJv5W+/6ZJ5bnNh7rEUI6KoHfWTz45Ht8gWwHuzlpZ5URw0/SzVFGFMopq7uLw2tbdLCby9UjGa/g9XxesMZfYU8uivp/JVVUh3V1l2SDEBx</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
</dir>