<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmtygiaxd" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Khai báo tỷ giá xăng dầu" e="Declare petrol rates"></title>
  <subtitle v="Cập nhật tỷ giá..." e="Add, Edit, Delete Exchange Rate..."></subtitle>
  <grids>
    <grid table="dmtygiaxd" fieldKey="ma_xd,ngay_hl" order="ma_xd" allowFilter="true" allowOrder="true" >
      <fields >
        <field name="ma_xd" fieldType="PK" width="120" >
          <text v="Mã xăng dầu" e="Petroleum Code"></text>
        </field>
        <field name="ten_xd" width="250" fieldType="EX"  aliasName="b">
          <text v="Tên xăng dầu" e="Petroleum Name"></text>
        </field>
        <field name="ngay_hl" fieldType="PK" width="120" dataType="D">
          <text v="Ngày" e="Date"></text>
        </field>
        <field name="ty_gia" dataType="N" format="ExRate" width="120">
          <text v="Tỷ giá" e="Exchange Rate"></text>
        </field>
      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>flgZdO9vnN1NknVapdBcs5aEr+gd82D7z/nYfWrktDQYDkCvFouyGx2SHY6rbvQUew4Cts5yNORK/Mx8wVKgX9zgSjK9GhEloXtmad5KBEKLD+NXyqZgZXGAfVyCdLKC7lp5kiYvTWmyQehCPQSF3vVB2AvfOVNiby/Ta8ye5X2uFVPS6YMFsq+UWamogtGN1VLmPvPlBqyVaNN+aWwSyQCjzZL2jaP4+KULeadYauADjP+aunb+QZ7yZs4i0HF4</enc>]]>
          </text>
        </query>
      </script>
    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>Xm0SQO244yhm4oovG3IvuLeLIyJNX4Y9n7qfFwoZpqxfL/qFn7D1g1rCOosd9pR+MKo5nKIo0LHRdOYuAhGH0nVmCB3XZumhP3p666keDcDtveiS4ozEe6foUdEUYeWZojPKuPNIRkskyp1chsfXMRJ8McaNKax1epjm8xIvoAJuKEiJ4Vf0mHSXyO8iJoJ7</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
</dir>