<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="vdmvitri" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục vị trí kho hàng" e="Location List"></title>
  <subtitle v="Cập nhật vị trí: thêm, sửa, xóa..." e="Add, Edit, Delete Location..."></subtitle>
  <grids>
    <grid table="vdmvitri" fieldKey="ma_kho, ma_vi_tri" order="ma_kho, ma_vi_tri" allowFilter="true" allowOrder="true">
      <fields>
        <field name="ma_kho" fieldType="PK" width="100">
          <text v="Mã kho" e="Site"></text>
        </field>
        <field name="ten_kho" width="300">
          <text v="Tên kho" e="Site Name"></text>
        </field>
        <field name="ma_vi_tri" fieldType="PK" width="100">
          <text v="Mã vị trí" e="Location"></text>
        </field>
        <field name="ten_vi_tri" width="300">
          <text v="Tên vị trí" e="Description"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>Xm0SQO244yhm4oovG3IvuNgcQY/8TaQwrefZaHkTKXF9pAXQ1VZp2HHilfqYpCVDehSDIQ5pnLa+BqtiLB24RSiydX40ZIZs7omii+0iukE1wNoff+X4kKGjGyncAc7Mvj5ayYULZEk4ktTQ5cnqiTrLKaXDb3eJW37Vp+a0M/G9Cdy6r7PyaA4vCMjKc6ep</enc>]]>
    </text>
  </js>
   <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
</dir>