<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmvtcv" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục vị trí công việc" e="List of Job Positions"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmvtcv" fieldKey="ma_vtcv" order="ma_vtcv" allowFilter="true" allowOrder="true">
      <fields >
        <field name="ma_vtcv" fieldType="PK" width="120">
          <text v="Mã vị trí công việc" e="Job Position Code"></text>
        </field>
        <field name="ten_vtcv" width="250">
          <text v="Tên vị trí công việc" e="Job Position Name"></text>
        </field>         
		<field name="ten_vtcv2" width="250">
          <text v="Tên khác" e="Other Name"></text>
        </field> 
		<field name="status" width="120" align="center">
          <text v="Trạng thái" e="Status"></text>
        </field>
      </fields>

      &DefaultButton;
	  <script>
		<query>
			<text>
				<![CDATA[<enc>cxblwlTjuf0RelEES+YgsZ31Dd1HelEUEdWl19BiKE0g8odsPtP2TqIBmDaT++NPKQ8aViJFi/5XhaU0OQ6A9xGOXC7pOJxOVJqtxNLJlZbVDumLHAHoNXG1DUGnpNWraE0Pd94leACG/DY8jPkmWr7wXP2hgBmBxnsqV+puSIewV/Pem69tfKwAPPCrbVMc/gjM0O7wQPHxNkm/6jqoDGssblvFO0HVOzln8drEZ/Y=</enc>]]>
			</text>
		</query>

		<finding>
			<text>
			<![CDATA[<enc>cxblwlTjuf0RelEES+YgsZsN721hLwjL3o8GIY4rMLmKLg602GmAllF988UH5sD8ZBq8nW5oaRzxVqXFeQujT3t8ntuLn+EEgxou/XEFyP4UlSVyHKWlPowBWCEegs2a3g8N1bp5FGuRw5ryBBInSyBZPEufRUeXZZhtNNe6roAR+rWx+xMKvWbMCinttBL9VmDbNgvIjDQVPBaIKALRZtG/FQUng3oxkszZkcoH4ek=</enc>]]>	
			</text>
		</finding>
	   </script>
    </grid>
  </grids>


  <js>
    <text>
      <![CDATA[<enc>gbveqZ921+F0tM5Cn1/sdH/qPjV+tq6XUIE6sG7TV5/JfzTq9lChAJSaFC3se5EDohqMvhfSgpCxE+wl3JtwvNMJoQLCcnOqbgsHVxSk5oOWfVGq4ki3BQr79eukdjJHsbCjXgdmK0HhiwCYs+WXGnEswZA20ywm5928iKo97JBB3YBaeBwtg3B/PlRTMnP4</enc>]]>
    </text>
  </js>
   <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
</dir>