<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="dmxe" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục Xe" e="Vehicle List"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="dmxe" fieldKey="ma_xe" order="ma_xe" allowFilter="true" allowOrder="true" >
      <fields>
        <field name="ma_xe" fieldType="PK" width="120">
          <text v="Mã Xe" e="Vehicle Code"></text>
        </field>
		 <field name="ten_xe" fieldType="PK" width="120">
          <text v="Tên Xe" e="Vehicle name"></text>
        </field>
		<field name="dia_chi"  width="120">
          <text v="Địa chỉ" e="Address"></text>
        </field>
		<field name="mau_son" width="120">
          <text v="Màu sơn" e="Color"></text>
        </field>
		 <field name="ma_loai"  width="120">
          <text v="Mã loại" e="Type code"></text>
        </field>
		<field name="tai_trong"  width="120">
          <text v="Tải trọng" e="Weight"></text>
        </field>
		<field name="dung_tich"  width="120">
          <text v="Dung tích" e="Capacity"></text>
        </field>
        <field name="status" width="250">
          <text v="Trạng thái" e="Status"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>T5Nuk0XwnW0VlRYHOIM5VYnHDnH7tu2xtEYSmkPfNZBJUl7r33sT+icriHahD1UD3+3dGBsz0uHGxvB6mj5gmPMYQazTaLZgbXVKdWxafU3XtSBtFJVaSYQsllHmwz1zX7MoFfu6hqdl+P8/KbiggoSfnQ4ved6vM9q9QIvS52u3SCxndIZLU7A6rgPZmKPv</enc>]]>
    </text>
  </js>
</dir>