<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridFinding.xml">
]>

<dir id="hrdmkcb" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục nơi đăng ký KCB" e="Medical Care Center List"></title>
  <subtitle v="Cập nhật nơi đăng ký KCB: thêm, sửa, xóa..." e="Add, Edit, Delete Medical Care Center..."></subtitle>
  <grids>
    <grid table="hrdmkcb" fieldKey="ma_kcb" order="ma_kcb" allowFilter="true" allowOrder="true" key="" >
      <fields>
        <field name="ma_kcb" fieldType="PK" width="80">
          <text v="Mã đăng ký" e="Code"></text>
        </field>
        <field name="ten_kcb" width="250">
          <text v="Tên đăng ký" e="Description"></text>
        </field>
        <field name="ma_tinh" width="100">
          <text v="Tỉnh thành" e="Province/City"></text>
        </field>
        <field name="benh_vien" width="100">
          <text v="Bệnh viện" e="Hospital"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>uw3iZoR/y/5o6FF1x5y/2WEhXacibHZmVTq0dnI8CfI0ovJcsZ+9nCvIqTk3iQ9yR+X1OfPFOBjwcy7ZF/jOSyn1gX/LuDjNt/Q1OMHCybNEO6cbbD79SVRGINBrLVo3VP9W9Zyq0YhV3kbsTuVjmUYelFL2xUoUXdd1cDmtiRTERD8ej9viEOaarCuDuFQC</enc>]]>
    </text>
  </js>
  <css>
    <text>
      <![CDATA[<enc>6xSGli4Wotw59iMlYNIY39BqoUr0dvPifiSg6AU9azEBDWoH1wuSqhMgAU8g7ZueXYxFl6C4F3zl+jeqH70TOY7s4YMemUtTL+n9QIc5jCx3dEGsELi5BYW6EvBaQOoGyQs6SEmPSbZsIi3sSeFx3lfhSfCdZg4ZgK6xvC7OpK8KfCWFAIXXLVMiF6EpXKCIiqyupTGDBdKkxVgsrYxaeGX4YDQmNouKV5Mc42FazvMbbRDJGHqmMZXvsJb/pcJe8e/+l9s+oPZT6pVJIrDaS+VwWTvc+k26w40+dBlyKu+18PjLzPO1FHiGqkERPIKJ</enc>]]>
    </text>
  </css>

</dir>