<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButtonImport SYSTEM "..\Include\XML\DefaultButtonGridImport.xml">
]>

<dir id="hreqtct" width="Large" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Quá trình công tác &lt;b&gt;[%s]&lt;/b&gt;" e="&lt;b&gt;[%s]&lt;/b&gt;"></title>
  <subtitle v="Thêm, sửa, xóa..." e="Add, Edit, Delete..."></subtitle>
  <grids>
    <grid table="hreqtct" fieldKey="id, line" order="id, line" allowFilter="true" allowOrder="true">
      <fields>
        <field name="id" dataType="N" fieldType="PK" width="100" format="0" hidden="true">
          <text v="ID" e="ID"></text>
        </field>
        <field name="line" dataType="N" fieldType="PK" width="100" format="0" hidden="true">
          <text v="Dòng" e="Line"></text>
        </field>
        <field name="ma_bp" width="100">
          <text v="Bộ phận" e="Department"></text>
        </field>
        <field name="ten_bp" fieldType="EX" width="250" aliasName="b" join="left join hrdmbp b on a.ma_bp = b.ma_bp" >
          <text v="Tên bộ phận" e="Deparment Name"></text>
        </field>
        <field name="ma_vtr" hidden="true" width="100">
          <text v="" e=""></text>
        </field>
        <field name="ten_vtr" fieldType="EX" width="120" aliasName="c" join="left join hrdmvtr c on a.ma_vtr = c.ma_vtr" >
          <text v="Vị trí" e="Position"></text>
        </field>
        <field name="ngay_tu" width="120" dataType="D">
          <text v="Ngày bắt đầu" e=""></text>
        </field>
      </fields>

      &DefaultButtonImport;

      <script>
        <query>
          <text>
            <![CDATA[<enc>BgU6fJXPsu8qA7uxiAa3uDf6ZsPF/TlxFYTz4X45vFojcCttWBn0Xy6MCriq92WY8YZTmcpb32GxbJrYFBA8lqxu6MuSaoGZdUPfpj38c7le+nSFs6D5nD5vscIJ5+EjQC+k9pAGdnhJMueO1cQK9PX/QPYaVd+nRLqQ/bpU1F+wf+pH8tMH6VII4erqkCDLM3/iMNyVQ1k/5sI061+wx78OTnrDDNfZjYlJEXxCYIJw68sjBCxB6ESiTC0fpmyQmgfIUx+VN9dTxTwWNNwCmw==</enc>]]>
          </text>
        </query>
      </script>

    </grid>

  </grids>

  <js>
    <text>
      <![CDATA[<enc>fwAk1FETPvvMjc3Jqxd5NXc1fTHeC1AK7lgXH0kCxHpg/prNdBRCanBlew09QupwsL9W2VHmgOKpVy8QWy62UZcCv2HHyVjZM0MZ3ZfDCL9QUGbzpCooMhUwDGmNFBaLE/ujGZivUDFQWiMi7HllJTtvEG212zTMRKQiufc04f0vaU6UxEz0fvZIN/9lPExl</enc>]]>
    </text>
  </js>
 