<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="kbnguoiduyet" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Khai báo người duyệt" e="Approving Officers List"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="kbnguoiduyet" fieldKey="id" order="user_id, loai, ma_nt" allowFilter="true" allowOrder="true">
      <fields >
        <field name="id" dataType="N" fieldType="PK" format="0" copy="false" hidden="true">
          <text v="" e=""></text>
        </field>
        <field name="loai" dataType="N" format="0">
          <text v="Loại" e="Type"></text>
        </field>
        <field name="user_id" dataType="N" format="0" copy="false" hidden="true">
          <text v="" e=""></text>
        </field>
        <field name="username" width="100" fieldType="EX">
          <text v="Tên" e="Name"></text>
        </field>
        <field name="nickname" width="300" fieldType="EX">
          <text v="Tên đầy đủ" e="FullName"></text>
        </field>
        <field name="ma_nt" width="100">
          <text v="Ngoại tệ" e="Customer Code"></text>
        </field>
        <field name="tien" width="120" dataType="N" format="0">
          <text v="Tiền" e="Amount"></text>
        </field>
      </fields>

      &DefaultButton;
      <script>
        <query>
          <text>
            <![CDATA[<enc>hqvDjgZi6gzJ58CHf5R3W1xNU8diPV9fCBEFIWoudtaD7bUhz3BiEX7k7z9o7w2X2iRoR7CEImBKvBQCNXrLbjt1ZX/Ow5eDh+2lkVVhbm0GG9HfNFSUXSPlccJz6zk0MXg6j2CQWgMDIVcymGyD6eS9xJ837FNc26sKasEBzmHq5OwDatkCcxYfK3Zw2X+s7I1CGJsRVwYcexOjBRcfz4xuHLXdLt4u8S62lH5AII8=</enc>]]>
          </text>
        </query>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>XvL+x8oVBBLliPvtuS2L9u+rMJT3rmVqJZGy6tiIT7UcxjagGgT37OiypRi2JZbFU+s+MtXrbWN2iL5zuPuGmasVXptMIFQVQP9Z6Ohz/lpMYT5GhLD/dqYSiMLOCm0FzfSk6uWaoPacBn70jt2P8IAyMPVDDOTM8jidMyrewE2N4YTmldOZXQDpzNUggzfmmELPnlcepFprSQF3fpLJNA==</enc>]]>
    </text>
  </js>
   <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
</dir>