<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridReport.xml">
]>

<dir id="khhdvhq" dirViewType="Grid" dirObjectType="Report" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Kế hoạch hàng: Dịch vụ hải quan" e="Row Plan: Customs Service"></title>
  <subtitle v="Từ ngày {ngay_ct1} đến ngày {ngay_ct2}..." e="From {ngay_ct1} To {ngay_ct2}..."></subtitle>
  <grids>
    <grid>
      <fields>
	  	<field name="id" width="100" hidden="true">
          <text v="ID" e="ID"></text>
        </field>
		<field name="ma_ct" width="80" align="center">
          <text v="Mã c/từ" e="Voucher Code"></text>
        </field>
		<field name="so_ct" width="0" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
		<field name="ma_job" width="80" align="center" link="V">
          <text v="Mã" e="Job Code"></text>
        </field>
		<field name="so_job" width="80" align="center" link="V">
          <text v="Số" e="Job Number"></text>
        </field>
        <field name="ngay_ct" width="100" align="center" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
		<field name="ma_kh" width="120" hidden="true">
          <text v="Mã khách hàng" e="Customer Code"></text>
        </field>
		<field name="ten_kh" width="250" fieldType="EX" >
          <text v="Tên khách hàng" e="Customer Name"></text>
        </field>
		<field name="so_tk" width="150">
          <text v="Số tờ khai" e="Declaration Number"></text>
        </field>
		<field name="so_kien" width="200" fieldType="EX" >
          <text v="Số kiện" e="Number of Pieces"></text>
        </field>
		<!-- <field name="so_luong_kien" width="120" fomat="Qty" hidden="true" fieldType="EX"> -->
          <!-- <text v="Số lượng" e="Amount"></text> -->
        <!-- </field> -->
		<field name="ma_noi_di" width="120" hidden="true">
          <text v="Mã nơi đến" e="Origin Code"></text>
        </field>
		<field name="ten_noi_di" width="250" fieldType="EX" >
          <text v="Cảng đi" e="Origin"></text>
        </field>
		<field name="ma_noi_den" width="120" hidden="true">
          <text v="Mã nơi đến" e="Destination Code"></text>
        </field>
		<field name="ten_noi_den" width="250" fieldType="EX" >
          <text v="Cảng đến" e="Destination"></text>
        </field>
		<field name="ngay_hl" width="100" align="center" dataType="D">
          <text v="ETD" e="ETD"></text>
        </field>
		<field name="ngay_hld" width="100" align="center" dataType="D">
          <text v="ETA" e="ETA"></text>
        </field>
		<field name="ma_nv" width="120" hidden="true">
          <text v="Mã nhân viên" e="Employee Code"></text>
        </field>
		<field name="ten_nv" width="250" fieldType="EX" >
          <text v="Tên nhân viên" e="Employee Name"></text>
        </field>
		<field name="dien_giai" width="250">
          <text v="Diễn giải" e="Explain"></text>
        </field>

      </fields>

      &DefaultButton;
    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>RpbzP+PqStLO2tPhVZO/oxKjrNKTdzhz5y4GGYPdQXi3b+Y6oeK4u/3C5CKm25Y14SlQoLx49lfqUbn5VtVxxVogjwN817NHzsDCAmk6jcXUyIEk8qhrWhHZLP60ZhOQ6+nNmNUnzpVDoiVGRIplIXCroeYjqwJccK7NvycOEaoibod4EBcL1VzSFV4RizKS2T2hOVj7LwAA1Y5EHy28OQIcGhnthHGEQDOmNo2fnWY8KzWGQGoRhGayfZ5vCHv+</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
  <script>
    <processing>
      <text>
        <![CDATA[<enc>g+KZ+QKBlC+LdD0jHhpbmZH+0cO49XMb4I2w1EhJoh9DSBCHEgZyLiYo38ktxqP37wVXUdFYY4UCs9n2fMJwlk4r6jXWb4pL9fTw54D8KIE=</enc>]]>
      </text>
    </processing>
  </script>
</dir>