<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="m32" dirViewType="Grid" dirObjectType="Voucher" voucherCode="CN1" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Phiếu chi hoạt động" e="Payment Slip for Activitye"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>

  <grids>
    <grid table="m32" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true">
      <fields>
	  
        <field name="so_ct" width="100" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
		
        <field name="ngay_ct" width="100" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
        <field name="ma_ngv" viewType="Combobox" width="100" >
          <text v="Loại hóa đơn" e="Inv. Type"></text>
          <viewInfo>
            <options query="select ma_ngv, ten_ngv%l from dmngv where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="ma_kh" width="120" >
          <text v="Mã nhà cung cấp" e="Customer Code"></text>
        </field>
        <field name="ten_kh" width="250" fieldType="EX" >
          <text v="Tên nhà cung cấp" e="Customer Name"></text>
        </field>
		<field name="dien_thoai" width="120" fieldType="EX" >
          <text v="Điện thoại" e="Tel"></text>
        </field>
        <field name="ma_nt" width="80" >
          <text v="Ngoại tệ" e="FC"></text>
        </field>
        <field name="t_tt_nt" dataType="N" format="FCAmount" width="100">
          <text v="Tổng tiền" e="Pcs UOM"></text>
        </field>
		 <field name="t_phi" dataType="N" format="CostAmount" width="100">
          <text v="Tổng phí" e="Pcs UOM"></text>
        </field>
		 <field name="t_tt" dataType="N" format="CostAmount" width="100">
          <text v="Tổng cộng" e="Total"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="80" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="80" fieldType="EX" >
          <text v="Đơn vị" e="Customer Name"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" >
          <text v="ID" e="ID"></text>
        </field>
      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>ut7bmtX51o7ohlkZy11sVOLa5Jhz2RDkKOEXar2fa7ZrRChgEQ8Al6jIu/IL/Y78hfUAw8KYrELQpHuehIbDA+e8AEOwIHjLApb2mvWnC0RgfiYW6SHiDNnphlX8rgqx81ffrhqgz8ZfW17EUUhto6Nu0grK+7s+eWQy1QX9pSOlQzvNbyPVNa4WouQZ1SH9fhgyt3SDiLHUsNLApDR9mb8YiIDVJt4G8PmZZ23HEvwqHf9GkyulpMsbTmG89NJejR1N83Smi8tHVSx8mu6xtg==</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>fLvsT8g+OP5RgvwdX+lih+f3tTPBZ7DMaEwgH2tlD2eyQv29NffAEl0IE5xNCmTYjESs90ofFQDheYlLKAVA1g0qeMPT8EyRDbTstgsFZn8NXxxcvjHAWjBxp9CnZywGY8IOXw8mK33ij5C4BAXRy1cmfR3finOnMe1rkMgeaW+CayF2tDPbxwiYHkIlqg1yS+UodPfLPNRT8Fy+LvfvVKtIRhNeEZf+fV/8hFKPsGBBj3jbDbE0TwtymNNWSoR0wfHTqYGsKiOZhqJpMpndRs2mTct/lgRQBPmGJCT15Q8f9w8uuIzCm1e07BdkMjjel46B+2M1XMfrXBtiLK3xR5My5DoqrNb81BpP+T9fMKFcvGOpNqe0OOtb8KxCBvUPAF1P+FIGMgTEVDlBZAaug5eeqj4mI3fXLaRYz9HOkb7oHRbuTTd610bu4NmvyGvWhrj4fIjcxLcswQRJhJ67xaDx4Fb6s3HMHqFmrLOAQLHJC++hgpcvxtAM7xwlbABG3OTEow3xx3ujxlBjCAIRHW5IT9yUInpXk78uW4Z2iZ+BDGLqM8FfdBE3X2beGEZhc4OY4DniSlnAPRONOw2/IW6fPBaPNF1U7Ev7g/+MrQyBpgeN+EFF1K5nVfk1YrdKm2yDX0G+qdddERQlVLcaSw==</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>hLiBLm3iF/aJj7eF2MoRKj/HDLPeZEvb8Oeh7zVev47Tb3AO52UkdhOKYxH2hA1bta+3Mg9EmL/FFYDqoqcZpDQxrBu3rX6F3GxN++HQ+zsIdh0UZdzL7ngdy17XEhSh7Re0LUK4F5JJ+F8/aGB0g0Pta4uBRLLRdTNIT1hc6DCZ6HtFVGFX3Vc/QWIiQaGN</enc>]]>
    </text>
  </js>
 <css>
    <text>
		<![CDATA[<enc>nRVQr8m62Vh+aFddZ4BstdkubgX5HMu2EJ1AdJiqIaGFiQym1g9S6q4+lwVIkHq2gGpWCxsZbipT3tMtrvFmp/e81RKmYn8CNYWFccGgs38/sc90DztIKHAlv2JblpKO36oBFbr/zKFKKpibg75FbPBCCv/sc9utXRvi4f/PUOy6uSdeaOhdV4fR3z+lEXfXefEEPhDMgMrTITxaId74x8b9TRcmlfLiQ9T9Zy0EpJIrIP0N7YlWjevD7S1VGVRa2xNCAgpp+uHyOpA/RKce/drgyg0TG/6t6GOXJWLcFupFRGMFgMKi0GfX5R6X+a05L0t3G9LOcsKhy0/qvIIWZvvZgEO1QWPw59p9pS08PduOOCjuYo3duZ99XewfBjJp</enc>]]>
    </text>
  </css>
  <script>
    &VoucherJSLoading;
  </script>

  <messages>
    <message val="DaThanhToan">
      <text v="Đã có chứng từ thanh toán cho hóa đơn này, không được sửa/xóa." e=""/>
    </message>
    <message val="DaTraLai">
      <text v="Đã có chứng từ trả lại cho hóa đơn này, không được sửa/xóa." e=""/>
    </message>
  </messages>
</dir>