<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="m48" dirViewType="Grid" dirObjectType="Voucher" voucherCode="CT0" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Chi tiền phiếu mua" e="Spend money on Vouchers"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>

  <grids>
    <grid table="m48" fieldKey="id, ma_kh" order="id desc" allowFilter="true" allowOrder="true" key = " ma_ngv =1">
      <fields>
		<field name="ma_ct" width="80">
          <text v="Mã c/từ" e="Voucher Code"></text>
        </field>
		<field name="so_ct" width="0" link="V" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
		<field name="ngay_ct" width="100" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
		
		<field name="ma_job" width="100" hidden = "false">
          <text v="Mã" e="Job Code"></text>
        </field>
		<field name="so_job" width="100" >
          <text v="Số" e="Job Number"></text>
        </field>
		<field name="ma_kh" width="120" hidden = "false" fieldType="PK">
          <text v="Mã khách hàng" e="Customer Code"></text>
        </field>
		<field name="ten_kh" width="250" hidden = "false" fieldType="EX">
          <text v="Tên khách hàng" e="Customer Code"></text>
        </field>
        <field name="ma_ngv" viewType="Combobox" valueDefault="" width="140" >
          <text v="Loại phiếu chi" e="Voucher Type"></text>
          <viewInfo>
            <options query="select ma_ngv, ten_ngv%l from dmngv where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="ma_nt" width="100" >
          <text v="Mã ngoại tệ" e="Currency Code"></text>
        </field>
        <field name="dien_giai" width="250">
          <text v="Diễn giải" e="Pay for"></text>
        </field>
        <field name="t_tien_nt" dataType="N" format="FCAmount" width="100">
          <text v="Tổng tiền" e="Total Amount"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="80" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="80" fieldType="EX" >
          <text v="Đơn vị" e="Customer Name"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>eI26kcY8K27UuHppYNqoUilnrrQxunLx7WT+a/kN785w4sUTIDzQS1bpP5EL9plTfKeptZGq30nRa+tQ2cfCPo/HyHs/ZJAQT4C/ftIQKqNDwGsjuhJCxH8Ofj/0g/AJaF4zci0eAW0R6UvJA2IAI7z73HozbWy/h5xWrjVRRbp51S5RWs9N9xi2MGX5TkuCuQ2kClcUsLEm/1DaqaZaK3Ae5KqJIngnmH8d70tPqIfOoIECFvyrb9j+TKSWH65q4ChytQB0239SmfnaEZsSq6RzL9JbKvT770RGU/+OfW8BRgRevqDD7pzqO5ho6Q6r</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>KSzpZO3yfkC46ccuO3MLih5uUguf+WtflncTtwjFV72qN/hJcG/AEuUP5lpqEyblugAVaCWCmdNVXE6aUwmIZuaHx1cqtRXAiM8uo3o6poRaemb3UY82uViKA4GBXYY9JXkXe5Rh4nPYk7nb9OhUHije4CK8oXfesSWrmXF1diZ/Q8iUgg4pn1otOwO/63KOoDh/KGLhjaQjpmzB/gNBLQHfNa2icX7kJvf3JCHdYgFhKLbl6D25wKyDDF8XHF/l2U78ci0C9NMabgKxb2aZ79tABFagHQoBtC6p1tciJJQsK3yhCjVliffAaJivoS5d5RfbpQbzT8kBSRRXDuTtoEiqtoQ7X/9ScsEvUVXf6lhjIF5UnGygg/ul5yWLXV6L0sPW46eT9jEgcCNFnWieWrZH5ePZt/jhMm6zB1vPrKl4MUx53S+eBRvz4OH174lWCPcSdTlqJQkFeHHPxeEgf8KwzghCV2Lf3pFG4xuYgVk=</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>XymOY7dD2w2+zQLbB/WOXG1d5GPL5AAFi2GKmZZrxlImw9YOui3xToTDW5HkBe0PnRzzNELkcgbQ7JRCOUjWAjnxvsYiARKpgxgam8SRuV/+q660E3V+uiMXuD6wAZ7DalljB4QcgqD0gwWh6fh+eJtmrJl9RAJ2fIn4CfnrbCBfe8vR97MUw5+KOpRtJbJuSiGwrvpV5QS6tAzAemCfzA==</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
  <script>
    &VoucherJSLoading;
  </script>

  <messages>
    <message val="DaPhanBo">
      <text v="Đã phân bổ phiếu chi này, không được sửa/xóa" e=""/>
    </message>
  </messages>
</dir>