<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="m48" dirViewType="Grid" dirObjectType="Voucher" voucherCode="CT0" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Chi tiền cho người mua" e="Spending money on buyer"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>

  <grids>
    <grid table="m48" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true" key = " ma_ngv =2">
      <fields>
		<field name="ma_ct" width="80">
          <text v="Mã c/từ" e="Voucher Code"></text>
        </field>
        <field name="so_ct" width="80" link="V" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="100" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
        <field name="ma_ngv" viewType="Combobox" valueDefault="" width="140" >
          <text v="Loại phiếu chi" e="Voucher Type"></text>
          <viewInfo>
            <options query="select ma_ngv, ten_ngv%l from dmngv where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
		<field name="ong_ba" width="250">
          <text v="Người nộp tiền" e="Pay for"></text>
        </field>
        <field name="ma_nt" width="100" >
          <text v="Mã ngoại tệ" e="Currency Code"></text>
        </field>
        <field name="dien_giai" width="250">
          <text v="Diễn giải" e="Pay for"></text>
        </field>
        <field name="t_tien_nt" dataType="N" format="FCAmount" width="100">
          <text v="Tổng tiền" e="Total Amount"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="80" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="80" fieldType="EX" >
          <text v="Đơn vị" e="Customer Name"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>7r3qJdCnhbIgdR/LFAUEGZCwAWlIGrYgDDEXkqFuTJSHDssloPIC/QQ1BBb9R0S3UgjgauIBvvYwYxQsXCOq2UKdXboftAL4rYk4m0bp5zfd7/IcVgrGb8Pei8uJWiWaGsNs8gQNHEtoz4NfosEcBiWhkei+fsOS7g3wVqcqwK2MZD5MbLrS38B2/xdPIz0/EkK5lf1r8Lfh4NFpSEThazv2GmH7eqykFasgOzSgHeU/PLH9VcIiPNxer6r07+KV</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>Xi9ks7k/W+jttFV06t2QjAwa0kVt7mF97MX3V9RCZOlUNr/y9C5e9rdzNrajkdpx/JMJm7fQQVvy53G9LiXaO8oqrV1E4FJwgRSMRo/KzXdGqzC98HJFZIyjtky6hJR43lRiv/9N8074M3gwJikt1/ZBUhCss9OX8BHD09PhmfexILUObLW4OEYW3zn5r4g/i2JOC8SO2blFFoJx3FYBcPN1N7kFRn//LoYewhClmIfXT3Dptu1ZTlxxzYsMPDoxbtLXiVqChab0orR0XgPzMiVpBV4MINlJTYVu/Y6kPL5nlZ3bU2L6jUoMkirOKsf//YRpjYTRjJBlsgW/BnL0ZyHnGtVsfeZzhIP3Gh5Ixk6hCKBlZ9PQjcmeNsvsOVpIVUj0EgfC+snGQW858unuq6wxvJ3poou11b3kr7dfEEBGxKhb/Jnphp2GIrg78iywRGmPi2WK9CqF0Pbt53fGbGK6IgOVxS2deCQnI7/+tUG+cWMKRELbAdqzqiX9JHPg6VKV5kZpHA4BKooVyYsI6YVu+FJBIo8ggzG3y5AAXiKn655QgKFGW4G4yclpF4OV</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>XymOY7dD2w2+zQLbB/WOXG1d5GPL5AAFi2GKmZZrxlK1UV20S6f0Zk+MSm/mKpSaQVElNOzzSqzuX4GCKEE81kI8mUW0WHM+cKXoVqs7XTNbayDmAGDhz1PGSvEo943L8E6OZur0GGBZ5q3+6v13l3TZKhISgi4DICfx1wWfeyriHajaVQs7X0/3SNcXNC+c</enc>]]>
    </text>
  </js>
<css>
    <text>
		<![CDATA[<enc>cTMcaemK/mtRjps8m/sJOVirlLEJ+6JxiLPeJpYli4TAugeI+9xS9CIT96sX4XiNHefVQOt7fompL31ydAZJ3zbOdWMd5eIffmA/BGo5olHD9HllibL9oaJ+q8SIGGIxctuUbBiK/AoBCVom/JB6t7K63gLTkI+n1+rKmi9w1o3agX3Q3T7VA7fpVMPNyATDKCMwOuHkuP8gVjUw+qEn8lDMfSVRMnD0/FysmWigoBh/gLFLiJHLlzQDzpc5t/w9ovG2+hZPKJkxSGbquy14Z/Moy+LeKNtoKkGhDFJLvHX1Z9I5Pqnoi64lNbwHXFIxbOALp0KsYLr56b26De9xBtmOeTdLi0YparLh4bTcD2fca+XxZyDGiDNFsNbEQ0ln</enc>]]>
    </text>
  </css>
  <script>
    &VoucherJSLoading;
  </script>

  <messages>
    <message val="DaPhanBo">
      <text v="Đã phân bổ phiếu chi này, không được sửa/xóa" e=""/>
    </message>
  </messages>
</dir>