<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="m52" dirViewType="Grid" dirObjectType="Voucher" voucherCode="DH1" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Đơn hàng" e="Sales Orders"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>

  <grids>
    <grid table="m52" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true">
      <fields>
        <field name="so_ct" width="100" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="100" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
        <field name="ma_ngv" viewType="Combobox" width="100" >
          <text v="Loại chứng từ" e="Voucher Type"></text>
          <viewInfo>
            <options query="select ma_ngv, ten_ngv%l from dmngv where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="ma_kh" width="120" >
          <text v="Mã khách hàng" e="Customer Code"></text>
        </field>
        <field name="ten_kh" width="250" fieldType="EX" >
          <text v="Tên khách hàng" e="Customer Name"></text>
        </field>
        <field name="ma_nt" width="80" >
          <text v="Ngoại tệ" e="FC"></text>
        </field>
        <field name="t_tt_nt" dataType="N" format="FCAmount" width="100">
          <text v="Tổng tiền" e="Pcs UOM"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="80" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="80" fieldType="EX" >
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>ut7bmtX51o7ohlkZy11sVIaZnUwHEM+ebZUTVuvKujT003xHFhXk+bfhdo+bOLeOc6q63u3F2aexGLbLnl1qTTXhLrNlXeSxVkMrIqXqOIV0K//tFN5voZDEwxmggErUPzh+qFPUrUMIk3h+Ki6PotHKs2S1UZVa98zmFp4o9+J+uINWCG/0sLwuHcsDKIU19OP6Sc81dVTM/vl6dUUBlcpGftcyDenTxwFE2b469gB46nBpzJU1ETEPwEwoY+NGyJC2fwU1SXrO9LnA5xSiMg==</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>8F3dGYAfTmkBA085VB5fh26oiky4ARwU7IOJMeFTboVlii6cjNeHFd8JAzb4GffJJFGcCjmWnWhmLDJVW5aLECkdXmRKDeN99rYOXLFruaAiCFYMiuRO5OPtwsNbeNr0T4g/HYQ1DFJhjpGZdlCh6Bf0y4JHajFQSWUvA4HqmnDtiOzv1toRobEHmxqQEshJz5ob8c7JDWghS8ipBCYXE3WOWPJy3joPl7s3ev6wiFBO7aNb29h4RO2E93mi+69odCYeZsYAiqr7wYeJwOIKsVUzPIzHLmXZgs11wa8V2iZIreOQpt3wcuwFIzN5a7aNYD3dS9afVpofgk7S2bbPnmKfZmiUJZ2+7h48/eAUFufdkbkdrrK5Vg9NxErapjPeXvyHAR0jXoN5qeCSCQzDG/fRTE3kCsjYkeJUu3FQ1v6xvvUZ6EBzOK/WfzBDtNf4Ufqbh5UJ7j/fxXYmkfEEZ7p+eqRQ/NeFpjXSdf+dut7QogwILcEppM8dNoUwQlWuwMWSzHbt1ckuK0UBN8P53pX1sJEeJg+vHkoNmJ2sHrWmjQV/oAY6g+EM3cs+IMLZfQ6w/MS4Eb8J6WPKP+nRP9GCF/98yXRFZQa0VG6ajbZJV+hO23I+tRoRpyxphzHMGn7kQkdRzO7RiiUIApp0Ig==</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>XymOY7dD2w2+zQLbB/WOXAD0H/r/pvM1arZOqu0yMtTQh4eMXgYRdeAgBia9tMuvO4/DMbcLNhx7fBMImgRk7ubKAqAcBTb2fQmhsjov/KK2mc6Cn+m9D4JCYh4XNOq7X5QpJ/oR05AEq511FSJGM+aGJlknkDE4/9rsLNPCmrAKf8vWjPR6cbR6EMV+aPWb</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>

  <script>
    &VoucherJSLoading;
  </script>

  <messages>
    <message val="notApproveRightEdit">
      <text v="Không có quyền sửa/xóa đơn hàng đã duyệt ngoài mức được phân quyền" e="" />
    </message>
  </messages>
</dir>