<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="m54" dirViewType="Grid" dirObjectType="Voucher" voucherCode="PX3" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Phiếu xuất/bán hàng" e="Sales Invoice"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>

  <grids>
    <grid table="m54" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true">
      <fields>
	  <field name="ma_ct" width="80">
          <text v="Mã c/từ" e="Voucher Code"></text>
        </field>
        <field name="so_ct" width="80" link="V" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="100" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>

		<field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="ma_kh" width="120" >
          <text v="Mã khách hàng" e="Customer Code"></text>
        </field>
        <field name="ten_kh" width="250" fieldType="EX" >
          <text v="Tên khách hàng" e="Customer Name"></text>
        </field>
		<field name="ong_ba" width="250" >
          <text v="Người nhận" e="Receipt"></text>
        </field>
		<field name="dien_thoai" width="120" fieldType="EX" >
          <text v="Điện thoại" e="Tel"></text>
        </field>
        <field name="ma_nt" width="80" >
          <text v="Ngoại tệ" e="FC"></text>
        </field>
        <field name="t_tien2" dataType="N" format="FCAmount" width="100">
          <text v="Tổng tiền" e="Pcs UOM"></text>
        </field>
		 <field name="t_tt" dataType="N" format="FCAmount" width="100">
          <text v="Tổng cộng" e="Total"></text>
        </field>
        <field name="ma_nvbh" width="120" >
          <text v="Mã nhân viên" e="Customer Code"></text>
        </field>
        <field name="ten_nvbh" width="250" fieldType="EX" >
          <text v="Tên nhân viên" e="Customer Name"></text>
        </field>
		<field name="dien_giai" width="250">
          <text v="Diễn giải" e="Explain"></text>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="80" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="80" fieldType="EX" >
          <text v="Đơn vị" e="Customer Name"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" >
          <text v="ID" e="ID"></text>
        </field>
      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>TFrXMfBM86WjKsyHbYMp7GKMhit0II0znti9WYjlJ1BgFngrw3VgvqjAKs3Bb/R4hWon4VFJTz6YjBQhHfafViw4J00lIR7MLnMQliNfOTG3ByftTnuKyvK62L2oL3dmytmm8fmXRMohkcak+wCguH1fUfbpEv3l0FeIm2Gfg7GB5XqwB+kyfa20wHirc8Z78wN3U8ps5sNkXt9rV5gr+npez8ZROOagKYgBc9YXdvzH7WfMS/uCvv2Ldxi11nJZErMr5SaH0US6iRr3MN+Y6UWRpXdxYkiKDY434KRqPzEszVoT+n+Uyx7edKTx16wB</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>D+QGugzUMBz+zjA5cEHcp44h8YpcC3M+Wz+CW1UXDx3lHPVJwNLzBLDNJu396q5ZA29UngnHuC9WjjPSWDALqGH5L6jOk1iJMmKP7LvXH6YElueMImz8kBqBgEnDTPB1d+uBS3UEIVCA01yDVIL/MFqjP90d8x6Nh9BhV2e6V7fAqC7GGmjxNVylZmgLL5c4smJHbsvPJjzvgUauDeNRVqQQCyhqEM0DEh/P3SGcnn6p/YaSkL1mA6pVp1lIfntBtH1ZFsmFu/7xBB0kwmH5+IIYN9kGsfxEmeHwXisq36tSUxrqYl/WIwBr35z9QylNJvF/LADuwQeOsWlXEk6d75R5PsBtEt6X15Orxxh4j07Jlo4e4qArOPC8p0l6CWwFkndjfeDISQXll16RXmrkjP2fA0flINPR8oGqRM32BgATHJs7e66vtvHLVWCihVK1ldI3wA9QOVPqTx4dPdPBFWszTCvtYqWYdCAUQIt3bPxqazNnVjdsmhnXt0BnPFTHvzBn5ckWvaUYo/hfWRK29Ui8zlZ54lrrnFptWoT+S0Nt59EyUyItYQkJnE9SG+akaxEBO6iIZnHZkzKvVO+ZRIrW4YYnuyZI5n+WHrUylOyvjUB36o6LUvtbMuEwuEoeOXsRPRCUoFUXdf92mRPnAcjjWDpmAH+8MkF5jDaQEGg=</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>hLiBLm3iF/aJj7eF2MoRKkVrUDZares+TCtMAvrDcy+DR6gzQww2/A93NXL1SDstz8B956IkQjCFpww+gt+mquRiZflgRnpYt+pKTQJv+3BTOnRC7vZn53yAMkUIDVFZus75Q11IqLMSyrl8vr/bSqcFAzoOf5ui/U+R17zDXv1wlnrf0/LnLhxWzDerKIIX</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
  <script>
    &VoucherJSLoading;
  </script>

  <messages>
    <message val="DaThanhToan">
      <text v="Đã có chứng từ thanh toán cho hóa đơn này, không được sửa/xóa." e=""/>
    </message>
    <message val="DaTraLai">
      <text v="Đã có chứng từ trả lại cho hóa đơn này, không được sửa/xóa." e=""/>
    </message>
  </messages>
</dir>