<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="m64" dirViewType="Grid" dirObjectType="Voucher" voucherCode="HU0" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Hoàn ứng theo phiếu tạm ứng" e="Refund according to advance slip"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>

  <grids>
    <grid table="m64" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true" key = " ma_ngv =1">
      <fields>
		<field name="ma_ct" width="80">
          <text v="Mã c/từ" e="Voucher Code"></text>
        </field>
        <field name="so_ct" width="80" link="V" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="100" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
        <field name="ma_ngv" viewType="Combobox" valueDefault="" width="140" >
          <text v="Loại phiếu chi" e="Voucher Type"></text>
          <viewInfo>
            <options query="select ma_ngv, ten_ngv%l from dmngv where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="ma_nt" width="100" >
          <text v="Mã ngoại tệ" e="Currency Code"></text>
        </field>
        <field name="dien_giai" width="250">
          <text v="Diễn giải" e="Pay for"></text>
        </field>
        <field name="t_tien_nt" dataType="N" format="FCAmount" width="100">
          <text v="Tổng tiền" e="Total Amount"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="80" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="80" fieldType="EX" >
          <text v="Đơn vị" e="Customer Name"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>vGhhx6UX2ukHmYI+roecmvkpcTu8WyDAXe6ey467lIg6chdIUIOsI8/uFwdjW6lEYL4Nl0UHv9BLLoa3uyQ7iAglYvuUBWGVpB0GkfINeBKe5cGRPG2U/hTi3/ta81n+XS2Yr9q1aGSBLkpmxmTA51q+tCju9izTlNFf+xz51oP7FCdpyJ82OyVtECyZEEKnKeVnqWcR1BYMOgNHD6ZwQCC/ODm8eGG9Scx1xmsGp1s=</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>Xi9ks7k/W+jttFV06t2QjEFcYZOJYOTnf69FU3Ik7iH+kAWm4JVeHS81B/hh1g/XUfD4N62v4havEO+FSpMkw7aaU+NiLJ3iPM99qB1Th+smu00Rc+iO3IBBz9dpqPfRCRr7mbEegzMFpU/VHTe8pEhv9Qk3JAzM8dCHt6aLiIlsuOvF0tka2ai9D5YeZnjw0cO2chR9pdq2jwESDmvDXqrIG72sMrYaHzczFhT36L39YERcW6MIWd6rlCxo2UMafpS67BvnIVs/lrnu2i5yJguhsTOXidhw0UtgmamzE9Mx7d/AsJXI3fLSeFcNbcMCT8HvKmaY0rivtgRFuvAcubb7wbl/tY9WCS0zoHIauAtLKqjyBxqblQxHA4AT3CYV/puONtWL/jf5NQ/iXkQtMGdzUV2/w5BM4iQ9ADH4yV5JBVfZ6UyzjJChUZ1YjoK4LNd8PH5fN5JYhQ7otSVH2kX1H1dW1eHGOybkTqXpmQuHOCBd1oytbZOyLGhhzKr2nseluFHRgao1iZLxhBQLPcXnxEwl6QHkp+s73OU2bJ1DfzHx8ujdGg0xncK7C2tv</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>hLiBLm3iF/aJj7eF2MoRKmVB4vIDFvr9AOk4fs5FlphoHlR9Q/BF+vuIU5uuy9AruRy2VhBnbbp9xDI4xyXp41CycQijXuZcmyb0zehwPlZtd8IlbfM9w6AO0PR4cYrVZrTGzneyvUTojuSaZ/VsWnwfHp0BNEW782lvGy8tQK1arDJn9IPbyXHxOQdiI2Nw</enc>]]>
    </text>
  </js>

  <script>
    &VoucherJSLoading;
  </script>

  <messages>
    <message val="DaPhanBo">
      <text v="Đã phân bổ phiếu chi này, không được sửa/xóa" e=""/>
    </message>
  </messages>
</dir>