<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="m73" dirViewType="Grid" dirObjectType="Voucher" voucherCode="PX1" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Phiếu xuất kho" e="Issue"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>

  <grids>
    <grid table="m73" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true">
      <fields>
        <field name="so_ct" width="100" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="100" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
        <field name="ma_ngv" viewType="Combobox" width="100" >
          <text v="Loại xuất" e="Issue Type"></text>
          <viewInfo>
            <options query="select ma_ngv, ten_ngv%l from dmngv where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="ma_kh" width="120" >
          <text v="Mã đối tượng" e="Customer Code"></text>
        </field>
        <field name="ten_kh" width="250" fieldType="EX" >
          <text v="Tên đối tượng" e="Customer Name"></text>
        </field>
        <field name="ma_nt" width="80" >
          <text v="Ngoại tệ" e="FC"></text>
        </field>
      
        <field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="80" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="80" fieldType="EX" >
          <text v="Đơn vị" e="Customer Name"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>ut7bmtX51o7ohlkZy11sVIaZnUwHEM+ebZUTVuvKujT003xHFhXk+bfhdo+bOLeOc6q63u3F2aexGLbLnl1qTTXhLrNlXeSxVkMrIqXqOIV0K//tFN5voZDEwxmggErUPzh+qFPUrUMIk3h+Ki6PotHKs2S1UZVa98zmFp4o9+J+uINWCG/0sLwuHcsDKIU19OP6Sc81dVTM/vl6dUUBlcpGftcyDenTxwFE2b469gB46nBpzJU1ETEPwEwoY+NGyJC2fwU1SXrO9LnA5xSiMg==</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>8F3dGYAfTmkBA085VB5fhz/SS8ticme5KhUssklA4KWl4y0UFjb4dqrQwQQpUxNCvd/cD5LYPKWBFTh8lF3qL8iAbC3KZaIklNq1xYdEjD46dVm/xACjh1keOexaj5cs6QaFy22lLXuCv5aTruPmW5yho2HWKuepzg3AefoJhspCV8hnr5i6D7U1LeJHVz6s+EG2xgV7C+llw92qkxAC+BMnGKE8a8wAveXimQ43A5C0D1aql8pWqDMqy+a+zWbRqtF1co1P/1THGezIe6LEcZ1sd2t8hkvu+LlLeaFdMRsAzxT4Gq2DPbPV0R1z+Z9BJsX+zXf2OUEq5K2FRSxDL32u/Q0pBonCcFsqnd+9mAGfMIntCHqlL+ETLBZTL3yUbwemvSdfmJFY2cpUEoVHe34Kc2lWfsQ9Fpz3lpzaNcBFN60cpMT4jmnQ6bhQNbJ/NXTH3DcolMxm+beG+yS66SlaKkfK2kwPZp6/zEMNj17V+xdMu7cNt8v48w/Pot0U7qILfiONVnqETHq/A55AEEhvL2Ld4HAQalRYHY+eLTSBxr50Yl/HnmgAyVCSn4jAAe6MadItnmTiv4z1daK5TfPe3J5kJFrqxJCjoO4bXXV2Y07HOEAjo0G7uov7K1drjCXFKwayLrj05XC5MsO2Ew==</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>hLiBLm3iF/aJj7eF2MoRKq+ezhnfR9ttQKO1/+2z8zguwputqdZoZGLnXSoETak0E5LifIhhJEAXS/Lx170ku+mAmNMlnmw+2rJ40joSMOzq/S0bUwtad+izTZUOXvqlJpjbFtdSU1ZzGxZc25o0X3Eqhv4Z34THSCsY9XvUwzCCf7AfRxIDwS+dowP6fFPy</enc>]]>
    </text>
  </js>
 <css>
    <text>
		<![CDATA[<enc>nRVQr8m62Vh+aFddZ4BstdkubgX5HMu2EJ1AdJiqIaGFiQym1g9S6q4+lwVIkHq2gGpWCxsZbipT3tMtrvFmp/e81RKmYn8CNYWFccGgs38/sc90DztIKHAlv2JblpKO36oBFbr/zKFKKpibg75FbPBCCv/sc9utXRvi4f/PUOy6uSdeaOhdV4fR3z+lEXfXefEEPhDMgMrTITxaId74x8b9TRcmlfLiQ9T9Zy0EpJIrIP0N7YlWjevD7S1VGVRa2xNCAgpp+uHyOpA/RKce/drgyg0TG/6t6GOXJWLcFupFRGMFgMKi0GfX5R6X+a05L0t3G9LOcsKhy0/qvIIWZvvZgEO1QWPw59p9pS08PduOOCjuYo3duZ99XewfBjJp</enc>]]>
    </text>
  </css>
  <script>
    &VoucherJSLoading;
  </script>
</dir>