<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="m74" dirViewType="Grid" dirObjectType="Voucher" voucherCode="PX2" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Phiếu xuất điều chuyển" e="Stock Transfer"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>

  <grids>
    <grid table="m74" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true">
      <fields>
        <field name="so_ct" width="100" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="100" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
		<field name="ma_job" width="100" >
          <text v="Mã" e="Code"></text>
        </field>
		<field name="so_job" width="100" >
          <text v="Số phiếu bán" e="Sales Invoice Number"></text>
        </field>
        <field name="ma_ngv" viewType="Combobox" width="100" >
          <text v="Loại xuất" e="Issue Type"></text>
          <viewInfo>
            <options query="select ma_ngv, ten_ngv%l from dmngv where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="ma_kho" width="120" >
          <text v="Mã kho xuất" e="Site Issue"></text>
        </field>
        <field name="ten_kho" width="250" fieldType="EX" >
          <text v="Tên kho" e="Site Name"></text>
        </field>
		<field name="ma_khon" width="120" fieldType="EX" >
          <text v="Mã kho nhập" e="Site Issue"></text>
        </field>
		<field name="ten_khon" width="250" fieldType="EX" >
          <text v="Tên kho nhập" e="Site Name"></text>
        </field>
        <field name="so_buoc" dataType="I" width="80">
          <text v="Số bước" e="Step"></text>
        </field>
        <!-- <field name="ma_nt" width="80" > -->
          <!-- <text v="Ngoại tệ" e="FC"></text> -->
        <!-- </field> -->
		<field name="t_so_luong" width="120" >
          <text v="Tổng số lượng" e="FC"></text>
        </field>
        <field name="t_tien_nt" dataType="N" format="FCAmount" width="100">
          <text v="Tổng tiền" e="Pcs UOM"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="80" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="80" fieldType="EX" >
          <text v="Đơn vị" e="Customer Name"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>8vLJUPR6bb4mTVg/bTOoWdmipWkjHv4rTCmcuxpQRVz3dUHrAaq1EL1DsdQlyt7ciMbjrNS5ymfNGLqzoWMNpjtjs/vcVu09Rz7Z6OFHUGcgquOeRpQOovOg7vItzxM36UUn0oB6FtwpVCK4cosAJ779Mkk1tMrEIvEF+aZhvhp5L4jP8EDCvUHF51yf2f1ftdvOP9jWtfW4Ta1qpoI2egcNY9/4qwNhuVf9C31ZI6kVhNoeq6gB/51OEggZsQ4XnrI+dDqTdDGRh68NAeqED27skaBbRS/dmnD5xpnRSqavYCAv56KyHuhbuD9KKlzZq4jMhqAQjGLaeV+21CqEmQ==</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>zTqXBEwNfXxYK+o+jyFk5SVBj3bIr4CH1ShVuZHjkytCUl12OL074804Sb+2ehtkpxzLBLYhCB1WHa0EFin58tX69ne6tFv7onSvNFbrxOim2GRYyGQcg5FhwqGR8RxdjZHpOnjNVZWMUKPmQW6URJP99xdGrvCfxL8xATLHU3Gpq6mEtuFtLV8ZFLbEgZ3ku4xCnRff2UP8DEHM+jJkhC/iVckj4v4bBk92Mal4l6JuZweNYP5ddEmU/gdFVplAE5hoJJ4GNIc0ytVYJklpctWVPRMDEGZzkW7h4MPz/MuZ/USOi0F18q0vZ1j1QSNf2WEbuaKsLdcORxtWjItx78P53GR3a9BFMjjzUBfBqAQbw06+ZQqzadhpOizlETsv4N7IObDgMTbCM/7Cd/wkC5OIt7AdqHdsVQiAcztrCbOZP99fVGBqvfkAjP4ExZlSlOg6KPQWSQbs9wjL3VPQAYa3JXPuqLAlcMmhZdcbQ1q2R6pl6fC8rLlxR+BTuSUrvYstnNDMp0VKdyKRT9u9nVIHUTvrk5L0QN+VXjUK0VOoI/Zm26Dc7fF3CTpG0wpzzrcw9rFiu/oD6OwEXv5dsT/i5kzpTTVpIJBEaj+xfCpw6w9jKDcImx5QKGbhXzeZJATmNJ9nWD/gDinqTO7BThZuTA/zBCWoz36bf19/Mx+OUWXAZkX5IdaxyszaQGMc38rsYH8cQ8neMx5yX8WYBg==</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>XymOY7dD2w2+zQLbB/WOXF+PgqPLUdyLqz5iLTNe/d/TUHdU1M5Dy4nqgh+/Cv5bFGF0zrT2di3w/iWA6BONgdzRoVAjrAOycsTCPOpD4s+q1yGaikkz95h78pfahfMbet+FO8J9y4KskejOYGrfJDGpLBFcF8Hkszfm2QC6KG8yrTFSIA6IGp574EJOYp5h</enc>]]>
    </text>
  </js>
<css>
    <text>
		<![CDATA[<enc>cTMcaemK/mtRjps8m/sJOVirlLEJ+6JxiLPeJpYli4TAugeI+9xS9CIT96sX4XiNHefVQOt7fompL31ydAZJ3zbOdWMd5eIffmA/BGo5olHD9HllibL9oaJ+q8SIGGIxctuUbBiK/AoBCVom/JB6t7K63gLTkI+n1+rKmi9w1o3agX3Q3T7VA7fpVMPNyATDKCMwOuHkuP8gVjUw+qEn8lDMfSVRMnD0/FysmWigoBh/gLFLiJHLlzQDzpc5t/w9ovG2+hZPKJkxSGbquy14Z/Moy+LeKNtoKkGhDFJLvHX1Z9I5Pqnoi64lNbwHXFIxbOALp0KsYLr56b26De9xBtmOeTdLi0YparLh4bTcD2fca+XxZyDGiDNFsNbEQ0ln</enc>]]>
    </text>
  </css>
  <script>
    &VoucherJSLoading;
  </script>
</dir>