<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="m81" dirViewType="Grid" dirObjectType="Voucher" voucherCode="CN1" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Giá cước vận tải" e="Freight charge"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>

  <grids>
    <grid table="m81" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true">
      <fields>
	  
       
        <field name="ngay_hl" width="100" dataType="D">
          <text v="Ngày hiệu lực" e="Effective date"></text>
        </field>
        
        <field name="ma_kh" width="120" >
          <text v="Mã khách hàng" e="Customer Code"></text>
        </field>
        <field name="ten_kh" width="250" fieldType="EX" >
          <text v="Tên khách hàng" e="Customer Name"></text>
        </field>
		<field name="dien_thoai" width="120" fieldType="EX" >
          <text v="Điện thoại" e="Tel"></text>
        </field>
       
        <field name="unit_id" hidden="true" dataType="I" width="80" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="80" fieldType="EX" >
          <text v="Đơn vị" e="Customer Name"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" >
          <text v="ID" e="ID"></text>
        </field>
		
		 <field name="nh_kh1" width="100" fieldType="PK">
          <text v="Nhóm khách hàng 1" e="Customer Group 1"></text>
        </field>
        <field name="nh_kh2" width="100" fieldType="PK">
          <text v="Nhóm khách hàng 2" e="Customer Group 2"></text>
        </field>
        <field name="nh_kh3" width="100" fieldType="PK">
          <text v="Nhóm khách hàng 3" e="Customer Group 3"></text>
        </field>
      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>ut7bmtX51o7ohlkZy11sVOLa5Jhz2RDkKOEXar2fa7ZrRChgEQ8Al6jIu/IL/Y78hfUAw8KYrELQpHuehIbDA+e8AEOwIHjLApb2mvWnC0RgfiYW6SHiDNnphlX8rgqx81ffrhqgz8ZfW17EUUhto6Nu0grK+7s+eWQy1QX9pSOlQzvNbyPVNa4WouQZ1SH9fhgyt3SDiLHUsNLApDR9mb8YiIDVJt4G8PmZZ23HEvwqHf9GkyulpMsbTmG89NJejR1N83Smi8tHVSx8mu6xtg==</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>oa2zooz+owggexi/0z5M6ak/cWceHgperX/wjLSMgNvixU9cAWYsWxglV3y8EacTyCTzcZo95qUzSEIsZZdboKfxmbee2c0x3rYzETYKKfXD5zNFXOJkVBjiNawBAuImNS56HabGbQV0T2Cgchs/YB09vkc9dLiN3O+iVlaIsP8FTd/r0YqcOea/uAh6h+39M/DEohEffbJTuLCVYoB9y8CrSKGFsvTNUA8kUsCra1i1RWDI0DU8q+/aj+GqgnwRzFcykIVpip8u20nmqd3J0AYlcIdRhtt8cFvOixJ69veO60nwBfOwbzKzaTbPKwXq1ecbQleKb2T8D7km29FALrTCwJfuszrN0IHNme0hdKmVnEFeGWks+F73E6r4d4dTfEoJQ1bqWwk5jhEdMvirCJv3Id5EwwTZXfxR3kh2mssmlJ4RUotyF89yNUhaYpAIeyLH0Rs62MqwJe+uqvcH/aqYyAPjVMrs8EsQYlYQ5yMjGq5DOeSn1B+EkFGWjLKFDaAuZnxxBLDL1wngs/jNJrBG+jRyniX/MjDa9s+KJksDmp+VtFSr+eXBhVZCS9TUyHbV0o6XSqGTr1t8Ou2PgpeNbDz8hgWjs+UBo0H/+H8=</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>XymOY7dD2w2+zQLbB/WOXA+Owm5refjT0ABAj71pUEH21oqwgdi996Nv8Ths6As9eugev7m2qScrhF6iigEG4ehhKcMzJFqwHZ6qusDbqUQWQzhzei4aKmmbu4GQS4mqMJTivrVPWA57DEKImBeXU8JW2lvhHeBCu2WyNM0JCgB+ktPrvryoD0UhZ7AuFg6i</enc>]]>
    </text>
  </js>
 <css>
    <text>
		<![CDATA[<enc>nRVQr8m62Vh+aFddZ4BstdkubgX5HMu2EJ1AdJiqIaGFiQym1g9S6q4+lwVIkHq2gGpWCxsZbipT3tMtrvFmp/e81RKmYn8CNYWFccGgs38/sc90DztIKHAlv2JblpKO36oBFbr/zKFKKpibg75FbPBCCv/sc9utXRvi4f/PUOy6uSdeaOhdV4fR3z+lEXfXefEEPhDMgMrTITxaId74x8b9TRcmlfLiQ9T9Zy0EpJIrIP0N7YlWjevD7S1VGVRa2xNCAgpp+uHyOpA/RKce/drgyg0TG/6t6GOXJWLcFupFRGMFgMKi0GfX5R6X+a05L0t3G9LOcsKhy0/qvIIWZvvZgEO1QWPw59p9pS08PduOOCjuYo3duZ99XewfBjJp</enc>]]>
    </text>
  </css>
  <script>
    &VoucherJSLoading;
  </script>

  <messages>
    <message val="DaThanhToan">
      <text v="Đã có chứng từ thanh toán cho hóa đơn này, không được sửa/xóa." e=""/>
    </message>
    <message val="DaTraLai">
      <text v="Đã có chứng từ trả lại cho hóa đơn này, không được sửa/xóa." e=""/>
    </message>
  </messages>
</dir>