<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="n15Approve" dirViewType="Grid" selectMultiple="Table" voucherCode="DT1" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Duyệt đề nghị nghỉ phép/ chế độ" e="Approve a training request form"></title>
  <subtitle v="Xử lý &lt;b&gt;%s&lt;/b&gt; phiếu yêu cầu đào tạo" e="&lt;b&gt;%s&lt;/b&gt; training request form"></subtitle>

  <grids>
    <grid table="n15" fieldKey="id" order="id desc" key="xstatus in (0,1)" allowFilter="true" allowOrder="true">
      <fields>
		<field name="unit_id" hidden="true" dataType="I" width="120" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="120" fieldType="EX" >
          <text v="Đơn vị" e="Unit"></text>
        </field>
		<field name="so_ct" width="120" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="120" dataType="D">
          <text v="Ngày hiệu lực" e="Voucher Date"></text>
        </field>
		<field name="ma_nv" width="250" hidden="true">
          <text v="Mã nhân viên" e="Origin"></text>
        </field>
		<field name="ten_nv" width="120" fieldType="EX">
		  <text v="Tên nhân viên " e="Origin Name"></text>
		</field>
		<field name="ma_loainghi" width="250" hidden="true">
          <text v="Loại nghỉ" e="Origin"></text>
        </field>
		<field name="ten_loainghi" width="250" fieldType="EX">
		  <text v="Tên loại nghỉ" e="Origin Name"></text>
		</field>

		<field name="ma_ca" width="250" hidden="true">
          <text v="Ca" e="Origin"></text>
        </field>
		<field name="ten_ca" width="250" fieldType="EX">
		  <text v="Tên ca" e="Origin Name"></text>
		</field>
		
		<field name="so_gio" width="120" >
		  <text v="Số giờ" e="Origin Name"></text>
		</field>
        <field name="id" fieldType="PK" hidden="true" width="120">
          <text v="" e=""></text>
        </field>
      </fields>

      <buttons>
        <button id="approve">
          <text v="Duyệt" e="Approve"></text>
        </button>
        <button id="cancel">
          <text v="Hủy" e="Close"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="find">
          <text v="$FindToolbar" e="$FindToolbar"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="refresh">
          <text v="$RefreshToolbar" e="$RefreshToolbar"></text>
        </button>
        <button id="freeze">
          <text v="$FreezeToolbar" e="$FreezeToolbar"></text>
        </button>
      </buttons>

      <script>
        <query>
          <text>
            <![CDATA[<enc>7+poRLx5P9001XVc9xv/AOJeSNBMibOBy2C6I+jIwocEPXq/LYPbKNBYBM6rBkoFlXa2dM/C0ejcGk6rbH3McmwJDNqdszfRaga71kDtHbxvXWK9x2wqEox3jE3xLEJFYDg1RpMsnU61E5yk4Y85pJpZ0vgUsy1P+nsAxeChII+jFrdcvMGMeq3rPmAZtX+8zTngJVhdCdf9zPqxEisbA4lOu9FBlyr2beGSi02C5J1FP4YyEbpdQV2Rvkyx6v670w5iMy+uQ1dMSX51RcnWBSlDZNR+AFX5dLm1rVuTpU9ek05yXQh1/2/0YfhkKMUG</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>hFkXVhengshh5OT1A7vSleW/0gsAD5HBuqIvBR+RUI2hWuynCkXk0yUbrhhe+bA6kx5HK9wnhLXLxhH315jaTX2pLe1aD3QR/dJPt44ib3nois++PndiTup5Rlc0Jc5E+YP1JNYQobLOjJTMguFe4OLEiup/Iu0qiPUg4B1VlZHhECPd0lGkv9Taml3SMC95Yd2IS1O4KV/lhitffFxMilfa1OKEtqDHQxtyuQzr6/fRV9Yqx4dhh8gS3wzE9WKLXzReyf9OiqyJz3rawlIuRuOqZeUzTXfwa8j2UfWZvWl8eXsPUkm7W9G2nWUKum9xSOjV1HAa1y28GiQn4IUBZO6xjjcEuHxhxud4IgHuyN7NI+YXUTLLL/QQZTO5nFW2FLQIlU2G0WWoe8zSO4+p6EIBCGbRpHQaUxy3ZYIxpAYy+QdVhxwCjOz22Ict/X34F9m2XuZvEGMA2ZsEBySX1IL66ub44i24DUaNDYRyJQZp8iXkYEV3WOvcTvlY1ms4LZN6M2j70EOrdW6yL7/LdiPAfluTxQstgbNWgrmV8N8/h0zgTMy4D04NSAbDeZPr</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>6CMkmSRkyZV4MrafDhzUmUSNIxdN+R82s3mX8KR6KA666lT60L4VrSoEk9cYxkNBrDljKbsch7fkVFeNYTsyNlMdB6W/wYofeSTW6TyufbtNyng5hX80oQVdfA4YpIOOvJWhWfJOQNOEh/Hlyqdo19HpuSrcHiQ7pfFbDiObdlO1f7a7y/DDxp37giiJPkJKxey1e57d3rGGXMEZaJckVKOldtSahf6xDQNjTL20LDWzZ1wqXuXwyUHmsjJ3+7Oq0oefdrqSffvW4E6zTb1kbI/kAl7E+pbIicBmWHBbpy5Ec/+bPtr68YK1fq4AZ5yKjPn34TONwoCYc39g5P4lStzYrGqB5u+QgtPcJn5tL7/GrTiFk0IbkPF/CFAcC7JHI2vmbLE0/QkvjeHGJ0edv69S+f8Ca7BEur1/ak3st7Rgc0dVzZsizSwYU2Boroanyfk88IUmQz7JzNTe3EYT2ejG9F10Q21LCifLdOKTY/hrTa/bcazVU7AlvfP+uz6jTHi1EE0xHQca81EdOZwxrQXH6Ch7BjUXm/V9/Na09/0mAjnN7HjwNhP2Tqlvf4yDl7TtB8fV0V0j8Q9TnZvTCLKlbXqHC3BJin9FR8Z65K3YCWHizecR8MDP6eoQM2OYuI3D/rejDltwiMP1xLwBhvq4R05c4pRjuR/d0gZUUtcGk4DRiBQDViAP1yMGJDzbmyCri9OmSUtkXqfArcAb2PVNrsYKONjge/0RcKWPy++SJfqeunHQ69W0G+Hhb6vkiov4hAS3sbKYtjNy61ittZosXFbM7T/RQnMN4T8Qtkqb65WTcHZkMfNGwSxzZiYlH4lat6Abv87oTg9BiXOnlHWuMWVG6NLSJRWYFH2ZsP5svuJnDqMiY6so9LHVwBaQd+dOfT1/O0KFjszeyP9iaGyM9hOo+GyoAuYm4HH4FOo=</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
  <script>
    <request code="Approve" transaction="true">
      <text>
        <![CDATA[<enc>xIx3Kc6eC1CuBzm4ZWw02M2LND4ILmK1AvzBNs++NhbzaXqcmJFiV1k6cFzEY5LVqsqUQuhH+svAvR9pHD+8sIJw6i4qK3epIi9rpnypR2fGZ1fYhTinZcsc0E9o++mCO8xnXqLbNRYnU2XiWmG6kN1vG4aDdSBxgtV7E8WwuH798Xg3wlEZ4LzCE4/YWhcIrYJhFwTfw9ZoTjDckEURW3yab5Ys4sw8Im0d591Tc7sNEx5uFCLhxH9r4fpWL1om+9tQo3PPOp6Xto3cxslSRdWDRCxHQy1hFLf0SfJ5FqN3I1UXvLY537NgIJagLsQVLpuHxoYROZK7doS8+9Eb62lfoHQP6/GPI1orzcMa7Do=</enc>]]>
      </text>
    </request>
    <request code="Close" transaction="true">
      <text>
        <![CDATA[<enc>NulJ0WTD24ro1jlpurl2M9ISjlS5pMKvewRL+upwhOZXghzXk4IMxvwHAIAbEsWlTRrUa0wkDht8esU0FxrWAiLaOCrPRvRr3bN0r81k54GqFXv9u5PoTtCJ8+lhSsx4/Wj0VzSlXtMsrniNepip+SRnaf/ySUTPBdgXWkXtcEuGD/FvB08mR5gxcQL7DFgg5FOnKO5mx7sHtlRUozxjzGu4Gb5P2f2/ex6F6teGIUyYTt69JGj1uiZail5PADh6</enc>]]>
      </text>
    </request>

    &VoucherJSLoading;
  </script>

  <messages>
    <message val="msg1">
      <text v="Bạn có chắc chắn sẽ &lt;b&gt;duyệt&lt;/b&gt; các phiếu được chọn không?" e=""/>
    </message>
    <message val="msg2">
      <text v="Bạn có chắc chắn sẽ &lt;b&gt;bỏ duyệt&lt;/b&gt; các phiếu được chọn trở về trạng thái [Chờ duyệt] không?" e=""/>
    </message>
    <message val="msg3">
      <text v="Bạn có chắc chắn sẽ &lt;b&gt;bỏ đóng&lt;/b&gt; các phiếu được chọn trở về trạng thái [Đã duyệt] không?" e=""/>
    </message>
    <message val="close">
      <text v="Hủy/đóng" e="Close"/>
    </message>
    <message val="approve">
      <text v="Duyệt" e="Approve"/>
    </message>
    <message val="undo">
      <text v="Bỏ duyệt" e="Undo"/>
    </message>
    <message val="open">
      <text v="Bỏ đóng" e="Open &amp; Approve"/>
    </message>
      <message val="inputTitle">
      <text v="Nhập lý do hủy phiếu" e=""/>
    </message>
    <message val="reason">
      <text v="Lý do" e="Reason"/>
    </message>
  </messages>
</dir>