<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="n21Approve" dirViewType="Grid" selectMultiple="Table" voucherCode="PF1" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Duyệt phiếu đề xuất" e="Approve proposals"></title>
  <subtitle v="Xử lý &lt;b&gt;%s&lt;/b&gt; phiếu đề xuat" e="&lt;b&gt;%s&lt;/b&gt; proposal form"></subtitle>

  <grids>
    <grid table="n21" fieldKey="id" order="id desc" key="xstatus in (0)" allowFilter="true" allowOrder="true">
      <fields>
	  <field name="ma_ct" width="0">
          <text v="Mã c/từ" e="Voucher Code"></text>
        </field>
        <field name="so_ct" width="80" link="V" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="120" dataType="D">
          <text v="Ngày hiệu lực" e="Voucher Date"></text>
        </field>
		<field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
		<field name="ma_dv" width="250" hidden="true">
          <text v="Mã đơn vị" e="Unit code"></text>
        </field>
		<field name="ten_dv" width="150" fieldType="EX">
		  <text v="Tên đơn vị" e="Unit name"></text>
		</field>
		<field name="ma_pb" width="250" hidden="true">
          <text v="Mã phòng ban" e="Department code"></text>
        </field>
		<field name="ten_pb" width="150" fieldType="EX">
		  <text v="Tên phòng ban" e="Department name"></text>
		</field>
		<field name="ma_bp" width="250" hidden="true">
          <text v="Mã bộ phận" e="Parts code"></text>
        </field>
		<field name="ten_bp" width="150" fieldType="EX">
		  <text v="Tên bộ phận" e="Parts name"></text>
		</field>
		<field name="ma_nv" width="250" hidden="true">
          <text v="Mã nhân viên" e="Employee ID"></text>
        </field>
		<field name="ten_nv" width="150" fieldType="EX">
		  <text v="Tên nhân viên " e="Employee name"></text>
		</field>
		<field name="ma_hmdx" width="150" hidden="true">
          <text v="Hạng mục đề xuất" e="Recommended items"></text>
        </field>
		<field name="ten_hmdx" width="150" fieldType="EX">
		  <text v="Hạng mục đề xuất" e="Recommended items"></text>
		</field>
		<field name="ma_loaidx" width="150" hidden="true">
          <text v="Loại đề xuất" e="Proposal type"></text>
        </field>
		<field name="ten_loaidx" width="150" fieldType="EX">
		  <text v="Loại đề xuất" e="Proposal type"></text>
		</field>
		<field name="tieu_de" width="200" >
		  <text v="Tiêu đề" e="Title"></text>
		</field>
		<field name="noi_dung" width="200" >
		  <text v="Nội dung" e="Content"></text>
		</field>
		<field name="ly_do" width="200" >
		  <text v="Lý do" e="Reason"></text>
		</field>
		<field name="gop_y" width="200" >
		  <text v="Góp ý" e="Feedback"></text>
		</field>
		<field name="unit_id" hidden="true" dataType="I" width="0" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="0" fieldType="EX" >
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="id" fieldType="PK" hidden="true" width="120">
          <text v="" e=""></text>
        </field>
      </fields>

      <buttons>
        <button id="approve">
          <text v="Duyệt" e="Approve"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="find">
          <text v="$FindToolbar" e="$FindToolbar"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="refresh">
          <text v="$RefreshToolbar" e="$RefreshToolbar"></text>
        </button>
        <button id="freeze">
          <text v="$FreezeToolbar" e="$FreezeToolbar"></text>
        </button>
      </buttons>

      <script>
        <query>
          <text>
            <![CDATA[<enc>f1SkM19+a1/f3CKl6rfy7uXDOTJLoFfyxQVoSnypmTAcQJcW4leaKKkCStWVo/CtiYftA4lpk3b2/AV42BsbbwpU/St4yGJDXp2Jb/K3OB/GSJtLoUNqrzqRkrMbHroDKWyhj5Hcyn2qem+xJZXH9wLNVK333qnczcaRnVfmXSIDkhZWl36nN00iuo2VtMmMJifqr2R5fzoknQ4zYicRBof4RLZIIshc9VWlff4maHGOwLcjedR+vaMBpqFbN2B7iB08lIHje2kBd6f0iy+Zj8d7/eBIi+FaZW66G2BZJBHTuko3ptLHOBg38xSZNAGT0IdqD+NzgPa9QFuKjfXA3HEVVhmxtZa/C/qOdKi37BtVmwEyGsmMHw00SO8RBACHWFLZ2/sAGlEgqopNfHdQS63zYbvwVCroCoOSkOK43h8=</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>aDV1jSwmTCNLA/YtG/OJISyazlGbu5T76eqYSH/TazbsPzFjDGWo9o1OfvSK8u1Nw2K5YgAY6V6sRPpxY5zD9xrvEloiRpIp3et92K+Vq+z9jubvKJvQD+BOaUQ6U48pyJ2MAf1srwDr9kzERe77JjNoxLGFisPedD0n2B5LoZZknuRLmcCmayJ2j3lxDKx9elRPNbGnkRCK/xzE+FG6DpN3My6jirZ2hB3Jb5jXLWb2cP42Dv6ilYn3u3KZz2CmfdVeI0hVfnvCQMZyvMClgiMMOITALBqG6QwCWDMhi8vJEatThojgHrlN9pNRZ8MHZvWKSuCyYT8kllN6fgCjlN3d4EWKjEfdx4tFn8qtYdqs2X/4fi+2unN8wq0gSDU5BCftDPoJaqRAsuEe/CF4UMoja65U1+J2gXAgczvoIoDXNFH68JT8adlpidxdhHy3srvO7WuT+iQ+LoN0HzsTfEL1HAbe5VuSbQeMvMxywD3QE4iiFZPlK5RciWCUnkuG0g0RDBKEHDf1M4zuk37HaH/9X9k/+0ec+phNY+Y/LxA80lyFYregE+fGgkQnYXveL2OnVx5X8CBsIBjDcz5ij+ndJDjAGCTXc8kCe/l7S4p51pIm/RWCovmrhmeymOyfXcTmySKgCGhdu+bbKCyp6Q==</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>hMNpb+ya+hTY4Yu5t+qT3GK5ludawLyyVXSd5BcdRI9B97jtnEQuGnmof4r6xccJmwVIu2qMJKd5+/Jbzd3OCk9i/NdwEvyG5IUsNss2QkPWCB9d21dqPQpv04R9jcuI5eMySugK7Q4A0Vu04eOmL0uSiWSBpQMSfZBURyyI/QLy+WyNqLuTv+QFDaQ6d9w8HFQM3jCtF4uekZMjo3BDggUpjJGrYbAP0+Ia/jo95/iAXMre1nJYtEdSjtrRKIK+fguWtul/WNJepGTnryGpWCT1xsdwPLUtnp8+tm3NbrxV2sAZHW63j83Nv9CMvHesKKXZsDHkWuStUcolqpmNYVcCi1nSxoZDz5JU0Tlirf/EQtpBB1d0Nwnn9hLlzqfpAMAJSKb0LRazJ6qyXvGMItC2XfDQ+EJMtDqVobrpbsRgZmlunpCrPHKXq7ngUqN3R+WyfMt6mMzBfOk2EUpiwYHsdFLoVgdsMj4/wlYZ3i1W1WHUU9ah3iREq30nYgOa14N7qCLX4TGfSaS3RBAL5uzbyKhtrFm1lAoVgIxZvXcYfb8ZsDftSAu9ovWBKS8zB7tutq97owvynS7BBIjvMcfIJ7EdnziG+bgCy/pBHpEhTEL8f2Hsopad0mVMoolra8JpgLrnA3OBPp1Wz8C99maecGt3971wsw96ZoSxa+ZaPq91kBNvsExOX3yklbSPRWQq3V7HMqkE1QnBjUbnv8R7+WEKQalcksXQKRIOgo5yUh1huf19YbMisnmf4Z1QImflPKO+z/zKsZPz8ImEKuOREOrX4TMci1KV6+AAYNkyDBbyyfPITzSXq9Hc+7PdhkhTHKCQckZpazfY6sETEImqUJGsa8Fp4i1dLzUYVnB1Ufr/U1z/FJvQe2YJPixnnJ7cmEqFHHfItw0niAtk+0KmVVXqKr5MgdOYvcE6ISQ=</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
  <script>
    <request code="Approve" transaction="true">
      <text>
        <![CDATA[<enc>du6diDKvIeOVynmCaZ+6sBEe6Wp4rdKmG79n0exRJG8eIdnAHTTnEcTCvlWysQ2vpSDcJJORhY6WgkS/6ZWf3P+Bq0vEn6U63Q4rT3FNnLvIZ8ivq2elNXtg1ScSYspF53jV//H9WevLUlSLEbBrWo72+Eju4rr9FjaYGIibgPyzX7YyREoPhQ7uDui2L9J/0di4i9qZLZi8uJIgSaiyFf5/Op28f/qxjLdQwXB7UQYQP7KnaOb5Z1MDEemNos9OCDX/9X0ko9SRKl90Pwdqlnt+hIzWCFSkDvwncUEJtTwj7sdsMePnz5uugav1rcWNA8Sq4jOqJfXcRZrSFqVYGW/JbubNXuIEVLSwNFv3Tns=</enc>]]>
      </text>
    </request>
    <request code="Close" transaction="true">
      <text>
        <![CDATA[<enc>puK4p+NYsDqsHf5dn+qH1oAd9RSu5ThEOUOMVTb0nSTMAEpUBOMd8I4FZFo7DEaQKVR0k3Sg//DkpZmW8NQucHLcNLk466Edn6jnzRCu2IQsC0hlE8nTi7wL/0DwXBD4sP2BvEg0uxO8zYoI8t7+WDdOc9RY4+02Dg/B+ctNvajKIkfCMnaHPqdtWFp8ZO2bPK5f+2xLUWQ/B2nn7MI/eJMfXCqLK6xN8D8zbbaG/CqeKoWqWLR0qS7ahodngTat</enc>]]>
      </text>
    </request>

    &VoucherJSLoading;
  </script>

  <messages>
    <message val="msg1">
      <text v="Bạn có chắc chắn sẽ &lt;b&gt;duyệt&lt;/b&gt; các phiếu được chọn không?" e=""/>
    </message>
    <message val="msg2">
      <text v="Bạn có chắc chắn sẽ &lt;b&gt;bỏ duyệt&lt;/b&gt; các phiếu được chọn trở về trạng thái [Chờ duyệt] không?" e=""/>
    </message>
    <message val="msg3">
      <text v="Bạn có chắc chắn sẽ &lt;b&gt;bỏ đóng&lt;/b&gt; các phiếu được chọn trở về trạng thái [Đã duyệt] không?" e=""/>
    </message>
    <message val="close">
      <text v="Hủy/đóng" e="Close"/>
    </message>
    <message val="approve">
      <text v="Duyệt" e="Approve"/>
    </message>
    <message val="undo">
      <text v="Bỏ duyệt" e="Undo"/>
    </message>
    <message val="open">
      <text v="Bỏ đóng" e="Open &amp; Approve"/>
    </message>
      <message val="inputTitle">
      <text v="Nhập lý do hủy phiếu" e=""/>
    </message>
    <message val="reason">
      <text v="Lý do" e="Reason"/>
    </message>
  </messages>
</dir>