<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="n21Complete" dirViewType="Grid" selectMultiple="Table" voucherCode="PF1" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Hoàn thành phiếu đề xuất" e="Approve a training request form"></title>
  <subtitle v="Xử lý &lt;b&gt;%s&lt;/b&gt; phiếu đề xuất" e="&lt;b&gt;%s&lt;/b&gt; training request form"></subtitle>

  <grids>
    <grid table="n21" fieldKey="id" order="id desc" key="xstatus in (0)" allowFilter="true" allowOrder="true">
      <fields>
	  <field name="ma_ct" width="0">
          <text v="Mã c/từ" e="Voucher Code"></text>
        </field>
        <field name="so_ct" width="80" link="V" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="120" dataType="D">
          <text v="Ngày hiệu lực" e="Voucher Date"></text>
        </field>
		<field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
		<field name="ma_dv" width="250" hidden="true">
          <text v="Mã đơn vị" e="Unit code"></text>
        </field>
		<field name="ten_dv" width="150" fieldType="EX">
		  <text v="Tên đơn vị" e="Unit name"></text>
		</field>
		<field name="ma_pb" width="250" hidden="true">
          <text v="Mã phòng ban" e="Department code"></text>
        </field>
		<field name="ten_pb" width="150" fieldType="EX">
		  <text v="Tên phòng ban" e="Department name"></text>
		</field>
		<field name="ma_bp" width="250" hidden="true">
          <text v="Mã bộ phận" e="Parts code"></text>
        </field>
		<field name="ten_bp" width="150" fieldType="EX">
		  <text v="Tên bộ phận" e="Parts name"></text>
		</field>
		<field name="ma_nv" width="250" hidden="true">
          <text v="Mã nhân viên" e="Employee ID"></text>
        </field>
		<field name="ten_nv" width="150" fieldType="EX">
		  <text v="Tên nhân viên " e="Employee name"></text>
		</field>
		<field name="ma_hmdx" width="150" hidden="true">
          <text v="Hạng mục đề xuất" e="Recommended items"></text>
        </field>
		<field name="ten_hmdx" width="150" fieldType="EX">
		  <text v="Hạng mục đề xuất" e="Recommended items"></text>
		</field>
		<field name="ma_loaidx" width="150" hidden="true">
          <text v="Loại đề xuất" e="Proposal type"></text>
        </field>
		<field name="ten_loaidx" width="150" fieldType="EX">
		  <text v="Loại đề xuất" e="Proposal type"></text>
		</field>
		<field name="tieu_de" width="200" >
		  <text v="Tiêu đề" e="Title"></text>
		</field>
		<field name="noi_dung" width="200" >
		  <text v="Nội dung" e="Content"></text>
		</field>
		<field name="ly_do" width="200" >
		  <text v="Lý do" e="Reason"></text>
		</field>
		<field name="gop_y" width="200" >
		  <text v="Góp ý" e="Feedback"></text>
		</field>
		<field name="unit_id" hidden="true" dataType="I" width="0" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="0" fieldType="EX" >
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="id" fieldType="PK" hidden="true" width="120">
          <text v="" e=""></text>
        </field>
      </fields>

      <buttons>
        <button id="approve">
          <text v="Duyệt" e="Approve"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="find">
          <text v="$FindToolbar" e="$FindToolbar"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="refresh">
          <text v="$RefreshToolbar" e="$RefreshToolbar"></text>
        </button>
        <button id="freeze">
          <text v="$FreezeToolbar" e="$FreezeToolbar"></text>
        </button>
      </buttons>

      <script>
        <query>
          <text>
            <![CDATA[<enc>f1SkM19+a1/f3CKl6rfy7uXDOTJLoFfyxQVoSnypmTAcQJcW4leaKKkCStWVo/CtiYftA4lpk3b2/AV42BsbbwpU/St4yGJDXp2Jb/K3OB/GSJtLoUNqrzqRkrMbHroDKWyhj5Hcyn2qem+xJZXH9wLNVK333qnczcaRnVfmXSIDkhZWl36nN00iuo2VtMmMJifqr2R5fzoknQ4zYicRBof4RLZIIshc9VWlff4maHGOwLcjedR+vaMBpqFbN2B7iB08lIHje2kBd6f0iy+Zj8d7/eBIi+FaZW66G2BZJBHTuko3ptLHOBg38xSZNAGT0IdqD+NzgPa9QFuKjfXA3HEVVhmxtZa/C/qOdKi37BtVmwEyGsmMHw00SO8RBACHWFLZ2/sAGlEgqopNfHdQS63zYbvwVCroCoOSkOK43h8=</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>aDV1jSwmTCNLA/YtG/OJISyazlGbu5T76eqYSH/TazantRvH/KnbL+b4JA9LUo4la/lCX5lTJhGkAzTdK6G14aACls9UAEm3xXaEta2Y5HKMEweBrGJmPZRZOblpJ9wwa7ETMMmPT+BTmGhhezP/0EkHjq+p84PQz+lB4RVsVM+Cy/fI8fI8QHvpBwGCr9geZIG5WEIl9DfhmiAmBV6qv7yKcczMVANL4/zVy/+P7NXQWfXs6tiyaF5C+T85LNaxzQ6gVu1GaeubEVzGpkjAf9VaUQGpOJCqHn8RRDGj3eExoYFBdyrJ3FdATLR0CO25SY3BCC8j+MLzPMY4YzFL6HKphyyu/dSskr1PyAFGrBeFLGQIIVPE/hlWyj6c7Myl8Nk+ePj36rPySJYEROJ9DGHhj7GczU+HmZET0rKV0Rcyvy2f40Xjgfd3eOO+/YAL9Aw946mjft/wvyjMmN8n1x+NTsHkJjJVawUuMSuJS87oF4SPwgDE1zHeFsaFAIGDy4vpnuuSJx6OoEsc6aVpnrE0KiVOFODVBgbY+xc/km0VOYZMNBvPvZyz7IvJbJesBUx3W980cEdrDPIcpiKRzZIFUqS6AM3v2JBKl3whlKnqg5hxxY89e+6OCU2ng9TqnKWPFV+MvO5Oe9vysnoQzQ==</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>vjxbp6fxCPE/ZBXFx/H2hhgWtM6uJoz9p4Fu5Jroh33PQq9TRnzZg2ATdPhu3dONEm7KE4NLUFZtIzWHcdqv2w8p+X4q/AX2UF6mEAO9nyp18wZFbiXGVu3g929mzY/uolLN0bGj3PoYTu0OscHLqUX/eei6pIHw4ybYwog2zXR5ppBUlek0VwvNAQi2BAaIQocj5rys6f7SCYSZUc96Dh5XbntXyiGjx+F7jqaCkAYVwt/XNcmi6HfWnnjZRxmURC1kbCLTm2Lh4I0dTw2Zrwzo6EHlUuTiW6EzNvqcRaXJUeHCHgj1QsPZfe3zg5En7DIwTwlRr5gfDtSs/+GFcV0nGzCGN5Yd7YM8Xvm9iizckoEOd9qsWDydutdWFsbq0R6sYa6p9DlyYxjOUScTfEbE99pmz94UPbGpkXkAO0KpaFtmrotjobSg/DCcneNygHdcOj2cpMzlbDfSJ23+JEOnWLgfnE9BgzFpkONm63WVR90Oxmk1y3lpOCr15kUEdsh0BN3gezJfPahBJRIzwim1/cA2MBpwGXes59aKTWgzLtnWpJxFOLpmmjg6h3lGuOZRTZW20xQRoR14elgDtHEoDaRfZMALuhdGKsMLQLA6XE+nMWx5J6BF4gwVB3jeuNHiWR8fxhCFe13n+vXuIjZe2ykczlClsENqPvDKr2Hv5c/fmv2JUg/7qNN/kgsbG2d5IMk5ED+dclTffMkx0rrXJMfZlDB5YCKKfLQ6saKaVAlhPs2zPIgOPWTLIgZK/S4BcNsTUTRpXNVaTZhaVYIsF7W7r82X5Lih7UDZ/44=</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
  <script>
    <request code="Approve" transaction="true">
      <text>
        <![CDATA[<enc>du6diDKvIeOVynmCaZ+6sO/t1SpGYfilhpbUO4pER3mIGO5a6ngmsZL8qHqqCBQ+seYggAf8lP597at+cx6pboARUpo0OjVb785p8j26d3DJdcyrksNiI8NKRbaNEpQl2q933rHPk33Iv2NfWU3hBv5jjdlfDg7pvBrI+Vr6O3IZJG7zm5V7FsqmiQB25pptCjCEFA7Miz/AnEK9ipd6GPRknCIOBuiKNfzDG8RzoZgBvPpx5ssiQx0H9Ds4JG0NQmL93+q51oCVhh6qs2NSLCvSyQTGpxRSjJjT85SKpjd26ZmhRYqS45kPPt6A4Yfx0p36C8u+beksGlhK9jEGdGi16eG9YL5vZkSHuG03DW0=</enc>]]>
      </text>
    </request>

    &VoucherJSLoading;
  </script>

  <messages>
    <message val="msg1">
      <text v="Bạn có chắc chắn sẽ &lt;b&gt;hoàn thành&lt;/b&gt; các phiếu được chọn không?" e=""/>
    </message>
    <message val="msg2">
      <text v="Bạn có chắc chắn sẽ &lt;b&gt;bỏ hoàn thành&lt;/b&gt; các phiếu được chọn trở về trạng thái [Chưa hoàn thành] không?" e=""/>
    </message>
    <message val="msg3">
      <text v="Bạn có chắc chắn sẽ &lt;b&gt;bỏ đóng&lt;/b&gt; các phiếu được chọn trở về trạng thái [Đã duyệt] không?" e=""/>
    </message>
    <message val="close">
      <text v="Hủy/đóng" e="Close"/>
    </message>
    <message val="approve">
      <text v="Hoàn thành" e="Approve"/>
    </message>
    <message val="undo">
      <text v="Bỏ hoàn thành" e="Undo"/>
    </message>
    <message val="open">
      <text v="Bỏ đóng" e="Open &amp; Approve"/>
    </message>
      <message val="inputTitle">
      <text v="Nhập lý do hủy phiếu" e=""/>
    </message>
    <message val="reason">
      <text v="Lý do" e="Reason"/>
    </message>
  </messages>
</dir>