<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="n21Return" dirViewType="Grid" selectMultiple="Table" voucherCode="PF1" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Trả phiếu đề xuất" e="Approve a training request form"></title>
  <subtitle v="Xử lý &lt;b&gt;%s&lt;/b&gt; phiếu đề xuất" e="&lt;b&gt;%s&lt;/b&gt; training request form"></subtitle>

  <grids>
    <grid table="n21" fieldKey="id" order="id desc" key="xstatus in (0)" allowFilter="true" allowOrder="true">
      <fields>
	  <field name="ma_ct" width="0">
          <text v="Mã c/từ" e="Voucher Code"></text>
        </field>
        <field name="so_ct" width="80" link="V" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="120" dataType="D">
          <text v="Ngày hiệu lực" e="Voucher Date"></text>
        </field>
		<field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
		<field name="ma_dv" width="250" hidden="true">
          <text v="Mã đơn vị" e="Unit code"></text>
        </field>
		<field name="ten_dv" width="150" fieldType="EX">
		  <text v="Tên đơn vị" e="Unit name"></text>
		</field>
		<field name="ma_pb" width="250" hidden="true">
          <text v="Mã phòng ban" e="Department code"></text>
        </field>
		<field name="ten_pb" width="150" fieldType="EX">
		  <text v="Tên phòng ban" e="Department name"></text>
		</field>
		<field name="ma_bp" width="250" hidden="true">
          <text v="Mã bộ phận" e="Parts code"></text>
        </field>
		<field name="ten_bp" width="150" fieldType="EX">
		  <text v="Tên bộ phận" e="Parts name"></text>
		</field>
		<field name="ma_nv" width="250" hidden="true">
          <text v="Mã nhân viên" e="Employee ID"></text>
        </field>
		<field name="ten_nv" width="150" fieldType="EX">
		  <text v="Tên nhân viên " e="Employee name"></text>
		</field>
		<field name="ma_hmdx" width="150" hidden="true">
          <text v="Hạng mục đề xuất" e="Recommended items"></text>
        </field>
		<field name="ten_hmdx" width="150" fieldType="EX">
		  <text v="Hạng mục đề xuất" e="Recommended items"></text>
		</field>
		<field name="ma_loaidx" width="150" hidden="true">
          <text v="Loại đề xuất" e="Proposal type"></text>
        </field>
		<field name="ten_loaidx" width="150" fieldType="EX">
		  <text v="Loại đề xuất" e="Proposal type"></text>
		</field>
		<field name="tieu_de" width="200" >
		  <text v="Tiêu đề" e="Title"></text>
		</field>
		<field name="noi_dung" width="200" >
		  <text v="Nội dung" e="Content"></text>
		</field>
		<field name="ly_do" width="200" >
		  <text v="Lý do" e="Reason"></text>
		</field>
		<field name="gop_y" width="0" >
		  <text v="Góp ý" e="Feedback"></text>
		</field>
		<field name="unit_id" hidden="true" dataType="I" width="0" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="0" fieldType="EX" >
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="id" fieldType="PK" hidden="true" width="120">
          <text v="" e=""></text>
        </field>
      </fields>

      <buttons>
        <button id="approve">
          <text v="Duyệt" e="Approve"></text>
        </button>
        <!-- <button id="cancel"> -->
          <!-- <text v="Hủy" e="Close"></text> -->
        <!-- </button> -->
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="find">
          <text v="$FindToolbar" e="$FindToolbar"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="refresh">
          <text v="$RefreshToolbar" e="$RefreshToolbar"></text>
        </button>
        <button id="freeze">
          <text v="$FreezeToolbar" e="$FreezeToolbar"></text>
        </button>
      </buttons>

      <script>
        <query>
          <text>
            <![CDATA[<enc>f1SkM19+a1/f3CKl6rfy7uXDOTJLoFfyxQVoSnypmTAcQJcW4leaKKkCStWVo/CtiYftA4lpk3b2/AV42BsbbwpU/St4yGJDXp2Jb/K3OB/GSJtLoUNqrzqRkrMbHroDKWyhj5Hcyn2qem+xJZXH9wLNVK333qnczcaRnVfmXSIDkhZWl36nN00iuo2VtMmMJifqr2R5fzoknQ4zYicRBof4RLZIIshc9VWlff4maHGOwLcjedR+vaMBpqFbN2B7iB08lIHje2kBd6f0iy+Zj8d7/eBIi+FaZW66G2BZJBHTuko3ptLHOBg38xSZNAGT0IdqD+NzgPa9QFuKjfXA3HEVVhmxtZa/C/qOdKi37BtVmwEyGsmMHw00SO8RBACHWFLZ2/sAGlEgqopNfHdQS63zYbvwVCroCoOSkOK43h8=</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>aDV1jSwmTCNLA/YtG/OJISyazlGbu5T76eqYSH/TazbsPzFjDGWo9o1OfvSK8u1Nw2K5YgAY6V6sRPpxY5zD9xrvEloiRpIp3et92K+Vq+z9jubvKJvQD+BOaUQ6U48pyJ2MAf1srwDr9kzERe77JjNoxLGFisPedD0n2B5LoZZknuRLmcCmayJ2j3lxDKx9elRPNbGnkRCK/xzE+FG6DpN3My6jirZ2hB3Jb5jXLWb2cP42Dv6ilYn3u3KZz2CmfdVeI0hVfnvCQMZyvMClgiMMOITALBqG6QwCWDMhi8vJEatThojgHrlN9pNRZ8MHZvWKSuCyYT8kllN6fgCjlE2SyotdF+JAo7Eu359OwOog1oyrPVrxFSJk6CELrFwcuCgUTvEUEep8C3NE6+3tbc+3nXIsWuds7RVAEHWJ6nMy9VwjO3DZZaSP0T4/a6LYC8bY5LeDGoXCGIPXRj0TVJdmJxnzuqn7jzHSHPcypIj1tgiG8uN1WDoxdomFDCg5/s6botvqefCP4hdyjV7T0ZcDLNAVwMGXpArrelh2j0CRK2bgRZwjsCEqLZW/WrqUA1D4HGlcsj0hz+f65p7W3JYtGdWieiG2I+7AKnNShRJyEk45rVOYk6fmqw4MbUhn0AQsgMsmiuF68TpKK7649Q==</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>erfcqtjVOCf+fLkZ3pN+bt251E0IZgRNy3+ts9LnK+9T72VY4/2dP+P8ufm1uCyJhBu0YScSxct/vokUAOLpngVJzD8qh9RPg/2n9m/N4nmunfe+lhHIOKmle7Odrx4m6o/9UbOOY3QRa1z64xIyhsDv/tBeezvt4ZcPtVWWbBz+Aeznst1HTE2Pna4M52hnvgfqyzwmnoCzk5/9DWUQ9JdZijBPQNUEZBr0ADCYJeH0G2u7R7kIkMRZg7pkbmv4H0G6P2PXNnyOMD4pnrXOvnMInPjCr1zOy8ZybuQhZqgk018hMuMlJDFDoqTKQucR+wb2TPqi2/KEk9dzWsh7hwU/MPZJeJVtWdegyBIAw219yx19Gh65X1KbtDO2IWAtoHokg9aI98bXRYiVpVqoSUik9dMT3kwmkAIy4OkgUtQOq9olTT6O3DnxXe/z52KQ5Ujx2C4pVL4eV6ByLISQzLVZIB3FyDiPV1oHhswqjePvmSGuHFPHnVzq01NzKIBjO7+2mrBouscXCZKE3307kEqv+gI3e0QrUmMuqpYcOCEGYDEO8tuAkvpA8peN5siYvDi2osIRMg7iQ9Ukxg1SwGcBCmZhE5IwHX6/UG59XFy2dzbA4TBRQg8KonS9rj5x7yfkBgi11rOhlOQ36TjidF07ZTxLgikYH+zTw0RE60phXnVm12v9l+jTkI6PU9gNkhRaK54IA5FD3j+9V4MvHctkn9Zdu0x3EiKVsMCPtxBLtP12WX+FtBMAruKunx99L8w1kvDtWMaJ0po3WmGrlA==</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
  <script>
    <request code="Approve" transaction="true">
      <text>
        <![CDATA[<enc>vd+BsfYqziWpizv0b63aU6KqNjgn8Q8ul+LlfZ0gQOiFjwmYsxSZpCjrLX+A+MUiESKFVNSYH4iTBDkRbGQsPYnCXzqDZuP1E1BIroO8rt8AWpQdHwrW4dUmfYfM1JoG42VV+jG8RPqKfyJjoPIftL+wC1e+meOXUWAiuljdAbDcpAdi8frFOFy+53+I6MCcdtUdWXaxpvZ35smgtIA8UMwreukw9gUjlkY4QZPauTg5bZo2K8IvyyXV//4/Nc1Z2VFB49+LIalmThUkM2tb35MlV2kSZzTXqL9LyAbSsV3bk2Mv5vCgMamIuv0Y/DwI</enc>]]>
      </text>
    </request>
    <!-- <request code="Close" transaction="true"> -->
      <!-- <text> -->
        <!-- <![CDATA[<enc>TzBKUVccXzRU1qT3uRgSPIcIatC4D9NzkrD2KVllTCwimdXAiQJm8Rziyqasm8Ua+tAqAY7kdrXZZ/dflzQTK0445/oN48WyEVAONXg3uhoX4r1YWxt4tlWw6dozR5Q0lYGFCPBDsto7mlDNPw1tFiiG/MyKrG4Ut92kScCfn4vk0sTD/j8r42UY0aFtuVOki9OfgKC0VgRIoGhvnzK+4nbmMMo8paJNR9mcQzVaGZ3cFT0ckYYyXPoBwXDaeAV9L/hDZmNIZLxheuJEwOJEfw==</enc>]]> -->
      <!-- </text> -->
    <!-- </request> -->

    &VoucherJSLoading;
  </script>

  <messages>
    <message val="msg1">
      <text v="Bạn có chắc chắn sẽ &lt;b&gt;trả lại&lt;/b&gt; các phiếu được chọn không?" e=""/>
    </message>
    <message val="msg2">
      <text v="Bạn có chắc chắn sẽ &lt;b&gt;bỏ duyệt&lt;/b&gt; các phiếu được chọn trở về trạng thái [Chờ duyệt] không?" e=""/>
    </message>
    <message val="msg3">
      <text v="Bạn có chắc chắn sẽ &lt;b&gt;bỏ đóng&lt;/b&gt; các phiếu được chọn trở về trạng thái [Đã duyệt] không?" e=""/>
    </message>
    <message val="close">
      <text v="Hủy/đóng" e="Close"/>
    </message>
    <message val="approve">
      <text v="Trả lại" e="Approve"/>
    </message>
    <message val="undo">
      <text v="Bỏ duyệt" e="Undo"/>
    </message>
    <message val="open">
      <text v="Bỏ đóng" e="Open &amp; Approve"/>
    </message>
      <message val="inputTitle">
      <text v="Nhập lý do hủy phiếu" e=""/>
    </message>
    <message val="reason">
      <text v="Lý do" e="Reason"/>
    </message>
  </messages>
</dir>