<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="n21Sug" dirViewType="Grid" dirObjectType="Voucher" voucherCode="PF1" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Góp ý phiếu đề xuất" e="Proposal form"></title>
  <subtitle v="Xử lý &lt;b&gt;%s&lt;/b&gt; phiếu đề xuất" e="New, delete, edit"></subtitle>
  <grids>
    <grid table="n21" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true">
      <fields>
	  <field name="ma_ct" width="0">
          <text v="Mã c/từ" e="Voucher Code"></text>
        </field>
        <field name="so_ct" width="80" link="V" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="120" dataType="D">
          <text v="Ngày hiệu lực" e="Voucher Date"></text>
        </field>
		<field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
		<field name="ma_dv" width="250" hidden="true">
          <text v="Mã đơn vị" e="Unit code"></text>
        </field>
		<field name="ten_dv" width="150" fieldType="EX">
		  <text v="Tên đơn vị" e="Unit name"></text>
		</field>
		<field name="ma_pb" width="250" hidden="true">
          <text v="Mã phòng ban" e="Department code"></text>
        </field>
		<field name="ten_pb" width="150" fieldType="EX">
		  <text v="Tên phòng ban" e="Department name"></text>
		</field>
		<field name="ma_bp" width="250" hidden="true">
          <text v="Mã bộ phận" e="Parts code"></text>
        </field>
		<field name="ten_bp" width="150" fieldType="EX">
		  <text v="Tên bộ phận" e="Parts name"></text>
		</field>
		<field name="ma_nv" width="250" hidden="true">
          <text v="Mã nhân viên" e="Employee ID"></text>
        </field>
		<field name="ten_nv" width="150" fieldType="EX">
		  <text v="Tên nhân viên " e="Employee name"></text>
		</field>
		<field name="ma_hmdx" width="150" hidden="true">
          <text v="Hạng mục đề xuất" e="Recommended items"></text>
        </field>
		<field name="ten_hmdx" width="150" fieldType="EX">
		  <text v="Hạng mục đề xuất" e="Recommended items"></text>
		</field>
		<field name="ma_loaidx" width="150" hidden="true">
          <text v="Loại đề xuất" e="Proposal type"></text>
        </field>
		<field name="ten_loaidx" width="150" fieldType="EX">
		  <text v="Loại đề xuất" e="Proposal type"></text>
		</field>
		<field name="tieu_de" width="200" >
		  <text v="Tiêu đề" e="Title"></text>
		</field>
		<field name="noi_dung" width="200" >
		  <text v="Nội dung" e="Content"></text>
		</field>
		<field name="ly_do" width="200" >
		  <text v="Lý do" e="Reason"></text>
		</field>
		<field name="gop_y" width="200" >
		  <text v="Góp ý" e="Feedback"></text>
		</field>
		<field name="unit_id" hidden="true" dataType="I" width="0" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="0" fieldType="EX" >
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="id" fieldType="PK" hidden="true" width="120">
          <text v="" e=""></text>
        </field>
		
     </fields>

	<buttons>
			<button id="find">
				  <text v="$FindToolbar" e="$FindToolbar"></text>
			</button>
		  <button id="split">
			<text v="-" e="-"></text>
		  </button>
		  <button id="refresh">
			<text v="$RefreshToolbar" e="$RefreshToolbar"></text>
		  </button>
		  <button id="freeze">
			<text v="$FreezeToolbar" e="$FreezeToolbar"></text>
		  </button>
		  <button id="split">
			<text v="-" e="-"></text>
		  </button>
		  <button id="export">
			<text v="$ExportToolbar" e="$ExportToolbar"></text>
		  </button>
		</buttons>
		
	<script>
        <query>
          <text>
            <![CDATA[<enc>f1SkM19+a1/f3CKl6rfy7ppgKAsFklrxI4C8IX/lQ5dA+EPuRxCIDP0Jjfr6p4EcfMyjdIjHmNp2dbMvfYjBc8Wrp0Pu/1nXFpoRwVFgnygPYGNtpeQnZmsQWJELRWJDejk71bUSgQuoWflqn349zwcznUsDSvjTPWlWgg/+/vzwgk2KjfC9KKWRMmYyx6OyC1bVuG0Hrkq0S4On4TfvNKPgVEFphucymMSlwTl0Ww62mPWkCZP9id0HmauLOqhd4dNyR76Hj/flOJ5ov9tPtJ86eDXYBfoHnYPXV2OnAzrJt/0Dv/7xKyUSWi62jDiQpb9bMi4VKFaQ7rJzn69aMTROrlXw4RIvhY5RcPTGyMxgkM/rcnpoR80IfO1/rUv7Ouzy+c+EhI2ZHn9h7GPtfqTOyW+CqAuXbUqiAY+YeEsTOxWonDos+0dvq9tihdWRwB80N/L/l04m4Ljakl2a6g==</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>e/PWR5sSPp38uUfIS0r7fNEvPOGbyn482phZK6k91LuK4VL0AAXmcyUbFCr/Gy6MEJyLTQ9F6dvgHVM6eEPhRjmhHND7h4YPwSDjVanj/udO+P/LYD3y0YMi2Tob55zbH35E1p3NzNa8qZ7f41odDjUd7dbCJPZbqwmsiNSSyYtmKVLlQ9fuD0Pc64yMaaQd9lXTVYXwdTByXWqQuOtVhiyk7xpePaTDvrgJQJN+MFkpjUfakkNRccVIMQzxU8ZXdPWMsySZolBXZpFCC/rWULLVImIA6z7pxSH458+gkrNnGE1T8IDZcrMvXt46uraUfzafEUCu4apeqciF1zf6f0sgwOC+M0DKJQuzzl+dHOHQGHybdms3SW3dz6lDdQ9sU6D+XxYqUByfmjQRHIXFz9zU8hbMJI0EMw8FAnl3HqV9AzKGhErsRsysxKsneL6WZExL+88Sfjyd5lRDpmz99qOnE97v67l2bSTKqiXordSEuspbvBCnX5s704HVwJpmkosxBuuUtcWGOk0pyaik14N4yZ0+IkgTs/vV5UJZzXnsf48gQEfd1q5mFejFjLO94BDTgpfxo6EoAT6Ken+mpvM/nvN2pODQA8axVzSzsPzYMPm7ElBQ26YaaVfZh5k4JH/VrMJhFPBXTIu8JUkqO6Fwcl0WTcyFZTZTX5ictHY=</enc>]]>
          </text>
        </finding>
		
      </script>
	  
    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>uw3iZoR/y/5o6FF1x5y/2bIRXw3WmaUJhG+jhpFmZtHHqhzNYIheViX/i3FAnun29IM+iY5d3WaEfnEUr8mdIUOAzwl/Qriw2UrmEngbCpcfXt4ilBMpF6fqZvwVBLLKiYrwWdqafuvL775mULSf4rIeC4PJbzV/BivmlbxXHgeeVFFxMp7npcVMuwBeoUjG</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
</dir>