<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="phixe" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Định mức phí vận chuyển" e="Shipping cost"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="phixe" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true" >
      <fields>

		<field name="so_ct" width="120" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="120" dataType="D">
          <text v="Ngày áp dụng" e="Voucher Date"></text>
        </field>
		<field name="ma_xe" width="120" >
          <text v="Xe" e="Vehicle"></text>
        </field>
		<field name="t_so_luong" width="120" >
          <text v="Tổng số lượng" e="Total"></text>
        </field>
		<field name="t_tien" width="120" >
          <text v="Tổng tiền" e="Total money"></text>
        </field>
		<field name="unit_id" hidden="true" dataType="I" width="120" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>

		
     
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>T5Nuk0XwnW0VlRYHOIM5VdJhATz9ca2gCg++31RngfngR/w7ONjxvyuheauHH+XtNhbZoaJMk3u7flup9cCJ0LuexfrvNLrOWaXUgrBdJkFV2G8hesXeQrT8M6ng6q4HRymDyKqrQa3ZEHnMDmfyH+YHJEbCf7SJaj78V2gIPuAUPacvpfEmTf25ngD9DbhH</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
</dir>