<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="q64" dirViewType="Grid" dirObjectType="Voucher" voucherCode="TQ1" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Trả quỹ theo nhân viên ứng" e="Credit Note"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>

  <grids>
    <grid table="q64" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true" key = " ma_ngv =2">
      <fields>
		<field name="ma_ct" width="80">
          <text v="Mã c/từ" e="Voucher Code"></text>
        </field>
        <field name="so_ct" width="80" link="V" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="100" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
        <field name="ma_ngv" viewType="Combobox" valueDefault="" width="140" >
          <text v="Loại phiếu chi" e="Voucher Type"></text>
          <viewInfo>
            <options query="select ma_ngv, ten_ngv%l from dmngv where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="ma_nt" width="100" >
          <text v="Mã ngoại tệ" e="Currency Code"></text>
        </field>
        <field name="dien_giai" width="250">
          <text v="Diễn giải" e="Pay for"></text>
        </field>
        <field name="t_tien_nt" dataType="N" format="FCAmount" width="100">
          <text v="Tổng tiền" e="Total Amount"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="80" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="80" fieldType="EX" >
          <text v="Đơn vị" e="Customer Name"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>vGhhx6UX2ukHmYI+roecmvkpcTu8WyDAXe6ey467lIg6chdIUIOsI8/uFwdjW6lE0GV9flyJ8moi7Vn0Aec33wVjkXJ1M5gm9Xo4tvXMHT01ZBVBvdwnCk6xGtJvaqYILCfqEKh819ZkSc2FZwY3Pmdn1Ev1vhXQjxYlkhDcFHeF5ddUGhSkZL/VlpYc/zSeENGIigmZZV7/iZGlamDD7AVjMr/rBO8k8jEpMwl5uqY=</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>Xi9ks7k/W+jttFV06t2QjEFcYZOJYOTnf69FU3Ik7iH+kAWm4JVeHS81B/hh1g/XUfD4N62v4havEO+FSpMkw7aaU+NiLJ3iPM99qB1Th+smu00Rc+iO3IBBz9dpqPfRCRr7mbEegzMFpU/VHTe8pEhv9Qk3JAzM8dCHt6aLiIlsuOvF0tka2ai9D5YeZnjw0cO2chR9pdq2jwESDmvDXqrIG72sMrYaHzczFhT36L1iF3P+C7dmwAEcFnBECj/nvg3nJmaP7cZHeG7/Ucs4EHlGrLkldWWQJ0tn7Xvm4d92uUfDe1ikedQqVEXrRMo10MvZngjp6+UnscDf54QSPVBf1qEDGWc6Le60Oa9tZMOq6PN3lfD4JkGKRW8AvqyQKhYfqSI1KnNoiS/FsDHtcUynhBRPogmvRWm9y01Z0qZUoxxIbzJNnz2+9B2yQDVVzwBJSIg+aZj2Y1CG/d4l2YJnkNuw0oBnOPan/Mzi+Rdho+0lZsKxbxXv2Zs4f0wQYdqt/yllsaMCEGu5Mm/Vor0morcl+3cJ55Vic1zqdsHjNckMlHDcSA8Wh/5pPBmO</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>hLiBLm3iF/aJj7eF2MoRKmVB4vIDFvr9AOk4fs5FlphNW1nUejtBaP9/kW4fJMX76PGWOdflVQ/zwc4bkXeSaVeQhIDTiyMT9pRcSYOiKTpA+KKuWbwqyqawfSeDU60c6brHllDJM+8/GmhDnmA2yakvGW5DRDNdyORQcshqyQK9Y7yVH1HX1Qhm+ZIqyl2B</enc>]]>
    </text>
  </js>

  <script>
    &VoucherJSLoading;
  </script>

  <messages>
    <message val="DaPhanBo">
      <text v="Đã phân bổ phiếu chi này, không được sửa/xóa" e=""/>
    </message>
  </messages>
</dir>