<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="q64Approve" dirViewType="Grid" selectMultiple="Table" voucherCode="TQ1" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Duyệt nhập quỹ" e="Approve Advance Orders"></title>
  <subtitle v="Xử lý &lt;b&gt;%s&lt;/b&gt; nhập quỹ" e="&lt;b&gt;%s&lt;/b&gt; Advance Orders"></subtitle>

  <grids>
    <grid table="q64" fieldKey="id" order="id desc" key="xstatus = 0" allowFilter="true" allowOrder="true">
      <fields>	
		<field name="ma_ct" width="80">
          <text v="Mã c/từ" e="Voucher Code"></text>
        </field>
        <field name="so_ct" width="80" link="V" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="100" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
		<field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="ma_kh" width="120" >
          <text v="Mã nhân viên" e="Employee Code"></text>
        </field>
        <field name="ten_kh" width="250" fieldType="EX" >
          <text v="Tên nhân viên" e="Employee Name"></text>
        </field>
		<field name="dien_thoai" width="120" fieldType="EX" >
          <text v="Điện thoại" e="Tel"></text>
        </field>
        <field name="ma_nt" width="80" >
          <text v="Ngoại tệ" e="FC"></text>
        </field>
		 <field name="t_tt" dataType="N" format="CostAmount" width="100">
          <text v="Tiền" e="Total"></text>
        </field>
		<field name="dien_giai" width="250">
          <text v="Diễn giải" e="Explain"></text>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="80" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="80" fieldType="EX" >
          <text v="Đơn vị" e="Customer Name"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" >
          <text v="ID" e="ID"></text>
        </field>
      </fields>

      <buttons>
        <button id="approve">
          <text v="Duyệt" e="Approve"></text>
        </button>
        <button id="cancel">
          <text v="Hủy" e="Close"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="find">
          <text v="$FindToolbar" e="$FindToolbar"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="refresh">
          <text v="$RefreshToolbar" e="$RefreshToolbar"></text>
        </button>
        <button id="freeze">
          <text v="$FreezeToolbar" e="$FreezeToolbar"></text>
        </button>
      </buttons>

      <script>
        <query>
          <text>
            <![CDATA[<enc>GWtRagW07ESuMHLqkFd2Mx0bMJuTKr3o5EgukQw/eim68V1Z5pF3eONXamMnOzrKItnEUxjuF2Ssg78IKBtE7Xc1vSQFGraf6YeHw0BsbOaasO3USnB+htj8PYhhgcGzT+TXZK7Kp1kHTjsbj389v51rFnFkDOYSfTXTT8RF1uDC87lXMXJgQdoqQaXudpVeGDfoC8ri68jtSUl/o2EumTkhxY4pblZMlGq66j6p5UPO8qQyRD2LhNH7f9yF/Qdn</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>blN+3mm9nDaEo6pKGdaa6GqGbTTxgieRZcK+uQAXpWkyjfVdYMJ7hk5bCdDT5sMIw4bOovj5jc/+e7yzNw3fr/Hov6SjNNxFc4Fy0wBv8k4YI4NSICGWNQ5saXG+IltZizmM+9cNNKGiuot8fnURMwzv0gQBGDGhhoNV9kriWPL/wRAdTpI59C+NPU0EPhwDx52KV/iKgpmmls9qJD2f7+wG4mIcESbWjZY/kkLtQ1V3dc2EmHeTcd33iDS/ro0u73s/7jmnKJuWgUOKs+sM6wOAOyOKuZIpukxcwsTiYxvuIQs/2nMEEQHNZjWjHNZ+k3NLkV3oQhvpu3FtRB/OkJD+ElVlfAee7WgLeoelyDxv4+bBu0KejZ/g4WlIjc0BY6zqIasij01uT+AOzPVbUGXx6cgk8Cksu0ggJJ1XwQXss/k95QWuXwMmLhG6DHqhns6e1t5WvUYwijRz/IZY2JejLVS8XHWymLpNb3GchS4mZwyvZ7qK6l0dJUGHfZia54UlWgq136gRYzy3HFj4jnAQTZA3Rn7ZUvZfJSitFKo5QQDzom7ebErqtFPi/u46</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>hMNpb+ya+hTY4Yu5t+qT3INSZEaYfodhGbajmVr125S3DpufKQJAQPSFkjQ/5jbpRRkCfu9tFsVyees/BQ/dT7UwA0fBD2Hk0+Sy/YR6usr3xX4Rq0b4jpfFFW+w4Kyu8J+5ozc2FEqE88iz6bQABn4V4BX7ZD7gXnEui0NUj5+VZbMaKz6i99+Ho9ayP5bqkUWkOIIQjJltsr2ezjzKvRJarmvKzpLyIHud+KVvWehTT5ptf873vXVOKXewhZA4i4rkfcH9s03AnydC6+nQI5sSmPExNV6CQcp3dHErWuTnP7kQR5NDKz6859OrHf7sUnv8MCRMintnc/UDtMkqFSy9hz3/vJK73oL4vm3RCcpvyyllkpIW1A5w5JThilimom7N8pqhUGbqGS7P/O2cNFXjEaMqCP0G9j+VEi1OOW2s4gEdkGTO6c1Lak+GXfhGpWRRvzh0yS/B6LCwmgk0DqluI0COjmyXbTom0zshLupH08/xmiTk25+2FNzhCv5U3xCw0Mv3LDu1yb1nA1cbzDGPo6rv0e3yzrHkj5wdWsfHna6vyDkaSR7kKy9FZPVy0k5kScB+jOUndZNdhw/ExQ5oUMy2jv7+Lvss1t4H5VDDRgauSnMfvPXGyHenvUduISgrtXtl8XxC4eNtdHrREsWWhTzOEzv6OKkSOc49zQsbMXtaAVluXd6UFvg8jePdzj0m1KI9XdAHuaSslEeqwXts51aCqEOX1BVI86qc9d1yt+Agan4E1qjTArrhYBbj2FAevxqygSE4C147eeFyQxGg5gW0+cx0bwd0ru6B6dlfM3WlXA689C+K9tzhBg0JjF82xh674Qv0yU4iSUsmbN8HBlQsDZ2gmoCoI3hnRR/Ic0ld1o6pA8OkFFJCY9tOewQXMtbEsW3ENdBC7iv4kcAA7unKqwJ9WvVEYbNRfoc=</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
  <script>
    <request code="Approve" transaction="true">
      <text>
        <![CDATA[<enc>BaR9+6ZMEuQF2Xpff+CQhypYvhbe1alKZwAEUO6fBWIxle8XiNd2QmMFGvXUBFVcjkzg0AiLJDnezUbj8H43rrcKKnDguC0QZKxB5B7Tk10BPbhZHPmMouGBb7WePtLBIwWvMrXcZMBV5kvOtOusJZo+4Alw/STDvKuzEuphKJ988Q7QcsjWmBniaeub5i2JOJzwms4VALpcx7bpEOlcJZn8iW/zcJEtI7P8EyKbhdFbXtWQx6r4/OBWJ6gBOI1PDWfJNlEFvGMs/aIj0om1e9m/qSLyhi8gqovsdZWRBsa+Y1lZ1MLFtrsGfNh1BEIjR781WbDrrf1znx+1czck4wfPUvGwbjkq7E95LLQAmbtuZDROEIbi3NUHTS8gr8h5H1eGlr2/SgB02a5eIeZJgV6jVAi661og60V/hHJxuio=</enc>]]>
      </text>
    </request>
    <request code="Close" transaction="true">
      <text>
        <![CDATA[<enc>KN+eMXrkHu3hlHWG7ZEDVlk93zhQq/xL3JXKSIs4fnO6CqqsTAQuPw3ZgtMlw1JXJSobWW7I/X73zSC5S/jSK834kKrYSUuTsqit2MJuDscpWhrjw5dvkJCerpW5QAUj00c4y34hsHBxuU8o9rfdsaACQCFThaTDZVWHuAGb72FNShA7uh16i/Eu4jXZCsQutbMhhMHpvzT2gcGWEM5e9f6bxct8OqJwYdfCsQNp9CS9Q5ALJ6o21Q9Yq8+oMyIUeOkVyrQK0nSPXO8AcUt56/Rbq0aUB2mrxBupZF1pXT8=</enc>]]>
      </text>
    </request>

    &VoucherJSLoading;
  </script>

  <messages>
    <message val="msg1">
      <text v="Bạn có chắc chắn sẽ &lt;b&gt;duyệt&lt;/b&gt; các nhập quỹ được chọn không?" e=""/>
    </message>
    <message val="msg2">
      <text v="Bạn có chắc chắn sẽ &lt;b&gt;bỏ duyệt&lt;/b&gt; các nhập quỹ được chọn trở về trạng thái [Chờ duyệt] không?" e=""/>
    </message>
    <message val="msg3">
      <text v="Bạn có chắc chắn sẽ &lt;b&gt;bỏ đóng&lt;/b&gt; các nhập quỹ được chọn trở về trạng thái [Đã duyệt] không?" e=""/>
    </message>
    <message val="close">
      <text v="Hủy/đóng" e="Close"/>
    </message>
    <message val="approve">
      <text v="Duyệt" e="Approve"/>
    </message>
    <message val="undo">
      <text v="Bỏ duyệt" e="Undo"/>
    </message>
    <message val="open">
      <text v="Bỏ đóng" e="Open &amp; Approve"/>
    </message>
      <message val="inputTitle">
      <text v="Nhập lý do hủy nhập quỹ" e=""/>
    </message>
    <message val="reason">
      <text v="Lý do" e="Reason"/>
    </message>
  </messages>
</dir>