<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="q82" dirViewType="Grid" dirObjectType="Voucher" voucherCode="NQ1" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Phiếu nhập quỹ" e="Fund Entry Slip"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>

  <grids>
    <grid table="q82" fieldKey="id" order="so_ct asc" allowFilter="true" allowOrder="true">
      <fields>
	  <field name="ma_ct" width="80">
          <text v="Mã c/từ" e="Voucher Code"></text>
        </field>
		<field name="so_ct" width="0" link="V" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
		<field name="ma_job" width="100" hidden = "false">
          <text v="Mã" e="Job Code"></text>
        </field>
		<field name="so_job" width="100" >
          <text v="Số" e="Job Number"></text>
        </field>
        <field name="ngay_ct" width="120" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
		<field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="ma_kh" width="120" >
          <text v="Mã nhân viên" e="Employee Code"></text>
        </field>
        <field name="ten_kh" width="250" fieldType="EX" >
          <text v="Tên nhân viên" e="Employee Name"></text>
        </field>
		<field name="dien_thoai" width="120" fieldType="EX" >
          <text v="Điện thoại" e="Tel"></text>
        </field>
        <field name="ma_nt" width="80" >
          <text v="Ngoại tệ" e="FC"></text>
        </field>
		 <field name="t_tt" dataType="N" format="CostAmount" width="100">
          <text v="Tiền" e="Total"></text>
        </field>
		<field name="dien_giai" width="250">
          <text v="Diễn giải" e="Explain"></text>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="80" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="80" fieldType="EX" >
          <text v="Đơn vị" e="Customer Name"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" >
          <text v="ID" e="ID"></text>
        </field>

      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>it8RC5Ir2HRWFluPUm/BmFTnsUg029yOFVj1ewq4okXM/Pt+oR53S6VGmjbJYBh30fIK6K0i8Ljx8NWAr0E0FBl6KeHJeolCvAkrt7a1DprreAWrLd1TuCmo6SY236/k7A48q6tNsaTxJwaLO/ctBSRe6FCosibHtTBiC2OsvH7EZrPmhDMCgf5ZVcNJTIUv8SMm9MVbN67TAawjrMoydTm0tIxY1AdfnfK05/t9dXSwQCL8p0523OgOXqNmBOSgzJAmAtHAzsXiyZdg+I2vz/oYjcsw4Mo44egRlBJ7pJI=</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>GpT9qwyHLQdjfmI00p5Gv4EeqSVfJmCoZLL3p2N2pi+nuj551macfZFVVCQvT6tDRDiPzIwxeKb8Uf8eVCj6yKn1op43taii9/CpGrrpgYt54yiw/WAQztXFtIve6+GX2POh7WjgeT/nMt6I5yCABrVbQAiwoO1K5dKoA3K+mMSRZD3zOL1bClNgcBQk4CSPwefknh3mP0RxrLj1t1XEsBlXKsXAnd+YC1yOsm40Ye2m90SqSfmqWDQWCLqE/P4aRIq1k1kPQUxannusHb8jhMirzJzYbZabg67PxCcP1PAcEfd0Xp+fb3KPngSI/1TBnSS9JOZPZO1D+D8ua26WrpE+kEAIGsRu13pNp6XiMIHLGe4XzCqG6cU24fLJyOX9ns8rMU0WC6bavz9sRMKTnjV8XBzCoArW4RfoVcDncVzBlhDwaULXI84ZtYGi5q1XpAELEaxeiny8iZZTSeZviUOLmtCVk/6segovyAHTNvM=</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>hLiBLm3iF/aJj7eF2MoRKm6VZigGIj//YTnmjGMxaQ2gI62g+fP1CUZp58xxnaZ3ddNTMq5jjbrEIKvUqhoMkx43d/o3HcmyXHBzd1BswbMqlK5xwn3pocwN1EEZ5Zy6huTL3dPQ/h+PzCTl8TIjRMCk5nhfudoNXHsDLBvyGa6cw37vhrGBUphugrpq3qOq</enc>]]>
    </text>
  </js>
  <css>
    <text>
      <![CDATA[<enc>wWmvqZXYbLrRfwnztyX4ZY6SO6KpItcl49wVeT+y7qVIF5b1ajZQW7Csw+eGtdMnDS6WyVcR6tA8eprO+de3IHWsam4rEHqBOZVXOVEBEI2mi/rIvX7CMTy+d4E1KHRKhsN+UAShFEC5+gvHQqEcjUlzKApEKS8NIywx6HyXh8mvpJBkg4xIFsXcEyE8oaR/dV7eMAbDm9SO1zZrXFJSJT1BzeniLOVEeMA2zpDbLx41WjSMBNZXjw2hA3tkG3EjvVGIH2L+L39ZjZQxDzI9xK3tq6rX8nBMCxM6Zlwg0Bw216pgwByd4KxoOT8rJP1s</enc>]]>
    </text>
  </css>

  <script>
    &VoucherJSLoading;
  </script>

  <messages>
    <message val="DaThanhToan">
      <text v="Đã có chứng từ thanh toán cho hóa đơn này, không được sửa/xóa." e=""/>
    </message>
    <message val="DaTraLai">
      <text v="Đã có chứng từ trả lại cho hóa đơn này, không được sửa/xóa." e=""/>
    </message>
  </messages>
</dir>