<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
]>

<dir id="q82Close" dirViewType="Grid" selectMultiple="Table" voucherCode="NQ1" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Đóng nhập quỹ" e="Đóng nhập quỹ"></title>
  <subtitle v="Xử lý &lt;b&gt;%s&lt;/b&gt; nhập quỹ" e="&lt;b&gt;%s&lt;/b&gt; Advance Order"></subtitle>

  <grids>
    <grid table="q82" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true">
      
      <fields>
		<field name="ma_ct" width="80">
          <text v="Mã c/từ" e="Voucher Code"></text>
        </field>
        <field name="so_ct" width="80" link="V" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="100" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
        <field name="ma_job_ct1" width="100" fieldType="EX" >
          <text v="Số c/t đh" e="Order Document Number"></text>
        </field>
		<field name="ma_job_ct2" width="100" fieldType="EX" >
          <text v="Số job dh" e="Order Job Number"></text>
        </field>
		<field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="ma_kh" width="120" >
          <text v="Mã nhân viên" e="Employee Code"></text>
        </field>
        <field name="ten_kh" width="250" fieldType="EX" >
          <text v="Tên nhân viên" e="Employee Name"></text>
        </field>
		<field name="dien_thoai" width="120" fieldType="EX" >
          <text v="Điện thoại" e="Tel"></text>
        </field>
        <field name="ma_nt" width="80" >
          <text v="Ngoại tệ" e="FC"></text>
        </field>
		 <field name="t_tt" dataType="N" format="CostAmount" width="100">
          <text v="Tổng cộng" e="Total"></text>
        </field>

        <field name="unit_id" hidden="true" dataType="I" width="80" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="80" fieldType="EX" >
          <text v="Đơn vị" e="Customer Name"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" >
          <text v="ID" e="ID"></text>
        </field>
		<field name="id_dh" dataType="N" fieldType="PK" format="0" >
          <text v="ID" e="ID"></text>
        </field>
      </fields>

      <buttons>
        <button id="close">
          <text v="Đóng/Bỏ đóng" e="Close/Cancel Close"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="find">
          <text v="$FindToolbar" e="$FindToolbar"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="refresh">
          <text v="$RefreshToolbar" e="$RefreshToolbar"></text>
        </button>
        <button id="freeze">
          <text v="$FreezeToolbar" e="$FreezeToolbar"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
      </buttons>

      <script>
        <finding>
          <text>
            <![CDATA[<enc>T6YiQWV/dVWecHoTsRsQCc4sKqAzaQ8MTnPK26SwCO1fu8wxFdzGOoPUJylup2WuOsaHkFKRqn2qYbIhL1J1CC7cGyheJtrxxdS5/b1IP24kQgp1b/9EVb5ZwBZNzo4ErowlVuk5E9cw2BcmSnqDSO2RHn5tZtV1gqMFXDliuHbWLHGauhR4xNbgeIbZOVDGo1lTIrtiBH+ja39H6iQ3/ESp8wp4sU9FgpvOE58O5yNDMWtRoi+a4zTevZvDAaBbAHQV+SC7/PbjskCW9Y2xaU93uJws71C1R/DQGqV4/dbgom3FLFYM9/+icLUuZpPelEWkIS2eUzNyGxctv5ngkGLgYmy0857GkUYl6hn81gRlURDZ71gN45IClNYC108ySD/fAQZrT0/BtvDet+9VElVpy5qiZUaihNpcGKN/+JnPTfLa4zbsxHTMkKy/xUFfTQ1hr+6YFhb+AzEnMtYHNN9TOwzUhAtiirhkbfXWCF8mSpIrvyRpUVF4qjWqrKuB</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>RHvQFF3mi+iQ+U21Y8fNc2qGxVHBjNIDhUPGt5nd7QziG1TG7+h4e+aeWj0XWlzmo/qoF98PjJroCqhE4dT/pSlbDbgy7XKqX5ypOKIMRzNjylL2bQkR+sYcjk7kaiSgdkhldnMwghAaMDW+k3HELPNr2GXolGPEWpunfdWRTskqxD/l8NPQaBGlqdbV2A5+657NZFJcGjSdkbFvqLB0CAbDrCcexxMOvRoLKZ7ThbucgWTNaU7SFnNbPEMc17ryd2nFN3DP2afzP4ypeeGGjsTy0cq1+qUJfEFyHf0ICFiX20RKH3v//gkhJAS8Ydu3/4VmL4FU586FOQJe4t9HlWb21LajRJz4wQdnBy5Zp6/MTvmch+Vvk81Q3THs+IYa8euJ36x6FmGJpQj2ZAspSs9yR/ozvfH5hFOvtrG0li+npQO1SXq0pe+npz1ourHMSIIItuFsRWCtUB6ME+5PA+Frhpj3Pah8kipsQRmBDHiV2ue+a8h+ZAGPMCFTWawdw66pXNmbzfxqbS3/GE61fiJqmF6vKU8OumSwmHHnLxQokHWpOzPK6c89Uy5GbNjxh/lsYbAWbu9qgPImSripG/X2tQazfBwgmoLmNP80UbStB0Ravn8aOGFleGUmo7LXhG5eU4XBRXKQLNK60JDGS21SMZLzYVyCLW16ZudbMabTos1wcKTCGB3R+uMZN2atsT/iLu/9Vd5rv25mRhmQJA==</enc>]]>
    </text>
  </js>

  <css>
    <text>
      <![CDATA[<enc>wWmvqZXYbLrRfwnztyX4ZWvBnlYWH9u5j5YmFumARmFE3+6fHyBPhmBC3p7zfguMPQjJQ8+0ADrfMZD5TY5bby9kjfKZDNacocXAxWWt1xIAqZJlRAlpDd+LUV51x8iKWoBWb7oj9qbl3ntBBADKLkHleP8OBNYCpffSA9xB/tQeZhEQ1XD5NoH3wpPkjb8DZpdX9n9bv5hUmpk0iv8hTflf3L6l79RDNsx+AYfLpyzxbKxSmKotE9a4KTdF410XQ6JzvvMfW872B73eQ5tEVWuPJXvkfRRUNUHn+CaxSckD11znkXdFO3tryMNFpF4F5KScZijx23+ZmHXAxs3sjXtjPymgtI4NWb4ckEskTYo4Gc18wMUN2+xobkomV6Cn</enc>]]>
    </text>
  </css>
  
  <script>
    <request code="CloseDH">
      <text>
        <![CDATA[<enc>Kz4+sqAq7IhQ1dYu3KNmfAJhLWzr7/X8uq04m+/CiIr+N9H20bhMU6i/6JCwhdTKaSTX7c/kLLGpuxiS5UF97+9Tfm30Vw+/Dll9913q5yMPbpLua1uaqQ9vijv+wqKeJ7SP3baXQxYTz+zoCfx0AenkBs3j7K3h0duNQFFdt8hKFqRVj6xGUDMZ85IYquitcJbSmSHdbEFod8jEOlZxRslkAFRuO1zgfB4/4RmX9Rj/ZDJ49vXyUWgbP7EEHLbRTrbfAHsaA6bz5wOjR8+HsOgE4KzwZeUwXcZzlPeFLYQ8jlOS0GKkyPvqn9VBjqBqpVjsok7O/eoDtVgATfvzarjUuLqYbY8ZGJvbLll4tC4=</enc>]]>
      </text>
    </request>
  </script>

  <messages>
    <message val="msg1">
      <text v="Bạn có chắc chắn sẽ &lt;b&gt;đóng&lt;/b&gt; các nhập quỹ được chọn không?" e="Bạn có chắc chắn sẽ &lt;b&gt;đóng&lt;/b&gt; các nhập quỹ được chọn không?"/>
    </message>
    <message val="msg2">
      <text v="Bạn có chắc chắn sẽ &lt;b&gt;bỏ đóng&lt;/b&gt; các nhập quỹ được chọn không?" e="Bạn có chắc chắn sẽ &lt;b&gt;bỏ đóng&lt;/b&gt; các nhập quỹ được chọn không?"/>
    </message>
    <message val="close">
      <text v="Đóng nhập quỹ" e="Đóng nhập quỹ"/>
    </message>
    <message val="unclose">
      <text v="Bỏ đóng nhập quỹ" e="Bỏ đóng nhập quỹ"/>
    </message>
  </messages>
</dir>