<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="qlcuochopApprove" dirViewType="Grid" selectMultiple="Table" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Xác nhận đồng ý họp" e="Approve proposals"></title>
  <subtitle v="Xử lý &lt;b&gt;%s&lt;/b&gt; họp" e="&lt;b&gt;%s&lt;/b&gt; meeting"></subtitle>

  <grids>
    <grid table="qlcuochop" fieldKey="ma_cuochop" order="ngay_hop desc" allowFilter="true" allowOrder="true" >
      <fields>
	  	<field name="unit_id" hidden="true" dataType="I" width="120" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="100" fieldType="EX" >
          <text v="Đơn vị" e="Unit"></text>
        </field>
		<field name="ngay_hop" dataType="D" width="120">
		  <text v="Ngày họp" e="Issue Date"></text>
		</field>
		<field name="thoi_gian" width="120" fieldType="EX">
          <text v="Thời gian" e="Time"></text>
        </field>
	  	<field name="ma_cuochop" width="120" fieldType="PK">
		  <text v="Mã cuộc họp" e="Meeting Code"></text>
		</field>
		<field name="ten_cuochop" width="250">
		  <text v="Tên cuộc họp" e="Meeting Name"></text>
		</field>
		<field name="ten_cuochop2" width="0">
		  <text v="Tên tiếng anh" e="English Name"></text>
		</field>
		
		<field name="ma_lcuochop" width="120">
		  <text v="Mã loại cuộc họp" e="Meeting Type Code"></text>
		</field>
		<field name="ten_lcuochop" width="200" fieldType="EX">
          <text v="Loại cuộc họp" e="Meeting Type"></text>
        </field>
		<field name="dia_chi" width="250">
			<text v="Địa điểm" e="Location"></text>
        </field>
		<field name="linkweb" width="200">
          <text v="Link Website" e="Link Website"></text>
        </field>
		
		<field name="ds_chutri" width="250">
          <text v="Chủ trì" e="Chairperson"></text>
        </field>
		<field name="ds_nguoithamgia" width="300">
          <text v="Danh sách người tham gia" e="Participants List"></text>
        </field>
		
		<field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_tt, ten_tt%l from dmttsd where status = 1">
            </options>
          </viewInfo>
        </field>
      </fields>

      <buttons>
        <button id="approve">
          <text v="Duyệt" e="Approve"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="find">
          <text v="$FindToolbar" e="$FindToolbar"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="refresh">
          <text v="$RefreshToolbar" e="$RefreshToolbar"></text>
        </button>
        <button id="freeze">
          <text v="$FreezeToolbar" e="$FreezeToolbar"></text>
        </button>
      </buttons>

      <script>

        <finding>
          <text>
            <![CDATA[<enc>NKzHSnif1gX6sRSMfAYWnPyqO/kwqfZTUZyehCJF5srrqBuBnRJZ2zUG4qH1g+ODUo63EE8WrMAIUdK0dpuSAXL/w7sug4OUkgdQH1uljwxEeyv3d83U4VKttgK1ZpfXicFj+xEBkI/u6x2ViQ0kb3GLk+6eHDo5Xm5v3psb+9nixoMrfpydcDS4ieOypNKn+ggxh4pmykfkbeF5SUKzNKY160ncZd5k9D9/ncnvWr520i9MLOEaVJdnmfp4YzZZxsPyXx4KGsgmnw4ffzLR2Cs3usAD8/rSyUJFMbOrIrFF0v/LQ1dVSDeXq29oij+ZvqBXM4hDYXdNZLJc5hvs+gk2LgM2splWJ4a2X95WL85YVMxB7ahXqyM9/5Jh2EcnxUJYiIy8tIfYMU9j0cs3z0N2me4PRGgbFNHOS1FBsVu+XqQNWV56HYOIOfv7Et6o72b+yvjSjq3meagcF/jeIIhFImlxlVE/rRjoOmedYA3jrO3l5UiAZqUDuEqk74Hguri+CwR3mLaUOLpK+EtY8ji64lhCe8HboiVFP1p72JUvZfeq+SRIO0z7qKj8RjZgIgtbNCbIJNMqZi7y8RvqgRhgvo8+WIEwB/9FjBxxJqb3B6rcz5LjDpfhAUIU0VbEZbmynKT+pQiYcfSp03io3wUsKzXMHQj3Y+vLzHVCR8A=</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>uc4lz99o7HEebCtoUW66yX+k1QZImp66+sz3luw53OI5FiVZNZHknPmPKbEVcg4HGKAetbr9OZKSFhpK9PcZXGWzIIY9zLn8noqjjNRmzCyKSFV06SR/F8lOWkmLN+sIsbnAODAi1+SqYlvJ+9XNL2eCyYKqlq/qvYuMJMVH28Mq5Vu6s5RPoNar5dq9Pw/ud7V1SB+ZworgLYZ+wM3dNDejFzKP/43eW2PS9aWmgLwCsLSzTEPfG12KAmBDrLBct6D6k9lDtQZYjkytIFyqGzSDkq9KBqqR2bSATiXVnDYVPtpJi4oE+oz6SAAYg9KLTS+skR1cWnIf9rQafY2B1eB/yrLCQ7GVfEbkLO4UbYnK6uFbl7qyYS9ehQKVVOBlhmN3E3YVw1Ov2ti8+cwT0dwbYw3HAu4QTHU7yUf038Dv5sGhy11mQRdvVxyB9ikmPR3wOB0dlAK5s9aPPPhtyJvkNa3Kzs4SgT2PNqhnamMBZ8xMBbh1wJmwCmVikVc71PjYCcyhd9kPYQH+zFxDqqa1wskqZTgDhALnlEpFteB04Zn5FXCJ4QYtrwC4A2ZH8b2pN//2rcyvnxq5wY/XJa79Q9XE5daUKmyykUOKihIbj4wDg1BgzuMU0vQJZPQyHz7cNnE0KSIAIOgUKNxCtd6OzhCYKVAGExT2WVVZrZiY+bu+JXPVeduorLlTWtdzOrKFo0KbCgqehTM3r72DowMUepGlfBhl2p6JUBldR7mV+dJqRCN+KJ260N2t2Pd4wtn0Bc4lR/kuzfLJ8D/5xg==</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
  <script>
    <request code="Approve" transaction="true">
      <text>
        <![CDATA[<enc>ZAOp6ChwbpDXlq55Wtc25hVnzimEbdEVbZZ/He3SjkSDSBuAsrNacAd+RPuWaa/spUjzsMJtQOErXQW1KX4pV+ye0DnbokkPCUCw1+j1zCng3ZZ7M4FItfa1o5QVtrmPEY0d+WDAlP66qMQ4ed+p73Adx9vibMAqfLyTw8WfEj1kBDqmcqfX++E1gd9KJr8x7dhaj/DA7jN9wOKDYXqmgRPEEw3AmJW2M9O+pPPoc9DWysf09LvHYhzvQBQ6NSkyDP69U1qzDOPrk/ecImh0SWUz4jvSbVWPjWaKs6tN/ba6Jy5Q2DFX2AlyhcGss+K1G+dqbd8Dj4+y/SnYlVnjsXB7X6P0y7mYCMD91N16acT6gUoJ85gyl4HkzVC55n38jrl5xR1umSjqG2VYthNHPQ==</enc>]]>
      </text>
    </request>

    &VoucherJSLoading;
  </script>

  <messages>
    <message val="msg1">
      <text v="Bạn có chắc chắn sẽ &lt;b&gt;đồng ý&lt;/b&gt; các cuộc họp được chọn không?" e=""/>
    </message>
    <message val="msg2">
      <text v="Bạn có chắc chắn sẽ &lt;b&gt;bỏ xác nhận&lt;/b&gt; các cuộc họp được chọn trở về trạng thái [Chờ xác nhận] không?" e=""/>
    </message>

    <message val="approve">
      <text v="Xác nhận" e="Confirm"/>
    </message>
    <message val="undo">
      <text v="Bỏ xác nhận" e="Cancel confirmation "/>
    </message>

  </messages>
</dir>