<?xml version="1.0" encoding="utf-8"?>

<dir id="reguserinfo" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Khai báo người sử dụng" e="User Maintenance"></title>
  <subtitle v="Thêm, sửa, phân quyền người sử dụng..." e="New, edit user..."></subtitle>
  <grids>
    <grid id="0" table="reguserinfo" fieldKey="user_id" order="user_id" allowFilter="true" allowOrder="true" key="(@@admin = 1 or user_id = @@userId)" >
      <fields>
        <field name="user_id" fieldType="PK" dataType="N" align="Right" width="40" filterType="Code" aliasName="a">
          <text v="ID" e="ID"></text>
        </field>
        <field name="username" width="120" filterType="Code" aliasName="a">
          <text v="Tên" e="Name"></text>
        </field>
		<field name="ma_so_thue" width="120" aliasName="a" hidden="false">
          <text v="Mã số thuế" e="Fullname"></text>
        </field>
        <field name="nickname" width="250" aliasName="a" hidden="true">
          <text v="Tên đầy đủ" e="Fullname"></text>
        </field>
		<field name="company" width="250" aliasName="a">
          <text v="Công ty" e="Fullname"></text>
        </field>
		<field name="phone" width="300" aliasName="a">
          <text v="Số điện thoại" e="Fullname"></text>
        </field>
		<field name="type_member" width="0" aliasName="a" hidden="true">
          <text v="Loại thành viên" e="Fullname"></text>
        </field>
		<field name="ten_type" width="250" fieldType="EX">
          <text v="Loại thành viên" e="Fullname"></text>
        </field>
        <field name="parent_user" hidden="true" dataType="N" align="Right" width="40" filterType="Code">
          <text v="ID" e="ID"></text>
        </field>
        <field name="parent_username" width="120" aliasName="b.username as " fieldType="EX" hidden="true">
          <text v="Cấp trên" e="Cấp trên"></text>
        </field>
      </fields>

      <buttons>
        <button id="add">
          <text v="Thêm (Alt + N)" e="Add (Alt + N)"></text>
        </button>
        <button id="edit">
          <text v="Sửa (Ctrl + E, Alt + E)" e="Edit (Ctrl + E, Alt + E)"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="permission">
          <text v="Phân quyền" e="Permission"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="refresh">
          <text v="Làm tươi" e="Refresh"></text>
        </button>
        <button id="freeze">
          <text v="Gim cột" e="Freeze"></text>
        </button>
      </buttons>

      <script>
        <query>
          <text>
            <![CDATA[<enc>7Hi7eYdvQp515CDiR1EyQ7yRiLG0DZf2CR5SwH7hLl0T5ApRv96XnVx8V+LrIfxGO9OVnvKmTZr0g2frYex8rE3Awj5r5SFa5+jx06ErZ09nKgRdtM5i0vFw6maayNPkCQr0WiazvYUoGmounY+UWJU1vZR4R7cMvCwbBRjdLklhsWV4XUbeLZ6qL3UngwBLK5S/BO3c5NCq6WqhQpNdwvuKho7NZNXqXbay9x1M3a/LmtmuaDpO4aAhqCxW+07eg3mrImduPFraFcXIUgQr49sGqKlDNbwwQm6jVYpHyDDPDiz0OD2PKkt7ft2o9Z/g</enc>]]>
          </text>
        </query>
      </script>


    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>1UXiXCk/W3rhTLc5cbTz7OY+WZHKvYcGuq49p/WaVssOkMDmW4WZqLBA+bAQinneGUvYd6AjqJK0+KsnMJtePu4MqEA4JXEgisHlX9jG0nJ/zp0dtUhHnZ0AHQneSCV1XyrJH4L9EF5/SXfqdx89wx12H7YLGMgaX3fD8xZolUtxdNZ96WhMOSARBTXUEN33GX/9hNY6YNjuHUsNzyKXIcsXtlvuLt8sQciHpDzhRItlD//t9nDSn0Y8HDOzCZ+WV/hEGIcLZUcuhjNBfY6iTi68eB3APXS79GIYvWNBOQ5Nye6jB/bgBLcjVeiDz5Oz0JFvaeNXGlxhzQf28kZBUSSQb40i7UlKXODmlsZU18zHaqyF8Frdi8dVS5ep8Md2xHRqCNkN3L22m7z7mFRR1UYmMqX++LXqzVB510Aw15phpGursO7/9Nc1lrSQoVitrLlQXaGxE4+gDg0nhF5tM+Z6bg7oPli9P+GN++aNsMCvfK4unCbIJqPFZQzXIr4ppaMqRRSW5eY2TqGUpGDGkA==</enc>]]>
    </text>
  </js>


  <script>
    <request code="permission">
      <text>
        <![CDATA[<enc>ByAnL5Y4HosYibrUaHDgBldG9vmxQFq36leGwJYN9eDJILwNnZHyfdPB80dGNExCmzfTiSKRAGx8/1RXMr+7mDLeFOctxzDioPGa7jeOVuzygiwC1nQk838G6ri4G7eWgdBL1+ZA7HcRIkJ2Lv1D6pscNdLB9kkHAWAnpaBbxhJj/Ly9WmXY9q03Bf4pYEpfB4hMOwEzJMnrY69wk3dfFnpPBRVEh35shBiZzpJ4wZg=</enc>]]>
      </text>
    </request>
  </script>

</dir>