<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridReport.xml">
]>

<dir id="rptcpdt" dirViewType="Grid" dirObjectType="Report" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Doanh thu chi tiết sau thuế" e="Detailed revenue after tax"></title>
  <subtitle v="Từ ngày {ngay_ct1} đến ngày {ngay_ct2}..." e="From {ngay_ct1} To {ngay_ct2}..."></subtitle>
  <grids>
    <grid>
      <fields>
		<field name="stt" width="70" fieldType="EX" align="Center">
          <text v="STT" e="STT"></text>
        </field>
		<field name="ngay_ct" width="150" dataType="D" align="center" hidden="true">
          <text v="Ngày c\từ" e="Customer Code"></text>
        </field>		
		<field name="id" width="100" hidden="true">
          <text v="Id hệ thống" e="Customer Code"></text>
        </field>
		<field name="ma_job" width="100" hidden="true">
          <text v="Mã Job" e="Customer Code"></text>
        </field>
		<field name="so_job" width="100" hidden="true">
          <text v="Số Job" e="Customer Code"></text>
        </field>
		<field name="so_ct" width="100" hidden="true">
          <text v="Số chứng từ" e="Customer Code"></text>
        </field>
		<field name="ma_ct" width="100" hidden="true">
          <text v="Mã chứng từ" e="Customer Code"></text>
        </field>
		
		<field name="ma_job_ct1" width="100" fieldType="EX">
          <text v="Số chứng từ Đ/H" e="Customer Code"></text>
        </field>
		<field name="ma_job_ct2" width="100" fieldType="EX">
          <text v="Số job Đ/H" e="Customer Code"></text>
        </field>
		<field name="ma_gd" width="100" hidden="true">
          <text v="mã loại" e="Customer Code"></text>
        </field>
		<field name="xnk_yn1" width="70" fieldType="EX" align="Center">
          <text v="IM" e="IM"></text>
        </field>
		<field name="xnk_yn2" width="70" fieldType="EX" align="Center">
          <text v="EX" e="IN"></text>
        </field>
		<field name="air_yn" width="70" fieldType="EX" align="Center">
          <text v="AIR" e="AIR"></text>
        </field>
		<field name="sea_yn" width="70" fieldType="EX" align="Center">
          <text v="SEA" e="SEA"></text>
        </field>
		<field name="orther" width="70" fieldType="EX" align="Center">
          <text v="ORTHER" e="ORTHER"></text>
        </field>
		
		<field name="t_tien1" width="100" dataType="N" hidden="true" aliasName="c">
          <text v="Cost" e="Cost"></text>
        </field>
		<field name="t_tt_tien1" width="100" dataType="N" aliasName="c">
          <text v="Cost" e="Cost"></text>
        </field>
		<field name="t_thue1" width="100" dataType="N" hidden="true" aliasName="c">
          <text v="Tax_1" e="Tax_1"></text>
        </field>
		<field name="t_tien2" width="100" dataType="N" hidden="true" aliasName="d">
          <text v="Sell" e="Sell"></text>
        </field>
		<field name="t_tt_tien2" width="100" dataType="N" aliasName="d">
          <text v="Sell" e="Sell"></text>
        </field>
		<field name="t_thue2" width="100" dataType="N" hidden="true" aliasName="d">
          <text v="Tax_2" e="Tax_2"></text>
        </field>
		<field name="t_tiench" width="100" dataType="N" aliasName="b">
          <text v="Chi hộ" e="Sell"></text>
        </field>
		<field name="profit" width="100" fieldType="EX" dataType="N">
          <text v="Lợi nhuận" e="Profit"></text>
        </field>
		
		
      </fields>

      &DefaultButton;
    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>mZtqOcs8LjvtlJPAC7NnQ9pAcWfOajRPkS+nYi7yF5+iPkdr08pxx5+Q3MX2eRepTwJb2umxkhnzRCVKNETaMZyibi6621Rb7IyaJrI8NXwhRi4M3/aJTAr8KoNUHf4a69jUeHX+G4++lBIlkgFIyCt7QijCd5HYorcmD1G46IbKEQlFtZKPSeYNddqF6/RsvhDfevpWxxmuWzh92EXD6+Y5DzbtPjFlKPXRQuNnuQc=</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
  <script>
    <processing>
      <text>
        <![CDATA[<enc>912QYdhqFaoxmTwymwtxUk12vSAdsEO7hiaIEk+OlZ7hX2SLkkbq3pADVNz5WD26B89SpHoawmCQYb7wQ7I0ehSPww8JNst2R2gC6n1Jz0kdUeuvCczqmxG2juGMQAB5njXGYdczovT/CH1h7ADZJy65F2S8wULGyQ2QOMfWakE=</enc>]]>
      </text>
    </processing>
  </script>
</dir>