<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucherNotPrint.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="s12" dirViewType="Grid" dirObjectType="Voucher" voucherCode="YG2" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Yêu cầu báo giá hàng biển LCL" e="Request LCL Marine Quote"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>

  <grids>
    <grid table="s12" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true">
      <fields>
        <field name="so_ct" width="80" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="100" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
        <field name="ma_kh" width="0" >
          <text v="Mã khách hàng" e="Customer Code"></text>
        </field>
        <field name="ten_kh" width="250" >
          <text v="Tên khách hàng" e="Customer Name"></text>
        </field>  
		<field name="ma_noi_di" width="120" hidden="true">
          <text v="Nơi đi" e="Origin"></text>
        </field>
		<field name="ten_noi_di" width="250" fieldType="EX">
		  <text v="Nơi đi " e="Origin Name"></text>
		</field>
		
		<field name="ma_noi_den" width="120" hidden="true" >
          <text v="Nơi đến" e="Destination"></text>
        </field>	
		<field name="ten_noi_den" width="250" fieldType="EX" >
		  <text v="Nơi đến " e="Destination Name"></text>
		</field>		
		
		<field name="ngay_hl" width="120" dataType="D">
          <text v="Ngày dự đi" e="Effective  date"></text>
        </field>
		<field name="ngay_hld" width="120" dataType="D">
          <text v="Ngày dự đến" e="Expiry  date"></text>
        </field>
		<field name="ma_nt" width="0" >
          <text v="Ngoại tệ" e="Currency"></text>
        </field>
		
		 <field name="t_so_luong" dataType="N" format="FCAmount" width="80">
          <text v="Tổng số lượng" e="Total"></text>
        </field>
        <field name="t_tong_trong" dataType="N" format="FCAmount" width="120">
          <text v="Tổng trọng lượng(KGS)" e="Total Gross Weight(KGS)"></text>
        </field>
		<field name="t_tong_khoi" dataType="N" format="FCAmount" width="120">
          <text v="Tổng Volume" e="Total Volume"></text>
        </field>
		<field name="dien_giai" width="250">
          <text v="Ghi chú" e="Note"></text>
        </field>
		<field name="status" viewType="Combobox" inactivate="true" width="120">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="120" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="120" fieldType="EX" >
          <text v="Đơn vị" e="Customer Name"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>vyZSTuDqaYKk9tl6j7Wt/tiJjapmAHHOlaG4xQJAe3abMWluLv6wje+YxlAMo3+/cvP9WJgvVFd41MynNBj5S4Z8opve30REF5WOGiKWoz6O4Z6x7rY/T88Qzu4GyyFEl6uoh0n8n4nz3Xk1dbAqRoO2YM2lpkMrGg4v2P33CKL2npOfztxgesnZiHcOg+z8A4YGUJttANaG1tUg47c+65fl9Z1GHum6ABwyL3Vxu8ogIbNGJbydOCk3Ug+AYr6Yx9xIV0jbwe4M7HMtmoRM8OzdMzn91f3djrgPxaeCMg5Kkt9ChO+uJfRsfBLrE+roKp2S5CbO3pUHkJdQEVxNkr+EOzkpsfVCtzSMy9r7Hmc=</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>QNehOSXLCQO5c8u/iW/IcCearURw40CoBnJl1ogdY9rnrPPpZe12ScF5l52c2FGCgEoFgtjVve4TznQX+8XjBoaIpi1HHbhKBz308k7XjjUmNfSuXCKEPo+N/FSYV9Jj8D2eiRBzMtlTL0U5lBgjOOaTaujZfrME/8pIMa4CPBg280TGuM1j3k10oDh9rSKjs6s4qSBq0Ey0h3krLfmktKLhZwq95w1zeR6SpOKu+0EeJSyWad7Y8i5rBSdcSRkz5CEoVrLMcutzw5JCW9ett3wOhWGq45ZpvK9aK4+ltD4RCEMty2DXYMm8i6O6sYbk6gMrU8SPaCYBp5iW13YexjSch9JII8E1AXD8MUgdl7iR22fCWkf1lu0dqnyiWZHeYeFCfIHc3T0tQHqMkZC2qp0uPagC16Q6TE6MzV4O2HBHvLuBl0f7j2MprUy5Q0L1rt03uBkG/MMXkRJdcpMbIDinDzyv/Ve56quTnOHDW5G9mP9mBR10ED1+gT/6wU7RYO+ATmaRItSCBS+DhBGiHlGBQeOnn/1gjhzBEfeyFLNS4rBdJHaHhI4wRUtPSv+ZBBFeqIM96HTLozbxg9nDKe39fZsgZdupZmPrHpD2C4Eyw31uLwYlcND24HWFd3MmuKVINeGQRBsuWALGTolKXqcvgIZk0rl2OYpFUFuqJKOznlzU2992n9NqsBmx0XTF</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>jzcoae1D7/AzsY7GhcCcRds+ZGYWFizzcBTraVYtXpu9V5Gvhb3mRDJR4SIJdt5GCLjJjD1UtjpWx7g/D56t4PT+Bmrz5mDK+WYIobAlmGWfrXWGhFOZVi8Qr47igwUNjh7ByFE8eJINeQLrLycs9/1jaL/8A8bziKuFUdY6G0WbI023ea/4hsQ1CEYIMq8fmBiyZC5TaSgrN63RrGnAQQ==</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>

  <script>
    &VoucherJSLoading;
  </script>
</dir>