<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucherNotPrint.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="s313" dirViewType="Grid" dirObjectType="Voucher" voucherCode="BN3" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Cước vận chuyển quốc tế hàng không(AIR)" e="International Air Freight"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>

  <grids>
    <grid table="s313" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true">
      <fields>
        <field name="so_ct" width="100" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="120" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
        <field name="ma_kh" width="0" hidden = "false">
          <text v="Hãng vận chuyển" e="Carrier Code"></text>
        </field>
		<field name="ma_phi" width="100" hidden="false">
          <text v="Mã phí" e="Fee code"></text>
        </field>
        <field name="ten_kh" width="250" fieldType="EX" >
          <text v="Hãng vận chuyển" e="Carrier Name"></text>
        </field>     
		<field name="ma_noi_di" width="0" hidden="false">
          <text v="Nơi đi" e="Origin"></text>
        </field>
		<field name="ten_noi_di" width="250" fieldType="EX">
		  <text v="Nơi đi " e="Origin Name"></text>
		</field>
		<field name="ma_noi_den" width="0" hidden="false">
          <text v="Nơi đến" e="Destination"></text>
        </field>	
		<field name="ten_noi_den" width="250" fieldType="EX" >
		  <text v="Nơi đến " e="Destination Name"></text>
		</field>		
		<field name="ngay_hl" width="120" dataType="D">
          <text v="Ngày hiệu lực" e="Effective  date"></text>
        </field>
		<field name="ngay_hld" width="120" dataType="D">
          <text v="Ngày hiệu lực đến" e="Expiry  date"></text>
        </field>
		<field name="ma_nt" width="100" >
          <text v="Ngoại tệ" e="Currency"></text>
        </field>
        <field name="t_tt" dataType="N" format="FCAmount" width="100">
          <text v="Tổng tiền" e="Total Amount"></text>
        </field>
		<field name="t_ban" dataType="N" format="FCAmount" width="100">
          <text v="Tổng bán" e="Total Sales"></text>
        </field>
		<field name="dien_giai" width="250">
          <text v="Diễn giải" e="Explain"></text>
        </field>
		<field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="120" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="100" fieldType="EX" >
          <text v="Đơn vị" e="Unit Name"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      &DefaultButton;


      <script>
        <query>
          <text>
            <![CDATA[<enc>+cqRnw3xIxP6k5U1nfeaCMwlsQu+OGxGSRjB90KOw59LZdXr6Jo21MzczgeqcOcoTFqrvPZdoq3slXp8RItdFl6sDjggaLv/MwEUPc+QA1Kcbw+l5a9c19xjEVbw5JRDqlFkufI90O9XKxZ7VIwko8DxQAklZhjnc8Iq75QL6Vm8P/q88TOvLUdICkVn+zFyZhgSyJujT0JE6PsM4Tx1rKpPQeeQ6pi8pAh+Or3eYm8LIkXDyQFxFbafDUIL5MM2filMW8NaCTJK3g7kI+1D3eholjlEVAQ/RdRwijYbLPBQtIXUDJqPtJIoSW6vznKG2gdtNXw9OEMiwbPH7aIH9C6VPSVXzvO2N+RIycfrgmjJGYXkWQsQs1C28G8jAVxJ</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>e7BEqTAcxs+ORk3tt3CjsF7lrqLzojCEgRi5pTzFc2DUCG2jDbf5rplmGp2iFh7uAiaugZzLL+DQUfmY5xS+dtAR3wNBggDt+Nq4wA1LCkBnLk7B1I8wMlxrgbkRJctcnJSSQvMB79O8j8UhE2yw7CrbOlFI7nopXegv+ddzPzIZ7kndnA2U5ZCEC3t3/8iMJIchVmPy7J3qWSLeNUqGpPEOkewGpmWpDZQNzitA2D+vvz/rtG0biEvGntrTg07bXEvETSlDjr1PSf5oDnruv9AW6dNu+fFOLtsOGiVr9F3lxRbzkiBVHDQHdTn7KuEyFYXS2hPqD7HZ+lZVhBLDPGwNJXAB3J2ddTvwAr87WTTOvOcqO7RyxALHXYIyCYzqFt/0eqoaPSPiAethyaVBsOm9HRuw17mw1YoWl2535QcKNwVUAO7C4bnPZKmCeX0dedjQggaZ/sHqNHB0LSOAK0OPqoJqK/x3RC0mJAVJ9fTwp29tJCfeq7JMqyUePBEBPSAokHNl2teCrYjVd9VntjsIagES0qToSl1/w7+vd/RE36U6QXoaaTL7x+vArAhQtLl0u9SD2bdfd9D7t+oUlX6T+fqeGa67JQGaSJMLS+Y6POHXVk+HyOmWzmVqJjzx0WFDAgq77MZyheugmvgXMK8yRZqugMCe3bs917pRxdUu9GCijhHqTk6q918HI3df</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>jTwWP4URN13fjiNnm/IWVIotII0c6ObWRSx/mS7Kj/UPDUpGFwICIqmPx4M2ikBDOrYi6ikmumfb7tn2/Td8RslYgmn8GsfFkEy+2nzw+cMD03y57+cvCOpm0jZoEBoeVZGgplL1kVUnRB37num/J9gGpncpEz2IDNnGpvSHOv9sKgvJauedviV3LlHM9R1mwWst9yLxbW0hD48U44DvHQ==</enc>]]>
    </text>
  </js>
<css>
    <text>
      <![CDATA[<enc>6xSGli4Wotw59iMlYNIY39BqoUr0dvPifiSg6AU9azEBDWoH1wuSqhMgAU8g7ZueXYxFl6C4F3zl+jeqH70TOY7s4YMemUtTL+n9QIc5jCx3dEGsELi5BYW6EvBaQOoGyQs6SEmPSbZsIi3sSeFx3lfhSfCdZg4ZgK6xvC7OpK8KfCWFAIXXLVMiF6EpXKCIiqyupTGDBdKkxVgsrYxaeGX4YDQmNouKV5Mc42FazvMbbRDJGHqmMZXvsJb/pcJe8e/+l9s+oPZT6pVJIrDaS+VwWTvc+k26w40+dBlyKu+18PjLzPO1FHiGqkERPIKJ</enc>]]>
    </text>
  </css>

  <script>
    &VoucherJSLoading;
  </script>
</dir>