<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="s314" dirViewType="Grid" dirObjectType="Voucher" voucherCode="BL1" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Phí FCL theo cảng" e="FCL Fees By Port"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>

  <grids>
    <grid table="s31" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true">
      <fields>
        <field name="so_ct" width="120" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
		 <field name="ma_ct" width="0" >
          <text v="Mã chứng từ" e="Voucher Name"></text>
        </field>
        <field name="ngay_ct" width="120" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
		<field name="ma_kh" width="120" hidden = "true">
          <text v="Mã hãng tàu / đại lý" e="Agent/ Daily Code"></text>
        </field>
        <field name="ten_kh" width="250" fieldType="EX" >
          <text v="Tên hãng tàu / đại lý" e="Agent/ Daily Name"></text>
        </field>     
		<field name="ma_noi_di" width="120" hidden="true" >
          <text v="Nơi đi" e="Origin"></text>
        </field>	
		<field name="ten_noi_di" width="250" fieldType="EX" >
		  <text v="Nơi đi " e="Origin Name"></text>
		</field>	
		<field name="ma_phi" width="120" hidden="true">
          <text v="Tên phí" e="Fees"></text>
        </field>
		<field name="ten_phi" width="250" fieldType="EX" hidden="true">
		  <text v="Tên phí" e="Fees Name"></text>
		</field>
		
		
		<field name="ma_kh" width="0" >
          <text v="Đại lý" e="Agent"></text>
        </field>
		<field name="ngay_hl" width="120" dataType="D">
          <text v="Ngày hiệu lực" e="Effective  date"></text>
        </field>
		<field name="ngay_hld" width="120" dataType="D">
          <text v="Ngày hiệu lực đến" e="Expiry  date"></text>
        </field>
		<field name="ma_nt" width="0" >
          <text v="Ngoại tệ" e="Currency"></text>
        </field>
		<field name="dien_giai" width="250">
          <text v="Ghi chú" e="Note"></text>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="80" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>RGWXZxGpGTx9kn0HjvseHhWk1czymWva+qkPBHAiTI+sbhjPx6sHHkGXQd8vYZ0h1Rdl/HDkXjDUpkBStNUWVK/1ndQwjYCsQlviOWrfLLdQ0C9npYu7F2Vji01eOTV+MFJEfV+bgwWjuvPSjGTTK9b8w2+iv3LhtuHHyp1ezV60QbR+yoVZnyWw1PqMivDynKP5FXtE7M5cquVUytEzdySlrXd6l9ZWJI61sgLSHrwqoaz7Nf8kC3JKrnP6Fu0A04ahbAumPsYkqvG0TuCC2/ZtXt3cWsyXqj7y8aFT6+3uLnm/+H8iV+jHCkr2NDSDjkqbV03wDGIIJv7SheBZU9Iw4z8ZGlFGsxbe1GH7b40bslhvx0aWEIYutMhns3xg5x/RoztIVmWXlxf2EeTqFA==</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>TE4cHw/1yyUxTheD6TeNNQPPmopSWGhBJG1l76he5qfMzJ04PUhQ6b60iJv74UYVdgVTNvsXdA52rZVkM442f2t9Y0W6/HwqeLFLqGR7MXFy07RBs8Zc7qnePslMxRprHK11xTajeKqH4krwftaRUakrmDSnmTCaX0vy52P1dfLUDaaF/HV8j7WeVpczxGuecyaJSK4jr8mm1BHTXSGbdZWMlHkndSUhFkzjcvBVKkfRpcCUs50v3wY/8xelKA6d80A8Qfo97eI4vpWGG8vcOySTiZMcePNl3QrIPOvCeneXjAMk6MpacPk0gMM7UcHB7WwMsnHs4mjSMxyJe1/Dk1P2J6iiKJqFtTJkVyo/NfJ8uozBX6zPawSw/P0EKg+XqCROJvlMttXMVA7FFF8Di2VawBpMg8BS7/+BWCuANDeWjLzvavt2cFPMrG7SEBduKoby5yEfC6csgtxLNXY1Pl9EXJM87Jiy8MGpAy2vXplJkUtcFdE2Eg1jqNw96kA1tEzv6N/gB8VdN9gw6MdoOu0EFieCxAof1+CDCxFAUx9hxwBR34Pi6VLLvVoEqcIP6SUbnTugEqKmJwmDnx12c+2hR+jRy0AaUF5VR0mQtFlehvg99kxhyKMAFIrfuuiIfiITeHTe1sv5nJ5MfBPtyVRxdJyjeBqItH5QNv193fA=</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>B3vwoV4prYvzOacbKQoWC7HeQtqx9dkRP2JCE7HIhZwMTTaI0OREP2jsF8HAEv1HqMzrU0FLJVXqXQgoPh/P2Y+5quVFASp2CrVnq8zqHgMH4AgsAKGVclIbmtMoJPkZ889I96IuIEnmIRUgrps1ljw89RvOsnbvcl5fMDD6JpnTWOKH9DREd/UgMPxwLniIhv+8nrjlrtXv1tg9iTWi2g==</enc>]]>
    </text>
  </js>
<css>
    <text>
      <![CDATA[<enc>6xSGli4Wotw59iMlYNIY39BqoUr0dvPifiSg6AU9azEBDWoH1wuSqhMgAU8g7ZueXYxFl6C4F3zl+jeqH70TOY7s4YMemUtTL+n9QIc5jCx3dEGsELi5BYW6EvBaQOoGyQs6SEmPSbZsIi3sSeFx3lfhSfCdZg4ZgK6xvC7OpK8KfCWFAIXXLVMiF6EpXKCIiqyupTGDBdKkxVgsrYxaeGX4YDQmNouKV5Mc42FazvMbbRDJGHqmMZXvsJb/pcJe8e/+l9s+oPZT6pVJIrDaS+VwWTvc+k26w40+dBlyKu+18PjLzPO1FHiGqkERPIKJ</enc>]]>
    </text>
  </css>

  <script>
    &VoucherJSLoading;
  </script>
</dir>