<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucherNotPrint.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="s321" dirViewType="Grid" dirObjectType="Voucher" voucherCode="BL1" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Phí Local Charge Cảng Xuất FCL" e="FCL Export Port Local Charge Fee"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>

  <grids>
    <grid table="s321" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true">
      <fields>
        <field name="so_ct" width="100" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="120" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>	
        <field name="ma_kh" width="0" hidden = "false">
          <text v="Mã hãng tàu / Đại lý" e="Carrier / Agent Code"></text>
        </field>
        <field name="ten_kh" width="250" fieldType="EX" >
          <text v="Tên hãng tàu / Đại lý" e="Carrier / Agent Name"></text>
        </field>  
		<field name="ngay_hl" width="120" dataType="D">
          <text v="Ngày hiệu lực" e="Effective date"></text>
        </field>
		<field name="ngay_hld" width="120" dataType="D">
          <text v="Hiệu lực đến" e="Expiry date"></text>
        </field>
		<field name="ma_nt" width="100" >
          <text v="Ngoại tệ" e="Currency"></text>
        </field>
		<field name="dien_giai" width="250">
          <text v="Diễn giải" e="Explain"></text>
        </field>
		<field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="120" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="100" fieldType="EX" >
          <text v="Đơn vị" e="Customer Name"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>KB8xqdyii61Ha3yaQfUGVUlIMCJDfDFgJnF2Ocumrst3jH6OeQT0l2BIduWsiZSQ1BTtrNCrybrzxgvqfkE4X1X8aJu+bQoKxdRae/k1c7TcuCJNOKmf06HgPZmYsG1yYk3wOKtpEgb4z6wQ9QYFgt3trccoL+fXqo7P7qWn+UykuDCJnTvdognjul349AhoWSBpKauIXwPdrpAOUL8SgHIEfpMNILUgc0aqtNEnONgqS5aibdkluNb2k5bJ2gJYUXbUwvEmqNLVcb5rczRaj5gWm8x4CITqEaNQSY07cIcI/EaISHZ2GVHMk/o7NVbz</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>lfcTso2MbCUpDyZ9bhoHEyz93vRyTQnyChyRkyv0kmR1Ws+gVHbCFZWesaAJCWJ4kOm0xwfMjHGN8TeyzlTEThLyf8YMHedsl/8G5+N/c+8t3UrbOgQG856rpaFSGbBI7vAXLN+pW81FWXbqUkYkhczwxMQOcw3j3Wbsa8/JQOoxca0z6jB8Yt84qXWl+7kbncOm/I+TJalBvmnGvZkeceaAtkN18JQkUQwPsr0rE656QIpiDAg6qBJyVuEmB8fwPwPrtem+KAlOGfXTxfaDnUKgVzun3T2jRqZok5xwhjOkJ2JBC43DGCGC+TmWDwUOfIzP3+R48jiZ5MFg6Q9e9tAiN5mFrKJfDWGpLe0kfGZgnUmw6aUIJMCOvcLaEFRCeralIMdTgNXan1BMPitFkRRt3SscZ6mdWB1LK+53b4dyp8BZ6Z78fU8IhbMGNjYe/bxN76sdvQzupu7ezaqabHiH+kqDFk+3M/TnmFQwCGAmgRofSDP0NLafDuEuo4W5H7NkwQFKeqrYn8FtrHLVJRhvdn5JCsOEKLYghfZMXCLB4SDMM0SLHtho/RzSRmWKFbQOFOM8rYSvZz8M2vYiHInHZzAVg15RG6IW59mfvuEooV40JHr8FmsNQPrRxdtm5ciJaChKyeauoedOn3DCKZuPfM9yhXG5bDZhOkRvlKw=</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>B3vwoV4prYvzOacbKQoWC53R/LFOlNuZjb7v9RQjlAiiQzOQYw2rLl55X8rZYQ4qSQr1GO+XgcWb+HHEL4VEDou3baeTjVcPInbtya1TX+GhZ7w49nhuZCbM/3w1R/phCSZXKZ3uJXlSfVQxEWDmDEk/s+i1gYqSJ9GJruQzgIDaKZJ99NOwY/YhQQ+h3kMuU5L/Y7z9eK8VHkVfp0QpAw==</enc>]]>
    </text>
  </js>
<css>
    <text>
      <![CDATA[<enc>6xSGli4Wotw59iMlYNIY39BqoUr0dvPifiSg6AU9azEBDWoH1wuSqhMgAU8g7ZueXYxFl6C4F3zl+jeqH70TOY7s4YMemUtTL+n9QIc5jCx3dEGsELi5BYW6EvBaQOoGyQs6SEmPSbZsIi3sSeFx3lfhSfCdZg4ZgK6xvC7OpK8KfCWFAIXXLVMiF6EpXKCIiqyupTGDBdKkxVgsrYxaeGX4YDQmNouKV5Mc42FazvMbbRDJGHqmMZXvsJb/pcJe8e/+l9s+oPZT6pVJIrDaS+VwWTvc+k26w40+dBlyKu+18PjLzPO1FHiGqkERPIKJ</enc>]]>
    </text>
  </css>

  <script>
    &VoucherJSLoading;
  </script>
</dir>