<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucherNotPrint.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="s323" dirViewType="Grid" dirObjectType="Voucher" voucherCode="BL3" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Phí Local Charge Cảng Xuất Hàng Không" e="AIR Export Port Local Charge"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>

  <grids>
    <grid table="s323" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true">
      <fields>
		<field name="so_ct" width="100" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="120" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
        <field name="ma_kh" width="0" hidden = "false">
          <text v="Mã hãng tàu / Đại lý" e="Carrier / Agent Code"></text>
        </field>
        <field name="ten_kh" width="250" fieldType="EX" >
          <text v="Tên hãng tàu / Đại lý" e="Carrier / Agent Name"></text>
        </field> 
		<field name="ngay_hl" width="120" dataType="D">
          <text v="Ngày hiệu lực" e="Effective date"></text>
        </field>
		<field name="ngay_hld" width="120" dataType="D">
          <text v="Hiệu lực đến" e="Expiry date"></text>
        </field>
		<field name="ma_nt" width="100" >
          <text v="Ngoại tệ" e="Currency"></text>
        </field>
        <field name="t_tt" dataType="N" format="FCAmount" width="100">
          <text v="Tổng tiền" e="Total Amount"></text>
        </field>
		<field name="t_ban" dataType="N" format="FCAmount" width="100">
          <text v="Tổng bán" e="Total Sales"></text>
        </field>
		<field name="dien_giai" width="250">
          <text v="Diễn giải" e="Explain"></text>
        </field>
		<field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="120" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="100" fieldType="EX" >
          <text v="Đơn vị" e="Customer Name"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      &DefaultButton;
	  
      <script>
        <query>
          <text>
            <![CDATA[<enc>KB8xqdyii61Ha3yaQfUGVWUU3lDj65S1WzGhx/t2U3PmVdsHPnt66u/OUfYAC4bOsiwCoJWRuUbKk20MAg628OEvZy6K9Uar283Ts6GIthriNkVCBV/axwwATmJMDkPuvMD1f9cB0BhJ1OG6GQPVOJmfdC7bPD0Gi0HtLehIn9LPLWFPE4pFf5i31YSvQfhZCdwTTKKzww7VIr7b5NKy7b3J6zLZZv2fEyDs58c6VoxJK0M8R4h7kcRybgdyqAtd7fiM7A9ub378N1uzGWv/LVzS7yi+FSy92FC8GWEmgRWPcQBoNySpiDcbWODtIYvMxBlz4uY1iqnxKlK8YcbbUg==</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>lfcTso2MbCUpDyZ9bhoHE0bwSBqyPWQ4olsSJk9lj5/gKaxw90M+p7zGny8e+LcyxA0ykq+qXPbdsL7efE+uWdv3XiuEmHlV1HMpUmIpHj7xxEE/huYY6p8TwUc9iJHlUYK3K4PaVXo10WoncolNmSq4SW0A9TmtBc5wEr1ka8XdhdKoBtzjVZxJZblWguQKifP6OahaugV+9o/lTgpttLZ59HoGIvE60FtSea3nfPb39aONoredWFusNphMXiyw2/Ij1infAJg/to7hUm48G4b5GUrZI0XQZPmgZPVier0Mp8nWGtcM13tNg++fQCEENiycp+28dlMm+EoOUM669pUdu/EBQgVPAOGbzYAytH3DgflMgf/DLZiaEWeGGo6O9DU0kpvlF8HKbNc8QaqwlMnWOoPBgtHHv+6m7Tjb1r7xWOuDDSS2j/Ql8OOXIYHEI4JGnTsV9sq2bLQYfL1WCw+KMlOZCo1LdkARswFhldjDMZNE2rvbNe2eLH5w1qyeen0z+v4TF0KN2WVlWUTWFlX7OUox03APMud9H/CO3mBEwI9lTErMMCWygmCLNMF3c8cPsJqCDe+zOoSlHIFi9ju4Qqvt2sa21R6LWR3Bj1JOR6BaNhBYc044la1wnPe5rrkJBngDrrld5Bb6whAO7Q==</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>uGYTDvvLc2EYt7AffrwGtrC/8RUONeeQCBa/YAoGhiVn3xLDZt+70cpDr2CrdDYaCLaGHEgmJW++2GwzSnYWjQNHZ8Kx7r0Gv8voA+Bqm1IX+4zEFoENi5/9X8+KdncTlDxHBRWn3gcfcaubqHmIEaSIBjivwLw7ntuHIo7kU9ZEaOrJIcYB6Ni7jlPA80VGg55o4BYKrBqZDANXkvUTiA==</enc>]]>
    </text>
  </js>
<css>
    <text>
      <![CDATA[<enc>6xSGli4Wotw59iMlYNIY39BqoUr0dvPifiSg6AU9azEBDWoH1wuSqhMgAU8g7ZueXYxFl6C4F3zl+jeqH70TOY7s4YMemUtTL+n9QIc5jCx3dEGsELi5BYW6EvBaQOoGyQs6SEmPSbZsIi3sSeFx3lfhSfCdZg4ZgK6xvC7OpK8KfCWFAIXXLVMiF6EpXKCIiqyupTGDBdKkxVgsrYxaeGX4YDQmNouKV5Mc42FazvMbbRDJGHqmMZXvsJb/pcJe8e/+l9s+oPZT6pVJIrDaS+VwWTvc+k26w40+dBlyKu+18PjLzPO1FHiGqkERPIKJ</enc>]]>
    </text>
  </css>

  <script>
    &VoucherJSLoading;
  </script>
</dir>