<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucherNotPrint.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="s331" dirViewType="Grid" dirObjectType="Voucher" voucherCode="BM1" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Phí Local Charge Cảng Nhập FCL" e="FCL Import Port Local Charge Fee"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>

  <grids>
    <grid table="s331" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true">
      <fields>
		<field name="so_ct" width="100" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="120" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>

        <field name="ma_kh" width="0" hidden = "false">
          <text v="Mã hãng tàu / Đại lý" e="Carrier / Agent Code"></text>
        </field>
        <field name="ten_kh" width="250" fieldType="EX" >
          <text v="Tên hãng tàu / Đại lý" e="Carrier / Agent Name"></text>
        </field> 
		<field name="ngay_hl" width="120" dataType="D">
          <text v="Ngày hiệu lực" e="Effective date"></text>
        </field>
		<field name="ngay_hld" width="120" dataType="D">
          <text v="Hiệu lực đến" e="Expiry date"></text>
        </field>
		<field name="ma_nt" width="100" >
          <text v="Ngoại tệ" e="Currency"></text>
        </field>
		<field name="dien_giai" width="250">
          <text v="Diễn giải" e="Explain"></text>
        </field>
		<field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="120" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="100" fieldType="EX" >
          <text v="Đơn vị" e="Customer Name"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>KB8xqdyii61Ha3yaQfUGVYufMU9aTs+nW1viJXPkK4zBmdFsNz+Mha2xWHfith6gwVsCP0ureRJxmhKQ76oo/0EyQeF8G2V9IGiAPLO83o8Yscj1A0TLvH0z/RX5dlnLfDiHtf6Acg+0Xt2SOej/4X0TSgpkSuXojTXnY3NhAGtZX6JngGCgn0wO98lozhDr2Hmm1T6nbYL2eyi1cuMMdLViGCU37nNzKtf9gwQ8QDoo+ZQzKUDr4w1udLK7q61zfhvSmfZAT7eUmSSMTmLa4efBzio4wuk1hSfCXDcru91OUV2Wj9bMo9cwDIoLG6pM</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>lfcTso2MbCUpDyZ9bhoHE6UMl74aiKzReEO7VM7kIdKaof5mtEb1/a29SaFvLyGYZILXcTNTzxOZAe8lYdiJ5KsIcs0zHzukvnQsr5l6oZYov6pK46et+kcyEgLak56L4oWgc9TTuqUyM528TzfX6CS5gcv+W23bZ/rpJBv31wgRR5Svc2mun0kSLV4UF809oAe7wPqVW6jHgNtFW5o9tzKepN9Gxmn5+HdeLMxSrFoulOrHu7DIJmpUGi6kSdvo89oreMypEXAm3PP+KOS09wnhgCsIIsB8J8C2QMLnsW4WA1OIs+YtmTw/f0MSMQBeHPl4QEEPoclWOzEdVnigSdM//7+JFo0+8aJaBxa16jVwBfrJ9yfuAkt05C8+vhRUC2r/YbhMGkN2RTtXIHjyxf6PB8v2lqskkDujdlbDumPMN4LY8LsesDHaFJn9ScyDr1LNv3fBKrWG8gUMWNdrgKbK6uGlw08+lepbHSCFDJ0PTWGCmFI/9GYg49wv42yFeo80//C1t8FyqhTh3rrOxpjYREfvkAi+uXrSc5yASYWXdfOh/NHCJe4IKX92+HkXA/Y+tAEmWUZBuj3kutaOX495sl4Iycgc7x5mcPYz3YKjqoR4DziVE8PlKSoh4uHUBqyMjow3hhK2eOUQlq72izV4C0vXMW+thGUNa2mojQk=</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>jTwWP4URN13fjiNnm/IWVIotII0c6ObWRSx/mS7Kj/UPDUpGFwICIqmPx4M2ikBDOrYi6ikmumfb7tn2/Td8RipsahurSRmAtr4h+14Bmlg5fhHYQGPPb2MCoTlWZpdrkjLp242sLFsIc56y1faghJOTx4pQREsl8t1e3m05xGtxLlWIMDspYnIZyscm9VI0vzYEGIjZkFSKenqqfsSq/g==</enc>]]>
    </text>
  </js>
<css>
    <text>
      <![CDATA[<enc>6xSGli4Wotw59iMlYNIY39BqoUr0dvPifiSg6AU9azEBDWoH1wuSqhMgAU8g7ZueXYxFl6C4F3zl+jeqH70TOY7s4YMemUtTL+n9QIc5jCx3dEGsELi5BYW6EvBaQOoGyQs6SEmPSbZsIi3sSeFx3lfhSfCdZg4ZgK6xvC7OpK8KfCWFAIXXLVMiF6EpXKCIiqyupTGDBdKkxVgsrYxaeGX4YDQmNouKV5Mc42FazvMbbRDJGHqmMZXvsJb/pcJe8e/+l9s+oPZT6pVJIrDaS+VwWTvc+k26w40+dBlyKu+18PjLzPO1FHiGqkERPIKJ</enc>]]>
    </text>
  </css>

  <script>
    &VoucherJSLoading;
  </script>
</dir>