<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucherNotPrint.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="s333" dirViewType="Grid" dirObjectType="Voucher" voucherCode="BM3" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Phí Local Charge Cảng Nhập Hàng Không" e="AIR Import Port Local Charge"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>

  <grids>
    <grid table="s333" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true">
      <fields>
		<field name="so_ct" width="100" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="120" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
        <field name="ma_kh" width="0" hidden = "false">
          <text v="Mã hãng tàu / Đại lý" e="Carrier / Agent Code"></text>
        </field>
        <field name="ten_kh" width="250" fieldType="EX" >
          <text v="Tên hãng tàu / Đại lý" e="Carrier / Agent Name"></text>
        </field> 
		<field name="ngay_hl" width="120" dataType="D">
          <text v="Ngày hiệu lực" e="Effective  date"></text>
        </field>
		<field name="ngay_hld" width="120" dataType="D">
          <text v="Hiệu lực đến" e="Expiry  date"></text>
        </field>
		<field name="ma_nt" width="100" >
          <text v="Ngoại tệ" e="Currency"></text>
        </field>
        <field name="t_tt" dataType="N" format="FCAmount" width="100">
          <text v="Tổng tiền" e="Total Amount"></text>
        </field>
		<field name="t_ban" dataType="N" format="FCAmount" width="100">
          <text v="Tổng bán" e="Total Sales"></text>
        </field>
		<field name="dien_giai" width="250">
          <text v="Diễn giải" e="Explain"></text>
        </field>
		<field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="120" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="100" fieldType="EX" >
          <text v="Đơn vị" e="Customer Name"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>KB8xqdyii61Ha3yaQfUGVWUU3lDj65S1WzGhx/t2U3MzObSugytscIvcQORhech+KAC/oksV/enQ6yRkNAMwmYKRdwtQDW0jCNT10pcYj1usS5xbsHZ7AMU0cKggZJnX672wAykIkMSYvDfSJt22WMOcNwqbADVGO9Ev2KcoS0++z7sD6VTsACVZDOwu3MqNG0Y0g51/VvmquJG3AwUprSOV2ML0x96Pq42c17C8/E3RW5N0jHTSX5TgbKioqogohjAcCwf2SfDOO6HSjKO8+hwDxFqf68q/VeymJVlxW3fRw5yV2wVKyBcokduLHTCVHxqBlxsNBoXBfts07AwfPA==</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>lfcTso2MbCUpDyZ9bhoHEwWxCcoP0IuNUkI1Lz8S5+4OXLySsTxBAE0t2hcG4P9a8xgcsZ8HgUvQ09oeu8wEto6qUbtAJlCAoyLbU8eo5eRlABxSYXlwxDb44B8NjCa7qKpmVUdoaX0N3b/tfPOmef1Ea1GLfhG8x/GDy7sD9z5Jwsg/V7jgxoUnusZRSYnfGCwiOIsIo+aKI3MefNS/23xm+Qs3T1djCQWmhwcjP5eKY1t1BAGD8Wz2uZf3HPdSbNgGh44OdUolkcXhHoKugbwVir35fpHlqm0I/kF+OcqcDPStpFPI65lQitkw6PgbswA8LBK08LQO77Eu245RM4Hoz+5qLK4HrAVB9WMwbksZeuxpnGo4l8ZZvClLU7qHFPm02KSSgyC7KInMpc4ft/49S4Sot1p5/NeMT3cs2sL69cKrXKa7I7PHZOxfOITg89MzOBoGoc96i0ZuWziJdWs1d92IxQgZTKKpgOpazP09WOhXQ0XB6nLt/evb2qSSLNLmIJVJA5NqfZcjIfuMOrw5wqekoLuZBrb/7Ls6DV9TiVdGykAtj0oW5K9/x4rUROLu77W2Xmxlkx/e1A2obrCahsdHgcY0V7LucMr16BgGU77aN3Gzn3gC4w2yi/XckIQILe1AYwypZwI92SCTiQ==</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>uGYTDvvLc2EYt7AffrwGtk0gJAt1+22zA7TjRB9FEvzo6u/F4a/md6l8fMErWo6QRZgpHSlFWSlLcLYf7TnoNzXcCWhH5F6KoKInIyE/4yGguWvVf4N0x7FrGzpuqjW7ixfEFnFb1N5MUHJlMmH6wF4SdenwRWsvb0DDS63RDEpTQDSD7JyZHcUZS3mKzDCMb5UPRAeZ9NQKZsY42IgNig==</enc>]]>
    </text>
  </js>
<css>
    <text>
      <![CDATA[<enc>6xSGli4Wotw59iMlYNIY39BqoUr0dvPifiSg6AU9azEBDWoH1wuSqhMgAU8g7ZueXYxFl6C4F3zl+jeqH70TOY7s4YMemUtTL+n9QIc5jCx3dEGsELi5BYW6EvBaQOoGyQs6SEmPSbZsIi3sSeFx3lfhSfCdZg4ZgK6xvC7OpK8KfCWFAIXXLVMiF6EpXKCIiqyupTGDBdKkxVgsrYxaeGX4YDQmNouKV5Mc42FazvMbbRDJGHqmMZXvsJb/pcJe8e/+l9s+oPZT6pVJIrDaS+VwWTvc+k26w40+dBlyKu+18PjLzPO1FHiGqkERPIKJ</enc>]]>
    </text>
  </css>

  <script>
    &VoucherJSLoading;
  </script>
</dir>