<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="s334" dirViewType="Grid" dirObjectType="Voucher" voucherCode="BL3" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Phí AIR theo cảng" e="AIR Fees By Port"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>

  <grids>
    <grid table="s33" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true">
      <fields>
		<field name="so_ct" width="120" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="120" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
		<field name="ma_kh" width="120" hidden = "true">
          <text v="Mã hãng tàu / đại lý" e="Agent Code"></text>
        </field>
        <field name="ten_kh" width="250" fieldType="EX" >
          <text v="Tên hãng tàu / đại lý" e="Agent Name"></text>
        </field> 
		<field name="ma_noi_di" width="120" hidden="true" >
          <text v="Nơi đi" e="Destination"></text>
        </field>	
		<field name="ten_noi_di" width="250" fieldType="EX"  hidden="false">
		  <text v="Nơi đi " e="Destination Name"></text>
		</field>	
		 <field name="ma_ttp" width="120" hidden = "true">
          <text v="Mã khu vực" e="Agent Code"></text>
        </field>
        <field name="ten_ttp" width="250" fieldType="EX" hidden = "true">
          <text v="Tên khu vực" e="Agent Name"></text>
        </field>
        <field name="ma_qg" width="120" hidden = "true">
          <text v="Mã quốc gia" e="Agent Code"></text>
        </field>
        <field name="ten_qg" width="250" fieldType="EX" hidden = "true">
          <text v="Tên quốc gia" e="Agent Name"></text>
        </field>		
		<field name="ma_phi" width="120" hidden="true">
          <text v="Tên phí" e="Origin"></text>
        </field>
		<field name="ten_phi" width="250" fieldType="EX" hidden="true">
		  <text v="Tên phí" e="Origin Name"></text>
		</field>
		
		
		<field name="ma_kh" width="0" >
          <text v="Đại lý" e="Agent"></text>
        </field>
		<field name="ngay_hl" width="120" dataType="D">
          <text v="Ngày hiệu lực" e="Effective  date"></text>
        </field>
		<field name="ngay_hld" width="120" dataType="D">
          <text v="Ngày hiệu lực đến" e="Expiry  date"></text>
        </field>
		<field name="ma_nt" width="0" >
          <text v="Ngoại tệ" e="Currency"></text>
        </field>
		<field name="dien_giai" width="250">
          <text v="Ghi chú" e="Note"></text>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="80" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>ujABaYhBD9Mmd75RvdVwDTXMURGu4rVJg0vIG1tVBSP70NLk70y3C6Sl5wl+l1wQyrusI4CQtQJNC3fC48EXl85TzZewqoTHGWXhdCNac7Lylzg7P2gyuZm8aND2sR9/VCMToVo4GzN/gPlGUiqymJ2+cuoD+KA1ZpfxYH8NMIdk7YA67PQ5AhZddNUG8MlLSdvhkluPIwk1QHxsrDoK3DiS3CXKiPi3RdIQ+4DU7ZgGng4jqDkN+2yDkThZTQnoVWjDPpS9TkzF+Uwz2KAYFpxIJesOXB3scThMDjp7fuWlrTqeHu+J2/XvZLQwFKya1nG34mPXm1gtIcDNN2n5nqeFNV3Ib9wGi8Lwb0O80bWIh8YS8WV2qvDo6Yobi3Aj861ZlxDEmgd8rIMAMN2cFiXFtIO+A1JvJxVsIWm8cYw=</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>+X9sfqDNRQHlmI8CW9fiG9G+c5LuJTMD/64SFrFbR9DykDxRhNqyD1usY0mHUQqO/z1QlHXbEwCXnKtUeL6ku9OadHuyhwswi/QGeQskSBhRr6Er2KoD0giyvxdGFCuZdwWod6NzeRA9MyCdf6PrNE9U8CZOHVKdeZacaM8zEILm3XKV1qC+tlCODaAFU4j9fnTupPhYiv4cxq1GJmxQH39BgMWO1hCAUw4bDcsXS92Bw9KjoT97vX+Kxs43DZvMMNtULuhSTeNs7izXp324how7C3lh04wxDbriKLXunHVrao0bQlieYntCF9bu2r3QBM2cK01e/LcIysE84fztpx1Es1K89ECzsia8eSuNxtdHGFc9RArmweVY6Id2O5KsMNM04I83T6a9OOS/Udbdo807nNw2SDTvPxmhE+YKKaWmCfSFdRZYNAhGOImTEI1A+Sk91y1uSw0vmm5vxvn1a1+JWwxJ8GRr2s0YGtopBBvkwI14r016mNkh/DQkypJxn+SQFRHzImCKJOsydOV6aU9RjlV/gJc0BLpU9lrA4BRrTGEIAqoILPRvZjFd7aJQmuXceh/S9L88fpdJHh6zdYEjiXeJnHTXsMQwOeN8qgz/QsIXTMBZdNEjM2v7IVXGxDaav8xQ6qEDT8bceMFnQ8RJVR63h/Shi3qb7r2tcDZin9WpsXaq0ahpOr+w2jrLxRfYRN/XMDEAxG+YAyCJCQ==</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>uGYTDvvLc2EYt7AffrwGtozDF8bds8Q4qStfN4yda7pDy6LFtRH1DeT10mRM/vuiEwqSQdNcPjjsvNmNXwQ5J9JRSzWmrvoH5F1qkgip5CLlU/oN6Bb4YRH6q+lvQxkxwFrFeUKRenl4FbzakUpSdaKQcl5HuSuQJ/VJKIOD/zhAE2UpxnVh5y9B4s7XZbueD31cBpBp8yTKErQqUbTkRA==</enc>]]>
    </text>
  </js>
<css>
    <text>
      <![CDATA[<enc>6xSGli4Wotw59iMlYNIY39BqoUr0dvPifiSg6AU9azEBDWoH1wuSqhMgAU8g7ZueXYxFl6C4F3zl+jeqH70TOY7s4YMemUtTL+n9QIc5jCx3dEGsELi5BYW6EvBaQOoGyQs6SEmPSbZsIi3sSeFx3lfhSfCdZg4ZgK6xvC7OpK8KfCWFAIXXLVMiF6EpXKCIiqyupTGDBdKkxVgsrYxaeGX4YDQmNouKV5Mc42FazvMbbRDJGHqmMZXvsJb/pcJe8e/+l9s+oPZT6pVJIrDaS+VwWTvc+k26w40+dBlyKu+18PjLzPO1FHiGqkERPIKJ</enc>]]>
    </text>
  </css>

  <script>
    &VoucherJSLoading;
  </script>
</dir>