<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="s34" dirViewType="Grid" dirObjectType="Voucher" voucherCode="PC1" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Phụ phí Hàng biển FCL (Hàng container) " e="FCL Surcharge "></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>

  <grids>
    <grid table="s34" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true">
      <fields>
        <field name="so_ct" width="120" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
		 <field name="ma_ct" width="0" >
          <text v="Mã chứng từ" e="Voucher Name"></text>
        </field>
        <field name="ngay_ct" width="120" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
		<field name="ma_kh" width="120" hidden = "true">
          <text v="Mã hãng tàu / đại lý" e="Agent Code"></text>
        </field>
        <field name="ten_kh" width="250" fieldType="EX" >
          <text v="Tên hãng tàu / đại lý" e="Agent Name"></text>
        </field>     
		<field name="ma_noi_di" width="120" hidden="true" >
          <text v="Nơi đi" e="Destination"></text>
        </field>	
		<field name="ten_noi_di" width="250" fieldType="EX" >
		  <text v="Nơi đi " e="Destination Name"></text>
		</field>	
		<field name="ma_phi" width="120" hidden="true">
          <text v="Tên phí" e="Origin"></text>
        </field>
		<field name="ten_phi" width="250" fieldType="EX" hidden="true">
		  <text v="Tên phí" e="Origin Name"></text>
		</field>
		
		
		<field name="ma_kh" width="0" >
          <text v="Đại lý" e="Agent"></text>
        </field>
		<field name="ngay_hl" width="120" dataType="D">
          <text v="Ngày hiệu lực" e="Effective  date"></text>
        </field>
		<field name="ngay_hld" width="120" dataType="D">
          <text v="Ngày hiệu lực đến" e="Expiry  date"></text>
        </field>
		<field name="ma_nt" width="0" >
          <text v="Ngoại tệ" e="Currency"></text>
        </field>
		<field name="dien_giai" width="250">
          <text v="Ghi chú" e="Note"></text>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="80" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>RO9DrUriKyeOgrTmU70n7vahfVyKmbaDpTWSa4IMG+xcq/vhmGimSvCqx25v4DnZiKsA7olKJtqyona67WncI6iSVLKE+dJ9u5k2rEYABygJMUf6DaGFBkwBgbJ4LYSzbsj5g3nUeXEDzRZns6oatCYziGF92sfdS3n6GSbfL6EuUMag6OpJQLTBHQszM3X6X6aWipiGdEjCiQjeecDaxDhaONgGpzYhRrvTBhbq6uuR1UjlkH64SNKxmRBzJ0WmjeUlLRzN45T2JaesPuKX6bD86EWSOZx3wDyX2yy95zvTZz2YUvNXttqw63xW23Wj19cZkPIy09NWXci33tcWdIKHIqUbOCtydbeZJ/Q7t9OoKDXbv+PuYNqzgPNtUhgi9Z8Q+j8A8R2LaSo2lCwSFw==</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>2MmiSIahkhxBzNVL/MXlp9K9RifFTspWOt3NlLkcd4mV2eefWIAMY2HrivLPniQPMamPWHvTgG8x6/3yVawQelZ54EvbErXMEv106dm7V50AWBkDSiZj+Y5hjIMPQbD+ivvgGrBI4H36LzGUBnYHoGMsIIQ2uXTagSHQohYhXGkEJBQIA5nXb7gk5Lmz8o8McGlhYazgfsQ6ufk5gPcdgUx0phtgjeqP4Oos19z/cyHDzxz/NGfKMzf8HfcomF21kCk5WXAqGCJ1cCJUL/swt8HYWmhmBHoX/sMUEkY2aAcOSyopmZ6ZZOMfMfhcazFoSpvYa/cVZgU7bmaHJgnwqyvLhtv9KWQC9U7+uG8VLjNSP+Kakfjh9aj20H5zzArI6vI8wr1E9/nmOaqlSGO5SbCXK1LWQwu33vzmAP5UZ/THXQ/rGDtHWUg0Kz3PvtZtdNCkZARH1W/LdSzWQ1tTUw8uN+gES6A97SDazDs3SyeJD673XUmcrw4ni1etuDrTi6n7TR24hSJFHTibC7E6XOvwgsbAbcPx+HqNu8QkRHBEj/uHu9xIvtwm0JpzmxvmPd8yA6YG0iwqFpQX5/qan27H9d4sewvFXx2zLb6Y/V7kDpfoQ4UdIasSCht2UZJN83PNlEam81jqMgkcuNJQEg==</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>5wErx4q93yz4A4Cu1Ug/I+aQ9Q5HONRREHvKMtyc12U2vvhEGWd6xFE8pPtLpNTuqRMr8JNn6VxMF6mq9HcvO0Wy8brGeJ+TebGm0pnxzKMSu1Sc80A7zxolZTzA+mQbmt4ox4TXPZr338ecM6y+DoPCxvLOIYBvISck7MN1k8T10iK4+7BfS0NscKU7O7r2kqxAUgi/F7FU1jHrvbOXSA==</enc>]]>
    </text>
  </js>
<css>
    <text>
      <![CDATA[<enc>6xSGli4Wotw59iMlYNIY39BqoUr0dvPifiSg6AU9azEBDWoH1wuSqhMgAU8g7ZueXYxFl6C4F3zl+jeqH70TOY7s4YMemUtTL+n9QIc5jCx3dEGsELi5BYW6EvBaQOoGyQs6SEmPSbZsIi3sSeFx3lfhSfCdZg4ZgK6xvC7OpK8KfCWFAIXXLVMiF6EpXKCIiqyupTGDBdKkxVgsrYxaeGX4YDQmNouKV5Mc42FazvMbbRDJGHqmMZXvsJb/pcJe8e/+l9s+oPZT6pVJIrDaS+VwWTvc+k26w40+dBlyKu+18PjLzPO1FHiGqkERPIKJ</enc>]]>
    </text>
  </css>

  <script>
    &VoucherJSLoading;
  </script>
</dir>