<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="s35" dirViewType="Grid" dirObjectType="Voucher" voucherCode="PC2" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Phụ phí hàng biển LCL (Hàng lẻ)" e="LCL Surcharge"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>

  <grids>
    <grid table="s35" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true">
      <fields>
        <field name="so_ct" width="120" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="120" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
		<field name="ma_noi_di" width="120" hidden="true" >
          <text v="Nơi đi" e="Origin"></text>
        </field>	
		<field name="ten_noi_di" width="250" fieldType="EX"  hidden="false">
		  <text v="Nơi đi " e="Origin Name"></text>
		</field>
		<field name="ma_noi_den" width="120" hidden="true" >
          <text v="Nơi đến" e="Destination"></text>
        </field>	
		<field name="ten_noi_den" width="250" fieldType="EX"  hidden="false">
		  <text v="Nơi đến " e="Destination Name"></text>
		</field>			
        <field name="ma_kh" width="120" hidden = "true">
          <text v="Mã hãng tàu / đại lý" e="Agent/ Daily Code"></text>
        </field>
        <field name="ten_kh" width="250" fieldType="EX" >
          <text v="Tên hãng tàu / đại lý" e="Agent/ Daily Name"></text>
        </field> 		
		<field name="ma_phi" width="120" hidden="true">
          <text v="Tên phí" e="Fees"></text>
        </field>
		<field name="ten_phi" width="250" fieldType="EX" hidden="true">
		  <text v="Tên phí" e="Fees Name"></text>
		</field>
		
		<field name="ngay_hl" width="120" dataType="D">
          <text v="Ngày hiệu lực" e="Effective  date"></text>
        </field>
		<field name="ngay_hld" width="120" dataType="D">
          <text v="Ngày hiệu lực đến" e="Expiry  date"></text>
        </field>
		<field name="ma_nt" width="0" >
          <text v="Ngoại tệ" e="Currency"></text>
        </field>
		<field name="dien_giai" width="250">
          <text v="Ghi chú" e="Note"></text>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="80" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>ZiwnTS3AMnoaAQdY57kT5pGztqUApmD+HkWmzUZB+8wbOSKrdjAskgdBlQY0tA/ktes4XXK7jI0/mHqZhH9LnCSWAsA6lW61DWAabGPk8xJNkiEKTYwb6QmK0JUT3kGKV9VWYtB42X4vra7GS5WtwDmpVrrJypzs+trR/O/92cLs1w7ACYaNvoWKJwAYLuUuN2CEL5hBGm4kc0IxHpZDnpOLIWZFNlZPgnk9LCw4K/FAFcsu42WyC2itKwpBLmbEhxGbdj7c+K5fhqbLHnHIZWSGBnVYEuS1EgxJ8M5f2z6y+fbnBbwHnebJxAcgtOvp4h0b2YTtzzhm3OmVbMqKKTls/CAGzCbMUa19Zll8wl0=</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>1GR90UOlw4PSi80aOx2j/9q/16B++nqHXipDbeykOU+dA1pKK8kGWSb3NuiagnZEzm6m1mwZA44DNOfjaFh3hBrvUZSaVQBlLzOdtVNB3QBN2DetyRE3+fJSkqHaTq4h+7KNlj4pJ/OX6m3O6gHruPuSTknvqlLKghEa8cGlD6SOJJY1Ukx45U5n6d/20OIuLAFQsfaHgWRe+ahyIIl0rU7qACW4iLwV2/J+jcUcD9vrGFjtNed+FPGR0Oqi+XBlpw3POjYws+HBoSCAeWwtmz57wjSyP2bs/W9rvNiArIJrmBDm9HTdNr3wzQbacNUdbGxpqcELb9w949sdFITtyfb5KhX2f8AMXKgqjJQvBk7iLRAp5hMHLQtzJQsxa1q308W8U7fwjg4Fh3OxXEH5B84gF8uN9dsJ9UKxEhDOdIatlm7FbmxJ0Y2WG73LyYaoJLRLTiI63Bym/Vm2npRPlvDxmxpgJPaNrT52EDQjNpcH7yJQGbFjALgkwIwKaAnUn6ytrWtrAanLkmoPfialNP2ajU8psRpsZZeaps8vOrOfFMr2WnlXwFKLTTPg4jOz</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>5wErx4q93yz4A4Cu1Ug/IxkCn7J5XFuguWXfrCqhSobfyw5Wylm0OCVhDcTDPaeNMgBilBAWNJEnBNI8nXVJA2i8EAampw7LZYKv+mP8AAXqVDqIs73JWyw98vkCdeIFsqJQOs7CfU1Y6g+WXr0vRt7FyozXAkyHx1+ejsdbK67VXiTemxvGB1bspLqCYUE/WxYpF6LAWjknwRH5Triz3A==</enc>]]>
    </text>
  </js>
<css>
    <text>
      <![CDATA[<enc>6xSGli4Wotw59iMlYNIY39BqoUr0dvPifiSg6AU9azEBDWoH1wuSqhMgAU8g7ZueXYxFl6C4F3zl+jeqH70TOY7s4YMemUtTL+n9QIc5jCx3dEGsELi5BYW6EvBaQOoGyQs6SEmPSbZsIi3sSeFx3lfhSfCdZg4ZgK6xvC7OpK8KfCWFAIXXLVMiF6EpXKCIiqyupTGDBdKkxVgsrYxaeGX4YDQmNouKV5Mc42FazvMbbRDJGHqmMZXvsJb/pcJe8e/+l9s+oPZT6pVJIrDaS+VwWTvc+k26w40+dBlyKu+18PjLzPO1FHiGqkERPIKJ</enc>]]>
    </text>
  </css>

  <script>
    &VoucherJSLoading;
  </script>
</dir>