<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="s41" dirViewType="Grid" dirObjectType="Voucher" voucherCode="BQ1" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Báo giá vận tải đường biển FCL" e="FCL Ocean Freight Quote"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>

  <grids>
    <grid table="s41" fieldKey="id" order="ngay_ct desc" allowFilter="true" allowOrder="true">
      <fields>
        <field name="unit_id" hidden="true" dataType="I" width="120" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="100" fieldType="EX" >
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="so_ct" width="80" hidden="true"  >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="100" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
		<field name="ma_job" width="100" hidden = "false" link="V" >
          <text v="Mã job" e="Job Code"></text>
        </field>
		<field name="so_job" width="100" link="V" >
          <text v="Số job" e="Job Number"></text>
        </field>

        <field name="ma_kh" width="150" hidden = "false">
          <text v="Mã khách hàng" e="Customer Code"></text>
        </field>
        <field name="ten_kh" width="250" fieldType="EX" >
          <text v="Tên khách hàng" e="Customer Name"></text>
        </field>     
		<field name="ma_noi_di" width="0" hidden="false">
          <text v="Nơi đi" e="Origin"></text>
        </field>
		<field name="ten_noi_di" width="250" fieldType="EX">
		  <text v="Nơi đi " e="Origin"></text>
		</field>
		<field name="ma_noi_den" width="0" hidden="false" >
          <text v="Nơi đến" e="Destination"></text>
        </field>	
		<field name="ten_noi_den" width="250" fieldType="EX" >
		  <text v="Nơi đến " e="Destination"></text>
		</field>		
		<field name="ma_hang" width="150" >
          <text v="Mã Hãng tàu/Đại lý" e=" Carrier/Agent Code"></text>
        </field>
		<field name="ten_hang" width="250" fieldType="EX" >
          <text v="Tên Hãng tàu/Đại lý" e="Carrier/Agent Name"></text>
        </field>
		<field name="ngay_hl" width="120" dataType="D">
          <text v="Ngày hiệu lực" e="Effective Date"></text>
        </field>
		<field name="ngay_hld" width="120" dataType="D">
          <text v="Hiệu lực đến" e="Expiry Date"></text>
        </field>
		<field name="ma_nt" width="0" >
          <text v="Ngoại tệ" e="Currency"></text>
        </field>
		<field name="dien_giai" width="250">
          <text v="Diễn giải" e="Explain"></text>
        </field>
		<field name="ma_ngv" viewType="Combobox" inactivate="true" width="120">
          <text v="Loại báo giá" e="Inv. Type"></text>
          <viewInfo>
            <options query="select ma_ngv, ten_ngv%l from dmngv where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
		<field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>JQaWevYFepPkpLNLrPr6arvHHF0IZXUsmsxHPxTWuyiKgwd3vSZXJ7dB/EbkJ3JbWTmEtyiNbg/y/AhxNLYzJ9OWsrhzEiqQQXChAhzVZqv1EM9nmYukULsvMQ58dcuClX6A5sUnMwjlPdPkKZnv5X2lM61gt2pSd9vRlLmNnKKd4nwrGH3ewizBPmXktPgOIBbQ5rwroAxfLKU/+sa/OGlSWm2yx6rZxJg9kqh37dU4QVJpP1HmRcnfwu4zA19ti5wwayY2DOUzYDdt8dKb4ALoTn5ZC8eKFMyf91kT/5pnSZ9rvwqFQzUb/Ees/N2xqN3DyHxro+PfVpL95tFLvAwoOH36cuXQOZgIfcvGTr0=</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>QNehOSXLCQO5c8u/iW/IcJuADf42cJP/klxs0h7rSwRQskc5R+4ATS5rT2YJ5rh9uRakpPFA68sOET0MxSPTVq+u/6EqeWynNJnmn0E+0hTYFDRv80L6TfmlPZLXGPqBtkhln9diAazrfjawSWgpGaWszMHUr39fzPN9IjH7KvaSZEhhIi0ftCBSMJNoNE8s2BvwtZgKHtMyaVXEOSqR1yABHyojzVuPuHw2cRr6P+M96svJ9dbo1QhfRnOsyRPYT7+HJVs77w/H9NMUTsJcacr0QseX7nMcv5kyfQfB+VSMPcs4+cbxmND8gVvvlz01JzTxS++NC80/u0wvzQDZQhGD0x0Yt7VKHDqbSoIvq7dh+U5DXxh8OBbOpTjqoK1+ZXS+CNZRAkrOWUj+QMH34oeHoMyqq238CDGWa50/nvxOLgyj0D8ok11y1QpmiO+XoJeucRb0q2Vk3J6IL/J14jbcQwBH7EdIpZV2tBRQTIXAm3HkM9DtrDLNn51VX3JKBg5lIR0HUpulwtf74wQAVthg2POSJbPpGmUkWCLUK/B3jkxzu/YC2tYoTLUltnhx/cwn3eWB+41KRL51oHhPl5bFqC0iJ45tRX/LQb00qaeyb3m4Ij8NKkxlq5sXtORpTnLIQGYlo6YA+3xcrgmxvdPykhRb3aGeajsYr46bFQNFwqduSVO2Ud6Beh7fpFPEYFZARYz++NcFwu75+lHiYxmgFiLcw9qCvcXJ9RBNVY0=</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>jzcoae1D7/AzsY7GhcCcRYBdD17pPuIw/3bHxjoQd+xTWjmuOnB7E27t1DyeA5Jj+P+TO4JcV/wZFZKU4P8jT0KB48hsS/bXZRCn/pWiE8dgij8qfepx4qHG4yj4wWzL24Truqib1hYjQ/bpn3eyO+3bEyrXgNU7UE6ucItkT3k9zd/uM2wAiwaq7sQWAhNtX/98tIAO4E94T6OxHMqzHA==</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>

  <script>
    &VoucherJSLoading;
  </script>
</dir>