<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="s41Approve" dirViewType="Grid" selectMultiple="Table" voucherCode="BQ1" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Duyệt báo giá" e="Approve Quote Orders"></title>
  <subtitle v="Xử lý &lt;b&gt;%s&lt;/b&gt; báo giá" e="&lt;b&gt;%s&lt;/b&gt; Quote Orders"></subtitle>

  <grids>
    <grid table="s41" fieldKey="id" order="id desc" key="xstatus = 0" allowFilter="true" allowOrder="true">
      <fields>
        <field name="unit_id" hidden="true" dataType="I" width="120" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="100" fieldType="EX" >
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="so_ct" width="80" hidden="true"  >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="100" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
		<field name="ma_job" width="100" hidden = "false" link="V" >
          <text v="Mã job" e="Job Code"></text>
        </field>
		<field name="so_job" width="100" link="V" >
          <text v="Số job" e="Job Number"></text>
        </field>

        <field name="ma_kh" width="150" hidden = "false">
          <text v="Mã khách hàng" e="Customer Code"></text>
        </field>
        <field name="ten_kh" width="250" fieldType="EX" >
          <text v="Tên khách hàng" e="Customer Name"></text>
        </field>     
		<field name="ma_noi_di" width="0" hidden="false">
          <text v="Nơi đi" e="Origin"></text>
        </field>
		<field name="ten_noi_di" width="250" fieldType="EX">
		  <text v="Nơi đi " e="Origin"></text>
		</field>
		<field name="ma_noi_den" width="0" hidden="false" >
          <text v="Nơi đến" e="Destination"></text>
        </field>	
		<field name="ten_noi_den" width="250" fieldType="EX" >
		  <text v="Nơi đến " e="Destination"></text>
		</field>		
		<field name="ma_hang" width="150" >
          <text v="Mã Hãng tàu/Đại lý" e=" Carrier/Agent Code"></text>
        </field>
		<field name="ten_hang" width="250" fieldType="EX" >
          <text v="Tên Hãng tàu/Đại lý" e="Carrier/Agent Name"></text>
        </field>
		<field name="ngay_hl" width="120" dataType="D">
          <text v="Ngày hiệu lực" e="Effective Date"></text>
        </field>
		<field name="ngay_hld" width="120" dataType="D">
          <text v="Hiệu lực đến" e="Expiry Date"></text>
        </field>
		<field name="ma_nt" width="0" >
          <text v="Ngoại tệ" e="Currency"></text>
        </field>
		<field name="dien_giai" width="250">
          <text v="Diễn giải" e="Explain"></text>
        </field>
		<field name="ma_ngv" viewType="Combobox" inactivate="true" width="120">
          <text v="Loại báo giá" e="Inv. Type"></text>
          <viewInfo>
            <options query="select ma_ngv, ten_ngv%l from dmngv where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
		<field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      <buttons>
        <button id="approve">
          <text v="Duyệt" e="Approve"></text>
        </button>
        <button id="cancel">
          <text v="Hủy" e="Close"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="find">
          <text v="$FindToolbar" e="$FindToolbar"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="refresh">
          <text v="$RefreshToolbar" e="$RefreshToolbar"></text>
        </button>
        <button id="freeze">
          <text v="$FreezeToolbar" e="$FreezeToolbar"></text>
        </button>
      </buttons>

      <script>
        <query>
          <text>
            <![CDATA[<enc>JQaWevYFepPkpLNLrPr6arvHHF0IZXUsmsxHPxTWuyiKgwd3vSZXJ7dB/EbkJ3JbWTmEtyiNbg/y/AhxNLYzJ9OWsrhzEiqQQXChAhzVZqv1EM9nmYukULsvMQ58dcuClX6A5sUnMwjlPdPkKZnv5X2lM61gt2pSd9vRlLmNnKKd4nwrGH3ewizBPmXktPgOIBbQ5rwroAxfLKU/+sa/OGlSWm2yx6rZxJg9kqh37dU4QVJpP1HmRcnfwu4zA19ti5wwayY2DOUzYDdt8dKb4ALoTn5ZC8eKFMyf91kT/5pnSZ9rvwqFQzUb/Ees/N2xqN3DyHxro+PfVpL95tFLvAwoOH36cuXQOZgIfcvGTr0=</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>Fxo1Y0tfPvuySpr6ORGVsoqt6TLg0haIELdYH0vXMQFSxgpt2MumIUDv5gTXVvvOj5Lpcxh9b7Z6Q5zd804uD/vWXO87qvaz2wQT1ITDEiwX2JpiDEweZ0Q/j2HKnCgDY/FhlsajKrY7uA3j3B4AQcApRwiBmXELMWdz5fiItcpCYppWzWgVN5sr3cIRkj7XWdQDiN0EN+Kt9cSe3nIT2qvOI4oAYvrXbVzROzTkQoAAEf/epR6UhgMCzTT2KbqAfT3sfrq6XzbzSmgPN6Emi4gL1O1fiTbuoohd8PvJdhcs83A3DaTuEHDEDUFb9Rq0v4BaCFomT5TGErcJyB9LcjZdPy9YWAmZhK4W2/9ptL7am2mW0n2fEcbdhzs9/xnui2KN58eSxI9jPRrnfbf3UU2UppkVgygL27MY6QbDVwYyliM1RxjAt/dLEaByGm0Y9XxphrP851LPJ/8KPRaLnLWkzunqsxvjSAuyfHuJsXh6UUWgk6+UgWvh8f11F61/15Z1Aiq7q1v89CJpFYr0LNkynX/s6+Es6kenboNH7OOBpoiDVVxCDfmbWfL1vSGzakFuPTZcRmShz7zhlRRncMyUq72GPECoLOaaIIFxL3Cy0SCZdKyDnauhKJzYAsVMGshBiO/3ZHDCuAKKIy1kKhZrXXKlSAfF/h5gKMRz4i6PfEyG8XHujtBk2KnGJ+zXnpWsAXGyiaQwxUDFwfNrQ7Q2nT33YDFnJiBDcC24t5c=</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>hMNpb+ya+hTY4Yu5t+qT3PzE2mD72uIa04w/hp4mzooDVILGLqTPvBUEeBy41ZtwugmsOiTh0lt+ip+/J/cd1rW9QAKFG9kQvgApcKRZW1EDh3kyQP2BcD8WJy5UIlr0hkOphDBM+WumawkkHt6rnwXNNLv0q4qzVSfj7YjAaQoKSeRKBKryQ11pKN1ucCdFH/i1JKmyp4ls6/irXfgsq7HeAUUoYn9DeEQxvQsuKBTU14sUmHP6Gqr7GwkKPjgHwYlpGLNyImChEqQPmaijm/i2TCGYhfpi76DurjvoW+vMxh7oRT7JPmBhzqcN0cBULfg+9+D63Dz67dl5qVPJ+gRAPZkaqyydGZO5LFo86NiiEUOJbmC2gbu12lXb0qb81zB2YewGBKJvbc4QOYD7ecWw2wzXZSb39fUtwuE0I3JmR7S3ig/gJrhp1qmfmSIgWE78JWAR0monAzrBmuWKpfCdIW0eSXPeJS3EfYwZCNpkHgq+MD/NScKq1th1J3ptLRb837c2XLqh2OPa0OOusZrEuZBep6VNdhnCEm9lv32/EfUQrkkB5asMsvx5Xm9vozXM5najAQ5zKxDRypDWeKzc6xaay10n5SpC3AYIKnXDGIoJLv07CHOuNufKWxeHVjP+XuhoSbHkMsZS6vAkgAjVhuzfeclcXCwbBatosJtk5TKTYjDxdxDzskWfwHwt6qAL90WkGDAAdPHZPJ6qyzcu4O5bZlCpJmkJAEAjSLWzQ1LPDPUPKkTgTIZMR8zdaB2dE2z6yTdYuuDwPOLLY30d/lbeVzuuGWSb4dz+XgRWj4AlSNKvh7SphKhK+cEdeZmmZk4LVyxUfhFpNNk0tuZDmSAHb+XgBgmI9wabyOYBrNIcjGpj55/UR6HXGQd65br8PYu6WJFbs5T307Td57AtLa8+fY6ILSu3AZhrvuA=</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
  <script>
    <request code="Approve" transaction="true">
      <text>
        <![CDATA[<enc>aRA3gieECo/ZXnHwfhSXKy4o6jgvL6Ov27q63eNEu+1ThvYvdFdFu07gcrg1mmYdgekkuxS5JWdx7VfQxun4RCrUPu+/MhLHwmr3o/18xbuwdKZCSEZDCju1hFGZ+ZBXj+AtdOe9a6To/xeemK4oxd3o22BMHWH9eqqsTZGLmwaJNW13Qmf6S+QlLaqcEpBdc6AZ1XUha59iKSRcmLSujfZaw/lknX6f+EuwJpNNUvjQTl6xC1o61W7UP8CGQJB4Du+70+i/LNuVSbNcVW0ecnkDVqg87ScY+m3Kwv4VJJaQr37p9G3mNHkiG61H0B753j9Xsd74/fnO97ztggjkjNzLcbnabsShenx1Zb3jxxEmtrhk2pIFHahps+yutZcAaK3k6QDCsRIxAYthr69+bMiMwXxbn/WW5JgeWGx1DoMP+XLE3Ac26CUn/4UCoA/AsyrtqTavrS62bcP4oLqtfRXYRREV7ploOAEPsLPKajM=</enc>]]>
      </text>
    </request>
    <request code="Close" transaction="true">
      <text>
        <![CDATA[<enc>LQPUDPFmeSSKqSr3lqsWmeGDOORcc79JVYE1A0KHJBWftTZs4vH1vicdIvFg4ZtQUtdLjSQyGrB5X7AMcao55MfUQjpa2KF1Wau9fPwcSH7Tp3I+HP19rIK7eXPfT7eCDm+nI9BC2TpOwVIM37tpDGJ/HMzeWHL8WGXDrO/yd+qvz4NvjxmWOaMCOXvE8E9vgL0wEps3FYlWTARw5BXrWzaPqtEvmRRXCCe2p3cHWIh0Mmo2TRLDiBKD1RSof3Fx</enc>]]>
      </text>
    </request>

    &VoucherJSLoading;
  </script>

  <messages>
    <message val="msg1">
      <text v="Bạn có chắc chắn sẽ &lt;b&gt;duyệt&lt;/b&gt; các báo giá được chọn không?" e=""/>
    </message>
    <message val="msg2">
      <text v="Bạn có chắc chắn sẽ &lt;b&gt;bỏ duyệt&lt;/b&gt; các báo giá được chọn trở về trạng thái [Chờ duyệt] không?" e=""/>
    </message>
    <message val="msg3">
      <text v="Bạn có chắc chắn sẽ &lt;b&gt;bỏ đóng&lt;/b&gt; các báo giá được chọn trở về trạng thái [Đã duyệt] không?" e=""/>
    </message>
    <message val="close">
      <text v="Hủy/đóng" e="Close"/>
    </message>
    <message val="approve">
      <text v="Duyệt" e="Approve"/>
    </message>
    <message val="undo">
      <text v="Bỏ duyệt" e="Undo"/>
    </message>
    <message val="open">
      <text v="Bỏ đóng" e="Open &amp; Approve"/>
    </message>
      <message val="inputTitle">
      <text v="Nhập lý do hủy báo giá" e=""/>
    </message>
    <message val="reason">
      <text v="Lý do" e="Reason"/>
    </message>
  </messages>
</dir>