<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
]>

<dir id="s41Close" dirViewType="Grid" selectMultiple="Table" voucherCode="BQ1" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Đóng báo giá" e="Đóng báo giá"></title>
  <subtitle v="Xử lý &lt;b&gt;%s&lt;/b&gt; báo giá" e="&lt;b&gt;%s&lt;/b&gt; Quote Order"></subtitle>

  <grids>
    <grid table="s41" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true">
      
      <fields>
        <field name="so_ct" width="100"  >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="120" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
		<field name="ma_gd" viewType="Combobox" inactivate="true" width="100">
          <text v="Giao dịch" e="Status"></text>
          <viewInfo>
            <options query="select ma_gd, ten_gd%l from dmgd where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
		<field name="ma_ngv" viewType="Combobox" inactivate="true" width="100">
          <text v="Loại báo giá" e="Inv. Type"></text>
          <viewInfo>
            <options query="select ma_ngv, ten_ngv%l from dmngv where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
		
        <field name="ma_kh" width="0" hidden = "false">
          <text v="Mã khách hàng" e="Customer Code"></text>
        </field>
        <field name="ten_kh" width="250" fieldType="EX" >
          <text v="Tên khách hàng" e="Customer Name"></text>
        </field>     
		
		<field name="ma_noi_di" width="0" hidden="false">
          <text v="Nơi đi" e="Origin"></text>
        </field>
		<field name="ten_noi_di" width="250" fieldType="EX">
		  <text v="Nơi đi " e="Origin Name"></text>
		</field>
		
		<field name="ma_noi_den" width="0" hidden="false" >
          <text v="Nơi đến" e="Destination"></text>
        </field>	
		<field name="ten_noi_den" width="250" fieldType="EX" >
		  <text v="Nơi đến " e="Destination Name"></text>
		</field>		
		<field name="ma_hang" width="0" >
          <text v="Hãng tàu" e="Carrier"></text>
        </field>
		<field name="ten_hang" width="250" fieldType="EX" >
          <text v="Hãng tàu" e="Carrier"></text>
        </field>
		<field name="ngay_hl" width="120" dataType="D">
          <text v="Ngày hiệu lực" e="Effective  date"></text>
        </field>
		<field name="ngay_hld" width="120" dataType="D">
          <text v="Ngày hiệu lực đến" e="Expiry  date"></text>
        </field>
		<field name="ma_nt" width="0" >
          <text v="Ngoại tệ" e="Currency"></text>
        </field>
		<field name="dien_giai" width="250">
          <text v="Diễn giải" e="Explain"></text>
        </field>
		<field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="120" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="100" fieldType="EX" >
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      <buttons>
        <button id="close">
          <text v="Đóng/Bỏ đóng" e="Close/Cancel Close"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="find">
          <text v="$FindToolbar" e="$FindToolbar"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="refresh">
          <text v="$RefreshToolbar" e="$RefreshToolbar"></text>
        </button>
        <button id="freeze">
          <text v="$FreezeToolbar" e="$FreezeToolbar"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
      </buttons>

      <script>
        <finding>
          <text>
            <![CDATA[<enc>VpC37KCPCW2+PzBC2PxOXM1jcLg2JQv/ep5+NtJQPWvguIVLAtpoEDUVf9EITgwk3GkROae1tKM4NQ6uH7nt0KRcaGN332E4IIIQwyZFgx0OPvxfqy/Ttr0kRNkSOh/9kr9Z6DF0/5lu8INByZj6mme1dqUaSq6Zu2G9aQRD7dcLqT3vG271u5BhWeGN7RXYUd6nqqROm9Ro5r/pet1wS+MtlQZLFZSyF0lwUUSFg5cLyPyJx/+TBaf9Q3FPhFPMvB5xMU/jWrHie8cRq6/HLbo2nMIYatDorrPPlBOdERTG1SIqNwG19m416ys94td9RQSGsCcX4w4z2UHOAfkD2upikPco+qmadk0MX1d2B1ojfmTe490c/AjAVg3RqbLvKO50na+FJ6viAF8tCWRbVcZmUK37Focv0P+4sKVJpdLrP24HSTdDHme6VszFZTYFLIrxMDQDKBZh//nj1cnwINkeZlOPN6CBGSukaMGqKeJHpwbolYPmQQlDla3XKcT2lc9uPVwuqomIsXzoHQSHiQ==</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>RHvQFF3mi+iQ+U21Y8fNc9y976It1uMTMIRPH20bAFnvfIRkackzi4wEhqLOlaWMmCWBn3DPM2GS6lZ8nlncaNPfae+/30AYbIZtecNeWJSR/G+Cl+o1PfMaIzrxlDCiynTVEYbUJXX840Xfav7wmwePksKaetubyzUIcwhNTkxRM3TG7fCnqOeRMAf62iuUTmCqcByvelOsOCU4g7cMk8wskoGWtaROhTEi+GaZMNPUnx/2ygNUfQAKX95QUX0C9bkaaDivzbJamwZP6kvYo5j7Lbvqmb4usYkAmrXAcz9mAKGiRqVEcK6t6Y8/11L8DJ12t7/vBqqqMOum3sSO4oKq80KG+heI4LUSDP/jzOQcVoNMdlnLUSu5kS7iaOLLWeiO+iLOj+hUpOuGLoJABw1tmvZqN5tKL9qmSQj3xiLpb9QNwKf1oEllgmvtGxUPd5kyTtUnUwqDt0jCtYDsWkdz8E8hwBHZ1fWcccLBPjE1zmAkgmXIlK3kgii2wyhcADzxMssXrJxnDQfrAxzvbdwFFtJXRRxUKjT4Zx3/QQJLpzqof9WS6G9MWY1fpu0ef7Uf9E5E0MOJI7lnoP4Dp6T7dfWxHtu3TdaQdwCVLEdsQZcWhWswtyGMYFai3qDvGRrL/cyDbnBw1AC3GwbDThLmMZ1Js8zRXEC6RHzCQ2CYefM8PLRgo8ccsVdHfY9CrqeprhQcqVec1nbACXCvig==</enc>]]>
    </text>
  </js>

  <css>
    <text>
      <![CDATA[<enc>wWmvqZXYbLrRfwnztyX4ZWvBnlYWH9u5j5YmFumARmFE3+6fHyBPhmBC3p7zfguMPQjJQ8+0ADrfMZD5TY5bby9kjfKZDNacocXAxWWt1xIAqZJlRAlpDd+LUV51x8iKWoBWb7oj9qbl3ntBBADKLkHleP8OBNYCpffSA9xB/tQeZhEQ1XD5NoH3wpPkjb8DZpdX9n9bv5hUmpk0iv8hTflf3L6l79RDNsx+AYfLpyzxbKxSmKotE9a4KTdF410XQ6JzvvMfW872B73eQ5tEVWuPJXvkfRRUNUHn+CaxSckD11znkXdFO3tryMNFpF4F5KScZijx23+ZmHXAxs3sjXtjPymgtI4NWb4ckEskTYo4Gc18wMUN2+xobkomV6Cn</enc>]]>
    </text>
  </css>
  
  <script>
    <request code="CloseDH">
      <text>
        <![CDATA[<enc>Kz4+sqAq7IhQ1dYu3KNmfMsRqfRgnW16tN6pE3kwRoqXVluADgZIvrHkLwuJFQbrPo5ii172RsiOxopxUKK0nFeaEK1FfLP+oGES58GdInR8U5C0sOf3+qh+uKaJLhERGTJvBf9cCFZzgIy5+mBUhM3YOhzQN3DuAXpb5QH6tEPSpUXOH42F2SundLfFa9jOIYucbXtH3MbANFE+WidT6w08NzuYAR0SE+ObcYWVPPMfmnDqB78zTYwSWxgSYQGzuDly0Pm2eKQS3KIf29oB+wWZsEn3ylmFIYQ6QpHGSueNrPwBw7xxLP0obWpJvEASFIbXLqV6qjH7hWfZ439vZuC7CPnEN5Rk8OecxDw6KUc=</enc>]]>
      </text>
    </request>
  </script>

  <messages>
    <message val="msg1">
      <text v="Bạn có chắc chắn sẽ &lt;b&gt;đóng&lt;/b&gt; các báo giá được chọn không?" e="Bạn có chắc chắn sẽ &lt;b&gt;đóng&lt;/b&gt; các báo giá được chọn không?"/>
    </message>
    <message val="msg2">
      <text v="Bạn có chắc chắn sẽ &lt;b&gt;bỏ đóng&lt;/b&gt; các báo giá được chọn không?" e="Bạn có chắc chắn sẽ &lt;b&gt;bỏ đóng&lt;/b&gt; các báo giá được chọn không?"/>
    </message>
    <message val="close">
      <text v="Đóng báo giá" e="Đóng báo giá"/>
    </message>
    <message val="unclose">
      <text v="Bỏ đóng báo giá" e="Bỏ đóng báo giá"/>
    </message>
  </messages>
</dir>