<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="s42Hold" dirViewType="Grid" selectMultiple="Table" voucherCode="BQ2" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Xử lý báo giá treo" e="Process Quote Orders Hold"></title>
  <subtitle v="Xử lý &lt;b&gt;%s&lt;/b&gt; báo giá" e="&lt;b&gt;%s&lt;/b&gt; Quote Orders"></subtitle>

  <grids>
    <grid table="s42" fieldKey="id" order="id desc" key="xstatus = 0" allowFilter="true" allowOrder="true">
      <fields>
        <field name="so_ct" width="120" link="V" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="120" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
       
        <field name="ma_kh" width="120" >
          <text v="Mã khách hàng" e="Customer Code"></text>
        </field>
        <field name="ten_kh" width="250" fieldType="EX" >
          <text v="Tên khách hàng" e="Customer Name"></text>
        </field>
        <field name="ma_nt" width="120" >
          <text v="Ngoại tệ" e="FC"></text>
        </field>
        <field name="t_tt_nt" dataType="N" format="FCAmount" width="120">
          <text v="Tổng tiền" e="Pcs UOM"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" width="120">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="120" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="120" fieldType="EX" >
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="ma_ct" hidden="true">
          <text v="" e=""></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      <buttons>
        <button id="approve">
          <text v="Duyệt" e="Approve"></text>
        </button>
        <button id="cancel">
          <text v="Hủy" e="Close"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="find">
          <text v="$FindToolbar" e="$FindToolbar"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="refresh">
          <text v="$RefreshToolbar" e="$RefreshToolbar"></text>
        </button>
        <button id="freeze">
          <text v="$FreezeToolbar" e="$FreezeToolbar"></text>
        </button>
      </buttons>

      <script>
        <query>
          <text>
            <![CDATA[<enc>ut7bmtX51o7ohlkZy11sVIaZnUwHEM+ebZUTVuvKujT003xHFhXk+bfhdo+bOLeOc6q63u3F2aexGLbLnl1qTTXhLrNlXeSxVkMrIqXqOIV0K//tFN5voZDEwxmggErUPzh+qFPUrUMIk3h+Ki6PotHKs2S1UZVa98zmFp4o9+J+uINWCG/0sLwuHcsDKIU19OP6Sc81dVTM/vl6dUUBlcpGftcyDenTxwFE2b469gB46nBpzJU1ETEPwEwoY+NGyJC2fwU1SXrO9LnA5xSiMg==</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>BboJkQKVEE0/E/5UJ6O4WSqawqMbE98dR7qt97RubYx02YoQo5lZgyoErzh+f3faNe8Vh3K/8XImh27GyIp/pvzvXHkpHs21/d4HxslniaK0BQsIdAnf+5/GX8yDCWUFnDLd7Qy9dYIQ81Vildw1kI0c6xl77UFZIvDUw35f7TqAKhpNaM1y10KdSJ06itNsN+mIajEXEbABABDJHroGFzDwlxAzd1tWfih9CTfcWKB/N5P3rgw7fxLFnduiZoL9LEUAZGeLDfGJIq1Kqt5GKJyzQUICkz2fbahl4dsGk50Tea+gPbmmYeCRUwravYYb/vczkK+yhr9LbSZLPyNJFYn++kDnNJXCn9LpaR862mG1P10MKS0VHPmHz1wIzZvpMIdfKmpvBwpznK7t9U9t/foAYIkxnIDMvlfozyUEwT6ErHQqk3A4EbqW2/YffMaMzJIdjlZYBavV4b5PKVvcZeIC+09RSRlO82TNSllYlOiMbh+Iuqva0Mk+chjSXQeadHPGr2mrdaCc5ZQzqx1IdNFpfeg61nek+OGDVRqH3j05tp6g7efbOJ++Ln2UhFxetMicJdfbYVWHvUNpzWmcExqoaifG7H/bb1n6yjC83mOO0Q+eaXV+0WBVyJQOmxzhrw20uCBKobKdqn9j82UfHQ==</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>6CMkmSRkyZV4MrafDhzUmTW4Up1BLwzM9qpxLnnzJn2wLtSrKNAaAxkuvPY6UjUi6zXj9mqAvUJqxV/OrXMs0hk/GpXXmaQx9S7Hb9v5Ls5WiTOZs7JlpCOH/SB8ZfjkODa0Kte5TYWoYv0DVeERxjdJEyLiXNFrYxLJCuNVaezz9d88tixXzv+1sO17NNJwb9APLczDTo0xu2ZnzMOoiu13ErUV2OPT2ounkD4NWOOHG1JRwx72imijcoYv0ysL8w4eFVzVbV6RYWFgZRNxhDkctnENV4h/s+/RR5G4ByLSehc2y83Y4ZEgRdZRS4lcPE9Ys9GRBNgkosB9/cdOLCZm7QzJRe7nksolWv2Z6v5fZs83mjXnDh/HwvelX1Vuk5GrcwW+lmFZRWAwAKJdT0azWihxEmhecUF49l9aJ25s/UVxv0VqlxQpfh5pzIkmyEX4NyiJ3mP+RAD1Md80oIGy7F9ExrKXCOg4cgSCBfmZRC4mCbtYW3M4pNXr3zk6a+8PTB7Cfn/68ief5DO8a0EsUW/IAHYJzo6ik7KLK3VhL/Fiih3UvaaZxvYWyJocWCcLouE8Bn/gbjsBwmdG6KZwk3wBIVE3Wq1+e0BS+jmJZrgGU610hwvVDBl5a++OK3NxxRzgrhzioOMKzMkOP5fIDChLqqf44MfkFyPp3r7e6CJO6GyLXP1XJ3ZMMcpJRlZOYHY3S7tsA4YpH13kHbgGfHcOvZL8RjUS9YldfP0tGQDFS/jhj92V3BDK8NEhQtzwR6qYkeX6JARGafhxz9JjN28m/A3vx3PxIVRruRFuIdxI1nk3IRsvvFnwGchdVy9Tk8uHZ3qK64Y0OzGb+9YasXm92BhY82kvtnEfX0zDzfNcMobUZM0qKUOPF1JJ5dM71Yslad3VSnipKzPeYPv+FCfOpS8a1mGxHXXAz2g=</enc>]]>
    </text>
  </js>
<css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
  <script>
    <request code="Approve" transaction="true">
      <text>
        <![CDATA[<enc>evLiw1T4JcaUh5PhlvA1OnhlVb37ZOqtvp9Zb4UVaq/ysvXcn2Pw1M4XjFIDwsG9MI87BRyLwVF4xX8Km8KmT8+TxrHJ5YFz0uV7D1N+7smQjlJvPYDNKI8Qm1temF60Ksoe5t9AyqO08+M/XBbyFcb8oW1GF2bPLVUuSz3QUujcaUtXa/VPwaJwzA5sNxO9YzLb8ltYN0BRWZeN496sMng4NTwtkpskgfinc9who1Br9LsO79kqynoOHQf2xDnRplBrEGeNsTCIcEXByrhQb8VSS1nlkxri7vyMh5/wA/m7P8nRHxNPt8lEfV7/z3X6KTPCGb3mYqitwu/Y9mlGX48jBPe25X04cTXrjZlHaDk=</enc>]]>
      </text>
    </request>
    <request code="Close" transaction="true">
      <text>
        <![CDATA[<enc>JcZUQ4IGFS04ndnhtJMqgEQDlkHa+7NLI5WzfnyPrH4DLKjPjccKVNC5uuhwV0jRx4C7JryZfahlpNODPpWWFqpscBNTxRrWvuRa08ssJA7lV9CAohKe9ZP2n1L12fNFs9X8gFU7IIIg0O0td6my5VWuGz5D28WDmal/fWsDVOaArPAa6QmCSwJl9wG8Df3ujcWllk1zRMZaBjTzIcraIl7fKweXpqJx4pwdrWr13eZoFXs9fySna+4MzwbJ1b9CI5eUTjyLuSgOqT32fSvRHg==</enc>]]>
      </text>
    </request>

    &VoucherJSLoading;
  </script>

  <messages>
    <message val="msg1">
      <text v="Bạn có chắc chắn sẽ &lt;b&gt;duyệt&lt;/b&gt; các báo giá được chọn không?" e=""/>
    </message>
    <message val="msg2">
      <text v="Bạn có chắc chắn sẽ &lt;b&gt;bỏ duyệt&lt;/b&gt; các báo giá được chọn trở về trạng thái [Chờ duyệt] không?" e=""/>
    </message>
    <message val="msg3">
      <text v="Bạn có chắc chắn sẽ &lt;b&gt;bỏ đóng&lt;/b&gt; các báo giá được chọn trở về trạng thái [Đã duyệt] không?" e=""/>
    </message>
    <message val="close">
      <text v="Hủy/đóng" e="Close"/>
    </message>
    <message val="approve">
      <text v="Duyệt" e="Approve"/>
    </message>
    <message val="undo">
      <text v="Bỏ duyệt" e="Undo"/>
    </message>
    <message val="open">
      <text v="Bỏ đóng" e="Open &amp; Approve"/>
    </message>
      <message val="inputTitle">
      <text v="Nhập lý do hủy báo giá" e=""/>
    </message>
    <message val="reason">
      <text v="Lý do" e="Reason"/>
    </message>
  </messages>
</dir>