<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
]>

<dir id="s43Close" dirViewType="Grid" selectMultiple="Table" voucherCode="BQ3" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Đóng báo giá" e="Đóng báo giá"></title>
  <subtitle v="Xử lý &lt;b&gt;%s&lt;/b&gt; báo giá" e="&lt;b&gt;%s&lt;/b&gt; Quote Order"></subtitle>

  <grids>
    <grid table="s43" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true">
      
      <fields>
        <field name="so_ct" width="80" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="120" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
		<field name="ma_gd" viewType="Combobox" inactivate="true" width="100">
          <text v="Giao dịch" e="Status"></text>
          <viewInfo>
            <options query="select ma_gd, ten_gd%l from dmgd where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
		<field name="ma_ngv" viewType="Combobox" inactivate="true" width="100">
          <text v="Loại báo giá" e="Inv. Type"></text>
          <viewInfo>
            <options query="select ma_ngv, ten_ngv%l from dmngv where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="ma_kh" width="0" hidden = "false">
          <text v="Mã khách hàng" e="Customer Code"></text>
        </field>
        <field name="ten_kh" width="250" fieldType="EX" >
          <text v="Tên khách hàng" e="Customer Name"></text>
        </field>     
		<field name="ma_noi_di" width="0" hidden="false">
          <text v="Nơi đi" e="Origin"></text>
        </field>
		<field name="ten_noi_di" width="250" fieldType="EX">
		  <text v="Nơi đi " e="Origin Name"></text>
		</field>
		<field name="ma_noi_den" width="0" hidden="false" >
          <text v="Nơi đến" e="Destination"></text>
        </field>	
		<field name="ten_noi_den" width="250" fieldType="EX" >
		  <text v="Nơi đến " e="Destination Name"></text>
		</field>		
		<field name="ma_hang" width="0" >
          <text v="Hãng tàu" e="Carrier"></text>
        </field>
		<field name="ten_hang" width="250" fieldType="EX" >
          <text v="Hãng tàu" e="Carrier"></text>
        </field>
		<field name="ngay_hl" width="120" dataType="D">
          <text v="Ngày hiệu lực" e="Effective  date"></text>
        </field>
		<field name="ngay_hld" width="120" dataType="D">
          <text v="Ngày hiệu lực đến" e="Expiry  date"></text>
        </field>
		<field name="t_tong_trong" width="100" >
          <text v="Tổng trọng lượng" e="Voucher Number"></text>
        </field>
		<field name="t_tong_khoi" width="100" >
          <text v="Tổng volume" e="Voucher Number"></text>
        </field>
		<field name="ma_nt" width="0" >
          <text v="Ngoại tệ" e="Currency"></text>
        </field>
		<field name="dien_giai" width="250">
          <text v="Diễn giải" e="Explain"></text>
        </field>
		<field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="120" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="100" fieldType="EX" >
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      <buttons>
        <button id="close">
          <text v="Đóng/Bỏ đóng" e="Close/Cancel Close"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="find">
          <text v="$FindToolbar" e="$FindToolbar"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="refresh">
          <text v="$RefreshToolbar" e="$RefreshToolbar"></text>
        </button>
        <button id="freeze">
          <text v="$FreezeToolbar" e="$FreezeToolbar"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
      </buttons>

      <script>
        <finding>
          <text>
            <![CDATA[<enc>BQuxIwv5i26yrmFPa/cljyOXTM+xwVn6ZtEEkaWpx+V3PMl0mv7iM/qpvZK7xm5wFF35wdIKCbvm3Zxmx6WMb/vGC9vw8OugSRQeu+2TjKLVnEcAmF91bKS69CieeaymzWL4xMBi/eFVNg0oTKNJqMHSc5RFl+7C9HXy8ur0SYEXZOTdwDD3SVndljOyjHnMFydsOhR/ii9sZ9On36Yqaa1ZGEEIhMHMfbcax42f6tUZzF1J2O72nSqyA5g30O2Bq+IRItqVJi8y1Wlg/aYIqMCwpa5bbvCHhfC8XgowWQc4wS7WiD5AQjjSeBLjtuQU5PGuXpPaAK4jJHlmlW2Il1xBgVlZHwxC87FnFyCetl/6vleXNk+XQR+xhENO/E01qERgoSLsTOh8TenQy5wpaGCFdO0AKa6kMm7lJ8x5JTG6zxfbUv1DPGJDHjLlBdhzmhZWlWYstClU4VP56rxUnbSmpJ4O2KwB5XJoK2hK6EgjjcN7r7EEahHW2qbnZ68SFC+VmTJecdSiU2JSQ63JkQ==</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>RHvQFF3mi+iQ+U21Y8fNc+7GqHT7wTgGfYVJlD1PEmQELmnvP4mxBe7R8+7dr0l2r7MeMocBjpUxHGo7CXvt4HcGfyP4TQi87rCyX+J7kj5QDh5NX4ILiMXTx1u1Pw8J5yk9BADEj3Yux5ScC8uisssJOPkJWSvef52DBHsOU91hyBwJgUzerrVoNRkR1w1iV0ikMPY2g9bjF0XNmyGvwCt9XWgWdMqxPUHaRzUrjQyh+6fxOYceBsA9mLT8uplRYSkbDCzyh3Exx/NQXSxC/LhCurZ6GF4ykzy5dAs/cPw9OhuJw0P+6f4fU67VK8NxPd+YuZ2qH1aGTyslMFHikSEvBdAdd1qYQ/keEEqVt+CvhxQgjEpiVV7DC/bhiCxdmeR0rcZlBDvkaxQM8aYrxq1btK5nU0oEBWQXQckqhCIf8dZ5J2jJ3ZC9I1MzeAhzSw4fZx74infW+wrHJx+TUamS0o26tsLSgHEGgawyLusRiufNG3eiMWEbZyeuVD5B17TYF/AXM8RdQwGMuzlGdSV83hc9vrD6YTcphQbS4CukHCZd7AEP2sDEwqIPiIpiILHXjFqSZHWDqEks8iFkAbvocTZeidaAYj9v/htydY2coqFYlYuFNnXrgAK8bnSU5eXLnX0iEfPvEsUrU2zloLaWh3M+SZ+mB9v0ocsQXGvLq1xoHuWdjtlYxseY5kyCyinbfqCCKRPlJ/beEyiVJw==</enc>]]>
    </text>
  </js>

  <css>
    <text>
      <![CDATA[<enc>wWmvqZXYbLrRfwnztyX4ZWvBnlYWH9u5j5YmFumARmFE3+6fHyBPhmBC3p7zfguMPQjJQ8+0ADrfMZD5TY5bby9kjfKZDNacocXAxWWt1xIAqZJlRAlpDd+LUV51x8iKWoBWb7oj9qbl3ntBBADKLkHleP8OBNYCpffSA9xB/tQeZhEQ1XD5NoH3wpPkjb8DZpdX9n9bv5hUmpk0iv8hTflf3L6l79RDNsx+AYfLpyzxbKxSmKotE9a4KTdF410XQ6JzvvMfW872B73eQ5tEVWuPJXvkfRRUNUHn+CaxSckD11znkXdFO3tryMNFpF4F5KScZijx23+ZmHXAxs3sjXtjPymgtI4NWb4ckEskTYo4Gc18wMUN2+xobkomV6Cn</enc>]]>
    </text>
  </css>
  
  <script>
    <request code="CloseDH">
      <text>
        <![CDATA[<enc>Kz4+sqAq7IhQ1dYu3KNmfIK0/iwT+vNLsfnevulLlAC1nRAwS9+S0k2FBFtbp26pXc+R6EFkpggTZoPFzUthrG6LjPmjRwqNLHMaTNiLcdMKZoPmlTTM/xNA1Q6Pksd5utXm1sYoe8TDJmu7igeNCU9rpRbjLtXHlBJq+mKoOmmH+Uv/bKvpgF9yjcTjNl6q5FuZb+ABHVAFdeCQpMyjTq99BbtA1HkISqKzGowYgY0h2fnCRQyaWBjZ9N3cJuFk+01wMd0sxjy/vkUSJsFPEII28mCuH3goDoB84K8xN3s6P/gf4uNZVzRje9o1m1QW450YwrjLwPNXLsivaNDna7AlxDHCTWAFMz31DtnhpiQ=</enc>]]>
      </text>
    </request>
  </script>

  <messages>
    <message val="msg1">
      <text v="Bạn có chắc chắn sẽ &lt;b&gt;đóng&lt;/b&gt; các báo giá được chọn không?" e="Bạn có chắc chắn sẽ &lt;b&gt;đóng&lt;/b&gt; các báo giá được chọn không?"/>
    </message>
    <message val="msg2">
      <text v="Bạn có chắc chắn sẽ &lt;b&gt;bỏ đóng&lt;/b&gt; các báo giá được chọn không?" e="Bạn có chắc chắn sẽ &lt;b&gt;bỏ đóng&lt;/b&gt; các báo giá được chọn không?"/>
    </message>
    <message val="close">
      <text v="Đóng báo giá" e="Đóng báo giá"/>
    </message>
    <message val="unclose">
      <text v="Bỏ đóng báo giá" e="Bỏ đóng báo giá"/>
    </message>
  </messages>
</dir>