<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucherNotPrint.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="s51" dirViewType="Grid" dirObjectType="Voucher" voucherCode="TG1" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Tìm giá vận tải đường biển FCL" e="Find FCL Sea Freight Rates"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>

  <grids>
    <grid table="s51" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true">
      <fields>
		<field name="so_ct" width="100" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="120" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
		<field name="ma_gd" viewType="Combobox" inactivate="true" width="100">
          <text v="Giao dịch" e="Status"></text>
          <viewInfo>
            <options query="select ma_gd, ten_gd%l from dmgd where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="ma_kh" width="0" hidden = "false">
          <text v="Mã khách hàng" e="Customer Code"></text>
        </field>
        <field name="ten_kh" width="250">
          <text v="Tên khách hàng" e="Customer Name"></text>
        </field>     
		<field name="ma_noi_di" width="0" hidden="false">
          <text v="Nơi đi" e="Origin"></text>
        </field>
		<field name="ten_noi_di" width="250" fieldType="EX">
		  <text v="Nơi đi " e="Origin Name"></text>
		</field>
		
		<field name="ma_noi_den" width="0" hidden="false" >
          <text v="Nơi đến" e="Destination"></text>
        </field>	
		<field name="ten_noi_den" width="250" fieldType="EX" >
		  <text v="Nơi đến " e="Destination Name"></text>
		</field>		
		<field name="ma_hang" width="0" >
          <text v="Hãng tàu" e="Carrier"></text>
        </field>
		<field name="ten_hang" width="250" fieldType="EX" >
          <text v="Hãng tàu" e="Carrier"></text>
        </field>
		<field name="ngay_hl" width="120" dataType="D">
          <text v="Ngày hiệu lực" e="Effective  date"></text>
        </field>
		<field name="ngay_hld" width="120" dataType="D">
          <text v="Ngày hiệu lực đến" e="Expiry  date"></text>
        </field>
		<field name="ma_nt" width="0" >
          <text v="Ngoại tệ" e="Currency"></text>
        </field>
		<field name="t_tt_nt" dataType="N" format="FCAmount" width="120">
          <text v="Tổng tiền" e="Total amount"></text>
        </field>
		<field name="dien_giai" width="250">
          <text v="Diễn giải" e="Explain"></text>
        </field>
		<field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="120" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="100" fieldType="EX" >
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

	  &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>+cqRnw3xIxP6k5U1nfeaCBvvlP7C17S9ZWZTy3Rkb5cVtFhqBeSRk/eJ4SSGV6OpH+gAJz6INi69d6QaJe1JAHrK2z/qtUA/7h8JYU3bdXJjt5KMCRdwZsVbpxx/tKJw6k7fcdhJgm9A31l2bNuXGgqJxpS4yCrAh6lmen4ZOcAVCEH7ZfOc6kXUvkYM41epurcPQvcpGfW6LYrt3kCqCGzY0d8wIkBSYCIKd+FE64oZ96SCqm7oeCO/dSdTwN2aDxsm/CzHGklZ/DCucxzBFy2EHqeaVcESyqbeN8e3ASi2lB4qn2eKdWq1eM0ot8yua92RWalzG6zqr/VdAmVrEA==</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>ZXvSnett6mObBWPIHuHKh+PZTb4uMrjJSK+HrJcJRVfFRS6du9+6FdYthhk8EKBCtg2UUleZk7Y5+wFMCDhshw+O1TjxAtlsaA5NJhqvWQlUg2F8yPXvssTP1/jwf8EoRpL1S7WsUXqNNLUTGLg71p69MWA04tRn7Ruq67Qqwltz+1Z81/l9ZbDWL+y2GVf0uoQs4TMeFY54AwjTVM6SA5uh+vlijZAK5d9aMWWlTOHZc9Hyi7KiECXOszfsLw7T2SUvaOraCPmlhOBS1azr6yevgFEcHRCJc2scBTLmDWBQl71lwnjKTdUYbMS12wdBnQVBgiw153PfKSaBQTg4Au8Hk0azNvVmahfnr4sAco7LdA24xCWcH+/cvneXQlqRo+2dNzPJwltsPqOANYHct5TRQnd8Ub4oLSzVURJSY20yNrdygFgcNfyuAxc2fCVYHQocNsED/6ug+Gt3hs7aNRQGK2QmA+2bCIq6YMTW4+YV9pcVH2qxh1MoP/4xSIHLJAnNdbREyJ2JMZ3BSvfckyAyvE1CR/K5x7MNV9Yt7VIOBqV6dgKUvb5RctCkRQRixZi26CxaM5cGP2YlJVO98gsnO2fKsB7Blrm1k3569TS7jiJ6wDv4bH7h0IB60Hc/kXFKxLzIzkbxo1LTkLkKx0GTvRJ5eM0UBBEePPiqxNK+MySeZ3LNEyhXXajzHhFK</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>5wErx4q93yz4A4Cu1Ug/IzC490NdRhuYU9GNUXk5yaxG2rCf33MPn1b2jXq1gCiFSlJfZdF1hMvCfoXTNr597CbmH4QjD5wMiINXbbBv4rbjftp2ftP8UdFYO/BJM2jPeHhgvx4PwwPav0mHnEbR9g5sUJCpAnQYVgO0B4xC/p6TUuzYXfgULzppf+XzChItuvjeR6tLMeoIZ7Lk6ICDEA==</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>

  <script>
    &VoucherJSLoading;
  </script>
</dir>