<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucherNotPrint.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="s53" dirViewType="Grid" dirObjectType="Voucher" voucherCode="TG3" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Tìm giá vận tải hàng không" e="Find Air Freight Rates"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>

  <grids>
    <grid table="s53" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true">
      <fields>
		<field name="so_ct" width="100" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="120" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
		<field name="ma_gd" viewType="Combobox" inactivate="true" width="100">
          <text v="Giao dịch" e="Status"></text>
          <viewInfo>
            <options query="select ma_gd, ten_gd%l from dmgd where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="ma_kh" width="0" hidden = "false">
          <text v="Mã khách hàng" e="Customer Code"></text>
        </field>
        <field name="ten_kh" width="250">
          <text v="Tên khách hàng" e="Customer Name"></text>
        </field>     
		<field name="ma_noi_di" width="0" hidden="false">
          <text v="Nơi đi" e="Origin"></text>
        </field>
		<field name="ten_noi_di" width="250" fieldType="EX">
		  <text v="Nơi đi " e="Origin Name"></text>
		</field>
		
		<field name="ma_noi_den" width="0" hidden="false" >
          <text v="Nơi đến" e="Destination"></text>
        </field>	
		<field name="ten_noi_den" width="250" fieldType="EX" >
		  <text v="Nơi đến " e="Destination Name"></text>
		</field>		
		<field name="ma_hang" width="0" >
          <text v="Hãng tàu" e="Carrier"></text>
        </field>
		<field name="ten_hang" width="250" fieldType="EX" >
          <text v="Hãng tàu" e="Carrier"></text>
        </field>
		<field name="ngay_hl" width="120" dataType="D">
          <text v="Ngày hiệu lực" e="Effective  date"></text>
        </field>
		<field name="ngay_hld" width="120" dataType="D">
          <text v="Ngày hiệu lực đến" e="Expiry  date"></text>
        </field>
		<field name="ma_nt" width="0" >
          <text v="Ngoại tệ" e="Currency"></text>
        </field>
		<field name="t_tt_nt" dataType="N" format="FCAmount" width="120">
          <text v="Tổng tiền" e="Total amount"></text>
        </field>
		<field name="dien_giai" width="250">
          <text v="Diễn giải" e="Explain"></text>
        </field>
		<field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="120" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="100" fieldType="EX" >
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>+cqRnw3xIxP6k5U1nfeaCBvvlP7C17S9ZWZTy3Rkb5cVtFhqBeSRk/eJ4SSGV6OpH+gAJz6INi69d6QaJe1JAHrK2z/qtUA/7h8JYU3bdXJjt5KMCRdwZsVbpxx/tKJw6k7fcdhJgm9A31l2bNuXGgqJxpS4yCrAh6lmen4ZOcAVCEH7ZfOc6kXUvkYM41epurcPQvcpGfW6LYrt3kCqCGzY0d8wIkBSYCIKd+FE64oZ96SCqm7oeCO/dSdTwN2aDxsm/CzHGklZ/DCucxzBFy2EHqeaVcESyqbeN8e3ASi2lB4qn2eKdWq1eM0ot8yua92RWalzG6zqr/VdAmVrEA==</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>2/rnSyY+2DqWiz2aeKbhKeRA0SzUpbBSZN9rOqpasDI//rgp4rTFq4zNB0dey+LZQQJiiOCXaQofNduF26wO0QfUsZ1XwPtyC1cuDPqo4gksD07L5mUbwdyzO84xb3We1Hc114GRH06T9ZjN2Uy7K+9WPJ6wu5ijnO5tev7BUktLwvUpENhItv9Mqa/7uXhbBryhffN75xLoZjGCHCs0wh5GKLO59F77Mjvy8DUZOwXPu/JA+3hMuFCRbxxNkxg5jlIr0rp1MKvKetw+l4s0bvHQt7MoqlvG9RR9cRwkbOgbE0ECeajNN1c/zxQ4ZVFiGolmXFo14xUkeTziCsjnbueXJ6+LK0EBbD/19JDPKrbofNkYw1IwMaWkowPj2dpiqS0mMFYeHOfSFxUhnIIDTYTYMp7+4zTvKxUhQM///wR2qPRbUwnJmIZ67bfPZ4Abwp4UH6mlnVoc8N+3YSAahOGYVVtakSfBK5XiG7P2rdbJ3BsFGRNt3ockuBoeru+wXlF9DjqauKZtXmHxYh1u1UoTO92W1UvM+Zqz3xbDcucAdx07TOmlmGhkYUlyNz2snry+7A/A9who8EFIF9kWZR/EEk2ixAIpu3eiqLJSNK0CEOMt4ppVhHzdkBN7KFtCpgNHtSqCkTMuF/t5EjkMmp8iAsnRV+zwsFm3tGMNQwxh1zOJ2Z1X35zd7nSW5lw0</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>hLiBLm3iF/aJj7eF2MoRKiBvkRp2E3JltYgPGsydv2Lhszs8XzD/0GVYBTyXVfpsSMzZmxz8Dz+OQh0npKgBGe/GJ0YNVMWEFkQpBjGHrzTHFRG06M63qur/L703QtvtIh0XdgO5El1ZaYoPd/KCzZB8ZycWE6DdhylGvTqGzol/zb01RBQqUVPiTBuW/QOIFbFEqKGsQVBZlKKL0HYxJg==</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>l1+ZpBwPNdbxY9xG7sW/noXd6d1d5wpaL6kn/VTUSegbx/kt9JvwxDpCUwlonqQBJ//lYsncsJ7z0g/yGcrUxp/UAuJAnZ4vUhrggPt7r5/nJtLXCfJJMJLEJ+k6hB1lg9FlaMe5gGDHayyqbPFEBbvifA01s5o53PgDeWqAGQIB9Lz/VJMDreEBIxAeT5XtFL+StZEdrRZTN+bzxyp5fmCM0yGjzvuOzpoerFtUgS8EZFcBx61SAxaFSsJ0ALacYAgnsEs9sIwr8/55wDvNAfrKC3ge1rKAr8AttrX0NBwmhZ/KJbEGrKB/aueoMbbz</enc>]]>
    </text>
  </css>

  <script>
    &VoucherJSLoading;
  </script>
</dir>