<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="s61" dirViewType="Grid" dirObjectType="Voucher" voucherCode="FCL" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Quản lý tổng hợp đơn hàng" e="Order Total Management"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>

  <grids>
    <grid table="s61" fieldKey="id" order="ma_ct asc, ma_job desc, so_job asc" allowFilter="true" allowOrder="true">
      <fields>    
		<field name="ma_ct" width="80">
          <text v="Mã c/từ" e="Voucher Code"></text>
        </field>
        <field name="so_ct" width="80" link="V" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="100" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
		<field name="ma_job" width="100" hidden = "false" link="V" >
          <text v="Mã job" e="Job Code"></text>
        </field>
		<field name="so_job" width="100" link="V" >
          <text v="Số job" e="Job Number"></text>
        </field>
		<field name="ma_ngv" viewType="Combobox" inactivate="true" width="120">
          <text v="Loại hóa đơn" e="Inv. Type"></text>
          <viewInfo>
            <options query="select ma_ngv, ten_ngv%l from dmngv where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
		<field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="ma_kh" width="120" hidden = "false">
          <text v="Mã khách hàng" e="Customer Code"></text>
        </field>
        <field name="ten_kh" width="250" fieldType="EX" >
          <text v="Khách hàng" e="Customer"></text>
        </field>		
		<field name="ma_noi_di" width="0" hidden="false">
          <text v="Nơi đi" e="Origin"></text>
        </field>
		<field name="ten_noi_di" width="250" fieldType="EX">
		  <text v="Nơi đi " e="Origin"></text>
		</field>
		<field name="ma_noi_den" width="0" hidden="false" >
          <text v="Nơi đến" e="Destination"></text>
        </field>	
		<field name="ten_noi_den" width="250" fieldType="EX" >
		  <text v="Nơi đến " e="Destination"></text>
		</field>
		<field name="hbl_no" width="120">
          <text v="Số HBL" e="HBL No"></text>
        </field>
		<field name="mbl_no" width="120">
          <text v="Số MBL" e="MBL No"></text>
        </field>
		<field name="so_tk" width="120">
          <text v="Số tờ khai" e="Declaration No"></text>
        </field>
		<field name="book_no" width="120">
          <text v="Book No" e="Book No"></text>
        </field>
		<field name="tien_mua" dataType="N" format="FCAmount" width="120" fieldType="EX">
          <text v="Tiền mua" e="Total Purchase Amount"></text>
        </field>
		<field name="tien_ch" dataType="N" format="FCAmount" width="120" fieldType="EX">
          <text v="Tiền chi hộ" e="Total Purchase Amount"></text>
        </field>
		<field name="tien_ban" dataType="N" format="FCAmount" width="120" fieldType="EX">
          <text v="Tiền bán" e="Total Purchase Amount"></text>
        </field>
		<field name="tien_th" dataType="N" format="FCAmount" width="120" fieldType="EX">
          <text v="Tiền thu hộ" e="Total Purchase Amount"></text>
        </field>
		<field name="dien_giai" width="200">
          <text v="Diễn giải" e="Explain"></text>
        </field>

        <field name="unit_id" hidden="true" dataType="I" width="120" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="120" fieldType="EX" >
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

<buttons>
  <button id="edit">
    <text v="$EditToolbar" e="$EditToolbar"></text>
  </button>
  <button id="delete">
    <text v="$DeleteToolbar" e="$DeleteToolbar"></text>
  </button>
  <button id="copy">
    <text v="$CopyToolbar" e="$CopyToolbar"></text>
  </button>
  <button id="view">
    <text v="$ViewToolbar" e="$ViewToolbar"></text>
  </button>
  <button id="split">
    <text v="-" e="-"></text>
  </button>
  <button id="find">
	<text v="$FindToolbar" e="$FindToolbar"></text>
  </button>
  <button id="refresh">
    <text v="$RefreshToolbar" e="$RefreshToolbar"></text>
  </button>
  <button id="freeze">
    <text v="$FreezeToolbar" e="$FreezeToolbar"></text>
  </button>
  <button id="split">
    <text v="-" e="-"></text>
  </button>
   <button id="print">
    <text v="$PrintToolbar" e="$PrintToolbar"></text>
  </button>
  <button id="export">
    <text v="$ExportToolbar" e="$ExportToolbar"></text>
  </button>
  <button id="downtemplate">
	<text v="Tải mẫu Excel" e="Down import template"></text>
  </button>
  <button id="import">
	<text v="Lấy dữ liệu từ tập tin" e="Import data"></text>
  </button>
</buttons>

      <script>
        <query>
          <text>
            <![CDATA[<enc>mMtZGTjC6D6ziw7/f0mighRitw8Gs9V+HwIfUNko/Kgvd4tziZhR0zo4NI8lxUVzboe7OY03wAq6Bzlh45e+rA1fnnhhlf5Pv1jN1DOXM5FLqYgoyvOolDuFH9Ktr95x7E4/gYGfP5n8tAIpdIqTnbw77UFes8/6ippRJs1SW9Y7mhSD4hmFz50A7C0hHe8dQFC2aAqEVeYgZmeRIEAvdWxQNKblML+oKpgz5vaZUIZkh8I2EDQ/eXotZo3tUGgI1LE9xqzVL3aiIwG/3mJ353f7/7eHN9lmpSVaiS1sb4vXRTIl5JK2AzuI2mjsM0keNUyqeVtnZYvdg75fMMHcKYpd32famCIL9Xm7/aG/mmiecafOBoagmIUTOKyHXNIJhheyKu6LpNzTYH34Zw4LXBI2oHTWLPlWIRVXIsnGyqvVr+f6icKWRK2Rt/gmxbXU1cFALugihSkvGl3c3UQmnDtnhZT10OaczBm8FBT0CNDbbaE7K02RGrGhgrVyCOiBNNgB0R7Cspe5qaiPo5DIxRebe4a4CEtGYb8DdNGoNBwtnFBna+yEJ7eeu/6xWtGXgQKp+05yNTtQN/c/EjaKhIEHeYreKz29FKOn6DH3wFsy4kU63fZaGeQ6G8avLZQN0eKQQuF4Zg5+egib9THsRw==</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>fWQscJLkSij+LRJye5OGur2JlcZ+Jq4zqZFmMwUjbTmjM1DAWYVW6kAUUGDEhRwkaHUvzTerZOhd0hZDkM8S/UiSHIsdyrFgLvWYuucBt5MoO3ycCkkYOu0uSOKJZ8oPeQD6KPfTMCMtAiY1kTy0/mbH6d8Z6Jy3lnxz7I1+J5+SjHuzARkZZV3h0AAH+t0UmAxNUKQ2gEdIE/dAcfbftUHj+IGnUfjj7KAMee5fcMfplKdA0sbu58b6F3lt0bqmdeyZXvbKLmCSjUUcyins6seWWz/NQbSnv4MSC+EK7NR3uL366xBI2xN4HAjXGuEYmbhOqhwGv5pYq04pB97hg4bJPYnZBiDOiSIKsxibQ7R5KtgsPdZtMh2E8QMtBDNFAv+S99PzMnA19t4qIBiGvGwj9QsTa4/EIOezC+8/r6VtwB/KPbF5pCkomMqacxOQ6o4TGUwW/cK3Ys5DKLCskDgi505Epb81q8j8lHqAZBBfW3le+zvJeXDu4cDCA6FmmLB6+GlFI3z136RqDKl5nRpWbizt9LQ/8gyoS6HlmORXFS7jH9IDNMcqjOi+lNzXQn228JUke/Rl2qge0c/K6ahies/gsDTDkigoBhrqbzhUIW5eaUIkG7AEr1zFn9EW7tXOa3Q5bH5hx/qDJowhHPoCEesxtbpgbCNeOt07fk5AGc6vIM7XWvv3XKtlaC8tKEh9SvVMSBitQW9FATeVjo4tBvgD5lPV41K+6cv+5M9RYmkRmKj3hKm6RNxc9RJZo7lKAF0dYDVMw1fTj4UAR0bMZDWZ7GSx4I5ZAwlNuwmu2X8H/y4vPHbuz61gAZ1mp5rMeiSJuULuvXRbDzH/LKzkMdEUCebyApv/K9QUTwzpMuXSUMp8RyYA0PYqMRjkfWQZ13rvKkblTGBUIcCY1YmrJ7N2m41ZzVr+racIpvz5nBnc8zqg/vu3xRr5wV+s</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>5wErx4q93yz4A4Cu1Ug/I4ESgVk+ZL7sV9ZqvsYlzACDQwUdn4lfEjowljuRCOopuuKQpCkJdNFWS1o/FkCs73YaDJufupuf8j2NiSF4h5LaXDtIrsqnJ1SBrvd6Mm+Qy1Kkw7CsijpHN2oWKWtL+xr2nQIZ9qUSUNI9n0QSf3MuRw49hqdI5yMazi03GOOggHqqNBow7uZ3GOeRjiQ8yg==</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>

  <script>
    &VoucherJSLoading;
  </script>
</dir>