<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="s621" dirViewType="Grid" dirObjectType="Voucher" voucherCode="PM1" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Phiếu mua hàng biển FCL" e="FCL Marine Offers"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>
  <grids>
    <grid table="s621" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true">
      <fields>
        <field name="so_ct" width="80" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="120" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
		<field name="ma_job" width="100" format="U" hidden = "false">
          <text v="Mã job" e="Job Code"></text>
        </field>
		<field name="so_job"  format="0" width="100" hidden="false">
          <text v="Số job" e="Order number"></text>
        </field>
        <field name="so_don" dataType="N" format="0" width="100" hidden="false">
          <text v="Số đơn" e="Order number"></text>
        </field>
		<field name="ma_nv" width="0" hidden = "false">
          <text v="Mã nhân viên" e="Employee Code"></text>
        </field>
        <field name="ten_nv" width="200" fieldType="EX" >
          <text v="Tên nhân viên" e="Employee Name"></text>
        </field> 
        <field name="ma_kh" width="0" hidden = "false">
          <text v="Mã khách hàng" e="Customer Code"></text>
        </field>
        <field name="ten_kh" width="250" fieldType="EX" >
          <text v="Tên khách hàng" e="Customer Name"></text>
        </field> 
		<field name="ma_noi_di" width="0" hidden="false">
          <text v="Nơi đi" e="Origin"></text>
        </field>
		<field name="ten_noi_di" width="250" fieldType="EX">
		  <text v="Nơi đi " e="Origin"></text>
		</field>
		<field name="ma_noi_den" width="0" hidden="false" >
          <text v="Nơi đến" e="Destination"></text>
        </field>	
		<field name="ten_noi_den" width="250" fieldType="EX" >
		  <text v="Nơi đến " e="Destination"></text>
		</field>		
		<field name="ma_hang" width="0" hidden="false" >
          <text v="Hãng tàu" e="Carrier"></text>
        </field>
		<field name="ten_hang" width="250" fieldType="EX" >
          <text v="Hãng tàu" e="Carrier"></text>
        </field>
		<field name="hbl_no" width="120" fieldType="EX" >
          <text v="Số HBL" e="HBL No"></text>
        </field>
		<field name="mbl_no" width="120" fieldType="EX" >
          <text v="Số MBL" e="MBL No"></text>
        </field>
		<field name="so_tk" width="120" fieldType="EX" >
          <text v="Số tờ khai" e="Declaration No"></text>
        </field>
		<field name="book_no" width="120" fieldType="EX" >
          <text v="Book No." e="Book_No"></text>
        </field>
		<field name="dien_giai" width="200">
          <text v="Diễn giải" e="Explain"></text>
        </field>
        <field name="t_tt" dataType="N" format="FCAmount" width="120">
          <text v="Tổng tiền" e="Total amount"></text>
        </field>
		<field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="120" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="120" fieldType="EX" >
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
		<field name="id_dh" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>K8bC2VjSx00bn/L+L4lgypTFPwBxTins6juHCKUv1RzFJ/sn0WsNTL5IK4VaHi87ih7oPAj3n12OlouWnmzM3YzOugMgMOLRZc1Ul6EebwWE5yZyUtr5FJbUDs/dpYTCP6HGtXgqKbN4yiiXbKxjlPuj+9ftKy9mlvXvVta20Og86kOixdU8ASNxKCcfDOzh+o+eD29homHgpPrdnI2emqXzwtd358xXr0gvlVGqfikiyU8IHYTqvMGHhjDFZkyV3WfWAXA6knjmH0JPHrFjNdazqiYFCx/ayZOZoFbqyDCt7bYEumDqxDiCzcIVnmb05/OR1r38jqwPJpRK24Nlb/43AajD+ay81yhY8fmyKtUIBhoUooo2aXbHlmS58276pLnaCBuagFGAj80MIisz6sfMIUl5aBf5q5mYsXD3OtdBB6xfk43hPSGjW53+71nyJ/JqDW2wPkccMCPdsNuiyg==</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>V2+DKwQoRMu7E+oSYBgIAG/kCwZNURwmSbVvY9XK5fncAUempGn1CJ13UQnv3HU/oN6vo5RPj8q5IneLqY5K6YcZ9F/+Ie73QoT366AGPZEeD/OUJcuFj4CMbFgTLla7IsxyOTUfJU8lPzieU4eQZaigMEiZW9h9wCl6thFhgij1M2Yn8wFJ82FPxLe3V/0tAFjPdBpFzQv3Zvii2TJ/w6xpw068Ymxt+P0G4WWitr4ETc+M84ZQsXVTgD2FLGq7eWD219pahMeRrTxUvY1pbTQHuMSK7K49TmHQ3Yj+l8Nq28cd4H8ai64CpZ7YsGhN8MEt5idTZqfsnXwSbxfJRK/PKqIlCBgTmovY/1Y1U1vmcGYoeHdKAeR+oHuPA8opPCTOqWNZpgvo0vTBea/JPKo7n43gFb7vkvRj0QPnMsmHg3UtOdOPgKQ7Fj6w+oaT7EbUZCFj8xYtOvhJRGUEtrJDSoaowGOHfn7Z8KMj3Fpms1EdT1byBOK0Cqq7JxwvUEx1jw8QyLIIZ1wOrdK36JYxD3eI+JsoZ6YSOBEYPUIGAlA2oAnan0nRROorBLXHOm7WYV6A7zJ5ejs8Xht2lE14d6+67LhOUnZcuBXSoLn8rk5OWvxVK6h/947GU+sJpQaAOXGoPLjUztJCMILKU8kWQYsLwYU/bEPpJJ0X8qSTxpIAmjc11pLahEisULZPf++FhOk+PFR14IeSnnR6whx319xbCUxJqCNSB57RTzQFiFyK4Znogpn+kY3/81tSRqlea/T2yC/mI7KbqH5rJA==</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>fr96RGVAJ9Kqqf8HatIol6OqDN9QvXjIDQiUl5CQdvBH8lWkhYKQdBcidfgH+3wQ46VXSXCPhpNqpNElM6zYMd2J209V8BQqH3t03bI7KtQjt+atgGI+9Vnw7U4kEVcaBxkBvGK5B0uDJ4zF3xiP/RHOTgwdJJb7wCkLZb/I+NmXLopdpZFBVFa+MrNVVgrSgJ+vq7K8JpLWnB+51YlIJw==</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>

  <script>
    &VoucherJSLoading;
  </script>
</dir>