<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="s623" dirViewType="Grid" dirObjectType="Voucher" voucherCode="PM3" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Phiếu mua hàng Hàng không" e="Air Offers"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>
  <grids>
    <grid table="s623" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true">
      <fields>
        <field name="so_ct" width="80" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="120" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
		<field name="ma_job" width="100" hidden = "false">
          <text v="Mã job" e="Job Code"></text>
        </field>
		<field name="so_job"  format="0" width="100" hidden="false">
          <text v="Số job" e="Order number"></text>
        </field>
        <field name="so_don" dataType="N" format="0" width="100" hidden="false">
          <text v="Số đơn" e="Order number"></text>
        </field>
		<field name="ma_nv" width="0" hidden = "false">
          <text v="Mã nhân viên" e="Employee Code"></text>
        </field>
        <field name="ten_nv" width="200" fieldType="EX" >
          <text v="Tên nhân viên" e="Employee Name"></text>
        </field> 
        <field name="ma_kh" width="0" hidden = "false">
          <text v="Mã khách hàng" e="Customer Code"></text>
        </field>
        <field name="ten_kh" width="250" fieldType="EX" >
          <text v="Tên khách hàng" e="Customer Name"></text>
        </field> 
		<field name="ma_noi_di" width="0" hidden="false">
          <text v="Nơi đi" e="Origin"></text>
        </field>
		<field name="ten_noi_di" width="250" fieldType="EX">
		  <text v="Nơi đi " e="Origin"></text>
		</field>
		<field name="ma_noi_den" width="0" hidden="false" >
          <text v="Nơi đến" e="Destination"></text>
        </field>	
		<field name="ten_noi_den" width="250" fieldType="EX" >
		  <text v="Nơi đến " e="Destination"></text>
		</field>		
		<field name="ma_hang" width="0" hidden="false" >
          <text v="Hãng tàu" e="Carrier"></text>
        </field>
		<field name="ten_hang" width="250" fieldType="EX" >
          <text v="Hãng tàu" e="Carrier"></text>
        </field>
		<field name="hbl_no" width="120">
          <text v="Số HBL" e="HBL No"></text>
        </field>
		<field name="mbl_no" width="120">
          <text v="Số MBL" e="MBL No"></text>
        </field>
		<field name="so_tk" width="120">
          <text v="Số tờ khai" e="Declaration No"></text>
        </field>
		<field name="book_no" width="120">
          <text v="Book No." e="Book_No"></text>
        </field>
		<field name="dien_giai" width="200">
          <text v="Diễn giải" e="Explain"></text>
        </field>

		<field name="dien_giai" width="250">
          <text v="Ghi chú" e="Note"></text>
        </field>
        <field name="t_tt" dataType="N" format="FCAmount" width="120">
          <text v="Tổng tiền" e="Total amount"></text>
        </field>
		<field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="120" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="120" fieldType="EX" >
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>1bttlfsyYj0MbK+xuyanjtS8Z5vYUGDv7AR+7I+uwDte/qm47MhvbMynrrcGzVbDEZI1wjO4bPJ/hACEF1MGtXbO++NDVUSBfVhqm4/HSwJso8bpMPlu5SU84qGmyAF/lhaL/5N5Kh0YWbfq127jd+Tah6BLS/sVwPL5wUCdF/IEvSCusNNYkWziHXWToRq0s/FKokH5hWzd1GZhQCuf9eUmHBvvPtw/GUa3k3Rwmvpw49sJy2KzHy/Nfjr+ZX38tMJ+RRftFVCApZguIrSnQQHZYrbQZeiL8wIjVSlvYX2r0EdyCW7oo2TIaH2PkKJRQTuKjHVgnQS7ETnjkw+TTooNemBlaesHxlftEprO6x2yIr04FQNPuc88q0Qqq4Mlsf2rAAT82mHi/dcR3TT2YCr0DwflCTYiVZ8d2cOIYdQ=</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>xkR6AFsu8zAHUx0YsBLthc9aPTFpmIedOYqmsUrICg5hJzjwkbf1lPXJawsf1tGtlYHdM/OOH9oAtpTFEcI5XWzhMm0ayWL8qmdhgmIXCqPEzFgRXNd1S0aml68534EQd0qKbizWLpIAb+xlzoWsdZZlP15rLnOEdeNscYaKoWXcSMT3LxM/s/Sjz7B453Gid3l6IDNnaAMBTgmoOwibocrY2ZccARuH2pQq4bxFvDAoesXQan5PbnZOlsnc5iVW0PERUiDQW5HBjZgEiW9KT695kaEuSHulMAki7ia/ekhMR9GJuxRJ9QXhMzrJUIvuryRB4ulvykMU51toLsc40xagDNvg5QvIY1C5o2K9fTFcAIG1+6+TTC1PoVNoga5gosTlD0dHQxR6lBkpYC9Wxr6R3FzGNk13uWyHYyVROjiQ0AxNYLCm9IpoBMWKnyENj4b8WJ0gACt9YrUaHaXW8oLor4rce8AfkcOLQW/mQHlvgW5iFxhSTH4I0v04qjIUTX6PGUnMqp71Xbx+uE0JWiMQ148Pu6fc5rqz5OcwPPgLKo5KvSV9k0nJ/V2AYrmwWwxsK7nGuPFjpR3J9yHN9P0OfGnMo0zESx+5GNhiXdeIYDcrJITY9gsjNkYNMqaefbLhPQRcH8OvArWvtTdlDDUcC3L3C3PWalF8UId//VB/8B5tPIlk8BCl3TL7lriWV8sVwKGmo+BnJJXTxQlNkRWK1KtyOmup2wAeTfUftwo=</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>fr96RGVAJ9Kqqf8HatIolyX1IfNO04m/6Mr3yAdK1uPmUfa5HgfoVzNGdRq0kAhIIHdzN3ziNasP/LW4P9KOmOfNU+n6xi87v3PpV4hyUxOLqs8No8bNOy1n2HihNxjOWsrKtsuIYzVzB4iYgcb6Aw1NP3Eq+vFLJHyLGulcrxA6M9v8VqXXxeid8/+pbao4lTYrJWwl4TZuAEtZTGxWcA==</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>

  <script>
    &VoucherJSLoading;
  </script>
</dir>