<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="s631" dirViewType="Grid" dirObjectType="Voucher" voucherCode="PB1" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Phiếu bán hàng hàng biển FCL" e="FCL Marine Sales Slip"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>
  <grids>
    <grid table="s631" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true">
      <fields>
        <field name="so_ct" width="80" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="120" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
		<field name="ma_job" width="100" format="U" hidden = "false">
          <text v="Mã job" e="Job Code"></text>
        </field>
		<field name="so_job"  format="0" width="100" hidden="false">
          <text v="Số job" e="Order number"></text>
        </field>
        <field name="so_don" dataType="N" format="0" width="100" hidden="false">
          <text v="Số đơn" e="Order number"></text>
        </field>
		<field name="ma_nv" width="0" hidden = "false">
          <text v="Mã nhân viên" e="Employee Code"></text>
        </field>
        <field name="ten_nv" width="200" fieldType="EX" >
          <text v="Tên nhân viên" e="Employee Name"></text>
        </field> 
        <field name="ma_kh" width="0" hidden = "false">
          <text v="Mã khách hàng" e="Customer Code"></text>
        </field>
        <field name="ten_kh" width="250" fieldType="EX" >
          <text v="Tên khách hàng" e="Customer Name"></text>
        </field> 
		<field name="ma_noi_di" width="0" hidden="false">
          <text v="Nơi đi" e="Origin"></text>
        </field>
		<field name="ten_noi_di" width="250" fieldType="EX">
		  <text v="Nơi đi " e="Origin"></text>
		</field>
		<field name="ma_noi_den" width="0" hidden="false" >
          <text v="Nơi đến" e="Destination"></text>
        </field>	
		<field name="ten_noi_den" width="250" fieldType="EX" >
		  <text v="Nơi đến " e="Destination"></text>
		</field>		
		<field name="ma_hang" width="0" hidden="false" >
          <text v="Hãng tàu" e="Carrier"></text>
        </field>
		<field name="ten_hang" width="250" fieldType="EX" >
          <text v="Hãng tàu" e="Carrier"></text>
        </field>
		<field name="hbl_no" width="120" fieldType="EX" >
          <text v="Số HBL" e="HBL No"></text>
        </field>
		<field name="mbl_no" width="120" fieldType="EX" >
          <text v="Số MBL" e="MBL No"></text>
        </field>
		<field name="so_tk" width="120" fieldType="EX" >
          <text v="Số tờ khai" e="Declaration No"></text>
        </field>
		<field name="book_no" width="120" fieldType="EX" >
          <text v="Book No." e="Book_No"></text>
        </field>
		<field name="dien_giai" width="200">
          <text v="Diễn giải" e="Explain"></text>
        </field>
        <field name="t_tt" dataType="N" format="FCAmount" width="120">
          <text v="Tổng tiền" e="Total amount"></text>
        </field>
		<field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="120" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="120" fieldType="EX" >
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
		<field name="id_dh" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>K8bC2VjSx00bn/L+L4lgylWrSc/H8RZ8mE8z3ARc4cPAFwXE9ABlefBjnDBM3QGHri0Cmqb1c8GrZpCw/BGUCNg8DfJq9DS+3bYmV/eI2iOCU6Vrt12VlWNEHrlEAe3DQ9L8WnktV8vIwG9bHckQsuwKCmoveNvvWPDlTgbD026OSHddl2i198jgQYRgWUSaoRabGDYJcx6+hTTyvmXt1Shxu84KXvoasF+7sbZsrI2Zuu9G3XAyBUnxXB9dn14FKlz0/4//oK1IMbHKCAZIxnFBhRBi+WRYzcctt26hdxfyTgwJyVxqTE7ftVLabGV9v1F5t9+hDvD8+fQ/4NOjzeyAvQ6MLK8lGi/lJvrlLZoh83yjYP5d4J6zzo7A8VDPkRRrRj4J/ukiBOqdhjYENdKE4wGnP+KwiSzpEbxT+GyWW1Oy41CmxaEUDEk2x6h+CLTtOc99c2n1mp//xI5GBw==</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>XIVjPJt6b6ODIrVETUzvvnCzLG3sPi3y0zyOKNpzKvjXxheGDad5ALLexEk2v/KvtM11z98gZDq8ElX3gaa7BAkjJRW2isnNbQEOVwWVt05XH+lwnDaDPSdxKYDH9U7jUaX4QMESmIkpgXyKJr7q3Ra1bP0J8zbK2iGGSF2RXuJCnyqdySdpFIQxT/K7gnRqjA030MlknyxrBv8Ih+ggusz0Zh/CqrxVMq6nNBnVPsVDx1x2gQxoUaUmbOkLszaGWU5PSAhjupzgCMcQD3NFEze+4r3f8N+yr7FyPFSMraPpqhrqiEujqKWfTG6bT7IHrSXl2YEeFx/oRNMPJKP5dXz6raLWwa614FfA+S/brXLdFZFJ61x8EHmFajqL4WJUX3MnnfxueATRH2BKB/yARA9TT5wZ3olNbiLbjrfrUlaItZJ+KUZ+lODJ3YO0v4S6Ma7YF0u5sX/HHy06gZrGcEk2RCf8N4DLD0VofPJTMUMc0zjBJ/FCeDYYe/uzfn6T39MAwz3xPor5Mx7QtACnVD8+X2CNyqtMWZabgYiz/ylpdVXufA8436r1dTI2KMCu4KuBN808lHxg8xiNqAMSWYWxteoSFfBbuDHI5GIAO0/WSIpzrUZs7ODBFy7hxwzlPC4ycoZio3VCB62E9KyUTSX4fkaqPj9tRnxQ+SWebcMYWV8wgR56R+AyriglCBCjJbP3wkKWHe9W4uFHLlXWgfJIRlAQ/u2F0g0cPxTMURA7KmD4C+eIuK9UidNvaIss4JDv53cf4XnA+hpsUiaSeQ==</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>B3vwoV4prYvzOacbKQoWCxVBhI3usbRijg3gX3poQZipTMNlwCJFe5BZYhAWSc5ZSFBIk99bB488n26r8M9nhPzBoJvXKYHRbfS+MfKhPil5EBA4zwFPwVqVECOU91u6a867SLAlFqYOWzMBJNAQ2i2231HpgOQrLpn73H6WokgWd/IQv6WSU9/TKFaevCHQK9nNe3FyMgCSk5eIncXGMg==</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>

  <script>
    &VoucherJSLoading;
  </script>
</dir>