<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="s643" dirViewType="Grid" dirObjectType="Voucher" voucherCode="TU3" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Phiếu hoàn ứng hàng không" e="Air Refund Voucher"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>
  <grids>
    <grid table="s643" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true">
      <fields>
        <field name="so_ct" width="100" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="120" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
        <field name="ma_nv" width="0" hidden = "false">
          <text v="Mã nhân viên" e="Employee Code"></text>
        </field>
        <field name="ten_nv" width="250" fieldType="EX" >
          <text v="Tên nhân viên" e="Employee Name"></text>
        </field> 		
		<field name="ngay_hl" width="120" dataType="D">
          <text v="Ngày hiệu lực" e="Effective  date"></text>
        </field>
		<field name="ngay_hld" width="120" dataType="D">
          <text v="Ngày hiệu lực đến" e="Expiry  date"></text>
        </field>
		<field name="ma_nt" width="0" >
          <text v="Ngoại tệ" e="Currency"></text>
        </field>
		<field name="dien_giai" width="250">
          <text v="Ghi chú" e="Note"></text>
        </field>
        <field name="t_tien_tu" dataType="N" format="FCAmount" width="120">
          <text v="Tiền ứng" e="Total amount"></text>
        </field>
		<field name="t_tien" dataType="N" format="FCAmount" width="120">
          <text v="Tiền hoàn ứng" e="Total amount"></text>
        </field>
		<field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="120" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="120" fieldType="EX" >
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

<buttons>
  <button id="edit">
    <text v="$EditToolbar" e="$EditToolbar"></text>
  </button>
  <button id="view">
    <text v="$ViewToolbar" e="$ViewToolbar"></text>
  </button>
  <button id="split">
    <text v="-" e="-"></text>
  </button>
  <button id="find">
    <text v="$FindToolbar" e="$FindToolbar"></text>
  </button>
  <button id="split">
    <text v="-" e="-"></text>
  </button>
  <button id="refresh">
    <text v="$RefreshToolbar" e="$RefreshToolbar"></text>
  </button>
  <button id="freeze">
    <text v="$FreezeToolbar" e="$FreezeToolbar"></text>
  </button>
  <button id="split">
    <text v="-" e="-"></text>
  </button>
  <button id="print">
    <text v="$PrintToolbar" e="$PrintToolbar"></text>
  </button>
  <button id="export">
    <text v="$ExportToolbar" e="$ExportToolbar"></text>
  </button>
</buttons>

      <script>
        <query>
          <text>
            <![CDATA[<enc>BLLPK5QUJEauN7sav9+5YFdKwCh0RCF38MVGZC5YrtOTuzIHwVlBHJeGAOLcHjK9NmAUuv7hDqqK47cIgl/MT4UcEY93C5qc1g3RQWHfBsF29v7aYrUaYkKPy5VUMQsztLXN7V3LdQ2lW0o2dEU7PAlrE8BFqVkeWIKcDwgVIAUrAWlRkWz0bD3QzMeg2pko64XS52QyKtXaCaD6wtjNFXZe6sBKneEd3GB4SolE5TOXNjlYqhK6T2Yb7jlIY8CmH9kipjdp0xEFP46X8qnxfqK13oilI+NAb1mB8EBY8rtMZlG6/lX93k6/ID10aBeY</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>w9cPdwVUVc/6V89AcOsFv63Z4cWRMkuRUlJ3T74orgzKxCLLobGgHm4Y57nMBpve3ioKosfXb85GboBG8mrMMOw3rw8EerL/KX0LyA5bzfLugrP2t45KfMhu/Na6cvLHShhzMtaiEyVFs0T3gc96F3/sIBnVUhlxtcr5IW0gnA2lHV3FRkjDEDCAwS3ZNL2W8Wqb4dNvteOHelNqPyiWL6cqLgetLPJZJbejPkKm7FYinmxZol0P7IVz3E+HDqkdGt7afmHfuWOtPIaOlQTeW/6G3EQo5wEFMbSK7J3R82Wu62gEH52HXScN3t5+RzVmKgfwWTzRIYP2IoOknHUB8vS++K/zF6HukowxAdZK2DxdUvxJ4cTvx2W5MHHiEemLqiPprVUy1/1+SXvlp0Da8hSvh7CSmokIqbQBHrcP4uan3+Mw3QSiOX3ygNW8s1lxm+NdNcWneRbTQt9At4Z12QkXjel785oDkuI3Mr/dLn8lWv1/Qda/auOyrv5O2tX0</enc>]]>
          </text>
        </finding>
      </script>
    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>fr96RGVAJ9Kqqf8HatIol19PnfYNfzFEeMbxpSHmk4IkoXnHIfzCoat+s5AweWXceJ7EvLxPLr7ddf7KeUdfD+T42KuFpOWufY50JEvr/o4juTFEoTibLvAsLKwPzx94RKbNDJY9EnN42cOhKmCSq24OaRAvwRDMsTcaWuXmnoWPJAKKXwRmigQERa04BFfvZkH0xUMl5ousIMk0iO8nvg==</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>

  <script>
    &VoucherJSLoading;
  </script>
</dir>