<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="smailApprove" dirViewType="Grid" selectMultiple="Table" voucherCode="HU0" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Duyệt đề nghị hoàn ứng" e="Approve Reimbursement Request"></title>
  <subtitle v="Xử lý &lt;b&gt;%s&lt;/b&gt; hoàn ứng" e="Process &lt;b&gt;%s&lt;/b&gt; Reimbursement"></subtitle>

  <grids>
    <grid table="smail" fieldKey="id" order="ngay_ct desc" key="xstatus = 0" allowFilter="true" allowOrder="true">
      <fields>
	    <field name="unit_id" hidden="true" dataType="I" width="120" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
	   <field name="ma_unit" width="120" fieldType="EX" >
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="ten_unit" width="200" fieldType="EX" hidden="true">
          <text v="Tên đơn vị" e="Unit Name"></text>
        </field>
        <field name="so_ct" width="100" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="120" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
		<field name="s_mail" width="400" >
          <text v="Mail gửi" e="Mail Sent"></text>
        </field>
        <field name="title" width="400" >
          <text v="Tiêu đề" e="Subject"></text>
        </field>
        <field name="email_body" width="500" >
          <text v="Nội dung" e="Body"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
		<field name="imageisf" width="100" fieldType="EX" hidden="true">
          <text v="Hình ảnh" e="Image"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" >
          <text v="ID" e="ID"></text>
        </field>
      </fields>

      <buttons>
        <button id="approve">
          <text v="Duyệt" e="Approve"></text>
        </button>
        <button id="cancel">
          <text v="Hủy" e="Close"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="find">
          <text v="$FindToolbar" e="$FindToolbar"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="refresh">
          <text v="$RefreshToolbar" e="$RefreshToolbar"></text>
        </button>
        <button id="freeze">
          <text v="$FreezeToolbar" e="$FreezeToolbar"></text>
        </button>
      </buttons>

      <script>
        <query>
          <text>
            <![CDATA[<enc>KB8xqdyii61Ha3yaQfUGVU8ZRMO1mUTc3Zxv4bJsx3wvpl4AUSqQyA4Wzr5OkUiBhDxvbM4NcEjRNfmqB4P3lF61n5azs1JhM+IX6Wc8Qg367ZNXWhg04PhmVurh4xkG8HFWIOnDJqqfOorT4rjj2ETQ31sw7u7KfKpwWSJyefewJ/gyhKiUfArhiK07/Fp/QzR9MAMXSWBacXU6IaNNP6S68zJHXkl0SajxHiFLwkEwFnFFcErge8vz5IPwmmJQGCfOXzBDIw1mhSxo61lftBeFNNcJJ/qXtjZljL23hEw=</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>B9otNKMn/OrDvLPNdJ3Kmzrg8yoUBRSs65nKY17vwkdcJ8zJzE56od6O/0MmiVhEN0x4//s8PDo+Bpnx5MZU43dAzQo1cXPC1fKiquwB2ahkHKeec/H9LbAZ9Vs7HlX9Aa4SkPtcXdxujaxbqIvywB4G47UYj3ougtZUuYUdjtYlsBADc8BtoJmbi7cxK8eKHtpxxYl0z9aPWRu2e+QIc47rw+FpJXlSLW77d6ixe9C8p3oZFBDfJtb/f7wwfXA5dy08YHWmbtz9My29PrTp8ii5O99EEiou9HB3WyY3pn95mkSzjFL0OWTMKm/CEgGOnGGRLDJp0Igvpd/tRpbohBKrzi+Ij5pyhEkdIlxuiM8u3oThjzirCC2Ws59d9JI6iUzVjc9LdW3fIZYjcP7zopsdOWLvSE3ahFpKGKjkQ7vAyJ5ZHUyBLJczO3wcaah6cFZfjTZasppZcYlu/nGgpZbtrGFwgVPDsjcJ+KCvqA0Cy/IV2UGDLmKXZDl/vfo//V6pMuJE0FKcNI6KKlVkOCY/7Og/oc1j+hjuOGZKrnDm6iLpW55x/Wjf8ApExeTtEmdCLAs7byEQfyKipm624w==</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>+Gi9XuPhUv9TmUZEaebBb4z36W7Ss2JGy5RBgA5+il1Rd0+AO4MAMJWKL956KURhIg1AaFIPX0KIAd3biJdJnGJY07rdJwMNW1ojg9hmVYqsBqIuukJXIdf4bg8ZJVeTCnryPul4ZTboJHI3uMlAqaGYMDfM4Qicrf+aOArbn0QEOPgXFNWa/KcjyXYfoBMBKpFBTOsimxtgCeo5XG4DzF9ZWBaH4uOcrWzupS0ZHG2q2MemATw0EK7VzLmgnMvRcT4tg5s/OHc4rTlGfpPxE4XdKV4qinOu7dTZilXcbmTt2Z6AUhl65cl5bECdKo0ZW/muYrqCDGBarn1MBi9F571tYstWHleywdrSD5Zos+9WNx4eOC6AtK2PtBuTQbKMwErzGmCfic5yRdyp1xpJDD9mMk+4PJXwJe0jaZ3+xuqu1mB6mU8VNGVQdviPrS8edmB2HrWlgbWx4B8tO7x3y4D7mI9UixDvf8dC7q/xK6Kd3kYF7vpE7lbQCsV50FXo1FGElSxnptrjht0pFyhARH+hk0oGJGPUU5MrZRX+ZLcxqeJ+mnx+xW+R61H6zi+lmJ24hkeTC3ywBAM9RBOH9J2vtB6axBKs21DLE4sif+M6Zok1cFCTR7RsxZqBv7mecfktpUm3I9uVM05TFq11WglgCLu7b1LdrE1yvpPHfsZ2nMlmDb623eeMCmUAdo14dfibwK267oi8vdeB/vAdaqisdUriJDXZUNZR7ZFewMPgtSFDz3a8zEUuKSznBRxBuTGjdxQyx/rnqVRjyfZNHyViFUzpvW1ulbs8QBcdi1/fG/ugpwW5yEOosxN7DNh8V1rxTiYQlIk17Jus1THzDQkKKcOSJuv43FWsEG+Bqg+G0Xg5bNEYXtZtoKSzp2BV1K0gzbnz8hOWaW0PfF8xpgREyIxFq43ffkgTRA0xcZjtSy5Rp1Sanq3eP1Sf+BS+</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>xcZazmBvA0RUyvp21icN77Cc3pvcV/9z4vzLmGOJlH2A0yE6vNNjVnZHynbwWmWn573HglBECfyhtKG05P1kRMc+/sgKycdJgEi9fBMC3kVLP0CFly3nUta7uFP8L93B5Rtp7G2DiGCVTNCKC/8vw0LFGFxb/jIy5YFEWv5cSI//evleF9RGiJxYCMf9yMWjmR05oW3e56KounEMMQf1P31E85ujfAY+y2pTw4H0lcZr1VqZqq7Bte+xGw3eWoctae1a4x2pBZil7Foea1xKpTELbaNy0VeAxfCpVUuo4k6TmkIl4beEJ6XOS5q/KxghL3ivLSRwoNaHY6+f/KGoVESY9xEt2oeffye1z6clW0KaBVY+82Mzv6IQonTkb4hC8W5MHFwCEtDoymLuzWvU1lM2WX5x3MJFJ2DIdWt+fLAdrnJ/34w6A1FEnS4u8M1pOVuKTYU3jSSfZ+T8bLMTPZ00T9g/agsCyFdgipA2CVkir6oW+/ugg3t2L5h1kARcAjQk6tGuc5T8A3q64aXmcg==</enc>]]>
    </text>
  </css>
  <script>
    <request code="Approve" transaction="true">
      <text>
        <![CDATA[<enc>ortgl3Zk4O41uVHmCuFcn7hGqd0lPzT8AEkEh65Xu7ccpPxl1TuN/gzaZnrJAMED1qq5P7MJqjlUvV5bjdsZhU4HX7eVWdcCb6ARkibIKsNbSU5vdP1bwABo6mZj7vSdmqQrapSi++4ftWOlrY7omUo0k1xe7DhTziNR7MHCvEQ7yg7CoLa6rREWH3M5dpKODaLgpc+4ssU1nCYbdx3pXGRzRpeO2BWOFrZZAPGM5Z8eFHrS9PvLV/dFgbFb1z9C2I41uoW9PhgrajSvcQD0meHlyYS0udbg/oSBHVfcbCeWZb5Uy8Q6wgnDwPjz8I3SAPs0sW3CydeAigDJJYOtv35UA6ohzTpcES/EHxIxR/Gp1xrDUJMPNl48ulnUZEoCkbvEIKNTN5ygZKKTTTxKmTgWqbgNj19GufCTRgjkC39SZKXy3+1bne6MoRyuLpnB</enc>]]>
      </text>
    </request>
    <request code="Close" transaction="true">
      <text>
        <![CDATA[<enc>tyhsE6Qt8hunfdX6yOnN6XvM9mOSIx+5WbSOz5YFZ8FEIwYo9/mc3w3l9GfZK2jzBdlvGHzhBoju+JJqZDs74FAYpsDYqIcJLam50MvJhS1zAySAnqBIkyEuWcoX4KhLNXxZOmZI1t7ky6v6l2rm8/QuylLQrssfkwNnLlpdUXL0psgjVhuM3fqdHk9B79QaLVLUsTArzQQ7M8TGF3eWIhceHMNGz4gFsGpJPTnL+kBI8MYBiWY6Rtv7cvBMR7j+qbGC7WyqigyScj2Cxlu0YQ==</enc>]]>
      </text>
    </request>

    &VoucherJSLoading;
  </script>

  <messages>
    <message val="msg1">
      <text v="Bạn có chắc chắn sẽ &lt;b&gt;duyệt&lt;/b&gt; các phiếu được chọn không?" e=""/>
    </message>
    <message val="msg2">
      <text v="Bạn có chắc chắn sẽ &lt;b&gt;bỏ duyệt&lt;/b&gt; các phiếu được chọn trở về trạng thái [Chờ duyệt] không?" e=""/>
    </message>
    <message val="msg3">
      <text v="Bạn có chắc chắn sẽ &lt;b&gt;bỏ đóng&lt;/b&gt; các phiếu được chọn trở về trạng thái [Đã duyệt] không?" e=""/>
    </message>
    <message val="close">
      <text v="Hủy/đóng" e="Close"/>
    </message>
    <message val="approve">
      <text v="Duyệt" e="Approve"/>
    </message>
    <message val="undo">
      <text v="Bỏ duyệt" e="Undo"/>
    </message>
    <message val="open">
      <text v="Bỏ đóng" e="Open &amp; Approve"/>
    </message>
      <message val="inputTitle">
      <text v="Nhập lý do hủy hoàn ứng " e=""/>
    </message>
    <message val="reason">
      <text v="Lý do" e="Reason"/>
    </message>
  </messages>
</dir>