<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="smaildmkhApprove" dirViewType="Grid" selectMultiple="Table" voucherCode="HU0" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Duyệt kế hoạch gửi mail" e="Approve Plan Send Mail"></title>
  <subtitle v="Xử lý &lt;b&gt;%s&lt;/b&gt; hoàn ứng" e="Process &lt;b&gt;%s&lt;/b&gt; Reimbursement"></subtitle>

  <grids>
    <grid table="smaildmkh" fieldKey="id" order="ngay_ct desc" key="xstatus = 0" allowFilter="true" allowOrder="true">
      <fields>
	    <field name="unit_id" hidden="true" dataType="I" width="120" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
	   <field name="ma_unit" width="120" fieldType="EX" >
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="ten_unit" width="200" fieldType="EX" hidden="true">
          <text v="Tên đơn vị" e="Unit Name"></text>
        </field>
        <field name="so_ct" width="100" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="120" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
		<field name="s_mail" width="400" >
          <text v="Mail gửi" e="Mail Sent"></text>
        </field>
        <field name="title" width="400" >
          <text v="Tiêu đề" e="Subject"></text>
        </field>
		<field name="ds_kh" width="400" >
          <text v="D/s khách hàng" e="Customer Sent"></text>
        </field>
        <field name="email_body" width="500" >
          <text v="Nội dung" e="Body"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
		<field name="imageisf" width="100" fieldType="EX" hidden="true">
          <text v="Hình ảnh" e="Image"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      <buttons>
        <button id="approve">
          <text v="Duyệt" e="Approve"></text>
        </button>
        <button id="cancel">
          <text v="Hủy" e="Close"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="find">
          <text v="$FindToolbar" e="$FindToolbar"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="refresh">
          <text v="$RefreshToolbar" e="$RefreshToolbar"></text>
        </button>
        <button id="freeze">
          <text v="$FreezeToolbar" e="$FreezeToolbar"></text>
        </button>
      </buttons>

      <script>
        <query>
          <text>
            <![CDATA[<enc>KB8xqdyii61Ha3yaQfUGVfw/0VRH+ToOyB6glknugpOWniwlKOIDZOYF3AUCprqTvhaDXIHG3kc2N9l/TSZHRrogQmRAFdO7cn9lbEJpIfnkPfR75rxKfGpvploANAsm9OqW+33LE+x45HN/7EmEcK96xxeYWmQH5QoyEyKGlfRfhqSbW92sQgxjB/ENcSR6xIv046NBjYcG8c01tLt5vY4F7wNtruS92KXoZ77CNo+SL9oAIbM3yeB6EjN8ryOVr3D+GgMqbqYSHuTRp1M/aMLDGOp+vM6wFyG3mDle3Ks=</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>qaqhMclEi1tYl22H/QLox88WKO0g0SYRq+61Qt+Dmud6/lWzg7GRJoHQHmZDrjL1TWK0dLt8zinKFHNQZSkxiiadtlejpr53MpSp/IUb02PnCJLwFsse1xLyJ3efSY57m8c+S7AqUy/MttHq6yBRGaoddFk1Wv3xl7E3pGYvX332pdcp+oUWMe+rqTNcxl3l3PlmmV1bSrKVYFqFdgYUcLWvvqS6C0XYm2IaagzRkjSA/rCs+cknSn10E+eSxLRrgZEwxX40n3EM+l3CRDffY47pMo/Om2K1ulEOKeFuvffAbw11/g5zDpKI3C2upPueBd4YWqxzl+Qk43FMMBizvTyd2Bj1mu1iA4W2uud+yCfQfNzDfz1IYJ5O6bPEKlr6uEamqOinWoVZ5rhI7zFuwkLK9UcZ8oq3ObsFThThmJfAVWwgNjhm5GmLTglpWuqrluRASgJgUpCV4XI08jdNMg==</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>+Gi9XuPhUv9TmUZEaebBbwYhJEVkrRJ9Crhqwy4rAOn8cga/jkyCwVDrWo5qF09BtuWR/E5oNLXUeNBAIzkTuK7c2wJRKpVeZsOCclBm0LGnI4b2T9uYoaaKisPwoFbmUTOlqUInEkXnwtxvV+3g8Km9WX/CS3ERGKo63Ix1+DbMBBOkUW+pu/JHbiPVjzJrd/O/SJEaNZjk5vKAqr+pykkNd2L+LaQwSzyUUd3eElCmu/5zrY5w2dXkr0NkyD2QuxahtcDOSt6ZEWgOhITgZCEE+UPXf4ACCtrKIwGhGjnLEPUG6I42flUaHDREG0xg5W5AH1ceBlhUg6Tx7IKm3kS12kIAMUAIWgFNnRwF/ZnYG5JcKHEZXwMT6E/rX1a1Yhuxe48pPQqjWtmwcbVw04nKNxC9p3SLsxwA5bpEQT3eMSvEuiZkhZ73Q32vCLkYQQ299+EVjE9EdfE7+RcDj038tvza+zQaQCUFhRksIngF5ui/8LePedRC0XnWVXCPd0AqQgG5Im5/RkoKEyjAlIdfPtxFjyaorTd0pFGHRnDedWOBBvugMHDfLdrhcBZbfmrsCWookTqvwxv3kFP1G2sHjKJdOrQMjPtYLFwMP5nZc6EkJEKPyCrAvL9Xv/ReMCu3IMjCasGunv2S88cFqz8LG7g8NjE00nVkLoTsvkXcEBtGnFVE1k+pPUmTGSNXTDr0r6GZ+OkILZSsQGx5aZFBS2strVYFWiPwkZKqyDRnl50MGCP9d5QKt9i2H4GOEkwmbCHHs9D81rmp95zLN+Tx+utLudpu+6HNSZPL7KxEnyb/DeRUPQ8kqMN1mw4Gq0gJz+GeNJm60RmHQBEWMUEW+SGZZbIItYLWzD3Qq3l8/0I6iTxtBXxUGsL3yfKVZ6awROYXxhB9Mr0pGTRpQ7IgwSQ5WdTrSxtcXYU3zbyL0Vy3zfXRgLC840r3dUlj</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
  <script>
    <request code="Approve" transaction="true">
      <text>
        <![CDATA[<enc>7pqWwM9j1eqUH7ew99HhBvT1JMfZ13a8zO8sryytRTTLn7N/CgX+hvC2YWd3vF0Fdt1Dj4/vxYnbuso8Juf5BHOYLm8P/xSYb6NFNYJPhXlCbNAuXmtF8domYByzOkV12X+6h2MwjeFmemzMFWSWBe59Q8ny46NVrIEqk19fT73YNPXR+DKj+rlqaSu/Yw5/9rlrSLIZpKcdc4egsFyCgUZD0GvAOMRU6by7A6cVDzAs9X/rvgO3vEQMTGNrVOMJR69XsKE1DJLA/gl4u3kKXueA74RlG0iBBFrSnmvqCOlysouoBpt3goUUiFJUCfgq1ut8ltqKewLfBklCGN611Ulk0wvon+B9+WqjvWosYAd2cIlj++yB9j5zLAFQ7fR8G9dKifFTyfkuU1sd8kNdXKxH8dH5UPTvTk0Qty+kGLqOhioBFlkDBaViXnUOOvQr</enc>]]>
      </text>
    </request>
    <request code="Close" transaction="true">
      <text>
        <![CDATA[<enc>5ZR5zFgfJNNt//nR0CmuAOP/8OzH82bHD+g3d2tOn9R2nFojphBGAQwNofBh0fxxffcbD3ntOYAECl/qux3l9IHANolXIZFOfkyxyMyTh2qnuhCI2qWVoOcrhOH/gdZhlx4S7F5uJ2jfsVgLtG5Q/dlHoJcJOFyGt9275yYJIeKnsfWfEej5/UaCQOFhk/1YeXaggZ3ITRfmPVfWNqrFYRWns7wPpJIOhOvqrivE8M1R4DF8N7ZDgroftU71vFu+</enc>]]>
      </text>
    </request>

    &VoucherJSLoading;
  </script>

  <messages>
    <message val="msg1">
      <text v="Bạn có chắc chắn sẽ &lt;b&gt;duyệt&lt;/b&gt; các phiếu được chọn không?" e=""/>
    </message>
    <message val="msg2">
      <text v="Bạn có chắc chắn sẽ &lt;b&gt;bỏ duyệt&lt;/b&gt; các phiếu được chọn trở về trạng thái [Chờ duyệt] không?" e=""/>
    </message>
    <message val="msg3">
      <text v="Bạn có chắc chắn sẽ &lt;b&gt;bỏ đóng&lt;/b&gt; các phiếu được chọn trở về trạng thái [Đã duyệt] không?" e=""/>
    </message>
    <message val="close">
      <text v="Hủy/đóng" e="Close"/>
    </message>
    <message val="approve">
      <text v="Duyệt" e="Approve"/>
    </message>
    <message val="undo">
      <text v="Bỏ duyệt" e="Undo"/>
    </message>
    <message val="open">
      <text v="Bỏ đóng" e="Open &amp; Approve"/>
    </message>
      <message val="inputTitle">
      <text v="Nhập lý do hủy hoàn ứng " e=""/>
    </message>
    <message val="reason">
      <text v="Lý do" e="Reason"/>
    </message>
  </messages>
</dir>