<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridReport.xml">
]>

<dir id="ss_bcdttt_tkh" dirViewType="Grid" dirObjectType="Report" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Bảng kê doanh thu trước thuế theo khách hàng" e="Detailed revenue before tax by customer"></title>
  <subtitle v="Từ ngày {ngay_ct1} đến ngày {ngay_ct2}..." e="From {ngay_ct1} To {ngay_ct2}..."></subtitle>
  <grids>
    <grid>
      <fields>

		<field name="ma_kh" width="120">
          <text v="Mã khách hàng" e="Customer Code"></text>
        </field>
		<field name="ten_kh" width="300">
          <text v="Tên khách hàng" e="Customer Name"></text>
        </field>
			
		<field name="t_tieny2_m72" width="100" dataType="N" >
          <text v="Tiền mua" e="Purchase Cost"></text>
        </field>
		<field name="t_tieny2_m54" width="100" dataType="N" >
          <text v="Tiền bán" e="Sale Proceeds"></text>
        </field>
		<field name="t_tien_ln" width="100" dataType="N" >
          <text v="Lợi nhuận" e="Profit"></text>
        </field>

		
		
      </fields>

      &DefaultButton;
    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>5GSJYQgGK1XjzBnCfiBdlfFkoLSWh5J51sxq3T7Juo0DXI8B3Iqrd3PEC3CpefQZgDQv3FQ0UnkVjKRJcwU46DToaVItd+/mYrKEjYj+xwzR3Kc1YTuUMD/1r77IA28jIEjteCoQ1TI1TQC722W3DFJtFbkr4LeDeWnOtj4WyhPmf1dnLt/YdJtQpkvBLcIlWaKakZkKCMbkCamnQXa27kj3UsMV72TUUhrxGdRoYM8V7HCAmvtMwHhxZT/sk7xb</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
  <script>
    <processing>
      <text>
        <![CDATA[<enc>g+KZ+QKBlC+LdD0jHhpbmUBJ1Dly7K6gkm1W0g2ywv0R9l12xD2PyQIJuqHQ2Qh/r40ed6qHdvRWY2PezDNwViQaPe3R9hQUFfBIlOQOqu4=</enc>]]>
      </text>
    </processing>
  </script>
</dir>