<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridReport.xml">
]>

<dir id="ss_bcdttt_tlh" dirViewType="Grid" dirObjectType="Report" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Bảng kê doanh thu trước thuế" e="Statement of revenue before tax"></title>
  <subtitle v="Từ ngày {ngay_ct1} đến ngày {ngay_ct2}..." e="From {ngay_ct1} To {ngay_ct2}..."></subtitle>
  <grids>
    <grid>
      <fields>
		<field name="stt" width="50" align="Center">
          <text v="STT" e="No."></text>
        </field>
		<field name="ngay_ct" width="150" dataType="D" align="center" hidden="true">
          <text v="Ngày c\từ" e="Customer Code"></text>
        </field>		
		<field name="id" width="100" hidden = "true" >
          <text v="Id hệ thống" e="Customer Code"></text>
        </field>
		<field name="ma_ct" width="60" hidden = "true" >
          <text v="Mã c/từ" e="Voucher Code"></text>
        </field>
		<field name="so_ct" width="80" hidden = "true" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
		<field name="ma_job" width="60" hidden = "false" align="center">
          <text v="Mã" e="Job Code"></text>
        </field>
		<field name="so_job" width="80" link="V" align="center" >
          <text v="Số" e="Job Number"></text>
        </field>
		<field name="ma_kh" width="0" hidden = "false">
          <text v="Mã khách hàng" e="Customer Code"></text>
        </field>
        <field name="ten_kh" width="200" >
          <text v="Khách hàng" e="Customer"></text>
        </field>		
		<field name="ma_nv" width="0" hidden = "true">
          <text v="Nhân viên" e="Employee"></text>
        </field>
        <field name="ten_nv" width="200">
          <text v="Nhân viên" e="Employee"></text>
        </field>   


		<field name="xnk_yn1" width="50" align="center">
          <text v="IM" e="IM"></text>
        </field>		
		<field name="xnk_yn2" width="50" align="center">
          <text v="EX" e="EX"></text>
        </field>
		<field name="sea_yn" width="50" align="center">
          <text v="FCL" e="FCL"></text>
        </field>		
		<field name="lcl_yn" width="50" align="center">
          <text v="LCL" e="LCL"></text>
        </field>		
		<field name="air_yn" width="50" align="center">
          <text v="AIR" e="AIR"></text>
        </field>		
		<field name="cts_yn" width="50" align="center">
          <text v="CTS" e="CTS"></text>
        </field>		
		<field name="oth_yn" width="50" align="center">
          <text v="OTH" e="OTH"></text>
        </field>		
		
		
		<field name="t_tienx2_m72" width="100" dataType="N">
          <text v="Chi hộ" e="Pay on Behalf"></text>
        </field>
		<field name="t_tieny2_m72" width="100" dataType="N">
          <text v="Tiền mua" e="Purchase Funds"></text>
        </field>
		
		<field name="t_tienx2_m54" width="100" dataType="N">
          <text v="Thu hộ" e="Collect on Behalf"></text>
        </field>
		<field name="t_tieny2_m54" width="100" dataType="N" hidden="fasle">
		  <text v="Tiền bán" e="Sales Income"></text>
        </field>

		<field name="loinhuan" width="100" dataType="N">
          <text v="Lợi nhuận" e="Profit"></text>
        </field>
		
		
      </fields>

      &DefaultButton;
    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>5GSJYQgGK1XjzBnCfiBdlfFkoLSWh5J51sxq3T7Juo1H5QMyBUNnNmbD5P82/CV0QScMVB8GpgK0cVb6EfyBQ1d9fL02m9C0PFXHPcv0kGL57rKdao3z77HScd5ikk+ISetcCpwfow08UDlbWyUepvQ+KpLgOc8iH9tk2RyPcqkzAovUVjfuz78eQDE1pJ9ByCQCFfmAcScN9fyiBhREg5E33DxaIP6bWBiU+xWdbQfDpBhwxgkRdNwNo3Yo1dCD</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
  <script>
    <processing>
      <text>
        <![CDATA[<enc>XCifUZf8Y2yfvq78OCSkUS1lHXxAGnaNuGBapc1z4ivrj5W5i2FofJ0tQ+HP6xsn76M5Fvvb57Bt6VyslE0Z8rXVaRStzQJyw+1KUdfpUp2lhBTw2jAvsBv+jByY8kWb</enc>]]>
      </text>
    </processing>
  </script>
</dir>