<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridReport.xml">
]>

<dir id="ss_bcqtvh" dirViewType="Grid" dirObjectType="Report" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Báo cáo chi tiết nhật ký" e="Detailed log reports"></title>
  <subtitle v="Từ ngày {ngay_ct1} đến ngày {ngay_ct2}..." e="From {ngay_ct1} To {ngay_ct2}..."></subtitle>
  <grids>
    <grid>
      <fields>
		<field name="line" width="150" hidden="true">
          <text v="Số dòng" e="Line"></text>
        </field>
		<field name="ma_donvi" width="120" hidden="false">
          <text v="ĐƠN VỊ" e="UNIT"></text>
        </field>
		<!-- <field name="ma_pb" width="120" hidden="true"> -->
          <!-- <text v="MÃ PHÒNG BAN" e="Employee Code"></text> -->
        <!-- </field> -->
		<field name="ma_nv" width="100" >
          <text v="CODE NV" e="EMPLOYEE CODE"></text>
        </field>
		<field name="ten_nv" width="150">
          <text v="TÊN NV" e="EMPLOYEE NAME"></text>
        </field>
		<field name="ten_parent" width="150">
          <text v="TÊN TL" e="TEAMLEADER NAME"></text>
        </field>
		<!-- <field name="team" width="120" hidden="false"> -->
          <!-- <text v="TEAM" e="TEAM"></text> -->
        <!-- </field> -->
		<field name="ma_bp" width="120" hidden="false">
          <text v="TEAM" e="TEAM"></text>
        </field>
		<field name="ma_so_thue" width="150" >
          <text v="MÃ SỐ THUẾ" e="TAX"></text>
        </field>
		<field name="ho_ten" width="150" >
          <text v="TÊN KHÁCH HÀNG" e="CUSTOMER NAME"></text>
        </field>
		<field name="sdt_vua_goi" width="120" hidden="false" align="right" >
          <text v="SỐ ĐIỆN THOẠI" e="Phone number"></text>
        </field>
		<field name="ma_td" width="120" hidden="false">
          <text v="MÃ TÁC ĐỘNG" e="ACTION CODE"></text>
        </field>
		<field name="ma_plkh" width="120" >
          <text v="P/LOẠI KHÁCH HÀNG" e="CUSTOMER CLASSIFICATION"></text>
        </field>
		<field name="dien_giai" width="150" hidden="false">
          <text v="GHI CHÚ CALL" e="CALL NOTE"></text>
        </field>
		<!-- <field name="ngay_gio_goi" width="120" hidden="false" align="center" > -->
          <!-- <text v="NGÀY GIỜ GỌI" e="DATETIME CALL"></text> -->
        <!-- </field> -->
		<field name="gio_goi" width="120" hidden="false" align="center" >
          <text v="NGÀY GIỜ GỌI" e="DATETIME CALL"></text>
        </field>
		<field name="ngay_goi_lai" width="120" hidden="false" dataType="D" align="center" >
          <text v="NGÀY GỌI LẠI" e="CALLBACK TATE"></text>
        </field>
      </fields>

      &DefaultButton;
    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>7qUuzbkaMoctM4Y9y+HkqrbmH9cnJnuoFgGvbg97e/WcRWYLRmRnvBTsxurDDFdVo8NKdZ4wuex+oeZDVufj8W8VoXTQwXe63W+rx/tUXX1QUV+cWnZiFFMf6FmTI1yFAULn4zJA1q2rGS6yXRd06R+hAoAcfLOt70fhReBC8sarKAiRPZsSi97cIbrdF/Z5/dk2Pk5J9l2lN2/9FzzPVjwWGp7LrSpzFAwn9jbj8W6H/qN4RhrSl/SrxKAZetrp</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
  <script>
    <processing>
      <text>
        <![CDATA[<enc>g+KZ+QKBlC+LdD0jHhpbmT5PlTTYCHPNEYImMfXpE5vnSfc1V27kBZi0JcbZsVIM5BVJV9l2QTbx4iFhfdO+9xg+YdQpWKF+SAU7imbkttT4fMi8AOQ2lEfWEkh+f+jbkfCn4/37h+CneDrrq50UDWZ7RQQ5p4SmNLqotTdoeLzlKPxCPM9hbRpw1ORGM6bT</enc>]]>
      </text>
    </processing>
  </script>
</dir>