<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridReport.xml">
]>

<dir id="ss_lslncuocgoi" dirViewType="Grid" dirObjectType="Report" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Call Detail" e="Call Detail"></title>
  <subtitle v="Từ ngày {ngay_ct1} đến ngày {ngay_ct2}..." e="From {ngay_ct1} To {ngay_ct2}..."></subtitle>
  <grids>
    <grid>
      <fields>
	  	<!-- <field name="uniqueid" width="150" align="right"  hidden="false"> -->
          <!-- <text v="UNIQUEID" e="UNIQUEID"></text> -->
        <!-- </field> -->
		<field name="o_number" width="80" hidden="false" align="right">
          <text v="STT" e="STT"></text>
        </field>
		<!-- <field name="ma_donvi" width="120" hidden="false"> -->
		  <!-- <text v="Unit" e="Unit"></text> -->
		<!-- </field> -->
		<field name="exnum" width="120" hidden="false">
          <text v="Ex. Number" e="AccountCode"></text>
        </field>
	  	<field name="accountcode" width="120" hidden="false">
          <text v="Client" e="Client"></text>
        </field>
		<field name="ten_nv" width="180" hidden="false">
          <text v="Fullname" e="Fullname"></text>
        </field>
		<field name="src" width="120" align="right"   hidden="false">
          <text v="Source" e="Source"></text>
        </field>
		<field name="dst" width="150" align="right"   hidden="false">
          <text v="Destination" e="Destination"></text>
        </field>
		
		<field name="ma_bp" width="120" hidden="false">
		  <text v="Group" e="Group"></text>
		</field>
		
		<field name="durationqd" width="150" hidden="false" align="right">
          <text v="Duration" e="Duration"></text>
        </field>
		<field name="billsecqd" width="150" align="right" hidden="false">
          <text v="Billsec" e="Billsec"></text>
        </field>
		
		<field name="ttcall" width="150" hidden="false">
          <text v="Call Status" e="Phone number"></text>
        </field>
		<field name="ma_so_thue" width="200" hidden="false">
          <text v="Mã số thuế" e="Tax Code"></text>
        </field>
		<field name="ma_td" width="150" hidden="false">
		  <text v="Call Note" e="Call Note"></text>
		</field>
		<!-- <field name="billsec" width="150" hidden="false" align="right"> -->
          <!-- <text v="Duration(s)" e="Billsec"></text> -->
        <!-- </field> -->
		<field name="hangup" width="150" hidden="false">
          <text v="Hangup Person" e="Hangup Person"></text>
        </field>
		<field name="ngay_kt" width="150" hidden="false" align="center">
          <text v="Maker Date" e="Maker Date"></text>
        </field>
		<field name="ngay_goi" width="150" hidden="false" align="center">
          <text v="Time Start" e="Time Start"></text>
        </field>

		<!-- <field name="ma_td" width="0" hidden="false"> -->
          <!-- <text v="Mã tác động" e="STT"></text> -->
        <!-- </field> -->
		<!-- <field name="ten_td" width="200" hidden="false"> -->
          <!-- <text v="Trạng thái tác động" e="STT"></text> -->
        <!-- </field> -->

      </fields>

      &DefaultButton;
    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>p45rP2MBMiXDOsXOIKyWQWyyNeY0GdTusUDy52Tld2QIgM4WZ3DdGc9XXcRRaWQMdzKPE0zKLu+oKkKGmLW/xEMBkuEWP8p9VVwN+4cjEoAnjBt97naRohQg6H08luQWkcgT1xmiSEgvFPo98gZlkD5iMdWDyomopRRiJfro+5vdjaBboGE0oQQmF24mSWeUmg3sSSbqS6QwUw6VCgxe5poX0FUTP8eqh3BknoD83GRuqTGx46Rnb0LCZFMns3WO</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
  <script>
    <processing>
      <text>
        <![CDATA[<enc>5Rm3Bi+3VEgtR4rweUbreBqL6Auh76IqASKWurKDn7FqVOx8SDNjj9YhTp5VZSqDz1SDFzRb7VR4ucNWN9ATxqnmvsmU5QQ8dXrvJGVzyDNNJYOQJfVqpq2kwMpsfg+khgEcxG+lQfdE9V/TnE4DPOGYGqdIhNd5Q7ykU/3wKGvxEOehx5unQaDSkrXeOls7</enc>]]>
      </text>
    </processing>
  </script>
</dir>