<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="t21" dirViewType="Grid" dirObjectType="Voucher" voucherCode="TC0" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Tạo chuyến hàng" e="Create a shipment"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>

  <grids>
    <grid table="t21" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true">
      <fields>
        <field name="so_ct" width="100" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="120" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
		<field name="id_dh" dataType="N" format="0" width="100" hidden="false">
          <text v="Số đơn hàng" e="Order number"></text>
        </field>
		<field name="ma_gd" viewType="Combobox" inactivate="true" width="100">
          <text v="Giao dịch" e="Status"></text>
          <viewInfo>
            <options query="select ma_gd, ten_gd%l from dmgd where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>

        <field name="ma_kh" width="0" hidden = "false">
          <text v="Mã khách hàng" e="Customer Code"></text>
        </field>
        <field name="ten_kh" width="250" fieldType="EX" >
          <text v="Khách hàng" e="Customer Name"></text>
        </field>
		
		<field name="ma_hang" width="0" >
          <text v="Hãng tàu" e="Carrier"></text>
        </field>
		<field name="ten_hang" width="250" fieldType="EX" >
          <text v="Hãng tàu" e="Carrier"></text>
        </field>		
		<field name="ma_noi_di" width="0" hidden="false">
          <text v="Nơi đi" e="Origin"></text>
        </field>
		<field name="ten_noi_di" width="250" fieldType="EX">
		  <text v="Nơi đi " e="Origin Name"></text>
		</field>
		<field name="ma_noi_den" width="0" hidden="false" >
          <text v="Nơi đến" e="Destination"></text>
        </field>	
		<field name="ten_noi_den" width="250" fieldType="EX" >
		  <text v="Nơi đến " e="Destination Name"></text>
		</field>		
		<field name="ngay_hl" width="120" dataType="D">
          <text v="Ngày hiệu lực" e="Effective  date"></text>
        </field>
		<field name="ngay_hld" width="120" dataType="D">
          <text v="Ngày hiệu lực đến" e="Expiry  date"></text>
        </field>
		<field name="t_so_luong" dataType="N" format="FCAmount" width="80">
          <text v="Tổng container" e="Total Container"></text>
        </field>
		<field name="dien_giai" width="250">
          <text v="Diễn giải" e="Explain"></text>
        </field>
		<field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="120" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="120" fieldType="EX" >
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>pJ2i7WvWz6Z3YXxOIgUjuTWopbANQenC1cPAeVmg9HsscoVWQKXpjHtPYkvMP+g3RgcbG2wiDehUFZ+/rr9G1APCx7Vw04FYhIvalFbO+s3BZKkbtW2+N7w5VFSo0+Q4Yv2WbnVZs6VyFHk5V876W8Pu0at+C6R8YfMawhyU2RfGXM0qolCRUWxgU6u5b1KdHfLapWbip8kqmArqz5TlKPu/wU7faDGGBfPagdosBKLi9mktVLuzUH/wLOGvCjckT31ZGzqw/RVAW7akMNeASkZuev1ZxS+Lw11VEv9rnjncymU8zosMI879W+AmAVkjDuGUOuFH1kIHOR+iyeS9GQjhivL6qC8XlZWfnvM0FqJyOMfZSskumnGaVO/1INw71X81LbQZEh/Y56weIhtOjw==</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>jsn6gEHrikxfl4eH8MP8ZTcj/X1lc8CtaF7FhQnFu3f/UPmmtpO3wIkJqkO2MMgUqcPqAY0UlDApz3WnKG3v9x/zY/loEbLMXxYJk60w6nu/74dTg3D46nAbcK01PJkYUJ+j9tFegN+9kQTfwVpmVYr/WVAYwZ/Lc/IQCcYwUMMaq3AoStBgq2k4r1WNTCMA3QP4I8TTzw3TyDRfFTgVii+7k05HpgX1/lEwNVDJuv849zB2RX1W5ichiqZP7Z3+It35U7bu54ZHTwCbhrgE7vA9IJyXkBu0SWxiNLEROV4ZJSjtC86epsbGFcnCBsYOccWH1fcHpdBzf9806NRWaTWQAH/9n5xKtC4CvnIpJZ+l+AymBgl0g6xY7UkIy6IrIV9x0RPFE5jK4/aFyyB2WHDa9bFsisWCFvT1vmpD/wHJ9Fv7qb+HEst/af92fUXQF6uwANNXIfOjN51vME+w0zYfEoMWjy5Et1V7168AbBXtI2uYWdDSrZ1cFYcxnUY3rW6tuOt81xv7dBEUxzFLzDMp1wu5K5MWHsLRLbhBbZ1o8iGZc6WVFmMoK+x6mQf6hsrPSj0WB624+ekCZ7A5Oy/4XZRTyVBKnGnYCzrtaFYWKTyxsM8oHhTe4ZQpl+5ffUi8y3lgSr4+8gGK0Lff1M1c2c6ocmlCFOgg0CfIytcokTedO3W7kJCXSJJ8WoS45rrp9Ht0cke3GjDTbTMeig==</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>jzcoae1D7/AzsY7GhcCcRdPbF5pa5HCoTC0+iRVnSAmCcdloCo0p1JepmWotXX5tXLuBHCrhA0uhYGnIYVUSdbq6oel+qap+gSLrB27lkoSTr7jVNzIPy3nBW96ad/szSLccD765FUcXvSYHM7FS4le8iTgGoJ8XB1KovsNH6zUtJE0xfZNo0TiCDpjtDfcvAykvOj/3zg1Qzy8iujnmUA==</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>

  <script>
    &VoucherJSLoading;
  </script>
</dir>