<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="t311" dirViewType="Grid" dirObjectType="Voucher" voucherCode="TT1" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Tạo điều xe tròn tua" e="Create a shipment"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>

  <grids>
    <grid table="t311" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true">
      <fields>
	  	<field name="ma_ldx" width="80" >
          <text v="Hình thức" e="Carrier"></text>
        </field>
        <field name="so_ct" width="100" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="120" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>

        <field name="ma_xe" width="0" hidden = "false">
          <text v="Mã đầu kéo" e="Tractor Code"></text>
        </field>
        <field name="ten_xe" width="250" fieldType="EX" >
          <text v="Đầu kéo" e="Tractor Name"></text>
        </field>
		<field name="ten_ldx" width="250" fieldType="EX" >
          <text v="Tên hình thức" e="Carrier"></text>
        </field>
		<field name="ma_tx" width="0" >
          <text v="Tài xế" e="Carrier"></text>
        </field>
		<field name="ten_tx" width="250" fieldType="EX" >
          <text v="Tài xế" e="Carrier"></text>
        </field>			
		
		<field name="ma_rm" width="0" >
          <text v="Tên rơ mooc" e="Carrier"></text>
        </field>
		<field name="ten_rm" width="250" fieldType="EX" >
          <text v="Rơ mooc" e="Carrier"></text>
        </field>	
		
		<field name="dien_giai" width="250">
          <text v="Diễn giải" e="Explain"></text>
        </field>
		<field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="120" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="120" fieldType="EX" >
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>jwDuc7WFdmq8N/fF/KJHbXkJNzdHOip8+iX01ErUTKm8YN+nQp0yJ3miy3Bs6S0HOXWCquba9Eyh9GOpcfsnml9gmPM9nRBnwisXEV89cOCdIXbKuoV8kD3PkelSDD7Q0Zd1/dTA8MsdGH+iJ6AWnG6xyYLlvDIj5SeNBdGJpY0g8pCxwEV2hhYiTeaT6oBGXbbdflF9jaW8DcnwJFj3kvdvAykt+gV1vgBwJXuIq1OnPCQxQBFrv3192eRjogAYg+4oZrpyfEyKRMsK4rclaCwcyHF32xT1Nwtz/WTGzCOw9LtrXtWJDq3zIsQiAfcJoJu3hxHMLnm0xX4lBTVrMtEgD06k4D+QBWaoybUuunyS1K5HR/zdfm5ydGodv3s+jzeImSC6ExcQhy+gRmobJA==</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>+X9sfqDNRQHlmI8CW9fiGyjzuwNiniSqBg2ZQqw1G4SsPonOxG+OhHojTO+iV/n4osUOecG1+m/7i2i9z8tc09cVJm0Kf2W24L35wkKNdI4Ata41zHHRFJALLyhhmOYG+5nicG/bNf9aQg0AT7jTQgfyThfB11VYecqHKmCb+uR93yA2x0sYsDkC1Rl5RAV9T+2T+ngjiH92ZIlN/vaHIzTYrWYrAyV+g9OFvh3yk3mdZfLTuh4m14A1moutIKig4ysSo1ybuzpZ+AFLmdhmWqie01s8tudfPr06MAuOy7d1BsdQ0CQ8CxpGRooJ2X8o8C9BJ3IyGL/sfDlaJtF1C4HgNVKDNqPksrnROlJnW7sMn4TneEVxUD3y0MrvgVrT2hhI2JnFshLG0SiVRPqnoYU91aExv444j2+uafQHyXhW9IyZgxV2HNT61ySoF1fNbAVj5Uh+AVSFyJm5xg4bCSe0er5+EY3270xFHjbJpuCLoY52quPNf5qJ3RGT6N9iRB0/W3EoCJ8+nAbbdNXf/O+2kKpiB26XkfqOQ5qEYw0oExOMOgCbTkqm62q4WP6KYQxYf4j4qGvt1d5ocwCFrefOobRGAtvYR5d2oiMf3gwcJFUuKnj/DHwTw2zJnvn0Uzv4CqnH3XIRbw8wddyktLN12/cqxdSWOYR7r1Mvx9L/e15HNB7o15n9ybLvIHAf</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>jTwWP4URN13fjiNnm/IWVHWbxgislSrQr10kPl1PjemM8pHHdEtmysrmJiSFiJ24xF8Xa4QLDO4PZGXiRVr/SlYBhf32ib/G5YntKehj/HysmU7tRdFdFKKQLmDIccG2vUbk7KkiQ1xyjZPNMY9CRiAy7bj6AJwrDKIU6vaWDtCDWVE3Kj/JLg245BsGkJ/64fzY78fSei3nHb8Sue5ELg==</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>

  <script>
    &VoucherJSLoading;
  </script>
</dir>