<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="tb_Brand" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Thương hiệu" e="Brand"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="tb_Brand" fieldKey="Id" order="Id" allowFilter="true" allowOrder="true" >
      <fields>
        <field name="Id" fieldType="PK" width="120">
          <text v="Mã thương hiệu" e="Brand code"></text>
        </field>
		 <field name="Title"   width="120">
          <text v="Tên thương hiệu" e="Brand name"></text>
        </field>
		<field name="Alias"  width="120">
          <text v="Alias" e="Alias"></text>
        </field>
		<field name="Description" width="120">
          <text v="Mô tả" e="Description"></text>
        </field>
		 <field name="Detail"  width="120">
          <text v="Chi tiết" e="Detail"></text>
        </field>
		<field name="Position"  width="120">
          <text v="Thứ tự" e="Position"></text>
        </field>
		<field name="SeoTitle"  width="120">
          <text v="Seo Title" e="Seo Title"></text>
        </field>
        <field name="SeoDescription" width="250">
          <text v="Seo Description" e="Seo Description"></text>
        </field>
		<field name="SeoKeywords" width="250">
          <text v="Seo Keywords" e="Seo Keywords"></text>
        </field>
		<field name="IsActive" width="120">
          <text v="Kích hoạt" e="Active"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>Xm0SQO244yhm4oovG3IvuNxOf1OYSDcg4eRUGISNxobTbjaX4O3mL6uCa8CbfIzojKlJCfhLpSTxZMQqYGybhl4sdWeH6klkvuEnVDAq8vbCGk8cCn569oTLIp5GSTlwDa/Dl+mDZl3J81mcmWu9gXZGdhRELgjkxxMrFVDYauBE6WUcgYPGujXVb/Hkz9Lw</enc>]]>
    </text>
  </js>
</dir>