<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="tb_Category" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục" e="Category List"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="tb_Category" fieldKey="Id" order="Id" allowFilter="true" allowOrder="true" >
      <fields>
        <field name="Id" fieldType="PK" width="120">
          <text v="Mã danh mục" e="Category code"></text>
        </field>
		 <field name="Title"   width="120">
          <text v="Tên Danh mục" e="Category name"></text>
        </field>
		<field name="Alias"  width="120">
          <text v="Alias" e="Alias"></text>
        </field>
		<field name="Description" width="120">
          <text v="Mô tả" e="Description"></text>
        </field>
		 <field name="Detail"  width="120">
          <text v="Chi tiết" e="Detail"></text>
        </field>
		<field name="Position"  width="120">
          <text v="Thứ tự" e="Position"></text>
        </field>
		<field name="SeoTitle"  width="120">
          <text v="Seo Title" e="Seo Title"></text>
        </field>
        <field name="SeoDescription" width="250">
          <text v="Seo Description" e="Seo Description"></text>
        </field>
		<field name="SeoKeywords" width="250">
          <text v="Seo Keywords" e="Seo Keywords"></text>
        </field>
		<field name="IsActive" width="120">
          <text v="Kích hoạt" e="Active"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>
 <css>
    <text>
      <![CDATA[<enc>Wr8k+dVX75qyIrFjR3AHzrD1Zqw+63/8icBaJpC4y+U0Lj0al2yOWA6urYbyHpWAvI5i5URbBaV6mSloPmTd5A/Rd2KTHQfufpQOFRMvNpUSbGCv0n/FLtjnAKKFSupLhckbF12KoiXKwbwLwWyK+c7QSJ2vmeOIB04GljKF7cI=</enc>]]>
    </text>
  </css>
  <js>
    <text>
      <![CDATA[<enc>GYD0OC5JhpEhu2renQHOp6Zu14uQovw5+gChWnoUYf4huSZ8p/Rbnw0RvtzyP3TsCggI8lbv0jDT/s7VofkU+n85PiG/HodmtnwtDhbdcxdyQcsrhz9TBE6K7ugv8eh9fYAeXmb3EFpxOc3GAHas5aIOisuUYQfeeTHCAtXG9loJ/NmKVFJBh4s9eURUbpzqIXMxHM/wLjZRbyUdz0DzwA==</enc>]]>
    </text>
  </js>
</dir>