<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="tb_CategoryType" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Loại danh mục" e="Category Type List"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="tb_CategoryType" fieldKey="Id" order="Id" allowFilter="true" allowOrder="true" >
      <fields>
		<field name="Id" fieldType="PK" width="120">
          <text v="Mã loại danh mục" e="Category type code"></text>
        </field>
		 <field name="Title"   width="120">
          <text v="Tên loại danh mục" e="Category type name"></text>
        </field>
		<field name="Alias"  width="120">
          <text v="Alias" e="Alias"></text>
        </field>
		<field name="Description" width="120">
          <text v="Mô tả" e="Description"></text>
        </field>
		 <field name="Detail"  width="120">
          <text v="Chi tiết" e="Detail"></text>
        </field>
		<field name="Position"  width="120">
          <text v="Thứ tự" e="Position"></text>
        </field>
		<field name="SeoTitle"  width="120">
          <text v="Seo Title" e="Seo Title"></text>
        </field>
        <field name="SeoDescription" width="250">
          <text v="Seo Description" e="Seo Description"></text>
        </field>
		<field name="SeoKeywords" width="250">
          <text v="Seo Keywords" e="Seo Keywords"></text>
        </field>
		<field name="IsActive" width="120">
          <text v="Kích hoạt" e="Active"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>wZj3cFuL3E/nXfBZm9QlQycFPuZ3rqYrqoFHaj9C3LNmR2V0RFd0wzcy5ivWJYGWnWetL4jNA2sIqwhANQv1S91L2Gr569xgfSFN+8ZDXjLz51zoHPJY80qjlLfHTiN5DZTUFi4Fp3ERuNypxuiV0X0+vUt1xSVGzPJ+2TV6meBPpastslEphKlEkLA9RmcCbDvDD31XnRiPKGqLM2P+pg==</enc>]]>
    </text>
  </js>
</dir>