<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="tb_Promotion" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Khuyến mãi" e="Promotion"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="tb_Promotion" fieldKey="Id" order="Id" allowFilter="true" allowOrder="true" >
      <fields>
        <field name="Id" fieldType="PK" width="120">
          <text v="Mã khuyến mãi" e="Promotion code"></text>
        </field>
		 <field name="Title"   width="120">
          <text v="Tên khuyến mãi" e="Promotion name"></text>
        </field>
		<field name="Alias"  width="120">
          <text v="Alias" e="Alias"></text>
        </field>
		<field name="Description" width="120">
          <text v="Mô tả" e="Description"></text>
        </field>
		 <field name="Detail"  width="120">
          <text v="Chi tiết" e="Detail"></text>
        </field>
		<field name="Image"  width="120">
          <text v="Hình ảnh" e="Image"></text>
        </field>
		<field name="Position"  width="120">
          <text v="Thứ tự" e="Position"></text>
        </field>
		<field name="CategoryId"  width="120">
          <text v="Mã danh mục" e="Category code"></text>
        </field>
		<field name="Link"  width="120">
          <text v="Link" e="Link"></text>
        </field>
		<field name="SeoTitle"  width="120">
          <text v="Seo Title" e="Seo Title"></text>
        </field>
        <field name="SeoDescription" width="250">
          <text v="Seo Description" e="Seo Description"></text>
        </field>
		<field name="SeoKeywords" width="250">
          <text v="Seo Keywords" e="Seo Keywords"></text>
        </field>
		<field name="IsActive" width="120">
          <text v="Kích hoạt" e="Active"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>res7o41ZyxV7ie5eKEA1FQVC8OlO1wpNcXbZ9mYf6gnFnej2FH0HF9lMRmVDXwLeF4r+vVu6mLt+lMqJezw2B3bwIB19iwnPQLgcZXIjLjTiXm0GjhSf/FiULhPs650wtQAtmsV8L0h4xz7YskzdRjnaOQyXvX28U2NKoXWaOqeeJe307No+hnUwQWgHY31KKs2Q+QrO/+hyFBZ8NEJWKQ==</enc>]]>
    </text>
  </js>
</dir>