<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="tb_ProductCategory" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Loại sản phẩm" e="Vehicle List"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="tb_ProductCategory" fieldKey="Id" order="Id" allowFilter="true" allowOrder="true" >
      <fields>
        <field name="Id" fieldType="PK" width="120">
          <text v="Mã loại sản phẩm" e="Product type code"></text>
        </field>
		<field name="Title" width="120">
          <text v="Tên loại sản phẩm" e="Product type name"></text>
        </field>
		<field name="Alias"  width="120">
          <text v="Alias" e="Alias"></text>
        </field>
		<field name="Description" width="120">
          <text v="Mô tả" e="Description"></text>
        </field>
		<field name="Icon" width="120">
          <text v="Icon" e="Icon"></text>
        </field>
		<!-- <field name="Position"  width="120"> -->
          <!-- <text v="Thứ tự" e="Position"></text> -->
        <!-- </field> -->
		<field name="CategoryTypeId"  width="120">
          <text v="Mã loại danh mục" e="Category type code"></text>
        </field>
		<field name="SeoTitle"  width="120">
          <text v="Seo Title" e="Seo Title"></text>
        </field>
        <field name="SeoDescription" width="250">
          <text v="Seo Description" e="Seo Description"></text>
        </field>
		<field name="SeoKeywords" width="250">
          <text v="Seo Keywords" e="Seo Keywords"></text>
        </field>
		<field name="IsActive" width="120">
          <text v="Kích hoạt" e="Active"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>QBrhxNLMAf9ag6nys9vC8eNt6JzoU23Oqx/3ymuEm/8hvr0AxwxbeT2hUee09EsKJWFf1946+tipSu/SEAUqhbNKgv8tZSP624OllRiwVj519qFBwolL8+GCC4DZXfJRHQaYae8UfwcLn+3gd0GZlsDCr81UplwRh89DI35HcC6KqoLa70CJUjxse8Jn0DkM75keGymqRvo7dbz2fOOgOg==</enc>]]>
    </text>
  </js>
</dir>