<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="tb_Post" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Bài viết" e="Brand"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="tb_Post" fieldKey="Id" order="Id" allowFilter="true" allowOrder="true" >
      <fields>
        <field name="Id" fieldType="PK" width="120">
          <text v="Mã Bài viết" e="Brand code"></text>
        </field>
		 <field name="Title"   width="120">
          <text v="Tên Bài viết" e="Brand name"></text>
        </field>
		<field name="Alias"  width="120">
          <text v="Alias" e="Alias"></text>
        </field>
		<field name="CategoryId"  width="120">
          <text v="CategoryId" e="Alias"></text>
        </field>
		<field name="Description" width="120">
          <text v="Mô tả" e="Description"></text>
        </field>
		 <field name="Detail"  width="120">
          <text v="Chi tiết" e="Detail"></text>
        </field>
		  <field name="ViewCount"  width="120">
          <text v="Lượt Xem" e="Detail"></text>
        </field>
		<field name="SeoTitle"  width="120">
          <text v="Seo Title" e="Seo Title"></text>
        </field>
        <field name="SeoDescription" width="250">
          <text v="Seo Description" e="Seo Description"></text>
        </field>
		<field name="SeoKeywords" width="250">
          <text v="Seo Keywords" e="Seo Keywords"></text>
        </field>
		<field name="IsActive" width="120">
          <text v="Kích hoạt" e="Active"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>fwAk1FETPvvMjc3Jqxd5NaP1M4s4qQImlj+O9y8+YfVUqbYK3nuhTMKYNuy5FXS+LY0dpXrBUKuVz8SDWyna8ySgWqfuOTJ6KbherSEhJwosdF0LwtUWElAs5g1UpU+1OD0jjaHE4pwatyTm/D9jEaAFEOY8qzmOgk/zdt5hRgUQnMZWZo2NwJ0VH+pP88i4</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>cTMcaemK/mtRjps8m/sJOVirlLEJ+6JxiLPeJpYli4TAugeI+9xS9CIT96sX4XiNHefVQOt7fompL31ydAZJ3zbOdWMd5eIffmA/BGo5olHD9HllibL9oaJ+q8SIGGIxctuUbBiK/AoBCVom/JB6t7K63gLTkI+n1+rKmi9w1o3agX3Q3T7VA7fpVMPNyATDKCMwOuHkuP8gVjUw+qEn8lDMfSVRMnD0/FysmWigoBh/gLFLiJHLlzQDzpc5t/w9ovG2+hZPKJkxSGbquy14Z/Moy+LeKNtoKkGhDFJLvHX1Z9I5Pqnoi64lNbwHXFIxbOALp0KsYLr56b26De9xBtmOeTdLi0YparLh4bTcD2fca+XxZyDGiDNFsNbEQ0ln</enc>]]>
    </text>
  </css>
</dir>