<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="tb_Category" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục Store" e="Vehicle List"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="tb_Category" fieldKey="Id" order="Id" allowFilter="true" allowOrder="true" >
      <fields>
        <field name="Id" fieldType="PK" hidden="true" width="120">
          <text v="Mã Xe" e="Vehicle Code"></text>
        </field>
		 <field name="Title"   width="120">
          <text v="Tên Danh mục" e="Vehicle name"></text>
        </field>
		<field name="Alias"  width="120">
          <text v="Alias" e="Address"></text>
        </field>
		<field name="Description" width="120">
          <text v="Description" e="Color"></text>
        </field>
		 <field name="Detail"  width="120">
          <text v="Detail" e="Type code"></text>
        </field>
		<field name="Position"  width="120">
          <text v="Position" e="Weight"></text>
        </field>
		<field name="SeoTitle"  width="120">
          <text v="SeoTitle" e="Capacity"></text>
        </field>
        <field name="SeoDescription" width="250">
          <text v="SeoDescription" e="Status"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>GYD0OC5JhpEhu2renQHOp6Zu14uQovw5+gChWnoUYf4huSZ8p/Rbnw0RvtzyP3TsCggI8lbv0jDT/s7VofkU+n85PiG/HodmtnwtDhbdcxdyQcsrhz9TBE6K7ugv8eh9fYAeXmb3EFpxOc3GAHas5aIOisuUYQfeeTHCAtXG9loJ/NmKVFJBh4s9eURUbpzqIXMxHM/wLjZRbyUdz0DzwA==</enc>]]>
    </text>
  </js>
</dir>