<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="tbCategoryType" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Loại danh mục" e="Category Type List"></title>
  <subtitle v="Thêm, xóa, sửa..." e="New, delete, edit"></subtitle>
  <grids>
    <grid table="tb_CategoryType" fieldKey="Id" order="Id" allowFilter="true" allowOrder="true" >
      <fields>
        <field name="Id" hidden="true" fieldType="PK" width="120">
          <text v="Mã loại danh mục" e="Category Type Code"></text>
        </field>
		<field name="Title" fieldType="PK" width="120">
          <text v="Tên loại danh mục" e="Category Type Name"></text>
        </field>
		<field name="Position"  width="120">
          <text v="Thứ tự" e="Position"></text>
        </field>
		<field name="IsActive" width="120">
          <text v="Kích hoạt" e="Active"></text>
        </field>
		 <field name="CategoryId"  width="120">
          <text v="Mã danh mục" e="Category Code"></text>
        </field>
		<field name="SeoTitle"  width="120">
          <text v="SEO Title" e="SEO Title"></text>
        </field>
		<field name="SeoDescription"  width="120">
          <text v="Seo Description" e="Seo Description"></text>
        </field>
        <field name="SeoKeywords" width="250">
          <text v="Seo Keywords" e="Seo Keywords"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>res7o41ZyxV7ie5eKEA1FX92CoG5jzphAZy22DPAagaMsi3Wc+DobdstC4jUkMxJVUBqI4DepsVpkUXW03TiJ6PnTlkyAFskF5txNWBbdEg7sjlU6LBJIaj3K0b/jMGIvxonTW91VX+/3AUiDuvBkTBv+YYk/wR+xQ50mc40UN6hlLA3Ovi6wv9re62oNOeRkK/D6JHRTU9Wf0KXcCmjOg==</enc>]]>
    </text>
  </js>
</dir>