<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="wfdmkh" dirViewType="Grid" dirObjectType="Voucher" voucherCode="WF1" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh sách cấu hình workflow" e="Workflow Configuration List"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>

  <grids>
    <grid table="wfdmkh" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true" key="ma_ct = ''WF1''">
      <fields>
	    <field name="ma_ct" width="0" link="V">
          <text v="Mã c/từ" e="Voucher Code"></text>
        </field>
        <field name="so_ct" width="100" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="120" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
		<field name="ma_wf" width="120" link="V">
          <text v="Mã workflow" e="Workflow Code"></text>
        </field>
		<field name="ds_kh" width="250">
          <text v="Khách hàng áp dụng" e="Applied Customer"></text>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="120" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="120" fieldType="EX" >
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="ten_unit" width="200" fieldType="EX" >
          <text v="Tên đơn vị" e="Unit Name"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      <buttons>
        <button id="add">
          <text v="$AddToolbar" e="$AddToobar"></text>
        </button>
        <button id="edit">
          <text v="$EditToolbar" e="$EditToolbar"></text>
        </button>
		<button id="delete">
          <text v="$DeleteToolbar" e="$DeleteToolbar"></text>
        </button>
        <button id="view">
          <text v="$ViewToolbar" e="$ViewToolbar"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="refresh">
          <text v="$RefreshToolbar" e="$RefreshToolbar"></text>
        </button>
        <button id="freeze">
          <text v="$FreezeToolbar" e="$FreezeToolbar"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="print">
          <text v="$PrintToolbar" e="$PrintToolbar"></text>
        </button>
        <button id="export">
          <text v="$ExportToolbar" e="$ExportToolbar"></text>
        </button>

      </buttons>

      <script>
        <query>
          <text>
            <![CDATA[<enc>n6SsM4/jSBKuL3BfLolp3JFiEX25/qMBpJKhhJEYZwYAj04FEwyCkp1jTTEqerNRVf0AMgKnU7ygDk0oyVT3hlytR6WYp00UaTppf+34Mh+FMiskJ2NiIZjlTfVAqQnc0EJjc39no/+cz3geH3rkZaQSQ7mbVx3vWKyKG0yiKebSKvxEPEsyjnKb3V5Wr0l5eO64CKbxKKcsO0zOUhfdzhBzHaKMItJOQ9JxltIRoSriovoMqqTcstrvTke3w0y2JESRjMj2u9P3nbXxFYZonw==</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>mwo1s1eIijqejy9zaPb0MjmbkuC8KDJeTl2dhIrj7LnpQShuM3PsbFjVy7IFesCRAumSyugF48YCwHjBd62WW1FsSc0Z/7rWAjA9ehc+gBVpXWDzH0F9Rbv4OpurWSKB2gVCGizwA48uNgxW5VGj02wr9NhlpQpd/FXjWeiLKIwQQf9W7Rv2aYHh7v2kicsgge8b/MRhtOfY+WFO2RXBVJ4auTW0a1JdwFOIxFFm8LhwIgvIinIux0IZo1DvcWlRRfauMXebfiugrBmACyaYa9BSb/oH/h0dlOsz8XzmVvBoDHl7f/7zvSE3JhKZqx+eCzYzscm2okEg8vQRmAb46fsZ4uw5WNsoE4ttslm0pFinxiT8n1dWVKh+Ix47TMSg8+/ekKm/ct3uk+OCFxW66kx1af0Aom1Bq7AOri3JPHIlYMypHpIN8ykOQddxBFvq0BfPJizyfRS7ucB2PSh1/g==</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>fwAk1FETPvvMjc3Jqxd5Nf4THsM12kfD9hXyhvrwcjSjwhSm3uKuDHw/tZyhji/p3/F0zi8d18gZAItrByOlAp/5y01xHBOO1epz7PRT7kHooOWaeHRXH8fNr/DYcaWqia0N9RHFtwv3+wXEnrryIUZiUCpBpVWQt5EeCpIgcTAs3MT8RiND9WjT4bY+X8Y2spEFhHb0cbzOdZlJB89KTQ==</enc>]]>
    </text>
  </js>
  <css>
    <text>
      <![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>

  <script>
    &VoucherJSLoading;
  </script>
</dir>