<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="x11" dirViewType="Grid" dirObjectType="Voucher" voucherCode="VL1" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Tạo đơn hàng tổng" e="Create a total order"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>

  <grids>
    <grid table="x11" fieldKey="id" order="id desc" allowFilter="true" allowOrder="true">
      <fields>
        <field name="so_ct" width="100" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="100" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
        <field name="ma_kh" width="120" >
          <text v="Mã khách hàng" e="Customer Code"></text>
        </field>
        <field name="ten_kh" width="250" fieldType="EX" >
          <text v="Tên khách hàng" e="Customer Name"></text>
        </field>
        <field name="ma_nt" width="80" >
          <text v="Ngoại tệ" e="FC"></text>
        </field>
        <field name="t_sl_n" dataType="N" format="FCAmount" width="120">
          <text v="Tổng số container" e="Total Container"></text>
        </field>
		<field name="t_sl_x" dataType="N" format="FCAmount" width="200">
          <text v="Tổng container đã phân bổ" e="Total containers allocated"></text>
        </field>
		<field name="t_sl_t" dataType="N" format="FCAmount" width="200">
          <text v="Tổng container chưa phân bổ" e="Total unallocated containers"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" width="150">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
            </options>
          </viewInfo>
        </field>
        <field name="unit_id" hidden="true" dataType="I" width="80" >
          <text v="Unit ID" e="Unit ID"></text>
        </field>
        <field name="ma_unit" width="80" fieldType="EX" >
          <text v="Đơn vị" e="Customer Name"></text>
        </field>
        <field name="id" dataType="N" fieldType="PK" format="0" hidden="true">
          <text v="" e=""></text>
        </field>
      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>ut7bmtX51o7ohlkZy11sVIaZnUwHEM+ebZUTVuvKujT003xHFhXk+bfhdo+bOLeOc6q63u3F2aexGLbLnl1qTTXhLrNlXeSxVkMrIqXqOIV0K//tFN5voZDEwxmggErUPzh+qFPUrUMIk3h+Ki6PotHKs2S1UZVa98zmFp4o9+J+uINWCG/0sLwuHcsDKIU19OP6Sc81dVTM/vl6dUUBlcpGftcyDenTxwFE2b469gB46nBpzJU1ETEPwEwoY+NGyJC2fwU1SXrO9LnA5xSiMg==</enc>]]>
          </text>
        </query>

        <finding>
          <text>
            <![CDATA[<enc>/pWgbzuUJ7Zdn9Kv0fh4kHfCrh9htcen1LZ2sIMH8PCdVpUK/Tc9fKyMbkE7DenhQSQ1kTPsOZgCrF8XIQZFox1BYlSlED8yNip95suVjJR0LrH55B5QVCw4N+bK0IBYF3TROK3WrRK9KQHICQxaOwkyh2zd747V8zF9EXrN8Knwm6ZMKYkURsaGFaWHHEIQpCWoFJgvlwxFOLY1DZbt6+WN2MAksEI7IUPwtcil8uUZDdO4I5Te/hv8yZbUAe1tID8kqTg0j9e5jd6A3jTtUGB2cX9GzlukvUzFzyNFXOuzBn3IyNN8mPPLHnUoNNbq6TB4IeAOHQIqHFROKFrk0yQ28IFRjdhWtlJMWx+1NROTP700sVA8nBZTBKHWLZlCR9Mmow7Y3ZQMVSe94mOC5hZCT8zSndIOitAMvZGhckKLQzJw4jEvw+t0eg4P1Tda9NUaLiCj5ENZAgBHJrd5QzHEnViXomVHuMBU+9fYbdkWY9Ofxr7SwudWOqLJYYuCscpbog7vw+48mEH440PEJmjnumPzkcWQ2TWyEW82Umb8Z2akCV1E8ZJjZAQeMIKMTNpO10mpQdUofkSALsWC4w==</enc>]]>
          </text>
        </finding>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>XymOY7dD2w2+zQLbB/WOXEGhmvnHs6lcqBNkKv4mhO/WwLhGgRCvcsG4bbt2X5IS4fg4unKzyLEes23vPbElXY7K4YnamnwVovV1RQQ+6BohZTHzjzZpyjQ7khpJP1dGvRcrIQIQl8wq4xgM2vU2CxlROxpLhK0Ujzb2AtBKtFHGC6pozcZpZtHzj/bd4gqf</enc>]]>
    </text>
  </js>

  <script>
    &VoucherJSLoading;
  </script>
</dir>