<?xml version="1.0" encoding="utf-8"?>

<dir id="dmct" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục chứng từ" e="List of group"></title>
  <subtitle v="Sửa, khóa sổ chứng từ" e="Edit, Lock Voucher"></subtitle>
  <grids>
    <grid table="dmct" fieldKey="ma_ct" order="ma_ct" allowFilter="true" allowOrder="true" key="" >
      <fields>
        <field name="ma_ct" fieldType="PK" width="100" filterType="Code">
          <text v="Mã chứng từ" e="Code"></text>
        </field>
        <field name="ten_ct" width="250">
          <text v="Tên chứng từ" e="Name"></text>
        </field>
        <field name="ma_ct_in" width="100">
          <text v="Mã in" e="Print Code"></text>
        </field>
        <field name="ngay_ks" dataType="D" width="100">
          <text v="Ngày khóa sổ" e="Lock Date"></text>
        </field>
        <field name="ct_nxd" width="100" viewType="Combobox">
          <text v="Loại ct kho" e="Inventory Type"></text>
          <viewInfo>
            <options>
              <option val="0">
                <text v="Khác" e="Other"/>
              </option>
              <option val="1">
                <text v="Nhập" e="Receipt"/>
              </option>
              <option val="2">
                <text v="Xuất" e="Issue"/>
              </option>
              <option val="3">
                <text v="Điều chuyển" e="Transfer"/>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>

      <buttons>
        <button id="edit">
          <text v="Sửa (Ctrl + E, Alt + E)" e="Edit (Ctrl + E, Alt + E)"></text>
        </button>
        <!--<button id="lock">
          <text v="Khóa số liệu chứng từ" e="Lock Voucher Data"></text>
        </button>-->
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="refresh">
          <text v="Làm tươi" e="Refresh"></text>
        </button>
        <button id="freeze">
          <text v="Gim cột" e="Freeze"></text>
        </button>
      </buttons>

    </grid>
  </grids>


  <js>
    <text>
      <![CDATA[<enc>09vAvxNvOeoYrZPo+m12cSwLnAfb9CqOwKl0FP3shHfpJbO7iAGGOF2TCXo1N/y8b1RTUgxYmT6RXDGyA6GoK+PWKSZnVJ2+1tt0ivBCZ6efZz45nWk27MllcyqYeTNcbC/uULzB72O8btfKD+3iN6g00L4U2PKmb4RzLvDyMHAStseBSxD/HHtKWlbiGgb9ReN+Ix1l1WLN4P2i0xP549rMdnOLuTZbLajcPbz0lzb6KKv+6Mk83lHEeixK9GxsSeSOQQBN33Lf+JUxfl+JeEW9clSmLZbXWwmFunSSZ0aQOvR8nlAjXvnEivwvf5qGIt/1hTQ7LGtXQUzIZt0IvjfTw33C5oAlo2SBk5YBsL7SHgKtzKBkD0f0PlQgc2Prcz3QD4vB30GHCMHm4R/ZzpS0OAgW1jaxTSL2tXKSN5qsd1VcYq8HXNCzyRuMw22UhQZoCgLgqznHJ+wZq9NKlQ==</enc>]]>
    </text>
  </js>

  <css>
    <text>
      <![CDATA[<enc>KC1cKJv5fV3yTGRKpOAWLDJoZXGBBb+UQ6CWl894mkLvM8Y0tL3eArP2GU+bgVzsDc2mhMdGCIncd0Pimfo0OEbTAj/Y4u3wx8CHrVOhNcBl44HHScnJdbdFUyGmIxxmzYHJUk1vr4uk7c+nMjJt/g==</enc>]]>
    </text>
  </css>

</dir>