<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridFinding.xml">
]>

<dir id="dmnh" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục phân nhóm" e="List of group"></title>
  <subtitle v="Phân nhóm: &lt;i&gt;{ma_loai_nh} - {ten_loai_nh}&lt;/i&gt;" e="Group: &lt;i&gt;{ma_loai_nh} - {ten_loai_nh}&lt;/i&gt;"></subtitle>
  <grids>
    <grid table="dmnh" fieldKey="ma_nh" order="ma_nh" allowFilter="true" allowOrder="true" key="" >
      <fields>
        <field name="ma_loai_nh" hidden="true" fieldType="PK" width="100">
          <text v="Loại nhóm" e="Parent Code"></text>
        </field>
        <field name="ma_nh" fieldType="PK" width="100" filterType="Code">
          <text v="Mã nhóm" e="Code"></text>
        </field>
        <field name="ten_nh" width="250">
          <text v="Tên nhóm" e="Name"></text>
        </field>
      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>gGAgiEG+77MUNyV95X98a1hs4d3vALjKjwGKm3c3B04VhwZfyJ+IbmbjhNVJMFE1uIm6Ba0oeTqmk/9fBY8OTOzwnudZjW0+iPXQjGMFXmqaluYDLCyT0WjKmObSmiljUz40O9iiFr4dTrb0D1SWsHUb+7sS/2sxKuPkL5I44lZA0+4JpqerzXf1I+0BF+ujRztEWG2vK2JU+qvSR1uORz2fz6djvQnol3EVPKNWl7SSzA2IVFg35kHqbdQfVxd8QVYe6lNJENKa0mpBgi48bWUgvUGkKNqI28zLV9ue1Pb93DszNydrIDe3mFFwuWHY</enc>]]>
          </text>
        </query>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>PoZY7gtiqLjMyWhzpqyQdteYM6BdDOjhFgu1zjS35mpiCr8N6AnLjrPkDmQnm3gzaYI2aGl+WaM7xA0EaJQbB9+DPve+gNelGop/EddiGgSUnYvlfQS9B/JUQrhFoXDHC9HN8ArFksnCwVJ+tZr5NThrqdyDTsG46s8WOIC4sAa+lRYhOII7hVjX26RR1aoI</enc>]]>
    </text>
  </js>
</dir>