<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridFinding.xml">
]>

<dir id="dmnk" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục quyển chứng từ" e="List of voucher book"></title>
  <subtitle v="Chứng từ: &lt;i&gt;{ma_ct}&lt;/i&gt;" e="Voucher: &lt;i&gt;{ma_ct}&lt;/i&gt;"></subtitle>
  <grids>
    <grid table="dmnk" fieldKey="ma_nk" order="ma_nk" allowFilter="true" allowOrder="true" key="" >
      <fields>
        <field name="ma_nk" fieldType="PK" width="100" filterType="Code">
          <text v="Mã quyển" e="Code"></text>
        </field>
        <field name="ten_nk" width="250">
          <text v="Tên quyển" e="Name"></text>
        </field>
        <field name="so_ct_mau" width="150">
          <text v="Số khai báo" e="Voucher Number"></text>
        </field>
        <field name="unit_id" dataType="I" hidden="true" width="80">
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="ma_unit" fieldType="EX" width="120" aliasName="b">
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="kieu_trung_so" viewType="Combobox" valueDefault="5" width="120" >
          <text v="Kiểm tra trùng số" e="Check Duplication"></text>
          <viewInfo>
            <options>
              <option val="0">
                <text v="0 - Không kiểm tra" e="0 - No"></text>
              </option>
              <option val="1">
                <text v="1 - Theo ngày" e="1 - Daily"/>
              </option>
              <option val="2">
                <text v="2 - Theo tháng" e="2 - Monthly"/>
              </option>
              <option val="3">
                <text v="3 - Theo quý" e="3 - Quarterly"/>
              </option>
              <option val="4">
                <text v="4 - Theo năm" e="4 - Annually"/>
              </option>
              <option val="5">
                <text v="5 - Tất" e="5 - All"/>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>

      &DefaultButton;

      <script>
        <query>
          <text>
            <![CDATA[<enc>Sg4uvoojcDc3GzYnlpqsXpBqNlwCfnkwVHpVaOp/Sr30CXxmXPDwHbE8cFAutmiaTXryfSuoFLnPLGTWiXxDloOACQfjzb27lAgQVYMNePdrB8dzF5WFBb5fswWctro8ZR/humHhFduv9Up/7gTmS+WvlXZ42iRxqe9b/8XxfpCp8r8RDqlvaoXWbgiGtpASad3TeT2iYh5vtnttMDAbJV+wJ8nfpdCZL8R6Q6qKDnpsEHwP0UlkL/E2VDaaXIx1mbRGuf8Y/ToawmnFwT0BVoSZnneBHwzzVO8JhVgA64QpfKdwql3ygYFChH106r2uUk1UbL3pch5iiAN3t2YHSRBmgy5AhpAJHkvhMOIXnYlFP92G0Iwh9YJbpj1b7Jaiuu+K5E4o92vpZsoyVDrnEeId2YoRDKYZlvpciNlyBre/rWShN0ixvV6qIp0qiwI4+vF0NWAdBBgVyFv95t1wCxFpLVFBokq6Si8ibClCr8HQgK1jWL4S7tsFk5jMXo0ZWW9ivIOVHl+d2vD4sWoc/A==</enc>]]>
          </text>
        </query>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>wpR3ICmqndSY1Y0uQqHX9LHiEgqEPHI96VFhKy0kXytng0AGSM4dTM0/3yLtdfy6XzVvQZsZKXXSId+WXOOjaJsZhR+LfSPvb/weIGB/eovjQfWTRPeSq0vMrd7buOM9r8oX9ADJlY4nerP9H/68BaLKaTNs3n2q1HBeyj8PIAhjLUyk06XDlxFVcZ5cxO+F</enc>]]>
    </text>
  </js>
</dir>