<?xml version="1.0" encoding="utf-8"?>

<dir id="listcurrentusers" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh sách người dùng đang sử dụng" e="List Of Current Users"></title>
  <subtitle v="Đang sử dụng..." e="Running..."></subtitle>
  <grids>
    <grid table="sysuserinfo" fieldKey="user_id" order="user_id" allowFilter="true" allowOrder="true" key="(@@admin = 1 or user_id = @@userId)" >
      <fields>
        <field name="user_id" fieldType="PK" dataType="N" align="Right" width="40" filterType="Code">
          <text v="ID" e="ID"></text>
        </field>
        <field name="username" width="120" filterType="Code">
          <text v="Tên" e="Name"></text>
        </field>
        <field name="nickname" width="300">
          <text v="Tên đầy đủ" e="Fullname"></text>
        </field>
      </fields>

      <buttons>
        <button id="refresh">
          <text v="Làm tươi" e="Refresh"></text>
        </button>
        <button id="killInstance">
          <text v="Kết thúc phiên làm việc" e="Kill user process"></text>
        </button>
        <button id="clearCache">
          <text v="Xóa bộ nhớ tạm" e="Clear cache"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="freeze">
          <text v="Gim cột" e="Freeze"></text>
        </button>
        <!--<button id="compressAll">
          <text v="Nén lại toàn bộ xml" e="Compress All XML"></text>
        </button>-->
      </buttons>

      <script>
        <query>
          <text>
            <![CDATA[<enc>sgWM+DoEMw4Yu7NzIIeIzr2roYrVMDBrxOgKCksmpWK13SoQhCSzDd+PeEOtVqnx7ARWXz1dKcSl+ogkaWXBZsg8LgsfIt+GvRMkL1hEvqToAFXgEwDhv6l66P2a161ZyMT4Jl5xuxefs68LEOo6bf7PP49F/Rzx8JEsMb4PArHEqzKXTAoVKD00txKruJCSBDEAmrHQXjBvBO6cZQ2XuG0YM+Vl2CuudvjYrfg11nYNqtoE3KmSgoJgKatGyZHr3V2ketyM2yOm7ZFs7RWa3qPkop6IyELBi9LMVZGFe7VbIMF2LbcF3SlBHyWM+ujndHS+oR/v5xLMNRFobPmBj7yQUDy40b7Lug5Ni3/UoQYWT7g6r3PAezX753uCr69xKPyxlDk05plM719LhKYRlhTeY1Ps9RIodp5JFJhBczBmRltkIuUYnTk5gRArbx1C</enc>]]>
          </text>
        </query>
      </script>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>vqqEx1WZDfTyN6LWbZjrfAF3MmZJ03TJZMpRRw1KaqMrgrPsHPZsWBTvRxBmELZvelzuoTbMVPHq8gJQ0oPRlzPIeb5jrnMOsnebDP2V9pkJ3ltKHpPdPlTeMXjEui7jSwRNGQ0BZaAkTbYs5qS8KqEUPT5lEUTYHPHIhHA113f7gXLVZJZEfzjvm6biYyFPyHj57pmUe2lmMw550/LE2Lr+8z0Ytvv3rS3pH52i4TtkEiy9uEjhdcqrMXgrEfg3k0HYT2xWipfmNY9Eqtsda1GIlBIP8vxsYVNvnwO6USYK/5k0ubvFdBqDjksp7uijuolk2A2M0R00zxG8cOeWK1sDrNrddjDk17H0CnTL4h0XH5mnIS93J7uHZ6S5jdKdSwxw6ee31hd2eZqTPwyx00Bt5mGRKMgVcRe1wFJWkoaniZmJzMXEPpJ5Bjnm8j++qbg1zZorW0zDKuFCnOb9R9Zfb54XthR39jtWoB0LEkPqlGjV2sNRydgeXs88dW5bwsZtiesNg4OkM43bphB1CnunoaEV2icwrX2l3a5vsxX+Nkyt2Tq8/sKF4AQdpg0bxBqh4WFIxYVrXRLDpY2lMIeCUz154/2ictiwo2fMLlexI2mm/WT6CEcmDTG0buVwOSzlvWIFlWsMj9tX4beTrtQEBow6Do/eiHPrFLhLNVUJiQVTVYIsGfbMiikdAP4gOqnhuQUMFYYF1hQPD/vZ3UASniD1OcBAaYLuU0iEhVR3bj87TAXjpS/NcUHXCz8Ej4R/HtUHYGcrSrkEsRlkDyh6HxJQP+8o54htmCBBbeM=</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>
  <script>
    <request code="clearCache">
      <text>
        <![CDATA[<enc>0/6rDJy7MgZTBIHArt/bHxyURC1Et80mejrdLj+/pH2E2kmNb5NevyW57oP0KoB1qV1UbJGoJSkr2Yxb5S8pHQ==</enc>]]>
      </text>
    </request>

    <request code="killInstance">
      <text>
        <![CDATA[<enc>0/6rDJy7MgZTBIHArt/bH/PdKdVb6OVsLV4kD8ea8ySgUOcAgnavKa88N3hirFISreBWfTzAK1hts9bnIJeQ/ncd0HMAWmib/ZA9IQfrTsqj3kSO2HLDgXAGoxBdmIIzejfCJYno2kBSKtgz3ASrCA==</enc>]]>
      </text>
    </request>

    <request code="compressAll">
      <text>
        <![CDATA[<enc>0/6rDJy7MgZTBIHArt/bHzLVPiH+mvSNLVxRVE/O/L4X8Uk6p6+aqVzhO+vfAi8DHfgVqOjnXg+bGjgehGcK6DoiQISB0swa4VsVxSUFk8nraKJXxr6yJPTDJ6uZPhn01KoS6fl5j/T+3I4aiS68x4OzvcpmPU/rhcDPOx1y9m8=</enc>]]>
      </text>
    </request>
  </script>

</dir>