<?xml version="1.0" encoding="utf-8"?>

<dir id="sysgroupinfo" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Khai báo nhóm người sử dụng và phân quyền truy cập" e="Group Maintenance"></title>
  <subtitle v="Thêm, sửa, phân quyền nhóm người sử dụng..." e="New, edit group..."></subtitle>
  <grids>
    <grid id="0" table="sysgroupinfo" fieldKey="group_id" order="group_id" allowFilter="true" allowOrder="true" key="(@@admin = 1)" >
      <fields>
        <field name="group_id" fieldType="PK" dataType="N" align="Right" width="40" filterType="Code" hidden="true">
          <text v="ID" e="ID"></text>
        </field>
        <field name="groupname" width="100" filterType="Code">
          <text v="Nhóm" e="Group"></text>
        </field>
        <field name="dien_giai" width="300" filterType="Code">
          <text v="Tên nhóm" e="Description"></text>
        </field>
        <field name="ds_username" width="300">
          <text v="Danh sách người sử dụng" e="Fullname"></text>
        </field>
      </fields>

      <buttons>
        <button id="add">
          <text v="Thêm (Alt + N)" e="Add (Alt + N)"></text>
        </button>
        <button id="edit">
          <text v="Sửa (Ctrl + E, Alt + E)" e="Edit (Ctrl + E, Alt + E)"></text>
        </button>
        <button id="delete">
          <text v="Xóa (Ctrl + D, Alt + D)" e="Delete (Ctrl + D, Alt + D)"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="permission">
          <text v="Phân quyền" e="Permission"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="refresh">
          <text v="Làm tươi" e="Refresh"></text>
        </button>
        <button id="freeze">
          <text v="Gim cột" e="Freeze"></text>
        </button>
      </buttons>

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>x/NwP6JAQpV00/wbfVRlEcBIPMRHhiRKoqbMpXeP/TMI4w2LH/KkwDH6ZiXz6v5Kg4TK+9JUEps5DuwObcbuVypNkYoh0SaTlAUzKs3JG3B6KH8LHPeI2HfQMjVQe3zxBMhu+p2ADvEGnqLFS1piKR+d+RJlNyuT5OfAxdmzLmk9Y8Hx/Ypit/ZUKgEOXxIMwfc4S+0CRm1e0vj3d8ubq7uJi4ga+qet1a6OpTGAdSrzguvHcVxnpuAdqtZm9+RPfxDFZ+UKckYk3sAkeaKnLQqQH5GxShXUdO+lDeutHIY9JIw997Wz1DbK1ttB533eqebBancuQGjaAxSo6cK/LkHQAI6C1QNYNEmcNXetdrtxqM/D/xCZ0J6meLBp4XUk0IxU4yGMZ4o0GqTskWTEUha099RCBd/Xc5aZBdAizqdenBxvD1gXBJekxKdG3IOVDHu9ASMnmv+PHB1fsCJDaBSE2qbuzh3+n13cyPZTbxkUD9FPsgmhoy/UxD/w50dUMraSe/LFKLrHkNWlwSQeJw==</enc>]]>
    </text>
  </js>


  <script>
    <request code="permission">
      <text>
        <![CDATA[<enc>If6NIX2MA6MzBXfNsCx/Tt/0P4xRlNjQC6guzFZvFoHFJqu38Jv5HwdvK+jW8/qw2PpkepF2So/0qqAmqjDYY3tI42j1U6vO0jrxs/blHO3Hrwqez3S83HNPpQiNw7Lq1DpYFSxq6YJ+7auzDbtRYg==</enc>]]>
      </text>
    </request>
  </script>

</dir>