<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="sysrightunit" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Phân quyền truy cập theo đơn vị" e="Access Right by Unit"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>
  <grids>
    <grid table="vsysrightunit" fieldKey="user_id" order="username" allowFilter="true" allowOrder="true" >
      <fields>
        <field name="user_id" fieldType="PK" width="50" hidden="true" filterType="Code">
          <text v="User ID" e="User ID"></text>
        </field>
        <field name="username" width="100">
          <text v="Mã/Nhóm" e="Code/Group"></text>
        </field>
        <field name="nickname" width="250">
          <text v="Tên/Nhóm" e="Name/Group"></text>
        </field>
        <field name="is_user" dataType="B" width="100">
          <text v="Người sử dụng" e="User"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>
</dir>