<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGrid.xml">
]>

<dir id="sysrightstatus" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Giới hạn quyền truy nhập cho các trạng thái của chứng từ" e="Limit Access Right to Voucher Statuses"></title>
  <subtitle v="Thêm, sửa, xóa..." e="New, Edit, Delete..."></subtitle>
  <grids>
    <grid table="vsysrightstatus" fieldKey="ma_ct,user_id" order="ma_ct, username" allowFilter="true" allowOrder="true" >
      <fields>
        <field name="ma_ct" fieldType="PK" width="120" filterType="Code">
          <text v="Mã chứng từ" e="Voucher Code"></text>
        </field>
        <field name="ten_ct" width="250">
          <text v="Tên chứng từ" e="Voucher Name"></text>
        </field>
        <field name="user_id" fieldType="PK" width="50" hidden="true" filterType="Code">
          <text v="User ID" e="User ID"></text>
        </field>
        <field name="username" width="100">
          <text v="Mã" e="Code"></text>
        </field>
        <field name="nickname" width="250">
          <text v="Tên" e="Name"></text>
        </field>
        <field name="is_user" dataType="B" width="100">
          <text v="Người sử dụng" e="User"></text>
        </field>
      </fields>

      &DefaultButton;

    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>1ClLBcOnSxdaIpVCOeBdz+Ks1W7g4qq/5AWcy4wYQjNZ+GqLNcJbSrVO1xvlID1d8V5I6MKFxhe8QUZ25gr+ZSktFnGKKualSbRHbtsw6AJ7w/tl+2KwkkOod5GZ1VHiBhXM7UTXyClLNbrK2YiHijt6yTVHecGaxeMxzrRKpNYSfrcjF1PB96jSC4RdGYVVf0wE60cxZJ5pFkTMiUR8CQ==</enc>]]>
    </text>
  </js>
</dir>