<?xml version="1.0" encoding="utf-8"?>

<dir id="sysuserinfo" dirViewType="Grid" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Khai báo người sử dụng cho nhân viên" e="User Maintenance"></title>
  <subtitle v="Thêm, sửa, phân quyền người sử dụng..." e="New, edit user..."></subtitle>
  <grids>
    <grid id="0" table="sysuserinfo" fieldKey="user_id" order="user_id" allowFilter="true" allowOrder="true" key="(@@admin = 1 or user_id = @@userId)" >
      <fields>
        <field name="user_id" fieldType="PK" dataType="N" align="Right" width="40" filterType="Code" aliasName="a">
          <text v="ID" e="ID"></text>
        </field>
        <field name="username" width="120" filterType="Code" aliasName="a">
          <text v="Tên" e="Name"></text>
        </field>
        <field name="nickname" width="300" aliasName="a">
          <text v="Tên đầy đủ" e="Fullname"></text>
        </field>
        <field name="parent_user" hidden="true" dataType="N" align="Right" width="40" filterType="Code">
          <text v="ID" e="ID"></text>
        </field>
        <field name="parent_username" width="120" aliasName="b.username as " fieldType="EX">
          <text v="Cấp trên" e="Cấp trên"></text>
        </field>
      </fields>

      <buttons>
        <button id="add">
          <text v="Thêm (Alt + N)" e="Add (Alt + N)"></text>
        </button>
        <button id="edit">
          <text v="Sửa (Ctrl + E, Alt + E)" e="Edit (Ctrl + E, Alt + E)"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="permission">
          <text v="Phân quyền" e="Permission"></text>
        </button>
        <button id="split">
          <text v="-" e="-"></text>
        </button>
        <button id="refresh">
          <text v="Làm tươi" e="Refresh"></text>
        </button>
        <button id="freeze">
          <text v="Gim cột" e="Freeze"></text>
        </button>
      </buttons>

      <script>
        <query>
          <text>
            <![CDATA[<enc>eI96QaPxPP1l1mvIPRfWiyp2bxpVTvFcD6ZV1+RckcEJmkHRyhhKxwgUf4cT6+AzzGUxypGo6EImbcos5hinIUvlxLNg6yLalZSB8X5Bt9fC4R5ckoNz1v4J+deHZfMQyN29QhRW3pjU7jrqpC1/1xByq824nDxVxQNSZ68pWrPdO7WOOfunmUFZD5SSN3ykNZ+e8rM5RV6ibl6QGVY1K8nlJRpa+dzzYZ/t1DUsauvra3Czx2PBUgeadMD5A/bjVw9JX1XKbfHxiijKacFKRYS8Jj/aym5zK+2V6m99Dzh2g7LbZ/Hswhs5grRpWO+kz0fHTaSrLtrBMcDWQ8pcy8xyUukQ01GeTbdGs05/K5H2O5R2g6ZFSucp4RQcuvoA3L2EWCnlDCriqRbnqqbVij8XJAgmPae+1IwNkX0wpm/1TDGta+uEsoCTxjCXp03x</enc>]]>
          </text>
        </query>
      </script>


    </grid>
  </grids>

  <js>
    <text>
      <![CDATA[<enc>hMsf5tdLzQJzak5MDyrxu+pSGscyXb5bb4WWoP2PZgZNK7lfH9mvPYWQ6oMfno0c20jXBlqc9+lwgBJi4AaRuzSI7K1lgexeu1rzEcpse/eo2qA5MwnpkUqgAUPadhYHXczRzT6Zaj3JNKitruG3tnrmsGEBwjs59qtD7DQoq/REnOi8QN0tTBy4SXFveD4f7GZSYzlP479N0h1WEMDAxkAppUvxx9ItkjX9eznD/wFdpdyNg0CI77YkzDNsUKOTZm+xNi5ifPXHuBrRRdZ+eQA541U462/vZzI9IFLJe/iK5IiaMLlZSaXS5Oe3pPxsbCTs8MEdSpDZgKPr85fuMGIGm501qQrNcKWDMu/5LjIiEgvUpTs6uYFtvzAvu4KPMdniEGpTESoMH/lrsTgFWK1aFC2ycOs8UZ0N2MYdZzjxSPQx4V4N5ecBYOOhddW6CFe16WquHYeXrv+CIIScxKFr6Xb5vIOMe1/2nLQdSlVMJrBFVTG5JhXJKmUF6mD1g6mtcccGGoDIJ5M9UFODDg==</enc>]]>
    </text>
  </js>
  <css>
    <text>
		<![CDATA[<enc>dfnT9ALQc8bNNRNNODv6ipjUJRxnE8SldWYBvvnvIxV6y0vDHgi++5gz+s8mtlEbxaQXTGjnRYjcOj2QtZUN2xc4zvaSd0JHmoIjW6x93fxALKNbvAdGbOEjwgGf4u6aBxO4XevTifLUDA01c1Y+/rO/P75GAPp+DW9PbgK85c2xyqJqBz3NI7aREzcCgDNIn+pb3Zy5cr1ptWzwD19z4Nm3pLK4N0gOyJxgDIThGPjrhD0fEy/CP/eQGnjn00+7yxrv2CXZnkLYgk1Wq1ckP3Nn6XQdvI8J3GGVQP7qbW+Fn3fGxn6XePqqF91qnR0E</enc>]]>
    </text>
  </css>


  <script>
    <request code="permission">
      <text>
        <![CDATA[<enc>+lXR2x4Em5J5jj2phV5zn/bEu3zFlLoMXrl6o1TVUSoBDnVlL12W1KghipigxADBKGt+IMa2qLXz5pfocyUqAwwUKJoy9nNkSyn0Vl0x3dnR4AwFbMyw8cRqIg11+uvxYuAg+xj0TZgbgjJtPGga6Rd7aLWctYM39EunqMBlPzZIhNJFbm07+Dz46edaG+kbTkMubO/qN8gqcNAG++V5Q12+W32RwGF1+3BeiVgmgU4=</enc>]]>
      </text>
    </request>
  </script>

</dir>