<?xml version="1.0" encoding="utf-8"?>

<dir id="dmdv" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục dịch vụ" e="Service List"></title>
  <grids>
    <grid table="dmdv" fieldKey="ma_dv" fieldName="ten_dv" order="ma_dv" allowFilter="true" allowOrder="true" key="" >
      <fields>
        <field name="ma_dv" fieldType="PK" width="100" filterType="Code" >
          <text v="Mã dịch vụ" e="Service Code"></text>
        </field>
        <field name="ten_dv" width="250">
          <text v="Tên dịch vụ" e="Service Name"></text>
        </field>
      </fields>
    </grid>
  </grids>
</dir>