<?xml version="1.0" encoding="utf-8"?>

<dir id="dmkh" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục khách hàng kế toán" e="List of customer"></title>
  <grids>
    <grid table="dmkh" fieldKey="ma_kh_kt" fieldName="ten_kh" order="ma_kh_kt" allowFilter="true" allowOrder="true" key="ma_kh_kt &lt;&gt; ''''" >
      <fields>
        <field name="ma_kh_kt" fieldType="PK" width="100" filterType="Code" >
          <text v="Mã khách hàng" e="Code"></text>
        </field>
        <field name="ten_kh" width="250">
          <text v="Tên khách hàng" e="Name"></text>
        </field>
        <field name="rg_code" width="100">
          <text v="Mã khu vực" e="Region"></text>
        </field>
      </fields>
    </grid>
  </grids>
</dir>