<?xml version="1.0" encoding="utf-8"?>

<dir id="dmkho" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục kho hàng" e="Warehouse/Site List"></title>
  <grids>
    <grid table="dmkho" fieldKey="ma_kho" fieldName="ten_kho" order="ma_kho" allowFilter="true" allowOrder="true" key="unit_id in (select unit_id from dbo.ISWIFTFunctionGetUnitIDRight(@@userId, @@admin, ''''))" >
      <fields>
        <field name="ma_kho" fieldType="PK" width="100" filterType="Code" >
          <text v="Mã kho" e="Site"></text>
        </field>
        <field name="ten_kho" width="250">
          <text v="Tên kho" e="Description"></text>
        </field>
      </fields>
    </grid>
  </grids>
</dir>