<?xml version="1.0" encoding="utf-8"?>

<dir id="dmkien" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục Kiện" e="List of packages"></title>
  <grids>
    <grid table="dmkien" fieldKey="ma_kien" fieldName="ten_kienkien" order="ma_kien" allowFilter="true" allowOrder="true" key="" >
      <fields>
        <field name="ma_kien" fieldType="PK" width="100" filterType="Code" >
          <text v="Mã kiện" e="Package Code"></text>
        </field>
        <field name="ten_kien" width="250">
          <text v="Tên kiện" e="Package Name"></text>
        </field>
      </fields>
    </grid>
  </grids>
</dir>