<?xml version="1.0" encoding="utf-8"?>

<dir id="dmloaitau" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục loại tàu" e="Port Type"></title>
  <grids>
    <grid table="dmloaitau" fieldKey="ma_loai" fieldName="ten_loai" order="ma_loai" allowFilter="true" allowOrder="true" key="" >
      <fields join="">
        <field name="ma_loai" fieldType="PK" width="100" filterType="Code" >
          <text v="Mã loại" e="Type Code"></text>
        </field>
        <field name="ten_loai" width="250">
          <text v="Tên loại" e="Type Name"></text>
        </field>
      </fields>
    </grid>
  </grids>
</dir>