<?xml version="1.0" encoding="utf-8"?>

<dir id="dmlo" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục lô" e="Lot Maintenance"></title>
  <grids>
    <grid table="dmlo" fieldKey="ma_lo" fieldName="ten_lo" order="ma_lo" allowFilter="true" allowOrder="true" key="" >
      <fields>
        <field name="ma_lo" fieldType="PK" width="100" filterType="Code" >
          <text v="Mã lô" e="Lot"></text>
        </field>
        <field name="ten_lo" width="300">
          <text v="Tên lô" e="Description"></text>
        </field>
        <field name="ma_vt" width="100">
          <text v="Mã vật tư" e="Item"></text>
        </field>
        <field name="sl_ton" dataType="N" format="Qty" aliasName="cast (0 as numeric(19,5)) as " width="100">
          <text v="Tồn" e="Stock"></text>
        </field>
      </fields>

      <script>
        <query>
          <text>
            <![CDATA[<enc>gXllMH9fy8MiEZOYRf2seuXcILiHLqLIbokmbksVotq6ssyIZEEraua/ezKYUZ654NBFeaDXj87blJpRttUWJ3exRksuI9mmCExl/uOEkI5AVPC5HMsVvQQccs7wftwj3NWhOpZcWpnJkKzf5qlMB50Zv10Z2plBnuqSxkYRU89Nh0Xjmof7JrzLXpBdl7uweIvW8qgWp6hn2dCfqbvKI5cqoKVo+jMEIfHhPQgLpskeYlMOGnKAQ2P9EJ6iWmItBzrSD4pAWrzFvqaGf3omm6LhO/AqOKkqnld4guH/BrF4Er6uzAKXcLdrlIt0d/Y/EcvjfbtAvJgluYgEdpBMDq+3W5E0XMZWYoRIH21qyKmoUA6hIL67XZhUs6T3kiwZ5NX099xv13JTi615XA/oZw==</enc>]]>
          </text>
        </query>
      </script>
    
    </grid>
  </grids>
</dir>