<?xml version="1.0" encoding="utf-8"?>

<dir id="dmpttt" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục phương thức thanh toán" e="Department List"></title>
  <grids>
    <grid table="dmpttt" fieldKey="ma_pttt" fieldName="ten_pttt" order="ma_pttt" allowFilter="true" allowOrder="true" key="" >
      <fields>
        <field name="ma_pttt" fieldType="PK" width="100" filterType="Code" >
          <text v="Mã phương thức" e="Department Code"></text>
        </field>
        <field name="ten_pttt" width="250">
          <text v="Tên phương thức" e="Department Name"></text>
        </field>
      </fields>
    </grid>
  </grids>
</dir>