<?xml version="1.0" encoding="utf-8"?>

<dir id="sysunit" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục đơn vị" e="List of Units"></title>
  <grids>
    <grid table="sysunit" fieldKey="ma_unit" fieldName="ten_unit" order="ma_unit" allowFilter="true" allowOrder="true" key="" >
      <fields>
        <field name="ma_unit" fieldType="PK" width="100" >
          <text v="Mã đơn vị" e="Code"></text>
        </field>
        <field name="ten_unit" width="300">
          <text v="Tên đơn vị" e="Name"></text>
        </field>
        <field name="unit_id" width="80"  >
          <text v="ID" e="ID"></text>
        </field>
      </fields>
    </grid>
  </grids>
</dir>