<?xml version="1.0" encoding="utf-8"?>

<dir id="dmdvvt" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục đơn vị" e="Trans/Site List"></title>
  <grids>
    <grid table="dmdvvt" fieldKey="ma_dvvt" fieldName="ten_dvvt" order="ma_dvvt" allowFilter="true" allowOrder="true" key="unit_id in (select unit_id from dbo.ISWIFTFunctionGetUnitIDRight(@@userId, @@admin, ''''))" >
      <fields>
        <field name="ma_dvvt" fieldType="PK" width="100" filterType="Code" >
          <text v="Mã đơn vị" e="Site"></text>
        </field>
        <field name="ten_dvvt" width="250">
          <text v="Tên đơn vị" e="Description"></text>
        </field>
      </fields>
    </grid>
  </grids>
</dir>