<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
]>

<dir id="m51" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Báo giá" e="Quotation Entry"></title>

  <grids>
    <grid table="m51" fieldKey="id" fieldName="so_ct" order="id" allowFilter="true" allowOrder="true">
      <fields>
        <field name="id" dataType="N" fieldType="PK" width="100" format="0" hidden="true">
          <text v="ID" e="ID"></text>
        </field>
        <field name="so_ct" width="100" fieldType="RF" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="100" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
        <field name="ma_kh" width="120" >
          <text v="Mã khách hàng" e="Customer Code"></text>
        </field>
        <field name="ten_kh" width="250" fieldType="EX" >
          <text v="Tên khách hàng" e="Customer Name"></text>
        </field>
        <field name="ma_nt" width="80" >
          <text v="Ngoại tệ" e="FC"></text>
        </field>
        <field name="t_tt_nt" dataType="N" format="FCAmount" width="100">
          <text v="Tổng tiền" e="Pcs UOM"></text>
        </field>
      </fields>
      <script>
        <query>
          <text>
            <![CDATA[<enc>o98Q/ebLZEAf52fn7MObKvpT2fQIz0/ED2OX8g3lK9zlW60jgk6P+QwMWsRw45K7wAmNiEoAt5OMNxqn+12FIZDR9kga+/lm3YVM7jBT+zxK7runrRjcQatIHylOu+eICi+89AIXHrc1dh2iuPrIecP2hucdWS23Cp6sxg2soUT+nZHP9e+RdHW/leRaBXGpFdbq+JdK0PrIJ07KFYXKrIUwjoC4Gz+/h8Za4kl7/qb0qzSIfzrm8R/ZSdh/wx283MNW2vXKGFJc/wdJEvV5nLkAnpuATClLcqVZbqabV7nt6SNXJBYQHyYEYr6i8yCziGOrnmlCtyr6wyth6dOydvffNVh6sSJS8ryucbWcJYZGRnk0nDCG965bzoDpxQohylanSuJrYJIboPymD6ZarA==</enc>]]>
          </text>
        </query>
      </script>

    </grid>
  </grids>
</dir>