<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonGridVoucher.xml">
]>

<dir id="m71" dirViewType="Lookup" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Phiếu yêu cầu xuất kho" e="Material Requisition"></title>

  <grids>
    <grid table="m71" fieldKey="id" fieldName="so_ct" order="id" allowFilter="true" allowOrder="true">
      <fields>
        <field name="id" dataType="N" fieldType="PK" width="100" format="0" hidden="true">
          <text v="ID" e="ID"></text>
        </field>
        <field name="so_ct" width="100" fieldType="RF" >
          <text v="Số c/từ" e="Voucher Number"></text>
        </field>
        <field name="ngay_ct" width="100" dataType="D">
          <text v="Ngày c/từ" e="Voucher Date"></text>
        </field>
        <field name="ma_bp" width="120" >
          <text v="Mã bộ phận" e="Department Code"></text>
        </field>
        <field name="ten_bp" width="250" fieldType="EX" >
          <text v="Tên bộ phận" e="Department Name"></text>
        </field>
        <field name="t_so_luong" dataType="N" format="Qty" width="100">
          <text v="Tổng số lượng" e="Total Quatity"></text>
        </field>
      </fields>
      <script>
        <query>
          <text>
            <![CDATA[<enc>o98Q/ebLZEAf52fn7MObKm6AfpSXss2GyeWd1HVyyK6AzcBSpiUo1UcMiHVunjFj6fKx1Zssb7T4Ssy+74CxkXakKiZt81OTTrtmeW1dyLkiprc6ni9fNjIcZRVZjMGhdfK9U1ZJh6tSirny9vIrqvTDEIEenxTzHGMTPAH/ChZfc+VVTpZz6/Nyz1Er5IpXOZ0sPRVlfO0Vg6UWnsWLNl9xJBie9K0QcAxcra7WMih6iQjO4NRRt9uLrjJPGmsCxbR5FT0h5/OKKqsAM0d7KuLnsC6E3oYyo70uINA9pA638fQhpnWZcE/VTrxrdDLQZ3KcTpOtIg8nV/+aDVVNNAIQrYlMP1WVwaYY9vUfQSTuiFHbEiSXX6tphVPnGzq7l+Zj1xrr1vMv5Gc9vUhruQ==</enc>]]>
          </text>
        </query>
      </script>

    </grid>
  </grids>
</dir>