<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="cdkh" table="" height="" fieldKey="nam" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Vào đầu kỳ công nợ khách hàng" e="Customer Opening Balance"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,240,120"  >
      <fields>
        <field name="nam" label="1" field="1" format="-1" maxLength="4" allowBlank="false" dataType="I" aliasName="@DFYear">
          <text v="Năm" e="Year"></text>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>8wsLme4If9rNawhEvon3/QVwfjdEwm+/bFrzUcaSHdv6zmU20/n1D56gkt/ZkIUF998knv/6GFjwJPKWZnysYnC08nZOTTmcCcZXI/VeoXGsK9qNDWhEUTh6gfQtfJKw57BDEaVW9vQ8xMilTwzpQyY0FFklaq10kHjY5hqzT2UuKJ080i2KbBMF5/OtEf1I</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>