<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="m55DH1" fieldKey="id" voucherCode="HD1" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc đơn hàng" e="Sales Orders Filter"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" allowBlank="false" dataType="D">
          <text v="Ngày c/từ từ/đến" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" allowBlank="false" inactivate="true" dataType="D" nextRow="false">
          <text v="Ngày đến" e="Voucher Date"></text>
        </field>
        <field name="ma_nt" hidden="true" label="1" field="1">
          <text v="Mã ngoại tệ" e="Ex Code"></text>
        </field>
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="ma_kh" viewType="Lookup" disabled="true" inactivate="true" label="1" field="1">
          <text v="Mã khách hàng" e=""></text>
          <viewInfo lookupType="One" lookupId="dmkh" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_kh" />
        </field>
        <field name="ten_kh" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
        <field name="so_ct" label="1" field="1" allowBlank="false" viewType="Lookup">
          <text v="Số đơn hàng" e="SO No"></text>
          <viewInfo lookupType="Multi" lookupId="m52" lookupRef="ds_so_ct" lookupKey="ngay_ct between ![ngay_ct1]! and ![ngay_ct2]! and ma_ngv = 5 and ma_kh = ![ma_kh]! and unit_id = ![unit_id]! and status in (5,6) and ma_nt = ![ma_nt]!" />
        </field>
        <field name="ds_so_ct" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>4rbgQPq2PC/Jy8+m3mXt/9TsBSiMq75zomNxLBQkQwGHSQN1TtgUfn1jgiIUqAz470zXYx0UebdUdrZTvAdtOp4iL424GFuAasZmbUfdCN0HfE/XsbX6jGaXxG5EfbuhReZAJpUvwBI/mXp38En6jVIAMMT67FUs1o52dbGVXOE8Zg1vjrX6CMU2npNP+wIaA+gtSOCa2MBEDUn7sJPfLARf4/B/YwoTjOUpsfpWYdL8/kWhH9/KVIqHF5hAB3D6z73mUTehmnCLrsPSicZ3eYEzU8+kuVtaFM9ktARJueFCBuLnz8AdrYlRL/B8VpKjF6CTTtHjKeefulShP85dW2Y3y/k4TKJ6HZzoXvWkZaUHm5YQTO2KV+/NtTvESaSFcaoq3msLNLozbiN9xRoER+pf59dYAgOPxRux6GnapV2+HBTd69CInKOzsUByJyLkV4LG81wtDbj2M9PKqlB1mG+bR7XNetlxlM5KrVVhwKpQ/7zCRPBtfAsw6O6oqQXz4N+xfqKcgUEi3UAP03mJsg==</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>