<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="m56PX3" fieldKey="id" voucherCode="HD1" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc phiếu xuất" e="Pick List Filter"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" allowBlank="false" dataType="D">
          <text v="Ngày c/từ từ/đến" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" allowBlank="false" inactivate="true" dataType="D" nextRow="false">
          <text v="Ngày đến" e="Voucher Date"></text>
        </field>
        <field name="ma_nt" hidden="true" label="1" field="1">
          <text v="Mã ngoại tệ" e="Ex Code"></text>
        </field>
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="ma_kh" viewType="Lookup" disabled="true" inactivate="true" label="1" field="1">
          <text v="Mã khách hàng" e=""></text>
          <viewInfo lookupType="One" lookupId="dmkh" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_kh" />
        </field>
        <field name="ten_kh" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
        <field name="so_ct" label="1" field="1" allowBlank="false" viewType="Lookup">
          <text v="Số phiếu xuất" e="PL No"></text>
          <viewInfo lookupType="Multi" lookupId="m54" lookupRef="ds_so_ct" lookupKey="ngay_ct between ![ngay_ct1]! and ![ngay_ct2]! and ma_kh = ![ma_kh]! and unit_id = ![unit_id]! and status in (5,6) and ma_nt = ![ma_nt]!" />
        </field>
        <field name="ds_so_ct" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>KnJ66uF0s8Sz+E1B2mMw0qeEb6Kymlpy3UItLSuck7NaaNywPsqFZi3DOoWV9cJ4Ab0gZUSUv42+7S9ySFqyLhG9NLHYXoWHsACgINn7YCkoHrgWIpkiCmEKmirMTYGY78n+dJvkh43J4XjMOHR0NHbLwMToLXrAQbrAWHnFzDAhymzG/s0PwR8VmQDgYXTtlG+5N0HK8apwpdqHsVaysaodGJS7rD9NzCynyc4UxFAhsTnxVdTkrAsZfnLb3fZZeWWpr8aEl5MKOTlG/5rMcaRIZ60RnHuo8Z9sK9/ayIXN5hYNz/QL/XmjxbYrqIwrtjKv9eSjfb8+W7lq8keCiDTiAoqutVP/42qOGnE/Ix9pPDXa2j0CbENPCfZ98J5qn2v42RdKe4pOdRRQJnsFciBUx9D67ufXUgCyEZtnfAxw4pNzB9zaLbYwR0V3mmx/LKfvO5WJS9Pl2udccTXszMR/8H7B4wgT7hWbiCgR0zkAsY31HnFxc7i+Pa6Xf+VbYHmtzp1dH9YPON/x6Fx0pQ==</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>