<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="m57PX1" table="" height="" fieldKey="id" voucherCode="PX1" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc phiếu xuất" e="Issue Filter"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" allowBlank="false" dataType="D">
          <text v="Ngày c/từ từ/đến" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" allowBlank="false" inactivate="true" dataType="D" nextRow="false">
          <text v="Ngày đến" e="Voucher Date"></text>
        </field>
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="ma_kh" viewType="Lookup" disabled="true" inactivate="true" label="1" field="1">
          <text v="Mã khách hàng" e="Customer"></text>
          <viewInfo lookupType="One" lookupId="dmkh" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_kh" />
        </field>
        <field name="ten_kh" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
        <field name="so_ct" label="1" field="1" allowBlank="false" viewType="Lookup">
          <text v="Số phiếu xuất" e="Voucher Number"></text>
          <viewInfo lookupType="Multi" lookupId="m73" lookupRef="ds_so_ct" lookupKey="ngay_ct between ![ngay_ct1]! and ![ngay_ct2]! and ma_kh = ![ma_kh]! and unit_id = ![unit_id]! and status in (5,6)" />
        </field>
        <field name="ds_so_ct" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>37YA8pIV31z1GB2JMvgyiENaDzwGah5YZM6wg9jZYbxY825ysG5Zvb4SS9r0LXkFa2luEpCx0KKaCQSmkvqQ2f7KCtafBIp21D7gZeAt1r8hGUg3RR5M6YoswLL4cbPcxnjydDLfyBjZcfWqpEE31GLPTV57jLm9aX0Mj3JZPnD0Y0odGE2k3l+V4Vx+YdCBscgXx1lQPIPx3q/gTqzwaGv1AtymnPM4bboskahQYCCnLSD3IeHnqQGg07imDa/1XoL42SpHfCvJ5vhKxLUZfW8PEFqxJQK+MdAzeEmknSp0kpm8CjpMwOLPGhhXq+8hbHnAhi2hdga3nP/LtymMwKs92HTUS6nNsw/zbMTmp9Gakhigb0GAV/UH5vTHS2GtvjtBrI36kBNpHP6LlnwcnLbs8qv3tbvqeVlQHZtO6tmGiHZukPbCZon8HJd25HQO+Thv1nD23QFvdyiTu5kzHz6/EnU2eMz3G6mxj83Z/FjQtCn1Z0d22a0Ew93GXTWZ</enc>]]>
    </text>
  </js>
</dir>