<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="m72PN1" table="" height="" fieldKey="id" voucherCode="PN1" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc phiếu nhập thực tế" e="Physical Issue"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" allowBlank="false" dataType="D">
          <text v="Ngày c/từ từ/đến" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" allowBlank="false" inactivate="true" dataType="D" nextRow="false">
          <text v="Ngày đến" e="Voucher Date"></text>
        </field>
          <field name="ma_nt" hidden="true" label="1" field="1">
          <text v="Mã ngoại tệ" e="Ex Code"></text>
        </field>
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="ma_kh" viewType="Lookup" disabled="true" inactivate="true" label="1" field="1">
          <text v="Mã khách hàng" e=""></text>
          <viewInfo lookupType="One" lookupId="dmkh" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_kh" />
        </field>
        <field name="ten_kh" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
        <field name="so_ct" label="1" field="1" allowBlank="false" viewType="Lookup">
          <text v="Số phiếu thực tế" e="Voucher Number"></text>
          <viewInfo lookupType="Multi" lookupId="m72" lookupRef="ds_so_ct" lookupKey="ngay_ct between ![ngay_ct1]! and ![ngay_ct2]! and ma_kh = ![ma_kh]! and unit_id = ![unit_id]! and status in (5,6) and ma_ngv = 2 and ma_nt = ![ma_nt]!" lookupCheck="ma_kh = ![ma_kh]! and status in (5,6) and ma_ngv = 2 and ma_nt = ![ma_nt]!" />
        </field>
        <field name="ds_so_ct" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>f0JAwjA4kf8Riu3axZPnUFKqpKNioYlRhOSCdb9ZmSmXjMx6E0G7YZU8NRldS7A4J747DZRTlVULJSd/f1LySZorXm5gZDnnSRlWRQgwMG0ryOBOzCk1DLKxtyfSDpaKGPnRHeT5mtqrzDMSJCM+gZhgyAai7v46BjbeLYtQjKBEp41BSTdBabrrytJRzR3l4CniBgk0HHqUgUFBa+4WskybYmK1NFTAHEqSrrMya4z24MKlDDfq+G7JPxtobPT9WCg4mZK1/VbFvZEPD2MxhzaDsaIH8GpwFNXvMrrnf3faJ2Ao00eHydN4t70gXAWqaYQXFRMJ5Wudi9FOYNXF4Oekq7v/+zg6IsxxaPkuW48H9VD8BY2PGTa4wjC4vaMbBfWGr3emhP+/QAag2kEf9cpMGUPuHmpfSMmfK5HqXd9eHv8/NzcFeA56EZVOb+qBhQbUJVe1/So/t4b09iqxmqJaNv4I6JvU8oEP/quZFdr40JWIyHIcg/CGxp1ieXz5POMpV52WF12Sbx84qgOOEQ==</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>