<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>

<dir id="dmbbct" table="dmbbct" fieldKey="ma_bbct" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục biên bản chứng từ" e="List of voucher report"></title>
  <title0 v="Mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
        <field name="ma_bbct" format="U" label="1" field="1" allowBlank="false" fieldType="PK" >
          <text v="Mã biên bản" e="Report code"></text>
        </field>
        <field name="ten_bbct" label="1" field="-" allowBlank="false">
          <text v="Tên biên bản" e="Report name"></text>
        </field>
        <field name="ten_bbct2" label="1" field="-">
          <text v="Tên khác" e="Other name"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>1PFOGp66gVgaSTPirrPUVVA7Sdo+G9ARYEjiUMo7mm4fi/r/q5n1hpYLl7CiD7DAGAUj+OdfMEs2HPDFZ0kfsXD1Tyw94qZrvh1VbfdmMF2pBcPfrTwNHpR5il2NT7h6VxQDRWYJbxQFWwFBZ/9uZENJjhx7fM2F9D5lN0M9vhcQtgG9PtFIeK3kUeMbSbaFGO2SozJ/FIDh8XZGfz1ifqg3OlKtEXXhuS+etv2rxlp8e/ZXF6vIV3Sdg0bf5psQBlaUxWvOHEu5fwmlTxwYEVxXNl2XFwQv4sMH9AdywNWpK1x3lP6C6KfcwXGuLCuY8UqjW5ZbcRFOusOBraVEgg==</enc>]]>
    </text>
  </js>
<css>
		<text>
		  <![CDATA[<enc>YkWQBTDGylCtyJwcHZMp4ku6Dq2oUNnvDbOHUD7o0MO4cQvZSR01/Iw1BU5fULM8h+F5QEt2lCYxsBSPaw6SJ6pSbm4TFFVR/dJvYfSUmQmnbTzCmkpvE2EQjuu+u+L+B/NmPQBSODXy3C0fZ6/mmA==</enc>]]>
		</text>
  </css>
  <script>
    <declare>
      <text>
        <![CDATA[<enc>RV+/GFjVDafki9YwPH6kr+fyb0HmhcXg1il3aaBkvDHj7R0soY4uZUwjRuDR3HkSdXKN2zfYy22g6X4MV4rH5VIs7N5Xs+VWmsfz4PZQ1sH9nWdx9KHygRQDtXlMmil9eEE2uoCQuy0hYCll5TLdt5iZCagIyxnPmPnupxTMkLgThmDV740J0FG4CjOzWpfeRrJ35WzNJ+hWLR0NgGeFrkATIzAE5kBPW5cJBNGPP6ksqSgU+ZJWiXD43wZD9Y0K8CXHoLD6rXzxB0Pm9rjLeQ==</enc>]]>
      </text>
    </declare>
  </script>

</dir>