<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmbcc" table="dmbcc" fieldKey="id" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục bảng chấm công" e="List of timesheets"></title>
  <title0 v="Thêm mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="80,120,120,120,120,120" >
      <fields>


		<field name="ma_nv" format="U" label="[120]" field="1" allowBlank="false"  viewType="Lookup">
			<text v="Mã nhân viên" e="Staff code"></text>
			<viewInfo lookupType="One" lookupId="dmnv" lookupKey="status = 1" lookupCheck="1=1" lookupRef="ten_nv2" lookupInfo="dmnv|ma_nv|ten_nv2" />
        </field>
        <field name="ten_nv2" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="2" aliasName="cast('' as nvarchar(4000)) as ">
			<text v="" e=""></text>
        </field>
		<field name="dt_mobil" label="[120]" field="[200]" allowBlank="false" fieldType="PK" >
          <text v="Điện thoại " e="Mobile phone"></text>
        </field>
		<field name="tt" nextRow="true" fieldType="EX" readOnly="true" inactivate="true" label="[350]" field="[50]">
			<text v="Chấm công ca làm việc" e="Shift time"></text>
		</field>
		
        <field name="ngay_ct" label="[120]" field="1" valueDefault="new Date()" copy="false" allowBlank="false" dataType="D">
			<text v="Ngày chấm công" e="Timekeeping date"></text>
		</field>

		
		
		<field name="ngay_cong" viewType="Combobox" inactivate="true" label="[120]" field="[180]" >
          <text v="Ngày công" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="Đủ ngày công" e="Enough working days"></text>
              </option>
              <option val="0.5">
                <text v="Nữa ngày công" e="Half working day"></text>
              </option>
			  <option val="0">
                <text v="Không làm việc" e="Not working"></text>
              </option>
			  <option val="0">
                <text v="Nghỉ thai sản" e="Not working"></text>
              </option>
            </options>
          </viewInfo>
        </field>		 
		
		<field name="ghi_chu" label="[120]" field="-" allowBlank="false">
          <text v="Diễn giải" e="Name"></text>
        </field>
      </fields>
    </form>
	
	<form gravity="TopRight" columns="120,120" >
      <fields>
		<field name="unit_id" viewType="Combobox" dataType="I" clientDefault="true" inactivate="true" label="[60]" field="[180]" nextRow="false" >
			<text v="Đơn vị" e="Unit"></text>
			<viewInfo>
				<options cache="false" query="select unit_id, ten_unit%l from sysunit where unit_id in (select unit_id from dbo.ISWIFTFunctionGetUnitIDRight(@@userId, @@admin, ''))">
				</options>
			</viewInfo>
		</field>
		
		
		<field name="status" viewType="Combobox" inactivate="true" label="[60]" field="[180]" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>		 
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>OIvoYpbA2cjnWLO6Y4m5qNmgN4Z8sOgdPZYwP7shMcg4wrCd7cYhJnL4lLzhWYEkMt4dzs4QolynDc/hv662sYSgh08kkenSAt67peNSnzsrF3OAuJ2AtN5btTyvyDorjTShv0kCRMTx3lqOrmtBJ5Ro+IE9xMJAERRcL478M1Bpb9CXCyYPbULNShE8DtOmE3esWSu2ZCmGZIhvXv7pIw4kjsHKjokwIaGhoFkhiKy0+R74U53uOaBB7Jx17h2qamEceTIze5XKQIsj6wUzTwPV7cW+Va0QOJpgcmcyttBsftcaT3ccFLesigXaYfHLZH+zIayv0BnlE0oXrrpmww==</enc>]]>
    </text>
  </js>
  <css>
		<text>
		  <![CDATA[<enc>YkWQBTDGylCtyJwcHZMp4kHLaONbdUrMufRzgaQUdjOVHbs5oKu+l6KFsfCID5FR0jKE8+DnzTXxaZEDG6fzYitaTLM56tGmLpzNts4bfg2w5y+VaHqLKlJ0qsMFP0R2xvftD6xoLu/RUn545KoPNRqcgD/u055Xj8Odu0HgiqI=</enc>]]>
		</text>
  </css>
       

  <script>
    <declare>
      <text>
        <![CDATA[<enc>hxQPm/hYhpvPifcenBxj7nfT+X4T8oXvYmZx4Kpwn3fRRVZY+foYIow2vt1OHdzq0lG6PkDpvnlKR1ei3AR28UkawCxswedTww8YMZ/ax/1/BVJZ6K0wvLOosliedaWZOUKTHJl3fWcYZ5hcBuMZRtdM4wFmajxtZDsG20FuQ+f+RCvqp0omqPqHL+Zbo40iuqwGPkP3/iq98JuhlMs2hUu6IqVOT3SDHIAREQ1qgd0=</enc>]]>
      </text>
    </declare>
  </script>

</dir> Iswift@123