<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmbencang" table="dmbencang" fieldKey="ma_ben" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục bến cảng" e="List of Ports"></title>
  <title0 v="Thêm mới" e="Create New"></title0>
  <title1 v="Sửa" e="Edit"></title1>


  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
        <field name="ma_ben" format="U" label="1" field="1" allowBlank="false" fieldType="PK" importable="1"  >
          <text v="Mã bến cảng" e="Port Code"></text>
        </field>
        <field name="ten_ben" label="1" field="-" allowBlank="false" importable="5" >
          <text v="Tên bến cảng" e="Port Name"></text>
        </field>
        <field name="ten_ben2" label="1" field="-" importable="10" >
          <text v="Tên khác" e="Other Name"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" valueDefault="1" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>1PFOGp66gVgaSTPirrPUVQbMSKkhmnTmRHH3u+H6D2zM8z3Qwt/ZFDnp1dW7nqktJ7jFzoeKjFoTwOCExszb2S/0Pf8fvxx7pZHiNx2qUZoQeiRDT9Z3bqnn1fXbtvHv2uC0PeSL1EhWXh58H9kYZM4he7FOAXwmLto0Eis3KUlzJaEk0rDd0BXOz8Hj8cx70lu1qMM61klESDg3wIjx+y9BRX7QAjieI/CN/zLIilH4SY0rJWb/SQWF57ZZlZ/O4eVbj4SsS2P+tkLw1MOmaXXBLXQPIW0fIZINhspJEtBEqCi73HjDoZBPICAyySkvx8HgsjcC5c0NLFkxxBA+8WyiNvZTqM9L/RBAFdsSDs0=</enc>]]>
    </text>
  </js>
 
  <css>
	<text>
	  <![CDATA[<enc>/T0x+X5J8VnLtXSs8xERB1iizBHxQmUovXeEmWW/qu+RCDSRAi2tV/vRJTUiV2b02TLH83n8/tTDMvVsFKYW4qoGRCUW+9luB59BfNJEGkTxh0FT/jAlQmozXWOC+yAFKQR7y4NoXjLou3BT2TQiLA==</enc>]]>
	</text>
  </css>
  
  <script>
	<importing>
      <text>
        <![CDATA[<enc>PDeYaSq5D3THjzUfjXLnuOov+zRPCu/HsQ7cYLJ9+NUbtW4WBDcym9s/zoBHUkNI</enc>]]>
      </text>
    </importing>
  </script>
  
  <messages>
	<message val="codeExistsNewMsg">
		<text v="Mã bến cảng đã tồn tại trong danh mục, vui lòng chọn một mã khác." e="The port code already exists in the catalog, please choose a different code."/>
	</message>
	<message val="codeExistsEditMsg">
		<text v="Mã bến cảng đã tồn tại trong danh mục, vui lòng chọn một mã khác." e="The port code already exists in the catalog, please choose a different code."/>
	</message>
  </messages>

</dir>