<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmcalv" table="dmcalv" fieldKey="ma_ca" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục ca làm việc" e="List of Work Shift"></title>
  <title0 v="Thêm mới" e="Create New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
        <field name="ma_ca" format="U" label="1" field="1" allowBlank="false" fieldType="PK" importable="5" >
          <text v="Mã ca làm việc" e="Shift Code"></text>
        </field>
        <field name="ten_ca" label="1" field="-" allowBlank="false" importable="10" >
          <text v="Tên ca làm việc" e="Shift Name"></text>
        </field>        
		<field name="ten_ca2" label="1" field="-" importable="15" >
          <text v="Tên khác" e="Other Name"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" valueDefault="1" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>dtYy4kD7R/zFbl3e6NPEDqyBBG/BQ+lTqA2sEc0zW/AssCjvP4veqPE1vq+fSIAdh5E5SYJ3Y4s4of7UwcI+uNIxukDcWWfULETeHmfQseRRSAKmCEY037vl+UWp5us4EcwpGG2Vy+JbidHAeGnMqriL0TK1VyGYcxSc3nrrKy07L7guZN6abDFElx3Uo7vhuon/dIIn5aXhjtY549DI3lZT+zENzIUW1D/Vn6BpP3q1HBggzmPiijjmN+7i/nEqYJ06OCCq3KlB0/vSa97bR+LuGpYYW7ZWSJAyocBP3+0xOWn2Ehl6vx+g9vSMDEiC4BlfFAt9fNp8T1Kyx8HBYSj6ADYocpN5MmK7FtdRj0Y=</enc>]]>
    </text>
  </js>
  
  <css>
	<text>
	  <![CDATA[<enc>/T0x+X5J8VnLtXSs8xERB1iizBHxQmUovXeEmWW/qu/u6xlhOBF8VLCQW24Qs0NlWjr9KAvJtxRHQc3hqOhA+6z6cyWa88usCCQkhZYXE8q3DW3J9kFuAsw/bVS3jsm8OPmu2eltxH+V707VakIflQ==</enc>]]>
	</text>
  </css>
  
  <script>
	<importing>
      <text>
        <![CDATA[<enc>PDeYaSq5D3THjzUfjXLnuOov+zRPCu/HsQ7cYLJ9+NUbtW4WBDcym9s/zoBHUkNI</enc>]]>
      </text>
    </importing>
  </script>
  
  <messages>
	<message val="codeExistsNewMsg">
		<text v="Mã ca làm việc đã tồn tại trong danh mục, vui lòng chọn một mã khác." e="The work shift code already exists in the catalog, please choose a different code."/>
	</message>
	<message val="codeExistsEditMsg">
		<text v="Mã ca làm việc đã tồn tại trong danh mục, vui lòng chọn một mã khác." e="The work shift code already exists in the catalog, please choose a different code."/>
	</message>
  </messages>
</dir>