<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmcang" table="dmcang" fieldKey="ma_cang" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục cảng" e="Port List"></title>
  <title0 v="Thêm mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
        <field name="ma_cang" format="U" label="1" field="1" allowBlank="false" fieldType="PK" >
          <text v="Mã cảng" e="Port Code"></text>
        </field>
        <field name="ten_cang" label="1" field="-" allowBlank="false">
          <text v="Tên cảng" e="Port Name"></text>
        </field>
        <field name="ten_cang2" label="1" field="-" allowBlank="false">
          <text v="Tên khác" e="Other name"></text>
        </field>
        <field name="dia_chi" label="1" field="-" importWidth="250" importable="30">
          <text v="Địa chỉ" e="Address"></text>
        </field>
		<field name="ma_qg" viewType="Lookup" label="1" field="[120]"  >
           <text v="Mã quốc gia" e="Country code"></text>
           <viewInfo lookupType="One" lookupId="dmquocgia" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_qg" lookupInfo="dmquocgia|ma_qg|ten_qg" importCheck="@@DF and z.status=1"/>
        </field>
        <field name="ten_qg" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
           <text v="" e=""></text>
        </field>
		
		<field name="ma_ttp" viewType="Lookup" label="1" field="[120]"  >
           <text v="Khu vực" e="Area code"></text>
           <viewInfo lookupType="One" lookupId="dmttp" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_ttp" lookupInfo="dmttp|ma_ttp|ten_ttp" importCheck="@@DF and z.status=1"/>
        </field>
        <field name="ten_ttp" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
           <text v="" e=""></text>
        </field>
		
		<field name="dien_thoai" label="1" field="2" importable="80">
          <text v="Điện thoại" e="Phone"></text>
        </field>
		<field name="fax" label="1" field="2" importable="85">
          <text v="Fax" e="Fax"></text>
        </field>
        <field name="email" label="1" field="2" importable="90">
          <text v="Email" e="Email"></text>
        </field>
		<field name="tdx" label="1" field="1" dataType="N" importable="90">
          <text v="Kinh độ" e="Longitude"></text>
        </field>
		<field name="tdy" label="1" field="1" dataType="N" importable="85">
          <text v="Vĩ độ" e="Latitude"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>1PFOGp66gVgaSTPirrPUVckmsJt7lgMHIb1CU9/SGqVobJ7OK6EearAueWrjVAN2H5czY1Y/LaGCJzrxbm+473t2OrD5n0oA1uFxlAO2cmkXdWqIeuIELmsNaXDMkaLgH4X1Sy1RWTzdXINELsZ86epaHboflPo1+lSz5yHbL6lC0SyHqsUMxYjud77PO+sAnCRyjk0j2DvTs7kTWd2EUebIR624xvshQi3i63tH3VTVO/CvjRrrb2pKsG17vGW92pcyYurcDmlossRYXdDvba/B8FQ55IRZCDZHoRIf7+0PD4sfLCbDCk0Uyb4gbGsS5FknDUAEp6ycYB+PcmecGw71yKvXv8LtHNVyiEOxkI8DoaGIXL7aFim4v8erBpgL</enc>]]>
    </text>
  </js>
  <css>
		<text>
		  <![CDATA[<enc>YkWQBTDGylCtyJwcHZMp4ku6Dq2oUNnvDbOHUD7o0MNGL5sc+0OTNc2UWPHw/6enx1ygHvpq5/ZhyhCjE/jxshodBnTtWoakFWkGfZgDUz7iCet38ccsOzkFSs7G3dND/cpoH5a/LCiSENdT7qrcIg==</enc>]]>
		</text>
  </css>

  <script>
	    

  
    <declare>
      <text>
        <![CDATA[<enc>hxQPm/hYhpvPifcenBxj7nfT+X4T8oXvYmZx4Kpwn3fRRVZY+foYIow2vt1OHdzq0lG6PkDpvnlKR1ei3AR28UkawCxswedTww8YMZ/ax/1/BVJZ6K0wvLOosliedaWZgdbtHsoQZhJeevXhLbmiEqiXRcqrZZZdv71dw4GhLZqL6Lx9b3uVojvrg42MfsqVvndDXn0Gc57VD2WDYs0oDMQ1xWNr569wqfdZIkXsZMQ=</enc>]]>
      </text>
    </declare>
  </script>

</dir>