<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>

<dir id="dmch" table="dmch" fieldKey="ma_ch" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục cửa hàng" e="Store List"></title>
  <title0 v="Thêm mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
		<field name="ma_ch" allowBlank="false" viewType="Lookup" label="[120]" field="[120]"  hidden="false" nextRow="true" disabled="false" fieldType="PK">
			<text v="Mã cửa hàng" e="Store Code"></text>
			<viewInfo lookupType="One" lookupId="dmkh" lookupKey="status = 1" lookupCheck="1=1" lookupRef="" lookupInfo="dmkh|ma_kh|ten_kh" />
		</field>
		<field name="ten_ch" label="1" field="2" allowBlank="false">
          <text v="Tên cửa hàng" e="Store name"></text>
        </field>
		<field name="ten_ch2" label="1" field="2" allowBlank="true">
          <text v="Tên khác" e="Alias"></text>
        </field>
		<field name="noi_dung" label="1" field="2" allowBlank="true">
          <text v="Nội dung" e="Content"></text>
        </field>
		<field name="dia_chi" label="1" field="2" allowBlank="true">
          <text v="Địa chỉ" e="Address"></text>
        </field>
		<field name="dien_thoai" label="1" field="2" allowBlank="true">
          <text v="Điện thoại" e="Phone"></text>
        </field>
		<field name="hotline" label="1" field="2" allowBlank="true">
          <text v="Hotline" e="Hotline"></text>
        </field>
		<field name="email" label="1" field="2" allowBlank="true">
          <text v="Email" e="Email"></text>
        </field>
		<field name="gio_mo_cua" label="1" field="2" allowBlank="true">
          <text v="Giờ mở cửa" e="Time open"></text>
        </field>
		<field name="gio_dong_cua" label="1" field="2" allowBlank="true">
          <text v="Giờ đóng cửa" e="Time close"></text>
        </field>
		<field name="ngay_mo_cua" label="1" field="2" allowBlank="true">
          <text v="Ngày mở cửa" e="Day open"></text>
        </field>
		<field name="ngay_dong_cua" label="1" field="2" allowBlank="true">
          <text v="Ngày đóng cửa" e="Day close"></text>
        </field>
		<field name="map" label="1" field="2" allowBlank="true">
          <text v="Bản đồ" e="Map"></text>
        </field>
		<field name="link" label="1" field="2" allowBlank="true">
          <text v="Link bản đồ" e="Link"></text>
        </field>
		<field name="link_bv" label="1" field="2" allowBlank="true">
          <text v="Link bài viết" e="Link News"></text>
        </field>
		<field name="link_ch" label="1" field="2" allowBlank="true">
          <text v="Link cửa hàng" e="Link Store"></text>
        </field>
		<field name="thu_tu" label="1" field="2" allowBlank="true">
          <text v="Thứ tự" e="Position"></text>
        </field>
		<field name="status" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
		<field name="ximage1" label="1" field="0" importable="65">
          <text v="&lt;img class='image-single' id='img_ximage1' src='' onerror='src=`../Images/noImage.png`'/&gt; &lt;input type='button' value='Tải ảnh' onclick='browseServer(`ximage1`, `img_ximage1`);' value='Mở 1' style='text-align: center; display: block; margin: 0 auto;' /&gt;" e="Image 1"></text>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>A9fpcEnBP1GxLmL7QCNmd5RjOEYNMxX88Dz7K8/6TaDmOyEgXhISYrR0FkCjhd7xArwPBzaBJ2/GvSWTOXxPA3jOgXP/GprOYozhsfPDGnqy4Bq5xS0c7clhbwIcYqwymu8OESkFIjMZneAtGb/xea0DMI3NFDwiyQipu3Tfw8FavUlxz8GzDawWB8UlqXyiqn2wIGdU8yWLVit7kVB6iMEUDwR26Ip8NP3bvxMthNP4eKt7dYWakqI8ASc/saUPpSzME8gQxeT5J3isiZMS0nebfNuylBKnFiXSKf+3Z7fzT6yz3Ej39sMig5DI6HFIWOeHnyn7Uu1rnrySxMJTmoO8iiAtSgIM9kIz2VGu43H+W73OfIJJCoGHAjdXTKU0hhCzUlIq/nIKi1Z5DdznZygRUNP0Y6/1IEMZH2tJgE3JnJEWWacqAETSTY/wCllvweQkicDOr3YdT156RY8kkHcQ7JW3CxrSRsSxmRJfnM4ag2r8KJfXTTRxFrd6JYWkxpnKvUUhbjIuZ0+QEnekrhLtWXI4YzBRPWxncLFhG4WHeWmxpyFilHIpLwild+txmkKCS732pj/hQyT7dO6Usow0Vw9d6UoXqo7qDOCJwLBivbPPRmRLOwzinTvLLnPfmGzjVWbiYUD0kNwlKTByiK7e+L69zqxLzlOyRVAW6UtsyzEmegmCKF2baUhUp8xvBd7bPY8BuEwVCFWTJO+yyA8xqEzBgiCm/WtmOKZh8dMCr1Yt2UQGuyzzez4atgTps76UKoLBNo7mg1b56aVjTMP1fwGgOJjqjXew4MrueQs=</enc>]]>
    </text>
  </js>
  <script>
	<request code="LoadBHCode">
		<text>		
			<![CDATA[<enc>fsADTClJH8iBF0GDeR9KGFOxx50NYIOC5Wb4lakjPjVvxjSsF6eMJj60oPkojBJ05wSvNluZV/ZxS1u2Ti4zO2YslahbtMT0ijbL18f0xcc=</enc>]]>
		</text>
	</request>
	<request code="LoadInfoProduct">
		<text>		
			<![CDATA[<enc>9YSCm4gmpNWSG62d18kkMvkXpOe/LGSxrzN/DEfE0A0AQ0xcE43L3XuQgWLrLCuU1p3w6nALwBfN5uAcNJJaSq0AZDkauxO6q8FAps1PJDSoGwnF/AHrjkjQQlBk0foxSRKyXCasYwO623mBVBDDDVQ8ddalvC1e75ZQWY0+jgI=</enc>]]>
		</text>
	</request>
  </script>

  <messages>
    <message val="codeExistsNewMsg">
      <text v="Mã dịch vụ đã có hoặc lồng nhau trong danh mục dịch vụ." e="The Service is invalid or already exists."/>
    </message>
    <message val="codeExistsEditMsg">
      <text v="Mã dịch vụ đã có hoặc lồng nhau trong danh mục dịch vụ." e="The Service is invalid or already exists."/>
    </message>
  </messages>

</dir>