<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmchungtu" table="dmchungtu" fieldKey="ma_ct" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục chứng từ" e="List of Voucher"></title>
  <title0 v="Thêm mới" e="Create New"></title0>
  <title1 v="Sửa" e="Edit"></title1>


  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
        <field name="ma_ct" format="U" label="1" field="1" allowBlank="false" fieldType="PK" importable="1" >
          <text v="Mã chứng từ" e="Voucher Code"></text>
        </field>
        <field name="ten_ct" label="1" field="-" allowBlank="false" importable="5" >
          <text v="Tên chứng từ" e="Voucher Name"></text>
        </field>
        <field name="ten_ct2" label="1" field="-" importable="10" >
          <text v="Tên khác" e="Other Name"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" valueDefault="1" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>dtYy4kD7R/zFbl3e6NPEDicRnNreIRyu0gAW/PTP9nS8R3NRqxp6avkRA+41KhFVCNjlUnF8ij8bTH8u2beWrOPLCQ7Kl1R+ylmidd6Cl24Y476tX5b6nwodzvpBO52kACUF18xqHPkONRLr28HrLFpkeLDI4YQn7DIl8phZaM6vaXmfyOpVKGJZjKUc6+iyCzYuB0P9K878sS9IdyZzsUoLkINHh1VyHhfENBnP7gTcvoaSq5LTeSjBsRcgLy3gvgzoDlEXZ/t8rKBw7o/Dr5zRe+Zp+0I3aU+tM/WYLxZuhrpcOapMauxYEN5m1iX1vg2RsZTE++mDT3B7ILcmPcWExAOho0FatU4SjJ3WWzY=</enc>]]>
    </text>
  </js>
  
  <css>
	<text>
	  <![CDATA[<enc>/T0x+X5J8VnLtXSs8xERB1iizBHxQmUovXeEmWW/qu+s9zyDnlRcP7M0eH24VqmElP4fkYkWQTf4cz8HDw6IVWHBkxEIOCLjQNaxQ/qMj4wTDvgrUjiA+C+F4nMWVfuuhX+Ozmi4VEis1O4xF4gvAA==</enc>]]>
	</text>
  </css>
  
  <script>
	<importing>
      <text>
        <![CDATA[<enc>PDeYaSq5D3THjzUfjXLnuOov+zRPCu/HsQ7cYLJ9+NUbtW4WBDcym9s/zoBHUkNI</enc>]]>
      </text>
    </importing>
  </script>
  
  <messages>
	<message val="codeExistsNewMsg">
		<text v="Mã chứng từ đã tồn tại trong danh mục, vui lòng chọn một mã khác." e="The document code already exists in the catalog, please choose a different code."/>
	</message>
	<message val="codeExistsEditMsg">
		<text v="Mã chứng từ đã tồn tại trong danh mục, vui lòng chọn một mã khác." e="The document code already exists in the catalog, please choose a different code."/>
	</message>
  </messages>

</dir>