<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmchucvu" table="dmchucvu" fieldKey="ma_cv" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục chức vụ" e="List of Position"></title>
  <title0 v="Thêm mới" e="Create New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
        <field name="ma_cv" format="U" label="1" field="1" allowBlank="false" fieldType="PK" importable="5" >
          <text v="Mã chức vụ" e="Position Code"></text>
        </field>
        <field name="ten_cv" label="1" field="-" allowBlank="false" importable="10" >
          <text v="Tên chức vụ" e="Position Name"></text>
        </field>
        <field name="ten_cv2" label="1" field="-" importable="15">
          <text v="Tên khác" e="Other Name"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" valueDefault="1" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>dtYy4kD7R/zFbl3e6NPEDgLHa+ZxYq7squvmGDmJwNM4OJTyhqiguflFpAgm7xCeWXrVncs+WtagIb1cv8lxhnJJgBlsJMiu6rg6YKu5sRsh9qPtKrOmI1dann7NNu91SA1NmzX4ayEvX0fLqVC2fO+keAVk+zdXRCSth9w7Xob/RQWV+uOowLyTOcLua5bELYZV2+mPIy6q83uOY9ZPvjkMO2//gmW0iXqvH+6c+PAPymMMEiXORr+3hkyPVtKDYkVJ/0FAOtLwdDNGSiETxRPhe2yM2Uo78mZn+uLAe9bLPbWIvgS3egEGiemvNjzkOigwl9zAnHGo2jI9LO23OIzKgcfUqvngRq1OVsCUSRA=</enc>]]>
    </text>
  </js>
  
  <css>
	<text>
	  <![CDATA[<enc>/T0x+X5J8VnLtXSs8xERB1iizBHxQmUovXeEmWW/qu8ntGvbJrvhiX6cDiQlUSuqJL+dwbXmIw9zSvNUZaaJiSmQFXE2v4MnF8PQ5lTUMENkUPRQErCP621RKXKtAdqXh7JDEtfBv87WalUrH2ZnJQ==</enc>]]>
	</text>
  </css>
  
  <script>
	<importing>
      <text>
        <![CDATA[<enc>PDeYaSq5D3THjzUfjXLnuOov+zRPCu/HsQ7cYLJ9+NUbtW4WBDcym9s/zoBHUkNI</enc>]]>
      </text>
    </importing>
  </script>
  
  <messages>
	<message val="codeExistsNewMsg">
		<text v="Mã chức vụ đã tồn tại trong danh mục, vui lòng chọn một mã khác." e="The position code already exists in the catalog, please choose a different code."/>
	</message>
	<message val="codeExistsEditMsg">
		<text v="Mã chức vụ đã tồn tại trong danh mục, vui lòng chọn một mã khác." e="The position code already exists in the catalog, please choose a different code."/>
	</message>
  </messages>
</dir>