<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmchiphi" table="dmchiphi" fieldKey="ma_phi" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục phí" e="List of fee"></title>
  <title0 v="Thêm mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
        <field name="ma_phi" format="U" label="1" field="1" allowBlank="false" fieldType="PK" >
          <text v="Mã phí" e="Fee code"></text>
        </field>
        <field name="ten_phi" label="1" field="-" allowBlank="false" >
          <text v="Tên phí" e="Fee name"></text>
        </field>
        <field name="ten_phi2" label="1" field="-">
          <text v="Tên khác" e="Other name"></text>
        </field>
        <field name="ma_loai" allowBlank="false" viewType="Lookup" label="1" field="1" >
          <text v="Mã loại" e="Type code"></text>
          <viewInfo lookupType="One" lookupId="dmloaichiphi" lookupKey="status = 1" lookupCheck="1=1" lookupRef="ten_loai" lookupInfo="dmloaichiphi|ma_loai|ten_loai" />
        </field>
        <field name="ten_loai" nextRow="false" fieldType="EX" readOnly="true" inactivate="true"  hidden="false" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
		<field name="ma_np" allowBlank="false" viewType="Lookup" label="1" field="1" >
          <text v="Nhóm in (kế toán)" e="Printing team (accounting)"></text>
          <viewInfo lookupType="One" lookupId="dmnphi_in" lookupKey="status = 1" lookupCheck="1=1" lookupRef="ten_np" lookupInfo="dmnphi_in|ma_np|ten_np" />
        </field>
        <field name="ten_np" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" hidden="false" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
		<field name="f_in" dataType="B" clientDefault="true" label="1" field="[40]" inactivate="true" >
			<text v="In (Default)" e="In (Default)"></text>
		</field> 
        <field name="status" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>1PFOGp66gVgaSTPirrPUVVXHCZhYQQOqRHPLw9CqJ8k3w4uJHZk8BZg6KMUlV1ODwy3gfFx5MTXEmUKlj7Acf7wTPkDQb4G5rXebu2TcWbXAkF26sB/qRMNa7s6UmPLyzS/dr6vGSVFVWHuXaclGfuQAeKqet/3+6z0w2qWZwbIBSDb61KduhYgK8qeQVG29a+jttlgMSga5lvcgYFbLqpsXAv3shUjKI7Voi5PIrk8N8vt7CA+9gg5RNWh+6XCT+Mep62H+V/4kauwFvSa4hfIMOTx3hfi9Fx3BSE4AVSeaCtvZgnRERj4Qhik7BQn5dI5gnUv3WGcjWAFcgTGC6EgMgOAd06a7/lThyaFpBW0=</enc>]]>
    </text>
  </js>
   <css>
		<text>
		  <![CDATA[<enc>YkWQBTDGylCtyJwcHZMp4lZsTBMUUzGyXkCNhkU8H8lRAqCUEFsMf2+JQQI2Pgrfab0Em3gcvR8oWMYJbO3pMQr9g+RcWj/6pjmBhBQgwa4h9EC23Y+mm6Nxhotq6Zpr</enc>]]>
		</text>
  </css>
  <script>
    <declare>
      <text>
        <![CDATA[<enc>hxQPm/hYhpvPifcenBxj7nfT+X4T8oXvYmZx4Kpwn3fRRVZY+foYIow2vt1OHdzq0lG6PkDpvnlKR1ei3AR28UkawCxswedTww8YMZ/ax/1/BVJZ6K0wvLOosliedaWZm23TaYHZ9fEWFuSfo8O1KnRSxwaalptnv4u5mkJ8TMGVg1mHiiZtkiZkYc7uozfsyKNWYn0GXMUGmfJOYG84SBZRHmRYuUcDP+cKZFfkTDY=</enc>]]>
      </text>
    </declare>
  </script>

</dir>