<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>

<dir id="dmcnct" table="dmcnct" fieldKey="ma_cnct" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục chức năng chức năng" e="List of Function functions"></title>
  <title0 v="Mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
        <field name="ma_cnct" format="U" label="1" field="1" allowBlank="false" fieldType="PK" >
          <text v="Mã chức năng " e="Function code"></text>
        </field>
        <field name="ten_cnct" label="1" field="-" allowBlank="false">
          <text v="Tên chức năng" e="Function name"></text>
        </field>
        <field name="ten_cnct2" label="1" field="-" >
          <text v="Tên khác" e="Other name"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>1PFOGp66gVgaSTPirrPUVUgXFguRdD4kd6Aw/AylcI85VhQTdfoBoPJsej69r4xhFn1lTx5dH1CAq9XwEcgjFxUp5bgPNUoyrYMl4vaAa6mUTLFZ6Zow3jjwQYKxaK4i3thIjcHSYwB2TWXRkyYXUwa7JNFOsYEnK7HFBLVWaY55i6fvzjMP9Egs6JTHejyMNpWhhCDGNDEz7uhZW5lK/sRsFkA9pLw7RAjzR367raRj3lpidbtwQ9POx5johTdH9aY0pTXQaGHBaB811Co7hsCbiF9iom8YudvzCHR7bv0FzFDB7W/YwmeBbCmp8J09R53f5TOhOsjgHPV5zkGvWg==</enc>]]>
    </text>
  </js>
<css>
		<text>
		  <![CDATA[<enc>YkWQBTDGylCtyJwcHZMp4ku6Dq2oUNnvDbOHUD7o0MN8raMIr5KVABy0j2TTFSY1qddd+Iak/PA3IRuv++3Ifyhx65QysYdqPsCOWv8oeRoL10Cfs9XRoJ9N8DeBGyZhdX/k+jaxJWTb22W/FSUi5Q==</enc>]]>
		</text>
  </css>
  <script>
    <declare>
      <text>
        <![CDATA[<enc>hxQPm/hYhpvPifcenBxj7nfT+X4T8oXvYmZx4Kpwn3fRRVZY+foYIow2vt1OHdzq0lG6PkDpvnlKR1ei3AR28UkawCxswedTww8YMZ/ax/1/BVJZ6K0wvLOosliedaWZOkzJZgfWwfZT50y/Wyc2/103IQZFeK2Xvmt5nCaOlncIjIlB/arUKgZKdjSYtpz3AfUbGJEcsur4sO199jSIXDnQ9USnbe5CvveGtkj/gvGyorvQR9lncZMRbkbiSnPNFMuMw8xIbB0HF60pznH2sw==</enc>]]>
      </text>
    </declare>
  </script>

</dir>