<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmdvt" table="dmdvt" fieldKey="dvt" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục đơn vị tính" e="Units of Measure"></title>
  <title0 v="Mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
        <field name="dvt" format="U" label="1" field="1" allowBlank="false" fieldType="PK" >
          <text v="Đơn vị tính" e="UOM"></text>
        </field>
        <field name="ten_dvt" label="1" field="2" allowBlank="false" fieldType="PK" >
          <text v="Tên đvt" e="Description"></text>
        </field>
        <field name="ten_dvt2" label="1" field="2" allowBlank="true">
          <text v="Tên khác" e="Other name"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>T5Nuk0XwnW0VlRYHOIM5VXhKO7/eOS+JOgvPzcIet9YIMDiLcEyTpsRHXjZnxhJpsOJCna2jNvSBLbbFOM70ap2js+Evxdv4DZkB8k8cEkeJDqIMqlbpX51MfOVyLz0MxPaSxagt+hWGQjCDswUxlpDr9rbyyCguxHLx/qSndV5UxsF2FmCGveoK7bzGkckH</enc>]]>
    </text>
  </js>

  <script>
    <declare>
      <text>
        <![CDATA[<enc>hxQPm/hYhpvPifcenBxj7nfT+X4T8oXvYmZx4Kpwn3fRRVZY+foYIow2vt1OHdzq0lG6PkDpvnlKR1ei3AR28UkawCxswedTww8YMZ/ax/1/BVJZ6K0wvLOosliedaWZ4p/etAyqAYs72bkFC2T8+iC2VmVTB1QYr6UFExkgBc+7dhGvNPYIxZAQts7b0MRBYncDsBBrZ/93SP3pISF3vA/d6ABYwwN3t6dJZWaMSww=</enc>]]>
      </text>
    </declare>
  </script>

</dir>