<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmdv2" table="dmdv2" fieldKey="ma_dv" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục dịch vụ" e="List of services"></title>
  <title0 v="Thêm mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
        <field name="ma_dv" format="U" label="1" field="1" allowBlank="false" fieldType="PK" >
          <text v="Mã dịch vụ" e="Services code"></text>
        </field>
        <field name="ten_dv" label="1" field="-" allowBlank="false" fieldType="PK" >
          <text v="Tên dịch vụ" e="Services name"></text>
        </field>
        <field name="ten_dv2" label="1" field="-">
          <text v="Tên khác" e="Other name"></text>
        </field>

        <field name="status" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>BNkCGJa0GOfBEp6lUnseuT6bwqQ8ThQwa7i2gG/JoKc+oqYSKc+f0SL5sVYXd5XTLNQClpH6YkJYzIVE0ektkP/wA5hI41Z9X5Z+pnK5Ufqt+gKO/tZHS5r4GhDnZzNsFXyz1oS004j//NIfNQeaXplzMzc4CpFB2Y6B1ux2JckMh82AruSrFjPn5MX4ukTnDbjzsq8NRp4/8QJz4LGR3yWAXIjA3W/NWyI0BkYEQ2okIG0llqJiPjUgbpzCpH1QXo8dkwTXGTN09J/NBhBwh2sJcPB5Tqlq9Ke1edO52n5DUu/gdqvhMuMILYn+uzR0M3OamwtgCUnvbpEmudxFOA==</enc>]]>
    </text>
  </js>
   <css>
		<text>
		  <![CDATA[<enc>YkWQBTDGylCtyJwcHZMp4ku6Dq2oUNnvDbOHUD7o0MPL4ioGRj6h9Pwkr4RX/S5/9KfPpw/gl1EgvXMWaVoPbe7SsC84y0iNzE+YdVYDTlo/SgiGVP00JnABftqIY+0D</enc>]]>
		</text>
  </css>
  <script>
    <declare>
      <text>
        <![CDATA[<enc>hxQPm/hYhpvPifcenBxj7nfT+X4T8oXvYmZx4Kpwn3fRRVZY+foYIow2vt1OHdzq0lG6PkDpvnlKR1ei3AR28UkawCxswedTww8YMZ/ax/1/BVJZ6K0wvLOosliedaWZp07kCSP8gvYvq6ayQ+6pIhJZ0Q6lzv/oMsmdORR/V5F5Ly0ewzZJKxmFfoLU+7Mowru2Ywfo5LdLjs3ZoQbI4fs1U6tEVvJLXUnxSazkK9V1iZyS4v3FjAx4xbms0JT2</enc>]]>
      </text>
    </declare>
  </script>

</dir>