<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmgplx" table="dmgplx" fieldKey="ma_tx,ngay_thi" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Khai báo giấy phép lái xe" e="Declare a driver's license"></title>
  <title0 v="Thêm" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120,120,120" >
      <fields>
        <field name="ma_tx" format="U" label="1" field="1" viewType="Lookup" clientDefault="true" allowBlank="false" fieldType="PK" >
          <text v="Tài xế" e="Driver Code"></text>
          <viewInfo lookupType="One" lookupId="dmnv" lookupKey="status=5 and ma_bp = 'TX' " lookupCheck="1=1" lookupRef="ten_nv" lookupInfo="dmnv|ma_nv|ten_nv" />
        </field>
        <field name="ten_nv" nextRow="false" fieldType="EX" readOnly="true" clientDefault="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
		
		
	
		
		
		
		<field name="so_gplx" label="1" field="1" allowBlank="false" >
          <text v="Số GPLX" e="Driver's license number"></text>
        </field>
		<field name="ngay_thi" label="1" field="1" valueDefault="new Date()" allowBlank="false" dataType="D" fieldType="PK">
          <text v="Ngày thi" e="Exam Date"></text>
        </field>
		<field name="khoang_cach" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" hidden="true" label="" field="1">
			<text v="" e=""></text>
		</field>
        <field name="ngay_hh" label="1" field="1" allowBlank="false" dataType="D" nextRow="false" fieldType="PK">
          <text v="Ngày hết hạn" e="Date From"></text>
        </field>
		
       
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>uw3iZoR/y/5o6FF1x5y/2XACQ/VWlTELVqLP0L84o5KEmzwDGRMe9LMR5ZmjKUlfDib89KJmvawvcz8sqPrPhldS6ioyaptUIVx8sUTOLefTe3kRtj64PljogPsHOnBgIBccOe9sc4qg0ZBab68ZPo3PM7zpnMdD4J1l0hgafWUVVSWrVyybXJ7F8NyqrnOf</enc>]]>
    </text>
  </js>
<css>
	.control-label.ma_tx
	{
		color: #499b98;;
	}
</css>
  <script>
    <declare>
      <text>
        <![CDATA[<enc>hxQPm/hYhpvPifcenBxj7nfT+X4T8oXvYmZx4Kpwn3fRRVZY+foYIow2vt1OHdzq0lG6PkDpvnlKR1ei3AR28UkawCxswedTww8YMZ/ax/1/BVJZ6K0wvLOosliedaWZ5n6EqlL8s3ib/8D1Ph5jO5Jni1qileL5fGNW4mYfolVDitmwwpNf2rVkWonSeKg6mjpGVIr1EwFw95SyNjNdBU5ogkwQ6VK+GUvI84KcVmuOT2ebtEgx+v9BrURk6uuL</enc>]]>
      </text>
    </declare>
  </script>

</dir>