<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>

<dir id="dmhogiadinh" table="dmhogiadinh" fieldKey="ma_hogiadinh" transaction="true" tryCatch="true" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh sách hộ gia đình" e="List of Circulated Documents"></title>
  <title0 v="Thêm mới - hộ gia đình" e="New - household"></title0>
  <title1 v="Sửa - hộ gia đình" e="Edit - household"></title1>

  <forms>
	<form gravity="TopLeft" columns="120,120,120,120,120" >
		<fields>
			<field name="unit_id" dataType="I" hidden="true" readOnly="true" inactivate="true" label="1" field="1" importable="-1">
			  <text v="" e=""></text>
			</field>
			<field name="ma_hogiadinh" label="[120]" field="[120]" allowBlank="false" format="U" disabled="false" fieldType="PK" importable="5" >
				<text v="Mã hộ gia đình" e="Household Code"></text>
			</field>
			<field name="ma_chuho" allowBlank="true" viewType="Lookup" label="1" field="1"  hidden="false" importable="10">
			  <text v="Mã chủ hộ" e="Household Head Code"></text>
			  <viewInfo lookupType="One" lookupId="qldctcccd" lookupKey="ma_qhgd = '03' and ma_dancu not in (select ma_chuho from dmhogiadinh) and status = 1" lookupCheck="1=1" lookupRef="ten_chuho" lookupInfo="qldctcccd|ma_dancu|ten_dancu" />
			</field>
			<field name="ten_chuho" nextRow="false" fieldType="EX" readOnly="true" inactivate="true"  hidden="false" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
			  <text v="" e=""></text>
			</field>

			<field name="ma_ttp" allowBlank="false" viewType="Lookup" label="1" field="1"  hidden="false" importable="15">
			  <text v="Mã tỉnh thành phố" e="Province/City Code"></text>
			  <viewInfo lookupType="One" lookupId="dmttp" lookupKey="status = 1" lookupCheck="1=1" lookupRef="ten_ttp" lookupInfo="dmttp|ma_ttp|ten_ttp" />
			</field>
			<field name="ten_ttp" nextRow="false" fieldType="EX" readOnly="true" inactivate="true"  hidden="false" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
			  <text v="" e=""></text>
			</field>
			<field name="ma_phuongxa" allowBlank="true" viewType="Lookup" label="1" field="1"  hidden="false" importable="15">
			  <text v="Mã phường/xã" e="Ward/Commune Code"></text>
			  <viewInfo lookupType="One" lookupId="dmphuongxa" lookupKey="ma_ttp = ![ma_ttp]! and status = 1" lookupCheck="1=1" lookupRef="ten_phuongxa" lookupInfo="dmphuongxa|ma_phuongxa|ten_phuongxa" />
			</field>
			<field name="ten_phuongxa" nextRow="false" fieldType="EX" readOnly="true" inactivate="true"  hidden="false" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
			  <text v="" e=""></text>
			</field>
			<field name="ma_khupho" allowBlank="true" viewType="Lookup" label="1" field="1"  hidden="false" importable="20">
			  <text v="Mã khu phố" e="Neighborhood Code"></text>
			  <viewInfo lookupType="One" lookupId="dmkhupho" lookupKey="(ma_phuongxa = '' or  ma_phuongxa = ![ma_phuongxa]!) and status = 1" lookupCheck="1=1" lookupRef="ten_khupho" lookupInfo="dmkhupho|ma_khupho|ten_khupho" />
			</field>
			<field name="ten_khupho" nextRow="false" fieldType="EX" readOnly="true" inactivate="true"  hidden="false" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
			  <text v="" e=""></text>
			</field>
			<field name="dia_chi" label="1" field="-"  allowBlank="true" disabled="false" importable="25">
			  <text v="Địa chỉ" e="Address"></text>
			</field>
			<field name="status" viewType="Combobox" inactivate="false" label="1" field="2" valueDefault="1" nextRow="true" importable="-1" >
			  <text v="Trạng thái" e="Status"></text>
			  <viewInfo>
				<options query="select ma_tt, ten_tt%l from dmttsd where status = 1 ">
				</options>
			  </viewInfo>
			</field>
      </fields>
    </form>
</forms>

&DefaultButton;

<js>
    <text>
  <![CDATA[<enc>cQJZhIecAG71USD6FX9J3NGs7xoAuZMMzZAaNgjEggiDld3uq01OiRY3mtQgJ5XHpMfyfXOHGFSWYzDE3l6TullHBoKewWd/1Hx4uyjhYPtYREC7xge7tAH0B5ixKCvHLZrEceRlHhbZ5B7sReXidNqHnmygQWLEvXOn3iiljoz7jl181obFcSy7z5VUp2+HGiphTy/4f8kJx7MrSfoqi6aAgPUgK9hc8gUORIKdJsEZgJf4gPWIBQK3rkBaEyZeT127FT/Q7bkBKZU92Gj/yhUCE7tk1Z0SWjaaFAFExulE2xuenkWbzcJ5Si9TQW1r</enc>]]>
    </text>
  </js>
	<css>
		<text>
			  <![CDATA[<enc>s5XWMSrs6w5R2zI1vM6n2zlNvdu05x8AyDC7rNaG/s2fTYknlNQ9ReEi4IpSbOdoEBUqyMWLxZiUFPJZwPXUVjvsx8xTuPtSaSdXR81C/RIk/NsxqeiCTjBSKdQHKDm+Jy08FVJAE+cyXcvgtWdfY2jh/+n+h7Sc5Rb8rgR/ue7WQZTvLJ/LMgQmSwSGvjV5</enc>]]>
		</text>
	</css>
	<script>
		<query>
		  <text>
			<![CDATA[<enc>GJgBVkOd9xy3In+SUACpOOdXdTQbLjDNG098RVYG+mqJrACGNi8MwNsRrtmQkuMIYyR65+M+8FdE2nQkBtdUjjGtkBSGsDqbRbA3vrYN89ZzUnQVJ+W1/9AMkiZ8xTjPYAdSbE6TNHswawXCA3Q7ZKpywgArBHY6CKMo02cq6Ek=</enc>]]>
		  </text>
		</query>
		<updated>
		  <text>
			<![CDATA[<enc>sxD5Swu0R4mcxEHdwcy2ynVkJ6IiRfsuHiDzDrC78ELIJg2k4xX5PxEITwgSuDtWSiTOU3sqnIo/Bv0T8e877uKHW6bIEuTFdpbPdQB+xElll2tzxh9iUOpwbot+jXTZNKo5+n5Fy+aXD8VrO81PEw==</enc>]]>
		  </text>
		</updated>
		<inserting>
		  <text>
			<![CDATA[<enc>/T/6v4fr7JtuEWROY5bEog4q37AdyKX5y50iwuf8o+kQ/cMLdjO5yBgIja/EXDIb67gjtJCgsvsoKVHnH40ASfHmT/5Pyqyz9fEF+eXazaeFq1QdO25I17j8uqKw4sm7PDDzWS+uYkqIWo1FmMQqY1vwSihUQwhC3DMwYBlMdqW/7I05kvZGgi3lyKQDrJ1gd1u3eDHWrXNvOq+fBosahfSLln2pO8chassI1khVi2Brg84FNLLprzwizWkmE7Kk</enc>]]>
		  </text>
		</inserting>
		<importing>
			<text>
			<![CDATA[<enc>sxD5Swu0R4mcxEHdwcy2yi46ZbQRyi0uEDh1tGVfNVOBZJeZZHskWnswm55XGvVMZq7vIrj1gngY5x8IJuKO1pkyFlxS8pifsEwHrhrpEjg=</enc>]]>
			</text>
		</importing>
	</script>
	<messages>
		<message val="codeExistsNewMsg">
		  <text v="Mã hộ gia đình đã tồn tại trong danh mục." e="The household code already exists in the list."/>
		</message>
	</messages>
</dir>
