<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmhoahong" table="dmhoahong" fieldKey="ma_hoahong" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục hoa hồng" e="List of commission"></title>
  <title0 v="Mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
        <field name="ma_hoahong" format="U" label="1" field="1" allowBlank="false" fieldType="PK" >
          <text v="Mã hoa hồng" e="Commission code"></text>
        </field>
        <field name="ten_hoahong" label="1" field="2" allowBlank="false" fieldType="PK" >
          <text v="Tên hoa hồng" e="Commission name"></text>
        </field>
       <field name="ten_hoahong2" label="1" field="1">
          <text v="Tên khác" e="Other name "></text>
        </field>
		<field name="tyle_hh" label="1" field="1" dataType="N">>
          <text v="Tỷ lệ" e="Ratio "></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>uw3iZoR/y/5o6FF1x5y/2e45Ch26I5UtY+kSARaVLyoILGg6P+6fmnHZ4XPUymdNtHEiMR0IGVWd+BEMRDvKT8gnhQeMkqp47NBYjfEp6TwG8EraI4/LcbBF9VELsTfwpMl/gRiE9E3Avav3mGoop/DfJNFOiHuBhujtsS1bk+lmJ36SLhCNk6252U8+SbsL</enc>]]>
    </text>
  </js>

  <script>
    <declare>
      <text>
        <![CDATA[<enc>JZyGgESirBtG5NTG2mOIr0NCLaE4K5qr/YMHv55KwejZMEeVmTQbRv8cqL+9s6UCTGVNBEvfX6IvpC+KtxWm3s85/XrplM7t9fXRufqPsUTMSdkyAd9HGfrmPPogxFPt362bYxWe10kEqd5Wr7Ua5IhY5TLL1zidEL+n38kttmf8gIE+c1Ydl0DcnC+0QZhuzVwe+EEorkOkuWHr5mc37hgPQJOqQcDc7tBa/tMfKh9Mmv1EoPLMYWFzTFTnERgA</enc>]]>
      </text>
    </declare>
  </script>

</dir>