<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmhttt" table="dmhttt" fieldKey="ma_httt" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục hình thức thanh toán" e="List Payment"></title>
  <title0 v="Mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
        <field name="ma_httt" label="[150]" field="1" allowBlank="false" fieldType="PK" >
          <text v="Mã hình thức thanh toán" e="Payment Code"></text>
        </field>
        <field name="ten_httt" label="[150]" field="2" allowBlank="false" fieldType="PK" >
          <text v="Tên hình thức thanh toán" e="Payment Name"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" label="[150]" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>T5Nuk0XwnW0VlRYHOIM5VYNfaGYwkaYTIoQrEJZAbA4YY6dhlzv6D7PbE3ShGfRLWjBejQ2SE1EgYGPYwADkqlkXOFkd2PZK70cfRCcwPuiCwwgwyzvI9IY9CD1IpAhY05ui5v9RDCD4yTtF4rMmHfVucMYlQT93dXCnP+YI3cT+bRIxm5oyRDZkTgkIk1wk</enc>]]>
    </text>
  </js>

  <script>
    <declare>
      <text>
        <![CDATA[<enc>hxQPm/hYhpvPifcenBxj7nfT+X4T8oXvYmZx4Kpwn3fRRVZY+foYIow2vt1OHdzq0lG6PkDpvnlKR1ei3AR28UkawCxswedTww8YMZ/ax/1/BVJZ6K0wvLOosliedaWZOs7gsx4IPsYsifJhBSRhIud2oizReOGfhVzJ00KgFD1Vm5EREABU8ioqIL/ewcsIAzNfIM3s5wG+oi9GRziEiUOVBONWQPSfJ8+BECD2T08=</enc>]]>
      </text>
    </declare>
  </script>

</dir>