<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>

<dir id="dmkc" table="dmkc" fieldKey="ma_kc" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục khoảng cách" e="Distance catalog"></title>
  <title0 v="Mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120,120" >
      <fields>
       <field name="ma_kc" fieldType="PK" label="1" field="1"  filterType="Code" allowBlank="false">
          <text v="Mã khoảng cách" e="Distance code"></text>
        </field>
        <field name="ten_kc" label="1" field="-"  allowBlank="false">
          <text v="Tên khoảng cách" e="Distance name"></text>
        </field>		
		<field name="ten_kc2" label="1" field="-" >
          <text v="Tên khoảng cách" e="Other name"></text>
        </field>
		<field name="noi_di" label="1" field="2"  allowBlank="false">
          <text v="Nơi đi" e="Vehicle name"></text>
        </field>
		<field name="noi_den" label="1" field="2"  allowBlank="false">
          <text v="Nơi đến" e="Vehicle name"></text>
        </field>
		<field name="chieu_dai" label="1" field="1"  allowBlank="false" dataType="N">
          <text v="Chiều dài" e="Vehicle name"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>OIvoYpbA2cjnWLO6Y4m5qFkd7azdU3cJsDnKvt0JeTGkFJ/mOZVH8+MZw1oLZpw9xPNrDm6eLf+uSCqz3xNDqAYjcck98evGbqI3uv47MWkAnJtb9aRJxptIazqFetQQyKfFyOlXyaGr/cUOW1dqOGQfaaL8bg+1awOvxcX4nYRF/d27grZBo3cY1YtowFv5J/ktIAOLX8sVqvoyEy9WmqGV70k8jZRYlt7Z9Z3M+ce1ZqmycFir+qjd9lM0Xb5aiYgy8QpUc8KmkUirkwfqBFfPX5OqAvk5Uqi5MGgE6zR2UQ4xv+0uuvOa5QSMIy5ckrAZ0ScK8zYJ+i4V+vwjMA==</enc>]]>
    </text>
  </js>
   <css>
		<text>
		  <![CDATA[<enc>YkWQBTDGylCtyJwcHZMp4kHLaONbdUrMufRzgaQUdjPFyU85FPqMp+YHpMM6V6K+e9Gb3a7ncl+t2q+uHBCOHAcJ7ZVcQxA9T4TuXM+3zDHBTU7p9g4vr7sQFi13rzgW8iFhYiMHvUeXn2DWwslLKw==</enc>]]>
		</text>
  </css>

  <script>
    <declare>
      <text>
        <![CDATA[<enc>kgNieZitFtjbYbV1eT4v7V7cbfxA2L9RTi1R+KENmoHTgwszfnwCdA0oUgki/+tmXkIOf6Yr3sWhk61dQxsIxLlwVS/V0cEFO5F9ziDowBWPdWHdjxpx/r6+OaTmdO2lQyTTvsMNwvnt402jdb0RB+JeqDhDIe2pGqKa/7e5Igc9gUNbrM959z35Ub4D3BDfDd+FNjR7CZ+ZmTn96U3n8DlEmCQZLfoIRLpOuAeE9aew+CXegVME3D+DrhDRZoYD</enc>]]>
      </text>
    </declare>
  </script>

</dir>