<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmkh0" table="dmkh0" fieldKey="ma_so_thue" transaction="true" tryCatch="true" dirViewType="Dialog" width="Large" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục khách hàng" e="List of Customer"></title>
  <title0 v="Thêm mới" e="Create New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120,120,120,120" >
      <fields>
        <field name="unit_id" dataType="I" hidden="true" readOnly="true" inactivate="true" label="1" field="1" importable="-1">
          <text v="" e=""></text>
        </field>
        <field name="ma_kh" format="U" label="1" field="1" viewType="AutoIncrease" allowBlank="false" fieldType="PK" importable="1">
          <text v="Mã khách hàng" e="Customer Code"></text>
        </field>
        <field name="ten_kh" allowBlank="false" label="1" field="-" importable="5">
          <text v="Tên khách hàng" e="Customer Name"></text>
        </field>
        <field name="ten_kh2" label="1" field="-" importable="10">
          <text v="Tên khác" e="Other Name"></text>
        </field>
		<field name="kh_yn" dataType="B"  blank="1" clientDefault="true" label="[100]" field="[40]" valueDefault="1"  inactivate="true" importable="15">
          <text v="Khách hàng" e="Customer"></text>
        </field>

        <field name="dia_chi" label="1" field="-" allowBlank="false" importable="45">
          <text v="Địa chỉ" e="Address"></text>
        </field>
        <field name="ma_so_thue" label="1" field="2" allowBlank="false" fieldType="PK" importable="50">
          <text v="Mã số thuế &lt;a onclick='getTax(this);'&gt;(Kiểm tra)&lt;/a&gt;" e="Tax Code &lt;a onclick='getTax(this);'&gt;(Test)&lt;/a&gt;"></text>
        </field>
        <field name="nguoi_lh" label="1" field="-" nextRow="false" importable="55">
          <text v="Người liên hệ" e="Contact"></text>
        </field>
		<field name="dien_thoai" label="1" field="2" allowBlank="false" importable="60">
          <text v="Điện thoại" e="Phone"></text>
        </field>
        <field name="fax" label="1" field="2" nextRow="false" importable="65">
          <text v="Fax" e="Fax"></text>
        </field>
		<field name="e_mail" label="1" field="2" importable="70">
          <text v="Email" e="Email"></text>
        </field>
        <field name="home_page" label="1" field="2" nextRow="false" importable="75">
          <text v="Trang chủ" e="Home Page"></text>
        </field>
		<field name="ghi_chu" label="1" field="-" inactivate="true" importable="80">
          <text v="Ghi chú" e="Notes"></text>
        </field>
        
        <field name="nh_kh1" viewType="Lookup" label="1" field="1" importable="85">
          <text v="Nhóm 1" e="Group 1"></text>
          <viewInfo lookupType="One" lookupId="dmnh" lookupKey="ma_loai_nh = 'KH1' and status=1" lookupCheck="ma_loai_nh = 'KH1'" lookupRef="ten_nh_kh1" lookupInfo="dmnh|ma_nh|ten_nh" importCheck="@@DF and z.ma_loai_nh = 'KH1' and z.status=1"/>
        </field>
        <field name="ten_nh_kh1" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
        <field name="nh_kh2" viewType="Lookup" label="1" field="1" importable="90">
          <text v="Nhóm 2" e="Group 2"></text>
          <viewInfo lookupType="One" lookupId="dmnh" lookupKey="ma_loai_nh = 'KH2' and status=1" lookupCheck="ma_loai_nh = 'KH2'" lookupRef="ten_nh_kh2" lookupInfo="dmnh|ma_nh|ten_nh" importCheck="@@DF and z.ma_loai_nh = 'KH2' and z.status=1"/>
        </field>
        <field name="ten_nh_kh2" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
        <field name="nh_kh3" viewType="Lookup" label="1" field="1" importable="95">
          <text v="Nhóm 3" e="Group 3"></text>
          <viewInfo lookupType="One" lookupId="dmnh" lookupKey="ma_loai_nh = 'KH3' and status=1" lookupCheck="ma_loai_nh = 'KH3'" lookupRef="ten_nh_kh3" lookupInfo="dmnh|ma_nh|ten_nh" importCheck="@@DF and z.ma_loai_nh = 'KH3' and z.status=1"/>
        </field>
        <field name="ten_nh_kh3" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
        <field name="rg_code" format="U" viewType="Lookup" label="1" field="1" clientDefault="true" importable="100">
          <text v="Khu vực" e="Area"></text>
          <viewInfo lookupType="One" lookupId="sysregioninfo" lookupKey="status=1" lookupCheck="1=1" lookupRef="rgname" lookupInfo="sysregioninfo|rg_code|rgname" importCheck="@@DF and z.status=1"/>
        </field>
        <field name="rgname" nextRow="false" fieldType="EX" readOnly="true" clientDefault="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
		<field name="ma_tt" viewType="Lookup" label="1" field="1" importable="105">
          <text v="Mã thanh toán" e="Payment"></text>
          <viewInfo lookupType="One" lookupId="dmtt" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_tt" lookupInfo="dmtt|ma_tt|ten_tt" importCheck="@@DF and z.status=1"/>
        </field>
        <field name="ten_tt" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="1" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>

		<field name="so_tk" label="1" field="1" nextRow="false" allowBlank="true" importable="110">
          <text v="Số tài khoản" e="Account Number"></text>
        </field>
		<field name="ma_nh" viewType="Lookup" label="1" field="1" importable="115">
          <text v="Ngân hàng" e="Bank"></text>
          <viewInfo lookupType="One" lookupId="dmnganhang" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_nh" lookupInfo="dmnganhang|ma_nh|ten_nh" importCheck="@@DF and z.status=1"/>
        </field>
        <field name="ten_nh" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
		
		<field name="gioi_han_no" label="1" field="1" dataType="N" format="" importable="120">
          <text v="Giới hạn tiền nợ" e="Debt Limit"></text>
        </field>
		 <field name="khoang_cach" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="1">
          <text v="" e=""></text>
        </field>
		<field name="ky_han_no" label="1" field="1" dataType="N" nextRow="false" format="" importable="125">
          <text v="Kỳ hạn nợ" e="Debt Maturity"></text>
        </field>
		
		<field name="ma_nvbh" viewType="Lookup" label="1" field="1" clientDefault="true" importable="130">
          <text v="Nhân viên bán hàng" e="Employee"></text>
          <viewInfo lookupType="One" lookupId="dmnvbh" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_nvbh" lookupInfo="dmnvbh|ma_nvbh|ten_nvbh" importCheck="@@DF and z.status=1" />
        </field>
        <field name="ten_nvbh" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="1" aliasName="cast('' as nvarchar(4000)) as " clientDefault="true">
          <text v="" e=""></text>
        </field>
		<field name="phong_kd" label="1" field="1" nextRow="false" dataType="N" format="" importable="135">
          <text v="Phòng kinh doanh" e="Sales Department"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" label="1" field="2" valueDefault="1" importable="-1">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>um9+HveWds1pYd7UAbrQIO1KeR+rizmtBCvrl0D+iwfJix1mqnSXjBlW04pzckryBJIjgox1O4t3S7/azTuyGSVnWfo9Z7a210SYzWr2dOb7umuYVSMKz0Qqb8pWZvyrUeheb0mvdJT6aqkDyW3PEMyjogW70legjPJe/EAnXsSPyYY2ejmT98usWb2ZFGOFQ4UqWRcY4ihUy6Ur0AAsIbT6elHIMqOeZkHOBotcCDDCdvX4b/6r/TmXMHpsE8N3mKf02wqUA9cxOgXUVVsDd/yQOGNH77QzNZ2JKe84SUEwU73NTzynug7pDELAqoy+Qpl7SwXzUYP+BmFfTom0MooBWhr2UKQhOskPv0yGc5PuELP+JdU/vETtOEDYVrB5+cK2CT3mPTI7RTg+TbYsxt9BW0WSwhbv6qKRRzLmi2sRZshDdcWISuvU+QNXDhlt91ciYm8jyMGNa9Y90W2fJSzpXRj7cxR0f4F19E2meXA8LPH0A0f69DshvCvjIN1CW1DwuYQqCoPMNCw320UKvAdNw+6k+N3yoC2U0EGU3fpTgO0HnTvYXv7IjQ9hCj5WflUlvcex8tNgbf421Yu2bWWy3L5RmP8ropMDVn1To6oHwAKGdzOmlNsvgC03eTuF2gi2RQgf8evNTrJYB24Lw8yIW6eYLL5luF/haIeg0uQrOFhnMW9QehPYcqU1PehyLwBYZ6pewzBLoBuSrGBvvIbzMRgV1qvw5PXkdSOaxT9LqKX1Ra8WKV71x3O4150y4T36jG5Ku0dnGDpOOhC6Ap7fJwgCIA9eAb1OA2AWM2A=</enc>]]>
		
    </text>
  </js>
  
  <css>
    <text>
       <![CDATA[<enc>FfBwFN+9gLduKlRWeDRzP021uD4xPQEYVmPwzDBRS/5PhoeqAEawX3yE27wyNUvm2IegseRydpx7Br76zp1PfuNsHdTysbzLX7DhQOwL6CI23JEZx6vnM73ShiYB4SnjV5k9oCmSvHJQ+q2IEyHbEzpFkK9PghwSwSZnPD0AynyHMY6/uutG8U4TUV1+9iVl</enc>]]>
    </text>
  </css>

  <script>
    
   <query>
      <text>
        <![CDATA[<enc>H4GUdC8VkeRZ+seKAqv63yc0kEiq2IGmAjclsbM7JjuncbC1jV2Eyq8uhZreNL0HK/GN+pYgX2ZQPXdMR2KJnya+zIsqor+dL7b8CzxeBfC7P+LkijqSgQEVkwp/6b4iTX6tXhyrp0y8MjDDFGqa7lSQ+0LmAJLW70jBH5IvDszxn01nnA99VTasCiN/hCO8dN/2RNoveHlPzVJ1VygerW7xzOyDdhOKFvvX8edc29U/bM1t4/mFD+iZ1OpQLfGnQiUaRfQliQvi7C4Vui0xyv5w92xJrK7pODLZD0wGF7lW6Rwl6vCptq+dyeZY+aWZtaRDxiT8djpErBptxo9VFb8U6du4ie5bGlKJ2Of+0ZweYdYlVAo6srAvqs9yuHAt</enc>]]>
      </text>
    </query>
	
   <inserting>
      <text>
        <![CDATA[<enc>ArurPA4yt4an7w7h9QL0RtCuxKD7mnKXqOjfVaoANzSITEUW8k3+psJM3GsHvzqeI4/XULCNsP0sX/mgcAihSSprg/0yM/Fy3b5vNAEqrlKUyX2fYyD5mCei7Fz6jE9er3LFPuQ82Q+a226C/guD6bQetuxSsYi/OD5nu1c1pKPfFnXbP+zq3wojnYrOiMii7IIq7aLpCFAvi90fKgd/HK8EAyFlHYUUwwmal6NH87fTHIzZCAA+KAJThRDFYtVVIdhfJ7MBxtMidhRns4XMmaUveLhHcaUXf2xyFlR1GxX7CzPjp5nJDRJn6BSrixfhKgC5vAOqIsUTiu6cRdpo0Q==</enc>]]>
      </text>
   </inserting>
	
   <aftersave>
      <text>
        <![CDATA[<enc>r07gHy2a1YsWBN5sJQoNxafW3r0h3PzEs9wzxo3Dj/lIvnI00rVkWm4e81pPULc0v1EO4L8cgvC6JBufsZP79rVnBRK/g/2f24jBmypB6mpYIKNG8NcV+07LrAefohq+Hd8TerbRjVz5jrWz6KRJO3wp11mIfZNRB3bfSVfFDOg=</enc>]]>
      </text>
   </aftersave>


   <importing>
      <text>
        <![CDATA[<enc>sxD5Swu0R4mcxEHdwcy2yi46ZbQRyi0uEDh1tGVfNVOBZJeZZHskWnswm55XGvVMtI3kJxA271ZmaBNQ7vOM1svvmG7tRC9SwsrihBxLjQw=</enc>]]>
      </text>
    </importing>
	
  </script>

  <messages>
    <message val="codeExistsNewMsg">
      <text v="Mã khách hàng đã tồn tại trong danh mục, vui lòng chọn một mã khác." e="The customer code already exists in the catalog, please choose a different code."/>
    </message>
    <message val="codeExistsEditMsg">
      <text v="Mã khách hàng đã tồn tại trong danh mục, vui lòng chọn một mã khác." e="The customer code already exists in the catalog, please choose a different code."/>
    </message>
    <message val="taxtCodeExists">
      <text v="&lt;span class='Highlight'&gt;Lưu ý:&lt;/span&gt; Mã số thuế đã tồn tại trong danh mục khách hàng" e="&lt;span class='Highlight'&gt;Warning:&lt;/span&gt; The tax code is already exists"/>
    </message>
  </messages>
</dir>