<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmkh" table="dmkh" fieldKey="ma_kh" transaction="true" tryCatch="true" dirViewType="Dialog" dirObjectType="Voucher" width="Large" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục khách hàng" e="List of customer"></title>
  <title0 v="Thêm" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120,120,120,120" >
      <fields>
        <field name="unit_id" dataType="I" hidden="true" readOnly="true" inactivate="true" label="1" field="1" importable="-1">
          <text v="" e=""></text>
        </field>
		<field name="ma_loai" viewType="Lookup" label="1" field="1" importable="1">
          <text v="Mã loại KH" e="Group 1"></text>
          <viewInfo lookupType="One" lookupId="dmloaikh" lookupKey="status = 1" lookupCheck="1=1" lookupRef="ten_loai" lookupInfo="dmloaikh|ma_loai|ten_loai" />
        </field>
        <field name="ten_loai" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
        <field name="ma_kh" format="U" label="1" field="1" viewType="AutoIncrease" allowBlank="false" fieldType="PK" importable="5">
          <text v="Mã khách hàng" e="Customer code"></text>
        </field>
        <field name="ten_kh" allowBlank="false" label="1" field="-" importWidth="250" importable="10">
          <text v="Tên khách hàng" e="Customer name"></text>
        </field>
        <field name="ten_kh2" label="1" field="-" importWidth="250" importable="15">
          <text v="Tên khác" e="Other name"></text>
        </field>
		<field name="dia_chi" label="1" field="-" importWidth="250" importable="20" allowBlank="false" >
          <text v="Địa chỉ" e="Address"></text>
        </field>
		<field name="dia_chi_kho" label="1" field="-" importWidth="250" importable="25" allowBlank="true" >
          <text v="Địa chỉ kho" e="Address Warehouse"></text>
        </field>
        <field name="ma_so_thue" format="U" fieldType="PK"  label="1" field="2"  importable="30">
          <text v="Mã số thuế &lt;a onclick='getTax(this);'&gt;(Kiểm tra)&lt;/a&gt;" e="Tax code &lt;a onclick='getTax(this);'&gt;(Test)&lt;/a&gt;"></text>
        </field>
		<field name="nguoi_lh" label="1" field="2" nextRow="false" importable="35">
          <text v="Người liên hệ" e="Contact Person"></text>
        </field>

		<field name="kh_yn" dataType="B" blank ="1" clientDefault="true" label="[100]" field="[40]" valueDefault="1" inactivate="true" importable="40">
          <text v="Khách hàng" e="Customer"></text>
        </field>
		<field name="ncc_yn" dataType="B" clientDefault="true" label="[100]" field="[40]" inactivate="true" importable="45" nextRow="false">
          <text v="Nhà cung cấp" e="Supplier"></text>
        </field>
		<field name="dl_yn" dataType="B" clientDefault="true" label="[100]" field="[40]" inactivate="true" importable="50" nextRow="false" hidden="false">
          <text v="Đại lý" e="Customer"></text>
        </field>
        <field name="nh_kh1" viewType="Lookup" label="1" field="1" importable="55">
          <text v="Nhóm 1" e="Group 1"></text>
          <viewInfo lookupType="One" lookupId="dmnh" lookupKey="ma_loai_nh = 'KH1' and status=1" lookupCheck="ma_loai_nh = 'KH1'" lookupRef="ten_nh_kh1" lookupInfo="dmnh|ma_nh|ten_nh" importCheck="@@DF and z.ma_loai_nh = 'KH1' and z.status=1"/>
        </field>
        <field name="ten_nh_kh1" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
        <field name="nh_kh2" viewType="Lookup" label="1" field="1" importable="60">
          <text v="Nhóm 2" e="Group 2"></text>
          <viewInfo lookupType="One" lookupId="dmnh" lookupKey="ma_loai_nh = 'KH2' and status=1" lookupCheck="ma_loai_nh = 'KH2'" lookupRef="ten_nh_kh2" lookupInfo="dmnh|ma_nh|ten_nh" importCheck="@@DF and z.ma_loai_nh = 'KH2' and z.status=1"/>
        </field>
        <field name="ten_nh_kh2" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
        <field name="nh_kh3" viewType="Lookup" label="1" field="1" importable="65">
          <text v="Nhóm 3" e="Group 3"></text>
          <viewInfo lookupType="One" lookupId="dmnh" lookupKey="ma_loai_nh = 'KH3' and status=1" lookupCheck="ma_loai_nh = 'KH3'" lookupRef="ten_nh_kh3" lookupInfo="dmnh|ma_nh|ten_nh" importCheck="@@DF and z.ma_loai_nh = 'KH3' and z.status=1"/>
        </field>
        <field name="ten_nh_kh3" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>


		<field name="dien_thoai" label="1" field="2" allowBlank="false" importable="70">
          <text v="Điện thoại" e="Phone"></text>
        </field>
        <field name="fax" label="1" field="2" nextRow="false" importable="75">
          <text v="Fax" e="Fax"></text>
        </field>
		<field name="e_mail" label="1" field="2" importable="80">
          <text v="Email" e="Email"></text>
        </field>
        <field name="home_page" label="1" field="2" nextRow="false" importWidth="150" importable="85">
          <text v="Trang chủ" e="Home Page"></text>
        </field>
		<field name="ghi_chu" label="1" field="-" inactivate="true" importWidth="250" importable="90">
          <text v="Ghi chú" e="Notes"></text>
        </field>
        

        <field name="rg_code" format="U" viewType="Lookup" label="1" field="1" clientDefault="true" importable="95">
          <text v="Khu vực" e="Area"></text>
          <viewInfo lookupType="One" lookupId="sysregioninfo" lookupKey="status=1" lookupCheck="1=1" lookupRef="rgname" lookupInfo="sysregioninfo|rg_code|rgname" importCheck="@@DF and z.status=1"/>
        </field>
        <field name="rgname" nextRow="false" fieldType="EX" readOnly="true" clientDefault="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
		<field name="ma_tt" viewType="Lookup" label="1" field="1" importable="100">
          <text v="Mã thanh toán" e="Payment code"></text>
          <viewInfo lookupType="One" lookupId="dmtt" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_tt" lookupInfo="dmtt|ma_tt|ten_tt" importCheck="@@DF and z.status=1"/>
        </field>
        <field name="ten_tt" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="1" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
		<field name="ma_nvbh" viewType="Lookup" label="1" field="1" clientDefault="true" importable="105">
          <text v="Nhân viên bán hàng" e="Sales agent"></text>
          <viewInfo lookupType="One" lookupId="dmnvbh" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_nvbh" lookupInfo="dmnvbh|ma_nvbh|ten_nvbh" importCheck="@@DF and z.status=1" />
        </field>
        <field name="ten_nvbh" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="1" aliasName="cast('' as nvarchar(4000)) as " clientDefault="true">
          <text v="" e=""></text>
        </field>

		<field name="phong_kd" label="1" field="1" nextRow="false" dataType="N" format="" importable="110">
          <text v="Phòng kinh doanh" e="Business Department"></text>
        </field>
		
		<field name="gioi_han_no" label="1" field="1" dataType="N" format="" importable="115">
          <text v="Giới hạn tiền nợ" e="Debt limit"></text>
        </field>
		 <field name="khoang_cach" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="1">
          <text v="" e=""></text>
        </field>
		<field name="ky_han_no" label="1" field="1" dataType="N" nextRow="false" format="" importable="125">
          <text v="Kỳ hạn nợ" e="Debt maturity"></text>
        </field>
		<field name="so_tk" label="1" field="1" nextRow="true" allowBlank="true" importable="130">
          <text v="Số tài khoản" e="Account number"></text>
        </field>
		<field name="ma_nh" viewType="Lookup" label="1" field="1" importable="135">
          <text v="Ngân hàng" e="Bank Code"></text>
          <viewInfo lookupType="One" lookupId="dmnganhang" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_nh" lookupInfo="dmnganhang|ma_nh|ten_nh" importCheck="@@DF and z.status=1"/>
        </field>
        <field name="ten_nh" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
		<field name="tinh_thanh" label="1" field="-" inactivate="true" importWidth="250" importable="140">
          <text v="Tỉnh thành" e="Province"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" label="1" field="2" valueDefault="1" importable="-1">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

<js>
    <text>
      <![CDATA[<enc>Hl+H8b/Ea6mUyxxSeVpms1RYraUx7+18d+aOx0v0RqqW7BBUmFzY937RTkOCyIN/Ohprc5tLRISCDWv9uE92MqOkTuOSKcMtGYXQcNY0MRINxwVU6+tktk4pvhyVrktTW9RGH5wFrzzWfRBBjNl8rtJsgU4glaNiZbtHA4284PjwVvL5+hTa11sm0gqJ1JdpwJItUWPC+Q+tSsCuqQEaFPiHBqkpaEbjtFkkJoIeHxhvN1z7fk5FT3bEMs/bT0dYBxTUs/tkxFi4glUEB0nlUyv/MtL/BaNUyK0575GQ3WFtleas/yVe6Ai+4RLc/tWGB+TcBljKfDssajX1aMe97zmMeljzOuaEU9hXPApbyKdoveq1SqPwGY3W9pg+YvCBh4b9usd8lgRAe2XMXSfxMsJn6QjJyZa4epsAcjoBk/YJvCk63GPtIBg/rdot12slkAGQXaXyb93O0lqp50K3m/QjzA3OA9kJ1yUD4KLhgiSJdVAgyxUifTRX5/d3SulwF9KsRTx3pfMT+kJQR7auJ6Kaht07wFGC0Q5/DBN5e3PyNAyrYvok841J1l4Jt/8GnD2docDGX0chI8PxGCcSTLZT2xvNh+FpZ11YXqw7aedFblU/GcN3G/AH0Vxcw7kYe3wSnhPKWt+j55Kl7gtb/TzvZDV54hkUsdmiIvlYakOfojDcsff4jY+S1F/ko4Y6xTiJp1c3yFxWtjyu914a2DWuMm6oo+Jm7Qj0yMe+SKd6Umr1uLfB0ZQP7wx1ZurAz0IpkVjurWSLms65OsbuKs6nGvEST38JTCJmq1z2jpYfA/g2WDvhUWoEP1uKLYB8W5wqyvXKHpn9brUoWgX12ypOGqbIDn7uUbwoQMllbm+kfLInGBv4OqYVHZAZzlYKVhJY33CihUOzrlIKoqMYxQ==</enc>]]>
		
    </text>
  </js>
   <css>
		<text>
		  <![CDATA[<enc>ejYmte7tsbAz1Giuc++EePXf3wUeQrllf6B6NsyCZcwYtM9k08bIUVkVYnBsDKaDCOZOU4pIQxi5d8DV9aOoGOcLGpy8ZtK/IB1axTIaFsxMuPIxHLwhDxb13p6PtS/mUiu3vYj6vEGd6PdV+uHxzye66drkl5m/yXTSeQWX+G+gUE76Y96ADwfW0PrLmoM7KCcIFVviS1IlCN9oJEC5WHqvq6XHk0QfIN9JK8dlycHKzC73qyQ0nx5K94Off4jb9Vb/GZlwrM4agk0l/7t1TFBdO7damOQsBNPQFDK/+A2ne/A6tygXDwmE5r2SknpP</enc>]]>
		</text>
  </css>


  <script>
  <request code="GetCustomerType">
	<text>
		<![CDATA[<enc>XCifUZf8Y2yfvq78OCSkUfvphEIBYucsL68Y489RvAw55145NvRFfKY+KNbppt/24GSIHSdAjVhBcAXUa3Z208DDXHQ5NmZr1EubBuWuAyA=</enc>]]>
	</text>
  </request>
    <query>
      <text>
        <![CDATA[<enc>iW+MwpbVYdGJDu1NI8DWbeeHIkMGYcUEJiMsNAg6qiO8/uGj5nuIH+ENTFDPmIGSc2NQPC8t0lTS64GaglPN/hbPcnxGdYWBgNY1AgYeRSLeXJgMviCgrw3m4URq0ypavYD2junWPDFlnFWIox8YXIwUS7pPA4moPHiIOiC+AuHCSPmr4tDguV9BTZdWMJCKsSDjSloQ6hvp78o9ryGapRCUMeBm1avY1U5RUwXw5/BFNYpwhtveV0JMVazTuywzSnI9seF1lLyEdd8O44FAiYVYEWb3yqBFF4kcu0Ey1zs93hHrUpuNg3vJw3zpM/wSBuDnJ8n20oxEf60vDglFAQ86U6RRKSPEDx4zFmbTosUKUCcE9uRs3Spgc9NSNAX3</enc>]]>
      </text>
    </query>
    <inserting>
      <text>
        <![CDATA[<enc>aTcATOlFrrXqAjRK8p/gr+37bbbjPMPTds06YH7KESYhW/qdZvd78nPQH4Wmoh22l1WK7XTC35PABhl5zr6ug/DdG8xEdjvN49/KBTz5/mFdz4xgFl0qs22tPaGBf9HKtHJz5cKQhLiVo06OIMBWJlNIvMA8Sl+MR6UM7RgK6KD60JG7dDFoh1V1ieQz3afHT6sUgh3usyEQYwfCoxJ3iVrNxOFtEhQpX/am8P5CpTXoXYMQI5aSKZemzrKeZ8fTD0pISoTRAsX0GegVrhgVcy+QENoxzhWX9zWa0oQb4zgs4+v3hqYczJPbOIDhiYxhGrQMGRuen+tMdY3tEagcpQ==</enc>]]>
      </text>
    </inserting>
    <aftersave>
      <text>
        <![CDATA[<enc>++V3V+E3NWH5wDFlTZgrSGbjNHJkVDS0vmsm1GR080eRHXmaYAHQCJloa1DZ2hAHX7Ul/SMrxMMA01pu0hKJuqh9ZZF8e5TF2ZR2GgJ/z+ukFomP5R6dNCYdzgWq8JWXAPilrl4x6jMYnwD1yXajgb4uRJRW3SuHjGaXxQm8QWEQV5UJ7DiV8FJhOPdV9FLF</enc>]]>
      </text>
    </aftersave>


    <importing>
      <text>
        <![CDATA[<enc>sxD5Swu0R4mcxEHdwcy2yi46ZbQRyi0uEDh1tGVfNVOBZJeZZHskWnswm55XGvVMtI3kJxA271ZmaBNQ7vOM1svvmG7tRC9SwsrihBxLjQw=</enc>]]>
      </text>

    </importing>
  </script>

  <messages>
    <message val="codeExistsNewMsg">
      <text v="Mã khách hàng đã tồn tại trong danh mục" e="Customer Code already exists."/>
    </message>
    <message val="codeExistsEditMsg">
      <text v="Mã khách hàng đã tồn tại trong danh mục" e="Customer Code already exists."/>
    </message>
    <message val="taxtCodeExists">
      <text v="&lt;span class='Highlight'&gt;Lưu ý:&lt;/span&gt; Mã số thuế đã tồn tại trong danh mục khách hàng" e="&lt;span class='Highlight'&gt;Warning:&lt;/span&gt; The tax code is already exists"/>
    </message>
  </messages>
</dir>