<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>

<dir id="dmkm" table="dmkm" fieldKey="ma_km" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Khuyến Mãi" e="Service List"></title>
  <title0 v="Thêm mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
        <field name="ma_km" format="U" label="1" field="2" allowBlank="false" fieldType="PK" >
          <text v="Mã Khuyến Mãi" e="Service Code"></text>
        </field>
        <field name="ten_km" label="1" field="2" allowBlank="false" >
          <text v="Tên Khuyến Mãi" e="Description"></text>
        </field>
        <field name="ten_km2" label="1" field="2">
          <text v="Tên khác" e="Other name"></text>
        </field>
		<field name="thu_tu" label="1" field="2" dataType="N">
          <text v="Thứ tự" e="Position"></text>
        </field>
		<field name="noi_dung" label="1" field="2" allowBlank="false" >
          <text v="Nội dung khuyến mãi" e="Description"></text>
        </field>
		<field name="noi_dung2" label="1" field="2" allowBlank="false" >
          <text v="Nội dung khác" e="Description other"></text>
        </field>
       <!-- <field name="ma_clvt" viewType="Lookup" label="1" field="1" clientDefault="true" importable="35"> -->
          <!-- <text v="Danh mục chính" e="Item Type"></text> -->
          <!-- <viewInfo lookupType="One" lookupId="dmclvt" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_clvt" lookupInfo="dmclvt|ma_clvt|ten_clvt" importCheck="@@DF and z.status=1"/> -->
        <!-- </field> -->
        <!-- <field name="ten_clvt" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as " clientDefault="true"> -->
          <!-- <text v="" e=""></text> -->
        <!-- </field> -->
  
        <field name="status" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
	<form tabPageIndex="1" gravity="MiddleRight" height="300" columns="120,120,120,120,120,120,120,120" >
		<text v="Chi tiết khuyến mãi" e="Promotion Details"></text>
		<fields>
			<field name="dmdkm" allowBlank="true" label="" field="-" viewType="Grid">
			  <text v="Chi tiết khuyến mãi" e="Promotion Details"></text>
			</field>
		</fields>
	</form>
	<form tabPageIndex="2" gravity="MiddleRight" height="300" columns="120,120,120,120,120,120,120,120" >
		<text v="Danh sách sản phẩm" e="Promotion Details"></text>
		<fields>
			<field name="dmkmvt" allowBlank="true" label="" field="-" viewType="Grid">
			  <text v="Danh sách sản phẩm" e="List Product"></text>
			</field>
		</fields>
	</form>
  </forms>
  <grids>
		<grid id="dmdkm" table="dmdkm" fieldKey="ma_km" order="line" allowFilter="true" readOnly="false" allowOrder="true">
		  <fields>
			<!-- <field name="ma_km" fieldType="PK" foreignField="ma_km" copy="false" hidden="false"> -->
			  <!-- <text v="Mã khuyến mãi" e="Promotion Code"></text> -->
			<!-- </field>	 -->
			<field name="loai_km" allowBlank="true" viewType="Lookup" width="140" readOnly="false">
				<text v="Loại khuyến mãi" e="Category Promotion Code"></text>
				<viewInfo lookupType="One" lookupId="dmloaikm" lookupKey="status = 1" lookupCheck="1=1" lookupInfo="dmloaikm|ma_loaikm|ten_loaikm" />
			</field>
			<field name="option_km" allowBlank="true" viewType="Lookup" width="150" readOnly="false">
				<text v="Lựa chọn" e="Option"></text>
				<viewInfo lookupType="One" lookupId="vdmvtvoucher" lookupKey="status = 1 and ma_loaikm = #[loai_km]#" lookupCheck="1=1" aliasName="b" join=""/>
			</field>				
			<field name="thu_tu" width="100" dataType="N" inactivate="true" readOnly="false">
			  <text v="Thứ tự" e="Order"></text>
			</field>		
		  </fields>
      <buttons>
		<button id="add">
          <text v="$AddToolbar" e="$AddToolbar"></text>
        </button>
		<button id="delete">
          <text v="$DeleteToolbar" e="$DeleteToolbar"></text>
        </button>
      </buttons>
		  <script>
			<query>
			  <text>
				<![CDATA[<enc>9Bejl7aT07JLWbYZrPrPozADvSS2RzNRfN6noepk86/g+STU5zpe+yNPDvzVJ58bKHHTzt56D7sqvXST5GDNzT7xQxuAkIKAs0/gWVvhiNgtmsrW6vIFw65qmLfIcg7uTt19dSuAbgmELObKlTvrB6O/YN6zu5f9+4OyWspRpSNBjVJeomsJTdEjrVuh+mo8xi0iLFLJ9MpQFHOBCuDYZA==</enc>]]>
			  </text>
			</query>
		  </script>
		</grid>
		<grid id="dmkmvt" table="dmkmvt" fieldKey="ma_km, ma_vt" order="line" allowFilter="true" readOnly="false" allowOrder="true">
		  <fields>
			<!-- <field name="ma_km" fieldType="PK" foreignField="ma_km" copy="false" hidden="true"> -->
			  <!-- <text v="Mã khuyến mãi" e="Promotion Code"></text> -->
			<!-- </field>	 -->
			<field name="ma_vt" allowBlank="true" viewType="Lookup" width="150" readOnly="false">
				<text v="Mã vật tư" e="Product Code"></text>
				<viewInfo lookupType="One" lookupId="dmvt" lookupKey="status = 1 and ma_vt not in (select ma_vt from dmkmvt)" lookupCheck="1=1" aliasName="b" join="" />
			</field>			
			<field name="thu_tu" width="100" dataType="N" inactivate="true" readOnly="false">
			  <text v="Thứ tự" e="Order"></text>
			</field>		
		  </fields>
      <buttons>
		<button id="add">
          <text v="$AddToolbar" e="$AddToolbar"></text>
        </button>
		<button id="delete">
          <text v="$DeleteToolbar" e="$DeleteToolbar"></text>
        </button>
      </buttons>
		  <script>
			<query>
			  <text>
				<![CDATA[<enc>kFYH+J/sLixcXLC0LJl2E0wvKBNoSL/nCYNu1tG9BbNt2lgzqwMaldwtpCahxQa6Xoy8EFWruJt7L3Po2zKV/hR6ScTWQwFnwvPz/Z4RBSn2+/etie39HCfrmzcGkEgbz+Ol9HQAafz53AosI2qzAq7eTgb4qd7HCvE2fEncffWaG7tlM+ydtWDA/QtGjixC4nZkyXfah2UOwtl0pw+PBw==</enc>]]>
			  </text>
			</query>
		  </script>
		</grid>
	</grids>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>A41+K2Hf427iJbH328HBMto/U99gsLfGRTjKQ7lLQxDp51PZgWtCO8goV8ROCyc0TQ8X0WA6zXJ8pXQ3usunfbib0mic4Y5IhyHC+PGIiflNV5zBEftzaouQ1uPo2qx/xGEkH1FM5A5RR6f2IJkWO4Nz1QUBX3787t7af8lX7qxBjFZAhCuHF4BRN7Yl8sYBEYcr3VkJ2pp0HgtVM4EC2g==</enc>]]>
    </text>
  </js>
  
  <script>
	<beforesave>
      <text>
        <![CDATA[<enc>nXKW/t/LBLZFNRtPr/M9R5XuOZC2sMp2aplwrOGqjzDt0/RV4362+6kRPvhsM9/JqJoFbuu9Pz+LUEaZxBYHNZcP/x54AaqPh3ephhXX9/TSySQYs/njXzf/jfFuXDYH5B7z13Jyieh62mziQ/fHVUi0+y8tqcuRMkpQpcgTAWgFl1Ejm0ICqUh1naZChP8WUFj/LjFOkaiSpnZVvusr2g==</enc>]]>
      </text>
    </beforesave>
	<aftersave>
      <text>
        <![CDATA[<enc>RToRmVh9DshVasMAHnbmDKbQeUI1IzwMZ+UMCGj0S2V2oECbIZbnwZQzb9hcRccxwpj/ttWAt2tUqV/KHM+kNIQTxvxmTqfyu1gn4LprYAO0Sjkb4Ps/G2Lp4XzzE+dfvpwYWPiMMDJGMbOdVo/+EJnk3mqub5bpD+DPa5dOlinHTOwGCk7k3x9pqzOsrWeC1hTjIc+luMzdGKXWPrfZv8Zjs5nlGSlANHmh2wVhCPVfsZSW2h5HOYFKUiU7i1eJ5N/9/wvoGLW/8cf3oOrCITG0lLPLyVIwaRpl+ruFRqQ=</enc>]]>
      </text>
    </aftersave>
  </script>

  <messages>
    <message val="codeExistsNewMsg">
      <text v="Mã dịch vụ đã có hoặc lồng nhau trong danh mục dịch vụ." e="The Service is invalid or already exists."/>
    </message>
    <message val="codeExistsEditMsg">
      <text v="Mã dịch vụ đã có hoặc lồng nhau trong danh mục dịch vụ." e="The Service is invalid or already exists."/>
    </message>
	<message val="DuplicateInv">
      <text v="Mã vật tư không được trùng" e="Duplicate Invoice Number"/>
    </message>
  </messages>

</dir>