<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>

<dir id="dmlcuochop" table="dmlcuochop" fieldKey="ma_lcuochop" transaction="true" tryCatch="true" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục loại cuộc họp" e="List of meeting type"></title>
  <title0 v="Thêm mới - loại cuộc họp" e="New - meeting type"></title0>
  <title1 v="Sửa - loại cuộc họp" e="Edit - meeting type"></title1>

  <forms>
	<form gravity="TopLeft" columns="120,120,120,120,120" >
		<fields>
			<field name="unit_id" dataType="I" hidden="true" readOnly="true" inactivate="true" label="1" field="1" importable="-1">
			  <text v="" e=""></text>
			</field>
			<field name="ma_lcuochop" label="[120]" field="[120]" allowBlank="false" format="U" disabled="false" fieldType="PK" importable="5" >
				<text v="Mã loại cuộc họp" e="Meeting Type Code"></text>
			</field>
			<field name="ten_lcuochop" label="[120]" field="-" allowBlank="false" disabled="false" importable="10">
			  <text v="Tên loại cuộc họp" e="Meeting Type Name"></text>
			</field>
			<field name="ten_lcuochop2" label="[120]" field="-" allowBlank="true" disabled="false" importable="15">
			  <text v="Tên tiếng anh" e="English Name"></text>
			</field>
			<field name="status" viewType="Combobox" inactivate="false" label="1" field="2" valueDefault="1" nextRow="true" importable="-1" >
			  <text v="Trạng thái" e="Status"></text>
			  <viewInfo>
				<options query="select ma_tt, ten_tt%l from dmttsd where status = 1 ">
				</options>
			  </viewInfo>
			</field>
      </fields>
    </form>
</forms>

&DefaultButton;

<js>
    <text>
  <![CDATA[<enc>b+8Kyakj9NOjSKKt0VV9dRppPM6Mg5MCJ1/01SAFxpEe38nrkR0Lvejph4tAOhzRmjuyJrhIlPJ+xHrrsOOoUK18FOzA96CJxKGM+4Ka+eZ4PZHaWR2unGB8INDhsLCjkU2W9U9OpNt36HDBLAeNt4D9Ux5kI2+0VOHOV0q8odKQEaPazcMxdBgi/WGxqGBM/CRQYkSsY/gleJYOLvQwvjUO23theGKzMIcO//Knk8DAtyl9pPYocj1RXzow12LApRvVURThpQqouRABeb5Kt/6H4m+C64HgTpxOxA4ARQtzaLaKSh0E4RL5YzIskDqmIRb3zggO4srlyDKpcsRK2g==</enc>]]>
    </text>
  </js>
	<css>
		<text>
			  <![CDATA[<enc>s5XWMSrs6w5R2zI1vM6n22Hme6FdQrV5BjHYDzhI7KZ6acAuDlcjIYeinVmpnpg1LAbR2N6XQXWH/DOXyurQQxFVfgL1JJehadwfyP5wvA+i7Z4u8gGa2SilTT3OAU5WQD72sYSYwoGfbUNZSg6WYE4VEg32BcHkN+bPukS+o4Gp+G1ESQJbJ5YMSQP2hjhu</enc>]]>
		</text>
	</css>
	<script>
		<query>
		  <text>
			<![CDATA[<enc>GJgBVkOd9xy3In+SUACpOOdXdTQbLjDNG098RVYG+mqJrACGNi8MwNsRrtmQkuMIYyR65+M+8FdE2nQkBtdUjjGtkBSGsDqbRbA3vrYN89ZzUnQVJ+W1/9AMkiZ8xTjPYAdSbE6TNHswawXCA3Q7ZKpywgArBHY6CKMo02cq6Ek=</enc>]]>
		  </text>
		</query>
		<updated>
		  <text>
			<![CDATA[<enc>sxD5Swu0R4mcxEHdwcy2ynVkJ6IiRfsuHiDzDrC78ELIJg2k4xX5PxEITwgSuDtWSiTOU3sqnIo/Bv0T8e877uKHW6bIEuTFdpbPdQB+xElll2tzxh9iUOpwbot+jXTZNKo5+n5Fy+aXD8VrO81PEw==</enc>]]>
		  </text>
		</updated>
		<inserting>
		  <text>
			<![CDATA[<enc>/T/6v4fr7JtuEWROY5bEog4q37AdyKX5y50iwuf8o+kQ/cMLdjO5yBgIja/EXDIb67gjtJCgsvsoKVHnH40ASfHmT/5Pyqyz9fEF+eXazaeFq1QdO25I17j8uqKw4sm7PDDzWS+uYkqIWo1FmMQqY1vwSihUQwhC3DMwYBlMdqW/7I05kvZGgi3lyKQDrJ1gd1u3eDHWrXNvOq+fBosahfSLln2pO8chassI1khVi2Brg84FNLLprzwizWkmE7Kk</enc>]]>
		  </text>
		</inserting>
		<importing>
			<text>
			<![CDATA[<enc>sxD5Swu0R4mcxEHdwcy2yi46ZbQRyi0uEDh1tGVfNVOBZJeZZHskWnswm55XGvVMZq7vIrj1gngY5x8IJuKO1pkyFlxS8pifsEwHrhrpEjg=</enc>]]>
			</text>
		</importing>
	</script>
	<messages>
		<message val="codeExistsNewMsg">
		  <text v="Mã văn bản lưu hành đã tồn tại trong danh mục." e="The circulation document code already exists in the list."/>
		</message>
	</messages>
</dir>
