<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmlinegoi" table="dmlinegoi" fieldKey="ma_line" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục line gọi" e="List of contract types"></title>
  <title0 v="Thêm mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120,120" >
      <fields>
        <field name="ma_line" format="U" label="1" field="1" allowBlank="false" fieldType="PK" importable="1">
          <text v="Mã line" e="Type code"></text>
        </field>
        <field name="ten_line" label="1" field="-" allowBlank="false" fieldType="PK" importable="2" >
          <text v="Tên line" e="Type name"></text>
        </field>
        <field name="ten_line2" label="1" field="-" importable="3">
          <text v="Tên khác" e="Other name"></text>
        </field>

        <field name="status" viewType="Combobox" inactivate="true" valueDefault="1" label="1" field="2" importable="-1" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>1PFOGp66gVgaSTPirrPUVeYzrXstur9UVisKTJQ3FkOfYXzCVa9boswHn3mKZaujZKNrQATLTm/NsnrUvAf6JiPOu6ecH9KBclZdxluzYlT+7OBVku1ZhsNQv1mpSQh3kiNzZh3LCXhbo/bjkw/61e5jS133099m8CsHqYJ966IMSD2lb6p1RVktYCmcVXGqtU2zYvUOlVF/xOm0cum5eXJrp3GkxDDFq7HCFL4aQkTRtZjaRRqmVihCgFu+7vL7SqteePx3D5cfRhiaT9eYfIwUsFOHPJ7Q7sf9GrKVUWzTzOFAJcOOY6Ax8QnaRrHwD7CY7kvDxNHZPymE5A7Y+8xxqUWd1DWyL8BU9l1jsDE=</enc>]]>
    </text>
  </js>
	<css>
		<text>
			<![CDATA[<enc>MG8oGqDWrLRccGk50hSKnbb4FUv7K7xz/NxcnnWxsiTIldbiqJcsFenqNTUdtCe4PMQQDYim0LWAjTkdWu7YaN1Ji+oTe4Vk1gf2+C3Dd7WnLjHWumCAmr1aYdm6Nm4i</enc>]]>
		</text>
	</css>
  <script>
   <importing>
      <text>
        <![CDATA[<enc>OJTGoSIy8QCZeoyJMmdxeUd7FCB/9CUKI3D1cWkrCmCczF6fKYxFNFvElWRVu3fA</enc>]]>
      </text>
    </importing>
    <declare>
      <text>
        <![CDATA[<enc>hxQPm/hYhpvPifcenBxj7nfT+X4T8oXvYmZx4Kpwn3fRRVZY+foYIow2vt1OHdzq0lG6PkDpvnlKR1ei3AR28UkawCxswedTww8YMZ/ax/1/BVJZ6K0wvLOosliedaWZAZZQJt+bLBksKe9RWXks/lvGUxSX00WHdpeXsltu63DiOYIsJfQeOVnnqr6WNvqmUTBa+W7k519UjE/89vWen/AIFgbTmiiG0Wyi2VGm9gQ=</enc>]]>
      </text>
    </declare>
  </script>
</dir>