<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmloaibencang" table="dmloaibencang" fieldKey="ma_loai" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục loại bến cảng" e="List of Port Types"></title>
  <title0 v="Thêm mới" e="Create New"></title0>
  <title1 v="Sửa" e="Edit"></title1>


  <forms>
    <form gravity="TopLeft" columns="120,120,120">
      <fields>
        <field name="ma_loai" format="U" label="1" field="1" allowBlank="false" fieldType="PK" importable="1" >
          <text v="Mã loại" e="Type Code"></text>
        </field>
        <field name="ten_loai" label="1" field="-" allowBlank="false" importable="5" >
          <text v="Tên loại" e="Type Name"></text>
        </field>
		<field name="ten_loai2" label="1" field="-" importable="10" >
          <text v="Tên khác" e="Other Name"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" valueDefault="1" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>pX79fY+BQf9bV+YuDv83hJMo/wxnw3GwASqN3hT2Q83CK/+x7aU3ijs2hPTtbdRN3E9UuDgS8AghuGmky4t6isMPTf1zNLisPh8nanVk9lOydOb/Bl9zBSKv1z//tAbMbI99EFGEoUPuZKwhk8+3ML7iwrHHknZmgDsOfAl4c7vKesq/nCS8bdFMKbLoQXZsSceWTh4pR7bMK/IZxIS3W5qoJ/CZBZyAlp1uK7UKDlcSiPwdX7a2uymFG/cXg9/ctJPgxNr2LLdARQQMT5r2b2zoEmpb4ZHbS45XHUqyMpY/kYJyHkuNH61CNOhzr8O8YBkP9ebXg8SIAx1ndfIt+8beh0m98sgXkcl5h99ev3Q=</enc>]]>
    </text>
  </js>
  
  <css>
	<text>
	  <![CDATA[<enc>/T0x+X5J8VnLtXSs8xERB1iizBHxQmUovXeEmWW/qu+LxnTFUzjqTAwGomB6HL6a1vSva3ktOivUq/OkdeJXUA0fsA0vRlkYL9GrfjSYL8/gFq5hhLteFw2tuM1JZ+c8HiJcvOGd/5SfJErsF7nvxg==</enc>]]>
	</text>
  </css>
  
  <script>
	<importing>
      <text>
        <![CDATA[<enc>PDeYaSq5D3THjzUfjXLnuOov+zRPCu/HsQ7cYLJ9+NUbtW4WBDcym9s/zoBHUkNI</enc>]]>
      </text>
    </importing>
  </script>
  
  <messages>
	<message val="codeExistsNewMsg">
		<text v="Mã loại bến cảng đã tồn tại trong danh mục, vui lòng chọn một mã khác." e="The port type code already exists in the catalog, please choose a different code."/>
	</message>
	<message val="codeExistsEditMsg">
		<text v="Mã loại bến cảng đã tồn tại trong danh mục, vui lòng chọn một mã khác." e="The port type code already exists in the catalog, please choose a different code."/>
	</message>
  </messages>

</dir>