<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmloaidvt" table="dmloaidvt" fieldKey="ma_loai" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục đơn vị tính" e="Units of Measure"></title>
  <title0 v="Mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>
  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
        <field name="ma_loai" format="U" label="1" field="1" allowBlank="false" fieldType="PK" >
          <text v="Mã loại ĐVT" e="UOM"></text>
        </field>
        <field name="ten_loai" label="1" field="2" allowBlank="false" fieldType="PK" >
          <text v="Tên loại ĐVT" e="Description"></text>
        </field>
        <field name="ten_loai2" label="1" field="2" allowBlank="true">
          <text v="Tên khác" e="Other name"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>q6iCSLCowTW5wC/k2hMF+0kaOYFC3sgtfE1W9SXdZKZtr2lqHJZxn3zyUn+Ks7Fjsg8QXodJlavqkFOmWp0fALIFQH6PsiZqWo/igi1mYTXvpVvBpFpTpYg4qN+GIX/WcKCDx1TFRl7Z2l7FQDpP/Fhi2QZwDz/ucaLvMiGZiuVI4OhI+Cze11SAiq3i/9o1</enc>]]>
    </text>
  </js>

  <script>
    <declare>
      <text>
        <![CDATA[<enc>hxQPm/hYhpvPifcenBxj7nfT+X4T8oXvYmZx4Kpwn3fRRVZY+foYIow2vt1OHdzq0lG6PkDpvnlKR1ei3AR28UkawCxswedTww8YMZ/ax/1/BVJZ6K0wvLOosliedaWZAZZQJt+bLBksKe9RWXks/nHp7x4Wss5jSrhqunFqW23r6/k3hW4LnQLJBtopNr0rVvrA+7UXoq4dX9RNjE6/WoY5cty0p7O0tvRnJgVyc60PcSzhh61dehUWouLowqhb</enc>]]>
      </text>
    </declare>
  </script>

</dir>