<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmloailuong" table="dmloailuong" fieldKey="ma_luong" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục loại lương" e="List of Salary types"></title>
  <title0 v="Thêm mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120,120" >
      <fields>
        <field name="ma_luong" format="U" label="1" field="1" allowBlank="false" fieldType="PK" >
          <text v="Mã lương" e="Salary code"></text>
        </field>
        <field name="ten_luong" label="1" field="2" allowBlank="false" fieldType="PK" >
          <text v="Loại lương" e="Salary type "></text>
        </field>
        <field name="ten_luong2" label="1" field="2">
          <text v="Loại lương 2" e="Salary type 2"></text>
        </field> 
        <field name="status" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>lEVRYe7GzDZqWzWfpmfh9XML7FL0th3/14dsD2Mxc083fr78pXHdhL4DAn2JSxYhDazjXoFRVOtAmkx/FWZ2IlWyvYBhIK1IEVDuW4M5xwkgFJDBsWB7dt4iuPf2p1UYs8e5e3B8kaqjTeA2JIwpdFNZkqDdYu5D3X1kQXFnlGtgmVLDSL0nwGHd7uGtkLJf</enc>]]>
    </text>
  </js>

  <script>
    <declare>
      <text>
        <![CDATA[<enc>hxQPm/hYhpvPifcenBxj7nfT+X4T8oXvYmZx4Kpwn3fRRVZY+foYIow2vt1OHdzq0lG6PkDpvnlKR1ei3AR28UkawCxswedTww8YMZ/ax/1/BVJZ6K0wvLOosliedaWZAZZQJt+bLBksKe9RWXks/lNZq8fPZ3XkwP092izDisSJa2SwXaUv9m7qBQtw/rXoOzN2lJNguk/af9yDz7j/vfJ9Zi2P+ptrAW8dfEJBb9+7SoFuKV+L/uMCjsC2JAX3</enc>]]>
      </text>
    </declare>
  </script>

</dir>