<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>

<dir id="dmloainganhnghe" table="dmloainganhnghe" fieldKey="ma_loai" transaction="true" tryCatch="true" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục loại ngành nghề" e="Occupation Category List"></title>
  <title0 v="Thêm mới - loại ngành nghề" e="New - Occupation Category"></title0>
  <title1 v="Sửa - loại ngành nghề" e="Edit - Occupation Category"></title1>

  <forms>
	<form gravity="TopLeft" columns="120,120,120,120,120" >
		<fields>
			<field name="unit_id" dataType="I" hidden="true" readOnly="true" inactivate="true" label="1" field="1" importable="-1">
			  <text v="" e=""></text>
			</field>
			<field name="ma_loai" label="1" field="1" allowBlank="false" format="U" disabled="false" fieldType="PK" importable="5" >
				<text v="Mã loại ngành nghề" e="Occupation Category Code"></text>
			</field>
			<field name="ten_loai" label="1" field="-" allowBlank="false" disabled="false" importable="10">
			  <text v="Tên loại ngành nghề" e="Occupation Category Name"></text>
			</field>
			<field name="ten_loai2" label="1" field="-" allowBlank="true" disabled="false" importable="15">
			  <text v="Tên tiếng anh" e="English Name"></text>
			</field>
			<field name="status" viewType="Combobox" inactivate="false" label="1" field="2" valueDefault="1" nextRow="true" importable="-1" >
			  <text v="Trạng thái" e="Status"></text>
			  <viewInfo>
				<options query="select ma_tt, ten_tt%l from dmttsd where status = 1 ">
				</options>
			  </viewInfo>
			</field>
      </fields>
    </form>
</forms>

&DefaultButton;

<js>
    <text>
  <![CDATA[<enc>DTVq5U0KToXNvouqCe9K+oFBmToZIncswcMex2mmn0MaGrf6srkJJXHVHACx6ebR/keWKktgK2YH5qSy0owwRBeZdeewRMEmOxcf1JMHrXjGSbGVA0ykrQHDBuxUtHzm+OgfMEBKJWT/vDh2G0rCChK9KvJLr8LsOaupgA+f7UhtqYEgXVV3omZJLge80eedfl/Al0opPY7ksgNaEJIemay/u+O+WUBAay0v3kbME3iuDh7k6FQ3j27Hl87KxPNqrAq2VQXDT5bXJ0qEH2184+eM14jp/uHIRZZyV8uVvBB95x02AeGtF3XAvUGWTkGjuHLGoQisGoZ/2wubwt11Nw==</enc>]]>
    </text>
  </js>
	<css>
		<text>
			  <![CDATA[<enc>GuCkAIqWYq6JWBQ7bTXsyNfZsS6nNOfnMC3XKRDsg/mrmLovy64F9UXbW3bmASX7Qer9wALSqDOWVwp9l7FtOspCR7VislP3N+MlAdUR2+fvWfaU6p14GJ0qUcYgXERWzb8J8neMu++gFdiZ57Ki0BGBXa1enIZKTqZa1Nfetw04SaEWwpQ9T8wpbRILz/jX</enc>]]>
		</text>
	</css>
	<script>
		<query>
		  <text>
			<![CDATA[<enc>GJgBVkOd9xy3In+SUACpOOdXdTQbLjDNG098RVYG+mqJrACGNi8MwNsRrtmQkuMIYyR65+M+8FdE2nQkBtdUjjGtkBSGsDqbRbA3vrYN89ZzUnQVJ+W1/9AMkiZ8xTjPYAdSbE6TNHswawXCA3Q7ZKpywgArBHY6CKMo02cq6Ek=</enc>]]>
		  </text>
		</query>
		<updated>
		  <text>
			<![CDATA[<enc>sxD5Swu0R4mcxEHdwcy2ynVkJ6IiRfsuHiDzDrC78ELIJg2k4xX5PxEITwgSuDtWSiTOU3sqnIo/Bv0T8e877uKHW6bIEuTFdpbPdQB+xElll2tzxh9iUOpwbot+jXTZNKo5+n5Fy+aXD8VrO81PEw==</enc>]]>
		  </text>
		</updated>
		<inserting>
		  <text>
			<![CDATA[<enc>/T/6v4fr7JtuEWROY5bEog4q37AdyKX5y50iwuf8o+kQ/cMLdjO5yBgIja/EXDIb67gjtJCgsvsoKVHnH40ASfHmT/5Pyqyz9fEF+eXazaeFq1QdO25I17j8uqKw4sm7PDDzWS+uYkqIWo1FmMQqY1vwSihUQwhC3DMwYBlMdqW/7I05kvZGgi3lyKQDrJ1gd1u3eDHWrXNvOq+fBosahfSLln2pO8chassI1khVi2Brg84FNLLprzwizWkmE7Kk</enc>]]>
		  </text>
		</inserting>
		<importing>
			<text>
			<![CDATA[<enc>sxD5Swu0R4mcxEHdwcy2yi46ZbQRyi0uEDh1tGVfNVOBZJeZZHskWnswm55XGvVMZq7vIrj1gngY5x8IJuKO1pkyFlxS8pifsEwHrhrpEjg=</enc>]]>
			</text>
		</importing>
	</script>
	<messages>
		<message val="codeExistsNewMsg">
		  <text v="Mã loại ngành nghề đã tồn tại trong danh mục." e="Industry/Occupation Categories code already exists."/>
		</message>
	</messages>
</dir>
