<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmloaibh" table="dmloaibh" fieldKey="ma_loaibh" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục loại bảo hành" e="Warranty of List"></title>
  <title0 v="Mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
	    <field name="unit_id" dataType="I" hidden="true" readOnly="true" inactivate="true" label="1" field="1" importable="-1">
          <text v="" e=""></text>
        </field>
        <field name="ma_loaibh" format="U" label="1" field="1" allowBlank="false" fieldType="PK" >
          <text v="Mã loại bảo hành" e="Warranty type code"></text>
        </field>
         <field name="ten_loaibh" label="1" field="-" allowBlank="false" fieldType="PK" >
          <text v="Tên loại bảo hành" e="Warranty type name"></text>
        </field>
        <field name="ten_loaibh2" label="1" field="-" allowBlank="true">
          <text v="Tên khác" e="Other name"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>TYNjJ4qGYlwxRKBOyaAHHeMEXhUGpcCBNzlgwOT1dJMJqhpFonNq0KV8e57q341rDc65VQUkze4rm1IWpJQ7el1PsAGvW8CyhXSdWyAq0HW3AGwzP60GT9uCaW19YSZmyLFZ7lDg+SpOwv0OW+it57kKK0QFtys81TsfGnIUMXpGrp3vGGNvVd+ltIXBjMG05C/590hHkuieBEuoLJnnSJSQSebgXKo8VUtk6J+8ksO1JppI5nH9v79eQ32fzf94AGQtw/m5uq2yNTf2Z36Gap4J4OEnGiWIeYcnLaHNIRSmozxW3TUGL5Xv+iQXaTyvL5lRPcXIykJpwNhFnL5akBMXZPYg65+pjkd1suvUxZmZDy3npgf9CtjTW0nyzzGmEdn3x1rRbbrW6lkOKkxtEHT2TjCJT9V0uZhmuYsxe78=</enc>]]>
    </text>
  </js>
  <css>
		<text>
		  <![CDATA[<enc>YkWQBTDGylCtyJwcHZMp4kHLaONbdUrMufRzgaQUdjP6Wnf4+4ysGWPq+3Lk6BEvRUsLG8tpWzc2YzRVPUNC2zIo6mjwaJs/HutcqPHFLozeT/lrxhyGJ3sK1jySYyUVh6rzT/rI1jDO+cCVsOnaFw==</enc>]]>
		</text>
  </css>

  <script>
	<request code="request_code_unit">
		<text> <![CDATA[<enc>EwFm1q1VegfrKqO0ssBlVIo82cYM4kuf21CDzI6EgpbjCvrHLOVXm1Y9I4Bzv/TySXe6ZZZrMpczzKBet1vpJnfYv4jri/hDQJoaxnD/r+VuiUXXKhIpKfB8l7uPOxZAVYleFjNDNTrlSDatzfoh/8jVrGakSYEG3pN/P89isQlHkcJMMlbtugqW6IB9lFp8jJZ+j9zw2PDClrBCvb8EufnfO3bMEV1DIVFyzjA43lwX/I55QvvwNhWDA2/VDnrLmC8XoP9Bro5MnBLwqduOtOxiNJbZYrDdY/Dx0SJlt4J+e+zTKH75zjPf0nEHF2jP</enc>]]> </text>
	</request>
	<inserting>
      <text>
        <![CDATA[<enc>/T/6v4fr7JtuEWROY5bEopFO1HCnIjtZjFzzDG3F9/vEkIfRrRIYFlNT+1c2A+G4DGK3P1V1ru+z1kGXJXjR1VzP1TAM3KziUQ39S5UPAFO5TtFkd+A7rjU9Cj84+ron+NnAUl09CZS+jY4xst+ifUx/y0L2N86LSRXXWB0b2jLk9z1JyBTjpFwFo33O8/V92Jll9ZnIKloIczVnEYCl2/5Q4n5X9mE3/5atjZjvFut8hbyHb/wqOO6O7YgIZzpT</enc>]]>
      </text>
    </inserting>
    <declare>
      <text>
        <![CDATA[<enc>D8ieS6Kn3Xfstmj4kvf1jQHDsxpfg82tO/Gjbnb7xTBNs9QJlr8wGVYToTt4QoBC696W1as8Nd8nArcZaNtIH7XBI/vjtd2ZzomqzCd2kcWUfXA2lxHZXACRqDyGhMh6XPRUK2b7qzoW9TxBb0BFjdOsaMNuj8oyz7fs8OGk4SfBHp7cvCyOvH109Wa1ZNZorJ/1IDSWpiT3UB68yL8VrT1PIpvcC907W8mdSE0ecmgNmgBAFn09os03ItBWWoXK</enc>]]>
      </text>
    </declare>
  </script>
  <messages>
    <message val="codeExistsNewMsg">
      <text v="Mã loại bảo hành đã tồn tại." e="Warranty code already exists."/>
    </message>
    <message val="codeExistsEditMsg">
      <text v="Mã loại bảo hành đã tồn tại." e="Warranty code already exists."/>
    </message>
  </messages>
</dir>