<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmloaichiphi" table="dmloaichiphi" fieldKey="ma_loai" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục loại chi phí" e="List of expense type"></title>
  <title0 v="Thêm mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
        <field name="ma_loai" format="U" label="1" field="1" allowBlank="false" fieldType="PK" >
          <text v="Mã loại" e="Type code"></text>
        </field>
        <field name="ten_loai" label="1" field="-" allowBlank="false" fieldType="PK" >
          <text v="Tên loại" e="Type name"></text>
        </field>
        <field name="ten_loai2" label="1" field="-">
          <text v="Tên khác" e="Other name"></text>
        </field>

        <field name="status" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>1PFOGp66gVgaSTPirrPUVQbMSKkhmnTmRHH3u+H6D2wW0Fk7G/fqKNkkXVS9knb00rhuMsOXBEeYL4UrM0U+ZpV4MO8YKzi5jFZevH4SGBG7WyV1xhxUlIopHFA2IGHIJ0HYoLRwPINuOEDNnP84I0ZX6fiT3LG1gUqaVpRugtuOpD/d0i475X7OglTmhDw7z87StBEE2ZXKy08eI4SXtp51ttwWqgDdoRLgzDGRxDp2KpWL47+jqcdACS5iK8JSF/523FK4Y26WxF/cIeZwq6j1DDbB5qkDRXPW5n+7QEUu4irR/juGcd8AxQlSBxmTYAp41YbmtRwJt+AwiUe4eh/OLPWXgy5NgWI0FMOBl0M=</enc>]]>
    </text>
  </js>
   <css>
		<text>
		  <![CDATA[<enc>YkWQBTDGylCtyJwcHZMp4kHLaONbdUrMufRzgaQUdjNiYOMMNAU3yd1068ZsfGDqo8DrFDZonQcecL1q9/3/ukNgUyAqY2dyCxmt2sowYHxU2wjEZQz5+vhNxDU3lZSV</enc>]]>
		</text>
  </css>
  <script>
    <declare>
      <text>
        <![CDATA[<enc>hxQPm/hYhpvPifcenBxj7nfT+X4T8oXvYmZx4Kpwn3fRRVZY+foYIow2vt1OHdzq0lG6PkDpvnlKR1ei3AR28UkawCxswedTww8YMZ/ax/1/BVJZ6K0wvLOosliedaWZAZZQJt+bLBksKe9RWXks/lvGUxSX00WHdpeXsltu63DiOYIsJfQeOVnnqr6WNvqmUTBa+W7k519UjE/89vWen/AIFgbTmiiG0Wyi2VGm9gQ=</enc>]]>
      </text>
    </declare>
  </script>

</dir>