<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmloaithue" table="dmloaithue" fieldKey="ma_loai" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục loại thuế" e="Tax Type List"></title>
  <title0 v="Thêm mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
        <field name="ma_loai" label="1" field="1" allowBlank="false" fieldType="PK">
          <text v="Mã loại thuế" e="Tax type code"></text>
        </field>
        <field name="ten_loai" label="1" field="2" allowBlank="false" fieldType="PK" >
          <text v="Tên loại thuế" e="Tax type name"></text>
        </field>
        <field name="ten_loai2" label="1" field="2">
          <text v="Tên khác" e="Other name"></text>
        </field>
		<field name="status" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>EeQqasvYrZb3YzvZxNfOgMqgJLTq8QRlRX+Ks0g52Hm82ycQq/Y0bgPThqOBU8hufDf9lAUwk/s96f26o41b8L/s0TVE++VgLQzlauH/m96/NsTYYg/at+xc+nGBoQkaQWO0OmJhtsT3KotCyp7fN0ont+aNpti4yxx2aJF76TRKVZP2BegUXQ99ldP35MlG</enc>]]>
    </text>
  </js>

  <script>
    <declare>
      <text>
        <![CDATA[<enc>hxQPm/hYhpvPifcenBxj7nfT+X4T8oXvYmZx4Kpwn3fRRVZY+foYIow2vt1OHdzq0lG6PkDpvnlKR1ei3AR28UkawCxswedTww8YMZ/ax/1/BVJZ6K0wvLOosliedaWZDcFoChsvzjpfmNAkZyictxKlsW9Nc6mlxi0BBx5vs59OyeWZcFuJimH2WAESjyGEkhI6BIRXAxt/n7oQTaJidbbKG0jSAHTzHPd+hTgPEGnYLfrg4lmAJDeW9Ls+rHW4</enc>]]>
      </text>
    </declare>
  </script>

</dir>