<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmloailtx" table="dmloailtx" fieldKey="ma_loai" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục loại kho và cảng" e="List of types warehouses and ports"></title>
  <title0 v="Thêm mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
        <field name="ma_loai" format="U" label="1" field="1" allowBlank="false" fieldType="PK" >
          <text v="Mã bộ phận" e="Department code"></text>
        </field>
        <field name="ten_loai" label="1" field="-" allowBlank="false" fieldType="PK" >
          <text v="Tên bộ phận" e="Department name"></text>
        </field>
        <field name="ten_loai2" label="1" field="-">
          <text v="Tên khác" e="Other name"></text>
        </field>

        <field name="status" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>1PFOGp66gVgaSTPirrPUVckmsJt7lgMHIb1CU9/SGqVsOaMqbDMbkUpOzD8iw1chdDgxDQEviepf9IuaRU6PvzDZBJZ2rXlg7FERICtu2BoMvqbUAGk9MinfKv81i/veAFT2mfrrF1xjVWQC3ncktmSFy8atiznFBiq4LX9oDxoWM3JvPF1aH8PX/2N6MrZEYJ/jfsKbSXvZnhMoHTYmwc53tfqyeIgs9qdZjma+flkqB+qB1xYxAKeLwV7FzEUDX3xmmtlZCEdEH/qmlwhIsSK3pMYYqMtJqbc/stiZcPLmMYkXdSu2iKRmVPnjWIpS2okDNEMfhGgMDIxNRzUSorTK4X47N7BsjDOVVW0SpSk=</enc>]]>
    </text>
  </js>
   <css>
		<text>
		  <![CDATA[<enc>YkWQBTDGylCtyJwcHZMp4kHLaONbdUrMufRzgaQUdjNiYOMMNAU3yd1068ZsfGDqo8DrFDZonQcecL1q9/3/ukNgUyAqY2dyCxmt2sowYHxU2wjEZQz5+vhNxDU3lZSV</enc>]]>
		</text>
  </css>
  <script>
    <declare>
      <text>
        <![CDATA[<enc>hxQPm/hYhpvPifcenBxj7nfT+X4T8oXvYmZx4Kpwn3fRRVZY+foYIow2vt1OHdzq0lG6PkDpvnlKR1ei3AR28UkawCxswedTww8YMZ/ax/1/BVJZ6K0wvLOosliedaWZmLxSZgWl5Nv86/s+CpLtxA/ViUc5nudkAXVNwY84fYXV/edx76DUYrjCaOINFnvAuq9q02nNbcQem7EzqiNM4yjsx44o14kNdHTH+Ii/D+mamSY3YPZUnmFFEvQa0Vqh</enc>]]>
      </text>
    </declare>
  </script>

</dir>