<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
	<!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>

<dir id="dmlvtc3" table="dmlvtc3" fieldKey="ma_lvtc3" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
	<title v="Danh mục nghành hàng cấp 2" e="Level 2 product catalog"></title>
	<title0 v="Thêm mới" e="New"></title0>
	<title1 v="Sửa" e="Edit"></title1>

	<forms>
		<form gravity="TopLeft" columns="120,120,120" >
			<fields>
				<field name="ma_lvtc3" label="1" field="2" fieldType="PK" >
					<text v="Mã nghành hàng" e="Industry code"></text>
				</field>
				<field name="ten_lvtc3" label="1" field="2" allowBlank="false" >
					<text v="Tên nghành hàng" e="Industry name"></text>
				</field>
				<field name="ten_khac" label="1" field="2" allowBlank="false" >
					<text v="Tên khác" e="Other name"></text>
				</field>
				<field name="ma_lvtc2" viewType="Lookup" label="1" field="1" importable="35" allowBlank="false">
					<text v="Mã nghành hàng cấp 2" e="Industry code level 2"></text>
					<viewInfo lookupType="One" lookupId="dmlvtc2" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_lvtc2" lookupInfo="dmlvtc2|ma_lvtc2|ten_lvtc2" importCheck="@@DF and z.status=1"/>
				</field>
				<field name="ten_lvtc2" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as " >
					<text v="" e=""></text>
				</field>
				<field name="unit_id" label="1" field="2" hidden="true" dataType="I">
					<text v="Đơn vị" e="Unit"></text>
				</field>
				<field name="thu_tu" label="1" field="2" dataType="I">
					<text v="Thứ tự" e="Position"></text>
				</field>
				<field name="status" viewType="Combobox" inactivate="true" label="1" field="2" >
					<text v="Trạng thái" e="Status"></text>
					<viewInfo>
						<options>
							<option val="1">
								<text v="1 - Còn sử dụng" e="1 - Use"></text>
							</option>
							<option val="0">
								<text v="0 - Không sử dụng" e="0 - Not use"></text>
							</option>
						</options>
					</viewInfo>
				</field>
			</fields>
		</form>
	</forms>

	&DefaultButton;

	<js>
		<text>
			<![CDATA[<enc>zpm0Cp/S6CwWlcy1dfV9ClUd7WWKKzcjKRzIF9JqpPzGV2HQHYIMb+GAdvR83tT1s0Snk6WWD/2k0Enhq1QGMgQM8/M87rU5BRYXRVjhtEc3TIfgvpjUxAKTP7RMgMMjxuavadNmhTpE3cA5nQTvgOmRnhPoksqiLkXVU3zDSd1OsN4DBjoaotMCnzeJFX/Y+WtLXPwuhVfXTbLddA/EWMVYDBNH1BCdTClPeWvuoLQR268cbjGHD1XNNzAhiXIeV3pg30U69A9J/Z3vUTKqFlWvm+aXzjC30tWrEcU/jWLfFjBICNODCKP1+pXAa25qyP+WNJitHwaDDKHukfaF2g==</enc>]]>
		</text>
	</js>
	<script>
		<request code="request_code_unit">
			<text> 
				<![CDATA[<enc>Uy4Ft9qYHB7mT97xf0R4dfa7mpzBVp/slQe9Lqx6rj1k0djuyZ5tFPnLbi3UUurMqKKnoEFwNOPPFmJM/+m1CfXGnVFHM6uaoKcGsBvQY8o63EnCEu1Gn6B5vlRIHJp8aNZTBVUP/vA5ptXQmUm0BDlT9If+8sPug7e8ejycwz3njDbE/phlx293r+zZSdTUbuG7SDuAp+iZHDN3JC6bTVDRhgX/6HNI985IYThZuuTavPk7chrBCHPayINsXR3eO/I88JrQeNHgmsEeHLfCgIigh03/avArRzyfJ8dfLHo=</enc>]]> 
			</text>
		</request>
		<inserting>
			<text>
				<![CDATA[<enc>z1s4NkrNk+40z3uOtt5qcuRYJ+xiyRCtCE0YMpz3KgaFylh3dSn5eZKrLw1MtPbCROcxvnpHntqqG00J+sxt+71UUgGeysv+wHZjwmVAelylqfxR/Z76m0OubHHMQnEvMv5l9eURjgif+A6h0Svd5cIkOWeg6Kr/iznSGEYRsO5Zov0xKPNd1DW0QI492KWzQP5+8je1LZF1fqljVlp1yQ==</enc>]]>
			</text>
		</inserting>
	</script>
	<messages>
		<message val="codeExistsNewMsg">
			<text v="Mã dịch vụ đã có hoặc lồng nhau trong danh mục dịch vụ." e="The Service is invalid or already exists."/>
		</message>
		<message val="codeExistsEditMsg">
			<text v="Mã dịch vụ đã có hoặc lồng nhau trong danh mục dịch vụ." e="The Service is invalid or already exists."/>
		</message>
	</messages>
</dir>