<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmmst" table="dmmst" fieldKey="ma_so_thue" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục mã số thuế" e="List of customer"></title>
  <title0 v="Thêm" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120,120,120,120" >
      <fields>
	    <field name="unit_id" dataType="I" hidden="true" readOnly="true" inactivate="true" label="1" field="1" importable="-1">
          <text v="" e=""></text>
        </field>
		<field name="ma_so_thue" label="1" field="2"  importable="35" fieldType="PK" allowBlank="false">
          <text v="Mã số thuế &lt;a onclick='getTax(this);'&gt;(Kiểm tra)&lt;/a&gt;" e="Tax code &lt;a onclick='getTax(this);'&gt;(Test)&lt;/a&gt;"></text>
        </field>
        <field name="ten_kh" label="1" field="-" importWidth="250" importable="15">
          <text v="Tên khách hàng" e="Other name"></text>
        </field>			
        <field name="dia_chi" label="1" field="-" importWidth="250" importable="30">
          <text v="Địa chỉ" e="Address"></text>
        </field>
		<field name="ngay_sinh" label="1" dataType="D" field="1" nextRow="true" importable="40">
          <text v="Ngày sinh" e="Contact"></text>
        </field>
        <field name="nguoi_lh" label="1" field="-" nextRow="false" importable="40">
          <text v="Người đại diện" e="Contact"></text>
        </field>
        <field name="dien_thoai" label="1" field="2" importable="80">
          <text v="Điện thoại" e="Phone"></text>
        </field>
		<field name="email" label="1" field="2" importable="80">
          <text v="Email" e="Phone"></text>
        </field>
		<field name="ngay_hoat_dong" label="1" dataType="D" field="1" nextRow="false" importable="40">
          <text v="Ngày hoạt động" e="Contact"></text>
        </field>
		<field name="noi_ql" label="1" field="2" importable="80">
          <text v="Quản lý bởi" e="Phone"></text>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

<js>
    <text>
      <![CDATA[<enc>YnlhnFNbXTNjVD86EPEjrcsb8nAY71UoOzZzrYcI2zMLIoU7YZkKNcopshPSEarFqJA7dxBaRaUu9WDQMSkRdAD2Fm6UwZikdjZFi7djhWUWvGCvjxajYmcIXF62T2LywGr1kcAKN7nSu14J1fL2n+iGeh5SKOr1TlzrEhM9EsXIMMUgPKBaEx8fp3HHvAYqZHaQ7byjePX/86gXrBNBzQjB0QS1L0UMnWgZwt449zCl+vFTcKP8edrVhq5keLfaxW5O1451hpzW/jHX01V0kXycSJPaPWrRr/O9BuINA5fgquOfvn81N+ARYq+j1QCnqpb+j3hDiq6hARlFcfBKJi5FPXuBDnDquawZnRnzrkYmiJ7nU476GI3hMuy+UM2YRBBSDHBuxN+m6Y04n9I7R1a5Z0mauTzHGgvGbZnU/olk99dwQMIlHCH2gu90OqEaewTOglc4hgXquyxz46N3c69Q+OguPhEdXCeuBQ2QxehS76febRRt+ouOsq28B1badGmzoipoewvyZBI04dtBsTp2YZkCTKG6TtdrkxuHLxSzmtn8Rcid7TDwPG5WbO6h6fuwau7FRXeCF221hAkVXGF8VrJE82dzAFbOQl1Ry9na9onZkM0Jc384KpWYiCTbJHkg3Q2KnUqzSy9iawvcac9qtURCFQ6VqiblqNxRpxJVsGeM3fJ7Iqm18MDmY2eLxA7K6RjLR21rZ83buN0dNyG3KJ/y86vVqz/biJu7as7vZve2fSd1NrUkcFq0wbSluzXOjhAc+wG7PKMLRnFARA==</enc>]]>
		
    </text>
  </js>
   <css>
		<text>
		  <![CDATA[<enc>YkWQBTDGylCtyJwcHZMp4lZsTBMUUzGyXkCNhkU8H8lipHy9GlksgUpB6GqZizW3dEtMoW3xTWPPVMBqil8A7WstuLXIG/G6bXYPJ10bVxZb4YtmX/lh3Imz/BDlxgn/flGGVdSlMG81zRWJGrTebA==</enc>]]>
		</text>
  </css>

  <script>
    
    <query>
      <text>
        <![CDATA[<enc>H4GUdC8VkeRZ+seKAqv63yc0kEiq2IGmAjclsbM7JjuncbC1jV2Eyq8uhZreNL0HK/GN+pYgX2ZQPXdMR2KJnya+zIsqor+dL7b8CzxeBfC7P+LkijqSgQEVkwp/6b4iTX6tXhyrp0y8MjDDFGqa7lSQ+0LmAJLW70jBH5IvDszxn01nnA99VTasCiN/hCO8dN/2RNoveHlPzVJ1VygerW7xzOyDdhOKFvvX8edc29U/bM1t4/mFD+iZ1OpQLfGnQiUaRfQliQvi7C4Vui0xyv5w92xJrK7pODLZD0wGF7lW6Rwl6vCptq+dyeZY+aWZtaRDxiT8djpErBptxo9VFb8U6du4ie5bGlKJ2Of+0ZweYdYlVAo6srAvqs9yuHAt</enc>]]>
      </text>
    </query>
    <inserting>
      <text>
        <![CDATA[<enc>/T/6v4fr7JtuEWROY5bEopFO1HCnIjtZjFzzDG3F9/vEkIfRrRIYFlNT+1c2A+G4DGK3P1V1ru+z1kGXJXjR1VzP1TAM3KziUQ39S5UPAFO5TtFkd+A7rjU9Cj84+ron+NnAUl09CZS+jY4xst+ifUx/y0L2N86LSRXXWB0b2jLk9z1JyBTjpFwFo33O8/V92Jll9ZnIKloIczVnEYCl2/5Q4n5X9mE3/5atjZjvFut8hbyHb/wqOO6O7YgIZzpT</enc>]]>
      </text>
    </inserting>
    <aftersave>
      <text>
        <![CDATA[<enc>sPSYwuwGGwmF0/9voZ/h5p85fmj8FSp+j6Jj68pGpswV+dqgI5LvdABNTCD0matKkJqfeOmhGtwGkHFM/Dgtq+4x9DxAaKZMFShbehLdiibRAkF/KhLt9wm6RF3cjRADicYMJX83MCxPpoHKVQTSyffWD0gcfoDrnrA0aljfVorruxpg9H8+gi3EfY29CetWC6r1WG0YL/HVQapwINe1YvoZodPf6WNLXRbEdOToB+yA5WuhYvAK1wZGrlmwqM3rz4jRCb4lJh5YJr9Odh92mF4rwEZJIhwvcPuu0M5/oLDMywcbaSOtvWHdCA9y8MoXHDnLGtFKBpxdjsrU7qz3E1SHh2+kYBrNKEoOOOXhJnZvWLUKrc/oW14jsShOFlJhlX77j0juuZ/QNxnyvYiNy6zmrQW15Maqkg+dzbRHIKsg9TheF9CrawTAED0O7yVm</enc>]]>
      </text>
    </aftersave>


    <importing>
      <text>
        <![CDATA[<enc>sxD5Swu0R4mcxEHdwcy2yi46ZbQRyi0uEDh1tGVfNVOBZJeZZHskWnswm55XGvVMtI3kJxA271ZmaBNQ7vOM1svvmG7tRC9SwsrihBxLjQw=</enc>]]>
      </text>

    </importing>
  </script>

  <messages>
    <message val="codeExistsNewMsg">
      <text v="Mã khách hàng đã tồn tại trong danh mục khách hàng." e="The record already exists."/>
    </message>
    <message val="codeExistsEditMsg">
      <text v="Mã khách hàng đã tồn tại trong danh mục khách hàng." e="The record already exists."/>
    </message>
    <message val="taxtCodeExists">
      <text v="Mã số thuế đã tồn tại trong danh mục, &lt;span class='Highlight'&gt;Lưu ý:&lt;/span&gt; hệ thống vẫn lưu dữ liệu vừa cập nhật." e="The tax code is already exists, &lt;span class='Highlight'&gt;Warning:&lt;/span&gt; Updated data has been saved."/>
    </message>
  </messages>
</dir>