<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmkh" table="dmkh" fieldKey="ma_kh" transaction="true" tryCatch="true" dirViewType="Dialog" dirObjectType="Voucher" width="Large" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục hãng tàu" e="List of Shipping Lines"></title>
  <title0 v="Thêm mới" e="Create New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
        <form gravity="TopLeft" columns="120,120,120,120,120,120" >
      <fields>
        <field name="unit_id" dataType="I" hidden="true" readOnly="true" inactivate="true" label="1" field="1" importable="-1">
          <text v="" e=""></text>
        </field>
        <field name="ma_kh" format="U" label="1" field="1" viewType="AutoIncrease" allowBlank="false" fieldType="PK" importable="5">
          <text v="Mã hãng tàu" e="Carrier Code"></text>
        </field>
        <field name="ten_kh" allowBlank="false" label="1" field="-" importable="10">
          <text v="Tên hãng tàu" e="Carrier Name"></text>
        </field>
        <field name="ten_kh2" label="1" field="-" importable="15">
          <text v="Tên khác" e="Other Name"></text>
        </field>
		<field name="kh_yn" dataType="B"  blank="1" clientDefault="true" label="[100]" field="[40]" inactivate="true" importable="20">
          <text v="Khách hàng" e="Customer"></text>
        </field>
		<field name="dl_yn" dataType="B" clientDefault="true" label="[120]" field="[40]" nextRow="false" inactivate="true" importable="25">
          <text v="Đại lý" e="Agent"></text>
        </field>
		<field name="nv_yn" dataType="B" nextRow="false" clientDefault="true" label="[100]" field="[40]" inactivate="true" importable="30">
          <text v="Nội bộ" e="Internal"></text>
        </field>	
		<field name="ncc_yn" dataType="B" blank="1" valueDefault="1" clientDefault="true" label="[100]" field="[40]" inactivate="true" importable="35">
          <text v="Hãng tàu" e="Carriers"></text>
        </field>
		<field name="hk_yn" dataType="B" clientDefault="true" label="[120]" field="[40]" nextRow="false" inactivate="true" importable="40	">
          <text v="Hãng hàng không" e="Airlines"></text>
        </field>
		<field name="vc_yn" dataType="B" clientDefault="true" label="[100]" field="[40]" nextRow="false" inactivate="true" importable="43" valueDefault="">
          <text v="Hãng vận tải" e="Trucking Company"></text>
        </field>
		<field name="other_yn" dataType="B" blank="1" nextRow="true" clientDefault="true" label="[100]" field="[40]" inactivate="true" importable="45">
          <text v="Khác" e="Other"></text>
        </field>	
		<field name="ghichu" nextRow="false" fieldType="EX" readOnly="true" inactivate="true"  hidden="true" label="[240]" field="" importable="-1" >
			<text v="(Người gửi/Người nhận/Người thông báo)" e="(Shipper/Consignee/Notify)"></text>
		</field>
        <field name="dia_chi" label="1" field="-" importable="50">
          <text v="Địa chỉ" e="Address"></text>
        </field>
        <field name="ma_so_thue" label="1" field="2"  importable="55">
          <text v="Mã số thuế &lt;a onclick='getTax(this);'&gt;(Kiểm tra)&lt;/a&gt;" e="Tax code &lt;a onclick='getTax(this);'&gt;(Test)&lt;/a&gt;"></text>
        </field>
        <field name="nguoi_lh" label="1" field="-" nextRow="false" importable="60">
          <text v="Người liên hệ" e="Contact"></text>
        </field>
		<field name="dien_thoai" label="1" field="2" allowBlank="false" importable="65">
          <text v="Điện thoại" e="Phone"></text>
        </field>
        <field name="fax" label="1" field="2" nextRow="false" importable="70">
          <text v="Fax" e="Fax"></text>
        </field>
		<field name="e_mail" label="1" field="2" importable="75">
          <text v="Email" e="Email"></text>
        </field>
        <field name="home_page" label="1" field="2" nextRow="false" importable="80">
          <text v="Trang chủ" e="Home Page"></text>
        </field>
		<field name="ghi_chu" label="1" field="-" inactivate="true" importable="85">
          <text v="Ghi chú" e="Notes"></text>
        </field>
        
        <field name="nh_kh1" viewType="Lookup" label="1" field="1" importable="90">
          <text v="Nhóm 1" e="Group 1"></text>
          <viewInfo lookupType="One" lookupId="dmnh" lookupKey="ma_loai_nh = 'KH1' and status=1" lookupCheck="ma_loai_nh = 'KH1'" lookupRef="ten_nh_kh1" lookupInfo="dmnh|ma_nh|ten_nh" importCheck="@@DF and z.ma_loai_nh = 'KH1' and z.status=1"/>
        </field>
        <field name="ten_nh_kh1" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
        <field name="nh_kh2" viewType="Lookup" label="1" field="1" importable="95">
          <text v="Nhóm 2" e="Group 2"></text>
          <viewInfo lookupType="One" lookupId="dmnh" lookupKey="ma_loai_nh = 'KH2' and status=1" lookupCheck="ma_loai_nh = 'KH2'" lookupRef="ten_nh_kh2" lookupInfo="dmnh|ma_nh|ten_nh" importCheck="@@DF and z.ma_loai_nh = 'KH2' and z.status=1"/>
        </field>
        <field name="ten_nh_kh2" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
        <field name="nh_kh3" viewType="Lookup" label="1" field="1" importable="100">
          <text v="Nhóm 3" e="Group 3"></text>
          <viewInfo lookupType="One" lookupId="dmnh" lookupKey="ma_loai_nh = 'KH3' and status=1" lookupCheck="ma_loai_nh = 'KH3'" lookupRef="ten_nh_kh3" lookupInfo="dmnh|ma_nh|ten_nh" importCheck="@@DF and z.ma_loai_nh = 'KH3' and z.status=1"/>
        </field>
        <field name="ten_nh_kh3" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
        <field name="rg_code" format="U" viewType="Lookup" label="1" field="1" clientDefault="true" importable="105">
          <text v="Khu vực" e="Area"></text>
          <viewInfo lookupType="One" lookupId="sysregioninfo" lookupKey="status=1" lookupCheck="1=1" lookupRef="rgname" lookupInfo="sysregioninfo|rg_code|rgname" importCheck="@@DF and z.status=1"/>
        </field>
        <field name="rgname" nextRow="false" fieldType="EX" readOnly="true" clientDefault="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
		<field name="ma_tt" viewType="Lookup" label="1" field="1" importable="110">
          <text v="Mã thanh toán" e="Payment"></text>
          <viewInfo lookupType="One" lookupId="dmtt" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_tt" lookupInfo="dmtt|ma_tt|ten_tt" importCheck="@@DF and z.status=1"/>
        </field>
        <field name="ten_tt" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="1" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>

		<field name="so_tk" label="1" field="1" nextRow="false" allowBlank="true" importable="115">
          <text v="Số tài khoản" e="Account Number"></text>
        </field>
		<field name="ma_nh" viewType="Lookup" label="1" field="1" importable="120">
          <text v="Ngân hàng" e="Bank"></text>
          <viewInfo lookupType="One" lookupId="dmnganhang" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_nh" lookupInfo="dmnganhang|ma_nh|ten_nh" importCheck="@@DF and z.status=1"/>
        </field>
        <field name="ten_nh" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
		
		<field name="gioi_han_no" label="1" field="1" dataType="N" format="" importable="125">
          <text v="Giới hạn tiền nợ" e="Debt Limit"></text>
        </field>
		 <field name="khoang_cach" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="1">
          <text v="" e=""></text>
        </field>
		<field name="ky_han_no" label="1" field="1" dataType="N" nextRow="false" format="" importable="130">
          <text v="Kỳ hạn nợ" e="Debt Maturity"></text>
        </field>
		
		<field name="ma_nvbh" viewType="Lookup" label="1" field="1" clientDefault="true" importable="135">
          <text v="Nhân viên bán hàng" e="Sales Employee"></text>
          <viewInfo lookupType="One" lookupId="dmnvbh" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_nvbh" lookupInfo="dmnvbh|ma_nvbh|ten_nvbh" importCheck="@@DF and z.status=1" />
        </field>
        <field name="ten_nvbh" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="1" aliasName="cast('' as nvarchar(4000)) as " clientDefault="true">
          <text v="" e=""></text>
        </field>
		<field name="phong_kd" label="1" field="1" nextRow="false" dataType="N" format="" importable="140">
          <text v="Phòng kinh doanh" e="Sales Department"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" label="1" field="2" valueDefault="1" importable="-1">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

<js>
    <text>
      <![CDATA[<enc>+Pr7HaYlTMO+V0bzV2b9RaH1+wGbMuFwTaeMMZA+OlVtP1DpgQkZgIEvJvAq/UvoQU5APa3JZWpuXgt3W1VQqwI1KVYT61Gqvjzz85t2ZbK41ibx15rfZ3KHma3VAFtlWGofm1AtaRNtDE6bMbKE24SKinTJngZLGU6uE9gInAEJNR1CSqP6/sXRW6gDpeDMSrDv3ijHGrB3bJX7SMX+hmM5qSxXUd26tevUTKmGNyb1/OavMRjxh+3UJDlnncykk1M9i//DO8laEqf+azvs3YGX1LNds/m0EFNiTDBI4NJRKjlG0ftmtXMVHm2oYEMg8klJdNar9sS5KJVOaRa+XG5sQ4n5g+h4AFlIfdG1v6PzkSzhmsfijda2V8qMsBROrCs5ONHfMiQKQsPi/LmXSPVqwY1l4bXz1ocqwas0kcIC0XUx2RmbnECTPkT9SIuQC0WJCt0YYUQBxKfdFxPBR90j2UnDv6A4+wNcI6aFYMr7YiR8m1MfLV4lViNRftHNSZ0XPaAxYbVAKh07BKpTH9M/SRYiBMFd58ezj4HCx8mOmg6F8Q5MRW50zJDYoIkZDEyFlUmVmqJih5hbMMs6aTQ6GUDXl0AEd3Cvumt+iFx7Gj2GEqcHDlNq4KXP6xPCb8VnfGHE+Gi56LukiWb4OEMBEWbr0UMf4gFZM9U8PH8b5lwGX4zZcD/MywkYYL8wLsRPn8y6nQkmIo3QMk6jXTIn7pES2vELRUzaNdyDrAn/gC3pHydOasHSR7OtYLI73GzmJgml6Da86sKRp68hrjK847YMIKf8NyHTsC1lSbGm2A42rMtB9Qrtz43CoxqB</enc>]]>
		
    </text>
  </js>
  
  <css>
	<text>
		<![CDATA[<enc>e5OMrfwCCofCdiKuVEasBTT9lFCvKfb9UU24vd++2s5TZMnpVLL57Pax0jrb1KMAejBcfSiKtOv85neNAGREqNUuhe3JbMs0dnlS96lvxfOM4Xtq1RZRAU7RUgaeaTJ0nALUn8ByGviCoQTefZ2XP3k9LZD50GAJno5/ykH2u/E=</enc>]]>
	</text>
  </css>

  <script>
    
    <query>
      <text>
        <![CDATA[<enc>iW+MwpbVYdGJDu1NI8DWbeeHIkMGYcUEJiMsNAg6qiO8/uGj5nuIH+ENTFDPmIGSc2NQPC8t0lTS64GaglPN/hbPcnxGdYWBgNY1AgYeRSLeXJgMviCgrw3m4URq0ypavYD2junWPDFlnFWIox8YXIwUS7pPA4moPHiIOiC+AuHCSPmr4tDguV9BTZdWMJCKsSDjSloQ6hvp78o9ryGapRCUMeBm1avY1U5RUwXw5/BFNYpwhtveV0JMVazTuywzSnI9seF1lLyEdd8O44FAiYVYEWb3yqBFF4kcu0Ey1zs93hHrUpuNg3vJw3zpM/wSBuDnJ8n20oxEf60vDglFAQ86U6RRKSPEDx4zFmbTosUKUCcE9uRs3Spgc9NSNAX3</enc>]]>
      </text>
    </query>
	
    <inserting>
      <text>
        <![CDATA[<enc>aTcATOlFrrXqAjRK8p/gr+37bbbjPMPTds06YH7KESYhW/qdZvd78nPQH4Wmoh22l1WK7XTC35PABhl5zr6ug/DdG8xEdjvN49/KBTz5/mFdz4xgFl0qs22tPaGBf9HKtHJz5cKQhLiVo06OIMBWJlNIvMA8Sl+MR6UM7RgK6KD60JG7dDFoh1V1ieQz3afHT6sUgh3usyEQYwfCoxJ3iVrNxOFtEhQpX/am8P5CpTXoXYMQI5aSKZemzrKeZ8fTD0pISoTRAsX0GegVrhgVcy+QENoxzhWX9zWa0oQb4zgs4+v3hqYczJPbOIDhiYxhGrQMGRuen+tMdY3tEagcpQ==</enc>]]>
      </text>
    </inserting>
	
    <aftersave>
      <text>
        <![CDATA[<enc>++V3V+E3NWH5wDFlTZgrSGbjNHJkVDS0vmsm1GR080eRHXmaYAHQCJloa1DZ2hAHX7Ul/SMrxMMA01pu0hKJuqh9ZZF8e5TF2ZR2GgJ/z+ukFomP5R6dNCYdzgWq8JWXAPilrl4x6jMYnwD1yXajgb4uRJRW3SuHjGaXxQm8QWEQV5UJ7DiV8FJhOPdV9FLF</enc>]]>
      </text>
    </aftersave>


   <importing>
      <text>
        <![CDATA[<enc>sxD5Swu0R4mcxEHdwcy2yi46ZbQRyi0uEDh1tGVfNVOBZJeZZHskWnswm55XGvVMtI3kJxA271ZmaBNQ7vOM1svvmG7tRC9SwsrihBxLjQw=</enc>]]>
      </text>
    </importing>
  </script>

  <messages>
    <message val="codeExistsNewMsg">
      <text v="Mã hãng tàu đã tồn tại trong danh mục, vui lòng chọn một mã khác." e="The shipping company code already exists in the catalog, please select a different code."/>
    </message>
    <message val="codeExistsEditMsg">
      <text v="Mã hãng tàu đã tồn tại trong danh mục, vui lòng chọn một mã khác." e="The shipping company code already exists in the catalog, please select a different code."/>
    </message>
    <message val="taxtCodeExists">
      <text v="&lt;span class='Highlight'&gt;Lưu ý:&lt;/span&gt; Mã số thuế đã tồn tại trong danh mục khách hàng" e="&lt;span class='Highlight'&gt;Warning:&lt;/span&gt; The tax code is already exists"/>
    </message>
  </messages>
  
</dir>