<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmnganhang" table="dmnganhang" fieldKey="ma_nh" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục Ngân hàng" e="List Bank"></title>
  <title0 v="Mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
        <field name="ma_nh" format="U" label="1" field="1" allowBlank="false" fieldType="PK" >
          <text v="Mã Ngân hàng" e="Bank Code"></text>
        </field>
        <field name="ten_nh" label="1" field="2" allowBlank="false" fieldType="PK" >
          <text v="Tên Ngân hàng" e="Bank Name"></text>
        </field>
		<field name="ma_qg" viewType="Lookup" label="1" field="1" >
           <text v="Mã quốc gia" e="Country code"></text>
           <viewInfo lookupType="One" lookupId="dmquocgia" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_qg" lookupInfo="dmquocgia|ma_qg|ten_qg" importCheck="@@DF and z.status=1"/>
        </field>
        <field name="ten_qg" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
           <text v="" e=""></text>
        </field>
		<field name="swift" label="1" field="2" allowBlank="false" fieldType="PK" >
          <text v="Mã BIC-SWIFT" e="BIC-SWIFT Code"></text>
        </field>
		<field name="post_office" label="1" field="2" allowBlank="false" fieldType="PK" >
          <text v="Mã bưu điện" e="Post Office code"></text>
        </field>
		<field name="account_no" label="1" field="1" allowBlank="false" fieldType="PK" >
          <text v="Số tài khoản" e="Account no"></text>
        </field>
		<field name="Branch" label="1" field="2" allowBlank="false" fieldType="PK" >
          <text v="Chi nhánh" e="Branch"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>Xm0SQO244yhm4oovG3IvuGWZVkwdldFFDmpUmMtuEWLEPqBfr7Wp/20wRPVJp9m5C6FmXagS0LOy3u7CTfzHaSzqWks7cOTmurfbNCYwfseLS9FZpZX0RYUkhqJZQAO3LzWJsgDY5vLcCMaFeKhC6vzelJ8qloSRThoL32OnuMBgoYuTs250yPUx8gAsvf3x</enc>]]>
    </text>
  </js>

  <script>
    <declare>
      <text>
        <![CDATA[<enc>hxQPm/hYhpvPifcenBxj7nfT+X4T8oXvYmZx4Kpwn3fRRVZY+foYIow2vt1OHdzq0lG6PkDpvnlKR1ei3AR28UkawCxswedTww8YMZ/ax/1/BVJZ6K0wvLOosliedaWZyUOck6+Xe/tCkoqE7UEYT/WYPBhJO8y27FNCb24AHPmk6O4gUTSw/ZPhNKfq3b1Q1Sz0KF9NaUSnamU+9Z7f3GDGGbGNRsLE4jNd6tJtoFQ=</enc>]]>
      </text>
    </declare>
  </script>

</dir>