<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmnhomcv" table="dmnhomcv" fieldKey="ma_nhom" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục nhóm chức vụ" e="List of position groups"></title>
  <title0 v="Thêm mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
        <field name="ma_nhom" format="U" label="1" field="1" allowBlank="false" fieldType="PK" >
          <text v="Mã nhóm" e="Group code"></text>
        </field>
        <field name="ten_nhom" label="1" field="-" allowBlank="false" fieldType="PK" >
          <text v="Tên nhóm" e="Group name"></text>
        </field>
		<field name="ten_nhom2" label="1" field="-" >
          <text v="Tên khác" e="Other name"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>8MPmUIIvSCTxlyUzlphwtLGpIwGFzA9S0Mr3nzqpKvngJO/wdrYDbwVCcuuivvD4fi8xRAmWM/4HT1UwHAkB1iEZ2i4D+rYC6X4Am85h7v/NfUGBzFEh872T8jfYh7LfE8jOtYfTi3mI6FiTROD5v+UkTuTveLtHHjXoAvdcvdtvHriCYWAdue3b2VoI9Ho0YdcHH4gqDASMDFad0udF4Sc7rgBUGC39coWQLhiy26KXuEgdkP6UtGt7RMKGEGxPZNhe+khQ44sG732nWcrZw45DWxrgK/6y9zt+UCfzFWLnm7T3SQhMC+CXvEb6fkKBdl5uXTEMgNwTTu/i3sHwGl60dOBjLUkvHMRVKYCQeI8=</enc>]]>
    </text>
  </js>
   <css>
		<text>
		  <![CDATA[<enc>YkWQBTDGylCtyJwcHZMp4kHLaONbdUrMufRzgaQUdjN/JxcIOOnidVToozq6jNo15k2mK89FU9XIqRz5Wjq+77HlMCYqgbKjGZirzYN8UZkmHQiTRuI9CD1nZ+cpc+fJ</enc>]]>
		</text>
  </css>

  <script>
    <declare>
      <text>
        <![CDATA[<enc>HoMfTI0EpDZZnzy3AwuL7iNCVeWjH5s4FoENJgex32bGrDwwh9XMqmgaPfjz4cZqTD3nOH1KPTFNwez91T6MA4h73ruSczJ0vzSSPhpjn5IpB3onRRrJzIvxh28D/4/pPOL8IELx/CUVUqJllmVAvU1euZMum4jcbhPnuK/cizJsRoyLHubm9NSvqaPruYaAR9Qxme+0A0rN8jr8Qjr+e9k+3PL0oMDtqkRzXZ698yiXMlp/9NWGqMG0ICQfI2/S96V7n2/v5pQ8KSDsq3NLFQ==</enc>]]>
      </text>
    </declare>
  </script>

</dir>