<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>

<dir id="dmnhomvb" table="dmnhomvb" fieldKey="ma_nvb, ma_loai" transaction="true" tryCatch="true" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục nhóm tài liệu mẫu" e="Template Document Group Catalog"></title>
  <title0 v="Thêm mới - nhóm tài liệu mẫu" e="New - template document group"></title0>
  <title1 v="Sửa - nhóm tài liệu mẫu" e="Edit - template document group"></title1>

  <forms>
	<form gravity="TopLeft" columns="120,120,120,120,120" >
		<fields>
			<field name="unit_id" dataType="I" hidden="true" readOnly="true" inactivate="true" label="1" field="1" importable="-1">
			  <text v="" e=""></text>
			</field>
			<field name="ma_nvb" label="1" field="[120]" importable="5" allowBlank="false" fieldType="PK">
				<text v="Mã nhóm tài liệu" e="Template Group Code"></text>
			</field>
			<field name="ten_nvb" label="[120]" field="-" importable="10" allowBlank="true">
			  <text v="Tên nhóm tài liệu" e="Template Group Name"></text>
			</field>
			<field name="ten_nvb2" label="[120]" field="-" importable="15" allowBlank="true">
			  <text v="Tên tiếng anh" e="English Name"></text>
			</field>
			<field name="ma_loai" label="" field="" importable="-1" allowBlank="true" hidden="true" fieldType="PK">
			  <text v="Mã loại" e="Type Code"></text>
			</field>
			<field name="status" viewType="Combobox" inactivate="false" label="1" field="2" valueDefault="1" nextRow="true" importable="-1" >
			  <text v="Trạng thái" e="Status"></text>
			  <viewInfo>
				<options query="select ma_tt, ten_tt%l from dmttsd where status = 1 ">
				</options>
			  </viewInfo>
			</field>
      </fields>
    </form>
</forms>

&DefaultButton;

<js>
    <text>
      <![CDATA[<enc>af+f2Sc/98IKT3xezdJpLjelzPW+HYBCS/4nMvOarsHadf4XW4I7L5spVtNr29KyI1DK4vd9vuirHE2rZAiTvafpAzFQOx/Q1qqF0Ql7+p+E/fjcccX50GbMbxjG7THJP60vriBXqHaL93tvpvwsdavJ4b2AwuPYG4qPSHEKc1ZfafToMb1mcMllnxAsdgsu9EghSqDOlS9957jtNMW0a2Oepot7FTZ22DhuG4JQK1K1h1qL3LkyLuKbCyGPMu4uF95TIl5IaysXRClzT2ZEt3ml9+gPWXCa4GM1PeI/RL5auiUZb8ROWiNgBqeg84vHxxt7kymCcNf+1ei/VqdOjQ==</enc>]]>
    </text>
  </js>
	<css>
		<text>
		<![CDATA[<enc>Pm//48dGSSHIE4J7qodrhaUx6aWVoX8bv+kaki6zKb81G+ePVyeUFo14Ixu/kos5FPlHFQrYoWp6Wz3HnEnE2pRFvfJo4Lw0Xm5pKbYbMB2uUw4gBoPyr1UWQQvlyLzo5mRdRjvmW0AEX+tXTPZXGWDfSYmHIrbzvT56IW9KFyWIpXb7FS07lku1/28ws83j</enc>]]>
		</text>
	</css>
	<script>
		<query>
		  <text>
			<![CDATA[<enc>GJgBVkOd9xy3In+SUACpOOdXdTQbLjDNG098RVYG+mqJrACGNi8MwNsRrtmQkuMIYyR65+M+8FdE2nQkBtdUjjGtkBSGsDqbRbA3vrYN89ZzUnQVJ+W1/9AMkiZ8xTjPYAdSbE6TNHswawXCA3Q7ZKpywgArBHY6CKMo02cq6Ek=</enc>]]>
		  </text>
		</query>
		<updated>
		  <text>
			<![CDATA[<enc>sxD5Swu0R4mcxEHdwcy2ynVkJ6IiRfsuHiDzDrC78ELIJg2k4xX5PxEITwgSuDtWSiTOU3sqnIo/Bv0T8e877uKHW6bIEuTFdpbPdQB+xElll2tzxh9iUOpwbot+jXTZNKo5+n5Fy+aXD8VrO81PEw==</enc>]]>
		  </text>
		</updated>
		<inserting>
		  <text>
			<![CDATA[<enc>oOkO+AWnvbkn3n1L15YhZKMBDoOUvLz2Zt6lglqlrpDpBMT+LcI+Vhm/LBIT4wBPUxnlsAI2BHvVaGVayJyUV/NF7bcrI+gdgZ5uc2Yuj2FX9krWNlKxkk0uPHqbx7R0vV/nYiYZrqi8w02Je6vTlV/xTO0+ef4U2Lb77KD4FUEmY5IDDnVQuEOqd5fnnaZg6ogNZzw9DDEchQf46g/nN3hAwH56SnTKtwZlFOa5z6neaKRZkGWbFl2RDWJ06i2ag/Dl776XbggcsOpYFYXFAg==</enc>]]>
		  </text>
		</inserting>
		<importing>
			<text>
			<![CDATA[<enc>sxD5Swu0R4mcxEHdwcy2yi46ZbQRyi0uEDh1tGVfNVNRcvUP6dkPQS2QqQDWYbioM8zBKzutsCScnfcwfRx/dFzdFlKj+5rg5sGl+07mob2moeViGS7LQWTctwZGiI71</enc>]]>
			</text>
		</importing>
	</script>
	<messages>
		<message val="codeExistsNewMsg">
		  <text v="Mã nhóm văn bản đã tồn tại trong danh mục." e="The circulation document code already exists in the list."/>
		</message>
	</messages>
</dir>
