<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmnhomxe" table="dmnhomxe" fieldKey="ma_nhom" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục nhóm xe" e="Vehicle group list"></title>
  <title0 v="Thêm mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
        <field name="ma_nhom" format="U" label="1" field="1" allowBlank="false" fieldType="PK" >
          <text v="Mã nhóm xe" e="Vehicle group code"></text>
        </field>
        <field name="ten_nhom" label="1" field="2" allowBlank="false" fieldType="PK" >
          <text v="Tên nhóm xe" e="Vehicle group name"></text>
        </field>
        <field name="ten_nhom2" label="1" field="2">
          <text v="Tên xe" e="Other name"></text>
        </field>
     
        <field name="status" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - xeông sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>uw3iZoR/y/5o6FF1x5y/2aIBzmI9Lu6OVC57bQBEAASKNvnwZiU+wbtMD1SY9qOWdZcvHTh/uJ2Zdier4Q1TDhT1ytcVuJVvNf+H6PfffjnhAw4GP7iwPHitCAAjWXQzFtB5MVOA/ODH8el2VgYDSPYpqHg2IXJqIIcKrbznKdNIG8wXX9p+yFaMj4qZ61c1</enc>]]>
    </text>
  </js>

  <script>
    <declare>
      <text>
        <![CDATA[<enc>hxQPm/hYhpvPifcenBxj7nfT+X4T8oXvYmZx4Kpwn3fRRVZY+foYIow2vt1OHdzq0lG6PkDpvnlKR1ei3AR28UkawCxswedTww8YMZ/ax/1/BVJZ6K0wvLOosliedaWZWTAQEksbk1KjXGJhJW1IfzCn0dv7Rzndcu7UFGgor7W/S0RAy6mcMRbp9lGbfPO9j0zolkud+SF5HQZCK+ArVMhVtNZ8OhQ95PDlnFpYVz5zEIeUbuyOweeCFSjdWjV4</enc>]]>
      </text>
    </declare>
  </script>

</dir>