<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmnhansu" table="dmnhansu" fieldKey="ma_ns" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục nhân viên" e="List of customer"></title>
  <title0 v="Thêm" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120,120,120,120" >
      <fields>
        <field name="unit_id" dataType="I" hidden="true" readOnly="true" inactivate="true" label="1" field="1" importable="-1">
          <text v="" e=""></text>
        </field>
        <field name="ma_ns" format="U" label="1" field="1" viewType="AutoIncrease" allowBlank="false" fieldType="PK" importable="5">
          <text v="Mã nhân viên" e="Code"></text>
        </field>
        <field name="ten_ns" allowBlank="false" label="1" field="-" importWidth="250" importable="10">
          <text v="Tên nhân viên" e="Name"></text>
        </field>
  
        <field name="ma_so_thue" label="1" field="2"  importable="35">
          <text v="Mã số thuế &lt;a onclick='getTax(this);'&gt;(Kiểm tra)&lt;/a&gt;" e="Tax Code"></text>
        </field>
		
      <field name="ma_hd" viewType="Lookup" label="1" field="[120] ">
        <text v="Hợp đồng LV" e="Position"></text>
        <viewInfo lookupType="One" lookupId="dmhopdong" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_hd" lookupInfo="dmhopdong|ma_hd|ten_hd" importCheck="@@DF and z.status=1"/>
        </field>
        <field name="ten_hd" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
           <text v="" e=""></text>
        </field>
       
        <field name="rg_code" format="U" viewType="Lookup" label="1" field="1" clientDefault="true" importable="75">
          <text v="Khu vực" e="Region Code"></text>
          <viewInfo lookupType="One" lookupId="sysregioninfo" lookupKey="status=1" lookupCheck="1=1" lookupRef="rgname" lookupInfo="sysregioninfo|rg_code|rgname" importCheck="@@DF and z.status=1"/>
        </field>
        <field name="rgname" nextRow="false" fieldType="EX" readOnly="true" clientDefault="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
     
        
        
       
      </fields>
    </form>
		<form tabPageIndex="1" gravity="MiddleLeft" height="200" columns="140,120,240" >
      <text v="Thông tin cá nhân" e="Personal information"></text>
      <fields>
	      <field name="dien_thoai" label="1" field="2"  importable="80">
          <text v="Điện thoại" e="Phone"></text>
        </field>
       
        <field name="e_mail" label="1" field="2" importable="90">
          <text v="Email" e="Email"></text>
        </field>
       <field name="dia_chi" label="1" field="-" importWidth="250" importable="30">
          <text v="Địa chỉ" e="Address"></text>
        </field>
		<field name="ngay_sinh" dataType="D" label="1" field="1" >
          <text v="Ngày sinh" e="Date of birth"></text>
        </field>
		 <field name="noi_sinh" label="1" field="-" importWidth="250" importable="30">
          <text v="Nơi sinh" e="Date of birth"></text>
        </field>
      </fields>
    </form>
	   <form tabPageIndex="2" gravity="MiddleLeft" height="320" columns="120,120,240" >
      <text v="Khai báo CMND" e="Declare ID card"></text>
      <fields>
        <field name="cmnd_so" label="1" field="1" allowBlank="false" fieldType="PK" >
          <text v="Số chứng minh" e="ID code"></text>
        </field>
		<field name="cmnd_ngay_cap" dataType="D" label="1" field="1" >
          <text v="Ngày cấp" e="Date Range"></text>
        </field>	
		<field name="cmnd_noi_cap" label="1" field="-" importWidth="250"  importable="85">
          <text v="Nơi cấp" e="Issued by"></text>
        </field>
		<field name="ma_gt" dataType="B" clientDefault="true" label="1" field="[60]"  inactivate="true" importable="25">
          <text v="Giới tính" e="Sex"></text>
        </field>
		 
		 
      </fields>
    </form>
		 
	  <form tabPageIndex="3" gravity="MiddleLeft" height="320" columns="120,120,240" >
      <text v="Phòng ban" e="Declare ID card"></text>
      <fields>
        <field name="phong_ban" label="1" field="1" allowBlank="false" >
          <text v="Phòng ban" e="ID code"></text>
        </field>
		<field name="ma_cv" viewType="Lookup" label="1" field="[120] ">
        <text v="Chức vụ" e="Position"></text>
        <viewInfo lookupType="One" lookupId="dmchucvu" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_cv" lookupInfo="dmchucvu|ma_cv|ten_cv" importCheck="@@DF and z.status=1"/>
        </field>
        <field name="ten_cv" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
           <text v="" e=""></text>
        </field>
		
		<field name="ma_bp" viewType="Lookup" label="1" field="[120] ">
        <text v="Bộ phận" e="Position"></text>
        <viewInfo lookupType="One" lookupId="dmbophan" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_bp" lookupInfo="dmbophan|ma_bp|ten_bp" importCheck="@@DF and z.status=1"/>
        </field>
        <field name="ten_bp" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
           <text v="" e=""></text>
        </field>
		
		 <field name="so_nam_lv" dataType="N" label="1" field="1" allowBlank="false" >
          <text v="Số năm làm việc" e="ID code"></text>
        </field>
		 
		 
      </fields>
    </form> 
  </forms>

  &DefaultButton;

<js>
    <text>
      <![CDATA[<enc>NM/V4VMDA+gtz9y2xLcpAb3gA/ulH6hPera+vaL3ifSJIJgPXG7jBYOJwsgllSfa79NGsQ849xOViQYW9eZtIm8uCFl+futTpyQJkRWAtKF7pFfVsEw1QDv0CFKXlOJ7BhpvcBal4LBYs+uvZMYM7/SpsB6dUZphgFMJDhrTLMemQ/LUjOqRyAQJdoon00kxUMQokm139FDkbb3YharSamtjNbzrNi7hN4QREDGEHykMU51kmPF2mU8kdH5H9DpqyHN1+/9Izg1qoxnY5D3TY4b4aeSavxYh870dcfTk5J4hh8cYjMMvDdpIVsTpmGNAswFxfWXXRe4mtVTmiqKkGuxoWMTLnnEJXRmiPhwca8I5h53jOSZYEg8I8T7HEnesjhbr9tofeOjmbffUAEWufDFglCXrNR8sF8xHrR+nkSczDH28oEbpF53q729wyE5FcHuLNZFng1Zt4/AE/WdXKxYYGNkvPf5ZV4zp5SmIx3nRmS7kEVK4gYLcl3bN8hUXAqaW/sO1C8XTtyJ4XwJAXMEDcnGzazmIWRTJv2Dep+E15fF1FeT0KQj+t86zZ4qy9igUw3X7jC+r7eDb3LwlUua08NEtj/IJMFEgeMAigEWHX+njn8T88/0/+lzJxij75QggWp1mjJAW359F7kNKRLGRGOqZEFYQBZys+PY0MgA8UoWwWuo1FldJcm9yV5arFJx4xEfE4CDrBcYXuIHz66rpwXELzpl4hlub0MZT/ery9eGLBnHUHNK++HO0Mx34JsDtKLGQfMBSudNvMsqufcXAmi5WPoX/o40REc/2lbw=</enc>]]>
		
    </text>
  </js>
   <css>
		<text>
		  <![CDATA[<enc>YkWQBTDGylCtyJwcHZMp4kHLaONbdUrMufRzgaQUdjNxeT0rAZym+jQ4M7vO1gWzo0bWpKItzzejK9ykQo3kwEbhH4VumKNe6JPV1OwNUNJRRcLjI8XfEUv8X79QJwbMKTvLTAZk8AsvlVRAfcHLPA==</enc>]]>
		</text>
  </css>

  <script>
    
    <query>
      <text>
        <![CDATA[<enc>iW+MwpbVYdGJDu1NI8DWbc2QH5/ih5IiZDN8dadcQvE5F/7Hgt04DhdFiFVckgKS0Hj/cC9o5NzNpHZPK/pgGQWlfwTH3cfjWNvqVD7y7K4fa/b42SH+g0Q43mpetD9QJHsyZX7m2Hyeawppt4LlzG7N+IiAmCl6XfBtmKOAdBlLbtGYM7d0aEy5zPC9cZWiC9XNL1XDRXqaohL+Xg7N+sluPvGkjjxIb9/SSTYlN/N9IqhyAXNcnB4ljQjKv/sr2TRgdSXS81j9d6ff1ZlaZHJCuxTzJfLz64X+0PA8XTtbC4KTNmFBjbrtsjDqX5Nql6+A5h7xJhuqotUNU7+oon4jC/LaX3l3hq9Bx6WIRbWFjzWnhOr5sZdXMYbhLAQs</enc>]]>
      </text>
    </query>
    <inserting>
      <text>
        <![CDATA[<enc>/T/6v4fr7JtuEWROY5bEopFO1HCnIjtZjFzzDG3F9/vEkIfRrRIYFlNT+1c2A+G4DGK3P1V1ru+z1kGXJXjR1VzP1TAM3KziUQ39S5UPAFO5TtFkd+A7rjU9Cj84+ron+NnAUl09CZS+jY4xst+ifUx/y0L2N86LSRXXWB0b2jLk9z1JyBTjpFwFo33O8/V92Jll9ZnIKloIczVnEYCl2/5Q4n5X9mE3/5atjZjvFut8hbyHb/wqOO6O7YgIZzpT</enc>]]>
      </text>
    </inserting>
    <aftersave>
      <text>
        <![CDATA[<enc>YO31cmfNssAd7SEkSV49zfungVLGueDfBsW5mNU0e2Y5CAM61qIYPDpKFj8qMkWAglNkKBdXZbVOHqNlr3pNqtT0j2nFPR+JUAIvPjQDTTWepj4Zt1QeJ7freiFVK1mcZE/QMQ1wX69GfnBfWZ0rCL+6mSoO3StvpNHSrWdbxt6QwNvCIKfL6UCe7hYKnR/U</enc>]]>
      </text>
    </aftersave>


    <importing>
      <text>
        <![CDATA[<enc>sxD5Swu0R4mcxEHdwcy2yi46ZbQRyi0uEDh1tGVfNVOBZJeZZHskWnswm55XGvVMtI3kJxA271ZmaBNQ7vOM1svvmG7tRC9SwsrihBxLjQw=</enc>]]>
      </text>

    </importing>
  </script>

  <messages>
    <message val="codeExistsNewMsg">
      <text v="Mã nhân viên đã tồn tại trong danh mục nhân viên." e="The record already exists."/>
    </message>
    <message val="codeExistsEditMsg">
      <text v="Mã nhân viên đã tồn tại trong danh mục nhân viên." e="The record already exists."/>
    </message>
    <message val="taxtCodeExists">
      <text v="Mã số thuế đã tồn tại trong danh mục, &lt;span class='Highlight'&gt;Lưu ý:&lt;/span&gt; hệ thống vẫn lưu dữ liệu vừa cập nhật." e="The tax code is already exists, &lt;span class='Highlight'&gt;Warning:&lt;/span&gt; Updated data has been saved."/>
    </message>
  </messages>
</dir>