<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmnv" table="dmnv" fieldKey="ma_nv" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục nhân viên" e="List of employee"></title>
  <title0 v="Mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120,120,120,120,360" >
      <fields>
	     <field name="user_id" label="" field="1" dataType="I" hidden="true" fieldType="PK" >
          <text v="" e=""></text>
        </field>
	    <field name="ma_nv" format="U" label="1" field="1" allowBlank="false" viewType="AutoIncrease" fieldType="PK"  >
          <text v="Mã nhân viên" e="Employee code"></text>
        </field>
		<field name="ten_nv"  label="1" field="-" allowBlank="false" >
          <text v="Họ và Tên" e="Name"></text>
        </field>
		<field name="ngay_sinh" dataType="D" label="1" field="1" allowBlank="false" >
          <text v="Ngày sinh" e="Date of birth"></text>
        </field>
		<field name="noi_sinh" label="[60]" field="[180]" nextRow="false">
          <text v="Nơi sinh" e="Place of birth"></text>
        </field>
		<field name="cmnd_so" label="1" field="[120]" allowBlank="false">
          <text v="Số CMND &lt;a onclick='getCMND(this);'&gt;(Kiểm tra)&lt;/a&gt;" e="Identity card &lt;a onclick='getCMND(this);'&gt;(Check)&lt;/a&gt;"></text>
        </field>
		<field name="cmnd_noi_cap" label="[60]" field="[180]" nextRow="false" allowBlank="false">
          <text v="Nơi cấp" e="Issued by"></text>
        </field>
		<field name="cmnd_ngay_cap" dataType="D" label="1" field="1" allowBlank="false">
          <text v="Ngày cấp" e="Date Range"></text>
        </field>	
		
		<field name="cmnd_ngay_hh" dataType="D" label="1" field="1" nextRow="false" allowBlank="false" >
          <text v="Ngày hết hạn" e="Expiration date"></text>
        </field>
		<field name="gioi_tinh" label="1" field="1" viewType="Combobox" allowBlank="false">
          <text v="Giới tính" e="SEX"></text>
		   <viewInfo>
            <options>
              <option val="Nam ">
                <text v=" Nam" e="Male"></text>
              </option>
              <option val="Nữ">
                <text v="Nữ" e="Fale Male"></text>
              </option>
			   <option val="0">
                <text v="Khác" e="Fale Male"></text>
              </option>
            </options>
          </viewInfo>
        </field>
		<field name="ket_hon" label="1" field="1" viewType="Combobox" allowBlank="false" nextRow="false">
          <text v="Tình trạng hôn nhân" e="Get married"></text>
		   <viewInfo>
            <options>
              <option val="1">
                <text v="Đã kết hôn" e="Married"></text>
              </option>
              <option val="0">
                <text v="Độc thân" e="Not married"></text>
              </option>
			  <option val="2">
                <text v="Goá" e="Not married"></text>
              </option>
			   <option val="3">
                <text v="Ly hôn / ly thân" e="Not married"></text>
              </option>
            </options>
          </viewInfo>
        </field>
		<field name="ma_qg" viewType="Lookup" label="1" field="[120]" allowBlank="false">
           <text v="Quốc tịch" e="Nationality"></text>
           <viewInfo lookupType="One" lookupId="dmquocgia" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_qg" lookupInfo="dmquocgia|ma_qg|ten_qg" importCheck="@@DF and z.status=1"/>
        </field>
        <field name="ten_qg" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
           <text v="" e=""></text>
        </field>		
		<field name="ma_dt" viewType="Lookup" label="1" field="1" allowBlank="false">
          <text v="Dân tộc" e="Ethnic"></text>
          <viewInfo lookupType="One" lookupId="dmdantoc" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_dt" lookupInfo="dmdantoc|ma_dt|ten_dt" importCheck="@@DF and z.status=1"/>
        </field>
        <field name="ten_dt" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="[200]" aliasName="cast('' as nvarchar(4000)) as ">
           <text v="" e=""></text>
        </field>		
	    <field name="ma_tg" viewType="Lookup" label="1" field="1" allowBlank="false">
          <text v="Tôn giáo" e="Religion"></text>
          <viewInfo lookupType="One" lookupId="dmtongiao" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_tg" lookupInfo="dmtongiao|ma_tg|ten_tg" importCheck="@@DF and z.status=1"/>
        </field>
        <field name="ten_tg" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
           <text v="" e=""></text>
        </field>
		
		
		

		<field name="dc_tt" label="1" field="-" allowBlank="false">
          <text v="Địa chỉ tạm tr" e="Permanent address"></text>
        </field>
		<field name="dien_giai" label="1" field="-" rows="3" allowBlank="false">
          <text v="Tóm tắt cơ bản" e="Permanent address"></text>
        </field>
		 	
	    <field name="status" viewType="Combobox" inactivate="true" label="1" field="[150]" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
	 	     
      </fields>
	  
    </form>
	  <form gravity="TopRight" columns="120,120" >
      <fields>
         <field name="image_id" label="[100]" field="1" viewType="Image">
          <text v="" e=""></text>
          <viewInfo fileFieldId0="user_id" fileGroup="SysUser" fileExtension="jpg,png" maxFileSize="10240" maxFileCount="1"></viewInfo>
        </field>
       
      </fields>
    </form>
    
	  

	
	
	<form tabPageIndex="1" gravity="MiddleLeft" height="250" columns="140,120,120,120,240">
      <text v="Liên hệ" e="Curriculum problem"></text>
      <fields>
		<field name="dt_mobil" label="1" field="1" allowBlank="false" >
          <text v="Điện thoại " e="Mobile phone"></text>
        </field>
		<field name="email" label="1" field="[200]">
          <text v="Email" e="Email"></text>
        </field>
		<field name="dia_chi" label="1" field="-" allowBlank="false">
          <text v="Địa chỉ tạm trú" e="Adress"></text>
        </field>
		<field name="ma_ttp" viewType="Lookup" label="1" field="[120]">
           <text v="Quê quán" e="Position"></text>
           <viewInfo lookupType="One" lookupId="dmttp" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_ttp" lookupInfo="dmttp|ma_ttp|ten_ttp" importCheck="@@DF and z.status=1"/>
        </field>
        <field name="ten_ttp" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
           <text v="" e=""></text>
        </field>
      </fields>
    </form>
	<form tabPageIndex="2" gravity="MiddleLeft" height="250" columns="140,120,120,120,240">
      <text v="Học vấn" e="Curriculum problem"></text>
      <fields>
       <field name="ma_hv" viewType="Lookup" label="1" field="1">
			<text v="Trình độ học vấn" e="Part"></text>
			<viewInfo lookupType="One" lookupId="dmtdhv" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_hv" lookupInfo="dmtdhv|ma_hv|ten_hv" importCheck="@@DF and z.status=1"/>
        </field>
        <field name="ten_hv" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
           <text v="" e=""></text>
        </field>
		<field name="ma_cn" viewType="Lookup" label="1" field="1">
			<text v="Ngành" e="Specialized"></text>
			<viewInfo lookupType="One" lookupId="dmcn" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_cn" lookupInfo="dmcn|ma_cn|ten_cn" importCheck="@@DF and z.status=1"/>
        </field>
        <field name="ten_cn" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
           <text v="" e=""></text>
        </field>
		<field name="chuyen_nganh" label="1" field="[200]" >
          <text v="Chuyên ngành" e="Specialized"></text>
        </field>
		<field name="xep_loai" label="1" field="1" >
          <text v="Xếp loại" e="Classification"></text>
        </field>
		<field name="ngay_tn" dataType="D" label="1" field="1" nextRow="false">
          <text v="Ngày tốt nghiệp" e="Graduation Date"></text>
        </field>
		<field name="ma_nn" viewType="Lookup" label="1" field="1">
			<text v="Ngôn ngữ khác" e="Languages"></text>
			<viewInfo lookupType="One" lookupId="dmngoaingu" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_nn" lookupInfo="dmngoaingu|ma_nn|ten_nn" importCheck="@@DF and z.status=1"/>
        </field>
        <field name="ten_nn" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
           <text v="" e=""></text>
        </field>
		<field name="ma_cc" viewType="Lookup" label="1" field="1">
			<text v="Chứng chỉ" e="Languages"></text>
			<viewInfo lookupType="One" lookupId="dmccnn" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_cc" lookupInfo="dmccnn|ma_cc|ten_cc" importCheck="@@DF and z.status=1"/>
        </field>
        <field name="ten_cc" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
           <text v="" e=""></text>
        </field>
      </fields>
    </form>
	
	
   
	<form tabPageIndex="3" gravity="MiddleLeft" height="250" columns="140,120,120,120,240">
      <text v="Thông tin người thân" e="info"></text>
      <fields>
		<field name="ten_cha" label="1" field="[200]">
          <text v="Tên cha" e="Adress"></text>
        </field>
		<field name="ngay_sinh_cha" dataType="D" label="1" field="1" nextRow="false">
          <text v="Ngày sinh" e="Date of birth"></text>
        </field>
		<field name="ten_me" label="1" field="[200]">
          <text v="Tên mẹ" e="Adress"></text>
        </field>
		<field name="ngay_sinh_me" dataType="D" label="1" field="1" nextRow="false">
          <text v="Ngày sinh" e="Date of birth"></text>
        </field>
		<field name="ten_ae" label="1" field="[200]">
          <text v="Tên anh/chị/em" e="Adress"></text>
        </field>
		<field name="ngay_sinh_ae" dataType="D" label="1" field="1" nextRow="false">
          <text v="Ngày sinh" e="Date of birth"></text>
        </field>
		<field name="ten_vc" label="1" field="[200]">
          <text v="Tên vợ/chồng" e="Adress"></text>
        </field>
		<field name="ngay_sinh_vc" dataType="D" label="1" field="1" nextRow="false">
          <text v="Ngày sinh" e="Date of birth"></text>
        </field>
		<field name="dc_gd" label="1" field="-" rows="3">
          <text v="Địa chỉ gia đình" e="Adress"></text>
        </field>
 
      </fields>
    </form>
	    <form tabPageIndex="4" gravity="MiddleLeft" height="0" columns="120,120,360" >
      <text v="Đính kèm" e="Attach Files"></text>
      <fields>
        <field name="xfile" label="1" field="2" viewType="File" fieldType="EXParam">
          <text v="Chọn files" e="Attach Files"></text>
          <viewInfo fileFieldId0="id" fileGroup="LX1" fileExtension="*" maxFileSize="10240" maxFileCount="10"></viewInfo>
        </field>
      </fields>
    </form>
	
  </forms>
    &DefaultButton;
  <js>
    <text>
     <![CDATA[<enc>efUu2HkaY7xpeSPVwzklGXtLAziuGXh3bYkkQSNg5o/Qns1ooUOyP+xLcci7uwvEKgK8toYMHzNgMUelQ7wVRViKEVtTP25MIa1fezzVanmvTVe7ftzZJtkcVuhx+mvWJ1l+pOV4ifjTY1fFKPZrw0BjvnfWeGv9h/+lVZAnQHMQ+rLdSRl5HxC3h06g9/KqqXHpoIAK/7nVlCX1PBLXPcbFW4i333mk8i0Q7EKnc0fGuygawSx/f8/N6Acc31JAMC6kForEli8rEAblgzdrT29lrzwewBwlEo2BEXKcWhLaGH9v/JnmaQ2Gp8RUU6oWc/Ctsb4SBlw30aj16invkNR88nsgcuM1TYQfmIKBLn2nzDrPkfSmSB/N/MuVLklyi5eUEo8COmDZ6deAJdTidiC9Os3C9/6Ll8+dKCvH2dz6YdCeKXeJc+fn1mrCNOFsmc8sZK0JqmDs0qTbAQqT6bqwZHTuYg1OfCXCjd9+QcTvmf10mtu7wwykBttEvesWdVfvywQapQICWJ6LWbgT4gmKZkpD6xvAn2fGWAJIRkP2qAxspZXPz9zb7m+Vd06a1XT8brluCLzQYWqS/UhViWRBL8Lcxni+EGVN8vR7/qFM2q4lIfMNZIMzoRYBqtxRitf3kUCYcyhEeST+1Mg5uM/UtohKX6oVYDZV3bUOraLyItbeee6w0uhW4XJF+wFyGWCzK9NjFwnR1xVTfTKIEWzJxYZgdvvCG7YOXJRYc/CWXQ/mGAuM2uyGTX8qvFd4nitu9ajkQH44vBiMWynw0yBVavfwm+gfiSqgQ9XFAovTDJn2TkSKck+/WKBtSqCKHDM7jvkJs+Ue9dH5oWaZo0NPElFGG05fB/7ZQ7Ma4t0eECmxmZxEIA3J2K8/he4q</enc>]]>
    </text>
  </js>
 <css>
		<text>
		  <![CDATA[<enc>YkWQBTDGylCtyJwcHZMp4kHLaONbdUrMufRzgaQUdjPGB5deqq8kFykwzWKhejn73Dw1LadfhGY7KqQfXhhbnyQacPjAR0zoaVFNz5BMqVk+YRNcP4IeeFsoTbGUZT3wI9yfACOV0waSsxd7Zkowgg==</enc>]]>
		</text>
  </css>
  <script>
    <declare>
      <text>
        <![CDATA[<enc>kgNieZitFtjbYbV1eT4v7RNUl/HxykdcW2sc3yYX+zXOLrwLOzrIBWfSq5Cu3Z+eNUnUGSEgyChWT0W49YD7NXBw6eW4fLczByMyEHg2bzABV9UKp+f8z96t4TBLIynOMe3jyU3iReAfjqfpqh2yVDIR64qMb5DdYTKNERS0YksXGPlUsSNxbREM7b4oeHObnrhKM+JN7E9UliN9BhmdF7yzcmImuMpAz5bC76n0wApQpzB6/gEzq/ICvnHhGCLe</enc>]]>
      </text>
    </declare>
  </script>

</dir>