<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmpb" table="dmpb" fieldKey="ma_pb" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục phòng ban" e="List of Departments"></title>
  <title0 v="Thêm mới" e="Create New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
        <field name="ma_pb" format="U" label="1" field="1" allowBlank="false" fieldType="PK" importable="5" >
          <text v="Mã phòng ban" e="Department Code"></text>
        </field>
        <field name="ten_pb" label="1" field="-" allowBlank="false" importable="10" >
          <text v="Tên phòng ban" e="Department Name"></text>
        </field>
        <field name="ten_pb2" label="1" field="-" importable="15" >
          <text v="Tên khác" e="Other Name"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" valueDefault="1" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>OIvoYpbA2cjnWLO6Y4m5qAOaoqU11VMluHX+feHLyhA3R1FoT8x9/icI6JtmhoYC1eWgqEOR7ukKyjGISFS8O2qePUNdAN4382EXRqnSv2mzeLhAppsdxJ84+DzZ67AISISDrSggnCQrEuETxMbeTi0n1C4kpEQtA6b25h4y6z1PRMhnqV5Li9/Vw6QMIchiQuDSE1tMYMLbefMns+K/KwBfABJD2VNla7N7it+FGy2jkJx7Ir75Pd/9IWG8zVbyuM4xtEVFnja9Bhky4V0wSiWH+zU9KwzSVfSm/zq9gdJkD+XUbheOsG9r5pRYujYYhdV95fobMm2qy7hirVthqw==</enc>]]>
    </text>
  </js>
  
  <css>
	<text>
	  <![CDATA[<enc>/T0x+X5J8VnLtXSs8xERB1iizBHxQmUovXeEmWW/qu9C0N8zNXvDnfU5p8pN3PzRSWayCJvv0/WVd50FeJGDGAuNheWfZ7D2syHDUy0ozVgAyL89BNY76LYSx13uQ80CEu/ow9r3lRTnL7p+cnh2xA==</enc>]]>
	</text>
  </css>
  
  <script>
	<importing>
      <text>
        <![CDATA[<enc>PDeYaSq5D3THjzUfjXLnuOov+zRPCu/HsQ7cYLJ9+NUbtW4WBDcym9s/zoBHUkNI</enc>]]>
      </text>
    </importing>
  </script>
  
  <messages>
	<message val="codeExistsNewMsg">
		<text v="Mã phòng ban đã tồn tại trong danh mục, vui lòng chọn một mã khác." e="The department code already exists in the catalog, please choose a different code."/>
	</message>
	<message val="codeExistsEditMsg">
		<text v="Mã phòng ban đã tồn tại trong danh mục, vui lòng chọn một mã khác." e="The department code already exists in the catalog, please choose a different code."/>
	</message>
  </messages>

</dir>