<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>

<dir id="dmphi" table="dmphi" fieldKey="ma_phi" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục phí" e="Fee List"></title>
  <title0 v="Mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
        <field name="ma_phi" format="U" label="1" field="1" allowBlank="false" fieldType="PK" >
          <text v="Mã Phí" e="Code"></text>
        </field>
        <field name="ten_phi" label="1" field="-" allowBlank="false">
          <text v="Tên phí" e="Description"></text>
        </field>
        <field name="ten_phi2" label="1" field="-" allowBlank="true">
          <text v="Tên khác" e="Other name"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>T5Nuk0XwnW0VlRYHOIM5VXhKO7/eOS+JOgvPzcIet9bQH2Sp9mX52HQ2UTWU+nY/QHSg35zzHmMl2biNpq41jBHSOL69z1Qg1zQJzRR7hVfXpkP5OFZfnXzp4KTzq4hGQB5HcZI78xafwrAFljs+vJXDgeYtmJkL4BETwpHsi7njj42PnwNgLr51jRwTTt6T</enc>]]>
    </text>
  </js>

  <script>
    <declare>
      <text>
        <![CDATA[<enc>hxQPm/hYhpvPifcenBxj7nfT+X4T8oXvYmZx4Kpwn3fRRVZY+foYIow2vt1OHdzq0lG6PkDpvnlKR1ei3AR28UkawCxswedTww8YMZ/ax/1/BVJZ6K0wvLOosliedaWZm23TaYHZ9fEWFuSfo8O1KnRSxwaalptnv4u5mkJ8TMGVg1mHiiZtkiZkYc7uozfsyKNWYn0GXMUGmfJOYG84SBZRHmRYuUcDP+cKZFfkTDY=</enc>]]>
      </text>
    </declare>
  </script>

</dir>