<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmphuongxa" table="dmphuongxa" fieldKey="ma_phuongxa" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục phường/xã" e="Ward/Commune List"></title>
  <title0 v="Thêm mới - phường/xã" e="New - Ward/Commune"></title0>
  <title1 v="Sửa - phường/xã" e="Edit - Ward/Commune"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
		<field name="unit_id" dataType="I" hidden="true" readOnly="true" inactivate="true" label="1" field="1" importable="-1">
		  <text v="" e=""></text>
		</field>
        <field name="ma_phuongxa" format="U" label="1" field="1" allowBlank="false" fieldType="PK" importable="5">
          <text v="Mã phường/xã" e="Ward/Commune Code"></text>
        </field>
        <field name="ten_phuongxa" label="1" field="-" allowBlank="false" importable="10">
          <text v="Tên phường/xã" e="Ward/Commune Name"></text>
        </field>
		<field name="ten_phuongxa2" label="1" field="-" allowBlank="true" importable="15">
          <text v="Tên tiếng anh" e="English Name "></text>
        </field>
		<field name="ma_loai" viewType="Combobox" inactivate="false" label="1" field="1" nextRow="true" importable="20" >
		  <text v="Mã loại" e="Type Code"></text>
		  <viewInfo>
			<options query="select ma_loai, ten_loai%l from dmloaiphuongxa where status = 1 ">
			</options>
		  </viewInfo>
		</field>
		<field name="ma_ttp" viewType="Lookup" label="1" field="1" clientDefault="true" importable="25">
          <text v="Tỉnh thành" e="Province/City"></text>
          <viewInfo lookupType="One" lookupId="dmttp" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_ttp" lookupInfo="dmttp|ma_ttp|ten_ttp" importCheck="@@DF and z.status=1" />
        </field>
        <field name="ten_ttp" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as " clientDefault="true">
          <text v="" e=""></text>
        </field>
		<field name="status" viewType="Combobox" inactivate="true" label="1" field="2" valueDefault="1" nextRow="true" importable="-1" >
		  <text v="Trạng thái" e="Status"></text>
		  <viewInfo>
			<options query="select ma_tt, ten_tt%l from dmttsd where status = 1 ">
			</options>
		  </viewInfo>
		</field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>sIXGRlalTPXlp8fIk0SPXQsF1ToMm15spHXl6E+NlkH57SifMDTCTZnLO93CXueVptTvBgFHCzNfxVaheZvGHbFvJms6fyVicOCb77ou1bZLjm5oedfiMk5EJ9p2iwiDE/+FTAxnSw1nltYjpzWdFtivcwtG92pJ+PpFQ+pHeIrgsj/7rdAjS9c4+jbH+kg2SqYshUa6KKEJGDwmWPa/5SsBhCgCTzoGNEgrUliOEjBsLSh79XEE8b5voxQRkh/8UXYZIf1BhNUxSVDf4jOj5lphPokjN1qG48sfSgYOX8NcF/TrvSy1I5SnRHNOwP0f71iBjDf9vzh+y0ucLnRZ8g==</enc>]]>
    </text>
  </js>
  <css>
		<text>
		  <![CDATA[<enc>YkWQBTDGylCtyJwcHZMp4lZsTBMUUzGyXkCNhkU8H8mSE9QAITcXEyUfamnM6ip19OQU8NIEoO6M6k2NvP2eQVM9OocbuTuwxk+7NEoNdTS1MTVCn97W8IZMT7p9P8hU</enc>]]>
		</text>
  </css>

	<script>
		<query>
		  <text>
			<![CDATA[<enc>GJgBVkOd9xy3In+SUACpOOdXdTQbLjDNG098RVYG+mqJrACGNi8MwNsRrtmQkuMIYyR65+M+8FdE2nQkBtdUjjGtkBSGsDqbRbA3vrYN89ZzUnQVJ+W1/9AMkiZ8xTjPYAdSbE6TNHswawXCA3Q7ZKpywgArBHY6CKMo02cq6Ek=</enc>]]>
		  </text>
		</query>
		<updated>
		  <text>
			<![CDATA[<enc>sxD5Swu0R4mcxEHdwcy2ynVkJ6IiRfsuHiDzDrC78ELIJg2k4xX5PxEITwgSuDtWSiTOU3sqnIo/Bv0T8e877uKHW6bIEuTFdpbPdQB+xElll2tzxh9iUOpwbot+jXTZNKo5+n5Fy+aXD8VrO81PEw==</enc>]]>
		  </text>
		</updated>
		<inserting>
		  <text>
			<![CDATA[<enc>/T/6v4fr7JtuEWROY5bEog4q37AdyKX5y50iwuf8o+kQ/cMLdjO5yBgIja/EXDIb67gjtJCgsvsoKVHnH40ASfHmT/5Pyqyz9fEF+eXazaeFq1QdO25I17j8uqKw4sm7PDDzWS+uYkqIWo1FmMQqY1vwSihUQwhC3DMwYBlMdqW/7I05kvZGgi3lyKQDrJ1gd1u3eDHWrXNvOq+fBosahfSLln2pO8chassI1khVi2Brg84FNLLprzwizWkmE7Kk</enc>]]>
		  </text>
		</inserting>
		<importing>
			<text>
			<![CDATA[<enc>sxD5Swu0R4mcxEHdwcy2yi46ZbQRyi0uEDh1tGVfNVOBZJeZZHskWnswm55XGvVMZq7vIrj1gngY5x8IJuKO1pkyFlxS8pifsEwHrhrpEjg=</enc>]]>
			</text>
		</importing>
	</script>
  <messages>
    <message val="codeExistsNewMsg">
      <text v="Mã phường/xã đã tổn tại." e="Ward/Commune code already exists."/>
    </message>
    <message val="codeExistsEditMsg">
      <text v="Mã phường/xã đã tổn tại." e="Ward/Commune code already exists."/>
    </message>
  </messages>
</dir>