<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>

<dir id="dmpldc" table="dmpldc" fieldKey="ma_pl" transaction="true" tryCatch="true" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục phân loại dân cư" e="Population Classification List"></title>
  <title0 v="Thêm mới - hu phố" e="New - Population Classification List"></title0>
  <title1 v="Sửa - hu phố" e="Edit - Population Classification List"></title1>

  <forms>
	<form gravity="TopLeft" columns="120,120,120,120,120" >
		<fields>
			<field name="unit_id" dataType="I" hidden="true" readOnly="true" inactivate="true" label="1" field="1" importable="-1">
			  <text v="" e=""></text>
			</field>
			<field name="ma_pl" label="[120]" field="[120]" allowBlank="false" format="U" disabled="false" fieldType="PK" importable="5" >
				<text v="Mã phân loại dân cư" e="Population Classification Code"></text>
			</field>
			<field name="ten_pl" label="[120]" field="-" allowBlank="false" disabled="false" importable="10">
			  <text v="Tên phân loại dân cư" e="Population Classification Name"></text>
			</field>
			<field name="ten_pl2" label="[120]" field="-" allowBlank="true" disabled="false" importable="15">
			  <text v="Tên tiếng anh" e="English Name"></text>
			</field>
			<!-- <field name="ma_ttp" viewType="Lookup" label="1" field="1" allowBlank="true" importable="15"> -->
			  <!-- <text v="Mã tỉnh/thành phố" e="Province/City Code"></text> -->
			  <!-- <viewInfo lookupType="One" lookupId="dmttp" lookupKey="status=1" lookupRef="ten_ttp" lookupCheck="1=1" lookupInfo="dmttp|ma_ttp|ten_ttp" importCheck="@@DF and z.status=1"/> -->
			<!-- </field> -->
			<!-- <field name="ten_ttp" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" hidden="false" label="" field="[240]" aliasName="cast('' as nvarchar(4000)) as "> -->
			  <!-- <text v="" e=""></text> -->
			<!-- </field> -->
			<!-- <field name="ma_phuongxa" viewType="Lookup" label="1" field="1" allowBlank="true" importable="20"> -->
			  <!-- <text v="Mã phường xã" e="Commune Code"></text> -->
			  <!-- <viewInfo lookupType="One" lookupId="dmphuongxa" lookupKey="status=1 and ma_ttp = ![ma_ttp]!" lookupRef="ten_phuongxa" lookupCheck="1=1" lookupInfo="dmphuongxa|ma_phuongxa|ten_phuongxa" importCheck="@@DF and z.status=1"/> -->
			<!-- </field> -->
			<!-- <field name="ten_phuongxa" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" hidden="false" label="" field="[240]" aliasName="cast('' as nvarchar(4000)) as "> -->
			  <!-- <text v="" e=""></text> -->
			<!-- </field> -->
			<field name="status" viewType="Combobox" inactivate="false" label="1" field="2" valueDefault="1" nextRow="true" importable="-1" >
			  <text v="Trạng thái" e="Status"></text>
			  <viewInfo>
				<options query="select ma_tt, ten_tt%l from dmttsd where status = 1 ">
				</options>
			  </viewInfo>
			</field>
      </fields>
    </form>
</forms>

&DefaultButton;

<js>
    <text>
  <![CDATA[<enc>ZZzljc7y7fui08CO7MBZnJdy03yehEaDJaHZU6qsCGGv6o6dBxyYOEG0tkNIaUy1DZ11qIm7p5CEwWYjMMwXy7fSb3WDmDuCz2JEuzm9dR7NppLTD+vNKDveq32RHiPUy6t/kX+Xq4BbkzzC+HyYF38snRVfOsP7UzQoGcfN5iVqAAcrfogw5bFpvlhnmTymB1L1iC2qN2WcebbUWnHl7Q5OfZvJjjPA6Jjj52aXi8V2RBpaHZGjyBhumk0oCO+EAoK7uVHwWazR6+GU1D2PtmVtWLBlMDSXZejZerghbIM2F5KYCsNZZch0d57lNqf4NsfNx/3z1x4BEwzj0L1GIA==</enc>]]>
    </text>
  </js>
	<css>
		<text>
			  <![CDATA[<enc>5CMWIYgWe2auffADL9RxFg1DfUmi6+Zx6nOT+KI+oV9mDCmkfew5cqb6jmADlFCaksZWmVXwYBzAEeyVsV27XaLjtwWNSNdqfu9TA/VVrDjddTRF3dfN2X3VJZ10BKEKiB4jTpPnuKQ5iktU7t78bacRWyz6b7s9jfzzY/zBmnRnVbPtlRxuKJMOWYKjgOoE</enc>]]>
		</text>
	</css>
	<script>
		<query>
		  <text>
			<![CDATA[<enc>GJgBVkOd9xy3In+SUACpOOdXdTQbLjDNG098RVYG+mqJrACGNi8MwNsRrtmQkuMIYyR65+M+8FdE2nQkBtdUjjGtkBSGsDqbRbA3vrYN89ZzUnQVJ+W1/9AMkiZ8xTjPYAdSbE6TNHswawXCA3Q7ZKpywgArBHY6CKMo02cq6Ek=</enc>]]>
		  </text>
		</query>
		<updated>
		  <text>
			<![CDATA[<enc>sxD5Swu0R4mcxEHdwcy2ynVkJ6IiRfsuHiDzDrC78ELIJg2k4xX5PxEITwgSuDtWSiTOU3sqnIo/Bv0T8e877uKHW6bIEuTFdpbPdQB+xElll2tzxh9iUOpwbot+jXTZNKo5+n5Fy+aXD8VrO81PEw==</enc>]]>
		  </text>
		</updated>
		<inserting>
		  <text>
			<![CDATA[<enc>/T/6v4fr7JtuEWROY5bEog4q37AdyKX5y50iwuf8o+kQ/cMLdjO5yBgIja/EXDIb67gjtJCgsvsoKVHnH40ASfHmT/5Pyqyz9fEF+eXazaeFq1QdO25I17j8uqKw4sm7PDDzWS+uYkqIWo1FmMQqY1vwSihUQwhC3DMwYBlMdqW/7I05kvZGgi3lyKQDrJ1gd1u3eDHWrXNvOq+fBosahfSLln2pO8chassI1khVi2Brg84FNLLprzwizWkmE7Kk</enc>]]>
		  </text>
		</inserting>
		<importing>
			<text>
			<![CDATA[<enc>sxD5Swu0R4mcxEHdwcy2yi46ZbQRyi0uEDh1tGVfNVOBZJeZZHskWnswm55XGvVMZq7vIrj1gngY5x8IJuKO1pkyFlxS8pifsEwHrhrpEjg=</enc>]]>
			</text>
		</importing>
	</script>
	<messages>
		<message val="codeExistsNewMsg">
		  <text v="Mã phân loại dân cư đã tồn tại trong danh mục." e="The circulation document code already exists in the list."/>
		</message>
	</messages>
</dir>
