<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmplnhvtc1" table="dmplnhvtc1" fieldKey="ma_nh" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục nhóm phân loại vật tư 1" e="Material Group Level 1"></title>
  <title0 v="Thêm mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
        <field name="unit_id" dataType="I" hidden="true" readOnly="true" inactivate="true" label="1" field="1">
          <text v="" e=""></text>
        </field>
        <field name="ma_unit" viewType="Lookup" fieldType="EXParam" readOnly="false" label="1" field="1" allowBlank="false">
          <text v="Đơn vị" e="Unit"></text>
          <viewInfo lookupType="One" lookupId="sysunit" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_unit" lookupInfo="sysunit|ma_unit|ten_unit" />
        </field>
        <field name="ten_unit" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
        <field name="ma_nh" format="U" label="1" field="1" allowBlank="false" fieldType="PK" >
          <text v="Mã nhóm plvt 1" e="MGroup Code 1"></text>
        </field>
        <field name="ten_nh" label="1" field="-" allowBlank="false" fieldType="PK" >
          <text v="Tên nhóm plvt 1" e="MGroup Name 1"></text>
        </field>
        <field name="ten_nh2" label="1" field="-">
          <text v="Tên tiếng anh" e="Other name"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>t5ThNOWSpgjuBz9ULt8tJQzbXeFA/PE8XjjKlwaPW6r9t0JZ76Ndh1QHIrwPGEFg97U7diQBjetSplJ2ttSr9eCDLWpBNFs0thiSjcU4VzfRmBiVtuVsjd8XrchbVsOxXqR4TddpGFqf2Gnh5hiSumi5Stk1PQys1HPaIn0BjG4Wz4LR3f2+IsB7Nrwo5PNi</enc>]]>
    </text>
  </js>
  
  <script>

    <query>
      <text>
        <![CDATA[<enc>9f1U6YGooAD/ahbpLaNsSHyE0S/SratPtk8AShhJK9pekWEt+swZdJ4S2uuv/TawWzZKvNZMYyQK6Ha9bb6amWRENM405VBZzBkYjI6+pXWvbHDyivoUN8QVetaADhpXX3UmgFsg2NJXJ1/YYVPHEVqlKUNeH+322jNJuEnzZHULbNWIC50gM4lbXlMfb3eCSzg/WlhdZZ4SNguHLj8FKpjUP/ntoByx6DaYAFklAm4pSdybV1jHC3wgFi6lKMGOkXW9BbiwxndZR1YOhh9Lqg==</enc>]]>
      </text>
    </query>
    
    <beforesave>
      <text>
        <![CDATA[<enc>GJgBVkOd9xy3In+SUACpOAX36I7LHdlCWd3wW+ezqekhnpBfBkJ3Cq8KmwzZKe7/AYwf3KxQjjmepz89VAdWL7UYyPJysyqX07UV50z8n9w=</enc>]]>
      </text>
    </beforesave>
    
  </script>

  <messages>
    <message val="codeExistsNewMsg">
      <text v="Mã nhóm phân loại nhóm vật tư 1 đã tồn tại." e="Material Group Level 1 code already exists."/>
    </message>
    <message val="codeExistsEditMsg">
      <text v="Mã nhóm phân loại nhóm vật tư 1 đã tồn tại." e="Material Group Level 1 code already exists."/>
    </message>
  </messages>

</dir>