<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>

<dir id="dmplvb" table="dmplvb" fieldKey="ma_pl" transaction="true" tryCatch="true" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh sách văn bản lưu hành" e="List of Circulated Documents"></title>
  <title0 v="Thêm mới - văn bản lưu hành" e="New - cirulated"></title0>
  <title1 v="Sửa - văn bản lưu hành" e="Edit - cirulated"></title1>

  <forms>
	<form gravity="TopLeft" columns="120,120,120,120,120" >
		<fields>
			<field name="unit_id" dataType="I" hidden="true" readOnly="true" inactivate="true" label="1" field="1" importable="-1">
			  <text v="" e=""></text>
			</field>
			<field name="ma_pl" label="[120]" field="[120]" allowBlank="false" format="U" disabled="false" fieldType="PK" importable="5" >
				<text v="Mã văn lưu hành" e="Circulation Document Code"></text>
			</field>
			<field name="ten_pl" label="[120]" field="-" allowBlank="false" disabled="false" importable="10">
			  <text v="Tên văn bản lưu hành" e="Circulation Document Name"></text>
			</field>
			<field name="ten_pl2" label="[120]" field="-" allowBlank="true" disabled="false" importable="15">
			  <text v="Tên tiếng anh" e="English Name"></text>
			</field>
			<field name="tu_so" dataType="N" format="0" label="1" field="1"  allowBlank="true" disabled="false" importable="20">
			  <text v="Ký hiệu từ" e="Word symbol"></text>
			</field>
			<field name="khoang_cach" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" hidden="true" label="" field="[20]">
				<text v="" e=""></text>
			</field>
			<field name="den_so" dataType="N" format="0" nextRow="false" label="1" field="1" allowBlank="true" disabled="false" importable="25">
			  <text v="Ký hiệu đến" e="Incoming symbol"></text>
			</field>
			<field name="loai_ut" viewType="Combobox" nextRow="true" inactivate="false" label="1" field="2" importable="30">
			  <text v="Ưu tiên" e="Priority"></text>
			  <viewInfo>
				<options>
					<option val="0">
						<text v="0 - Không ưu tiên" e="0 - Không ưu tiên"></text>
					</option>
					<option val="1">
						<text v="1 - Ưu tiên" e="1 - Ưu tiên"></text>
					</option>
				</options>
			  </viewInfo>
			</field>
			<field name="status" viewType="Combobox" inactivate="false" label="1" field="2" valueDefault="1" nextRow="true" importable="-1" >
			  <text v="Trạng thái" e="Status"></text>
			  <viewInfo>
				<options query="select ma_tt, ten_tt%l from dmttsd where status = 1 ">
				</options>
			  </viewInfo>
			</field>
      </fields>
    </form>
</forms>

&DefaultButton;

<js>
    <text>
  <![CDATA[<enc>tlfZjva6C3UejB0yyPuv75L5cMU4HypCQ72dJi9ZAU28wpTkJvxigARdOZ4OI+eGBiy9TOt+RaASm/cUZdRZ5EmjC2n6k25hhGrU57pp81dC1E7sRnrNkqqtOX26pIESNKCLz6vIMIaCeRlOwgtBv3rfuKZRpFZR10T+KMcRIrbXBu4S3uYZn3rthnySF+KiMEBSBQPlpMvm5AfdMcXItRiICzjr13ViHGyIAhS/nWch/J3rR0oh3GiUWFRUXQPUqGIZ8q3dKo97XKuCBOBh+UFfeaRs6maCDebuWGgQggeM3kj644Xp3WYERCwFICYu</enc>]]>
    </text>
  </js>
	<css>
		<text>
			  <![CDATA[<enc>GuCkAIqWYq6JWBQ7bTXsyOlGcZj7l0OaR3Dtu+2SSMyzBYmmNkLyBCw6LdiRhzb5beFkIzC8LpoWb2z46EFlYET5X+lHL/r8xBeRykZLWO00PrhD4GQdEm1xYSB4cGk+rQ5/rmwF3PxxqKcnut1q2Gywq/S/WQ8zlIDTIQTkH8AEmdyzW5gsKYe14GuurYdx</enc>]]>
		</text>
	</css>
	<script>
		<query>
		  <text>
			<![CDATA[<enc>GJgBVkOd9xy3In+SUACpOOdXdTQbLjDNG098RVYG+mqJrACGNi8MwNsRrtmQkuMIYyR65+M+8FdE2nQkBtdUjjGtkBSGsDqbRbA3vrYN89ZzUnQVJ+W1/9AMkiZ8xTjPYAdSbE6TNHswawXCA3Q7ZKpywgArBHY6CKMo02cq6Ek=</enc>]]>
		  </text>
		</query>
		<updated>
		  <text>
			<![CDATA[<enc>sxD5Swu0R4mcxEHdwcy2ynVkJ6IiRfsuHiDzDrC78ELIJg2k4xX5PxEITwgSuDtWSiTOU3sqnIo/Bv0T8e877uKHW6bIEuTFdpbPdQB+xElll2tzxh9iUOpwbot+jXTZNKo5+n5Fy+aXD8VrO81PEw==</enc>]]>
		  </text>
		</updated>
		<inserting>
		  <text>
			<![CDATA[<enc>/T/6v4fr7JtuEWROY5bEog4q37AdyKX5y50iwuf8o+kQ/cMLdjO5yBgIja/EXDIb67gjtJCgsvsoKVHnH40ASfHmT/5Pyqyz9fEF+eXazaeFq1QdO25I17j8uqKw4sm7PDDzWS+uYkqIWo1FmMQqY1vwSihUQwhC3DMwYBlMdqW/7I05kvZGgi3lyKQDrJ1gd1u3eDHWrXNvOq+fBosahfSLln2pO8chassI1khVi2Brg84FNLLprzwizWkmE7Kk</enc>]]>
		  </text>
		</inserting>
		<importing>
			<text>
			<![CDATA[<enc>sxD5Swu0R4mcxEHdwcy2yi46ZbQRyi0uEDh1tGVfNVOBZJeZZHskWnswm55XGvVMZq7vIrj1gngY5x8IJuKO1pkyFlxS8pifsEwHrhrpEjg=</enc>]]>
			</text>
		</importing>
	</script>
	<messages>
		<message val="codeExistsNewMsg">
		  <text v="Mã văn bản lưu hành đã tồn tại trong danh mục." e="The circulation document code already exists in the list."/>
		</message>
	</messages>
</dir>
