<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmptgh" table="dmptgh" fieldKey="ma_ptgh" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục phương thức giao hàng" e="Delivery Methods List"></title>
  <title0 v="Mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
        <field name="ma_ptgh" format="U" label="1" field="1" allowBlank="false" fieldType="PK" >
          <text v="Mã phương thức" e="Delivery Methods Code"></text>
        </field>
         <field name="ten_ptgh" label="1" field="-" allowBlank="false" fieldType="PK" >
          <text v="Tên phương thức" e="Description"></text>
        </field>
        <field name="ten_ptgh2" label="1" field="-" allowBlank="true">
          <text v="Tên khác" e="Other name"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>T5Nuk0XwnW0VlRYHOIM5VZtxTNhw2REw24qf32G6cey6dhUT4czo8m1b2RSW76UOQb9i4IKZSgvX9IDjpcbcDpJJi4T0wHLwuzY8OKb4E7FDhTNvL10KVpdweTTETZ8vQIQ+gd7qfUTKI4sPLkywaKcnSQUjciv/fF/gV38lJvV4lBz/BOoMDTDqV7pffs8A</enc>]]>
    </text>
  </js>

  <script>
    <declare>
      <text>
        <![CDATA[<enc>HoMfTI0EpDZZnzy3AwuL7kZWFPr7Ri1NL/GVDQC621XZxmp8o1bYj7tejphnzLdvxypTCjEq2y7whXitKvmBoAqWPGra4jlJB11jXzD3t7ydeKaSns1CPqIhAONo0xd3EFWVpH3OlGBAjah/uLBsWkwJe4Z6clL2HpQcuKWx0HdT/vOdxj32Y/GrLgG5HoyaZ9DmNX7UWOtgqs7NYz4v0hdHGWoIBYJxxogaljdxAGfyIC6aPb5uzSQWPyLrVZIOCg5P/7ASSO67SHX1AGvDvQ==</enc>]]>
      </text>
    </declare>
  </script>
  
</dir>