<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmqhgd" table="dmqhgd" fieldKey="ma_qh" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục quan hệ gia đình" e="List of Family Relationships"></title>
  <title0 v="Thêm mới" e="Create New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
        <field name="ma_qh" format="U" label="1" field="1" allowBlank="false" fieldType="PK"  importable="5" >
          <text v="Mã quan hệ" e="Relationship Code"></text>
        </field>
        <field name="ten_qh" label="1" field="-" allowBlank="false" importable="10" >
          <text v="Tên quan hệ" e="Relationship Name"></text>
        </field>
        <field name="ten_qh2" label="1" field="-" importable="15">
          <text v="Tên khác" e="Other Name"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" valueDefault="1" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>dtYy4kD7R/zFbl3e6NPEDtBTBKHngLhKIs/VhJQOi5jGx1m28PKg6RYgQ6hQrgksCZWsePUjtNOwceWAxeHt6q+liHaq+HrpVV8wodRB+mXU0Yy9OwdAU3C6mgii2WF+U7K/0YSQiHudPiujzkzUtR4tav7XyU3DSFLjUJGdQVas2oGYa6n44zYNLpv4djiPkoU/c4kywQmIVNGgbW0iLUt8zH832QrIom9QCQ/yrslOQ1svbni++S+Zty7tmredlgIExgGmjXWfoRWxEX/MAyWf0d+raAczgf66coPt39hOl0mkPkFHPP7TWeU3ChK6uDM/T0M9vYbRPZDKJ66+QImkeQCSOLJ/PYR3+TVp+Vw=</enc>]]>
    </text>
  </js>

  <css>
	<text>
	  <![CDATA[<enc>/T0x+X5J8VnLtXSs8xERB1iizBHxQmUovXeEmWW/qu93qjuHFDu+lXBtlJPsy0eSkobXhvddWnPU2YfPq9MnjEH5L11nrH1UUlj8Web3S2AbLvvhAruj1BtAapRjwfSOoS6MKhdm+hbDOAZ/96wy+w==</enc>]]>
	</text>
  </css>
  
  <script>
	<importing>
      <text>
        <![CDATA[<enc>PDeYaSq5D3THjzUfjXLnuOov+zRPCu/HsQ7cYLJ9+NUbtW4WBDcym9s/zoBHUkNI</enc>]]>
      </text>
    </importing>
  </script>
  
  <messages>
	<message val="codeExistsNewMsg">
		<text v="Mã quan hệ gia đình đã tồn tại trong danh mục, vui lòng chọn một mã khác." e="The family relationship code already exists in the catalog, please choose a different code."/>
	</message>
	<message val="codeExistsEditMsg">
		<text v="Mã quan hệ gia đình đã tồn tại trong danh mục, vui lòng chọn một mã khác." e="The family relationship code already exists in the catalog, please choose a different code."/>
	</message>
  </messages>
</dir>