<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmquocgia" table="dmquocgia" fieldKey="ma_qg" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục quốc gia" e="List of country"></title>
  <title0 v="Mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
        <field name="ma_qg" format="U" label="1" field="1" allowBlank="false" fieldType="PK" >
          <text v="Mã quốc gia" e="Country code"></text>
        </field>
         <field name="ten_qg" label="1" field="-" allowBlank="false" fieldType="PK" >
          <text v="Tên quốc gia" e="Country name"></text>
        </field>
        <field name="ten_qg2" label="1" field="-" allowBlank="true">
          <text v="Tên khác" e="Other name"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>dtYy4kD7R/zFbl3e6NPEDicRnNreIRyu0gAW/PTP9nTDJmLMfaY1rrEc7qlKJro2U9V/DRLdmdzVhh8hrerhD/FUhrfV8IbkSsDeoKGkRscdo+cB4cUlIb6jUQ0O0Utzeiq056GJB1JFYS9oyJfaOIDf8xTVHef17mqaCXkU/oqFE2+WfQujaDj9mitdUFkA74JpcA/bWSetVgAW8YGE+mSfE06gkPk60fvHK109x+wiVOVK2eUWZodOvP5O8ohBkE+nZciE2pEKQmEPV4RDYjItXUIaxQ/VlP2esgSF8Gt9D8VrjtSWFU2JKUGcFutQDqozWlPKnYCPBQnZ2VMSc8RWkJSFVGGH/eNH37pw2DQ=</enc>]]>
    </text>
  </js>
  <css>
		<text>
		  <![CDATA[<enc>YkWQBTDGylCtyJwcHZMp4lZsTBMUUzGyXkCNhkU8H8kynB6sNzz45xo6bDJ9x73LIRmBFLsyoBbs54YutP4PTlvhDTeT/a3f3Z8GSnyDVAnvA2b/fxdvYgtP6v7y1XFAWYJEcyMRRnptNpfkfETNJw==</enc>]]>
		</text>
  </css>

  <script>
    <declare>
      <text>
        <![CDATA[<enc>hxQPm/hYhpvPifcenBxj7nfT+X4T8oXvYmZx4Kpwn3fRRVZY+foYIow2vt1OHdzq0lG6PkDpvnlKR1ei3AR28UkawCxswedTww8YMZ/ax/1/BVJZ6K0wvLOosliedaWZZt2COv3tOeOjMmBQuk/4Rwt2x8QTjTjMiSHn+IroEtakBX7bGKwyxmCTjhFOp9BNmfYGFOSpbck+xSy5ljuIkkedSelm6m5Bp4Y/MXqACx0hfBLsbE1tv4NeeV8q7mcH</enc>]]>
      </text>
    </declare>
  </script>
  <messages>
    <message val="codeExistsNewMsg">
      <text v="Mã quốc gia đã tồn tại." e="Country code already exists."/>
    </message>
    <message val="codeExistsEditMsg">
      <text v="Mã quốc gia đã tồn tại." e="Country code already exists."/>
    </message>
  </messages>
</dir>