<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>

<dir id="dmrmail" table="dmrmail" fieldKey="ma_rmail" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục mail" e="List of mail"></title>
  <title0 v="Thêm mới" e="Create New"></title0>
  <title1 v="Sửa" e="Edit"></title1>


  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
	    <field name="unit_id" dataType="I" hidden="true" readOnly="true" inactivate="true" label="1" field="1" importable="-1">
          <text v="" e=""></text>
        </field>
		<field name="ma_rmail" format="U" label="1" field="1" allowBlank="true" fieldType="PK" importable="-1" >
          <text v="Mã" e="Code"></text>
        </field>
        <field name="r_mail" label="1" field="-" allowBlank="false" importable="5" >
          <text v="Email" e="Email"></text>
        </field>
        <field name="ten_mail" label="1" field="-" allowBlank="false" importable="10" >
          <text v="Tên mail" e="Full Name"></text>
        </field>
        <field name="ten_mail2" label="1" field="-" importable="15">
          <text v="Tên khác" e="Other Name"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" valueDefault="1" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
		<field name="so_lan_gui" label="" field="" importable="-1">
          <text v="Số lần gửi" e="Total"></text>
        </field>
		<field name="lastsentdate" label="" field="" importable="-1">
          <text v="Lần gửi cuối" e="Other Name"></text>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>cnTIilkuex8tBnzmJV3WRQeSLZKx03Ozt1BFpwpXMmk1EhNvjGKpIACteQKpEcCf2IObR2jVt+HEwkV0OCSHRkvRrmwx8jYee4/f22JKTsZPuqpaaADLBqSBLxPb5d2EuW/doCyAxCRyPvjvkUIU7mxTOPjIwsmUQ9AIaDdz4/1YDv/bC6ds5JNmL9xbpyBq223APtHYJCtY39wVxy8pUZQHZg07hQZr3DDeZ7/eQr4a1giu1vmpO0Y4jN1eKnzWymi0MBfJDbAWVwIY0n2yACVfIlKU0q+FQKCoc/hhmoTN2WRKUaXnqd8ryOiNNHVtd+MchU4uKSmdL39Z5ZRJIELqrVgEUh/0XYr3NBzrFDHJiozWNtPWEH/662owLuRChJMU3cGzfjCPXjSQ1vglnU0Lx2KhPCZXaVH7r4jpvIA=</enc>]]>
    </text>
  </js>
  
  <css>
	<text>
	  <![CDATA[<enc>/T0x+X5J8VnLtXSs8xERB9wqMq74Q58aEDQjJi30oAN4aYbb9wPquzHXDYd3jr/k2hsFI1I0aI4upNqfGvbJqG+5i4mHIyO74vGifOBSEOTXRl/TLOTraC8vJBFx7ciHosVrIrWleAo+H66xMeI+DA==</enc>]]>
	</text>
   </css>
  
   <script>
		<request code="request_ma_rmail">
			<text> <![CDATA[<enc>uszKPhlwrpvAeJxnxwZwcyNqiM6WrMMwzarCysu5yHoTF+UfWcPjJQviITdx886uDOqDjwS3+T+u/uXYHSdAiqJ1XDqcba0FeQEDObNtGkv7LCE8fDYwAJCGD6d8gI8fLz3pg4A+SWYyx/vKZmvqWVj6rYbHJSFUQ1eGJkxpz9yl0/yxmTmkZKo1nqcIPO93yJLtD/x8ybc90NYCyGKluvxQJYg9Qv1fsD4Kvh4z97opx9SQVXUpYIn9hP1wJTl0</enc>]]> </text>
		</request>
	<importing>
      <text>
        <![CDATA[<enc>C8cedqZBsuwKxSy2c5tPS28q1XTwbiUTan9eTyO3Ja6Q4qIjjg1VofmJ/nr9RRrKiBiS0eZ3fNjX/0jCSKTRlnaqQe1D4kb0yn1WhiekEF+DWK49zT0lWkiJ699uGug3Zyb4+D6d5XJeDAivbH2kpB8lEGOdgODfM13C4gS8Md9MeW0gBb25VrMNUUPphIJHpoNF5FvVXPubw5rKCNePHl9UU6btLCb0l/N3QON23JZwhONhss0MhPvgorKKJeJpGvX0N01HPCOy94Qlw4NNNFTQicYfR+GklHLuTj75CPR7gBvS9FZSs4frnWPiXJtWc4pbJiVGUUKDU2QOHOTWsKQ5zHQvcVhVpS+fCkfxy2W3M9iSVjV8/llWCqYao6oqVN+qgbUSTM6XGrq6znEokJOdmoCJyQCmlCJcTmDErlN9rwOhW1u7uygZkWfBUTOVNV5G130Ep3eA9JEfqr1yuH0fasVcg4Bs+HEVIObES50zE3XwIgLYvCi2pvbnqEgogbQXdGbk2V3ZJzYqA4bRiRHwqv96bKxya51su/L9k90MjkQWM6pbFeiQhktZM+vXHpY+OZ4sNAnWKuv6Pb209A==</enc>]]>
      </text>
    </importing>
   </script>
  
   <messages>
	<message val="codeExistsNewMsg">
		<text v="Mã mail đã tồn tại trong danh mục, vui lòng chọn một mã khác." e="The mail code already exists in the catalog, please choose a different code."/>
	</message>
	<message val="codeExistsEditMsg">
		<text v="Mã mail đã tồn tại trong danh mục, vui lòng chọn một mã khác." e="The mail code already exists in the catalog, please choose a different code."/>
	</message>
   </messages>

</dir>