<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>

<dir id="dmsmail" table="dmsmail" fieldKey="ma_smail" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh sách Mail gửi" e="Sent list"></title>
  <title0 v="Thêm mới" e="Create New"></title0>
  <title1 v="Sửa" e="Edit"></title1>


  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
	    <field name="unit_id" dataType="I" hidden="true" readOnly="true" inactivate="true" label="1" field="1" importable="-1">
          <text v="" e=""></text>
        </field>
		<field name="ma_smail" format="U" label="1" field="1" allowBlank="true" fieldType="PK" importable="-1" >
          <text v="Mã" e="Code"></text>
        </field>
        <field name="s_mail" label="1" field="-" allowBlank="false" importable="5" >
          <text v="Email" e="Email"></text>
        </field>
        <field name="ten_mail" label="1" field="-" allowBlank="true" importable="10" >
          <text v="Tên mail" e="Full Name"></text>
        </field>
        <field name="ten_mail2" label="1" field="-" importable="-1" hidden="true">
          <text v="Tên khác" e="Other Name"></text>
        </field>
		<field name="username_smail" label="1" field="-" allowBlank="true" importable="15" >
          <text v="Tài khoản" e="Account"></text>
        </field>

		<field name="vpassword" allowBlank="false" fieldType="EX" valueDefault="********" label="1" field="1">
          <text v="Mật khẩu" e="Password"></text>
        </field>

		<field name="smtp_server" label="1" field="-" allowBlank="true" importable="25" >
          <text v="Máy chủ SMTP" e="SMTP Server"></text>
        </field>
		<field name="smtp_port" dataType="N" label="1" field="-" allowBlank="true" importable="30" >
          <text v="Cổng SMTP" e="SMTP Port"></text>
        </field>
		<!-- <field name="password_smail" label="1" field="-" allowBlank="true" valueDefault="********" importable="20" > -->
          <!-- <text v="Mật khẩu" e="Password"></text> -->
        <!-- </field> -->
		<field name="type_smail" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Loại mail" e="Type Mail"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Gmail" e="1 - Gmail"></text>
              </option>
              <option val="0">
                <text v="2 - Outlook" e="0 - Outlook"></text>
              </option>
            </options>
          </viewInfo>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" valueDefault="1" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
		<field name="mk_mail" label="1" field="-" allowBlank="true"  importable="20" hidden="true">
          <text v="Mật khẩu ứng dụng" e="Full Name"></text>
        </field>
	
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>Trkb2bekX4tiEuol68lz9vYcy34V7/l2C5hbd5TnTCcvNoNb1K7wJmkmpiqjmRKHcF5+343ba4PRDgjkN7fsTZ3GCIRCyVP2oRe81UaVNy97WqWnbo3g422JcNFBraoQd7mNJAOAFSgg/dxAdq+/qKjNJW9FgGQrnLswlV+Pz0K0ZulROZRg5/TZfZ+n8hz6yXTqjHNcPn1oCVENuvU1sIHa8Bj905P6EY0hep+B4Y5E8KMgZ6wlOiAimL6Yb+QoR6M84bOzcCB7y+K8O8ZOmmjRmn3tl+xXnR3XyUGSRKFboL6UG0K9J/Hn3J3gZ8MkQRIhRmTEIbyfUqRing3C/RswHw5+nb+Z0ZwwdfCJlVWrMkmfrNCdMXT6/9jLEpFbWvnnaGcizGSpLU06TIjWxJFUqNRXpdMVG0hUs5xwDThArU/qacB4VqbdaN/ZLj5gN2E5GTYexw3MIDL4akWPNxQOHu47TSyXgTCm1OT1ecXCa8HRPINGH7si5Os7Tsliw0Gy36emBz8s7nof4CVFfekHmxT2NOdo/w23lI3Lk+6Ho66sR08fScg2Z2y37HE0WqP82hQzRmMxWdH5xsfkvp5+qhsok1Zl1WImtFlPrP3aEIBUpDrYi9Zzs8OReo4GiQTxYXza+kpjMMqIuNzHDA==</enc>]]>
    </text>
  </js>
  
  <css>
	<text>
	  <![CDATA[<enc>/T0x+X5J8VnLtXSs8xERB45lpaMLmbkDdizJXje3PE0iWdEzrt69PfhDBnFVqoXRnlYi3i4/Utw7dFBqlqFC5xJCdl5ftxcKiyklF0l1jwIYeq1C/xspy/Q7eImvZxyy66O1voOF1PFdEoBp3jsiWA==</enc>]]>
	</text>
   </css>
  
   <script>
		<request code="request_ma_smail">
			<text> <![CDATA[<enc>RUILbEfyaZqwpDkL4LNTxnRrBbZJ8KaHkJ5bDti/YqtGqXYO9sQN9LYZCfTsvz2gRtRfRmrlVemvaI1rEHovUfwKC+yVoGCDNyqjp9p7KAyyY32/aUfkx6LbwXdAljalrpcVQh1r9AQUBOJzv2Iq6KSiawgXjY4Xjb8kFxcreJ2f6qE/IK340ntwle5Kk1UGSejsijeO1RwLR8J4ApXQrbJiX/n4t/ipSaikyGHSV9x+g3RKOcezBo6qebeV7nB5</enc>]]> </text>
		</request>
	<importing>
      <text>
        <![CDATA[<enc>k3o07gO3J36jc4OoF5gt1ngdcosS/y+vyYK7zUpOTFwr+kcOkdc+LMwLwvlvDg8qs16836VWIdVZHbsCiVyeWLFJ9kTUy2PuDod7fcvGgQ1aP9FldL5cxmebVhwvbrCAmYFlJvofhrisDIFLU+orCdjO94jLnSmSS2p93z8ccghfa3aHBZPAxIH8UWgr+PH+HOGy7Srhh9gRvOfWemNaX+1JGc0nz/+Hgt3Bp5QLESd9wot4EFKsv8QeGV1bbUDhpgUCkreFy2lAq72lwQmuKLtdkrGomytgu+vHkiBHHIt8EH0l8W5TZCDW16JroRAoRRxuL+j2B7K4XFinmsGi5LkEPnnu3Y8miM+akSc+cWF/J2yhVqsHyO8vorktwXngI5TTKqJ4q4Gz/eyIHU4T4gTQpgpjalwZNxwjlmGq+tNOsbZ/5T/wvLZG7PIqmyQSeV+P7EECUDtSK70MfTUq5+AuXLZndp0RmH9b2lO+TNxlDscHmU+B7irQXu0FLIPSE8CddRwMNnwJlAYj3tJISQ==</enc>]]>
      </text>
    </importing>
   </script>
  
   <messages>
	<message val="codeExistsNewMsg">
		<text v="Mã mail đã tồn tại trong danh mục, vui lòng chọn một mã khác." e="The mail code already exists in the catalog, please choose a different code."/>
	</message>
	<message val="codeExistsEditMsg">
		<text v="Mã mail đã tồn tại trong danh mục, vui lòng chọn một mã khác." e="The mail code already exists in the catalog, please choose a different code."/>
	</message>
   </messages>

</dir>