<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmsp" table="dmsp" fieldKey="ma_sp" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục sản phẩm" e="Product List"></title>
  <title0 v="Mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>
  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
        <field name="unit_id" dataType="I" hidden="true" readOnly="true" inactivate="true" label="1" field="1" importable="-1">
          <text v="" e=""></text>
        </field>
        <field name="ma_sp" format="U" label="1" field="1" viewType="AutoIncrease" clientDefault="true" allowBlank="false" fieldType="PK" importable="5" importWidth="250">
          <text v="Mã sản phẩm" e="Code"></text>
        </field>
        <field name="ten_sp" allowBlank="false" label="1" field="-" importable="10">
          <text v="Tên sản phẩm" e="Description"></text>
        </field>
        <field name="ten_sp2" allowBlank="true" label="1" field="-" importable="15">
          <text v="Tên khác" e="Other name"></text>
        </field>
      </fields>
    </form>
    <form tabPageIndex="1" gravity="MiddleLeft" height="330" columns="120,120,240" >
      <text v="Thông tin chung" e="General"></text>
      <fields>
		<field name="ma_km" format="U" viewType="Lookup" label="1" field="1" clientDefault="true" allowBlank="false" importable="20" importWidth="50">
          <text v="Mã khuyến mãi" e="UOM"></text>
          <viewInfo lookupType="One" lookupId="dmkm" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_km" lookupInfo="dmkm|ma_km|ten_km" importCheck="@@DF and z.status=1"/>
        </field>
        <field name="ten_km" nextRow="false" fieldType="EX" readOnly="true" clientDefault="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
        <field name="dvt" format="U" viewType="Lookup" label="1" field="1" clientDefault="true" allowBlank="false" importable="20" importWidth="50">
          <text v="Đơn vị tính" e="UOM"></text>
          <viewInfo lookupType="One" lookupId="dmdvt" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_dvt" lookupInfo="dmdvt|dvt|ten_dvt" importCheck="@@DF and z.status=1"/>
        </field>
        <field name="ten_dvt" nextRow="false" fieldType="EX" readOnly="true" clientDefault="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
     
        <field name="ma_lvt" viewType="Lookup" label="1" field="1" clientDefault="true" importable="35">
          <text v="Loại vật tư" e="Item Type"></text>
          <viewInfo lookupType="One" lookupId="dmlvt" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_lvt" lookupInfo="dmlvt|ma_lvt|ten_lvt" importCheck="@@DF and z.status=1"/>
        </field>
        <field name="ten_lvt" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as " clientDefault="true">
          <text v="" e=""></text>
        </field>
      
      </fields>
    </form>
	<form tabPageIndex="2" gravity="MiddleLeft" height="350" columns="140,120,240" >
      <text v="Bảo hành" e="Guarantee"></text>
      <fields>
        <field name="ma_imei" format="U" label="1" field="1" importable="65">
          <text v="Mã imei" e="Imei Code"></text>
        </field>
				
		<!-- <field name="bh_yn" dataType="B" clientDefault="true" label="[10]" field="[60]" inactivate="true" importable="66"> -->
          <!-- <text v="Theo dõi bảo hành" e="Guarantee Control"></text> -->
        <!-- </field> -->
        <field name="so_ngay_sp" label="1" field="1" dataType="N" format="Amount" importable="67">
          <text v="Vòng đời sp (số ngày)" e="Product Lifecycle (days)"></text>
        </field>
        <field name="so_ngay_bh" label="1" field="1" dataType="N" format="Amount" importable="68">
          <text v="Tg bảo hành (số ngày)" e="Warranty Period (days)"></text>
        </field>     
      </fields>
    </form>
	<form tabPageIndex="3" gravity="MiddleLeft" height="350" columns="120,120,240" >
      <text v="Thông tin" e="Information"></text>
      <fields>
        <field name="mo_ta" label="1" field="1" importable="69">
          <text v="Thông tin sản phẩm" e="Information"></text>
        </field>
      </fields>
    </form>
    <form tabPageIndex="4" gravity="MiddleLeft" height="350" columns="120,120,240" >
      <text v="Kích cỡ/Màu sắc" e="Size/Color"></text>
      <fields>
        <field name="ma_sp2" format="U" label="1" field="1" importable="69">
          <text v="Mã phụ" e="Other Code"></text>
        </field>
        <field name="nuoc_sx" label="1" field="2" importable="70">
          <text v="Nước sản xuất" e="Manufacturer"></text>
        </field>
        <field name="mau_sac" label="1" field="2" importable="75">
          <text v="Màu sắc" e="Color"></text>
        </field>
        <field name="kich_co" label="1" field="2" importable="80">
          <text v="Kích cỡ" e="Size"></text>
        </field>
        <field name="kieu" label="1" field="2" importable="85">
          <text v="Kiểu" e="Style"></text>
        </field>
      </fields>
    </form>
    <form tabPageIndex="5" gravity="MiddleLeft" height="0" columns="120,120,360" >
      <text v="Hình ảnh" e="Images"></text>
      <fields>
        <field name="ximage" label="1" field="2" viewType="Image" fieldType="EXParam">
          <text v="Chọn hình ảnh" e="Chọn hình ảnh"></text>
          <viewInfo fileFieldId0="ma_sp" fileGroup="Item" fileExtension="jpg,png" maxFileSize="10240" maxFileCount="10"></viewInfo>
        </field>
      </fields>
    </form>
    <form tabPageIndex="6" gravity="MiddleLeft" height="350" columns="120,120,240" >
      <text v="Khác" e="Other"></text>
      <fields>
        <field name="sl_min" label="1" field="1" dataType="N" format="Qty" importable="90">
          <text v="Tồn tối thiểu" e="Minimum Quantity"></text>
        </field>
        <field name="sl_max" label="1" field="1" dataType="N" format="Qty" importable="95">
          <text v="Tồn tối đa" e="Maximum Quantity"></text>
        </field>
        <field name="ngay_nhap" label="1" field="1" dataType="D" importable="96">
          <text v="Ngày nhập cuối" e="Last Receipt Date"></text>
        </field>
        <field name="ngay_xuat" label="1" field="1" dataType="D" importable="97">
          <text v="Ngày xuất cuối" e="Last Issue Date"></text>
        </field>
        <field name="ghi_chu" allowBlank="true" label="1" field="-" rows="3" importable="100">
          <text v="Ghi chú" e="Notes"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" label="1" field="2" valueDefault="1" importable="-1">
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>gD/uSOoPDzFOLnQtghwTxckUbemx/Uh3OMjBu2lloVbXxUVrcxaGD6faqb1bHxu1XSDNd0UrZ2qTUtr5T2osfHKwQ+kYlqRIzB7xnr656qTvtkX798abLurGxqnTuigIPhbTZhM0D+yP1MsZSTm6Gnyqar1VrJq7IGYDzzoyyaJJ6XeV1rvksp69WTriIAVRqHyPw93dNPn+h5pRPf8QKyth5Up24YgMIbf1xf72pS/7E51jIeUJPQht9t5OyLreM3ZBvi26dSTdK2MUHnSLOiYPuerPdEwmv8hu2c0uYHeUthp3LllbjQqWC4t2qEJ7CKCK4GO35SGdhCsU7ONH3Q==</enc>]]>
    </text>
  </js>

  <script>
    <query>
      <text>
        <![CDATA[<enc>Vbd/StiFCIDjnkLIOcPmKSxmSha9/HL33Op+pNLSDqZJsXQ2DmiIsa36Jtba82+isYCH+K979gBA3nxXSyEhpQO6WZb3x81VVSj0Ase3Ew5Y4tv7lRGtm9S/AOaytWytYFkT9WjvWnv3GfKJA4ianHSAfqI6oc2vbr3xLGZH/oc4isU5zNDlf6b7TijwHJwuLgPE7Qxx2OT6G0yo8/6sIIRSbzXn8daJfDSGMomLjOHbjVM/+rt+E5caRmHNzaKUh37ZuSJK0/DVYu1wFg2o+h1tgU5hAHaYtYQ/MJwofAfrwDABJ+abh8Uf98rSaRwk3BfPJX260mMZclWxNKb9qRL5AaRdOi+IMKwya9en4Xhedn10ReaP6EFrF/k/7WLkZjjd+6jgY4gjDYjdGne7wz9VM+X6JhApldbIrAw9jlCWe69lMyJB9O7twqGjhaFCyQVghN+Dm0YdhiCH8MBn/w==</enc>]]>
      </text>
    </query>

    <loading>
      <text>
        <![CDATA[<enc>GJgBVkOd9xy3In+SUACpOCHm272a6mCfLVOChps8jpZZw1SMxcSYS2nYwkJ1OGzw8fXuLQcv1y6qon3b06Mf4cXoiPtPwxwnDG2Z0kc4054=</enc>]]>
      </text>
    </loading>

    <deleting>
      <text>
        <![CDATA[<enc>Rfu1b572zNGZ4iXIsrNy29FHbe+12BLCuShkF0eKRXtPoicJ69x3xEXW0izNSDeOEVhI2QnY3S1bJIPLgkRSJZfOu4uQ8vXUkmxp/5rVT0LJCvFetcscvdAa+GWlz5K7IX8zsRdQQzznVP0ixpNi/pqAdkD4Gk5SK5cwld72iGrtBIXWn/rYHFSaz5TZejAfVsrM1YUSC04ryR6nnXC+Hg==</enc>]]>
      </text>
    </deleting>

    <updated>
      <text>
        <![CDATA[<enc>res7o41ZyxV7ie5eKEA1FR3DoqNrY1g3enPEBN+doWObylOrMfkyxVneiA834I9tbG1Qpc+jQ5ZT0mdK1/0LUd37aenWgfXk5TGF+gRuVNMWdqVMxsgvtEINuGRF/km1GwK4DoMWuZead72rT80z/EvWOxgXDFJyXi4kWSi7rWWWAgQSNNg0npMae5UuL4Qy</enc>]]>
      </text>
    </updated>
    
    <inserting>
      <text>
        <![CDATA[<enc>/T/6v4fr7JtuEWROY5bEopFO1HCnIjtZjFzzDG3F9/vEkIfRrRIYFlNT+1c2A+G4DGK3P1V1ru+z1kGXJXjR1VzP1TAM3KziUQ39S5UPAFO5TtFkd+A7rjU9Cj84+ron+NnAUl09CZS+jY4xst+ifUx/y0L2N86LSRXXWB0b2jLk9z1JyBTjpFwFo33O8/V92Jll9ZnIKloIczVnEYCl2/5Q4n5X9mE3/5atjZjvFut8hbyHb/wqOO6O7YgIZzpT</enc>]]>
      </text>
    </inserting>
    <inserted>
      <text>
        <![CDATA[<enc>DAAM1Z144udHkjgEmwvZ+Di9x948bvkxFdpFwLEMTktq9ALg9+Hglwq+rYALBoKRvztExohZMFZZGlsrFRMmZKtS66q83p4bLQMzpFMkaZAF71HWsYSgRYDYfYqp8F/R1aYm3c2W4ik+mKM3dgMS/oOMF98bxGu8yQZYF5EbAqU=</enc>]]>
      </text>
    </inserted>

    <aftersave>
      <text>
        <![CDATA[<enc>hpzldKetGcs61JyJT2ezF8/tCrhAm9mHMaXmeGv7aOenHT9hR7ODAWBeMFL7IMQabTI4V0M+Hq/NCIrNMt1XnqVl/6SYNwLyp/8C9q9kTMP3W2NmwYEw29XJQfk23dc7OI8ydj1oYWhWA+tUXc22SvAAHq4SlJZ2nCwPcvmE+o71MlkulYrEmk8vA5YqOH0M</enc>]]>
      </text>
    </aftersave>
    <importing>
      <text>
        <![CDATA[<enc>sxD5Swu0R4mcxEHdwcy2yi46ZbQRyi0uEDh1tGVfNVOBZJeZZHskWnswm55XGvVMtI3kJxA271ZmaBNQ7vOM1svvmG7tRC9SwsrihBxLjQw=</enc>]]>
      </text>
    </importing>
  </script>

  <messages>
    <message val="codeExistsNewMsg">
      <text v="Mã vật tư đã tồn tại trong danh mục vật tư." e="The record already exists."/>
    </message>
    <message val="codeExistsEditMsg">
      <text v="Mã vật tư đã tồn tại trong danh mục vật tư." e="The record already exists."/>
    </message>
  </messages>
</dir>