<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmthue" table="dmthue" fieldKey="ma_thue" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục thuế" e="Tax List"></title>
  <title0 v="Thêm mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
        <field name="ma_thue" format="U" label="1" field="1" allowBlank="false" fieldType="PK" >
          <text v="Mã thuế" e="Tax code"></text>
        </field>
        <field name="ten_thue" label="1" field="2" allowBlank="false" fieldType="PK" >
          <text v="Tên thuế" e="Tax name"></text>
        </field>
        <field name="ten_thue2" label="1" field="2">
          <text v="Tên khác" e="Other name"></text>
        </field>    
	   <field name="ma_loai" viewType="Lookup" label="1" field="1" importable="50">
          <text v="Loại thuế" e="Tax type"></text>
          <viewInfo lookupType="One" lookupId="dmloaithue" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_loai" lookupInfo="dmloaithue|ma_loai|ten_loai" importCheck="@@DF and z.status=1"/>
        </field>
        <field name="ten_loai" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
        <field name="tyle_thue" label="1" field="1" dataType="N" format="Rate" >
          <text v="Tỷ lệ thuế" e="Tax rate"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>T5Nuk0XwnW0VlRYHOIM5VXhKO7/eOS+JOgvPzcIet9ayt9ZRbuGDSnZBxgrpjKc5Wh8tRPbKaP5GMrMEPFcVTw+u+R56b1AITOxRsQDdK3YxK9K+VqREaIvIMB90l8jAk9Wc2776BpQtkxbL8gsjk1wiWrTqxUiJ5iBN/xHrFoe2YAMijDyTr/yBXiQc3GuL</enc>]]>
    </text>
  </js>

  <script>
    <declare>
      <text>
        <![CDATA[<enc>hxQPm/hYhpvPifcenBxj7nfT+X4T8oXvYmZx4Kpwn3fRRVZY+foYIow2vt1OHdzq0lG6PkDpvnlKR1ei3AR28UkawCxswedTww8YMZ/ax/1/BVJZ6K0wvLOosliedaWZGLemg/a55K+V/CU1zpoKSnqEDOxVgXAgXd61wM3ot5WSWF4nwV+X34IuQIfQ19hcxF5nscECchAEmXR6pB4eG4tPtYv8/5MNeKhW2XaZG2Q=</enc>]]>
      </text>
    </declare>
  </script>

</dir>