<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>

<dir id="dmth" table="dmth" fieldKey="ma_th" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Thương hiệu/ Nhãn hàng" e="Service List"></title>
  <title0 v="Thêm mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
        <field name="ma_th" format="U" label="1" field="2" allowBlank="false" fieldType="PK">
          <text v="Mã Thương hiệu" e="Service Code"></text>
        </field>
        <field name="ten_th" label="1" field="2" allowBlank="false">
          <text v="Tên Thương hiệu" e="Description"></text>
        </field>
        <field name="ten_th2" label="1" field="2">
          <text v="Tên khác" e="Other name"></text>
        </field>
		<field name="thu_tu" label="1" field="2" dataType="N">
          <text v="Thứ tự" e="Position"></text>
        </field>
		<field name="mo_ta" label="1" field="2">
          <text v="Mô tả" e="Description"></text>
        </field>
       <!-- <field name="ma_clvt" viewType="Lookup" label="1" field="1" clientDefault="true" importable="35"> -->
          <!-- <text v="Danh mục chính" e="Item Type"></text> -->
          <!-- <viewInfo lookupType="One" lookupId="dmclvt" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_clvt" lookupInfo="dmclvt|ma_clvt|ten_clvt" importCheck="@@DF and z.status=1"/> -->
        <!-- </field> -->
        <!-- <field name="ten_clvt" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as " clientDefault="true"> -->
          <!-- <text v="" e=""></text> -->
        <!-- </field> -->
  
        <field name="status" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
	<form gravity="TopRight" columns="120,120" >
		<fields>
			<field name="ximage1" label="1" field="0" importable="65">
			  <text v="&lt;img class='image-single' id='img_ximage1' src='' onerror='src=`../Images/noImage.png`'/&gt; &lt;input type='button' value='Tải ảnh' onclick='browseServer(`ximage1`, `img_ximage1`);' value='Mở 1' style='text-align: center; display: block; margin: 0 auto;' /&gt;" e="Image 1"></text>
			</field>
			<field name="ximage2" label="1" field="0" importable="65" nextRow="false">
			  <text v="&lt;img class='image-single' id='img_ximage2' src='' onerror='src=`../Images/noImage.png`'/&gt; &lt;input type='button' value='Tải ảnh' onclick='browseServer(`ximage2`, `img_ximage2`);' value='Mở 2' style='text-align: center; display: block; margin: 0 auto;' /&gt;" e="Image 2"></text>
			</field>
	   </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>HF2P1JAN+rXaUbRtDo7ioQ2VnAlntjvZG0giMsuO8V2CdpgJ5COcHf4coqY1E1FMjDdtytxWYGcK9y/z+ultJgQ79UPp+9Fy7wEmoQUXPriyyiXRu3CzMCmhmFZuLvd8rTQfxgJZGSRvNh+btXVFRO3c44G7fOescf72wq67wwa+Xfbm98+coSd/eSjbfYIWmk7/fQoVXoeM7jPkF/xWRU5fCTfLxXw9lCJ0a0pSV/FOlYuwktYSrt4dLmYXEupdZLrr+jZ6P8Rl5tqxs7d/PhuT0pQqJwS0SsVm+964YUGmqAH5tOgmEG1vaaBHnFzz5EgdutpvB+gxLyHO7nEC1uBfgMNzH5VWFJ04sKHD+5MzxQw8E2Y0PwNLsRG09zKXf2MZK7+i2xWDo/n1kxosCh3mxicYcBUh+4HEHfqxzX5fKShpzkh735gqw1neijGPF7AclpPD5yavIJkoHH/uwdyTALTR5AH9OxBdy7LJcEU=</enc>]]>
    </text>
  </js>

  <messages>
    <message val="codeExistsNewMsg">
      <text v="Mã dịch vụ đã có hoặc lồng nhau trong danh mục dịch vụ." e="The Service is invalid or already exists."/>
    </message>
    <message val="codeExistsEditMsg">
      <text v="Mã dịch vụ đã có hoặc lồng nhau trong danh mục dịch vụ." e="The Service is invalid or already exists."/>
    </message>
  </messages>

</dir>