<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmttbm" table="dmttbm" fieldKey="ma_ttbm" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục trạng thái nhấc máy" e="List of Pick-up state"></title>
  <title0 v="Thêm mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
        <field name="ma_ttbm" format="U" label="1" field="1" allowBlank="false" fieldType="PK" >
          <text v="Mã trạng thái nhấc máy" e="Pick-up state code"></text>
        </field>
        <field name="ten_ttbm" label="1" field="-" allowBlank="false" fieldType="PK" >
          <text v="Tên trạng thái nhấc máy" e="Pick-up state name"></text>
        </field>
        <field name="ten_ttbm2" label="1" field="-">
          <text v="Tên khác" e="Other name"></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>1PFOGp66gVgaSTPirrPUVUgXFguRdD4kd6Aw/AylcI+IqzvktXkatD0lxoI7uQv4niQDBcDomQ6ZwXCvCRAULnNUohsQ/qUJdvTHKpupXyWyy30JDZSZPbSwMJYC0GP4JeNCBDqCwtMjIOUoBxO+1hD1ReGFbJmHBDIN5ORH6FywqaUX2O3dlTmrM7QeJAth1olxpXeGhdKBKK9KKGDT3xgaF98DikcFw0Js+qOKkzo+1Is1GMP8AOwQIBJq86g+gwNjJ28o/x+inXmtgJCRldQU7wwn2ZjFH3UM5PlKrf0RDPz7wmTbYoKxwuMDVi36VtoZAKb9lumZGIE/30VLnQ==</enc>]]>
    </text>
  </js>
   <css>
		<text>
		  <![CDATA[<enc>YkWQBTDGylCtyJwcHZMp4lZsTBMUUzGyXkCNhkU8H8mLgvL6slXH6rnUcq0TVqrCcZ1NRp3xXAuSRqwheBARPA0eLzpeogAEDheKXrfAER+d/FH3rHi9JU5bifv+oM21</enc>]]>
		</text>
  </css>
  <script>
    <declare>
      <text>
        <![CDATA[<enc>gBf+82ceCywnr5uKt9NZLLSy6yolb77/2cuNg8eD8vsKJaFLPHJp332bfrztnYqQoAV0DPs65w0uY7qDPRuFuxF8Nfo3v8yRpgyoXv+It9LJIa7YDP82eqMjlm5VcQhUII0mCv8dtZRSeYLG0sQW9Q3PdQ5g6GSqTG71/TRQNL4SngW4RC6thzpS45naCWWf6nipx+YXus5HHTQn50HP2HJBBEXNCeYZhK+R1G8zfyx235ngwgAB8cxREo9mHtYCDg63n8/mztKs6YoCjepQow==</enc>]]>
      </text>
    </declare>
  </script>
  <messages>
    <message val="codeExistsNewMsg">
      <text v="Mã trạng thái nhấc máy đã tồn tại." e="Pick-up state code already exists."/>
    </message>
    <message val="codeExistsEditMsg">
      <text v="Mã trạng thái nhấc máy đã tồn tại." e="Pick-up state code already exists."/>
    </message>
  </messages>
</dir>