<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmtygiaxd" table="dmtygiaxd" fieldKey="ma_xd,ngay_hl" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Khai báo tỷ giá xăng dầu" e="Declare petrol rates"></title>
  <title0 v="Thêm" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
        <field name="ma_xd" format="U" label="1" field="1" viewType="Lookup" clientDefault="true" allowBlank="false" fieldType="PK" >
          <text v="Mã xăng dầu" e="Petroleum Code"></text>
          <viewInfo lookupType="One" lookupId="dmxd" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_xd" lookupInfo="dmxd|ma_xd|ten_xd" />
        </field>
        <field name="ten_xd" nextRow="false" fieldType="EX" readOnly="true" clientDefault="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
        <field name="ngay_hl" label="1" field="1" valueDefault="new Date()" allowBlank="false" dataType="D" fieldType="PK">
          <text v="Ngày hiệu lực" e="Date From"></text>
        </field>
        <field name="ty_gia" label="1" field="1" dataType="N" format="ExRate" >
          <text v="Tỷ giá" e="Exchange Rate"></text>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>uw3iZoR/y/5o6FF1x5y/2Was742uZt8MJLHMq+3w6bF4m7oGRU5toWljp4Ytw7xlzRyh5OWkWD4zzb9StdHdyRi2cgMToTMi5chIX3lxOjqd/CBh86XtKqrGfQaGRGteX38P2NVMdAEthaatJKuXSTmm8sIkdhWfLEHSCDmhcbmFd+DF1o/ZvjPASBuw8jv8</enc>]]>
    </text>
  </js>
  
  
  
	<css>
		<text>
		  <![CDATA[<enc>YkWQBTDGylCtyJwcHZMp4jDvm0u1sJJhM8YQ9YMcSxrVKezgN9sXFwCY42fkdS6IlQi4Fz+HgtWvxaSg4KL8uLIWnfJTFfMFvcT5t1mCiRtHdHD7JXs188FMCFUdbTbQ</enc>]]>
		</text>
	</css>
  <script>
    <declare>
      <text>
        <![CDATA[<enc>hxQPm/hYhpvPifcenBxj7nfT+X4T8oXvYmZx4Kpwn3fRRVZY+foYIow2vt1OHdzq0lG6PkDpvnlKR1ei3AR28UkawCxswedTww8YMZ/ax/1/BVJZ6K0wvLOosliedaWZJiNd/6vhu/vNYf00JVn4EfF6KfL+V1qtGn6/moth90FYvPD4XUwfj23KBA3T4I67MF50PR8DavBPGoFM7WxksGL5MD6p2QNb/p9ig5j9DQ3GtHvJUM9vTdu/fFqpvs8B</enc>]]>
      </text>
    </declare>
  </script>

</dir>