<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="dmtygiakm" table="dmtygiakm" fieldKey="ma_dvt,ngay_hl" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Giá trị quy đổi KM" e="Exchange value"></title>
  <title0 v="Thêm" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
        <field name="ma_dvt" format="U" label="1" field="1" viewType="Lookup" clientDefault="true" allowBlank="false" fieldType="PK" >
          <text v="Mã đơn vị tính" e="Unit Code"></text>
          <viewInfo lookupType="One" lookupId="dmdvt" lookupKey=" ma_loai = 'DD' and status=1" lookupCheck="1=1" lookupRef="ten_dvt" lookupInfo="dmdvt|dvt|ten_dvt" />
        </field>
        <field name="ten_dvt" nextRow="false" fieldType="EX" readOnly="true" clientDefault="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
        <field name="ngay_hl" label="1" field="1" valueDefault="new Date()" allowBlank="false" dataType="D" fieldType="PK">
          <text v="Ngày hiệu lực" e="Date From"></text>
        </field>
        <field name="ty_gia" label="1" field="1" dataType="N" format="ExRate" >
          <text v="Tỷ giá" e="Exchange Rate"></text>
        </field>
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>uw3iZoR/y/5o6FF1x5y/2Was742uZt8MJLHMq+3w6bHfhicxH7cwnTTtLZjcfaY0KvWYunYD/pY1wqmZrBuUuffI4sgDpBt3LKznoE0j5jmStFoC7T9gUPDVNlcbpGWIAtqwjNENlIQT9Kax58ZaUSwoV6AzWLLYbSx7c6bQjFxutEW/Vx0eIcbiXnmL23L1</enc>]]>
    </text>
  </js>
  
  
  
	<css>
		<text>
		  <![CDATA[<enc>YkWQBTDGylCtyJwcHZMp4ku6Dq2oUNnvDbOHUD7o0MPop5fX6Nm4JITTHnKD5ERjI611tOQlNPCh4g2hBVZDYoYMHzMOeCLhego/i3XNy+5Vgc6WnZLoornyI3BtymZE</enc>]]>
		</text>
	</css>
  <script>
    <declare>
      <text>
        <![CDATA[<enc>hxQPm/hYhpvPifcenBxj7nfT+X4T8oXvYmZx4Kpwn3fRRVZY+foYIow2vt1OHdzq0lG6PkDpvnlKR1ei3AR28UkawCxswedTww8YMZ/ax/1/BVJZ6K0wvLOosliedaWZdaayIfsp0+GRope2BDihQPyWxxk4tUIslmmFdWUdnQoiG0j/12uzzs/Yduy+OBtmt2IijkDyBf+F896B8Q0mZnNGjI7wAenXt6EqcpCwAWLCWUTLo7NHN0DcE9mDMis7</enc>]]>
      </text>
    </declare>
  </script>

</dir>