<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>

<dir id="dmvb" table="dmvb" fieldKey="ma_vb" transaction="true" tryCatch="true" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục mẫu văn bản" e="Document Template Catalog"></title>
  <title0 v="Mới - văn bản" e="New - document"></title0>
  <title1 v="Sửa - văn bản" e="Edit - document"></title1>

  <forms>
	<form gravity="TopLeft" columns="120,120,120,120,120,120">
		<fields>
			<field name="unit_id" dataType="I" hidden="true" readOnly="true" inactivate="true" label="1" field="1" importable="-1">
			  <text v="" e=""></text>
			</field>
			<field name="ngay_ct" nextRow="true" dataType="D" valueDefault="new Date()" label="1" field="1" importable="5" >
				<text v="Ngày phát hành" e="Issue Date"></text>
			</field>
			<field name="tu_so" label="1" field="1" fieldType="EX" allowBlank="true" disabled="true" nextRow="false">
			  <text v="Trong khoảng từ:" e="In the range from"></text>
			</field>
			<field name="den_so" label="1" field="1" fieldType="EX" allowBlank="true" disabled="true" nextRow="false">
			  <text v="Đến:" e="In the range to"></text>
			</field>
			<field name="ma_vb" label="1" field="-" allowBlank="false" fieldType="PK" disabled="true" importable="-1">
				<text v="Mã văn bản" e="Group code"></text>
			</field>
			<field name="ten_vb" label="1" field="-" allowBlank="true" disabled="false" importable="10">
			  <text v="Tên văn bản" e="Name"></text>
			</field>
			<field name="ten_vb2" label="1" field="-" allowBlank="true" disabled="false"  importable="15">
			  <text v="Tên tiếng anh" e="Name English"></text>
			</field>
			<field name="ky_hieu" label="1" field="1" allowBlank="true" disabled="false" nextRow="true" importable="20" >
			  <text v="Ký hiệu" e="Symbol"></text>
			</field>
			
			<field name="ma_pl" label="1" field="1" viewType="Lookup" allowBlank="false" importable="25">
			  <text v="Văn bản lưu hành" e="Circulation Document"></text>
			  <viewInfo lookupType="One" lookupId="dmplvb" lookupKey="status = 1" lookupCheck="1=1" lookupRef="ten_pl" lookupInfo="dmplvb|ma_pl|ten_pl" />
			</field>
			<field name="ten_pl" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" hidden="false" label="" field="[240]" aliasName="cast('' as nvarchar(4000)) as ">
			  <text v="" e=""></text>
			</field>

			<field name="ma_nvb" label="1" field="1" viewType="Lookup" allowBlank="false" importable="30"> 
			  <text v="Nhóm văn bản" e="Group Document"></text>
			  <viewInfo lookupType="One" lookupId="dmnhomvb" lookupKey="status = 1" lookupCheck="1=1" lookupRef="ten_nvb" lookupInfo="dmnhomvb|ma_nvb|ten_nvb" />
			</field>
			<field name="ten_nvb" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" hidden="false" label="" field="[360]" aliasName="cast('' as nvarchar(4000)) as ">
			  <text v="" e=""></text>
			</field>
			<field name="status" viewType="Combobox" inactivate="false" label="1" field="2" valueDefault="1" nextRow="true" importable="-1" >
			  <text v="Trạng thái" e="Status"></text>
			  <viewInfo>
				<options query="select ma_tt, ten_tt%l from dmttsd where status = 1 ">
				</options>
			  </viewInfo>
			</field>
      </fields>
    </form>
	<form tabPageIndex="1" gravity="MiddleLeft" height="300" columns="120,120,360" >
      <text v="Đính kèm" e="Attach Files"></text>
      <fields>
        <field name="xfile" label="1" field="2" viewType="File" fieldType="EXParam">
          <text v="Chọn files" e="Attach Files"></text>
          <viewInfo fileFieldId0="ma_vb" fileGroup="dmvb" fileExtension="*" maxFileSize="10240" maxFileCount="10"></viewInfo>
        </field>
      </fields>
    </form>
</forms>

&DefaultButton;

<js>
<text>
  <![CDATA[<enc>DhRctQT1mdQ+6fGK9dQj0+XMRSfkms5FfvHSyUC6bjkzsDO7/EDjBPW2BL89IWk+fOyLyx7kq3VdtrIxwVqCkDw8oEgiSN38n0Tb4HXaUbaaQp4vvWQiGoiGSceomei/Z5WWVEZ7ncPAEo8bTnHcXCQzjE1CsZGGKq8F0annGfcy8ghguKAxeIhzK1u+gtTVVJVSztYXlh0v+P4fVpSX0DAQ6gX693QX+ZKcdh2Y+sdCjW+hmVbX2HRrnmuSW3UbHkKXPiFkyxvP3ysCwlbXLYkyun0lJ3CRBJeZUAuAAgj2BTsIF4EF2S7xcB9gCeTNOg9SzZgIKaBvR+Ir+I1bFlHST10tJU+c/2O0wCzsqUrt031zxL/F3wwvdxqOlrDiqLOI2MOmPNIKYJCaBcDS7Wu2i7LzjLHrR8BAGgviWF2apiT90qPkUu9NfsYN1gju5AvZ+P0CrVS67r3KwuJiNM34uTFHDvFZRyDMJl0QyjTYZ5JbVdo2I1QbkrihcdfQ5q9lU8lTyyCCIKpOomgOzl4KXPsi5C4Nah8a+o07gYXjdDHmUbZ+pQTUtCMjA//AH7Et4qA+uN9DmLj3h9hzIuslH6+2bESe6V3InL9YoCaSL7a4z6r04VKAYe1vC3E/847TN/1F0vCK7S2V9eIAIyuVcCsICpQT+/8OjZymPU9lBX/YcvIAk7dn/AU5LgwXxa+3Am6aUP2v8RDwlVhGv2gMIaw6juihBk/ubcjNWqb+OB+LAyAQSaxR1Us6Qui0Ez4FQtJibwpoEwQ1HimAjAoZVjO6vhzaOIO7hzciF43HxfPvxPScUPGMvL5RsAG7</enc>]]>
    </text>
  </js>
	<css>
		<text>
			  <![CDATA[<enc>oQzagFEVvgZSRpzoWY9G1hb85u572QIbDHrl5oqzczW3HfrE7nQu9JzIb4WwTzFbRoqfsTFD8U5glAIOUGy47fD+9PjU0VujT4FHD6fU8Yax2KqWf5FjMjEGKbDuN6pwXuAh9SW5Xyew1RwskTxO9UJIuTxSc+eLorzAXEn7oKBHOLu4aeV5gPEQup0gfHLjIvWGQFazwUoqmJVTXHnKNQ==</enc>]]>
		</text>
	</css>
	<script>
		<request code="LoadInfoMaPl">
			<text>
			  <![CDATA[<enc>J/6M2fsHORC1FC6FkzRY+KTEOxLdrs4ZwGs5oLNimn18/QGlNMfgSvX5EKHHJS2Oj1VZV7QekVTgauWJ7JIt0av3ziIYdHIKn0dRTHzRGyiGcknGuHnDFqDzJat88m+ivJtPgL8lKznDQsfQFgOZDrRJbevzN/obEwnWBohgleU=</enc>]]>
			</text>
		</request>
		<request code="LoadMavb">
		<text>		
			<![CDATA[<enc>KeGj6rYqiUccvXDvBhfBlGm/0jccz72o2EDmvwI9tnSyQSpzc9XBJwqfiQdPADMqF7J0nytY9bLNNIqTnBoUXSW65CdHJAfVZRYE1+8ynpa95l15t5tNDLaRWHjazSwN</enc>]]>				
		</text>
		</request>
  		<query>
		  <text>
			<![CDATA[<enc>hPexS+VD3npdrf/5Wx9Fbhhd9L/MD2u9uYYhVnlqw8sp2V4Xas+qiAjH2E9fstmxW+6ZNDjWzRhY7Htyu45rG7nXyl0MkL8AxgMiJHujI1PCgp/XXy5xXQzy10HGTCyjP5MFZQJSQvek24oTpvg8JcEck0s4nHVWemyfMiLYsdRlG63bV25wLoW64RYoZKucL5tGOk9xNZqsNnadbFPKcHHgd+suMU8hNAit1CjDnZGqp0ziOoFcaqjScLIDybc0bRJ1OrXu5wb7VSdF4oJ9Z/xUYElcNIieq5s6SFd3N/Vvl6xYVgjSCGc0cTCwxr8AFx9m0hDdwn8JG4j7mXcwOQ==</enc>]]>
		  </text>
		</query>
		<updated>
		  <text>
			<![CDATA[<enc>j/aRUDcC9xRDT3BBbdR7vOsv0iQXGwqcK2s/7C9Nj485EiK/Rq2vIIuDgtZP3ik+ZGasK3lmHaapJkj8T6flF/Z4+enIxAMYvzZmKvoM7HutIMdMqUccO7NoeswGwLR2VqBUELKUep5G/xMg0wy2vkOfuWGhOFlqJcb+ODjSZn4vUs5XfGz3ZwXJ3JINMECg30FfNDN/NniwhVdGlBD91Wppc6IUP+xBb1g95eBRyLPSD3hS7DQo2sU2G+QuiWWs9ysRd5/tJxlr5sFP+X3owg==</enc>]]>
		  </text>
		</updated>
		<inserting>
		  <text>
			<![CDATA[<enc>/T/6v4fr7JtuEWROY5bEog4q37AdyKX5y50iwuf8o+kQ/cMLdjO5yBgIja/EXDIb67gjtJCgsvsoKVHnH40ASfHmT/5Pyqyz9fEF+eXazaeFq1QdO25I17j8uqKw4sm7PDDzWS+uYkqIWo1FmMQqY1vwSihUQwhC3DMwYBlMdqW/7I05kvZGgi3lyKQDrJ1gd1u3eDHWrXNvOq+fBosahfSLln2pO8chassI1khVi2Brg84FNLLprzwizWkmE7Kk</enc>]]>
		  </text>
		</inserting>
		<inserted>
		  <text>
			<![CDATA[<enc>TokeQrNoHZhXoSssGWOt1Q5GfHvc9gJj2MoN4VfQf2N7bYWkIEAOdkUFhPp46U7+PsWSAqqBV1aM7AGE5LhR30+DBnYDGMHxuax9KClopqWIenoJB3dxEXUX6ZCYm3u/eGU+2TSX6csCfF37MhbvidDtDswp3Bn0QKGrt7xQofL5q5d2vpXvJMoUuj0vbO3Y</enc>]]>
		  </text>
		</inserted>
		<importing>
			<text>
			<![CDATA[<enc>sxD5Swu0R4mcxEHdwcy2yi46ZbQRyi0uEDh1tGVfNVOBZJeZZHskWnswm55XGvVMZq7vIrj1gngY5x8IJuKO1pkyFlxS8pifsEwHrhrpEjg=</enc>]]>
			</text>
		</importing>
	</script>
  <messages>

	 <message val="RequireMaPl">
      <text v="Vui lòng chọn văn bản lưu hành để tạo mã văn bản" e="Please select a circulation document to generate a document code."/>
    </message>
	<message val="RequireMaNVB">
      <text v="Vui lòng chọn nhóm văn bản để tạo mã văn bản" e="Please select a document group to generate a document code."/>
    </message>
	<message val="codeExistsNewMsg">
	  <text v="Mã văn bản đã tồn tại trong danh mục." e="The document code already exists in the list."/>
	</message>
  </messages>
</dir>
