<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
	<!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>

<dir id="dmvt" table="dmvt" fieldKey="ma_vt" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
	<title v="Danh mục vật tư" e="Product List"></title>
	<title0 v="Mới" e="New"></title0>
	<title1 v="Sửa" e="Edit"></title1>
	<forms>
		<form gravity="TopLeft" columns="120,120,120" >
			<fields>
				<field name="unit_id" dataType="I" hidden="true" readOnly="true" inactivate="true" label="1" field="1" importable="-1">
					<text v="" e=""></text>
				</field>
				<field name="ma_vt" format="U" label="1" field="1" viewType="AutoIncrease" clientDefault="true" allowBlank="false" fieldType="PK" importable="5" importWidth="250">
					<text v="Mã vật tư" e="Item Code"></text>
				</field>
				<field name="ten_vt" allowBlank="false" label="1" field="-" importable="10">
					<text v="Tên vật tư" e="Item Name"></text>
				</field>
				<field name="ten_vt2" allowBlank="true" label="1" field="-" importable="15">
					<text v="Tên khác" e="Other name"></text>
				</field>
			</fields>
		</form>
		<form tabPageIndex="1" gravity="MiddleLeft" height="330" columns="120,120,240" >
			<text v="Thông tin chung" e="General"></text>
			<fields>
				<field name="dvt" format="U" viewType="Lookup" label="1" field="1" clientDefault="true" allowBlank="false" importable="20" importWidth="50">
					<text v="Đơn vị tính" e="UOM"></text>
					<viewInfo lookupType="One" lookupId="dmdvt" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_dvt" lookupInfo="dmdvt|dvt|ten_dvt" importCheck="@@DF and z.status=1"/>
				</field>
				<field name="ten_dvt" nextRow="false" fieldType="EX" readOnly="true" clientDefault="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
					<text v="" e=""></text>
				</field>
				<field name="ton_kho_yn" dataType="B" clientDefault="true" label="[120]" field="[60]" inactivate="true" importable="25">
					<text v="Theo dõi tồn kho" e="Stock Control"></text>
				</field>
				<field name="lo_yn" dataType="B" clientDefault="true" label="[80]" field="[60]" nextRow="false" inactivate="true" importable="30">
					<text v="Theo dõi lô" e="Lot Control"></text>
				</field>
				<!-- <field name="ma_lvt" viewType="Lookup" label="1" field="1" clientDefault="true" importable="35"> -->
					<!-- <text v="Loại vật tư" e="Fee Type"></text> -->
					<!-- <viewInfo lookupType="One" lookupId="dmlvt" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_lvt" lookupInfo="dmlvt|ma_lvt|ten_lvt" importCheck="@@DF and z.status=1"/> -->
				<!-- </field> -->
				<!-- <field name="ten_lvt" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as " clientDefault="true"> -->
					<!-- <text v="" e=""></text> -->
				<!-- </field> -->
				<field name="ma_lo" viewType="Lookup" label="1" field="1" clientDefault="true" importable="55">
					<text v="Mã lô" e="Lot Number "></text>
					<viewInfo lookupType="One" lookupId="dmlo" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_lo" lookupInfo="dmlo|ma_lo|ten_lo" importCheck="@@DF and z.status=1"/>
				</field>
				<field name="ten_lo" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="1" aliasName="cast('' as nvarchar(4000)) as "  clientDefault="true">
					<text v="" e=""></text>
				</field>
				<field name="nh_vt1" viewType="Lookup" label="1" field="1" importable="40">
					<text v="Nhóm 1" e="Group 1"></text>
					<viewInfo lookupType="One" lookupId="dmnh" lookupKey="ma_loai_nh = 'VT1' and status=1" lookupCheck="ma_loai_nh = 'VT1'" lookupRef="ten_nh_vt1" lookupInfo="dmnh|ma_nh|ten_nh" importCheck="@@DF and z.ma_loai_nh = 'VT1' and z.status=1"/>
				</field>
				<field name="ten_nh_vt1" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
					<text v="" e=""></text>
				</field>
				<field name="nh_vt2" viewType="Lookup" label="1" field="1" importable="45">
					<text v="Nhóm 2" e="Group 2"></text>
					<viewInfo lookupType="One" lookupId="dmnh" lookupKey="ma_loai_nh = 'VT2' and status=1" lookupCheck="ma_loai_nh = 'VT2'" lookupRef="ten_nh_vt2" lookupInfo="dmnh|ma_nh|ten_nh" importCheck="@@DF and z.ma_loai_nh = 'VT2' and z.status=1"/>
				</field>
				<field name="ten_nh_vt2" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
					<text v="" e=""></text>
				</field>
				<field name="nh_vt3" viewType="Lookup" label="1" field="1" importable="50">
					<text v="Nhóm 3" e="Group 3"></text>
					<viewInfo lookupType="One" lookupId="dmnh" lookupKey="ma_loai_nh = 'VT3' and status=1" lookupCheck="ma_loai_nh = 'VT3'" lookupRef="ten_nh_vt3" lookupInfo="dmnh|ma_nh|ten_nh" importCheck="@@DF and z.ma_loai_nh = 'VT3' and z.status=1"/>
				</field>
				<field name="ten_nh_vt3" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
					<text v="" e=""></text>
				</field>
				<field name="ma_kho" viewType="Lookup" label="1" field="1" clientDefault="true" importable="55">
					<text v="Mã kho" e="Site"></text>
					<viewInfo lookupType="One" lookupId="dmkho" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_kho" lookupInfo="dmkho|ma_kho|ten_kho" importCheck="@@DF and z.status=1"/>
				</field>
				<field name="ten_kho" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as "  clientDefault="true">
					<text v="" e=""></text>
				</field>
				<field name="ma_vi_tri" viewType="Lookup" label="1" field="1" clientDefault="true" importable="60">
					<text v="Mã vị trí" e="Location"></text>
					<viewInfo lookupType="One" lookupId="dmvitri" lookupKey="status=1 and ma_kho = ![ma_kho]!" lookupCheck="ma_kho = ![ma_kho]!" lookupRef="ten_vi_tri" lookupInfo="dmvitri|ma_vi_tri|ten_vi_tri" importCheck="@@DF and z.ma_kho = a.ma_kho and z.status=1"/>
				</field>
				<field name="ten_vi_tri" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as "  clientDefault="true">
					<text v="" e=""></text>
				</field>
			</fields>
		</form>
		<form tabPageIndex="2" gravity="MiddleLeft" height="350" columns="140,120,240" >
			<text v="Bảo hành" e="Guarantee"></text>
			<fields>
				<field name="ma_imei" format="U" label="1" field="1" importable="65">
					<text v="Mã imei" e="Imei Code"></text>
				</field>
				<field name="so_ngay_sp" label="1" field="1" dataType="N" format="Amount" importable="67">
					<text v="Vòng đời sp (số ngày)" e="Product Lifecycle (days)"></text>
				</field>
				<field name="so_ngay_bh" label="1" field="1" dataType="N" format="Amount" importable="68">
					<text v="Tg bảo hành (số ngày)" e="Warranty Period (days)"></text>
				</field>     
			</fields>
		</form>
		<form tabPageIndex="3" gravity="MiddleLeft" height="350" columns="120,120,240" >
			<text v="Kích cỡ/Màu sắc" e="Size/Color"></text>
			<fields>
				<field name="ma_vt2" format="U" label="1" field="1" importable="69">
					<text v="Mã phụ" e="Other Code"></text>
				</field>
				<field name="nuoc_sx" label="1" field="2" importable="70">
					<text v="Nước sản xuất" e="Manufacturer"></text>
				</field>
				<field name="mau_sac" label="1" field="2" importable="75">
					<text v="Màu sắc" e="Color"></text>
				</field>
				<field name="kich_co" label="1" field="2" importable="80">
					<text v="Kích cỡ" e="Size"></text>
				</field>
				<field name="kieu" label="1" field="2" importable="85">
					<text v="Kiểu" e="Style"></text>
				</field>
			</fields>
		</form>
		<form tabPageIndex="4" gravity="MiddleLeft" height="0" columns="120,120,360" >
			<text v="Hình ảnh" e="Images"></text>
			<fields>
				<field name="ximage" label="1" field="2" viewType="Image" fieldType="EXParam">
					<text v="Chọn hình ảnh" e="Chọn hình ảnh"></text>
					<viewInfo fileFieldId0="ma_vt" fileGroup="Fee" fileExtension="jpg,png" maxFileSize="10240" maxFileCount="10"></viewInfo>
				</field>
			</fields>
		</form>
		<form tabPageIndex="5" gravity="MiddleLeft" height="350" columns="120,120,240" >
			<text v="Khác" e="Other"></text>
			<fields>
				<field name="sl_min" label="1" field="1" dataType="N" format="Qty" importable="90">
					<text v="Tồn tối thiểu" e="Minimum Quantity"></text>
				</field>
				<field name="sl_max" label="1" field="1" dataType="N" format="Qty" importable="95">
					<text v="Tồn tối đa" e="Maximum Quantity"></text>
				</field>
				<field name="ngay_nhap" label="1" field="1" dataType="D" importable="96">
					<text v="Ngày nhập cuối" e="Last Receipt Date"></text>
				</field>
				<field name="ngay_xuat" label="1" field="1" dataType="D" importable="97">
					<text v="Ngày xuất cuối" e="Last Issue Date"></text>
				</field>
				<field name="ghi_chu" allowBlank="true" label="1" field="-" rows="3" importable="100">
					<text v="Ghi chú" e="Notes"></text>
				</field>
				<field name="status" viewType="Combobox" inactivate="true" label="1" field="2" valueDefault="1" importable="-1">
					<text v="Trạng thái" e="Status"></text>
					<viewInfo>
						<options>
							<option val="1">
								<text v="1 - Còn sử dụng" e="1 - Use"></text>
							</option>
							<option val="0">
								<text v="0 - Không sử dụng" e="0 - Not use"></text>
							</option>
						</options>
					</viewInfo>
				</field>
			</fields>
		</form>
	</forms>

	&DefaultButton;

	<js>
		<text>
			<![CDATA[<enc>rfywcmObC04SarYGwFsTseAhCjrCZ6FrMZ4OnTm4K5Y0iD+4oMJCUrmE3fa6IQJEQSWAtrqKobyQo6MjVF70H6oEmygMnuM2tJQ6pEPnGng/c2Azx4niCMFZGKjvSOhBL9gJ4K5QHrmbm1PMZBMc1pvY4pbIaP4KFtoExc2aXt/nR0DA0ZHFeYhE+X4AP0eW5DCnT+DIy6g+EMzYt9+OlTmlO/EnE1AGlsm59kEEEPSFOukWQMzgXtkFn+rFx7pmZUoP66wDG6dsRQXCsVL+tzpIakwv+GrUc4WXfiBwqDjEurJ2Zc3d9qiJtfAro36aHAvSlKoBf/EhvlGY2E1xAM2Zk/gJzFSC9pN5zZIMSpWzqJNhUeaX4lB6e8TbOLYZUr3qaIbdamq47oZI2iMdP2KhjBKmPXtkBj3soQENS4uKPf5AquuFjh6ECCTe6ex6</enc>]]>
		</text>
	</js>
	
	<css>
		<text>
			<![CDATA[<enc>p8Jv6giswZ7gKMwflAwRnNif0NFIzu3ucm4CBKpYIP0=</enc>]]>
		</text>
	</css>

	<script>
		<request code="request_code_unit">
			<text> 
				<![CDATA[<enc>gzJrT4xu5mtr7+EhBmJgUGe64dLfJ8ACKKBC8gacqfJLECCo5N8oLx/bfUCVlybixpyfV0B6fxnd4jJJG82Clxc6c5rBj5SCZrrG/3ZCior9f3Ra3bSL8VC4YUSVKhjq06OBwNsbWr2oHLdoq0sdLgGRWo9VVcLMpVZPe1gJ4pLlJ1gXwzZ10CFV7yxACfZ7g2kkq9GGO1yt+06ZWFAOfjuOvYxugDART3evlv+pwDW+TJpN0mdzTZR1h34jtUWfseVYzSbLbK3T3iM+RkgUManij692UwU4IFNErdoUEbw=</enc>]]> 
			</text>
		</request>
		<query>
			<text>
				<![CDATA[<enc>SBayJrZ/GcBJn5rvpLYxsiXYV/7t8OpKAKZwm1ILLaLqrOtVY7DIQbwZ+AHdpV6/9OO8EJg6TUmdwE93UnkunJ6ucBD9hNpM6qrvRw8b9Ts0S5D8ud4susR0cR0oWyZ28wBuklA/CuJRorhgTK7hkIHBfzTN5nQD7r6QD3mNvdZd9tOJ64dZSZM2eQiDOEIM4CZpHZ4rPVS0SaKVEQ0pMHWBYZExjyJJIgRIsWMug6z4oP/0NMzTbNw6tISRDHgLp+sLaQw9/vS8GKoH1RE+Apxhata1CiBVVJUKClO4Sc8oXpBawixdTJYJf8XbG4BsryAINno2mLZUjD4oPjSA/9ck/XFuHO2Y0ID2wNjuU2UKm/LlQnYnHNbF/JeLvkDakECHkDXBECEz+mHc6B/T8pDi+0fALJSTaOIkSDy2Y+sY8tt8Ol7/qrKmrLjj++OUkz5K1/fHVEKJ65ROG+eCiQ==</enc>]]>
			</text>
		</query>

		<loading>
			<text>
				<![CDATA[<enc>yR1E57ukVCLmcZS/15gUZrLrROMk3naPMqwG6IyIpXWh5rZ2D4XlTicYbBS7xhzqsfnLYY/iXe7NdD4NYDIQQo3kMRJxuMrkr6qgmFCDHUI=</enc>]]>
			</text>
		</loading>

		<deleting>
			<text>
				<![CDATA[<enc>wpQRktacvABtD9QYiEoVXXBJlrbYgTUhw4+BJzdHRnU1V0D/ha3lhz+D2STe5QD688YDv+QA3ltezh5u+gqrDKafkFYazJXkrU2+aDpqV/F8YsuZMwPHKXGQnGUrNpeUrR5nS3vJqUHniGHgLwUXoJSeIMEC2MkaKUA3rZ0UB2IfNViBlBRYJdNnVRPzUE/e1/XI+4MVVs0TbcgLHVaKRA==</enc>]]>
			</text>
		</deleting>

		<updated>
			<text>
				<![CDATA[<enc>1b1INIQKRz2gLcZbOz6dVgdw7Dhn2nNXkQk9a1WF/Np2v2GdKyJf1DgUTziWyZ3whs1n+6EX54N/gkQ++Y/xEy0qnThXYcPhcWH7JsOTcvIaf3JxAMuXtoIDeR9MuV+ad7ziMBOWxQp7tsOX8ieD7P8IeSjlXBu9qnkuhFAZ6MsuGmn9ILVNyrjs8xSRhZpY</enc>]]>
			</text>
		</updated>
		
		<inserting>
			<text>
			<![CDATA[<enc>w8ckaGfi+JLvRoBu68qTdFjM4tvGlzwJQLdgFldug2V9YJXfTd1GoGle/eEzSBnk3fklrznPWOUjOC7x5DFgvfKXYPj4I9FPoJ72JXwuLF8soqT0/YzAjcByY48aAj+zWR/xrJ9XPylXfeNXqQEdqNZbtrjUSAl/GIpGkfOir8m3l5YplnJ6/T1+OJ8e3agoZVTXdLxIU8RfAN12OfaR9vORJj9RFFQCZmTo/+c+/3SJoEfYvNe5qUvWZYn2jtLN</enc>]]>
			</text>
		</inserting>
		<inserted>
			<text>
				<![CDATA[<enc>9wBF2jk6v0PpznkGvdlFyI19BD3nLR1dZlOTF0Z/ccpYfMdKoJLuX1lZXB9yMvy+wTw++oCJAbkfpGamAPOuZQgaCyT3fLDiNJeT+elFKlWa7tFrzdx2bzUx68E5jGwfpLdle/7+vxRkOCycQRFt3bmi2+NETnqxEWap/D+zkRoA1D4ibJMFN09Sfged1uHb</enc>]]>
			</text>
		</inserted>

		<aftersave>
			<text>
				<![CDATA[<enc>A9L02moLrgvoKp8FnDA62e1FQo0KFCPC0hnUt8GF1cq86ZEmiVDldnW/mH2r9VEYSjcVpiH09nnh2rW621FbeWuglLF4dtXXc5sjw+pXmHkVhDlgZNWfasksW8Ztp7xUJ5RimP9M0GRlWkf/dHSUOnUFXbioMOQu/q2LEkJcve9PfcLk2dMBeORXuM6hcQj565/B9668ng2vkxdg/9RZEg==</enc>]]>
			</text>
		</aftersave>
		<importing>
			<text>
				<![CDATA[<enc>CWQZvQUeCtk1G1Xnsp3vN4m8Hc+i9HnHDbuqWeErzn9R1b6tkLe3Hf+aC0qhedFoa6+d6PUHun1VBTYTJB83rnippYFqPbzmLr12w/sDrIg=</enc>]]>
			</text>
		</importing>
	</script>

	<messages>
		<message val="codeExistsNewMsg">
			<text v="Mã vật tư đã tồn tại trong danh mục vật tư." e="The record already exists."/>
		</message>
		<message val="codeExistsEditMsg">
			<text v="Mã vật tư đã tồn tại trong danh mục vật tư." e="The record already exists."/>
		</message>
	</messages>
</dir>