<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>

<dir id="qlhccong" table="qlhccong" fieldKey="ma_hccong, stt" transaction="true" tryCatch="true" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Quản lý hành chính công" e="Public Administration Management."></title>
  <title0 v="Thêm mới - hành chính công" e="New - public administration"></title0>
  <title1 v="Sửa - hành chính công" e="Edit - Public Administration"></title1>

  <forms>
	<form gravity="TopLeft" columns="120,120,120,120,120" >
		<fields>
			<field name="unit_id" dataType="I" hidden="true" readOnly="true" inactivate="true" label="1" field="1" importable="-1">
			  <text v="" e=""></text>
			</field>
			<field name="ma_hccong" allowBlank="false" viewType="Lookup" label="1" field="1"  hidden="false" fieldType="PK">
			  <text v="Mã hành chính công" e="Public Administration Code"></text>
			  <viewInfo lookupType="One" lookupId="dmhccong" lookupKey="status = 1" lookupCheck="1=1" lookupRef="ten_hccong" lookupInfo="dmhccong|ma_hccong|ten_hccong" />
			</field>
			<field name="ten_hccong" nextRow="false" fieldType="EX" readOnly="true" inactivate="true"  hidden="false" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
			  <text v="" e=""></text>
			</field>
			<field name="stt" dataType="N" label="1" field="1" disabled="true" format="0" hidden="false" nextRow="true" fieldType="PK">
				<text v="Số thứ tự" e="STT"></text>
			</field>
			<field name="thoi_gian" label="1" field="1" allowBlank="true" disabled="true" nextRow="true" >
				<text v="Thời gian" e="Time"></text>
			</field>
			<field name="tg_dukienbd" label="1" field="1" allowBlank="true" disabled="true" nextRow="true" >
				<text v="TG dự kiến bắt đầu" e="Estimated Start Time"></text>
			</field>
			<field name="tg_dukienkt" label="1" field="1" allowBlank="true" disabled="true" nextRow="true" >
				<text v="TG dự kiến kết thúc" e="Estimated End Time"></text>
			</field>
			<field name="error" label="1" field="1" fieldType="EX" readOnly="true" inactivate="true" hidden="true">
			  <text v="" e=""></text>
			</field>
      </fields>
    </form>
	<form gravity="TopRight" columns="120,120" >
		<fields>
			<field name="ngay_ct" label="1" field="1" valueDefault="new Date()" copy="false" allowBlank="false" dataType="D">
			  <text v="Ngày đăng ký" e="Resgiter Date"></text>
			</field>
			<field name="status" viewType="Combobox" valueDefault="5" inactivate="true" label="[60]" field="[180]" >
			  <text v="Trạng thái" e="Status"></text>
			  <viewInfo>
				<options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = 'HC1' and status = 1 order by stt">
				</options>
			  </viewInfo>
			</field>
		</fields>
    </form>
</forms>

&DefaultButton;

<js>
    <text>
  <![CDATA[<enc>vH0l48A3Ncctxxn5OOGN+ujQoSm1/7qokAwBApvNTCPFBmcqFbl+1ZhA2cuwh+w3PpxsDcWqZ40J7KVK6sK6FXq60zSCTwnLsaRAbown3o4HGcKn895Em4a8evkVODSe3ZhCooEiIl3ybplsDbOKEnK095YL4rslJAmDAcbJcFrezeZLvAdqVu+M90EEtfOx6jasJGDO2Zro7qqtxVVabMk8sY1U2xMqpSY//kokze7AOFDUSKQNANXklLfuj7jAzfsQ2gy2jpJ7gU7c7hGrGQoA2Smr5p10uIL7Bk9VQlPNFege0Z2dD+lgRmoT5oITie8iduWOpfjMmYZnpg4i9b6GtTeOZ9kAwWDCkKzdRQMJ6LcXNY8cdUAL9fxevRFtLuEcqnjrCW5P3895IjIvCKxGzWgfo4JenBqqN2i99LzSUdcV5njLoTyXetfWX+ljqzPDhtmwE2dA5NqW95a5V3BuOLGq/+mggSUcAbL+i7ujwnhH6aQ6e6sytto+zXmGSFKzYgwTjNGiBkRz8hM/cA16AP1iQqLhQRHZTydqwPkPAkSssV2SbNEZ+q0/Uk9p2LTKi5FRBttjUWCf3GbS3ne0v5yCAPXxAgzEmXUdB7OFpvXIvumPEe9SNGhOzPRj</enc>]]>
    </text>
  </js>
	<css>
		<text>
			  <![CDATA[<enc>AAdll/pZu2N+c7RH98PhWZFrccmREmDJzWIiKsMQ5jGwc4P8Lch98yuQ+ksmlIX2NayGADyNNdzfHnO/pSqgjXA+nhaxU7dllHCyqRYC4bCLN55vO5k+7ZFA1C4p+2FwBuiF5DRVctGyXdBSapGiVT4MFiQHxmPagQCaYr9I/6QhyH1tAkTnhHRzemM93njq</enc>]]>
		</text>
	</css>
	<script>
	<request code="requestHCCONG">
		<text> <![CDATA[<enc>/5SOpJOcVJwXZVe4zaOuP6vNfY9N25PCmu3Xq89820wqbb/Prb0FtylmF1oRHFUdgNG5n3qTbd/Jf7iW+AknKurxHrIUK0XMOeGeCMw0hLjjT7soQh/wtwlrYfvs952IRACUID1151HGCinWFBohQtY7YWhcsg8cTui9RVXejobJuwrpUBXJALHbg/b/iggKyuZuXW+pVOVSwvffQU+hkqbZcpilCMPCnrjVIoFFIA/e42tw5230BBFdBEbfzgeQRu/8MjVjeCMdvxEl8D2UFI+8TPiqairF6lk4AsV3aceNC8brsIugLB4Qc303MIa0</enc>]]> </text>
	</request>
		<query>
		  <text>
			<![CDATA[<enc>GJgBVkOd9xy3In+SUACpOOdXdTQbLjDNG098RVYG+mqJrACGNi8MwNsRrtmQkuMIYyR65+M+8FdE2nQkBtdUjjGtkBSGsDqbRbA3vrYN89ZzUnQVJ+W1/9AMkiZ8xTjPYAdSbE6TNHswawXCA3Q7ZKpywgArBHY6CKMo02cq6Ek=</enc>]]>
		  </text>
		</query>
		<updated>
		  <text>
			<![CDATA[<enc>sxD5Swu0R4mcxEHdwcy2ynVkJ6IiRfsuHiDzDrC78ELIJg2k4xX5PxEITwgSuDtWSiTOU3sqnIo/Bv0T8e877uKHW6bIEuTFdpbPdQB+xElll2tzxh9iUOpwbot+jXTZNKo5+n5Fy+aXD8VrO81PEw==</enc>]]>
		  </text>
		</updated>
		<inserting>
		  <text>
			<![CDATA[<enc>/T/6v4fr7JtuEWROY5bEog4q37AdyKX5y50iwuf8o+kQ/cMLdjO5yBgIja/EXDIb67gjtJCgsvsoKVHnH40ASfHmT/5Pyqyz9fEF+eXazaeFq1QdO25I17j8uqKw4sm7PDDzWS+uYkqIWo1FmMQqY1vwSihUQwhC3DMwYBlMdqW/7I05kvZGgi3lyKQDrJ1gd1u3eDHWrXNvOq+fBosahfSLln2pO8chassI1khVi2Brg84FNLLprzwizWkmE7Kk</enc>]]>
		  </text>
		</inserting>
		<importing>
			<text>
			<![CDATA[<enc>sxD5Swu0R4mcxEHdwcy2yi46ZbQRyi0uEDh1tGVfNVOBZJeZZHskWnswm55XGvVMZq7vIrj1gngY5x8IJuKO1pkyFlxS8pifsEwHrhrpEjg=</enc>]]>
			</text>
		</importing>
	</script>
	<messages>
		<message val="codeExistsNewMsg">
		  <text v="Mã văn bản lưu hành đã tồn tại trong danh mục." e="The circulation document code already exists in the list."/>
		</message>
	</messages>
</dir>
