<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>

<dir id="tb_Brand" table="tb_Brand" fieldKey="Id" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Thương hiệu" e="Category Type List"></title>
  <title0 v="Mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120,120" >
      <fields>
       <field name="Id" disabled="true" fieldType="PK" width="100" filterType="Code">
          <text v="Mã thương hiệu" e="Brand code"></text>
        </field>
        <field name="Title" width="250">
          <text v="Tên thương hiệu" e="Brand name"></text>
        </field>	
        <field name="Alias" width="250">
          <text v="Alias" e="Alias"></text>
        </field>			
        <field name="Description" width="120">
          <text v="Mô tả" e="Description More"></text>
        </field>
		<field name="Detail" width="120">
          <text v="Chi tiết" e="Detail"></text>
        </field>
		<field name="Position" width="120" valueDefault="1">
          <text v="Thứ tự" e="Position"></text>
        </field>
		<field name="IsActive" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
		<field name="SeoTitle"  width="120">
          <text v="SEO Title" e="SEO Title"></text>
        </field>
		<field name="SeoDescription"  width="120">
          <text v="Seo Description" e="Seo Description"></text>
        </field>
        <field name="SeoKeywords" width="250">
          <text v="Seo Keywords" e="Seo Keywords"></text>
        </field>
      </fields>
    </form>
	<!-- <form gravity="TopRight" columns="120,120" > -->
      <!-- <fields> -->
	    <!-- <field name="ngay_dk" label="1" field="1" dataType="D"> -->
          <!-- <text v="Ngày đăng kí" e="Registration date"></text> -->
        <!-- </field> -->
		<!-- <field name="ngay_dk_ld" label="1" field="1" dataType="D" > -->
          <!-- <text v="Ngày đăng kí lần đầu" e="First registration date"></text> -->
        <!-- </field> -->
		<!-- <field name="han_dk" label="1" field="1" dataType="D"> -->
          <!-- <text v="Hạn đăng kí" e="Registration deadline"></text> -->
        <!-- </field> -->
		<!-- <field name="tai_trong" label="1" field="1" dataType="N"> -->
          <!-- <text v="Tải trọng" e="Weight"></text> -->
        <!-- </field> -->
		<!-- <field name="dung_tich" label="1" field="1" dataType="N"> -->
          <!-- <text v="Dung tích" e="Capacity"></text> -->
        <!-- </field> -->
	  <!-- </fields> -->
    <!-- </form> -->
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>dJDvh1j08T18JreEmGCmnYmp8ssROgAsgv71FnmNqvHzwAslTInmKSgH7ukvPaz23R4DjPNr4hvbdFy+bsyGnTHF9cFJVf+y1vW/+P+ZK9j/PRapeGgK2JhkGMq+6JCFJiHo8J0Ge55Wwt8Sa1qasCIRW5Sa8Z6c+AZd7HTeqVVdEuHTYW2TGmTf4pbOys4GEt2hyXapWohu5X9mXQdG6j+7ULcP7aDqVcJDLITgl97/yj13sMQ6T5KzQGa38TL0utm/pu4G++HfuhakmgVa6aCIYZj/Q7fvWFIpn5mGf2o=</enc>]]>
    </text>

  </js>

  <script>
  <request code="get_id">
			<text> <![CDATA[<enc>8UP5znVoHpHEvb3lYZoLYUbhX9rYqQHH0KBquBhC1NQEMisWG7p1KTszM89SancC3eZtZpLmKlAheV8/j+LfEQ==</enc>]]> </text>
	</request>

    <declare>
      <text>
        <!-- <![CDATA[<enc>DIgruXSDtKnCR15GyIWsKUFwRJRgdGFXg69aVYLm49FLxhTawwa/Frs6s0uyC0vdWhX+521yRNvpXzLVgsUIW/OuRJJbCfYsZ0lwzGdszkmx1xW7L9cBlCjs6uy0hciRbHmUvQ5X8PZB0KlSob1eaADPyc2BR1s5F/OxmOlbN+LIi4wBBVKuETEOp5UPyhl9yPFOQuIcEzHpVt/ciEKS9dJl6Pn+T6QnZUQENKKTCO6Q0pXTnJiL+TaQoxZebDRW</enc>]]> -->
      </text>
    </declare>
  </script>

</dir>