<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>

<dir id="tb_Post" table="tb_Post" fieldKey="Id" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Bài viết" e="News"></title>
  <title0 v="Mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120,120" >
      <fields>
       <field name="Id" disabled="true" fieldType="PK" width="100" filterType="Code">
          <text v="Mã Bài viết" e="Brand code"></text>
        </field>
        <field name="Title" width="250">
          <text v="Tên Bài viết" e="Brand name"></text>
        </field>	
        <field name="Alias" width="250">
          <text v="Alias" e="Alias"></text>
        </field>
		<field name="CategoryId" viewType="Lookup" label="1" field="1" >
          <text v="Mã danh mục" e="Category Code"></text>
          <viewInfo lookupType="One" lookupId="tb_Category" lookupKey="IsActive=1" lookupCheck="1=1" lookupRef="CategoryName" lookupInfo="tb_Category|Id|Title"/>
        </field>
		<field name="CategoryName" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
			<field name="Image" label="0" field="1" viewType="Image">
          <text v="" e=""></text>
          <viewInfo fileFieldId0="user_id" fileGroup="SysUser" fileExtension="jpg,png" maxFileSize="10240" maxFileCount="2"></viewInfo>
        </field>
		<field name="Image" width="200">
		<img src="path/to/image.jpg" alt="Image Description" />
		</field>		
        <field name="Description" width="120">
          <text v="Mô tả" e="Description More"></text>
        </field>
		<field name="Detail" width="120">
          <text v="Chi tiết" e="Detail"></text>
        </field>
	 
		<field name="IsActive" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
		<field name="SeoTitle"  width="120">
          <text v="SEO Title" e="SEO Title"></text>
        </field>
		<field name="SeoDescription"  width="120">
          <text v="Seo Description" e="Seo Description"></text>
        </field>
        <field name="SeoKeywords" width="250">
          <text v="Seo Keywords" e="Seo Keywords"></text>
        </field>
      </fields>
    </form>
	<!-- <form gravity="TopRight" columns="120,120" > -->
      <!-- <fields> -->
	    <!-- <field name="ngay_dk" label="1" field="1" dataType="D"> -->
          <!-- <text v="Ngày đăng kí" e="Registration date"></text> -->
        <!-- </field> -->
		<!-- <field name="ngay_dk_ld" label="1" field="1" dataType="D" > -->
          <!-- <text v="Ngày đăng kí lần đầu" e="First registration date"></text> -->
        <!-- </field> -->
		<!-- <field name="han_dk" label="1" field="1" dataType="D"> -->
          <!-- <text v="Hạn đăng kí" e="Registration deadline"></text> -->
        <!-- </field> -->
		<!-- <field name="tai_trong" label="1" field="1" dataType="N"> -->
          <!-- <text v="Tải trọng" e="Weight"></text> -->
        <!-- </field> -->
		<!-- <field name="dung_tich" label="1" field="1" dataType="N"> -->
          <!-- <text v="Dung tích" e="Capacity"></text> -->
        <!-- </field> -->
	  <!-- </fields> -->
    <!-- </form> -->
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>JiqXEVO9kvC8fpKgDpluN61MyauLrP2wuDQ6ql8SYozUM4AKcNJDW9uTgTSCQDL2ERoSOiFwea5P8OXeBWdGZxRZuA5mMVUfY+w7kUVVfbYTqPBGQgbwu/DFBOu0tVPRLzy9F71a0VXcBdqz8JKXUkJr5A/sOKzOM1+JAPHfxFgJ3LHJ1dPQIyw2ZAkHU+uUVowfPQsT18kuLBYSjoTTbkWrky5sLJOmTXjmkLnLtgNL4qvYaHPk071zOHxH2lSESHTGEsfX+WhiKcbD2WqTFGxcZ6WeoKqmkalHUUNwUR0=</enc>]]>
    </text>

  </js>

  <script>
  <request code="get_id">
			<text> <![CDATA[<enc>8UP5znVoHpHEvb3lYZoLYUbhX9rYqQHH0KBquBhC1NQE67CsmHyhIcn729US3WfRN5Ymwa7gD2e10mCSRTpdsA==</enc>]]> </text>
	</request>

    <declare>
      <text>
        <!-- <![CDATA[<enc>DIgruXSDtKnCR15GyIWsKUFwRJRgdGFXg69aVYLm49FLxhTawwa/Frs6s0uyC0vdWhX+521yRNvpXzLVgsUIW/OuRJJbCfYsZ0lwzGdszkmx1xW7L9cBlCjs6uy0hciRbHmUvQ5X8PZB0KlSob1eaADPyc2BR1s5F/OxmOlbN+LIi4wBBVKuETEOp5UPyhl9yPFOQuIcEzHpVt/ciEKS9dJl6Pn+T6QnZUQENKKTCO6Q0pXTnJiL+TaQoxZebDRW</enc>]]> -->
      </text>
    </declare>
  </script>

</dir>