<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>

<dir id="tb_Product" table="tb_Product" fieldKey="Id" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Sản phẩm" e="Product List"></title>
  <title0 v="Mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120,120" >
      <fields>
       <field name="Id" fieldType="PK" width="120">
          <text v="Mã sản phẩm" e="Product code"></text>
        </field>
		 <field name="Title"   width="120">
          <text v="Tên sản phẩm" e="Product name"></text>
        </field>
		<field name="Alias"  width="120">
          <text v="Alias" e="Alias"></text>
        </field>
		<field name="ProductCode"  width="120">
          <text v="Code sản phẩm" e="Product code"></text>
        </field>
		<field name="ProductCategoryId" viewType="Lookup" label="1" field="1" >
          <text v="Mã loại sản phẩm" e="Product category code"></text>
          <viewInfo lookupType="One" lookupId="tb_ProductCategory" lookupKey="IsActive=1" lookupCheck="1=1" lookupRef="ProductCategoryName" lookupInfo="tb_ProductCategory|Id|Title"/>
        </field>
		<field name="ProductCategoryName" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
		<field name="PromotionId" viewType="Lookup" label="1" field="1" >
          <text v="Mã khuyến mãi" e="Promotion code"></text>
          <viewInfo lookupType="One" lookupId="tb_Promotion" lookupKey="IsActive=1" lookupCheck="1=1" lookupRef="PromotionName" lookupInfo="tb_Promotion|Id|Title"/>
        </field>
		<field name="PromotionName" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
		<field name="BrandId" viewType="Lookup" label="1" field="1" >
          <text v="Mã thương hiệu" e="Brand Code"></text>
          <viewInfo lookupType="One" lookupId="tb_Brand" lookupKey="IsActive=1" lookupCheck="1=1" lookupRef="BrandName" lookupInfo="tb_Brand|Id|Title"/>
        </field>
		<field name="BrandName" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
		<field name="Description" width="120">
          <text v="Mô tả" e="Description"></text>
        </field>
		 <field name="Detail"  width="120">
          <text v="Chi tiết" e="Detail"></text>
        </field>
		<field name="Information"  width="120">
          <text v="Thông tin sản phẩm" e="Information"></text>
        </field>
		
		<field name="Image" label="1" field="2" viewType="Image" fieldType="EXParam">
          <text v="" e=""></text>
           <viewInfo fileFieldId0="Id" fileGroup="Item" fileExtension="jpg,png" maxFileSize="10240" maxFileCount="1"></viewInfo>
        </field>
		 

		<field name="Price"  width="120" dataType="N">
          <text v="Giá gốc" e="Price"></text>
        </field>
		<field name="PriceSale"  width="120" dataType="N">
          <text v="Giá khuyến mãi" e="Price sale"></text>
        </field>
		<field name="Quantity" width="120">
          <text v="Số lượng" e="Quantity"></text>
        </field>
		<field name="Guarantee" width="120">
          <text v="Bảo hành" e="Guarantee"></text>
        </field>
		<field name="ViewCount" width="120">
          <text v="Số lượt xem" e="View count"></text>
        </field>
		<field name="Position"  width="120">
          <text v="Thứ tự" e="Position"></text>
        </field>
		<field name="SeoTitle"  width="120">
          <text v="Seo Title" e="Seo Title"></text>
        </field>
        <field name="SeoDescription" width="250">
          <text v="Seo Description" e="Seo Description"></text>
        </field>
		<field name="SeoKeywords" width="250">
          <text v="Seo Keywords" e="Seo Keywords"></text>
        </field>
		<field name="IsActive" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
		<field name="IsHome" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Trang chính" e="Is Home"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
		<field name="IsFeature" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Tính năng" e="Is Feature"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
		<field name="IsSale" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Khuyễn mãi" e="Is Sale"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
		<field name="IsHot" viewType="Combobox" inactivate="true" label="1" field="2" >
          <text v="Nổi bật" e="Is Hot"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="1 - Còn sử dụng" e="1 - Use"></text>
              </option>
              <option val="0">
                <text v="0 - Không sử dụng" e="0 - Not use"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
	<!-- <form gravity="TopRight" columns="120,120" > -->
      <!-- <fields> -->
	    <!-- <field name="ngay_dk" label="1" field="1" dataType="D"> -->
          <!-- <text v="Ngày đăng kí" e="Registration date"></text> -->
        <!-- </field> -->
		<!-- <field name="ngay_dk_ld" label="1" field="1" dataType="D" > -->
          <!-- <text v="Ngày đăng kí lần đầu" e="First registration date"></text> -->
        <!-- </field> -->
		<!-- <field name="han_dk" label="1" field="1" dataType="D"> -->
          <!-- <text v="Hạn đăng kí" e="Registration deadline"></text> -->
        <!-- </field> -->
		<!-- <field name="tai_trong" label="1" field="1" dataType="N"> -->
          <!-- <text v="Tải trọng" e="Weight"></text> -->
        <!-- </field> -->
		<!-- <field name="dung_tich" label="1" field="1" dataType="N"> -->
          <!-- <text v="Dung tích" e="Capacity"></text> -->
        <!-- </field> -->
	  <!-- </fields> -->
    <!-- </form> -->
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>ROauGl1B11VGsIPpKHkYMDSrHoImMOKL4MCkWpqA5S1/lsfzXtHGS/Ozli81yNNxo6DsfYuvjCrLQJLhTEciHEDwdG+WQUCKhGVeH8ehZN572S2hJzH6+X30BOS1Wh/w0MJEtk5wIZ+K6+5B9ErPa61l+Zz+TZyxXTg4KTT9uIYki0WBBhLKjVF950wColmCIqXcrLjnAaoDkcjQjCtOu3nK+7lAzJnY5wLkwbM90Qkm8Py6q6yjDuCSmx/sYkSwPhHXlsn4bjTaJg+rJF0N7MiozWIbRala0dKwefVrvdA=</enc>]]>
    </text>

  </js>

  <script>
  <request code="get_id">
			<text> <![CDATA[<enc>8UP5znVoHpHEvb3lYZoLYUbhX9rYqQHH0KBquBhC1NRel3UjxRkgVGdnLvxzqJkVTxmxiWbkLc6hTWWJ1gqE9A==</enc>]]> </text>
	</request>

    <declare>
      <text>
        <!-- <![CDATA[<enc>DIgruXSDtKnCR15GyIWsKUFwRJRgdGFXg69aVYLm49FLxhTawwa/Frs6s0uyC0vdWhX+521yRNvpXzLVgsUIW/OuRJJbCfYsZ0lwzGdszkmx1xW7L9cBlCjs6uy0hciRbHmUvQ5X8PZB0KlSob1eaADPyc2BR1s5F/OxmOlbN+LIi4wBBVKuETEOp5UPyhl9yPFOQuIcEzHpVt/ciEKS9dJl6Pn+T6QnZUQENKKTCO6Q0pXTnJiL+TaQoxZebDRW</enc>]]> -->
      </text>
    </declare>
  </script>
  <script>
       <query>
      <text>
        <![CDATA[<enc>GyqTBrshNfUvxEq58a7Fg5V+5ZK0lHRx0URaqILXcx7zm/sfLboI1omuBhkyQQ/g7ujF3KVXzEyrzZQJtop3mrr6YjgxFg9z6ZvOjT/c9ZLTY7lGT8DC1Zlf9olmLxOVTaqxO+/tw5MtRW/vtjSrTt0CSQ+FZcAoxmlO/4u8BLQxfHaiqZNvbmxI/TyozR9q7dCiFC81yacKb+rLUNAT9sxMbnafz55CKgrUrk3NQBdK58Hspy0i9QwJYp+6p143JEeZaLfx5WooYqGKAaqegZvUZA7csoZPR5HKAdlNkBj7z8qgr2saMj8f9TvFfor8ei/IPSV0nghvNHrcVwopyj1qLKTPa/cCdIcZz64Xhx7oVe3FMacoxPij8/PLuJBG7UoV4DkggULoncyr7Sb9u5UNWVkFWyYvGnEUW8s84F6+TQWEUxGfj4nwuKd+uCPFr50M7++/WDXIBlYmvNKi+w==</enc>]]>
      </text>
    </query>
	    <updated>
      <text>
        <![CDATA[<enc>dijbzDLMK0LZYagC6QUqKUUXaFeo4+IW3QhBjRehzBtFuQvClW4FWQX8hqa75nVP5NzL41VrYI0UNecaMfEmHTnfPAsUg6qgFo6LD2JFeHS/DIyEfV3dqkUZZsryL9wTsXX9VnDKVlF9fQHwz7+NHf5JZKSLD7XOUfLjQQlg6JQ0tS7PVG0JySoIIoOKo2Ku</enc>]]>
      </text>
    </updated>
    
    <inserting>
      <text>
        <![CDATA[<enc>/T/6v4fr7JtuEWROY5bEopFO1HCnIjtZjFzzDG3F9/vEkIfRrRIYFlNT+1c2A+G4DGK3P1V1ru+z1kGXJXjR1VzP1TAM3KziUQ39S5UPAFO5TtFkd+A7rjU9Cj84+ron+NnAUl09CZS+jY4xst+ifUx/y0L2N86LSRXXWB0b2jLk9z1JyBTjpFwFo33O8/V92Jll9ZnIKloIczVnEYCl2/5Q4n5X9mE3/5atjZjvFut8hbyHb/wqOO6O7YgIZzpT</enc>]]>
      </text>
    </inserting>
    <inserted>
      <text>
        <![CDATA[<enc>pU2rQ3VOsdZRbhcO4OoAzb/I+rqiqC8tiVnz0/DyO2l83BdQ5Eb4k/okRsQks2ewhM+pRbAoIFB62qqSTiapGxPapCUc3WxeJElAWZOYW5EihgIwwnZ6+w2ZiPWAoyvfqx7YQDWWL+8foVbmVNxo4TeLPqi4/iqVdwYB7N3/gAw=</enc>]]>
      </text>
    </inserted>
	</script>
</dir>