<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>

<dir id="tbCategoryType" table="tb_CategoryType" fieldKey="Id" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Loại danh mục" e="Category Type List"></title>
  <title0 v="Mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120,120" >
      <fields>
       <field name="Id" fieldType="PK" width="100" filterType="Code" >
          <text v="Mã loại danh mục" e="License plate"></text>
        </field>
		<!--
        <field name="Title" width="250">
          <text v="Tên loại danh mục" e="Car owner"></text>
        </field>	
		-->
        <field name="Alias" width="250">
          <text v="FuckYou" e="Alias"></text>
        </field>			
		<field name="CategoryId" viewType="Lookup" label="1" field="1" >
          <text v="Mã danh mục" e="Category Code"></text>
          <viewInfo lookupType="One" lookupId="tb_Category" lookupKey="IsActive=1" lookupCheck="1=1" lookupRef="Categoryname" lookupInfo="tb_Category|Id|Title"/>
        </field>
		<field name="Categoryname" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
        <!-- <field name="ten_loai" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as "> -->
          <!-- <text v="" e=""></text> -->
        <!-- </field> -->
		<!-- <field name="ma_nhom" viewType="Lookup" label="1" field="1" > -->
          <!-- <text v="Mã nhóm" e="Group code"></text> -->
          <!-- <viewInfo lookupType="One" lookupId="dmnhomxe" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_nhom" lookupInfo="dmnhomxe|ma_nhom|ten_nhom" importCheck="@@DF and z.status=1"/> -->
        <!-- </field> -->
        <!-- <field name="ten_nhom" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as "> -->
          <!-- <text v="" e=""></text> -->
        <!-- </field> -->
		<!-- <field name="dia_chi" label="1" field="-" > -->
          <!-- <text v="Địa chỉ" e="Address"></text> -->
        <!-- </field> -->
		<!-- <field name="nhan_hieu" label="1" field="1" > -->
          <!-- <text v="Nhãn hiệu" e="Brand"></text> -->
        <!-- </field> -->
		<!-- <field name="so_khung" label="[70]" field="[160]" nextRow="false"> -->
          <!-- <text v="Số khung" e="Frame number"></text> -->
        <!-- </field> -->
		<!-- <field name="mau_son" label="1" field="1"  > -->
          <!-- <text v="Màu sơn" e="Color of paint"></text> -->
        <!-- </field> -->
		<!-- <field name="so_may" label="[70]" field="[160]" nextRow="false" > -->
          <!-- <text v="Số máy" e="Phone number"></text> -->
        <!-- </field> -->
        <!-- <field name="status" viewType="Combobox" inactivate="true" label="1" field="2" > -->
          <!-- <text v="Trạng thái" e="Status"></text> -->
          <!-- <viewInfo> -->
            <!-- <options> -->
              <!-- <option val="1"> -->
                <!-- <text v="1 - Còn sử dụng" e="1 - Use"></text> -->
              <!-- </option> -->
              <!-- <option val="0"> -->
                <!-- <text v="0 - Không sử dụng" e="0 - Not use"></text> -->
              <!-- </option> -->
            <!-- </options> -->
          <!-- </viewInfo> -->
        <!-- </field> -->
      </fields>
    </form>
	<!-- <form gravity="TopRight" columns="120,120" > -->
      <!-- <fields> -->
	    <!-- <field name="ngay_dk" label="1" field="1" dataType="D"> -->
          <!-- <text v="Ngày đăng kí" e="Registration date"></text> -->
        <!-- </field> -->
		<!-- <field name="ngay_dk_ld" label="1" field="1" dataType="D" > -->
          <!-- <text v="Ngày đăng kí lần đầu" e="First registration date"></text> -->
        <!-- </field> -->
		<!-- <field name="han_dk" label="1" field="1" dataType="D"> -->
          <!-- <text v="Hạn đăng kí" e="Registration deadline"></text> -->
        <!-- </field> -->
		<!-- <field name="tai_trong" label="1" field="1" dataType="N"> -->
          <!-- <text v="Tải trọng" e="Weight"></text> -->
        <!-- </field> -->
		<!-- <field name="dung_tich" label="1" field="1" dataType="N"> -->
          <!-- <text v="Dung tích" e="Capacity"></text> -->
        <!-- </field> -->
	  <!-- </fields> -->
    <!-- </form> -->
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>res7o41ZyxV7ie5eKEA1FX92CoG5jzphAZy22DPAagYsavmCoD/aHFdIiDGysS2ZET//zdbVKTf+LwOxWJtu6LCPUqqreqajn9G9L79WcGmADJT1AguXWVCccKN8W0ikoAUcctF45PeP46EQYdiXBO4TTxmZlel6Spi2VRXLdcx9g/5f46Ht7Xsh2Ux67wVlFqzFLZIsOUmNhe4DWPmIfA==</enc>]]>
    </text>
  </js>

  <script>
    <declare>
      <text>
        <!-- <![CDATA[<enc>DIgruXSDtKnCR15GyIWsKUFwRJRgdGFXg69aVYLm49FLxhTawwa/Frs6s0uyC0vdWhX+521yRNvpXzLVgsUIW/OuRJJbCfYsZ0lwzGdszkmx1xW7L9cBlCjs6uy0hciRbHmUvQ5X8PZB0KlSob1eaADPyc2BR1s5F/OxmOlbN+LIi4wBBVKuETEOp5UPyhl9yPFOQuIcEzHpVt/ciEKS9dJl6Pn+T6QnZUQENKKTCO6Q0pXTnJiL+TaQoxZebDRW</enc>]]> -->
      </text>
    </declare>
  </script>

</dir>