<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonDir.xml">
]>


<dir id="tb_Category" table="tb_Category" fieldKey="Id" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Danh mục Store" e="Location List"></title>
  <title0 v="Thêm mới" e="New"></title0>
  <title1 v="Sửa" e="Edit"></title1>

  <forms>
    <form gravity="TopLeft" columns="120,120,120" >
      <fields>
      
        <field name="Id"   hidden="true"   inactivate="true" label="1" field="1" importable="-1">
          <text v="id" e="Description"></text>
        </field>
        <field name="Title" label="1" field="1">
          <text v="Tên danh mục" e="Other Name"></text>
        </field>
		   <field name="Alias" label="1" field="1">
          <text v="Alias" e="Other Name"></text>
        </field>
		  <field name="Description" label="1" field="-">
          <text v="Description" e="Other Name"></text>
        </field>
		  <field name="Detail" label="1" field="-">
          <text v="Detail" e="Other Name"></text>
        </field>
		  <field name="IsActive" label="1" field="1">
          <text v="Hiển thị" e="Other Name"></text>
        </field>

        <field name="Position" label="1" field="-" >
          <text v="Position" e="Notes"></text>
        </field>
		<field name="SeoTitle"   label="1" field="-" >
          <text v="SeoTitle" e="Notes"></text>
        </field>
		<field name="SeoDescription"  label="1" field="-" >
          <text v="SeoDescription" e="Notes"></text>
        </field>
		 <field name="SeoKeywords"  label="1" field="-" >
          <text v="SeoKeywords" e="Notes"></text>
        </field>
		 <field name="CreatedDate"   label="1" field="1" dataType="D" >
          <text v="CreatedDate" e="Notes"></text>
        </field>
		 
		 sssss

       
      </fields>
    </form>
  </forms>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>GYD0OC5JhpEhu2renQHOp/tdfS6zOQ+VS2KqpT4N32Dp1MnwMU1DrRmSxeS3f5fICyOhzGhzAUFaiO0MlVKQOP3mHiHwWbb3gWI9oLrYBT0DgTV2NmGQLHHHdbg7GAwIOM39dcry4Vy+ufNXV5p4+2khQtmu5ZcmqASucqAjbuQYM5qb1Ht3H2+a73qxht0D</enc>]]>
    </text>
  </js>

  <messages>
    <message val="codeExistsNewMsg">
      <text v="Mã kho và vị trí đã có trong danh mục vị trí kho." e="The record consisting of site and location is already exists."/>
    </message>
    <message val="codeExistsEditMsg">
      <text v="Mã kho và vị trí đã có trong danh mục vị trí kho." e="The record consisting of site and location is already exists."/>
    </message>
  </messages>

</dir>