<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
  <!ENTITY ReportFilterItemGroup SYSTEM "..\Include\XML\ReportFilterItemGroup.xml">
  <!ENTITY ReportFilterCustomerGroup SYSTEM "..\Include\XML\ReportFilterCustomerGroup.xml">
  <!ENTITY ReportFilterStockType SYSTEM "..\Include\XML\ReportFilterStockType.xml">
  <!ENTITY ReportJSLoading SYSTEM "..\Include\XML\ReportJSLoading.xml">
  <!ENTITY ReportFilterUnit SYSTEM "..\Include\XML\ReportFilterUnit.xml">
  <!ENTITY ReportFiltering SYSTEM "..\Include\XML\ReportFiltering.xml">
  <!ENTITY ReportDataAnalysisStruct SYSTEM "..\Include\XML\ReportDataAnalysisStruct.xml">

]>

<dir id="bkctdvmh" table="" height="" fieldKey="id" dirViewType="Dialog" dirObjectType="Report" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Bảng kê mua/chi hoạt động" e="Activity purchase/expenditure statement"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" clientDefault="true" allowBlank="false" dataType="D">
          <text v="Ngày từ/đến" e="Date From/To"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" aliasName="@DFDTo" clientDefault="true" allowBlank="false" dataType="D" nextRow="false">
          <text v="" e=""></text>
        </field>
        <field name="so_ct1"  label="1" field="1" operation="a.so_ct &gt;= N'%s'">
          <text v="Số c/từ (từ/đến)" e="Voucher Number"></text>
        </field>
        <field name="so_ct2"  label="" nextRow="false" field="1" operation="a.so_ct &lt;= N'%s'">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>

    <form tabPageIndex="1" gravity="MiddleLeft" height="0" columns="120,120,120,120,120"  >
      <text v="Thông tin chung" e="Thông tin chung"></text>
      <fields>
       
        <field name="ma_kh" viewType="Lookup" label="1" field="1" operation="like">
          <text v="Mã khách hàng" e="Customer"></text>
          <viewInfo lookupType="One" lookupId="dmkh" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_kh" />
        </field>
        <field name="ten_kh" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
        &ReportFilterCustomerGroup;
        <field name="ma_dv" viewType="Lookup" operation="like" label="1" field="1">
          <text v="Mã dịch vụ" e="Services"></text>
          <viewInfo lookupType="One" lookupId="dmdv" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_dv" />
        </field>
        <field name="ten_vt" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
        &ReportFilterUnit;     
      </fields>
    </form>
  </forms>
  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>FX6/CwAQ8MlKX3V0i7zucgVdtUsQ5tH4qy1iRbW0ZIzBBgqnPdUzYYHWr5bkTWJnB1k71PLCzm8OVBPNnrZMCP1hF/URID+IHwdsj09UIVuK1Gc69f8kZ20hOlpdHwPqrqe62Bn/TCaHFsT9O0RqPwzoeVAzT8xzZ3c3MnoZTzXujMrktfTzj+zsxa9XPV47aZrL6ySxct5PZN5noh4T7g==</enc>]]>
    </text>
  </js>

  <script>
    <processing>
      <text>
        <![CDATA[<enc>TN45BLVvlQZWD1bhImJFui3B6za/B5OT7CPnricv7F9VxXndoQI7mrkZhe35dbbb</enc>]]>
      </text>
    </processing>
    &ReportJSLoading;
  </script>
</dir>