<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="cnkhbh" table="" height="" fieldKey="ky, nam" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Cập nhật kế hoạch bán hàng (Lọc)" e="Sale Plan Input (Filter)"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,240,120"  >
      <fields>
        <field name="ky" label="1" field="1" format="-1" maxLength="2" allowBlank="false" dataType="I" aliasName="@DFMonth">
          <text v="Kỳ" e="Month"></text>
        </field>
        <field name="nam" label="1" field="1" format="-1" maxLength="4" allowBlank="false" dataType="I" aliasName="@DFYear">
          <text v="Năm" e="Year"></text>
        </field>
      </fields>
    </form>
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>q6iCSLCowTW5wC/k2hMF+8p7FSPnfLJe19h1tvq+Rr0UGDMEiJSHUmP1x9I3fag8aCYUtKx6A+pAJSFK3QFaTlgqk/D/zYOfq7C6C3/O6RcAxzTqQ/TRGAwfpJBjamp3CbTex+5veXh6i/CF5as9eBSeWzewEx6r5OG1KekYtrNr3PPxbje2k18byXmJHMbS</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>