<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
  <!ENTITY VoucherJSLoading SYSTEM "..\Include\XML\VoucherJSLoading.xml">
]>

<dir id="m52" table="" height="" fieldKey="id" voucherCode="DH1" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc đơn hàng" e="Sales Orders Filter"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D">
          <text v="Ngày c/từ (từ/đến)" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" aliasName="@DFDTo" clientDefault="true" allowBlank="false" fieldType="PK" dataType="D" nextRow="false">
          <text v="" e=""></text>
        </field>
        <field name="so_ct1"  label="1" field="1" operation="a.so_ct &gt;= N'%s'">
          <text v="Số c/từ (từ/đến)" e="Voucher Number"></text>
        </field>
        <field name="so_ct2"  label="" nextRow="false" field="1" operation="a.so_ct &lt;= N'%s'">
          <text v="" e=""></text>
        </field>
        <field name="ma_ngv" viewType="Combobox" label="1" field="2" operation="=" >
          <text v="Loại chứng từ" e="Voucher Type"></text>
          <viewInfo>
            <options query="select ma_ngv, ten_ngv%l from dmngv where ma_ct = '@@voucherCode' and status = 1 order by stt">
              <option val="">
                <text v="Tất cả" e="All"></text>
              </option>
            </options>
          </viewInfo>
        </field>
        <field name="ma_gd" viewType="Combobox" label="1" field="2" operation="=" >
          <text v="Giao dịch" e="Transaction"></text>
          <viewInfo>
            <options query="select ma_gd, ten_gd%l from dmgd where ma_ct = '@@voucherCode' and status = 1 order by stt">
              <option val="">
                <text v="Tất cả" e="All"></text>
              </option>
            </options>
          </viewInfo>
        </field>
        <field name="ma_kh" viewType="Lookup" label="1" field="1" operation="like">
          <text v="Mã khách hàng" e="Customer"></text>
          <viewInfo lookupType="One" lookupId="dmkh" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_kh" />
        </field>
        <field name="ten_kh" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
        <field name="ma_nvbh" viewType="Lookup" label="1" field="1" operation="like">
          <text v="Mã nhân viên" e="Salesman"></text>
          <viewInfo lookupType="One" lookupId="dmnvbh" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_nvbh" />
        </field>
        <field name="ten_nvbh" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
        <field name="dien_giai" label="1" field="-" operation="a.dien_giai like N'%%s%'">
          <text v="Diễn giải" e="Voucher Number"></text>
        </field>
      </fields>
    </form>
    
    <form gravity="MiddleLeft" tabPageIndex="1" columns="120,120,120"  >
      <text v="Chi tiết" e="Detail"/>
      <fields>
        <field name="ma_vt" viewType="Lookup" label="1" field="1">
          <text v="Mã vật tư" e="Item"></text>
          <viewInfo lookupType="One" lookupId="dmvt" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_vt" />
        </field>
        <field name="ten_vt" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
        <field name="ma_kho" viewType="Lookup" label="1" field="1">
          <text v="Mã kho" e="Site"></text>
          <viewInfo lookupType="One" lookupId="dmkho" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_kho" />
        </field>
        <field name="ten_kho" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
        <field name="ma_lo" viewType="Lookup" hidden="true" label="1" field="1">
          <text v="Mã lô" e="Lot"></text>
          <viewInfo lookupType="One" lookupId="dmlo2" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_lo" />
        </field>
        <field name="ten_lo" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
        <field name="ma_vi_tri" viewType="Lookup" hidden="true" label="1" field="1">
          <text v="Mã vị trí" e="Position"></text>
          <viewInfo lookupType="One" lookupId="dmvitri" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_vi_tri" />
        </field>
        <field name="ten_vi_tri" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
    
    <form gravity="BottomLeft" columns="120,120,120"  >
      <fields>
        <field name="ma_unit" viewType="Lookup" inactivate="true" label="1" field="2" >
          <text v="Đơn vị" e="Unit"></text>
          <viewInfo lookupType="Multi" lookupId="sysunit" lookupKey="status = 1 and unit_id in (select unit_id from dbo.ISWIFTFunctionGetUnitIDRight(@@userId, @@admin, ''))" lookupCheck="1 = 1" lookupRef="ten_unit" />
        </field>
        <field name="ten_unit" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
        <field name="status" viewType="Combobox" inactivate="true" label="1" field="2" operation="=" >
          <text v="Trạng thái" e="Status"></text>
          <viewInfo>
            <options query="select ma_ttct, ten_ttct%l from dmttct where ma_ct = '@@voucherCode' and status = 1 order by stt">
              <option val="">
                <text v="Tất cả" e="All"></text>
              </option>
            </options>
          </viewInfo>
        </field>
        <field name="user_id0" viewType="Combobox" inactivate="true" label="1" field="2" operation="a.user_id0 in (select user_id from sysuserinfo where user_ref like '@@userRef%')" >
          <text v="Lọc theo người sd" e="Filter By User"></text>
          <viewInfo>
            <options>
              <option val="">
                <text v="Tất cả" e="All"></text>
              </option>
              <option val="1">
                <text v="Lọc theo người tạo" e="Filter By Create User"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>uw3iZoR/y/5o6FF1x5y/2Tl5+KQzckE7GQfinBx9N2oNYYT7x62pRT9PDJu7jj4GZJbumDMBZ+CEam2NykFQlHc0AQAvgnu7m2+whCc3PdzP3Z9cp3Ei7BDNhUGCsDtQP/FDrBDzWyvFST5cquYJOLpkkivS1LYp4iAPn6tXvE/gA0ti67WShz0gRYPhc4uz</enc>]]>
    </text>
  </js>

  <script>
    &VoucherJSLoading;
  </script>
</dir>