<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="m52DH1" table="" height="" fieldKey="id" voucherCode="PN1" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc hợp đồng" e="Contract Filter"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" allowBlank="false" dataType="D">
          <text v="Ngày c/từ từ/đến" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" allowBlank="false" inactivate="true" dataType="D" nextRow="false">
          <text v="Ngày đến" e="Voucher Date"></text>
        </field>
          <field name="ma_nt" hidden="true" label="1" field="1">
          <text v="Mã ngoại tệ" e="Ex Code"></text>
        </field>
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="ma_kh" viewType="Lookup" disabled="true" inactivate="true" label="1" field="1">
          <text v="Mã khách hàng" e=""></text>
          <viewInfo lookupType="One" lookupId="dmkh" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_kh" />
        </field>
        <field name="ten_kh" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
        <field name="so_ct" label="1" field="1" allowBlank="false" viewType="Lookup">
          <text v="Số hợp đồng" e="Voucher Number"></text>
          <viewInfo lookupType="Multi" lookupId="m52" lookupRef="ds_so_ct" lookupKey="ngay_ct between ![ngay_ct1]! and ![ngay_ct2]! and ma_kh = ![ma_kh]! and unit_id = ![unit_id]! and status in (5,6) and ma_ngv = 4 and ma_nt = ![ma_nt]!" lookupCheck="ma_kh = ![ma_kh]! and status in (5,6) and ma_ngv = 4 and ma_nt = ![ma_nt]!" />
        </field>
        <field name="ds_so_ct" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>pJbGGH5KqF4j5C32fF3T9pVn+v1GFsw2VydXfI0m3fCPN3P+NoCoLKhf70ZBsulolPrt8S9jZ4CxpBkse8BFpWC7xcaIIezjcVhznuRqYWXaqQaSMVPMCY6j2tsla3gOv2Mg5ehIehMoib9VvXLKTavgm/Q6nuEG5pzzVgJqSjGwNCWNqzSdUNZBOZnrFUNmw7FtehakIlcMOGYmMImw7h9i3RjfQQPpYDDdgZvVzc9Y49VJXMUM0bp00Vr7EVt1MjdUCwj88Z/jYkmSpb5qPGSZhtmY2ljxYzgaXPK8fLsu70en02V3t/FpxjlhCgeGHSamJgaqm3Wsd+k34k2SyAhEh3tBDSb0NJj2P43zs7EuqaKD+EWdxaOpZXidUqPJavyCdIZKfN1PKt6kgez9yw2q4kom22crxQ0Hfn/f2AfiOWwnuak61Lc+k8D0VS9wo7dio6nOMFSHnWH2vyFTYfm2hLhFYTAbMbfqGzAysQxj16uuxKaKT28W15k7M9tO1zJN0JOitW+klptZ6grhnBUU57LrgKdtVTQ5BNURaeainxyOBssXk6aIRSlIdelUTi/gE51sO3An5Rjz5s3cMg==</enc>]]>
    </text>
  </js>

  <script>

  </script>
  <messages>
    <message val="contractTitle">
      <text v="Hợp đồng" e="Contract" />
    </message>
  </messages>
</dir>