<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="m53DH1" table="" height="" fieldKey="id" voucherCode="LX1" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc đơn hàng" e="SO Filter"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" allowBlank="false" dataType="D">
          <text v="Ngày c/từ từ/đến" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" allowBlank="false" inactivate="true" dataType="D" nextRow="false">
          <text v="Ngày đến" e="Voucher Date"></text>
        </field>
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="ma_kh" viewType="Lookup" disabled="true" inactivate="true" label="1" field="1">
          <text v="Mã khách hàng" e=""></text>
          <viewInfo lookupType="One" lookupId="dmkh" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_kh" />
        </field>
        <field name="ten_kh" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
        <field name="so_ct" label="1" field="1" allowBlank="false" viewType="Lookup">
          <text v="Số đơn hàng" e="Voucher Number"></text>
          <viewInfo lookupType="Multi" lookupId="m52" lookupRef="ds_so_ct" lookupKey="ngay_ct between ![ngay_ct1]! and ![ngay_ct2]! and ma_kh = ![ma_kh]! and unit_id = ![unit_id]! and status in (5,6) and ma_ngv = 5" />
        </field>
        <field name="ds_so_ct" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>iwAGzPlHWEKzuNu1v5HhnBHESUWwOtEJ8KF6BNfzr3a44zXipZY+r77EAYPd52S32nc0YZCPtGDGXgK8/oVNM+kkbGzk/t/NCnvfLSnQwWyjG0yCfPlUWpRV48Hte6YZfRdzFP7+evEU0fo4t2e0GNpgHawPoTgGtzijMH/4oak5BwTRfZfJah6ScICRe2tc+d0GD6IBARhXouPh3V6OdZP5LG9QzaCwLLsVlgtErgDd16LDCKu4c50AV8TpeNjP5XW1h/5HjdZBZL3zTOMs6fva+4ysDA5oIaakkDic8PZVKwg21FmfAkIPe5q9VyAq6hEkl5z/r5oxgbEtl4e1Eku/Y1kGSXhuchuStLP9Bg52ttYrySP/YAMKoBH1L0kVN2pg8MHXGh64M6/Nd7+Pg4Vm/uDFTSa26yo2BfqasgTpk/P5Pwh6NepuDfYBgv0Ltr87OkbUdTvEN4ZsMtzzHIKCIEJ273TZfEIlzh83IdYP4B6qBVwGbic/Mwc7hgG4</enc>]]>
    </text>
  </js>
</dir>