<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
  <!ENTITY VoucherExtendFields SYSTEM "..\Include\XML\VoucherExtendFields.xml">
]>

<dir id="m54DH1Select" table="" height="" fieldKey="id" voucherCode="PX3" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Chi tiết hợp đồng được chọn" e="Contract Detail"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ma_kh" viewType="Lookup" disabled="true" label="1" field="1">
          <text v="Mã đối tượng" e="Customer"></text>
          <viewInfo lookupType="One" lookupId="dmkh" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_kh" />
        </field>
        <field name="ten_kh" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
        <field name="so_ct" label="1" field="2" disabled="true">
          <text v="Số đơn hàng" e="SO No."></text>
        </field>
        <field name="xprocess" label="1" field="2" valueDefault="2" viewType="Combobox">
          <text v="Xử lý" e="Process"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="Thêm vào chi tiết" e="Append To Detail"></text>
              </option>
              <option val="2">
                <text v="Xóa hết chi tiết và thêm mới" e="Delete All Detail And Append New"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
    <form tabPageIndex="1" gravity="MiddleLeft" height="350" columns="120,120,240" >
      <text v="Chi tiết" e="Detail"></text>
      <fields>
        <field name="d54" label="" field="-" viewType="Grid">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
  </forms>

  <grids>
    <grid id="d54" table="d54" fieldKey="id, line" order="id, line" allowFilter="true" readOnly="false" allowOrder="true">
      <fields>
        <field name="id" dataType="N" fieldType="PK" format="0" copy="false" hidden="true" aliasName="0 as ">
          <text v="" e=""></text>
        </field>
        <field name="line" dataType="I" fieldType="PK" hidden="true" aliasName="0 as ">
          <text v="Dòng" e="Line"></text>
        </field>
        
        <field name="ma_vt" width="100" viewType="Lookup" readOnly="true" >
          <text v="Mã sản phẩm" e="Item"></text>
          <viewInfo lookupType="One" lookupId="dmvt" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_vt" lookupInfo="dmvt|ma_vt|ten_vt" />
        </field>
        <field name="ten_vt" width="250" fieldType="EX" inactivate="true" readOnly="true" aliasName="b" join=" left join dmvt b on a.ma_vt = b.ma_vt ">
          <text v="Tên sản phẩm" e="Item Name"></text>
        </field>
        <field name="dvt" width="60" readOnly="true" viewType="Lookup" aliasName="a">
          <text v="Đvt" e="UOM"></text>
          <viewInfo lookupType="One" lookupId="dmdvt" lookupKey="dvt in (select dvt from dmqddvt where ma_vt = #[ma_vt]#)" lookupCheck="dvt in (select dvt from dmqddvt where ma_vt = #[ma_vt]#)" lookupRef="ten_dvt" lookupInfo="dmdvt|dvt|ten_dvt" />
        </field>
        <field name="ten_dvt" width="120" inactivate="true" readOnly="true" hidden="true" aliasName="c" join=" left join dmdvt c on a.dvt = c.dvt ">
          <text v="Tên đvt" e="UOM"></text>
        </field>
        <field name="so_luong0" dataType="N" format="Qty" width="100" readOnly="false" aliasName="0*a.so_luong as " >
          <text v="&lt;b&gt;Sl lấy&lt;/b&gt;" e="&lt;b&gt;Qty Input&lt;/b&gt;"></text>
        </field>
        <field name="so_luong" dataType="N" format="Qty" width="100" readOnly="true" >
          <text v="Số lượng" e="Quantity"></text>
        </field>
		<field name="so_luong_vc" dataType="N" format="Qty" width="0"  aliasName="0*a.so_luong as " >
          <text v="Số lượng" e="Quantity"></text>
        </field>
        <field name="sl_cl" dataType="N" format="Qty" width="100" aliasName="0*a.so_luong as " >
          <text v="&lt;b&gt;Sl còn lại&lt;/b&gt;" e="PO Qty"></text>
        </field>
        <field name="ma_kho" width="100" clientDefault="true" viewType="Lookup" >
          <text v="Mã kho" e="Site"></text>
          <viewInfo lookupType="One" lookupId="dmkho" lookupKey="unit_id = ![unit_id]! and status=1" lookupCheck="unit_id = ![unit_id]!" lookupRef="ten_kho" lookupInfo="dmkho|ma_kho|ten_kho" />
        </field>
        <field name="ten_kho" width="120" clientDefault="true" inactivate="true" hidden="true" aliasName="d" join=" left join dmkho d on a.ma_kho = d.ma_kho ">
          <text v="Tên kho" e="Site"></text>
        </field>
        <field name="ma_lo" width="100" viewType="Lookup" hidden="true" readOnlyCondition="[lo_yn]==0" allowBlankCondition="[lo_yn]==0" >
          <text v="Mã lô" e="Lot"></text>
          <viewInfo lookupType="One" lookupId="dmlo" lookupKey="ma_vt = #[ma_vt]# and status=1" lookupCheck="1=1" lookupRef="ten_lo" lookupInfo="dmlo|ma_lo|ten_lo" />
        </field>
        <field name="ten_lo" width="120" inactivate="true" readOnly="true" hidden="true" aliasName="e" join=" left join dmlo e on a.ma_vt = e.ma_vt and a.ma_lo = e.ma_lo ">
          <text v="Tên lô" e="Lot"></text>
        </field>
        <field name="lo_yn" dataType="B" width="50" hidden="true" inactivate="true" readOnly="true" aliasName="b">
          <text v="Td lô" e="Lot"></text>
        </field>
        <field name="ma_vi_tri" width="100" clientDefault="true" hidden="true" viewType="Lookup" readOnlyCondition="[vi_tri_yn]==0" allowBlankCondition="[vi_tri_yn]==0" >
          <text v="Mã vị trí" e="Location"></text>
          <viewInfo lookupType="One" lookupId="dmvitri" lookupKey="ma_kho = #[ma_kho]# and status=1" lookupCheck="1=1" lookupRef="ten_vi_tri" lookupInfo="dmvitri|ma_vi_tri|ten_vi_tri" />
        </field>
        <field name="ten_vi_tri" width="120" inactivate="true" clientDefault="true" readOnly="true" hidden="true" aliasName="f" join=" left join dmvitri f on a.ma_kho = f.ma_kho and a.ma_vi_tri = f.ma_vi_tri ">
          <text v="Tên vị trí" e="Location Name"></text>
        </field>
        <field name="vi_tri_yn" dataType="B" width="50" clientDefault="true" hidden="true" inactivate="true" readOnly="true" aliasName="d">
          <text v="Td vị trí" e="Location"></text>
        </field>
        <field name="he_so" dataType="N" format="Rate" width="50" readOnly="true" inactivate="true" aliasName="a" hidden="true" >
          <text v="Hệ số" e="Rate"></text>
        </field>
        <field name="sl_ton" dataType="N" format="Qty" inactivate="true" width="100" readOnly="true" fieldType="EX" aliasName="0*a.so_luong as " >
          <text v="Tồn" e="Stock"></text>
        </field>
        <field name="ct_km" hidden="true" width="100" viewType="Combobox" inactivate="true" >
          <text v="Loại hàng" e="Item Type"></text>
          <viewInfo>
            <options>
              <option val="0">
                <text v="Hàng bán" e="Sale"/>
              </option>
              <option val="1">
                <text v="Hàng KM" e="Promotion"/>
              </option>
            </options>
          </viewInfo>
        </field>
         <field name="gia_nt1" dataType="N" hidden="true" inactivate="true" format="FCPrice" width="100" readOnly="true" >
          <text v="Giá chuẩn %s" e="%s Std.Price"></text>
        </field>
        <field name="gia_nt2" dataType="N" format="FCPrice" width="100" >
          <text v="Giá bán %s" e="%s Price"></text>
        </field>
        <field name="tien_nt2" dataType="N" format="FCAmount" width="100" >
          <text v="Doanh số %s" e="%s Amount"></text>
        </field>
        <field name="tl_ck" dataType="N" format="Rate" width="100" >
          <text v="Tl ck(%)" e="Dis.Rate"></text>
        </field>
        <field name="ck_nt" dataType="N" format="FCAmount" width="100" clientDefault="true" >
          <text v="Ch.khấu %s" e="%s Discount"></text>
        </field>
        <field name="thue_suat" dataType="N" format="0" width="100" clientDefault="true" >
          <text v="Thuế suất(%)" e="Tax"></text>
        </field>
        <field name="thue_nt" dataType="N" format="FCAmount" width="100">
          <text v="Thuế %s" e="%s Tax"></text>
        </field>
        <field name="ngay_giao" dataType="D" width="100">
          <text v="Ngày giao" e="Delivery Date"></text>
        </field>
        &VoucherExtendFields;
                <field name="gia1" dataType="N" hidden="true" format="Price" width="100" inactivate="true" readOnly="true" >
          <text v="Giá chuẩn" e="Std.Price"></text>
        </field>
        <field name="gia2" dataType="N" hidden="true" format="Price" width="100" inactivate="true" >
          <text v="Giá bán" e="Price"></text>
        </field>
        <field name="tien2" dataType="N" hidden="true" format="Amount" width="100" inactivate="true" >
          <text v="Doanh số" e="Amount"></text>
        </field>
        <field name="ck" dataType="N" hidden="true" format="Amount" width="100" inactivate="true">
          <text v="Chiết khấu" e="Discount"></text>
        </field>
        <field name="thue" dataType="N" hidden="true" format="Amount" width="100" inactivate="true">
          <text v="Thuế" e="Tax"></text>
        </field>
        <field name="id_dh" dataType="N" fieldType="PK" format="0" hidden="true" aliasName="a.id as ">
          <text v="" e=""></text>
        </field>
        <field name="so_ct_dh" dataType="N" fieldType="PK" format="0" hidden="true" aliasName="a.so_ct as ">
          <text v="" e=""></text>
        </field>
        <field name="line_dh" dataType="I" fieldType="PK" hidden="true" aliasName="a.line as ">
          <text v="" e=""></text>
        </field>
      </fields>

      <buttons>
        <button id="freeze">
          <text v="$FreezeToolbar" e="$FreezeToolbar"></text>
        </button>
      </buttons>

      <script>
        <query>
          <text>
            <![CDATA[<enc>VqUMBhs2JIRyA/o63KOuSGC6CTvDulQ8g4EEAysCPIPLDzKqsx6jEf3OtsiqHJNQ+2ioT98lQdn/up3HKghFCHO79QKTmj53po4YoqTlkix/Vgx198DXUeTzPRpPlHJhWCZ1UUimiwizACsaLPTPpDhslpO5g76+5qpePl6GrUdd/3v8iH30AoDv6eyEMSzE40QXO2KA3rN/W7ZyCon/X64tXlBpzdCiveAFOInVOgx0R4ObBKr4x9l9xUrwtTwX/nrZ0jTOdNsvCVVPM5cMB/RsHNqagdM5tL60ezF8XkC6HSXyyDOywpmgyE1cHq7c1kLCqItfayoI49LfgL6BLg26TL+m2Ed+PjrPh3rVKIbogj/UF1I/81lqT7PPV9j6eQxRii08qVz+0Y9g7tsg9iUFfvE1zZlYZbOQH42StxmfCVykCLMjPmGsD+jwLavpzNqeY/5OTQT2FGvaN0P7xKSppPLMfh1BCpJzNd7jDDI/Bo2onsg0knvpq0KWkS8jZ8fr8Oczt+QDU7KXI2ZsHCiHgCJhHvIQMxgL3Plcohum4eKza+NqevRUKyVDVoncX8Pqpc4YqHWgaB55wM88jEsQjbhzdvLmoy3lVRljYTRvta8yedA7XAxiN4+YlpIrZyDy9KeueqXzEr7lXYL2Bv+KOUr7ssDc9/cWBf+9h8wrfRQmDJ8NaOpTTyz6D1lftffj+JOGiG0BTSDeh4AwDDe29GkQ88C2suNrshRgOCkYoyfLvIU2muxk//0Rxr6I0BxzTRtGG7S3khvOP24fExQiHbQhtAKCwV+cycfwkksEillpjPlkw/Q8DaTWBUdfEZwoJxMllx0dsAQaJJUvqvZm1Zsc+LldPVKh6O2g2klZ+qJpOW/T0u0TFwTJWe5Nqv9aJYTD6B/jMcLlqcRUag==</enc>]]>
          </text>
        </query>
      </script>

    </grid>
  </grids>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>5AuJJzGDCDKPiv+lTKjZQapQSxi9XxYAs0Qw1Rt1URcBgBtcLh0oJCvXzZ0hymEa61/24nGNZL3ZJr/z5eIyHCL9OlcOVOy9+m/F9UTtUCdUIQnYLaQZgDEghhbRMZu0o0G7/sGXxQgi+87ZKhlnq0G/cfYYFf3DXydzW52ivmGFYJmyNulgSwmrMRRJx72HGj/II0sVTj3wSjeDsetoUJivzT+2nT/eUHDjMRgDlPcEPLjHOSQ0eP9BItIGwKAQ7Y4clOOpNFhDXBedGqOBiOY+d8+1n1n3zYUiU7/Fo7ILNlMiaU8i9JDit6qzRyP4N3o6Y5aBBQKuwFYgWv5XZbzS80asf0BK3Q6YQPFGr/LV6Wmk2mPR9uN1euJOoGlfWF+9+bxIP8evNiYQ9aIGy9Hvzsn9Nbc4Va0rFiMJX5jJDoG0U5+F6uUrz73bvOPm9P3Bh1rqqp7fz+v6iIXsSmgKx5P8RWb9pF/yQ2C6UHL6DyvaoFP/URtb51C/SeQwr3QWnKJyOyDm7GwkJqAAE1aaZxbNhvN14f2wkMjQ4bBh7fAatC0Qv3w9+du+wK0ZL3DK1MqyXUxwmgUF4iWxauwrQ1OMM6u4kZTOdnP83FbWhVJgXIq7I6xn4ZjZvmWolcFZ15vo9KaI9g0OcjFjsdm62O32N3YdoxEaH9WQG1PRhpw2o91UYJPnWL/qS2RfEdHYUH16u4k+1kgMxyKXqQ==</enc>]]>
    </text>
  </js>
</dir>