<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="m54HD1" fieldKey="id" voucherCode="PX3" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc hóa đơn" e="Sales Invoice Filter"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" allowBlank="false" dataType="D">
          <text v="Ngày c/từ từ/đến" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" allowBlank="false" inactivate="true" dataType="D" nextRow="false">
          <text v="Ngày đến" e="Voucher Date"></text>
        </field>
          <field name="ma_nt" hidden="true" label="1" field="1">
          <text v="Mã ngoại tệ" e="Ex Code"></text>
        </field>
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="ma_kh" viewType="Lookup" disabled="true" inactivate="true" label="1" field="1">
          <text v="Mã khách hàng" e=""></text>
          <viewInfo lookupType="One" lookupId="dmkh" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_kh" />
        </field>
        <field name="ten_kh" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
        <field name="so_ct" label="1" field="1" allowBlank="false" viewType="Lookup">
          <text v="Số hóa đơn" e="Inv. No"></text>
          <viewInfo lookupType="Multi" lookupId="m55" lookupRef="ds_so_ct" lookupKey="ngay_ct between ![ngay_ct1]! and ![ngay_ct2]! and ma_ngv = 1 and ma_kh = ![ma_kh]! and unit_id = ![unit_id]! and status in (5,6)" />
        </field>
        <field name="ds_so_ct" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>4rbgQPq2PC/Jy8+m3mXt/0yMvryNXm6sfX0ssy2mVvuPjk17LIarB3AE5kgANo0LrYCbaZwCZM/QPQCBKM676rsMRYJ9oYJnyXCNgcSzEPldAKaZF+swW1wrRBGLhsrtG3qFh/QGk5gJCoq4lsE+TmOgwnG2yQ33g8mqnHjTNP/SyG06oyW7bF/PSaTbogSKmD2bzbvlaDACnZAzrhMlxpl8qeylNv/gGzPzRO8rqi9aMztpsunNBH37i02Z70zq+A52oz+2kV0hdM37U2z6QUbaTiGVEtVR5mLvDdFQ3ihf3XN8bE3RXlTVBP+jPe6OLGGKjowkYiLolYG3EHG1l7ABQ3D5lg399fwQR2E4XIfWwLeqwbM4yleP0tqis7/Dby2oRdLeyQIL/EkNPUiqCn+ylGDT5oPyElLKHJ56Th9+Hbm4Hnb1w8zLLGMjK1YQVuUWJLl3Emhg4iMK8uBlSrPErkLoQpar7SNtDlIdfwOtv6tcmxqtKXgQbyN1JoBb4orMuFE/DO6sjeHoxDAmxQ==</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>