<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="m54LX1" fieldKey="id" voucherCode="PX3" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc lệnh xuất" e="Issue Orders Filter"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" allowBlank="false" dataType="D">
          <text v="Ngày c/từ từ/đến" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" allowBlank="false" inactivate="true" dataType="D" nextRow="false">
          <text v="Ngày đến" e="Voucher Date"></text>
        </field>
          <field name="ma_nt" hidden="true" label="1" field="1">
          <text v="Mã ngoại tệ" e="Ex Code"></text>
        </field>
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="ma_kh" viewType="Lookup" disabled="true" inactivate="true" label="1" field="1">
          <text v="Mã khách hàng" e=""></text>
          <viewInfo lookupType="One" lookupId="dmkh" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_kh" />
        </field>
        <field name="ten_kh" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
        <field name="so_ct" label="1" field="1" allowBlank="false" viewType="Lookup">
          <text v="Số lệnh" e="IO No"></text>
          <viewInfo lookupType="Multi" lookupId="m53" lookupRef="ds_so_ct" lookupKey="ngay_ct between ![ngay_ct1]! and ![ngay_ct2]! and ma_kh = ![ma_kh]! and unit_id = ![unit_id]! and status in (5,6)" />
        </field>
        <field name="ds_so_ct" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>KnJ66uF0s8Sz+E1B2mMw0mOquDQGBXjg4zon0QrsaGPs1fFliPy7jdT8DjBlmon4qAIf7ajQDY+3YvfMK+DZmqthF3iJRhM8lY2MTFous/utLPqbsELNMIknqBIPqjFTgwgPCwCQS/8oky8XLtXjAgOyK/0q01/ucu7i8ygd6FiKBGK5yRDmzyjlK8Vg15m9i6sJQIFhGEKvY3hw4Zb620TJWsFdZuA//jxF6JW5jgd1DNizPca0sJNxycFM/qUW+9YDoVTvSbfFQ60muIb4wW0nVpCMlikiPNGDIuoxmEs8qTcsuh4iEYHbVynwIdpFzkolt+KY8J0dYdt8Vnwl8r9S0HzjF4s3hjajXiC6FXRWXnIvP7zd9fvqzOZfd7yJqB4VtQKVi5YjMN97ZlewQD6YKj/NfXVM0gcGoVssQKrtFdAPCdX1SpOqA1EEHZ95ZesnptL2pdusZyBEeen8CF1Okj9uhqAv5frWPMy2c8/k8pNi1ik3ZosGNUQGUYpCltKznRQv9s1W/F+i+0oDOw==</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>