<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="m73PX1" table="" height="" fieldKey="id" voucherCode="PX1" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc phiếu xuất thực tế" e="Physical Issue"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" allowBlank="false" dataType="D">
          <text v="Ngày c/từ từ/đến" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" allowBlank="false" inactivate="true" dataType="D" nextRow="false">
          <text v="Ngày đến" e="Voucher Date"></text>
        </field>
          <field name="ma_nt" hidden="true" label="1" field="1">
          <text v="Mã ngoại tệ" e="Ex Code"></text>
        </field>
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="ma_kh" viewType="Lookup" disabled="true" inactivate="true" label="1" field="1">
          <text v="Mã khách hàng" e=""></text>
          <viewInfo lookupType="One" lookupId="dmkh" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_kh" />
        </field>
        <field name="ten_kh" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
        <field name="so_ct" label="1" field="1" allowBlank="false" viewType="Lookup">
          <text v="Số phiếu thực tế" e="Voucher Number"></text>
          <viewInfo lookupType="Multi" lookupId="m73" lookupRef="ds_so_ct" lookupKey="ngay_ct between ![ngay_ct1]! and ![ngay_ct2]! and ma_kh = ![ma_kh]! and unit_id = ![unit_id]! and status in (5,6) and ma_ngv = 2 and ma_nt = ![ma_nt]!" lookupCheck="ma_kh = ![ma_kh]! and status in (5,6) and ma_ngv = 2 and ma_nt = ![ma_nt]!" />
        </field>
        <field name="ds_so_ct" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>f0JAwjA4kf8Riu3axZPnUNln5QqD7jkWM1bjZCStS4mdco6QsulWi/BuIgO2TKAiJZnW1B6Yn7dqN141ypiyR3zTgsRMU4XypFPyRYfaRogKCiCmMmVsMrn9NdSMTwA2O5Z/q1NXuVfj8jhHhQxunPmMvIOd26gVenN/V+pRP5g1YoYEx9q/UW3EFOAsuvNiO3mcXZA3TOVypCWZJgnvBigUdeQSvVoT/Tj3IEs3yQQlghGvsa0uR1/qCuTkcz7ELPQi8VRskAquX2wwXgQZ8NhQr2B/6RySK3JoTfL4iN4uaLhc5lGJ9rbh0FJfFDRJIyi/fzgV7CDNzv1vAFdZnG69FpN/40xvtOenTxJeHxPCxb0rzPY5gpaY1b8jd4UlX9HXCN2+oWUkR2EpJQWwnv+XZTByeXDatoEFQJy4QKA1UkwKjTtqntCJS7T7TjhiBvkpTbTVT1itDGb5LLe7lVN7iQUyj4ZMD6YaaVkJiYCWmDHARZJXN49tqr9Fj6bMUkueiw8yA2ScECRv6Lcizg==</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>