<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
  <!ENTITY VoucherExtendFields SYSTEM "..\Include\XML\VoucherExtendFields.xml">
]>

<dir id="m73PX1Select" table="" height="" fieldKey="id" voucherCode="PO1" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Chi tiết phiếu xuất được chọn" e="Issue Detail"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ma_kh" viewType="Lookup" disabled="true" label="1" field="1">
          <text v="Mã đối tượng" e="Customer"></text>
          <viewInfo lookupType="One" lookupId="dmkh" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_kh" />
        </field>
        <field name="ten_kh" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
        <field name="so_ct" label="1" field="2" disabled="true">
          <text v="Phiếu xuất" e="Issue"></text>
        </field>
        <field name="xprocess" label="1" field="2" valueDefault="2" viewType="Combobox">
          <text v="Xử lý" e="Process"></text>
          <viewInfo>
            <options>
              <option val="1">
                <text v="Thêm vào chi tiết" e="Append To Detail"></text>
              </option>
              <option val="2">
                <text v="Xóa hết chi tiết và thêm mới" e="Delete All Detail And Append New"></text>
              </option>
            </options>
          </viewInfo>
        </field>
      </fields>
    </form>
    <form tabPageIndex="1" gravity="MiddleLeft" height="350" columns="120,120,240" >
      <text v="Chi tiết" e="Detail"></text>
      <fields>
        <field name="d73" allowBlank="false" label="" field="-" viewType="Grid">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
  </forms>

  <grids>
    <grid id="d73" table="d73" fieldKey="id, line" order="id, line" allowFilter="true" allowOrder="true" readOnly="false">
      <fields>
        <field name="id" dataType="N" fieldType="PK" format="0" copy="false" hidden="true" aliasName="0 as ">
          <text v="" e=""></text>
        </field>
        <field name="line" dataType="I" fieldType="PK" hidden="true" aliasName="0 as ">
          <text v="Dòng" e="Line"></text>
        </field>
        <field name="ma_vt" width="100" allowBlank="false" viewType="Lookup" readOnly="true" >
          <text v="Mã sản phẩm" e="Item"></text>
          <viewInfo lookupType="One" lookupId="dmvt" lookupKey="status=1" lookupCheck="1=1" lookupRef="ten_vt" lookupInfo="dmvt|ma_vt|ten_vt" />
        </field>
        <field name="ten_vt" width="250" fieldType="EX" inactivate="true" readOnly="true" aliasName="b" join=" left join dmvt b on a.ma_vt = b.ma_vt ">
          <text v="Tên sản phẩm" e="Item Name"></text>
        </field>
        <field name="dvt" width="60" readOnly="true" viewType="Lookup" aliasName="a">
          <text v="Đvt" e="UOM"></text>
          <viewInfo lookupType="One" lookupId="dmdvt" lookupKey="dvt in (select dvt from dmqddvt where ma_vt = #[ma_vt]#)" lookupCheck="dvt in (select dvt from dmqddvt where ma_vt = #[ma_vt]#)" lookupRef="ten_dvt" lookupInfo="dmdvt|dvt|ten_dvt" />
        </field>
        <field name="ten_dvt" width="120" inactivate="true" readOnly="true" hidden="true" aliasName="c" join=" left join dmdvt c on a.dvt = c.dvt ">
          <text v="Tên đvt" e="UOM"></text>
        </field>
        <field name="so_luong0" dataType="N" format="Qty" width="100" readOnly="false" aliasName="0*a.so_luong as " >
          <text v="&lt;b&gt;Sl lấy&lt;/b&gt;" e="&lt;b&gt;Qty Input&lt;/b&gt;"></text>
        </field>
        <field name="so_luong" dataType="N" format="Qty" allowBlank="false" width="100" readOnly="true" >
          <text v="Số lượng" e="Quantity"></text>
        </field>
        <field name="sl_cl" dataType="N" format="Qty" width="100" aliasName="0*a.so_luong as " >
          <text v="&lt;b&gt;Sl còn lại&lt;/b&gt;" e="PO Qty"></text>
        </field>
        <field name="sl_ton" dataType="N" format="Qty" inactivate="true" allowBlank="false" width="100" readOnly="true" fieldType="EX" aliasName="0*a.so_luong as " >
          <text v="Tồn" e="Stock"></text>
        </field>
        <field name="ma_kho" width="100" clientDefault="true" allowBlank="false" viewType="Lookup" readOnly="true" >
          <text v="Mã kho" e="Site"></text>
          <viewInfo lookupType="One" lookupId="dmkho" lookupKey="unit_id = ![unit_id]! and status=1" lookupCheck="unit_id = ![unit_id]!" lookupRef="ten_kho" lookupInfo="dmkho|ma_kho|ten_kho" />
        </field>
        <field name="ten_kho" width="120" clientDefault="true" inactivate="true" hidden="true" aliasName="d" join=" left join dmkho d on a.ma_kho = d.ma_kho ">
          <text v="Tên kho" e="Site"></text>
        </field>
        <field name="ma_lo" width="100" readOnly="true" allowBlank="false" viewType="Lookup" readOnlyCondition="[lo_yn]==0" allowBlankCondition="[lo_yn]==0" >
          <text v="Mã lô" e="Lot"></text>
          <viewInfo lookupType="One" lookupId="dmlo" lookupKey="ma_vt = #[ma_vt]# and status=1" lookupCheck="1=1" lookupRef="ten_lo" lookupInfo="dmlo|ma_lo|ten_lo" />
        </field>
        <field name="ten_lo" width="120" inactivate="true" readOnly="true" hidden="true" aliasName="e" join=" left join dmlo e on a.ma_vt = e.ma_vt and a.ma_lo = e.ma_lo ">
          <text v="Tên lô" e="Lot"></text>
        </field>
        <field name="lo_yn" dataType="B" width="50" hidden="true" inactivate="true" readOnly="true" aliasName="b">
          <text v="Td lô" e="Lot"></text>
        </field>
        <field name="ma_vi_tri" width="100" readOnly="true" clientDefault="true" allowBlank="false" viewType="Lookup" readOnlyCondition="[vi_tri_yn]==0" allowBlankCondition="[vi_tri_yn]==0" >
          <text v="Mã vị trí" e="Location"></text>
          <viewInfo lookupType="One" lookupId="dmvitri" lookupKey="ma_kho = #[ma_kho]# and status=1" lookupCheck="1=1" lookupRef="ten_vi_tri" lookupInfo="dmvitri|ma_vi_tri|ten_vi_tri" />
        </field>
        <field name="ten_vi_tri" width="120" inactivate="true" clientDefault="true" readOnly="true" hidden="true" aliasName="f" join=" left join dmvitri f on a.ma_kho = f.ma_kho and a.ma_vi_tri = f.ma_vi_tri ">
          <text v="Tên vị trí" e="Location Name"></text>
        </field>
        <field name="vi_tri_yn" dataType="B" width="50" clientDefault="true" hidden="true" inactivate="true" readOnly="true" aliasName="d">
          <text v="Td vị trí" e="Location"></text>
        </field>
        <field name="he_so" dataType="N" format="Rate" width="50" readOnly="true" inactivate="true" aliasName="a" hidden="true" >
          <text v="Hệ số" e="Rate"></text>
        </field>
        <field name="sl_px" dataType="N" inactivate="true" format="Qty" width="100" copy="false" aliasName="0*so_luong as " >
          <text v="Sl PX t/tế" e="Py.Qty"></text>
        </field>
        <field name="id_px" dataType="N" fieldType="PK" format="0" hidden="true" aliasName="a.id as ">
          <text v="ID PX" e="ID PX"></text>
        </field>
        <field name="so_ct_px" dataType="N" fieldType="PK" format="0" hidden="true" aliasName="a.so_ct as ">
          <text v="Số PX t/tế" e="Issue Py.No"></text>
        </field>
        <field name="line_px" dataType="I" fieldType="PK" hidden="true" aliasName="a.line as ">
          <text v="Dòng px" e="Issue Line"></text>
        </field>
        &VoucherExtendFields;
      </fields>

      <buttons>
        <button id="freeze">
          <text v="$FreezeToolbar" e="$FreezeToolbar"></text>
        </button>
      </buttons>

      <script>
        <query>
          <text>
            <![CDATA[<enc>ffayE8bqNEEqjxEGjXjutojkxkBZQgl8CZbsQZmsyKQ6F4WqrPAeF3sypREYS8XVDAUsqanCz6SYrlXbvWf6VpUE0Kl+nm2ghcnMmEJ6xl91Y182pb2mDMLYKSOTJFe6sjMYHiqqoxym04n+3N6/EbM4cDnXRn25lAPZRG/7svGyx5fzOhITGbiqi4QYoiIBcg9mGxnmevuAJlmzQwPY2FtE8am/1IKrtw6Hv4fNriyvULEAHy5AxbZJZ6D6GCjV/YEAo0R6DRZb3c0yU6QsplWCxM38mAfCTPqjjlmhagK/oyhJJTpL6sYvk+IGruNciTQD1NIL0s9QgONAZEh/9uvP3TMtI6lS0jsKYspU9IHLV6O+mAsKZcR5P/Yvd5P6OY30S96UpAiJZleJv6jg6KMdELP1+xnCVhFmehMkLiWGJ9x9cdTp8aKszDBN3riTATvb2bTm2tdevAMWDBD+l4Cm0HUjndQh3Ag4o8/taOE41HFpJN5BAa3NM2RUNxDz</enc>]]>
          </text>
        </query>
      </script>

    </grid>
  </grids>

  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>Jz4b7GJDin0w09YHvpA1tjMPlHBGTsCYtJnY0yocTmb/kDWjuqgZ48+4EJcIjxo9AHWElP4UaJMhmPpCjD/+r+zufwJ6Y86qJalzogaB214radV2iR0MZDaZNIc5E15ZJNTKj9WGp8b95WbRP+X7CRPAGfrJr9nJ6ebXkZ8kV0S7B8v1ZjohC2mcUXw0euR2V2giDH+qLiC9YiEr62g4+fc/4f+JTV8HR4SxVdGsRtuCqTssB+rsXibN2U49fAHL/fy6PgEPBL1WXyMUcbFNt1BFIfzyEmgPXj9yhfNu031X/dZNqjdeYv7SYTrRAB5Q+kF27N/wBZvFn8K8DCC6JvVh2ON80W8Of3aEODlGkPBZgsTIFqupnno8dJQGQ7qINufBdYQc0GdGaQAwwTfR5/+HJVQZTDUEsBPmE6sigF1muI1nwnnpntSKYXdyq/JDGo35322Z2bADtH5/PL7OaITEb6iQcCsTQzPHT2CMqgoK0wY+A0G9w5rVVrztOfplJHzFXvcZsxf5ggmJaQJwJk/zbYA4ZqxHcjOe2A1p+kNNnWt7PidRzPwRblnxCRkzSBVsNZudxlfJFwLQTH/Zw5Pakn7EEwk28K1V7ySlJq0ZQRCLzfK0VH8fiVTuyqk4DD+ec1PFIFdt1zkBicMc3PLVB8MMw+LEJra8LUosO7Y=</enc>]]>
    </text>
  </js>
</dir>