<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="m73YC1" table="" height="" fieldKey="id" voucherCode="YC1" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc phiếu yêu cầu xuất kho" e=""></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" allowBlank="false" dataType="D">
          <text v="Ngày c/từ từ/đến" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" allowBlank="false" inactivate="true" dataType="D" nextRow="false">
          <text v="Ngày đến" e="Voucher Date"></text>
        </field>
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="so_ct" label="1" field="1" allowBlank="false" viewType="Lookup">
          <text v="Số phiếu yêu cầu" e="Voucher Number"></text>
          <viewInfo lookupType="Multi" lookupId="m71" lookupRef="ds_so_ct" lookupKey="unit_id = ![unit_id]! and status in (5,6)" lookupCheck="status in (5,6)" />
        </field>
        <field name="ds_so_ct" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
      </fields>
    </form>
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>RDjxmTehkD14wzAw6RB8cNgUV8Nv6zpCRm/OOHOjdRMFBqV9SCADDRV1gx1hv1pJ6f+Ndl9Fk94NvGo5Mcc9IeTCsiOlxRNykIxvhZQmitCvmg7MUyMZM8OmtyjMGPF9oM+UYw0PIPxvhytzqDE4jKSm05GF8rRzRYR47H4qdD8Q9pSYCWSXCVLw4b5fEBSo1XjetVDAmd5SQACLxlS/ZKwpwoRKMpmgSgG7Tb746u+0shyaa3Vu2jXYEK+y7rErrbaxhv/qI4LtXPqgwOfK5IYKVnvbAmuO30fztGa1O73XX0GRt9Rhrt+7Sgv+HV+odhu0zDpjOXkqqLGdEiTD58B7eOFEInNNidq6wg5z5e/xUge2AOYyHm/9BBPgjDK9uoYLKPVYgwDeHNguqrUlvYwiBARIOGkyPZxleTWDoSFMwshxO4YL67ZHtrCw818G15mqmJHpA3L+gVR0aSoUUTv/DqHS6NoFJul5gTNNv5U=</enc>]]>
    </text>
  </js>

  <script>

  </script>
</dir>