<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dir [
  <!ENTITY DefaultButton SYSTEM "..\Include\XML\DefaultButtonFilter.xml">
]>

<dir id="m85PX3" table="" height="" fieldKey="id" voucherCode="PX3" dirViewType="Dialog" xmlns="urn:schemas-iswift:struct-dir">
  <title v="Lọc phiếu xuất" e="Issue Filter"></title>

  <forms>
    <form gravity="TopLeft" columns="120,120,120"  >
      <fields>
        <field name="ngay_ct1" label="1" field="1" aliasName="@DFDFrom" allowBlank="false" dataType="D">
          <text v="Ngày c/từ từ/đến" e="Voucher Date"></text>
        </field>
        <field name="ngay_ct2" label="" field="1" allowBlank="false" inactivate="true" dataType="D" nextRow="false">
          <text v="Ngày đến" e="Voucher Date"></text>
        </field>
        <field name="unit_id" dataType="I" hidden="true" label="1" field="1">
          <text v="Đơn vị" e="Unit"></text>
        </field>
        <field name="ma_kh" viewType="Lookup" disabled="true" inactivate="true" label="1" field="1">
          <text v="Mã khách hàng" e="Customer"></text>
          <viewInfo lookupType="One" lookupId="dmkh" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_kh" />
        </field>
        <field name="ten_kh" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
		
        <field name="so_ct" label="1" field="1" allowBlank="false" viewType="Lookup">
          <text v="Số phiếu xuất" e="Voucher Number"></text>
          <viewInfo lookupType="Multi" lookupId="m54" lookupRef="ds_so_ct" lookupKey="ngay_ct between ![ngay_ct1]! and ![ngay_ct2]! and ma_kh = ![ma_kh]! and unit_id = ![unit_id]! and status in (5,6)" />
        </field>
        <field name="ds_so_ct" nextRow="false" fieldType="EX" readOnly="true" inactivate="true" label="" field="-" aliasName="cast('' as nvarchar(4000)) as ">
          <text v="" e=""></text>
        </field>
		
		<field name="ma_dvvt" disabled="true" inactivate="true" label="1" field="1" >
          <text v="Mã đơn vị vận chuyển" e="Trans"></text>
		  <viewInfo lookupType="One" lookupId="dmdvvt" lookupKey="status = 1" lookupCheck="1 = 1" lookupRef="ten_dvvt" />
        </field>
		<field name="ten_dvvt" nextRow="false" readOnly="true" fieldType="EX" disabled="true" label="" field="-">
          <text v="" e=""></text>
        </field>
		
		<field name="ngay_ct" label="1" field="1" disabled="true" allowBlank="false" inactivate="true" dataType="D" >
          <text v="Ngày hiệu lực " e="Effective Date"></text>
        </field>
      </fields>
    </form>
  </forms>


  &DefaultButton;

  <js>
    <text>
      <![CDATA[<enc>oeUl9yxqjf9tDdqcT9DKQ4vtfu2x3soPu75JaXHj5+UkaDGvaB7W/IoDdL4LIqgMmI0NoP0wSngVfKye2fErkKIV2BeqohnWztWpqJKMRLhVztkSEU4Rq0ooX2oLDagO+UPOTEDqr+xO9EkXF9tFvWesI3Z6jOWYj8NwE5dz/qIRL/FeeHeOpJfEjcGE65ykDvJ+7t5MhEOX5PtTg7yZ+x62Lp6QeX9tkXl4a7erdvp2cl1mUX4JmBovuy7LNnxulsBv1ejnik4i4W/t+1jCCiNn08XvX+LFfEe0oaSeS6qUPTN2Y5TBCTgSgr8PpEJByiE6NyOpl0rVC7j6g4rZv2AtzOuqww2T1+Nu6tkZGFBjWlVPTbGFsXIK1qZy+Kv+pG7zndajtH7U/rQrmr9ecrr0yjbi8zhKNnY4DpLx0NJ6FLNcsiSRfMXkfIoMBRC8O+WgIXCfS9dWnkvcqEl+2QMQhT7O8lfmiA3374dnG7kP7JHeSPmw6htKEWVAeUCMpevewGvVTzpY+Gf+ZHnTsg==</enc>]]>
    </text>
  </js>
</dir>